/* ============================================================
   GEOPOLITICA 2026 — Dati di gioco
   Valori approssimati allo stato del mondo nell'autunno 2026.
   PIL in miliardi USD, popolazione in milioni, tecnologie 0-10.
   ============================================================ */
(function (root) {
  const GEO = root.GEO = root.GEO || {};

  GEO.VERSION = '1.0.0';

  // ---- Blocchi ----------------------------------------------------------
  GEO.BLOCS = {
    NATO:   { name: 'NATO',      color: '#60a5fa', defense: true },
    EU:     { name: 'Unione Europea', color: '#2563eb', defense: false, trade: true },
    G7:     { name: 'G7',        color: '#93c5fd', defense: false },
    BRICS:  { name: 'BRICS+',    color: '#f59e0b', defense: false, trade: true },
    SCO:    { name: 'SCO',       color: '#d97706', defense: false },
    CSTO:   { name: 'CSTO',      color: '#b45309', defense: true },
    AUKUS:  { name: 'AUKUS',     color: '#0ea5e9', defense: true },
    QUAD:   { name: 'QUAD',      color: '#38bdf8', defense: false },
    OPEC:   { name: 'OPEC+',     color: '#84cc16', defense: false },
    USMCA:  { name: 'USMCA',     color: '#a78bfa', defense: false, trade: true },
    MERCOSUR:{ name: 'Mercosur', color: '#c084fc', defense: false, trade: true },
    AU:     { name: 'Unione Africana', color: '#22c55e', defense: false },
    ASEAN:  { name: 'ASEAN',     color: '#14b8a6', defense: false, trade: true },
    FIVEEYES:{ name: 'Five Eyes',color: '#7dd3fc', defense: false },
  };

  // ---- Personalità IA ---------------------------------------------------
  // aggression: propensione a guerre/ultimatum; loyalty: rispetto dei patti;
  // greed: priorità economica; risk: tolleranza al rischio (incl. nucleare)
  GEO.PERSONAS = {
    egemone:       { label: 'Egemone',       aggression: 0.45, loyalty: 0.7, greed: 0.6, risk: 0.4, desc: 'Difende alleati e ordine esistente, punisce gli aggressori.' },
    falco:         { label: 'Falco',         aggression: 0.85, loyalty: 0.35, greed: 0.4, risk: 0.75, desc: 'Cerca lo scontro quando è in vantaggio, revisionista.' },
    paziente:      { label: 'Paziente',      aggression: 0.55, loyalty: 0.5, greed: 0.8, risk: 0.35, desc: 'Accumula potere, colpisce solo con grande superiorità.' },
    mercante:      { label: 'Mercante',      aggression: 0.15, loyalty: 0.7, greed: 0.9, risk: 0.2, desc: 'Vuole commercio e stabilità, evita i conflitti.' },
    opportunista:  { label: 'Opportunista',  aggression: 0.5,  loyalty: 0.3, greed: 0.7, risk: 0.55, desc: 'Cambia alleanze a seconda della convenienza.' },
    isolazionista: { label: 'Isolazionista', aggression: 0.1,  loyalty: 0.6, greed: 0.5, risk: 0.2, desc: 'Si tiene fuori dai conflitti altrui.' },
    difensivo:     { label: 'Difensivo',     aggression: 0.25, loyalty: 0.8, greed: 0.5, risk: 0.45, desc: 'Cerca garanzie di sicurezza, combatte solo se minacciato.' },
    ambizioso:     { label: 'Ambizioso',     aggression: 0.5,  loyalty: 0.5, greed: 0.75, risk: 0.45, desc: 'Vuole salire di rango, oscilla tra i blocchi.' },
    imprevedibile: { label: 'Imprevedibile', aggression: 0.7,  loyalty: 0.2, greed: 0.3, risk: 0.95, desc: 'Regime chiuso, ricatto nucleare, mosse irrazionali.' },
  };

  // ---- Tecnologie -------------------------------------------------------
  GEO.TECHS = {
    ai:      { name: 'Intelligenza Artificiale', icon: '🧠', desc: '+crescita PIL, +cyber, +efficienza militare. Richiede semiconduttori (max AI = chip+3 senza accesso ai chip).' },
    semis:   { name: 'Semiconduttori', icon: '🔬', desc: 'Base per IA e quantistica. Chi produce chip può imporre embarghi tecnologici.' },
    energy:  { name: 'Energia & Nucleare civile', icon: '⚡', desc: 'Riduce la dipendenza da petrolio/gas e i danni da shock energetici.' },
    space:   { name: 'Spazio & Satelliti', icon: '🛰️', desc: 'Intelligence: vedi gli ordini nemici, migliori l’intercettazione e il targeting.' },
    cyber:   { name: 'Cyberwarfare', icon: '💻', desc: 'Attacchi cyber contro economia e infrastrutture, difesa dalle intrusioni.' },
    hyper:   { name: 'Missili ipersonici', icon: '🚀', desc: 'I tuoi missili aggirano le difese: -8% intercettazione per livello.' },
    bio:     { name: 'Biotecnologie', icon: '🧬', desc: 'Resilienza alle pandemie, +stabilità, +crescita sanitaria.' },
    quantum: { name: 'Quantistica', icon: '⚛️', desc: 'Difesa cyber quasi impenetrabile, +ricerca in tutte le aree.' },
    defense: { name: 'Difesa aerea & antimissile', icon: '🛡️', desc: 'Scudo contro missili balistici: +8% intercettazione per livello.' },
  };

  // ---- Settori di borsa & materie prime -----------------------------------
  GEO.SECTORS = {
    TECH:   { name: 'Tecnologia globale', icon: '💾', base: 100 },
    ENERGY: { name: 'Energia', icon: '🛢️', base: 100 },
    DEF:    { name: 'Difesa & Aerospazio', icon: '✈️', base: 100 },
    AGRI:   { name: 'Agroalimentare', icon: '🌾', base: 100 },
    FIN:    { name: 'Finanza', icon: '🏦', base: 100 },
    GOLD:   { name: 'Oro (bene rifugio)', icon: '🥇', base: 100 },
  };
  GEO.COMMODITIES = {
    oil:   { name: 'Petrolio', unit: '$/bbl', base: 78, icon: '🛢️' },
    gas:   { name: 'Gas naturale', unit: '$/MWh', base: 38, icon: '🔥' },
    grain: { name: 'Grano', unit: '$/t', base: 240, icon: '🌾' },
    chips: { name: 'Chip avanzati', unit: 'indice', base: 100, icon: '🔲' },
    rare:  { name: 'Terre rare', unit: 'indice', base: 100, icon: '⛏️' },
  };

  // ---- Nazioni ------------------------------------------------------------
  // res: capacità produttiva 0-10 per materia prima (0 = importatore netto)
  // regions: [nome, quota PIL, capitale?]
  GEO.NATIONS = [
    { id:'USA', name:'Stati Uniti', flag:'🇺🇸', continent:'Nord America', lat:38.9, lon:-77.0, regime:'democrazia', persona:'egemone',
      gdp:29400, growth:2.1, pop:341, stability:58, debt:123, treasury:400,
      army:85, navy:100, air:100, missiles:500, nukes:3700,
      tech:{ai:10,semis:8,energy:8,space:10,cyber:10,hyper:6,bio:10,quantum:9,defense:9},
      res:{oil:10,gas:10,grain:9,chips:6,rare:2}, blocs:['NATO','G7','AUKUS','FIVEEYES','QUAD','USMCA'],
      neighbors:['CAN','MEX'], seaNeighbors:['CUB'], color:'#3b82f6',
      regions:[['Washington & Costa Est',0.30,true],['Midwest',0.18],['Sud & Texas',0.22],['California & Costa Ovest',0.25],['Alaska & Hawaii',0.05]] },
    { id:'CHN', name:'Cina', flag:'🇨🇳', continent:'Asia', lat:39.9, lon:116.4, regime:'autocrazia', persona:'paziente',
      gdp:19600, growth:4.4, pop:1409, stability:72, debt:90, treasury:900,
      army:95, navy:85, air:80, missiles:1500, nukes:600,
      tech:{ai:9,semis:6,energy:9,space:9,cyber:9,hyper:9,bio:7,quantum:8,defense:8},
      res:{oil:3,gas:2,grain:7,chips:4,rare:10}, blocs:['BRICS','SCO'],
      neighbors:['RUS','IND','PAK','VNM','PRK','KAZ'], seaNeighbors:['PHL','JPN','KOR'], color:'#ef4444', claims:{TWN:'all',PHL:'Mar Cinese Meridionale'},
      regions:[['Pechino & Nord',0.25,true],['Shanghai & Est',0.28],['Guangdong & Sud',0.24],['Sichuan & Centro',0.15],['Xinjiang & Tibet',0.08]] },
    { id:'RUS', name:'Russia', flag:'🇷🇺', continent:'Europa/Asia', lat:55.75, lon:37.6, regime:'autocrazia', persona:'falco',
      gdp:2150, growth:1.0, pop:144, stability:52, debt:20, treasury:120,
      army:75, navy:45, air:55, missiles:900, nukes:5500,
      tech:{ai:4,semis:2,energy:7,space:7,cyber:8,hyper:9,bio:4,quantum:3,defense:7},
      res:{oil:10,gas:10,grain:9,chips:0,rare:3}, blocs:['BRICS','SCO','CSTO','OPEC'],
      neighbors:['UKR','POL','CHN','KAZ','PRK','FIN','BLR','NOR'], seaNeighbors:['JPN'], color:'#b91c1c', claims:{UKR:['Donbass','Crimea']},
      regions:[['Mosca',0.30,true],['San Pietroburgo & Nord-Ovest',0.14],['Volga & Urali',0.18],['Siberia',0.20],['Estremo Oriente',0.10],['Caucaso & Sud',0.08]] },
    { id:'IND', name:'India', flag:'🇮🇳', continent:'Asia', lat:28.6, lon:77.2, regime:'democrazia', persona:'ambizioso',
      gdp:4300, growth:6.4, pop:1445, stability:63, debt:82, treasury:150,
      army:80, navy:40, air:50, missiles:300, nukes:172,
      tech:{ai:6,semis:3,energy:5,space:7,cyber:6,hyper:4,bio:6,quantum:4,defense:5},
      res:{oil:1,gas:1,grain:8,chips:1,rare:2}, blocs:['BRICS','QUAD','SCO'],
      neighbors:['PAK','CHN','BGD'], color:'#f97316',
      regions:[['Delhi & Nord',0.30,true],['Mumbai & Ovest',0.30],['Bengaluru & Sud',0.25],['Calcutta & Est',0.15]] },
    { id:'JPN', name:'Giappone', flag:'🇯🇵', continent:'Asia', lat:35.7, lon:139.7, regime:'democrazia', persona:'mercante',
      gdp:4100, growth:0.9, pop:123, stability:80, debt:250, treasury:300,
      army:30, navy:55, air:45, missiles:150, nukes:0,
      tech:{ai:7,semis:8,energy:5,space:7,cyber:7,hyper:4,bio:8,quantum:7,defense:8},
      res:{oil:0,gas:0,grain:2,chips:7,rare:1}, blocs:['G7','QUAD'],
      neighbors:[], color:'#f43f5e', allies:['USA'],
      regions:[['Tokyo & Kanto',0.45,true],['Osaka & Kansai',0.30],['Kyushu & Okinawa',0.15],['Hokkaido & Nord',0.10]] },
    { id:'DEU', name:'Germania', flag:'🇩🇪', continent:'Europa', lat:52.5, lon:13.4, regime:'democrazia', persona:'mercante',
      gdp:4700, growth:0.8, pop:84, stability:66, debt:64, treasury:200,
      army:30, navy:20, air:30, missiles:40, nukes:0,
      tech:{ai:6,semis:6,energy:7,space:5,cyber:6,hyper:2,bio:8,quantum:7,defense:6},
      res:{oil:0,gas:0,grain:5,chips:3,rare:0}, blocs:['NATO','EU','G7'],
      neighbors:['FRA','POL','NLD','CHE'], color:'#fbbf24',
      regions:[['Berlino & Est',0.25,true],['Baviera & Sud',0.30],['Renania & Ovest',0.30],['Amburgo & Nord',0.15]] },
    { id:'FRA', name:'Francia', flag:'🇫🇷', continent:'Europa', lat:48.85, lon:2.35, regime:'democrazia', persona:'egemone',
      gdp:3250, growth:1.0, pop:68, stability:55, debt:112, treasury:150,
      army:35, navy:40, air:40, missiles:100, nukes:290,
      tech:{ai:6,semis:4,energy:9,space:7,cyber:7,hyper:4,bio:7,quantum:6,defense:6},
      res:{oil:0,gas:0,grain:7,chips:1,rare:0}, blocs:['NATO','EU','G7'],
      neighbors:['DEU','ESP','ITA','GBR','CHE'], color:'#6366f1',
      regions:[['Parigi & Île-de-France',0.35,true],['Lione & Sud-Est',0.25],['Nord & Est',0.20],['Ovest & Atlantico',0.20]] },
    { id:'GBR', name:'Regno Unito', flag:'🇬🇧', continent:'Europa', lat:51.5, lon:-0.1, regime:'democrazia', persona:'egemone',
      gdp:3600, growth:1.2, pop:69, stability:58, debt:100, treasury:150,
      army:30, navy:45, air:40, missiles:80, nukes:225,
      tech:{ai:7,semis:4,energy:6,space:5,cyber:8,hyper:3,bio:8,quantum:7,defense:6},
      res:{oil:3,gas:3,grain:4,chips:1,rare:0}, blocs:['NATO','G7','AUKUS','FIVEEYES'],
      neighbors:['FRA'], color:'#8b5cf6',
      regions:[['Londra & Sud-Est',0.45,true],['Midlands & Nord',0.30],['Scozia',0.15],['Galles & Irlanda del Nord',0.10]] },
    { id:'ITA', name:'Italia', flag:'🇮🇹', continent:'Europa', lat:41.9, lon:12.5, regime:'democrazia', persona:'mercante',
      gdp:2350, growth:0.7, pop:59, stability:60, debt:137, treasury:90,
      army:28, navy:35, air:30, missiles:30, nukes:0,
      tech:{ai:4,semis:3,energy:5,space:6,cyber:5,hyper:2,bio:6,quantum:5,defense:5},
      res:{oil:0,gas:1,grain:5,chips:1,rare:0}, blocs:['NATO','EU','G7'],
      neighbors:['FRA','CHE'], color:'#22c55e',
      regions:[['Roma & Centro',0.25,true],['Milano & Nord-Ovest',0.33],['Veneto & Nord-Est',0.22],['Sud & Isole',0.20]] },
    { id:'ESP', name:'Spagna', flag:'🇪🇸', continent:'Europa', lat:40.4, lon:-3.7, regime:'democrazia', persona:'mercante',
      gdp:1750, growth:2.2, pop:48, stability:62, debt:104, treasury:60,
      army:22, navy:25, air:22, missiles:20, nukes:0,
      tech:{ai:4,semis:2,energy:7,space:4,cyber:5,hyper:1,bio:6,quantum:4,defense:4},
      res:{oil:0,gas:0,grain:5,chips:0,rare:0}, blocs:['NATO','EU'],
      neighbors:['FRA'], seaNeighbors:['MAR','DZA'], color:'#eab308',
      regions:[['Madrid & Centro',0.35,true],['Catalogna & Est',0.30],['Andalusia & Sud',0.20],['Nord',0.15]] },
    { id:'POL', name:'Polonia', flag:'🇵🇱', continent:'Europa', lat:52.2, lon:21.0, regime:'democrazia', persona:'difensivo',
      gdp:950, growth:3.2, pop:37, stability:63, debt:55, treasury:40,
      army:45, navy:8, air:25, missiles:60, nukes:0,
      tech:{ai:3,semis:1,energy:4,space:2,cyber:5,hyper:1,bio:4,quantum:2,defense:6},
      res:{oil:0,gas:1,grain:6,chips:0,rare:0}, blocs:['NATO','EU'],
      neighbors:['DEU','RUS','UKR','BLR'], color:'#e11d48',
      regions:[['Varsavia & Centro',0.40,true],['Slesia & Sud',0.30],['Baltico & Nord',0.15],['Est',0.15]] },
    { id:'UKR', name:'Ucraina', flag:'🇺🇦', continent:'Europa', lat:50.45, lon:30.5, regime:'democrazia', persona:'difensivo',
      gdp:200, growth:2.5, pop:36, stability:45, debt:95, treasury:15,
      army:55, navy:5, air:15, missiles:120, nukes:0,
      tech:{ai:3,semis:0,energy:4,space:2,cyber:6,hyper:1,bio:3,quantum:1,defense:6},
      res:{oil:0,gas:2,grain:9,chips:0,rare:2}, blocs:[],
      neighbors:['RUS','POL','BLR','ROU','HUN'], color:'#0ea5e9',
      regions:[['Kiev',0.35,true],['Leopoli & Ovest',0.20],['Kharkiv & Nord-Est',0.15],['Odessa & Sud',0.12],['Donbass',0.12,false,'RUS'],['Crimea',0.06,false,'RUS']] },
    { id:'FIN', name:'Finlandia', flag:'🇫🇮', continent:'Europa', lat:60.2, lon:24.9, regime:'democrazia', persona:'difensivo',
      gdp:310, growth:1.2, pop:5.6, stability:85, debt:78, treasury:20,
      army:20, navy:6, air:15, missiles:20, nukes:0,
      tech:{ai:5,semis:2,energy:7,space:3,cyber:7,hyper:1,bio:6,quantum:5,defense:5},
      res:{oil:0,gas:0,grain:3,chips:0,rare:1}, blocs:['NATO','EU'],
      neighbors:['RUS','SWE','NOR'], color:'#cbd5e1',
      regions:[['Helsinki & Sud',0.65,true],['Lapponia & Nord',0.35]] },
    { id:'TUR', name:'Turchia', flag:'🇹🇷', continent:'Europa/Asia', lat:39.9, lon:32.9, regime:'ibrido', persona:'opportunista',
      gdp:1350, growth:3.0, pop:86, stability:50, debt:35, treasury:40,
      army:55, navy:25, air:35, missiles:150, nukes:0,
      tech:{ai:4,semis:1,energy:4,space:3,cyber:5,hyper:2,bio:3,quantum:1,defense:5},
      res:{oil:0,gas:0,grain:6,chips:0,rare:1}, blocs:['NATO'],
      neighbors:['IRN','ISR','IRQ','GRC'], color:'#dc2626',
      regions:[['Ankara & Anatolia',0.35,true],['Istanbul & Marmara',0.40],['Sud-Est',0.25]] },
    { id:'SAU', name:'Arabia Saudita', flag:'🇸🇦', continent:'Medio Oriente', lat:24.7, lon:46.7, regime:'autocrazia', persona:'opportunista',
      gdp:1150, growth:3.5, pop:37, stability:70, debt:28, treasury:600,
      army:30, navy:15, air:40, missiles:120, nukes:0,
      tech:{ai:5,semis:0,energy:6,space:2,cyber:4,hyper:1,bio:3,quantum:1,defense:7},
      res:{oil:10,gas:6,grain:1,chips:0,rare:0}, blocs:['OPEC','BRICS'],
      neighbors:['ARE','IRN','EGY','IRQ','QAT'], color:'#16a34a',
      regions:[['Riad & Najd',0.45,true],['Provincia Orientale (petrolio)',0.35],['Hejaz & Mar Rosso',0.20]] },
    { id:'ARE', name:'Emirati Arabi', flag:'🇦🇪', continent:'Medio Oriente', lat:24.5, lon:54.4, regime:'autocrazia', persona:'mercante',
      gdp:560, growth:4.0, pop:10, stability:85, debt:30, treasury:450,
      army:12, navy:10, air:25, missiles:40, nukes:0,
      tech:{ai:6,semis:0,energy:6,space:3,cyber:5,hyper:1,bio:3,quantum:2,defense:6},
      res:{oil:8,gas:5,grain:0,chips:0,rare:0}, blocs:['OPEC','BRICS'],
      neighbors:['SAU'], color:'#4ade80',
      regions:[['Abu Dhabi',0.55,true],['Dubai',0.45]] },
    { id:'IRN', name:'Iran', flag:'🇮🇷', continent:'Medio Oriente', lat:35.7, lon:51.4, regime:'autocrazia', persona:'falco',
      gdp:420, growth:1.5, pop:90, stability:38, debt:35, treasury:25,
      army:50, navy:15, air:20, missiles:800, nukes:0, nuclearProgram:0.6,
      tech:{ai:3,semis:0,energy:4,space:3,cyber:6,hyper:3,bio:3,quantum:1,defense:4},
      res:{oil:8,gas:9,grain:3,chips:0,rare:0}, blocs:['SCO','BRICS','OPEC'],
      neighbors:['TUR','PAK','SAU','ARE','IRQ'], color:'#15803d',
      regions:[['Teheran & Nord',0.45,true],['Khuzestan & Golfo (petrolio)',0.30],['Est & Sud',0.25]] },
    { id:'ISR', name:'Israele', flag:'🇮🇱', continent:'Medio Oriente', lat:31.8, lon:35.2, regime:'democrazia', persona:'difensivo',
      gdp:560, growth:2.5, pop:10, stability:50, debt:68, treasury:40,
      army:35, navy:10, air:45, missiles:200, nukes:90,
      tech:{ai:8,semis:5,energy:5,space:5,cyber:10,hyper:3,bio:7,quantum:5,defense:10},
      res:{oil:0,gas:3,grain:1,chips:2,rare:0}, blocs:[],
      neighbors:['EGY','TUR'], color:'#38bdf8', allies:['USA'],
      regions:[['Tel Aviv & Centro',0.60,true],['Gerusalemme & Sud',0.25],['Nord & Haifa',0.15]] },
    { id:'EGY', name:'Egitto', flag:'🇪🇬', continent:'Africa', lat:30.0, lon:31.2, regime:'autocrazia', persona:'opportunista',
      gdp:410, growth:3.8, pop:112, stability:48, debt:92, treasury:15,
      army:45, navy:20, air:30, missiles:60, nukes:0,
      tech:{ai:2,semis:0,energy:4,space:2,cyber:3,hyper:1,bio:2,quantum:0,defense:4},
      res:{oil:2,gas:4,grain:3,chips:0,rare:0}, blocs:['BRICS','AU'],
      neighbors:['ISR','SAU','NGA','ETH'], color:'#ca8a04',
      regions:[['Cairo & Delta',0.55,true],['Alessandria & Canale di Suez',0.30],['Alto Egitto',0.15]] },
    { id:'NGA', name:'Nigeria', flag:'🇳🇬', continent:'Africa', lat:9.1, lon:7.5, regime:'democrazia', persona:'isolazionista',
      gdp:260, growth:3.4, pop:230, stability:40, debt:45, treasury:10,
      army:22, navy:8, air:10, missiles:5, nukes:0,
      tech:{ai:2,semis:0,energy:2,space:1,cyber:3,hyper:0,bio:2,quantum:0,defense:1},
      res:{oil:7,gas:5,grain:4,chips:0,rare:1}, blocs:['OPEC','AU'],
      neighbors:['EGY','ZAF','COD','DZA'], color:'#059669',
      regions:[['Abuja & Centro',0.30,true],['Lagos & Sud-Ovest',0.40],['Delta del Niger (petrolio)',0.20],['Nord',0.10]] },
    { id:'ZAF', name:'Sudafrica', flag:'🇿🇦', continent:'Africa', lat:-25.7, lon:28.2, regime:'democrazia', persona:'isolazionista',
      gdp:410, growth:1.2, pop:63, stability:48, debt:75, treasury:15,
      army:12, navy:8, air:10, missiles:5, nukes:0,
      tech:{ai:3,semis:0,energy:3,space:2,cyber:4,hyper:0,bio:4,quantum:1,defense:2},
      res:{oil:0,gas:0,grain:4,chips:0,rare:5}, blocs:['BRICS','AU'],
      neighbors:['NGA','COD'], color:'#10b981',
      regions:[['Pretoria & Gauteng',0.45,true],['Città del Capo & Ovest',0.30],['Durban & Est',0.25]] },
    { id:'BRA', name:'Brasile', flag:'🇧🇷', continent:'Sud America', lat:-15.8, lon:-47.9, regime:'democrazia', persona:'mercante',
      gdp:2350, growth:2.2, pop:217, stability:52, debt:88, treasury:60,
      army:30, navy:20, air:20, missiles:10, nukes:0,
      tech:{ai:4,semis:1,energy:7,space:3,cyber:4,hyper:0,bio:5,quantum:2,defense:2},
      res:{oil:7,gas:3,grain:10,chips:0,rare:3}, blocs:['BRICS','MERCOSUR'],
      neighbors:['ARG','COL','PER','VEN'], color:'#4ade80',
      regions:[['Brasilia & Centro',0.20,true],['San Paolo & Sud-Est',0.45],['Sud',0.17],['Nord-Est & Amazzonia',0.18]] },
    { id:'ARG', name:'Argentina', flag:'🇦🇷', continent:'Sud America', lat:-34.6, lon:-58.4, regime:'democrazia', persona:'isolazionista',
      gdp:680, growth:3.0, pop:46, stability:45, debt:80, treasury:10,
      army:12, navy:8, air:8, missiles:5, nukes:0,
      tech:{ai:3,semis:0,energy:5,space:2,cyber:3,hyper:0,bio:4,quantum:1,defense:1},
      res:{oil:4,gas:5,grain:9,chips:0,rare:3}, blocs:['MERCOSUR'],
      neighbors:['BRA','CHL'], color:'#7dd3fc', claims:{GBR:'Falkland'},
      regions:[['Buenos Aires',0.55,true],['Pampa & Centro',0.25],['Patagonia & Vaca Muerta',0.20]] },
    { id:'MEX', name:'Messico', flag:'🇲🇽', continent:'Nord America', lat:19.4, lon:-99.1, regime:'democrazia', persona:'mercante',
      gdp:1950, growth:1.5, pop:131, stability:45, debt:55, treasury:40,
      army:20, navy:10, air:8, missiles:5, nukes:0,
      tech:{ai:3,semis:1,energy:4,space:1,cyber:3,hyper:0,bio:4,quantum:1,defense:2},
      res:{oil:5,gas:2,grain:5,chips:0,rare:1}, blocs:['USMCA'],
      neighbors:['USA'], seaNeighbors:['CUB'], color:'#86efac',
      regions:[['Città del Messico & Centro',0.40,true],['Nord & Monterrey',0.35],['Sud & Yucatán',0.25]] },
    { id:'CAN', name:'Canada', flag:'🇨🇦', continent:'Nord America', lat:45.4, lon:-75.7, regime:'democrazia', persona:'mercante',
      gdp:2300, growth:1.4, pop:41, stability:72, debt:105, treasury:80,
      army:15, navy:15, air:20, missiles:10, nukes:0,
      tech:{ai:7,semis:2,energy:7,space:4,cyber:6,hyper:1,bio:6,quantum:7,defense:4},
      res:{oil:9,gas:7,grain:8,chips:0,rare:4}, blocs:['NATO','G7','FIVEEYES','USMCA'],
      neighbors:['USA'], color:'#fb7185',
      regions:[['Ottawa & Ontario',0.40,true],['Québec',0.20],['Prairie & Alberta (petrolio)',0.25],['Columbia Britannica',0.15]] },
    { id:'AUS', name:'Australia', flag:'🇦🇺', continent:'Oceania', lat:-35.3, lon:149.1, regime:'democrazia', persona:'mercante',
      gdp:1850, growth:1.8, pop:27, stability:75, debt:50, treasury:80,
      army:15, navy:30, air:25, missiles:30, nukes:0,
      tech:{ai:6,semis:1,energy:5,space:4,cyber:7,hyper:2,bio:6,quantum:6,defense:5},
      res:{oil:2,gas:8,grain:7,chips:0,rare:7}, blocs:['AUKUS','QUAD','FIVEEYES'],
      neighbors:[], seaNeighbors:['IDN','NZL'], color:'#fde047',
      regions:[['Canberra & Sydney',0.45,true],['Melbourne & Victoria',0.25],['Perth & Ovest (miniere)',0.20],['Queensland & Nord',0.10]] },
    { id:'IDN', name:'Indonesia', flag:'🇮🇩', continent:'Asia', lat:-6.2, lon:106.8, regime:'democrazia', persona:'mercante',
      gdp:1500, growth:5.0, pop:281, stability:60, debt:40, treasury:40,
      army:30, navy:20, air:15, missiles:20, nukes:0,
      tech:{ai:3,semis:0,energy:4,space:1,cyber:3,hyper:0,bio:3,quantum:1,defense:2},
      res:{oil:3,gas:5,grain:5,chips:0,rare:6}, blocs:['BRICS','ASEAN'],
      neighbors:[], seaNeighbors:['AUS','VNM','MYS','PHL'], color:'#f87171',
      regions:[['Giacarta & Giava',0.60,true],['Sumatra',0.20],['Borneo & Est',0.20]] },
    { id:'VNM', name:'Vietnam', flag:'🇻🇳', continent:'Asia', lat:21.0, lon:105.8, regime:'autocrazia', persona:'difensivo',
      gdp:490, growth:6.0, pop:100, stability:70, debt:36, treasury:15,
      army:35, navy:10, air:12, missiles:30, nukes:0,
      tech:{ai:3,semis:1,energy:3,space:1,cyber:4,hyper:0,bio:3,quantum:1,defense:3},
      res:{oil:1,gas:1,grain:6,chips:1,rare:3}, blocs:['ASEAN'],
      neighbors:['CHN','THA'], seaNeighbors:['IDN','PHL'], color:'#fca5a5',
      regions:[['Hanoi & Nord',0.40,true],['Da Nang & Centro',0.15],['Ho Chi Minh & Sud',0.45]] },
    { id:'KOR', name:'Corea del Sud', flag:'🇰🇷', continent:'Asia', lat:37.6, lon:127.0, regime:'democrazia', persona:'mercante',
      gdp:1850, growth:1.8, pop:52, stability:65, debt:55, treasury:120,
      army:45, navy:30, air:40, missiles:250, nukes:0,
      tech:{ai:7,semis:10,energy:6,space:5,cyber:7,hyper:3,bio:7,quantum:6,defense:8},
      res:{oil:0,gas:0,grain:2,chips:10,rare:0}, blocs:[],
      neighbors:['PRK'], color:'#a5b4fc', allies:['USA'],
      regions:[['Seul & Nord',0.55,true],['Busan & Sud',0.45]] },
    { id:'PRK', name:'Corea del Nord', flag:'🇰🇵', continent:'Asia', lat:39.0, lon:125.7, regime:'autocrazia', persona:'imprevedibile',
      gdp:30, growth:1.0, pop:26, stability:78, debt:0, treasury:2,
      army:40, navy:5, air:8, missiles:600, nukes:50,
      tech:{ai:1,semis:0,energy:1,space:2,cyber:7,hyper:3,bio:2,quantum:0,defense:2},
      res:{oil:0,gas:0,grain:1,chips:0,rare:3}, blocs:[],
      neighbors:['KOR','CHN','RUS'], color:'#7f1d1d', claims:{KOR:'all'},
      regions:[['Pyongyang',0.55,true],['Costa Est & Wonsan',0.20],['Nord & Confine cinese',0.25]] },
    { id:'TWN', name:'Taiwan', flag:'🇹🇼', continent:'Asia', lat:25.0, lon:121.5, regime:'democrazia', persona:'difensivo',
      gdp:820, growth:3.0, pop:23, stability:70, debt:30, treasury:150,
      army:25, navy:15, air:25, missiles:200, nukes:0,
      tech:{ai:7,semis:10,energy:4,space:3,cyber:7,hyper:2,bio:6,quantum:5,defense:7},
      res:{oil:0,gas:0,grain:1,chips:10,rare:0}, blocs:[],
      neighbors:[], color:'#2dd4bf', allies:['USA'], seaNeighbors:['CHN'],
      regions:[['Taipei & Nord',0.45,true],['Hsinchu & Taichung (fab di chip)',0.35],['Kaohsiung & Sud',0.20]] },
    { id:'PAK', name:'Pakistan', flag:'🇵🇰', continent:'Asia', lat:33.7, lon:73.1, regime:'ibrido', persona:'opportunista',
      gdp:380, growth:2.5, pop:242, stability:38, debt:75, treasury:5,
      army:50, navy:10, air:25, missiles:250, nukes:170,
      tech:{ai:2,semis:0,energy:3,space:2,cyber:4,hyper:1,bio:2,quantum:0,defense:3},
      res:{oil:0,gas:2,grain:5,chips:0,rare:1}, blocs:['SCO'],
      neighbors:['IND','CHN','IRN'], color:'#065f46', claims:{IND:'Kashmir'},
      regions:[['Islamabad & Punjab',0.55,true],['Karachi & Sindh',0.30],['Belucistan & Nord-Ovest',0.15]] },
    { id:'KAZ', name:'Kazakistan', flag:'🇰🇿', continent:'Asia', lat:51.1, lon:71.4, regime:'autocrazia', persona:'isolazionista',
      gdp:280, growth:4.0, pop:20, stability:60, debt:25, treasury:60,
      army:10, navy:0, air:8, missiles:10, nukes:0,
      tech:{ai:2,semis:0,energy:5,space:3,cyber:3,hyper:0,bio:2,quantum:0,defense:2},
      res:{oil:6,gas:4,grain:6,chips:0,rare:5}, blocs:['CSTO','SCO'],
      neighbors:['RUS','CHN','UZB'], color:'#93c5fd',
      regions:[['Astana & Nord',0.45,true],['Almaty & Sud',0.30],['Caspio (petrolio)',0.25]] },

    // ---- Estensione: altre 26 nazioni ----
    { id:'ETH', name:'Etiopia', flag:'🇪🇹', continent:'Africa', lat:9.0, lon:38.7, regime:'ibrido', persona:'ambizioso',
      gdp:175, growth:6.5, pop:130, stability:38, debt:40, treasury:5,
      army:30, navy:0, air:8, missiles:10, nukes:0,
      tech:{ai:1,semis:0,energy:3,space:1,cyber:2,hyper:0,bio:1,quantum:0,defense:1},
      res:{oil:0,gas:0,grain:4,chips:0,rare:1}, blocs:['BRICS','AU'],
      neighbors:['KEN','EGY'], color:'#16a34a',
      regions:[['Addis Abeba & Centro',0.50,true],['Oromia & Sud',0.30],['Tigray & Nord',0.20]] },
    { id:'KEN', name:'Kenya', flag:'🇰🇪', continent:'Africa', lat:-1.3, lon:36.8, regime:'democrazia', persona:'mercante',
      gdp:125, growth:5.0, pop:56, stability:48, debt:70, treasury:5,
      army:10, navy:4, air:6, missiles:0, nukes:0,
      tech:{ai:2,semis:0,energy:4,space:1,cyber:3,hyper:0,bio:2,quantum:0,defense:1},
      res:{oil:0,gas:0,grain:3,chips:0,rare:1}, blocs:['AU'],
      neighbors:['ETH','COD'], color:'#dc2626',
      regions:[['Nairobi',0.60,true],['Mombasa & Costa',0.25],['Ovest',0.15]] },
    { id:'DZA', name:'Algeria', flag:'🇩🇿', continent:'Africa', lat:36.7, lon:3.1, regime:'autocrazia', persona:'opportunista',
      gdp:270, growth:3.0, pop:46, stability:50, debt:50, treasury:60,
      army:35, navy:12, air:25, missiles:60, nukes:0,
      tech:{ai:2,semis:0,energy:4,space:2,cyber:3,hyper:0,bio:2,quantum:0,defense:4},
      res:{oil:6,gas:8,grain:2,chips:0,rare:0}, blocs:['OPEC','AU'],
      neighbors:['MAR','ESP'], color:'#15803d', claims:{},
      regions:[['Algeri & Nord',0.55,true],['Hassi Messaoud (gas)',0.30],['Sud sahariano',0.15]] },
    { id:'MAR', name:'Marocco', flag:'🇲🇦', continent:'Africa', lat:34.0, lon:-6.8, regime:'ibrido', persona:'mercante',
      gdp:165, growth:3.5, pop:38, stability:60, debt:70, treasury:10,
      army:22, navy:8, air:15, missiles:20, nukes:0,
      tech:{ai:2,semis:0,energy:5,space:1,cyber:3,hyper:0,bio:2,quantum:0,defense:3},
      res:{oil:0,gas:0,grain:3,chips:0,rare:4}, blocs:['AU'],
      neighbors:['DZA','ESP'], color:'#b91c1c',
      regions:[['Rabat & Casablanca',0.65,true],['Nord & Tangeri',0.20],['Sahara Occidentale',0.15]] },
    { id:'COD', name:'RD Congo', flag:'🇨🇩', continent:'Africa', lat:-4.3, lon:15.3, regime:'ibrido', persona:'isolazionista',
      gdp:80, growth:4.5, pop:105, stability:28, debt:20, treasury:2,
      army:12, navy:0, air:3, missiles:0, nukes:0,
      tech:{ai:0,semis:0,energy:1,space:0,cyber:1,hyper:0,bio:1,quantum:0,defense:0},
      res:{oil:1,gas:0,grain:2,chips:0,rare:9}, blocs:['AU'],
      neighbors:['KEN','ZAF','NGA'], color:'#2563eb',
      regions:[['Kinshasa',0.45,true],['Katanga (cobalto)',0.35],['Kivu & Est',0.20]] },
    { id:'COL', name:'Colombia', flag:'🇨🇴', continent:'Sud America', lat:4.7, lon:-74.1, regime:'democrazia', persona:'mercante',
      gdp:430, growth:2.5, pop:53, stability:45, debt:60, treasury:10,
      army:25, navy:8, air:10, missiles:5, nukes:0,
      tech:{ai:2,semis:0,energy:4,space:1,cyber:3,hyper:0,bio:3,quantum:0,defense:2},
      res:{oil:4,gas:2,grain:4,chips:0,rare:1}, blocs:[],
      neighbors:['VEN','PER','BRA'], color:'#facc15',
      regions:[['Bogotá',0.45,true],['Medellín & Antioquia',0.30],['Caraibi & Pacifico',0.25]] },
    { id:'VEN', name:'Venezuela', flag:'🇻🇪', continent:'Sud America', lat:10.5, lon:-66.9, regime:'autocrazia', persona:'falco',
      gdp:105, growth:2.0, pop:29, stability:30, debt:150, treasury:3,
      army:20, navy:5, air:10, missiles:30, nukes:0,
      tech:{ai:1,semis:0,energy:3,space:0,cyber:2,hyper:0,bio:1,quantum:0,defense:3},
      res:{oil:7,gas:3,grain:1,chips:0,rare:2}, blocs:['OPEC'],
      neighbors:['COL','BRA'], color:'#7c2d12',
      regions:[['Caracas',0.55,true],['Maracaibo (petrolio)',0.30],['Orinoco & Sud',0.15]] },
    { id:'PER', name:'Perù', flag:'🇵🇪', continent:'Sud America', lat:-12.0, lon:-77.0, regime:'democrazia', persona:'isolazionista',
      gdp:295, growth:2.8, pop:34, stability:38, debt:35, treasury:15,
      army:15, navy:8, air:8, missiles:5, nukes:0,
      tech:{ai:2,semis:0,energy:4,space:1,cyber:2,hyper:0,bio:2,quantum:0,defense:1},
      res:{oil:1,gas:3,grain:3,chips:0,rare:6}, blocs:[],
      neighbors:['COL','CHL','BRA'], color:'#ef4444',
      regions:[['Lima',0.55,true],['Ande & miniere',0.30],['Amazzonia',0.15]] },
    { id:'CHL', name:'Cile', flag:'🇨🇱', continent:'Sud America', lat:-33.4, lon:-70.7, regime:'democrazia', persona:'mercante',
      gdp:355, growth:2.5, pop:20, stability:58, debt:40, treasury:40,
      army:15, navy:12, air:12, missiles:10, nukes:0,
      tech:{ai:3,semis:0,energy:6,space:2,cyber:4,hyper:0,bio:3,quantum:1,defense:2},
      res:{oil:0,gas:0,grain:3,chips:0,rare:8}, blocs:[],
      neighbors:['PER','ARG'], color:'#3b82f6',
      regions:[['Santiago',0.60,true],['Nord minerario (litio, rame)',0.30],['Sud & Patagonia',0.10]] },
    { id:'CUB', name:'Cuba', flag:'🇨🇺', continent:'Nord America', lat:23.1, lon:-82.4, regime:'autocrazia', persona:'difensivo',
      gdp:28, growth:0.5, pop:11, stability:42, debt:60, treasury:1,
      army:12, navy:2, air:5, missiles:10, nukes:0,
      tech:{ai:1,semis:0,energy:2,space:0,cyber:3,hyper:0,bio:5,quantum:0,defense:2},
      res:{oil:0,gas:0,grain:1,chips:0,rare:2}, blocs:[],
      neighbors:[], seaNeighbors:['USA','MEX'], color:'#1d4ed8',
      regions:[['L’Avana',0.65,true],['Santiago & Oriente',0.35]] },
    { id:'THA', name:'Thailandia', flag:'🇹🇭', continent:'Asia', lat:13.7, lon:100.5, regime:'ibrido', persona:'mercante',
      gdp:560, growth:2.8, pop:72, stability:50, debt:62, treasury:40,
      army:25, navy:12, air:15, missiles:20, nukes:0,
      tech:{ai:3,semis:1,energy:4,space:1,cyber:3,hyper:0,bio:4,quantum:1,defense:3},
      res:{oil:1,gas:2,grain:7,chips:1,rare:1}, blocs:['ASEAN'],
      neighbors:['MYS','VNM'], color:'#a855f7',
      regions:[['Bangkok',0.55,true],['Nord & Chiang Mai',0.20],['Sud & Istmo',0.25]] },
    { id:'PHL', name:'Filippine', flag:'🇵🇭', continent:'Asia', lat:14.6, lon:121.0, regime:'democrazia', persona:'difensivo',
      gdp:490, growth:5.5, pop:118, stability:52, debt:60, treasury:10,
      army:20, navy:10, air:8, missiles:30, nukes:0,
      tech:{ai:2,semis:1,energy:3,space:1,cyber:3,hyper:0,bio:2,quantum:0,defense:2},
      res:{oil:0,gas:1,grain:3,chips:1,rare:3}, blocs:['ASEAN'],
      neighbors:[], seaNeighbors:['CHN','TWN','IDN'], allies:['USA'], color:'#0ea5e9',
      regions:[['Manila & Luzon',0.65,true],['Visayas',0.15],['Mindanao',0.20]] },
    { id:'MYS', name:'Malesia', flag:'🇲🇾', continent:'Asia', lat:3.1, lon:101.7, regime:'democrazia', persona:'mercante',
      gdp:450, growth:4.5, pop:35, stability:60, debt:65, treasury:40,
      army:12, navy:10, air:10, missiles:10, nukes:0,
      tech:{ai:4,semis:4,energy:4,space:1,cyber:4,hyper:0,bio:3,quantum:1,defense:2},
      res:{oil:4,gas:5,grain:2,chips:3,rare:2}, blocs:['ASEAN'],
      neighbors:['THA'], seaNeighbors:['IDN'], color:'#fbbf24',
      regions:[['Kuala Lumpur',0.60,true],['Penang & Nord',0.20],['Borneo malese',0.20]] },
    { id:'BGD', name:'Bangladesh', flag:'🇧🇩', continent:'Asia', lat:23.8, lon:90.4, regime:'ibrido', persona:'isolazionista',
      gdp:490, growth:5.5, pop:175, stability:40, debt:40, treasury:10,
      army:18, navy:5, air:6, missiles:5, nukes:0,
      tech:{ai:1,semis:0,energy:3,space:1,cyber:2,hyper:0,bio:2,quantum:0,defense:1},
      res:{oil:0,gas:3,grain:4,chips:0,rare:0}, blocs:[],
      neighbors:['IND'], color:'#15803d',
      regions:[['Dacca',0.55,true],['Chittagong & Sud-Est',0.25],['Nord',0.20]] },
    { id:'IRQ', name:'Iraq', flag:'🇮🇶', continent:'Medio Oriente', lat:33.3, lon:44.4, regime:'ibrido', persona:'opportunista',
      gdp:270, growth:3.0, pop:46, stability:35, debt:45, treasury:30,
      army:30, navy:2, air:10, missiles:40, nukes:0,
      tech:{ai:1,semis:0,energy:3,space:0,cyber:2,hyper:0,bio:1,quantum:0,defense:2},
      res:{oil:9,gas:3,grain:2,chips:0,rare:0}, blocs:['OPEC'],
      neighbors:['IRN','TUR','SAU'], color:'#b45309',
      regions:[['Baghdad',0.45,true],['Bassora (petrolio)',0.35],['Kurdistan & Nord',0.20]] },
    { id:'QAT', name:'Qatar', flag:'🇶🇦', continent:'Medio Oriente', lat:25.3, lon:51.5, regime:'autocrazia', persona:'mercante',
      gdp:240, growth:3.0, pop:3, stability:85, debt:40, treasury:500,
      army:6, navy:4, air:12, missiles:20, nukes:0,
      tech:{ai:4,semis:0,energy:6,space:1,cyber:4,hyper:0,bio:2,quantum:1,defense:5},
      res:{oil:5,gas:10,grain:0,chips:0,rare:0}, blocs:['OPEC'],
      neighbors:['SAU'], allies:['USA'], color:'#7f1d1d',
      regions:[['Doha',0.70,true],['Ras Laffan (GNL)',0.30]] },
    { id:'GRC', name:'Grecia', flag:'🇬🇷', continent:'Europa', lat:38.0, lon:23.7, regime:'democrazia', persona:'difensivo',
      gdp:255, growth:2.0, pop:10, stability:55, debt:160, treasury:10,
      army:20, navy:15, air:20, missiles:30, nukes:0,
      tech:{ai:3,semis:0,energy:5,space:2,cyber:4,hyper:0,bio:4,quantum:1,defense:4},
      res:{oil:0,gas:1,grain:3,chips:0,rare:0}, blocs:['NATO','EU'],
      neighbors:['TUR'], color:'#60a5fa',
      regions:[['Atene & Attica',0.55,true],['Salonicco & Nord',0.25],['Isole & Creta',0.20]] },
    { id:'SWE', name:'Svezia', flag:'🇸🇪', continent:'Europa', lat:59.3, lon:18.1, regime:'democrazia', persona:'mercante',
      gdp:620, growth:1.5, pop:10.6, stability:78, debt:35, treasury:50,
      army:15, navy:10, air:20, missiles:20, nukes:0,
      tech:{ai:6,semis:2,energy:7,space:4,cyber:7,hyper:1,bio:7,quantum:5,defense:5},
      res:{oil:0,gas:0,grain:3,chips:0,rare:3}, blocs:['NATO','EU'],
      neighbors:['FIN','NOR'], color:'#fde047',
      regions:[['Stoccolma',0.55,true],['Göteborg & Sud',0.30],['Norrland',0.15]] },
    { id:'NOR', name:'Norvegia', flag:'🇳🇴', continent:'Europa', lat:59.9, lon:10.7, regime:'democrazia', persona:'mercante',
      gdp:520, growth:1.5, pop:5.6, stability:86, debt:40, treasury:1500,
      army:10, navy:12, air:15, missiles:20, nukes:0,
      tech:{ai:5,semis:1,energy:8,space:3,cyber:6,hyper:1,bio:6,quantum:3,defense:4},
      res:{oil:8,gas:9,grain:1,chips:0,rare:1}, blocs:['NATO'],
      neighbors:['SWE','RUS'], color:'#ef4444',
      regions:[['Oslo',0.50,true],['Mare del Nord (petrolio)',0.35],['Nord artico',0.15]] },
    { id:'NLD', name:'Paesi Bassi', flag:'🇳🇱', continent:'Europa', lat:52.4, lon:4.9, regime:'democrazia', persona:'mercante',
      gdp:1180, growth:1.5, pop:18, stability:72, debt:45, treasury:80,
      army:12, navy:15, air:15, missiles:20, nukes:0,
      tech:{ai:6,semis:9,energy:6,space:4,cyber:7,hyper:1,bio:7,quantum:6,defense:5},
      res:{oil:0,gas:2,grain:5,chips:4,rare:0}, blocs:['NATO','EU'],
      neighbors:['DEU'], color:'#fb923c',
      regions:[['Amsterdam & Randstad',0.65,true],['Eindhoven & Sud (litografia chip)',0.20],['Nord',0.15]] },
    { id:'ROU', name:'Romania', flag:'🇷🇴', continent:'Europa', lat:44.4, lon:26.1, regime:'democrazia', persona:'difensivo',
      gdp:390, growth:2.5, pop:19, stability:50, debt:52, treasury:10,
      army:18, navy:5, air:12, missiles:20, nukes:0,
      tech:{ai:3,semis:1,energy:5,space:2,cyber:5,hyper:0,bio:3,quantum:1,defense:4},
      res:{oil:2,gas:3,grain:6,chips:0,rare:0}, blocs:['NATO','EU'],
      neighbors:['UKR','HUN'], color:'#fde68a',
      regions:[['Bucarest',0.50,true],['Transilvania',0.30],['Costanza & Mar Nero',0.20]] },
    { id:'HUN', name:'Ungheria', flag:'🇭🇺', continent:'Europa', lat:47.5, lon:19.0, regime:'ibrido', persona:'opportunista',
      gdp:225, growth:2.0, pop:9.6, stability:55, debt:72, treasury:8,
      army:10, navy:0, air:8, missiles:10, nukes:0,
      tech:{ai:3,semis:1,energy:5,space:1,cyber:4,hyper:0,bio:4,quantum:1,defense:3},
      res:{oil:0,gas:1,grain:5,chips:0,rare:0}, blocs:['NATO','EU'],
      neighbors:['ROU','UKR'], color:'#22c55e',
      regions:[['Budapest',0.60,true],['Ovest & Győr',0.25],['Est',0.15]] },
    { id:'BLR', name:'Bielorussia', flag:'🇧🇾', continent:'Europa', lat:53.9, lon:27.6, regime:'autocrazia', persona:'difensivo',
      gdp:78, growth:1.0, pop:9, stability:50, debt:40, treasury:3,
      army:20, navy:0, air:8, missiles:60, nukes:0,
      tech:{ai:2,semis:0,energy:4,space:1,cyber:4,hyper:1,bio:2,quantum:0,defense:4},
      res:{oil:0,gas:0,grain:4,chips:0,rare:1}, blocs:['CSTO'],
      neighbors:['RUS','UKR','POL'], color:'#991b1b',
      regions:[['Minsk',0.65,true],['Gomel & Sud',0.35]] },
    { id:'UZB', name:'Uzbekistan', flag:'🇺🇿', continent:'Asia', lat:41.3, lon:69.3, regime:'autocrazia', persona:'isolazionista',
      gdp:115, growth:5.5, pop:36, stability:60, debt:35, treasury:15,
      army:15, navy:0, air:8, missiles:10, nukes:0,
      tech:{ai:1,semis:0,energy:4,space:0,cyber:2,hyper:0,bio:1,quantum:0,defense:1},
      res:{oil:1,gas:5,grain:4,chips:0,rare:3}, blocs:['SCO'],
      neighbors:['KAZ'], color:'#38bdf8',
      regions:[['Tashkent',0.55,true],['Samarcanda & Sud',0.25],['Fergana',0.20]] },
    { id:'CHE', name:'Svizzera', flag:'🇨🇭', continent:'Europa', lat:46.9, lon:7.4, regime:'democrazia', persona:'isolazionista',
      gdp:960, growth:1.3, pop:9, stability:88, debt:38, treasury:300,
      army:10, navy:0, air:12, missiles:10, nukes:0,
      tech:{ai:6,semis:2,energy:7,space:3,cyber:6,hyper:0,bio:9,quantum:6,defense:5},
      res:{oil:0,gas:0,grain:2,chips:0,rare:0}, blocs:[],
      neighbors:['DEU','FRA','ITA'], color:'#f87171',
      regions:[['Zurigo & Berna',0.65,true],['Ginevra & Romandia',0.25],['Ticino & Alpi',0.10]] },
    { id:'NZL', name:'Nuova Zelanda', flag:'🇳🇿', continent:'Oceania', lat:-41.3, lon:174.8, regime:'democrazia', persona:'isolazionista',
      gdp:265, growth:1.8, pop:5.3, stability:82, debt:45, treasury:20,
      army:5, navy:4, air:5, missiles:0, nukes:0,
      tech:{ai:4,semis:0,energy:7,space:3,cyber:5,hyper:0,bio:5,quantum:2,defense:1},
      res:{oil:0,gas:1,grain:5,chips:0,rare:0}, blocs:['FIVEEYES'],
      neighbors:[], seaNeighbors:['AUS'], color:'#e2e8f0',
      regions:[['Auckland & Isola del Nord',0.75,true],['Isola del Sud',0.25]] },
  ];

  // ---- Profili aggiuntivi (capitale, carica, ISU, CO2 Mt/anno, disoccupazione %, età mediana) ----
  GEO.PROFILES = {"USA":{"capital":"Washington","title":"Presidente","hdi":0.93,"co2":4800,"unemp":4.2,"medianAge":38.5},"CHN":{"capital":"Pechino","title":"Segretario generale","hdi":0.79,"co2":11900,"unemp":5.2,"medianAge":39.8},"RUS":{"capital":"Mosca","title":"Presidente","hdi":0.82,"co2":1800,"unemp":2.6,"medianAge":40.3},"IND":{"capital":"Nuova Delhi","title":"Primo ministro","hdi":0.64,"co2":2900,"unemp":7.8,"medianAge":28.4},"JPN":{"capital":"Tokyo","title":"Primo ministro","hdi":0.92,"co2":1000,"unemp":2.5,"medianAge":49.5},"DEU":{"capital":"Berlino","title":"Cancelliere","hdi":0.95,"co2":600,"unemp":3.4,"medianAge":46.8},"FRA":{"capital":"Parigi","title":"Presidente","hdi":0.91,"co2":290,"unemp":7.3,"medianAge":42.3},"GBR":{"capital":"Londra","title":"Primo ministro","hdi":0.94,"co2":320,"unemp":4.3,"medianAge":40.6},"ITA":{"capital":"Roma","title":"Presidente del Consiglio","hdi":0.91,"co2":310,"unemp":6.5,"medianAge":48.1},"ESP":{"capital":"Madrid","title":"Presidente del Governo","hdi":0.91,"co2":230,"unemp":11.5,"medianAge":45.1},"POL":{"capital":"Varsavia","title":"Primo ministro","hdi":0.88,"co2":300,"unemp":3.0,"medianAge":42.0},"UKR":{"capital":"Kiev","title":"Presidente","hdi":0.73,"co2":110,"unemp":15.0,"medianAge":44.3},"FIN":{"capital":"Helsinki","title":"Primo ministro","hdi":0.94,"co2":35,"unemp":7.5,"medianAge":43.5},"TUR":{"capital":"Ankara","title":"Presidente","hdi":0.86,"co2":440,"unemp":9.0,"medianAge":33.0},"SAU":{"capital":"Riad","title":"Principe ereditario","hdi":0.88,"co2":650,"unemp":4.0,"medianAge":30.8},"ARE":{"capital":"Abu Dhabi","title":"Presidente","hdi":0.94,"co2":220,"unemp":2.8,"medianAge":33.0},"IRN":{"capital":"Teheran","title":"Guida suprema","hdi":0.78,"co2":700,"unemp":9.0,"medianAge":33.0},"ISR":{"capital":"Gerusalemme","title":"Primo ministro","hdi":0.92,"co2":65,"unemp":3.5,"medianAge":30.1},"EGY":{"capital":"Il Cairo","title":"Presidente","hdi":0.73,"co2":270,"unemp":7.0,"medianAge":24.5},"NGA":{"capital":"Abuja","title":"Presidente","hdi":0.55,"co2":130,"unemp":5.0,"medianAge":18.1},"ZAF":{"capital":"Pretoria","title":"Presidente","hdi":0.72,"co2":440,"unemp":32.0,"medianAge":28.0},"BRA":{"capital":"Brasilia","title":"Presidente","hdi":0.76,"co2":480,"unemp":7.5,"medianAge":33.5},"ARG":{"capital":"Buenos Aires","title":"Presidente","hdi":0.85,"co2":190,"unemp":7.5,"medianAge":32.4},"MEX":{"capital":"Città del Messico","title":"Presidente","hdi":0.78,"co2":490,"unemp":2.8,"medianAge":29.3},"CAN":{"capital":"Ottawa","title":"Primo ministro","hdi":0.94,"co2":550,"unemp":6.3,"medianAge":41.1},"AUS":{"capital":"Canberra","title":"Primo ministro","hdi":0.95,"co2":390,"unemp":4.0,"medianAge":37.5},"IDN":{"capital":"Giacarta","title":"Presidente","hdi":0.71,"co2":700,"unemp":5.0,"medianAge":30.2},"VNM":{"capital":"Hanoi","title":"Segretario generale","hdi":0.73,"co2":350,"unemp":2.2,"medianAge":32.5},"KOR":{"capital":"Seul","title":"Presidente","hdi":0.93,"co2":600,"unemp":2.8,"medianAge":44.5},"PRK":{"capital":"Pyongyang","title":"Leader supremo","hdi":0.5,"co2":50,"unemp":25.0,"medianAge":35.0},"TWN":{"capital":"Taipei","title":"Presidente","hdi":0.92,"co2":270,"unemp":3.4,"medianAge":43.0},"PAK":{"capital":"Islamabad","title":"Primo ministro","hdi":0.54,"co2":230,"unemp":8.0,"medianAge":22.0},"KAZ":{"capital":"Astana","title":"Presidente","hdi":0.8,"co2":220,"unemp":4.8,"medianAge":31.0},"ETH":{"capital":"Addis Abeba","title":"Primo ministro","hdi":0.49,"co2":20,"unemp":3.5,"medianAge":19.5},"KEN":{"capital":"Nairobi","title":"Presidente","hdi":0.6,"co2":22,"unemp":5.7,"medianAge":20.0},"DZA":{"capital":"Algeri","title":"Presidente","hdi":0.75,"co2":180,"unemp":12.0,"medianAge":28.5},"MAR":{"capital":"Rabat","title":"Re","hdi":0.7,"co2":75,"unemp":12.5,"medianAge":29.0},"COD":{"capital":"Kinshasa","title":"Presidente","hdi":0.48,"co2":4,"unemp":5.0,"medianAge":16.7},"COL":{"capital":"Bogotá","title":"Presidente","hdi":0.76,"co2":95,"unemp":10.0,"medianAge":31.0},"VEN":{"capital":"Caracas","title":"Presidente","hdi":0.7,"co2":110,"unemp":7.0,"medianAge":29.0},"PER":{"capital":"Lima","title":"Presidente","hdi":0.76,"co2":55,"unemp":6.5,"medianAge":29.0},"CHL":{"capital":"Santiago","title":"Presidente","hdi":0.86,"co2":90,"unemp":8.5,"medianAge":35.5},"CUB":{"capital":"L'Avana","title":"Presidente","hdi":0.76,"co2":28,"unemp":3.0,"medianAge":42.0},"THA":{"capital":"Bangkok","title":"Primo ministro","hdi":0.8,"co2":270,"unemp":1.0,"medianAge":40.0},"PHL":{"capital":"Manila","title":"Presidente","hdi":0.71,"co2":150,"unemp":4.5,"medianAge":25.7},"MYS":{"capital":"Kuala Lumpur","title":"Primo ministro","hdi":0.81,"co2":270,"unemp":3.5,"medianAge":30.3},"BGD":{"capital":"Dacca","title":"Primo ministro","hdi":0.67,"co2":100,"unemp":5.0,"medianAge":27.0},"IRQ":{"capital":"Baghdad","title":"Primo ministro","hdi":0.69,"co2":190,"unemp":15.0,"medianAge":21.0},"QAT":{"capital":"Doha","title":"Emiro","hdi":0.87,"co2":110,"unemp":0.2,"medianAge":33.7},"GRC":{"capital":"Atene","title":"Primo ministro","hdi":0.89,"co2":55,"unemp":10.0,"medianAge":45.6},"SWE":{"capital":"Stoccolma","title":"Primo ministro","hdi":0.95,"co2":38,"unemp":8.0,"medianAge":41.1},"NOR":{"capital":"Oslo","title":"Primo ministro","hdi":0.96,"co2":42,"unemp":4.0,"medianAge":40.0},"NLD":{"capital":"Amsterdam","title":"Primo ministro","hdi":0.95,"co2":140,"unemp":3.7,"medianAge":42.8},"ROU":{"capital":"Bucarest","title":"Presidente","hdi":0.83,"co2":70,"unemp":5.5,"medianAge":43.0},"HUN":{"capital":"Budapest","title":"Primo ministro","hdi":0.85,"co2":45,"unemp":4.5,"medianAge":44.0},"BLR":{"capital":"Minsk","title":"Presidente","hdi":0.8,"co2":60,"unemp":3.5,"medianAge":40.9},"UZB":{"capital":"Tashkent","title":"Presidente","hdi":0.73,"co2":120,"unemp":5.0,"medianAge":29.0},"CHE":{"capital":"Berna","title":"Presidente della Confederazione","hdi":0.97,"co2":35,"unemp":2.5,"medianAge":43.0},"NZL":{"capital":"Wellington","title":"Primo ministro","hdi":0.94,"co2":33,"unemp":4.5,"medianAge":37.5}};

  // ---- Rivalità strutturali (relazione iniziale) -----------------------------
  GEO.RELATIONS_SEED = [
    ['USA','CHN',-55],['USA','RUS',-80],['USA','IRN',-85],['USA','PRK',-90],['USA','UKR',55],['USA','TWN',60],
    ['USA','ISR',75],['USA','SAU',35],['USA','MEX',25],['USA','CAN',50],['USA','GBR',80],['USA','JPN',75],['USA','KOR',70],
    ['USA','IND',40],['USA','AUS',80],['USA','POL',65],['USA','DEU',55],['USA','FRA',55],['USA','ITA',55],['USA','VNM',20],
    ['USA','BRA',10],['USA','ZAF',-5],['USA','TUR',10],['USA','EGY',20],['USA','PAK',-10],['USA','ARE',40],
    ['CHN','RUS',65],['CHN','IND',-45],['CHN','JPN',-50],['CHN','TWN',-85],['CHN','VNM',-30],['CHN','PRK',40],['CHN','PAK',60],
    ['CHN','AUS',-25],['CHN','KOR',-15],['CHN','IRN',40],['CHN','SAU',30],['CHN','BRA',30],['CHN','ZAF',35],['CHN','NGA',30],
    ['CHN','IDN',20],['CHN','KAZ',45],['CHN','EGY',25],['CHN','DEU',0],['CHN','GBR',-25],['CHN','FRA',-10],['CHN','ITA',0],
    ['RUS','UKR',-100],['RUS','POL',-80],['RUS','FIN',-60],['RUS','DEU',-55],['RUS','FRA',-55],['RUS','GBR',-70],['RUS','ITA',-40],
    ['RUS','IRN',55],['RUS','PRK',60],['RUS','IND',45],['RUS','TUR',10],['RUS','SAU',25],['RUS','KAZ',50],['RUS','JPN',-45],
    ['RUS','BRA',20],['RUS','ZAF',25],['RUS','EGY',20],['RUS','ESP',-45],['RUS','CAN',-55],['RUS','AUS',-50],['RUS','KOR',-30],
    ['IND','PAK',-85],['IND','JPN',55],['IND','AUS',50],['IND','GBR',35],['IND','FRA',45],['IND','ISR',40],['IND','IRN',15],
    ['JPN','KOR',25],['JPN','PRK',-80],['JPN','TWN',45],['JPN','AUS',60],['KOR','PRK',-85],['PRK','TWN',-30],
    ['IRN','ISR',-100],['IRN','SAU',-50],['IRN','ARE',-35],['IRN','TUR',-10],['IRN','PAK',10],['IRN','EGY',-25],
    ['ISR','SAU',-5],['ISR','ARE',30],['ISR','EGY',10],['ISR','TUR',-50],['SAU','ARE',55],['SAU','EGY',45],
    ['DEU','FRA',75],['DEU','POL',40],['DEU','ITA',60],['DEU','ESP',55],['FRA','ITA',60],['FRA','ESP',65],['FRA','GBR',45],
    ['GBR','ARG',-30],['ITA','ESP',55],['POL','UKR',65],['POL','FIN',50],['FIN','UKR',50],['DEU','UKR',45],['FRA','UKR',45],['GBR','UKR',60],
    ['BRA','ARG',40],['MEX','CAN',35],['AUS','IDN',25],['VNM','IDN',30],['NGA','ZAF',20],['EGY','NGA',15],['TUR','EGY',-15],
    ['CHN','USA',-55],['ARE','USA',40],
    ['USA','CUB',-70],['USA','VEN',-70],['USA','PHL',60],['USA','QAT',40],['USA','COL',45],['USA','NLD',60],['USA','NOR',60],['USA','SWE',55],['USA','IRQ',10],['USA','HUN',15],['USA','BLR',-60],['USA','NZL',55],['USA','CHL',35],
    ['CHN','PHL',-55],['CHN','CUB',45],['CHN','VEN',45],['CHN','ETH',35],['CHN','KEN',30],['CHN','COD',40],['CHN','MYS',15],['CHN','THA',20],['CHN','UZB',40],['CHN','BLR',40],['CHN','HUN',30],['CHN','CHL',20],['CHN','PER',20],['CHN','NLD',-20],
    ['RUS','BLR',85],['RUS','VEN',55],['RUS','CUB',50],['RUS','HUN',25],['RUS','SWE',-55],['RUS','NOR',-50],['RUS','NLD',-55],['RUS','ROU',-55],['RUS','GRC',-20],['RUS','UZB',45],['RUS','DZA',35],['RUS','IRQ',20],['RUS','ETH',25],
    ['BLR','UKR',-75],['BLR','POL',-65],['BLR','FIN',-40],['UKR','ROU',50],['UKR','HUN',-15],['UKR','SWE',55],['UKR','NOR',55],['UKR','NLD',60],
    ['GRC','TUR',-45],['DZA','MAR',-55],['ETH','EGY',-45],['VEN','COL',-40],['CUB','MEX',30],['PHL','TWN',30],['PHL','JPN',45],['PHL','VNM',35],
    ['IRQ','IRN',35],['IRQ','SAU',5],['QAT','SAU',20],['QAT','IRN',10],['QAT','ARE',10],
    ['NLD','DEU',70],['NLD','GBR',55],['SWE','NOR',75],['SWE','FIN',75],['NOR','FIN',65],['CHE','DEU',55],['CHE','FRA',50],['CHE','ITA',50],['HUN','ROU',-15],['ROU','POL',45],['GRC','ITA',40],
    ['NZL','AUS',80],['MYS','IDN',40],['THA','VNM',25],['BGD','IND',10],['KEN','ETH',20],['COD','ZAF',20],['CHL','ARG',30],['PER','CHL',-10],['COL','BRA',35],['VEN','BRA',10],
  ];

  // Partnership di difesa bilaterali attive all'inizio
  GEO.TREATIES_SEED = [
    { type:'difesa', a:'USA', b:'JPN' }, { type:'difesa', a:'USA', b:'KOR' }, { type:'difesa', a:'USA', b:'ISR' },
    { type:'difesa', a:'USA', b:'TWN', informal:true }, { type:'difesa', a:'USA', b:'SAU', informal:true }, { type:'difesa', a:'USA', b:'ARE', informal:true }, { type:'difesa', a:'USA', b:'PHL' }, { type:'difesa', a:'USA', b:'QAT', informal:true }, { type:'difesa', a:'RUS', b:'BLR' }, { type:'difesa', a:'RUS', b:'PRK' }, { type:'difesa', a:'CHN', b:'PAK' },
    { type:'commercio', a:'CHN', b:'RUS' }, { type:'commercio', a:'USA', b:'JPN' }, { type:'commercio', a:'DEU', b:'CHN' },
    { type:'commercio', a:'IND', b:'ARE' }, { type:'commercio', a:'AUS', b:'JPN' }, { type:'commercio', a:'BRA','b':'CHN' },
    { type:'nonaggressione', a:'IND', b:'CHN' },
  ];

  // Guerre in corso all'inizio dello scenario
  GEO.WARS_SEED = [
    { attackers:['RUS'], defenders:['UKR'], since:-14, score:15, label:'Guerra russo-ucraina' },
  ];

  // Sanzioni attive all'inizio
  GEO.SANCTIONS_SEED = [
    ['USA','RUS'],['GBR','RUS'],['DEU','RUS'],['FRA','RUS'],['ITA','RUS'],['ESP','RUS'],['POL','RUS'],['FIN','RUS'],['CAN','RUS'],['JPN','RUS'],['AUS','RUS'],['UKR','RUS'],
    ['USA','IRN'],['GBR','IRN'],['FRA','IRN'],['DEU','IRN'],['ISR','IRN'],
    ['USA','PRK'],['JPN','PRK'],['KOR','PRK'],['GBR','PRK'],['FRA','PRK'],['DEU','PRK'],
    ['USA','CHN','tech'],['CHN','USA','rare'],['NLD','CHN','tech'],
    ['USA','CUB'],['USA','VEN'],['GBR','BLR'],['DEU','BLR'],['POL','BLR'],['USA','BLR'],['FRA','BLR'],
  ];

  // ---- Eventi casuali ---------------------------------------------------------
  // scope: 'player' (con scelte), 'nation' (colpisce una nazione a caso), 'global'
  GEO.EVENTS = [
    { id:'elezioni', scope:'player', weight:3, cond:n=>n.regime==='democrazia', title:'Elezioni generali', text:'Il paese va alle urne. La campagna elettorale polarizza l’opinione pubblica.',
      options:[
        { label:'Campagna populista: promesse di spesa', fx:{stability:+8, debt:+6, growth:-0.3, approval:+10} },
        { label:'Campagna tecnocratica: rigore e riforme', fx:{stability:-4, debt:-4, growth:+0.4, approval:-5} },
        { label:'Campagna nazionalista: nemici esterni', fx:{stability:+5, approval:+6, relAll:-8, military:+5} },
      ]},
    { id:'scandalo', scope:'player', weight:2, title:'Scandalo di corruzione', text:'Un’inchiesta giornalistica travolge membri del governo.',
      options:[
        { label:'Insabbiare', fx:{stability:-3, approval:-2, risk:'scandalo2'} },
        { label:'Rimuovere i responsabili', fx:{stability:+2, approval:-6} },
      ]},
    { id:'cyberattack', scope:'player', weight:3, title:'Cyberattacco alle infrastrutture', text:'Un gruppo hacker sponsorizzato da uno stato ha colpito la rete elettrica.',
      options:[
        { label:'Rappresaglia cyber contro il sospettato', fx:{relSuspect:-25, cyberHit:true} },
        { label:'Investire in difese', fx:{treasury:-30, techProg:{cyber:40}} },
        { label:'Ignorare', fx:{gdpPct:-0.4, stability:-2} },
      ]},
    { id:'giacimento', scope:'player', weight:2, title:'Scoperta di un giacimento', text:'I geologi confermano un grande giacimento offshore di gas e petrolio.',
      options:[
        { label:'Sfruttamento rapido con major straniere', fx:{res:{oil:+2,gas:+2}, treasury:+60, relAll:+3} },
        { label:'Compagnia nazionale, sviluppo lento', fx:{res:{oil:+1,gas:+1}, growth:+0.3} },
      ]},
    { id:'proteste', scope:'player', weight:3, cond:n=>n.stability<55, title:'Proteste di massa', text:'Centinaia di migliaia in piazza contro il carovita.',
      options:[
        { label:'Sussidi e calmieramento dei prezzi', fx:{treasury:-50, stability:+8, debt:+3} },
        { label:'Repressione', fx:{stability:+3, approval:-10, relDem:-10} },
        { label:'Dialogo e riforme', fx:{stability:+4, growth:-0.1} },
      ]},
    { id:'pandemia', scope:'global', weight:1, title:'Nuova pandemia', text:'Un patogeno respiratorio si diffonde dai mercati asiatici. Chi ha biotecnologie avanzate soffre meno.',
      global:{ gdpPctByBio:true } },
    { id:'crisi_finanziaria', scope:'global', weight:1, title:'Crisi finanziaria globale', text:'Il fallimento di un grande istituto innesca una corsa alla liquidità. I mercati crollano.',
      global:{ marketShock:-18, gdpPct:-1.2, sector:{FIN:-30, GOLD:+15} } },
    { id:'oil_shock', scope:'global', weight:2, title:'Shock petrolifero', text:'Attacchi a infrastrutture nel Golfo fanno impennare il greggio.',
      global:{ commodity:{oil:+35, gas:+25}, sector:{ENERGY:+20} } },
    { id:'ai_breakthrough', scope:'global', weight:2, title:'Svolta nell’IA generale', text:'Un laboratorio annuncia un modello che automatizza la ricerca scientifica. La corsa tecnologica accelera.',
      global:{ sector:{TECH:+18}, techProgTop:{ai:60} } },
    { id:'clima', scope:'nation', weight:3, title:'Disastro climatico', text:'{n} è colpita da inondazioni e ondate di calore record.',
      fx:{gdpPct:-0.8, stability:-4} },
    { id:'colpo', scope:'nation', weight:1, cond:n=>n.stability<45 && n.regime!=='democrazia', title:'Colpo di stato', text:'I militari prendono il potere in {n}. Il nuovo governo è imprevedibile.',
      fx:{stability:+10, approval:-20, persona:'falco', relAll:-15} },
    { id:'rivoluzione', scope:'nation', weight:1, cond:n=>n.stability<35, title:'Rivoluzione', text:'Il regime di {n} cade sotto la pressione popolare.',
      fx:{stability:+15, gdpPct:-3, regime:'democrazia', persona:'difensivo', relDem:+20} },
    { id:'boom', scope:'nation', weight:2, title:'Boom economico', text:'Investimenti esteri record in {n}: la crescita accelera.',
      fx:{growth:+0.8, stability:+3} },
    { id:'test_missilistico', scope:'nation', weight:2, cond:n=>n.persona==='imprevedibile'||n.persona==='falco', title:'Test missilistico', text:'{n} testa un nuovo missile balistico intercontinentale sopra il mare.',
      fx:{missiles:+30, relAll:-5, sector:{DEF:+6}} },
    { id:'embargo_chip', scope:'global', weight:1, title:'Stretta sulle esportazioni di chip', text:'I produttori di semiconduttori avanzati restringono le forniture ai rivali.',
      global:{ commodity:{chips:+30}, sector:{TECH:-6} } },
    { id:'carestia', scope:'global', weight:1, title:'Cattivo raccolto globale', text:'Siccità in tre continenti: il grano vola.',
      global:{ commodity:{grain:+40}, sector:{AGRI:+15}, stabilityImporters:-4 } },
    { id:'onu_pace', scope:'global', weight:1, title:'Conferenza di pace ONU', text:'Una conferenza internazionale apre canali di dialogo: le tensioni calano ovunque.',
      global:{ relAllShift:+6 } },
    { id:'sabotaggio', scope:'player', weight:2, cond:n=>n.atWar, title:'Sabotaggio dietro le linee', text:'I servizi propongono un’operazione di sabotaggio contro il nemico.',
      options:[
        { label:'Autorizzare', fx:{enemyMissiles:-40, enemyStability:-3, risk:'esposizione'} },
        { label:'Rifiutare', fx:{} },
      ]},
    { id:'fuga_cervelli', scope:'player', weight:2, cond:n=>n.stability<50, title:'Fuga di cervelli', text:'I migliori ricercatori emigrano verso paesi più stabili.',
      options:[
        { label:'Incentivi fiscali ai ricercatori', fx:{treasury:-25, techProgAll:10} },
        { label:'Accettare la perdita', fx:{techProgAll:-25} },
      ]},
    { id:'spy_scandal', scope:'player', weight:2, title:'Rete di spie scoperta', text:'Il controspionaggio smantella una rete che faceva capo a {s}.',
      options:[
        { label:'Espellere i diplomatici', fx:{relSuspect:-20, stability:+2} },
        { label:'Usarli per disinformazione', fx:{techProg:{space:25}} },
      ]},
  ];

  // ---- Profili di bilancio IA per personalità (quote di spesa) ----------------
  GEO.AI_BUDGETS = {
    egemone:       { military:0.34, research:0.22, welfare:0.22, infra:0.14, diplomacy:0.08 },
    falco:         { military:0.45, research:0.12, welfare:0.18, infra:0.15, diplomacy:0.10 },
    paziente:      { military:0.30, research:0.30, welfare:0.15, infra:0.20, diplomacy:0.05 },
    mercante:      { military:0.15, research:0.28, welfare:0.30, infra:0.22, diplomacy:0.05 },
    opportunista:  { military:0.30, research:0.15, welfare:0.25, infra:0.20, diplomacy:0.10 },
    isolazionista: { military:0.15, research:0.15, welfare:0.40, infra:0.25, diplomacy:0.05 },
    difensivo:     { military:0.35, research:0.20, welfare:0.25, infra:0.15, diplomacy:0.05 },
    ambizioso:     { military:0.28, research:0.27, welfare:0.20, infra:0.20, diplomacy:0.05 },
    imprevedibile: { military:0.55, research:0.10, welfare:0.15, infra:0.15, diplomacy:0.05 },
  };

  // ---- Contorni dei continenti (lon,lat) per la mappa stilizzata ---------------
  GEO.CONTINENTS = {
    'Nord America': [[-168,66],[-160,70],[-140,70],[-125,73],[-110,76],[-95,78],[-80,80],[-68,80],[-62,73],[-56,62],[-55,50],[-65,44],[-72,40],[-76,35],[-81,30],[-80,25],[-83,28],[-90,29],[-97,27],[-97,20],[-92,16],[-85,12],[-78,8],[-82,8],[-88,15],[-95,16],[-105,20],[-110,24],[-114,30],[-117,32],[-122,37],[-124,42],[-124,48],[-130,54],[-140,60],[-150,60],[-160,58],[-165,62]],
    'Groenlandia': [[-55,60],[-45,60],[-40,65],[-25,70],[-20,76],[-25,82],[-45,83],[-60,82],[-70,78],[-65,72],[-55,68]],
    'Sud America': [[-80,9],[-72,12],[-62,10],[-52,4],[-50,0],[-44,-2],[-35,-6],[-37,-12],[-39,-16],[-41,-22],[-48,-27],[-52,-33],[-57,-37],[-62,-40],[-65,-46],[-68,-52],[-67,-55],[-72,-54],[-74,-48],[-74,-40],[-72,-32],[-71,-25],[-70,-18],[-76,-13],[-81,-5],[-80,0],[-78,3]],
    'Eurasia': [[-10,36],[-9,43],[-2,47],[-5,49],[2,51],[5,53],[8,55],[10,57],[8,59],[6,62],[12,65],[16,69],[25,71],[32,70],[42,67],[50,69],[60,70],[70,73],[80,72],[95,76],[110,77],[130,72],[150,71],[170,70],[180,66],[175,63],[162,60],[158,52],[150,58],[141,52],[140,46],[136,43],[130,42],[128,38],[125,35],[122,30],[120,25],[115,22],[109,19],[106,10],[104,2],[100,6],[98,10],[94,16],[91,22],[86,20],[80,15],[77,8],[74,16],[70,21],[66,25],[62,25],[57,25],[57,22],[52,24],[52,17],[44,13],[43,16],[39,20],[35,28],[34,32],[36,36],[30,36],[26,40],[22,37],[18,40],[15,38],[12,44],[8,44],[3,43],[0,40],[-2,37]],
    'Africa': [[-17,15],[-17,21],[-13,28],[-9,33],[-5,36],[2,37],[10,37],[11,34],[20,32],[25,32],[32,31],[34,28],[38,22],[43,12],[51,12],[47,5],[41,-2],[40,-10],[36,-20],[33,-27],[30,-32],[24,-35],[18,-34],[15,-28],[12,-18],[13,-10],[9,-2],[9,4],[5,6],[-4,5],[-8,5],[-13,8],[-17,11]],
    'Australia': [[114,-22],[114,-30],[116,-35],[124,-33],[132,-32],[136,-35],[140,-38],[146,-39],[150,-37],[153,-32],[153,-26],[150,-22],[146,-18],[143,-14],[142,-11],[137,-13],[136,-12],[131,-11],[127,-14],[122,-17],[117,-20]],
    'Isole Britanniche': [[-6,50],[-1,51],[2,53],[0,56],[-2,58],[-5,58],[-6,56],[-10,54],[-10,52],[-6,52]],
    'Giappone': [[130,31],[132,34],[136,35],[140,36],[142,40],[141,45],[144,44],[146,46],[142,47],[140,42],[139,38],[136,37],[133,35],[130,33]],
    'Indonesia': [[95,5],[104,-1],[106,-6],[115,-8],[125,-9],[135,-5],[141,-3],[141,-8],[132,-9],[120,-10],[108,-8],[101,-4],[95,2]],
    'Madagascar': [[44,-16],[49,-13],[50,-16],[47,-25],[44,-24],[43,-19]],
    'Taiwan': [[120,22],[121.5,25],[122,24.5],[121,22]],
    'Sri Lanka': [[80,6],[80,10],[82,8],[81,6]],
  };

  // ---- Capacità nazionali acquistabili con il tesoro (costo in % del PIL) ----
  GEO.PERKS = {
    intel:        { name:'Servizi segreti d’élite', icon:'🕵️', costPct:1.0, min:15, desc:'Spionaggio e destabilizzazione +25% successo e metà rischio di scoperta. Rivela complotti e operazioni coperte contro di te.' },
    propaganda:   { name:'Apparato di propaganda', icon:'📺', costPct:0.8, min:10, desc:'Consenso +6 a regime. Prerequisito per il controllo dei media e per i brogli.' },
    specialforces:{ name:'Forze speciali', icon:'🎖️', costPct:1.2, min:15, desc:'+12% potenza offensiva nelle invasioni, −30% perdite nei sabotaggi.' },
    guard:        { name:'Guardia pretoriana', icon:'🛡️', costPct:0.6, min:8, desc:'Immunità ai colpi di stato; lealtà delle élite +15.' },
    cybershield:  { name:'Scudo cyber nazionale', icon:'🔐', costPct:0.7, min:10, desc:'Dimezza i danni dei cyberattacchi subiti; +3 livelli di difesa cyber effettiva.' },
    navy:         { name:'Flotta d’alto mare', icon:'⚓', costPct:2.0, min:25, desc:'+20 marina; gli sbarchi anfibi perdono solo il 20% invece del 40%.' },
    culture:      { name:'Diplomazia culturale', icon:'🎭', costPct:0.5, min:8, desc:'Le relazioni con tutti migliorano di +2 a turno; proposte accettate più facilmente.' },
    centralbank:  { name:'Banca centrale indipendente', icon:'🏦', costPct:0.5, min:8, desc:'Inflazione dimezzata; crisi del debito molto meno probabili.' },
    techhub:      { name:'Polo tecnologico nazionale', icon:'🧪', costPct:1.5, min:20, desc:'+20% punti ricerca ogni turno.' },
    reserves:     { name:'Riserve strategiche', icon:'🛢️', costPct:0.8, min:10, desc:'Immunità agli shock di petrolio, gas e grano.' },
    missileshield:{ name:'Scudo antimissile a strati', icon:'🛰️', costPct:1.5, min:20, desc:'+2 livelli effettivi di difesa aerea contro missili e testate.' },
    triad:        { name:'Triade nucleare', icon:'☢️', costPct:1.5, min:20, req:n=>n.nukes>0, desc:'Secondo colpo garantito: la rappresaglia nucleare è completa anche se la capitale cade.' },
    nuclearprog:  { name:'Programma nucleare militare', icon:'⚛️', costPct:2.5, min:20, req:n=>n.nukes===0&&n.nuclearProgram===undefined&&n.tech.energy>=4, desc:'Avvia il programma: circa 8 turni per la prima bomba. Se scoperto, sanzioni e rischio di attacco preventivo.' },
    surveillance: { name:'Stato di sorveglianza', icon:'👁️', costPct:0.7, min:10, desc:'Stabilità +6, opposizione frenata; relazioni con le democrazie −10. Prerequisito per le purghe.' },
    swf:          { name:'Fondo sovrano professionale', icon:'📊', costPct:0.6, min:10, desc:'Dividendi dalle imprese di stato +50%; commissioni di borsa azzerate.' },
  };
  // ---- Progetti una tantum finanziati dal tesoro ----
  GEO.PROJECTS = {
    infra:    { name:'Grande piano infrastrutturale', icon:'🏗️', costPct:2.0, min:20, desc:'+0,5% crescita annua per 8 turni.', boost:{growth:0.5,turns:8} },
    health:   { name:'Piano sanitario nazionale', icon:'🏥', costPct:1.0, min:10, desc:'Stabilità +6, consenso +4, ripopolamento più rapido, +40 progresso Biotech.', fx:{stability:6,approval:4,techProg:{bio:40}}, boost:{popRecover:true,turns:8} },
    education:{ name:'Riforma dell’istruzione', icon:'🎓', costPct:1.2, min:12, desc:'+15% punti ricerca per 12 turni.', boost:{research:0.15,turns:12} },
    rearm:    { name:'Riarmo d’emergenza', icon:'🔫', costPct:1.5, min:15, desc:'Esercito +8, aeronautica +4, +40 missili, prontezza +10 immediatamente.', fx:{army:8,air:4,missiles:40,readiness:10} },
    housing:  { name:'Welfare straordinario', icon:'🏘️', costPct:1.0, min:10, desc:'Consenso +10, stabilità +4, inflazione +1.', fx:{approval:10,stability:4,inflation:1} },
    bailout:  { name:'Salvataggio bancario', icon:'🏦', costPct:1.5, min:15, desc:'Azzera il rischio di crisi per 8 turni, indice nazionale +10%.', fx:{indexPct:10}, boost:{nocrisis:true,turns:8} },
    rebuild:  { name:'Ricostruzione nazionale', icon:'🧱', costPct:1.5, min:15, desc:'Recupera il 30% del PIL perso rispetto al picco e accelera il ripopolamento.', special:'rebuild' },
    tighten:  { name:'Stretta monetaria', icon:'📉', costPct:0.4, min:5, desc:'Inflazione −4 punti; crescita −0,6 per 2 turni.', fx:{inflation:-4}, boost:{growth:-0.6,turns:2} },
    campaign: { name:'Campagna elettorale', icon:'🗳️', costPct:0.3, min:3, desc:'Consenso +8. Solo in democrazia, entro 4 turni dalle elezioni.', req:(n,s)=>n.regime==='democrazia'&&n.politics.nextElection-s.turn<=4, fx:{approval:8} },
    bribe:    { name:'Regalie alle élite', icon:'💎', costPct:0.5, min:5, desc:'Lealtà delle élite +15. Solo in regimi ibridi o autocratici.', req:(n)=>n.regime!=='democrazia', fx:{loyalty:15} },
    relief:   { name:'Aiuti umanitari interni', icon:'🚑', costPct:0.5, min:5, desc:'Dopo un disastro o un attacco: stabilità +5, ripopolamento immediato parziale.', fx:{stability:5}, special:'relief' },
  };
  GEO.SOE_SECTORS = ['ENERGY','TECH','DEF','AGRI','FIN'];

  GEO.EVENTS.push(
    { id:'attentato', scope:'player', weight:1, cond:n=>n.stability<50, title:'Attentato al leader', text:'Un ordigno esplode al passaggio del corteo presidenziale. {deathNote}',
      options:[
        { label:'Incolpare {s} e reagire', fx:{relSuspect:-35, stability:+4, approval:+6} },
        { label:'Appello all’unità nazionale', fx:{stability:+6, approval:+3} },
        { label:'Stato di emergenza e retate', fx:{stability:+8, approval:-4, pressFreedom:-15, relDem:-8} },
      ]},
    { id:'terrorismo', scope:'player', weight:2, cond:n=>n.stability<60, title:'Attacco terroristico', text:'Un attentato in una grande città causa centinaia di vittime.',
      options:[
        { label:'Rappresaglia militare contro i mandanti', fx:{stability:-2, approval:+5, relSuspect:-25, treasury:-15} },
        { label:'Rafforzare sicurezza interna', fx:{treasury:-25, stability:+3, pressFreedom:-5} },
        { label:'Nessuna reazione forte', fx:{stability:-6, approval:-6} },
      ]},
    { id:'migranti', scope:'player', weight:2, title:'Crisi migratoria', text:'Centinaia di migliaia di profughi dalle guerre vicine premono ai confini.',
      options:[
        { label:'Accoglienza e integrazione', fx:{treasury:-30, stability:-3, growth:+0.3, relDem:+6} },
        { label:'Chiusura delle frontiere', fx:{stability:+2, approval:+4, relDem:-8} },
      ]},
    { id:'sciopero', scope:'player', weight:2, cond:n=>n.inflation>6||n.approval<45, title:'Sciopero generale', text:'I sindacati bloccano il paese contro il carovita.',
      options:[
        { label:'Aumenti salariali', fx:{stability:+6, inflation:+2, growth:-0.2} },
        { label:'Resistere', fx:{stability:-5, approval:-5, growth:-0.4} },
      ]},
    { id:'generali', scope:'player', weight:1, cond:n=>n.regime!=='democrazia'&&n.politics.loyalty<45, title:'Malumori nelle forze armate', text:'I servizi riferiscono che un gruppo di generali discute della tua sostituzione.',
      options:[
        { label:'Purga preventiva dei vertici', fx:{loyalty:+20, army:-6, stability:-3} },
        { label:'Promozioni e privilegi', fx:{loyalty:+12, treasury:-20} },
        { label:'Ignorare', fx:{loyalty:-10} },
      ]},
    { id:'opposizione', scope:'player', weight:2, cond:n=>n.regime==='democrazia'&&n.approval<50, title:'L’opposizione cresce', text:'Un leader carismatico dell’opposizione guadagna consensi con una piattaforma populista.',
      options:[
        { label:'Confronto pubblico in TV', fx:{approval:+4, opposition:-5} },
        { label:'Dossier e fango', fx:{opposition:-12, stability:-3, pressFreedom:-8, risk:'scandalo2'} },
        { label:'Lasciar fare', fx:{opposition:+8} },
      ]},
    { id:'default_estero', scope:'global', weight:1, title:'Default sovrano di un mercato emergente', text:'Un grande paese emergente sospende i pagamenti: contagio sui mercati obbligazionari.', global:{ sector:{FIN:-12}, debtShock:+4 } },
    { id:'ondata_calore', scope:'global', weight:1, title:'Estate record', text:'Ondate di calore e incendi su tre continenti: raccolti distrutti, consumi energetici alle stelle.', global:{ commodity:{grain:+30, gas:+15}, gdpPct:-0.4 } },
  );


  // ---- Politiche nazionali: 10 ambiti, opzioni mutuamente esclusive ----
  // fx: growth (punti crescita annua), debt (deriva debito/turno), stab/appr/infl (target), popG (crescita pop %/anno),
  //     research (molt.), milEff (molt. potenza), shock (molt. shock materie prime), sanct (molt. danno sanzioni),
  //     co2 (molt. emissioni), relDem/relAut/relAll (deriva relazioni), press (deriva libertà stampa), loyalty, opposition,
  //     soe (molt. dividendi), deter (molt. deterrenza vs invasioni IA), rep (deriva reputazione), chips (accesso chip autonomo)
  GEO.POLICIES = {
    fisco: { name:'Fisco', icon:'🧾', options:{
      tasse_basse:{ name:'Tasse basse', desc:'Crescita +0,4, debito +1/turno, consenso +2, welfare meno efficace.', fx:{growth:0.4,debt:1.0,appr:2,opposition:2} },
      equilibrio:{ name:'Equilibrio fiscale', desc:'Nessun effetto particolare.', fx:{} },
      tasse_alte:{ name:'Tasse progressive alte', desc:'Crescita −0,3, debito −1,5/turno, stabilità +3, consenso −2.', fx:{growth:-0.3,debt:-1.5,stab:3,appr:-2} } } },
    commercio: { name:'Commercio', icon:'🚢', options:{
      libero_scambio:{ name:'Libero scambio', desc:'Crescita +0,4, accordi commerciali più facili, +1,3× esposizione agli shock.', fx:{growth:0.4,shock:1.3,relAll:1,trade:1} },
      protezionismo:{ name:'Protezionismo', desc:'Crescita −0,3, stabilità +2, shock ×0,6, inflazione +1, partner commerciali −.', fx:{growth:-0.3,stab:2,shock:0.6,infl:1,relAll:-1} },
      autarchia:{ name:'Autarchia', desc:'Crescita −0,8, sanzioni dimezzate, inflazione +2, chip solo se li produci.', fx:{growth:-0.8,sanct:0.5,infl:2,relAll:-2,chips:'self'} } } },
    economia: { name:'Modello economico', icon:'🏭', options:{
      mercato:{ name:'Libero mercato', desc:'Crescita +0,3, opposizione +3 (diseguaglianze), dividendi imprese di stato ×0,7.', fx:{growth:0.3,opposition:3,soe:0.7} },
      misto:{ name:'Economia mista', desc:'Equilibrio tra stato e mercato.', fx:{} },
      stato:{ name:'Economia di stato', desc:'Dividendi imprese di stato ×1,6, lealtà élite +5, crescita −0,4, ricerca ×0,95.', fx:{growth:-0.4,soe:1.6,loyalty:5,research:0.95} } } },
    immigrazione: { name:'Immigrazione', icon:'🧳', options:{
      aperta:{ name:'Frontiere aperte', desc:'Popolazione +0,3%/anno, ricerca ×1,05, stabilità −2, consenso −2.', fx:{popG:0.3,research:1.05,stab:-2,appr:-2,relDem:1} },
      selettiva:{ name:'Immigrazione selettiva', desc:'Popolazione +0,1%, ricerca ×1,03.', fx:{popG:0.1,research:1.03} },
      chiusa:{ name:'Frontiere chiuse', desc:'Popolazione −0,2%, stabilità +2, consenso +2, democrazie −1.', fx:{popG:-0.2,stab:2,appr:2,relDem:-1} } } },
    welfare: { name:'Welfare', icon:'🏥', options:{
      universale:{ name:'Welfare universale', desc:'Stabilità +4, consenso +4, debito +1/turno, crescita −0,2.', fx:{stab:4,appr:4,debt:1.0,growth:-0.2} },
      base:{ name:'Rete di sicurezza di base', desc:'Equilibrio.', fx:{} },
      minimo:{ name:'Stato minimo', desc:'Crescita +0,3, debito −1/turno, stabilità −4, opposizione +4.', fx:{growth:0.3,debt:-1.0,stab:-4,opposition:4} } } },
    energia: { name:'Energia & clima', icon:'⚡', options:{
      fossile:{ name:'Fossili a oltranza', desc:'Crescita +0,3 (+0,3 se produttore), emissioni ×1,2, UE e democrazie −1.', fx:{growth:0.3,co2:1.2,relDem:-1,fossilBonus:0.3} },
      transizione:{ name:'Transizione verde', desc:'Emissioni ×0,7, +30 progresso Energia/turno, crescita −0,2, democrazie +1.', fx:{co2:0.7,growth:-0.2,techProg:{energy:30},relDem:1} },
      nucleare:{ name:'Rinascimento nucleare', desc:'Richiede Energia ≥ 5. Emissioni ×0,5, immune a shock petrolio/gas, crescita +0,1.', req:n=>n.tech.energy>=5, fx:{co2:0.5,growth:0.1,energyShield:1} } } },
    difesa: { name:'Dottrina militare', icon:'🪖', options:{
      leva:{ name:'Leva obbligatoria', desc:'Esercito +0,8/turno fino al limite, consenso −2, costo ridotto.', fx:{armyGrow:0.8,appr:-2} },
      professionale:{ name:'Esercito professionale', desc:'Potenza militare ×1,08.', fx:{milEff:1.08} },
      neutralita:{ name:'Neutralità armata', desc:'Relazioni +2 con tutti, deterrenza ×1,2, dichiarare guerra senza casus belli costa 30 reputazione.', fx:{relAll:2,deter:1.2,warRep:-30} } } },
    esteri: { name:'Dottrina estera', icon:'🌐', options:{
      ovest:{ name:'Allineamento occidentale', desc:'Democrazie +2/turno, autocrazie −2, accesso facilitato a NATO/UE.', fx:{relDem:2,relAut:-2} },
      est:{ name:'Allineamento con BRICS/SCO', desc:'Autocrazie +2, democrazie −2.', fx:{relDem:-2,relAut:2} },
      non_allineato:{ name:'Non allineamento', desc:'Relazioni +1 con tutti, reputazione +0,5/turno.', fx:{relAll:1,rep:0.5} },
      interventismo:{ name:'Interventismo', desc:'Le guerre costano meno reputazione, alleati più inclini a intervenire, spesa militare +.', fx:{warRep:6,allyBoost:0.2,appr:-1} },
      isolazionismo:{ name:'Isolazionismo', desc:'Crescita −0,1, reputazione +1/turno, nessuna richiesta di intervento.', fx:{growth:-0.1,rep:1,noCalls:1} } } },
    nucleare: { name:'Dottrina nucleare', icon:'☢️', options:{
      no_first_use:{ name:'No first use', desc:'Relazioni +1 con tutti, reputazione +0,5; un tuo primo colpo costa doppia reputazione.', fx:{relAll:1,rep:0.5,firstStrikeRep:2} },
      deterrenza:{ name:'Deterrenza', desc:'Equilibrio.', fx:{} },
      primo_colpo:{ name:'Primo colpo', desc:'Relazioni −1/turno con tutti, deterrenza ×1,5 (se hai testate).', fx:{relAll:-1,deter:1.5} } } },
    digitale: { name:'Tecnologia', icon:'💻', options:{
      aperta:{ name:'Innovazione aperta', desc:'Ricerca ×1,10, spionaggio contro di te +15%.', fx:{research:1.10,spyVuln:0.15} },
      sovranita:{ name:'Sovranità digitale', desc:'Difesa cyber +2, ricerca ×0,95, +20 progresso Semiconduttori/turno.', fx:{research:0.95,cyberDef:2,techProg:{semis:20}} },
      regolata:{ name:'IA fortemente regolata', desc:'Stabilità +2, ricerca IA ×0,8, democrazie +1.', fx:{stab:2,aiResearch:0.8,relDem:1} } } },
    istituzioni: { name:'Istituzioni', icon:'⚖️', options:{
      diritto:{ name:'Stato di diritto', desc:'Crescita +0,2, libertà di stampa +1/turno, opposizione +2, democrazie +1.', fx:{growth:0.2,press:1,opposition:2,relDem:1} },
      ordine:{ name:'Ordine e sicurezza', desc:'Stabilità +4, libertà di stampa −1/turno, lealtà +3, democrazie −1.', fx:{stab:4,press:-1,loyalty:3,relDem:-1} },
      religione:{ name:'Religione di stato', desc:'Stabilità +3, consenso +2, ricerca ×0,95, relazioni −2 con chi ha regime diverso.', fx:{stab:3,appr:2,research:0.95,relDiff:-2} } } },
  };
  // Politiche iniziali per nazione (dedotte da regime/persona, con eccezioni)
  GEO.defaultPolicies = (n) => {
    const d = n.regime === 'democrazia';
    const pol = { fisco:'equilibrio', commercio: d ? 'libero_scambio' : 'protezionismo', economia: n.regime === 'autocrazia' ? 'stato' : 'misto', immigrazione:'selettiva', welfare: d ? 'base' : 'minimo', energia: (n.res.oil >= 6 || n.res.gas >= 6) ? 'fossile' : 'transizione', difesa:'professionale', esteri:'non_allineato', nucleare:'deterrenza', digitale:'aperta', istituzioni: d ? 'diritto' : 'ordine' };
    if (n.blocs.includes('NATO') || n.blocs.includes('EU') || n.blocs.includes('AUKUS') || (n.allies || []).includes('USA')) pol.esteri = 'ovest';
    if (n.blocs.includes('SCO') || n.blocs.includes('CSTO')) pol.esteri = 'est';
    if (n.persona === 'isolazionista') pol.esteri = n.blocs.includes('NATO') ? 'ovest' : 'isolazionismo';
    if (n.persona === 'egemone') pol.esteri = 'interventismo';
    if (['DEU','FRA','ITA','ESP','SWE','FIN','NOR','NLD','CHE','GBR','CAN','AUS','NZL','JPN','KOR'].includes(n.id)) { pol.welfare = 'universale'; pol.fisco = 'tasse_alte'; }
    if (['USA','ARE','QAT','SAU','CHL'].includes(n.id)) { pol.fisco = 'tasse_basse'; pol.economia = 'mercato'; }
    if (['FRA','CHE','SWE','FIN','KOR','JPN','ARE','HUN','CHN','RUS'].includes(n.id) && n.tech.energy >= 5) pol.energia = 'nucleare';
    if (['KOR','ISR','FIN','TUR','IRN','EGY','PRK','VNM','RUS','UKR','GRC','CHE','BRA','MEX','THA'].includes(n.id)) pol.difesa = 'leva';
    if (['CHE','FIN','SWE','AUT','NZL','IRL'].includes(n.id) && !n.blocs.includes('NATO')) pol.difesa = 'neutralita';
    if (['CHN','IND'].includes(n.id)) pol.nucleare = 'no_first_use';
    if (['RUS','PRK','PAK'].includes(n.id)) pol.nucleare = 'primo_colpo';
    if (['CHN','RUS','IRN','PRK','VNM','CUB','BLR'].includes(n.id)) pol.digitale = 'sovranita';
    if (['DEU','FRA','ITA','ESP','NLD','SWE','FIN','GRC','ROU','POL'].includes(n.id)) pol.digitale = 'regolata';
    if (['IRN','SAU','ARE','QAT','PAK','ISR','MAR','DZA','EGY','IRQ'].includes(n.id)) pol.istituzioni = 'religione';
    if (['USA','CAN','AUS','DEU','SWE','ARE','QAT','SAU'].includes(n.id)) pol.immigrazione = 'aperta';
    if (['JPN','HUN','PRK','POL','KOR'].includes(n.id)) pol.immigrazione = 'chiusa';
    if (['PRK','CUB','VEN'].includes(n.id)) pol.commercio = 'autarchia';
    if (['IND','BRA','ZAF','IDN','ARG','MEX','ETH'].includes(n.id)) pol.esteri = 'non_allineato';
    return pol;
  };

  // ---- Visioni nazionali: il futuro che scegli per il paese (cambiabile ogni 24 turni) ----
  GEO.VISIONS = {
    tech:     { name:'Superpotenza tecnologica', icon:'🧠', desc:'Ricerca ×1,15; indice nazionale +; vittoria tecnologica più vicina.', fx:{research:1.15}, goal:'Tutte le tecnologie ≥ 9' },
    fortress: { name:'Fortezza inespugnabile', icon:'🏰', desc:'Difesa aerea +1 effettivo, esercito oltre il limite (+10), stabilità +2, crescita −0,2.', fx:{defense:1,armyCap:10,stab:2,growth:-0.2}, goal:'Mai perdere una regione' },
    trade:    { name:'Impero commerciale', icon:'💱', desc:'Ogni accordo commerciale vale +0,25 crescita (invece di +0,15), dividendi ×1,3, mercanti +2/turno.', fx:{tradeBonus:0.1,soe:1.3,relMerchant:2}, goal:'Accordi commerciali con 15 nazioni' },
    green:    { name:'Potenza verde', icon:'🌱', desc:'Emissioni ×0,6, +40 progresso Energia/turno, democrazie +1, disastri climatici dimezzati, crescita −0,1.', fx:{co2:0.6,techProg:{energy:40},relDem:1,climateShield:0.5,growth:-0.1}, goal:'Energia 10 e transizione verde' },
    hegemon:  { name:'Egemonia regionale', icon:'🦅', desc:'Invasioni e ultimatum contro i vicini +15%, guerre costano metà reputazione, democrazie −1/turno.', fx:{invadeNeighbors:1.15,warRep:0.5,relDem:-1}, goal:'Controllare 6 regioni straniere' },
    beacon:   { name:'Faro della democrazia', icon:'🗽', desc:'Democrazie +2/turno, libertà di stampa +1, proiezione elettorale +5%, alleanze più facili con le democrazie.', fx:{relDem:2,press:1,election:0.05,allyDem:1}, goal:'Alleanze con 8 democrazie' },
    order:    { name:'Ordine e grandezza', icon:'👑', desc:'Stabilità +4, lealtà +5, consenso +2, libertà di stampa −1/turno, democrazie −1.', fx:{stab:4,loyalty:5,appr:2,press:-1,relDem:-1}, goal:'Stabilità ≥ 85 per 8 turni' },
  };

  GEO.EVENTS.push(
    { id:'vertice_clima', scope:'global', weight:2, title:'Vertice mondiale sul clima', text:'Le grandi potenze si impegnano a tagliare le emissioni. Chi ha scelto la transizione verde guadagna prestigio.', global:{ climatePledge:true } },
    { id:'disastro_clima', scope:'global', weight:2, cond:s=>s.climate&&s.climate.temp>1.6, title:'Catastrofe climatica', text:'Uragani, siccità e inondazioni su scala continentale: il riscaldamento presenta il conto.', global:{ gdpPct:-0.8, commodity:{grain:+25}, stabilityAll:-3 } },
    { id:'ondata_democratica', scope:'global', weight:1, title:'Ondata democratica', text:'Proteste di massa scuotono diversi regimi autoritari.', global:{ autocracyStab:-8 } },
    { id:'ondata_autoritaria', scope:'global', weight:1, title:'Ondata populista', text:'In molte democrazie avanzano forze che promettono mano forte.', global:{ democracyOpp:+10 } },
    { id:'successione', scope:'player', weight:1, cond:n=>n.regime==='autocrazia', title:'Questione della successione', text:'Le fazioni del regime chiedono chiarezza sul futuro: chi erediterà il potere?',
      options:[
        { label:'Designare un erede fidato', fx:{loyalty:+10, stability:+3} },
        { label:'Rinviare la questione', fx:{loyalty:-6} },
        { label:'Aprire a elezioni controllate', fx:{loyalty:-8, relDem:+10, pressFreedom:+10} },
      ]},
    { id:'referendum', scope:'player', weight:1, cond:n=>n.regime==='democrazia', title:'Referendum popolare', text:'Una raccolta firme impone un referendum su una grande riforma.',
      options:[
        { label:'Sostenerlo: riforma delle istituzioni', fx:{stability:+3, pressFreedom:+5, opposition:-5} },
        { label:'Osteggiarlo', fx:{approval:-4, opposition:+6} },
      ]},
  );

  GEO.DIFFICULTY = {
    facile:   { label:'Facile',   aiAggr:0.7, playerBonus:1.15, aiBonus:0.9 },
    normale:  { label:'Normale',  aiAggr:1.0, playerBonus:1.0, aiBonus:1.0 },
    difficile:{ label:'Difficile',aiAggr:1.35, playerBonus:0.9, aiBonus:1.1 },
  };

})(typeof globalThis !== 'undefined' ? globalThis : window);
