FQC(1, {
  intro: 'Scopri che cos’è davvero il denaro: da dove nasce, a cosa serve e perché un pezzo di carta in tasca vale qualcosa.',
  cards: [
    { t: 'Prima del denaro: il baratto', x: 'Scambiare una gallina con un paio di scarpe funziona solo se il calzolaio vuole proprio la tua gallina. È la “doppia coincidenza dei bisogni”, il grande limite del baratto che il denaro ha risolto.', v: { k: 'vs', a: ['Baratto', 'Devi trovare chi vuole ciò che offri'], b: ['Denaro', 'Tutti lo accettano in cambio di tutto'] } },
    { t: 'Le tre funzioni del denaro', x: 'Il denaro serve a scambiare (paghi la spesa), a misurare (confronti i prezzi con la stessa unità) e a conservare (metti da parte oggi per spendere domani).', v: { k: 'icons', d: [['🤝', 'Mezzo di scambio'], ['📏', 'Unità di conto'], ['🏺', 'Riserva di valore']] } },
    { t: 'Dalla conchiglia allo smartphone', x: 'Nel tempo il denaro è diventato più leggero e comodo: prima beni con valore proprio come sale e metalli, poi la carta, oggi soprattutto cifre registrate sui conti e pagamenti digitali.', v: { k: 'steps', s: ['Baratto', 'Moneta merce', 'Monete metalliche', 'Banconote', 'Moneta digitale'] } },
    { t: 'L’euro vale perché ci fidiamo', x: 'L’euro è moneta fiduciaria: non si può convertire in oro. Vale perché la legge lo impone come mezzo di pagamento e perché tutti si fidano che sarà accettato. In Italia ha sostituito la lira a un cambio fisso.', v: { k: 'stat', n: '1.936,27', l: 'lire per 1 euro: il cambio fisso della conversione' } },
    { t: 'Il potere d’acquisto', x: 'Il valore del denaro sta in ciò che ti permette di comprare. Se i prezzi salgono, con la stessa somma compri meno: lo vedrai bene nel livello sull’inflazione.', v: { k: 'formula', f: 'Potere d’acquisto = somma ÷ prezzo del bene', n: 'Es.: 10 € ÷ 1,25 € a caffè = 8 caffè' } },
    { t: 'Non tutto è liquido allo stesso modo', x: 'La liquidità indica quanto in fretta trasformi un bene in denaro spendibile senza perderci. Il contante lo è già; per vendere una casa possono servire mesi e magari uno sconto sul prezzo.', v: { k: 'scale', a: 'Più liquido', b: 'Meno liquido', d: [['Contante', 4], ['Conto corrente', 12], ['Auto usata', 62], ['Casa', 92]] } },
  ],
  terms: [
    ['Baratto', 'Scambio diretto di beni o servizi senza usare denaro.'],
    ['Mezzo di scambio', 'Funzione del denaro che lo rende accettato da tutti in cambio di beni e servizi.'],
    ['Unità di conto', 'Funzione del denaro che permette di esprimere e confrontare tutti i prezzi con la stessa misura.'],
    ['Riserva di valore', 'Funzione del denaro che permette di conservare ricchezza oggi per usarla in futuro.'],
    ['Moneta fiduciaria', 'Denaro senza valore intrinseco, accettato per legge e per fiducia in chi lo emette.'],
    ['Corso legale', 'Riconoscimento per legge di una moneta come mezzo di pagamento valido in un Paese.'],
    ['Potere d’acquisto', 'Quantità di beni e servizi che puoi comprare con una certa somma di denaro.'],
    ['Liquidità', 'Facilità e rapidità con cui un bene si trasforma in denaro spendibile senza perdite.'],
  ],
  tf: [
    ['Con il baratto devi trovare qualcuno che abbia ciò che vuoi e che, allo stesso tempo, voglia ciò che offri.', true, 'È la doppia coincidenza dei bisogni: un ostacolo enorme che il denaro elimina, perché tutti lo accettano.'],
    ['Le banconote in euro valgono perché la BCE custodisce una quantità equivalente di oro.', false, 'L’euro è moneta fiduciaria: non è convertibile in oro. Il suo valore poggia sulla legge e sulla fiducia di chi lo usa.'],
    ['Le banconote e le monete in euro sono entrate in circolazione il 1° gennaio 2002.', true, 'L’euro esisteva già dal 1999 per conti e bonifici; dal 2002 sono arrivati banconote e monete.'],
    ['Oggi la maggior parte del denaro esiste sotto forma di contante nei portafogli.', false, 'La gran parte del denaro è registrata sui conti bancari: è moneta “scritturale”, che si muove con carte e bonifici.'],
    ['Esprimere in euro sia il prezzo di un caffè sia quello di un’auto è un esempio di unità di conto.', true, 'Il denaro fa da metro comune: grazie a lui puoi confrontare beni diversissimi con la stessa misura.'],
    ['Tenere i risparmi sotto il materasso li protegge del tutto dalla perdita di valore.', false, 'Restano esposti a furti e smarrimenti e, se i prezzi salgono, la stessa somma compra meno cose.'],
    ['Il contante è lo strumento più liquido perché è già denaro spendibile.', true, 'Non serve venderlo né convertirlo: puoi usarlo subito per pagare.'],
    ['Una buona moneta dovrebbe deteriorarsi in fretta, così circola più velocemente.', false, 'Una buona moneta deve essere durevole, oltre che divisibile, trasportabile, difficile da falsificare e accettata.'],
    ['Il saldo del tuo conto corrente è denaro a tutti gli effetti, anche se non lo tocchi con mano.', true, 'Puoi spenderlo con carta o bonifico: svolge le stesse funzioni del contante.'],
    ['Per funzionare come moneta, un oggetto deve per forza avere un valore proprio, come l’oro.', false, 'Le monete moderne non hanno valore intrinseco: funzionano perché sono accettate da tutti e riconosciute per legge.'],
  ],
  mcq: [
    { q: 'Qual è il limite principale del baratto?', a: 'Serve una doppia coincidenza dei bisogni', w: ['Non permette di scambiare servizi', 'È vietato dalla legge italiana', 'Richiede un conto in banca'], e: 'Nel baratto entrambe le parti devono volere proprio ciò che l’altra offre: trovare la persona giusta è difficile.' },
    { q: 'Confronti il prezzo di due smartphone espresso in euro. Quale funzione del denaro stai usando?', a: 'Unità di conto', w: ['Riserva di valore', 'Mezzo di scambio', 'Corso legale'], e: 'Usi il denaro come metro comune per misurare e confrontare valori diversi.' },
    { q: 'Metti da parte 200 € oggi per spenderli fra sei mesi. Quale funzione del denaro stai usando?', a: 'Riserva di valore', w: ['Unità di conto', 'Mezzo di scambio', 'Moneta merce'], e: 'Conservare denaro per usarlo in futuro sfrutta la sua funzione di riserva di valore.' },
    { q: 'Su che cosa si basa il valore dell’euro?', a: 'Sulla fiducia e sul corso legale', w: ['Sulla convertibilità in oro', 'Sul metallo delle monete', 'Sul prezzo del petrolio'], e: 'L’euro è moneta fiduciaria: è accettato perché la legge lo riconosce e perché tutti si fidano di chi lo emette.' },
    { q: 'Quale di questi beni è il meno liquido?', a: 'Un appartamento', w: ['Una banconota da 50 €', 'Il saldo del conto corrente', 'Il credito su una carta prepagata'], e: 'Per vendere una casa servono tempo e costi, e a volte bisogna accettare un prezzo più basso.' },
    { q: 'Un caffè costa 1,25 €. Quanti caffè compri con 10 €?', a: '8', w: ['6', '10', '12'], e: '10 ÷ 1,25 = 8. Il potere d’acquisto di una somma dipende dai prezzi dei beni che vuoi comprare.' },
    { q: 'Chi ha il diritto esclusivo di autorizzare l’emissione delle banconote in euro?', a: 'La Banca centrale europea', w: ['La Commissione europea', 'Il Ministero dell’Economia', 'Le banche commerciali'], e: 'La BCE autorizza l’emissione delle banconote in euro, che vengono poi messe in circolazione dalle banche centrali nazionali.' },
    { q: 'A quale cambio fisso la lira è stata convertita in euro?', a: '1.936,27 lire per 1 euro', w: ['1.000 lire per 1 euro', '2.500 lire per 1 euro', '1.500 lire per 1 euro'], e: 'Il cambio fu fissato in modo irrevocabile: 1 euro = 1.936,27 lire. Per stime veloci molti arrotondavano a 2.000.' },
  ],
  fill: [
    { s: 'Lo scambio diretto di beni senza usare denaro si chiama ___.', a: 'baratto', w: ['credito', 'prestito', 'risparmio'] },
    { s: 'Una moneta senza valore intrinseco, accettata per fiducia e per legge, si dice ___.', a: 'fiduciaria', w: ['metallica', 'aurea', 'convertibile'] },
    { s: 'Quando conservi denaro per spenderlo più avanti, lo usi come riserva di ___.', a: 'valore', w: ['scambio', 'conto', 'credito'] },
    { s: 'La facilità con cui un bene si trasforma in contante senza perdite si chiama ___.', a: 'liquidità', w: ['solvibilità', 'redditività', 'volatilità'] },
    { s: 'Le banconote in euro sono entrate in circolazione nel ___.', a: '2002', w: ['1999', '1992', '2008'] },
  ],
  order: [
    { q: 'Ordina le tappe dell’evoluzione del denaro, dalla più antica alla più recente', i: ['Baratto', 'Moneta merce (sale, conchiglie)', 'Monete metalliche coniate', 'Banconote di carta', 'Pagamenti digitali'], e: 'Il denaro è diventato via via più pratico: dai beni con valore proprio alle monete, poi alla carta e infine ai pagamenti elettronici.' },
    { q: 'Ordina dal più liquido al meno liquido', i: ['Contante', 'Saldo del conto corrente', 'Auto usata', 'Appartamento'], e: 'Il contante si spende subito; il conto richiede carta o bonifico; un’auto si vende in giorni o settimane; una casa anche in molti mesi.' },
  ],
  cat: [
    { q: 'Mezzo di scambio o unità di conto?', g: [['Mezzo di scambio', ['Paghi la spesa al supermercato', 'Saldi il parrucchiere con la carta', 'Compri un biglietto del treno']], ['Unità di conto', ['Confronti i prezzi di due televisori', 'Leggi il prezzo al chilo delle mele', 'Stimi quanto vale la tua bici usata']]] },
    { q: 'Moneta merce o moneta fiduciaria?', g: [['Moneta merce', ['Monete d’oro', 'Sale', 'Conchiglie']], ['Moneta fiduciaria', ['Banconota da 20 €', 'Saldo del conto corrente', 'Yen giapponese']]] },
  ],
  scen: [
    { s: 'Giulia, 24 anni, vende online la sua vecchia bici a 150 €. Un acquirente propone di pagarla con una console usata invece che in denaro. A Giulia la console non interessa.', q: 'Cosa fa?', o: [
      { t: 'Chiede il pagamento in euro', ok: true, f: 'Giusto: il denaro è accettato da tutti. Con la console dovrebbe poi trovare qualcuno che la voglia, perdendo tempo e forse valore.' },
      { t: 'Accetta la console e prova a rivenderla', ok: false, f: 'È il problema del baratto: deve trovare un secondo acquirente, con il rischio di incassare meno di 150 €.' },
      { t: 'Accetta per non perdere l’affare', ok: false, f: 'Riceve qualcosa che non le serve e di valore incerto. Il denaro esiste proprio per evitare scambi così scomodi.' },
    ] },
    { s: 'Marco, 19 anni, ha ricevuto 300 € in regalo per il diploma. Vuole usarli tra un anno per un corso di fotografia. Pensa di tenerli in una busta nel cassetto della sua camera.', q: 'Qual è la scelta migliore?', o: [
      { t: 'Metterli in una busta nel cassetto', ok: false, f: 'Il contante in casa può essere perso, rubato o speso d’impulso, e non è tracciabile.' },
      { t: 'Spenderli ora in gadget da rivendere', ok: false, f: 'Gli oggetti perdono valore e non sono liquidi: tra un anno potrebbe ricavarne molto meno.' },
      { t: 'Versarli sul suo conto e non toccarli', ok: true, f: 'Il saldo sul conto è denaro a tutti gli effetti, più sicuro del contante in casa e pronto quando servirà.' },
    ] },
    { s: 'Paolo, 45 anni, deve pagare entro due giorni una riparazione dell’auto da 1.000 €. Ha 1.200 € sul conto corrente e un orologio che vale circa 2.000 €.', q: 'Come paga?', o: [
      { t: 'Vende l’orologio in fretta a 900 €', ok: false, f: 'Vendere in fretta un bene poco liquido costringe spesso ad accettare un prezzo molto più basso del suo valore.' },
      { t: 'Usa il saldo del conto corrente', ok: true, f: 'Il conto è liquido: paga subito senza perdite. L’orologio vale di più, ma trasformarlo in denaro richiede tempo.' },
      { t: 'Offre l’orologio al meccanico', ok: false, f: 'È un baratto: il meccanico potrebbe non volerlo e, se accetta, Paolo cede un bene da 2.000 € per un debito di 1.000 €.' },
    ] },
    { s: 'Luca, 22 anni, lavora in un bar. Un cliente paga con una banconota da 50 € che al tatto sembra liscia e, inclinandola, non mostra l’ologramma.', q: 'Cosa fa?', o: [
      { t: 'La accetta e la spende in fretta altrove', ok: false, f: 'Rimettere in circolazione una banconota falsa è un reato, anche se l’hai ricevuta in buona fede.' },
      { t: 'La accetta: tanto la garantisce la BCE', ok: false, f: 'Una banconota falsa non ha alcun valore e non viene rimborsata da nessuno.' },
      { t: 'La controlla e chiede un altro pagamento', ok: true, f: 'Bene: tatto, filigrana in controluce e ologramma aiutano a riconoscere i falsi. Una buona moneta deve essere difficile da falsificare.' },
    ] },
  ],
  tip: 'Il denaro è uno strumento: conta ciò che ti permette di fare. Tieni in contante solo ciò che ti serve e conserva il resto su un conto.',
});
