FQC(2, {
  intro: 'Impara a sapere quanto entra, quanto esce e dove va ogni euro: il budget è la base di ogni buona scelta finanziaria.',
  cards: [
    { t: 'Lordo e netto', x: 'Il budget si costruisce sul netto, cioè su ciò che arriva davvero sul conto. La RAL che leggi nel contratto è lorda: tasse e contributi ne trattengono una parte importante prima che arrivi a te.', v: { k: 'vs', a: ['Reddito lordo', 'Prima di tasse e contributi'], b: ['Reddito netto', 'Quello che ricevi davvero'] } },
    { t: 'La regola 50/30/20', x: 'Un punto di partenza semplice: 50% del netto per i bisogni, 30% per i desideri, 20% per il risparmio. Con 1.600 € al mese significa 800, 480 e 320 €. Puoi adattarla alla tua situazione.', v: { k: 'pie', d: [['Bisogni', 50], ['Desideri', 30], ['Risparmio', 20]] } },
    { t: 'Dove vanno i soldi', x: 'Ecco il mese tipo di chi guadagna 1.500 € netti. Le spese fisse, come l’affitto, si ripetono uguali; quelle variabili, come spesa e svago, cambiano e sono le prime su cui puoi intervenire.', v: { k: 'bars', d: [['Affitto', 600], ['Spesa', 300], ['Bollette', 110], ['Trasporti', 120], ['Svago', 190], ['Risparmio', 180]], u: '€' } },
    { t: 'Costruire un budget in 4 passi', x: 'Parti dai numeri reali, non da quelli che speri. Per un mese registra ogni uscita: scoprirai spese che non ricordavi di avere.', v: { k: 'steps', s: ['Calcola le entrate nette', 'Registra tutte le spese', 'Raggruppale per categoria', 'Fissa limiti e correggi'] } },
    { t: 'Il saldo del mese', x: 'Se il saldo è positivo hai un avanzo da destinare al risparmio. Se è negativo stai spendendo più di quanto incassi: devi correggere subito, prima che diventi debito.', v: { k: 'formula', f: 'Saldo = entrate − uscite', n: 'Es.: 1.500 € − 1.380 € = +120 €' } },
    { t: 'Le spese invisibili', x: 'Piccole spese ricorrenti sembrano innocue ma si sommano: abbonamenti dimenticati, app, consegne a domicilio. Controlla gli addebiti sul conto almeno una volta al mese.', v: { k: 'stat', n: '240 €', l: 'all’anno per 4 abbonamenti da 5 € al mese' } },
  ],
  terms: [
    ['Reddito netto', 'Somma che ricevi davvero, dopo le trattenute di tasse e contributi.'],
    ['RAL', 'Retribuzione annua lorda: lo stipendio di un anno prima di tasse e contributi.'],
    ['Budget', 'Piano che assegna in anticipo le entrate del mese a spese e risparmio.'],
    ['Spesa fissa', 'Uscita che si ripete con importo uguale o quasi, come affitto o rata.'],
    ['Spesa variabile', 'Uscita che cambia di mese in mese, come la spesa alimentare o il carburante.'],
    ['Spesa discrezionale', 'Uscita non indispensabile, legata ai desideri, che puoi rinviare o eliminare.'],
    ['Avanzo', 'Differenza positiva tra entrate e uscite di un periodo.'],
    ['Tredicesima', 'Mensilità aggiuntiva che molti lavoratori dipendenti ricevono a dicembre.'],
  ],
  tf: [
    ['Il budget va costruito sul reddito netto, non sul lordo.', true, 'Puoi spendere e risparmiare solo ciò che arriva davvero sul conto, cioè il netto.'],
    ['L’affitto è un esempio tipico di spesa variabile.', false, 'L’affitto si ripete ogni mese con lo stesso importo: è una spesa fissa.'],
    ['Fare un budget significa rinunciare a ogni divertimento.', false, 'Un buon budget prevede anche i desideri: nella regola 50/30/20 sono il 30%. Serve a scegliere, non a vietare.'],
    ['Se le uscite superano le entrate, il saldo del mese è negativo.', true, 'Saldo = entrate − uscite: se spendi più di quanto incassi, il risultato è sotto zero.'],
    ['Una spesa annuale di 240 € equivale a 20 € al mese da mettere da parte.', true, '240 ÷ 12 = 20. Dividere le spese annuali in quote mensili evita brutte sorprese.'],
    ['Con la regola 50/30/20, il 20% del reddito netto va al risparmio.', true, 'La ripartizione è 50% bisogni, 30% desideri e 20% risparmio.'],
    ['Le piccole spese quotidiane non incidono sul bilancio perché sono troppo piccole.', false, 'Un caffè da 1,20 € ogni giorno lavorativo vale circa 25 € al mese, circa 300 € l’anno: i piccoli importi si sommano.'],
    ['Il budget serve solo a chi ha un reddito basso.', false, 'Anche con redditi alti si può spendere tutto: il budget serve a chiunque voglia sapere dove vanno i soldi.'],
    ['Risparmiare solo ciò che avanza a fine mese funziona meglio che accantonare subito una quota fissa.', false, 'Di solito a fine mese non avanza nulla. Mettere da parte il risparmio appena arriva lo stipendio è molto più efficace.'],
    ['Le spese variabili sono spesso le prime su cui intervenire per risparmiare.', true, 'Le spese fisse sono legate a contratti; quelle variabili, come cene e acquisti, si possono ridurre subito.'],
  ],
  mcq: [
    { q: 'Luca guadagna 2.000 € netti al mese. Secondo la regola 50/30/20, quanto dovrebbe risparmiare?', a: '400 €', w: ['200 €', '600 €', '1.000 €'], e: 'Il 20% di 2.000 € è 400 €. Il resto si divide in 1.000 € per i bisogni e 600 € per i desideri.' },
    { q: 'Quale di queste è una spesa fissa?', a: 'La rata del mutuo', w: ['La cena al ristorante', 'Il regalo di compleanno', 'Il carburante per le gite'], e: 'La rata del mutuo è uguale ogni mese ed è prevista dal contratto; le altre cambiano di volta in volta.' },
    { q: 'Quale spesa rientra nei “desideri” della regola 50/30/20?', a: 'L’abbonamento allo streaming', w: ['La bolletta della luce', 'L’affitto di casa', 'La spesa alimentare di base'], e: 'Lo streaming è piacevole ma non indispensabile; luce, casa e cibo sono bisogni.' },
    { q: 'Che cosa indica un saldo mensile di −150 €?', a: 'Hai speso 150 € più di quanto hai incassato', w: ['Hai risparmiato 150 € nel mese', 'La banca ti deve 150 € di interessi', 'Il tuo reddito lordo è di 150 €'], e: 'Un saldo negativo significa che le uscite hanno superato le entrate: stai consumando risparmi o accumulando debiti.' },
    { q: 'Che cosa significa “paga prima te stesso”?', a: 'Risparmiare appena arriva lo stipendio', w: ['Comprarti un regalo a ogni stipendio', 'Pagare le bollette prima dell’affitto', 'Prelevare tutto lo stipendio in contanti'], e: 'Mettere da parte subito una quota, magari con un bonifico automatico, evita di spenderla durante il mese.' },
    { q: 'Qual è il primo passo per costruire un budget?', a: 'Conoscere le entrate nette del mese', w: ['Tagliare tutte le spese di svago', 'Aprire un conto in un’altra banca', 'Chiedere un aumento di stipendio'], e: 'Senza sapere quanto entra davvero non puoi decidere quanto spendere e quanto risparmiare.' },
    { q: 'Perché conviene registrare tutte le spese per almeno un mese?', a: 'Per scoprire dove vanno davvero i soldi', w: ['Perché è un obbligo di legge', 'Per ottenere un mutuo più facilmente', 'Per aumentare il reddito lordo'], e: 'Spesso la memoria inganna: i dati reali mostrano le spese nascoste e dove intervenire.' },
    { q: 'Paghi 360 € di assicurazione auto in un’unica rata annuale. Come la gestisci nel budget?', a: 'Accantoni 30 € al mese', w: ['Accantoni 3 € al mese', 'La ignori fino alla scadenza', 'Accantoni 360 € al mese'], e: '360 ÷ 12 = 30 €. Così, quando arriva la scadenza, i soldi sono già pronti.' },
  ],
  fill: [
    { s: 'Il reddito ___ è quello che ricevi davvero dopo tasse e contributi.', a: 'netto', w: ['lordo', 'fisso', 'annuo'] },
    { s: 'Nella regola 50/30/20, la metà del reddito netto va ai ___.', a: 'bisogni', w: ['desideri', 'risparmi', 'debiti'] },
    { s: 'L’affitto è una spesa ___, perché si ripete ogni mese con lo stesso importo.', a: 'fissa', w: ['variabile', 'discrezionale', 'straordinaria'] },
    { s: 'Quando le entrate superano le uscite, il mese si chiude con un ___.', a: 'avanzo', w: ['disavanzo', 'debito', 'prestito'] },
    { s: 'Il ___ è un piano che assegna in anticipo ogni euro delle entrate a spese e risparmio.', a: 'budget', w: ['bonifico', 'mutuo', 'estratto conto'] },
  ],
  order: [
    { q: 'Ordina i passi per costruire un budget', i: ['Calcola le entrate nette', 'Registra tutte le spese del mese', 'Raggruppa le spese per categoria', 'Fissa un limite per ogni categoria', 'Controlla a fine mese e correggi'], e: 'Prima i numeri reali, poi l’analisi, infine le regole e il controllo: il budget è un ciclo che si ripete ogni mese.' },
    { q: 'Ordina dalla cifra più alta alla più bassa', i: ['Stipendio lordo', 'Stipendio netto', 'Netto meno spese fisse', 'Netto meno spese fisse e risparmio'], e: 'Dal lordo si tolgono tasse e contributi; dal netto le spese fisse e la quota di risparmio. Ciò che resta è per variabili e desideri.' },
  ],
  cat: [
    { q: 'Spesa fissa o variabile?', g: [['Fissa', ['Affitto', 'Rata del finanziamento', 'Abbonamento in palestra', 'Canone internet']], ['Variabile', ['Spesa alimentare', 'Carburante', 'Cene fuori', 'Vestiti']]] },
    { q: 'Bisogno o desiderio?', g: [['Bisogno', ['Bolletta del gas', 'Farmaci', 'Abbonamento al bus per andare al lavoro']], ['Desiderio', ['Smartphone di ultima generazione', 'Weekend alle terme', 'Cena al sushi']]] },
  ],
  scen: [
    { s: 'Chiara, 26 anni, è al primo lavoro con 1.400 € netti al mese. A fine mese il conto è sempre a zero e non sa dove finiscano i soldi.', q: 'Qual è la prima cosa da fare?', o: [
      { t: 'Cercare subito un secondo lavoro', ok: false, f: 'Più entrate aiutano, ma se non sa dove vanno i soldi rischia di spendere anche quelle.' },
      { t: 'Registrare ogni spesa per un mese', ok: true, f: 'Bene: con i dati reali potrà vedere le spese nascoste e costruire un budget per categorie.' },
      { t: 'Eliminare del tutto lo svago', ok: false, f: 'Tagli drastici e senza analisi durano poco. Meglio capire prima dove intervenire.' },
    ] },
    { s: 'Davide, 34 anni, riceve un aumento di 150 € netti al mese. Ha un budget in ordine e risparmia già 200 € al mese.', q: 'Cosa fa con l’aumento?', o: [
      { t: 'Si concede tutti i 150 € in più di spese', ok: false, f: 'È l’inflazione dello stile di vita: il reddito sale, ma il risparmio resta fermo.' },
      { t: 'Prende un’auto nuova con rata da 150 €', ok: false, f: 'Vincola per anni tutto l’aumento a una spesa fissa: perde flessibilità.' },
      { t: 'Alza il risparmio di 100 € e spende il resto', ok: true, f: 'Ottimo equilibrio: aumenta subito il risparmio in automatico e si gode comunque una parte del miglioramento.' },
    ] },
    { s: 'Francesca e Matteo, 40 e 42 anni, ricevono a dicembre 1.800 € di tredicesime. A febbraio devono pagare 500 € di assicurazione auto e 250 € di bollo.', q: 'Come usano la tredicesima?', o: [
      { t: 'Mettono da parte prima le spese in arrivo', ok: true, f: 'Giusto: accantonano 750 € per le scadenze note e decidono con calma come usare gli altri 1.050 €.' },
      { t: 'La spendono tutta in regali di Natale', ok: false, f: 'A febbraio dovranno trovare 750 € dal budget del mese, magari ricorrendo a un prestito.' },
      { t: 'La lasciano sul conto senza un piano', ok: false, f: 'Senza una destinazione precisa, i soldi tendono a sparire in piccole spese.' },
    ] },
    { s: 'Simone, 22 anni, è studente lavoratore e guadagna tra 600 e 1.000 € al mese, a seconda dei turni. Vuole fare un budget.', q: 'Su quale entrata lo basa?', o: [
      { t: 'Sulla media di 800 € al mese', ok: false, f: 'Nei mesi da 600 € andrebbe in rosso: con entrate irregolari la media è troppo ottimista.' },
      { t: 'Sul mese più basso, 600 €', ok: true, f: 'Prudente: nei mesi migliori l’eccedenza va in una riserva che copre quelli più magri.' },
      { t: 'Non lo fa, le entrate sono troppo variabili', ok: false, f: 'È proprio con entrate irregolari che il budget serve di più.' },
    ] },
  ],
  tip: 'Imposta un bonifico automatico verso il risparmio il giorno dopo lo stipendio: quello che non vedi sul conto, non rischi di spenderlo.',
});
