FQC(3, {
  intro: 'Gli imprevisti arrivano sempre: scopri come costruire un cuscinetto di sicurezza che ti protegge da debiti e scelte affrettate.',
  cards: [
    { t: 'A cosa serve', x: 'È una somma messa da parte solo per imprevisti veri: spese urgenti e necessarie che non potevi prevedere. Ti evita di indebitarti o di dover vendere investimenti nel momento sbagliato.', v: { k: 'icons', d: [['🔧', 'Auto in panne'], ['🦷', 'Cure urgenti'], ['💼', 'Perdita del lavoro'], ['🔥', 'Caldaia rotta']] } },
    { t: 'Quanto deve essere grande', x: 'Si calcola sulle spese essenziali, non sullo stipendio: affitto o mutuo, bollette, cibo, trasporti, rate. Sono le uscite che devi pagare anche se smetti di guadagnare.', v: { k: 'formula', f: 'Fondo = spese essenziali mensili × mesi di copertura', n: 'Es.: 1.200 € × 4 mesi = 4.800 €' } },
    { t: 'Da 3 a 6 mesi', x: 'Con spese essenziali di 1.200 € al mese, un fondo da 3 mesi vale 3.600 € e uno da 6 mesi 7.200 €. Più il tuo reddito è incerto, più mesi conviene coprire.', v: { k: 'bars', d: [['3 mesi', 3600], ['6 mesi', 7200], ['9 mesi', 10800], ['12 mesi', 14400]], u: '€' } },
    { t: 'Chi ha bisogno di più mesi', x: 'In genere si consigliano 3-6 mesi di spese essenziali. Ne servono di più se hai entrate irregolari, figli a carico o un solo stipendio in famiglia.', v: { k: 'scale', a: 'Fondo più piccolo', b: 'Fondo più grande', d: [['Coppia, due stipendi stabili', 12], ['Single, dipendente stabile', 35], ['Famiglia monoreddito', 65], ['Autonomo, entrate irregolari', 90]] } },
    { t: 'Dove tenerlo', x: 'Il fondo deve essere sicuro e disponibile in pochi giorni: un conto separato da quello delle spese o un conto deposito non vincolato. Non serve a rendere, serve a esserci quando ti serve.', v: { k: 'vs', a: ['Adatto', 'Conto separato, sicuro, prelevabile subito'], b: ['Non adatto', 'Azioni o somme vincolate per anni'] } },
    { t: 'Un passo alla volta', x: 'Non serve avere tutto subito. Risparmiando 150 € al mese arrivi a 3.600 € in 24 mesi. Il primo traguardo può essere anche un solo mese di spese.', v: { k: 'steps', s: ['Calcola le spese essenziali', 'Fissa l’obiettivo in mesi', 'Versa una cifra fissa ogni mese', 'Usalo solo per vere emergenze', 'Ricostituiscilo dopo l’uso'] } },
  ],
  terms: [
    ['Fondo di emergenza', 'Riserva di denaro destinata solo a spese urgenti e impreviste.'],
    ['Spese essenziali', 'Uscite indispensabili per vivere: casa, cibo, bollette, trasporti e rate.'],
    ['Mesi di copertura', 'Numero di mesi di spese essenziali che la riserva riesce a pagare.'],
    ['Imprevisto', 'Evento inatteso che richiede una spesa, come un guasto, una malattia o un licenziamento.'],
    ['Spesa prevedibile', 'Uscita nota in anticipo, come il bollo auto, da pianificare nel budget.'],
    ['Conto separato', 'Conto distinto da quello quotidiano, usato per tenere la riserva lontana dalle spese.'],
    ['Conto deposito libero', 'Conto di risparmio da cui puoi ritirare i soldi in qualsiasi momento senza penali.'],
    ['Ricostituzione', 'Riportare la riserva all’importo previsto dopo averla usata.'],
  ],
  tf: [
    ['Il fondo di emergenza si calcola sulle spese essenziali mensili, non sullo stipendio.', true, 'In un’emergenza ti servono i soldi per vivere, non per mantenere tutto il tuo tenore di vita.'],
    ['Le vacanze estive sono un buon motivo per usare il fondo di emergenza.', false, 'Le vacanze sono una spesa prevedibile e desiderata: vanno finanziate con un risparmio dedicato.'],
    ['Un lavoratore autonomo con entrate irregolari di solito ha bisogno di un fondo più grande di un dipendente stabile.', true, 'Se il reddito oscilla o può fermarsi all’improvviso, servono più mesi di copertura.'],
    ['Il posto migliore per il fondo di emergenza è un investimento in azioni, perché rende di più.', false, 'Le azioni possono perdere valore proprio quando ti servono i soldi. Il fondo deve essere sicuro e disponibile.'],
    ['Dopo aver usato il fondo per un imprevisto, conviene ricostituirlo il prima possibile.', true, 'Il prossimo imprevisto può arrivare presto: riportare il fondo al livello previsto è una priorità.'],
    ['Se hai una carta di credito, il fondo di emergenza non serve.', false, 'Pagare un imprevisto a debito costa interessi e, se perdi il lavoro, il debito resta da rimborsare.'],
    ['Il bollo auto annuale è una spesa prevedibile, non un’emergenza.', true, 'Conosci importo e scadenza in anticipo: va messo nel budget, non pagato con il fondo.'],
    ['Un fondo di emergenza si può costruire solo con una grossa somma tutta insieme.', false, 'Si costruisce un po’ alla volta: anche 50 o 100 € al mese, versati con costanza, fanno crescere il cuscinetto.'],
    ['Tenere il fondo su un conto separato aiuta a non spenderlo per sbaglio.', true, 'Se è mescolato al conto delle spese, è facile intaccarlo senza accorgersene.'],
    ['Più persone in famiglia dipendono dal tuo reddito, più piccolo può essere il fondo.', false, 'È il contrario: se altri dipendono da te, un imprevisto pesa di più e serve una riserva maggiore.'],
  ],
  mcq: [
    { q: 'Elena ha spese essenziali di 1.000 € al mese e vuole coprire 6 mesi. Quanto deve accantonare?', a: '6.000 €', w: ['1.000 €', '3.000 €', '12.000 €'], e: '1.000 € × 6 mesi = 6.000 €. Il calcolo parte sempre dalle spese essenziali mensili.' },
    { q: 'Quale di queste è una vera emergenza?', a: 'La caldaia si rompe a gennaio', w: ['Iniziano i saldi di fine stagione', 'Arriva il compleanno di un amico', 'Esce un concerto imperdibile'], e: 'È urgente, necessaria e imprevista. Le altre sono spese che si possono pianificare o evitare.' },
    { q: 'Qual è la caratteristica più importante del posto in cui tieni il fondo?', a: 'Sicurezza e disponibilità rapida', w: ['Il rendimento più alto possibile', 'Un vincolo di almeno cinque anni', 'Una forte crescita nel lungo periodo'], e: 'Il fondo deve esserci, intatto, quando arriva l’imprevisto. Il rendimento viene dopo.' },
    { q: 'Perché è rischioso tenere il fondo di emergenza in azioni?', a: 'Possono valere meno proprio quando ti servono', w: ['Per legge non si possono mai vendere', 'Sono vietate ai piccoli risparmiatori', 'Non producono mai alcun guadagno'], e: 'Crisi economiche e perdita del lavoro spesso arrivano insieme ai cali di borsa: rischieresti di vendere in perdita.' },
    { q: 'Marco risparmia 200 € al mese. In quanti mesi raggiunge un fondo di 4.800 €?', a: '24 mesi', w: ['12 mesi', '20 mesi', '48 mesi'], e: '4.800 ÷ 200 = 24 mesi, cioè due anni di versamenti costanti.' },
    { q: 'Arriva una spesa imprevista di 1.500 €. Che cosa ti evita di fare il fondo di emergenza?', a: 'Ricorrere a prestiti costosi', w: ['Pagare le tasse sul reddito', 'Avere un conto corrente', 'Fare la spesa ogni settimana'], e: 'Senza riserva dovresti usare carte rateali o prestiti, pagando interessi su una spesa già pesante.' },
    { q: 'Quale dato serve per calcolare il fondo di emergenza?', a: 'Le spese essenziali di un mese', w: ['Il reddito lordo annuale', 'Il valore della propria casa', 'Il limite della carta di credito'], e: 'Il fondo si misura in mesi di spese essenziali: è quello che devi pagare anche senza entrate.' },
    { q: 'Hai usato 800 € del fondo per riparare l’auto. Che cosa fai dopo?', a: 'Lo ricostituisci con versamenti mensili', w: ['Lo chiudi, l’imprevisto è passato', 'Investi il resto in azioni', 'Lo lasci così fino al prossimo guasto'], e: 'Il fondo va riportato al livello previsto: il prossimo imprevisto non avvisa.' },
  ],
  fill: [
    { s: 'Il fondo di emergenza si misura in mesi di spese ___.', a: 'essenziali', w: ['superflue', 'discrezionali', 'fiscali'] },
    { s: 'In genere si consiglia un fondo pari a ___ mesi di spese essenziali.', a: '3-6', w: ['0-1', '24-36', '48-60'] },
    { s: 'Il fondo deve essere sicuro e facilmente ___.', a: 'disponibile', w: ['vincolato', 'tassato', 'investito'] },
    { s: 'Dopo averlo usato, il fondo va ___ con nuovi versamenti.', a: 'ricostituito', w: ['chiuso', 'investito', 'dimezzato'] },
    { s: 'Per non spenderlo per sbaglio, conviene tenere il fondo su un conto ___.', a: 'separato', w: ['cointestato', 'vincolato', 'estero'] },
  ],
  order: [
    { q: 'Ordina i passi per costruire il fondo di emergenza', i: ['Calcola le spese essenziali mensili', 'Scegli quanti mesi coprire', 'Apri un conto separato', 'Imposta un versamento automatico', 'Ricostituisci il fondo dopo ogni uso'], e: 'Prima calcoli l’obiettivo, poi prepari dove tenerlo, lo alimenti con costanza e lo ripristini quando lo usi.' },
    { q: 'A parità di spese mensili, ordina dal fondo più piccolo al più grande', i: ['Coppia con due stipendi stabili', 'Single con contratto a tempo indeterminato', 'Single con contratto a termine', 'Autonomo con entrate irregolari e figli a carico'], e: 'Più il reddito è incerto e più persone dipendono da te, più mesi di copertura servono.' },
  ],
  cat: [
    { q: 'Emergenza o spesa da pianificare nel budget?', g: [['Emergenza', ['Guasto improvviso dell’auto', 'Cure dentistiche urgenti', 'Perdita del lavoro', 'Lavatrice che si rompe']], ['Da pianificare', ['Bollo auto', 'Regali di Natale', 'Rata annuale dell’assicurazione', 'Vacanze estive']]] },
    { q: 'Adatto o non adatto al fondo di emergenza?', g: [['Adatto', ['Conto deposito libero', 'Conto di risparmio separato', 'Conto corrente']], ['Non adatto', ['Azioni di una singola società', 'Deposito vincolato per 5 anni', 'Criptovalute']]] },
  ],
  scen: [
    { s: 'Sofia, 29 anni, ha messo da parte un fondo di emergenza di 4.000 €. Un’amica la invita a un viaggio in Giappone che costa 2.500 €, tra un anno.', q: 'Come lo finanzia?', o: [
      { t: 'Usa il fondo e lo ricostituisce dopo', ok: false, f: 'Per un anno resterebbe quasi scoperta: un viaggio non è un’emergenza.' },
      { t: 'Apre un risparmio dedicato al viaggio', ok: true, f: 'Giusto: 2.500 € in 12 mesi sono circa 210 € al mese, senza toccare la sua rete di sicurezza.' },
      { t: 'Lo paga con un finanziamento a rate', ok: false, f: 'Pagherebbe interessi su una vacanza. Avendo un anno di tempo, può risparmiare prima.' },
    ] },
    { s: 'Giorgio, 45 anni, è un artigiano con entrate molto variabili. Le sue spese essenziali sono 2.000 € al mese e ha un fondo di 6.000 €.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Investire il fondo in borsa per farlo crescere', ok: false, f: 'Esporrebbe il fondo a cali proprio quando gli potrebbe servire.' },
      { t: 'Considerarlo sufficiente: 3 mesi bastano', ok: false, f: 'Per un dipendente stabile forse sì, ma con entrate irregolari 3 mesi sono pochi.' },
      { t: 'Aumentarlo gradualmente verso 6-12 mesi', ok: true, f: 'Bene: con un reddito incerto servono più mesi di copertura per affrontare i periodi senza lavoro.' },
    ] },
    { s: 'Valentina, 33 anni, deve riparare l’auto che le serve per il lavoro: 900 €. Ha 5.000 € nel fondo di emergenza e una carta revolving con un tasso alto.', q: 'Come paga?', o: [
      { t: 'Con il fondo, poi versa 150 € al mese', ok: true, f: 'È esattamente lo scopo del fondo. In sei mesi lo riporta al livello di partenza.' },
      { t: 'Con la carta revolving, a piccole rate', ok: false, f: 'Pagherebbe interessi elevati pur avendo i soldi disponibili.' },
      { t: 'Rimanda la riparazione per non toccare il fondo', ok: false, f: 'Senza auto rischia problemi sul lavoro: il fondo esiste proprio per questo.' },
    ] },
    { s: 'Lorenzo, 25 anni, ha appena iniziato a lavorare: 1.300 € netti, 900 € di spese essenziali e nessun risparmio. Vuole investire subito 200 € al mese in borsa.', q: 'Qual è la scelta più prudente?', o: [
      { t: 'Investire subito tutti i 200 € al mese', ok: false, f: 'Al primo imprevisto dovrebbe vendere, magari in perdita, o indebitarsi.' },
      { t: 'Tenere tutto in contanti in casa', ok: false, f: 'Il contante in casa è esposto a furti e tentazioni: meglio un conto separato.' },
      { t: 'Costruire prima un fondo di qualche mese', ok: true, f: 'Prima la rete di sicurezza, poi gli investimenti: anche solo 3 mesi di spese, cioè 2.700 €, lo proteggono.' },
    ] },
  ],
  tip: 'Inizia anche con poco, per esempio 50 € al mese su un conto separato. Il primo traguardo è un mese di spese essenziali: poi punta a tre e oltre.',
});
