FQC(4, {
  intro: 'Scopri come si calcola il compenso per chi presta denaro: capitale, tasso e tempo in una formula semplicissima.',
  cards: [
    { t: 'Il prezzo del denaro', x: 'L’interesse è il compenso per chi presta denaro e il costo per chi lo prende in prestito. Si esprime come tasso percentuale annuo calcolato sul capitale.', v: { k: 'vs', a: ['Chi presta', 'Riceve interessi: è un guadagno'], b: ['Chi prende in prestito', 'Paga interessi: è un costo'] } },
    { t: 'La formula', x: 'Moltiplichi capitale, tasso in forma decimale e durata in anni. Il 3% diventa 0,03: 1.000 × 0,03 × 4 = 120 €.', v: { k: 'formula', f: 'Interesse = Capitale × tasso × tempo', n: 'Es.: 1.000 € × 3% × 4 anni = 120 €' } },
    { t: 'Il montante', x: 'Il montante è capitale più interessi: M = C + I. Nell’interesse semplice gli interessi maturati non vengono aggiunti al capitale e quindi non producono altri interessi.', v: { k: 'stat', n: '1.120 €', l: 'montante di 1.000 € al 3% semplice dopo 4 anni' } },
    { t: 'Crescita in linea retta', x: 'Ogni anno si aggiungono sempre 30 €, perché il tasso si applica solo al capitale iniziale di 1.000 €. Il montante cresce come una linea retta.', v: { k: 'bars', d: [['Anno 0', 1000], ['Anno 1', 1030], ['Anno 2', 1060], ['Anno 3', 1090], ['Anno 4', 1120]], u: '€' } },
    { t: 'Periodi più brevi di un anno', x: 'Se il tasso è annuo, la durata va espressa in anni: 6 mesi sono 0,5 e 3 mesi 0,25. Esempio: 2.000 € al 6% per 6 mesi danno 2.000 × 0,06 × 0,5 = 60 €.', v: { k: 'steps', s: ['Trasforma il tasso in decimale', 'Esprimi la durata in anni', 'Calcola C × r × t', 'Somma al capitale'] } },
    { t: 'Lordo e netto', x: 'In Italia sugli interessi di conti correnti e depositi si applica una ritenuta del 26%: su 100 € di interessi lordi ne incassi 74 netti.', v: { k: 'pie', d: [['Interessi netti', 74], ['Ritenuta del 26%', 26]] } },
  ],
  terms: [
    ['Capitale', 'Somma iniziale prestata o depositata, su cui si calcolano gli interessi.'],
    ['Interesse', 'Compenso pagato per usare denaro altrui per un certo periodo.'],
    ['Tasso di interesse', 'Percentuale annua del capitale che indica quanto rende o costa un prestito.'],
    ['Montante', 'Somma finale data dal capitale più gli interessi maturati.'],
    ['Interesse semplice', 'Regime in cui gli interessi si calcolano sempre e solo sul capitale iniziale.'],
    ['Durata', 'Periodo, in anni o frazioni di anno, per cui il capitale resta impiegato.'],
    ['Interesse lordo', 'Importo degli interessi prima delle imposte.'],
    ['Ritenuta fiscale', 'Imposta trattenuta direttamente dalla banca sugli interessi: in Italia è del 26%.'],
  ],
  tf: [
    ['Nell’interesse semplice gli interessi maturati non producono altri interessi.', true, 'Gli interessi si calcolano sempre sul capitale iniziale, mai sugli interessi già maturati.'],
    ['1.000 € al 5% di interesse semplice per 2 anni producono 100 € di interessi.', true, '1.000 × 0,05 × 2 = 100 €.'],
    ['Con l’interesse semplice gli interessi annui sono ogni anno più alti.', false, 'Sono uguali ogni anno, perché il tasso si applica sempre allo stesso capitale iniziale.'],
    ['Un tasso del 4% annuo applicato per 6 mesi produce interessi pari al 2% del capitale.', true, '4% × 0,5 anni = 2%. Metà anno, metà interessi.'],
    ['Il montante è l’importo degli interessi al netto delle tasse.', false, 'Il montante è la somma di capitale e interessi.'],
    ['Per chi prende denaro in prestito, l’interesse è un costo.', true, 'Chi riceve il prestito paga gli interessi; chi presta li incassa.'],
    ['Con l’interesse semplice, raddoppiando la durata raddoppiano anche gli interessi.', true, 'Gli interessi sono proporzionali al tempo: 2 anni ne producono il doppio di 1 anno.'],
    ['Un tasso del 3% si scrive 0,3 in forma decimale.', false, 'Il 3% è 3 su 100, cioè 0,03. Scrivere 0,3 significherebbe il 30%: un errore comune.'],
    ['In Italia gli interessi di un conto deposito sono esenti da imposte.', false, 'Sugli interessi di conti correnti e depositi si paga una ritenuta del 26%.'],
    ['Con un tasso annuo, una durata di 3 mesi va inserita nella formula come 3.', false, 'Va espressa in anni: 3 mesi = 3/12 = 0,25. Usare 3 moltiplicherebbe per 12 gli interessi.'],
  ],
  mcq: [
    { q: 'Quanto rendono 2.000 € al 3% di interesse semplice in 1 anno?', a: '60 €', w: ['6 €', '600 €', '30 €'], e: '2.000 × 0,03 × 1 = 60 €.' },
    { q: 'Qual è il montante di 5.000 € al 2% di interesse semplice dopo 3 anni?', a: '5.300 €', w: ['5.100 €', '5.030 €', '6.000 €'], e: 'Interessi: 5.000 × 0,02 × 3 = 300 €. Montante: 5.000 + 300 = 5.300 €.' },
    { q: 'Che cosa rappresenta la t nella formula I = C × r × t?', a: 'La durata espressa in anni', w: ['Il tasso in percentuale', 'Le tasse sugli interessi', 'Il totale finale'], e: 'La t è il tempo, espresso nella stessa unità del tasso: se il tasso è annuo, in anni.' },
    { q: 'Depositi 1.200 € al 5% annuo di interesse semplice per 4 mesi. Quanto maturi?', a: '20 €', w: ['60 €', '240 €', '5 €'], e: '4 mesi = 4/12 di anno. 1.200 × 0,05 × 4/12 = 20 €.' },
    { q: 'Un prestito di 1.000 € costa 80 € di interessi semplici in 2 anni. Qual è il tasso annuo?', a: '4%', w: ['8%', '2%', '16%'], e: 'Tasso = I ÷ (C × t) = 80 ÷ (1.000 × 2) = 0,04, cioè il 4% annuo.' },
    { q: 'Hai 200 € di interessi lordi su un deposito. Quanto ti resta dopo la ritenuta del 26%?', a: '148 €', w: ['174 €', '200 €', '126 €'], e: 'La ritenuta è 200 × 0,26 = 52 €. Restano 200 − 52 = 148 €.' },
    { q: 'Che forma ha il grafico del montante con l’interesse semplice?', a: 'Una linea retta in salita', w: ['Una curva sempre più ripida', 'Una linea orizzontale', 'Una curva in discesa'], e: 'Ogni anno si aggiunge lo stesso importo: la crescita è lineare.' },
    { q: 'Quale di questi è un errore comune nei calcoli con l’interesse semplice?', a: 'Usare 5 invece di 0,05 per il 5%', w: ['Moltiplicare il capitale per il tasso', 'Esprimere i mesi come frazione d’anno', 'Sommare capitale e interessi'], e: 'Il tasso va in forma decimale: 5% = 0,05. Usare 5 gonfia il risultato di 100 volte.' },
  ],
  fill: [
    { s: 'Nell’interesse semplice gli interessi si calcolano solo sul ___ iniziale.', a: 'capitale', w: ['montante', 'tasso', 'reddito'] },
    { s: 'La somma di capitale e interessi si chiama ___.', a: 'montante', w: ['ritenuta', 'cedola', 'commissione'] },
    { s: 'Con un tasso annuo, 9 mesi corrispondono a ___ anni nella formula.', a: '0,75', w: ['9', '0,9', '0,25'] },
    { s: 'Per chi presta denaro, l’interesse è un ___.', a: 'guadagno', w: ['costo', 'debito', 'rimborso'] },
    { s: 'In Italia sugli interessi di conti e depositi bancari si paga una ritenuta del ___.', a: '26%', w: ['12,5%', '0,2%', '50%'] },
  ],
  order: [
    { q: 'Ordina i passi per calcolare il montante con l’interesse semplice', i: ['Trasforma il tasso in decimale', 'Esprimi la durata in anni', 'Calcola C × r × t', 'Somma gli interessi al capitale'], e: 'Prima prepari i dati nel formato giusto, poi calcoli gli interessi e infine li aggiungi al capitale.' },
    { q: 'Ordina dagli interessi più bassi ai più alti (interesse semplice)', i: ['1.000 € al 2% per 1 anno', '1.000 € al 3% per 1 anno', '1.000 € al 2% per 2 anni', '2.000 € al 3% per 1 anno', '1.000 € al 4% per 2 anni'], e: 'Gli interessi sono 20, 30, 40, 60 e 80 €: contano insieme capitale, tasso e durata.' },
  ],
  cat: [
    { q: 'Per chi l’interesse è un guadagno e per chi un costo?', g: [['Guadagno', ['Chi ha un conto deposito', 'Chi presta denaro con interessi', 'Chi possiede un buono fruttifero']], ['Costo', ['Chi ha un prestito per l’auto', 'Chi usa una carta revolving', 'Chi paga un mutuo']]] },
    { q: 'Scritto correttamente o no nella formula, con tasso annuo?', g: [['Corretto', ['5% → 0,05', '6 mesi → 0,5', '18 mesi → 1,5']], ['Errato', ['5% → 5', '6 mesi → 6', '3 mesi → 0,3']]] },
  ],
  scen: [
    { s: 'Alice, 31 anni, vuole depositare 5.000 € per 2 anni. Offerta A: 3% annuo di interesse semplice. Offerta B: bonus fisso di 150 € più l’1% annuo semplice.', q: 'Quale sceglie?', o: [
      { t: 'L’offerta B, grazie al bonus', ok: false, f: 'B dà 150 + 5.000 × 0,01 × 2 = 250 €. Il bonus attira, ma rende meno.' },
      { t: 'L’offerta A', ok: true, f: 'A dà 5.000 × 0,03 × 2 = 300 € contro i 250 € di B. Trasformare tutto in euro rende il confronto chiaro.' },
      { t: 'Sono equivalenti', ok: false, f: 'Basta fare il calcolo: 300 € contro 250 €, la differenza c’è.' },
    ] },
    { s: 'Riccardo, 50 anni, ha 10.000 € da depositare per un anno. Una banca pubblicizza “6%!”, ma solo per i primi 3 mesi, poi l’1%. Un’altra offre il 3% per tutto l’anno.', q: 'Cosa sceglie?', o: [
      { t: 'Il 6% promozionale', ok: false, f: '6% per 0,25 anni = 150 €, più 1% per 0,75 anni = 75 €: totale 225 €, meno del 3% annuo.' },
      { t: 'Il 3% per tutto l’anno', ok: true, f: '10.000 × 0,03 = 300 € contro 225 €. Le promozioni vanno sempre calcolate sull’intero periodo.' },
      { t: 'Divide a metà tra le due banche', ok: false, f: 'Otterrebbe una via di mezzo: 262,50 €. Meglio scegliere l’offerta che rende di più.' },
    ] },
    { s: 'Martina, 23 anni, calcola gli interessi su 2.000 € al 4% annuo per 3 mesi. Scrive 2.000 × 0,04 × 3 e ottiene 240 €. È entusiasta.', q: 'Che cosa dovrebbe fare?', o: [
      { t: 'Ricalcolare con la durata in anni', ok: true, f: '3 mesi = 0,25 anni: 2.000 × 0,04 × 0,25 = 20 €. Con un tasso annuo, il tempo va in anni.' },
      { t: 'Fidarsi: la formula è quella giusta', ok: false, f: 'La formula è giusta, ma i dati no: ha usato 3 mesi come se fossero 3 anni.' },
      { t: 'Dividere il risultato per 3', ok: false, f: 'Otterrebbe 80 €, ancora sbagliato. Deve esprimere la durata come 3/12 di anno.' },
    ] },
    { s: 'Nicola, 27 anni, ha bisogno di 1.000 € per un anno. Lo zio chiede il 5% annuo. Una società propone “solo 10 € al mese di interessi” per 12 mesi.', q: 'Quale proposta conviene?', o: [
      { t: 'La società: 10 € al mese sono pochi', ok: false, f: '10 € × 12 = 120 € di interessi, cioè il 12% annuo su 1.000 €: più del doppio rispetto allo zio.' },
      { t: 'Lo zio, al 5% annuo', ok: true, f: '1.000 × 0,05 = 50 € contro 120 €. Riportare i costi mensili su base annua svela il vero prezzo.' },
      { t: 'Sono simili, conta solo la rata', ok: false, f: 'La rata piccola inganna: conta il costo totale, 120 € contro 50 €.' },
    ] },
  ],
  tip: 'Prima di confrontare due offerte trasformale in euro di interessi sullo stesso periodo: è il modo più rapido per capire quale conviene davvero.',
});
