FQC(5, {
  intro: 'Scopri l’effetto palla di neve: quando gli interessi producono altri interessi, il tempo diventa il tuo miglior alleato.',
  cards: [
    { t: 'Interessi sugli interessi', x: 'Con l’interesse composto gli interessi maturati si aggiungono al capitale e, dall’anno dopo, producono a loro volta interessi. La base di calcolo cresce ogni anno: è l’effetto palla di neve.', v: { k: 'steps', s: ['Anno 1: 1.000 € → 1.050 €', 'Anno 2: 5% su 1.050 €', 'Anno 3: 5% su 1.102,50 €', 'La base cresce ogni anno'] } },
    { t: 'La formula', x: 'Moltiplichi il capitale per (1 + tasso) tante volte quanti sono gli anni. Al 5% per 2 anni: 1.000 × 1,05 × 1,05 = 1.102,50 €.', v: { k: 'formula', f: 'Montante = Capitale × (1 + tasso)^anni', n: 'Es.: 1.000 € × 1,05² = 1.102,50 €' } },
    { t: 'Semplice contro composto', x: '1.000 € al 5% annuo: dopo 10 anni la differenza è di circa 130 €, dopo 30 anni supera i 1.800 €. All’inizio le due strade quasi coincidono, poi il composto prende il largo.', v: { k: 'bars', d: [['Semplice, 10 anni', 1500], ['Composto, 10 anni', 1629], ['Semplice, 30 anni', 2500], ['Composto, 30 anni', 4322]], u: '€' } },
    { t: 'La regola del 72', x: 'Dividi 72 per il tasso annuo e ottieni, circa, in quanti anni il capitale raddoppia. Al 6% servono circa 12 anni, al 3% circa 24. È una stima veloce, non un calcolo esatto.', v: { k: 'stat', n: '72 ÷ tasso', l: 'anni necessari, circa, per raddoppiare il capitale' } },
    { t: 'Il tempo è l’ingrediente segreto', x: 'Stesso capitale, stesso tasso ipotetico del 6% annuo costante: dieci anni in più di capitalizzazione portano quasi l’80% in più alla stessa età di arrivo, 65 anni.', v: { k: 'vs', a: ['Inizia a 25 anni', '10.000 € diventano circa 102.900 €'], b: ['Inizia a 35 anni', '10.000 € diventano circa 57.400 €'] } },
    { t: 'Più spesso si capitalizza, più cresce', x: 'Se gli interessi si aggiungono al capitale ogni mese invece che ogni anno, iniziano prima a produrre altri interessi. Per questo il tasso effettivo annuo supera di poco quello nominale: il 3% capitalizzato ogni mese rende circa il 3,04%.', v: { k: 'icons', d: [['📅', 'Annuale'], ['🗓️', 'Trimestrale'], ['📆', 'Mensile']] } },
  ],
  terms: [
    ['Interesse composto', 'Regime in cui gli interessi maturati si sommano al capitale e producono altri interessi.'],
    ['Capitalizzazione', 'Momento in cui gli interessi maturati vengono aggiunti al capitale.'],
    ['Regola del 72', 'Stima rapida degli anni necessari per raddoppiare un capitale: 72 diviso il tasso.'],
    ['Crescita esponenziale', 'Aumento in cui l’incremento di ogni periodo è più grande di quello precedente.'],
    ['Fattore di capitalizzazione', '(1 + tasso) elevato al numero di anni: moltiplicato per il capitale dà il montante.'],
    ['Frequenza di capitalizzazione', 'Ogni quanto gli interessi vengono aggiunti al capitale: ogni anno, trimestre o mese.'],
    ['Tasso effettivo annuo', 'Rendimento annuo che tiene conto degli interessi aggiunti al capitale durante l’anno.'],
    ['Reinvestimento', 'Uso dei guadagni ottenuti per aumentare il capitale investito, invece di spenderli.'],
  ],
  tf: [
    ['Con l’interesse composto anche gli interessi già maturati producono interessi.', true, 'È la differenza chiave rispetto all’interesse semplice: la base di calcolo cresce ogni anno.'],
    ['Con l’interesse composto, 1.000 € al 10% annuo diventano 1.210 € dopo 2 anni.', true, '1.000 × 1,10 = 1.100 il primo anno; 1.100 × 1,10 = 1.210 il secondo.'],
    ['Secondo la regola del 72, al 9% annuo un capitale raddoppia in circa 8 anni.', true, '72 ÷ 9 = 8. Il calcolo esatto dà poco più di 8 anni: la regola è una buona approssimazione.'],
    ['Su un solo anno, con capitalizzazione annuale, interesse semplice e composto danno lo stesso risultato.', true, 'Nel primo anno gli interessi si calcolano in entrambi i casi sul capitale iniziale: la differenza nasce dal secondo anno.'],
    ['Nel lungo periodo l’interesse composto conta poco: conta solo quanto capitale versi.', false, 'Su molti anni la parte dovuta agli interessi sugli interessi può superare il capitale versato.'],
    ['Con l’interesse composto il capitale cresce ogni anno della stessa cifra.', false, 'Cresce ogni anno di una cifra maggiore, perché il tasso si applica a una base sempre più grande.'],
    ['Iniziare a risparmiare 10 anni prima cambia poco il risultato finale.', false, 'Dieci anni in più di capitalizzazione possono quasi raddoppiare il risultato: il tempo è decisivo.'],
    ['A parità di tasso nominale, capitalizzare ogni mese invece che ogni anno dà un risultato leggermente più alto.', true, 'Gli interessi iniziano prima a produrre altri interessi: il 3% mensilizzato diventa circa il 3,04% effettivo.'],
    ['La regola del 72 indica il numero esatto di anni necessari per raddoppiare.', false, 'È un’approssimazione, utile per tassi tra circa il 2% e il 12%.'],
    ['Se ritiri e spendi gli interessi ogni anno, ottieni comunque l’effetto composto.', false, 'Se gli interessi escono, non si sommano al capitale: la crescita torna a essere come quella semplice.'],
  ],
  mcq: [
    { q: 'Quanto diventano 1.000 € al 5% di interesse composto dopo 2 anni?', a: '1.102,50 €', w: ['1.100,00 €', '1.105,00 €', '1.050,00 €'], e: '1.000 × 1,05 = 1.050; 1.050 × 1,05 = 1.102,50 €. I 2,50 € in più sono interessi sugli interessi.' },
    { q: 'Secondo la regola del 72, in quanti anni circa raddoppia un capitale al 4% annuo?', a: '18 anni', w: ['12 anni', '25 anni', '7 anni'], e: '72 ÷ 4 = 18 anni.' },
    { q: 'Quale fattore, a parità di tasso, rende più grande l’effetto dell’interesse composto?', a: 'Il tempo lasciato a crescere', w: ['Il numero di conti aperti', 'La filiale della banca scelta', 'Il giorno del primo versamento'], e: 'Più anni passano, più interessi si accumulano sugli interessi: la crescita accelera.' },
    { q: 'Che cosa succede quando gli interessi vengono capitalizzati?', a: 'Si sommano al capitale', w: ['Vengono tassati due volte', 'Vengono restituiti alla banca', 'Azzerano il tasso futuro'], e: 'Diventano parte del capitale e, dal periodo successivo, producono anche loro interessi.' },
    { q: 'Un capitale raddoppia in 12 anni. Che tasso annuo indica, circa, la regola del 72?', a: '6%', w: ['12%', '8%', '3%'], e: '72 ÷ 12 = 6. La regola funziona in entrambe le direzioni: anni da tasso, tasso da anni.' },
    { q: 'Che forma ha nel tempo il grafico del montante con l’interesse composto?', a: 'Una curva sempre più ripida', w: ['Una linea retta', 'Una linea orizzontale', 'Una curva che si appiattisce'], e: 'Ogni anno si aggiunge un importo maggiore del precedente: la crescita è esponenziale.' },
    { q: 'Anna investe 10.000 € dai 25 ai 65 anni, Bruno dai 35 ai 65, entrambi a un ipotetico 6% annuo costante. Chi ottiene di più?', a: 'Anna, quasi l’80% in più', w: ['Ottengono la stessa somma', 'Anna, ma solo il 10% in più', 'Bruno, grazie a meno anni di rischio'], e: 'Anna arriva a circa 102.900 €, Bruno a circa 57.400 €: dieci anni in più fanno una grande differenza.' },
    { q: 'Perché spendere ogni anno gli interessi rallenta la crescita del capitale?', a: 'Non producono più altri interessi', w: ['La banca applica una penale', 'Il tasso annuo si azzera', 'Il capitale iniziale si riduce'], e: 'Senza reinvestimento la base resta ferma al capitale iniziale e l’effetto palla di neve si spegne.' },
  ],
  fill: [
    { s: 'Con l’interesse ___ gli interessi maturati producono altri interessi.', a: 'composto', w: ['semplice', 'fisso', 'lordo'] },
    { s: 'Secondo la regola del ___, al 6% annuo un capitale raddoppia in circa 12 anni.', a: '72', w: ['100', '50', '12'] },
    { s: 'L’aggiunta degli interessi maturati al capitale si chiama ___.', a: 'capitalizzazione', w: ['liquidazione', 'svalutazione', 'ritenuta'] },
    { s: 'L’interesse composto produce una crescita ___, sempre più veloce nel tempo.', a: 'esponenziale', w: ['lineare', 'costante', 'decrescente'] },
    { s: 'Con l’interesse composto, 1.000 € al 10% annuo diventano ___ € dopo 2 anni.', a: '1.210', w: ['1.200', '1.100', '1.020'] },
  ],
  order: [
    { q: 'Partendo da 1.000 € per 10 anni, ordina dal montante più basso al più alto', i: ['2% semplice', '2% composto', '5% semplice', '5% composto', '8% composto'], e: 'I montanti sono circa 1.200, 1.219, 1.500, 1.629 e 2.159 €: a parità di tasso il composto vince, e il tasso conta molto.' },
    { q: 'Con la regola del 72, ordina dal tempo di raddoppio più lungo al più breve', i: ['2% annuo', '3% annuo', '6% annuo', '9% annuo', '12% annuo'], e: '72 ÷ tasso: circa 36, 24, 12, 8 e 6 anni. Più alto è il tasso, prima raddoppi.' },
  ],
  cat: [
    { q: 'Interesse semplice o composto?', g: [['Semplice', ['Interessi sempre sul capitale iniziale', 'Crescita in linea retta', 'Interessi uguali ogni anno']], ['Composto', ['Interessi che producono interessi', 'Crescita a curva sempre più ripida', 'Interessi più alti ogni anno']]] },
    { q: 'Rafforza o indebolisce l’effetto composto?', g: [['Rafforza', ['Iniziare presto', 'Reinvestire gli interessi', 'Capitalizzazione più frequente', 'Tasso più alto']], ['Indebolisce', ['Ritirare gli interessi ogni anno', 'Costi annui elevati', 'Rimandare l’inizio', 'Prelievi frequenti dal capitale']]] },
  ],
  scen: [
    { s: 'Federica, 22 anni, al primo lavoro potrebbe mettere da parte 100 € al mese. Pensa però di aspettare i 30 anni, quando guadagnerà di più, per iniziare con 200 €.', q: 'Cosa le consigli?', o: [
      { t: 'Aspettare: 200 € al mese sono il doppio', ok: false, f: 'Rinuncia a 8 anni di capitalizzazione: il tempo perso è difficile da recuperare anche versando di più.' },
      { t: 'Iniziare ora, anche con soli 100 €', ok: true, f: 'Giusto: i primi versamenti avranno più anni per crescere. Potrà sempre aumentare la cifra quando guadagnerà di più.' },
      { t: 'Risparmiare ora, ma in contanti a casa', ok: false, f: 'Il contante in casa non produce interessi: niente effetto composto.' },
    ] },
    { s: 'Stefano, 41 anni, confronta due conti deposito identici, entrambi al 3% annuo nominale. Il conto A capitalizza gli interessi una volta l’anno, il conto B ogni mese.', q: 'Quale sceglie?', o: [
      { t: 'Il conto A', ok: false, f: 'Con capitalizzazione annuale gli interessi restano fermi fino a fine anno: rende un po’ meno.' },
      { t: 'Sono identici', ok: false, f: 'Il tasso nominale è lo stesso, ma la frequenza di capitalizzazione cambia il risultato.' },
      { t: 'Il conto B', ok: true, f: 'Gli interessi mensili producono subito altri interessi: circa il 3,04% effettivo contro il 3%. Piccola differenza, ma a suo favore.' },
    ] },
    { s: 'Giacomo, 38 anni, ha un investimento che gli paga gli interessi ogni anno. Li spende sempre in cene e regali. Il suo obiettivo è far crescere il capitale per la pensione.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Reinvestire gli interessi', ok: true, f: 'Solo così gli interessi si sommano al capitale e producono altri interessi: coerente con il suo obiettivo.' },
      { t: 'Continuare a spenderli', ok: false, f: 'Il capitale resta fermo: rinuncia all’effetto composto proprio sull’orizzonte lungo della pensione.' },
      { t: 'Ritirare anche parte del capitale', ok: false, f: 'Ridurrebbe la base che produce interessi: va nella direzione opposta al suo obiettivo.' },
    ] },
    { s: 'Irene, 55 anni, incontra un venditore che le promette: “Con il nostro prodotto raddoppi il capitale in 3 anni, senza rischi”.', q: 'Come reagisce?', o: [
      { t: 'Investe subito, l’offerta è a tempo', ok: false, f: 'La fretta è un classico segnale di pressione commerciale. Prima si verifica, poi si decide.' },
      { t: 'Fa due conti e diffida', ok: true, f: '72 ÷ 3 = 24% l’anno: un rendimento così alto “senza rischi” non è credibile. Meglio verificare chi lo propone e se è autorizzato.' },
      { t: 'Investe solo metà per prudenza', ok: false, f: 'Se la promessa non è credibile, il problema resta anche con metà del capitale.' },
    ] },
  ],
  tip: 'Inizia presto e lascia lavorare il tempo: anche piccole somme reinvestite con costanza per molti anni possono crescere più di quanto immagini.',
});
