FQC(6, {
  intro: 'Perché con 10 € oggi compri meno di dieci anni fa? Scopri l’inflazione e come proteggere il valore reale dei tuoi soldi.',
  cards: [
    { t: 'Che cos’è l’inflazione', x: 'L’inflazione è l’aumento generale e prolungato dei prezzi, non il rincaro di un singolo prodotto. La BCE punta a mantenerla al 2% annuo nel medio termine: bassa, stabile e positiva.', v: { k: 'stat', n: '2%', l: 'obiettivo di inflazione della BCE nel medio termine' } },
    { t: 'Lo stesso euro compra meno', x: 'Con un’inflazione del 2% annuo, 100 € tenuti fermi comprano dopo 10 anni quanto 82 € di oggi. La cifra sul conto resta uguale, il potere d’acquisto scende.', v: { k: 'bars', d: [['Oggi', 100], ['Dopo 5 anni', 91], ['Dopo 10 anni', 82], ['Dopo 20 anni', 67]], u: '€' } },
    { t: 'Rendimento reale', x: 'Conta quanto cresce ciò che puoi comprare, non solo il numero sul conto. Se un deposito rende l’1% e i prezzi salgono del 3%, in termini reali perdi circa il 2% l’anno.', v: { k: 'formula', f: 'Rendimento reale ≈ nominale − inflazione', n: 'Es.: 3% − 2% = circa 1%' } },
    { t: 'Come si misura', x: 'In Italia l’ISTAT rileva ogni mese i prezzi di un paniere di beni e servizi rappresentativo dei consumi delle famiglie. Per l’area euro Eurostat pubblica un indice armonizzato, confrontabile tra Paesi.', v: { k: 'steps', s: ['Si definisce il paniere', 'Si rilevano i prezzi', 'Si calcola l’indice', 'Si confronta con un anno prima'] } },
    { t: 'Inflazione e deflazione', x: 'Prezzi in calo sembrano solo un vantaggio, ma una deflazione prolungata spinge a rimandare acquisti e investimenti e pesa su imprese e lavoro. Per questo si punta a un’inflazione bassa ma positiva.', v: { k: 'vs', a: ['Inflazione', 'I prezzi salgono, il denaro perde valore'], b: ['Deflazione', 'I prezzi scendono, consumi e investimenti frenano'] } },
    { t: 'Chi perde e chi guadagna', x: 'L’inflazione erode il valore reale del contante e dei redditi che non crescono. Chi ha un debito a tasso fisso, invece, lo rimborsa con euro che valgono meno.', v: { k: 'icons', d: [['💶', 'Risparmi fermi: perdono'], ['🏠', 'Debito a tasso fisso: si alleggerisce'], ['💼', 'Stipendio non adeguato: perde']] } },
  ],
  terms: [
    ['Inflazione', 'Aumento generale e prolungato del livello dei prezzi.'],
    ['Deflazione', 'Calo generale e prolungato del livello dei prezzi.'],
    ['Potere d’acquisto', 'Quantità di beni e servizi che una somma di denaro permette di comprare.'],
    ['Paniere', 'Insieme di beni e servizi rappresentativi dei consumi, usato per misurare i prezzi.'],
    ['Rendimento nominale', 'Guadagno percentuale in euro, senza tener conto dell’aumento dei prezzi.'],
    ['Rendimento reale', 'Guadagno dopo aver tolto l’inflazione: misura la crescita del potere d’acquisto.'],
    ['Indice dei prezzi al consumo', 'Misura statistica dell’andamento dei prezzi pagati dalle famiglie.'],
    ['Iperinflazione', 'Aumento dei prezzi rapidissimo e fuori controllo, per esempio oltre il 50% al mese.'],
  ],
  tf: [
    ['L’inflazione è l’aumento generale dei prezzi, non quello di un singolo prodotto.', true, 'Se rincara solo il caffè non è inflazione: serve un aumento diffuso e prolungato del livello medio dei prezzi.'],
    ['Se i prezzi salgono del 3% in un anno e il tuo stipendio resta uguale, il tuo potere d’acquisto diminuisce.', true, 'Con gli stessi euro compri circa il 3% in meno di beni e servizi.'],
    ['Tenere i risparmi fermi sul conto corrente li protegge dall’inflazione.', false, 'Il saldo nominale resta uguale, ma se i prezzi salgono quella somma compra sempre meno.'],
    ['L’obiettivo della BCE è un’inflazione pari a zero.', false, 'La BCE punta al 2% nel medio termine: un margine che allontana il rischio di deflazione.'],
    ['Con un rendimento nominale del 2% e un’inflazione del 2%, il rendimento reale è circa zero.', true, 'Guadagni euro, ma il tuo potere d’acquisto resta più o meno lo stesso.'],
    ['La deflazione è sempre una buona notizia per l’economia.', false, 'Se i prezzi calano a lungo, famiglie e imprese rimandano le spese: l’economia può rallentare.'],
    ['Con un’inflazione del 3% annuo, i prezzi raddoppiano in circa 24 anni.', true, 'La regola del 72 vale anche per i prezzi: 72 ÷ 3 = 24 anni.'],
    ['Un’inflazione più alta del previsto riduce il valore reale di un debito a tasso fisso.', true, 'La rata resta uguale in euro, ma quegli euro valgono meno: il peso reale del debito scende.'],
    ['Se l’inflazione passa dal 5% al 3%, significa che i prezzi stanno scendendo.', false, 'I prezzi continuano a salire, solo più lentamente. Scenderebbero con un’inflazione negativa.'],
    ['Un rendimento del 4% batte sempre l’inflazione.', false, 'Dipende dall’inflazione del periodo: con prezzi in aumento del 6%, un 4% nominale è una perdita reale.'],
  ],
  mcq: [
    { q: 'Un deposito rende il 2% e l’inflazione è al 4%. Qual è, circa, il rendimento reale?', a: '−2%', w: ['+2%', '+6%', '0%'], e: 'Rendimento reale ≈ 2% − 4% = −2%: il saldo cresce, ma compra meno di prima.' },
    { q: 'Chi calcola e pubblica l’inflazione ufficiale in Italia?', a: 'L’ISTAT', w: ['La CONSOB', 'L’Agenzia delle Entrate', 'Borsa Italiana'], e: 'L’ISTAT rileva ogni mese i prezzi di un ampio paniere di beni e servizi.' },
    { q: 'Qual è l’obiettivo di inflazione della BCE nel medio termine?', a: '2%', w: ['0%', '5%', '10%'], e: 'Un’inflazione al 2% è considerata compatibile con la stabilità dei prezzi e lontana dal rischio di deflazione.' },
    { q: 'Un carrello della spesa costa 100 €. Con un’inflazione del 5%, quanto costerà circa tra un anno?', a: '105 €', w: ['95 €', '150 €', '100,50 €'], e: '100 × 1,05 = 105 €: lo stesso carrello richiede 5 € in più.' },
    { q: 'L’inflazione scende dal 6% al 2%. Che cosa significa?', a: 'I prezzi salgono, ma più lentamente', w: ['I prezzi stanno scendendo', 'I prezzi tornano a quelli di prima', 'Gli stipendi stanno diminuendo'], e: 'Un’inflazione più bassa ma positiva indica prezzi ancora in crescita, a un ritmo minore.' },
    { q: 'Chi è avvantaggiato da un’inflazione più alta del previsto?', a: 'Chi ha un mutuo a tasso fisso', w: ['Chi tiene molti contanti in casa', 'Chi ha una pensione non rivalutata', 'Chi ha prestato a tasso fisso'], e: 'Il debitore a tasso fisso rimborsa rate uguali con euro che valgono meno; chi presta ci perde.' },
    { q: 'Che cosa misura il paniere dell’ISTAT?', a: 'I prezzi dei beni acquistati dalle famiglie', w: ['I prezzi delle azioni di Borsa Italiana', 'Il valore delle case di lusso', 'Gli stipendi dei dipendenti pubblici'], e: 'Il paniere rappresenta i consumi tipici delle famiglie: cibo, casa, trasporti, servizi.' },
    { q: 'Perché una deflazione prolungata può essere un problema?', a: 'Spinge a rimandare acquisti e investimenti', w: ['Fa aumentare velocemente i prezzi', 'Rende il contante privo di valore', 'Azzera gli stipendi dei dipendenti'], e: 'Se tutti aspettano prezzi più bassi, la domanda cala: imprese e lavoro ne risentono.' },
  ],
  fill: [
    { s: 'Il ___ è l’insieme di beni e servizi usato per misurare l’inflazione.', a: 'paniere', w: ['bilancio', 'portafoglio', 'listino'] },
    { s: 'Il rendimento ___ è circa uguale al rendimento nominale meno l’inflazione.', a: 'reale', w: ['lordo', 'composto', 'medio'] },
    { s: 'Quando il livello dei prezzi cala in modo generale e prolungato si parla di ___.', a: 'deflazione', w: ['inflazione', 'iperinflazione', 'svalutazione'] },
    { s: 'Con l’inflazione, la stessa somma di denaro compra ___ beni di prima.', a: 'meno', w: ['più', 'gli stessi', 'il doppio dei'] },
    { s: 'Con un’inflazione del 2% annuo, 100 € fermi per 10 anni comprano quanto circa ___ € di oggi.', a: '82', w: ['98', '120', '50'] },
  ],
  order: [
    { q: 'Ordina i passi per misurare l’inflazione', i: ['Definire il paniere di beni e servizi', 'Rilevare i prezzi nei punti vendita', 'Calcolare l’indice dei prezzi', 'Confrontarlo con un anno prima'], e: 'Prima si sceglie cosa misurare, poi si raccolgono i prezzi, si costruisce l’indice e si calcola la variazione annua.' },
    { q: 'Ordina dal rendimento reale più basso al più alto', i: ['Conto allo 0% con inflazione al 3%', 'Deposito all’1% con inflazione al 3%', 'Deposito al 2% con inflazione al 2%', 'Titolo al 4% con inflazione al 2%', 'Titolo al 5% con inflazione all’1%'], e: 'I rendimenti reali sono circa −3%, −2%, 0%, +2% e +4%: conta la differenza, non il solo tasso nominale.' },
  ],
  cat: [
    { q: 'Danneggiato o avvantaggiato da un’inflazione più alta del previsto?', g: [['Danneggiato', ['Chi tiene molti contanti', 'Chi ha uno stipendio fisso non adeguato', 'Chi ha prestato denaro a tasso fisso']], ['Avvantaggiato', ['Chi ha un mutuo a tasso fisso', 'Uno Stato indebitato a tasso fisso', 'Un’azienda con debiti a tasso fisso']]] },
    { q: 'Inflazione o deflazione?', g: [['Inflazione', ['I prezzi medi salgono per mesi', 'Il paniere costa il 4% in più di un anno fa', 'Lo stesso carrello costa ogni anno di più']], ['Deflazione', ['I prezzi medi calano per due anni', 'Il paniere costa l’1% in meno di un anno fa', 'Le famiglie rimandano gli acquisti aspettando ribassi']]] },
  ],
  scen: [
    { s: 'Laura, 30 anni, tiene da anni 20.000 € fermi sul conto corrente “per sicurezza”, oltre a un fondo di emergenza già completo. Nel frattempo i prezzi salgono di circa il 2-3% l’anno.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Lasciare tutto com’è: il saldo non scende', ok: false, f: 'Il saldo nominale non scende, ma il potere d’acquisto sì: in 10 anni al 2,5% perderebbe circa un quinto del valore reale.' },
      { t: 'Darsi un obiettivo e cercare strumenti adatti', ok: true, f: 'Giusto: chiarire a cosa servono quei soldi e quando le permette di scegliere come proteggerli dall’inflazione.' },
      { t: 'Investire tutto in una sola azione', ok: false, f: 'Per battere l’inflazione si prenderebbe un rischio enorme e concentrato: è l’eccesso opposto.' },
    ] },
    { s: 'Pietro, 45 anni, riceve un aumento di stipendio del 2%. Nello stesso anno l’inflazione è al 5%.', q: 'Che cosa è successo al suo potere d’acquisto?', o: [
      { t: 'È aumentato del 2%', ok: false, f: 'È aumentato il numero di euro, non ciò che può comprare: i prezzi sono saliti di più.' },
      { t: 'È sceso di circa il 3%', ok: true, f: 'In termini reali il suo stipendio vale circa il 3% in meno: è il momento di rivedere il budget.' },
      { t: 'È aumentato del 7%', ok: false, f: 'Aumento e inflazione non si sommano: l’inflazione si sottrae all’aumento.' },
    ] },
    { s: 'Beatrice, 28 anni, deve sostituire la lavatrice rotta. Al telegiornale sente che “l’inflazione è scesa al 2%” e pensa di aspettare che i prezzi tornino a quelli di un anno fa.', q: 'Cosa le consigli?', o: [
      { t: 'Aspettare qualche mese', ok: false, f: 'Inflazione in calo non vuol dire prezzi in calo: probabilmente pagherebbe di più, e intanto resta senza lavatrice.' },
      { t: 'Comprarla a rate subito, senza confronti', ok: false, f: 'Il problema non è il momento ma il prezzo: meglio confrontare le offerte ed evitare costi di finanziamento inutili.' },
      { t: 'Comprarla ora, confrontando le offerte', ok: true, f: 'Bene: con l’inflazione al 2% i prezzi salgono ancora, solo più piano. Aspettare non li riporterà indietro.' },
    ] },
    { s: 'Michela, 40 anni, vuole cambiare auto tra 5 anni. Il modello che le piace oggi costa 20.000 €. Si aspetta un’inflazione media del 2% annuo.', q: 'Quale cifra si pone come obiettivo?', o: [
      { t: 'Circa 22.000 €', ok: true, f: '20.000 × 1,02^5 ≈ 22.080 €. Tenere conto dell’inflazione evita di arrivare alla scadenza con una somma insufficiente.' },
      { t: 'Esattamente 20.000 €', ok: false, f: 'Tra 5 anni lo stesso modello costerà probabilmente di più: rischia di non bastare.' },
      { t: '30.000 €, per stare tranquilla', ok: false, f: 'Con il 2% annuo l’aumento atteso è di circa 2.000 €, non di 10.000: obiettivo troppo distante dalla realtà.' },
    ] },
  ],
  tip: 'Quando valuti un rendimento sottrai sempre l’inflazione: l’unico guadagno che conta davvero è quello che aumenta ciò che puoi comprare.',
});
