FQC(7, {
  intro: 'Il debito non è sempre un nemico: impara a distinguere quello che ti aiuta a crescere da quello che ti costa caro.',
  cards: [
    { t: 'Non tutti i debiti sono uguali', x: 'Un mutuo sostenibile per la casa o un prestito per studiare possono migliorare il tuo futuro. Un acquisto d’impulso pagato a rate ti fa pagare di più qualcosa che perde valore in fretta.', v: { k: 'vs', a: ['Debito buono', 'Finanzia qualcosa che crea valore nel tempo'], b: ['Debito cattivo', 'Finanzia consumi che svaniscono, spesso a caro prezzo'] } },
    { t: 'Quanto costa davvero un prestito', x: 'Prendi 10.000 € e li restituisci in 5 anni con un tasso del 6%: paghi 60 rate da circa 193 €. In totale restituisci circa 11.600 €, cioè circa 1.600 € in più del prestito.', v: { k: 'formula', f: 'Costo del prestito = totale delle rate − somma ricevuta', n: 'Es.: 60 × 193,33 € − 10.000 € ≈ 1.600 €' } },
    { t: 'TAN e TAEG', x: 'Il TAN misura solo gli interessi. Il TAEG aggiunge le spese obbligatorie: istruttoria, incasso rata, assicurazioni richieste. Per confrontare due prestiti guarda il TAEG: un “tasso zero” può avere un TAEG sopra lo zero.', v: { k: 'stat', n: 'TAEG', l: 'l’indicatore che include interessi e spese obbligatorie' } },
    { t: 'Quanto debito puoi sostenere', x: 'Una regola prudente: la somma di tutte le rate non dovrebbe superare circa il 30% del reddito netto. Con 2.000 € netti al mese significa al massimo 600 € di rate.', v: { k: 'pie', d: [['Rate dei debiti', 30], ['Spese, risparmio e imprevisti', 70]] } },
    { t: 'Dal più sano al più pericoloso', x: 'Conta lo scopo, ma anche il costo e la sostenibilità. Le carte revolving hanno spesso tassi molto alti: si rimborsano a piccole rate, ma gli interessi corrono a lungo.', v: { k: 'scale', a: 'Debito più sano', b: 'Debito più dannoso', d: [['Mutuo sostenibile', 15], ['Prestito per studiare', 25], ['Auto a rate', 60], ['Carta revolving', 90]] } },
    { t: 'Come uscire dai debiti', x: 'Paga sempre almeno le rate dovute per evitare penali e segnalazioni. Con i soldi in più estingui prima il debito con il tasso più alto: risparmi più interessi.', v: { k: 'steps', s: ['Elenca debiti, tassi e rate', 'Paga sempre le rate dovute', 'Estingui prima il tasso più alto', 'Non aprire nuovi debiti per consumi'] } },
  ],
  terms: [
    ['Debito', 'Somma ricevuta in prestito che va restituita, di solito con gli interessi.'],
    ['TAN', 'Tasso annuo nominale: misura soltanto il costo degli interessi di un prestito.'],
    ['TAEG', 'Tasso annuo effettivo globale: comprende interessi e tutte le spese obbligatorie del prestito.'],
    ['Rata', 'Pagamento periodico che restituisce una parte del capitale più gli interessi.'],
    ['Carta revolving', 'Carta di credito che si rimborsa a piccole rate mensili, di solito con tassi elevati.'],
    ['Mutuo', 'Prestito a lungo termine, di solito per comprare casa, garantito da ipoteca.'],
    ['Usura', 'Prestito a tassi oltre la soglia massima fissata per legge: è un reato.'],
    ['Rapporto rata/reddito', 'Quota del reddito netto mensile assorbita dalle rate di tutti i debiti.'],
  ],
  tf: [
    ['Il TAEG comprende, oltre agli interessi, le spese obbligatorie del prestito.', true, 'Per questo è l’indicatore giusto per confrontare il costo complessivo di prestiti diversi.'],
    ['Un prestito pubblicizzato a “tasso zero” è sempre del tutto gratuito.', false, 'Il TAN può essere zero, ma spese di istruttoria o di incasso rata fanno salire il TAEG sopra lo zero.'],
    ['Tutti i debiti sono negativi e vanno evitati a qualsiasi costo.', false, 'Un debito sostenibile per casa, studio o lavoro può creare valore. Conta a cosa serve, quanto costa e se puoi ripagarlo.'],
    ['Pagare una vacanza con una carta revolving è un tipico esempio di debito cattivo.', true, 'Finanzia un consumo che finisce subito con un debito a tasso alto che dura mesi.'],
    ['Per confrontare il costo di due prestiti conviene guardare il TAN invece del TAEG.', false, 'Il TAN ignora le spese: due prestiti con lo stesso TAN possono costare in modo molto diverso.'],
    ['Se hai più debiti, rimborsare prima quello con il tasso più alto fa risparmiare più interessi.', true, 'Ogni euro tolto dal debito più caro elimina gli interessi più alti: è il metodo “valanga”.'],
    ['Un mutuo resta un debito buono anche se la rata assorbe il 60% del reddito netto.', false, 'Con una rata così pesante basta un imprevisto per non riuscire a pagare: lo scopo è buono, la sostenibilità no.'],
    ['Allungando la durata di un prestito, la rata scende ma gli interessi totali di solito aumentano.', true, 'Paghi interessi per più tempo: la rata più leggera ha un prezzo complessivo più alto.'],
    ['Applicare tassi oltre la soglia fissata dalla legge è usura ed è un reato.', true, 'In Italia la legge fissa tassi soglia aggiornati ogni trimestre: superarli è usura.'],
    ['Pagare una rata in ritardo non ha conseguenze se la saldi il mese dopo.', false, 'Possono scattare interessi di mora e penali, e i ritardi possono essere segnalati nelle banche dati sul credito.'],
  ],
  mcq: [
    { q: 'Quale di questi debiti è più vicino a un debito buono?', a: 'Un mutuo con rata sostenibile', w: ['Un prestito per l’ultimo smartphone', 'Una carta revolving per le vacanze', 'Un finanziamento per una festa'], e: 'Finanzia un bene durevole che serve per anni, con una rata che il reddito può reggere.' },
    { q: 'Quale indicatore usi per confrontare il costo totale di due prestiti?', a: 'Il TAEG', w: ['Il TAN', 'L’importo della rata', 'La durata in mesi'], e: 'Il TAEG include interessi e spese obbligatorie: è l’unico che misura il costo complessivo.' },
    { q: 'Con 1.800 € netti al mese, quale rata totale massima rispetta la regola prudente del 30%?', a: '540 €', w: ['180 €', '900 €', '1.260 €'], e: '1.800 × 0,30 = 540 €. Oltre questa soglia il bilancio diventa fragile.' },
    { q: 'Ricevi 10.000 € e restituisci 60 rate da 193 €. Quanto paghi, circa, tra interessi e spese?', a: '1.580 €', w: ['193 €', '11.580 €', '600 €'], e: '60 × 193 = 11.580 €. Tolti i 10.000 € ricevuti, il costo è di circa 1.580 €.' },
    { q: 'Hai una carta revolving al 18% e un prestito auto al 6%, e 1.000 € in più. Cosa rimborsi prima?', a: 'La carta revolving', w: ['Il prestito auto', 'Metà e metà', 'Nessuno dei due'], e: 'Ridurre il debito al 18% fa risparmiare il triplo degli interessi rispetto a quello al 6%.' },
    { q: 'Perché un prestito per studiare può essere un debito buono?', a: 'Può aumentare il reddito futuro', w: ['Non va mai restituito', 'Ha sempre un tasso pari a zero', 'Non compare in alcuna banca dati'], e: 'Se la formazione migliora le opportunità di lavoro, il debito finanzia una crescita del reddito.' },
    { q: 'Che cosa succede se allunghi la durata di un prestito, a parità di tasso?', a: 'Rata più bassa, interessi totali più alti', w: ['Rata e interessi totali più bassi', 'Rata più alta, interessi più bassi', 'Rata e interessi totali invariati'], e: 'Restituisci il capitale più lentamente e quindi paghi interessi per più tempo.' },
    { q: 'Un negozio offre un televisore a “tasso zero” con 50 € di spese di istruttoria. Cosa è vero?', a: 'Il TAEG è maggiore di zero', w: ['Il prestito è del tutto gratuito', 'TAN e TAEG sono uguali', 'Le spese non contano nel costo'], e: 'Il TAN è zero, ma le spese obbligatorie entrano nel TAEG: il finanziamento ha un costo.' },
  ],
  fill: [
    { s: 'Il ___ include interessi e spese obbligatorie: è il numero giusto per confrontare i prestiti.', a: 'TAEG', w: ['TAN', 'saldo', 'canone'] },
    { s: 'Un debito che finanzia consumi che svaniscono, a tassi alti, è un debito ___.', a: 'cattivo', w: ['buono', 'agevolato', 'garantito'] },
    { s: 'Prestare denaro a tassi oltre la soglia di legge si chiama ___.', a: 'usura', w: ['leva', 'mora', 'ipoteca'] },
    { s: 'Secondo una regola prudente, le rate non dovrebbero superare circa il ___ del reddito netto.', a: '30%', w: ['50%', '70%', '90%'] },
    { s: 'Il ___ è un prestito a lungo termine per comprare casa, garantito da ipoteca.', a: 'mutuo', w: ['fido', 'leasing', 'bonifico'] },
  ],
  order: [
    { q: 'Ordina i passi per chiedere un prestito in modo consapevole', i: ['Chiediti se l’acquisto è davvero necessario', 'Calcola quale rata puoi sostenere', 'Confronta il TAEG di più offerte', 'Leggi con attenzione il contratto', 'Firma solo se la rata resta sostenibile'], e: 'Prima decidi se ti serve davvero e quanto puoi permetterti, poi confronti le offerte e verifichi le condizioni.' },
    { q: 'Con il metodo “valanga”, ordina i debiti da estinguere per primi', i: ['Carta revolving al 19%', 'Prestito personale al 9%', 'Prestito auto al 6%', 'Mutuo al 3%'], e: 'Pagando le rate dovute di tutti, i soldi in più vanno al tasso più alto: così risparmi più interessi.' },
  ],
  cat: [
    { q: 'Più vicino al debito buono o al debito cattivo?', g: [['Debito buono', ['Mutuo sostenibile per la casa', 'Prestito per un master', 'Finanziamento per avviare un’attività']], ['Debito cattivo', ['Carta revolving per lo shopping', 'Prestito per una vacanza', 'Rate per l’ultimo smartphone']]] },
    { q: 'Incluso nel TAEG o escluso?', g: [['Incluso', ['Interessi', 'Spese di istruttoria', 'Spese di incasso rata', 'Assicurazione obbligatoria']], ['Escluso', ['Penali per ritardi nei pagamenti', 'Assicurazione facoltativa', 'Prezzo del bene acquistato']]] },
  ],
  scen: [
    { s: 'Tommaso, 24 anni, guadagna 1.300 € al mese e ha pochi risparmi. Vuole uno smartphone da 1.200 € “a tasso zero” in 20 rate da 60 €, più 40 € di istruttoria. Il suo telefono attuale funziona.', q: 'Cosa fa?', o: [
      { t: 'Tiene il telefono e risparmia per uno adatto', ok: true, f: 'Bravo: evita un debito per un bene che perde valore in fretta e non vincola il suo budget per quasi due anni.' },
      { t: 'Firma: con il tasso zero non paga niente', ok: false, f: 'Paga 40 € di istruttoria, quindi il TAEG è sopra lo zero. E si lega a 20 rate per un bene non necessario.' },
      { t: 'Lo compra con la carta revolving', ok: false, f: 'È la scelta peggiore: tassi alti su un acquisto non necessario.' },
    ] },
    { s: 'Serena, 32 anni, ha 3.000 € di debito su una carta revolving al 18%. Ha anche 4.000 € di risparmi oltre al fondo di emergenza, che è completo.', q: 'Cosa fa?', o: [
      { t: 'Investe i 4.000 € sperando di guadagnare di più', ok: false, f: 'Dovrebbe ottenere più del 18% l’anno, con rischio: estinguere il debito è un guadagno certo.' },
      { t: 'Paga solo la rata minima', ok: false, f: 'Il debito si trascina a lungo e gli interessi al 18% continuano a pesare.' },
      { t: 'Estingue la revolving con i risparmi extra', ok: true, f: 'Ottimo: elimina un costo del 18% annuo senza toccare il fondo di emergenza.' },
    ] },
    { s: 'Alessandro e Marta, 35 e 33 anni, guadagnano insieme 3.200 € netti al mese. La casa A comporta una rata di 900 €, la casa B, più grande, una rata di 1.500 €.', q: 'Quale scelta è più prudente?', o: [
      { t: 'La casa B: la casa è un debito buono', ok: false, f: 'La rata assorbirebbe quasi metà del reddito: un imprevisto o un figlio metterebbero il bilancio in crisi.' },
      { t: 'La casa A, con rata al 28% del reddito', ok: true, f: 'Giusto: 900 ÷ 3.200 ≈ 28%, sotto la soglia prudente del 30%. Resta spazio per spese, risparmio e imprevisti.' },
      { t: 'La casa B, allungando il mutuo al massimo', ok: false, f: 'La rata scende un po’, ma gli interessi totali salgono molto e il debito dura più a lungo.' },
    ] },
    { s: 'Roberto, 52 anni, ha bisogno di 1.000 € in fretta. Un conoscente glieli presta subito, senza controlli, ma vuole indietro 1.500 € dopo 3 mesi.', q: 'Cosa fa?', o: [
      { t: 'Accetta: è un’emergenza', ok: false, f: '500 € in 3 mesi corrispondono ad almeno il 200% annuo: tassi da usura, che possono trascinarlo in una spirale di debiti.' },
      { t: 'Rifiuta e si rivolge a canali regolari', ok: true, f: 'Bene: banche e finanziarie autorizzate sono soggette a regole e tassi soglia. In difficoltà esistono anche fondazioni antiusura.' },
      { t: 'Accetta, ma solo per metà della somma', ok: false, f: 'Il tasso resta da usura anche su 500 €: il problema non è l’importo ma chi presta e a che condizioni.' },
    ] },
  ],
  tip: 'Prima di firmare un prestito chiediti: mi servirà ancora quando avrò finito di pagarlo? E confronta sempre il TAEG, non solo la rata.',
});
