FQC(8, {
  intro: 'Conto corrente, conto deposito, bollo e garanzie: scopri come funzionano le banche e dove conviene tenere i tuoi soldi.',
  cards: [
    { t: 'Il mestiere della banca', x: 'La banca fa da intermediario: raccoglie i depositi e li usa in parte per concedere prestiti. Guadagna soprattutto sulla differenza tra il tasso che chiede a chi prende a prestito e quello che paga ai depositanti.', v: { k: 'icons', d: [['📥', 'Raccoglie depositi'], ['📤', 'Concede prestiti'], ['🔁', 'Gestisce i pagamenti']] } },
    { t: 'Conto corrente o conto deposito?', x: 'Il conto corrente è lo strumento di tutti i giorni e di solito rende poco o nulla. Il conto deposito offre un tasso più alto ma non permette pagamenti: i soldi entrano ed escono passando da un conto corrente collegato.', v: { k: 'vs', a: ['Conto corrente', 'Per pagare: carte, bonifici, bollette'], b: ['Conto deposito', 'Per far fruttare i risparmi, non per pagare'] } },
    { t: 'La garanzia sui depositi', x: 'Se una banca fallisce, i sistemi di garanzia dei depositi, come il FITD, rimborsano conti correnti e conti deposito fino a 100.000 € per depositante e per banca. Azioni, obbligazioni e fondi non sono depositi e non rientrano in questa tutela.', v: { k: 'stat', n: '100.000 €', l: 'tutela per depositante e per banca' } },
    { t: 'Libero o vincolato', x: 'Nel conto deposito vincolato ti impegni a non toccare i soldi fino a una scadenza e di solito ottieni un tasso più alto. Se svincoli prima, in genere perdi tutti o parte degli interessi.', v: { k: 'scale', a: 'Tasso più basso, più flessibile', b: 'Tasso più alto, meno flessibile', d: [['Conto corrente', 5], ['Deposito libero', 40], ['Vincolato 12 mesi', 65], ['Vincolato 36 mesi', 85]] } },
    { t: 'L’imposta di bollo', x: 'Sul conto corrente di una persona fisica il bollo è di 34,20 € l’anno, ma solo se la giacenza media supera 5.000 €. Sul conto deposito si paga lo 0,2% annuo della somma depositata.', v: { k: 'formula', f: 'Bollo conto deposito = 0,2% × somma depositata', n: 'Es.: 10.000 € × 0,2% = 20 € l’anno' } },
    { t: 'Dal lordo al netto', x: 'Esempio con 10.000 € al 3% lordo per un anno: 300 € di interessi, meno 78 € di ritenuta del 26% e 20 € di bollo. Restano 202 € netti: ecco il numero da confrontare.', v: { k: 'bars', d: [['Interessi lordi', 300], ['Ritenuta 26%', -78], ['Bollo 0,2%', -20], ['Netto', 202]], u: '€' } },
  ],
  terms: [
    ['Conto corrente', 'Conto per gestire pagamenti e incassi quotidiani: carte, bonifici, bollette.'],
    ['Conto deposito', 'Conto di risparmio che paga interessi, senza funzioni di pagamento.'],
    ['Deposito vincolato', 'Somma bloccata fino a una scadenza in cambio di un tasso più alto.'],
    ['IBAN', 'Codice che identifica in modo univoco un conto per inviare e ricevere bonifici.'],
    ['Bonifico', 'Trasferimento di denaro da un conto a un altro tramite banca.'],
    ['Giacenza media', 'Saldo medio del conto in un periodo, usato ad esempio per calcolare il bollo.'],
    ['Garanzia dei depositi', 'Tutela che rimborsa i depositanti fino a 100.000 € per persona e per banca.'],
    ['ISC', 'Indicatore sintetico di costo: stima quanto costa in un anno un conto corrente.'],
  ],
  tf: [
    ['La garanzia sui depositi copre fino a 100.000 € per depositante e per banca.', true, 'Il limite vale per ogni persona in ciascuna banca: chi ha somme più alte può distribuirle tra banche diverse.'],
    ['Con un conto deposito puoi pagare le bollette e prelevare al bancomat.', false, 'Il conto deposito non ha funzioni di pagamento: i soldi passano sempre da un conto corrente collegato.'],
    ['Sul conto corrente di una persona fisica il bollo di 34,20 € si paga solo se la giacenza media supera 5.000 €.', true, 'Sotto quella soglia di giacenza media annua il bollo sul conto corrente non è dovuto.'],
    ['Le banche tengono in cassaforte tutti i soldi depositati, senza usarli.', false, 'Le banche usano buona parte dei depositi per concedere prestiti: è il cuore della loro attività.'],
    ['Svincolare in anticipo un deposito vincolato può farti perdere parte degli interessi.', true, 'Il tasso più alto è il compenso per il vincolo: se lo rompi, la banca di solito riduce o annulla gli interessi.'],
    ['Gli interessi del conto deposito sono tassati al 12,5%.', false, 'Sugli interessi di conti correnti e depositi la ritenuta è del 26%. Il 12,5% vale per i titoli di Stato.'],
    ['La garanzia sui depositi protegge anche il valore delle azioni comprate tramite la banca.', false, 'Le azioni non sono depositi: se scendono di prezzo nessuno ti rimborsa la perdita.'],
    ['Su un conto deposito da 20.000 € il bollo annuo è di 40 €.', true, '20.000 × 0,2% = 40 €.'],
    ['Per confrontare il costo di due conti correnti puoi usare l’ISC.', true, 'L’Indicatore sintetico di costo stima la spesa annua per diversi profili di utilizzo.'],
    ['Avere 300.000 € in un’unica banca li rende tutti coperti dalla garanzia sui depositi.', false, 'La copertura si ferma a 100.000 € per depositante e per banca: oltre quella cifra la somma non è garantita.'],
  ],
  mcq: [
    { q: 'Come guadagna, principalmente, una banca tradizionale?', a: 'Presta a tassi più alti di quelli che paga', w: ['Stampa le banconote che presta', 'Trattiene il bollo dei correntisti', 'Investe tutti i depositi in azioni'], e: 'La differenza tra i tassi sui prestiti e quelli sui depositi è la principale fonte di guadagno.' },
    { q: 'Quale conto è adatto per ricevere lo stipendio e pagare con la carta?', a: 'Il conto corrente', w: ['Il conto deposito vincolato', 'Il conto deposito libero', 'Il dossier titoli'], e: 'Solo il conto corrente offre carte, bonifici e domiciliazioni delle bollette.' },
    { q: 'Hai 15.000 € su un conto deposito. Quanto paghi di bollo in un anno?', a: '30 €', w: ['34,20 €', '150 €', '3 €'], e: '15.000 × 0,2% = 30 €. I 34,20 € fissi riguardano il conto corrente.' },
    { q: 'Hai 150.000 € su un conto in una banca che fallisce. Quanto è coperto dalla garanzia sui depositi?', a: '100.000 €', w: ['150.000 €', '50.000 €', '75.000 €'], e: 'La garanzia copre fino a 100.000 € per depositante e per banca: i restanti 50.000 € non sono garantiti.' },
    { q: 'Perché un deposito vincolato offre, di solito, un tasso più alto di uno libero?', a: 'Rinunci a usare i soldi per un periodo', w: ['È garantito dallo Stato senza limiti', 'Non paga alcuna imposta', 'Ha costi di gestione più alti'], e: 'La banca può contare su quei soldi fino alla scadenza e ti ricompensa con un tasso maggiore.' },
    { q: 'A che cosa serve l’IBAN?', a: 'A identificare un conto per i bonifici', w: ['A calcolare il bollo annuo', 'A proteggere il PIN della carta', 'A misurare il costo del conto'], e: 'L’IBAN indica Paese, banca e conto: serve per inviare e ricevere denaro con un bonifico.' },
    { q: 'Un deposito ti dà 300 € di interessi lordi. Quanto paghi di ritenuta?', a: '78 €', w: ['37,50 €', '26 €', '34,20 €'], e: '300 × 26% = 78 €. Il 12,5% vale per i titoli di Stato, non per i depositi bancari.' },
    { q: 'Un conto corrente “a canone zero” è sempre gratuito?', a: 'No, possono esserci altri costi', w: ['Sì, per legge non ha costi', 'Sì, se la giacenza supera 5.000 €', 'No, ma solo per le aziende'], e: 'Possono esserci commissioni su bonifici, prelievi o carte, e il bollo se la giacenza media supera 5.000 €.' },
  ],
  fill: [
    { s: 'Il conto ___ serve per pagamenti e incassi di tutti i giorni.', a: 'corrente', w: ['deposito', 'titoli', 'vincolato'] },
    { s: 'Sul conto deposito l’imposta di bollo annua è pari a ___ della somma depositata.', a: '0,2%', w: ['2%', '26%', '12,5%'] },
    { s: 'I depositi sono garantiti fino a ___ € per depositante e per banca.', a: '100.000', w: ['50.000', '20.000', '1.000.000'] },
    { s: 'Il codice che identifica un conto per i bonifici si chiama ___.', a: 'IBAN', w: ['PIN', 'ISC', 'TAEG'] },
    { s: 'In un deposito ___ ti impegni a non toccare i soldi fino alla scadenza.', a: 'vincolato', w: ['libero', 'corrente', 'cointestato'] },
  ],
  order: [
    { q: 'Ordina dal più liquido al meno liquido', i: ['Conto corrente', 'Conto deposito libero', 'Deposito vincolato a 12 mesi', 'Deposito vincolato a 5 anni'], e: 'Il conto corrente si usa subito; il deposito libero richiede un giroconto; i vincolati bloccano i soldi fino alla scadenza.' },
    { q: 'Ordina dal bollo annuo più basso al più alto (persona fisica)', i: ['Conto corrente con giacenza media di 4.000 €', 'Conto deposito con 5.000 €', 'Conto deposito con 15.000 €', 'Conto corrente con giacenza media di 8.000 €', 'Conto deposito con 25.000 €'], e: 'I bolli sono 0 €, 10 €, 30 €, 34,20 € e 50 €: fisso sul conto corrente oltre 5.000 €, proporzionale sul deposito.' },
  ],
  cat: [
    { q: 'Coperto o non coperto dalla garanzia sui depositi?', g: [['Coperto', ['Saldo del conto corrente', 'Conto deposito', 'Certificato di deposito nominativo']], ['Non coperto', ['Azioni', 'Quote di fondi comuni', 'Obbligazioni']]] },
    { q: 'Conto corrente o conto deposito?', g: [['Conto corrente', ['Accredito dello stipendio', 'Pagamento delle bollette', 'Carta di debito']], ['Conto deposito', ['Somme da non toccare per un anno', 'Tasso più alto in cambio di un vincolo', 'Nessuna funzione di pagamento']]] },
  ],
  scen: [
    { s: 'Cristina, 38 anni, tiene 40.000 € sul conto corrente “per comodità”. Spende circa 2.000 € al mese e vuole comprare casa tra 2 anni.', q: 'Cosa fa?', o: [
      { t: 'Lascia tutto sul conto corrente', ok: false, f: 'Paga il bollo e non riceve quasi nulla di interessi su soldi che non le servono per due anni.' },
      { t: 'Sposta il grosso su un conto deposito', ok: true, f: 'Giusto: tiene sul corrente una scorta per le spese e mette il resto su un deposito, magari vincolato fino alla data dell’acquisto.' },
      { t: 'Investe tutto in azioni per due anni', ok: false, f: 'Con un orizzonte così breve un calo dei mercati potrebbe mettere a rischio l’acquisto della casa.' },
    ] },
    { s: 'Ugo, 70 anni, ha 250.000 € su un unico conto nella stessa banca. Legge che la garanzia sui depositi ha un limite e si preoccupa.', q: 'Qual è la scelta più prudente?', o: [
      { t: 'Distribuire la somma su più banche', ok: true, f: 'Con conti in tre banche diverse resta sotto i 100.000 € per banca e tutta la somma rientra nella garanzia.' },
      { t: 'Non fare nulla: le banche non falliscono', ok: false, f: 'Le crisi bancarie sono rare ma possibili: oltre 100.000 € per banca la somma non è garantita.' },
      { t: 'Prelevare tutto in contanti', ok: false, f: 'Il contante in casa è esposto a furti e smarrimenti, e non produce alcun interesse.' },
    ] },
    { s: 'Elisa, 27 anni, ha 8.000 € che le serviranno tra 6 mesi per pagare un master. Una banca le offre un deposito vincolato a 24 mesi con un tasso più alto.', q: 'Cosa sceglie?', o: [
      { t: 'Il vincolo a 24 mesi, poi svincola', ok: false, f: 'Svincolando dopo 6 mesi perderebbe in genere parte o tutti gli interessi: il tasso alto resterebbe solo sulla carta.' },
      { t: 'Un deposito libero o vincolato a 6 mesi', ok: true, f: 'La durata deve coincidere con quando servono i soldi: meglio un tasso un po’ più basso ma senza penalità.' },
      { t: 'Tiene tutto in contanti fino al master', ok: false, f: 'Perde gli interessi e corre rischi di furto o smarrimento senza alcun vantaggio.' },
    ] },
    { s: 'Fabio, 44 anni, confronta due conti. A: canone zero, ma 2 € a bonifico e 1,50 € a prelievo. B: canone di 4 € al mese con operazioni incluse. Fa 4 bonifici e 4 prelievi al mese.', q: 'Quale conviene?', o: [
      { t: 'Il conto A, perché il canone è zero', ok: false, f: 'Con il suo uso spenderebbe 4 × 2 + 4 × 1,50 = 14 € al mese: molto più dei 4 € del conto B.' },
      { t: 'Sono equivalenti', ok: false, f: 'Basta fare i conti: 14 € contro 4 € al mese, cioè 120 € l’anno di differenza.' },
      { t: 'Il conto B', ok: true, f: 'Giusto: il costo dipende da come usi il conto. L’ISC aiuta a confrontare i conti per profili di utilizzo.' },
    ] },
  ],
  tip: 'Tieni sul conto corrente solo ciò che ti serve per le spese, verifica che la banca aderisca a un fondo di garanzia e confronta i rendimenti al netto di ritenuta e bollo.',
});
