FQC(9, {
  intro: 'Nessun guadagno è gratis: scopri perché rischio e rendimento camminano insieme e come capire quanto rischio puoi sopportare.',
  cards: [
    { t: 'Il patto rischio-rendimento', x: 'Per sperare in un rendimento più alto devi accettare più incertezza. Non esiste un investimento con rendimento alto e rischio nullo: se qualcuno lo promette, diffida.', v: { k: 'scale', a: 'Rischio e rendimento atteso bassi', b: 'Rischio e rendimento atteso alti', d: [['Conto deposito', 8], ['Titoli di Stato a breve', 20], ['Obbligazioni', 40], ['Azioni', 75], ['Criptovalute', 95]] } },
    { t: 'Che cos’è il rischio', x: 'In finanza rischio significa incertezza: il risultato effettivo può essere diverso da quello atteso, in meglio o in peggio. Più ampie sono le oscillazioni, più alto è il rischio.', v: { k: 'vs', a: ['Rendimento atteso', 'Quanto speri di guadagnare in media'], b: ['Rischio', 'Quanto il risultato può allontanarsi, anche in perdita'] } },
    { t: 'Stessa media, rischio diverso', x: 'A rende 4% e 4%; B rende +20% e −12%. La media aritmetica è 4% per entrambi, ma B oscilla molto di più. Dopo due anni 100 € diventano 108,16 € con A e solo 105,60 € con B.', v: { k: 'bars', d: [['A, anno 1', 4], ['A, anno 2', 4], ['B, anno 1', 20], ['B, anno 2', -12]], u: '%' } },
    { t: 'Il rendimento di un mix', x: 'Se combini strumenti diversi, il rendimento atteso è la media dei rendimenti pesata per quanto hai messo in ciascuno. Con 60% al 6% e 40% al 2% ottieni il 4,4%.', v: { k: 'formula', f: 'Rendimento atteso = Σ (peso × rendimento di ogni parte)', n: 'Es.: 60% × 6% + 40% × 2% = 4,4%' } },
    { t: 'I volti del rischio', x: 'Il rischio non è solo vedere scendere un prezzo. Chi ha emesso il titolo può non rimborsarti, potresti non riuscire a vendere quando vuoi, o guadagnare meno dell’aumento dei prezzi.', v: { k: 'icons', d: [['📉', 'Mercato: i prezzi scendono'], ['🏚️', 'Credito: chi deve pagare non paga'], ['🔒', 'Liquidità: non riesci a vendere'], ['🎈', 'Inflazione: perdi potere d’acquisto']] } },
    { t: 'Le perdite pesano doppio', x: 'Se 1.000 € scendono a 500 €, per tornare a 1.000 € serve un +100%. Per questo non conta solo quanto puoi guadagnare, ma anche quanto potresti perdere.', v: { k: 'stat', n: '+100%', l: 'rialzo necessario per recuperare un calo del 50%' } },
  ],
  terms: [
    ['Rischio', 'Possibilità che il risultato di un investimento sia diverso da quello atteso.'],
    ['Rendimento atteso', 'Guadagno medio che si prevede di ottenere, senza alcuna garanzia.'],
    ['Volatilità', 'Ampiezza delle oscillazioni di un prezzo o di un rendimento nel tempo.'],
    ['Tolleranza al rischio', 'Quanto ti senti a tuo agio, sul piano emotivo, con perdite temporanee.'],
    ['Capacità di rischio', 'Quanta perdita puoi sostenere senza compromettere i tuoi obiettivi e la tua vita.'],
    ['Rischio di credito', 'Possibilità che chi ha emesso un titolo non paghi gli interessi o non rimborsi il capitale.'],
    ['Premio per il rischio', 'Rendimento extra richiesto per accettare un investimento più incerto.'],
    ['Drawdown', 'Calo dal punto più alto al punto più basso del valore di un investimento.'],
  ],
  tf: [
    ['Un rendimento atteso più alto richiede, in genere, di accettare un rischio più alto.', true, 'Chi investe pretende un compenso extra per sopportare più incertezza: è il premio per il rischio.'],
    ['Esistono investimenti con rendimenti elevati e garantiti, senza alcun rischio.', false, 'Rendimento alto e rischio zero non vanno insieme: chi lo promette sta nascondendo qualcosa.'],
    ['Volatilità alta significa che il prezzo oscilla molto.', true, 'La volatilità misura l’ampiezza dei movimenti, verso l’alto e verso il basso.'],
    ['Se un investimento è salito molto negli ultimi anni, continuerà sicuramente a salire.', false, 'I rendimenti passati non garantiscono quelli futuri: anche ciò che è salito molto può scendere.'],
    ['Dopo un calo del 50%, serve un guadagno del 100% per tornare al valore iniziale.', true, 'Da 1.000 € a 500 € si perde il 50%; per tornare a 1.000 € bisogna raddoppiare i 500 €.'],
    ['Il rischio riguarda solo le azioni: obbligazioni e conti non hanno alcun rischio.', false, 'Le obbligazioni hanno rischio di credito e di prezzo; anche la liquidità subisce l’inflazione.'],
    ['Un portafoglio diviso a metà tra uno strumento al 6% e uno al 2% ha un rendimento atteso del 4%.', true, '50% × 6% + 50% × 2% = 4%: è la media pesata.'],
    ['Tolleranza e capacità di rischio sono la stessa cosa.', false, 'La tolleranza è emotiva; la capacità dipende da reddito, patrimonio, obiettivi e tempi.'],
    ['Anche tenere tutto in liquidità comporta un rischio: quello dell’inflazione.', true, 'Il saldo non oscilla, ma il suo potere d’acquisto può diminuire anno dopo anno.'],
    ['Un investimento più rischioso garantisce sempre un rendimento più alto.', false, 'Più rischio significa un rendimento atteso più alto, non garantito: il risultato può essere anche una perdita.'],
  ],
  mcq: [
    { q: 'Quale di questi investimenti ha, di solito, il rischio più alto?', a: 'Le azioni di una piccola società', w: ['Un conto deposito libero', 'Un titolo di Stato a 6 mesi', 'Un fondo monetario in euro'], e: 'Una singola azione di una piccola società può oscillare molto e anche perdere quasi tutto il suo valore.' },
    { q: 'Portafoglio: 70% azioni con rendimento atteso del 7% e 30% obbligazioni al 3%. Qual è il rendimento atteso?', a: '5,8%', w: ['5,0%', '10,0%', '4,2%'], e: '0,7 × 7% + 0,3 × 3% = 4,9% + 0,9% = 5,8%.' },
    { q: 'Che cosa misura la volatilità?', a: 'Quanto oscillano prezzi o rendimenti', w: ['Il costo annuo di un investimento', 'Il numero di azionisti di una società', 'La durata di un titolo'], e: 'Più un prezzo si muove su e giù, più è volatile e meno prevedibile è il risultato.' },
    { q: 'Un amico ti promette il 20% l’anno garantito e senza rischi. Che cosa ne pensi?', a: 'È un segnale d’allarme', w: ['È un’occasione da cogliere', 'È normale per le obbligazioni', 'È tipico dei conti deposito'], e: 'Rendimenti alti e garantiti non esistono: promesse così sono tipiche delle truffe.' },
    { q: 'Un investimento passa da 10.000 € a 7.000 €. Quale rialzo serve per tornare a 10.000 €?', a: 'Circa +43%', w: ['+30%', '+70%', '+3%'], e: '10.000 ÷ 7.000 ≈ 1,43: serve circa +43%, più del 30% perso.' },
    { q: 'Qual è la differenza tra tolleranza e capacità di rischio?', a: 'Una è emotiva, l’altra oggettiva', w: ['Sono due nomi dello stesso concetto', 'Una riguarda le banche, l’altra lo Stato', 'Una si misura in euro, l’altra in anni'], e: 'Puoi sentirti tranquillo davanti alle perdite ma non potertele permettere, o il contrario.' },
    { q: 'Perché un titolo più rischioso dovrebbe offrire un rendimento atteso più alto?', a: 'Per compensare l’incertezza in più', w: ['Perché costa sempre meno degli altri', 'Perché lo impone la CONSOB', 'Perché gode di tasse più basse'], e: 'Nessuno accetterebbe più rischio senza la prospettiva di un compenso maggiore: è il premio per il rischio.' },
    { q: 'Laura dice: “Tengo tutto sul conto, così non corro nessun rischio”. Che cosa trascura?', a: 'Il rischio di perdere potere d’acquisto', w: ['Il rischio di cambio', 'Il rischio di credito dello Stato', 'Il rischio di oscillazione delle azioni'], e: 'Se l’inflazione supera il rendimento del conto, i suoi soldi comprano ogni anno un po’ meno.' },
  ],
  fill: [
    { s: 'In finanza, il ___ è la possibilità che il risultato sia diverso da quello atteso.', a: 'rischio', w: ['rendimento', 'capitale', 'dividendo'] },
    { s: 'L’ampiezza delle oscillazioni di un prezzo si chiama ___.', a: 'volatilità', w: ['liquidità', 'inflazione', 'solvibilità'] },
    { s: 'Per recuperare un calo del 50% serve un rialzo del ___.', a: '100%', w: ['50%', '25%', '150%'] },
    { s: 'Un rendimento atteso più alto comporta, in genere, un rischio più ___.', a: 'alto', w: ['basso', 'stabile', 'garantito'] },
    { s: 'La ___ al rischio indica quanto ti senti a tuo agio con le perdite temporanee.', a: 'tolleranza', w: ['avversione', 'esposizione', 'immunità'] },
  ],
  order: [
    { q: 'Ordina dal rischio più basso al più alto', i: ['Conto deposito', 'Titolo di Stato a breve termine', 'Obbligazioni societarie', 'ETF azionario globale', 'Azioni di una sola società'], e: 'Salendo nella scala crescono le oscillazioni possibili e il rischio di perdite, insieme al rendimento atteso.' },
    { q: 'Con azioni al 7% e obbligazioni al 3% di rendimento atteso, ordina dal rendimento atteso più basso al più alto', i: ['100% obbligazioni', '20% azioni e 80% obbligazioni', '50% azioni e 50% obbligazioni', '80% azioni e 20% obbligazioni', '100% azioni'], e: 'I rendimenti attesi sono 3%, 3,8%, 5%, 6,2% e 7%: più azioni significa più rendimento atteso, ma anche più oscillazioni.' },
  ],
  cat: [
    { q: 'Tolleranza al rischio o capacità di rischio?', g: [['Tolleranza', ['Dormi male se il portafoglio perde il 10%', 'Le oscillazioni non ti agitano', 'Dopo un calo venderesti tutto per paura']], ['Capacità', ['Hai un reddito stabile e sicuro', 'Ti serviranno i soldi tra un anno', 'Hai un fondo di emergenza completo']]] },
    { q: 'Segnale d’allarme o caratteristica normale di un investimento?', g: [['Segnale d’allarme', ['Rendimento alto garantito', 'Guadagni elevati “senza rischi”', 'Pressione a decidere subito']], ['Normale', ['Prezzo che oscilla nel tempo', 'Più rendimento atteso con più rischio', 'Possibili perdite temporanee']]] },
  ],
  scen: [
    { s: 'Nicoletta, 28 anni, ha 10.000 € che le serviranno tra un anno per il matrimonio. Un amico le consiglia le azioni “perché rendono di più”.', q: 'Cosa fa?', o: [
      { t: 'Investe tutto in azioni', ok: false, f: 'In un anno le azioni possono anche perdere il 20% o più: rischierebbe di non avere i soldi quando servono.' },
      { t: 'Sceglie strumenti a basso rischio', ok: true, f: 'Giusto: con un orizzonte di un anno la priorità è avere la somma intatta, non massimizzare il rendimento.' },
      { t: 'Prova con le criptovalute per guadagnare di più', ok: false, f: 'Strumenti molto volatili sono incompatibili con soldi che servono a breve.' },
    ] },
    { s: 'Gabriele, 40 anni, investe per la pensione. In un mese il suo portafoglio perde il 15% e lui è tentato di vendere tutto per “salvare il salvabile”.', q: 'Qual è la scelta più ragionata?', o: [
      { t: 'Vendere subito tutto', ok: false, f: 'Vendere dopo un calo trasforma una perdita temporanea in una perdita definitiva, spesso nel momento peggiore.' },
      { t: 'Rivedere obiettivi e orizzonte prima di agire', ok: true, f: 'Se obiettivi e tempi non sono cambiati, le oscillazioni erano prevedibili. Se il calo gli toglie il sonno, può ridurre il rischio con calma.' },
      { t: 'Indebitarsi per comprare di più', ok: false, f: 'Usare debiti per investire amplifica le perdite: un rischio che va ben oltre le sue intenzioni.' },
    ] },
    { s: 'Paola, 50 anni, confronta due investimenti. A ha un rendimento atteso del 5% con oscillazioni moderate; B del 5,5%, ma in passato è sceso anche del 40%. Lei sa che venderebbe in preda al panico dopo un −15%.', q: 'Cosa sceglie?', o: [
      { t: 'B, perché rende di più', ok: false, f: 'Lo 0,5% in più non vale cali che non riuscirebbe a sopportare: rischierebbe di vendere al momento peggiore.' },
      { t: 'Metà A e metà B', ok: false, f: 'Ridurrebbe il problema, ma un calo forte di B la spingerebbe comunque a vendere in perdita.' },
      { t: 'A, coerente con la sua tolleranza', ok: true, f: 'Un investimento che riesci a mantenere nei momenti difficili vale più di uno che rende un po’ di più sulla carta.' },
    ] },
    { s: 'Vittorio, 65 anni, riceve la proposta di un’obbligazione che rende il 9% l’anno, mentre i titoli di Stato con la stessa scadenza rendono circa il 3%.', q: 'Come la valuta?', o: [
      { t: 'Investe subito: è un’obbligazione, quindi è sicura', ok: false, f: 'Anche le obbligazioni hanno rischi: chi le emette può non pagare interessi o non rimborsare il capitale.' },
      { t: 'Si chiede perché paghi così tanto', ok: true, f: 'Un rendimento molto più alto segnala un rischio molto più alto, spesso di credito. Va capito chi è l’emittente prima di decidere.' },
      { t: 'Ci mette tutti i suoi risparmi per avere più cedole', ok: false, f: 'Concentrare tutto su un emittente rischioso potrebbe compromettere la sua pensione.' },
    ] },
  ],
  tip: 'Davanti a ogni investimento chiediti prima “quanto posso perdere?” e solo dopo “quanto posso guadagnare?”.',
});
