FQC(10, {
  intro: 'Senza una meta ogni strada sembra giusta: impara a fissare obiettivi chiari e a scegliere strumenti adatti a quando ti serviranno i soldi.',
  cards: [
    { t: 'Obiettivi SMART', x: '“Risparmiare di più” è un desiderio. “Mettere da parte 3.000 € per un viaggio entro 18 mesi” è un obiettivo: specifico, misurabile, raggiungibile, rilevante per te e con una scadenza.', v: { k: 'steps', s: ['Specifico', 'Misurabile', 'Raggiungibile', 'Rilevante', 'Temporizzato'] } },
    { t: 'Tre orizzonti', x: 'Una vacanza, un’auto, la pensione: ogni obiettivo ha la sua scadenza. Più è lontana, più tempo hai per assorbire eventuali cali temporanei degli investimenti.', v: { k: 'icons', d: [['🏖️', 'Breve: entro 3 anni'], ['🚗', 'Medio: da 3 a 10 anni'], ['🏡', 'Lungo: oltre 10 anni']] } },
    { t: 'Quanto mettere da parte', x: 'È il calcolo di base, senza rendimenti. Se l’obiettivo è lontano e i soldi possono crescere nel frattempo, la cifra mensile necessaria può essere più bassa.', v: { k: 'formula', f: 'Risparmio mensile = obiettivo ÷ mesi disponibili', n: 'Es.: 6.000 € ÷ 24 mesi = 250 € al mese' } },
    { t: 'Orizzonte e rischio', x: 'I soldi che ti servono presto non dovrebbero stare in strumenti che possono perdere molto. Sul lungo periodo puoi accettare oscillazioni maggiori in cambio di un rendimento atteso più alto.', v: { k: 'scale', a: 'Orizzonte breve: poco rischio', b: 'Orizzonte lungo: più rischio sostenibile', d: [['Vacanza tra 1 anno', 10], ['Auto tra 4 anni', 35], ['Casa tra 8 anni', 55], ['Pensione tra 30 anni', 85]] } },
    { t: 'Il tempo lavora per te', x: 'Con 200 € al mese e un rendimento ipotetico costante del 4% annuo, dopo 10 anni hai circa 29.450 €; dopo 30 anni circa 138.800 €, quasi il doppio di quanto versato. Il tempo moltiplica l’effetto.', v: { k: 'bars', d: [['Versato in 10 anni', 24000], ['Valore a 10 anni', 29450], ['Versato in 30 anni', 72000], ['Valore a 30 anni', 138810]], u: '€' } },
    { t: 'Rivedi il piano', x: 'La vita cambia: un nuovo lavoro, un figlio, un trasloco. Controlla obiettivi e risparmi almeno una volta l’anno e ogni volta che succede qualcosa di importante, adeguando cifre e scadenze.', v: { k: 'stat', n: '1 volta l’anno', l: 'il controllo minimo di obiettivi e risparmi' } },
  ],
  terms: [
    ['Obiettivo finanziario', 'Traguardo economico con un importo preciso e una scadenza.'],
    ['Orizzonte temporale', 'Tempo che manca al momento in cui ti serviranno i soldi.'],
    ['SMART', 'Criteri per un buon obiettivo: specifico, misurabile, raggiungibile, rilevante, con scadenza.'],
    ['Breve termine', 'Orizzonte di pochi anni, in genere fino a circa 3.'],
    ['Lungo termine', 'Orizzonte di molti anni, in genere oltre 10, come per la pensione.'],
    ['Accantonamento', 'Somma messa da parte con regolarità per raggiungere un obiettivo.'],
    ['Approccio a secchielli', 'Metodo che divide i risparmi in gruppi distinti in base a quando serviranno.'],
    ['Revisione del piano', 'Controllo periodico di obiettivi, risparmi e scadenze per adeguarli alla tua vita.'],
  ],
  tf: [
    ['“Voglio risparmiare di più” è un obiettivo SMART.', false, 'Manca tutto: quanto, entro quando e per cosa. Senza cifra e scadenza non puoi misurare i progressi.'],
    ['I soldi che ti servono tra un anno non dovrebbero stare in strumenti molto volatili.', true, 'In un anno non c’è tempo per recuperare un calo: serve stabilità più che rendimento.'],
    ['Per mettere da parte 4.800 € in 2 anni servono 200 € al mese, senza contare i rendimenti.', true, '4.800 ÷ 24 mesi = 200 € al mese.'],
    ['L’orizzonte temporale è il tempo che hai già passato a investire.', false, 'È il tempo che manca al momento in cui userai i soldi: si guarda avanti, non indietro.'],
    ['Più un obiettivo è lontano, più tempo hai per recuperare eventuali cali temporanei.', true, 'Per questo sugli orizzonti lunghi si può accettare più oscillazione in cambio di un rendimento atteso maggiore.'],
    ['Tutti gli obiettivi dovrebbero usare lo stesso strumento di risparmio.', false, 'Obiettivi con scadenze diverse richiedono strumenti diversi: sicuri per il breve, più dinamici per il lungo.'],
    ['Per un obiettivo lontano conviene tenere conto anche dell’inflazione futura.', true, 'Tra molti anni la stessa cosa costerà probabilmente di più: l’obiettivo va stimato in euro di domani.'],
    ['Una volta fissato, un piano finanziario non va più modificato.', false, 'Il piano va rivisto quando cambiano reddito, famiglia o priorità, e comunque periodicamente.'],
    ['Investire a lungo termine elimina del tutto il rischio di perdere.', false, 'Il tempo aiuta a superare i cali, ma non offre garanzie: il rischio si riduce, non sparisce.'],
    ['Dare una scadenza a un obiettivo aiuta a calcolare quanto risparmiare ogni mese.', true, 'Importo ÷ mesi disponibili: senza scadenza questo calcolo è impossibile.'],
  ],
  mcq: [
    { q: 'Quale di questi è un obiettivo SMART?', a: '3.000 € per un corso entro 15 mesi', w: ['Risparmiare di più a partire da subito', 'Diventare ricco prima o poi', 'Spendere meno in cose inutili'], e: 'Ha un importo, uno scopo e una scadenza: puoi calcolare quanto risparmiare e misurare i progressi.' },
    { q: 'Vuoi 9.000 € tra 3 anni. Quanto devi mettere da parte al mese, senza rendimenti?', a: '250 €', w: ['300 €', '3.000 €', '90 €'], e: '3 anni = 36 mesi; 9.000 ÷ 36 = 250 € al mese.' },
    { q: 'Ti servono 15.000 € tra 18 mesi per l’anticipo della casa. Quale scelta è più coerente?', a: 'Strumenti a basso rischio e disponibili', w: ['Un ETF azionario dei Paesi emergenti', 'Criptovalute per farli crescere in fretta', 'Le azioni di una sola società'], e: 'Con un orizzonte breve e una data precisa, un calo dei mercati potrebbe far saltare l’acquisto.' },
    { q: 'Quale obiettivo ha l’orizzonte temporale più lungo?', a: 'La pensione di un trentenne', w: ['Le vacanze della prossima estate', 'Il cambio dell’auto tra 4 anni', 'Un corso di inglese in autunno'], e: 'Mancano circa 35 anni: è il classico obiettivo di lungo termine.' },
    { q: 'Perché un orizzonte lungo permette di accettare più oscillazioni?', a: 'C’è tempo per recuperare eventuali cali', w: ['Le perdite diventano impossibili', 'Le tasse si azzerano con il passare del tempo', 'La banca garantisce sempre il capitale'], e: 'Un calo temporaneo pesa meno se non devi usare i soldi a breve. Ma il recupero non è mai garantito.' },
    { q: 'Quale ordine di priorità è, in generale, il più prudente?', a: 'Fondo di emergenza, poi investimenti', w: ['Investimenti, poi fondo di emergenza', 'Vacanze, poi fondo di emergenza', 'Solo investimenti, nessun fondo'], e: 'Senza una riserva, il primo imprevisto ti costringerebbe a vendere gli investimenti o a indebitarti.' },
    { q: 'Che cosa prevede l’approccio a secchielli?', a: 'Dividere i risparmi in base a quando serviranno', w: ['Investire tutto in un unico strumento finanziario', 'Spendere prima i risparmi più vecchi', 'Tenere i contanti di casa in buste separate'], e: 'Ogni secchiello ha il suo orizzonte e il suo livello di rischio: sicuro per il breve, più dinamico per il lungo.' },
    { q: 'Marco dice: “Investo a lungo termine, quindi non posso perdere”. Che cosa c’è di sbagliato?', a: 'Il tempo riduce il rischio, non lo elimina', w: ['Nulla: dopo 10 anni si guadagna sempre', 'Nulla: il rischio riguarda solo il trading', 'Il lungo termine vale solo per i depositi'], e: 'Un orizzonte lungo aiuta a superare i cali, ma nessun periodo garantisce un risultato positivo.' },
  ],
  fill: [
    { s: 'Il tempo che manca al momento in cui ti serviranno i soldi si chiama orizzonte ___.', a: 'temporale', w: ['fiscale', 'contabile', 'bancario'] },
    { s: 'Nella sigla SMART, la T indica che l’obiettivo deve avere una ___.', a: 'scadenza', w: ['tassa', 'garanzia', 'banca'] },
    { s: 'Per un obiettivo a ___ termine sono adatti strumenti sicuri e liquidi.', a: 'breve', w: ['lungo', 'lunghissimo', 'medio-lungo'] },
    { s: 'Per mettere da parte 12.000 € in 5 anni servono ___ € al mese, senza rendimenti.', a: '200', w: ['240', '2.400', '120'] },
    { s: 'È buona norma ___ il piano almeno una volta l’anno.', a: 'rivedere', w: ['abbandonare', 'nascondere', 'raddoppiare'] },
  ],
  order: [
    { q: 'Ordina gli obiettivi dall’orizzonte più breve al più lungo', i: ['Regali di Natale tra 3 mesi', 'Vacanza tra 1 anno', 'Auto nuova tra 4 anni', 'Università dei figli tra 12 anni', 'Pensione tra 30 anni'], e: 'Più la scadenza è lontana, più l’orizzonte è lungo e più rischio si può, in genere, sostenere.' },
    { q: 'Senza rendimenti, ordina dal risparmio mensile necessario più basso al più alto', i: ['2.400 € in 24 mesi', '3.000 € in 20 mesi', '6.000 € in 30 mesi', '9.000 € in 36 mesi', '6.000 € in 20 mesi'], e: 'Le quote mensili sono 100, 150, 200, 250 e 300 €: contano sia l’importo sia il tempo disponibile.' },
  ],
  cat: [
    { q: 'Breve o lungo termine?', g: [['Breve termine', ['Vacanza estiva', 'Corso di formazione tra 6 mesi', 'Nuovo computer tra un anno']], ['Lungo termine', ['Pensione', 'Università dei figli ancora piccoli', 'Acquisto della casa tra 15 anni']]] },
    { q: 'Obiettivo SMART o desiderio vago?', g: [['SMART', ['4.000 € per l’auto entro 2 anni', '1.200 € per un viaggio in 12 mesi', 'Fondo di 6.000 € entro 30 mesi']], ['Desiderio vago', ['Risparmiare di più', 'Sistemarmi un giorno', 'Avere più soldi da parte']]] },
  ],
  scen: [
    { s: 'Rebecca, 26 anni, vuole comprare un’auto da 8.000 € tra 2 anni e, nel frattempo, iniziare a risparmiare per la pensione. Ha già un fondo di emergenza.', q: 'Come organizza i risparmi?', o: [
      { t: 'Separa i due obiettivi con strumenti diversi', ok: true, f: 'Giusto: i soldi dell’auto vanno su strumenti sicuri, quelli per la pensione possono sostenere più rischio. Ogni secchiello ha il suo orizzonte.' },
      { t: 'Mette tutto in azioni, rendono di più', ok: false, f: 'Un calo dei mercati tra due anni potrebbe lasciarla senza i soldi per l’auto.' },
      { t: 'Tiene tutto sul conto corrente', ok: false, f: 'Va bene per l’auto, ma per un obiettivo a 40 anni rinuncia a crescita e protezione dall’inflazione.' },
    ] },
    { s: 'Mattia, 35 anni, vuole 24.000 € per l’anticipo di una casa tra 4 anni. Riesce a risparmiare solo 300 € al mese, cioè 14.400 € in 4 anni.', q: 'Cosa fa?', o: [
      { t: 'Investe in strumenti molto rischiosi per recuperare', ok: false, f: 'Con 4 anni di orizzonte potrebbe perdere proprio i soldi dell’anticipo: troppo rischio per il tempo che ha.' },
      { t: 'Rivede scadenza, importo o risparmio mensile', ok: true, f: 'Bene: può allungare i tempi a circa 6-7 anni, cercare una casa che richieda un anticipo minore o aumentare il risparmio.' },
      { t: 'Rinuncia del tutto all’obiettivo', ok: false, f: 'Un obiettivo irrealistico si ricalibra, non si abbandona: 14.400 € sono già un ottimo inizio.' },
    ] },
    { s: 'Ornella, 58 anni, investe da anni per la pensione, che arriverà a 67. Il suo portafoglio è quasi tutto in azioni.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Aumentare le azioni per accelerare', ok: false, f: 'Con meno anni davanti, un forte calo vicino alla pensione avrebbe poco tempo per essere recuperato.' },
      { t: 'Vendere tutto oggi e tenere i contanti', ok: false, f: 'Mancano ancora 9 anni: passare di colpo al contante la esporrebbe all’inflazione e rinuncerebbe alla crescita.' },
      { t: 'Ridurre gradualmente il rischio', ok: true, f: 'Man mano che la scadenza si avvicina, l’orizzonte si accorcia: ha senso spostare un po’ alla volta verso strumenti più stabili.' },
    ] },
    { s: 'Caterina, 40 anni, può risparmiare 400 € al mese. Ha tre obiettivi: completare il fondo di emergenza (le mancano 2.000 €), una vacanza tra 6 mesi e la pensione.', q: 'Come divide i 400 €?', o: [
      { t: 'Tutto alla pensione, la priorità più grande', ok: false, f: 'Senza fondo completo, un imprevisto la costringerebbe a toccare i risparmi per la pensione o a indebitarsi.' },
      { t: 'Prima il fondo, poi quote per gli altri obiettivi', ok: true, f: 'Bene: completa la rete di sicurezza in pochi mesi, poi assegna una quota a ogni obiettivo secondo scadenza e importanza.' },
      { t: 'Tutto alla vacanza, che è la più vicina', ok: false, f: 'La scadenza vicina conta, ma il fondo di emergenza protegge tutti gli altri obiettivi: viene prima.' },
    ] },
  ],
  tip: 'Dai a ogni obiettivo un nome, un importo e una data, e tienilo in un “secchiello” separato: saprai sempre quanto rischio puoi permetterti.',
});
