FQC(11, {
  intro: 'Scopri dove si incontrano chi ha risparmi da investire e chi cerca capitali, e perché i mercati finanziari muovono l’economia.',
  cards: [
    { t: 'Dal risparmio agli investimenti', x: 'Un mercato finanziario mette in contatto chi ha risparmi in eccesso (famiglie, investitori) con chi ha bisogno di capitali (imprese, Stati). Così il risparmio diventa investimento produttivo: fabbriche, strade, ricerca.', v: { k: 'steps', s: ['Le famiglie risparmiano', 'Comprano titoli', 'Imprese e Stati ricevono capitali', 'Nascono investimenti e crescita'] } },
    { t: 'Finanza diretta e indiretta', x: 'Con il conto in banca il risparmio passa da un intermediario che decide a chi prestarlo. Sul mercato invece compri direttamente titoli emessi da aziende o Stati, e il rischio dell’emittente ricade su di te.', v: { k: 'vs', a: ['Finanza indiretta', 'Depositi in banca: la banca presta i fondi'], b: ['Finanza diretta', 'Compri tu azioni o obbligazioni'] } },
    { t: 'A cosa servono i mercati', x: 'I mercati raccolgono capitali, formano i prezzi attraverso domanda e offerta, permettono di rivendere i titoli (liquidità) e di trasferire i rischi a chi è disposto a sopportarli.', v: { k: 'icons', d: [['💰', 'Raccolta di capitali'], ['🏷️', 'Formazione dei prezzi'], ['💧', 'Liquidità'], ['🛡️', 'Gestione del rischio']] } },
    { t: 'Monetario o dei capitali', x: 'Il mercato monetario scambia strumenti a breve termine, con scadenza entro 12 mesi, come i BOT. Il mercato dei capitali scambia strumenti a medio-lungo termine: azioni e obbligazioni pluriennali come i BTP.', v: { k: 'stat', n: '12 mesi', l: 'confine tra mercato monetario e mercato dei capitali' } },
    { t: 'Regolamentati e OTC', x: 'Nei mercati regolamentati, come Euronext Milan, gli scambi seguono regole comuni e i prezzi sono pubblici. Negli scambi OTC (over the counter) le parti trattano direttamente tra loro, con meno trasparenza.', v: { k: 'vs', a: ['Mercato regolamentato', 'Regole comuni e prezzi pubblici'], b: ['OTC', 'Accordo diretto tra le parti'] } },
    { t: 'Quanto vale un’azienda in borsa', x: 'La capitalizzazione è il valore di mercato di una società quotata: prezzo di un’azione per numero di azioni. Cambia ogni volta che cambia il prezzo, cioè di continuo durante la seduta.', v: { k: 'formula', f: 'Capitalizzazione = prezzo × numero di azioni', n: 'Es.: 12 € × 500 milioni di azioni = 6 miliardi €' } },
  ],
  terms: [
    ['Mercato finanziario', 'Insieme di luoghi e sistemi in cui si emettono e si scambiano strumenti finanziari.'],
    ['Emittente', 'Chi crea e vende un titolo per raccogliere capitali: un’impresa, uno Stato, un ente pubblico.'],
    ['Strumento finanziario', 'Contratto negoziabile con diritti economici: azioni, obbligazioni, quote di fondi, derivati.'],
    ['Mercato monetario', 'Segmento in cui si scambiano strumenti a breve termine, con scadenza entro 12 mesi.'],
    ['Mercato dei capitali', 'Segmento degli strumenti a medio-lungo termine, come azioni e obbligazioni pluriennali.'],
    ['OTC', 'Scambi conclusi direttamente tra due parti, fuori da un mercato regolamentato.'],
    ['Formazione del prezzo', 'Processo con cui l’incontro tra molti compratori e venditori determina il valore di scambio di un titolo.'],
    ['Investitore istituzionale', 'Operatore professionale che investe grandi somme: fondi, assicurazioni, fondi pensione.'],
  ],
  tf: [
    ['Un mercato finanziario serve a trasferire risorse da chi risparmia a chi ha bisogno di capitali.', true, 'È la sua funzione principale: il risparmio di famiglie e investitori finanzia imprese e Stati che vogliono investire.'],
    ['Oggi a Piazza Affari gli operatori gridano ancora gli ordini in sala per concludere gli scambi.', false, 'Le contrattazioni “alle grida” sono finite da decenni: oggi gli scambi avvengono su piattaforme elettroniche.'],
    ['Il mercato azionario è un gioco a somma zero: se qualcuno guadagna, un altro perde la stessa cifra.', false, 'Le aziende producono utili e possono crescere: nel tempo il valore complessivo può aumentare, a vantaggio di molti azionisti.'],
    ['Un BOT a 6 mesi appartiene al mercato monetario.', true, 'Il mercato monetario comprende gli strumenti con scadenza entro 12 mesi: i BOT ne sono l’esempio italiano più noto.'],
    ['Un BTP a 10 anni fa parte del mercato monetario.', false, 'Con una scadenza oltre i 12 mesi appartiene al mercato dei capitali; il monetario riguarda solo gli strumenti a breve.'],
    ['Negli scambi OTC le parti trattano direttamente tra loro e i prezzi sono di solito meno trasparenti.', true, 'Fuori da un mercato regolamentato non c’è un prezzo pubblico unico: confrontare le condizioni diventa più difficile.'],
    ['Il prezzo di un titolo quotato viene fissato ogni mattina dalla società che gestisce la borsa.', false, 'Il prezzo nasce dall’incontro tra ordini di acquisto e di vendita: la borsa organizza gli scambi, non decide i prezzi.'],
    ['Se non ci fosse un modo per rivendere i titoli, gli investitori sarebbero meno disposti a finanziare le imprese.', true, 'Poter rivendere riduce il rischio di restare bloccati: per questo la liquidità dei mercati facilita la raccolta di capitali.'],
    ['La borsa è solo un casinò: i prezzi non hanno alcun legame con le aziende.', false, 'Nel breve i prezzi oscillano molto, ma nel lungo periodo tendono a riflettere utili e prospettive delle aziende reali.'],
    ['Comprando un’obbligazione presti denaro all’emittente, comprando un’azione ne diventi socio.', true, 'L’obbligazionista è un creditore con diritto a interessi e rimborso; l’azionista è un proprietario che partecipa a utili e rischi.'],
  ],
  mcq: [
    { q: 'Qual è la funzione principale di un mercato finanziario?', a: 'Collegare chi risparmia e chi cerca capitali', w: ['Stampare nuova moneta per sostenere l’economia', 'Garantire un guadagno sicuro a chi investe', 'Fissare i tassi dei mutui delle banche'], e: 'Il mercato collega risparmio e investimento. Non crea moneta (lo fa la banca centrale) e non garantisce alcun guadagno.' },
    { q: 'Quale strumento appartiene al mercato monetario?', a: 'Un BOT a 12 mesi', w: ['Un BTP a 10 anni', 'Un’azione di una banca', 'Un’obbligazione a 7 anni'], e: 'Il mercato monetario riguarda le scadenze fino a 12 mesi. Azioni e obbligazioni pluriennali fanno parte del mercato dei capitali.' },
    { q: 'Che cosa indica la sigla OTC?', a: 'Scambi diretti tra le parti, fuori dalla borsa', w: ['Ordini trasmessi con commissioni ridotte', 'Titoli emessi solo per investitori esteri', 'Operazioni chiuse entro la stessa giornata'], e: 'Over the counter: “al banco”. Le parti trattano direttamente, senza il book pubblico di una borsa.' },
    { q: 'Un’azienda ha 200 milioni di azioni che valgono 15 € l’una. Qual è la sua capitalizzazione?', a: '3 miliardi di euro', w: ['300 milioni di euro', '30 miliardi di euro', '215 milioni di euro'], e: '200 milioni × 15 € = 3.000 milioni, cioè 3 miliardi di euro.' },
    { q: 'Chi tra questi è un emittente?', a: 'Il Tesoro che colloca nuovi BTP', w: ['Il risparmiatore che compra BTP', 'Il broker che esegue l’ordine', 'La CONSOB che vigila sul mercato'], e: 'L’emittente crea i titoli per raccogliere fondi: lo Stato tramite il Tesoro, le società con azioni e obbligazioni.' },
    { q: 'Perché nel lungo periodo il mercato azionario non è un gioco a somma zero?', a: 'Perché le aziende producono utili e creano valore', w: ['Perché la borsa rimborsa le perdite ai soci', 'Perché i prezzi nel tempo possono solo salire', 'Perché ogni azione paga sempre un dividendo'], e: 'Il valore nasce dall’attività delle imprese. I prezzi possono scendere e non tutte le società pagano dividendi.' },
    { q: 'Che cosa cambia per te tra conto deposito e acquisto diretto di obbligazioni?', a: 'Con le obbligazioni sopporti tu il rischio dell’emittente', w: ['Con le obbligazioni il capitale è sempre garantito', 'Con il conto deposito non esiste alcun tipo di rischio', 'Con le obbligazioni non puoi mai rivendere prima'], e: 'Nella finanza diretta il rischio dell’emittente è tuo. Anche il deposito ha rischi, sia pure ridotti dalle garanzie sui depositi.' },
    { q: 'Quale di questi è un investitore istituzionale?', a: 'Un fondo pensione', w: ['Un risparmiatore privato', 'Una piccola impresa artigiana', 'Uno studente con un piano di accumulo'], e: 'Fondi pensione, assicurazioni e fondi comuni investono professionalmente grandi somme raccolte da molte persone.' },
  ],
  fill: [
    { s: 'Il mercato ___ scambia strumenti con scadenza entro 12 mesi, come i BOT.', a: 'monetario', w: ['azionario', 'immobiliare', 'valutario'] },
    { s: 'Chi crea e vende un titolo per raccogliere capitali si chiama ___.', a: 'emittente', w: ['intermediario', 'sottoscrittore', 'depositario'] },
    { s: 'Gli scambi conclusi direttamente tra due parti, fuori da un mercato regolamentato, si dicono ___.', a: 'OTC', w: ['IPO', 'ETF', 'PAC'] },
    { s: 'La ___ di una società quotata è il prezzo dell’azione per il numero di azioni.', a: 'capitalizzazione', w: ['liquidità', 'cedola', 'volatilità'] },
    { s: 'Comprando un’obbligazione presti denaro, comprando azioni diventi ___ dell’azienda.', a: 'socio', w: ['creditore', 'cliente', 'garante'] },
  ],
  order: [
    { q: 'Ordina il percorso del risparmio nella finanza diretta', i: ['Una famiglia risparmia', 'Sottoscrive titoli di nuova emissione', 'L’impresa riceve i capitali', 'L’impresa investe e produce'], e: 'Il risparmio arriva all’impresa quando l’investitore sottoscrive titoli nuovi; poi l’impresa lo usa per investire.' },
    { q: 'Ordina dalla scadenza più breve alla più lunga', i: ['BOT a 3 mesi', 'BOT a 12 mesi', 'BTP a 5 anni', 'BTP a 30 anni', 'Azione (nessuna scadenza)'], e: 'I BOT stanno nel mercato monetario; BTP e azioni nel mercato dei capitali. L’azione non ha scadenza: dura quanto la società.' },
  ],
  cat: [
    { q: 'Mercato monetario o mercato dei capitali?', g: [['Monetario', ['BOT a 6 mesi', 'Pronti contro termine a 1 mese', 'Prestito interbancario a un giorno']], ['Dei capitali', ['BTP a 10 anni', 'Azioni di una società quotata', 'Obbligazione societaria a 7 anni']]] },
    { q: 'Chi offre capitali e chi li cerca?', g: [['Offre capitali', ['Famiglia che risparmia', 'Fondo pensione', 'Compagnia assicurativa']], ['Cerca capitali', ['Impresa che apre un nuovo stabilimento', 'Stato che finanzia il deficit', 'Comune che emette un prestito obbligazionario']]] },
  ],
  scen: [
    { s: 'Giulia, 28 anni, ha 5.000 € sul conto e vorrebbe iniziare a investire. Uno zio le ripete che “la borsa è un casinò, ci si rovina e basta”.', q: 'Come valuta questa affermazione?', o: [
      { t: 'Dietro i titoli ci sono aziende reali: serve orizzonte lungo e diversificazione', ok: true, f: 'Giusto: nel breve i prezzi oscillano molto, ma nel lungo periodo seguono utili e prospettive. Il rischio si gestisce con tempo e diversificazione.' },
      { t: 'Lo zio ha ragione: meglio evitare per sempre ogni investimento', ok: false, f: 'Evitare tutto ha un costo: l’inflazione erode il denaro fermo. Il rischio va capito e dosato, non per forza evitato.' },
      { t: 'Lo zio sbaglia: nel lungo periodo in borsa si guadagna sempre', ok: false, f: 'Nessun guadagno è garantito, nemmeno nel lungo periodo: esistono singole aziende e interi mercati rimasti in perdita per anni.' },
    ] },
    { s: 'Marco, 35 anni, riceve dalla banca la proposta di un’obbligazione societaria scambiata solo OTC: il prezzo non è pubblicato su nessun mercato e la banca è l’unica controparte.', q: 'Cosa fa prima di decidere?', o: [
      { t: 'Chiede prezzo, costi e rendimento e li confronta con titoli simili quotati', ok: true, f: 'Bene: senza un prezzo pubblico è più difficile capire se le condizioni sono corrette. Il confronto con titoli quotati simili aiuta.' },
      { t: 'Compra subito: se lo propone la banca è sicuramente conveniente', ok: false, f: 'La banca può avere interesse a vendere i propri prodotti. Fidarsi è ok, ma verificare costi e alternative è meglio.' },
      { t: 'Compra molto perché, non essendo quotata, il prezzo non può scendere', ok: false, f: 'Il valore cambia anche se non lo vedi su uno schermo. In più, rivendere fuori da un mercato può essere difficile e costoso.' },
    ] },
    { s: 'Elena, 41 anni, deve pagare tra 8 mesi la retta universitaria del figlio, circa 6.000 €. Ha la somma da parte e vuole farla rendere un po’ nel frattempo.', q: 'Quale scelta è più coerente?', o: [
      { t: 'Uno strumento del mercato monetario con scadenza entro gli 8 mesi', ok: true, f: 'Corretto: una scadenza breve e coerente con l’obiettivo rende prevedibile la somma disponibile quando servirà.' },
      { t: 'Azioni, perché nel tempo rendono di più', ok: false, f: 'In 8 mesi le azioni possono perdere anche molto: il loro vantaggio emerge su orizzonti lunghi, non per una spesa vicina.' },
      { t: 'Un BTP a 30 anni, perché offre una cedola più alta', ok: false, f: 'Tra 8 mesi dovrebbe rivenderlo al prezzo di mercato, che può essere più basso se i tassi salgono. Scadenza e obiettivo non coincidono.' },
    ] },
    { s: 'Sara, 22 anni, studentessa, pensa che tenere i soldi su un conto deposito e comprare BTP sia “praticamente la stessa cosa”.', q: 'Qual è la differenza principale?', o: [
      { t: 'Col BTP presta direttamente allo Stato e il prezzo può oscillare prima della scadenza', ok: true, f: 'Esatto: è finanza diretta. Se rivende prima della scadenza incassa il prezzo di mercato, che può essere sopra o sotto quanto ha pagato.' },
      { t: 'Nessuna: anche i BTP sono coperti dalla garanzia dei depositi fino a 100.000 €', ok: false, f: 'La garanzia dei depositi riguarda i conti presso le banche, non i titoli. Il BTP dipende dalla solidità dello Stato emittente.' },
      { t: 'Il BTP non ha alcun rischio perché è emesso dallo Stato', ok: false, f: 'Anche un titolo di Stato ha rischi: il prezzo varia con i tassi e il rimborso dipende dalla solidità dell’emittente.' },
    ] },
  ],
  tip: 'Prima di investire chiediti sempre: su quale mercato sto entrando, chi è l’emittente e potrò rivendere facilmente il titolo quando mi servirà?',
});
