FQC(12, {
  intro: 'Quando i tuoi soldi arrivano davvero all’azienda e quando passano solo da un investitore all’altro? Scopri primario e secondario.',
  cards: [
    { t: 'Due mercati, due ruoli', x: 'Sul mercato primario i titoli nascono: l’emittente li vende per la prima volta e incassa il denaro. Sul secondario quei titoli passano di mano tra investitori e l’emittente non incassa nulla.', v: { k: 'vs', a: ['Primario', 'Titoli nuovi: incassa l’emittente'], b: ['Secondario', 'Titoli esistenti: incassa chi vende'] } },
    { t: 'La vita di un titolo', x: 'Un titolo viene emesso, poi collocato presso gli investitori, spesso con l’aiuto di un gruppo di banche. Una volta ammesso alla quotazione, si compra e si vende ogni giorno in borsa.', v: { k: 'steps', s: ['Emissione', 'Collocamento', 'Quotazione', 'Scambi sul secondario'] } },
    { t: 'Esempi di mercato primario', x: 'Sono operazioni di mercato primario le aste del Tesoro per BOT e BTP, la prima quotazione di un’azienda (IPO) con nuove azioni, un aumento di capitale e l’emissione di una nuova obbligazione societaria.', v: { k: 'icons', d: [['🏛️', 'Aste di BOT e BTP'], ['🔔', 'IPO con nuove azioni'], ['➕', 'Aumento di capitale'], ['📜', 'Nuovo bond aziendale']] } },
    { t: 'Chi incassa in borsa?', x: 'Quando compri azioni in borsa da un altro investitore, il tuo denaro va al venditore, non alla società. L’azienda però beneficia di un secondario attivo: le sarà più facile raccogliere capitali in futuro.', v: { k: 'stat', n: '0 €', l: 'incasso dell’emittente da uno scambio tra investitori' } },
    { t: 'OPS e OPV', x: 'In un’offerta pubblica di sottoscrizione (OPS) la società emette nuove azioni e incassa. In un’offerta pubblica di vendita (OPV) sono i soci esistenti a cedere le loro azioni e il denaro va a loro. Un’IPO può combinare le due.', v: { k: 'vs', a: ['OPS', 'Azioni nuove: incassa la società'], b: ['OPV', 'Azioni esistenti: incassano i soci'] } },
    { t: 'Dopo l’emissione il prezzo cambia', x: 'Sul secondario il prezzo segue il mercato: un BTP emesso a 100 può valere 104 o 96 qualche anno dopo. Chi compra in seguito paga il prezzo corrente, non quello d’emissione.', v: { k: 'bars', d: [['All’emissione', 100], ['Dopo 1 anno', 104], ['Dopo 2 anni', 96]], u: '€' } },
  ],
  terms: [
    ['Mercato primario', 'Luogo in cui i titoli vengono venduti per la prima volta, con incasso per chi li emette.'],
    ['Mercato secondario', 'Luogo in cui si scambiano tra investitori titoli già emessi, senza incasso per l’emittente.'],
    ['Collocamento', 'Fase in cui i nuovi titoli vengono distribuiti agli investitori, spesso tramite un consorzio di banche.'],
    ['Sottoscrizione', 'Acquisto di titoli di nuova emissione direttamente al momento del collocamento.'],
    ['Asta del Tesoro', 'Procedura con cui lo Stato colloca BOT e BTP tra gli operatori, gestita dalla Banca d’Italia.'],
    ['OPS', 'Offerta pubblica di sottoscrizione: la società emette nuove azioni e incassa il denaro raccolto.'],
    ['OPV', 'Offerta pubblica di vendita: i soci attuali cedono azioni già esistenti e incassano loro.'],
    ['Riparto', 'Riduzione delle quantità assegnate quando le richieste superano i titoli offerti.'],
  ],
  tf: [
    ['Quando compri azioni in borsa da un altro investitore, la società riceve il tuo denaro.', false, 'Sul secondario il denaro va a chi vende. La società incassa solo quando emette nuovi titoli sul mercato primario.'],
    ['Le aste di BOT e BTP sono un esempio di mercato primario.', true, 'Il Tesoro emette titoli nuovi e incassa il denaro: è la prima vendita, quindi mercato primario.'],
    ['Un BTP comprato sul MOT da un altro risparmiatore è un acquisto sul mercato secondario.', true, 'Il titolo esiste già e passa da un investitore all’altro: il Tesoro non incassa nulla da quello scambio.'],
    ['In un’offerta pubblica di vendita (OPV) la società incassa il denaro degli investitori.', false, 'Nell’OPV vendono i soci esistenti e il denaro va a loro; la società incassa con un’offerta di sottoscrizione (OPS).'],
    ['Un mercato secondario liquido rende più facile per le imprese raccogliere capitali sul primario.', true, 'Gli investitori sottoscrivono più volentieri se sanno di poter rivendere: il secondario sostiene il primario.'],
    ['Dopo l’emissione, il prezzo di un titolo resta uguale al prezzo di emissione fino alla scadenza.', false, 'Sul secondario il prezzo cambia ogni giorno con domanda, offerta, tassi e notizie: può salire o scendere.'],
    ['Se in un collocamento le richieste superano i titoli offerti, può esserci un riparto.', true, 'Con domanda in eccesso ognuno riceve solo una parte di quanto richiesto, secondo criteri annunciati prima del collocamento.'],
    ['Sottoscrivere azioni in un’IPO garantisce di poterle rivendere in guadagno il primo giorno.', false, 'Dopo la quotazione il prezzo può scendere sotto quello di offerta: nessun guadagno è garantito.'],
    ['Un aumento di capitale con emissione di nuove azioni è un’operazione di mercato primario.', true, 'La società emette azioni nuove e incassa il denaro dei sottoscrittori: è raccolta di capitale, quindi primario.'],
    ['Il mercato primario è riservato alle banche: un privato non può mai sottoscrivere titoli nuovi.', false, 'Molte emissioni sono aperte al pubblico: titoli di Stato tramite la propria banca, IPO con quote retail, aumenti di capitale.'],
  ],
  mcq: [
    { q: 'In quale caso l’azienda incassa denaro dagli investitori?', a: 'Quando emette nuove azioni con un aumento di capitale', w: ['Quando un grande fondo compra le sue azioni in borsa', 'Quando le sue azioni salgono del 10% in una seduta', 'Quando un socio vende in borsa le azioni che possiede'], e: 'Solo l’emissione di titoli nuovi porta denaro all’azienda. Gli scambi in borsa spostano denaro tra investitori.' },
    { q: 'Mario compra sul MOT un BTP già in circolazione. Dove sta operando?', a: 'Sul mercato secondario', w: ['Sul mercato primario', 'In un’asta del Tesoro', 'In un’offerta di vendita'], e: 'Il BTP esiste già e Mario lo compra da un altro investitore: è un acquisto sul secondario.' },
    { q: 'Che cosa distingue un’OPS da un’OPV?', a: 'Nell’OPS le azioni sono nuove e incassa la società', w: ['Nell’OPS le azioni sono riservate ai dipendenti', 'Nell’OPV le azioni sono nuove e incassa la società', 'Nell’OPV il prezzo viene fissato dalla CONSOB'], e: 'OPS = nuove azioni, denaro alla società. OPV = azioni esistenti, denaro ai soci che vendono.' },
    { q: 'Perché un mercato secondario efficiente aiuta anche le imprese?', a: 'Perché si sottoscrive più volentieri se si può rivendere', w: ['Perché ogni scambio versa una commissione all’impresa', 'Perché impedisce ai soci di vendere le loro azioni', 'Perché garantisce per legge un prezzo minimo'], e: 'La possibilità di rivendere riduce il rischio per chi sottoscrive: così le imprese raccolgono capitali più facilmente e a costi minori.' },
    { q: 'Chi gestisce, per conto del Ministero dell’Economia, le aste dei titoli di Stato?', a: 'La Banca d’Italia', w: ['La CONSOB', 'L’ESMA', 'Borsa Italiana'], e: 'Le aste di BOT e BTP sono organizzate dalla Banca d’Italia per conto del Tesoro (Ministero dell’Economia e delle Finanze).' },
    { q: 'Un BTP emesso a 100 oggi quota 96 sul MOT. Chi lo compra ora quanto paga?', a: 'Circa 96, il prezzo corrente', w: ['100, il prezzo di emissione', '96, ma il Tesoro incassa 100', 'Nulla fino alla scadenza'], e: 'Sul secondario si paga il prezzo di mercato del momento, più eventuali interessi maturati e costi.' },
    { q: 'Che cos’è il riparto in un collocamento?', a: 'La riduzione delle quantità assegnate se la domanda è eccessiva', w: ['La divisione degli utili tra i nuovi soci della società', 'Il rimborso del titolo al valore nominale alla scadenza', 'La commissione pagata alle banche che collocano i titoli'], e: 'Se si chiedono più titoli di quelli offerti, ciascuno ne riceve solo una parte e il resto del denaro viene restituito o liberato.' },
    { q: 'Quale affermazione su un’IPO è corretta?', a: 'Il prezzo può scendere sotto quello di offerta', w: ['Il primo giorno di quotazione il prezzo sale sempre', 'Chi sottoscrive ottiene un rendimento minimo garantito', 'Il prezzo di offerta viene deciso dalla CONSOB'], e: 'Molte IPO salgono, molte scendono. La CONSOB approva il prospetto informativo, ma non fissa il prezzo né giudica la convenienza.' },
  ],
  fill: [
    { s: 'Sul mercato ___ l’emittente vende i titoli per la prima volta e incassa il denaro.', a: 'primario', w: ['secondario', 'valutario', 'interbancario'] },
    { s: 'Quando compri da un altro investitore titoli già emessi operi sul mercato ___.', a: 'secondario', w: ['primario', 'monetario', 'interbancario'] },
    { s: 'Se le richieste superano i titoli offerti, l’assegnazione avviene con un ___.', a: 'riparto', w: ['rimborso', 'dividendo', 'riscatto'] },
    { s: 'Nell’offerta pubblica di ___ la società emette nuove azioni e incassa il denaro.', a: 'sottoscrizione', w: ['vendita', 'scambio', 'rimborso'] },
    { s: 'BOT e BTP vengono emessi tramite ___ gestite dalla Banca d’Italia.', a: 'aste', w: ['borse', 'lotterie', 'compensazioni'] },
  ],
  order: [
    { q: 'Ordina le fasi della vita di un nuovo titolo azionario', i: ['Delibera di emissione', 'Approvazione del prospetto', 'Collocamento presso gli investitori', 'Inizio delle negoziazioni', 'Scambi quotidiani tra investitori'], e: 'Si decide l’emissione, si pubblica il prospetto approvato, si colloca; dopo la quotazione i titoli passano di mano sul secondario.' },
    { q: 'Ordina il percorso di un nuovo BTP', i: ['Il Tesoro annuncia l’asta', 'Gli operatori presentano le offerte', 'I titoli vengono assegnati e pagati', 'Il BTP si scambia sul MOT tra investitori'], e: 'L’asta è il mercato primario: il Tesoro incassa. Da lì in poi il BTP vive sul secondario, dove il prezzo cambia ogni giorno.' },
  ],
  cat: [
    { q: 'Mercato primario o secondario?', g: [['Primario', ['Asta di BOT', 'IPO con nuove azioni', 'Emissione di un nuovo bond aziendale', 'Aumento di capitale']], ['Secondario', ['Acquisto in borsa di azioni già quotate', 'Vendita di un BTP sul MOT', 'Compravendita di ETF su ETFplus']]] },
    { q: 'Chi incassa il denaro di chi compra?', g: [['L’emittente', ['Sottoscrizione di BTP all’asta', 'OPS durante un’IPO', 'Nuove azioni offerte ai soci']], ['Un altro investitore', ['Acquisto di azioni in borsa', 'OPV dei soci fondatori', 'Acquisto di un BOT già in circolazione']]] },
  ],
  scen: [
    { s: 'Luca, 30 anni, crede molto in un’azienda italiana di energie rinnovabili e vuole contribuire a finanziarne i progetti con i suoi risparmi.', q: 'Cosa fa per finanziarla davvero?', o: [
      { t: 'Partecipa a un aumento di capitale o sottoscrive un bond di nuova emissione', ok: true, f: 'Giusto: solo sottoscrivendo titoli nuovi il denaro arriva all’azienda. Resta importante non concentrare troppo i risparmi su un solo emittente.' },
      { t: 'Compra in borsa le azioni già quotate da altri investitori', ok: false, f: 'Diventa socio, ma il denaro va a chi vende. L’azienda ne beneficia solo indirettamente, tramite un mercato più attivo.' },
      { t: 'Compra un fondo sull’indice in cui l’azienda è presente', ok: false, f: 'Anche il fondo compra quasi sempre sul secondario: i soldi non arrivano all’azienda e l’investimento è diluito su molti titoli.' },
    ] },
    { s: 'Francesca, 45 anni, riceve dalla banca l’invito a sottoscrivere le azioni di un’IPO. Il consulente dice: “Le IPO salgono sempre il primo giorno”.', q: 'Come si comporta?', o: [
      { t: 'Legge il prospetto, valuta prezzo e rischi e, se convinta, investe una piccola quota', ok: true, f: 'Bene: il prospetto descrive attività, rischi e uso dei fondi. Non tutte le IPO salgono, quindi l’importo va dosato.' },
      { t: 'Investe gran parte dei risparmi per il guadagno rapido del primo giorno', ok: false, f: 'Il rialzo del debutto non è garantito: molte IPO scendono sotto il prezzo di offerta anche per lunghi periodi.' },
      { t: 'Chiede un prestito per sottoscrivere più azioni possibile', ok: false, f: 'Indebitarsi per un’IPO somma due rischi: il titolo può scendere e il debito resta da ripagare con gli interessi.' },
    ] },
    { s: 'Antonio, 60 anni, ha sottoscritto all’emissione un BTP a 100. Due anni dopo i tassi sono saliti e il titolo quota 93 sul MOT. Il BTP scade tra 3 anni, proprio quando gli serviranno i soldi.', q: 'Cosa fa?', o: [
      { t: 'Lo tiene fino alla scadenza, quando sarà rimborsato a 100, incassando le cedole', ok: true, f: 'Corretto: il prezzo di 93 conta solo se vende ora. Salvo insolvenza dell’emittente, a scadenza riceve il valore nominale.' },
      { t: 'Lo vende subito, perché a scadenza il Tesoro rimborserà solo 93', ok: false, f: 'Il rimborso a scadenza è al valore nominale (100), non al prezzo di mercato del momento. Vendendo ora realizzerebbe la perdita.' },
      { t: 'Ne compra altri all’asta, convinto che sul primario il prezzo sia sempre 100', ok: false, f: 'Anche alle aste il prezzo dipende dalle condizioni di mercato del momento: non è fissato sempre a 100.' },
    ] },
    { s: 'Chiara, 26 anni, chiede 10.000 € di un nuovo bond di una grande azienda durante il collocamento. A fine offerta riceve solo 4.000 € di titoli e teme un errore.', q: 'Cosa è successo?', o: [
      { t: 'C’è stato un riparto: la domanda ha superato l’offerta e il resto viene liberato', ok: true, f: 'Esatto: con richieste superiori ai titoli disponibili si assegna una parte a ciascuno. I 6.000 € non usati restano a sua disposizione.' },
      { t: 'La banca ha trattenuto parte dei titoli come commissione', ok: false, f: 'Le commissioni si pagano in denaro e devono essere indicate in anticipo: non si trattengono titoli in questo modo.' },
      { t: 'Deve fare subito ricorso alla CONSOB per ottenere tutti i titoli', ok: false, f: 'Il riparto è previsto dalle regole dell’offerta. Può chiedere spiegazioni alla banca, ma non ha diritto all’intera quantità.' },
    ] },
  ],
  tip: 'In borsa compri quasi sempre da un altro investitore. Se vuoi sapere chi incassa i tuoi soldi, chiediti: il titolo è nuovo o già in circolazione?',
});
