FQC(13, {
  intro: 'Da Milano a New York, da Londra a Tokyo: scopri le principali borse del mondo, i loro orari e cosa cambia quando investi all’estero.',
  cards: [
    { t: 'Le grandi piazze', x: 'Le borse più grandi al mondo per valore delle società quotate sono quelle statunitensi, NYSE e Nasdaq. In Europa spiccano Euronext, il London Stock Exchange e Deutsche Börse; in Asia Tokyo, Shanghai, Shenzhen e Hong Kong.', v: { k: 'icons', d: [['🇺🇸', 'NYSE e Nasdaq'], ['🇪🇺', 'Euronext'], ['🇬🇧', 'Londra'], ['🇯🇵', 'Tokyo']] } },
    { t: 'Piazza Affari', x: 'La Borsa di Milano nacque nel 1808. Oggi Borsa Italiana fa parte del gruppo Euronext e il suo mercato azionario principale si chiama Euronext Milan; la sede storica è Palazzo Mezzanotte, in Piazza Affari.', v: { k: 'stat', n: '1808', l: 'anno di nascita della Borsa di Milano' } },
    { t: 'Le borse seguono il sole', x: 'La giornata dei mercati parte dall’Asia, nella notte italiana; poi apre l’Europa e nel pomeriggio Wall Street. Milano negozia in continua indicativamente dalle 9 alle 17:30, New York di solito dalle 15:30 alle 22 ora italiana.', v: { k: 'steps', s: ['Asia: notte italiana', 'Europa: 9:00-17:30', 'USA: 15:30-22:00'] } },
    { t: 'I mercati di Borsa Italiana', x: 'Borsa Italiana ha più mercati: Euronext Milan per le azioni principali, Euronext Growth Milan per le piccole e medie imprese, il MOT per obbligazioni e titoli di Stato, ETFplus per ETF e altri prodotti quotati.', v: { k: 'icons', d: [['📈', 'Euronext Milan: azioni'], ['🌱', 'Growth Milan: PMI'], ['📜', 'MOT: obbligazioni'], ['🧺', 'ETFplus: ETF']] } },
    { t: 'Il rischio di cambio', x: 'Un titolo estero è quotato nella sua valuta. Il risultato in euro dipende dal prezzo e dal cambio: se l’azione sale del 10% in dollari ma il dollaro perde il 5% sull’euro, in euro guadagni circa il 4,5%.', v: { k: 'formula', f: 'Risultato in euro = (1 + rend. in valuta) × (1 + var. cambio) − 1', n: 'Es.: 1,10 × 0,95 − 1 = +4,5%' } },
    { t: 'Sedute di durata diversa', x: 'Milano, Francoforte e Londra negoziano in continua per circa 8 ore e mezza, New York per 6 ore e mezza. Tra le 15:30 e le 17:30 italiane Europa e Wall Street sono aperte insieme: spesso è la fase più movimentata.', v: { k: 'bars', d: [['Milano', 8.5], ['Londra', 8.5], ['New York', 6.5]], u: 'ore' } },
  ],
  terms: [
    ['Borsa valori', 'Mercato regolamentato e organizzato in cui si negoziano titoli quotati secondo regole comuni.'],
    ['Piazza Affari', 'Nome con cui si indica la Borsa di Milano, dalla piazza dove sorge Palazzo Mezzanotte.'],
    ['Euronext', 'Gruppo che gestisce varie borse europee, tra cui Parigi, Amsterdam e, dal 2021, Milano.'],
    ['Wall Street', 'Via di New York sede del NYSE, usata per indicare l’intero mercato azionario statunitense.'],
    ['Nasdaq', 'Borsa elettronica statunitense, nota per l’alta presenza di società tecnologiche.'],
    ['Doppia quotazione', 'Situazione in cui le azioni di una stessa società si negoziano su due o più borse.'],
    ['Rischio di cambio', 'Possibile guadagno o perdita dovuto alla variazione della valuta in cui è quotato un titolo.'],
    ['Euronext Growth Milan', 'Mercato di Borsa Italiana dedicato alle piccole e medie imprese, con requisiti più leggeri.'],
  ],
  tf: [
    ['Borsa Italiana fa parte del gruppo Euronext.', true, 'Dal 2021 Borsa Italiana appartiene a Euronext, che riunisce varie borse europee come Parigi, Amsterdam e Dublino.'],
    ['Le borse di tutto il mondo aprono e chiudono alla stessa ora.', false, 'Ogni borsa ha i suoi orari locali: quando Milano chiude, New York è aperta da circa due ore; Tokyo negozia di notte.'],
    ['Un’azione statunitense comprata in dollari espone un investitore italiano al rischio di cambio.', true, 'Il risultato in euro dipende sia dal prezzo dell’azione sia dal cambio euro/dollaro, che può aiutare o penalizzare.'],
    ['La borsa di New York è gestita direttamente dal governo degli Stati Uniti.', false, 'Il NYSE appartiene a una società privata quotata, Intercontinental Exchange. Anche Euronext e Deutsche Börse sono società quotate.'],
    ['Se un titolo è quotato sia a Milano sia a New York, si tratta di due aziende diverse.', false, 'È la stessa società: le sue azioni (o certificati che le rappresentano) si negoziano su più mercati, in valute diverse.'],
    ['Sul London Stock Exchange molte azioni sono quotate in pence, cioè centesimi di sterlina.', true, 'Spesso i prezzi a Londra sono espressi in pence (GBX): 250 pence equivalgono a 2,50 sterline.'],
    ['Euronext Growth Milan è il mercato di Borsa Italiana dedicato ai titoli di Stato.', false, 'È il mercato per le piccole e medie imprese in crescita; i titoli di Stato si scambiano soprattutto sul MOT.'],
    ['Le borse hanno calendari di festività diversi: un giorno Milano può essere aperta e New York chiusa.', true, 'Ad esempio nel giorno del Ringraziamento la borsa di New York è chiusa, mentre quelle europee negoziano normalmente.'],
    ['Un risparmiatore italiano non può comprare azioni quotate su borse estere.', false, 'Tramite banca o broker puoi accedere a molte borse estere, tenendo conto di costi, orari e cambio valuta.'],
    ['Per gran parte dell’anno, tra le 15:30 e le 17:30 italiane le borse europee e Wall Street sono aperte insieme.', true, 'Wall Street apre alle 9:30 di New York, cioè di solito alle 15:30 in Italia, mentre l’Europa chiude verso le 17:30.'],
  ],
  mcq: [
    { q: 'Qual è la borsa più grande al mondo per valore delle società quotate?', a: 'Il New York Stock Exchange', w: ['Il London Stock Exchange', 'La Borsa di Tokyo', 'Il gruppo Euronext'], e: 'Il NYSE ospita molte delle società più grandi del mondo; al secondo posto c’è il Nasdaq, sempre negli Stati Uniti.' },
    { q: 'Indicativamente, a che ora italiana apre la borsa di New York?', a: 'Alle 15:30', w: ['Alle 9:00', 'Alle 13:00', 'Alle 18:00'], e: 'Apre alle 9:30 di New York: di solito le 15:30 in Italia. Per poche settimane l’anno, per il cambio d’ora sfasato, le 14:30.' },
    { q: 'Quale mercato di Borsa Italiana è dedicato soprattutto alle piccole e medie imprese?', a: 'Euronext Growth Milan', w: ['MOT', 'ETFplus', 'IDEM'], e: 'Euronext Growth Milan ha requisiti più leggeri per le PMI. Il MOT è per le obbligazioni, ETFplus per gli ETF, l’IDEM per i derivati.' },
    { q: 'Un’azione USA sale del 10% in dollari, ma il dollaro perde il 5% sull’euro. Il risultato in euro è circa:', a: '+4,5%', w: ['+15%', '+10%', '−5%'], e: '1,10 × 0,95 = 1,045: in euro guadagni circa il 4,5%, perché il cambio ha eroso parte del rialzo.' },
    { q: 'Perché si parla di “Piazza Affari”?', a: 'È la piazza di Milano dove ha sede la Borsa', w: ['È il nome del mercato delle obbligazioni', 'È la zona di Roma dove ha sede la CONSOB', 'È il nome dell’indice delle 40 big italiane'], e: 'Palazzo Mezzanotte, sede storica di Borsa Italiana, si trova in Piazza degli Affari a Milano.' },
    { q: 'In quale parte della giornata italiana è aperta la borsa di Tokyo?', a: 'Di notte e nelle prime ore del mattino', w: ['Nel tardo pomeriggio e in serata', 'Dalle 9 alle 17:30, come Milano', 'Solo il sabato e la domenica'], e: 'Tokyo negozia di giorno secondo l’ora giapponese, che è avanti di 7-8 ore: per noi è notte o primissima mattina.' },
    { q: 'Una società è quotata sia su Euronext Milan sia al NYSE. Che cosa significa?', a: 'Le sue azioni si scambiano su due borse, in due valute', w: ['Ha due bilanci separati, uno per ciascun Paese', 'Esistono due società distinte con lo stesso nome', 'Può essere acquistata solo da investitori esteri'], e: 'Con la doppia quotazione la stessa società è scambiata in euro a Milano e in dollari a New York: i prezzi, convertiti, restano allineati.' },
    { q: 'Comprando azioni su una borsa estera, quale costo devi considerare spesso in più?', a: 'La conversione di valuta applicata dal broker', w: ['Un’imposta del 26% sull’importo acquistato', 'Una commissione da versare alla CONSOB', 'Un’imposta di bollo doppia sul conto corrente'], e: 'Molti broker applicano un costo o un margine sul cambio. Il 26% si paga sulle plusvalenze, non sull’acquisto.' },
  ],
  fill: [
    { s: 'Il mercato azionario principale di Borsa Italiana si chiama Euronext ___.', a: 'Milan', w: ['Italia', 'Roma', 'Mezzanotte'] },
    { s: 'Il ___ è la borsa elettronica americana nota per le grandi società tecnologiche.', a: 'Nasdaq', w: ['Nikkei', 'DAX', 'FTSE MIB'] },
    { s: 'Quando investi in titoli quotati in un’altra valuta sei esposto al rischio di ___.', a: 'cambio', w: ['credito', 'liquidità', 'inflazione'] },
    { s: 'Sul London Stock Exchange molte azioni sono quotate in ___, centesimi di sterlina.', a: 'pence', w: ['scellini', 'cent', 'ghinee'] },
    { s: 'Borsa Italiana ha sede a Palazzo ___, in Piazza Affari a Milano.', a: 'Mezzanotte', w: ['Marino', 'Chigi', 'Madama'] },
  ],
  order: [
    { q: 'Ordina le borse per ora italiana di apertura, dalla prima all’ultima', i: ['Tokyo', 'Hong Kong', 'Francoforte', 'New York'], e: 'L’Asia apre nella notte italiana, prima Tokyo e poi Hong Kong; l’Europa alle 9; New York nel pomeriggio italiano.' },
    { q: 'Ordina i passaggi di un investimento in azioni USA partendo da un conto in euro', i: ['Versi gli euro al broker', 'Converti gli euro in dollari', 'Compri le azioni in dollari', 'Alla vendita incassi dollari', 'Riconverti i dollari in euro'], e: 'Ogni conversione ha un costo e un cambio diverso: il risultato finale in euro dipende anche da come si è mosso il dollaro.' },
  ],
  cat: [
    { q: 'Borsa europea o asiatica?', g: [['Europa', ['Euronext Milan', 'Borsa di Francoforte', 'London Stock Exchange', 'SIX Swiss Exchange']], ['Asia', ['Borsa di Tokyo', 'Borsa di Hong Kong', 'Borsa di Shanghai', 'Borsa di Mumbai']]] },
    { q: 'Dove si scambia su Borsa Italiana?', g: [['MOT', ['BTP', 'BOT', 'Obbligazioni societarie']], ['Euronext Milan', ['Azioni delle grandi banche italiane', 'Azioni delle società energetiche', 'Azioni delle case automobilistiche']]] },
  ],
  scen: [
    { s: 'Davide, 33 anni, alle 11 del mattino vuole comprare un’azione di una società americana. Sul suo broker il mercato principale, New York, risulta ancora chiuso.', q: 'Cosa fa?', o: [
      { t: 'Aspetta l’apertura di Wall Street nel pomeriggio italiano', ok: true, f: 'Bene: con il mercato principale aperto ci sono più scambi, spread più stretti e prezzi più affidabili.' },
      { t: 'La compra subito su una piccola piazza estera dove ha uno spread molto ampio', ok: false, f: 'Pagare uno spread ampio solo per non aspettare qualche ora è un costo inutile, se non hai un motivo preciso.' },
      { t: 'Rinuncia: pensa che dall’Italia non si possano comprare azioni USA', ok: false, f: 'Tramite banca o broker puoi accedere a Wall Street: basta rispettarne gli orari e valutare costi e cambio.' },
    ] },
    { s: 'Martina, 38 anni, ha comprato azioni giapponesi: in un anno sono salite dell’8% in yen, ma nello stesso periodo lo yen ha perso il 10% sull’euro.', q: 'Come valuta il risultato?', o: [
      { t: 'In euro ha perso circa il 3%: il cambio ha più che annullato il rialzo', ok: true, f: 'Corretto: 1,08 × 0,90 = 0,972, cioè circa −2,8%. Per chi investe in euro il cambio conta quanto il prezzo.' },
      { t: 'Ha guadagnato l’8%: il cambio non conta per chi investe dall’Italia', ok: false, f: 'Il cambio conta eccome: per riportare il denaro in euro deve convertire gli yen, che ora valgono meno.' },
      { t: 'Ha guadagnato il 18%: rialzo e cambio si sommano', ok: false, f: 'Lo yen si è indebolito, quindi il cambio ha tolto valore. I due effetti si combinano, e qui vanno in direzioni opposte.' },
    ] },
    { s: 'Roberto, 55 anni, vuole investire in azioni solo a Piazza Affari: “La conosco e non ho rischio di cambio”.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Piazza Affari è piccola e concentrata: conviene diversificare anche altrove', ok: true, f: 'Giusto: il listino italiano pesa poco sul totale mondiale ed è molto legato a banche, energia e utility. Diversificare riduce questa dipendenza.' },
      { t: 'Restando in Italia elimina il rischio di cambio e quindi ogni rischio', ok: false, f: 'Il rischio di cambio è solo uno dei rischi: restano quello di mercato, quello settoriale e quello delle singole aziende.' },
      { t: 'Meglio spostare tutto su azioni USA, perché quella borsa è la più grande', ok: false, f: 'Passare da una concentrazione all’altra non risolve il problema: la diversificazione riguarda più mercati, non uno solo.' },
    ] },
    { s: 'Ilaria, 29 anni, nota che la stessa società quota 50 € a Milano e 54 $ a New York. Pensa di aver trovato un guadagno sicuro: comprare a Milano e vendere a New York.', q: 'Cosa dovrebbe fare prima?', o: [
      { t: 'Convertire i prezzi nella stessa valuta: probabilmente la differenza è solo il cambio', ok: true, f: 'Esatto: se un euro vale 1,08 dollari, 50 € equivalgono a 54 $. I prezzi sulle due piazze, convertiti, restano allineati.' },
      { t: 'Comprare subito a Milano e vendere a New York: è un guadagno garantito', ok: false, f: 'Non c’è alcun guadagno: i prezzi sono in valute diverse. In più pagherebbe commissioni e costi di cambio su entrambi i lati.' },
      { t: 'Concludere che a New York il titolo è sopravvalutato e venderlo', ok: false, f: 'Senza convertire le valute il confronto non ha senso: 54 dollari non sono 54 euro.' },
    ] },
  ],
  tip: 'Prima di comprare un titolo estero controlla tre cose: gli orari della sua borsa, la valuta di quotazione e i costi di cambio applicati dal tuo broker.',
});
