FQC(14, {
  intro: 'In borsa non entri da solo: ti serve un intermediario autorizzato. Scopri chi sono, come guadagnano e come sceglierli con giudizio.',
  cards: [
    { t: 'Il percorso di un ordine', x: 'Solo gli intermediari ammessi possono operare direttamente sui mercati. Tu dai l’ordine alla banca o al broker, che lo porta sul mercato; dopo l’esecuzione titoli e denaro vengono regolati e i titoli finiscono nel tuo dossier.', v: { k: 'steps', s: ['Inserisci l’ordine', 'Il broker lo trasmette', 'Esecuzione sul mercato', 'Regolamento e deposito'] } },
    { t: 'Chi può offrirti servizi', x: 'In Italia i servizi di investimento li prestano banche e SIM; le SGR gestiscono fondi e patrimoni. Operano anche imprese di altri Paesi UE grazie al passaporto europeo, vigilate soprattutto dal Paese d’origine.', v: { k: 'icons', d: [['🏦', 'Banche'], ['💼', 'SIM'], ['🧺', 'SGR'], ['🇪🇺', 'Imprese UE con passaporto']] } },
    { t: 'Banca o broker online?', x: 'La banca offre filiale, consulenza e servizi integrati, spesso con commissioni più alte. Il broker online punta su costi bassi e operatività da app, ma di solito non dà consigli: le decisioni restano tue.', v: { k: 'vs', a: ['Banca tradizionale', 'Filiale e consulenza, costi spesso più alti'], b: ['Broker online', 'App e costi bassi, decidi da solo'] } },
    { t: 'Come si calcola la commissione', x: 'Molti listini applicano una percentuale sul controvalore, con un minimo e talvolta un massimo per ordine. Su ordini piccoli il minimo pesa molto; su ordini grandi conta di più la percentuale.', v: { k: 'formula', f: 'Commissione = percentuale × controvalore, entro minimo e massimo', n: 'Es.: 0,19% di 3.000 € = 5,70 €; con minimo 8 € paghi 8 €' } },
    { t: 'Stesso ordine, costi diversi', x: 'Su un ordine da 2.000 € la stessa operazione può costare da 2 € a 9 € a seconda del listino. Su piccoli importi i minimi fissi pesano molto in percentuale.', v: { k: 'bars', d: [['Banca: 0,25%, min 9 €', 9], ['Broker A: fissa 5 €', 5], ['Broker B: 0,1%', 2]], u: '€' } },
    { t: 'Chi paga le tasse?', x: 'Con un intermediario italiano (o estero con rappresentante fiscale) di solito sei in regime amministrato: il broker calcola e versa le imposte. Con molti broker esteri sei in regime dichiarativo e fai tutto tu in dichiarazione.', v: { k: 'vs', a: ['Regime amministrato', 'Il broker fa da sostituto d’imposta'], b: ['Regime dichiarativo', 'Dichiari e versi tu le imposte'] } },
  ],
  terms: [
    ['Intermediario', 'Soggetto autorizzato a prestare servizi di investimento, come una banca o una SIM.'],
    ['Broker', 'Intermediario che riceve gli ordini dei clienti e li esegue o li trasmette al mercato.'],
    ['SIM', 'Società di intermediazione mobiliare: impresa di investimento italiana diversa da una banca.'],
    ['SGR', 'Società di gestione del risparmio: gestisce fondi comuni e patrimoni per conto degli investitori.'],
    ['Dossier titoli', 'Conto presso l’intermediario in cui sono registrati e custoditi gli strumenti finanziari del cliente.'],
    ['Commissione di negoziazione', 'Costo pagato all’intermediario per ogni ordine eseguito, fisso o in percentuale.'],
    ['Execution only', 'Servizio di sola esecuzione degli ordini, senza consulenza né raccomandazioni personalizzate.'],
    ['Sostituto d’imposta', 'Chi calcola e versa le imposte al posto del contribuente, come il broker in regime amministrato.'],
  ],
  tf: [
    ['Un risparmiatore può inviare i suoi ordini direttamente alla borsa, senza intermediario.', false, 'Solo gli intermediari ammessi alle negoziazioni accedono al mercato: tu passi sempre da una banca o da un broker.'],
    ['Un broker “a zero commissioni” non ha alcun costo per chi investe.', false, 'Può guadagnare su spread, cambio valuta, interessi sulla liquidità o altri servizi: il costo c’è, è solo meno visibile.'],
    ['In regime amministrato è l’intermediario a calcolare e versare le imposte sui tuoi guadagni.', true, 'Fa da sostituto d’imposta: trattiene le tasse su plusvalenze e redditi e le versa per te, senza bisogno di dichiararle.'],
    ['Su un ordine da 500 €, una commissione minima di 9 € pesa l’1,8% del controvalore.', true, '9 / 500 = 0,018, cioè l’1,8% solo in entrata: con piccoli importi i minimi fissi incidono molto.'],
    ['Un servizio “execution only” include sempre consigli personalizzati su cosa comprare.', false, 'È pura esecuzione: il broker esegue i tuoi ordini senza raccomandazioni. Le scelte, e i loro rischi, restano tuoi.'],
    ['Prima di aprire un conto conviene verificare che il broker compaia negli elenchi ufficiali di CONSOB o Banca d’Italia.', true, 'Gli intermediari autorizzati sono iscritti in albi ed elenchi pubblici: un controllo di pochi minuti evita gli operatori abusivi.'],
    ['Con un broker italiano, sugli strumenti finanziari in dossier si paga di norma l’imposta di bollo dello 0,2% annuo.', true, 'Il bollo dello 0,2% si applica al valore dei titoli in deposito; con un broker estero in regime dichiarativo lo versi tu come IVAFE.'],
    ['Le SGR sono le società che gestiscono i fondi comuni di investimento.', true, 'Le società di gestione del risparmio raccolgono il denaro dei sottoscrittori e lo investono secondo la politica del fondo.'],
    ['Il broker più economico è sempre quello con la commissione per ordine più bassa.', false, 'Contano anche canoni, cambio valuta, spread, costi di custodia e il tuo modo di operare: va confrontato il costo totale.'],
    ['Se il broker fallisce, i titoli nel tuo dossier vengono usati per pagare i suoi debiti.', false, 'Per legge i titoli dei clienti sono un patrimonio separato da quello dell’intermediario: i suoi creditori non possono prenderli.'],
  ],
  mcq: [
    { q: 'Chi può accedere direttamente al mercato per eseguire gli ordini?', a: 'Gli intermediari ammessi alle negoziazioni', w: ['Qualsiasi risparmiatore maggiorenne', 'Soltanto le società quotate in borsa', 'Soltanto la Banca d’Italia e la CONSOB'], e: 'Le borse accettano ordini solo dai loro membri autorizzati. Il risparmiatore passa sempre da una banca o da un broker.' },
    { q: 'Il listino prevede lo 0,19% con minimo 5 € e massimo 19 €. Quanto paghi su un ordine da 15.000 €?', a: '19 €', w: ['28,50 €', '5 €', '15 €'], e: '0,19% di 15.000 € = 28,50 €, ma il massimo è 19 €: paghi 19 €.' },
    { q: 'Che cos’è una SIM?', a: 'Un’impresa di investimento non bancaria', w: ['Un fondo comune quotato in borsa', 'Un’autorità che vigila sui broker', 'Un tipo di conto deposito vincolato'], e: 'La società di intermediazione mobiliare presta servizi di investimento, come esecuzione ordini o gestione, ma non raccoglie depositi.' },
    { q: 'Come può guadagnare un broker che pubblicizza zero commissioni?', a: 'Con spread, cambio valuta e interessi sulla liquidità', w: ['Solo con la pubblicità mostrata dentro l’app', 'Con una quota fissa dei guadagni dei clienti', 'Con contributi pubblici per ogni nuovo cliente'], e: 'Il costo si sposta dove si vede meno: margini sul cambio, spread, interessi non riconosciuti sul contante, servizi a pagamento.' },
    { q: 'Nel regime dichiarativo, tipico di molti broker esteri, chi dichiara i redditi da investimento?', a: 'Il contribuente, nella propria dichiarazione', w: ['Il broker estero, come sostituto d’imposta', 'La CONSOB, in modo automatico', 'Borsa Italiana, alla fine dell’anno'], e: 'Nel dichiarativo l’intermediario non trattiene le imposte: plusvalenze, redditi e attività estere vanno indicati da te.' },
    { q: 'Che cosa significa servizio “execution only”?', a: 'Il broker esegue gli ordini senza darti consigli', w: ['Il broker decide al posto tuo cosa comprare', 'Puoi comprare soltanto titoli italiani', 'Gli ordini vengono eseguiti solo a fine giornata'], e: 'Sola esecuzione: nessuna raccomandazione. È economico, ma la responsabilità delle scelte resta tutta tua.' },
    { q: 'Investi 1.000 € al mese con un ordine separato ogni volta. Quale listino ti pesa di più?', a: 'Commissione fissa di 12 € per ordine', w: ['Commissione dello 0,1% senza minimo', 'Commissione fissa di 2 € per ordine', 'Commissione dello 0,19% con minimo 1 €'], e: '12 € su 1.000 € sono l’1,2% a ogni acquisto; le altre costano tra 1 € e 2 € per ordine, cioè lo 0,1-0,2%.' },
    { q: 'Perché i titoli in dossier sono protetti se l’intermediario fallisce?', a: 'Perché per legge sono separati dal suo patrimonio', w: ['Perché lo Stato rimborsa ogni perdita di borsa', 'Perché il broker li assicura contro ogni ribasso', 'Perché sono sempre depositati presso la CONSOB'], e: 'La separazione patrimoniale tutela la proprietà dei titoli, non il loro valore: se il mercato scende, la perdita resta tua.' },
  ],
  fill: [
    { s: 'Il costo pagato al broker per ogni ordine eseguito è la ___ di negoziazione.', a: 'commissione', w: ['cedola', 'imposta', 'franchigia'] },
    { s: 'In regime ___ è il broker a calcolare e versare le imposte per te.', a: 'amministrato', w: ['dichiarativo', 'forfettario', 'agevolato'] },
    { s: 'Le società che gestiscono i fondi comuni di investimento si chiamano ___.', a: 'SGR', w: ['SIM', 'IPO', 'OTC'] },
    { s: 'Il conto in cui sono custoditi i tuoi titoli si chiama ___ titoli.', a: 'dossier', w: ['libretto', 'registro', 'fascicolo'] },
    { s: 'Un broker di un altro Paese UE può operare in Italia grazie al ___ europeo.', a: 'passaporto', w: ['visto', 'brevetto', 'mandato'] },
  ],
  order: [
    { q: 'Ordina i passaggi per iniziare a investire con un broker', i: ['Verifichi che sia autorizzato', 'Confronti costi e servizi', 'Apri conto e dossier titoli', 'Versi il denaro', 'Inserisci il primo ordine'], e: 'Prima la sicurezza (autorizzazione), poi la convenienza (costi), infine l’operatività.' },
    { q: 'Ordina il percorso di un ordine di acquisto', i: ['Inserisci l’ordine nell’app', 'Il broker controlla fondi e parametri', 'L’ordine arriva al mercato', 'Il contratto viene eseguito', 'Titoli e denaro vengono regolati'], e: 'Il regolamento, cioè lo scambio definitivo di titoli e denaro, avviene di solito uno o due giorni lavorativi dopo l’esecuzione.' },
  ],
  cat: [
    { q: 'Costo esplicito o implicito?', g: [['Esplicito', ['Commissione per ordine', 'Canone mensile del conto', 'Costo di custodia titoli']], ['Implicito', ['Spread denaro-lettera', 'Margine sul cambio valuta', 'Interessi non pagati sulla liquidità']]] },
    { q: 'Chi fa cosa?', g: [['Broker o banca', ['Esegue gli ordini dei clienti', 'Custodisce i titoli nel dossier', 'Applica le commissioni di negoziazione']], ['SGR', ['Gestisce un fondo comune', 'Sceglie gli investimenti del fondo', 'Redige il regolamento del fondo']]] },
  ],
  scen: [
    { s: 'Valentina, 27 anni, vuole investire 100 € al mese in un ETF. La sua banca applica una commissione minima di 9 € per ordine; un broker online autorizzato chiede 1 €.', q: 'Cosa le conviene fare?', o: [
      { t: 'Confrontare il costo totale: 9 € su 100 € sono il 9% a ogni acquisto', ok: true, f: 'Giusto: con importi piccoli e frequenti il minimo fisso divora il rendimento. Il broker da 1 € costa l’1%: confronta anche canoni e altri costi.' },
      { t: 'Restare in banca: nel lungo periodo le commissioni non contano', ok: false, f: 'Contano moltissimo: un costo del 9% su ogni versamento richiede anni di rendimento solo per essere recuperato.' },
      { t: 'Scegliere il broker con l’app più bella, senza guardare i costi', ok: false, f: 'L’app conta, ma prima vengono autorizzazione e costi totali: sono loro a incidere sul risultato finale.' },
    ] },
    { s: 'Stefano, 42 anni, vede sui social un broker con “bonus di 500 € e leva fino a 1:500”. Ha sede in un Paese extra UE e non compare negli elenchi della CONSOB.', q: 'Cosa fa?', o: [
      { t: 'Non apre il conto: un abusivo non offre tutele', ok: true, f: 'Corretto: senza autorizzazione non hai tutele né controlli. Bonus e leve esagerate sono tipici degli operatori abusivi.' },
      { t: 'Apre il conto con una piccola somma, giusto per provare', ok: false, f: 'Anche una piccola somma può sparire, e spesso questi operatori insistono poi per farti versare di più.' },
      { t: 'Si fida perché il sito mostra molte recensioni positive', ok: false, f: 'Le recensioni si comprano o si inventano facilmente: l’unico controllo affidabile sono gli elenchi ufficiali.' },
    ] },
    { s: 'Anna, 66 anni, in filiale riceve la proposta di un fondo “della casa” con costi annui elevati. Non ha capito bene come funziona, ma il funzionario insiste per firmare subito.', q: 'Cosa fa?', o: [
      { t: 'Chiede il documento con costi e rischi e prende tempo per confrontare alternative', ok: true, f: 'Bene: l’intermediario deve informarla su costi e rischi. Prendere tempo e confrontare è un suo diritto.' },
      { t: 'Firma subito: la banca agisce solo nell’interesse del cliente', ok: false, f: 'La banca può avere un conflitto di interessi quando vende prodotti propri: per questo esistono obblighi di trasparenza.' },
      { t: 'Rifiuta qualsiasi investimento per principio, senza leggere nulla', ok: false, f: 'Il rifiuto a priori non è un’analisi: il problema non è investire, ma capire cosa si compra e quanto costa.' },
    ] },
    { s: 'Giorgio, 31 anni, apre un conto presso un broker di un altro Paese UE, autorizzato, che opera in regime dichiarativo.', q: 'Cosa deve tenere presente?', o: [
      { t: 'Dovrà dichiarare tutto e versare le imposte, IVAFE compresa', ok: true, f: 'Esatto: nel dichiarativo nessuno trattiene le tasse per lui. Deve dichiarare plusvalenze, redditi e investimenti esteri.' },
      { t: 'Non pagherà tasse in Italia, perché il broker è estero', ok: false, f: 'Il residente in Italia è tassato in Italia sui redditi ovunque prodotti: il broker estero non cambia questo obbligo.' },
      { t: 'Le imposte saranno trattenute in automatico dal broker', ok: false, f: 'Questo accade nel regime amministrato. Nel dichiarativo il calcolo e il versamento spettano al contribuente.' },
    ] },
  ],
  tip: 'Scegli il broker guardando il costo totale per il tuo modo di investire (importi, frequenza, valute) e verifica sempre che sia autorizzato.',
});
