FQC(15, {
  intro: 'Perché un titolo sale o scende? Scopri come l’incontro tra chi vuole comprare e chi vuole vendere forma il prezzo, minuto dopo minuto.',
  cards: [
    { t: 'Domanda contro offerta', x: 'In borsa la domanda è fatta dagli ordini di acquisto, l’offerta dagli ordini di vendita. Il prezzo si forma quando un compratore e un venditore trovano un accordo e si conclude un contratto.', v: { k: 'vs', a: ['Domanda', 'Chi vuole comprare, e a quale prezzo'], b: ['Offerta', 'Chi vuole vendere, e a quale prezzo'] } },
    { t: 'Dalla notizia al prezzo', x: 'Una notizia, come utili migliori del previsto, cambia le aspettative. I compratori accettano di pagare di più, i venditori chiedono di più: gli scambi si spostano su prezzi più alti.', v: { k: 'steps', s: ['Arriva una notizia', 'Cambiano le aspettative', 'Cambiano gli ordini', 'Si forma un nuovo prezzo'] } },
    { t: 'Cosa muove domanda e offerta', x: 'Domanda e offerta di un titolo cambiano con gli utili attesi dell’azienda, il livello dei tassi di interesse, le notizie economiche e l’umore degli investitori, che a volte amplifica tutto.', v: { k: 'icons', d: [['📊', 'Utili e prospettive'], ['🏦', 'Tassi di interesse'], ['📰', 'Notizie e dati economici'], ['😨', 'Emozioni e sentiment']] } },
    { t: 'Misurare il movimento', x: 'Le variazioni di prezzo si leggono in percentuale, sempre rispetto al prezzo di partenza. Attenzione: dopo un calo serve un rialzo percentuale più grande per tornare al punto di prima.', v: { k: 'formula', f: 'Variazione % = (prezzo finale − prezzo iniziale) / prezzo iniziale', n: 'Es.: da 20 € a 21 € → 1 / 20 = +5%' } },
    { t: 'Il prezzo d’asta', x: 'Nelle aste di apertura e chiusura la borsa sceglie il prezzo che permette di scambiare la quantità massima di titoli. In questo esempio a 10 € si scambiano 8.000 azioni, più che a ogni altro prezzo.', v: { k: 'bars', d: [['9,90 €', 3000], ['9,95 €', 5000], ['10,00 €', 8000], ['10,05 €', 6000]], u: 'azioni' } },
    { t: 'Un compratore, un venditore', x: 'Ogni scambio ha un compratore e un venditore per la stessa quantità. Il prezzo non sale perché ci sono “più compratori”, ma perché chi compra è più deciso e accetta prezzi più alti.', v: { k: 'stat', n: '1 = 1', l: 'per ogni azione comprata ce n’è una venduta' } },
  ],
  terms: [
    ['Domanda', 'Insieme degli ordini di chi vuole comprare un titolo, con i prezzi che è disposto a pagare.'],
    ['Offerta', 'Insieme degli ordini di chi vuole vendere un titolo, con i prezzi a cui è disposto a cedere.'],
    ['Prezzo di equilibrio', 'Livello a cui la quantità che si vuole comprare incontra quella che si vuole vendere.'],
    ['Asta di apertura', 'Fase iniziale in cui si raccolgono gli ordini e si fissa un unico prezzo che massimizza gli scambi.'],
    ['Negoziazione continua', 'Fase della seduta in cui i contratti si concludono appena due ordini compatibili si incontrano.'],
    ['Aspettative', 'Previsioni degli investitori su utili, tassi ed economia che guidano le loro decisioni.'],
    ['Sentiment', 'Umore prevalente del mercato, tra ottimismo e pessimismo, che può amplificare i movimenti.'],
    ['Ultimo prezzo', 'Prezzo dell’ultimo contratto concluso su un titolo durante la seduta.'],
  ],
  tf: [
    ['Il prezzo di un’azione sale perché ci sono più azioni comprate che azioni vendute.', false, 'In ogni scambio le azioni comprate e vendute sono le stesse. Il prezzo sale perché i compratori accettano di pagare di più.'],
    ['Una notizia attesa da tutti può muovere poco il prezzo quando viene annunciata.', true, 'Se il mercato se l’aspettava, era già in gran parte nel prezzo: contano le sorprese rispetto alle attese.'],
    ['Un’azienda che annuncia utili in crescita vede sempre salire il prezzo delle sue azioni.', false, 'Se gli utili crescono meno del previsto, il prezzo può scendere: conta il confronto con le aspettative.'],
    ['Nell’asta di apertura si sceglie il prezzo che consente di scambiare la quantità massima di titoli.', true, 'È il criterio principale dell’asta: il prezzo unico che fa incontrare più titoli tra compratori e venditori.'],
    ['Un forte aumento dei tassi di interesse può ridurre la domanda di azioni.', true, 'Con tassi più alti le alternative meno rischiose, come i titoli di Stato, rendono di più e gli utili futuri valgono meno oggi.'],
    ['Il prezzo di borsa coincide sempre con il valore reale dell’azienda.', false, 'Il prezzo è ciò che si paga oggi: riflette aspettative e umori e può allontanarsi a lungo dal valore stimato dei fondamentali.'],
    ['Se tutti vogliono vendere, il prezzo resta fermo perché non si trovano compratori.', false, 'Il prezzo scende finché qualcuno è disposto a comprare: con molta offerta e poca domanda si scambia più in basso.'],
    ['A Milano il prezzo di chiusura nasce da un’asta finale, dopo la negoziazione continua.', true, 'Gli ordini raccolti negli ultimi minuti formano un unico prezzo di chiusura, come in molte borse europee.'],
    ['Paura e avidità possono spingere i prezzi oltre quanto giustificato dalle notizie.', true, 'Il sentiment amplifica i movimenti: nel panico si vende anche a sconto, nell’euforia si paga troppo.'],
    ['L’ultimo prezzo mostrato è sempre quello a cui potrai comprare subito dopo.', false, 'È il prezzo dell’ultimo contratto concluso: il prossimo dipende dagli ordini presenti ora sul mercato.'],
  ],
  mcq: [
    { q: 'Un titolo passa da 40 € a 46 €. Qual è la variazione percentuale?', a: '+15%', w: ['+6%', '+13%', '+46%'], e: '(46 − 40) / 40 = 6 / 40 = 15%. Il 13% si ottiene sbagliando base e dividendo per 46.' },
    { q: 'Nell’asta di apertura, come viene scelto il prezzo?', a: 'È quello che permette di scambiare più titoli', w: ['È il prezzo di chiusura del giorno prima', 'È la media dei prezzi chiesti dai venditori', 'È il prezzo fissato dalla società quotata'], e: 'L’asta raccoglie gli ordini e cerca il prezzo unico che massimizza la quantità scambiata.' },
    { q: 'Un’azienda annuncia utili +10%, ma il mercato si aspettava +20%. Che cosa è più probabile?', a: 'Il prezzo scende perché il dato delude le attese', w: ['Il prezzo sale per forza perché gli utili crescono', 'Il prezzo resta fermo per legge fino al giorno dopo', 'Il titolo viene escluso dalla borsa per i conti'], e: 'I prezzi incorporano le aspettative: un risultato sotto le attese è una sorpresa negativa, anche se gli utili crescono.' },
    { q: 'Quale di questi fattori tende a ridurre la domanda di azioni?', a: 'Un forte aumento dei tassi di interesse', w: ['Utili superiori alle attese degli analisti', 'Un clima di fiducia diffuso sui mercati', 'Previsioni di crescita economica'], e: 'Tassi più alti rendono più attraenti le alternative meno rischiose e riducono il valore attuale degli utili futuri.' },
    { q: 'Da 50 € un titolo scende a 40 €. Di quanto deve salire per tornare a 50 €?', a: '+25%', w: ['+20%', '+10%', '+30%'], e: 'Il calo è del 20% (10 / 50), ma il recupero si calcola su 40: 10 / 40 = 25%.' },
    { q: 'Che cos’è il sentiment di mercato?', a: 'L’umore prevalente degli investitori', w: ['Il prezzo medio della giornata', 'Il giudizio ufficiale della CONSOB', 'Il numero di azioni scambiate'], e: 'Ottimismo e paura spingono a comprare o vendere più del necessario e possono amplificare i movimenti dei prezzi.' },
    { q: 'Quale evento aumenta il numero di azioni di una società in circolazione?', a: 'Un aumento di capitale con nuove azioni', w: ['Un riacquisto di azioni proprie', 'Il pagamento di un dividendo in denaro', 'Un calo dei tassi di interesse'], e: 'L’aumento di capitale crea nuove azioni; il riacquisto (buyback) le riduce; dividendi in denaro e tassi non cambiano il numero.' },
    { q: 'Che cosa indica l’ultimo prezzo di un titolo?', a: 'Il prezzo dell’ultimo contratto concluso', w: ['Il prezzo a cui comprerai di sicuro', 'Il prezzo di chiusura del giorno prima', 'La media dei prezzi della giornata'], e: 'È un dato del passato, anche se recentissimo: per sapere a quanto puoi comprare o vendere ora guarda gli ordini in attesa.' },
  ],
  fill: [
    { s: 'Il prezzo si forma dall’incontro tra domanda e ___.', a: 'offerta', w: ['inflazione', 'cedola', 'liquidità'] },
    { s: 'I prezzi reagiscono soprattutto alle ___ rispetto a quanto il mercato si aspettava.', a: 'sorprese', w: ['abitudini', 'ricorrenze', 'commissioni'] },
    { s: 'Nell’asta di apertura il prezzo è quello che massimizza la ___ scambiata.', a: 'quantità', w: ['commissione', 'volatilità', 'cedola'] },
    { s: 'L’umore prevalente degli investitori si chiama ___.', a: 'sentiment', w: ['spread', 'rating', 'flottante'] },
    { s: 'Da 80 € a 60 € un titolo perde il ___.', a: '25%', w: ['20%', '33%', '60%'] },
  ],
  order: [
    { q: 'Ordina la catena che porta a un nuovo prezzo', i: ['Esce una notizia inattesa', 'Gli investitori rivedono le aspettative', 'Cambiano gli ordini di acquisto e vendita', 'Si concludono contratti a un nuovo prezzo'], e: 'Il prezzo è l’ultimo anello: prima cambiano le attese, poi gli ordini, infine i contratti conclusi.' },
    { q: 'Ordina le fasi di una seduta tipica a Piazza Affari', i: ['Raccolta ordini prima dell’apertura', 'Asta di apertura', 'Negoziazione continua', 'Asta di chiusura'], e: 'Prima si raccolgono gli ordini e si fissa il prezzo d’apertura, poi si scambia in continua, infine l’asta stabilisce il prezzo di chiusura.' },
  ],
  cat: [
    { q: 'A parità di altre condizioni, spinge il prezzo verso l’alto o verso il basso?', g: [['Verso l’alto', ['Utili sopra le attese', 'Nuovo contratto importante', 'Calo inatteso dei tassi']], ['Verso il basso', ['Previsioni di utili tagliate', 'Forte aumento dei tassi', 'Perdita di un cliente chiave']]] },
    { q: 'Fa parte della domanda o dell’offerta?', g: [['Domanda', ['Ordine di acquisto a 10 €', 'Fondo che vuole entrare nel titolo', 'Risparmiatore che vuole comprare']], ['Offerta', ['Ordine di vendita a 10,10 €', 'Socio che vuole cedere la sua quota', 'Investitore che vuole incassare il guadagno']]] },
  ],
  scen: [
    { s: 'Elisa, 34 anni, legge il titolo “Utili record per la società X”. Apre l’app e scopre che le azioni di X perdono il 5%.', q: 'Come lo interpreta?', o: [
      { t: 'Confronta i risultati con le attese e le prospettive annunciate', ok: true, f: 'Giusto: probabilmente il mercato si aspettava ancora di più, o le previsioni per il futuro sono deboli. Contano le sorprese, non il dato in sé.' },
      { t: 'Pensa a un errore della borsa e chiede che il prezzo venga corretto', ok: false, f: 'Non c’è nessun errore: il prezzo nasce dagli ordini degli investitori, che hanno giudicato i conti meno buoni del previsto.' },
      { t: 'Compra subito molte azioni: con utili record il prezzo deve risalire', ok: false, f: 'Nessun prezzo “deve” salire. Prima di decidere serve capire perché il mercato ha reagito così.' },
    ] },
    { s: 'Lorenzo, 24 anni, legge su un forum: “Compra subito, il titolo salirà: ci sono molti più compratori che venditori!”.', q: 'Come valuta il messaggio?', o: [
      { t: 'La frase non dice nulla: ogni scambio ha due parti', ok: true, f: 'Esatto: per ogni azione comprata ce n’è una venduta. Messaggi del genere servono spesso a creare entusiasmo, non a informare.' },
      { t: 'Compra subito, prima che arrivino tutti gli altri', ok: false, f: 'Agire per paura di restare fuori, su un messaggio anonimo, è uno degli errori più costosi per chi investe.' },
      { t: 'Vende tutto, perché i forum sbagliano sempre', ok: false, f: 'Fare l’opposto di un forum non è una strategia: le decisioni vanno prese su analisi proprie, non per reazione.' },
    ] },
    { s: 'Rita, 48 anni, vuole vendere 2.000 azioni di una piccola società. Nel book ci sono pochi acquirenti, con prezzi sempre più bassi man mano che la quantità cresce.', q: 'Cosa fa?', o: [
      { t: 'Vende gradualmente, fissando un prezzo minimo accettabile', ok: true, f: 'Bene: con poca domanda, vendere tutto subito spingerebbe il prezzo in basso. Un limite di prezzo e un po’ di pazienza la tutelano.' },
      { t: 'Vende tutto subito, a qualunque prezzo', ok: false, f: 'Così “scende” lungo gli acquirenti disponibili e incassa sempre meno per ogni azione aggiuntiva.' },
      { t: 'Aspetta che la borsa fissi un prezzo più alto per lei', ok: false, f: 'La borsa non fissa prezzi per nessuno: il prezzo dipende solo da chi è disposto a comprare.' },
    ] },
    { s: 'Federico, 39 anni, ha in portafoglio le azioni di un’azienda. La sera, a mercati chiusi, la società annuncia di aver perso il suo cliente più importante.', q: 'Cosa si aspetta il mattino seguente?', o: [
      { t: 'Che l’asta di apertura incorpori subito la notizia, con un prezzo probabilmente più basso', ok: true, f: 'Corretto: gli ordini raccolti prima dell’apertura tengono conto della notizia. Il titolo può aprire già molto sotto la chiusura precedente.' },
      { t: 'Che il titolo apra al prezzo di ieri e scenda piano durante il giorno', ok: false, f: 'Il prezzo d’apertura non è vincolato a quello di ieri: può aprire subito molto più in basso (o in alto).' },
      { t: 'Che il titolo resti bloccato finché l’azienda non trova un nuovo cliente', ok: false, f: 'Le notizie, anche cattive, non bloccano gli scambi: il mercato le incorpora nel prezzo.' },
    ] },
  ],
  tip: 'Quando un titolo si muove, chiediti: cosa si aspettava il mercato? I prezzi reagiscono alle sorprese, non alle notizie già note a tutti.',
});
