FQC(16, {
  intro: 'Ogni titolo ha due prezzi: quello a cui puoi vendere e quello a cui puoi comprare. La differenza, lo spread, è un costo che paghi sempre.',
  cards: [
    { t: 'Denaro e lettera', x: 'Il bid (“denaro”) è il prezzo più alto che un compratore offre; l’ask (“lettera”) è il prezzo più basso chiesto da un venditore. Se compri subito paghi l’ask, se vendi subito incassi il bid.', v: { k: 'vs', a: ['Bid (denaro)', 'Proposta dei compratori: qui vendi'], b: ['Ask (lettera)', 'Proposta dei venditori: qui compri'] } },
    { t: 'Calcolare lo spread', x: 'Lo spread è la distanza tra ask e bid. Per confrontare titoli diversi si esprime in percentuale del prezzo medio: 4 centesimi pesano poco su un titolo da 10 €, molto su uno da 1 €.', v: { k: 'formula', f: 'Spread % = (ask − bid) / prezzo medio', n: 'Es.: bid 9,98 €, ask 10,02 € → 0,04 / 10 = 0,4%' } },
    { t: 'Andata e ritorno', x: 'Se compri e rivendi subito, senza che il prezzo cambi, perdi lo spread: comprando 1.000 azioni a 10,02 € e rivendendole a 9,98 € lasci sul tavolo 40 €, più le commissioni.', v: { k: 'steps', s: ['Compri all’ask: 10,02 €', 'Il prezzo resta fermo', 'Vendi al bid: 9,98 €', 'Perdi 0,04 € per azione'] } },
    { t: 'Spread stretti e spread ampi', x: 'Più un titolo è scambiato, più lo spread è stretto. Le grandi società e gli ETF molto diffusi hanno spread minimi; titoli piccoli o poco trattati possono arrivare a qualche punto percentuale.', v: { k: 'scale', a: 'Spread stretto', b: 'Spread ampio', d: [['Grande azione del FTSE MIB', 5], ['ETF molto scambiato', 10], ['Small cap poco scambiata', 60], ['Obbligazione illiquida', 85]] } },
    { t: 'Dentro il book', x: 'Il book mostra le proposte in acquisto e in vendita con le quantità. In cima ci sono il bid più alto e l’ask più basso; a parità di prezzo ha la precedenza l’ordine arrivato prima.', v: { k: 'bars', d: [['Bid 9,97 €', 2200], ['Bid 9,98 €', 1500], ['Ask 10,02 €', 800], ['Ask 10,03 €', 2500]], u: 'azioni' } },
    { t: 'Quando lo spread si allarga', x: 'Lo spread si allarga nei primi minuti di seduta, con notizie forti, sui titoli poco liquidi e quando il mercato del sottostante è chiuso: per esempio un ETF su azioni USA scambiato a Milano al mattino.', v: { k: 'icons', d: [['🌅', 'Inizio seduta'], ['📰', 'Notizie forti'], ['🐢', 'Titoli poco scambiati'], ['🌙', 'Sottostante chiuso']] } },
  ],
  terms: [
    ['Bid', 'Prezzo più alto a cui qualcuno è disposto a comprare; in italiano si chiama “denaro”.'],
    ['Ask', 'Prezzo più basso a cui qualcuno è disposto a vendere; in italiano si chiama “lettera”.'],
    ['Spread', 'Differenza tra il miglior prezzo in vendita e il miglior prezzo in acquisto.'],
    ['Prezzo medio', 'Valore a metà tra bid e ask, usato come riferimento per esprimere lo spread in percentuale.'],
    ['Book di negoziazione', 'Elenco delle proposte di acquisto e vendita in attesa, con prezzi e quantità.'],
    ['Profondità', 'Quantità di titoli disponibili ai vari livelli di prezzo, oltre alle migliori proposte.'],
    ['Market maker', 'Operatore che espone in continuo prezzi in acquisto e in vendita, fornendo liquidità.'],
    ['Tick', 'Variazione minima di prezzo ammessa per un titolo su un certo mercato.'],
  ],
  tf: [
    ['Se vuoi comprare subito un titolo, paghi il prezzo ask.', true, 'L’ask è il prezzo più basso a cui qualcuno vende ora: per comprare immediatamente devi accettarlo.'],
    ['Il bid è il prezzo a cui puoi comprare immediatamente.', false, 'Il bid è ciò che offrono i compratori: è il prezzo a cui tu puoi vendere subito. Per comprare subito paghi l’ask.'],
    ['In negoziazione continua il miglior bid è sempre inferiore al miglior ask.', true, 'Se un compratore offrisse almeno l’ask, i due ordini si incrocerebbero e il contratto verrebbe eseguito subito.'],
    ['Lo spread è un costo anche quando il broker non applica commissioni.', true, 'Compri più caro e vendi più a buon mercato del prezzo medio: è un costo implicito, che non compare in nessuna voce di spesa.'],
    ['Uno spread di 0,10 € pesa di più su un titolo da 50 € che su uno da 5 €.', false, 'In percentuale è l’opposto: 0,10 / 50 = 0,2%, mentre 0,10 / 5 = 2%. Lo spread va sempre valutato in percentuale.'],
    ['Gli spread tendono ad allargarsi nei momenti di forte volatilità o di notizie importanti.', true, 'Con più incertezza chi espone prezzi si tutela allargando la distanza tra acquisto e vendita.'],
    ['Un titolo poco scambiato ha di solito uno spread più stretto, perché ci sono meno ordini in competizione.', false, 'Meno ordini significa meno concorrenza tra compratori e venditori: lo spread tende ad allargarsi, non a stringersi.'],
    ['Il market maker si impegna a esporre prezzi sia in acquisto sia in vendita.', true, 'È il suo ruolo: garantisce una controparte quasi sempre presente e guadagna sulla differenza tra i due prezzi.'],
    ['Un ETF su azioni USA quotato a Milano ha spesso uno spread più ampio al mattino, quando Wall Street è chiusa.', true, 'Senza prezzi aggiornati del sottostante il market maker si copre allargando lo spread; dopo le 15:30 di solito si stringe.'],
    ['Comprare e rivendere subito un titolo, se il prezzo non cambia, costa solo le commissioni.', false, 'Compri all’ask e rivendi al bid: perdi lo spread su ogni azione, anche se il prezzo “non si è mosso”.'],
  ],
  mcq: [
    { q: 'Bid 4,95 €, ask 5,05 €. Quanto vale lo spread in percentuale del prezzo medio?', a: '2%', w: ['0,1%', '1%', '5%'], e: 'Spread = 0,10 €, prezzo medio = 5 €: 0,10 / 5 = 2%.' },
    { q: 'Vuoi vendere subito 100 azioni. Quale prezzo incassi?', a: 'Il bid, il miglior prezzo in acquisto', w: ['L’ask, il miglior prezzo in vendita', 'Il prezzo medio tra bid e ask', 'Il prezzo di chiusura di ieri'], e: 'Chi vende subito accetta la miglior proposta dei compratori, cioè il bid (denaro).' },
    { q: 'Compri 2.000 azioni a 3,02 € (ask) e le rivendi subito a 2,98 € (bid). Quanto perdi per lo spread?', a: '80 €', w: ['40 €', '8 €', '160 €'], e: '(3,02 − 2,98) × 2.000 = 0,04 × 2.000 = 80 €, commissioni escluse.' },
    { q: 'Che cosa fa un market maker?', a: 'Quota di continuo sia il bid sia l’ask', w: ['Decide quali società possono quotarsi', 'Calcola il valore degli indici di borsa', 'Vigila sulla correttezza degli scambi'], e: 'Garantisce liquidità esponendo sempre un bid e un ask. Ammissioni, indici e vigilanza spettano ad altri soggetti.' },
    { q: 'Quale titolo avrà con ogni probabilità lo spread più ampio?', a: 'Una small cap scambiata poche volte al giorno', w: ['Una grande banca presente nel FTSE MIB', 'Un ETF sull’S&P 500 scambiato moltissimo', 'Un BTP decennale molto trattato sul MOT'], e: 'Pochi scambi e pochi ordini nel book significano meno concorrenza sui prezzi e quindi spread più ampi.' },
    { q: 'In italiano, come si chiama il prezzo ask?', a: 'Lettera', w: ['Denaro', 'Cedola', 'Riferimento'], e: 'Nel gergo di borsa italiano ask si dice lettera (il prezzo dei venditori) e bid si dice denaro (il prezzo dei compratori).' },
    { q: 'Nel book, a parità di prezzo, quale ordine viene eseguito per primo?', a: 'Quello inserito per primo', w: ['Quello di quantità maggiore', 'Quello del cliente più ricco', 'Quello inserito per ultimo'], e: 'Vale la priorità prezzo-tempo: prima il prezzo migliore, poi, a parità di prezzo, l’orario di arrivo.' },
    { q: 'Che cos’è il tick?', a: 'La variazione minima di prezzo ammessa', w: ['La commissione minima per ordine', 'Il numero di contratti di una seduta', 'Il ritardo nella pubblicazione dei prezzi'], e: 'Il prezzo si muove a scatti di almeno un tick: per questo lo spread non può mai essere inferiore a un tick.' },
  ],
  fill: [
    { s: 'Il prezzo a cui puoi comprare subito si chiama ___.', a: 'ask', w: ['bid', 'mid', 'tick'] },
    { s: 'In italiano il bid si chiama ___.', a: 'denaro', w: ['lettera', 'cedola', 'valuta'] },
    { s: 'Lo ___ è la differenza tra ask e bid.', a: 'spread', w: ['slippage', 'yield', 'stop'] },
    { s: 'L’elenco delle proposte in attesa con prezzi e quantità si chiama ___ di negoziazione.', a: 'book', w: ['ticker', 'listino', 'report'] },
    { s: 'Più un titolo è scambiato, più lo spread tende a essere ___.', a: 'stretto', w: ['ampio', 'negativo', 'fisso'] },
  ],
  order: [
    { q: 'Ordina dal prezzo più basso al più alto', i: ['Secondo miglior bid', 'Miglior bid', 'Prezzo medio', 'Miglior ask', 'Secondo miglior ask'], e: 'I bid stanno sotto, gli ask sopra; il prezzo medio è a metà tra miglior bid e miglior ask.' },
    { q: 'Ordina dallo spread tipicamente più stretto al più ampio', i: ['Grande azione del FTSE MIB', 'Azione di media capitalizzazione', 'Small cap su Euronext Growth Milan', 'Obbligazione societaria scambiata di rado'], e: 'Lo spread cresce man mano che scambi e ordini nel book diminuiscono.' },
  ],
  cat: [
    { q: 'Spread tipicamente stretto o ampio?', g: [['Stretto', ['Grande titolo a metà seduta', 'ETF molto scambiato con sottostante aperto', 'BTP molto trattato sul MOT']], ['Ampio', ['Primi minuti di seduta', 'Small cap con pochi scambi', 'Subito dopo una notizia shock']]] },
    { q: 'Bid o ask?', g: [['Bid (denaro)', ['Prezzo a cui vendi subito', 'Proposta dei compratori', 'Il più basso dei due prezzi']], ['Ask (lettera)', ['Prezzo a cui compri subito', 'Proposta dei venditori', 'Il più alto dei due prezzi']]] },
  ],
  scen: [
    { s: 'Simone, 26 anni, alle 9:10 vuole comprare un ETF su azioni USA quotato a Milano. Lo spread è dello 0,8%, mentre di solito nel pomeriggio è intorno allo 0,1%.', q: 'Cosa fa?', o: [
      { t: 'Aspetta il pomeriggio, quando Wall Street è aperta, o usa un ordine con limite', ok: true, f: 'Bene: senza fretta conviene operare quando il sottostante è aperto e lo spread è più stretto, oppure fissare il prezzo massimo.' },
      { t: 'Compra subito al meglio: lo spread è un dettaglio irrilevante', ok: false, f: 'Lo 0,8% è otto volte il solito: un costo evitabile che si paga subito, prima ancora di iniziare.' },
      { t: 'Rinuncia agli ETF: costano sempre troppo', ok: false, f: 'Lo spread alto è legato all’orario, non allo strumento: basta scegliere il momento giusto.' },
    ] },
    { s: 'Nadia, 52 anni, guarda un titolo poco scambiato: ultimo prezzo 12 €, ma nel book il bid è 11,40 € e l’ask 12,60 €.', q: 'Come valuta l’acquisto?', o: [
      { t: 'Calcola lo spread: 1,20 € su 12 €, cioè il 10%', ok: true, f: 'Esatto: 1,20 € su un prezzo medio di 12 € è il 10%. Il titolo dovrebbe salire molto solo per compensare questo costo.' },
      { t: 'Compra pensando di pagare 12 €, il prezzo mostrato', ok: false, f: 'L’ultimo prezzo è un contratto passato: oggi per comprare subito deve accettare l’ask a 12,60 €.' },
      { t: 'Compra perché uno spread ampio indica un titolo in crescita', ok: false, f: 'Lo spread ampio indica scarsa liquidità, non prospettive di crescita: è un costo, non un segnale positivo.' },
    ] },
    { s: 'Tommaso, 31 anni, ha iniziato a fare trading: compra e vende lo stesso titolo circa 20 volte al giorno. Lo spread medio è dello 0,3%.', q: 'Cosa dovrebbe capire?', o: [
      { t: 'Ogni andata e ritorno paga lo spread: i costi si sommano', ok: true, f: 'Giusto: 0,3% × 20 = 6% al giorno di costi impliciti, commissioni escluse. Per guadagnare deve battere ogni volta questa soglia.' },
      { t: 'Lo spread conta solo per chi investe a lungo termine', ok: false, f: 'È il contrario: chi investe a lungo paga lo spread poche volte, chi fa trading lo paga a ogni operazione.' },
      { t: 'Più operazioni fa, più lo spread si riduce', ok: false, f: 'Lo spread dipende dal mercato, non da quante volte operi: ogni operazione in più lo paga di nuovo.' },
    ] },
    { s: 'Laura, 44 anni, vuole vendere obbligazioni societarie sul MOT. Bid 97, ask 99, ma sul bid la quantità esposta è piccola. Non ha fretta di incassare.', q: 'Cosa fa?', o: [
      { t: 'Mette un ordine con limite vicino al prezzo medio e attende', ok: true, f: 'Bene: senza fretta può chiedere un prezzo migliore del bid e lasciare che sia il mercato a venirle incontro.' },
      { t: 'Vende tutto al meglio subito, anche oltre la quantità sul bid', ok: false, f: 'Esaurita la quantità a 97, scenderebbe sui prezzi successivi, ancora più bassi: un costo inutile senza urgenza.' },
      { t: 'Chiede all’emittente di ricomprarle al prezzo di emissione', ok: false, f: 'L’emittente non è obbligato a ricomprarle prima della scadenza: la via è vendere sul mercato o aspettare il rimborso.' },
    ] },
  ],
  tip: 'Prima di inviare un ordine guarda bid, ask e quantità nel book: uno spread ampio è un costo certo, e spesso basta aspettare o usare un limite.',
});
