FQC(17, {
  intro: 'Al meglio, con limite, stop o stop-limit: ogni ordine bilancia velocità e controllo del prezzo. Impara a scegliere quello giusto.',
  cards: [
    { t: 'Al meglio o con limite?', x: 'L’ordine al meglio (a mercato) viene eseguito subito ai migliori prezzi disponibili, qualunque siano. L’ordine con limite fissa il prezzo massimo per comprare o minimo per vendere, ma potrebbe non essere eseguito.', v: { k: 'vs', a: ['Al meglio', 'Esecuzione rapida, prezzo incerto'], b: ['Con limite', 'Prezzo sotto controllo, esecuzione incerta'] } },
    { t: 'Quando l’ordine “mangia” il book', x: 'Un ordine al meglio di 1.000 azioni può consumare più livelli del book: 300 a 10,00 €, 500 a 10,02 € e 200 a 10,05 €. Spesa totale 10.020 €: prezzo medio 10,02 €, più dell’ask iniziale.', v: { k: 'bars', d: [['300 az. a 10,00 €', 3000], ['500 az. a 10,02 €', 5010], ['200 az. a 10,05 €', 2010]], u: '€' } },
    { t: 'L’ordine stop', x: 'Un ordine stop resta dormiente finché il prezzo non tocca il livello di attivazione; poi diventa un ordine al meglio. Serve a limitare le perdite, ma in un crollo improvviso puoi vendere molto sotto lo stop.', v: { k: 'steps', s: ['Fissi il prezzo di attivazione', 'Il mercato tocca lo stop', 'Nasce un ordine al meglio', 'Esecuzione al prezzo disponibile'] } },
    { t: 'Lo stop-limit', x: 'Lo stop-limit, una volta attivato, diventa un ordine con limite. Ti protegge da prezzi troppo bassi, ma se il titolo scende di colpo sotto il limite l’ordine resta ineseguito e tu resti con i titoli.', v: { k: 'formula', f: 'Stop-limit = prezzo di attivazione + prezzo limite', n: 'Es.: stop 18 €, limite 17,80 €: vendi solo a 17,80 € o più' } },
    { t: 'Per quanto vale l’ordine', x: 'La validità dice quanto resta attivo l’ordine: solo per la seduta, fino a una data, fino a revoca (entro i limiti del mercato) o per un istante, come “esegui e cancella” e “tutto o niente”.', v: { k: 'icons', d: [['📅', 'Giornaliero'], ['🗓️', 'Fino a data'], ['♾️', 'Fino a revoca'], ['⚡', 'Esegui e cancella']] } },
    { t: 'Velocità contro controllo', x: 'Ogni ordine sceglie un punto tra velocità e controllo: al meglio e stop privilegiano l’esecuzione, con limite e stop-limit privilegiano il prezzo, accettando che l’ordine possa restare ineseguito.', v: { k: 'scale', a: 'Massima velocità', b: 'Massimo controllo del prezzo', d: [['Al meglio', 5], ['Stop', 25], ['Stop-limit', 70], ['Con limite', 90]] } },
  ],
  terms: [
    ['Ordine al meglio', 'Ordine eseguito subito ai migliori prezzi disponibili, senza un prezzo massimo o minimo.'],
    ['Ordine con limite', 'Ordine che fissa il prezzo massimo per comprare o il prezzo minimo per vendere.'],
    ['Ordine stop', 'Ordine che si attiva al raggiungimento di un prezzo e diventa allora un ordine al meglio.'],
    ['Stop-limit', 'Ordine che, toccato il prezzo di attivazione, diventa un ordine con un limite di prezzo prefissato.'],
    ['Esecuzione parziale', 'Caso in cui solo una parte della quantità richiesta viene scambiata e il resto attende.'],
    ['Esegui e cancella', 'Validità per cui l’ordine si esegue subito per quanto possibile e la parte residua si annulla.'],
    ['Tutto o niente', 'Validità per cui l’ordine si esegue subito per l’intera quantità oppure viene cancellato.'],
    ['Slippage', 'Differenza tra il prezzo atteso e quello effettivamente ottenuto al momento dell’esecuzione.'],
  ],
  tf: [
    ['Un ordine al meglio garantisce il prezzo che vedi sullo schermo quando lo invii.', false, 'Punta all’esecuzione immediata, non al prezzo: il book può cambiare in un attimo o l’ordine può consumare più livelli.'],
    ['Un ordine di acquisto con limite 10,10 € può essere eseguito a 10,00 € se c’è un venditore a quel prezzo.', true, 'Il limite è il prezzo massimo: se trovi un’offerta migliore, compri al prezzo più conveniente.'],
    ['Un ordine con limite viene sempre eseguito entro la fine della giornata.', false, 'Se il mercato non raggiunge il tuo prezzo, l’ordine resta ineseguito: è il prezzo da pagare per il controllo.'],
    ['Uno stop di vendita a 20 € garantisce di vendere esattamente a 20 €.', false, 'Toccato lo stop, l’ordine diventa al meglio: se il titolo apre in forte ribasso, ad esempio a 18 €, vendi intorno a quel prezzo.'],
    ['Uno stop-limit può restare ineseguito se il prezzo scende rapidamente sotto il limite.', true, 'Attivato lo stop nasce un ordine con limite: se il mercato è già più in basso, nessuno compra al tuo prezzo minimo.'],
    ['Un ordine stop di acquisto si posiziona di solito sopra il prezzo corrente.', true, 'Serve a comprare solo se il titolo supera un certo livello, ad esempio per entrare dopo una rottura al rialzo.'],
    ['Un ordine con validità “tutto o niente” può essere eseguito solo in parte.', false, 'O si esegue subito l’intera quantità o l’ordine viene cancellato: le esecuzioni parziali sono escluse.'],
    ['Un ordine con limite può essere eseguito solo in parte se al tuo prezzo non c’è abbastanza quantità.', true, 'Compri o vendi quello che trovi al tuo prezzo; il resto rimane nel book in attesa, salvo validità diverse.'],
    ['Su titoli poco liquidi un ordine al meglio può ottenere prezzi molto diversi da quelli attesi.', true, 'Con pochi ordini nel book l’ordine scende o sale di parecchi livelli: lo slippage può essere pesante.'],
    ['Un ordine giornaliero non eseguito resta attivo anche nelle sedute successive.', false, 'A fine seduta l’ordine giornaliero viene cancellato: per riproporlo devi reinserirlo o scegliere un’altra validità.'],
  ],
  mcq: [
    { q: 'Vuoi comprare un titolo, ma senza pagare più di 25 €. Quale ordine usi?', a: 'Un ordine di acquisto con limite a 25 €', w: ['Un ordine di acquisto al meglio', 'Un ordine stop di acquisto a 25 €', 'Un ordine stop di vendita a 25 €'], e: 'Solo il limite fissa un tetto al prezzo. Lo stop di acquisto, toccati 25 €, diventa al meglio e potresti pagare di più.' },
    { q: 'Nel book ci sono 300 azioni a 10,00 €, 500 a 10,02 € e 1.000 a 10,05 €. Compri 800 azioni al meglio: prezzo medio?', a: '10,01 €', w: ['10,00 €', '10,02 €', '10,05 €'], e: '300 × 10,00 + 500 × 10,02 = 8.010 €; diviso 800 azioni fa circa 10,01 € di media.' },
    { q: 'Hai azioni a 30 € e vuoi uscire se scendono sotto 27 €. Quale ordine è tipico?', a: 'Uno stop di vendita a 27 €', w: ['Un limite di vendita a 27 €', 'Uno stop di acquisto a 27 €', 'Un acquisto al meglio'], e: 'Un limite di vendita a 27 € verrebbe eseguito subito a circa 30 €, perché vendere sopra il minimo è consentito. Serve lo stop.' },
    { q: 'Stop-limit di vendita: stop 18 €, limite 17,80 €. Il titolo apre a 17 €. Cosa succede?', a: 'Si attiva ma resta ineseguito', w: ['Viene eseguito a 18 €', 'Viene eseguito a 17 €', 'Diventa un ordine al meglio'], e: 'Lo stop è toccato e nasce un ordine con limite a 17,80 €: con il prezzo a 17 € nessuno compra così in alto.' },
    { q: 'Quale validità cancella subito la parte di ordine non eseguita?', a: 'Esegui e cancella', w: ['Valido fino a revoca', 'Valido fino a data', 'Giornaliero'], e: 'Con “esegui e cancella” si scambia subito quanto disponibile e il residuo si annulla, senza restare nel book.' },
    { q: 'Che cos’è lo slippage?', a: 'La differenza tra prezzo atteso e ottenuto', w: ['La commissione minima applicata dal broker', 'Il ritardo nella conferma dell’ordine', 'Lo sconto riservato agli ordini con limite'], e: 'Nasce quando il prezzo si muove o la quantità ai prezzi migliori non basta. È tipico degli ordini al meglio e degli stop.' },
    { q: 'Il titolo vale 14 € e hai un ordine di vendita con limite a 15 €. Perché non viene eseguito?', a: 'Perché nessuno compra a 15 € o più', w: ['Perché la borsa rifiuta limiti sopra il prezzo', 'Perché i limiti valgono solo per comprare', 'Perché prima deve scattare uno stop'], e: 'Il limite di vendita è il prezzo minimo: l’ordine aspetta nel book finché un compratore non accetta almeno 15 €.' },
    { q: 'Quale affermazione sugli ordini stop è corretta?', a: 'In un gap possono essere eseguiti oltre lo stop', w: ['Garantiscono sempre il prezzo di attivazione', 'Vengono eseguiti solo nell’asta di chiusura', 'Non possono mai essere usati per comprare'], e: 'Se il titolo apre molto lontano dallo stop, l’ordine diventa al meglio e si esegue al primo prezzo disponibile.' },
  ],
  fill: [
    { s: 'Un ordine al ___ viene eseguito subito ai prezzi migliori disponibili.', a: 'meglio', w: ['limite', 'termine', 'rialzo'] },
    { s: 'In un ordine con limite di acquisto fissi il prezzo ___ che sei disposto a pagare.', a: 'massimo', w: ['minimo', 'medio', 'nominale'] },
    { s: 'Toccato il livello di attivazione, un ordine stop diventa un ordine ___.', a: 'al meglio', w: ['con limite', 'tutto o niente', 'annullato'] },
    { s: 'Con validità “___ o niente” l’ordine si esegue tutto e subito, altrimenti viene cancellato.', a: 'tutto', w: ['meglio', 'sempre', 'subito'] },
    { s: 'Se compri solo 300 azioni delle 1.000 richieste, l’esecuzione è ___.', a: 'parziale', w: ['completa', 'condizionata', 'anticipata'] },
  ],
  order: [
    { q: 'Ordina il funzionamento di uno stop-limit di vendita', i: ['Imposti stop e limite', 'L’ordine resta in attesa', 'Il prezzo tocca lo stop', 'Nasce un ordine con limite', 'Si esegue al limite o meglio'], e: 'Lo stop fa da interruttore; il limite stabilisce il prezzo minimo accettabile una volta attivato l’ordine.' },
    { q: 'Ordina le validità dalla più breve alla più lunga', i: ['Esegui e cancella', 'Giornaliero', 'Fino a data, tra una settimana', 'Fino a revoca'], e: '“Esegui e cancella” dura un istante, il giornaliero una seduta; fino a revoca resta attivo più a lungo, entro i limiti del mercato o del broker.' },
  ],
  cat: [
    { q: 'Cosa privilegia l’ordine?', g: [['Rapidità di esecuzione', ['Ordine al meglio', 'Ordine stop', 'Vendita al meglio in apertura']], ['Controllo del prezzo', ['Ordine con limite', 'Stop-limit', 'Acquisto con limite sotto il prezzo attuale']]] },
    { q: 'Stop di acquisto o stop di vendita?', g: [['Stop di acquisto', ['Comprare solo se il titolo supera 50 €', 'Entrare dopo un rialzo confermato', 'Comprare se il prezzo rompe il massimo recente']], ['Stop di vendita', ['Limitare la perdita sotto 40 €', 'Proteggere un guadagno se il titolo scende', 'Uscire se il prezzo rompe il minimo recente']]] },
  ],
  scen: [
    { s: 'Beatrice, 36 anni, vuole comprare 500 azioni di una small cap poco scambiata. Nel book in vendita ci sono 100 azioni a 4,00 €, 200 a 4,20 € e 300 a 4,50 €.', q: 'Che ordine usa?', o: [
      { t: 'Un ordine con limite a 4,05 €, senza fretta', ok: true, f: 'Bene: fissa il prezzo massimo e lascia che i venditori arrivino. Può ottenere un’esecuzione parziale, ma evita prezzi eccessivi.' },
      { t: 'Un ordine al meglio per tutte le 500 azioni', ok: false, f: 'Pagherebbe 100 a 4,00, 200 a 4,20 e 200 a 4,50 €: prezzo medio 4,28 €, il 7% sopra il primo ask.' },
      { t: 'Uno stop di acquisto a 4,00 €', ok: false, f: 'Lo stop di acquisto va sopra il prezzo corrente: qui scatterebbe subito, diventando al meglio, con lo stesso problema.' },
    ] },
    { s: 'Carlo, 58 anni, ha comprato azioni a 40 € che ora valgono 50 €. Parte per due settimane senza internet e vuole proteggere il guadagno se il titolo scende sotto 45 €.', q: 'Cosa fa?', o: [
      { t: 'Uno stop di vendita a 45 € valido fino a una data dopo il rientro', ok: true, f: 'Corretto: lo stop resta attivo per tutto il viaggio. Sa però che, in caso di brusco ribasso in apertura, potrebbe vendere sotto 45 €.' },
      { t: 'Un ordine con limite di vendita a 45 €', ok: false, f: 'Un limite di vendita a 45 € con il titolo a 50 € verrebbe eseguito subito, a circa 50 €: venderebbe ora, non in caso di calo.' },
      { t: 'Uno stop di vendita a 45 € con validità giornaliera', ok: false, f: 'L’ordine giornaliero scade a fine seduta: dal giorno dopo non sarebbe più protetto.' },
    ] },
    { s: 'Irene, 23 anni, vuole comprare un ETF a non più di 80 €. In questo momento l’ask è 80,40 €. Non ha fretta.', q: 'Che ordine sceglie?', o: [
      { t: 'Un ordine con limite a 80 €, valido più giorni', ok: true, f: 'Bene: comprerà solo a 80 € o meno. Se il prezzo non scende, l’ordine resta ineseguito, ed è un rischio che accetta.' },
      { t: 'Un ordine al meglio, da inviare subito', ok: false, f: 'Pagherebbe subito circa 80,40 €, sopra il suo tetto: il contrario di ciò che vuole.' },
      { t: 'Uno stop di acquisto a 80 €, valido più giorni', ok: false, f: 'Lo stop di acquisto si usa sopra il prezzo corrente: qui il prezzo è già oltre gli 80 €, quindi non le garantirebbe affatto quel tetto.' },
    ] },
    { s: 'Gianni, 47 anni, aveva uno stop-limit di vendita con stop a 30 € e limite a 29,80 €. Dopo una brutta notizia notturna il titolo apre a 26 € e il suo ordine non viene eseguito.', q: 'Cosa fa ora?', o: [
      { t: 'Capisce che il prezzo è sotto il limite e decide con calma se vendere o tenere', ok: true, f: 'Esatto: lo stop-limit ha funzionato come previsto, ma non poteva vendere sotto 29,80 €. Ora serve valutare la notizia, non agire d’impulso.' },
      { t: 'Contesta alla borsa l’errore e chiede di vendere a 30 €', ok: false, f: 'Non c’è errore: nessuno era disposto a comprare a 29,80 € o più. Le regole dell’ordine sono state rispettate.' },
      { t: 'Aspetta: lo stop-limit garantisce comunque di vendere a 29,80 €', ok: false, f: 'Lo stop-limit garantisce il prezzo minimo, non l’esecuzione: se il titolo non risale, l’ordine può restare ineseguito.' },
    ] },
  ],
  tip: 'Su titoli poco scambiati e nei momenti agitati preferisci ordini con limite. E ricorda: uno stop non garantisce il prezzo, garantisce solo che l’ordine parta.',
});
