FQC(18, {
  intro: 'Un titolo è liquido se puoi comprarlo o venderlo in fretta, a costi bassi e senza muoverne il prezzo. Scopri come misurarlo con volumi e spread.',
  cards: [
    { t: 'Le facce della liquidità', x: 'Un mercato liquido permette di scambiare in fretta, con spread stretti, grandi quantità disponibili a ogni livello di prezzo e prezzi che si riassestano rapidamente dopo un ordine grosso.', v: { k: 'icons', d: [['⏱️', 'Rapidità'], ['💶', 'Spread stretto'], ['📚', 'Profondità del book'], ['🔄', 'Prezzo che si riprende']] } },
    { t: 'Volume e controvalore', x: 'Il volume conta i pezzi scambiati, il controvalore il denaro. 1 milione di azioni a 2 € (2 milioni di euro) muove meno denaro di 100.000 azioni a 50 € (5 milioni): per confrontare titoli guarda il controvalore.', v: { k: 'vs', a: ['Volume', 'Numero di titoli scambiati'], b: ['Controvalore', 'Euro scambiati: volume × prezzo'] } },
    { t: 'Dal contante all’illiquido', x: 'Grandi azioni e titoli di Stato molto trattati si vendono in pochi secondi, una piccola società può richiedere giorni, un immobile mesi. Meno liquidità significa di solito costi più alti e tempi più lunghi per uscire.', v: { k: 'scale', a: 'Molto liquido', b: 'Poco liquido', d: [['Azione del FTSE MIB', 10], ['BTP molto scambiato', 15], ['Small cap', 55], ['Immobile', 85], ['Quota di società non quotata', 95]] } },
    { t: 'Quanto pesa il tuo ordine', x: 'Confronta la quantità che vuoi scambiare con il volume medio giornaliero del titolo. Se il tuo ordine vale una quota importante degli scambi di una giornata, rischi di spostare il prezzo contro di te.', v: { k: 'formula', f: 'Peso dell’ordine = quantità / volume medio giornaliero', n: 'Es.: 20.000 azioni su 400.000 al giorno = 5%' } },
    { t: 'Due titoli a confronto', x: 'Esempio: il titolo A scambia 5 milioni di azioni al giorno, il titolo B appena 20.000. Vendere 10.000 azioni di A passa inosservato; per B equivale a metà degli scambi di un’intera giornata.', v: { k: 'bars', d: [['Titolo A', 5000000], ['Titolo B', 20000]], u: 'azioni al giorno' } },
    { t: 'La giornata a forma di U', x: 'Durante la seduta i volumi sono di solito più alti all’apertura e verso la chiusura, asta finale compresa, e più bassi a metà giornata. Nei primi minuti però gli spread sono spesso più ampi.', v: { k: 'stat', n: 'U', l: 'forma tipica dei volumi durante la seduta' } },
  ],
  terms: [
    ['Liquidità di mercato', 'Facilità di comprare o vendere un titolo in fretta, a basso costo e senza spostarne il prezzo.'],
    ['Volume', 'Numero di titoli scambiati in un certo periodo, ad esempio in una seduta.'],
    ['Controvalore', 'Valore in denaro degli scambi: quantità scambiata moltiplicata per il prezzo.'],
    ['Volume medio giornaliero', 'Media dei titoli scambiati ogni giorno in un periodo, usata per stimare la liquidità.'],
    ['Impatto di mercato', 'Spostamento del prezzo causato da un ordine grande rispetto agli scambi disponibili.'],
    ['Rischio di liquidità', 'Rischio di non riuscire a vendere in tempi brevi senza accettare un forte sconto.'],
    ['Flottante', 'Quota delle azioni di una società liberamente scambiabile sul mercato, esclusi i soci stabili.'],
    ['Premio di illiquidità', 'Rendimento extra che gli investitori chiedono per detenere attività difficili da vendere.'],
  ],
  tf: [
    ['Liquidità di mercato e liquidità sul conto sono la stessa cosa.', false, 'Sul conto è il denaro disponibile; quella di mercato è la facilità di comprare e vendere un titolo senza spostarne il prezzo.'],
    ['Un volume record in un giorno di ribasso significa che quel giorno nessuno ha comprato.', false, 'Per ogni azione venduta qualcuno l’ha comprata: il volume misura quanto si è scambiato, non chi ha “vinto”.'],
    ['A parità di altre condizioni, un titolo più liquido ha di solito uno spread più stretto.', true, 'Più ordini e più scambi significano più concorrenza sui prezzi: la distanza tra bid e ask si riduce.'],
    ['Nelle fasi di crisi la liquidità può ridursi bruscamente proprio quando molti vogliono vendere.', true, 'Nel panico i compratori si ritirano, gli spread si allargano e vendere costa di più: è successo in diverse crisi.'],
    ['Un titolo che scambia 1 milione di azioni al giorno muove sempre più euro di uno che ne scambia 200.000.', false, 'Dipende dal prezzo: 1 milione di azioni a 1 € sono 1 milione di €, 200.000 azioni a 20 € sono 4 milioni di €.'],
    ['Vendere in un colpo una quantità pari a metà del volume medio giornaliero può far scendere il prezzo.', true, 'Un ordine così grande esaurisce gli acquirenti ai prezzi migliori e scende su livelli più bassi: è l’impatto di mercato.'],
    ['Per detenere attività difficili da vendere, gli investitori chiedono di solito un rendimento atteso più alto.', true, 'È il premio di illiquidità: chi rinuncia alla possibilità di uscire in fretta vuole essere compensato.'],
    ['La liquidità di un titolo resta sempre la stessa nel tempo.', false, 'Cambia con l’orario della seduta, le notizie, le condizioni di mercato e l’interesse degli investitori.'],
    ['Un flottante ridotto tende a rendere un titolo meno liquido.', true, 'Se gran parte delle azioni è in mano a soci stabili che non vendono, ne restano poche da scambiare sul mercato.'],
    ['Un immobile si vende di norma più rapidamente di un’azione di una grande società quotata.', false, 'L’azione si vende in pochi secondi in borsa; per un immobile servono in genere settimane o mesi, con costi elevati.'],
  ],
  mcq: [
    { q: 'Quale descrizione corrisponde a un titolo liquido?', a: 'Si scambia in fretta, con costi e impatto bassi', w: ['Ha un prezzo che sale quasi tutti i giorni', 'Paga ogni anno un dividendo molto elevato', 'È emesso da una società con molta cassa'], e: 'La liquidità riguarda la facilità di scambio, non il rendimento né la solidità dell’azienda.' },
    { q: 'Un titolo scambia 300.000 azioni al giorno a 8 €. Qual è il controvalore giornaliero?', a: '2,4 milioni di euro', w: ['300.000 euro', '24 milioni di euro', '37.500 euro'], e: '300.000 × 8 € = 2.400.000 €, cioè 2,4 milioni di euro.' },
    { q: 'Devi vendere 50.000 azioni di un titolo che ne scambia 100.000 al giorno. Qual è il rischio principale?', a: 'Far scendere il prezzo vendendo tutto subito', w: ['Pagare per legge una commissione doppia', 'Non poter più vendere il titolo in futuro', 'Ricevere il pagamento in un’altra valuta'], e: 'Il tuo ordine vale metà degli scambi giornalieri: venderlo tutto insieme esaurirebbe gli acquirenti e abbasserebbe il prezzo.' },
    { q: 'In quale momento della seduta i volumi sono di solito più bassi?', a: 'A metà giornata', w: ['All’apertura', 'Verso la chiusura', 'Durante l’asta finale'], e: 'La curva tipica dei volumi è a U: alta all’apertura e in chiusura, più bassa a metà seduta.' },
    { q: 'Che cosa misura il volume?', a: 'Quante unità di un titolo sono state scambiate', w: ['Quanti investitori hanno guadagnato', 'Di quanto è salito il prezzo nella seduta', 'Quante azioni la società ha emesso in tutto'], e: 'Il volume conta i titoli passati di mano in un periodo; non dice nulla su chi ha guadagnato o sulla direzione futura.' },
    { q: 'Quale di questi investimenti è in genere il meno liquido?', a: 'Una quota di una società non quotata', w: ['Un BTP decennale molto scambiato', 'Un’azione presente nel FTSE MIB', 'Un ETF azionario globale molto diffuso'], e: 'Senza un mercato organizzato bisogna trovare un acquirente privato: può richiedere mesi e un forte sconto.' },
    { q: 'Perché nelle crisi la liquidità diventa un problema?', a: 'Perché i compratori si ritirano e gli spread crescono', w: ['Perché le borse chiudono per legge a ogni crisi', 'Perché i titoli smettono di avere un prezzo', 'Perché gli ordini diventano tutti gratuiti'], e: 'Quando molti vogliono vendere e pochi comprare, uscire costa di più ed è più lento proprio nel momento peggiore.' },
    { q: 'Il titolo X scende dell’8% con un volume record. Cosa puoi dire con certezza?', a: 'Molte azioni sono passate di mano', w: ['Nessuno ha comprato il titolo', 'Il titolo risalirà il giorno dopo', 'La società ha emesso nuove azioni'], e: 'Il volume alto dice solo che si è scambiato molto: ogni azione venduta ha trovato un compratore, a prezzi più bassi.' },
  ],
  fill: [
    { s: 'Il ___ è il numero di titoli scambiati in un periodo.', a: 'volume', w: ['flottante', 'dividendo', 'nominale'] },
    { s: 'Quantità scambiata per prezzo dà il ___ degli scambi.', a: 'controvalore', w: ['rendimento', 'flottante', 'rating'] },
    { s: 'La quota di azioni liberamente scambiabile sul mercato si chiama ___.', a: 'flottante', w: ['capitale sociale', 'riserva legale', 'dividendo'] },
    { s: 'Il rischio di non riuscire a vendere in fretta senza un forte sconto è il rischio di ___.', a: 'liquidità', w: ['cambio', 'tasso', 'credito'] },
    { s: 'Un ordine grande rispetto agli scambi disponibili ha un forte ___ di mercato.', a: 'impatto', w: ['rendimento', 'indice', 'dividendo'] },
  ],
  order: [
    { q: 'Ordina dal più liquido al meno liquido', i: ['Saldo del conto corrente', 'Azione del FTSE MIB', 'Small cap su Euronext Growth Milan', 'Appartamento', 'Quota in una startup non quotata'], e: 'Il contante è subito disponibile; poi titoli molto scambiati, titoli piccoli, immobili e infine partecipazioni senza mercato.' },
    { q: 'Ordina cosa accade quando la liquidità sparisce in una crisi', i: ['Arrivano notizie molto negative', 'Molti vogliono vendere insieme', 'I compratori si ritirano', 'Gli spread si allargano', 'I prezzi scendono a scatti'], e: 'La liquidità tende a mancare proprio quando serve di più: per questo conviene non contare sul vendere in fretta nelle crisi.' },
  ],
  cat: [
    { q: 'Segnale di alta o bassa liquidità?', g: [['Alta liquidità', ['Spread stretto', 'Grandi quantità nel book', 'Milioni di euro scambiati ogni giorno']], ['Bassa liquidità', ['Spread ampio', 'Pochi contratti al giorno', 'Prezzo che salta tra un contratto e l’altro']]] },
    { q: 'Facile o difficile da vendere in un giorno?', g: [['In genere facile', ['Azione di una grande banca italiana', 'BTP decennale', 'ETF su un indice globale']], ['In genere difficile', ['Casa in un piccolo paese', 'Opera d’arte', 'Quota di una srl di famiglia']]] },
  ],
  scen: [
    { s: 'Michele, 37 anni, ha trovato una piccola società che “rende tanto”. Sul mercato scambia in media poche migliaia di euro al giorno, e lui vorrebbe investirci 30.000 €.', q: 'Cosa fa?', o: [
      { t: 'Riduce l’importo e usa ordini con limite, senza fretta', ok: true, f: 'Giusto: il suo ordine varrebbe molti giorni di scambi. Entrare costerebbe caro e, soprattutto, uscire potrebbe essere molto difficile.' },
      { t: 'Compra tutto in un colpo con un ordine al meglio', ok: false, f: 'Esaurirebbe le offerte in vendita salendo su prezzi sempre più alti: pagherebbe molto più del prezzo visto.' },
      { t: 'Ignora i volumi: contano solo i rendimenti passati', ok: false, f: 'I rendimenti passati non garantiscono nulla, e un titolo illiquido può essere difficile da vendere proprio quando serve.' },
    ] },
    { s: 'Serena, 41 anni, tra due mesi deve versare l’anticipo per una casa. Ha azioni di grandi società, BTP e una quota di un fondo immobiliare chiuso, rimborsabile solo a scadenza.', q: 'Come si organizza?', o: [
      { t: 'Pianifica per tempo e usa prima gli strumenti più liquidi', ok: true, f: 'Bene: il fondo chiuso si rimborsa a scadenza e, se quotato, si vende spesso a sconto. Per spese vicine servono attività liquide.' },
      { t: 'Vende per primo il fondo chiuso, perché è il più stabile', ok: false, f: 'Stabile sulla carta non vuol dire vendibile: potrebbe non trovare acquirenti o doverlo cedere con un forte sconto.' },
      { t: 'Aspetta l’ultimo giorno: tanto si vende tutto con un clic', ok: false, f: 'Non tutto si vende con un clic, e anche le azioni possono essere scese proprio quel giorno: meglio non ridursi all’ultimo.' },
    ] },
    { s: 'Pietro, 29 anni, legge un messaggio allarmato: “Volumi record e titolo −8%: stanno tutti vendendo, scappate!”.', q: 'Come reagisce?', o: [
      { t: 'Ricorda che ogni azione venduta è stata comprata e cerca i motivi del ribasso', ok: true, f: 'Esatto: il volume alto non dice che “nessuno compra”. Prima di decidere servono i fatti dietro il movimento.' },
      { t: 'Vende subito, perché volumi alti significano che nessuno vuole il titolo', ok: false, f: 'Con volumi alti, al contrario, molti hanno comprato: vendere solo per panico è spesso la scelta peggiore.' },
      { t: 'Compra il doppio, perché il volume alto garantisce un rimbalzo', ok: false, f: 'Il volume non garantisce rimbalzi: dice quanto si è scambiato, non come andrà il prezzo.' },
    ] },
    { s: 'Ivan, 33 anni, scarta un ETF su grandi azioni europee perché scambia poche centinaia di migliaia di euro al giorno: “Non riuscirò mai a venderlo”.', q: 'Cosa dovrebbe controllare?', o: [
      { t: 'Lo spread e la liquidità dei titoli che l’ETF contiene', ok: true, f: 'Giusto: le quote di un ETF possono essere create o rimborsate, e il market maker quota prezzi basati sul paniere. Lo spread è il vero indicatore del costo.' },
      { t: 'Nulla: un ETF con pochi scambi è sempre invendibile', ok: false, f: 'Non è così: per un ETF su titoli molto liquidi i volumi in borsa sono solo una parte della liquidità disponibile.' },
      { t: 'Sceglie l’ETF con più volume anche se replica un indice diverso', ok: false, f: 'Così cambia investimento per un dettaglio: prima conta cosa replica l’ETF, poi costi e spread.' },
    ] },
  ],
  tip: 'Prima di comprare guarda volume medio, controvalore e spread: chiediti non solo quanto può salire il titolo, ma anche quanto ti costerà uscire quando vorrai.',
});
