FQC(19, {
  intro: 'FTSE MIB, S&P 500, MSCI World: scopri cosa misurano gli indici di borsa, come si calcolano e perché le grandi società pesano di più.',
  cards: [
    { t: 'Un paniere che racconta un mercato', x: 'Un indice è un paniere di titoli che sintetizza un mercato. Il FTSE MIB raccoglie 40 grandi società di Borsa Italiana, l’S&P 500 circa 500 grandi società USA, l’MSCI World oltre mille aziende di 23 Paesi sviluppati.', v: { k: 'icons', d: [['🇮🇹', 'FTSE MIB: 40 titoli'], ['🇺🇸', 'S&P 500: circa 500 titoli'], ['🌍', 'MSCI World: Paesi sviluppati'], ['🇪🇺', 'Euro Stoxx 50: area euro']] } },
    { t: 'Il peso di ogni titolo', x: 'Nella ponderazione per capitalizzazione ogni titolo pesa in proporzione al suo valore di borsa, di solito considerando solo il flottante. Le società più grandi muovono l’indice più delle piccole.', v: { k: 'formula', f: 'Peso = capitalizzazione del titolo / capitalizzazione totale dell’indice', n: 'Es.: 30 miliardi su 600 miliardi = 5%' } },
    { t: 'Pochi titoli, molto peso', x: 'In un indice ponderato per capitalizzazione pochi grandi titoli possono contare moltissimo. In questo esempio A e B insieme fanno l’80%: un +1% di A pesa dieci volte un +1% di D.', v: { k: 'pie', d: [['Società A', 50], ['Società B', 30], ['Società C', 15], ['Società D', 5]] } },
    { t: 'Con o senza dividendi', x: 'L’indice di prezzo ignora i dividendi; la versione total return li considera reinvestiti. Sul lungo periodo la differenza è grande: il FTSE MIB più citato è un indice di prezzo, il DAX tedesco è total return.', v: { k: 'vs', a: ['Indice di prezzo', 'Solo le variazioni dei prezzi'], b: ['Total return', 'Prezzi più dividendi reinvestiti'] } },
    { t: 'Quando conta il prezzo', x: 'Non tutti gli indici pesano la capitalizzazione: il Dow Jones (30 titoli) e il Nikkei 225 sono ponderati per prezzo, quindi un’azione dal prezzo unitario alto pesa di più anche se la società è più piccola.', v: { k: 'stat', n: '30', l: 'titoli del Dow Jones, indice ponderato per prezzo' } },
    { t: 'Come si muove l’indice', x: 'La variazione di un indice è la media dei rendimenti dei titoli, pesata per il loro peso. Con A al 60% (+2%) e B al 40% (−1%): 0,6 × 2% + 0,4 × (−1%) = +0,8%.', v: { k: 'bars', d: [['A (peso 60%)', 2], ['B (peso 40%)', -1], ['Indice', 0.8]], u: '%' } },
  ],
  terms: [
    ['Indice di borsa', 'Paniere di titoli il cui valore sintetizza l’andamento di un mercato o di un suo segmento.'],
    ['Ponderazione per capitalizzazione', 'Metodo in cui ogni titolo pesa in proporzione al suo valore di mercato.'],
    ['Ponderazione per prezzo', 'Metodo in cui pesano di più le azioni dal prezzo unitario più alto, come nel Dow Jones.'],
    ['Equiponderato', 'Detto di un indice in cui ogni titolo ha lo stesso peso, a prescindere dalle dimensioni.'],
    ['Indice total return', 'Indice che oltre ai prezzi include i dividendi, considerati reinvestiti.'],
    ['Benchmark', 'Indice di riferimento con cui si confrontano i risultati di un fondo o di un portafoglio.'],
    ['FTSE MIB', 'Principale indice di Borsa Italiana: 40 società tra le più grandi e scambiate.'],
    ['MSCI World', 'Indice di grandi e medie società di 23 Paesi sviluppati, senza i mercati emergenti.'],
  ],
  tf: [
    ['Il FTSE MIB è composto da 40 tra le principali società quotate su Borsa Italiana.', true, 'Raccoglie 40 titoli tra i più capitalizzati e scambiati del listino italiano, pesati per capitalizzazione del flottante.'],
    ['L’MSCI World comprende tutti i Paesi del mondo, anche Cina e India.', false, 'Include solo Paesi sviluppati: gli emergenti come Cina e India sono in altri indici, come l’MSCI Emerging Markets o l’MSCI ACWI.'],
    ['In un indice ponderato per capitalizzazione, un +5% di una grande società muove l’indice più di un +5% di una piccola.', true, 'Il contributo di ogni titolo è peso × rendimento: a parità di rendimento conta di più chi pesa di più.'],
    ['Un indice a 30.000 punti è “più caro” di uno a 5.000 punti.', false, 'I punti dipendono dal valore di partenza e dal metodo di calcolo: per confrontare indici contano le variazioni percentuali.'],
    ['Si può comprare direttamente un indice in borsa, come se fosse un’azione.', false, 'Un indice è un calcolo, non un titolo: per replicarlo si usano fondi o ETF che ne acquistano i componenti.'],
    ['Un indice di prezzo non tiene conto dei dividendi distribuiti.', true, 'Quando un titolo stacca il dividendo il suo prezzo scende, e l’indice di prezzo registra solo quel calo.'],
    ['Il Dow Jones è ponderato per prezzo: un’azione dal prezzo unitario alto pesa di più.', true, 'Conta il prezzo della singola azione, non il valore della società: è un metodo storico, oggi poco usato.'],
    ['La composizione di un indice resta fissa per sempre.', false, 'Gli indici vengono rivisti periodicamente: entrano società cresciute ed escono quelle scese o poco scambiate.'],
    ['Un indice ponderato per capitalizzazione può diventare molto concentrato su pochi titoli o settori.', true, 'Se poche società crescono molto, il loro peso aumenta e l’indice dipende sempre più da loro.'],
    ['Se il FTSE MIB sale dell’1% in una seduta, tutti i 40 titoli che lo compongono sono saliti.', false, 'L’indice è una media ponderata: può salire anche se molti titoli scendono, purché salgano quelli che pesano di più.'],
  ],
  mcq: [
    { q: 'Quale indice segue circa 500 grandi società statunitensi?', a: 'S&P 500', w: ['Dow Jones', 'Nasdaq Composite', 'Euro Stoxx 50'], e: 'L’S&P 500 copre circa 500 grandi società USA. Il Dow Jones ne conta 30, il Nasdaq Composite migliaia; l’Euro Stoxx 50 è europeo.' },
    { q: 'Una società vale 45 miliardi in borsa e l’intero indice 900 miliardi. Qual è il suo peso?', a: '5%', w: ['4,5%', '20%', '0,5%'], e: '45 / 900 = 0,05, cioè il 5% dell’indice.' },
    { q: 'Titolo A pesa il 70% e sale del 3%; titolo B pesa il 30% e scende del 2%. Come va l’indice?', a: '+1,5%', w: ['+0,5%', '+1%', '+2,1%'], e: '0,7 × 3% + 0,3 × (−2%) = 2,1% − 0,6% = +1,5%. Il +0,5% è la media semplice, che ignora i pesi.' },
    { q: 'Che cosa manca nell’MSCI World?', a: 'I mercati emergenti, come Cina e India', w: ['Le società degli Stati Uniti d’America', 'Le grandi società dei Paesi europei', 'Le grandi aziende tecnologiche'], e: 'Nonostante il nome, l’MSCI World copre solo i Paesi sviluppati; per avere anche gli emergenti esistono indici come l’MSCI ACWI.' },
    { q: 'Perché nel lungo periodo un indice total return supera la versione di prezzo?', a: 'Perché include i dividendi reinvestiti', w: ['Perché contiene un numero maggiore di titoli', 'Perché è calcolato sempre in dollari', 'Perché esclude i titoli in perdita'], e: 'I titoli e i loro pesi sono gli stessi: cambia solo che i dividendi vengono conteggiati e reinvestiti.' },
    { q: 'In quale tipo di indice ogni titolo pesa allo stesso modo?', a: 'Equiponderato', w: ['Ponderato per capitalizzazione', 'Ponderato per prezzo', 'Total return'], e: 'Nell’indice equiponderato ogni titolo ha lo stesso peso: le piccole società contano quanto le grandi.' },
    { q: 'A che cosa serve un benchmark?', a: 'A confrontare i risultati di un fondo', w: ['A garantire un rendimento minimo', 'A calcolare le tasse dovute sul fondo', 'A decidere quali azioni vietare'], e: 'Il benchmark è il termine di paragone: dice se il gestore ha fatto meglio o peggio del mercato di riferimento.' },
    { q: 'Quale di questi indici è ponderato per prezzo?', a: 'Il Nikkei 225', w: ['Il FTSE MIB', 'L’S&P 500', 'L’MSCI World'], e: 'Il Nikkei 225 di Tokyo, come il Dow Jones, pesa i titoli in base al prezzo. Gli altri sono ponderati per capitalizzazione.' },
  ],
  fill: [
    { s: 'Il FTSE MIB comprende ___ società di Borsa Italiana.', a: '40', w: ['30', '50', '100'] },
    { s: 'Nella ponderazione per ___ pesano di più le società con il valore di borsa più alto.', a: 'capitalizzazione', w: ['prezzo', 'dividendo', 'anzianità'] },
    { s: 'Un indice ___ include anche i dividendi reinvestiti.', a: 'total return', w: ['di prezzo', 'equiponderato', 'settoriale'] },
    { s: 'L’indice con cui si confrontano i risultati di un fondo si chiama ___.', a: 'benchmark', w: ['rating', 'spread', 'prospetto'] },
    { s: 'L’MSCI World comprende solo i Paesi ___.', a: 'sviluppati', w: ['emergenti', 'europei', 'asiatici'] },
  ],
  order: [
    { q: 'Ordina dal minor al maggior numero di titoli', i: ['Dow Jones', 'FTSE MIB', 'Euro Stoxx 50', 'S&P 500', 'MSCI World'], e: '30, 40, 50, circa 500 e oltre mille titoli: più titoli non significa per forza più diversificazione se pochi pesano molto.' },
    { q: 'Ordina i passaggi per calcolare la variazione di un indice ponderato per capitalizzazione', i: ['Calcoli la capitalizzazione di ogni titolo', 'Ricavi il peso di ciascuno sul totale', 'Moltiplichi ogni peso per il rendimento del titolo', 'Sommi i risultati'], e: 'La variazione dell’indice è la somma dei contributi: peso × rendimento di ciascun titolo.' },
  ],
  cat: [
    { q: 'Indice europeo o statunitense?', g: [['Europa', ['FTSE MIB', 'DAX', 'CAC 40', 'Euro Stoxx 50']], ['Stati Uniti', ['S&P 500', 'Dow Jones', 'Nasdaq-100', 'Russell 2000']]] },
    { q: 'Caratteristica di un indice ponderato per capitalizzazione o equiponderato?', g: [['Per capitalizzazione', ['Le grandi società pesano di più', 'Può concentrarsi su pochi titoli', 'Il peso cresce se il titolo sale più degli altri']], ['Equiponderato', ['Ogni titolo ha lo stesso peso', 'Le piccole società contano come le grandi', 'Serve riportare spesso i pesi in pari']]] },
  ],
  scen: [
    { s: 'Alessia, 30 anni, sente al telegiornale che “Piazza Affari chiude in rialzo dell’1%”. Apre l’app e scopre che la sua azione, presente nel FTSE MIB, è scesa del 2%.', q: 'Come lo interpreta?', o: [
      { t: 'L’indice è una media: alcuni titoli possono scendere', ok: true, f: 'Esatto: se salgono i titoli che pesano di più, l’indice sale anche con molti titoli in calo, compreso il suo.' },
      { t: 'Pensa che il suo broker abbia sbagliato i prezzi', ok: false, f: 'Non c’è errore: il dato dell’indice è una media, i singoli titoli possono muoversi in direzioni diverse.' },
      { t: 'Vende subito, perché il titolo “non segue l’indice”', ok: false, f: 'Un giorno diverso dall’indice è normalissimo: non è un motivo sufficiente per vendere.' },
    ] },
    { s: 'Fabio, 35 anni, vuole investire “in tutto il mondo” e sceglie un ETF sull’MSCI World, convinto di avere dentro anche Cina, India e Brasile.', q: 'Cosa dovrebbe sapere?', o: [
      { t: 'L’MSCI World copre solo i Paesi sviluppati e pesa molto sugli USA', ok: true, f: 'Giusto: se vuole anche gli emergenti deve guardare a indici come l’MSCI ACWI o aggiungere una parte di mercati emergenti.' },
      { t: 'L’MSCI World dà lo stesso peso a ogni Paese del mondo', ok: false, f: 'È ponderato per capitalizzazione: i Paesi con le borse più grandi, Stati Uniti in testa, pesano molto di più.' },
      { t: 'Il nome “World” garantisce la massima diversificazione possibile', ok: false, f: 'Il nome non basta: bisogna leggere la composizione dell’indice, che esclude tutti i mercati emergenti.' },
    ] },
    { s: 'Marta, 46 anni, ha un fondo azionario Italia che in un anno ha reso il 6%, dividendi inclusi. Nello stesso anno il FTSE MIB, indice di prezzo, è salito dell’8%.', q: 'Come valuta il fondo?', o: [
      { t: 'Lo confronta con il FTSE MIB total return: il divario è ancora più ampio', ok: true, f: 'Corretto: aggiungendo i dividendi l’indice avrebbe reso più dell’8%, quindi il fondo è rimasto indietro ancora di più.' },
      { t: 'Il fondo è andato bene, perché ha incassato anche i dividendi', ok: false, f: 'Il confronto va fatto alla pari: anche l’indice va considerato con i dividendi, e allora il ritardo cresce.' },
      { t: 'Fondi e indici non si possono mai confrontare', ok: false, f: 'Si possono e si devono confrontare: è proprio la funzione del benchmark, purché si usi la versione corretta.' },
    ] },
    { s: 'Nicola, 40 anni, investe in un ETF su un grande indice azionario e scopre che i primi dieci titoli pesano una quota molto ampia del totale.', q: 'Cosa ne conclude?', o: [
      { t: 'Valuta se quella concentrazione è adatta a lui', ok: true, f: 'Bene: è normale in un indice pesato per capitalizzazione, ma va capito. Può affiancare altri strumenti se vuole ridurre la concentrazione.' },
      { t: 'L’indice è calcolato male e l’ETF va segnalato alla CONSOB', ok: false, f: 'Nessun errore: è il risultato del metodo di calcolo, descritto nelle regole pubbliche dell’indice.' },
      { t: 'Alta concentrazione nei giganti significa rischio quasi nullo', ok: false, f: 'Anche le grandi società possono calare molto: la concentrazione rende l’indice più dipendente da pochi nomi.' },
    ] },
  ],
  tip: 'Quando confronti un investimento con un indice, controlla quale versione usi (prezzo o total return) e cosa c’è davvero dentro: nome e contenuto non sempre coincidono.',
});
