FQC(20, {
  intro: 'Chi controlla i mercati e cosa ti protegge davvero? CONSOB, Banca d’Italia, ESMA e MiFID II: conosci regole, tutele e i loro limiti.',
  cards: [
    { t: 'Chi vigila su chi', x: 'In Italia la CONSOB vigila su mercati, trasparenza e correttezza verso i clienti; la Banca d’Italia sulla solidità di banche e intermediari. In Europa l’ESMA coordina le autorità nazionali e la BCE vigila sulle banche più grandi.', v: { k: 'icons', d: [['🛡️', 'CONSOB: trasparenza e correttezza'], ['🏦', 'Banca d’Italia: solidità'], ['🇪🇺', 'ESMA: regole comuni UE'], ['💶', 'BCE: grandi banche']] } },
    { t: 'Le tutele della MiFID II', x: 'Con la MiFID II l’intermediario ti classifica, raccoglie conoscenze, esperienza, obiettivi e situazione finanziaria, verifica se un prodotto è adatto a te e ti informa prima e dopo su tutti i costi.', v: { k: 'steps', s: ['Classificazione del cliente', 'Questionario MiFID', 'Verifica di adeguatezza', 'Informativa su costi e rischi'] } },
    { t: 'I tuoi titoli restano tuoi', x: 'Per legge i titoli dei clienti sono separati dal patrimonio dell’intermediario: se questo fallisce, i suoi creditori non possono prenderli e vanno restituiti ai legittimi proprietari.', v: { k: 'vs', a: ['Patrimonio del broker', 'Serve a pagare i suoi creditori'], b: ['Titoli dei clienti', 'Patrimonio separato, da restituire'] } },
    { t: 'Due sistemi di garanzia', x: 'I depositi bancari sono garantiti fino a 100.000 € per depositante e per banca. Il Fondo Nazionale di Garanzia copre fino a 20.000 € i crediti verso un intermediario insolvente. Nessuno dei due copre le perdite di mercato.', v: { k: 'bars', d: [['Depositi bancari', 100000], ['Servizi di investimento', 20000]], u: '€' } },
    { t: 'Pause e sospensioni', x: 'Se un titolo si muove oltre certi limiti, la negoziazione continua si ferma e parte un’asta di volatilità di pochi minuti. Borsa Italiana o la CONSOB possono anche sospendere un titolo, ad esempio in attesa di notizie importanti.', v: { k: 'vs', a: ['Asta di volatilità', 'Pausa automatica di pochi minuti'], b: ['Sospensione', 'Stop deciso da Borsa o CONSOB'] } },
    { t: 'Se nasce una controversia', x: 'Per una lite con banca o broker sui servizi di investimento, dopo un reclamo all’intermediario puoi rivolgerti gratis all’Arbitro per le Controversie Finanziarie (ACF) della CONSOB, per richieste fino a 500.000 €.', v: { k: 'stat', n: '500.000 €', l: 'importo massimo delle richieste all’ACF' } },
  ],
  terms: [
    ['CONSOB', 'Autorità italiana che vigila su trasparenza e correttezza dei mercati e degli intermediari.'],
    ['Banca d’Italia', 'Banca centrale nazionale: vigila sulla stabilità e sulla solidità di banche e intermediari.'],
    ['ESMA', 'Autorità europea dei mercati finanziari: coordina i vigilanti nazionali e armonizza le regole.'],
    ['MiFID II', 'Direttiva europea sui servizi di investimento che rafforza tutela, trasparenza e adeguatezza.'],
    ['Valutazione di adeguatezza', 'Verifica che un investimento consigliato sia coerente con profilo, obiettivi e situazione del cliente.'],
    ['Abuso di informazioni privilegiate', 'Operare sfruttando notizie riservate capaci di influenzare il prezzo di un titolo.'],
    ['Fondo Nazionale di Garanzia', 'Sistema che indennizza fino a 20.000 € gli investitori se l’intermediario è insolvente.'],
    ['Separazione patrimoniale', 'Regola per cui i titoli dei clienti restano distinti dai beni dell’intermediario.'],
  ],
  tf: [
    ['La CONSOB garantisce che gli investimenti quotati in borsa non perdano valore.', false, 'La CONSOB vigila su trasparenza e correttezza, non sui risultati: il rischio di mercato resta sempre a carico di chi investe.'],
    ['Se il tuo broker fallisce, i titoli nel dossier restano tuoi perché sono separati dal suo patrimonio.', true, 'È la separazione patrimoniale: i titoli dei clienti non servono a pagare i debiti dell’intermediario.'],
    ['La garanzia dei depositi fino a 100.000 € copre anche le perdite su azioni e obbligazioni.', false, 'Tutela solo i depositi, come conti correnti e conti deposito, se la banca va in crisi; non le perdite sugli investimenti.'],
    ['Con la MiFID II l’intermediario deve informarti su costi e oneri, anche con un resoconto annuale.', true, 'Devi conoscere i costi prima di investire e riceverne il riepilogo effettivo dopo, almeno una volta l’anno.'],
    ['Comprare azioni sfruttando una notizia riservata, prima che sia pubblica, è un illecito.', true, 'È abuso di informazioni privilegiate: la normativa europea sugli abusi di mercato lo punisce, anche penalmente.'],
    ['Un’asta di volatilità significa che il titolo è stato escluso definitivamente dalla borsa.', false, 'È una pausa automatica di pochi minuti quando il prezzo si muove troppo: poi la negoziazione continua riprende.'],
    ['L’ESMA può limitare a livello europeo la vendita ai piccoli investitori di prodotti molto rischiosi.', true, 'Ha poteri di intervento sui prodotti: ad esempio ha limitato la leva sui CFD e vietato le opzioni binarie ai clienti al dettaglio.'],
    ['Un operatore assente dagli elenchi degli intermediari autorizzati può offrire servizi di investimento in Italia.', false, 'Senza autorizzazione è abusivo: la CONSOB pubblica avvisi e può ordinare l’oscuramento dei siti che operano senza permesso.'],
    ['Il questionario MiFID serve all’intermediario per capire quali prodotti sono adatti a te.', true, 'Conoscenze, esperienza, obiettivi e situazione finanziaria servono a valutare se un investimento è coerente con il tuo profilo.'],
    ['Esagerare la propria esperienza nel questionario MiFID per comprare prodotti più rischiosi non ha conseguenze.', false, 'Le valutazioni si basano sulle tue risposte: dati non veri riducono la tua tutela e possono indebolire eventuali reclami.'],
  ],
  mcq: [
    { q: 'Quale autorità vigila sulla trasparenza e sulla correttezza dei mercati in Italia?', a: 'La CONSOB', w: ['L’IVASS', 'La COVIP', 'L’Agenzia delle Entrate'], e: 'La CONSOB vigila su mercati e intermediari. L’IVASS si occupa di assicurazioni, la COVIP di fondi pensione.' },
    { q: 'Fino a quanto indennizza il Fondo Nazionale di Garanzia per ciascun investitore?', a: '20.000 €', w: ['100.000 €', '500.000 €', 'Senza limiti'], e: 'Il Fondo copre fino a 20.000 € i crediti verso intermediari insolventi. I 100.000 € riguardano invece i depositi bancari.' },
    { q: 'Che cosa protegge la garanzia dei depositi fino a 100.000 €?', a: 'Il denaro sui conti di una banca in crisi', w: ['Le perdite su azioni in calo in borsa', 'Il valore dei BTP nel dossier titoli', 'Le perdite sugli ETF azionari in portafoglio'], e: 'Riguarda conti correnti e conti deposito, per depositante e per banca. Il valore dei titoli resta soggetto al mercato.' },
    { q: 'Che cosa fa l’ESMA?', a: 'Armonizza le regole e la vigilanza nell’UE', w: ['Fissa i tassi di interesse dell’area euro', 'Gestisce le aste dei titoli di Stato', 'Calcola gli indici delle borse europee'], e: 'L’ESMA lavora per regole e vigilanza uniformi nell’UE. I tassi li decide la BCE, le aste dei titoli di Stato le organizza ciascuno Stato.' },
    { q: 'Una banca ti raccomanda un prodotto con il servizio di consulenza. Cosa le impone la MiFID II?', a: 'Verificare che sia adeguato al tuo profilo', w: ['Garantirti un rendimento minimo annuo', 'Restituirti le perdite entro un anno', 'Proporti soltanto titoli di Stato'], e: 'Nella consulenza l’intermediario deve valutare l’adeguatezza del prodotto rispetto a te. Nessuna regola garantisce rendimenti.' },
    { q: 'Durante la seduta un titolo supera i limiti di variazione del prezzo. Cosa accade di solito?', a: 'Parte un’asta di volatilità di pochi minuti', w: ['Il titolo viene escluso dalla borsa', 'Gli scambi del giorno vengono annullati', 'Il prezzo torna a quello di apertura'], e: 'La pausa serve a raccogliere ordini e far emergere un prezzo più ordinato. Poi riprende la negoziazione continua.' },
    { q: 'Hai una controversia con il broker su un servizio di investimento. A chi ti rivolgi dopo il reclamo, senza costi?', a: 'All’Arbitro per le Controversie Finanziarie', w: ['Alla Banca Centrale Europea di Francoforte', 'Al Ministero dell’Economia e delle Finanze', 'Alla borsa dove è quotato il titolo'], e: 'L’ACF, istituito presso la CONSOB, decide gratuitamente per l’investitore le liti sui servizi di investimento fino a 500.000 €.' },
    { q: 'Quale di questi comportamenti è un abuso di mercato?', a: 'Diffondere notizie false per far salire un titolo', w: ['Comprare un titolo dopo aver letto il bilancio', 'Vendere un titolo per incassare un guadagno', 'Usare un ordine con limite di prezzo'], e: 'Diffondere informazioni false o fuorvianti per muovere i prezzi è manipolazione del mercato, vietata e sanzionata.' },
  ],
  fill: [
    { s: 'In Italia la ___ vigila sulla trasparenza e sulla correttezza dei mercati.', a: 'CONSOB', w: ['COVIP', 'IVASS', 'SIAE'] },
    { s: 'La direttiva europea che regola i servizi di investimento si chiama ___.', a: 'MiFID II', w: ['PSD2', 'GDPR', 'Basilea III'] },
    { s: 'I titoli dei clienti sono un patrimonio ___ da quello dell’intermediario.', a: 'separato', w: ['unito', 'garantito', 'vincolato'] },
    { s: 'Se il prezzo si muove troppo, la negoziazione continua si ferma per un’asta di ___.', a: 'volatilità', w: ['chiusura', 'apertura', 'liquidazione'] },
    { s: 'Operare sfruttando una notizia riservata è abuso di informazioni ___.', a: 'privilegiate', w: ['pubbliche', 'contabili', 'storiche'] },
  ],
  order: [
    { q: 'Ordina i passaggi per verificare un’offerta di investimento sospetta', i: ['Ricevi la proposta', 'Cerchi la società negli elenchi ufficiali', 'Controlli gli avvisi CONSOB sugli abusivi', 'Se non è autorizzata, non investi e segnali'], e: 'Prima di valutare il prodotto verifica chi lo offre: senza autorizzazione non ci sono tutele.' },
    { q: 'Ordina il percorso di un reclamo per un servizio di investimento', i: ['Raccogli contratti e documenti', 'Invii un reclamo scritto all’intermediario', 'Attendi la risposta nei tempi previsti', 'Se insoddisfatto ricorri all’ACF'], e: 'Il reclamo all’intermediario viene prima: solo dopo, se la risposta non arriva o non ti soddisfa, puoi ricorrere all’ACF.' },
  ],
  cat: [
    { q: 'Compito tipico della CONSOB o della Banca d’Italia?', g: [['CONSOB', ['Approvare i prospetti delle offerte al pubblico', 'Vigilare sulla correttezza verso i clienti', 'Contrastare gli abusi di mercato']], ['Banca d’Italia', ['Controllare la solidità patrimoniale delle banche', 'Contenere i rischi degli intermediari', 'Tutelare la stabilità del sistema finanziario']]] },
    { q: 'Coperto da un sistema di garanzia o no?', g: [['Coperto', ['Saldo del conto corrente fino a 100.000 €', 'Conto deposito fino a 100.000 €', 'Titoli non restituiti da un broker insolvente, fino a 20.000 €']], ['Non coperto', ['Perdita per il calo di un’azione', 'Ribasso di un ETF azionario', 'Calo del prezzo di un BTP prima della scadenza']]] },
  ],
  scen: [
    { s: 'Riccardo, 39 anni, riceve su WhatsApp la proposta di una società estera: “Trading automatico con rendimento garantito del 10% al mese”. Il sito mostra il logo della CONSOB.', q: 'Cosa fa?', o: [
      { t: 'Controlla gli elenchi ufficiali e nel dubbio non investe', ok: true, f: 'Giusto: un rendimento “garantito” del 10% al mese è un segnale tipico di truffa, e un logo si copia in un attimo. Contano solo gli elenchi ufficiali.' },
      { t: 'Investe una piccola somma per vedere se funziona davvero', ok: false, f: 'Spesso i primi “guadagni” servono solo a convincerti a versare di più: anche poco denaro può andare perso del tutto.' },
      { t: 'Si fida perché il sito mostra il logo della CONSOB', ok: false, f: 'Il logo di un’autorità non prova nulla: gli abusivi lo usano proprio per sembrare affidabili.' },
    ] },
    { s: 'Paola, 62 anni, compila il questionario MiFID in banca. Il funzionario le suggerisce di indicare “esperienza elevata” così da poter accedere a un prodotto complesso che le vuole proporre.', q: 'Cosa fa?', o: [
      { t: 'Risponde in modo veritiero, anche se il prodotto risulterà non adatto', ok: true, f: 'Corretto: il questionario serve a proteggerla. Risposte non veritiere la espongono a prodotti che non capisce e indeboliscono le sue tutele.' },
      { t: 'Segue il suggerimento: è solo una formalità burocratica', ok: false, f: 'Non è una formalità: da quelle risposte dipende cosa le possono proporre. E chi firma il questionario è lei.' },
      { t: 'Firma senza leggere: tanto la CONSOB la tutela da ogni perdita', ok: false, f: 'Nessuna autorità tutela dalle perdite di mercato: le regole proteggono la correttezza, non il risultato.' },
    ] },
    { s: 'Emanuele, 45 anni, ha 180.000 € fermi su un unico conto corrente presso la stessa banca. Legge notizie preoccupanti sulla sua solidità.', q: 'Cosa considera?', o: [
      { t: 'Valuta di ripartire la liquidità tra più banche', ok: true, f: 'Bene: oltre i 100.000 € per depositante e per banca il denaro non è garantito. I titoli in dossier invece restano separati dal patrimonio della banca.' },
      { t: 'È tutto coperto, perché le banche non possono fallire', ok: false, f: 'Le banche possono andare in crisi: proprio per questo esiste la garanzia, che però ha un limite di 100.000 €.' },
      { t: 'Ritira tutto in contanti e lo tiene in casa', ok: false, f: 'Il contante in casa rischia furti, non rende nulla e l’inflazione lo erode: esistono soluzioni più sicure.' },
    ] },
    { s: 'Sofia, 28 anni, vede il suo titolo salire del 12% in pochi minuti dopo una notizia. Poi le contrattazioni si bloccano e l’app segnala “asta di volatilità”.', q: 'Cosa fa?', o: [
      { t: 'Attende la ripresa degli scambi e intanto legge la notizia', ok: true, f: 'Esatto: è una pausa di pochi minuti per far emergere un prezzo ordinato. È il momento giusto per informarsi, non per agire d’istinto.' },
      { t: 'Chiama il broker per farsi restituire i soldi investiti', ok: false, f: 'L’asta non annulla gli scambi né rimborsa nessuno: è un meccanismo normale per gestire movimenti bruschi.' },
      { t: 'Inserisce subito un grosso ordine al meglio per non perdere il rialzo', ok: false, f: 'Un ordine al meglio in asta partecipa al prezzo che uscirà, qualunque sia: rischia di pagare molto più del previsto.' },
    ] },
  ],
  tip: 'Prima di investire verifica sempre che chi ti propone un prodotto sia autorizzato: bastano pochi minuti sugli elenchi di CONSOB e Banca d’Italia.',
});
