FQC(21, {
  intro: 'Comprare un’azione significa diventare socio di un’azienda: scopri cosa possiedi davvero, che rischi corri e da dove arrivano i guadagni.',
  cards: [
    { t: 'Un pezzo di azienda', x: 'Il capitale di una società per azioni è diviso in parti uguali chiamate azioni. Se l’azienda ha 1 milione di azioni e tu ne possiedi 1.000, sei proprietario dello 0,1% della società.', v: { k: 'formula', f: 'Quota = azioni possedute ÷ azioni totali', n: 'Es.: 1.000 ÷ 1.000.000 = 0,1%' } },
    { t: 'Socio, non creditore', x: 'Con un’azione partecipi a utili e perdite dell’azienda. Con un’obbligazione, invece, le presti denaro e ricevi interessi e rimborso a scadenza. L’azionista rischia di più, ma il suo guadagno potenziale non ha un tetto.', v: { k: 'vs', a: ['Azione', 'Quota di proprietà, nessuna scadenza'], b: ['Obbligazione', 'Prestito con interessi e scadenza'] } },
    { t: 'Due fonti di guadagno', x: 'Un’azione può rendere in due modi: il dividendo, cioè la parte di utili distribuita ai soci, e il capital gain, la differenza tra prezzo di vendita e prezzo di acquisto. Nessuno dei due è garantito.', v: { k: 'icons', d: [['💶', 'Dividendi'], ['📈', 'Aumento del prezzo']] } },
    { t: 'Responsabilità limitata', x: 'Se l’azienda fallisce, l’azionista può perdere tutto il capitale investito, ma non di più: non risponde con il proprio patrimonio personale dei debiti della società.', v: { k: 'stat', n: '100%', l: 'perdita massima: il capitale investito, non oltre' } },
    { t: 'Ultimi in fila', x: 'Se una società viene liquidata, il patrimonio rimasto serve prima a pagare i creditori: dipendenti, fisco, banche, obbligazionisti. Agli azionisti va solo ciò che avanza, spesso nulla.', v: { k: 'steps', s: ['Creditori privilegiati', 'Creditori chirografari', 'Creditori subordinati', 'Azionisti'] } },
    { t: 'Più rischio, più potenziale', x: 'La singola azione è tra gli strumenti più volatili per un risparmiatore: in un anno può salire o scendere molto. Per questo ha senso con un orizzonte lungo e un portafoglio diversificato.', v: { k: 'scale', a: 'Rischio basso', b: 'Rischio alto', d: [['Conto deposito', 5], ['Titolo di Stato', 25], ['Obbligazione societaria', 40], ['Singola azione', 85]] } },
  ],
  terms: [
    ['Azione', 'Quota unitaria del capitale di una società per azioni che rende socio chi la possiede.'],
    ['Azionista', 'Chi possiede almeno un titolo di una Spa e ne è quindi socio, con diritti e rischi.'],
    ['Capitale sociale', 'Valore dei conferimenti dei soci indicato nello statuto, suddiviso in quote uguali.'],
    ['Dividendo', 'Parte dell’utile che la società decide di distribuire ai soci.'],
    ['Capital gain', 'Guadagno dato dalla differenza positiva tra prezzo di vendita e prezzo di acquisto.'],
    ['Responsabilità limitata', 'Principio per cui il socio rischia solo quanto ha investito, non il patrimonio personale.'],
    ['Dematerializzazione', 'Sistema per cui i titoli non sono certificati di carta ma registrazioni elettroniche.'],
    ['Società quotata', 'Società le cui azioni sono scambiate in Borsa, dove chiunque può comprarle e venderle.'],
  ],
  tf: [
    ['Chi possiede un’azione è comproprietario della società, anche se per una quota piccolissima.', true, 'L’azione è una frazione del capitale: rende socio, con diritti agli utili e alle decisioni in proporzione alle azioni possedute.'],
    ['Comprando un’azione presti denaro all’azienda, che dovrà restituirtelo a una scadenza.', false, 'Questo descrive un’obbligazione. L’azione non ha scadenza né rimborso: per rientrare del capitale devi venderla a un altro investitore.'],
    ['Comprando azioni con i tuoi soldi puoi perdere più del capitale che hai investito.', false, 'Grazie alla responsabilità limitata la perdita massima è il capitale investito. Si può perdere di più solo usando prestiti o leva.'],
    ['Il dividendo è un pagamento obbligatorio che ogni società deve versare ogni anno.', false, 'Il dividendo dipende dagli utili e da una decisione dell’assemblea: può essere ridotto, sospeso o non esserci affatto.'],
    ['Se un’azienda fallisce, gli azionisti vengono rimborsati prima degli obbligazionisti.', false, 'È il contrario: gli azionisti sono gli ultimi. Prima si pagano tutti i creditori, obbligazionisti compresi; ai soci resta solo l’eventuale avanzo.'],
    ['Se un’azienda chiude l’anno in utile, il prezzo della sua azione sale di sicuro.', false, 'Il prezzo dipende dalle aspettative: se gli utili sono inferiori a quanto il mercato si attendeva, il titolo può scendere anche con l’azienda in utile.'],
    ['Oggi le azioni quotate in Italia sono registrazioni elettroniche, non certificati di carta.', true, 'Sono dematerializzate: esistono come scritture contabili presso il depositario centrale e la tua banca le riporta nel dossier titoli.'],
    ['Il capital gain è la differenza positiva tra prezzo di vendita e prezzo di acquisto.', true, 'Se compri a 20 € e vendi a 26 €, il capital gain è di 6 € per azione, prima di costi e tasse.'],
    ['Il prezzo di un’azione riflette soprattutto le aspettative sugli utili futuri dell’azienda.', true, 'Chi compra oggi paga per i risultati di domani: per questo un titolo può muoversi molto su notizie che cambiano le previsioni.'],
    ['Con 100 azioni di una società che ne ha emesse 10.000 possiedi l’1% del capitale.', true, '100 ÷ 10.000 = 0,01, cioè l’1%. La stessa proporzione vale per la tua quota degli utili distribuiti.'],
  ],
  mcq: [
    { q: 'Cosa diventi quando compri un’azione di Alfa Spa?', a: 'Socio della società', w: ['Creditore della società', 'Dipendente della società', 'Garante dei suoi debiti'], e: 'L’azione è una quota di proprietà: ti rende socio, con diritto a partecipare agli utili e alle decisioni in proporzione alla quota.' },
    { q: 'Alfa Spa ha 2.000.000 di azioni e tu ne possiedi 10.000. Quale quota della società hai?', a: '0,5%', w: ['5%', '0,05%', '2%'], e: '10.000 ÷ 2.000.000 = 0,005, cioè lo 0,5% del capitale.' },
    { q: 'Qual è la perdita massima se compri azioni senza usare prestiti o leva?', a: 'Il capitale investito', w: ['Il doppio del capitale investito', 'Una quota dei debiti aziendali', 'Nessuna, il capitale è protetto'], e: 'La responsabilità limitata protegge il patrimonio personale: puoi perdere tutto ciò che hai investito, ma non di più.' },
    { q: 'In caso di fallimento della società, chi viene pagato per ultimo?', a: 'Gli azionisti', w: ['Gli obbligazionisti', 'I dipendenti', 'Le banche creditrici'], e: 'Gli azionisti hanno un diritto residuale: ricevono qualcosa solo dopo che tutti i creditori sono stati soddisfatti.' },
    { q: 'Compri un’azione a 40 €, incassi 2 € di dividendo e la rivendi a 46 €. Qual è il capital gain?', a: '6 €', w: ['8 €', '2 €', '46 €'], e: 'Il capital gain è solo la differenza di prezzo: 46 − 40 = 6 €. I 2 € di dividendo sono un guadagno distinto.' },
    { q: 'Perché il titolo di Beta Spa può scendere anche se l’azienda ha chiuso l’anno in utile?', a: 'Gli utili sono stati sotto le attese', w: ['Le società in utile non pagano dividendi', 'La Borsa non guarda mai i risultati', 'Il prezzo è fissato dalla CONSOB'], e: 'Il prezzo incorpora le aspettative: se il mercato si attendeva di più, la delusione può far scendere il titolo.' },
    { q: 'Quale forma deve avere una società per far quotare il proprio capitale in Borsa?', a: 'Società per azioni', w: ['Società a responsabilità limitata', 'Società in nome collettivo', 'Ditta individuale'], e: 'In Borsa si scambiano azioni: le quote di una Srl, le società di persone e le ditte individuali non possono essere quotate.' },
    { q: 'In che forma esistono oggi le azioni di una società quotata italiana?', a: 'Registrazioni elettroniche', w: ['Certificati di carta numerati', 'Contratti firmati dal notaio', 'Gettoni digitali su blockchain'], e: 'Le azioni quotate sono dematerializzate: scritture contabili presso il depositario centrale, riportate nel tuo dossier titoli.' },
  ],
  fill: [
    { s: 'L’azione è una frazione del ___ di una società per azioni.', a: 'capitale sociale', w: ['debito bancario', 'fatturato annuo', 'fondo pensione'] },
    { s: 'La parte di utili che la società distribuisce ai soci si chiama ___.', a: 'dividendo', w: ['cedola', 'interesse', 'spread'] },
    { s: 'Grazie alla responsabilità ___, l’azionista non può perdere più di quanto ha investito.', a: 'limitata', w: ['illimitata', 'solidale', 'sussidiaria'] },
    { s: 'Chi vende un’azione a un prezzo più alto di quello pagato realizza un ___.', a: 'capital gain', w: ['dividendo', 'rimborso', 'aumento di capitale'] },
    { s: 'In caso di fallimento, gli azionisti vengono pagati ___, dopo tutti i creditori.', a: 'per ultimi', w: ['per primi', 'insieme alle banche', 'prima del fisco'] },
  ],
  order: [
    { q: 'Ordina dalla quota di proprietà più piccola alla più grande', i: ['100 azioni su 1.000.000', '500 azioni su 1.000.000', '2.000 azioni su 100.000', '1.000 azioni su 10.000'], e: 'Le quote sono 0,01%, 0,05%, 2% e 10%: conta il rapporto tra azioni possedute e azioni totali, non il numero assoluto.' },
    { q: 'Ordina chi viene pagato prima in caso di liquidazione della società', i: ['Creditori privilegiati', 'Creditori chirografari', 'Creditori subordinati', 'Azionisti'], e: 'Prima i creditori con privilegio (es. dipendenti e fisco), poi quelli ordinari, poi i subordinati. Gli azionisti chiudono la fila.' },
  ],
  cat: [
    { q: 'Caratteristica di un’azione o di un’obbligazione?', g: [['Azione', ['Quota di proprietà', 'Nessuna scadenza', 'Dividendo variabile', 'Diritto di voto']], ['Obbligazione', ['Prestito alla società', 'Data di rimborso', 'Interessi da contratto', 'Pagata prima dei soci']]] },
    { q: 'Possibile guadagno o rischio per l’azionista?', g: [['Guadagno', ['Dividendo incassato', 'Aumento del prezzo', 'Dividendo straordinario']], ['Rischio', ['Calo del prezzo', 'Taglio del dividendo', 'Fallimento della società']]] },
  ],
  scen: [
    { s: 'Marta, 24 anni, ha 2.000 € da parte. Un collega le dice: «Compra azioni di Alfa Spa, è solida e il dividendo è garantito, è come un conto deposito che rende di più».', q: 'Cosa fa Marta?', o: [
      { t: 'Ricorda che né dividendo né prezzo sono garantiti e valuta il rischio', ok: true, f: 'Giusto: un’azione è capitale di rischio. Né il dividendo né il valore sono garantiti, quindi non è paragonabile a un conto deposito.' },
      { t: 'Investe tutti i 2.000 € perché un dividendo garantito è un affare', ok: false, f: 'Il presupposto è sbagliato: nessun dividendo è garantito e il prezzo dell’azione può calare anche molto.' },
      { t: 'Ci rinuncia perché teme di dover pagare i debiti di Alfa se fallisce', ok: false, f: 'Paura infondata: con la responsabilità limitata rischia al massimo i soldi investiti, non il patrimonio personale.' },
    ] },
    { s: 'Giorgio, 58 anni, vuole riavere esattamente i suoi 20.000 € tra tre anni per aiutare la figlia a comprare casa. Un amico gli propone azioni «che tanto prima o poi salgono».', q: 'Cosa dovrebbe considerare Giorgio?', o: [
      { t: 'Che le azioni non hanno scadenza: tra tre anni potrebbero valere meno', ok: true, f: 'Esatto: l’azione non promette il rimborso del capitale. Per una somma da usare a data certa conviene valutare strumenti con scadenza e rischio più basso.' },
      { t: 'Che le azioni vengono rimborsate dalla società dopo qualche anno', ok: false, f: 'Falso: la società non rimborsa le azioni. Per uscire devi vendere sul mercato al prezzo del momento.' },
      { t: 'Che basta scegliere una grande azienda per avere il capitale al sicuro', ok: false, f: 'Anche le grandi aziende possono perdere molto valore in pochi anni: la dimensione non garantisce il capitale.' },
    ] },
    { s: 'Sara, 31 anni, ha azioni di Beta Spa. L’azienda annuncia utili in crescita del 10%, ma il titolo scende del 6% in giornata. Sara pensa che sia un errore del mercato.', q: 'Qual è la lettura più corretta?', o: [
      { t: 'Il mercato si aspettava di più: valuta se le prospettive sono cambiate', ok: true, f: 'Bravo: il prezzo riflette le aspettative. Conta capire se la notizia cambia il valore di lungo periodo, non reagire alla singola giornata.' },
      { t: 'È sicuramente un errore del mercato: compra subito il triplo delle azioni', ok: false, f: 'Il mercato non sbaglia per definizione, e raddoppiare la posizione su una sola notizia aumenta il rischio di concentrazione.' },
      { t: 'Vende tutto: se scende con buone notizie, l’azienda è in crisi', ok: false, f: 'Un calo in un giorno non dimostra una crisi: può riflettere attese troppo alte. Serve analizzare, non agire d’impulso.' },
    ] },
    { s: 'Luca, 40 anni, ha 3.000 € in azioni di Gamma Spa. Legge che l’azienda è in difficoltà e teme che, se fallisse, i creditori potrebbero chiedere soldi anche a lui.', q: 'Cosa è vero per Luca?', o: [
      { t: 'Rischia al massimo i 3.000 €, ma conviene non concentrarsi su un titolo', ok: true, f: 'Corretto: la responsabilità limitata lo protegge oltre l’investimento, ma i 3.000 € possono andare persi. La diversificazione riduce questo rischio.' },
      { t: 'Rischia di dover coprire i debiti in proporzione alla sua quota', ok: false, f: 'No: l’azionista di una Spa non risponde dei debiti sociali con il proprio patrimonio.' },
      { t: 'In caso di fallimento sarà rimborsato prima delle banche creditrici', ok: false, f: 'È l’opposto: gli azionisti vengono dopo tutti i creditori e spesso non recuperano nulla.' },
    ] },
  ],
  tip: 'Prima di comprare un’azione chiediti: «Sarei contento di possedere un pezzo di questa azienda per anni?». Se la risposta è no, forse stai solo scommettendo sul prezzo.',
});
