FQC(22, {
  intro: 'Quanto vale un’azienda per la Borsa? Lo dice la capitalizzazione: impara a calcolarla, a leggerla e a non farti ingannare dal prezzo unitario.',
  cards: [
    { t: 'La formula base', x: 'La capitalizzazione di mercato è il valore che la Borsa attribuisce a tutte le azioni di una società. Si aggiorna di continuo, insieme al prezzo del titolo.', v: { k: 'formula', f: 'Capitalizzazione = prezzo × numero di azioni', n: 'Es.: 12 € × 50 milioni di azioni = 600 milioni €' } },
    { t: 'Il prezzo unitario inganna', x: 'Il prezzo di una singola azione non dice quanto vale l’azienda: conta anche quante azioni esistono. Beta costa molto meno per azione, ma in Borsa vale dieci volte Alfa.', v: { k: 'vs', a: ['Alfa Spa', '200 € × 1 mln di azioni = 200 mln €'], b: ['Beta Spa', '5 € × 400 mln di azioni = 2 mld €'] } },
    { t: 'Il flottante', x: 'Le azioni dei soci di controllo o stabili di solito non vengono scambiate. La parte liberamente negoziabile si chiama flottante: più è ampia, più il titolo tende a essere liquido.', v: { k: 'pie', d: [['Socio di controllo', 55], ['Soci stabili', 10], ['Flottante', 35]] } },
    { t: 'Il peso negli indici', x: 'Indici come il FTSE MIB pesano le società in base alla capitalizzazione corretta per il flottante: i titoli più grandi muovono l’indice molto più di quelli piccoli.', v: { k: 'bars', d: [['Società A', 40], ['Società B', 25], ['Società C', 20], ['Società D', 15]], u: '%' } },
    { t: 'Non è denaro in cassa', x: 'Se il titolo sale del 20%, la capitalizzazione cresce del 20%, ma l’azienda non incassa nulla: le azioni passano da un investitore all’altro. Il guadagno è dei soci, non della società.', v: { k: 'stat', n: '0 €', l: 'incassati dall’azienda quando il suo titolo sale in Borsa' } },
    { t: 'Mercato e bilancio', x: 'La capitalizzazione riflette quanto gli investitori pagano oggi, sulla base delle aspettative. Il patrimonio netto è il valore dei mezzi dei soci secondo il bilancio. Possono differire molto.', v: { k: 'vs', a: ['Capitalizzazione', 'Valore di mercato delle azioni'], b: ['Patrimonio netto', 'Valore contabile in bilancio'] } },
  ],
  terms: [
    ['Capitalizzazione di mercato', 'Valore di Borsa di una società: prezzo di un’azione per il numero di azioni.'],
    ['Azioni in circolazione', 'Titoli emessi dalla società, escluse le azioni proprie che possiede lei stessa.'],
    ['Flottante', 'Quota di azioni liberamente negoziabili, escluse quelle dei soci di controllo e stabili.'],
    ['Capitalizzazione flottante', 'Valore di mercato delle sole azioni liberamente negoziabili.'],
    ['Indice ponderato per capitalizzazione', 'Indice in cui ogni società pesa in proporzione al suo valore di Borsa.'],
    ['Peso nell’indice', 'Percentuale che una società rappresenta sul valore totale dei titoli dell’indice.'],
    ['Valore contabile', 'Patrimonio netto di un’azienda come risulta dal bilancio, non dal mercato.'],
    ['Valore d’impresa', 'Capitalizzazione più debito finanziario netto: il costo teorico per rilevare tutta l’azienda.'],
  ],
  tf: [
    ['La capitalizzazione si calcola moltiplicando il prezzo dell’azione per il numero di azioni.', true, 'Es.: 8 € × 100 milioni di azioni = 800 milioni €. È il valore che il mercato attribuisce all’intero capitale.'],
    ['Un’azione che costa 300 € appartiene per forza a un’azienda più grande di una che costa 3 €.', false, 'Il prezzo unitario non basta: un’azienda con poche azioni a 300 € può valere molto meno di una con miliardi di azioni a 3 €.'],
    ['Quando il titolo di un’azienda sale del 10%, l’azienda incassa il 10% di denaro in più.', false, 'Il rialzo arricchisce gli azionisti, non la cassa della società: le azioni passano tra investitori sul mercato secondario.'],
    ['A parità di prezzo, se la società emette nuove azioni la sua capitalizzazione aumenta.', true, 'Capitalizzazione = prezzo × azioni: con più azioni allo stesso prezzo il prodotto cresce. Nella realtà il prezzo spesso reagisce all’emissione.'],
    ['Il flottante comprende anche le azioni detenute dall’azionista di controllo.', false, 'Il flottante esclude le partecipazioni di controllo e stabili: comprende solo le azioni che si possono comprare e vendere liberamente.'],
    ['Nel FTSE MIB i titoli con capitalizzazione flottante maggiore pesano di più sull’indice.', true, 'L’indice è ponderato per la capitalizzazione corretta per il flottante: un +2% di un titolo grande lo sposta più di un +2% di uno piccolo.'],
    ['Capitalizzazione e patrimonio netto di bilancio coincidono sempre.', false, 'La capitalizzazione è un valore di mercato basato sulle aspettative; il patrimonio netto è un valore contabile. Spesso sono molto diversi.'],
    ['La capitalizzazione di una società quotata può cambiare più volte in una sola seduta.', true, 'Il prezzo si muove di continuo durante le contrattazioni, quindi anche il valore di mercato dell’azienda si aggiorna in tempo reale.'],
    ['Un titolo con flottante molto ridotto tende a essere meno liquido.', true, 'Con poche azioni disponibili ci sono meno scambi: spread più ampi e prezzi che si muovono più facilmente anche con ordini piccoli.'],
    ['Il valore d’impresa di una società con debiti netti è inferiore alla sua capitalizzazione.', false, 'Il valore d’impresa somma alla capitalizzazione il debito finanziario netto: se il debito netto è positivo, il risultato è più alto.'],
  ],
  mcq: [
    { q: 'Alfa Spa ha 50 milioni di azioni che quotano 12 €. Qual è la sua capitalizzazione?', a: '600 milioni €', w: ['62 milioni €', '6 miliardi €', '60 milioni €'], e: '12 € × 50 milioni di azioni = 600 milioni €.' },
    { q: 'Alfa quota 200 € e ha 1 milione di azioni; Beta quota 5 € e ne ha 400 milioni. Quale vale di più?', a: 'Beta, con 2 miliardi €', w: ['Alfa, perché costa di più', 'Valgono esattamente uguale', 'Non si può stabilire'], e: 'Alfa: 200 € × 1 mln = 200 mln €. Beta: 5 € × 400 mln = 2 mld €. Il prezzo unitario da solo inganna.' },
    { q: 'Che cos’è il flottante di una società quotata?', a: 'Le azioni liberamente negoziabili', w: ['Le azioni del socio di controllo', 'Le azioni riacquistate dalla società', 'Le azioni di nuova emissione'], e: 'Il flottante esclude i pacchetti di controllo e le partecipazioni stabili: è la parte che passa davvero di mano in Borsa.' },
    { q: 'In un indice ponderato per capitalizzazione, quale titolo influenza di più l’indice?', a: 'Quello con il valore di Borsa maggiore', w: ['Quello con il prezzo unitario più alto', 'Quello con più dipendenti', 'Quello con il dividendo più alto'], e: 'Il peso dipende dal valore di mercato, spesso corretto per il flottante, non dal prezzo della singola azione o dalle dimensioni operative.' },
    { q: 'Il titolo di Gamma Spa sale del 15% in un mese. Cosa succede alla cassa dell’azienda per effetto del rialzo?', a: 'Resta invariata', w: ['Aumenta del 15%', 'Diminuisce del 15%', 'Aumenta del 15% del flottante'], e: 'La capitalizzazione cresce, ma gli scambi avvengono tra investitori: l’azienda incassa denaro solo se emette nuove azioni.' },
    { q: 'Un indice vale in totale 500 miliardi € e una delle società che lo compongono ne vale 100. Qual è il suo peso?', a: '20%', w: ['25%', '10%', '40%'], e: '100 ÷ 500 = 0,20, cioè il 20%. Tutte le altre società insieme pesano l’80%.' },
    { q: 'Delta Spa capitalizza 1 miliardo € e ha debiti finanziari netti per 400 milioni €. Qual è il suo valore d’impresa?', a: '1,4 miliardi €', w: ['600 milioni €', '1 miliardo €', '400 milioni €'], e: 'Valore d’impresa = capitalizzazione + debito netto = 1 mld + 0,4 mld = 1,4 mld €.' },
    { q: 'Una società ha 100 milioni di azioni e il socio di controllo ne possiede 60 milioni. Non ci sono altri soci stabili. Qual è il flottante?', a: '40%', w: ['60%', '100%', '30%'], e: 'Il flottante è la parte non vincolata: 100 − 60 = 40 milioni di azioni, cioè il 40% del capitale.' },
  ],
  fill: [
    { s: 'La capitalizzazione si ottiene moltiplicando il prezzo per il numero di ___.', a: 'azioni', w: ['dipendenti', 'dividendi', 'clienti'] },
    { s: 'La parte di azioni liberamente scambiabile in Borsa si chiama ___.', a: 'flottante', w: ['nominale', 'riserva', 'cedola'] },
    { s: 'Il patrimonio netto di bilancio è un valore ___, mentre la capitalizzazione è un valore di mercato.', a: 'contabile', w: ['nominale', 'fiscale', 'atteso'] },
    { s: 'Se il prezzo di un’azione raddoppia e il numero di azioni non cambia, la capitalizzazione ___.', a: 'raddoppia', w: ['si dimezza', 'resta uguale', 'triplica'] },
    { s: 'In un indice ponderato per capitalizzazione, le società più ___ influenzano di più l’andamento.', a: 'grandi', w: ['giovani', 'piccole', 'antiche'] },
  ],
  order: [
    { q: 'Ordina dalla capitalizzazione più bassa alla più alta', i: ['10 € × 5 milioni di azioni', '2 € × 100 milioni di azioni', '50 € × 20 milioni di azioni', '4 € × 1 miliardo di azioni'], e: 'Valgono 50 milioni, 200 milioni, 1 miliardo e 4 miliardi di euro: il prezzo di 50 € non basta a farne la società più grande.' },
    { q: 'Ricostruisci come si calcola il peso di un titolo in un indice', i: ['Rilevi il prezzo del titolo', 'Lo moltiplichi per le azioni', 'Correggi per il flottante', 'Dividi per il totale dell’indice'], e: 'Prezzo × azioni dà la capitalizzazione; tenendo solo il flottante e dividendo per il valore totale dell’indice ottieni il peso.' },
  ],
  cat: [
    { q: 'Rientra nel flottante oppure no?', g: [['Flottante', ['Azioni di piccoli risparmiatori', 'Piccole quote di fondi comuni', 'Azioni scambiate ogni giorno']], ['Non flottante', ['Pacchetto del socio di controllo', 'Quota vincolata da patto parasociale', 'Azioni proprie della società']]] },
    { q: 'Valore di mercato o valore contabile?', g: [['Di mercato', ['Capitalizzazione', 'Prezzo di Borsa', 'Valore d’impresa']], ['Contabile', ['Patrimonio netto', 'Capitale sociale', 'Riserve di bilancio']]] },
  ],
  scen: [
    { s: 'Paolo, 27 anni, confronta due titoli: Alfa quota 400 € e Beta 4 €. Pensa che Beta sia «più economica» e che per questo abbia più spazio per salire.', q: 'Qual è il ragionamento corretto?', o: [
      { t: 'Confrontare capitalizzazioni e utili delle due aziende', ok: true, f: 'Giusto: il prezzo unitario dipende da quante azioni esistono. Per capire se un titolo è caro serve il valore totale rapportato a ciò che l’azienda produce.' },
      { t: 'Comprare Beta: con 4 € ad azione ne prende cento volte di più', ok: false, f: 'Avere più azioni non significa possedere di più: conta la quota dell’azienda e il suo valore, non il numero di titoli.' },
      { t: 'Comprare Alfa: un prezzo alto è sinonimo di qualità', ok: false, f: 'Anche questo è un errore: il prezzo unitario non misura né la qualità né la convenienza di un’azienda.' },
    ] },
    { s: 'Chiara, 35 anni, legge che il titolo di Gamma Spa è salito del 30% in un anno. Pensa di comprarlo perché «ora l’azienda ha il 30% di soldi in più da investire».', q: 'Cosa le conviene fare?', o: [
      { t: 'Correggere l’idea, perché il rialzo non porta cassa, e studiare i conti', ok: true, f: 'Esatto: la cassa non cambia per un rialzo di Borsa. Per valutare Gamma servono bilancio, utili e prospettive, non la sola performance del titolo.' },
      { t: 'Comprare subito, perché più cassa in azienda significa crescita sicura', ok: false, f: 'Premessa sbagliata: le azioni passano tra investitori, l’azienda non incassa nulla dal rialzo.' },
      { t: 'Aspettare che la capitalizzazione torni al livello di partenza', ok: false, f: 'Non esiste un livello a cui il titolo debba tornare: il prezzo segue le aspettative sull’azienda, non un valore fisso.' },
    ] },
    { s: 'Federico, 50 anni, vuole investire 30.000 € in Delta Spa, una società con flottante del 5% e pochi scambi giornalieri. Sta per inserire un unico grande ordine al prezzo di mercato.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Usare ordini con limite, anche frazionati, e pesare la scarsa liquidità', ok: true, f: 'Corretto: con un flottante ridotto un ordine grande può spostare il prezzo. Il limite lo protegge e la poca liquidità va considerata anche per quando vorrà vendere.' },
      { t: 'Procedere: il flottante non incide su come si eseguono gli ordini', ok: false, f: 'Incide eccome: meno azioni scambiabili significano meno controparti, spread più ampi e prezzi più instabili.' },
      { t: 'Chiedere al socio di controllo di vendergli direttamente le sue azioni', ok: false, f: 'Non è una soluzione realistica per un piccolo investitore: le azioni del socio di controllo sono proprio quelle fuori dal flottante.' },
    ] },
    { s: 'Anna, 44 anni, vuole un ETF sul FTSE MIB convinta che ognuna delle 40 società pesi il 2,5% del totale, così da avere un’esposizione perfettamente uguale.', q: 'Cosa le conviene fare?', o: [
      { t: 'Controllare i pesi: l’indice è ponderato per capitalizzazione', ok: true, f: 'Esatto: nel FTSE MIB le società più grandi pesano molto di più. Conoscere i pesi aiuta a capire a quali titoli e settori è davvero esposta.' },
      { t: 'Comprare: tutti gli indici danno lo stesso peso a ogni società', ok: false, f: 'Falso: la maggior parte degli indici azionari, FTSE MIB compreso, pesa le società in base al valore di mercato.' },
      { t: 'Considerare che pesano di più le azioni con il prezzo unitario più alto', ok: false, f: 'Il prezzo unitario non conta nel FTSE MIB: conta la capitalizzazione corretta per il flottante.' },
    ] },
  ],
  tip: 'Quando confronti due aziende guarda la capitalizzazione, non il prezzo della singola azione: un titolo da 2 € può valere in Borsa molto più di uno da 200 €.',
});
