FQC(23, {
  intro: 'Il dividendo è la parte di utili che arriva nelle tasche dei soci: scopri le sue date chiave, come misurarlo e quando è davvero sostenibile.',
  cards: [
    { t: 'Il calendario del dividendo', x: 'Il consiglio di amministrazione propone il dividendo e l’assemblea lo approva. Poi contano la data di stacco, la record date (chi risulta socio nei registri) e la data di pagamento.', v: { k: 'steps', s: ['Proposta del CDA', 'Delibera dell’assemblea', 'Data di stacco', 'Pagamento'] } },
    { t: 'Il rendimento da dividendo', x: 'Il dividend yield misura quanto rende il dividendo rispetto al prezzo dell’azione. Cambia con il prezzo: se il titolo scende e il dividendo resta uguale, la percentuale sale.', v: { k: 'formula', f: 'Dividend yield = dividendo annuo ÷ prezzo', n: 'Es.: 1,20 € ÷ 30 € = 4%' } },
    { t: 'Il payout', x: 'Il payout ratio è la quota di utile netto distribuita ai soci. Con un payout del 60%, su 100 € di utile 60 vanno in dividendi e 40 restano in azienda per investire o ridurre i debiti.', v: { k: 'pie', d: [['Dividendi', 60], ['Utili trattenuti', 40]] } },
    { t: 'Il prezzo dopo lo stacco', x: 'Il giorno dello stacco il prezzo di riferimento scende, in teoria, dell’importo del dividendo: il valore passa dall’azione al tuo conto. Il dividendo non è un regalo aggiuntivo.', v: { k: 'bars', d: [['Prezzo prima', 20], ['Dividendo', 1], ['Prezzo dopo (teorico)', 19]], u: '€' } },
    { t: 'Le tasse sul dividendo', x: 'Per una persona fisica residente, sui dividendi si applica di norma una ritenuta del 26%: su 100 € lordi ne incassi 74. Sui titoli esteri può aggiungersi la ritenuta del Paese d’origine.', v: { k: 'stat', n: '26%', l: 'ritenuta tipica sui dividendi per un privato in Italia' } },
    { t: 'Quando il payout preoccupa', x: 'Un payout sopra il 100% significa distribuire più di quanto si guadagna: la società attinge a riserve o debito e prima o poi il dividendo rischia di essere tagliato.', v: { k: 'scale', a: 'Payout prudente', b: 'Payout a rischio', d: [['30%', 20], ['60%', 45], ['90%', 75], ['120%', 95]] } },
  ],
  terms: [
    ['Data di stacco', 'Giorno da cui il titolo si scambia senza il diritto al dividendo appena deliberato.'],
    ['Record date', 'Data in cui si individua, dai registri, chi ha diritto a ricevere il dividendo.'],
    ['Data di pagamento', 'Giorno in cui l’importo distribuito viene accreditato sul conto degli azionisti.'],
    ['Dividend yield', 'Rapporto tra dividendo annuo per azione e prezzo del titolo, in percentuale.'],
    ['Payout ratio', 'Percentuale dell’utile netto che la società distribuisce ai soci.'],
    ['Acconto sul dividendo', 'Parte della distribuzione pagata in anticipo durante l’esercizio, prima del saldo.'],
    ['Dividendo straordinario', 'Distribuzione eccezionale e non ricorrente, ad esempio dopo la vendita di un’attività.'],
    ['Trappola del rendimento', 'Yield molto alto dovuto al crollo del prezzo, spesso segnale di un taglio in arrivo.'],
  ],
  tf: [
    ['Per ricevere il dividendo devi possedere l’azione prima della data di stacco.', true, 'Chi compra il giorno dello stacco o dopo acquista un titolo già senza dividendo: il pagamento andrà a chi aveva le azioni prima.'],
    ['Comprare un’azione il giorno prima dello stacco permette di incassare il dividendo gratis.', false, 'Allo stacco il prezzo scende in teoria dell’importo del dividendo, che poi viene anche tassato: non c’è un guadagno automatico.'],
    ['Se il prezzo dell’azione scende e il dividendo resta uguale, il dividend yield sale.', true, 'Yield = dividendo ÷ prezzo: con 1 € di dividendo, a 25 € rende il 4%, a 20 € il 5%.'],
    ['Un dividend yield molto alto è sempre il segnale di un ottimo affare.', false, 'Spesso è alto perché il prezzo è crollato e il mercato si aspetta un taglio del dividendo: è la cosiddetta trappola del rendimento.'],
    ['Il payout ratio indica quale parte dell’utile netto viene distribuita ai soci.', true, 'Con un utile per azione di 2 € e un dividendo di 0,80 €, il payout è del 40%: il resto viene trattenuto in azienda.'],
    ['Un payout stabilmente superiore al 100% è sostenibile senza problemi nel tempo.', false, 'Significa distribuire più di quanto si guadagna, attingendo a riserve o debito: a lungo andare il dividendo rischia di essere ridotto.'],
    ['In Italia il dividendo di fine esercizio viene deliberato dall’assemblea degli azionisti.', true, 'Il consiglio di amministrazione propone, ma è l’assemblea che approva il bilancio e decide come destinare l’utile.'],
    ['Un’azienda che non paga dividendi è sempre un cattivo investimento.', false, 'Molte società reinvestono tutti gli utili per crescere: il rendimento per il socio può arrivare dall’aumento di valore delle azioni.'],
    ['Per un privato residente in Italia, sui dividendi si applica di norma una ritenuta del 26%.', true, 'Su un dividendo lordo di 100 € ne incassi 74 netti. Sui titoli esteri può aggiungersi la ritenuta del Paese d’origine.'],
    ['La record date è il giorno in cui il dividendo viene accreditato sul conto.', false, 'La record date serve a stabilire chi ha diritto al dividendo; l’accredito avviene alla data di pagamento.'],
  ],
  mcq: [
    { q: 'Alfa Spa paga un dividendo annuo di 1,50 € e l’azione quota 30 €. Qual è il dividend yield?', a: '5%', w: ['1,5%', '20%', '3%'], e: '1,50 ÷ 30 = 0,05, cioè il 5% annuo, prima delle tasse.' },
    { q: 'Beta Spa ha un utile per azione di 2 € e paga un dividendo di 1,20 €. Qual è il payout?', a: '60%', w: ['40%', '120%', '6%'], e: '1,20 ÷ 2 = 0,60: la società distribuisce il 60% dell’utile e ne trattiene il 40%.' },
    { q: 'Il dividendo di Gamma Spa stacca lunedì. Entro quando devi aver comprato le azioni per riceverlo?', a: 'Entro la chiusura del venerdì precedente', w: ['Entro la chiusura di lunedì stesso', 'Entro la data di pagamento del dividendo', 'Entro la fine del mese in corso'], e: 'Devi possedere il titolo prima del giorno di stacco: chi compra lunedì acquista azioni già senza dividendo.' },
    { q: 'Un titolo quota 50 € e stacca un dividendo di 2 €. Qual è il prezzo teorico dopo lo stacco, a parità di altre condizioni?', a: '48 €', w: ['50 €', '52 €', '49 €'], e: 'Il valore del dividendo esce dall’azione ed entra nel tuo conto: in teoria il prezzo si riduce di 2 €, a 48 €.' },
    { q: 'Delta Spa offre un dividend yield del 14% dopo aver perso metà del valore in sei mesi. Cosa è più prudente pensare?', a: 'Il mercato potrebbe attendersi un taglio', w: ['È un rendimento garantito per anni', 'Il calo del prezzo è irrilevante', 'Più è alto, più è sicuro'], e: 'Un yield anomalo dopo un crollo può essere una trappola: se gli utili calano, il dividendo futuro può essere ridotto o sospeso.' },
    { q: 'Un privato residente in Italia riceve un dividendo lordo di 200 € da una società italiana. Con la ritenuta del 26%, quanto incassa?', a: '148 €', w: ['174 €', '200 €', '52 €'], e: '200 × 26% = 52 € di ritenuta: restano 200 − 52 = 148 € netti.' },
    { q: 'A cosa serve la record date?', a: 'A individuare chi ha diritto al dividendo', w: ['A fissare il giorno dell’accredito', 'A convocare l’assemblea dei soci', 'A calcolare il prezzo di chiusura'], e: 'Alla record date si controllano i registri: chi risulta azionista riceverà il dividendo alla data di pagamento.' },
    { q: 'Una società in utile reinveste tutto e non distribuisce dividendi. Qual è il suo payout?', a: '0%', w: ['100%', '50%', '10%'], e: 'Il payout misura la parte di utile distribuita: se non distribuisce nulla è zero, e tutto l’utile resta in azienda.' },
  ],
  fill: [
    { s: 'Dalla data di ___ l’azione si scambia senza diritto al dividendo.', a: 'stacco', w: ['pagamento', 'emissione', 'scadenza'] },
    { s: 'Il dividend ___ è il rapporto tra dividendo annuo e prezzo dell’azione.', a: 'yield', w: ['payout', 'spread', 'split'] },
    { s: 'Il ___ ratio misura la quota di utile netto distribuita ai soci.', a: 'payout', w: ['yield', 'leverage', 'quick'] },
    { s: 'Un rendimento altissimo dovuto al crollo del prezzo può essere una ___ del rendimento.', a: 'trappola', w: ['garanzia', 'promessa', 'conferma'] },
    { s: 'Il dividendo di fine esercizio viene deliberato dall’___ degli azionisti.', a: 'assemblea', w: ['amministratore delegato', 'autorità di vigilanza', 'agenzia di rating'] },
  ],
  order: [
    { q: 'Metti in ordine le tappe di un dividendo', i: ['Proposta del consiglio di amministrazione', 'Delibera dell’assemblea', 'Data di stacco', 'Data di pagamento'], e: 'Il CDA propone, l’assemblea approva; poi il titolo stacca il dividendo e, pochi giorni dopo, il denaro arriva sul conto.' },
    { q: 'Ordina dal dividend yield più basso al più alto', i: ['1 € con prezzo di 50 €', '1,50 € con prezzo di 50 €', '2 € con prezzo di 40 €', '3 € con prezzo di 40 €'], e: 'Gli yield sono 2%, 3%, 5% e 7,5%: conta il rapporto tra dividendo e prezzo, non il dividendo in euro.' },
  ],
  cat: [
    { q: 'Segnale di dividendo sostenibile o a rischio?', g: [['Sostenibile', ['Payout del 50%', 'Utili stabili da anni', 'Cassa che copre il dividendo']], ['A rischio', ['Payout del 130%', 'Utili in forte calo', 'Dividendo pagato a debito']]] },
    { q: 'Riguarda il dividend yield o il payout ratio?', g: [['Dividend yield', ['Dividendo diviso prezzo', 'Sale se il prezzo scende', 'Rendimento sul prezzo pagato']], ['Payout ratio', ['Dividendo diviso utile', 'Oltre 100% è un allarme', 'Quota di utili distribuita']]] },
  ],
  scen: [
    { s: 'Roberto, 62 anni, in pensione, cerca un’entrata regolare. Trova Epsilon Spa con un dividend yield del 12%: il titolo ha perso il 50% in un anno e gli utili sono in calo.', q: 'Cosa fa Roberto?', o: [
      { t: 'Verifica payout, utili e debito e non punta tutto su un solo titolo', ok: true, f: 'Ottimo: uno yield così alto dopo un crollo è un campanello d’allarme. Controllare la sostenibilità e diversificare protegge il suo reddito.' },
      { t: 'Investe gran parte dei risparmi: il 12% è un reddito sicuro', ok: false, f: 'Il dividendo non è garantito: con utili in calo il rischio di taglio è alto, e il prezzo potrebbe scendere ancora.' },
      { t: 'Compra perché un titolo sceso del 50% non può scendere di più', ok: false, f: 'Falso: un titolo dimezzato può dimezzarsi ancora. Il calo passato non mette un pavimento al prezzo.' },
    ] },
    { s: 'Giulia, 29 anni, vuole comprare Zeta Spa il giorno prima dello stacco di un dividendo del 3% e rivenderla il giorno dopo, convinta di guadagnare il 3% in 24 ore.', q: 'Cosa dovrebbe sapere Giulia?', o: [
      { t: 'Allo stacco il prezzo scende di circa il dividendo, che è anche tassato', ok: true, f: 'Esatto: il dividendo esce dal valore dell’azione. Tra ritenuta del 26% e commissioni, l’operazione rischia di chiudersi in perdita.' },
      { t: 'Il piano funziona: il prezzo dopo lo stacco resta invariato', ok: false, f: 'No: il prezzo di riferimento viene ridotto dell’importo del dividendo, quindi il guadagno «facile» sparisce.' },
      { t: 'Le conviene comprare il giorno stesso dello stacco', ok: false, f: 'Chi compra il giorno dello stacco non riceve il dividendo: il titolo si scambia già senza.' },
    ] },
    { s: 'Matteo, 45 anni, cerca un dividendo affidabile nel tempo. Alfa ha payout del 40%, yield del 3% e utili in crescita; Beta ha payout del 110%, yield del 7% e utili fermi.', q: 'Come ragiona correttamente?', o: [
      { t: 'Considera più sostenibile il dividendo di Alfa e approfondisce entrambe', ok: true, f: 'Giusto: un payout moderato con utili in crescita lascia margine; un payout oltre il 100% con utili fermi è difficile da mantenere.' },
      { t: 'Sceglie Beta: un dividendo più alto è sempre più affidabile', ok: false, f: 'Il dividendo alto oggi non garantisce quello di domani: Beta distribuisce più di quanto guadagna.' },
      { t: 'Le considera uguali: il payout non dice nulla sul dividendo futuro', ok: false, f: 'Il payout è proprio uno degli indicatori chiave della sostenibilità del dividendo.' },
    ] },
    { s: 'Elisa, 38 anni, apre l’app della banca e vede che il suo titolo principale ha aperto in calo del 2,5%. Poi nota che proprio oggi c’è lo stacco di un dividendo del 2,5%.', q: 'Come interpreta il calo?', o: [
      { t: 'È l’effetto dello stacco: il valore le arriva come dividendo', ok: true, f: 'Corretto: il prezzo si riduce dell’importo del dividendo, che le verrà accreditato (al netto delle tasse). La sua ricchezza non è crollata.' },
      { t: 'È un segnale di crisi: vende subito tutte le azioni', ok: false, f: 'Vendere per un calo tecnico legato allo stacco significa reagire a un movimento atteso, pagando commissioni inutili.' },
      { t: 'È un errore della banca da segnalare subito alla CONSOB', ok: false, f: 'Nessun errore: la riduzione del prezzo allo stacco è un meccanismo normale del mercato.' },
    ] },
  ],
  tip: 'Non scegliere un’azione solo per il dividendo alto: controlla payout, andamento degli utili e debito. Un dividendo vale se è sostenibile, non se è spettacolare.',
});
