FQC(24, {
  intro: 'Come fa un’azienda a entrare in Borsa? Scopri le tappe di una IPO, chi incassa i soldi e perché un debutto brillante non garantisce nulla.',
  cards: [
    { t: 'Il percorso verso la Borsa', x: 'Una quotazione richiede mesi: si scelgono banche e consulenti, si prepara il prospetto informativo da far approvare, si raccolgono gli ordini e infine il titolo debutta sul mercato.', v: { k: 'steps', s: ['Scelta delle banche', 'Prospetto approvato', 'Bookbuilding', 'Prezzo finale', 'Debutto in Borsa'] } },
    { t: 'Chi incassa i soldi', x: 'Con un’offerta di sottoscrizione la società emette nuove azioni e raccoglie capitale per crescere. Con un’offerta di vendita sono i vecchi soci a cedere azioni e a incassare. Spesso le IPO combinano le due.', v: { k: 'vs', a: ['Sottoscrizione', 'Nuove azioni: i soldi vanno alla società'], b: ['Vendita', 'Azioni esistenti: i soldi vanno ai soci'] } },
    { t: 'Dalla forchetta al prezzo', x: 'Le banche propongono una forchetta di prezzo; durante il bookbuilding raccolgono gli ordini degli investitori e, in base alla domanda, fissano il prezzo finale di collocamento.', v: { k: 'formula', f: 'Raccolta = prezzo di collocamento × azioni offerte', n: 'Es.: 8 € × 25 milioni di azioni = 200 milioni €' } },
    { t: 'I listini di Borsa Italiana', x: 'Le società più strutturate si quotano su Euronext Milan; il segmento STAR riunisce medie imprese con requisiti di trasparenza più elevati; Euronext Growth Milan è pensato per le PMI.', v: { k: 'icons', d: [['🏛️', 'Euronext Milan'], ['⭐', 'Segmento STAR'], ['🌱', 'Euronext Growth Milan']] } },
    { t: 'La greenshoe', x: 'Se la domanda è forte, le banche possono collocare azioni in più rispetto all’offerta base grazie alla greenshoe, un’opzione usata anche per stabilizzare il prezzo nelle prime settimane.', v: { k: 'stat', n: '15%', l: 'quota massima tipica della greenshoe rispetto all’offerta' } },
    { t: 'Il debutto non è tutto', x: 'Un primo giorno brillante non garantisce il futuro. Diversi studi mostrano che, in media, molte società neoquotate hanno reso meno del mercato negli anni successivi. Esempio illustrativo:', v: { k: 'bars', d: [['Prezzo IPO', 10], ['Fine 1° giorno', 12], ['Dopo 3 anni', 9]], u: '€' } },
  ],
  terms: [
    ['IPO', 'Prima offerta al pubblico delle azioni di una società che chiede di essere quotata.'],
    ['Prospetto informativo', 'Documento su società, offerta e rischi, approvato dall’autorità di vigilanza.'],
    ['Bookbuilding', 'Raccolta degli ordini degli investitori per misurare la domanda e fissare il prezzo.'],
    ['Forchetta di prezzo', 'Intervallo tra minimo e massimo entro cui si prevede di collocare le azioni.'],
    ['Greenshoe', 'Opzione per collocare azioni extra oltre l’offerta base se la domanda è alta.'],
    ['Lock-up', 'Impegno dei soci esistenti a non vendere azioni per un certo periodo dopo il debutto.'],
    ['Riparto', 'Assegnazione proporzionale delle azioni quando la domanda supera l’offerta.'],
    ['Delisting', 'Revoca della quotazione: le azioni smettono di essere scambiate in Borsa.'],
  ],
  tf: [
    ['In un’offerta di sottoscrizione il denaro raccolto va alla società.', true, 'La società emette nuove azioni: è un aumento di capitale e i soldi entrano nelle sue casse, al netto dei costi.'],
    ['In un’offerta pubblica di vendita la società incassa tutto il denaro raccolto.', false, 'Nell’offerta di vendita sono i soci esistenti a cedere le loro azioni: il ricavato va a loro, non alla società.'],
    ['In Italia il prospetto di un’IPO su Euronext Milan deve essere approvato dalla CONSOB.', true, 'La CONSOB verifica che il prospetto sia completo, coerente e comprensibile, ma non giudica la convenienza dell’investimento.'],
    ['Se la CONSOB approva il prospetto, l’investimento nell’IPO è sicuro e conveniente.', false, 'L’approvazione riguarda la qualità delle informazioni, non la bontà dell’affare: il rischio resta tutto dell’investitore.'],
    ['Le azioni di un’IPO salgono sempre il primo giorno di quotazione.', false, 'Molte IPO debuttano in rialzo, ma altre scendono subito sotto il prezzo di collocamento: non esiste alcuna garanzia.'],
    ['Il lock-up impedisce ai vecchi soci di vendere le loro azioni per un periodo dopo l’IPO.', true, 'Serve a evitare che vendite massicce subito dopo il debutto pesino sul prezzo. Alla sua scadenza possono arrivare vendite.'],
    ['Nel bookbuilding le banche raccolgono gli ordini per decidere a che prezzo collocare le azioni.', true, 'La domanda raccolta entro la forchetta aiuta a fissare il prezzo finale: più è forte, più il prezzo può avvicinarsi al massimo.'],
    ['Euronext Growth Milan è il mercato di Borsa Italiana pensato per le piccole e medie imprese.', true, 'Ha requisiti di accesso più leggeri del mercato principale: le società quotate sono spesso più piccole e i titoli meno liquidi.'],
    ['Se un’IPO è molto richiesta, ogni investitore riceve tutte le azioni che ha chiesto.', false, 'Con una domanda superiore all’offerta si procede al riparto: ciascuno riceve solo una parte di quanto richiesto.'],
    ['Quotarsi in Borsa non comporta nuovi obblighi per la società.', false, 'Una quotata deve pubblicare bilanci periodici, comunicare subito le notizie rilevanti e rispettare regole di governance più severe.'],
  ],
  mcq: [
    { q: 'Alfa Spa colloca 25 milioni di nuove azioni a 8 € ciascuna. Quanto raccoglie, al lordo dei costi?', a: '200 milioni €', w: ['33 milioni €', '20 milioni €', '2 miliardi €'], e: '8 € × 25 milioni = 200 milioni €. Trattandosi di nuove azioni, il denaro va alla società.' },
    { q: 'Nell’IPO di Beta il fondatore vende parte delle sue azioni. Chi incassa il ricavato di questa vendita?', a: 'Il fondatore', w: ['La società Beta', 'La CONSOB', 'Borsa Italiana'], e: 'È un’offerta di vendita: azioni già esistenti cambiano proprietario e il ricavato va a chi le cede.' },
    { q: 'A cosa serve la greenshoe in un’IPO?', a: 'A collocare azioni extra se la domanda è alta', w: ['A garantire il rialzo del primo giorno', 'A vietare le vendite dei vecchi soci', 'A rimborsare chi perde in Borsa'], e: 'È un’opzione di sovrallocazione, di solito fino al 15% dell’offerta, usata anche per sostenere il prezzo dopo il debutto.' },
    { q: 'Quale autorità approva il prospetto informativo di un’IPO in Italia?', a: 'La CONSOB', w: ['La BCE', 'L’Agenzia delle Entrate', 'L’IVASS'], e: 'La CONSOB vigila sui mercati e approva il prospetto, senza però garantire la bontà dell’investimento.' },
    { q: 'La forchetta di prezzo dell’IPO di Gamma è 10-12 € e la domanda risulta molto debole. Cosa è più probabile?', a: 'Un prezzo vicino al minimo della forchetta', w: ['Un prezzo fissato sopra i 12 €', 'Un prezzo garantito di 12 €', 'Un rialzo sicuro al debutto'], e: 'Con poca domanda il prezzo tende verso il basso; nei casi estremi l’offerta viene ridotta, rinviata o ritirata.' },
    { q: 'Qual è lo scopo principale del lock-up?', a: 'Evitare vendite massicce dei vecchi soci', w: ['Bloccare gli acquisti dei piccoli investitori', 'Fissare il prezzo di collocamento', 'Limitare i dividendi del primo anno'], e: 'Il lock-up vincola i soci esistenti per un periodo: riduce il rischio che un’ondata di vendite affossi il titolo appena quotato.' },
    { q: 'Un’IPO riceve ordini pari a 3 volte le azioni offerte e tu hai chiesto azioni per 3.000 €. Cosa è più probabile?', a: 'Ricevi solo una parte, per il riparto', w: ['Ricevi il triplo di quanto chiesto', 'Ricevi tutto perché sei un privato', 'L’IPO viene annullata'], e: 'Quando la domanda supera l’offerta si applica il riparto: ogni investitore ottiene una parte delle azioni richieste.' },
    { q: 'Secondo l’esperienza storica, quale affermazione sulle IPO è corretta?', a: 'Un buon debutto non garantisce buoni risultati', w: ['Le IPO battono sempre il mercato', 'Il primo giorno chiude sempre in rialzo', 'Il prezzo di collocamento fa da minimo'], e: 'Diversi studi mostrano che, in media, molte società neoquotate hanno reso meno del mercato negli anni dopo il debutto.' },
  ],
  fill: [
    { s: 'L’offerta pubblica iniziale di azioni si indica con la sigla ___.', a: 'IPO', w: ['OPA', 'ETF', 'PIL'] },
    { s: 'Il documento che descrive la società e i rischi dell’offerta si chiama prospetto ___.', a: 'informativo', w: ['contabile', 'fiscale', 'tecnico'] },
    { s: 'L’impegno dei vecchi soci a non vendere per un periodo dopo l’IPO si chiama ___.', a: 'lock-up', w: ['greenshoe', 'bookbuilding', 'delisting'] },
    { s: 'Nell’offerta pubblica di ___ la società emette nuove azioni e incassa il denaro.', a: 'sottoscrizione', w: ['vendita', 'acquisto', 'scambio'] },
    { s: 'Quando la domanda supera l’offerta, le azioni vengono assegnate con il ___.', a: 'riparto', w: ['rimborso', 'raggruppamento', 'riscatto'] },
  ],
  order: [
    { q: 'Metti in ordine le fasi di una IPO', i: ['Scelta delle banche', 'Approvazione del prospetto', 'Bookbuilding', 'Fissazione del prezzo', 'Inizio delle negoziazioni'], e: 'Prima si organizza l’operazione e si fa approvare il prospetto, poi si raccolgono gli ordini, si fissa il prezzo e il titolo debutta.' },
    { q: 'Ordina gli eventi tipici nella vita di una società quotata', i: ['Offerta delle azioni in IPO', 'Primo giorno di negoziazione', 'Scadenza del lock-up', 'Offerta pubblica di acquisto totalitaria', 'Delisting'], e: 'Dopo l’offerta il titolo debutta; scaduto il lock-up i vecchi soci possono vendere; anni dopo un’OPA su tutte le azioni può portare al delisting.' },
  ],
  cat: [
    { q: 'Vantaggio o svantaggio della quotazione per l’azienda?', g: [['Vantaggio', ['Accesso a nuovo capitale', 'Maggiore visibilità', 'Azioni usabili per acquisizioni']], ['Svantaggio', ['Costi di quotazione elevati', 'Obblighi di trasparenza', 'Pressione sui risultati di breve']]] },
    { q: 'Il denaro va alla società o ai soci venditori?', g: [['Alla società', ['Emissione di nuove azioni', 'Offerta di sottoscrizione', 'Aumento di capitale in IPO']], ['Ai soci venditori', ['Cessione di azioni del fondatore', 'Offerta pubblica di vendita', 'Uscita di un fondo di private equity']]] },
  ],
  scen: [
    { s: 'Valentina, 33 anni, vede ovunque la pubblicità dell’IPO di Alfa Spa, definita «molto richiesta». Vuole investire 10.000 €, metà dei suoi risparmi, convinta che il titolo salirà al debutto.', q: 'Cosa le conviene fare?', o: [
      { t: 'Leggere i rischi nel prospetto e investire solo una quota adatta a lei', ok: true, f: 'Ottimo: il prospetto spiega rischi e destinazione dei soldi. Un’IPO resta un’azione rischiosa e non va concentrata metà del patrimonio su un titolo.' },
      { t: 'Investire i 10.000 €: con tanta domanda il rialzo è garantito', ok: false, f: 'Nessun rialzo è garantito: la pubblicità e la domanda non proteggono dal calo, e con il riparto potrebbe ricevere meno azioni.' },
      { t: 'Chiedere 50.000 € di azioni sapendo che il riparto ridurrà l’assegnazione', ok: false, f: 'È rischioso: se il riparto è più leggero del previsto, si ritrova con una posizione molto più grande di quanto può permettersi.' },
    ] },
    { s: 'Marco, 47 anni, legge nel prospetto dell’IPO di Teta Spa che l’80% delle azioni offerte è venduto dai soci attuali, tra cui un fondo di private equity che esce del tutto.', q: 'Come dovrebbe interpretare questa informazione?', o: [
      { t: 'Chiedersi perché i soci vendono e se il prezzo è ragionevole', ok: true, f: 'Giusto: un’offerta soprattutto di vendita non è per forza negativa, ma chi vende conosce bene l’azienda. Il prezzo va valutato con attenzione.' },
      { t: 'Pensare che quei soldi serviranno a far crescere Teta Spa', ok: false, f: 'Errore: nell’offerta di vendita il ricavato va ai soci venditori, non alla società.' },
      { t: 'Ignorarla: chi vende in un’IPO non conta nulla', ok: false, f: 'Conta: sapere chi incassa e quanto resta ai vecchi soci aiuta a capire gli interessi in gioco.' },
    ] },
    { s: 'Silvia, 26 anni, ha comprato azioni in IPO a 10 €. Dopo sei mesi il titolo vale 14 € e legge che tra pochi giorni scade il lock-up dei fondatori.', q: 'Qual è l’approccio più sensato?', o: [
      { t: 'Considerare che possono arrivare vendite e decidere in base al proprio piano', ok: true, f: 'Corretto: la fine del lock-up può portare pressione sul prezzo, ma la decisione va presa sui fondamentali e sui suoi obiettivi, non sul panico.' },
      { t: 'Vendere tutto: la fine del lock-up significa che l’azienda è in crisi', ok: false, f: 'Il lock-up scade per contratto, non per difficoltà aziendali: non è un segnale di crisi in sé.' },
      { t: 'Comprare molte altre azioni: dopo il lock-up il titolo sale sempre', ok: false, f: 'Al contrario, alla scadenza del lock-up può aumentare l’offerta di azioni sul mercato. Nessun rialzo è automatico.' },
    ] },
    { s: 'Tommaso, 55 anni, non ha partecipato all’IPO di Kappa Spa, che al debutto è salita del 40%. Il giorno dopo vuole comprare con un ordine a mercato all’apertura, usando 15.000 €.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Valutare l’azienda al nuovo prezzo e, se compra, usare un limite', ok: true, f: 'Bravo: dopo un +40% la capitalizzazione è molto più alta. Un ordine con limite evita di pagare prezzi eccessivi in una fase volatile.' },
      { t: 'Comprare a mercato all’apertura: il rialzo continuerà come il primo giorno', ok: false, f: 'Il primo giorno non predice i successivi, e un ordine a mercato in apertura può essere eseguito a prezzi molto lontani dalle attese.' },
      { t: 'Considerare il prezzo di IPO come il valore giusto a cui tornerà presto', ok: false, f: 'Non esiste un prezzo a cui il titolo debba tornare: il valore dipende dalle prospettive dell’azienda.' },
    ] },
  ],
  tip: 'Prima di aderire a un’IPO leggi nel prospetto almeno i fattori di rischio e l’uso dei proventi: sapere chi vende e perché ti dice molto sull’operazione.',
});
