FQC(25, {
  intro: 'Non tutte le azioni reagiscono allo stesso modo all’economia: scopri i settori, la differenza tra ciclici e difensivi e il rischio di concentrazione.',
  cards: [
    { t: 'Tanti settori, un mercato', x: 'Le società quotate si classificano per settore in base all’attività. Lo standard GICS, molto diffuso, ne individua 11: dall’energia alla tecnologia, dalla sanità alle utility.', v: { k: 'icons', d: [['🏦', 'Finanziari'], ['⚡', 'Utility'], ['💊', 'Sanità'], ['🚗', 'Consumi discrezionali']] } },
    { t: 'Ciclici e difensivi', x: 'Auto, viaggi o macchinari si rimandano quando l’economia rallenta; bollette, cibo e farmaci si comprano comunque. Per questo i settori reagiscono in modo diverso al ciclo economico.', v: { k: 'vs', a: ['Ciclici', 'Utili legati all’andamento dell’economia'], b: ['Difensivi', 'Domanda stabile anche in recessione'] } },
    { t: 'In una recessione', x: 'Esempio illustrativo: in recessione un titolo ciclico può perdere molto più del mercato, mentre un difensivo di solito perde meno. Anche i difensivi, però, possono scendere.', v: { k: 'bars', d: [['Ciclico', -35], ['Mercato', -20], ['Difensivo', -10]], u: '%' } },
    { t: 'Sensibilità al ciclo', x: 'Ogni settore ha una diversa sensibilità all’economia: alimentari e utility in basso, auto e materie prime in alto. Il beta misura quanto un titolo tende a muoversi rispetto al mercato.', v: { k: 'scale', a: 'Difensivo', b: 'Ciclico', d: [['Utility', 15], ['Alimentari', 20], ['Banche', 70], ['Auto', 85]] } },
    { t: 'La rotazione settoriale', x: 'Secondo la teoria della rotazione, nelle diverse fasi del ciclo tendono a fare meglio settori diversi. È una tendenza storica, non una regola: riconoscere le fasi in tempo reale è difficile.', v: { k: 'steps', s: ['Ripresa', 'Espansione', 'Rallentamento', 'Recessione'] } },
    { t: 'Attenti alla concentrazione', x: 'Se metà del portafoglio è in un solo settore, una crisi di quel comparto pesa moltissimo. La Borsa italiana, per esempio, pesa molto su banche, energia e utility: diversificare tra settori riduce il rischio.', v: { k: 'pie', d: [['Banche', 50], ['Energia', 30], ['Altri settori', 20]] } },
  ],
  terms: [
    ['Settore', 'Gruppo di società che svolgono attività economiche simili, come energia o sanità.'],
    ['Titolo ciclico', 'Azione di un’azienda i cui utili seguono da vicino le fasi di crescita e crisi dell’economia.'],
    ['Titolo difensivo', 'Azione di un’azienda con domanda stabile, poco sensibile all’andamento dell’economia.'],
    ['Ciclo economico', 'Alternanza di fasi di espansione e di contrazione dell’attività economica.'],
    ['Rotazione settoriale', 'Spostamento degli investimenti tra comparti in base alla fase del ciclo.'],
    ['GICS', 'Standard internazionale che classifica le società quotate in 11 settori.'],
    ['Beta', 'Misura di quanto un titolo tende a muoversi rispetto al mercato nel suo complesso.'],
    ['Leva operativa', 'Effetto per cui, con molti costi fissi, piccole variazioni dei ricavi cambiano molto gli utili.'],
  ],
  tf: [
    ['Le aziende di beni di consumo di base, come alimentari e detersivi, sono considerate difensive.', true, 'Si continua a mangiare e a fare la spesa anche in recessione: la domanda resta abbastanza stabile, e con essa gli utili.'],
    ['I titoli difensivi non perdono mai valore durante una crisi di mercato.', false, 'Anche i difensivi possono scendere, a volte parecchio: tendono solo a perdere meno dei ciclici nelle fasi negative.'],
    ['Le case automobilistiche sono un esempio tipico di settore ciclico.', true, 'L’acquisto di un’auto si può rimandare: quando l’economia rallenta le vendite calano e gli utili ne risentono molto.'],
    ['Un titolo con beta 1,5 tende in media a muoversi più del mercato.', true, 'Con beta 1,5, a un movimento del mercato del 10% corrisponde in media un movimento del titolo di circa il 15%, in entrambe le direzioni.'],
    ['Avere tutte le azioni nello stesso settore equivale a essere ben diversificati.', false, 'Le società di uno stesso settore subiscono spesso gli stessi shock: diversificare tra settori diversi riduce il rischio complessivo.'],
    ['Le utility, come le società elettriche, sono di solito considerate un settore difensivo.', true, 'Luce e gas si consumano anche in recessione e molte attività sono regolate: gli utili sono relativamente stabili.'],
    ['La rotazione settoriale permette di sapere in anticipo e con certezza quale settore salirà.', false, 'È una tendenza storica legata al ciclo, ma le fasi sono difficili da riconoscere in tempo reale e i mercati spesso le anticipano.'],
    ['Le aziende con molti costi fissi vedono gli utili oscillare più dei ricavi.', true, 'È la leva operativa: se i ricavi calano del 10% ma i costi restano fermi, gli utili possono scendere molto di più.'],
    ['Il settore del lusso è tipicamente difensivo perché i suoi clienti sono benestanti.', false, 'Il lusso è classificato tra i consumi discrezionali: è una spesa rinviabile, sensibile alla fiducia e al clima economico.'],
    ['Un titolo ciclico è sempre un investimento peggiore di uno difensivo.', false, 'Dipende dal prezzo pagato e dalla fase del ciclo: i ciclici soffrono nelle recessioni ma possono correre molto nelle riprese.'],
  ],
  mcq: [
    { q: 'Quale di questi settori è considerato tipicamente difensivo?', a: 'Beni di consumo di base', w: ['Automobili', 'Materiali da costruzione', 'Viaggi e turismo'], e: 'Alimentari e prodotti per la casa hanno una domanda stabile: si comprano anche quando l’economia rallenta.' },
    { q: 'Quale settore rischia di soffrire di più all’inizio di una recessione?', a: 'Beni di consumo discrezionali', w: ['Farmaceutico', 'Utility elettriche', 'Alimentare'], e: 'Viaggi, auto, abbigliamento di fascia alta: sono spese che si rinviano subito quando reddito o fiducia calano.' },
    { q: 'Il mercato scende del 10%. Di quanto tende a scendere, in media, un titolo con beta 0,6?', a: 'Circa il 6%', w: ['Circa il 16%', 'Circa il 10%', 'Circa lo 0,6%'], e: 'Beta 0,6 × 10% = 6%. È una tendenza media: il singolo episodio può andare diversamente.' },
    { q: 'Perché un’acciaieria tende ad avere utili molto variabili?', a: 'Domanda ciclica e alti costi fissi', w: ['Prezzi di vendita fissati per legge', 'Ricavi del tutto stabili', 'Assenza di costi fissi'], e: 'La domanda di acciaio segue l’economia e gli impianti costano anche quando lavorano poco: la leva operativa amplifica utili e perdite.' },
    { q: 'Laura ha il 70% delle sue azioni in titoli bancari. Qual è il rischio principale?', a: 'Concentrazione su un solo settore', w: ['Eccesso di diversificazione', 'Mancanza di titoli ciclici', 'Assenza di rischio di mercato'], e: 'Se il settore bancario attraversa una crisi, gran parte del portafoglio ne risente insieme: è un rischio di concentrazione.' },
    { q: 'Cosa sostiene la teoria della rotazione settoriale?', a: 'Settori diversi fanno meglio in fasi diverse', w: ['Tutti i settori salgono sempre insieme', 'I difensivi battono sempre i ciclici', 'I settori si alternano ogni mese'], e: 'Secondo la teoria, la forza relativa dei settori cambia con il ciclo economico. È una tendenza, non un orologio preciso.' },
    { q: 'Un portafoglio ha il 50% in un titolo ciclico che rende +12% e il 50% in un difensivo che rende +4%. Qual è il rendimento complessivo?', a: '+8%', w: ['+16%', '+12%', '+6%'], e: 'Media ponderata: 0,5 × 12% + 0,5 × 4% = 6% + 2% = 8%.' },
    { q: 'Quale affermazione sui titoli difensivi è corretta?', a: 'In una crisi tendono a scendere meno', w: ['In una crisi salgono sempre', 'Non risentono mai dei tassi', 'Rendono sempre più dei ciclici'], e: 'I difensivi hanno utili più stabili e tendono a perdere meno, ma non sono immuni dai cali né da fattori come i tassi d’interesse.' },
  ],
  fill: [
    { s: 'Un’azienda i cui utili seguono da vicino l’andamento dell’economia si definisce ___.', a: 'ciclica', w: ['difensiva', 'regolata', 'sottovalutata'] },
    { s: 'Le società elettriche e del gas appartengono al settore delle ___.', a: 'utility', w: ['materie prime', 'telecomunicazioni', 'costruzioni'] },
    { s: 'Un titolo con ___ maggiore di 1 tende a muoversi più del mercato.', a: 'beta', w: ['payout', 'flottante', 'dividendo'] },
    { s: 'Spostare gli investimenti tra settori seguendo il ciclo economico si chiama rotazione ___.', a: 'settoriale', w: ['valutaria', 'temporale', 'fiscale'] },
    { s: 'Con molti costi fissi di produzione, un piccolo calo dei ricavi pesa molto sugli utili: è la leva ___.', a: 'operativa', w: ['commerciale', 'fiscale', 'monetaria'] },
  ],
  order: [
    { q: 'Ordina dal titolo meno sensibile al mercato al più sensibile', i: ['Alimentare con beta 0,5', 'Utility con beta 0,7', 'Banca con beta 1,2', 'Auto con beta 1,5'], e: 'Più alto è il beta, più il titolo tende ad amplificare i movimenti del mercato: i ciclici hanno spesso beta superiori a 1.' },
    { q: 'Metti in ordine le fasi del ciclo economico, partendo dalla ripresa', i: ['Ripresa', 'Espansione', 'Rallentamento', 'Recessione'], e: 'Dopo la ripresa l’economia si espande, poi rallenta e può entrare in recessione, da cui riparte un nuovo ciclo.' },
  ],
  cat: [
    { q: 'Settore ciclico o difensivo?', g: [['Ciclico', ['Automobili', 'Viaggi e hotel', 'Macchinari industriali', 'Lusso']], ['Difensivo', ['Alimentari', 'Farmaceutici', 'Distribuzione elettrica', 'Prodotti per la casa']]] },
    { q: 'Spesa che si rinvia in una crisi o che si fa comunque?', g: [['Si rinvia', ['Auto nuova', 'Vacanza all’estero', 'Cucina nuova']], ['Si fa comunque', ['Bolletta della luce', 'Spesa alimentare', 'Medicinali']]] },
  ],
  scen: [
    { s: 'Davide, 36 anni, dopo un anno ottimo ha tutto il portafoglio in titoli ciclici: auto, lusso e costruzioni. Ora legge diverse previsioni di rallentamento economico.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Aggiungere settori diversi, senza inseguire le previsioni', ok: true, f: 'Ottimo: il problema è la concentrazione, non il tempismo. Un portafoglio bilanciato tra settori regge meglio qualunque scenario.' },
      { t: 'Vendere tutto e comprare solo difensivi, perché la recessione è certa', ok: false, f: 'Le previsioni sono incerte: passare da un estremo all’altro sostituisce un rischio di concentrazione con un altro.' },
      { t: 'Non cambiare nulla: un anno ottimo dimostra che i ciclici sono i migliori', ok: false, f: 'Un buon anno non elimina il rischio: proprio i ciclici possono perdere molto quando l’economia rallenta.' },
    ] },
    { s: 'Francesca, 60 anni, è vicina alla pensione e teme le oscillazioni. Chiede al consulente di mettere tutti i suoi risparmi in «azioni difensive, che tanto non scendono».', q: 'Qual è la risposta più corretta?', o: [
      { t: 'Anche i difensivi scendono: meglio valutare una quota minore in azioni', ok: true, f: 'Giusto: nessuna azione è al riparo dai cali. Per chi teme le oscillazioni conta soprattutto quanto patrimonio è investito in azioni.' },
      { t: 'Va bene: i difensivi proteggono il capitale come un conto deposito', ok: false, f: 'Falso: i difensivi sono comunque azioni e il loro valore può calare, anche in modo significativo.' },
      { t: 'Meglio i ciclici, che dopo i cali risalgono più in fretta', ok: false, f: 'Per chi teme le oscillazioni i ciclici sono la scelta meno adatta: amplificano i movimenti del mercato.' },
    ] },
    { s: 'Nicola, 29 anni, nota che un’acciaieria quotata ha un rapporto prezzo/utili molto basso proprio mentre l’economia è al massimo e gli utili sono record. Pensa che sia un affare evidente.', q: 'Come ragiona correttamente?', o: [
      { t: 'Considera che gli utili sono al picco del ciclo e potrebbero calare molto', ok: true, f: 'Esatto: nei ciclici un prezzo/utili basso al culmine del ciclo può ingannare, perché gli utili record difficilmente durano.' },
      { t: 'Compra subito: un prezzo/utili basso significa sempre titolo a sconto', ok: false, f: 'Non sempre: se gli utili sono gonfiati dalla fase economica, il multiplo basso può riflettere un calo atteso.' },
      { t: 'Ignora il ciclo: per un’acciaieria conta solo il dividendo', ok: false, f: 'Il ciclo è il fattore principale per un’acciaieria: guida ricavi, utili e quindi anche i dividendi.' },
    ] },
    { s: 'Irene, 42 anni, ha un portafoglio composto per il 50% da banche, il 30% da energia e il 20% da utility, perché «così rispecchia la Borsa italiana». Vuole ridurre il rischio.', q: 'Cosa le conviene fare?', o: [
      { t: 'Ampliare l’esposizione ad altri settori e ad altri mercati', ok: true, f: 'Corretto: il listino italiano è concentrato in pochi comparti. Aggiungere settori e Paesi diversi riduce la dipendenza da pochi rischi.' },
      { t: 'Aumentare le banche, che sono il settore più importante in Italia', ok: false, f: 'Aumenterebbe ancora la concentrazione: il peso di un settore nel listino non lo rende meno rischioso.' },
      { t: 'Tenere tutto: tre settori sono già una diversificazione sufficiente', ok: false, f: 'Tre comparti, per giunta legati tra loro da tassi ed energia, lasciano scoperti molti altri settori dell’economia.' },
    ] },
  ],
  tip: 'Guarda il tuo portafoglio per settori, non solo per titoli: dieci azioni dello stesso comparto possono comportarsi come una sola quando arriva la crisi.',
});
