FQC(26, {
  intro: 'Crescita veloce o prezzo a sconto? Scopri i due grandi stili di investimento azionario, come si riconoscono e quali rischi nasconde ciascuno.',
  cards: [
    { t: 'Due stili di investimento', x: 'Lo stile growth punta su aziende che crescono più della media e per questo costano care. Lo stile value cerca aziende che il mercato prezza poco rispetto a utili, patrimonio o dividendi.', v: { k: 'vs', a: ['Growth', 'Crescita veloce, multipli alti'], b: ['Value', 'Prezzo basso rispetto ai fondamentali'] } },
    { t: 'Il rapporto prezzo/utili', x: 'Il P/E dice quanti euro paghi per ogni euro di utile annuo. I titoli growth hanno spesso P/E alti perché il mercato si aspetta utili futuri molto maggiori; i value hanno P/E più bassi.', v: { k: 'formula', f: 'P/E = prezzo ÷ utile per azione', n: 'Es.: 40 € ÷ 2 € = 20' } },
    { t: 'Multipli a confronto', x: 'Esempio illustrativo: il titolo growth costa 35 volte gli utili, quello value 10 volte. Non vuol dire che uno sia caro e l’altro conveniente: dipende da quanto cresceranno davvero gli utili.', v: { k: 'bars', d: [['P/E titolo growth', 35], ['P/E del mercato', 18], ['P/E titolo value', 10]] } },
    { t: 'Uno spettro, non due scatole', x: 'Tra value e growth c’è uno spettro: i titoli a metà strada si dicono blend. Un’azienda può anche cambiare stile nel tempo, quando la crescita rallenta e matura.', v: { k: 'scale', a: 'Value', b: 'Growth', d: [['Banca tradizionale', 15], ['Utility', 25], ['Blend', 50], ['Software in forte crescita', 88]] } },
    { t: 'Rischi diversi', x: 'Il rischio del value è la trappola: il titolo è economico perché l’azienda è in declino. Il rischio del growth è pagare troppo: basta una crescita inferiore alle attese per un forte calo.', v: { k: 'icons', d: [['🪤', 'Trappola del valore'], ['🎈', 'Aspettative eccessive']] } },
    { t: 'Stili che si alternano', x: 'Storicamente growth e value si sono alternati alla guida, anche per molti anni di fila. Chi investe in un indice ampio possiede già entrambi gli stili, come in questo esempio bilanciato.', v: { k: 'pie', d: [['Growth', 50], ['Value', 50]] } },
  ],
  terms: [
    ['Titolo growth', 'Azione di un’azienda con crescita attesa di ricavi e utili superiore alla media.'],
    ['Titolo value', 'Azione prezzata poco rispetto a utili, patrimonio o dividendi dell’azienda.'],
    ['P/E', 'Rapporto tra prezzo e utile per azione: quante volte paghi gli utili annui.'],
    ['PEG', 'Rapporto tra P/E e crescita annua attesa degli utili, utile per confrontare titoli in crescita.'],
    ['Value trap', 'Titolo che sembra economico ma resta tale perché l’azienda è in declino.'],
    ['Blend', 'Stile o titolo a metà strada, con caratteristiche sia di crescita sia di valore.'],
    ['Margine di sicurezza', 'Differenza tra valore stimato di un’azienda e prezzo pagato, che protegge dagli errori.'],
    ['Indice di stile', 'Indice che seleziona dal mercato solo i titoli di crescita oppure solo quelli di valore.'],
  ],
  tf: [
    ['I titoli growth hanno in genere un rapporto prezzo/utili più alto dei titoli value.', true, 'Il mercato paga di più oggi perché si aspetta utili molto maggiori domani: per questo i multipli sono più elevati.'],
    ['Un titolo con P/E basso è sempre un affare.', false, 'Può essere una value trap: il prezzo è basso perché il mercato prevede utili in calo o problemi seri per l’azienda.'],
    ['Le aziende growth tendono a distribuire dividendi bassi o nulli.', true, 'Preferiscono reinvestire gli utili per crescere: il ritorno per il socio arriva soprattutto, se arriva, dall’aumento del prezzo.'],
    ['Lo stile growth ha battuto lo stile value in ogni decennio della storia.', false, 'Gli stili si sono alternati: ci sono stati lunghi periodi a favore del value e altri, anche lunghi, a favore del growth.'],
    ['Se gli utili di un titolo growth crescono meno del previsto, il prezzo può scendere molto.', true, 'Il prezzo incorpora attese elevate: anche una crescita buona ma inferiore alle stime può causare forti ribassi.'],
    ['Un titolo growth può diventare value con il passare degli anni.', true, 'Quando un’azienda matura, la crescita rallenta e i multipli scendono: molte ex aziende di crescita oggi sono considerate value.'],
    ['I titoli value sono quelli con il prezzo per azione più basso, per esempio sotto i 10 €.', false, 'Value non riguarda il prezzo unitario ma il rapporto tra prezzo e fondamentali come utili, patrimonio netto o dividendi.'],
    ['Con un P/E di 25, paghi 25 € per ogni euro di utile annuo per azione.', true, 'P/E = prezzo ÷ utile per azione: se l’utile è 2 €, il prezzo è 50 €. Il dato va sempre letto insieme alla crescita attesa.'],
    ['I titoli growth sono in genere poco sensibili all’aumento dei tassi d’interesse.', false, 'Sono spesso più sensibili: il loro valore dipende da utili lontani nel tempo, che oggi valgono meno quando i tassi salgono.'],
    ['Un PEG pari a 1 indica un P/E in linea con il tasso di crescita atteso degli utili.', true, 'Es.: P/E 20 e crescita attesa del 20% annuo danno PEG 1. È un indicatore semplice, ma basato su stime incerte.'],
  ],
  mcq: [
    { q: 'Un titolo quota 60 € e ha un utile per azione di 3 €. Qual è il suo P/E?', a: '20', w: ['5', '180', '63'], e: '60 ÷ 3 = 20: il mercato paga 20 volte l’utile annuo.' },
    { q: 'Quale caratteristica è tipica di un titolo value?', a: 'Multipli bassi rispetto ai fondamentali', w: ['Ricavi in crescita molto rapida', 'Nessun utile e grandi promesse', 'Prezzo unitario sotto 1 €'], e: 'Il value si riconosce dal prezzo contenuto rispetto a utili, patrimonio o dividendi, non dal prezzo della singola azione.' },
    { q: 'Alfa ha P/E 30 e una crescita attesa degli utili del 15% annuo. Qual è il PEG?', a: '2', w: ['0,5', '45', '15'], e: 'PEG = P/E ÷ crescita % = 30 ÷ 15 = 2. Più è alto, più stai pagando la crescita.' },
    { q: 'Che cos’è una value trap?', a: 'Un titolo economico perché l’azienda è in declino', w: ['Un titolo growth che paga molti dividendi', 'Un indice che seleziona titoli value', 'Un ordine che scatta a prezzo basso'], e: 'Il prezzo basso può riflettere problemi reali: senza un miglioramento, il titolo resta a sconto o scende ancora.' },
    { q: 'Perché i titoli growth sono spesso più sensibili ai tassi d’interesse?', a: 'Il loro valore dipende da utili lontani', w: ['Pagano dividendi molto alti', 'Hanno sempre molti debiti', 'Sono quotati solo all’estero'], e: 'Più alti sono i tassi, meno valgono oggi i guadagni attesi tra molti anni: i titoli growth ne risentono di più.' },
    { q: 'Un’azienda reinveste tutti gli utili, cresce del 25% l’anno e ha P/E 50. Come la classificheresti?', a: 'Growth', w: ['Value', 'Difensiva', 'Ad alto dividendo'], e: 'Crescita elevata, multiplo alto e nessun dividendo sono i tratti tipici dello stile growth.' },
    { q: 'Con un P/E pari a 20, qual è il rendimento degli utili (utile ÷ prezzo)?', a: '5%', w: ['20%', '2%', '0,5%'], e: 'È l’inverso del P/E: 1 ÷ 20 = 0,05, cioè il 5%. Aiuta a capire quanto un titolo «rende» in utili.' },
    { q: 'Cosa mostra la storia degli stili growth e value?', a: 'Si sono alternati per lunghi periodi', w: ['Il value ha sempre vinto', 'Il growth ha sempre vinto', 'Hanno reso sempre uguale'], e: 'Ci sono stati anni, anche decenni, favorevoli all’uno o all’altro stile: prevedere quale prevarrà è molto difficile.' },
  ],
  fill: [
    { s: 'Le azioni di aziende che crescono più della media si chiamano titoli ___.', a: 'growth', w: ['value', 'difensivi', 'ciclici'] },
    { s: 'Il rapporto tra prezzo e utile per azione si indica con la sigla ___.', a: 'P/E', w: ['PIL', 'TER', 'IPO'] },
    { s: 'Un titolo che sembra economico perché l’azienda è in declino è una ___ del valore.', a: 'trappola', w: ['promessa', 'riserva', 'garanzia'] },
    { s: 'La differenza tra valore stimato e prezzo pagato si chiama margine di ___.', a: 'sicurezza', w: ['interesse', 'liquidità', 'garanzia'] },
    { s: 'I titoli con caratteristiche sia growth sia value si definiscono ___.', a: 'blend', w: ['penny stock', 'blue chip', 'small cap'] },
  ],
  order: [
    { q: 'Ordina dal P/E più basso al più alto', i: ['Prezzo 20 €, utile 4 €', 'Prezzo 30 €, utile 3 €', 'Prezzo 45 €, utile 3 €', 'Prezzo 80 €, utile 2 €'], e: 'I P/E sono 5, 10, 15 e 40: un prezzo alto non implica un P/E alto, conta il rapporto con l’utile.' },
    { q: 'Ordina dal profilo più value al più growth', i: ['P/E 8, crescita 1%', 'P/E 14, crescita 5%', 'P/E 25, crescita 12%', 'P/E 60, crescita 30%'], e: 'Passando dal value al growth salgono insieme multipli e crescita attesa: il mercato paga di più la crescita più rapida.' },
  ],
  cat: [
    { q: 'Tratto tipico growth o value?', g: [['Growth', ['P/E elevato', 'Utili reinvestiti', 'Ricavi in forte crescita', 'Dividendo assente']], ['Value', ['P/E contenuto', 'Dividendo generoso', 'Azienda matura', 'Prezzo sotto il patrimonio netto']]] },
    { q: 'Rischio tipico di quale stile?', g: [['Growth', ['Pagare troppo le attese', 'Crollo se la crescita delude', 'Forte sensibilità ai tassi']], ['Value', ['Azienda in declino strutturale', 'Titolo a sconto per anni', 'Taglio del dividendo']]] },
  ],
  scen: [
    { s: 'Simone, 25 anni, vuole investire solo in titoli tecnologici growth perché «il futuro è lì» e sono saliti molto negli ultimi anni. Molti hanno P/E sopra 80.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che il prezzo sconta già molta crescita: meglio diversificare', ok: true, f: 'Giusto: con multipli così alti basta una delusione per forti cali. Diversificare evita di dipendere da un solo scenario.' },
      { t: 'Che i rialzi degli ultimi anni garantiscono quelli futuri', ok: false, f: 'Le performance passate non si ripetono per forza: anzi, possono aver alzato troppo le aspettative.' },
      { t: 'Che un P/E alto è sempre il segno di un’azienda migliore', ok: false, f: 'Il P/E alto indica attese alte, non qualità garantita: se le attese non si realizzano, il prezzo si adegua.' },
    ] },
    { s: 'Paola, 52 anni, trova Omega Spa con P/E 5 e dividend yield del 10%. Leggendo meglio scopre che i ricavi calano da cinque anni e il debito cresce.', q: 'Come si comporta?', o: [
      { t: 'Sospetta una trappola del valore e approfondisce prima di decidere', ok: true, f: 'Ottimo: ricavi in calo e debito in crescita spiegano il prezzo basso. Un titolo può essere economico per ottime ragioni.' },
      { t: 'Compra subito: P/E 5 e 10% di dividendo sono un affare sicuro', ok: false, f: 'Il multiplo basso e il dividendo alto potrebbero non durare: con utili in calo il dividendo rischia il taglio.' },
      { t: 'Compra perché il debito non incide sul valore delle azioni', ok: false, f: 'Il debito incide eccome: più debiti significano più rischi per gli azionisti, che vengono pagati per ultimi.' },
    ] },
    { s: 'Andrea, 40 anni, ha un ETF sull’azionario globale. Legge che nell’ultimo secolo il value ha reso di più e pensa di vendere tutto per passare a un ETF solo value.', q: 'Qual è la scelta più ragionevole?', o: [
      { t: 'Mantenere entrambi gli stili, al massimo con una leggera preferenza', ok: true, f: 'Corretto: gli stili si alternano anche per decenni. Una scelta estrema basata sulla storia può costare cara se il ciclo non si ripete.' },
      { t: 'Passare tutto al value: la storia dimostra che vincerà sempre', ok: false, f: 'Il passato non garantisce il futuro: ci sono stati lunghi periodi in cui il value ha reso meno del growth.' },
      { t: 'Passare tutto al growth, che negli ultimi anni è andato meglio', ok: false, f: 'Anche questa è una scommessa estrema su un solo stile, basata sulle performance recenti.' },
    ] },
    { s: 'Beatrice, 33 anni, confronta due titoli: Alfa con P/E 40 e utili attesi in crescita del 40% annuo, Beta con P/E 20 e crescita attesa del 5%. Pensa che Beta sia più economica.', q: 'Come ragiona correttamente?', o: [
      { t: 'Guarda anche la crescita: PEG 1 per Alfa e 4 per Beta, con stime incerte', ok: true, f: 'Esatto: rapportato alla crescita, Alfa costa meno. Però una crescita del 40% è difficile da mantenere: va verificata con prudenza.' },
      { t: 'Sceglie Beta: un P/E più basso indica sempre il titolo più conveniente', ok: false, f: 'Il P/E da solo ignora la crescita: un multiplo basso con utili quasi fermi può non essere conveniente.' },
      { t: 'Sceglie Alfa: le stime di crescita degli analisti sono sempre affidabili', ok: false, f: 'Le stime di crescita sono spesso sbagliate, soprattutto quando sono molto alte: il PEG è solo un punto di partenza.' },
    ] },
  ],
  tip: 'Non chiederti solo se un titolo è growth o value: chiediti quanto stai pagando per ciò che l’azienda guadagna oggi e per ciò che promette domani.',
});
