FQC(27, {
  intro: 'Split, aumenti di capitale e buyback cambiano il numero di azioni: scopri quando cambia anche il valore e quando è solo aritmetica.',
  cards: [
    { t: 'Lo split', x: 'Con un frazionamento ogni azione diventa più azioni e il prezzo si divide nella stessa proporzione. Il tuo investimento e la tua quota della società restano identici.', v: { k: 'formula', f: 'Prezzo dopo lo split = prezzo ÷ rapporto di split', n: 'Es.: split 5 per 1 su un’azione da 100 € → 5 azioni da 20 €' } },
    { t: 'Split e raggruppamento', x: 'Il raggruppamento è l’operazione inversa: per esempio 10 azioni da 0,20 € diventano 1 azione da 2 €. Anche qui il valore totale non cambia: cambia solo come è tagliata la torta.', v: { k: 'vs', a: ['Split', 'Più azioni, prezzo unitario più basso'], b: ['Raggruppamento', 'Meno azioni, prezzo unitario più alto'] } },
    { t: 'L’aumento di capitale', x: 'La società emette nuove azioni per raccogliere denaro. Di norma i soci ricevono un diritto di opzione per sottoscriverle, spesso a sconto, così da poter mantenere la propria quota.', v: { k: 'steps', s: ['Delibera', 'Diritti ai soci', 'Sottoscrizione', 'Nuove azioni emesse'] } },
    { t: 'La diluizione', x: 'Se una società con 10 milioni di azioni ne emette altri 5 milioni, chi non sottoscrive vede la sua quota scendere di un terzo: i vecchi soci passano da tutto il capitale a circa due terzi.', v: { k: 'pie', d: [['Azioni esistenti', 67], ['Nuove azioni', 33]] } },
    { t: 'Il buyback', x: 'Con il buyback la società ricompra azioni proprie. Se le annulla, lo stesso utile si divide tra meno azioni: 50 milioni € di utile su 100 milioni di azioni danno 0,50 €; su 90 milioni circa 0,56 €.', v: { k: 'bars', d: [['Utile per azione prima', 0.5], ['Utile per azione dopo', 0.56]], u: '€' } },
    { t: 'Aritmetica o valore?', x: 'Split, raggruppamenti e aumenti gratuiti cambiano il numero di azioni ma non il valore dell’azienda. Un buyback crea valore per chi resta solo se le azioni vengono ricomprate sotto il loro valore.', v: { k: 'stat', n: '0 €', l: 'valore creato da uno split per l’azionista' } },
  ],
  terms: [
    ['Frazionamento', 'Operazione che divide ogni azione in più azioni, riducendo il prezzo nella stessa proporzione.'],
    ['Raggruppamento', 'Operazione che riunisce più azioni in una sola, aumentando il prezzo unitario.'],
    ['Aumento di capitale a pagamento', 'Emissione di nuove azioni che i sottoscrittori pagano, portando denaro alla società.'],
    ['Aumento di capitale gratuito', 'Passaggio di riserve a capitale con assegnazione di nuove azioni senza esborso.'],
    ['Diluizione', 'Calo della quota percentuale di un socio quando vengono emesse nuove azioni.'],
    ['Buyback', 'Riacquisto da parte di una società dei propri titoli sul mercato.'],
    ['Azioni proprie', 'Titoli che la società detiene in portafoglio, con diritto di voto sospeso.'],
    ['Utile per azione', 'Utile netto diviso il numero di azioni in circolazione, detto anche EPS.'],
  ],
  tf: [
    ['Dopo uno split 2 per 1, chi aveva 100 azioni da 40 € ne ha 200 da 20 €.', true, 'Il numero di azioni raddoppia e il prezzo si dimezza: il valore resta 4.000 € e la quota della società non cambia.'],
    ['Uno split rende l’azienda più ricca e aumenta il valore dell’investimento.', false, 'Lo split cambia solo il numero di «fette»: il valore totale dell’azienda e del tuo investimento resta lo stesso.'],
    ['Un raggruppamento 10 in 1 trasforma 1.000 azioni da 0,30 € in 100 azioni da 3 €.', true, 'Il numero di azioni si divide per 10 e il prezzo si moltiplica per 10: il valore resta di 300 €.'],
    ['In un aumento di capitale a pagamento il denaro raccolto entra nelle casse della società.', true, 'Chi sottoscrive paga le nuove azioni alla società, che usa i fondi per investire, ridurre i debiti o rafforzare il patrimonio.'],
    ['Se non partecipi a un aumento di capitale, la tua quota percentuale resta invariata.', false, 'Le azioni totali aumentano mentre le tue no: la tua percentuale scende. È la diluizione.'],
    ['Il buyback con annullamento riduce il numero di azioni in circolazione.', true, 'Le azioni ricomprate e annullate spariscono: ogni azione rimasta rappresenta una quota un po’ più grande dell’azienda.'],
    ['Un buyback crea sempre valore per gli azionisti, qualunque sia il prezzo pagato.', false, 'Se la società ricompra a prezzi superiori al valore delle azioni, distrugge valore: conta il prezzo, come per qualunque acquisto.'],
    ['Un aumento di capitale gratuito porta nuovo denaro nelle casse della società.', false, 'Non entra denaro: riserve già esistenti diventano capitale e i soci ricevono nuove azioni, con un effetto simile a uno split.'],
    ['In Italia, per acquistare azioni proprie, la società ha bisogno dell’autorizzazione dell’assemblea.', true, 'Il codice civile richiede una delibera assembleare che fissa numero massimo di azioni, durata dell’autorizzazione e limiti di prezzo.'],
    ['Un aumento di capitale è sempre una cattiva notizia per gli azionisti.', false, 'Dipende dall’uso dei fondi: finanziare progetti redditizi può creare valore; coprire perdite ricorrenti è più preoccupante.'],
  ],
  mcq: [
    { q: 'Possiedi 50 azioni da 120 €. La società annuncia uno split 3 per 1. Cosa avrai dopo?', a: '150 azioni da 40 €', w: ['50 azioni da 40 €', '150 azioni da 120 €', '17 azioni da 360 €'], e: 'Le azioni triplicano e il prezzo si divide per 3: 150 × 40 € = 6.000 €, esattamente come prima.' },
    { q: 'Alfa ha 50 milioni € di utile e 100 milioni di azioni. Ricompra e annulla 10 milioni di azioni. Quanto diventa l’utile per azione, a parità di utile?', a: 'Circa 0,56 €', w: ['0,50 €', '0,45 €', '5 €'], e: 'Prima: 50 ÷ 100 = 0,50 €. Dopo: 50 ÷ 90 ≈ 0,56 €. Lo stesso utile si divide tra meno azioni.' },
    { q: 'Hai 1.000 azioni di Beta, che ne ha 10 milioni. Beta emette 5 milioni di nuove azioni e tu non sottoscrivi. Qual è la tua nuova quota?', a: 'Circa 0,0067%', w: ['0,01%', '0,015%', '0,005%'], e: 'Prima: 1.000 ÷ 10 mln = 0,01%. Dopo: 1.000 ÷ 15 mln ≈ 0,0067%. La quota scende di un terzo: è la diluizione.' },
    { q: 'Perché una società può decidere un raggruppamento azionario?', a: 'Per alzare un prezzo unitario molto basso', w: ['Per raccogliere nuovo capitale', 'Per distribuire un dividendo', 'Per aumentare i propri utili'], e: 'Il raggruppamento riduce il numero di azioni e alza il prezzo unitario, spesso dopo forti cali. Non cambia il valore della società.' },
    { q: 'Quale di queste operazioni porta nuovo denaro nelle casse dell’azienda?', a: 'Aumento di capitale a pagamento', w: ['Frazionamento delle azioni', 'Aumento di capitale gratuito', 'Raggruppamento delle azioni'], e: 'Solo nell’aumento a pagamento qualcuno versa denaro alla società; le altre operazioni cambiano il numero di azioni senza nuovi fondi.' },
    { q: 'Un aumento in opzione offre 1 nuova azione ogni 4 possedute a 8 €, mentre il titolo vale 12 €. Qual è il prezzo teorico dopo l’aumento?', a: '11,20 €', w: ['12 €', '10 €', '8 €'], e: '(4 × 12 + 1 × 8) ÷ 5 = 56 ÷ 5 = 11,20 €. Lo sconto sulle nuove azioni abbassa il prezzo teorico, e il diritto di opzione lo compensa.' },
    { q: 'Quando un buyback crea davvero valore per chi resta socio?', a: 'Quando le azioni costano meno del loro valore', w: ['Sempre, a qualsiasi prezzo', 'Solo se finanziato con nuovi debiti', 'Quando il titolo è ai massimi storici'], e: 'Ricomprare sotto valore aumenta la ricchezza dei soci rimasti; ricomprare troppo caro la trasferisce a chi vende.' },
    { q: 'Cosa succede al diritto di voto delle azioni proprie detenute dalla società?', a: 'È sospeso', w: ['Vale doppio', 'Passa al presidente', 'Passa ai dipendenti'], e: 'Le azioni proprie non votano in assemblea; il loro diritto agli utili viene attribuito, in proporzione, alle altre azioni.' },
  ],
  fill: [
    { s: 'L’operazione che divide ogni azione in più azioni a prezzo più basso si chiama ___.', a: 'frazionamento', w: ['raggruppamento', 'buyback', 'collocamento'] },
    { s: 'Se vengono emesse nuove azioni e non le sottoscrivi, la tua quota subisce una ___.', a: 'diluizione', w: ['rivalutazione', 'capitalizzazione', 'conversione'] },
    { s: 'Il riacquisto di azioni proprie da parte della società si chiama ___.', a: 'buyback', w: ['split', 'payout', 'lock-up'] },
    { s: 'Con un aumento di capitale a ___ la società raccoglie nuovo denaro dagli investitori.', a: 'pagamento', w: ['titolo gratuito', 'raggruppamento', 'frazionamento'] },
    { s: 'Se la società annulla azioni proprie e l’utile resta uguale, l’utile per azione ___.', a: 'aumenta', w: ['diminuisce', 'resta uguale', 'si azzera'] },
  ],
  order: [
    { q: 'Metti in ordine le fasi di un aumento di capitale in opzione', i: ['Delibera dell’aumento', 'Assegnazione dei diritti ai soci', 'Periodo di sottoscrizione', 'Emissione delle nuove azioni'], e: 'L’aumento viene deliberato, i soci ricevono i diritti, durante il periodo d’offerta decidono se esercitarli, poi le nuove azioni vengono emesse.' },
    { q: 'Un titolo vale 60 €. Ordina il prezzo dopo ciascuna operazione, dal più basso al più alto', i: ['Split 6 per 1', 'Split 3 per 1', 'Split 2 per 1', 'Nessuna operazione', 'Raggruppamento 2 in 1'], e: 'I prezzi diventano 10, 20, 30, 60 e 120 €: lo split divide il prezzo, il raggruppamento lo moltiplica. Il valore totale resta uguale.' },
  ],
  cat: [
    { q: 'Porta nuovo denaro alla società oppure no?', g: [['Porta denaro', ['Aumento a pagamento', 'Aumento in opzione', 'Collocamento di nuove azioni']], ['Non porta denaro', ['Split', 'Raggruppamento', 'Aumento gratuito']]] },
    { q: 'Se non fai nulla, la tua quota percentuale scende oppure no?', g: [['Scende', ['Aumento che non sottoscrivi', 'Azioni emesse per un’acquisizione', 'Conversione di obbligazioni in azioni']], ['Non scende', ['Split', 'Raggruppamento', 'Aumento gratuito', 'Buyback con annullamento']]] },
  ],
  scen: [
    { s: 'Emma, 30 anni, legge che Alfa Spa farà uno split 10 per 1: il titolo passerà da 500 € a 50 €. Pensa che a 50 € sarà «finalmente conveniente» e vuole comprarne molte.', q: 'Qual è il ragionamento corretto?', o: [
      { t: 'Lo split non cambia il valore: deve decidere guardando l’azienda', ok: true, f: 'Esatto: a 50 € con dieci volte le azioni, Alfa vale quanto prima. La convenienza dipende da utili e prospettive, non dal prezzo unitario.' },
      { t: 'Comprare subito: a 50 € il titolo è dieci volte più economico', ok: false, f: 'È un’illusione: ogni nuova azione rappresenta un decimo della quota di prima. Il valore per euro investito non cambia.' },
      { t: 'Evitarlo: uno split è sempre segnale di difficoltà', ok: false, f: 'Non è così: spesso lo split segue forti rialzi del prezzo. Di per sé non è né positivo né negativo.' },
    ] },
    { s: 'Giovanni, 55 anni, ha 2.000 azioni di Beta Spa, che lancia un aumento di capitale in opzione a sconto. Leggendo il comunicato scopre che servirà a coprire perdite accumulate negli ultimi anni.', q: 'Cosa fa Giovanni?', o: [
      { t: 'Analizza il piano e la sua credibilità prima di decidere se sottoscrivere', ok: true, f: 'Ottimo: coprire perdite non è come finanziare la crescita. Serve capire se il piano rimetterà l’azienda in carreggiata.' },
      { t: 'Sottoscrive di sicuro: un prezzo a sconto è sempre un affare', ok: false, f: 'Lo sconto è compensato dal calo teorico del prezzo: da solo non rende conveniente l’operazione.' },
      { t: 'Vende tutto: un aumento di capitale significa fallimento imminente', ok: false, f: 'Non è automatico: molte aziende si rafforzano con un aumento. Va valutato caso per caso.' },
    ] },
    { s: 'Lucia, 41 anni, legge che Gamma Spa farà un grande buyback finanziato con nuovi debiti, mentre il titolo è ai massimi storici con un P/E molto alto. Pensa che il buyback sia sempre una buona notizia.', q: 'Come dovrebbe valutarlo?', o: [
      { t: 'Guardando prezzo e debito: ricomprare caro a debito può distruggere valore', ok: true, f: 'Giusto: un buyback crea valore se le azioni costano meno di quanto valgono. Comprare caro e indebitarsi aumenta il rischio.' },
      { t: 'Come un regalo sicuro: meno azioni significano sempre più valore per tutti', ok: false, f: 'L’utile per azione sale, ma se il prezzo pagato è eccessivo chi resta socio perde valore.' },
      { t: 'Come un’operazione irrilevante, perché non porta denaro alla società', ok: false, f: 'Non è irrilevante: esce cassa e, in questo caso, entra debito. Cambia la struttura finanziaria dell’azienda.' },
    ] },
    { s: 'Pietro, 63 anni, apre il dossier titoli: le sue azioni Delta sono passate da 8.000 a 800 e il prezzo da 0,40 € a 4 €. Teme di aver perso il 90% del suo investimento.', q: 'Cosa è successo?', o: [
      { t: 'Un raggruppamento 10 in 1: il valore è rimasto 3.200 €', ok: true, f: 'Corretto: 8.000 × 0,40 € = 3.200 € e 800 × 4 € = 3.200 €. Cambia il numero di azioni, non il valore della posizione.' },
      { t: 'Un errore della banca: va chiesto il ripristino delle azioni', ok: false, f: 'Nessun errore: il raggruppamento riduce le azioni e alza il prezzo nella stessa proporzione.' },
      { t: 'Una perdita del 90%: la società ha cancellato le sue azioni', ok: false, f: 'Il valore complessivo è invariato: la quota della società posseduta da Pietro è la stessa di prima.' },
    ] },
  ],
  tip: 'Davanti a split, aumenti o buyback chiediti due cose: entra o esce denaro dalla società? E la mia quota percentuale cambia? Il resto è solo aritmetica.',
});
