FQC(28, {
  intro: 'Da azionista non hai solo un titolo: hai diritti economici e di voto. Scopri l’assemblea, i tipi di azioni e come funziona il diritto di opzione.',
  cards: [
    { t: 'Due famiglie di diritti', x: 'Come socio hai diritti patrimoniali, cioè partecipare agli utili e a ciò che resta in caso di liquidazione, e diritti amministrativi, cioè partecipare alla vita della società, a partire dal voto.', v: { k: 'vs', a: ['Patrimoniali', 'Dividendo, quota di liquidazione, opzione'], b: ['Amministrativi', 'Voto, intervento, informazione'] } },
    { t: 'Ordinaria e straordinaria', x: 'L’assemblea ordinaria approva il bilancio, decide il dividendo e nomina amministratori e sindaci. Quella straordinaria decide su statuto, fusioni, scissioni e, salvo deleghe, aumenti di capitale.', v: { k: 'icons', d: [['📊', 'Ordinaria: bilancio e utili'], ['👥', 'Ordinaria: nomine'], ['📜', 'Straordinaria: statuto e fusioni']] } },
    { t: 'Come si vota', x: 'Nelle quotate italiane vota chi risulta socio alla record date, il settimo giorno di mercato aperto prima dell’assemblea. Puoi partecipare o delegare, anche al rappresentante designato dalla società.', v: { k: 'steps', s: ['Convocazione', 'Record date', 'Delega o partecipazione', 'Voto in assemblea'] } },
    { t: 'Un’azione, un voto', x: 'Con le azioni ordinarie il peso in assemblea è proporzionale alle azioni possedute. Chi ha la maggioranza decide le delibere ordinarie, ma le minoranze hanno tutele, come il voto di lista per il consiglio.', v: { k: 'pie', d: [['Socio di controllo', 51], ['Investitori istituzionali', 34], ['Piccoli azionisti', 15]] } },
    { t: 'Le azioni di risparmio', x: 'Le azioni di risparmio, emesse solo da società quotate, non danno voto in assemblea ma offrono privilegi economici, come un dividendo maggiorato rispetto alle ordinarie. Esempio illustrativo:', v: { k: 'bars', d: [['Dividendo ordinaria', 0.1], ['Dividendo risparmio', 0.13]], u: '€' } },
    { t: 'Il diritto di opzione', x: 'Quando la società emette nuove azioni, puoi sottoscriverle per primo in proporzione a quelle che hai. Puoi esercitare il diritto o venderlo in Borsa: lasciarlo scadere significa perderne il valore.', v: { k: 'formula', f: 'Nuove azioni = azioni possedute × rapporto di opzione', n: 'Es.: 1 nuova ogni 5 → con 500 azioni ne sottoscrivi 100' } },
  ],
  terms: [
    ['Azione ordinaria', 'Titolo che attribuisce tutti i diritti del socio, compreso il voto in ogni assemblea.'],
    ['Azione di risparmio', 'Titolo senza voto ma con privilegi economici, emesso solo da società quotate.'],
    ['Assemblea ordinaria', 'Riunione dei soci che approva il bilancio, decide sugli utili e nomina gli organi sociali.'],
    ['Assemblea straordinaria', 'Riunione dei soci che decide su statuto, fusioni, scissioni e operazioni sul capitale.'],
    ['Diritto di opzione', 'Diritto dei soci di sottoscrivere per primi le nuove azioni, in proporzione alla quota.'],
    ['Voto di lista', 'Sistema di nomina del consiglio che riserva almeno un posto alla lista di minoranza.'],
    ['Voto maggiorato', 'Più voti per azione riconosciuti dallo statuto a chi detiene i titoli a lungo.'],
    ['Rappresentante designato', 'Soggetto indicato dalla società a cui i soci possono affidare istruzioni di voto.'],
  ],
  tf: [
    ['Le azioni di risparmio danno diritto di voto nell’assemblea ordinaria.', false, 'Non votano nelle assemblee della società: in cambio offrono privilegi economici, come un dividendo maggiorato o la priorità nel rimborso.'],
    ['L’assemblea ordinaria approva il bilancio e decide la distribuzione degli utili.', true, 'È il momento in cui i soci votano sul bilancio dell’esercizio, sul dividendo e sulla nomina di amministratori e sindaci.'],
    ['Nelle quotate italiane può votare chi era socio alla record date, anche se ha venduto le azioni dopo.', true, 'La legittimazione al voto si fotografa alla record date: chi vende dopo può ancora votare, chi compra dopo no.'],
    ['Un piccolo azionista non ha alcun diritto reale: decide sempre e solo il socio di controllo.', false, 'Ha diritti economici pieni, può votare e fare domande, e nelle quotate le minoranze hanno tutele come il voto di lista per il consiglio.'],
    ['Se non eserciti né vendi i diritti di opzione, ne perdi il valore.', true, 'I diritti hanno un prezzo di mercato: lasciarli scadere significa rinunciarvi gratis e subire la diluizione senza compenso.'],
    ['Il diritto di opzione non può mai essere escluso o limitato.', false, 'Può essere escluso o limitato nei casi previsti dalla legge, per esempio con aumenti riservati motivati dall’interesse della società.'],
    ['Per votare in assemblea è obbligatorio partecipare di persona.', false, 'Puoi delegare un’altra persona o dare istruzioni al rappresentante designato dalla società, senza essere presente.'],
    ['Con il voto maggiorato chi detiene le azioni a lungo può avere più voti per azione.', true, 'Se lo statuto lo prevede, i soci di lungo periodo ottengono voti aggiuntivi: rafforza la stabilità ma riduce il peso relativo degli altri.'],
    ['Le modifiche dello statuto sono decise dall’assemblea straordinaria.', true, 'Statuto, fusioni, scissioni e operazioni straordinarie sul capitale spettano all’assemblea straordinaria, con maggioranze più elevate.'],
    ['Tutte le azioni di una società danno sempre gli stessi diritti, senza eccezioni.', false, 'Esistono categorie diverse, come ordinarie, di risparmio o privilegiate, e regole come il voto maggiorato: i diritti possono variare.'],
  ],
  mcq: [
    { q: 'Alfa Spa ha 100 milioni di azioni ordinarie e tu ne possiedi 2 milioni. Quale percentuale dei voti hai?', a: '2%', w: ['0,2%', '20%', '50%'], e: 'Con azioni ordinarie vale «un’azione, un voto»: 2 ÷ 100 = 2% dei voti.' },
    { q: 'Una società ha 80 milioni di azioni ordinarie e 20 milioni di risparmio. Hai 4 milioni di ordinarie. Che quota dei voti in assemblea ordinaria hai?', a: '5%', w: ['4%', '20%', '3,2%'], e: 'Le azioni di risparmio non votano, quindi i voti sono 80 milioni: 4 ÷ 80 = 5%. Sul capitale totale avresti invece il 4%.' },
    { q: 'Quale di queste decisioni spetta all’assemblea straordinaria?', a: 'Una fusione con un’altra società', w: ['L’approvazione del bilancio', 'La distribuzione del dividendo', 'La nomina dei sindaci'], e: 'Fusioni, scissioni e modifiche dello statuto sono materie straordinarie; bilancio, dividendo e nomine sono ordinarie.' },
    { q: 'Cosa offrono le azioni di risparmio in cambio dell’assenza del voto?', a: 'Privilegi economici', w: ['Un capitale garantito', 'Una cedola fissa annuale', 'La nomina dell’amministratore delegato'], e: 'Offrono vantaggi patrimoniali, come un dividendo maggiorato o la priorità nel rimborso, non garanzie sul capitale.' },
    { q: 'Un aumento in opzione assegna 1 nuova azione ogni 4 possedute. Hai 800 azioni. Quante nuove azioni puoi sottoscrivere?', a: '200', w: ['400', '3.200', '804'], e: '800 ÷ 4 = 200: il diritto di opzione è proporzionale alle azioni che già possiedi.' },
    { q: 'Hai ricevuto diritti di opzione ma non vuoi investire altro denaro. Qual è la scelta più razionale?', a: 'Vendere i diritti in Borsa', w: ['Lasciarli scadere', 'Chiederne il rimborso alla CONSOB', 'Convertirli in un dividendo'], e: 'Vendendo i diritti incassi il loro valore, che compensa almeno in parte la diluizione. Se li lasci scadere, quel valore va perso.' },
    { q: 'Compri azioni di Beta dopo la record date della prossima assemblea. Puoi votare in quella assemblea?', a: 'No, conta chi era socio alla record date', w: ['Sì, basta essere soci il giorno stesso', 'Sì, ma solo sulle delibere straordinarie', 'Sì, se possiedi più di mille azioni'], e: 'Nelle quotate italiane la legittimazione al voto si fissa alla record date, il settimo giorno di mercato aperto prima dell’assemblea.' },
    { q: 'A cosa serve il voto di lista nelle società quotate italiane?', a: 'A dare un posto in consiglio alle minoranze', w: ['A far votare solo i grandi soci', 'A eleggere i vertici della CONSOB', 'A stabilire il prezzo delle azioni'], e: 'Con il voto di lista almeno un amministratore viene dalla lista di minoranza più votata: una tutela per chi non controlla la società.' },
  ],
  fill: [
    { s: 'Le azioni che danno tutti i diritti, compreso il voto, si chiamano azioni ___.', a: 'ordinarie', w: ['di risparmio', 'proprie', 'di godimento'] },
    { s: 'Le azioni senza diritto di voto ma con privilegi economici si chiamano azioni di ___.', a: 'risparmio', w: ['sottoscrizione', 'garanzia', 'tesoreria'] },
    { s: 'Il bilancio annuale viene approvato dall’assemblea ___.', a: 'ordinaria', w: ['straordinaria', 'speciale', 'consultiva'] },
    { s: 'Il diritto di ___ permette ai soci di sottoscrivere per primi le nuove azioni.', a: 'opzione', w: ['recesso', 'riscatto', 'voto'] },
    { s: 'Puoi votare senza andare in assemblea dando istruzioni al rappresentante ___.', a: 'designato', w: ['commerciale', 'legale', 'fiscale'] },
  ],
  order: [
    { q: 'Metti in ordine i passi per votare all’assemblea di una società quotata', i: ['Avviso di convocazione', 'Record date', 'Invio della delega con istruzioni', 'Svolgimento dell’assemblea'], e: 'La società convoca l’assemblea; alla record date si fissa chi può votare; poi si inviano le deleghe e infine si vota.' },
    { q: 'Una società ha 100 milioni di azioni ordinarie. Ordina dalla quota di voti più bassa alla più alta', i: ['500.000 azioni', '2 milioni di azioni', '15 milioni di azioni', '51 milioni di azioni'], e: 'Sono lo 0,5%, il 2%, il 15% e il 51% dei voti: solo l’ultima quota dà da sola la maggioranza del capitale votante.' },
  ],
  cat: [
    { q: 'Diritto patrimoniale o amministrativo?', g: [['Patrimoniale', ['Dividendo', 'Quota di liquidazione', 'Diritto di opzione']], ['Amministrativo', ['Voto in assemblea', 'Domande prima dell’assemblea', 'Impugnazione delle delibere', 'Presentazione di liste']]] },
    { q: 'Materia dell’assemblea ordinaria o straordinaria?', g: [['Ordinaria', ['Approvazione del bilancio', 'Nomina degli amministratori', 'Destinazione dell’utile', 'Autorizzazione al buyback']], ['Straordinaria', ['Modifica dello statuto', 'Fusione', 'Scissione', 'Scioglimento della società']]] },
  ],
  scen: [
    { s: 'Alessia, 34 anni, riceve dalla banca la comunicazione che le sono stati assegnati diritti di opzione per l’aumento di capitale di Beta Spa. Non ha liquidità da investire e pensa di ignorare il messaggio.', q: 'Cosa le conviene fare?', o: [
      { t: 'Vendere i diritti in Borsa entro il periodo di negoziazione', ok: true, f: 'Giusto: i diritti hanno un valore. Venderli le permette di incassare qualcosa a fronte della diluizione che comunque subirà.' },
      { t: 'Ignorare il messaggio: i diritti non valgono nulla', ok: false, f: 'Lasciarli scadere significa perderne il valore e subire la diluizione senza alcun compenso.' },
      { t: 'Chiedere un prestito per sottoscrivere tutte le nuove azioni', ok: false, f: 'Indebitarsi per investire in un solo titolo aumenta molto il rischio: non è obbligata a sottoscrivere.' },
    ] },
    { s: 'Mario, 67 anni, non partecipa mai alle assemblee e gli interessano solo i dividendi. Della stessa società trova azioni ordinarie e azioni di risparmio, che pagano un dividendo un po’ più alto.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Privilegi economici, assenza di voto e liquidità spesso più bassa', ok: true, f: 'Corretto: le risparmio possono essere adatte a chi non vota, ma sono spesso meno scambiate e il dividendo resta legato agli utili.' },
      { t: 'Che le azioni di risparmio hanno il capitale garantito', ok: false, f: 'Falso: restano azioni, con rischio di perdita. Il privilegio riguarda dividendi e rimborso, non la garanzia del capitale.' },
      { t: 'Che le azioni di risparmio danno più voti delle ordinarie', ok: false, f: 'È il contrario: non danno diritto di voto nelle assemblee della società.' },
    ] },
    { s: 'Chiara, 45 anni, ha 300 azioni di Delta Spa. L’assemblea voterà una fusione che lei non condivide. Pensa che il suo voto non conti nulla e decide di non leggere neppure i documenti.', q: 'Qual è l’approccio migliore?', o: [
      { t: 'Leggere i documenti e votare tramite delega', ok: true, f: 'Ottimo: informarsi è il primo diritto del socio. I voti dei piccoli azionisti, sommati, possono pesare, e votare è semplice.' },
      { t: 'Non fare nulla: con poche azioni il suo voto è inutile', ok: false, f: 'Rinunciare al voto lascia decidere solo gli altri. Molte delibere straordinarie richiedono maggioranze qualificate.' },
      { t: 'Vendere subito tutto, senza capire i termini della fusione', ok: false, f: 'Decidere senza leggere i documenti è rischioso: la fusione potrebbe anche creare valore per i soci.' },
    ] },
    { s: 'Valeria, 50 anni, intende tenere a lungo le azioni di Zeta Spa. L’assemblea introduce nello statuto il voto maggiorato per gli azionisti di lungo periodo.', q: 'Cosa le conviene fare?', o: [
      { t: 'Informarsi su iscrizione all’elenco e periodo minimo di possesso', ok: true, f: 'Esatto: la maggiorazione non è automatica. Di norma serve chiedere l’iscrizione in un apposito elenco e detenere le azioni per un periodo minimo.' },
      { t: 'Aspettarsi voti doppi già dal giorno dopo, senza fare nulla', ok: false, f: 'Non è così: servono la richiesta e un periodo di detenzione continuativa previsto dallo statuto.' },
      { t: 'Vendere: il voto maggiorato cancella il suo diritto di voto', ok: false, f: 'Il voto maggiorato non toglie diritti: aggiunge voti a chi resta socio a lungo e rispetta le condizioni.' },
    ] },
  ],
  tip: 'Leggi l’avviso di convocazione delle assemblee delle società che possiedi: anche con poche azioni puoi votare tramite delega e far sentire la tua voce.',
});
