FQC(29, {
  intro: 'Colossi o piccole promesse? Scopri come si classificano le società per dimensione e cosa cambia tra small, mid e large cap in rischio e liquidità.',
  cards: [
    { t: 'Le classi di dimensione', x: 'Le quotate si classificano per capitalizzazione. Le soglie non sono ufficiali e variano tra fornitori di indici: una convenzione diffusa negli USA mette le small cap tra circa 300 milioni e 2 miliardi di dollari, le large oltre i 10 miliardi.', v: { k: 'steps', s: ['Micro cap', 'Small cap', 'Mid cap', 'Large cap', 'Mega cap'] } },
    { t: 'Gli indici italiani per dimensione', x: 'In Italia il FTSE MIB riunisce le 40 società principali; gli indici FTSE Italia Mid Cap e Small Cap seguono quelle medie e piccole; su Euronext Growth Milan sono quotate molte PMI ancora più piccole.', v: { k: 'icons', d: [['🏛️', 'FTSE MIB'], ['🏢', 'FTSE Italia Mid Cap'], ['🏠', 'FTSE Italia Small Cap'], ['🌱', 'Euronext Growth Milan']] } },
    { t: 'Dimensione e volatilità', x: 'In genere più un’azienda è piccola, più il suo titolo oscilla: ha meno clienti e mercati, un accesso al credito più difficile e meno investitori che la seguono.', v: { k: 'scale', a: 'Più stabile', b: 'Più volatile', d: [['Large cap', 30], ['Mid cap', 50], ['Small cap', 70], ['Micro cap', 90]] } },
    { t: 'Potenziale e rischio', x: 'Una piccola azienda può raddoppiare le vendite più facilmente di un colosso, ma anche fallire più facilmente. Le grandi sono più solide e diversificate, ma tendono a crescere più piano.', v: { k: 'vs', a: ['Small cap', 'Più potenziale di crescita, più rischio'], b: ['Large cap', 'Più stabilità, crescita più lenta'] } },
    { t: 'Il costo della liquidità', x: 'Le small cap si scambiano meno: lo spread tra prezzo denaro e lettera è spesso più ampio e vendere in fretta può costare caro. Esempio illustrativo di spread:', v: { k: 'bars', d: [['Large cap', 0.05], ['Small cap', 0.5], ['Micro cap', 2]], u: '%' } },
    { t: 'Il peso negli indici', x: 'Negli indici ponderati per capitalizzazione le large cap pesano molto più delle piccole. L’MSCI World, per esempio, include solo large e mid cap: per le small cap servono indici dedicati. Esempio indicativo:', v: { k: 'pie', d: [['Large cap', 70], ['Mid cap', 20], ['Small cap', 10]] } },
  ],
  terms: [
    ['Large cap', 'Società ad alta capitalizzazione, in genere affermata e con titolo molto scambiato.'],
    ['Mid cap', 'Società di media capitalizzazione, a metà strada tra le grandi e le piccole quotate.'],
    ['Small cap', 'Società a bassa capitalizzazione, con più potenziale di crescita ma anche più rischio.'],
    ['Micro cap', 'Quotata di dimensioni molto ridotte, spesso poco liquida e poco seguita.'],
    ['Blue chip', 'Titolo di una grande società solida e nota, tra i più scambiati della Borsa.'],
    ['Effetto dimensione', 'Tendenza storica, non costante, delle piccole società a rendere più delle grandi.'],
    ['Copertura degli analisti', 'Numero di analisti che studiano un titolo e ne pubblicano stime e giudizi.'],
    ['Segmento STAR', 'Parte di Euronext Milan per medie imprese con requisiti più alti di trasparenza.'],
  ],
  tf: [
    ['Le soglie tra small, mid e large cap sono fissate per legge e uguali in tutto il mondo.', false, 'Sono convenzioni: ogni fornitore di indici usa criteri propri, e le soglie cambiano tra mercati e nel tempo.'],
    ['In genere le small cap sono più volatili delle large cap.', true, 'Hanno attività meno diversificate, accesso al credito più difficile e meno scambi: il prezzo tende a oscillare di più.'],
    ['Le small cap rendono sempre più delle large cap nel lungo periodo.', false, 'Alcuni studi hanno trovato un premio storico per le piccole società, ma non è stato costante: per lunghi periodi le grandi hanno fatto meglio.'],
    ['Lo spread denaro-lettera è di solito più ampio sulle small cap che sulle large cap.', true, 'Con meno scambi ci sono meno compratori e venditori: chi compra e vende paga di più in termini di spread.'],
    ['Una small cap è sempre una società rischiosa e gestita male.', false, 'Piccola non vuol dire scadente: molte piccole aziende sono solide e leader di nicchia. Il rischio è maggiore in media, non in ogni caso.'],
    ['L’indice MSCI World comprende large e mid cap, ma non le small cap.', true, 'Copre le società grandi e medie dei Paesi sviluppati: per investire nelle piccole servono indici dedicati alle small cap.'],
    ['Una società quotata può passare da small cap a large cap nel corso degli anni.', true, 'Se cresce e il mercato la valuta di più, la sua capitalizzazione sale e cambia categoria; può accadere anche il contrario.'],
    ['Le large cap sono al riparo da forti ribassi grazie alle loro dimensioni.', false, 'Anche le grandi aziende possono perdere molto valore, nelle crisi o per problemi propri. La dimensione riduce il rischio, non lo azzera.'],
    ['Le small cap sono in media seguite da meno analisti rispetto alle large cap.', true, 'Meno analisti significa meno informazioni disponibili, ma anche più probabilità che il prezzo non rifletta ancora tutte le notizie.'],
    ['In un indice ponderato per capitalizzazione le small cap pesano più delle large cap.', false, 'È il contrario: le società più grandi hanno il peso maggiore e influenzano di più l’andamento dell’indice.'],
  ],
  mcq: [
    { q: 'Secondo una convenzione diffusa negli Stati Uniti, una società che capitalizza 5 miliardi di dollari è una…', a: 'Mid cap', w: ['Micro cap', 'Small cap', 'Mega cap'], e: 'Con soglie indicative di 2 e 10 miliardi di dollari, 5 miliardi rientrano nelle mid cap. Altri fornitori usano soglie diverse.' },
    { q: 'Alfa Spa ha 40 milioni di azioni che quotano 15 €. Quanto capitalizza?', a: '600 milioni €', w: ['55 milioni €', '6 miliardi €', '60 milioni €'], e: '15 € × 40 milioni = 600 milioni €: una small cap secondo le convenzioni internazionali più diffuse.' },
    { q: 'Quale caratteristica è più tipica delle small cap rispetto alle large cap?', a: 'Maggiore volatilità del prezzo', w: ['Spread più stretti', 'Più analisti che le seguono', 'Ricavi più diversificati'], e: 'Le piccole società hanno in media prezzi più oscillanti, spread più ampi e meno copertura da parte degli analisti.' },
    { q: 'Che cos’è l’effetto dimensione?', a: 'Un extra-rendimento storico delle piccole società', w: ['Un rendimento garantito delle small cap', 'Una tassa sulle grandi società', 'Un bonus fiscale per le PMI quotate'], e: 'Alcuni studi lo hanno osservato su lunghi periodi, ma non è costante né garantito: per anni può non manifestarsi.' },
    { q: 'Un titolo small cap scende del 30%. Di quanto deve risalire per tornare al prezzo iniziale?', a: 'Circa il 43%', w: ['30%', '15%', 'Circa il 23%'], e: 'Da 100 a 70 serve un +42,9% per tornare a 100 (30 ÷ 70). I cali profondi, frequenti nelle small cap, richiedono recuperi più che proporzionali.' },
    { q: 'Quale indice raccoglie le 40 principali società italiane per capitalizzazione e liquidità?', a: 'FTSE MIB', w: ['FTSE Italia Small Cap', 'FTSE Italia Mid Cap', 'FTSE Italia Growth'], e: 'Il FTSE MIB è il paniere delle principali società italiane; medie e piccole hanno indici dedicati.' },
    { q: 'Perché investire una grande somma in una micro cap può essere complicato?', a: 'I pochi scambi rendono difficile entrare e uscire', w: ['Le micro cap non si possono mai rivendere in Borsa', 'Il prezzo viene fissato ogni giorno dalla società', 'Gli acquisti sono vietati ai risparmiatori privati'], e: 'Con volumi ridotti, ordini consistenti possono spostare il prezzo: entrare o uscire costa di più e richiede tempo.' },
    { q: 'Paolo ha un ETF che replica l’MSCI World e valuta di aggiungere un ETF sulle small cap. Perché potrebbe farlo?', a: 'Perché il suo indice non include le small cap', w: ['Perché il suo indice contiene solo small cap', 'Perché le small cap sono meno rischiose', 'Perché il suo indice esclude le large cap'], e: 'L’MSCI World copre large e mid cap: le small cap richiedono uno strumento dedicato, con il loro maggiore rischio.' },
  ],
  fill: [
    { s: 'Le società a bassa capitalizzazione si chiamano ___ cap.', a: 'small', w: ['large', 'mega', 'blue'] },
    { s: 'I titoli di grandi società solide e molto scambiate sono detti ___ chip.', a: 'blue', w: ['red', 'green', 'gold'] },
    { s: 'Il paniere delle 40 principali società italiane quotate è il ___.', a: 'FTSE MIB', w: ['FTSE Italia Small Cap', 'Euronext Growth Milan', 'segmento STAR'] },
    { s: 'La tendenza storica, ma non costante, delle piccole società a rendere di più si chiama effetto ___.', a: 'dimensione', w: ['leva', 'stacco', 'gregge'] },
    { s: 'Le small cap hanno in genere uno spread denaro-lettera più ___ delle large cap.', a: 'ampio', w: ['stretto', 'stabile', 'regolato'] },
  ],
  order: [
    { q: 'Ordina le categorie dalla capitalizzazione più piccola alla più grande', i: ['Micro cap', 'Small cap', 'Mid cap', 'Large cap', 'Mega cap'], e: 'È la scala dimensionale usata per classificare le quotate; le soglie esatte variano tra fornitori di indici.' },
    { q: 'Ordina queste società dalla più piccola alla più grande per capitalizzazione', i: ['2 € × 50 milioni di azioni', '8 € × 100 milioni di azioni', '25 € × 200 milioni di azioni', '40 € × 1 miliardo di azioni'], e: 'Valgono 100 milioni, 800 milioni, 5 miliardi e 40 miliardi di euro: indicativamente, dalla micro alla large cap.' },
  ],
  cat: [
    { q: 'Caratteristica più tipica di small cap o di large cap?', g: [['Small cap', ['Spread più ampi', 'Pochi analisti', 'Maggiore volatilità', 'Rischio di fallimento più alto']], ['Large cap', ['Alta liquidità', 'Ricavi diversificati nel mondo', 'Peso elevato negli indici', 'Crescita più lenta']]] },
    { q: 'Indice o mercato di grandi società oppure di piccole e medie?', g: [['Grandi società', ['FTSE MIB', 'Euro Stoxx 50', 'S&P 500']], ['Piccole e medie', ['FTSE Italia Small Cap', 'FTSE Italia Mid Cap', 'Euronext Growth Milan', 'Segmento STAR']]] },
  ],
  scen: [
    { s: 'Riccardo, 28 anni, legge che in passato le piccole società hanno reso più delle grandi. Vuole mettere tutta la parte azionaria in tre micro cap di Euronext Growth Milan.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Limitare le small cap a una quota misurata e diversificata', ok: true, f: 'Giusto: il premio storico non è garantito e tre micro cap concentrano rischio e illiquidità. Una quota contenuta e diversificata è più prudente.' },
      { t: 'Procedere: il passato dimostra che le piccole vincono sempre', ok: false, f: 'L’effetto dimensione non è stato costante: per lunghi periodi le small cap hanno reso meno delle large.' },
      { t: 'Scegliere le micro cap più economiche, sotto 1 € per azione', ok: false, f: 'Il prezzo unitario non dice nulla sul valore: scegliere in base a questo aumenta solo il rischio.' },
    ] },
    { s: 'Sofia, 59 anni, andrà in pensione tra due anni e userà quei risparmi per ristrutturare casa. Vede che un fondo small cap ha reso il 35% nell’ultimo anno, uno large cap il 10%.', q: 'Come dovrebbe ragionare?', o: [
      { t: 'Considerare il breve orizzonte e la maggiore volatilità delle small cap', ok: true, f: 'Esatto: con soldi che servono tra due anni, un forte calo delle small cap potrebbe non avere il tempo di essere recuperato.' },
      { t: 'Spostare tutto sul fondo small cap: il +35% si ripeterà', ok: false, f: 'Le performance passate non si ripetono per forza, e su due anni le small cap possono anche perdere molto.' },
      { t: 'Scegliere il fondo con il rendimento più alto, l’orizzonte non conta', ok: false, f: 'L’orizzonte conta moltissimo: più è breve, meno rischio ci si può permettere.' },
    ] },
    { s: 'Lorenzo, 52 anni, possiede una micro cap che in una giornata con pochi scambi perde il 25%, senza notizie apparenti. Il titolo pesa il 3% del suo portafoglio.', q: 'Qual è la reazione più sensata?', o: [
      { t: 'Cercare comunicati e notizie, poi decidere in base alla sua analisi', ok: true, f: 'Bravo: nelle micro cap pochi ordini possono muovere molto il prezzo. Prima di agire conviene capire se è cambiato qualcosa nell’azienda.' },
      { t: 'Vendere subito tutto con un ordine al prezzo di mercato', ok: false, f: 'Con pochi scambi un ordine a mercato può essere eseguito a prezzi ancora peggiori: il panico costa caro sulle micro cap.' },
      { t: 'Comprare per altri 30.000 € per abbassare il prezzo medio', ok: false, f: 'Aumentare molto la posizione senza capire il motivo del calo concentra il rischio su un titolo poco liquido.' },
    ] },
    { s: 'Giada, 31 anni, è convinta che le grandi aziende «non possano fallire». Vuole investire tutti i risparmi in tre blue chip italiane molto note, tutte dello stesso settore.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che anche le large cap possono crollare e conviene diversificare', ok: true, f: 'Esatto: la dimensione riduce il rischio ma non lo elimina. Tre titoli dello stesso settore restano un portafoglio molto concentrato.' },
      { t: 'Che le blue chip sono garantite dallo Stato', ok: false, f: 'Nessuna azione è garantita dallo Stato: anche le grandi società possono perdere molto valore.' },
      { t: 'Che tre titoli grandi equivalgono a un indice completo', ok: false, f: 'Un indice contiene decine o centinaia di titoli di settori diversi: tre azioni non offrono la stessa diversificazione.' },
    ] },
  ],
  tip: 'Se aggiungi small cap al portafoglio, fallo con una quota misurata e diversificata: il loro potenziale arriva insieme a più volatilità e meno liquidità.',
});
