FQC(30, {
  intro: 'Il prezzo racconta solo metà della storia: scopri come calcolare il rendimento totale, perché reinvestire i dividendi conta e come confrontare i risultati.',
  cards: [
    { t: 'Prezzo più dividendi', x: 'Il rendimento di un’azione non è solo la variazione del prezzo: bisogna aggiungere i dividendi incassati. Guardare solo il grafico del prezzo sottostima quanto hai guadagnato.', v: { k: 'formula', f: 'Rendimento totale = (P finale − P iniziale + dividendi) ÷ P iniziale', n: 'Es.: (105 − 100 + 3) ÷ 100 = 8%' } },
    { t: 'Indice di prezzo o total return', x: 'Molti indici famosi, come il FTSE MIB nella versione più citata, sono indici di prezzo: allo stacco dei dividendi scendono. Le versioni total return reinvestono i dividendi e misurano il risultato completo.', v: { k: 'vs', a: ['Indice di prezzo', 'Solo la variazione delle quotazioni'], b: ['Indice total return', 'Quotazioni più dividendi reinvestiti'] } },
    { t: 'Il peso del reinvestimento', x: 'Esempio: 10.000 € per 30 anni. Con un rialzo del prezzo del 4% annuo diventano circa 32.400 €; aggiungendo un 3% annuo di dividendi reinvestiti, circa 76.100 €, prima di tasse e costi.', v: { k: 'bars', d: [['Solo prezzo, +4% annuo', 32434], ['Con dividendi reinvestiti, +7% annuo', 76123]], u: '€' } },
    { t: 'Il rendimento annualizzato', x: 'Per confrontare periodi diversi si usa il rendimento medio annuo composto (CAGR). Raddoppiare in 10 anni equivale a circa il 7,2% annuo, non al 10%, perché i guadagni si capitalizzano.', v: { k: 'stat', n: '7,2%', l: 'rendimento annuo composto che raddoppia il capitale in 10 anni' } },
    { t: 'Il ciclo del reinvestimento', x: 'Reinvestire i dividendi significa usarli per comprare altre azioni, che a loro volta genereranno dividendi. Gli ETF ad accumulazione lo fanno in automatico.', v: { k: 'steps', s: ['Incassi il dividendo', 'Compri nuove azioni', 'Ricevi più dividendi', 'Il capitale accelera'] } },
    { t: 'Dal lordo al netto', x: 'Il rendimento che conta è quello netto: tasse su dividendi e plusvalenze (di norma 26%), costi di gestione e di negoziazione e inflazione riducono ciò che resta davvero a te.', v: { k: 'icons', d: [['🧾', 'Tasse'], ['💸', 'Costi e commissioni'], ['🎈', 'Inflazione']] } },
  ],
  terms: [
    ['Rendimento totale', 'Guadagno complessivo di un investimento: variazione di prezzo più redditi incassati.'],
    ['Indice di prezzo', 'Indice che misura solo l’andamento delle quotazioni, senza considerare i dividendi.'],
    ['Indice total return', 'Indice che somma alle quotazioni i dividendi, ipotizzandone il reinvestimento.'],
    ['Net total return', 'Variante di un indice che reinveste i dividendi al netto delle ritenute fiscali.'],
    ['Reinvestimento dei dividendi', 'Uso dei proventi distribuiti per acquistare nuove quote dello stesso investimento.'],
    ['CAGR', 'Tasso di crescita medio annuo composto che porta dal valore iniziale a quello finale.'],
    ['ETF ad accumulazione', 'Fondo quotato che non distribuisce i proventi ma li reinveste automaticamente.'],
    ['Rendimento cumulato', 'Guadagno complessivo su tutto il periodo, senza ripartirlo per anno.'],
  ],
  tf: [
    ['Il rendimento totale di un’azione comprende sia la variazione del prezzo sia i dividendi.', true, 'Es.: compri a 50 €, dopo un anno vale 52 € e hai incassato 1,50 € di dividendo: (2 + 1,50) ÷ 50 = 7%.'],
    ['Il grafico del prezzo di un’azione mostra già tutto il guadagno dell’investitore.', false, 'Il grafico del prezzo ignora i dividendi: per i titoli che distribuiscono molto, sottostima anche di parecchio il risultato reale.'],
    ['Il FTSE MIB, nella sua versione più citata, è un indice di prezzo.', true, 'Non include i dividendi e allo stacco scende. Esistono versioni total return del FTSE MIB che li reinvestono.'],
    ['Il DAX tedesco, nella versione più citata, è calcolato reinvestendo i dividendi.', true, 'È un indice di performance: per questo confrontarlo direttamente con un indice di prezzo come il FTSE MIB è fuorviante.'],
    ['Un rendimento del 50% in 5 anni equivale a un rendimento del 10% all’anno.', false, 'Il rendimento annuo composto è circa l’8,4%: 1,084 elevato alla quinta fa circa 1,50. Dividere il cumulato per gli anni sovrastima la media.'],
    ['Reinvestire i dividendi sfrutta l’interesse composto e fa crescere più in fretta il capitale.', true, 'I dividendi reinvestiti comprano nuove azioni, che producono a loro volta dividendi: su orizzonti lunghi la differenza diventa molto grande.'],
    ['I dividendi contano poco nel rendimento delle azioni nel lungo periodo.', false, 'Storicamente i dividendi reinvestiti hanno rappresentato una parte rilevante del rendimento totale dei mercati azionari.'],
    ['Il rendimento totale può essere negativo anche se l’azione ha pagato un dividendo.', true, 'Se compri a 40 €, incassi 1 € e il titolo scende a 35 €, il rendimento totale è (−5 + 1) ÷ 40 = −10%.'],
    ['Confrontare la variazione di prezzo di un titolo con un indice total return è un confronto corretto.', false, 'Bisogna confrontare grandezze omogenee: prezzo con prezzo, oppure rendimento totale con rendimento totale.'],
    ['Per un residente in Italia, un ETF ad accumulazione rinvia la tassazione dei proventi alla vendita.', true, 'Non distribuendo i proventi, non genera tasse annuali sui dividendi incassati: le imposte si pagano sul guadagno quando vendi le quote.'],
  ],
  mcq: [
    { q: 'Compri un’azione a 100 €. Dopo un anno vale 105 € e hai incassato 3 € di dividendo. Qual è il rendimento totale?', a: '8%', w: ['5%', '3%', '2%'], e: '(105 − 100 + 3) ÷ 100 = 8%: 5% dal prezzo e 3% dal dividendo, prima di tasse e costi.' },
    { q: 'Compri a 40 €, incassi 1 € di dividendo e il titolo scende a 36 €. Qual è il rendimento totale?', a: '−7,5%', w: ['−10%', '+2,5%', '−12,5%'], e: '(36 − 40 + 1) ÷ 40 = −3 ÷ 40 = −7,5%. Il dividendo attenua la perdita ma non la cancella.' },
    { q: 'Un investimento passa da 10.000 € a 20.000 € in 10 anni. Qual è circa il rendimento medio annuo composto?', a: '7,2%', w: ['10%', '5%', '20%'], e: 'Serve il tasso che raddoppia il capitale in 10 anni: 1,072 elevato alla decima fa circa 2. Il 10% semplice sovrastima la media.' },
    { q: 'Che differenza c’è tra un indice di prezzo e uno total return?', a: 'Il secondo include i dividendi reinvestiti', w: ['Il secondo esclude le società estere', 'Il primo include le commissioni', 'Il primo si calcola una volta l’anno'], e: 'L’indice di prezzo misura solo le quotazioni; il total return aggiunge i dividendi come se fossero reinvestiti.' },
    { q: 'Laura confronta il +6% di prezzo del suo titolo con il +9% di un indice total return. Cosa dovrebbe fare prima di trarre conclusioni?', a: 'Aggiungere al suo dato i dividendi incassati', w: ['Concludere che ha reso il 3% in meno', 'Aggiungere le commissioni all’indice', 'Considerare i due dati già omogenei'], e: 'Il confronto va fatto tra grandezze omogenee: rendimento totale del titolo contro rendimento totale dell’indice.' },
    { q: 'Quale strumento reinveste automaticamente i dividendi dei titoli che contiene?', a: 'Un ETF ad accumulazione', w: ['Un ETF a distribuzione', 'Un conto corrente', 'Un BOT'], e: 'L’ETF ad accumulazione non distribuisce i proventi: li reinveste nel fondo, sfruttando l’interesse composto.' },
    { q: 'Un titolo rende ogni anno il 4% di prezzo e il 3% di dividendi, sempre reinvestiti. Dopo 30 anni, 10.000 € diventano circa…', a: '76.000 €', w: ['32.000 €', '31.000 €', '21.000 €'], e: 'Al 7% annuo composto 10.000 € diventano circa 76.000 €; con il solo 4% di prezzo, circa 32.400 €. Il reinvestimento fa la differenza.' },
    { q: 'Perché il rendimento netto è più basso del rendimento totale lordo?', a: 'Per tasse e costi', w: ['Per il reinvestimento dei dividendi', 'Per l’effetto dell’interesse composto', 'Per la crescita degli utili'], e: 'Ritenute sui dividendi, imposte sulle plusvalenze, commissioni e costi di gestione riducono ciò che resta all’investitore.' },
  ],
  fill: [
    { s: 'Il rendimento che somma variazione di prezzo e dividendi si chiama rendimento ___.', a: 'totale', w: ['cedolare', 'marginale', 'implicito'] },
    { s: 'Un indice che include i dividendi reinvestiti si chiama indice ___.', a: 'total return', w: ['di prezzo', 'di volatilità', 'settoriale'] },
    { s: 'Il tasso di crescita medio annuo composto si indica con la sigla ___.', a: 'CAGR', w: ['TER', 'EPS', 'IPO'] },
    { s: 'Un ETF ad ___ reinveste automaticamente i dividendi incassati.', a: 'accumulazione', w: ['distribuzione', 'emissione', 'esenzione'] },
    { s: 'Usare i dividendi per comprare altre azioni sfrutta l’interesse ___.', a: 'composto', w: ['semplice', 'legale', 'variabile'] },
  ],
  order: [
    { q: 'Ordina i passaggi per calcolare il rendimento totale di un anno', i: ['Prendi il prezzo finale', 'Sottrai il prezzo iniziale', 'Aggiungi i dividendi incassati', 'Dividi per il prezzo iniziale'], e: 'Rendimento totale = (prezzo finale − prezzo iniziale + dividendi) ÷ prezzo iniziale.' },
    { q: 'Prezzo iniziale 100 €. Ordina dal rendimento totale più basso al più alto', i: ['Prezzo 90 €, dividendo 2 €', 'Prezzo 100 €, dividendo 0 €', 'Prezzo 98 €, dividendo 5 €', 'Prezzo 104 €, dividendo 1 €', 'Prezzo 103 €, dividendo 4 €'], e: 'I rendimenti totali sono −8%, 0%, +3%, +5% e +7%: un dividendo alto può compensare un prezzo in calo, ma non sempre.' },
  ],
  cat: [
    { q: 'Fa crescere il rendimento netto o lo riduce?', g: [['Lo fa crescere', ['Aumento del prezzo', 'Dividendi incassati', 'Reinvestimento dei dividendi']], ['Lo riduce', ['Commissioni di negoziazione', 'Ritenuta sui dividendi', 'Costi annui di un fondo', 'Calo del prezzo']]] },
    { q: 'Indice di prezzo o indice con dividendi reinvestiti (versione più citata)?', g: [['Indice di prezzo', ['FTSE MIB', 'Euro Stoxx 50', 'S&P 500']], ['Con dividendi reinvestiti', ['DAX', 'FTSE MIB Total Return', 'MSCI World Net Total Return']]] },
  ],
  scen: [
    { s: 'Marco, 50 anni, ha da cinque anni un titolo che paga circa il 5% annuo di dividendi, sempre reinvestiti, ma il prezzo è salito solo del 2%. Un amico vanta un +25% di prezzo su un titolo senza dividendi.', q: 'Come dovrebbe confrontare i risultati?', o: [
      { t: 'Calcolare il rendimento totale di entrambi, dividendi compresi', ok: true, f: 'Giusto: con circa il 5% annuo reinvestito per cinque anni, il suo rendimento totale supera il 25%. Solo così il confronto è corretto.' },
      { t: 'Ammettere di aver sbagliato: +2% contro +25% non lascia dubbi', ok: false, f: 'Il confronto ignora i dividendi reinvestiti, che per il suo titolo sono la parte principale del rendimento.' },
      { t: 'Confrontare solo i dividendi: il titolo dell’amico ha reso zero', ok: false, f: 'Anche questo è parziale: il rendimento dell’amico arriva dal prezzo. Serve sommare entrambe le componenti.' },
    ] },
    { s: 'Elena, 30 anni, investe per il lungo periodo e non ha bisogno di entrate. Deve scegliere tra la versione a distribuzione e quella ad accumulazione dello stesso ETF, sapendo che tenderebbe a spendere i dividendi.', q: 'Quale scelta è più coerente con il suo obiettivo?', o: [
      { t: 'La versione ad accumulazione, che reinveste in automatico', ok: true, f: 'Ottimo: reinvestire sempre è ciò che le serve, e l’accumulazione lo fa senza tentazioni, rinviando le tasse alla vendita.' },
      { t: 'La versione a distribuzione, perché rende sempre di più', ok: false, f: 'A parità di indice e costi, il rendimento lordo è simile: cambia cosa succede ai dividendi, e lei rischierebbe di spenderli.' },
      { t: 'Indifferente: i dividendi non incidono sul rendimento di lungo periodo', ok: false, f: 'Incidono molto: spendere i dividendi invece di reinvestirli riduce la crescita del capitale nel tempo.' },
    ] },
    { s: 'Andrea, 44 anni, vede la pubblicità di un fondo con «+60% in 10 anni» e pensa che equivalga al 6% all’anno. Vuole confrontarlo con altre alternative.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Calcolare il rendimento annuo composto (circa 4,8%) prima di confrontare', ok: true, f: 'Esatto: 1,048 elevato alla decima fa circa 1,60. Va poi confrontato con un indice total return omogeneo e al netto dei costi.' },
      { t: 'Considerarlo un 6% annuo garantito per i prossimi dieci anni', ok: false, f: 'Il 6% è una media semplice sbagliata e i rendimenti passati non sono garantiti per il futuro.' },
      { t: 'Confrontarlo con la variazione di un indice di prezzo dello stesso mercato', ok: false, f: 'Se il fondo include i dividendi, va confrontato con un indice total return, non con uno di prezzo.' },
    ] },
    { s: 'Teresa, 70 anni, legge che un noto indice azionario di prezzo è oggi allo stesso livello di 15 anni fa. Conclude che le azioni di quel mercato non hanno reso nulla in tutto quel periodo.', q: 'Qual è la lettura corretta?', o: [
      { t: 'L’indice esclude i dividendi: il rendimento totale può essere positivo', ok: true, f: 'Corretto: in 15 anni i dividendi reinvestiti possono aver prodotto un guadagno importante anche con un indice di prezzo fermo.' },
      { t: 'Ha ragione: se l’indice è fermo, nessun investitore ha guadagnato', ok: false, f: 'Chi ha incassato e reinvestito i dividendi ha avuto un risultato diverso da quello mostrato dall’indice di prezzo.' },
      { t: 'L’indice è sbagliato: dopo 15 anni dovrebbe essere per forza più alto', ok: false, f: 'Non esiste alcun obbligo di crescita: l’indice di prezzo può restare fermo a lungo. Ma non racconta tutto il rendimento.' },
    ] },
  ],
  tip: 'Valuta un investimento azionario con il rendimento totale netto, annualizzato e confrontato con un indice omogeneo: il solo grafico del prezzo racconta metà della storia.',
});
