FQC(31, {
  intro: 'Un’obbligazione è un prestito che fai a uno Stato o a un’azienda: scopri chi paga, quanto, quando e quali rischi corri.',
  cards: [
    { t: 'Un prestito in forma di titolo', x: 'Comprando un’obbligazione presti denaro a chi la emette. In cambio ricevi interessi periodici, le cedole, e alla scadenza la restituzione del capitale prestato, cioè il valore nominale.', v: { k: 'steps', s: ['Presti il capitale', 'Incassi le cedole', 'Ricevi il rimborso a scadenza'] } },
    { t: 'Creditore, non socio', x: 'L’azionista possiede una quota dell’azienda e partecipa a utili e perdite. L’obbligazionista è un creditore: ha diritto a interessi e rimborso stabiliti nel contratto, ma non vota in assemblea.', v: { k: 'vs', a: ['Azione', 'Quota di proprietà, flussi incerti'], b: ['Obbligazione', 'Credito con flussi stabiliti'] } },
    { t: 'Chi emette obbligazioni', x: 'Emettono obbligazioni gli Stati (come l’Italia con i BTP), gli enti sovranazionali (come la Banca europea per gli investimenti), le banche e le imprese. Servono a finanziare spese e investimenti o a rimborsare debiti in scadenza.', v: { k: 'icons', d: [['🏛️', 'Stati'], ['🌐', 'Enti sovranazionali'], ['🏦', 'Banche'], ['🏭', 'Imprese']] } },
    { t: 'Un esempio numerico', x: 'Compri 10.000 € nominali di un’obbligazione a 5 anni con cedola annua del 3%: incassi 300 € lordi ogni anno e alla scadenza ti vengono restituiti i 10.000 €. In totale ricevi 11.500 € lordi.', v: { k: 'bars', d: [['Anno 1', 300], ['Anno 2', 300], ['Anno 3', 300], ['Anno 4', 300], ['Anno 5', 10300]], u: '€' } },
    { t: 'Il prezzo è in percentuale', x: 'Puoi sottoscrivere un’obbligazione quando viene emessa (mercato primario) o comprarla e venderla dopo in Borsa, ad esempio sul MOT di Borsa Italiana. Il prezzo si esprime in percentuale del nominale e cambia ogni giorno.', v: { k: 'stat', n: '100', l: 'prezzo “alla pari”: uguale al valore nominale' } },
    { t: 'Non è senza rischi', x: 'Un’obbligazione può perdere valore: se i tassi di mercato salgono il suo prezzo scende, l’emittente può non pagare, l’inflazione erode il potere d’acquisto e alcuni titoli sono difficili da vendere prima della scadenza.', v: { k: 'icons', d: [['📈', 'Rischio tasso'], ['⚠️', 'Rischio di credito'], ['🎈', 'Rischio inflazione'], ['💧', 'Rischio di liquidità']] } },
  ],
  terms: [
    ['Obbligazione', 'Titolo di debito: chi lo compra presta denaro all’emittente in cambio di interessi e rimborso.'],
    ['Emittente', 'Stato, ente o impresa che prende denaro a prestito e si impegna a pagare interessi e capitale.'],
    ['Obbligazionista', 'Chi possiede un titolo di debito: è un creditore dell’emittente, non un suo socio.'],
    ['Cedola', 'Interesse pagato periodicamente a chi possiede il titolo, calcolato sul valore nominale.'],
    ['Valore nominale', 'Importo che l’emittente restituisce alla scadenza e su cui si calcolano gli interessi.'],
    ['Mercato primario', 'Mercato in cui i titoli vengono collocati per la prima volta presso gli investitori.'],
    ['Mercato secondario', 'Mercato in cui si scambiano titoli già emessi, ad esempio il MOT di Borsa Italiana.'],
    ['Titolo di Stato', 'Obbligazione emessa da un governo per finanziare il debito pubblico, come BOT e BTP.'],
  ],
  tf: [
    ['Chi compra un’obbligazione diventa socio dell’azienda che la emette.', false, 'Diventa creditore: ha diritto a interessi e rimborso, ma non possiede quote dell’azienda e non vota in assemblea.'],
    ['Con un’obbligazione l’emittente si impegna a pagare flussi di denaro stabiliti nel contratto.', true, 'Importo delle cedole, date di pagamento e rimborso a scadenza sono fissati alle condizioni di emissione.'],
    ['Le obbligazioni non possono mai far perdere soldi.', false, 'Mito diffuso: il prezzo scende se i tassi salgono e l’emittente può fallire. Tenere fino a scadenza non elimina il rischio di credito.'],
    ['In caso di fallimento, gli obbligazionisti vengono soddisfatti prima degli azionisti.', true, 'I creditori hanno priorità sul patrimonio residuo: gli azionisti ricevono qualcosa solo dopo che tutti i creditori sono stati pagati.'],
    ['Solo gli Stati possono emettere obbligazioni.', false, 'Le emettono anche imprese, banche ed enti sovranazionali come la Banca europea per gli investimenti.'],
    ['Un’obbligazione quotata si può vendere prima della scadenza sul mercato secondario.', true, 'Sì, al prezzo di mercato del momento, che può essere più alto o più basso di quello pagato.'],
    ['Se vendi un’obbligazione prima della scadenza, ricevi sempre il valore nominale.', false, 'Prima della scadenza ricevi il prezzo di mercato, che dipende dai tassi e dall’affidabilità dell’emittente.'],
    ['Un’obbligazione ordinaria paga le cedole solo se l’emittente chiude l’anno in utile.', false, 'Mito: la cedola è un obbligo contrattuale, dovuta anche in caso di perdite. È il dividendo delle azioni a dipendere dagli utili.'],
    ['L’inflazione può ridurre il rendimento reale di un’obbligazione a cedola fissa.', true, 'Cedole e rimborso sono fissi in euro: se i prezzi salgono più del previsto, il loro potere d’acquisto diminuisce.'],
    ['A parità di emittente, un’obbligazione è in genere meno rischiosa della sua azione.', true, 'L’obbligazionista ha flussi stabiliti e priorità nel rimborso; l’azionista ha diritto solo a ciò che resta dopo i creditori.'],
  ],
  mcq: [
    { q: 'Che cosa fai quando compri un’obbligazione?', a: 'Presti denaro all’emittente', w: ['Compri una quota dell’azienda', 'Apri un deposito in banca', 'Acquisti un diritto di voto'], e: 'L’obbligazione è un prestito: diventi creditore e ricevi interessi e rimborso del capitale alla scadenza.' },
    { q: 'Che cos’è la cedola di un’obbligazione?', a: 'L’interesse periodico pagato al possessore', w: ['Il prezzo di acquisto del titolo', 'La commissione pagata al broker', 'L’utile distribuito agli azionisti'], e: 'La cedola è l’interesse che l’emittente paga, ad esempio ogni anno o ogni sei mesi, calcolato sul valore nominale.' },
    { q: 'Un’obbligazione da 5.000 € nominali paga una cedola annua del 4%. Quanto incassi ogni anno, al lordo delle tasse?', a: '200 €', w: ['40 €', '400 €', '20 €'], e: '5.000 € × 4% = 200 € lordi l’anno, indipendentemente da come si muove il prezzo del titolo sul mercato.' },
    { q: 'Se una società fallisce, chi ha la precedenza tra obbligazionisti e azionisti?', a: 'Gli obbligazionisti', w: ['Gli azionisti', 'Hanno la stessa priorità', 'Decide l’assemblea dei soci'], e: 'Gli obbligazionisti sono creditori e vengono prima degli azionisti, che sono gli ultimi a essere soddisfatti.' },
    { q: 'Dove puoi vendere un’obbligazione quotata prima della scadenza?', a: 'Sul mercato secondario, come il MOT', w: ['Solo restituendola all’emittente', 'Da nessuna parte: va tenuta a scadenza', 'Solo alla prossima asta di emissione'], e: 'I titoli quotati si scambiano ogni giorno in Borsa: il MOT di Borsa Italiana è il mercato telematico di obbligazioni e titoli di Stato.' },
    { q: 'Come si chiama il rischio che l’emittente non paghi cedole o capitale?', a: 'Rischio di credito', w: ['Rischio di cambio', 'Rischio di liquidità', 'Rischio di inflazione'], e: 'Il rischio di credito, o di insolvenza, è la possibilità che l’emittente non rispetti i pagamenti promessi.' },
    { q: 'Perché uno Stato o un’impresa emette obbligazioni?', a: 'Per raccogliere denaro a prestito', w: ['Per distribuire gli utili ai soci', 'Per aumentare il numero di soci', 'Per ridurre le tasse dei risparmiatori'], e: 'Emettere obbligazioni significa finanziarsi a debito, senza cedere quote di proprietà come avviene con le azioni.' },
    { q: 'Luca dice: “Se tengo l’obbligazione fino a scadenza, il rischio è zero”. Cosa dimentica?', a: 'Che l’emittente potrebbe non rimborsare', w: ['Che a scadenza si riceve il prezzo di Borsa', 'Che le cedole sono pagate in azioni', 'Che la scadenza la decide l’investitore'], e: 'Tenere fino a scadenza evita di vendere a prezzi bassi, ma non elimina il rischio di insolvenza dell’emittente né quello di inflazione.' },
  ],
  fill: [
    { s: 'Chi compra un’obbligazione diventa un ___ dell’emittente.', a: 'creditore', w: ['socio', 'cliente', 'garante'] },
    { s: 'Il soggetto che prende denaro a prestito emettendo obbligazioni si chiama ___.', a: 'emittente', w: ['sottoscrittore', 'intermediario', 'depositario'] },
    { s: 'Alla scadenza l’emittente restituisce il valore ___ del titolo.', a: 'nominale', w: ['di mercato', 'medio', 'contabile'] },
    { s: 'Il MOT di Borsa Italiana è un mercato ___, dove si scambiano titoli già emessi.', a: 'secondario', w: ['primario', 'valutario', 'interbancario'] },
    { s: 'Se l’emittente non paga cedole o capitale si parla di ___.', a: 'default', w: ['dividendo', 'rendimento', 'stacco'] },
  ],
  order: [
    { q: 'Ordina le fasi della vita di un’obbligazione', i: ['L’emittente annuncia il prestito', 'Gli investitori sottoscrivono i titoli', 'L’emittente paga le cedole periodiche', 'Alla scadenza rimborsa il nominale'], e: 'Prima si colloca il prestito sul mercato primario, poi si pagano gli interessi per tutta la durata e infine si restituisce il capitale.' },
    { q: 'Ordina dal meno rischioso al più rischioso, in genere', i: ['Titolo di Stato di un Paese solido', 'Obbligazione di una grande impresa solida', 'Obbligazione di un’impresa molto indebitata', 'Azione di un’impresa molto indebitata'], e: 'Il rischio cresce con la fragilità dell’emittente; a parità di emittente, l’azione è più rischiosa dell’obbligazione perché viene pagata per ultima.' },
  ],
  cat: [
    { q: 'Caratteristica tipica dell’azione o dell’obbligazione?', g: [['Azione', ['Dà diritto di voto', 'Può pagare dividendi', 'Non ha una scadenza']], ['Obbligazione', ['Paga cedole stabilite', 'Ha una data di scadenza', 'Rimborsa il valore nominale']]] },
    { q: 'Chi è l’emittente?', g: [['Stati ed enti sovranazionali', ['BTP della Repubblica Italiana', 'Bund tedesco', 'Obbligazione della BEI']], ['Imprese e banche', ['Bond di una casa automobilistica', 'Obbligazione di una banca', 'Bond di una compagnia telefonica']]] },
  ],
  scen: [
    { s: 'Marta, 45 anni, ha 20.000 € che le serviranno tra 3 anni per ristrutturare casa. Confronta un titolo di Stato a 3 anni, uno a 30 anni con cedola più alta e il bond di una piccola società sconosciuta che paga il 9%.', q: 'Cosa sceglie Marta?', o: [
      { t: 'Il titolo di Stato a 3 anni', ok: true, f: 'La scadenza coincide con il suo obiettivo: tra 3 anni riceve il nominale senza dover vendere a un prezzo incerto.' },
      { t: 'Il titolo a 30 anni, per la cedola più alta', ok: false, f: 'Tra 3 anni dovrebbe venderlo sul mercato: se nel frattempo i tassi fossero saliti, incasserebbe meno di quanto ha pagato.' },
      { t: 'Il bond al 9%, per guadagnare di più', ok: false, f: 'Una cedola così alta segnala un rischio di credito elevato: non è adatta a soldi che le servono con certezza.' },
    ] },
    { s: 'Giorgio, 62 anni, vuole un’entrata periodica prevedibile per integrare la pensione. Il cognato gli consiglia di comprare solo azioni “perché i dividendi arrivano sempre”.', q: 'Cosa fa Giorgio?', o: [
      { t: 'Valuta obbligazioni di emittenti solidi e diversificati', ok: true, f: 'Le cedole sono un obbligo contrattuale con importi e date noti: più adatte a un reddito prevedibile, pur con i loro rischi.' },
      { t: 'Compra solo azioni ad alto dividendo', ok: false, f: 'I dividendi non sono garantiti: l’azienda può ridurli o sospenderli, e il prezzo delle azioni oscilla di più.' },
      { t: 'Tiene tutto in contanti a casa', ok: false, f: 'Nessun reddito, rischio di furto e perdita di potere d’acquisto con l’inflazione: non risolve il suo obiettivo.' },
    ] },
    { s: 'Sara, 28 anni, ha 6.000 € di fondo di emergenza. Vuole metterli tutti in un’obbligazione societaria a 10 anni perché rende più del conto deposito.', q: 'Cosa le conviene fare?', o: [
      { t: 'Tenere il fondo liquido e investire solo i soldi vincolabili', ok: true, f: 'Il fondo di emergenza deve essere disponibile subito e senza perdite: un titolo a 10 anni andrebbe venduto al prezzo del momento.' },
      { t: 'Comprare il bond: tanto si può vendere quando vuole', ok: false, f: 'Può venderlo, ma al prezzo di mercato, che potrebbe essere in perdita; alcuni bond inoltre sono poco scambiati.' },
      { t: 'Investire il fondo in azioni, che rendono di più', ok: false, f: 'Le azioni oscillano ancora di più: un fondo di emergenza investito in Borsa può valere molto meno proprio quando serve.' },
    ] },
    { s: 'Paolo, 35 anni, lavora per una grande azienda che ha appena emesso un’obbligazione. Vorrebbe investirci tutti i suoi 15.000 € di risparmi perché “conosce bene l’azienda”.', q: 'Cosa fa Paolo?', o: [
      { t: 'Investe solo una parte e diversifica tra più emittenti', ok: true, f: 'Se l’azienda andasse in crisi rischierebbe insieme stipendio e risparmi: dividere il capitale tra più emittenti riduce questo rischio.' },
      { t: 'Investe tutto: conosce l’azienda dall’interno', ok: false, f: 'Conoscere l’azienda non elimina il rischio di credito, e concentrare lavoro e risparmi sullo stesso emittente raddoppia l’esposizione.' },
      { t: 'Compra le azioni dell’azienda invece del bond', ok: false, f: 'La concentrazione resta, e in più l’azionista viene pagato dopo l’obbligazionista: il rischio aumenta invece di diminuire.' },
    ] },
  ],
  tip: 'Prima di comprare un’obbligazione chiediti sempre tre cose: chi è l’emittente, quando restituisce il capitale e cosa succede se devi vendere prima.',
});
