FQC(32, {
  intro: 'Cedola, scadenza e valore nominale sono la carta d’identità di un’obbligazione: impara a leggerli e a calcolare quanto incassi davvero.',
  cards: [
    { t: 'Il valore nominale', x: 'È l’importo su cui si calcolano le cedole e che viene rimborsato a scadenza. Si compra in multipli di un taglio minimo: per i titoli di Stato italiani è 1.000 €, per molte obbligazioni societarie arriva a 100.000 €.', v: { k: 'stat', n: '1.000 €', l: 'taglio minimo dei titoli di Stato italiani' } },
    { t: 'Come si calcola la cedola', x: 'La cedola annua è il tasso cedolare moltiplicato per il valore nominale, non per il prezzo pagato. Se è semestrale, ogni sei mesi ricevi metà dell’importo annuo.', v: { k: 'formula', f: 'Cedola annua = tasso cedolare × nominale', n: 'Es.: 4% × 10.000 € = 400 €, cioè 200 € ogni sei mesi' } },
    { t: 'Tipi di cedola', x: 'La cedola può essere fissa, variabile (legata a un tasso di mercato come l’Euribor più uno spread), crescente nel tempo (step-up) o assente: gli zero coupon non pagano cedole e il guadagno è la differenza tra prezzo e rimborso.', v: { k: 'icons', d: [['📌', 'Fissa'], ['🔀', 'Variabile'], ['📶', 'Crescente'], ['⭕', 'Zero coupon']] } },
    { t: 'La scadenza', x: 'È la data in cui il prestito finisce: da pochi mesi a 30 anni e oltre. Più è lontana, più a lungo il tuo capitale resta esposto alle variazioni dei tassi, all’inflazione e al rischio dell’emittente.', v: { k: 'scale', a: 'Breve termine', b: 'Lungo termine', d: [['12 mesi', 4], ['5 anni', 20], ['10 anni', 38], ['30 anni', 95]] } },
    { t: 'Il prezzo in percentuale', x: 'Il prezzo si esprime in percentuale del nominale: 100 è “alla pari”, sopra 100 “sopra la pari”, sotto 100 “sotto la pari”. Con 10.000 € nominali a 98 paghi 9.800 €, ma a scadenza ti rimborsano 10.000 €.', v: { k: 'bars', d: [['Pagato a 98', 9800], ['Rimborso a 100', 10000]], u: '€' } },
    { t: 'Il rateo: la cedola in corso', x: 'Se compri tra due date di pagamento, versi al venditore anche gli interessi maturati fino a quel giorno (rateo). Alla cedola successiva incassi l’intero importo: così ciascuno riceve la sua parte.', v: { k: 'steps', s: ['Cedola pagata', 'Gli interessi maturano giorno per giorno', 'Compri e paghi il rateo', 'Incassi la cedola intera'] } },
  ],
  terms: [
    ['Tasso cedolare', 'Percentuale annua del nominale che l’emittente paga come interesse.'],
    ['Cedola fissa', 'Interesse che resta uguale per tutta la vita del titolo, stabilito all’emissione.'],
    ['Cedola variabile', 'Interesse che cambia nel tempo seguendo un parametro di mercato, ad esempio l’Euribor.'],
    ['Zero coupon', 'Titolo senza interessi periodici: il guadagno è la differenza tra prezzo pagato e rimborso.'],
    ['Taglio minimo', 'Importo nominale più piccolo che si può acquistare; si compra in suoi multipli.'],
    ['Rateo', 'Interessi maturati dall’ultimo pagamento fino al giorno dell’acquisto, versati al venditore.'],
    ['Rimborso bullet', 'Restituzione dell’intero capitale in un’unica soluzione alla data di scadenza.'],
    ['Rendimento corrente', 'Cedola annua divisa per il prezzo di mercato: ignora la differenza tra prezzo e rimborso.'],
  ],
  tf: [
    ['La cedola si calcola sul prezzo che hai pagato per il titolo.', false, 'Mito: si calcola sul nominale. Il 3% su 10.000 € nominali dà 300 € l’anno, sia che tu abbia pagato 9.500 € sia 10.500 €.'],
    ['Un titolo zero coupon non paga cedole periodiche.', true, 'Il suo rendimento deriva tutto dalla differenza tra prezzo d’acquisto e valore di rimborso a scadenza.'],
    ['Una cedola annua del 4% pagata ogni sei mesi corrisponde a due cedole del 2%.', true, 'Il tasso annuo si divide per il numero di pagamenti: 2% del nominale ogni sei mesi.'],
    ['Comprare a 102 significa pagare 102 € per ogni 100 € di nominale.', true, 'Il prezzo è in percentuale del nominale: 10.000 € nominali a 102 costano 10.200 €, più eventuale rateo e commissioni.'],
    ['Un titolo comprato sopra la pari viene rimborsato a scadenza al prezzo d’acquisto.', false, 'A scadenza si riceve il nominale, cioè 100: chi ha comprato a 105 perde 5 punti di capitale al rimborso.'],
    ['Una cedola variabile può diminuire se il tasso di riferimento scende.', true, 'È legata a un parametro come l’Euribor: se il parametro cala, cala anche la cedola, salvo eventuali minimi previsti dal contratto.'],
    ['Il rateo pagato all’acquisto è una commissione che perdi.', false, 'Mito: non è un costo, ma un anticipo al venditore degli interessi già maturati, che recuperi incassando la cedola intera.'],
    ['Due obbligazioni con la stessa cedola hanno sempre lo stesso rischio.', false, 'La cedola non dice tutto: contano scadenza, emittente, valuta e clausole. Cedole uguali possono nascondere rischi molto diversi.'],
    ['Il rendimento corrente di un titolo con cedola del 3% comprato a 100 è del 3%.', true, 'Rendimento corrente = cedola ÷ prezzo = 3 ÷ 100 = 3%. Se il prezzo fosse 75, salirebbe al 4%.'],
    ['Il taglio minimo di un’obbligazione indica il massimo che puoi investire.', false, 'È il minimo acquistabile: puoi comprare qualsiasi multiplo del taglio, ad esempio 3.000 € di un titolo con taglio da 1.000 €.'],
  ],
  mcq: [
    { q: 'Un BTP ha cedola annua del 3,5% e ne possiedi 20.000 € nominali. Quanto incassi lordo ogni sei mesi?', a: '350 €', w: ['700 €', '175 €', '3.500 €'], e: 'Cedola annua: 20.000 × 3,5% = 700 €. Pagata in due rate semestrali, fa 350 € ciascuna, al lordo delle tasse.' },
    { q: 'Compri 5.000 € nominali a 97. Quanto paghi, esclusi rateo e commissioni?', a: '4.850 €', w: ['5.000 €', '5.150 €', '4.970 €'], e: '5.000 × 97% = 4.850 €. A scadenza riceverai 5.000 €: il guadagno in conto capitale sarà di 150 €.' },
    { q: 'Che cosa caratterizza un titolo zero coupon?', a: 'Non paga cedole: guadagni sullo sconto', w: ['Paga cedole crescenti ogni anno', 'Paga una cedola legata all’Euribor', 'Non restituisce il capitale a scadenza'], e: 'Lo zero coupon si compra a un prezzo inferiore al rimborso: il guadagno sta tutto nella differenza tra i due.' },
    { q: 'A cosa è di solito legata la cedola di un titolo a tasso variabile?', a: 'A un tasso di mercato come l’Euribor', w: ['Al prezzo dell’oro', 'Agli utili dell’emittente', 'All’andamento del FTSE MIB'], e: 'I titoli a tasso variabile aggiornano la cedola in base a un parametro, spesso l’Euribor più uno spread fisso.' },
    { q: 'Un titolo con cedola del 4% quota 80. Qual è il suo rendimento corrente?', a: '5%', w: ['4%', '3,2%', '20%'], e: 'Rendimento corrente = cedola ÷ prezzo = 4 ÷ 80 = 5%. È più alto della cedola perché il titolo costa meno della pari.' },
    { q: 'Compri un’obbligazione 2 mesi dopo il pagamento di una cedola semestrale. Cosa versi in più al venditore?', a: 'Il rateo di circa 2 mesi di interessi', w: ['L’intera cedola semestrale', 'Una penale per acquisto anticipato', 'Nulla: gli interessi spettano a te'], e: 'Il venditore ha diritto agli interessi maturati mentre teneva il titolo: tu glieli anticipi e poi incassi la cedola intera.' },
    { q: 'Cosa ricevi a scadenza da un’obbligazione bullet da 10.000 € nominali comprata a 104?', a: '10.000 € più l’ultima cedola', w: ['10.400 € più l’ultima cedola', 'Il prezzo di Borsa di quel giorno', 'Solo l’ultima cedola'], e: 'A scadenza si rimborsa il nominale, a prescindere dal prezzo pagato: i 400 € pagati sopra la pari non tornano indietro.' },
    { q: 'Quale affermazione sulla scadenza è corretta?', a: 'Più è lunga, più tempo il capitale è a rischio', w: ['Più è lunga, più il titolo è sicuro', 'La scadenza non influenza il rischio', 'Le obbligazioni scadono tutte entro 10 anni'], e: 'Su orizzonti lunghi possono cambiare tassi, inflazione e solidità dell’emittente: per questo la scadenza conta quanto la cedola.' },
  ],
  fill: [
    { s: 'La cedola annua si calcola moltiplicando il tasso cedolare per il valore ___.', a: 'nominale', w: ['di mercato', 'di acquisto', 'di bilancio'] },
    { s: 'Un titolo che quota 103 è quotato ___ la pari.', a: 'sopra', w: ['sotto', 'entro', 'prima'] },
    { s: 'Un titolo che non paga cedole e si compra a sconto si chiama ___.', a: 'zero coupon', w: ['step-up', 'perpetuo', 'callable'] },
    { s: 'Gli interessi maturati dall’ultima cedola fino al giorno dell’acquisto si chiamano ___.', a: 'rateo', w: ['spread', 'premio', 'dividendo'] },
    { s: 'Una cedola pari all’Euribor più uno spread è una cedola ___.', a: 'variabile', w: ['fissa', 'crescente', 'reale'] },
  ],
  order: [
    { q: 'Ordina i passi per calcolare quanto incassi da una cedola semestrale', i: ['Leggi il tasso cedolare annuo', 'Moltiplicalo per il nominale che possiedi', 'Dividi per due il risultato', 'Togli le imposte per ottenere il netto'], e: 'Esempio: 3% × 10.000 € = 300 € l’anno, 150 € a semestre lordi; con un titolo di Stato al 12,5% restano 131,25 € netti.' },
    { q: 'Cedola del 4%: ordina dal rendimento corrente più basso al più alto', i: ['Prezzo 110', 'Prezzo 100', 'Prezzo 90', 'Prezzo 80'], e: '4 ÷ 110 ≈ 3,6%; 4 ÷ 100 = 4%; 4 ÷ 90 ≈ 4,4%; 4 ÷ 80 = 5%. A parità di cedola, più paghi meno rendi.' },
  ],
  cat: [
    { q: 'Cedola fissa o variabile?', g: [['Fissa', ['BTP con cedola del 3%', 'Bond al 4,5% fino a scadenza', 'Cedola uguale per 10 anni']], ['Variabile', ['CCT legato all’Euribor', 'Euribor a 6 mesi + 1%', 'Cedola ricalcolata ogni semestre']]] },
    { q: 'Sopra o sotto la pari?', g: [['Sopra la pari', ['Prezzo 101,5', 'Prezzo 108', '10.300 € per 10.000 € nominali']], ['Sotto la pari', ['Prezzo 96', 'Prezzo 99,9', '9.700 € per 10.000 € nominali']]] },
  ],
  scen: [
    { s: 'Elena, 50 anni, confronta due obbligazioni dello stesso emittente, entrambe a 3 anni: la A ha cedola del 6% e costa 115, la B ha cedola del 2% e costa 96. È attratta dalla cedola alta della A.', q: 'Cosa dovrebbe fare Elena?', o: [
      { t: 'Considerare anche il rimborso rispetto al prezzo', ok: true, f: 'La A rimborsa 100 dopo averla pagata 115: perde 15 punti, quasi tutte le cedole incassate (18). La B incassa 6 di cedole più 4 al rimborso.' },
      { t: 'Scegliere la A: la cedola più alta rende di più', ok: false, f: 'La cedola si calcola sul nominale, ma il premio pagato sopra la pari si perde a scadenza: guardare solo la cedola inganna.' },
      { t: 'Scartare per principio i titoli sopra la pari', ok: false, f: 'Un prezzo sopra 100 è normale quando la cedola supera i tassi di mercato: basta tenerne conto nei calcoli.' },
    ] },
    { s: 'Tommaso, 30 anni, compra 10.000 € di un BTP a metà periodo cedolare. Nel riepilogo dell’ordine vede un “rateo” di circa 90 € in più rispetto al prezzo e pensa che la banca lo abbia imbrogliato.', q: 'Cosa fa Tommaso?', o: [
      { t: 'Capisce che recupererà il rateo con la cedola', ok: true, f: 'Il rateo sono gli interessi maturati che spettano al venditore: alla prossima cedola Tommaso incasserà l’intero semestre.' },
      { t: 'Fa reclamo e chiede di annullare il rateo', ok: false, f: 'Il rateo è un meccanismo standard del mercato obbligazionario, non una commissione: non c’è nulla da contestare.' },
      { t: 'Rivende subito il titolo per recuperarlo', ok: false, f: 'Vendendo pagherebbe nuove commissioni; il rateo gli verrebbe sì riconosciuto, ma senza alcun vantaggio rispetto a tenere il titolo.' },
    ] },
    { s: 'Chiara, 40 anni, ha 2.500 € e vorrebbe investirli nel bond di una grande azienda, ma scopre che ha un taglio minimo di 100.000 €.', q: 'Cosa fa Chiara?', o: [
      { t: 'Valuta un fondo o ETF obbligazionario', ok: true, f: 'Con piccole cifre un fondo o un ETF permette di accedere a molti emittenti insieme, diversificando il rischio di credito.' },
      { t: 'Chiede un prestito per arrivare a 100.000 €', ok: false, f: 'Indebitarsi per comprare un singolo bond moltiplica il rischio: se l’emittente va in difficoltà la perdita ricade tutta su di lei.' },
      { t: 'Chiede al broker di comprarne 2.500 €', ok: false, f: 'Non è possibile: sotto il taglio minimo il titolo non si può acquistare, si compra solo in multipli di quell’importo.' },
    ] },
    { s: 'Franco, 67 anni, vuole un’entrata ogni sei mesi di importo noto per pagare le spese di casa. Confronta uno zero coupon a 5 anni, un BTP a 5 anni con cedola fissa semestrale e un titolo a cedola variabile.', q: 'Quale titolo è più adatto a Franco?', o: [
      { t: 'Il BTP a cedola fissa semestrale', ok: true, f: 'Paga ogni sei mesi un importo stabilito fin dall’inizio: è il flusso prevedibile che Franco cerca.' },
      { t: 'Lo zero coupon a 5 anni', ok: false, f: 'Non paga nulla fino alla scadenza: Franco non avrebbe entrate per 5 anni.' },
      { t: 'Il titolo a cedola variabile', ok: false, f: 'Paga regolarmente, ma l’importo cambia con i tassi: Franco non saprebbe in anticipo quanto incasserà.' },
    ] },
  ],
  tip: 'Leggi sempre la scheda del titolo: tasso cedolare, frequenza, scadenza, taglio minimo e prezzo. La cedola da sola non ti dice quanto guadagnerai.',
});
