FQC(33, {
  intro: 'Quando i tassi salgono i prezzi delle obbligazioni scendono, e viceversa. Scopri perché succede e cosa significa per chi le possiede.',
  cards: [
    { t: 'L’altalena dei tassi', x: 'Prezzo e rendimento di un’obbligazione si muovono in direzioni opposte: se i tassi di mercato salgono, il prezzo dei titoli a tasso fisso già emessi scende; se i tassi scendono, il loro prezzo sale.', v: { k: 'vs', a: ['Tassi in rialzo', 'Prezzi dei titoli esistenti in calo'], b: ['Tassi in calo', 'Prezzi dei titoli esistenti in rialzo'] } },
    { t: 'Perché succede', x: 'Hai un titolo che paga il 2%. Se i nuovi titoli simili pagano il 4%, nessuno comprerà il tuo a 100: per venderlo dovrai accettare un prezzo più basso, finché chi lo compra ottiene un rendimento simile a quello dei nuovi.', v: { k: 'steps', s: ['I tassi di mercato salgono', 'I nuovi titoli pagano di più', 'Il tuo titolo è meno attraente', 'Il suo prezzo scende'] } },
    { t: 'Uno zero coupon a un anno', x: 'Un titolo che rimborsa 100 tra un anno vale circa 96,15 se il rendimento richiesto è il 4%. Se il rendimento sale al 5% vale circa 95,24; se scende al 3%, circa 97,09.', v: { k: 'bars', d: [['Rend. 3%', 97.09], ['Rend. 4%', 96.15], ['Rend. 5%', 95.24]] } },
    { t: 'Il rendimento a scadenza', x: 'Il rendimento a scadenza è il tasso che rende il prezzo di oggi uguale al valore attuale di tutte le cedole e del rimborso. Tiene conto sia delle cedole sia del guadagno o della perdita tra prezzo pagato e 100.', v: { k: 'formula', f: 'Prezzo = somma dei flussi futuri scontati al rendimento', n: 'Es.: 1 anno, cedola 3, rimborso 100, prezzo 99 → 103 ÷ 99 − 1 ≈ 4,04%' } },
    { t: 'Sopra, alla o sotto la pari', x: 'Se il prezzo è 100, il rendimento a scadenza è circa uguale alla cedola. Se il prezzo è sotto 100, il rendimento supera la cedola; se è sopra 100, è inferiore alla cedola.', v: { k: 'scale', a: 'Prezzo basso, rendimento alto', b: 'Prezzo alto, rendimento basso', d: [['92: rendimento > cedola', 15], ['100: rendimento ≈ cedola', 50], ['108: rendimento < cedola', 85]] } },
    { t: 'Verso 100 alla scadenza', x: 'Avvicinandosi alla scadenza, il prezzo di un titolo il cui emittente resta solvibile tende verso 100, il valore di rimborso. Chi tiene il titolo fino alla fine non realizza le oscillazioni intermedie.', v: { k: 'stat', n: '100', l: 'il valore verso cui converge il prezzo a scadenza' } },
  ],
  terms: [
    ['Rendimento a scadenza', 'Tasso annuo ottenuto comprando al prezzo attuale e tenendo il titolo fino al rimborso.'],
    ['Alla pari', 'Prezzo uguale a 100, cioè al valore nominale del titolo.'],
    ['Sotto la pari', 'Prezzo inferiore a 100: chi compra guadagna anche la differenza con il rimborso.'],
    ['Sopra la pari', 'Prezzo superiore a 100: la differenza rispetto al rimborso è una perdita a scadenza.'],
    ['Valore attuale', 'Quanto vale oggi una somma che si riceverà in futuro, scontata al rendimento richiesto.'],
    ['Tasso di sconto', 'Rendimento richiesto usato per riportare a oggi i flussi futuri di un titolo.'],
    ['Minusvalenza', 'Perdita realizzata vendendo un titolo a un prezzo inferiore a quello di acquisto.'],
    ['Pull to par', 'Tendenza del prezzo a convergere verso 100 man mano che si avvicina la scadenza.'],
  ],
  tf: [
    ['Se i tassi di mercato salgono, il prezzo delle obbligazioni a tasso fisso già emesse tende a scendere.', true, 'I nuovi titoli pagano di più: quelli vecchi devono costare meno per offrire un rendimento competitivo a chi li compra.'],
    ['Un calo dei tassi di mercato fa scendere il prezzo dei titoli a tasso fisso in circolazione.', false, 'È il contrario: se i tassi scendono, le vecchie cedole più alte diventano più preziose e il prezzo sale.'],
    ['Se un titolo quota sotto 100, il suo rendimento a scadenza è più alto della cedola.', true, 'Chi compra incassa le cedole e in più guadagna la differenza tra il prezzo pagato e il rimborso a 100.'],
    ['Un titolo comprato sopra la pari rende a scadenza più della sua cedola.', false, 'Il premio pagato sopra 100 si perde al rimborso: il rendimento a scadenza è inferiore alla cedola.'],
    ['Se il prezzo del tuo BTP scende ma lo tieni fino a scadenza, ricevi comunque 100, se lo Stato paga.', true, 'La perdita resta solo sulla carta: a scadenza si rimborsa il nominale, qualunque sia stato il prezzo nel frattempo.'],
    ['Quando il prezzo di un titolo a tasso fisso scende, l’emittente riduce la cedola.', false, 'Mito: la cedola di un titolo a tasso fisso non cambia. Cambia il prezzo, e quindi il rendimento per chi compra in quel momento.'],
    ['Il rendimento a scadenza tiene conto sia delle cedole sia della differenza tra prezzo e rimborso.', true, 'Per questo è più completo della cedola e del rendimento corrente, che ignorano il guadagno o la perdita in conto capitale.'],
    ['Un’obbligazione a tasso fisso non può mai scendere sotto il prezzo di emissione.', false, 'Mito: sul mercato secondario il prezzo varia ogni giorno e può scendere anche molto se i tassi salgono o l’emittente peggiora.'],
    ['Dopo un calo del prezzo, chi compra il titolo ottiene un rendimento a scadenza più alto di prima.', true, 'Paga meno per gli stessi flussi futuri: a parità di cedole e rimborso, un prezzo più basso significa un rendimento più alto.'],
    ['Avvicinandosi alla scadenza, il prezzo di un titolo solvibile tende ad allontanarsi da 100.', false, 'Succede il contrario: il prezzo converge verso 100, il valore che sarà rimborsato a scadenza.'],
  ],
  mcq: [
    { q: 'Hai un titolo a tasso fisso con cedola del 2%. I nuovi titoli simili ora pagano il 4%. Cosa succede al prezzo del tuo?', a: 'Scende', w: ['Sale', 'Resta invariato', 'Dipende solo dalla scadenza'], e: 'Per essere competitivo con i nuovi titoli al 4%, il tuo deve costare meno, finché il rendimento per chi lo compra è simile.' },
    { q: 'Uno zero coupon rimborsa 100 tra un anno e oggi costa 95. Qual è il suo rendimento, arrotondato al decimo?', a: '5,3%', w: ['5,0%', '4,8%', '9,5%'], e: 'Rendimento = 100 ÷ 95 − 1 ≈ 5,26%. Guadagni 5 su 95 investiti, non su 100.' },
    { q: 'Un titolo con cedola del 3% quota 106. Come sarà il rendimento a scadenza rispetto alla cedola?', a: 'Inferiore al 3%', w: ['Superiore al 3%', 'Esattamente il 3%', 'Pari al 6%'], e: 'Pagando 106 per un rimborso di 100 perdi 6 punti a scadenza: il rendimento complessivo resta sotto la cedola.' },
    { q: 'Perché il prezzo di un titolo esistente scende quando i tassi salgono?', a: 'Per allinearne il rendimento ai nuovi titoli', w: ['Perché l’emittente riduce la cedola', 'Perché il nominale viene ridotto', 'Perché la scadenza viene allungata'], e: 'Cedola, nominale e scadenza restano fissi: l’unica variabile che può adattarsi ai nuovi tassi è il prezzo.' },
    { q: 'Quale misura considera insieme cedole, prezzo pagato e rimborso?', a: 'Il rendimento a scadenza', w: ['Il tasso cedolare', 'Il rendimento corrente', 'Il valore nominale'], e: 'Il rendimento a scadenza è il tasso che rende il prezzo uguale al valore attuale di tutti i flussi futuri.' },
    { q: 'Anna ha un BTP comprato a 100 che ora quota 93. Lo terrà fino a scadenza. Quanto riceverà a scadenza, se lo Stato paga?', a: '100, più l’ultima cedola', w: ['93, il prezzo attuale', '96,5, la media dei due prezzi', 'Il prezzo di Borsa di quel giorno'], e: 'A scadenza si rimborsa il nominale. La perdita di 7 punti diventerebbe reale solo vendendo prima.' },
    { q: 'Un titolo quota 100 e ha cedola annua del 4%. Il suo rendimento a scadenza è circa…', a: '4%', w: ['0%', '8%', '2%'], e: 'Alla pari non ci sono guadagni né perdite sul capitale: il rendimento a scadenza coincide con la cedola.' },
    { q: 'Marco pensa: “Le obbligazioni sono sicure, quindi il loro prezzo non si muove”. Cosa c’è di sbagliato?', a: 'Il prezzo varia con tassi e rischio emittente', w: ['Nulla: il prezzo è fisso per legge', 'Il prezzo varia solo nel giorno della cedola', 'Il prezzo varia solo per le azioni'], e: 'Sul mercato secondario il prezzo delle obbligazioni oscilla ogni giorno, anche per i titoli di Stato più solidi.' },
  ],
  fill: [
    { s: 'Prezzo e rendimento di un’obbligazione hanno una relazione ___.', a: 'inversa', w: ['diretta', 'casuale', 'fissa'] },
    { s: 'Se i tassi di mercato salgono, il prezzo dei titoli a tasso fisso già emessi tende a ___.', a: 'scendere', w: ['salire', 'raddoppiare', 'stabilizzarsi'] },
    { s: 'Se un titolo quota sotto 100, il suo rendimento a scadenza è ___ rispetto alla cedola.', a: 'più alto', w: ['più basso', 'identico', 'irrilevante'] },
    { s: 'Avvicinandosi alla scadenza, il prezzo di un titolo solvibile converge verso ___.', a: '100', w: ['0', '50', '200'] },
    { s: 'Il tasso che rende il prezzo uguale al valore attuale di cedole e rimborso è il rendimento a ___.', a: 'scadenza', w: ['vista', 'pronti', 'cedola'] },
  ],
  order: [
    { q: 'Ordina la catena di eventi quando i tassi di mercato salgono', i: ['I tassi di mercato salgono', 'I nuovi titoli offrono cedole più alte', 'I titoli già emessi diventano meno richiesti', 'Il loro prezzo scende', 'Il loro rendimento sale per chi li compra'], e: 'Il prezzo dei vecchi titoli si aggiusta finché il loro rendimento a scadenza torna in linea con quello dei nuovi.' },
    { q: 'Titoli identici, cedola 3%, scadenza 5 anni: ordina dal rendimento a scadenza più basso al più alto', i: ['Prezzo 104', 'Prezzo 100', 'Prezzo 97', 'Prezzo 92'], e: 'A parità di flussi, più basso è il prezzo pagato, più alto è il rendimento: chi paga 92 guadagna anche 8 punti al rimborso.' },
  ],
  cat: [
    { q: 'Cosa fa salire o scendere il prezzo di un BTP a tasso fisso già emesso?', g: [['Prezzo in rialzo', ['I tassi di mercato scendono', 'Lo Stato appare più affidabile', 'L’inflazione attesa diminuisce']], ['Prezzo in calo', ['I tassi di mercato salgono', 'Cresce il timore di insolvenza', 'L’inflazione attesa aumenta']]] },
    { q: 'Rendimento a scadenza maggiore o minore della cedola?', g: [['Maggiore della cedola', ['Prezzo 95', 'Prezzo 88', 'Comprato sotto la pari']], ['Minore della cedola', ['Prezzo 103', 'Prezzo 110', 'Comprato sopra la pari']]] },
  ],
  scen: [
    { s: 'Luca, 34 anni, ha comprato 10.000 € di un BTP a 10 anni a 100. Dopo un rialzo dei tassi quota 91 e l’estratto conto mostra una perdita di 900 €. Non gli servono i soldi prima della scadenza.', q: 'Cosa fa Luca?', o: [
      { t: 'Lo tiene fino a scadenza, come previsto', ok: true, f: 'Se lo Stato paga, a scadenza riceverà 100 e nel frattempo incassa le cedole: la perdita resta solo sulla carta.' },
      { t: 'Lo vende subito per non perdere di più', ok: false, f: 'Vendendo trasforma una perdita temporanea in una perdita reale, senza che il suo obiettivo sia cambiato.' },
      { t: 'Si fa prestare soldi per comprarne altri a 91', ok: false, f: 'Usare debito per mediare il prezzo aumenta il rischio: se i tassi salissero ancora, le perdite crescerebbero insieme agli interessi da pagare.' },
    ] },
    { s: 'Valentina, 29 anni, ha liquidità da investire per 5 anni. Dopo un rialzo dei tassi molti BTP già emessi quotano sotto 100 e lei teme di “comprare qualcosa che sta perdendo”.', q: 'Come ragiona Valentina?', o: [
      { t: 'A prezzo più basso, il rendimento per chi compra è più alto', ok: true, f: 'Chi compra dopo il calo paga meno per gli stessi flussi: il rendimento a scadenza è più alto di quello di chi aveva comprato prima.' },
      { t: 'Aspetta che i prezzi tornino a 100 prima di comprare', ok: false, f: 'I prezzi possono restare bassi a lungo: aspettare 100 significa rinunciare proprio al rendimento più alto disponibile oggi.' },
      { t: 'Compra solo titoli sopra 100 perché “vanno bene”', ok: false, f: 'Un prezzo alto non indica un titolo migliore: indica solo una cedola superiore ai tassi attuali, che si paga con il premio sopra la pari.' },
    ] },
    { s: 'Stefano, 55 anni, ha un BTP comprato a 100 che, dopo un calo dei tassi, quota 112. Mancano 2 anni alla scadenza. Un amico gli dice: “Tienilo, a scadenza ti daranno 112”.', q: 'Come ragiona Stefano?', o: [
      { t: 'Sa che a scadenza riceverà 100 e valuta se vendere ora', ok: true, f: 'Il prezzo converge verso 100: vendendo ora incassa la plusvalenza, tenendo riceve cedole più alte ma vede sparire il premio.' },
      { t: 'Si fida: a scadenza incasserà 112', ok: false, f: 'A scadenza si rimborsa sempre il nominale, cioè 100: il premio attuale si riduce man mano che la scadenza si avvicina.' },
      { t: 'Ne compra altri a 112 per rivenderli a 120', ok: false, f: 'Il prezzo può salire ancora solo se i tassi scendono ancora; con il passare del tempo, invece, tende a tornare verso 100.' },
    ] },
    { s: 'Giulia, 61 anni, si sente proporre un’obbligazione con cedola del 6% che quota 109 e scade tra 3 anni. Il venditore insiste: “Rende il 6% all’anno”.', q: 'Cosa fa Giulia?', o: [
      { t: 'Chiede il rendimento a scadenza, che considera il prezzo', ok: true, f: 'Pagando 109 per ricevere 100 perde 9 punti in 3 anni: il rendimento a scadenza è sotto il 3% annuo, non il 6%.' },
      { t: 'Compra: il 6% all’anno è garantito', ok: false, f: 'Il 6% è la cedola sul nominale, non il rendimento di chi paga 109: il premio sopra la pari si perde al rimborso.' },
      { t: 'Rifiuta perché i titoli sopra 100 sono sempre una truffa', ok: false, f: 'Un prezzo sopra la pari è normale per un titolo con cedola alta: il problema è solo come viene presentato il rendimento.' },
    ] },
  ],
  tip: 'Il prezzo di un’obbligazione oscilla, il suo rimborso no: se l’emittente paga, a scadenza ricevi 100. Fai coincidere la scadenza con il momento in cui ti servono i soldi.',
});
