FQC(34, {
  intro: 'BOT, BTP, CCT, BTP Italia, BTP€i e BTP Valore: conosci la famiglia dei titoli di Stato italiani, come si comprano e come sono tassati.',
  cards: [
    { t: 'I BOT: il guadagno è lo sconto', x: 'I Buoni Ordinari del Tesoro durano fino a 12 mesi e non pagano cedole: di norma si comprano sotto la pari e a scadenza rimborsano 100. Il guadagno è la differenza tra prezzo pagato e rimborso, detta scarto di emissione.', v: { k: 'formula', f: 'Guadagno lordo BOT = 100 − prezzo d’acquisto', n: 'Es. ipotetico: compri a 98 → guadagni 2 ogni 100 di nominale' } },
    { t: 'BTP e CCT', x: 'I BTP pagano una cedola fissa ogni sei mesi, con scadenze da pochi anni fino a 50. I CCT pagano una cedola semestrale variabile, legata all’Euribor a 6 mesi più uno spread: per questo il loro prezzo risente meno delle variazioni dei tassi.', v: { k: 'vs', a: ['BTP', 'Cedola fissa semestrale, fino a 50 anni'], b: ['CCT', 'Cedola variabile: Euribor 6 mesi + spread'] } },
    { t: 'I titoli contro l’inflazione', x: 'Il BTP Italia rivaluta il capitale con l’inflazione italiana, misurata dall’indice FOI senza tabacchi. Il BTP€i segue invece l’inflazione dell’area euro, misurata dall’indice IAPC senza tabacchi.', v: { k: 'icons', d: [['🇮🇹', 'BTP Italia: inflazione italiana'], ['🇪🇺', 'BTP€i: inflazione dell’area euro']] } },
    { t: 'Il BTP Valore', x: 'È riservato ai risparmiatori individuali e si sottoscrive in giorni dedicati tramite la propria banca o l’home banking. Ha cedole fisse che crescono nel tempo (step-up) e un premio fedeltà per chi lo tiene dall’emissione alla scadenza. Nel grafico, cedole ipotetiche.', v: { k: 'bars', d: [['Anni 1-2', 3], ['Anni 3-4', 3.5], ['Anni 5-6', 4]], u: '%' } },
    { t: 'Come si comprano', x: 'BOT, BTP e CCT si collocano con aste a cui partecipano solo gli intermediari, che raccolgono le prenotazioni dei clienti. BTP Italia e BTP Valore si sottoscrivono sul MOT in un periodo dedicato. Dopo, tutti si scambiano in Borsa.', v: { k: 'steps', s: ['Il Tesoro annuncia l’asta', 'Prenoti tramite banca o broker', 'L’asta fissa il prezzo', 'I titoli arrivano nel dossier'] } },
    { t: 'Una tassazione agevolata', x: 'Su cedole, scarti di emissione e plusvalenze dei titoli di Stato italiani (e dei Paesi in white list) l’aliquota è del 12,5%, contro il 26% di azioni e obbligazioni societarie. Sul dossier titoli si paga comunque il bollo dello 0,2% annuo.', v: { k: 'stat', n: '12,5%', l: 'aliquota su interessi e plusvalenze dei titoli di Stato' } },
  ],
  terms: [
    ['BOT', 'Buono Ordinario del Tesoro: titolo senza cedole con durata fino a 12 mesi.'],
    ['BTP', 'Buono del Tesoro Poliennale: titolo a medio-lungo termine con cedola fissa semestrale.'],
    ['CCT', 'Certificato di Credito del Tesoro: cedola semestrale variabile legata all’Euribor a 6 mesi.'],
    ['BTP Italia', 'Titolo che rivaluta capitale e cedole con l’inflazione italiana misurata dall’indice FOI.'],
    ['BTP€i', 'Titolo che rivaluta il capitale con l’inflazione dell’area euro, misurata dall’indice IAPC.'],
    ['BTP Valore', 'Titolo riservato ai risparmiatori individuali, con cedole crescenti e premio fedeltà.'],
    ['Asta', 'Procedura con cui il Tesoro colloca i titoli presso gli intermediari, fissando prezzo e quantità.'],
    ['Scarto di emissione', 'Differenza tra il valore di rimborso e il prezzo di emissione, tipica dei BOT.'],
  ],
  tf: [
    ['I BOT pagano una cedola fissa ogni sei mesi.', false, 'I BOT sono zero coupon: non pagano cedole e il rendimento deriva dalla differenza tra prezzo d’acquisto e rimborso a 100.'],
    ['I CCT hanno una cedola variabile legata all’Euribor a 6 mesi.', true, 'La cedola è pari all’Euribor a 6 mesi più uno spread fissato all’emissione e si aggiorna a ogni semestre.'],
    ['Interessi e plusvalenze dei titoli di Stato italiani sono tassati al 12,5%.', true, 'È un’aliquota agevolata rispetto al 26% che si applica, ad esempio, ad azioni e obbligazioni societarie.'],
    ['I titoli di Stato italiani sono esenti dall’imposta di bollo sul dossier titoli.', false, 'Mito: il bollo dello 0,2% annuo si applica all’intero dossier, titoli di Stato compresi. L’agevolazione riguarda l’aliquota sui redditi.'],
    ['Il BTP€i è indicizzato all’inflazione italiana.', false, 'Il BTP€i segue l’inflazione dell’area euro (indice IAPC senza tabacchi). È il BTP Italia a seguire l’inflazione italiana.'],
    ['Il premio fedeltà del BTP Valore spetta a chi lo sottoscrive all’emissione e lo tiene fino a scadenza.', true, 'Chi lo compra dopo sul mercato secondario, o lo vende prima della scadenza, non riceve il premio.'],
    ['I titoli di Stato italiani non rientrano nella base imponibile dell’imposta di successione.', true, 'Chi li riceve in eredità non li conteggia ai fini dell’imposta di successione: un vantaggio rispetto a molti altri investimenti.'],
    ['Tutti i titoli di Stato italiani sono a tasso fisso.', false, 'Ci sono BTP a tasso fisso, CCT a tasso variabile, BOT senza cedola e titoli legati all’inflazione come BTP Italia e BTP€i.'],
    ['Il prezzo di un BTP a lunga scadenza può scendere sensibilmente se i tassi salgono.', true, 'Anche un titolo di Stato ha rischio di prezzo: più lunga è la scadenza, più il prezzo reagisce alle variazioni dei tassi.'],
    ['Un titolo di Stato non può perdere valore perché è garantito dallo Stato.', false, 'Mito: lo Stato si impegna a pagare cedole e rimborso a scadenza, non garantisce il prezzo di mercato prima della scadenza.'],
  ],
  mcq: [
    { q: 'Quale titolo di Stato italiano non paga cedole?', a: 'BOT', w: ['BTP', 'CCT', 'BTP Valore'], e: 'Il BOT è uno zero coupon con durata fino a 12 mesi: il rendimento è lo scarto tra prezzo pagato e rimborso.' },
    { q: 'Un CCT paga Euribor a 6 mesi + 1%. Con l’Euribor (ipotetico) al 2,5%, qual è la cedola annua?', a: '3,5%', w: ['2,5%', '1%', '1,5%'], e: 'Cedola = Euribor + spread = 2,5% + 1% = 3,5% annuo, pagato in due rate semestrali da 1,75%.' },
    { q: 'Su 1.000 € lordi di cedole di un BTP, quanto paghi di imposta?', a: '125 €', w: ['260 €', '200 €', '0 €'], e: 'I titoli di Stato italiani sono tassati al 12,5%: 1.000 × 12,5% = 125 €, quindi ti restano 875 € netti.' },
    { q: 'Quale titolo segue l’inflazione italiana misurata dall’indice FOI?', a: 'BTP Italia', w: ['BTP€i', 'CCT', 'BOT'], e: 'Il BTP Italia è indicizzato all’inflazione italiana (FOI senza tabacchi); il BTP€i a quella dell’area euro.' },
    { q: 'Cosa caratterizza il BTP Valore?', a: 'Cedole crescenti e premio fedeltà', w: ['Cedola legata all’Euribor', 'Nessuna cedola e durata di un anno', 'Capitale rivalutato con l’inflazione'], e: 'È riservato ai risparmiatori individuali: cedole fisse che aumentano nel tempo e un premio extra per chi lo tiene fino a scadenza.' },
    { q: 'Come partecipa un risparmiatore a un’asta di BTP?', a: 'Prenotando tramite la propria banca o broker', w: ['Presentandosi di persona all’asta', 'Scrivendo direttamente al Tesoro', 'Solo in contanti allo sportello'], e: 'All’asta partecipano solo gli intermediari autorizzati: il risparmiatore prenota tramite banca o broker, che acquista per suo conto.' },
    { q: 'Un BOT a 12 mesi costa 97 e rimborsa 100. Qual è il guadagno lordo su 10.000 € nominali?', a: '300 €', w: ['97 €', '30 €', '3.000 €'], e: 'Paghi 9.700 € e ricevi 10.000 €: il guadagno lordo è 300 €, su cui si applica l’imposta del 12,5%.' },
    { q: 'Perché il prezzo di un CCT oscilla meno di quello di un BTP di pari durata quando cambiano i tassi?', a: 'La sua cedola si adegua ai tassi di mercato', w: ['È garantito da una banca centrale estera', 'Ha sempre una scadenza sotto un anno', 'Non è quotato in Borsa'], e: 'Ogni sei mesi la cedola si riallinea all’Euribor: il prezzo resta più stabile, ma risente comunque del rischio Italia.' },
  ],
  fill: [
    { s: 'I BOT hanno una durata massima di ___ mesi.', a: '12', w: ['24', '6', '36'] },
    { s: 'La cedola dei CCT è legata all’___ a 6 mesi più uno spread.', a: 'Euribor', w: ['inflazione', 'IAPC', 'oro'] },
    { s: 'Su interessi e plusvalenze dei titoli di Stato italiani l’aliquota è del ___.', a: '12,5%', w: ['26%', '20%', '0,2%'] },
    { s: 'Il BTP Valore premia chi lo tiene dall’emissione alla scadenza con un premio ___.', a: 'fedeltà', w: ['produzione', 'rischio', 'emissione'] },
    { s: 'Il BTP€i è indicizzato all’inflazione dell’area ___.', a: 'euro', w: ['dollaro', 'mediterranea', 'OCSE'] },
  ],
  order: [
    { q: 'Ordina dalla durata più breve alla più lunga', i: ['BOT a 3 mesi', 'BOT a 12 mesi', 'BTP a 5 anni', 'BTP a 30 anni', 'BTP a 50 anni'], e: 'I BOT coprono il breve termine, fino a 12 mesi; i BTP vanno da pochi anni fino a 50.' },
    { q: 'Ordina le fasi per sottoscrivere un BTP in asta', i: ['Il Tesoro annuncia l’asta e i titoli offerti', 'Prenoti l’importo tramite banca o broker', 'L’asta si svolge e fissa il prezzo', 'I titoli vengono accreditati nel tuo dossier'], e: 'Il Tesoro pubblica il calendario delle aste; l’intermediario raccoglie le prenotazioni e partecipa all’asta per conto dei clienti.' },
  ],
  cat: [
    { q: 'Il titolo è indicizzato (all’inflazione o all’Euribor) oppure no?', g: [['Indicizzato', ['CCT', 'BTP Italia', 'BTP€i']], ['Non indicizzato', ['BOT', 'BTP', 'BTP Valore']]] },
    { q: 'Aliquota del 12,5% o del 26%?', g: [['12,5%', ['Cedole di un BTP', 'Scarto di emissione di un BOT', 'Plusvalenza su un CCT']], ['26%', ['Dividendi di un’azione italiana', 'Cedole di un bond societario', 'Plusvalenza su un’azione']]] },
  ],
  scen: [
    { s: 'Alberto, 52 anni, ha 30.000 € che gli serviranno tra circa un anno per l’anticipo di una casa. Non vuole rischiare il capitale e cerca un titolo di Stato.', q: 'Cosa sceglie Alberto?', o: [
      { t: 'Un BOT che scade prima che gli servano i soldi', ok: true, f: 'Breve durata e rimborso a 100 alla scadenza: il capitale sarà disponibile nel momento giusto, senza dover vendere sul mercato.' },
      { t: 'Un BTP a 30 anni, che rende di più', ok: false, f: 'Tra un anno dovrebbe venderlo al prezzo del momento: con una scadenza così lunga, anche un piccolo rialzo dei tassi può costare caro.' },
      { t: 'Un CCT a 7 anni, perché oscilla poco', ok: false, f: 'Oscilla meno di un BTP, ma il prezzo tra un anno non è garantito: meglio una scadenza allineata all’obiettivo.' },
    ] },
    { s: 'Federica, 38 anni, vuole investire per circa 7 anni in titoli di Stato e preferisce una cedola che si adegui se i tassi di mercato salgono.', q: 'Quale titolo è più coerente con la sua richiesta?', o: [
      { t: 'Un CCT con scadenza intorno ai 7 anni', ok: true, f: 'La cedola segue l’Euribor a 6 mesi: se i tassi salgono, anche le cedole successive aumentano, e il prezzo oscilla meno.' },
      { t: 'Un BTP a tasso fisso a 7 anni', ok: false, f: 'La cedola resta quella fissata all’emissione: se i tassi salgono non si adegua e il prezzo del titolo scende.' },
      { t: 'Un BTP Valore a 7 anni', ok: false, f: 'Le cedole crescono, ma secondo un calendario fissato all’inizio: non dipendono dall’andamento dei tassi di mercato.' },
    ] },
    { s: 'Michele, 44 anni, ha sottoscritto un BTP Valore all’emissione. Due anni dopo il prezzo sul MOT è salito a 103 e un amico gli consiglia di vendere subito “per prendere il guadagno”. Non gli servono i soldi.', q: 'Cosa fa Michele?', o: [
      { t: 'Confronta il guadagno di oggi con premio e cedole future', ok: true, f: 'Vendendo incassa 3 punti ma rinuncia al premio fedeltà e alle cedole crescenti: la scelta va fatta con i numeri, non d’impulso.' },
      { t: 'Vende subito: un guadagno va sempre incassato', ok: false, f: 'Non è una regola: se il titolo è ancora adatto al suo piano, vendere può costargli il premio e i rendimenti futuri.' },
      { t: 'Vende e ricompra sul MOT per avere di nuovo il premio', ok: false, f: 'Il premio spetta solo a chi sottoscrive all’emissione e conserva il titolo fino a scadenza: ricomprandolo sul mercato lo perde.' },
    ] },
    { s: 'Teresa, 58 anni, confronta un BTP e un’obbligazione societaria con lo stesso rendimento lordo ipotetico del 4% e scadenza simile. Le sembrano equivalenti.', q: 'Cosa fa Teresa?', o: [
      { t: 'Calcola il rendimento netto di entrambi', ok: true, f: 'Al 12,5% il BTP rende il 3,5% netto, al 26% la societaria circa il 2,96%. E il rischio dell’emittente è diverso.' },
      { t: 'Le considera identiche e sceglie a caso', ok: false, f: 'Le aliquote sono diverse: a parità di lordo, la societaria rende meno al netto, e il rischio di credito non è lo stesso.' },
      { t: 'Sceglie la societaria perché diversifica', ok: false, f: 'Diversificare è utile, ma non giustifica ignorare che, a parità di lordo, il netto della societaria è più basso.' },
    ] },
  ],
  tip: 'Prima di scegliere un titolo di Stato, fai coincidere la scadenza con il tuo obiettivo e confronta i rendimenti al netto: il 12,5% fa la differenza.',
});
