FQC(35, {
  intro: 'Anche le aziende si finanziano emettendo obbligazioni. Il rating ti aiuta a capire quanto è affidabile chi ti chiede un prestito.',
  cards: [
    { t: 'Perché le aziende emettono bond', x: 'Le imprese emettono obbligazioni per finanziare investimenti, acquisizioni o rimborsare debiti, senza cedere quote di proprietà. In cambio di solito pagano un rendimento più alto di un titolo di Stato di pari durata dello stesso Paese.', v: { k: 'steps', s: ['L’azienda ha bisogno di capitale', 'Emette obbligazioni', 'Paga le cedole', 'Rimborsa a scadenza'] } },
    { t: 'Il rating', x: 'È un giudizio sulla capacità dell’emittente di pagare cedole e capitale. Le agenzie principali sono S&P Global, Moody’s e Fitch. Nella scala di S&P e Fitch si va da AAA, massima affidabilità, a D, insolvenza.', v: { k: 'icons', d: [['🟢', 'AAA: massima qualità'], ['🟡', 'BBB: qualità adeguata'], ['🟠', 'BB e sotto: speculativo'], ['🔴', 'D: insolvenza']] } },
    { t: 'Investment grade e high yield', x: 'Da AAA a BBB− (Baa3 per Moody’s) si parla di investment grade: rischio di insolvenza contenuto. Da BB+ in giù i titoli sono high yield, o speculativi: rendono di più perché il rischio di default è più alto.', v: { k: 'vs', a: ['Investment grade', 'Da AAA a BBB−'], b: ['High yield', 'Da BB+ in giù'] } },
    { t: 'Più rischio, più spread', x: 'Gli investitori chiedono un premio per il rischio di credito: più basso è il rating, più alto è lo spread rispetto ai titoli privi di rischio. I valori del grafico sono ipotetici e servono solo a mostrare la tendenza.', v: { k: 'bars', d: [['AAA', 0.4], ['A', 0.9], ['BBB', 1.5], ['BB', 3], ['B', 5]], u: '%' } },
    { t: 'Fallen angel e rising star', x: 'Un emittente che perde l’investment grade è un “fallen angel”. Alcuni fondi, per regolamento, possono tenere solo titoli investment grade e devono vendere: il prezzo può scendere più del previsto. Il percorso opposto è la “rising star”.', v: { k: 'scale', a: 'Investment grade', b: 'High yield', d: [['A', 15], ['BBB−', 42], ['BB+', 58], ['B', 85]] } },
    { t: 'Un parere, non una garanzia', x: 'Il rating è un’opinione e può cambiare: le agenzie lo rivedono e segnalano l’outlook (positivo, stabile o negativo). Spesso è pagato dall’emittente stesso. Usalo come punto di partenza, non come verdetto.', v: { k: 'stat', n: 'BBB−', l: 'ultimo gradino dell’investment grade per S&P e Fitch' } },
  ],
  terms: [
    ['Obbligazione societaria', 'Titolo di debito emesso da un’impresa per finanziarsi; detta anche corporate bond.'],
    ['Rating', 'Giudizio di un’agenzia specializzata sulla capacità di un emittente di rimborsare i debiti.'],
    ['Agenzia di rating', 'Società che valuta il merito di credito degli emittenti, come S&P Global, Moody’s e Fitch.'],
    ['Investment grade', 'Fascia di giudizio da AAA a BBB−: emittenti con rischio di insolvenza contenuto.'],
    ['High yield', 'Titoli con giudizio BB+ o inferiore: rendono di più perché il rischio di default è più alto.'],
    ['Spread di credito', 'Rendimento aggiuntivo di un bond rispetto a un titolo privo di rischio di pari durata.'],
    ['Fallen angel', 'Emittente declassato dalla fascia investment grade a quella speculativa.'],
    ['Outlook', 'Indicazione dell’agenzia sulla probabile direzione futura del giudizio: positivo, stabile o negativo.'],
  ],
  tf: [
    ['Un rating BBB− è ancora investment grade.', true, 'Per S&P e Fitch BBB− è l’ultimo gradino dell’investment grade; per Moody’s l’equivalente è Baa3.'],
    ['Un rating AAA garantisce che l’emittente non farà mai default.', false, 'Mito: il rating è un’opinione sulla probabilità di insolvenza, non una garanzia. Anche emittenti con voti alti possono essere declassati.'],
    ['I titoli high yield offrono rendimenti più alti perché sono più rischiosi.', true, 'Il rendimento extra compensa una probabilità di default più alta e perdite potenzialmente maggiori.'],
    ['Le cedole delle obbligazioni societarie sono tassate al 12,5% come quelle dei BTP.', false, 'Le obbligazioni societarie sono tassate al 26%. Il 12,5% vale per i titoli di Stato italiani e white list e per gli enti sovranazionali.'],
    ['Un fallen angel è un emittente passato da investment grade a high yield.', true, 'Il declassamento può costringere alcuni investitori istituzionali a vendere, causando forti cali di prezzo.'],
    ['Un rendimento molto più alto di quello di titoli simili è di per sé un buon affare.', false, 'Mito: un rendimento molto sopra la media di solito segnala che il mercato vede un rischio di credito elevato.'],
    ['Molte obbligazioni societarie hanno un taglio minimo di 100.000 €.', true, 'Sono pensate per gli investitori istituzionali: con piccole cifre si usano spesso fondi ed ETF o emissioni con taglio ridotto.'],
    ['Dopo l’emissione, il rating di un’obbligazione non può più cambiare.', false, 'Il rating viene rivisto periodicamente e può essere alzato (upgrade) o abbassato (downgrade) in base ai conti e al contesto.'],
    ['Un’obbligazione callable può essere rimborsata in anticipo dall’emittente.', true, 'Di solito l’emittente la richiama quando i tassi scendono: l’investitore deve reinvestire a rendimenti più bassi.'],
    ['A parità di scadenza, un bond con rating B ha di solito uno spread più basso di uno con rating A.', false, 'È il contrario: un rating più basso significa più rischio, quindi gli investitori chiedono uno spread più alto.'],
  ],
  mcq: [
    { q: 'Quale di questi rating rientra nella fascia high yield?', a: 'BB+', w: ['BBB−', 'A', 'AA+'], e: 'Sotto BBB− (Baa3 per Moody’s) si entra nella fascia speculativa, detta high yield.' },
    { q: 'Quale di queste è una delle principali agenzie di rating?', a: 'Moody’s', w: ['CONSOB', 'Borsa Italiana', 'Banca d’Italia'], e: 'S&P Global, Moody’s e Fitch sono le agenzie più note. CONSOB e Banca d’Italia sono autorità di vigilanza, Borsa Italiana gestisce mercati.' },
    { q: 'Un BTP rende (ipoteticamente) il 3,5% e un bond societario di pari durata il 5%. Qual è lo spread del bond rispetto al BTP?', a: '150 punti base', w: ['15 punti base', '85 punti base', '500 punti base'], e: '5% − 3,5% = 1,5 punti percentuali = 150 punti base: è il compenso extra chiesto per il rischio dell’azienda.' },
    { q: 'Cosa succede di solito al prezzo di un bond quando il rating dell’emittente viene abbassato?', a: 'Tende a scendere', w: ['Tende a salire', 'Resta invariato per legge', 'Viene rimborsato subito'], e: 'Il mercato chiede un rendimento più alto per il rischio maggiore: con una cedola fissa, è il prezzo a dover scendere.' },
    { q: 'Perché un emittente rimborsa in anticipo un’obbligazione callable?', a: 'Per rifinanziarsi a tassi più bassi', w: ['Perché i tassi sono saliti molto', 'Perché il suo rating è peggiorato', 'Perché gli investitori lo chiedono'], e: 'Se i tassi scendono conviene rimborsare il vecchio debito e riemetterne uno più economico: l’investitore perde la cedola alta.' },
    { q: 'Cosa indica un outlook negativo su un rating A?', a: 'Un possibile declassamento futuro', w: ['Un default già avvenuto', 'Un rating già sceso a BBB', 'Un aumento sicuro della cedola'], e: 'L’outlook segnala la direzione probabile del rating nei mesi successivi: non è un declassamento già avvenuto.' },
    { q: 'Qual è un limite noto dei rating?', a: 'Spesso li paga l’emittente valutato', w: ['Li stabilisce la BCE per legge', 'Valgono solo per i titoli di Stato', 'Non cambiano mai nel tempo'], e: 'Nel modello “paga l’emittente” c’è un potenziale conflitto di interessi. In Europa le agenzie sono vigilate dall’ESMA.' },
    { q: 'Due bond con la stessa scadenza: uno AA rende il 3%, uno B l’8% (dati ipotetici). Cosa spiega la differenza?', a: 'Il maggior rischio di default del bond B', w: ['La scadenza più lunga del bond B', 'I costi di Borsa più alti del bond AA', 'La garanzia statale del bond B'], e: 'Lo spread più alto del bond B compensa una probabilità di insolvenza e perdite attese molto più elevate.' },
  ],
  fill: [
    { s: 'I rating da AAA a BBB− formano la fascia ___.', a: 'investment grade', w: ['high yield', 'junk bond', 'default'] },
    { s: 'Le obbligazioni con rating BB+ o inferiore sono dette ___.', a: 'high yield', w: ['investment grade', 'covered bond', 'titoli di Stato'] },
    { s: 'Il rendimento extra di un bond societario rispetto a un titolo privo di rischio di pari durata è lo spread di ___.', a: 'credito', w: ['denaro', 'cambio', 'Borsa'] },
    { s: 'Un emittente declassato da investment grade a high yield è detto fallen ___.', a: 'angel', w: ['star', 'hero', 'giant'] },
    { s: 'Le cedole delle obbligazioni societarie sono tassate al ___.', a: '26%', w: ['12,5%', '20%', '0,2%'] },
  ],
  order: [
    { q: 'Ordina i rating dal più affidabile al più rischioso (scala S&P e Fitch)', i: ['AAA', 'AA', 'A', 'BBB', 'BB'], e: 'La scala scende da AAA ad AA, A e BBB, ancora investment grade; da BB in giù si entra nella fascia speculativa.' },
    { q: 'Ordina dal rendimento richiesto più basso al più alto, a parità di scadenza', i: ['Titolo di Stato tedesco con rating AAA', 'Bond societario con rating A', 'Bond societario con rating BBB', 'Bond societario con rating B'], e: 'Più alto è il rischio di credito percepito, più rendimento chiedono gli investitori per prestare denaro.' },
  ],
  cat: [
    { q: 'Investment grade o high yield?', g: [['Investment grade', ['AA+', 'A−', 'BBB−', 'Baa3']], ['High yield', ['BB+', 'B', 'CCC', 'Ba1']]] },
    { q: 'Notizia positiva o negativa per chi possiede il bond?', g: [['Positiva', ['Upgrade del rating', 'Outlook da negativo a stabile', 'Debiti dell’azienda in calo']], ['Negativa', ['Downgrade del rating', 'Outlook da stabile a negativo', 'Perdita dell’investment grade']]] },
  ],
  scen: [
    { s: 'Riccardo, 41 anni, trova il bond di una società poco nota con cedola dell’11% e rating CCC. Vorrebbe investirci i 15.000 € messi da parte per l’anticipo della casa.', q: 'Cosa fa Riccardo?', o: [
      { t: 'Non usa quei risparmi: il rischio di default è alto', ok: true, f: 'Un CCC è nella parte più bassa della fascia speculativa: soldi destinati a un obiettivo preciso non possono permettersi un default.' },
      { t: 'Investe tutto: l’11% è un’occasione', ok: false, f: 'Una cedola così alta è il prezzo del rischio: il mercato chiede l’11% proprio perché teme di non essere rimborsato.' },
      { t: 'Investe tutto ma venderà al primo calo', ok: false, f: 'I bond di emittenti in difficoltà possono crollare all’improvviso e diventare difficili da vendere: l’uscita rapida non è garantita.' },
    ] },
    { s: 'Laura, 55 anni, ha in portafoglio il bond di un’azienda che viene declassata da BBB− a BB+. Il prezzo scende del 6%. Non le servono i soldi a breve.', q: 'Cosa fa Laura?', o: [
      { t: 'Studia i motivi del declassamento e il peso del titolo', ok: true, f: 'Il rischio è cambiato: serve capire se l’azienda può ancora pagare e se quell’esposizione è sostenibile, senza agire d’impulso.' },
      { t: 'Vende subito in automatico', ok: false, f: 'Spesso il prezzo riflette già la notizia, a volte amplificata dalle vendite forzate dei fondi: vendere senza analisi può fissare la perdita.' },
      { t: 'Raddoppia la posizione perché ora rende di più', ok: false, f: 'Un rendimento più alto riflette un rischio più alto: aumentare l’esposizione senza analisi concentra ancora di più il portafoglio.' },
    ] },
    { s: 'Pietro, 33 anni, vuole investire 20.000 € in obbligazioni societarie per migliorare il rendimento rispetto ai titoli di Stato.', q: 'Come imposta il portafoglio?', o: [
      { t: 'Distribuisce il capitale su molti emittenti e settori', ok: true, f: 'Con molti emittenti un singolo default pesa poco sul totale: un fondo o ETF obbligazionario può aiutare a diversificare.' },
      { t: 'Compra un solo bond con rating A, perché è sicuro', ok: false, f: 'Anche un buon rating può peggiorare: concentrare tutto su un emittente espone a un unico rischio di credito.' },
      { t: 'Compra solo bond high yield per massimizzare la cedola', ok: false, f: 'Più rendimento significa più rischio: un portafoglio solo speculativo può subire perdite pesanti nelle fasi di crisi.' },
    ] },
    { s: 'Simona, 49 anni, valuta un bond decennale con cedola del 6%, richiamabile dall’emittente dopo 2 anni. Pensa di incassare il 6% per tutti i 10 anni.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che potrebbe essere rimborsata dopo soli 2 anni', ok: true, f: 'Se i tassi scendono l’emittente probabilmente lo richiama: Simona riavrebbe il capitale proprio quando reinvestire rende meno.' },
      { t: 'Niente: il 6% è assicurato per 10 anni', ok: false, f: 'La clausola call dà all’emittente il diritto di rimborsare prima: la cedola alta potrebbe durare solo 2 anni.' },
      { t: 'Che la clausola call va a suo vantaggio', ok: false, f: 'L’opzione appartiene all’emittente, che la usa quando gli conviene: per questo i bond callable pagano di solito un po’ di più.' },
    ] },
  ],
  tip: 'Il rating è un buon punto di partenza, non la fine dell’analisi: guarda anche scadenza, clausole, settore e quanto pesa ogni emittente nel tuo portafoglio.',
});
