FQC(36, {
  intro: 'La duration misura quanto il prezzo di un’obbligazione reagisce ai tassi: è il numero chiave per capire e misurare il rischio tasso.',
  cards: [
    { t: 'Cos’è il rischio tasso', x: 'È il rischio che il prezzo di un’obbligazione scenda perché i tassi di mercato salgono. Riguarda anche i titoli di Stato più solidi e pesa soprattutto se devi vendere prima della scadenza.', v: { k: 'icons', d: [['📈', 'I tassi salgono'], ['📉', 'I prezzi scendono'], ['⏳', 'Più duration, più effetto']] } },
    { t: 'La duration di Macaulay', x: 'È la durata media finanziaria del titolo: la media dei tempi in cui ricevi i flussi (cedole e rimborso), pesata per il loro valore attuale. Si misura in anni ed è minore della scadenza, o uguale per uno zero coupon.', v: { k: 'stat', n: '≤ scadenza', l: 'in un’obbligazione ordinaria la duration non supera la vita residua' } },
    { t: 'La duration modificata', x: 'Trasforma la duration in sensibilità: indica di quanto varia in percentuale il prezzo per ogni punto percentuale di variazione del rendimento. È un’approssimazione, precisa soprattutto per piccole variazioni.', v: { k: 'formula', f: 'Variazione % del prezzo ≈ − duration modificata × variazione del rendimento', n: 'Es.: duration 7, tassi +1 punto → prezzo ≈ −7%' } },
    { t: 'Cosa fa salire la duration', x: 'La duration è più alta se la scadenza è più lunga, se la cedola è più bassa e se i rendimenti sono più bassi. Uno zero coupon ha duration pari alla scadenza, perché tutto il valore arriva alla fine.', v: { k: 'scale', a: 'Duration bassa', b: 'Duration alta', d: [['BOT 6 mesi', 3], ['BTP 3 anni', 15], ['BTP 10 anni', 43], ['BTP 30 anni', 90]] } },
    { t: 'Stessa notizia, effetti diversi', x: 'Se i tassi salgono di 1 punto, un titolo con duration modificata 2 perde circa il 2%, uno con duration 8 circa l’8% e uno con duration 18 circa il 18%. Se i tassi scendono, succede il contrario.', v: { k: 'bars', d: [['Duration 2', -2], ['Duration 8', -8], ['Duration 18', -18]], u: '%' } },
    { t: 'Due rischi che si compensano', x: 'Se i tassi salgono il prezzo scende, ma reinvesti le cedole a tassi più alti; se scendono avviene il contrario. Se il tuo orizzonte è simile alla duration, i due effetti tendono a compensarsi.', v: { k: 'vs', a: ['Rischio di prezzo', 'Tassi su: il titolo vale meno'], b: ['Rischio di reinvestimento', 'Tassi giù: le cedole rendono meno'] } },
  ],
  terms: [
    ['Rischio tasso', 'Possibilità che il prezzo di un titolo scenda per un aumento dei tassi di mercato.'],
    ['Duration di Macaulay', 'Durata media finanziaria: media dei tempi dei flussi, pesata per il loro valore attuale.'],
    ['Duration modificata', 'Variazione percentuale stimata del prezzo per ogni punto di variazione del rendimento.'],
    ['Convessità', 'Curvatura della relazione tra prezzo e rendimento, che la stima lineare non coglie.'],
    ['Rischio di reinvestimento', 'Rischio di dover reinvestire cedole o capitale a tassi più bassi del previsto.'],
    ['Immunizzazione', 'Strategia che allinea duration e orizzonte per compensare rischio di prezzo e di reinvestimento.'],
    ['Orizzonte d’investimento', 'Periodo per cui pensi di tenere l’investimento prima di usare il denaro.'],
    ['Duration di portafoglio', 'Media delle duration dei titoli posseduti, pesata per il valore di ciascuno.'],
  ],
  tf: [
    ['Uno zero coupon ha una duration pari alla sua scadenza.', true, 'Non ci sono cedole intermedie: l’unico flusso arriva alla fine, quindi la durata media coincide con la vita del titolo.'],
    ['A parità di scadenza, un titolo con cedola più alta ha una duration più alta.', false, 'È il contrario: cedole alte restituiscono più valore prima, abbassano la durata media e quindi la sensibilità ai tassi.'],
    ['Con duration modificata 6, un rialzo dei tassi di 1 punto fa scendere il prezzo di circa il 6%.', true, 'Variazione ≈ −6 × 1% = −6%. È una stima: per variazioni ampie la convessità rende la perdita effettiva un po’ minore.'],
    ['I titoli di Stato non hanno rischio tasso perché lo Stato è solvibile.', false, 'Mito: la solidità dell’emittente riguarda il rischio di credito. Anche un BTP a 30 anni può perdere molto se i tassi salgono.'],
    ['Il prezzo di un CCT è in genere poco sensibile alle variazioni dei tassi di mercato.', true, 'La cedola si adegua all’Euribor ogni sei mesi, quindi la sua duration rispetto ai tassi è molto bassa; resta sensibile allo spread.'],
    ['Un ETF obbligazionario con duration 15 è adatto a chi vuole oscillazioni minime.', false, 'Con duration 15, un rialzo dei tassi di 1 punto può costare circa il 15%: è uno strumento che oscilla molto.'],
    ['A parità di altre condizioni, più è lunga la scadenza, più è alta la duration.', true, 'I flussi arrivano più lontano nel tempo: la durata media aumenta e il prezzo diventa più sensibile ai tassi.'],
    ['La duration di un titolo con cedole è maggiore della sua scadenza.', false, 'È minore: le cedole pagate prima abbassano la durata media. È uguale alla scadenza solo per uno zero coupon.'],
    ['Se i tassi scendono, i titoli con duration alta guadagnano di più di quelli con duration bassa.', true, 'La sensibilità vale nei due sensi: duration alta significa guadagni maggiori se i tassi scendono e perdite maggiori se salgono.'],
    ['Tenere un titolo fino a scadenza elimina il rischio di reinvestimento delle cedole.', false, 'Le cedole incassate prima della scadenza vanno reinvestite ai tassi del momento, che possono essere più bassi di quelli iniziali.'],
  ],
  mcq: [
    { q: 'Un titolo ha duration modificata 8. I tassi salgono di 0,5 punti. Come cambia circa il prezzo?', a: '−4%', w: ['−8%', '+4%', '−0,5%'], e: 'Variazione ≈ −8 × 0,5% = −4%. Se i tassi fossero scesi di 0,5 punti, il prezzo sarebbe salito di circa il 4%.' },
    { q: 'Quale di questi titoli ha la duration più alta?', a: 'Zero coupon a 20 anni', w: ['BTP a 20 anni con cedola 5%', 'BTP a 5 anni con cedola 3%', 'BOT a 12 mesi'], e: 'Lo zero coupon a 20 anni ha duration 20: senza cedole, tutto il valore arriva alla scadenza.' },
    { q: 'Che cosa misura la duration modificata?', a: 'La sensibilità del prezzo ai tassi', w: ['La probabilità di default', 'Il numero di cedole residue', 'Il tempo alla prossima cedola'], e: 'Indica la variazione percentuale approssimata del prezzo per ogni punto percentuale di variazione del rendimento.' },
    { q: 'Ti servono i soldi tra 2 anni e temi un rialzo dei tassi. Quale scelta limita il rischio tasso?', a: 'Titoli con duration vicina a 2 anni', w: ['Titoli con duration di 20 anni', 'Uno zero coupon a 30 anni', 'Un ETF di BTP a lunga scadenza'], e: 'Allineare la duration all’orizzonte limita l’effetto dei tassi: tra 2 anni il titolo sarà vicino al rimborso.' },
    { q: 'Perché, a parità di scadenza, una cedola più alta riduce la duration?', a: 'Perché anticipa una parte maggiore dei flussi', w: ['Perché allunga la scadenza', 'Perché abbassa il rating', 'Perché rende il titolo meno liquido'], e: 'Con cedole alte ricevi più valore nei primi anni: la media dei tempi dei flussi si accorcia.' },
    { q: 'Un portafoglio ha metà del valore in titoli con duration 2 e metà in titoli con duration 10. Qual è la sua duration?', a: '6', w: ['12', '10', '2'], e: 'La duration di portafoglio è la media ponderata: 50% × 2 + 50% × 10 = 6.' },
    { q: 'A cosa serve tenere conto della convessità?', a: 'A correggere la stima per grandi variazioni', w: ['A misurare il rischio di default', 'A calcolare la cedola variabile', 'Ad azzerare il rischio tasso'], e: 'La relazione prezzo-rendimento è curva: per grandi variazioni dei tassi la stima lineare della duration si allontana dal prezzo reale.' },
    { q: 'Sofia dice: “Ho un ETF obbligazionario, quindi non posso perdere”. Cosa le sfugge?', a: 'Il suo prezzo scende se i tassi salgono', w: ['Gli ETF obbligazionari sono garantiti dalla BCE', 'Gli ETF obbligazionari non sono quotati', 'Gli ETF obbligazionari hanno duration zero'], e: 'Un ETF obbligazionario ha una sua duration: se i tassi salgono il suo valore scende, e non ha una scadenza che lo riporti a 100.' },
  ],
  fill: [
    { s: 'La duration di uno zero coupon è uguale alla sua ___.', a: 'scadenza', w: ['cedola', 'convessità', 'liquidità'] },
    { s: 'Con duration modificata 5, un rialzo dei tassi di 1 punto fa scendere il prezzo di circa il ___.', a: '5%', w: ['1%', '0,5%', '10%'] },
    { s: 'La curvatura della relazione tra prezzo e rendimento si chiama ___.', a: 'convessità', w: ['duration', 'liquidità', 'volatilità'] },
    { s: 'A parità di scadenza, una cedola più alta rende la duration più ___.', a: 'bassa', w: ['alta', 'lunga', 'instabile'] },
    { s: 'Il rischio di dover investire le cedole a tassi più bassi si chiama rischio di ___.', a: 'reinvestimento', w: ['liquidità', 'cambio', 'credito'] },
  ],
  order: [
    { q: 'Ordina dalla duration più bassa alla più alta', i: ['BOT a 6 mesi', 'BTP a 3 anni', 'BTP a 10 anni', 'BTP a 30 anni'], e: 'Con cedole simili, la duration cresce con la scadenza: da circa mezzo anno per il BOT a molti anni per il BTP trentennale.' },
    { q: 'I tassi salgono di 1 punto: ordina dalla perdita più piccola alla più grande', i: ['CCT', 'BTP a 2 anni', 'BTP a 7 anni', 'Zero coupon a 25 anni'], e: 'La perdita cresce con la duration: il CCT adegua la cedola ai tassi, lo zero coupon a 25 anni ha duration 25.' },
  ],
  cat: [
    { q: 'Aumenta o riduce la duration?', g: [['Aumenta la duration', ['Scadenza più lunga', 'Cedola più bassa', 'Nessuna cedola']], ['Riduce la duration', ['Scadenza più breve', 'Cedola più alta', 'Cedola che si adegua ai tassi']]] },
    { q: 'Chi trae vantaggio da un rialzo dei tassi e chi ne è penalizzato?', g: [['Ne trae vantaggio', ['Chi deve investire nuova liquidità', 'Chi reinveste le cedole', 'Chi ha titoli in scadenza da reinvestire']], ['Ne è penalizzato', ['Chi ha un BTP a 30 anni', 'Chi ha un ETF a lunga duration', 'Chi deve vendere presto un titolo lungo']]] },
  ],
  scen: [
    { s: 'Giovanni, 58 anni, ha 40.000 € che gli serviranno tra 2 anni. Sceglie tra un ETF di titoli di Stato con duration 2 e uno con duration 17, che oggi rende un po’ di più.', q: 'Quale ETF sceglie Giovanni?', o: [
      { t: 'Quello con duration 2', ok: true, f: 'La sensibilità ai tassi è bassa e coerente con il suo orizzonte: un rialzo dei tassi peserebbe poco sul capitale che gli serve.' },
      { t: 'Quello con duration 17, perché rende di più', ok: false, f: 'Con un rialzo dei tassi di 1 punto potrebbe perdere circa il 17% proprio quando deve usare i soldi.' },
      { t: 'Metà e metà, per diversificare', ok: false, f: 'Mescolare non risolve il problema: metà del capitale resterebbe esposta a forti oscillazioni con un orizzonte di soli 2 anni.' },
    ] },
    { s: 'Martina, 31 anni, ha un ETF obbligazionario con duration 9. In un anno i tassi salgono di 1,5 punti e l’ETF perde circa il 13%. Pensava che le obbligazioni fossero sicure.', q: 'Come reagisce Martina?', o: [
      { t: 'Capisce che il calo è coerente con la duration', ok: true, f: '9 × 1,5 ≈ 13%: la perdita era prevedibile. Ora valuta se il suo orizzonte è adatto; intanto i rendimenti futuri sono più alti.' },
      { t: 'Vende e passa alle cripto per recuperare', ok: false, f: 'Sostituire un rischio che non aveva capito con uno ancora più alto non è una strategia: aumenta solo la possibilità di nuove perdite.' },
      { t: 'Pensa che l’ETF sia difettoso e fa reclamo', ok: false, f: 'L’ETF ha fatto esattamente ciò che la sua duration indicava: il prezzo dei titoli lunghi scende quando i tassi salgono.' },
    ] },
    { s: 'Nicola, 45 anni, è convinto che i tassi scenderanno presto e vuole mettere tutti i suoi risparmi in uno zero coupon a 30 anni per guadagnare il più possibile.', q: 'Cosa dovrebbe fare Nicola?', o: [
      { t: 'Evitare di scommettere tutto su una previsione', ok: true, f: 'Con una duration di circa 30 anni un errore costa caro: se i tassi salgono di appena 1 punto, il titolo perde circa un quarto del valore.' },
      { t: 'Investire tutto: se ha ragione guadagnerà molto', ok: false, f: 'Il guadagno potenziale è alto, ma lo è anche la perdita: nessuno prevede i tassi con certezza.' },
      { t: 'Usare un prestito per comprarne di più', ok: false, f: 'La leva moltiplica un rischio già enorme: un rialzo dei tassi potrebbe causare perdite superiori al capitale proprio.' },
    ] },
    { s: 'Beatrice, 39 anni, mette da parte 25.000 € per l’università della figlia, tra 7 anni. Vuole limitare sia l’effetto dei tassi sul prezzo sia quello sul reinvestimento delle cedole.', q: 'Quale portafoglio è più coerente?', o: [
      { t: 'Titoli con duration complessiva vicina a 7 anni', ok: true, f: 'È l’idea dell’immunizzazione: con duration pari all’orizzonte, rischio di prezzo e di reinvestimento tendono a compensarsi.' },
      { t: 'Titoli con duration di 25 anni, che rendono di più', ok: false, f: 'Tra 7 anni dovrebbe vendere titoli ancora molto sensibili ai tassi: un rialzo potrebbe ridurre parecchio il capitale.' },
      { t: 'Tutto sul conto corrente senza interessi', ok: false, f: 'Elimina il rischio tasso, ma rinuncia a ogni rendimento per 7 anni e lascia il capitale esposto all’inflazione.' },
    ] },
  ],
  tip: 'Prima di comprare un titolo o un ETF obbligazionario, guarda la duration: ti dice quanto puoi perdere, in percentuale, se i tassi salgono di un punto.',
});
