FQC(37, {
  intro: 'La curva dei rendimenti mette in fila i tassi per scadenza: la sua forma racconta cosa si aspetta il mercato da economia e banche centrali.',
  cards: [
    { t: 'Che cos’è la curva', x: 'È il grafico che collega i rendimenti di titoli dello stesso emittente con scadenze diverse, ad esempio i titoli di Stato italiani da 3 mesi a 30 anni. In orizzontale c’è la scadenza, in verticale il rendimento. Nel grafico, dati ipotetici.', v: { k: 'bars', d: [['3 mesi', 2], ['2 anni', 2.4], ['5 anni', 2.9], ['10 anni', 3.5], ['30 anni', 4.1]], u: '%' } },
    { t: 'Tre forme principali', x: 'Normale: i rendimenti lunghi superano quelli brevi. Piatta: sono simili su tutte le scadenze. Invertita: i rendimenti brevi superano quelli lunghi. La forma cambia nel tempo con tassi, crescita e inflazione attese.', v: { k: 'icons', d: [['↗️', 'Normale: lungo > breve'], ['➡️', 'Piatta: lungo ≈ breve'], ['↘️', 'Invertita: breve > lungo']] } },
    { t: 'Chi muove i due estremi', x: 'La parte breve segue da vicino i tassi della banca centrale, come la BCE. La parte lunga dipende di più dalle attese su crescita e inflazione e dal premio a termine, il compenso per vincolare il denaro più a lungo.', v: { k: 'vs', a: ['Parte breve', 'Tassi della banca centrale'], b: ['Parte lunga', 'Crescita, inflazione e premio a termine'] } },
    { t: 'Misurare la pendenza', x: 'La pendenza si misura spesso come differenza tra il rendimento a 10 anni e quello a 2 anni. Se è positiva la curva è normale, se è vicina a zero è piatta, se è negativa è invertita.', v: { k: 'formula', f: 'Pendenza = rendimento a 10 anni − rendimento a 2 anni', n: 'Es. ipotetico: 3,5% − 2,4% = +1,1 punti, cioè +110 punti base' } },
    { t: 'Quando la curva si inverte', x: 'Una curva invertita indica che il mercato si aspetta tassi più bassi in futuro, spesso per un rallentamento. Storicamente, negli Stati Uniti, ha preceduto diverse recessioni, ma con anticipi molto variabili e qualche falso allarme.', v: { k: 'steps', s: ['La banca centrale alza i tassi', 'Salgono i rendimenti brevi', 'Il mercato prevede un rallentamento', 'I rendimenti lunghi restano più bassi'] } },
    { t: 'Irripidimento e appiattimento', x: 'Se la distanza tra rendimenti lunghi e brevi aumenta, la curva si irripidisce; se diminuisce, si appiattisce. Può accadere perché si muove la parte breve, quella lunga o entrambe.', v: { k: 'vs', a: ['Irripidimento', 'Distanza lungo-breve in aumento'], b: ['Appiattimento', 'Distanza lungo-breve in calo'] } },
  ],
  terms: [
    ['Curva dei rendimenti', 'Grafico dei rendimenti di titoli dello stesso emittente in funzione della scadenza.'],
    ['Curva normale', 'Forma in cui i rendimenti a lungo termine superano quelli a breve: inclinata verso l’alto.'],
    ['Curva piatta', 'Forma in cui i rendimenti sono simili su tutte le scadenze.'],
    ['Curva invertita', 'Forma in cui i rendimenti a breve superano quelli a lungo termine.'],
    ['Premio a termine', 'Rendimento extra richiesto per vincolare il denaro più a lungo, a fronte di maggiore incertezza.'],
    ['Irripidimento', 'Aumento della differenza tra i rendimenti a lungo e quelli a breve termine.'],
    ['Appiattimento', 'Riduzione della differenza tra i rendimenti a lungo e quelli a breve termine.'],
    ['Pendenza', 'Differenza tra un rendimento a lunga e uno a breve scadenza, ad esempio 10 anni meno 2 anni.'],
  ],
  tf: [
    ['In una curva normale i rendimenti a lungo termine sono più alti di quelli a breve.', true, 'È la forma più comune: chi presta per più anni chiede un premio per l’incertezza su tassi e inflazione.'],
    ['In una curva invertita i titoli a lunga scadenza rendono più di quelli a breve.', false, 'È il contrario: nella curva invertita i rendimenti a breve superano quelli a lungo termine.'],
    ['La parte breve della curva è molto influenzata dai tassi decisi dalla banca centrale.', true, 'I rendimenti a pochi mesi seguono da vicino i tassi ufficiali, come quelli della BCE nell’area euro.'],
    ['Una curva invertita annuncia con certezza una recessione entro pochi mesi.', false, 'Mito: storicamente ha spesso preceduto recessioni, ma con ritardi molto variabili e non sempre. È un segnale, non una certezza.'],
    ['Se il rendimento a 10 anni sale e quello a 2 anni resta fermo, la curva si irripidisce.', true, 'La distanza tra lungo e breve aumenta: è proprio la definizione di irripidimento.'],
    ['La curva dei rendimenti confronta titoli di emittenti diversi con la stessa scadenza.', false, 'Confronta titoli dello stesso emittente con scadenze diverse. Il confronto tra emittenti alla stessa scadenza è uno spread.'],
    ['In una curva piatta i rendimenti sono simili per tutte le scadenze.', true, 'Breve e lungo termine offrono rendimenti vicini: il mercato non chiede un premio rilevante per le scadenze lunghe.'],
    ['Con una curva invertita conviene sempre comprare i titoli più lunghi.', false, 'Non esiste una regola fissa: i titoli brevi rendono di più, quelli lunghi fissano il rendimento più a lungo. Dipende dall’orizzonte.'],
    ['Le attese di inflazione futura pesano molto sulla parte lunga della curva.', true, 'Chi presta per molti anni vuole essere compensato per l’inflazione attesa in quel periodo: se sale, tendono a salire i rendimenti lunghi.'],
    ['Con una curva normale, allungare la scadenza aumenta il rendimento senza aggiungere rischi.', false, 'Mito: il rendimento extra è il compenso per un rischio maggiore, soprattutto il rischio tasso legato a una duration più lunga.'],
  ],
  mcq: [
    { q: 'Rendimenti ipotetici: 2 anni al 3%, 10 anni al 4,2%. Che forma ha la curva?', a: 'Normale', w: ['Invertita', 'Piatta', 'A campana'], e: 'Il rendimento a lungo è più alto di quello a breve: la curva è inclinata verso l’alto, cioè normale.' },
    { q: 'Rendimenti ipotetici: 2 anni al 4,5%, 10 anni al 3,8%. Quanto vale la pendenza 10-2 anni?', a: '−70 punti base', w: ['+70 punti base', '−7 punti base', '+830 punti base'], e: '3,8% − 4,5% = −0,7 punti = −70 punti base: su questo tratto la curva è invertita.' },
    { q: 'Cosa influenza di più la parte breve della curva?', a: 'I tassi ufficiali della banca centrale', w: ['Il prezzo delle azioni', 'Il cambio euro-dollaro', 'Il rating delle singole aziende'], e: 'I rendimenti a pochi mesi seguono i tassi decisi dalla banca centrale; la parte lunga dipende più da attese e premi.' },
    { q: 'Perché di solito la curva è inclinata verso l’alto?', a: 'Per il premio richiesto sulle scadenze lunghe', w: ['Perché i titoli lunghi sono più liquidi', 'Perché i titoli brevi sono più rischiosi', 'Perché le cedole lunghe sono esentasse'], e: 'Vincolare il denaro più a lungo espone a più incertezza su tassi e inflazione: gli investitori chiedono un premio a termine.' },
    { q: 'Il 2 anni passa dal 3% al 3,5%, il 10 anni resta al 4%. Cosa fa la curva?', a: 'Si appiattisce', w: ['Si irripidisce', 'Si inverte', 'Resta uguale'], e: 'La distanza tra 10 e 2 anni scende da 100 a 50 punti base: la curva diventa più piatta, ma non è invertita.' },
    { q: 'Cosa segnala spesso una curva invertita?', a: 'Attese di tagli dei tassi e di rallentamento', w: ['Attese di forte inflazione futura', 'Un rialzo certo delle Borse', 'Un default imminente dello Stato'], e: 'Se il mercato prevede tassi più bassi in futuro, i rendimenti lunghi scendono sotto quelli brevi.' },
    { q: 'Quali titoli servono per costruire la curva dei rendimenti dello Stato italiano?', a: 'BOT e BTP con scadenze diverse', w: ['BTP e Bund con la stessa scadenza', 'Azioni e bond dello stesso settore', 'BTP e bond bancari a 10 anni'], e: 'La curva usa titoli dello stesso emittente, qui lo Stato italiano, su scadenze diverse: da pochi mesi a 30 anni e oltre.' },
    { q: 'Paolo vede una curva invertita e vende tutte le azioni “perché la recessione arriva domani”. Qual è l’errore?', a: 'Tratta un segnale incerto come una certezza', w: ['La curva invertita indica crescita forte', 'Le azioni salgono sempre in recessione', 'La curva riguarda solo le materie prime'], e: 'L’inversione ha preceduto molte recessioni, ma con anticipi molto variabili e qualche falso allarme: non è un orologio.' },
  ],
  fill: [
    { s: 'Quando i rendimenti a breve superano quelli a lungo, la curva è ___.', a: 'invertita', w: ['normale', 'ripida', 'convessa'] },
    { s: 'Il rendimento extra chiesto per prestare più a lungo si chiama premio a ___.', a: 'termine', w: ['pronti', 'rischio zero', 'vista'] },
    { s: 'Se la distanza tra rendimenti lunghi e brevi aumenta, la curva si ___.', a: 'irripidisce', w: ['appiattisce', 'inverte', 'azzera'] },
    { s: 'La parte breve della curva segue soprattutto i tassi della banca ___.', a: 'centrale', w: ['commerciale', 'depositaria', 'd’affari'] },
    { s: 'Una curva con rendimenti simili su tutte le scadenze si dice ___.', a: 'piatta', w: ['invertita', 'normale', 'ripida'] },
  ],
  order: [
    { q: 'Ordina dalla pendenza 10-2 anni più negativa alla più positiva (dati ipotetici)', i: ['2 anni 5%, 10 anni 4%', '2 anni 4%, 10 anni 3,8%', '2 anni 3%, 10 anni 3%', '2 anni 2%, 10 anni 3,5%'], e: 'Pendenze: −100, −20, 0 e +150 punti base, dalla curva più invertita a quella più inclinata verso l’alto.' },
    { q: 'Ordina le fasi tipiche di un ciclo di rialzi dei tassi', i: ['La banca centrale alza i tassi ufficiali', 'Salgono i rendimenti a breve', 'La curva si appiattisce', 'Se il breve supera il lungo, la curva si inverte'], e: 'I rialzi colpiscono prima la parte breve; se il mercato prevede un rallentamento, i rendimenti lunghi salgono meno e la curva si inverte.' },
  ],
  cat: [
    { q: 'Curva normale o invertita? (rendimenti ipotetici)', g: [['Normale', ['2 anni 2%, 10 anni 3%', '3 mesi 1%, 30 anni 3,5%', '1 anno 3,2%, 10 anni 4%']], ['Invertita', ['2 anni 4%, 10 anni 3%', '3 mesi 5%, 30 anni 4%', '1 anno 3,5%, 10 anni 3,1%']]] },
    { q: 'Irripidimento o appiattimento?', g: [['Irripidimento', ['Il 10 anni sale, il 2 anni è fermo', 'Il 2 anni scende più del 10 anni', 'Pendenza da +50 a +120 pb']], ['Appiattimento', ['Il 2 anni sale, il 10 anni è fermo', 'Il 10 anni scende più del 2 anni', 'Pendenza da +120 a +50 pb']]] },
  ],
  scen: [
    { s: 'Enrico, 50 anni, vede che la curva è molto inclinata: il BTP a 30 anni rende parecchio più del BOT a 12 mesi. Vorrebbe spostare nel trentennale il suo fondo di emergenza.', q: 'Cosa fa Enrico?', o: [
      { t: 'Tiene il fondo di emergenza su scadenze brevi', ok: true, f: 'Il rendimento extra del lungo termine paga un rischio tasso elevato: un fondo che può servire domani non deve dipendere dal prezzo di un trentennale.' },
      { t: 'Sposta tutto nel BTP a 30 anni', ok: false, f: 'Se i tassi salissero, il titolo potrebbe perdere molto proprio quando gli servono i soldi: il premio non è gratis.' },
      { t: 'Divide il fondo tra 10 e 30 anni', ok: false, f: 'Anche un decennale oscilla parecchio: per denaro che deve essere sempre disponibile servono scadenze brevi.' },
    ] },
    { s: 'Alessia, 27 anni, lavora in banca. Dopo un annuncio della BCE il rendimento del BTP a 2 anni sale molto, quello a 10 anni quasi non si muove. Un cliente le chiede perché.', q: 'Cosa risponde Alessia?', o: [
      { t: 'Il breve segue i tassi BCE, il lungo anche altri fattori', ok: true, f: 'La parte breve reagisce subito alle decisioni di politica monetaria; la lunga dipende anche da crescita, inflazione attesa e premio a termine.' },
      { t: 'È un errore: la curva si muove sempre in parallelo', ok: false, f: 'Breve e lungo termine si muovono spesso in modo diverso: è proprio così che la curva si appiattisce o si irripidisce.' },
      { t: 'Il BTP a 10 anni non è influenzato dai tassi', ok: false, f: 'Anche il decennale dipende dai tassi, ma soprattutto da quelli attesi negli anni futuri, non solo dalla decisione di oggi.' },
    ] },
    { s: 'Vittorio, 63 anni, sta per andare in pensione e vuole un reddito stabile per 10 anni. La curva è invertita: un BOT a 12 mesi rende (ipoteticamente) il 3,8%, un BTP a 10 anni il 3,4%.', q: 'Come ragiona Vittorio?', o: [
      { t: 'Valuta di fissare parte del reddito su scadenze lunghe', ok: true, f: 'Il BOT rende di più oggi, ma andrà rinnovato a tassi ignoti: bloccare una parte su 10 anni rende il reddito più prevedibile.' },
      { t: 'Sceglie solo BOT perché oggi rendono di più', ok: false, f: 'Una curva invertita segnala attese di tassi in calo: tra un anno potrebbe rinnovare a rendimenti più bassi.' },
      { t: 'Aspetta che la curva torni normale per investire', ok: false, f: 'Nessuno sa quando succederà: restare fermo ha un costo e non risolve la scelta.' },
    ] },
    { s: 'Chiara, 36 anni, deve scegliere un mutuo. La curva dei tassi è molto inclinata: il tasso fisso è molto più alto del variabile, legato all’Euribor. Il suo bilancio familiare è già al limite.', q: 'Cosa fa Chiara?', o: [
      { t: 'Verifica se reggerebbe la rata con l’Euribor in rialzo', ok: true, f: 'Il variabile costa meno oggi, ma segue i tassi a breve: con un bilancio già teso, deve sapere cosa succede se salgono.' },
      { t: 'Sceglie il variabile solo perché oggi costa meno', ok: false, f: 'La rata di oggi non è quella di domani: se i tassi a breve salgono, il variabile può diventare più caro del fisso.' },
      { t: 'Sceglie il fisso perché il variabile sale sempre', ok: false, f: 'Non è vero che il variabile sale sempre: la scelta dipende dalla sua capacità di sopportare rate diverse, non da una regola fissa.' },
    ] },
  ],
  tip: 'Guarda la curva come il prezzo del tempo: confronta il rendimento extra delle scadenze lunghe con il rischio tasso in più che ti stai prendendo.',
});
