FQC(38, {
  intro: 'Lo spread BTP-Bund misura quanto rendimento in più chiede il mercato per prestare all’Italia invece che alla Germania.',
  cards: [
    { t: 'Che cos’è lo spread', x: 'È la differenza tra il rendimento del BTP a 10 anni e quello del Bund tedesco a 10 anni. Si esprime in punti base: con il BTP al 3,8% e il Bund al 2,3% (dati ipotetici) lo spread è di 150 punti base.', v: { k: 'formula', f: 'Spread = rendimento BTP 10 anni − rendimento Bund 10 anni', n: 'Es. ipotetico: 3,8% − 2,3% = 1,5 punti = 150 punti base' } },
    { t: 'Il punto base', x: 'Un punto base (pb, in inglese bp) è un centesimo di punto percentuale, cioè lo 0,01%. Quindi 100 punti base fanno 1 punto percentuale. È l’unità usata per misurare differenze di rendimento piccole ma importanti.', v: { k: 'stat', n: '1 pb = 0,01%', l: 'quindi 100 punti base = 1 punto percentuale' } },
    { t: 'Perché proprio la Germania', x: 'Il Bund è il riferimento dell’area euro: la Germania ha un rating molto alto e un mercato del debito molto liquido. Confrontarsi con il Bund permette di isolare il rischio specifico di un Paese rispetto all’emittente considerato più sicuro.', v: { k: 'vs', a: ['BTP', 'Debito italiano, rendimento più alto'], b: ['Bund', 'Debito tedesco, riferimento “sicuro”'] } },
    { t: 'Cosa misura', x: 'Lo spread riflette il premio chiesto per il rischio Italia: dubbi sui conti pubblici, sulla crescita, sulla stabilità politica e differenze di liquidità. Nelle crisi più gravi può includere il timore che un Paese esca dall’euro.', v: { k: 'icons', d: [['🏛️', 'Conti pubblici'], ['🗳️', 'Stabilità politica'], ['📉', 'Crescita'], ['💧', 'Liquidità']] } },
    { t: 'Due modi per allargarsi', x: 'Lo spread sale se il BTP rende di più o se il Bund rende di meno. Nelle fasi di paura molti comprano Bund come rifugio: il rendimento tedesco scende e lo spread si allarga. Nel grafico, dati ipotetici: da 150 a 200 pb.', v: { k: 'bars', d: [['BTP prima', 3.8], ['Bund prima', 2.3], ['BTP dopo', 4.1], ['Bund dopo', 2.1]], u: '%' } },
    { t: 'Una lezione dal 2011', x: 'Durante la crisi del debito sovrano dell’area euro lo spread superò i 500 punti base, nel novembre 2011. Calò poi in modo marcato dopo l’impegno della BCE a difendere l’euro, nell’estate 2012. Dal 2022 la BCE dispone anche dello strumento TPI.', v: { k: 'steps', s: ['Crisi di fiducia', 'Spread oltre 500 pb', 'Impegno della BCE', 'Spread in calo'] } },
  ],
  terms: [
    ['Spread BTP-Bund', 'Differenza tra il rendimento del BTP decennale e quello del titolo tedesco decennale.'],
    ['Punto base', 'Un centesimo di punto percentuale, cioè lo 0,01%.'],
    ['Bund', 'Titolo di Stato tedesco a lungo termine, riferimento per i rendimenti dell’area euro.'],
    ['Benchmark', 'Titolo o indice di riferimento con cui si confrontano rendimenti e prezzi.'],
    ['Flight to quality', 'Fuga degli investitori verso attività considerate più sicure nelle fasi di forte paura.'],
    ['Rischio sovrano', 'Rischio che uno Stato non paghi, o paghi in ritardo, il proprio debito.'],
    ['Rischio di ridenominazione', 'Timore che un debito venga convertito in una nuova valuta più debole, ad esempio uscendo dall’euro.'],
    ['TPI', 'Strumento della BCE, nato nel 2022, per contrastare aumenti disordinati e ingiustificati degli spread.'],
  ],
  tf: [
    ['Lo spread BTP-Bund si calcola di solito sui titoli a 10 anni.', true, 'Il riferimento più usato è il decennale: si confrontano BTP e Bund con scadenza a 10 anni.'],
    ['Uno spread di 250 punti base equivale a 25 punti percentuali.', false, '250 punti base sono 2,5 punti percentuali, perché un punto base vale lo 0,01%.'],
    ['Lo spread può salire anche se il rendimento del BTP resta fermo.', true, 'Se il rendimento del Bund scende, ad esempio per una fuga verso la sicurezza, la differenza aumenta anche con il BTP invariato.'],
    ['Uno spread in aumento indica che il mercato chiede un premio maggiore per prestare all’Italia rispetto alla Germania.', true, 'Più spread significa più rischio percepito sull’Italia, almeno in termini relativi rispetto al Bund.'],
    ['Se lo spread sale, aumentano subito le cedole di tutti i BTP già emessi.', false, 'Mito: le cedole dei BTP esistenti sono fisse. Uno spread più alto fa scendere i loro prezzi e rende più costose le nuove emissioni.'],
    ['Lo spread misura il livello assoluto dei tassi italiani.', false, 'Misura una differenza: l’Italia può pagare tassi più alti anche con spread stabile, se salgono pure i rendimenti tedeschi.'],
    ['Uno spread alto e duraturo rende più costoso per lo Stato finanziare il debito.', true, 'Le nuove emissioni e i titoli da rinnovare pagano rendimenti più alti: l’effetto sulla spesa per interessi arriva gradualmente.'],
    ['Con uno spread basso i BTP non possono perdere valore.', false, 'Mito: anche con spread basso i BTP perdono valore se salgono i tassi in generale, ad esempio quando salgono anche i Bund.'],
    ['Nel novembre 2011 lo spread BTP-Bund superò i 500 punti base.', true, 'Durante la crisi del debito sovrano dell’area euro superò quota 500, segnalando forti timori sulla tenuta dei conti italiani.'],
    ['Il Bund è il riferimento perché è il titolo di Stato con il rendimento più alto dell’area euro.', false, 'È il riferimento perché considerato tra i più sicuri e liquidi: proprio per questo rende di solito meno degli altri titoli dell’area.'],
  ],
  mcq: [
    { q: 'BTP a 10 anni al 4,1% e Bund a 10 anni al 2,6% (dati ipotetici). Quanto vale lo spread?', a: '150 punti base', w: ['15 punti base', '1.500 punti base', '670 punti base'], e: '4,1% − 2,6% = 1,5 punti percentuali, cioè 150 punti base.' },
    { q: 'Quanto vale un punto base?', a: '0,01%', w: ['0,1%', '1%', '0,001%'], e: 'Un punto base è un centesimo di punto percentuale: 100 punti base fanno 1%.' },
    { q: 'Lo spread passa da 180 a 140 punti base. Cosa sappiamo con certezza?', a: 'Il divario BTP-Bund si è ridotto', w: ['Il rendimento del BTP è sceso di 40 pb', 'Il rendimento del Bund è salito di 40 pb', 'Il rating italiano è stato alzato'], e: 'Lo spread misura solo il divario: è sceso di 40 pb, ma può dipendere da un calo del BTP, da un rialzo del Bund o da entrambi.' },
    { q: 'In una fase di forte paura molti investitori comprano Bund. Cosa succede di solito allo spread?', a: 'Tende ad allargarsi', w: ['Tende a restringersi', 'Si azzera', 'Non può cambiare'], e: 'Gli acquisti fanno scendere il rendimento del Bund: se il BTP non segue, la differenza aumenta.' },
    { q: 'Perché uno spread alto e duraturo pesa sui conti pubblici?', a: 'Lo Stato si rifinanzia a tassi più alti', w: ['Lo Stato deve ricomprare tutti i BTP', 'Le cedole già emesse aumentano subito', 'La tassa sui BTP sale al 26%'], e: 'Il debito in scadenza va rinnovato e le nuove emissioni pagano rendimenti più alti: la spesa per interessi cresce nel tempo.' },
    { q: 'Cosa si intende per rischio di ridenominazione?', a: 'Il timore di un ritorno a una valuta nazionale', w: ['Il rischio che cambi il nome del titolo', 'Il rischio di un ritardo nelle cedole', 'Il rischio legato al cambio euro-dollaro'], e: 'Nelle crisi dell’euro il mercato temeva che i debiti venissero convertiti in una nuova valuta svalutata, e chiedeva spread più alti.' },
    { q: 'Il BTP passa dal 3,5% al 3,7%, il Bund dal 2,0% al 2,2% (dati ipotetici). Cosa succede allo spread?', a: 'Resta a 150 punti base', w: ['Sale a 170 punti base', 'Scende a 130 punti base', 'Sale a 370 punti base'], e: 'Entrambi salgono di 20 pb: lo spread non cambia, ma l’Italia paga comunque di più per finanziarsi.' },
    { q: 'Quale di questi fattori tende ad allargare lo spread BTP-Bund?', a: 'Dubbi sulla sostenibilità del debito italiano', w: ['Un miglioramento del rating italiano', 'Una crescita italiana più forte', 'Un calo del deficit pubblico italiano'], e: 'Se crescono i timori sui conti pubblici, gli investitori chiedono un premio più alto per tenere BTP invece di Bund.' },
  ],
  fill: [
    { s: 'Un punto base vale ___ di punto percentuale.', a: 'un centesimo', w: ['un decimo', 'un millesimo', 'la metà'] },
    { s: 'Lo spread confronta il BTP a 10 anni con il ___ tedesco di pari scadenza.', a: 'Bund', w: ['BOT', 'Treasury', 'OAT'] },
    { s: 'Quando gli investitori spaventati si rifugiano in titoli sicuri si parla di flight to ___.', a: 'quality', w: ['quantity', 'value', 'growth'] },
    { s: 'Con il BTP al 4% e il Bund al 2,5%, lo spread è di ___ punti base.', a: '150', w: ['15', '1.500', '650'] },
    { s: 'Il timore che un Paese esca dall’euro è detto rischio di ___.', a: 'ridenominazione', w: ['reinvestimento', 'liquidità', 'controparte'] },
  ],
  order: [
    { q: 'Ordina dallo spread più basso al più alto (dati ipotetici)', i: ['BTP 3,0%, Bund 2,5%', 'BTP 3,6%, Bund 2,8%', 'BTP 4,0%, Bund 2,9%', 'BTP 4,5%, Bund 2,5%'], e: 'Spread: 50, 80, 110 e 200 punti base. Conta la differenza, non il livello del rendimento italiano.' },
    { q: 'Ordina la catena di una crisi di fiducia sul debito italiano', i: ['Crescono i dubbi sui conti pubblici', 'Gli investitori vendono BTP', 'Il prezzo dei BTP scende e il rendimento sale', 'Lo spread con il Bund si allarga', 'Le nuove emissioni costano di più allo Stato'], e: 'Le vendite abbassano i prezzi e alzano i rendimenti: lo spread cresce e, con il tempo, sale il costo del debito.' },
  ],
  cat: [
    { q: 'Tende ad allargare o a restringere lo spread?', g: [['Lo allarga', ['Instabilità politica in Italia', 'Taglio del rating italiano', 'Fuga verso i Bund in una crisi']], ['Lo restringe', ['Rating italiano alzato', 'Calo del deficit pubblico', 'Fiducia nella tenuta dell’euro']]] },
    { q: 'Spread sotto o sopra 200 punti base? (dati ipotetici)', g: [['Sotto 200 pb', ['BTP 3,5%, Bund 2,0%', 'BTP 4,2%, Bund 2,5%', 'BTP 2,8%, Bund 1,9%']], ['Sopra 200 pb', ['BTP 5,0%, Bund 2,5%', 'BTP 4,6%, Bund 2,0%', 'BTP 6,0%, Bund 1,5%']]] },
  ],
  scen: [
    { s: 'Francesca, 44 anni, ha un BTP che terrà fino alla scadenza, tra 4 anni. Il telegiornale annuncia “spread in forte rialzo” e il prezzo del suo titolo scende del 3%.', q: 'Cosa fa Francesca?', o: [
      { t: 'Ricorda che a scadenza riceverà 100, se lo Stato paga', ok: true, f: 'Il calo di prezzo conta solo se vende. Il suo piano non è cambiato: continua a incassare le cedole e attende il rimborso.' },
      { t: 'Vende subito per evitare altri cali', ok: false, f: 'Vendendo trasforma una perdita temporanea in definitiva, reagendo a una notizia invece che al suo obiettivo.' },
      { t: 'Compra altri BTP con un prestito per approfittarne', ok: false, f: 'Usare debito su un titolo che si sta muovendo per timori sul Paese aumenta molto il rischio: se lo spread salisse ancora, perderebbe di più.' },
    ] },
    { s: 'Lorenzo, 29 anni, studia economia e vuole confrontare il rischio percepito dal mercato su Italia e Spagna.', q: 'Quale confronto è più corretto?', o: [
      { t: 'Gli spread a 10 anni di BTP e Bonos sul Bund', ok: true, f: 'Usare lo stesso riferimento e la stessa scadenza rende i due premi confrontabili: lo spread più alto indica più rischio percepito.' },
      { t: 'Le cedole di due titoli qualsiasi dei due Paesi', ok: false, f: 'Le cedole dipendono dal momento di emissione e dalla scadenza: confrontarle non dice nulla sul rischio percepito oggi.' },
      { t: 'L’andamento dei due indici di Borsa', ok: false, f: 'Le Borse riflettono gli utili delle aziende quotate, non il rischio del debito pubblico: è un confronto diverso.' },
    ] },
    { s: 'Serena, 52 anni, ha un portafoglio diversificato. Lo spread è salito molto e un’amica le dice: “Metti tutto in BTP, adesso rendono tantissimo”.', q: 'Cosa fa Serena?', o: [
      { t: 'Ricorda che più rendimento significa più rischio', ok: true, f: 'Lo spread alto paga un rischio più alto: può valutare i BTP nel suo piano, ma concentrarvi tutto il portafoglio aumenta l’esposizione al rischio Italia.' },
      { t: 'Sposta tutto in BTP per il rendimento più alto', ok: false, f: 'Concentrare tutto su un solo emittente lega il patrimonio al rischio Italia: se lo spread salisse ancora, il portafoglio soffrirebbe tutto insieme.' },
      { t: 'Vende tutti i titoli e compra solo oro', ok: false, f: 'Passare da un estremo all’altro non è prudenza: l’oro non paga cedole e ha oscillazioni anche ampie.' },
    ] },
    { s: 'Antonio, 33 anni, sta per chiedere un mutuo. Legge che lo spread BTP-Bund è alto da mesi e un collega gli dice che “lo spread riguarda solo lo Stato”.', q: 'Come ragiona Antonio?', o: [
      { t: 'Sa che può incidere sui mutui e confronta più offerte', ok: true, f: 'Uno spread alto e duraturo aumenta il costo con cui le banche italiane si finanziano, e questo può riflettersi sui tassi dei mutui.' },
      { t: 'Ignora lo spread: non riguarda famiglie e imprese', ok: false, f: 'Il costo del debito pubblico influenza quello delle banche, e quindi i tassi applicati a famiglie e imprese.' },
      { t: 'Rinvia il mutuo finché lo spread non torna a zero', ok: false, f: 'Lo spread con il Bund difficilmente va a zero: aspettarlo significa rinviare la decisione all’infinito.' },
    ] },
  ],
  tip: 'Quando senti parlare di spread, guarda anche i due rendimenti: lo spread dice quanto paga l’Italia in più della Germania, non quanto paga in assoluto.',
});
