FQC(39, {
  intro: 'Le obbligazioni indicizzate proteggono il potere d’acquisto: capitale e cedole crescono con i prezzi. Scopri come funzionano e quali limiti hanno.',
  cards: [
    { t: 'Il meccanismo', x: 'Il capitale viene rivalutato in base a un indice dei prezzi e la cedola, fissa in termini reali, si applica al capitale rivalutato. Se i prezzi salgono, crescono in euro sia le cedole sia il capitale da rimborsare.', v: { k: 'steps', s: ['Si fissa un tasso reale', 'L’inflazione rivaluta il capitale', 'La cedola si calcola sul capitale rivalutato', 'Si rimborsa il capitale rivalutato'] } },
    { t: 'Un esempio numerico', x: 'Investi 10.000 € in un titolo con cedola reale annua dell’1%. Se in un anno l’inflazione è del 3%, il capitale diventa 10.300 € e la cedola annua è l’1% di 10.300 €, cioè 103 € invece di 100 €.', v: { k: 'bars', d: [['Capitale iniziale', 10000], ['Capitale rivalutato', 10300]], u: '€' } },
    { t: 'Gli indicizzati italiani', x: 'Il BTP€i segue l’inflazione dell’area euro (IAPC senza tabacchi) e paga la rivalutazione del capitale a scadenza. Il BTP Italia segue l’inflazione italiana (FOI senza tabacchi) e la paga ogni sei mesi. Negli Stati Uniti esistono i TIPS.', v: { k: 'vs', a: ['BTP€i', 'Inflazione area euro, rivalutazione a scadenza'], b: ['BTP Italia', 'Inflazione italiana, rivalutazione semestrale'] } },
    { t: 'L’inflazione di pareggio', x: 'Confrontando un titolo nominale e uno indicizzato con la stessa scadenza ottieni l’inflazione attesa dal mercato (breakeven). Se l’inflazione effettiva sarà più alta, in linea di massima renderà di più l’indicizzato; se più bassa, il nominale.', v: { k: 'formula', f: 'Inflazione di pareggio ≈ rendimento nominale − rendimento reale', n: 'Es. ipotetico: 3,5% − 1,2% = 2,3% di inflazione attesa' } },
    { t: 'Protezione dalla deflazione', x: 'Per il BTP€i, se i prezzi scendono, a scadenza viene comunque rimborsato almeno il valore nominale. Le cedole, invece, possono ridursi se durante la vita del titolo l’indice dei prezzi scende.', v: { k: 'stat', n: '100', l: 'rimborso minimo a scadenza del BTP€i, anche in caso di deflazione' } },
    { t: 'Non sono a rischio zero', x: 'Il prezzo degli indicizzati dipende dai tassi reali: se salgono, il prezzo scende anche con inflazione alta. Inoltre l’indicizzazione arriva con qualche mese di ritardo e l’indice ufficiale può differire dalla tua inflazione personale.', v: { k: 'icons', d: [['📈', 'Tassi reali in rialzo'], ['⏱️', 'Ritardo di indicizzazione'], ['🛒', 'Paniere diverso dal tuo']] } },
  ],
  terms: [
    ['Titolo indicizzato all’inflazione', 'Obbligazione il cui capitale, e quindi le cedole, si rivaluta in base a un indice dei prezzi.'],
    ['Tasso reale', 'Rendimento al netto dell’inflazione, cioè misurato in potere d’acquisto.'],
    ['Coefficiente di indicizzazione', 'Rapporto tra l’indice dei prezzi a una certa data e quello alla data di partenza del titolo.'],
    ['Inflazione di pareggio', 'Inflazione che rende uguali i rendimenti di un titolo nominale e di uno indicizzato; detta breakeven.'],
    ['IAPC', 'Indice dei prezzi al consumo armonizzato a livello europeo: il BTP€i usa quello dell’area euro senza tabacchi.'],
    ['FOI', 'Indice ISTAT dei prezzi per le famiglie di operai e impiegati: il BTP Italia lo usa senza tabacchi.'],
    ['Floor di deflazione', 'Clausola che garantisce un rimborso almeno pari al nominale anche se i prezzi scendono.'],
    ['Ritardo di indicizzazione', 'Intervallo tra il mese dell’indice usato nel calcolo e la data di pagamento: di solito alcuni mesi.'],
  ],
  tf: [
    ['In un titolo indicizzato, la cedola reale si applica al capitale rivalutato per l’inflazione.', true, 'Per questo, se i prezzi salgono, crescono in euro sia le cedole sia il capitale da rimborsare.'],
    ['Il BTP Italia paga la rivalutazione del capitale solo alla scadenza.', false, 'Il BTP Italia la paga ogni sei mesi insieme alla cedola. È il BTP€i a corrisponderla alla scadenza.'],
    ['Un titolo indicizzato all’inflazione non può mai scendere di prezzo.', false, 'Mito: il prezzo dipende dai tassi reali. Se salgono, scende anche con inflazione alta, come accadde a molti indicizzati lunghi nel 2022.'],
    ['Se l’inflazione effettiva supera quella di pareggio, l’indicizzato rende più del nominale di pari scadenza.', true, 'L’inflazione di pareggio è quella già incorporata nei prezzi: se ne arriva di più, la rivalutazione premia chi ha l’indicizzato.'],
    ['Il rendimento reale di un titolo indicizzato non può mai essere negativo.', false, 'Può esserlo: in passato, con tassi molto bassi, diversi indicizzati di Paesi solidi avevano rendimenti reali sotto zero.'],
    ['Per il BTP€i, a scadenza il rimborso non può essere inferiore al valore nominale.', true, 'C’è una protezione dalla deflazione sul capitale: anche se l’indice dei prezzi scende, a scadenza si riceve almeno 100.'],
    ['La rivalutazione del capitale dei titoli di Stato indicizzati italiani è tassata al 12,5%.', true, 'Come gli interessi, anche la rivalutazione del capitale è un reddito, tassato con l’aliquota agevolata dei titoli di Stato.'],
    ['Un titolo indicizzato conviene sempre rispetto a uno nominale.', false, 'Mito: se l’inflazione effettiva resta sotto quella di pareggio, il titolo nominale di pari scadenza rende di più.'],
    ['L’indicizzazione all’inflazione avviene di solito con qualche mese di ritardo.', true, 'Gli indici dei prezzi si pubblicano dopo la fine del mese: per questo si usa l’indice di alcuni mesi prima della data di calcolo.'],
    ['Un titolo indicizzato ti protegge esattamente dall’aumento delle tue spese personali.', false, 'Segue un indice ufficiale: se il tuo paniere di spesa è diverso, la tua inflazione personale può essere più alta o più bassa.'],
  ],
  mcq: [
    { q: 'Investi 5.000 € in un indicizzato con cedola reale del 2%. In un anno l’inflazione è del 4%. Qual è la cedola annua lorda, per semplicità pagata una volta?', a: '104 €', w: ['100 €', '200 €', '300 €'], e: 'Capitale rivalutato: 5.000 × 1,04 = 5.200 €. Cedola: 2% × 5.200 = 104 €, invece dei 100 € senza inflazione.' },
    { q: 'BTP nominale a 10 anni al 3,6% e BTP€i a 10 anni all’1,4% reale (dati ipotetici). Qual è circa l’inflazione di pareggio?', a: '2,2%', w: ['5,0%', '1,4%', '3,6%'], e: 'Inflazione di pareggio ≈ 3,6% − 1,4% = 2,2%: è l’inflazione media annua che renderebbe equivalenti i due titoli.' },
    { q: 'Quale indice dei prezzi usa il BTP€i?', a: 'IAPC dell’area euro senza tabacchi', w: ['FOI italiano senza tabacchi', 'Euribor a 6 mesi', 'Indice FTSE MIB'], e: 'Il BTP€i segue l’inflazione dell’area euro (IAPC senza tabacchi); il BTP Italia quella italiana (FOI senza tabacchi).' },
    { q: 'Cosa succede di solito al prezzo di un indicizzato a lunga scadenza se i tassi reali salgono molto?', a: 'Scende', w: ['Sale', 'Resta fermo per contratto', 'Viene rimborsato subito'], e: 'Come per ogni obbligazione, un rendimento richiesto più alto riduce il prezzo: la protezione riguarda l’inflazione, non i tassi reali.' },
    { q: 'Per chi ha più senso un indicizzato rispetto a un nominale di pari scadenza?', a: 'Chi teme un’inflazione sopra le attese', w: ['Chi prevede una forte deflazione', 'Chi vuole cedole identiche ogni anno', 'Chi prevede inflazione sotto le attese'], e: 'L’indicizzato conviene se l’inflazione effettiva supera quella già incorporata nei prezzi, cioè l’inflazione di pareggio.' },
    { q: 'Cosa garantisce il floor di deflazione del BTP€i?', a: 'Un rimborso a scadenza di almeno 100', w: ['Una cedola minima del 2% annuo', 'Un prezzo di mercato mai sotto 100', 'Un rendimento reale sempre positivo'], e: 'La protezione riguarda il capitale a scadenza: prima della scadenza il prezzo di mercato può comunque scendere sotto 100.' },
    { q: 'Perché un indicizzato può non coprire la tua inflazione personale?', a: 'Segue un paniere medio, non le tue spese', w: ['Esclude sempre l’energia dal calcolo', 'Si aggiorna una volta ogni dieci anni', 'Segue l’inflazione degli Stati Uniti'], e: 'Gli indici misurano un paniere rappresentativo: se spendi molto in voci che rincarano di più, la tua inflazione sarà più alta.' },
    { q: 'Inflazione di pareggio al 2,5%. Nei 10 anni successivi l’inflazione media è dell’1,5%. Quale titolo ha reso di più, a pari scadenza?', a: 'Il titolo nominale', w: ['Il titolo indicizzato', 'Hanno reso esattamente uguale', 'Dipende solo dal rating'], e: 'L’inflazione è stata inferiore a quella prezzata: il nominale, che incorporava il 2,5%, ha battuto l’indicizzato.' },
  ],
  fill: [
    { s: 'In un titolo indicizzato, la cedola reale si applica al capitale ___.', a: 'rivalutato', w: ['scontato', 'svalutato', 'medio'] },
    { s: 'Rendimento nominale meno rendimento reale dà, in prima approssimazione, l’inflazione di ___.', a: 'pareggio', w: ['base', 'cassa', 'bilancio'] },
    { s: 'Il BTP€i è legato all’inflazione dell’area euro misurata dall’indice ___.', a: 'IAPC', w: ['FOI', 'PIL', 'Euribor'] },
    { s: 'Il prezzo dei titoli indicizzati scende se salgono i tassi ___.', a: 'reali', w: ['di cambio', 'di natalità', 'di disoccupazione'] },
    { s: 'Poiché l’indice dei prezzi usato è di alcuni mesi prima, si parla di ___ di indicizzazione.', a: 'ritardo', w: ['premio', 'floor', 'anticipo'] },
  ],
  order: [
    { q: 'Ordina i passi per calcolare la cedola di un titolo indicizzato', i: ['Si rileva l’indice dei prezzi di riferimento', 'Si calcola il coefficiente di indicizzazione', 'Si rivaluta il capitale nominale', 'Si applica il tasso reale al capitale rivalutato'], e: 'Il coefficiente confronta l’indice di oggi con quello di partenza: moltiplicato per il nominale dà il capitale su cui si calcola la cedola.' },
    { q: 'Ordina dall’inflazione di pareggio più bassa alla più alta (dati ipotetici)', i: ['Nominale 2,5%, reale 1,0%', 'Nominale 3,0%, reale 1,2%', 'Nominale 3,4%, reale 1,0%', 'Nominale 4,0%, reale 0,8%'], e: 'Inflazione di pareggio: 1,5%, 1,8%, 2,4% e 3,2%. È la differenza tra rendimento nominale e reale.' },
  ],
  cat: [
    { q: 'Inflazione di pareggio al 2%: rende di più l’indicizzato o il nominale?', g: [['Indicizzato', ['Inflazione media del 3%', 'Inflazione media del 4,5%', 'Inflazione media del 2,6%']], ['Nominale', ['Inflazione media dell’1%', 'Inflazione media dell’1,5%', 'Prezzi in calo dello 0,5% annuo']]] },
    { q: 'Caratteristica del BTP€i o del BTP Italia?', g: [['BTP€i', ['Inflazione dell’area euro', 'Indice IAPC senza tabacchi', 'Rivalutazione pagata a scadenza']], ['BTP Italia', ['Inflazione italiana', 'Indice FOI senza tabacchi', 'Rivalutazione pagata ogni sei mesi']]] },
  ],
  scen: [
    { s: 'Carla, 66 anni, vive di pensione e risparmi. Teme che nei prossimi 10 anni l’inflazione eroda il valore delle cedole fisse dei suoi BTP.', q: 'Cosa fa Carla?', o: [
      { t: 'Inserisce una quota di titoli indicizzati con scadenza adatta', ok: true, f: 'Una parte legata all’inflazione rende il reddito più robusto se i prezzi salgono più del previsto, senza stravolgere il portafoglio.' },
      { t: 'Compra BTP a 30 anni a tasso fisso', ok: false, f: 'Cedola fissa e scadenza lunga: è proprio il titolo più esposto a un’inflazione più alta del previsto.' },
      { t: 'Tiene tutto sul conto corrente per sicurezza', ok: false, f: 'Sul conto corrente il denaro rende poco o nulla: con l’inflazione perde potere d’acquisto anno dopo anno.' },
    ] },
    { s: 'Matteo, 35 anni, confronta un BTP nominale e un BTP€i a 10 anni: l’inflazione di pareggio è (ipoteticamente) del 2%. Lui ritiene probabile un’inflazione media più alta.', q: 'Come ragiona Matteo?', o: [
      { t: 'Confronta la sua previsione con il 2% già prezzato', ok: true, f: 'L’indicizzato rende di più solo se l’inflazione supera il 2%: se Matteo ha ragione conviene, ma la sua resta una previsione.' },
      { t: 'Compra l’indicizzato: conviene in ogni caso', ok: false, f: 'Se l’inflazione restasse sotto il 2%, il nominale renderebbe di più: l’indicizzato non vince sempre.' },
      { t: 'Sceglie il titolo con la cedola più alta', ok: false, f: 'La cedola del nominale include già l’inflazione attesa: confrontarla con una cedola reale non ha senso.' },
    ] },
    { s: 'Irene, 42 anni, ha comprato un indicizzato a 25 anni. In un anno di inflazione alta, i tassi reali salgono molto e il prezzo scende del 15%. È confusa e vuole vendere.', q: 'Cosa fa Irene?', o: [
      { t: 'Capisce che il calo dipende dai tassi reali', ok: true, f: 'La rivalutazione continua a proteggere dall’inflazione; il prezzo è sceso per i tassi reali. Se tiene fino a scadenza, riceve il capitale rivalutato.' },
      { t: 'Vende: il titolo non funziona', ok: false, f: 'Il titolo fa ciò che promette, cioè proteggere dall’inflazione a scadenza: non protegge dalle oscillazioni dovute ai tassi reali.' },
      { t: 'Ne compra altri con un prestito', ok: false, f: 'Con una duration così lunga, la leva amplificherebbe ulteriori cali di prezzo se i tassi reali continuassero a salire.' },
    ] },
    { s: 'Davide, 30 anni, spende soprattutto in affitto ed energia, voci che per lui sono rincarate più della media. Pensa che un BTP Italia lo copra al centesimo.', q: 'Cosa fa Davide?', o: [
      { t: 'Sa che segue un indice medio e tiene un margine nel budget', ok: true, f: 'Il BTP Italia segue l’indice FOI, non le sue spese: se la sua inflazione è più alta, la protezione sarà solo parziale.' },
      { t: 'Ci investe tutto, convinto di essere coperto', ok: false, f: 'La copertura riguarda un paniere medio: concentrare tutto su questa convinzione lo lascia esposto alle sue spese specifiche.' },
      { t: 'Rinuncia: se non copre perfettamente non serve', ok: false, f: 'Una protezione parziale resta utile: l’indice segue l’andamento generale dei prezzi, che in buona parte riguarda anche le sue spese.' },
    ] },
  ],
  tip: 'Un titolo indicizzato protegge dall’inflazione a scadenza, non dalle oscillazioni di prezzo: confronta sempre l’inflazione di pareggio con le tue aspettative.',
});
