FQC(40, {
  intro: 'Cosa succede se chi ti ha chiesto un prestito non paga? Perdita attesa, tasso di recupero, gerarchia dei creditori e bail-in.',
  cards: [
    { t: 'Che cos’è il default', x: 'Si ha default quando l’emittente non paga cedole o capitale nei tempi previsti, oppure impone una ristrutturazione che riduce il valore del debito. Non sempre si perde tutto: spesso si recupera una parte del capitale.', v: { k: 'icons', d: [['⏰', 'Mancato pagamento'], ['✂️', 'Ristrutturazione forzata'], ['🧾', 'Procedura di insolvenza']] } },
    { t: 'La perdita attesa', x: 'Combina tre elementi: probabilità di default, quota persa in caso di default (1 meno il tasso di recupero) ed esposizione. Con 10.000 €, probabilità del 2% e recupero del 40%, la perdita attesa è di 120 €.', v: { k: 'formula', f: 'Perdita attesa = probabilità di default × (1 − recupero) × esposizione', n: 'Es.: 2% × 60% × 10.000 € = 120 €' } },
    { t: 'Il tasso di recupero', x: 'È la parte del credito che i creditori riescono a recuperare dopo il default. Dipende dalla posizione nella gerarchia, dalle garanzie e dal valore dei beni dell’emittente. Nel grafico, valori ipotetici per tipo di titolo.', v: { k: 'bars', d: [['Garantite', 70], ['Senior', 45], ['Subordinate', 20]], u: '%' } },
    { t: 'La fila dei creditori', x: 'In modo semplificato, in caso di insolvenza si paga in quest’ordine: creditori garantiti, poi obbligazionisti senior non garantiti, poi subordinati e per ultimi gli azionisti. Più sei in fondo, più rendimento chiedi e più puoi perdere.', v: { k: 'steps', s: ['Creditori garantiti', 'Obbligazioni senior', 'Obbligazioni subordinate', 'Azionisti'] } },
    { t: 'Il bail-in', x: 'Dal 2016, nell’Unione europea, se una banca va in crisi le perdite ricadono prima su azionisti e creditori che sui contribuenti: si parte dalle azioni, poi le subordinate, poi le obbligazioni senior. I depositi fino a 100.000 € sono esclusi.', v: { k: 'scale', a: 'Colpito per primo', b: 'Colpito per ultimo', d: [['Azioni', 5], ['Subordinate', 30], ['Senior', 60], ['Depositi oltre 100.000 €', 90]] } },
    { t: 'Diversificare il rischio di credito', x: 'Con un solo emittente, un default può costarti gran parte del capitale. Dividendo il capitale in parti uguali tra 50 emittenti, un singolo default pesa al massimo il 2%, e meno se c’è un recupero.', v: { k: 'stat', n: '2%', l: 'peso di ciascun emittente in un portafoglio diviso tra 50' } },
  ],
  terms: [
    ['Default', 'Mancato pagamento di cedole o capitale, o ristrutturazione forzata del debito da parte dell’emittente.'],
    ['Probabilità di default', 'Probabilità stimata che l’emittente non paghi entro un certo periodo, spesso un anno.'],
    ['Tasso di recupero', 'Percentuale del credito che si riesce a riavere dopo un’insolvenza.'],
    ['Perdita in caso di default', 'Quota dell’esposizione persa se l’emittente fallisce: 1 meno il tasso di recupero.'],
    ['Obbligazione subordinata', 'Titolo rimborsato solo dopo i creditori ordinari: rende di più ma è più rischioso.'],
    ['Obbligazione senior', 'Titolo di debito con priorità di rimborso rispetto ai titoli subordinati.'],
    ['Bail-in', 'Strumento di risoluzione bancaria che addossa le perdite ad azionisti e creditori, non ai contribuenti.'],
    ['Ristrutturazione del debito', 'Modifica forzata delle condizioni del prestito, ad esempio taglio del capitale o rinvio delle scadenze.'],
  ],
  tf: [
    ['In caso di default si perde sempre il 100% del capitale investito.', false, 'Mito: spesso i creditori recuperano una parte del valore. Quanto dipende da garanzie, posizione nella gerarchia e beni dell’emittente.'],
    ['Le obbligazioni subordinate vengono rimborsate dopo quelle senior in caso di insolvenza.', true, 'Sono più in basso nella gerarchia dei creditori: per questo rendono di più e in caso di default recuperano meno.'],
    ['Con il bail-in, i depositi bancari fino a 100.000 € sono esclusi dalle perdite.', true, 'Sono protetti dal sistema di garanzia dei depositi e non possono essere usati per assorbire le perdite della banca.'],
    ['Le obbligazioni emesse da una banca sono coperte dalla garanzia dei depositi come un conto corrente.', false, 'Mito: le obbligazioni bancarie non sono depositi e possono essere coinvolte nel bail-in, anche quelle senior.'],
    ['Perdita attesa = probabilità di default × (1 − tasso di recupero) × esposizione.', true, 'Ad esempio: 3% × (1 − 0,5) × 10.000 € = 150 € di perdita attesa.'],
    ['Gli azionisti vengono soddisfatti prima degli obbligazionisti subordinati.', false, 'Gli azionisti sono gli ultimi: ricevono qualcosa solo dopo che tutti i creditori, subordinati compresi, sono stati pagati.'],
    ['Anche uno Stato può fare default o ristrutturare il proprio debito.', true, 'È successo più volte: ad esempio l’Argentina nel 2001 e la ristrutturazione del debito greco verso i privati nel 2012.'],
    ['Diversificare tra molti emittenti riduce l’impatto di un singolo default sul portafoglio.', true, 'Se un emittente pesa il 2% del portafoglio, il suo default costa al massimo il 2%, e meno se c’è un recupero.'],
    ['Il bail-in colpisce prima le obbligazioni senior e solo dopo le azioni.', false, 'L’ordine è il contrario: prima le azioni, poi gli strumenti subordinati e solo dopo le obbligazioni senior.'],
    ['Un tasso di recupero del 40% significa che si perde il 40% del capitale.', false, 'Si recupera il 40% e si perde il 60%: la perdita in caso di default è 1 meno il tasso di recupero.'],
  ],
  mcq: [
    { q: 'Esposizione 20.000 €, probabilità di default 1%, recupero 50%. Qual è la perdita attesa?', a: '100 €', w: ['200 €', '10.000 €', '50 €'], e: '20.000 × 1% × (1 − 0,5) = 100 €. È una media statistica: in caso di default la perdita effettiva sarebbe di 10.000 €.' },
    { q: 'Un bond va in default con un tasso di recupero del 30%. Quanto ricevi su 10.000 € nominali?', a: '3.000 €', w: ['7.000 €', '300 €', '10.000 €'], e: 'Recuperi il 30% del nominale, cioè 3.000 €: la perdita è di 7.000 €, pari al 70%.' },
    { q: 'Nel bail-in, quale strumento assorbe le perdite per primo?', a: 'Le azioni', w: ['Le obbligazioni senior', 'I depositi fino a 100.000 €', 'Le obbligazioni subordinate'], e: 'Si parte dal capitale degli azionisti, poi si passa agli strumenti subordinati e infine alle obbligazioni senior.' },
    { q: 'Perché una subordinata della stessa banca rende più di una senior?', a: 'In caso di crisi viene rimborsata dopo', w: ['Ha sempre una scadenza più breve', 'È garantita dallo Stato', 'Paga cedole esenti da imposte'], e: 'Il rischio di perdita è maggiore perché sta più in basso nella gerarchia: il rendimento extra serve a compensarlo.' },
    { q: 'Quale di questi è esposto a un bail-in della tua banca?', a: 'Un’obbligazione senior della banca', w: ['Un deposito da 30.000 €', 'Un BTP nel dossier titoli', 'Un ETF azionario nel dossier'], e: 'I titoli nel dossier restano di proprietà del cliente e i depositi fino a 100.000 € sono protetti; le obbligazioni della banca no.' },
    { q: 'Cosa determina soprattutto il tasso di recupero?', a: 'Garanzie e posto nella fila dei creditori', w: ['La cedola fissata all’emissione', 'Il prezzo pagato dall’investitore', 'La data di stacco della cedola'], e: 'I creditori garantiti e senior recuperano di più; conta anche quanto valgono i beni dell’emittente al momento della crisi.' },
    { q: 'Un portafoglio è diviso in parti uguali tra 25 emittenti. Uno fa default con recupero zero. Quanto perde il portafoglio?', a: '4%', w: ['25%', '1%', '40%'], e: '1 ÷ 25 = 4%: con la diversificazione un singolo default fa male, ma non distrugge il portafoglio.' },
    { q: 'Quale situazione rientra nella definizione di default?', a: 'Una cedola non pagata alla data prevista', w: ['Un calo del prezzo del 10%', 'Un rating sceso da AA ad A', 'Un aumento dei tassi di mercato'], e: 'Il default riguarda il mancato rispetto degli impegni di pagamento. Cali di prezzo o declassamenti sono segnali, non insolvenze.' },
  ],
  fill: [
    { s: 'La quota di credito recuperata dopo un default si chiama tasso di ___.', a: 'recupero', w: ['rendimento', 'sconto', 'cambio'] },
    { s: 'Le obbligazioni ___ vengono rimborsate dopo le senior in caso di insolvenza.', a: 'subordinate', w: ['garantite', 'privilegiate', 'indicizzate'] },
    { s: 'Nel ___ le perdite di una banca in crisi ricadono su azionisti e creditori.', a: 'bail-in', w: ['bail-out', 'buyback', 'rating'] },
    { s: 'Perdita attesa = probabilità di default × perdita in caso di default × ___.', a: 'esposizione', w: ['duration', 'cedola', 'spread'] },
    { s: 'Nel bail-in i depositi fino a ___ euro sono esclusi dalle perdite.', a: '100.000', w: ['10.000', '50.000', '500.000'] },
  ],
  order: [
    { q: 'Ordina chi assorbe le perdite nel bail-in, dal primo all’ultimo', i: ['Azionisti', 'Obbligazionisti subordinati', 'Obbligazionisti senior', 'Depositi oltre 100.000 €'], e: 'Le perdite risalgono la gerarchia: si parte dal capitale e si arriva ai depositi oltre 100.000 € solo se non basta. Quelli fino a 100.000 € sono esclusi.' },
    { q: 'Esposizione 10.000 €: ordina dalla perdita attesa più bassa alla più alta', i: ['Probabilità 0,5%, recupero 60%', 'Probabilità 1%, recupero 40%', 'Probabilità 3%, recupero 50%', 'Probabilità 5%, recupero 20%'], e: 'Perdite attese: 20 €, 60 €, 150 € e 400 €. Conta la combinazione di probabilità di default e tasso di recupero.' },
  ],
  cat: [
    { q: 'Protetto o esposto in caso di bail-in della tua banca?', g: [['Protetto', ['Conto corrente con 20.000 €', 'BTP nel dossier titoli', 'Quote di un ETF nel dossier']], ['Esposto', ['Azioni della banca', 'Obbligazioni subordinate della banca', 'Obbligazioni senior della banca']]] },
    { q: 'Aumenta o riduce la perdita attesa?', g: [['La aumenta', ['Probabilità di default più alta', 'Tasso di recupero più basso', 'Esposizione maggiore verso l’emittente']], ['La riduce', ['Garanzie reali sul prestito', 'Posizione senior invece che subordinata', 'Esposizione minore verso l’emittente']]] },
  ],
  scen: [
    { s: 'Rosa, 68 anni, ha 60.000 € di risparmi. La sua banca le propone di investirne gran parte in obbligazioni subordinate emesse dalla banca stessa, con un rendimento più alto dei titoli di Stato.', q: 'Cosa fa Rosa?', o: [
      { t: 'Non concentra i risparmi in quelle subordinate', ok: true, f: 'In una crisi della banca sarebbero tra le prime a subire perdite, subito dopo le azioni. Il rendimento più alto paga proprio questo rischio.' },
      { t: 'Accetta: è la sua banca, quindi è sicura', ok: false, f: 'La fiducia nella banca non cambia la gerarchia: nel 2015, in Italia, la risoluzione di quattro banche colpì anche i possessori di subordinate.' },
      { t: 'Accetta perché sono coperte come i depositi', ok: false, f: 'Le obbligazioni non sono depositi: non godono della garanzia fino a 100.000 € e possono assorbire perdite.' },
    ] },
    { s: 'Fabio, 47 anni, ha un bond di una società andata in default. Il titolo ora quota 25 e lui pensa che “non valga più niente”, quindi vuole venderlo a qualsiasi prezzo.', q: 'Cosa fa Fabio?', o: [
      { t: 'Si informa su procedura e recupero atteso prima di decidere', ok: true, f: 'Il prezzo di 25 riflette il recupero atteso dal mercato: capire tempi e prospettive della procedura lo aiuta a scegliere se vendere o attendere.' },
      { t: 'Vende subito a qualsiasi prezzo', ok: false, f: 'Dopo un default il titolo può essere poco scambiato: vendere a qualsiasi prezzo rischia di regalare una parte del valore recuperabile.' },
      { t: 'Investe altri risparmi nel bond per mediare', ok: false, f: 'Aumentare l’esposizione a un emittente già insolvente, senza analisi, concentra ancora di più il rischio.' },
    ] },
    { s: 'Elisa, 34 anni, confronta due bond a un anno (dati ipotetici). A: rendimento 4%, probabilità di default 0,5%, recupero 40%. B: rendimento 9%, probabilità di default 8%, recupero 30%.', q: 'Come ragiona Elisa?', o: [
      { t: 'Toglie la perdita attesa dal rendimento e confronta', ok: true, f: 'A: 4% − 0,3% ≈ 3,7%. B: 9% − 5,6% ≈ 3,4%. Al netto della perdita attesa B rende meno, con un rischio molto più alto.' },
      { t: 'Sceglie B: il 9% è più del doppio del 4%', ok: false, f: 'Il rendimento promesso non è quello atteso: con l’8% di probabilità di default, gran parte del premio serve solo a coprire le perdite.' },
      { t: 'Sceglie quello dell’azienda più famosa', ok: false, f: 'La notorietà non misura il rischio di credito: servono probabilità di default, recupero e rating.' },
    ] },
    { s: 'Marco, 52 anni, ha 250.000 € di risparmi sul conto corrente di un’unica banca e ha sentito parlare di bail-in.', q: 'Cosa fa Marco?', o: [
      { t: 'Ripartisce la liquidità restando sotto 100.000 € per banca', ok: true, f: 'La garanzia copre fino a 100.000 € per depositante e per banca: dividere tra più istituti, o investire in titoli nel dossier, riduce il rischio.' },
      { t: 'Compra obbligazioni della stessa banca', ok: false, f: 'Peggiora la situazione: le obbligazioni bancarie non sono coperte dalla garanzia e nel bail-in sono colpite prima dei depositi.' },
      { t: 'Ritira tutto e tiene i contanti in casa', ok: false, f: 'Elimina il rischio bancario ma introduce furto, perdita e inflazione, senza alcun rendimento: non è una soluzione prudente.' },
    ] },
  ],
  tip: 'Prima di comprare un’obbligazione chiediti dove ti trovi nella fila dei creditori. Diversifica tra emittenti e diffida dei rendimenti troppo alti per essere veri.',
});
