FQC(41, {
  intro: 'Scopri come funziona un fondo comune: chi lo gestisce, chi custodisce i soldi, come si calcola il valore della quota e perché esistono classi diverse.',
  cards: [
    { t: 'Un paniere collettivo', x: 'Un fondo comune raccoglie il denaro di tanti risparmiatori e lo investe in un portafoglio di titoli. Ognuno possiede quote del fondo in proporzione a quanto ha versato, non i singoli titoli.', v: { k: 'icons', d: [['👥', 'Tanti risparmiatori'], ['🧺', 'Un unico patrimonio'], ['📊', 'Portafoglio diversificato']] } },
    { t: 'Chi decide e chi custodisce', x: 'La SGR sceglie gli investimenti; la banca depositaria custodisce titoli e liquidità e controlla che le regole siano rispettate. Il patrimonio del fondo è separato da quello di entrambe: i creditori della SGR non possono toccarlo.', v: { k: 'vs', a: ['SGR', 'Decide dove investire'], b: ['Banca depositaria', 'Custodisce e controlla'] } },
    { t: 'NAV e valore della quota', x: 'Il NAV è il valore netto del patrimonio del fondo. Diviso per il numero di quote in circolazione dà il valore unitario della quota, calcolato di norma ogni giorno lavorativo.', v: { k: 'formula', f: 'Valore quota = (attività − passività) ÷ numero di quote', n: 'Es.: (101 − 1) mln € ÷ 8 mln quote = 12,50 €' } },
    { t: 'Come entri ed esci', x: 'In un fondo aperto sottoscrivi e chiedi il rimborso tramite il collocatore. Il prezzo è il valore della quota del giorno di riferimento, che non conosci ancora quando dai l’ordine.', v: { k: 'steps', s: ['Ordine al collocatore', 'Calcolo del valore della quota', 'Assegnazione delle quote', 'Lettera di conferma'] } },
    { t: 'Le famiglie di fondi', x: 'In base a ciò in cui investono, i fondi sono monetari, obbligazionari, bilanciati, azionari o flessibili. Il rischio cambia molto: la parola “fondo” non significa “prudente”.', v: { k: 'scale', a: 'Rischio più basso', b: 'Rischio più alto', d: [['Monetari', 8], ['Obbligazionari', 35], ['Bilanciati', 55], ['Azionari', 85]] } },
    { t: 'Le classi di quote', x: 'Lo stesso fondo può avere più classi: stesso portafoglio, ma costi, importi minimi o politica dei proventi diversi. Esempio: 1,8% di costi annui per la classe retail, 0,9% per quella istituzionale con minimi elevati.', v: { k: 'bars', d: [['Classe retail', 1.8], ['Classe istituzionale', 0.9]], u: '%' } },
  ],
  terms: [
    ['SGR', 'Società di gestione del risparmio: l’ente autorizzato che gestisce il fondo e decide gli investimenti.'],
    ['Banca depositaria', 'Soggetto che custodisce titoli e liquidità del fondo e controlla che la SGR rispetti le regole.'],
    ['NAV', 'Net Asset Value: valore netto del patrimonio del fondo, cioè attività meno passività.'],
    ['Quota', 'Unità in cui è diviso il patrimonio del fondo; ognuna dà diritto a una frazione del suo valore.'],
    ['Fondo aperto', 'Fondo in cui puoi sottoscrivere e chiedere il rimborso in ogni giorno di valorizzazione.'],
    ['Classe di quote', 'Versione dello stesso fondo con costi, importi minimi o politica dei proventi differenti.'],
    ['KID', 'Documento di poche pagine con le informazioni chiave: obiettivi, rischi, scenari e costi del prodotto.'],
    ['OICR', 'Organismo di investimento collettivo del risparmio: categoria che comprende fondi comuni e SICAV.'],
  ],
  tf: [
    ['Se la SGR fallisce, i suoi creditori possono rivalersi sul patrimonio del fondo.', false, 'Il patrimonio del fondo è autonomo e separato da quello della SGR: i creditori della società non possono aggredirlo.'],
    ['Il valore della quota si ottiene dividendo il patrimonio netto del fondo per il numero di quote in circolazione.', true, 'Per esempio, 100 milioni di patrimonio netto e 8 milioni di quote danno un valore di 12,50 € a quota.'],
    ['Quando sottoscrivi un fondo aperto conosci già il prezzo esatto a cui entrerai.', false, 'Entri al valore della quota del giorno di riferimento, calcolato dopo la chiusura dei mercati: al momento dell’ordine non lo conosci.'],
    ['Due classi dello stesso fondo possono avere rendimenti diversi pur investendo nello stesso portafoglio.', true, 'Il portafoglio è identico, ma costi diversi riducono il rendimento in misura diversa: la classe più cara rende meno.'],
    ['Un fondo comune è sempre un investimento prudente, perché è gestito da professionisti.', false, 'Mito diffuso: un fondo azionario può perdere molto. Il rischio dipende da ciò in cui il fondo investe, non dal fatto che sia gestito.'],
    ['La banca depositaria custodisce i titoli del fondo e controlla che la SGR rispetti le regole.', true, 'Custodia e controllo sono i suoi compiti principali: separa chi decide gli investimenti da chi tiene materialmente i beni.'],
    ['Comprando quote di un fondo diventi proprietario diretto delle azioni che il fondo detiene.', false, 'Possiedi quote, cioè una frazione del patrimonio del fondo; i titoli appartengono al fondo e sono custoditi dal depositario.'],
    ['Un fondo che ha reso il 15% l’anno scorso renderà probabilmente il 15% anche quest’anno.', false, 'I rendimenti passati non sono indicativi di quelli futuri: dipendono dai mercati, che cambiano di anno in anno.'],
    ['Prima di sottoscrivere un fondo devi ricevere il KID, che riassume obiettivi, rischi e costi.', true, 'Il KID va consegnato prima della sottoscrizione e ha un formato standard europeo, utile per confrontare prodotti diversi.'],
    ['In un fondo chiuso il rimborso delle quote è possibile solo a scadenze prestabilite.', true, 'Nei fondi chiusi si esce alla scadenza o in finestre predefinite; per uscire prima bisogna vendere le quote ad altri, se esiste un mercato.'],
  ],
  mcq: [
    { q: 'Chi prende le decisioni di investimento in un fondo comune?', a: 'La SGR', w: ['La banca depositaria', 'La CONSOB', 'Il collocatore'], e: 'La SGR gestisce il portafoglio; il depositario custodisce e controlla, la CONSOB vigila e il collocatore vende le quote.' },
    { q: 'Un fondo ha attività per 52 milioni €, passività per 2 milioni € e 4 milioni di quote. Quanto vale una quota?', a: '12,50 €', w: ['13,00 €', '13,50 €', '12,00 €'], e: '(52 − 2) mln ÷ 4 mln = 12,50 €. Le passività vanno sottratte prima di dividere per il numero di quote.' },
    { q: 'Perché si dice che il patrimonio di un fondo è “separato”?', a: 'È protetto dai creditori della SGR', w: ['Garantisce un rendimento minimo', 'Non può subire perdite di mercato', 'Paga meno tasse sui guadagni'], e: 'La separazione tutela i sottoscrittori se la SGR o il depositario hanno problemi; non protegge dalle oscillazioni dei mercati.' },
    { q: 'Che cosa differenzia di solito due classi di quote dello stesso fondo?', a: 'Costi, importi minimi e uso dei proventi', w: ['Il portafoglio di titoli in cui investono', 'Il gestore e la banca depositaria', 'Il paese in cui è registrato il fondo'], e: 'Le classi condividono portafoglio e gestore: cambiano condizioni come commissioni, soglie minime e accumulo o distribuzione dei proventi.' },
    { q: 'Dai l’ordine di sottoscrizione di un fondo aperto alle 11 di mattina. A che prezzo entri?', a: 'Al valore della quota del giorno di riferimento', w: ['Al prezzo di borsa registrato alle 11 in punto', 'Al valore della quota del giorno precedente', 'Al prezzo fissato alla nascita del fondo'], e: 'I fondi aperti usano il valore della quota calcolato per il giorno indicato dal regolamento: lo scopri solo dopo aver dato l’ordine.' },
    { q: 'Quale affermazione su un fondo comune azionario è un mito?', a: 'Essendo gestito, non può perdere molto', w: ['Il suo valore può scendere parecchio', 'Ha costi che riducono il rendimento', 'Investe in molti titoli diversi'], e: 'La gestione professionale non elimina il rischio di mercato: in una crisi un fondo azionario scende insieme ai mercati in cui investe.' },
    { q: 'Qual è il compito principale del collocatore?', a: 'Vendere le quote ai risparmiatori', w: ['Scegliere i titoli del portafoglio', 'Custodire i titoli del fondo', 'Controllare l’operato della SGR'], e: 'Il collocatore, spesso una banca o una rete di consulenti, distribuisce il fondo: non lo gestisce né lo custodisce.' },
    { q: 'Nei fondi armonizzati UCITS vale la regola “5/10/40”. A cosa serve?', a: 'A limitare la concentrazione su singoli emittenti', w: ['A fissare le commissioni massime del fondo', 'A garantire il capitale investito dai clienti', 'A stabilire il rendimento obiettivo annuo'], e: 'Un singolo emittente non può superare il 10% del fondo e le posizioni oltre il 5%, sommate, non possono superare il 40%.' },
  ],
  fill: [
    { s: 'La ___ è la società che gestisce il fondo e sceglie in quali titoli investire.', a: 'SGR', w: ['banca depositaria', 'CONSOB', 'Borsa'] },
    { s: 'Il valore della quota si calcola dividendo il ___ del fondo per il numero di quote in circolazione.', a: 'patrimonio netto', w: ['patrimonio lordo', 'fatturato', 'capitale iniziale'] },
    { s: 'In un fondo ___ puoi chiedere il rimborso delle quote in ogni giorno di valorizzazione.', a: 'aperto', w: ['chiuso', 'di private equity', 'pensione'] },
    { s: 'Il ___ è il documento sintetico che descrive obiettivi, rischi e costi del fondo.', a: 'KID', w: ['bilancio', 'rendiconto', 'contratto'] },
    { s: 'Classi diverse dello stesso fondo condividono il portafoglio ma hanno ___ diversi.', a: 'costi', w: ['gestori', 'titoli', 'depositari'] },
  ],
  order: [
    { q: 'Ordina le fasi della sottoscrizione di un fondo aperto', i: ['Leggi il KID', 'Firmi il modulo di sottoscrizione', 'Viene calcolato il valore della quota del giorno', 'Ricevi la conferma con le quote assegnate'], e: 'Prima ti informi, poi sottoscrivi; le quote ti vengono assegnate al valore del giorno di riferimento e infine ricevi la lettera di conferma.' },
    { q: 'Ordina dal meno rischioso al più rischioso (tipicamente)', i: ['Fondo monetario', 'Fondo obbligazionario', 'Fondo bilanciato', 'Fondo azionario'], e: 'Più cresce la quota azionaria, più aumentano oscillazioni e possibili perdite; i monetari investono in titoli a brevissima scadenza.' },
  ],
  cat: [
    { q: 'Compito della SGR o della banca depositaria?', g: [['SGR', ['Sceglie i titoli da comprare', 'Decide quando vendere', 'Definisce la strategia del fondo']], ['Banca depositaria', ['Custodisce i titoli', 'Tiene la liquidità del fondo', 'Controlla la regolarità delle operazioni']]] },
    { q: 'Tra due classi dello stesso fondo: cosa può cambiare e cosa resta uguale?', g: [['Può cambiare', ['Commissioni di gestione', 'Importo minimo', 'Accumulo o distribuzione']], ['Resta uguale', ['Portafoglio di titoli', 'Gestore', 'Politica d’investimento']]] },
  ],
  scen: [
    { s: 'Marta, 34 anni, vuole un investimento prudente per i prossimi 3 anni. In banca le propongono un fondo descritto come “gestito da esperti, quindi sicuro”. Nel KID l’indicatore di rischio è 6 su 7.', q: 'Cosa fa?', o: [
      { t: 'Chiede un’alternativa coerente con rischio basso e orizzonte breve', ok: true, f: 'Il KID parla chiaro: 6 su 7 è un rischio alto. La gestione professionale non rende sicuro un fondo azionario.' },
      { t: 'Sottoscrive: se lo gestiscono esperti, il rischio è sotto controllo', ok: false, f: 'È il mito più comune: i gestori non possono evitare i cali del mercato in cui il fondo investe.' },
      { t: 'Sottoscrive, ma investendo solo metà della somma', ok: false, f: 'Ridurre l’importo non risolve il problema: il prodotto resta incoerente con il suo obiettivo e il suo orizzonte.' },
    ] },
    { s: 'Giorgio, 52 anni, vuole investire 20.000 € in un fondo. Scopre che la classe retail costa l’1,9% annuo, mentre la classe istituzionale dello stesso fondo costa lo 0,9% ma richiede un minimo di 500.000 €.', q: 'Cosa fa?', o: [
      { t: 'Confronta la classe retail con fondi simili più economici', ok: true, f: 'Non può accedere alla classe istituzionale: la mossa utile è confrontare i costi di prodotti analoghi a cui ha davvero accesso.' },
      { t: 'Chiede comunque la classe istituzionale con 20.000 €', ok: false, f: 'L’importo minimo è un requisito della classe: con 20.000 € non può sottoscriverla.' },
      { t: 'Ignora la differenza: un punto in più è poco', ok: false, f: 'Un punto percentuale l’anno, per vent’anni, può mangiare una parte consistente del guadagno complessivo.' },
    ] },
    { s: 'Luca, 41 anni, legge che la SGR che gestisce il suo fondo obbligazionario è in difficoltà finanziarie. Teme di perdere tutto e pensa di chiedere subito il rimborso, anche se il fondo è in linea con i suoi obiettivi.', q: 'Cosa fa?', o: [
      { t: 'Verifica che il patrimonio del fondo sia separato dalla SGR', ok: true, f: 'I beni del fondo, custoditi dal depositario, non rispondono dei debiti della SGR; se serve, la gestione può passare a un’altra società.' },
      { t: 'Chiede il rimborso di tutte le quote senza approfondire', ok: false, f: 'Decisione d’impulso: la crisi della SGR non intacca i titoli del fondo, che appartengono ai sottoscrittori.' },
      { t: 'Sottoscrive altre quote per “sostenere” la SGR', ok: false, f: 'Comprare quote non aiuta la SGR: il patrimonio del fondo è separato e i problemi della società non si risolvono così.' },
    ] },
    { s: 'Sara, 29 anni, deve scegliere tra due fondi azionari europei. Il fondo A l’anno scorso ha fatto +22%, il B +14%. A costa il 2,2% annuo, B lo 0,8%, e sugli ultimi 10 anni i loro rendimenti sono stati simili.', q: 'Come sceglie?', o: [
      { t: 'Guarda costi e risultati su più anni, non su uno solo', ok: true, f: 'Un singolo anno dice poco: su periodi lunghi i costi più bassi sono uno dei pochi vantaggi davvero prevedibili.' },
      { t: 'Sceglie A: l’ultimo anno ha battuto B di ben 8 punti', ok: false, f: 'Scegliere in base all’ultimo anno è un errore comune: le performance eccezionali raramente si ripetono.' },
      { t: 'Divide a metà tra A e B, così non può sbagliare', ok: false, f: 'Due fondi quasi uguali non diversificano davvero, e metà del capitale continuerebbe a pagare costi alti.' },
    ] },
  ],
  tip: 'Prima di sottoscrivere un fondo leggi il KID: indicatore di rischio, costi e periodo di detenzione consigliato ti dicono in pochi minuti se fa per te.',
});
