FQC(42, {
  intro: 'Gli ETF sono fondi quotati in borsa: scopri come replicano un indice, cosa significa il marchio UCITS, accumulo o distribuzione e tracking error.',
  cards: [
    { t: 'Si compra come un’azione', x: 'Un ETF (Exchange Traded Fund) è un fondo, quasi sempre indicizzato, quotato in borsa. Lo compri dal conto titoli durante la giornata, a prezzo di mercato, pagando la commissione del broker e lo spread.', v: { k: 'steps', s: ['Scegli l’indice', 'Confronta gli ETF', 'Inserisci l’ordine', 'Quote nel dossier titoli'] } },
    { t: 'La replica fisica', x: 'L’ETF compra i titoli dell’indice: tutti (replica totale) o un campione rappresentativo (replica ottimizzata). Dentro il fondo ci sono davvero le azioni o le obbligazioni che compongono l’indice.', v: { k: 'icons', d: [['📦', 'Totale: tutti i titoli'], ['🎯', 'Ottimizzata: un campione']] } },
    { t: 'La replica sintetica', x: 'L’ETF detiene un paniere di titoli e firma uno swap con una banca, che gli paga il rendimento dell’indice. Le regole UCITS limitano l’esposizione verso la controparte, che di solito è anche coperta da garanzie.', v: { k: 'stat', n: '10%', l: 'esposizione massima del fondo verso una banca controparte (UCITS)' } },
    { t: 'Il marchio UCITS', x: 'UCITS è la normativa europea sui fondi armonizzati: impone regole su diversificazione, liquidità, custodia separata e trasparenza. Un ETF UCITS può essere distribuito in tutta l’Unione Europea.', v: { k: 'icons', d: [['🇪🇺', 'Regole europee comuni'], ['⚖️', 'Limiti di concentrazione'], ['🔐', 'Custodia separata']] } },
    { t: 'Accumulazione o distribuzione', x: 'Gli ETF ad accumulazione reinvestono dividendi e cedole nel fondo; quelli a distribuzione li pagano periodicamente ai detentori. Il portafoglio può essere identico: cambia solo cosa succede ai proventi.', v: { k: 'vs', a: ['Accumulazione', 'Reinveste i proventi'], b: ['Distribuzione', 'Ti paga i proventi'] } },
    { t: 'Quanto bene replica?', x: 'La tracking difference è lo scarto di rendimento tra ETF e indice in un periodo; il tracking error misura quanto questo scarto varia nel tempo. Più sono piccoli, più la replica è fedele.', v: { k: 'formula', f: 'Tracking difference = rendimento ETF − rendimento indice', n: 'Es.: 7,8% − 8,0% = −0,2%' } },
  ],
  terms: [
    ['ETF', 'Fondo, di solito indicizzato, le cui quote si comprano e vendono in borsa durante la giornata.'],
    ['Replica fisica', 'Metodo in cui il fondo detiene direttamente tutti o parte dei titoli dell’indice.'],
    ['Replica sintetica', 'Metodo che ottiene il rendimento dell’indice tramite un contratto swap con una controparte.'],
    ['UCITS', 'Normativa europea sui fondi armonizzati: fissa regole di diversificazione, liquidità e trasparenza.'],
    ['Accumulazione', 'Politica in cui dividendi e cedole incassati vengono reinvestiti nel fondo invece di essere pagati.'],
    ['Distribuzione', 'Politica in cui i proventi incassati vengono versati periodicamente ai detentori delle quote.'],
    ['Tracking error', 'Volatilità della differenza tra i rendimenti del fondo e quelli dell’indice che replica.'],
    ['Market maker', 'Operatore che espone di continuo prezzi di acquisto e vendita, garantendo liquidità in borsa.'],
  ],
  tf: [
    ['Un ETF si può comprare e vendere in borsa durante la giornata, a prezzi che cambiano di continuo.', true, 'Le quote sono negoziate in continua e il prezzo cambia durante la giornata, mentre un fondo tradizionale ha un solo valore al giorno.'],
    ['Gli ETF sono privi di rischio perché replicano un indice.', false, 'Mito: un ETF azionario segue l’indice anche quando scende. Replicare un indice toglie il rischio del singolo gestore, non quello di mercato.'],
    ['In un ETF a replica sintetica il rendimento dell’indice arriva da uno swap con una controparte.', true, 'L’ETF scambia il rendimento del paniere che detiene con quello dell’indice; il rischio controparte è limitato da regole UCITS e garanzie.'],
    ['Un ETF ad accumulazione non incassa mai dividendi dalle società in portafoglio.', false, 'Li incassa, ma invece di pagarli a te li reinveste nel fondo: è il valore della quota a beneficiarne.'],
    ['Una tracking difference di −0,2% indica che l’ETF ha reso 0,2 punti percentuali meno dell’indice.', true, 'È lo scarto di rendimento nel periodo; spesso è vicino al TER, perché i costi sono la prima causa di sottoperformance.'],
    ['Due ETF sullo stesso indice danno sempre esattamente lo stesso rendimento.', false, 'Costi, metodo di replica, prestito titoli e trattamento dei dividendi creano differenze, anche di qualche decimale l’anno.'],
    ['Un ETF a replica fisica ottimizzata detiene solo un campione dei titoli dell’indice.', true, 'Si usa per indici con migliaia di titoli o poco liquidi: il campione riduce i costi, a prezzo di un tracking error un po’ più alto.'],
    ['Se la società che emette l’ETF fallisce, le quote perdono tutto il loro valore.', false, 'Il patrimonio dell’ETF è separato da quello dell’emittente e custodito dal depositario: i titoli restano dei detentori delle quote.'],
    ['Il marchio UCITS indica che l’ETF rispetta regole europee su diversificazione e trasparenza.', true, 'La normativa impone limiti di concentrazione, liquidità, custodia separata e un KID standard: è una tutela, non una garanzia di guadagno.'],
    ['Comprando un ETF paghi solo il TER, senza nessun altro costo.', false, 'Oltre al TER ci sono la commissione del broker, lo spread denaro-lettera e l’imposta di bollo sul dossier titoli.'],
  ],
  mcq: [
    { q: 'Qual è la differenza principale tra un ETF e un fondo comune tradizionale?', a: 'L’ETF è quotato e scambiato in borsa', w: ['L’ETF non ha un patrimonio separato', 'L’ETF garantisce il rendimento dell’indice', 'L’ETF può investire in un solo titolo'], e: 'Entrambi sono fondi con patrimonio separato; l’ETF però si negozia in borsa durante la giornata, il fondo tradizionale si sottoscrive tramite la SGR.' },
    { q: 'Come ottiene il rendimento dell’indice un ETF a replica sintetica?', a: 'Con un contratto swap con una controparte', w: ['Comprando tutti i titoli dell’indice', 'Comprando un campione dei titoli', 'Acquistando quote di altri fondi'], e: 'La controparte paga all’ETF il rendimento dell’indice in cambio di quello del paniere di titoli che il fondo detiene.' },
    { q: 'Un indice ha reso il 9,0% e l’ETF che lo replica l’8,8%. Qual è la tracking difference?', a: '−0,2%', w: ['+0,2%', '−1,8%', '+17,8%'], e: '8,8% − 9,0% = −0,2%: l’ETF ha reso due decimi di punto meno dell’indice, in linea con costi annui di circa lo 0,2%.' },
    { q: 'Paolo vuole ricevere ogni anno i dividendi sul conto. Quale versione di ETF fa per lui?', a: 'A distribuzione', w: ['Ad accumulazione', 'A replica sintetica', 'A replica ottimizzata'], e: 'Solo la versione a distribuzione paga i proventi; il metodo di replica è un aspetto diverso, che non decide cosa succede ai dividendi.' },
    { q: 'Cosa misura il tracking error?', a: 'Quanto varia nel tempo lo scarto dall’indice', w: ['Il costo annuo complessivo dell’ETF', 'Il rischio di fallimento dell’emittente', 'La distanza tra prezzo denaro e lettera'], e: 'È la deviazione standard delle differenze di rendimento: un tracking error basso indica una replica regolare e fedele.' },
    { q: 'Qual è un rischio tipico della replica sintetica?', a: 'Il rischio di controparte dello swap', w: ['Il rischio di uscire dalla quotazione', 'Il rischio di cambiare indice ogni giorno', 'Il rischio di commissioni d’ingresso'], e: 'Se la controparte non paga, l’ETF può subire una perdita; le regole UCITS limitano l’esposizione verso di lei e le garanzie la riducono.' },
    { q: 'Chi contribuisce a tenere il prezzo di borsa di un ETF vicino al valore dei titoli che contiene?', a: 'Market maker e partecipanti autorizzati', w: ['La Banca centrale europea', 'L’emittente, con un prezzo fisso', 'La CONSOB, con un tetto ai prezzi'], e: 'Comprano e vendono quote e possono crearne o rimborsarne: gli arbitraggi tengono il prezzo di borsa vicino al NAV.' },
    { q: 'Quale di queste convinzioni sugli ETF è sbagliata?', a: 'Seguendo un indice, non possono perdere', w: ['Possono replicare indici obbligazionari', 'Sono fondi con patrimonio separato', 'Possono distribuire i dividendi'], e: 'Un ETF replica l’indice nel bene e nel male: se l’indice perde il 20%, anche l’ETF perde circa il 20%.' },
  ],
  fill: [
    { s: 'Un ETF ___ reinveste automaticamente i dividendi e le cedole che incassa.', a: 'ad accumulazione', w: ['a distribuzione', 'a cedola fissa', 'a capitale garantito'] },
    { s: 'Nella replica ___ l’ETF detiene direttamente i titoli che compongono l’indice.', a: 'fisica', w: ['sintetica', 'derivata', 'inversa'] },
    { s: 'La volatilità dello scarto tra i rendimenti dell’ETF e quelli dell’indice si chiama tracking ___.', a: 'error', w: ['difference', 'ratio', 'spread'] },
    { s: 'La normativa europea che armonizza le regole dei fondi aperti, ETF compresi, si chiama ___.', a: 'UCITS', w: ['MiFID', 'PRIIPs', 'Basilea'] },
    { s: 'In borsa un ETF si compra al prezzo ___ e si vende al prezzo denaro.', a: 'lettera', w: ['medio', 'di chiusura', 'nominale'] },
  ],
  order: [
    { q: 'Ordina i passi per arrivare a comprare un ETF', i: ['Definisci obiettivo e orizzonte', 'Scegli l’asset class e l’indice', 'Confronta gli ETF su quell’indice', 'Inserisci l’ordine di acquisto in borsa'], e: 'Si parte dall’obiettivo, poi si sceglie l’esposizione e solo alla fine il prodotto: confrontare ETF ha senso tra quelli sullo stesso indice.' },
    { q: 'Ordina il percorso dei dividendi in un ETF a distribuzione', i: ['Le società in portafoglio pagano i dividendi', 'L’ETF li incassa', 'L’ETF li tiene fino alla data di stacco', 'L’ETF li versa ai detentori delle quote'], e: 'I dividendi passano dalle aziende al fondo e da lì, alle date previste, a chi possiede le quote.' },
  ],
  cat: [
    { q: 'Replica fisica o sintetica?', g: [['Fisica', ['Detiene tutti i titoli dell’indice', 'Detiene un campione dei titoli', 'Può prestare i titoli per ricavi extra']], ['Sintetica', ['Usa un contratto swap', 'Ha un rischio di controparte sullo swap', 'Il paniere detenuto può differire dall’indice']]] },
    { q: 'Accumulazione o distribuzione?', g: [['Accumulazione', ['Reinveste i dividendi', 'Sfrutta l’interesse composto in automatico', 'Non genera flussi di cassa per te']], ['Distribuzione', ['Paga i dividendi periodicamente', 'Adatta a chi cerca un’entrata periodica', 'La quota scende allo stacco del provento']]] },
  ],
  scen: [
    { s: 'Elena, 45 anni, confronta due ETF sullo stesso indice azionario globale. A: TER 0,20%, negli ultimi 5 anni ha reso in media 0,15 punti meno dell’indice. B: TER 0,12%, ma ha reso in media 0,40 punti meno dell’indice.', q: 'Cosa guarda per scegliere?', o: [
      { t: 'Lo scarto effettivo dall’indice: preferisce A', ok: true, f: 'La tracking difference misura ciò che hai davvero ottenuto rispetto all’indice: include costi, qualità della replica e ricavi extra, non solo il TER.' },
      { t: 'Il TER più basso: preferisce B', ok: false, f: 'Il TER è solo una parte del quadro: B ha replicato peggio l’indice e ha reso meno nonostante il costo dichiarato inferiore.' },
      { t: 'Nulla: replicano lo stesso indice, sono uguali', ok: false, f: 'Stesso indice non vuol dire stesso risultato: 0,25 punti l’anno di differenza si sommano nel tempo.' },
    ] },
    { s: 'Matteo, 67 anni, è in pensione e vuole investire parte dei risparmi in un ETF obbligazionario, usando i proventi per integrare la pensione ogni anno senza dover vendere quote.', q: 'Quale versione sceglie?', o: [
      { t: 'La versione a distribuzione', ok: true, f: 'Paga periodicamente cedole e proventi: Matteo riceve un’entrata senza dover decidere ogni volta quante quote vendere.' },
      { t: 'La versione ad accumulazione, senza ritirare nulla', ok: false, f: 'Reinvestirebbe i proventi: per avere un’entrata Matteo dovrebbe vendere quote, proprio ciò che voleva evitare.' },
      { t: 'L’ETF obbligazionario con la cedola più alta, qualunque sia il rischio', ok: false, f: 'Cedole molto alte spesso significano emittenti più rischiosi: per un pensionato la qualità del credito conta più del rendimento massimo.' },
    ] },
    { s: 'Chiara, 31 anni, vuole comprare un ETF alle 9:01, appena aperta la borsa. Nota che lo spread tra denaro e lettera è dell’1%, mentre di solito è intorno allo 0,1%.', q: 'Cosa fa?', o: [
      { t: 'Aspetta che lo spread si normalizzi e usa un ordine limite', ok: true, f: 'Nei primi minuti gli spread sono spesso più larghi; più tardi e con un limite di prezzo evita di pagare un costo inutile.' },
      { t: 'Compra subito al meglio: lo spread è un dettaglio', ok: false, f: 'Lo spread è un costo reale: con l’1% paghi circa lo 0,5% sopra il prezzo medio, più di due anni di un TER dello 0,2%.' },
      { t: 'Rinuncia agli ETF: comprarli in borsa costa troppo', ok: false, f: 'Il problema è il momento scelto, non lo strumento: nelle ore centrali lo spread torna di solito su livelli contenuti.' },
    ] },
    { s: 'Federico, 38 anni, possiede un ETF UCITS a replica sintetica. Su un forum legge che “i sintetici sono derivati pericolosi che possono azzerarsi da un giorno all’altro”.', q: 'Cosa fa?', o: [
      { t: 'Verifica nei documenti dell’ETF controparti e garanzie', ok: true, f: 'Il rischio controparte esiste ma è limitato dalle regole UCITS e dalle garanzie: conoscerlo permette di decidere senza panico.' },
      { t: 'Vende subito: un derivato può azzerare tutto', ok: false, f: 'Nei sintetici UCITS l’esposizione alla controparte è limitata e coperta da garanzie: il rischio non è “tutto o niente”.' },
      { t: 'Ignora il tema: il rischio di controparte non esiste', ok: false, f: 'Esiste, anche se contenuto: sapere come funziona fa parte di una scelta consapevole.' },
    ] },
  ],
  tip: 'Confronta gli ETF sullo stesso indice guardando insieme TER, tracking difference, dimensione del fondo e spread in borsa, non solo il costo dichiarato.',
});
