FQC(43, {
  intro: 'Pochi decimali di costo all’anno possono valere migliaia di euro nel tempo: impara a leggere TER e commissioni e a calcolarne l’effetto composto.',
  cards: [
    { t: 'Il TER', x: 'Il TER (Total Expense Ratio) indica i costi annui di gestione di un fondo in percentuale del patrimonio. Non lo paghi a parte: viene prelevato giorno per giorno ed è già incorporato nel valore della quota.', v: { k: 'formula', f: 'Costo annuo ≈ capitale investito × TER', n: 'Es.: 20.000 € × 1,5% = 300 € l’anno' } },
    { t: 'Commissioni di ingresso e uscita', x: 'Alcuni fondi applicano una commissione quando entri (sottoscrizione) o quando esci (rimborso). Con il 3% d’ingresso su 10.000 € ne investi davvero 9.700: i primi 300 € non lavorano per te.', v: { k: 'stat', n: '9.700 €', l: 'investiti davvero su 10.000 € con il 3% d’ingresso' } },
    { t: 'La commissione di performance', x: 'È una quota dell’extra-rendimento rispetto a un parametro di riferimento. Se il fondo fa +8%, il benchmark +5% e la commissione è del 20%, il gestore trattiene lo 0,6%.', v: { k: 'steps', s: ['Fondo +8%', 'Benchmark +5%', 'Extra-rendimento 3%', '20% di 3% = 0,6%'] } },
    { t: 'I costi fuori dal TER', x: 'Il TER non dice tutto: ci sono i costi di compravendita dei titoli sostenuti dal fondo, le commissioni del tuo intermediario, lo spread in borsa e l’imposta di bollo dello 0,2% annuo.', v: { k: 'icons', d: [['🔄', 'Compravendite del fondo'], ['💼', 'Commissioni dell’intermediario'], ['↔️', 'Spread denaro-lettera'], ['🧾', 'Imposta di bollo']] } },
    { t: 'L’effetto composto dei costi', x: '10.000 € per 30 anni con un rendimento lordo ipotetico del 6%: con costi dello 0,2% annuo arrivi a circa 54.300 €, con l’1% a 43.200 €, con il 2% a 32.400 €. I soldi trattenuti smettono di rendere.', v: { k: 'bars', d: [['Costi 0,2%', 54271], ['Costi 1%', 43219], ['Costi 2%', 32434]], u: '€' } },
    { t: 'Ragiona in euro', x: 'Le percentuali ingannano: l’1,8% sembra poco, ma su 50.000 € sono 900 € ogni anno. Per legge (MiFID II) l’intermediario ti invia ogni anno un rendiconto dei costi sostenuti, in euro e in percentuale.', v: { k: 'vs', a: ['In percentuale', '1,8%: sembra poco'], b: ['In euro', '900 € l’anno su 50.000 €'] } },
  ],
  terms: [
    ['TER', 'Total Expense Ratio: costi annui di gestione del fondo espressi in percentuale del patrimonio.'],
    ['Commissione di sottoscrizione', 'Percentuale trattenuta sull’importo versato al momento dell’ingresso nel fondo.'],
    ['Commissione di rimborso', 'Percentuale trattenuta sull’importo riscattato quando esci dal fondo.'],
    ['Commissione di performance', 'Quota dell’extra-rendimento rispetto a un parametro che il gestore trattiene come incentivo.'],
    ['High watermark', 'Regola per cui l’incentivo al gestore scatta solo se la quota supera il suo massimo precedente.'],
    ['Costi di transazione', 'Spese sostenute dal fondo per comprare e vendere titoli, non comprese nel TER.'],
    ['Effetto composto dei costi', 'Perdita che cresce nel tempo perché il denaro trattenuto non genera più rendimento.'],
    ['Benchmark', 'Indice di riferimento usato per confrontare i risultati del fondo e calcolarne l’extra-rendimento.'],
  ],
  tf: [
    ['Il TER viene addebitato separatamente sul conto corrente una volta l’anno.', false, 'Il TER è prelevato pro quota ogni giorno dal patrimonio del fondo: lo trovi già incorporato nel valore della quota.'],
    ['Una commissione d’ingresso del 3% su 10.000 € riduce subito il capitale investito a 9.700 €.', true, 'I 300 € non lavorano per te: per tornare in pari serve prima un guadagno di circa il 3,1% (300 ÷ 9.700).'],
    ['Una differenza di costo dell’1% annuo è irrilevante su un orizzonte di 30 anni.', false, 'Mito: per l’effetto composto, l’1% annuo in più può ridurre il capitale finale di circa un quarto in 30 anni.'],
    ['Il TER non comprende i costi di compravendita dei titoli sostenuti dal fondo.', true, 'I costi di transazione del portafoglio sono esclusi dal TER: nel KID sono indicati a parte.'],
    ['Una commissione di performance si paga solo se il fondo supera il suo parametro di riferimento.', true, 'È calcolata sull’extra-rendimento rispetto al benchmark o all’obiettivo fissato: senza sovraperformance non è dovuta.'],
    ['Un fondo più costoso rende sempre di più, perché i costi pagano gestori migliori.', false, 'Non c’è un legame affidabile tra costo e risultato: anzi, costi alti sono uno dei segnali più affidabili di rendimenti netti più bassi.'],
    ['Con l’high watermark, dopo una perdita il gestore non incassa commissioni di performance sul semplice recupero.', true, 'La commissione torna dovuta solo quando la quota supera il massimo precedente: risalire fino al livello già raggiunto non viene premiato.'],
    ['Su 30.000 € investiti, un TER dell’1,5% costa circa 450 € l’anno.', true, '30.000 × 1,5% = 450 €. Tradurre i costi in euro aiuta a capire quanto pesano davvero.'],
    ['Le commissioni di uscita si pagano anche se non riscatti mai le quote.', false, 'Si applicano solo al momento del rimborso; in alcuni fondi diminuiscono con gli anni di permanenza fino ad azzerarsi.'],
    ['Un costo dello 0,5% annuo pesa di più su un rendimento lordo del 3% che su uno del 9%.', true, 'Sul 3% si porta via un sesto del guadagno, sul 9% circa un diciottesimo: con rendimenti attesi bassi i costi contano ancora di più.'],
  ],
  mcq: [
    { q: 'Investi 25.000 € in un fondo con TER dell’1,2%. Quanto paghi circa di costi di gestione in un anno?', a: '300 €', w: ['120 €', '30 €', '1.200 €'], e: '25.000 × 1,2% = 300 €. Il TER non lo vedi addebitato, ma riduce ogni giorno il valore della quota.' },
    { q: 'Un fondo fa +10%, il benchmark +6%. La commissione di performance è il 20% dell’extra-rendimento. Quanto costa?', a: '0,8%', w: ['2,0%', '1,2%', '4,0%'], e: 'Extra-rendimento: 10% − 6% = 4%. Il 20% del 4% è lo 0,8%, che si aggiunge agli altri costi del fondo.' },
    { q: 'Quale costo NON è compreso nel TER di un fondo?', a: 'La commissione di sottoscrizione', w: ['La commissione di gestione', 'Il compenso del depositario', 'Le spese amministrative del fondo'], e: 'Il TER raccoglie i costi ricorrenti del fondo; le commissioni di ingresso e uscita sono una tantum e si pagano a parte.' },
    { q: 'Perché l’effetto dei costi cresce più che proporzionalmente con gli anni?', a: 'I soldi trattenuti non producono più rendimento', w: ['Il TER aumenta per legge ogni anno', 'Sui costi si pagano tasse ogni anno', 'I costi si ricalcolano a ogni versamento'], e: 'Ogni euro di costo smette di capitalizzare: perdi il costo e anche tutti i rendimenti futuri che avrebbe generato.' },
    { q: 'Due fondi rendono il 6% lordo; A costa lo 0,3% annuo, B il 2%. Partendo da 10.000 €, quale cifra si avvicina di più alla differenza tra A e B dopo 30 anni?', a: 'Circa 20.000 €', w: ['Circa 500 €', 'Circa 5.100 €', 'Circa 60.000 €'], e: 'A arriva a circa 52.800 €, B a circa 32.400 €. Sommare 1,7% × 30 anni (5.100 €) sottostima molto: i costi si compongono.' },
    { q: 'Su quale portafoglio un costo annuo dell’1% si mangia la quota maggiore del rendimento?', a: 'Uno che rende il 3% lordo', w: ['Uno che rende il 5% lordo', 'Uno che rende l’8% lordo', 'Uno che rende il 10% lordo'], e: 'Sul 3% l’1% di costo si porta via un terzo del rendimento; sull’8% “solo” un ottavo. Con rendimenti bassi, i costi pesano di più.' },
    { q: 'Quale affermazione sui costi è un errore comune?', a: '“Se il fondo rende bene, i costi non contano”', w: ['“Il TER riduce ogni giorno la quota”', '“L’ingresso riduce il capitale investito”', '“I costi vanno letti anche in euro”'], e: 'I costi si pagano sempre, anche negli anni buoni, e si compongono: un buon rendimento lordo non rende irrilevante quanto ne viene trattenuto.' },
    { q: 'Dove trovi, in un formato standard europeo, i costi di un fondo prima di sottoscriverlo?', a: 'Nel KID', w: ['Nell’estratto conto corrente', 'Nella dichiarazione dei redditi', 'Nel bilancio della SGR'], e: 'Il KID riporta costi una tantum, ricorrenti e accessori, e mostra il loro impatto annuo sul rendimento.' },
  ],
  fill: [
    { s: 'Il ___ indica i costi annui di gestione di un fondo in percentuale del patrimonio.', a: 'TER', w: ['NAV', 'KID', 'benchmark'] },
    { s: 'La commissione di ___ si paga una sola volta, al momento dell’ingresso nel fondo.', a: 'sottoscrizione', w: ['rimborso', 'performance', 'gestione'] },
    { s: 'Grazie alla clausola di ___, la commissione di performance si paga solo se la quota supera il suo massimo precedente.', a: 'high watermark', w: ['hurdle rate', 'benchmark', 'switch'] },
    { s: 'I costi riducono il capitale anno dopo anno e il loro effetto è ___: cresce con il passare del tempo.', a: 'composto', w: ['costante', 'trascurabile', 'una tantum'] },
    { s: 'Le commissioni di uscita si pagano al momento del ___ delle quote.', a: 'rimborso', w: ['acquisto', 'dividendo', 'calcolo'] },
  ],
  order: [
    { q: 'Ordina dal capitale finale più alto al più basso: 10.000 € per 30 anni al 6% lordo con costi annui di…', i: ['0,2%', '0,8%', '1,5%', '2,5%'], e: 'A parità di rendimento lordo, ogni decimale di costo in più riduce il capitale finale: da circa 54.300 € a circa 28.100 €.' },
    { q: 'Ordina dal più economico al più caro: 10.000 € investiti per un solo anno', i: ['TER 0,3%, nessuna commissione', 'TER 0,5% + 50 € di commissioni', 'TER 1,5%, nessuna commissione', 'TER 1% + ingresso del 2%'], e: 'In euro: 30 €, 100 €, 150 € e 300 €. Su un orizzonte breve le commissioni una tantum pesano moltissimo.' },
  ],
  cat: [
    { q: 'Costo ricorrente o una tantum?', g: [['Ricorrente', ['TER', 'Imposta di bollo annua', 'Canone annuo del conto titoli']], ['Una tantum', ['Commissione di sottoscrizione', 'Commissione di rimborso', 'Commissione del broker su un acquisto']]] },
    { q: 'Compreso nel TER o escluso?', g: [['Compreso', ['Commissione di gestione', 'Compenso del depositario', 'Spese amministrative del fondo']], ['Escluso', ['Commissione d’ingresso', 'Costi di compravendita del portafoglio', 'Commissione del tuo broker']]] },
  ],
  scen: [
    { s: 'Anna, 40 anni, vuole investire 30.000 € per 20 anni sull’azionario globale. In banca le propongono un fondo con il 3% d’ingresso e il 2% di costi annui. Un prodotto con esposizione simile costa lo 0,25% annuo, senza ingresso.', q: 'Cosa fa?', o: [
      { t: 'Confronta in euro i costi delle due soluzioni sui 20 anni', ok: true, f: 'Il primo anno sono 900 € d’ingresso più 600 € di gestione contro 75 €. Con un 6% lordo ipotetico, in 20 anni la differenza supera i 25.000 €.' },
      { t: 'Sceglie il fondo: il 2% annuo sembra comunque poco', ok: false, f: 'In percentuale sembra poco, ma il 2% l’anno per 20 anni, composto, si mangia una parte enorme del guadagno.' },
      { t: 'Sceglie il fondo, ma chiede di non pagare il bollo', ok: false, f: 'Il bollo è un’imposta di legge uguale per tutti e non si negozia: il vero margine di risparmio è sui costi del prodotto.' },
    ] },
    { s: 'Davide, 36 anni, potrebbe aver bisogno dei soldi tra un anno per l’anticipo di una casa. Il fondo che gli propongono non ha commissioni d’ingresso, ma ne ha di uscita: 3% il primo anno, poi a scalare fino a zero dopo 4 anni.', q: 'Cosa fa?', o: [
      { t: 'Lo scarta: uscendo presto pagherebbe la penale più alta', ok: true, f: 'Le commissioni d’uscita decrescenti premiano chi resta a lungo: se rischi di uscire presto, paghi proprio la parte più cara.' },
      { t: 'Lo sottoscrive: “senza costi d’ingresso” significa gratis', ok: false, f: 'Il costo è solo spostato all’uscita: per chi esce presto può pesare quanto, o più di, un ingresso.' },
      { t: 'Lo sottoscrive e spera di non dover uscire', ok: false, f: 'Sperare non è una strategia: i soldi per un obiettivo vicino vanno su strumenti liquidi e senza penali.' },
    ] },
    { s: 'Irene, 50 anni, ha un fondo bilanciato da 10 anni. Nel rendiconto annuale dei costi legge che ha pagato 1.150 € su 50.000 € investiti, cioè il 2,3%. Non se n’era mai accorta.', q: 'Cosa fa?', o: [
      { t: 'Chiede il dettaglio dei costi e confronta alternative', ok: true, f: 'Prima capisce da dove nasce il 2,3%, poi valuta se cambiare conviene davvero al netto di eventuali penali e imposte sulle plusvalenze.' },
      { t: 'Ignora il rendiconto: il fondo ha comunque guadagnato', ok: false, f: 'Guadagnare non significa guadagnare abbastanza: 1.150 € l’anno, composti per altri anni, sono molti soldi.' },
      { t: 'Vende tutto immediatamente, senza fare confronti', ok: false, f: 'Uscire d’impulso può far pagare commissioni di uscita e tasse: prima si confronta, poi si decide.' },
    ] },
    { s: 'Stefano, 33 anni, investe 20.000 € una sola volta e li terrà per 25 anni. Sullo stesso indice trova due ETF: A con costi annui dello 0,07% e spread in borsa dello 0,15%; B con costi annui dello 0,20% e spread dello 0,05%.', q: 'Quale sceglie?', o: [
      { t: 'A: su 25 anni il costo ricorrente pesa più dello spread', ok: true, f: 'Lo spread si paga in acquisto e in vendita; il TER ogni anno. 0,13 punti risparmiati per 25 anni battono di gran lunga 0,10 punti di spread in più.' },
      { t: 'B: lo spread è il costo che pesa di più in assoluto', ok: false, f: 'Per chi compra una volta e tiene a lungo, il costo ricorrente domina: lo spread conta di più per chi compra e vende spesso.' },
      { t: 'È indifferente: sono costi tutti sotto l’1% annuo', ok: false, f: 'Anche differenze piccole, ripetute per 25 anni e composte, diventano centinaia di euro.' },
    ] },
  ],
  tip: 'Trasforma sempre i costi in euro e proiettali sugli anni in cui terrai l’investimento: è il modo più semplice per capire quanto pesano davvero.',
});
