FQC(44, {
  intro: 'Battere il mercato o replicarlo? Scopri come lavorano i gestori attivi e passivi, cosa dicono i dati sui risultati e quanto contano i costi.',
  cards: [
    { t: 'Due filosofie', x: 'Il gestore attivo seleziona titoli e momenti di ingresso per fare meglio del mercato. Il gestore passivo replica un indice: accetta il rendimento del mercato, meno costi contenuti.', v: { k: 'vs', a: ['Gestione attiva', 'Prova a battere il benchmark'], b: ['Gestione passiva', 'Replica il benchmark'] } },
    { t: 'L’aritmetica della gestione attiva', x: 'Tutti gli investitori insieme possiedono il mercato: prima dei costi, la media degli attivi ottiene il rendimento del mercato. Dopo costi più alti, la media degli attivi resta sotto quella dei passivi.', v: { k: 'formula', f: 'Media degli attivi (prima dei costi) = rendimento del mercato', n: 'Al netto dei costi, l’attivo medio fa peggio del passivo medio' } },
    { t: 'Il peso dei costi', x: 'Esempio: se il mercato fa il 7%, un fondo passivo con costi dello 0,2% offre circa il 6,8%; un attivo medio con costi dell’1,5% circa il 5,5%. Molti studi confermano lo svantaggio degli attivi sul lungo periodo.', v: { k: 'bars', d: [['Mercato', 7], ['Passivo (−0,2%)', 6.8], ['Attivo medio (−1,5%)', 5.5]], u: '%' } },
    { t: 'Vincere non basta: bisogna ripetersi', x: 'I fondi che battono il mercato in un periodo raramente si ripetono nel successivo. E molti fondi andati male vengono chiusi o fusi: è il survivorship bias, che abbellisce le statistiche.', v: { k: 'icons', d: [['🏆', 'Primi oggi'], ['🎲', 'Di rado primi domani'], ['🪦', 'I peggiori spariscono']] } },
    { t: 'Attivi solo di nome', x: 'Alcuni fondi si dichiarano attivi ma tengono un portafoglio quasi identico all’indice, facendo pagare costi da gestione attiva (closet indexing). L’active share misura quanto un fondo si discosta davvero.', v: { k: 'scale', a: 'Uguale all’indice', b: 'Molto diverso', d: [['ETF indicizzato', 2], ['Closet indexer', 35], ['Attivo concentrato', 90]] } },
    { t: 'Il meglio dei due mondi', x: 'Molti investitori combinano i due approcci: un nucleo (core) a basso costo che replica i mercati principali e una parte minore (satellite) affidata a scelte attive in cui credono.', v: { k: 'pie', d: [['Core passivo', 80], ['Satellite attivo', 20]] } },
  ],
  terms: [
    ['Gestione attiva', 'Strategia che seleziona titoli e tempi per ottenere un rendimento superiore al benchmark.'],
    ['Gestione passiva', 'Strategia che replica un indice per ottenerne il rendimento con costi contenuti.'],
    ['Alfa', 'Rendimento extra rispetto al benchmark, a parità di rischio, attribuibile alle scelte del gestore.'],
    ['Closet indexing', 'Pratica di un fondo che si dichiara attivo ma di fatto replica l’indice, con costi da fondo attivo.'],
    ['Active share', 'Percentuale del portafoglio che differisce dalla composizione dell’indice di riferimento.'],
    ['Survivorship bias', 'Distorsione che migliora le statistiche perché esclude i fondi chiusi o fusi per scarsi risultati.'],
    ['Market timing', 'Tentativo di entrare e uscire dal mercato anticipandone rialzi e ribassi.'],
    ['Core-satellite', 'Approccio che unisce un nucleo passivo a basso costo e una parte minore gestita attivamente.'],
  ],
  tf: [
    ['Prima dei costi, il rendimento medio dei gestori attivi è circa uguale a quello del mercato.', true, 'Insieme gli investitori detengono il mercato: chi lo batte lo fa a spese di altri. Dopo i costi, la media degli attivi scende sotto l’indice.'],
    ['Un fondo che ha battuto l’indice negli ultimi 3 anni lo batterà quasi certamente anche nei prossimi 3.', false, 'Gli studi sulla persistenza mostrano che pochi fondi restano in cima alla classifica: i risultati passati non si ripetono in modo affidabile.'],
    ['Un ETF che replica un indice azionario perde quando l’indice perde.', true, 'La gestione passiva non cerca di evitare i ribassi: segue l’indice nel bene e nel male, meno i costi.'],
    ['Gestione attiva significa rendimenti più alti, perché c’è un esperto che sceglie.', false, 'Mito: storicamente la maggioranza dei fondi attivi ha fatto peggio del proprio indice sul lungo periodo, soprattutto a causa dei costi.'],
    ['Il survivorship bias fa apparire i fondi attivi migliori di quanto siano stati in media.', true, 'I fondi peggiori vengono chiusi o fusi e spariscono dalle statistiche: restano i “sopravvissuti”, in media più bravi.'],
    ['Un fondo con active share molto bassa e costi elevati potrebbe essere un closet indexer.', true, 'Portafoglio quasi identico all’indice ma costi da gestione attiva: è il peggio dei due mondi.'],
    ['La gestione passiva elimina ogni decisione da parte dell’investitore.', false, 'Restano scelte importanti: quali indici, con quali pesi, quanto investire e come comportarsi nei ribassi.'],
    ['Nei forti ribassi i fondi attivi riescono sempre a limitare le perdite rispetto all’indice.', false, 'Convinzione diffusa, ma i dati non la confermano in modo sistematico: in diverse crisi la maggioranza degli attivi non ha battuto l’indice.'],
    ['Un alfa positivo indica che il gestore ha fatto meglio del benchmark tenendo conto del rischio.', true, 'L’alfa misura l’extra-rendimento corretto per il rischio: è ciò che dovrebbe giustificare costi più alti.'],
    ['A parità di indice replicato, due fondi passivi possono avere costi molto diversi.', true, 'Esistono anche fondi indicizzati costosi: pure nella gestione passiva conviene confrontare i costi.'],
  ],
  mcq: [
    { q: 'Qual è l’obiettivo di un gestore passivo?', a: 'Replicare il rendimento di un indice', w: ['Battere l’indice ogni anno', 'Evitare tutti i ribassi', 'Scegliere i titoli sottovalutati'], e: 'Il gestore passivo non cerca di battere il mercato: vuole replicarlo con lo scarto e i costi più bassi possibili.' },
    { q: 'Il mercato rende il 7%. Un fondo passivo costa lo 0,2%, uno attivo l’1,5%. Di quanto deve battere il mercato, prima dei costi, l’attivo solo per pareggiare il passivo?', a: '1,3 punti percentuali', w: ['0,2 punti percentuali', '1,5 punti percentuali', '1,7 punti percentuali'], e: 'La differenza di costo è 1,5 − 0,2 = 1,3 punti: è il vantaggio che l’attivo deve conquistare ogni anno solo per arrivare pari.' },
    { q: 'Che cos’è il closet indexing?', a: 'Un fondo “attivo” che di fatto copia l’indice', w: ['Un ETF che cambia indice di nascosto', 'Un indice composto da pochissimi titoli', 'Un fondo passivo con costi molto bassi'], e: 'Il closet indexer fa pagare costi da gestione attiva ma tiene un portafoglio quasi uguale al benchmark: il suo alfa netto tende a essere negativo.' },
    { q: 'Perché le classifiche costruite solo sui fondi ancora esistenti sono troppo ottimistiche?', a: 'Escludono i fondi chiusi per cattivi risultati', w: ['Contano due volte i fondi migliori', 'Usano un benchmark diverso per ogni fondo', 'Considerano solo i fondi passivi'], e: 'È il survivorship bias: i fondi peggiori spariscono e la media dei rimasti sembra migliore di quella vissuta dagli investitori.' },
    { q: 'Cosa indica un’active share del 90%?', a: 'Il portafoglio è molto diverso dall’indice', w: ['Il fondo ha battuto l’indice del 90%', 'Il 90% dei titoli coincide con l’indice', 'I costi sono il 90% di quelli medi'], e: 'L’active share misura quanto il portafoglio si discosta dal benchmark: 90% significa scelte molto lontane dall’indice, nel bene o nel male.' },
    { q: 'Quale portafoglio applica correttamente l’approccio core-satellite?', a: 'Nucleo indicizzato e una piccola quota attiva', w: ['Tre fondi attivi molto concentrati e nessun ETF', 'Metà ETF globali e metà sul conto corrente', 'Un fondo attivo diverso da cambiare ogni anno'], e: 'Il core a basso costo assicura l’esposizione ai mercati; il satellite, più piccolo, ospita scelte attive senza stravolgere il rischio.' },
    { q: 'Quale convinzione sulla gestione attiva è un errore comune?', a: 'Pagare di più garantisce un gestore migliore', w: ['I costi più alti riducono il rendimento netto', 'Alcuni gestori attivi battono l’indice', 'I risultati passati non si ripetono per forza'], e: 'I costi sono certi, l’extra-rendimento no: una commissione alta è un ostacolo da superare, non una garanzia di qualità.' },
    { q: 'Qual è il principale vantaggio strutturale della gestione passiva?', a: 'Costi bassi e prevedibili', w: ['Rendimento garantito', 'Protezione dai ribassi', 'Assenza di rischio di mercato'], e: 'Il passivo non promette di battere il mercato né di proteggerti: offre il rendimento dell’indice a costi contenuti, che si compongono a tuo favore.' },
  ],
  fill: [
    { s: 'Il gestore ___ cerca di battere il benchmark scegliendo titoli e momenti di ingresso.', a: 'attivo', w: ['passivo', 'indicizzato', 'depositario'] },
    { s: 'Il rendimento extra rispetto al benchmark, corretto per il rischio, si chiama ___.', a: 'alfa', w: ['beta', 'TER', 'spread'] },
    { s: 'Le statistiche che ignorano i fondi chiusi soffrono del ___ bias.', a: 'survivorship', w: ['confirmation', 'home', 'recency'] },
    { s: 'Un indicatore chiamato ___ misura quanto il portafoglio di un fondo si discosta dall’indice.', a: 'active share', w: ['alfa', 'TER', 'NAV'] },
    { s: 'Entrare e uscire dal mercato cercando di anticiparne le mosse si chiama market ___.', a: 'timing', w: ['making', 'cap', 'share'] },
  ],
  order: [
    { q: 'Ordina i passaggi del ragionamento sull’aritmetica della gestione attiva', i: ['Il mercato è la somma di investitori attivi e passivi', 'I passivi ottengono il rendimento del mercato', 'Quindi anche gli attivi, in media, lo ottengono prima dei costi', 'Dopo i costi, l’attivo medio fa peggio del passivo medio'], e: 'Il ragionamento non dice che nessuno può battere il mercato, ma che in media non può succedere al netto dei costi.' },
    { q: 'Ordina dall’active share più bassa alla più alta', i: ['ETF che replica l’indice', 'Fondo indicizzato con piccole deviazioni', 'Fondo attivo vicino al benchmark', 'Fondo attivo con 25 titoli concentrati'], e: 'Più le scelte si allontanano dall’indice, più cresce l’active share: un portafoglio concentrato è il più lontano.' },
  ],
  cat: [
    { q: 'Tipico della gestione attiva o passiva?', g: [['Attiva', ['Selezione dei singoli titoli', 'Costi di gestione più alti', 'Obiettivo di battere l’indice']], ['Passiva', ['Replica di un indice', 'Costi contenuti', 'Rendimento vicino a quello del mercato']]] },
    { q: 'Segnale d’allarme o buona pratica nella scelta di un fondo attivo?', g: [['Allarme', ['Portafoglio quasi uguale all’indice ma costi alti', 'Pubblicità basata su un solo anno eccezionale', 'Benchmark molto facile da battere']], ['Buona pratica', ['Confronto con il benchmark su 10 anni', 'Verifica dei costi totali', 'Strategia chiara e coerente nel tempo']]] },
  ],
  scen: [
    { s: 'Valentina, 37 anni, riceve la proposta di un fondo attivo che negli ultimi 2 anni ha battuto l’indice del 4% l’anno. Costa il 2% annuo. Il consulente insiste: “Il gestore è bravissimo”.', q: 'Cosa fa?', o: [
      { t: 'Chiede i risultati netti su 10 anni e li confronta con un indicizzato', ok: true, f: 'Due anni sono pochi per distinguere bravura e fortuna: servono periodi lunghi, al netto dei costi, e un confronto con l’alternativa passiva.' },
      { t: 'Sottoscrive subito: 2 anni sopra l’indice provano la bravura', ok: false, f: 'Le serie brevi sono spesso fortuna: la persistenza dei risultati è bassa, mentre il 2% di costi è certo ogni anno.' },
      { t: 'Rifiuta per principio qualsiasi fondo attivo', ok: false, f: 'Escludere a priori non è un’analisi: un fondo attivo può avere senso, se costi e risultati di lungo periodo reggono il confronto.' },
    ] },
    { s: 'Alberto, 60 anni, ha un fondo “attivo” con costi dell’1,8% annuo e active share del 25%. Negli ultimi anni ha reso quasi sempre circa 1,6 punti meno del suo indice.', q: 'Cosa fa?', o: [
      { t: 'Valuta un indicizzato, tenendo conto di costi d’uscita e tasse', ok: true, f: 'Ha i segni del closet indexing: paga l’1,8% per un risultato che con un indicizzato otterrebbe a una frazione del costo.' },
      { t: 'Resta: il fondo segue bene l’indice, quindi funziona', ok: false, f: 'Segue l’indice ma costa come un attivo: lo scarto di 1,6 punti l’anno è quasi tutto costo.' },
      { t: 'Aggiunge un secondo fondo attivo simile per diversificare', ok: false, f: 'Raddoppia il problema: un altro fondo vicino all’indice con costi alti non diversifica e non migliora il rendimento.' },
    ] },
    { s: 'Nicola, 25 anni, investe in ETF azionari globali con un orizzonte di 30 anni. Legge previsioni di un crollo imminente e pensa di vendere tutto per ricomprare “più in basso”.', q: 'Cosa fa?', o: [
      { t: 'Mantiene il piano: prevedere i crolli è quasi impossibile', ok: true, f: 'Il market timing richiede di azzeccare due momenti; perdere pochi giorni di forte rialzo può costare caro, oltre a tasse e commissioni.' },
      { t: 'Vende tutto ora e ricompra dopo il crollo annunciato', ok: false, f: 'Le previsioni di crollo sono frequenti e spesso sbagliate: rischia di restare fuori mentre il mercato sale.' },
      { t: 'Vende metà ora e l’altra metà al primo calo del 5%', ok: false, f: 'È sempre market timing, solo a rate: resta una scommessa sui tempi, con costi e tasse in più.' },
    ] },
    { s: 'Laura, 48 anni, ha 100.000 € in ETF globali. È convinta che un gestore specializzato in piccole aziende europee sia molto bravo e vuole dargli spazio senza stravolgere il suo piano.', q: 'Quale soluzione sceglie?', o: [
      { t: 'Affida al fondo attivo una quota satellite, per esempio il 10-15%', ok: true, f: 'Il core indicizzato resta il motore del portafoglio; il satellite sfrutta la sua convinzione limitando il danno se si rivelasse sbagliata.' },
      { t: 'Sposta tutto sul fondo attivo: se è bravo, meglio puntarci', ok: false, f: 'Concentrare tutto su un gestore e su un segmento di mercato aumenta molto il rischio: la bravura passata non è garantita.' },
      { t: 'Rinuncia: se non è certo che batta il mercato, è inutile', ok: false, f: 'Nessuna scelta è certa: una quota limitata è un compromesso ragionevole tra convinzione e prudenza.' },
    ] },
  ],
  tip: 'Prima di pagare una gestione attiva chiediti di quanto deve battere l’indice ogni anno solo per coprire la differenza di costo, poi verifica se ci è riuscita su 10 anni.',
});
