FQC(45, {
  intro: 'Non mettere tutte le uova nello stesso paniere: scopri quale rischio puoi eliminare diversificando, quale no, e come diversificare davvero.',
  cards: [
    { t: 'Due tipi di rischio', x: 'Il rischio specifico nasce da eventi della singola società: un prodotto che fallisce, uno scandalo. Il rischio sistematico colpisce tutto il mercato: recessioni, tassi, crisi. Diversificare tra azioni riduce il primo, non il secondo.', v: { k: 'vs', a: ['Rischio specifico', 'Si riduce diversificando'], b: ['Rischio sistematico', 'Resta comunque'] } },
    { t: 'Più titoli, meno rischio, fino a un certo punto', x: 'Esempio teorico con azioni di volatilità 35% e correlazione 0,3: la volatilità del portafoglio scende in fretta con i primi titoli, poi si stabilizza intorno al 19%. Quel pavimento è il rischio sistematico.', v: { k: 'bars', d: [['1 titolo', 35], ['5 titoli', 23.2], ['20 titoli', 20.3], ['100 titoli', 19.4]], u: '%' } },
    { t: 'Il peso di un incidente', x: 'Con una sola azione, il fallimento dell’azienda azzera il capitale. Con 50 titoli a pesi uguali, la stessa notizia costa il 2% del portafoglio: la diversificazione limita il danno dei singoli eventi.', v: { k: 'stat', n: '2%', l: 'perdita del portafoglio se fallisce 1 titolo su 50 a pesi uguali' } },
    { t: 'Le dimensioni della diversificazione', x: 'Diversificare non è solo avere tanti titoli: conta distribuirli tra settori, paesi, classi di attività e valute. Trenta banche dello stesso paese restano un portafoglio concentrato.', v: { k: 'icons', d: [['🏭', 'Settori'], ['🌍', 'Aree geografiche'], ['🧩', 'Classi di attività'], ['💱', 'Valute']] } },
    { t: 'Il rischio che il mercato non paga', x: 'Secondo la teoria finanziaria classica il mercato premia, in media, solo il rischio sistematico. Il rischio specifico si elimina quasi gratis diversificando: per questo nessuno ti paga un premio per tenerlo.', v: { k: 'formula', f: 'Rischio totale = rischio sistematico + rischio specifico', n: 'Solo il primo è remunerato, in media, dal mercato' } },
    { t: 'Tanti prodotti, poca diversificazione', x: 'Avere molti strumenti non basta: tre fondi azionari globali contengono in gran parte le stesse aziende. Conta quanto sono diversi i rischi sottostanti, non il numero di prodotti.', v: { k: 'scale', a: 'Concentrato', b: 'Diversificato', d: [['Una sola azione', 3], ['Dieci banche italiane', 20], ['Tre fondi azionari globali simili', 60], ['Azioni e obbligazioni globali', 90]] } },
  ],
  terms: [
    ['Diversificazione', 'Distribuzione del capitale su investimenti diversi per ridurre il rischio complessivo del portafoglio.'],
    ['Rischio specifico', 'Rischio legato alla singola azienda o emittente, riducibile combinando molti titoli diversi.'],
    ['Rischio sistematico', 'Rischio che colpisce l’intero mercato e che non si elimina aggiungendo titoli dello stesso mercato.'],
    ['Beta', 'Misura di quanto un titolo tende a muoversi rispetto al mercato: indica l’esposizione al rischio sistematico.'],
    ['Home bias', 'Tendenza a investire troppo nel proprio paese rispetto al suo peso nei mercati mondiali.'],
    ['Concentrazione', 'Situazione in cui gran parte del patrimonio dipende da pochi titoli, settori o paesi.'],
    ['Asset class', 'Categoria omogenea di investimenti, come azioni, obbligazioni, liquidità o materie prime.'],
    ['Sovrapposizione', 'Presenza degli stessi titoli in più fondi dello stesso portafoglio, che riduce la diversificazione reale.'],
  ],
  tf: [
    ['Diversificando su molte azioni puoi ridurre quasi del tutto il rischio specifico.', true, 'Gli eventi delle singole aziende tendono a compensarsi: con decine di titoli di settori diversi il loro impatto diventa piccolo.'],
    ['Con abbastanza titoli in portafoglio si elimina anche il rischio di un crollo generale della borsa.', false, 'Il rischio sistematico colpisce tutte le azioni insieme: nel 2008 anche i portafogli azionari più diversificati hanno perso molto.'],
    ['Possedere 20 azioni dello stesso settore è una buona diversificazione.', false, 'Mito: titoli dello stesso settore reagiscono agli stessi fattori. Conta distribuire il rischio tra settori, paesi e asset class.'],
    ['Il beneficio della diversificazione è più forte con i primi titoli aggiunti e poi diminuisce.', true, 'Passare da 1 a 10 titoli riduce molto la volatilità; da 100 a 200 cambia poco, perché resta quasi solo il rischio sistematico.'],
    ['Comprare cinque fondi azionari globali diversi garantisce cinque volte la diversificazione di uno solo.', false, 'Se contengono in gran parte le stesse aziende, la sovrapposizione è alta: il portafoglio è diversificato quanto uno solo, con più costi.'],
    ['Secondo la teoria classica, il mercato non remunera il rischio specifico perché si può eliminare diversificando.', true, 'Nessuno ti paga un premio per un rischio che potresti togliere quasi gratis: in media è remunerato solo il rischio sistematico.'],
    ['La diversificazione serve a ridurre il rischio, non a massimizzare il rendimento.', true, 'Diversificando rinunci al colpo grosso su un singolo titolo, ma eviti che un solo errore comprometta il patrimonio.'],
    ['Chi lavora in un’azienda quotata e ne ha solo le azioni è ben diversificato, perché la conosce bene.', false, 'È una doppia concentrazione: se l’azienda va in crisi rischiano insieme stipendio e risparmi. Conoscerla non ne riduce il rischio.'],
    ['La borsa italiana pesa meno dell’1% del mercato azionario mondiale.', true, 'Per capitalizzazione l’Italia è una piccola parte del totale: un portafoglio solo italiano è molto concentrato (home bias).'],
    ['Un titolo con beta 1,5 tende ad amplificare i movimenti del mercato.', true, 'Un beta superiore a 1 indica che, in media, il titolo sale e scende più del mercato: è più esposto al rischio sistematico.'],
  ],
  mcq: [
    { q: 'Quale evento è un esempio di rischio specifico?', a: 'Il ritiro di un farmaco di un’azienda', w: ['Un aumento dei tassi deciso dalla BCE', 'Una recessione che colpisce tutta Europa', 'Una crisi finanziaria a livello globale'], e: 'Riguarda una sola società; tassi, recessioni e crisi globali colpiscono l’intero mercato e sono rischi sistematici.' },
    { q: 'Hai 50 titoli a pesi uguali e uno fallisce, azzerandosi. Quanto perde il portafoglio, a parità del resto?', a: '2%', w: ['5%', '50%', '0,5%'], e: 'Ogni titolo pesa 1/50, cioè il 2%: il fallimento costa il 2% del portafoglio invece del 100% che perderesti con una sola azione.' },
    { q: 'Quale portafoglio è più diversificato?', a: 'Azioni globali, obbligazioni e liquidità', w: ['Trenta azioni di banche italiane diverse', 'Tre fondi azionari globali molto simili', 'Una sola azienda, ma molto solida e famosa'], e: 'Combina asset class diverse e un’ampia copertura geografica; gli altri restano concentrati su un settore, su un solo tipo di rischio o su un titolo.' },
    { q: 'Perché aggiungere il 200° titolo a un portafoglio azionario riduce poco il rischio?', a: 'Resta quasi solo il rischio sistematico', w: ['Il rischio specifico torna a crescere', 'Il beta del portafoglio scende a zero', 'Il mercato smette di essere volatile'], e: 'Dopo molti titoli il rischio specifico è già quasi annullato: quello che resta dipende dal mercato nel suo complesso.' },
    { q: 'Cosa misura il beta di un titolo?', a: 'La sua sensibilità ai movimenti del mercato', w: ['La sua probabilità di fallimento', 'Il dividendo rispetto al prezzo', 'Il suo peso all’interno di un indice'], e: 'Beta 1: si muove come il mercato; sopra 1 amplifica, sotto 1 attenua. È una misura dell’esposizione al rischio sistematico.' },
    { q: 'Quale affermazione sulla diversificazione è un mito?', a: 'Più prodotti hai, più sei diversificato', w: ['Settori diversi riducono la concentrazione', 'Il rischio di mercato resta anche diversificando', 'Con molti titoli il rischio specifico cala'], e: 'Conta cosa c’è dentro: cinque fondi con gli stessi titoli non diversificano più di uno solo.' },
    { q: 'Giada lavora in un’azienda quotata e tiene il 70% dei risparmi in azioni della stessa società. Qual è il problema principale?', a: 'Reddito e risparmi dipendono dallo stesso rischio', w: ['Le azioni aziendali non pagano mai dividendi', 'Le azioni dei dipendenti non vengono tassate', 'Il titolo dell’azienda non si può vendere in borsa'], e: 'Se l’azienda va in difficoltà, Giada rischia di perdere insieme lavoro e capitale: è una delle forme più pericolose di concentrazione.' },
    { q: 'Che cos’è l’home bias?', a: 'Sovrappesare gli investimenti del proprio paese', w: ['Preferire sempre gli immobili alle azioni', 'Tenere i risparmi in casa invece che in banca', 'Evitare le azioni estere perché vietate'], e: 'Molti investitori tengono quasi tutto nel mercato domestico, anche se è una piccola parte del mondo: è una concentrazione non necessaria.' },
  ],
  fill: [
    { s: 'Il rischio ___ riguarda la singola azienda e si riduce aumentando il numero di titoli.', a: 'specifico', w: ['sistematico', 'di mercato', 'valutario'] },
    { s: 'Il rischio ___ colpisce tutto il mercato e non si elimina diversificando tra azioni.', a: 'sistematico', w: ['specifico', 'idiosincratico', 'operativo'] },
    { s: 'Un titolo con ___ pari a 1 tende a muoversi come il mercato.', a: 'beta', w: ['alfa', 'TER', 'rating'] },
    { s: 'La presenza degli stessi titoli in più fondi si chiama ___ e riduce la diversificazione reale.', a: 'sovrapposizione', w: ['correlazione', 'replica', 'leva'] },
    { s: 'La tendenza a investire troppo nel proprio paese si chiama ___ bias.', a: 'home', w: ['survivorship', 'confirmation', 'recency'] },
  ],
  order: [
    { q: 'Ordina dal più concentrato al più diversificato', i: ['Una sola azione', 'Dieci azioni dello stesso settore', 'Un ETF azionario globale', 'Un portafoglio di azioni e obbligazioni globali'], e: 'Si passa dal rischio di un’azienda a quello di un settore, poi al mercato azionario mondiale, infine si combinano asset class diverse.' },
    { q: 'Ordina dalla volatilità attesa più alta alla più bassa: portafogli di azioni simili a pesi uguali', i: ['1 titolo', '5 titoli', '20 titoli', '100 titoli'], e: 'Aggiungere titoli riduce il rischio specifico: la discesa è rapida all’inizio e poi rallenta verso il livello del rischio sistematico.' },
  ],
  cat: [
    { q: 'Rischio specifico o sistematico?', g: [['Specifico', ['Scandalo contabile in un’azienda', 'Fallimento di un fornitore chiave', 'Dimissioni improvvise dell’amministratore delegato']], ['Sistematico', ['Recessione globale', 'Rialzo generale dei tassi', 'Crisi finanziaria internazionale']]] },
    { q: 'Diversifica davvero o no?', g: [['Diversifica', ['Aggiungere obbligazioni a un portafoglio azionario', 'Affiancare azioni estere a quelle italiane', 'Distribuire su più settori']], ['Non diversifica', ['Comprare un secondo fondo uguale al primo', 'Aggiungere un’altra banca a dieci banche', 'Comprare altre azioni del proprio datore di lavoro']]] },
  ],
  scen: [
    { s: 'Franco, 58 anni, ha 150.000 € investiti: l’80% in azioni di tre banche italiane che pagano buoni dividendi. Dice di essere diversificato perché ha tre titoli diversi.', q: 'Cosa dovrebbe valutare?', o: [
      { t: 'Ridurre gradualmente la concentrazione su settore e paese', ok: true, f: 'Tre banche dello stesso paese reagiscono agli stessi fattori: tassi, spread, economia italiana. Distribuire su settori e aree riduce un rischio non remunerato.' },
      { t: 'Aggiungere una quarta banca per diversificare meglio', ok: false, f: 'Un’altra banca italiana aggiunge lo stesso tipo di rischio: il portafoglio resta concentrato.' },
      { t: 'Nulla: i dividendi compensano ogni rischio', ok: false, f: 'I dividendi non proteggono dai cali: una crisi del settore può tagliare insieme prezzi e dividendi.' },
    ] },
    { s: 'Silvia, 30 anni, partecipa al piano di azionariato della sua azienda quotata. Le azioni ricevute negli anni valgono ormai il 60% dei suoi risparmi, e il vincolo di detenzione è scaduto.', q: 'Cosa fa?', o: [
      { t: 'Vende una parte nel tempo e diversifica il ricavato', ok: true, f: 'Riduce la dipendenza da un’unica azienda, da cui arriva già lo stipendio, senza rinunciare del tutto al titolo.' },
      { t: 'Tiene tutto: conosce l’azienda meglio di chiunque', ok: false, f: 'Conoscere l’azienda non la protegge dalle crisi: se va male, Silvia rischia insieme lavoro e risparmi.' },
      { t: 'Compra altre azioni dell’azienda finché costano poco', ok: false, f: 'Aumenta una concentrazione già pericolosa: un singolo evento negativo colpirebbe gran parte del suo patrimonio.' },
    ] },
    { s: 'Tommaso, 35 anni, ha quattro ETF: azionario mondiale, azionario USA, tecnologia USA e grandi aziende USA. Pensa di essere molto diversificato perché ha quattro prodotti.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Controllare la sovrapposizione tra i quattro ETF', ok: true, f: 'Le grandi aziende americane compaiono in tutti e quattro gli ETF: il portafoglio è più concentrato di quanto sembri.' },
      { t: 'Aggiungerne altri due per aumentare la diversificazione', ok: false, f: 'Più prodotti simili non riducono il rischio: bisogna guardare cosa contengono, non quanti sono.' },
      { t: 'Vendere tutto e comprare un solo titolo tecnologico', ok: false, f: 'Passerebbe dalla concentrazione su un settore a quella su una singola azienda: il rischio specifico esploderebbe.' },
    ] },
    { s: 'Beatrice, 42 anni, ha un portafoglio azionario globale ben diversificato. In un anno di crisi perde il 18%, come il mercato, e conclude che “la diversificazione non serve” e che tanto vale puntare su pochi titoli.', q: 'Qual è la conclusione corretta?', o: [
      { t: 'Per ridurre i cali servono anche altre asset class', ok: true, f: 'Ha eliminato il rischio specifico, ma non quello sistematico: per attenuare i cali servono componenti diverse dalle azioni.' },
      { t: 'Concentrarsi su tre titoli che sembrano più solidi', ok: false, f: 'Aggiungerebbe rischio specifico a quello di mercato: nella prossima crisi potrebbe perdere molto più del 18%.' },
      { t: 'Vendere tutto e restare in liquidità per sempre', ok: false, f: 'Eviterebbe le oscillazioni ma perderebbe potere d’acquisto e la crescita di lungo periodo dei mercati.' },
    ] },
  ],
  tip: 'Guarda il tuo patrimonio nel complesso, lavoro e casa inclusi: se tutto dipende dallo stesso paese, settore o azienda, non sei diversificato.',
});
