FQC(46, {
  intro: 'Diversificare funziona davvero solo se gli asset non si muovono all’unisono: scopri cos’è la correlazione, come si legge e perché cambia nel tempo.',
  cards: [
    { t: 'Cos’è la correlazione', x: 'Il coefficiente di correlazione misura quanto due asset si muovono insieme, da −1 a +1. A +1 salgono e scendono sempre insieme, a −1 sempre in direzioni opposte; vicino a 0 non c’è un legame lineare.', v: { k: 'scale', a: 'Correlazione −1', b: 'Correlazione +1', d: [['Opposti', 0], ['Indipendenti', 50], ['Identici', 100]] } },
    { t: 'Perché conta', x: 'Due asset con volatilità del 20%, in parti uguali: con correlazione +1 il portafoglio oscilla del 20%, con 0 di circa il 14%, con −1 il rischio si annulla. Più bassa è la correlazione, maggiore il beneficio.', v: { k: 'bars', d: [['ρ = +1', 20], ['ρ = +0,5', 17.3], ['ρ = 0', 14.1], ['ρ = −0,5', 10], ['ρ = −1', 0]], u: '%' } },
    { t: 'La formula del portafoglio', x: 'Il rischio di un portafoglio non è la media dei rischi: dipende anche dalla correlazione ρ. Se ρ è minore di 1, la volatilità complessiva è inferiore alla media ponderata delle volatilità.', v: { k: 'formula', f: 'σ²p = w₁²σ₁² + w₂²σ₂² + 2·w₁·w₂·ρ·σ₁·σ₂', n: 'Il termine con ρ è quello che la diversificazione riduce' } },
    { t: 'Correlazioni tipiche', x: 'Le azioni dei grandi mercati sviluppati sono di solito molto correlate tra loro. Tra azioni e titoli di Stato di qualità la correlazione è variata nel tempo; l’oro storicamente ha avuto un legame debole con le azioni.', v: { k: 'icons', d: [['🌍', 'Azioni Europa e USA: alta'], ['📜', 'Azioni e titoli di Stato: variabile'], ['🥇', 'Azioni e oro: bassa']] } },
    { t: 'Le correlazioni cambiano', x: 'Le correlazioni non sono costanti: nelle crisi molti asset rischiosi tendono a scendere insieme, proprio quando servirebbe la diversificazione. Nel 2022, con inflazione e tassi in rialzo, azioni e obbligazioni sono calate insieme.', v: { k: 'stat', n: '2022', l: 'anno in cui azioni e obbligazioni sono scese insieme' } },
    { t: 'Cosa la correlazione non dice', x: 'La correlazione indica la direzione comune, non l’ampiezza dei movimenti né un rapporto di causa: con correlazione +1 un asset può salire del 2% mentre l’altro sale del 6%.', v: { k: 'vs', a: ['Dice', 'Se si muovono nella stessa direzione'], b: ['Non dice', 'Di quanto, né perché'] } },
  ],
  terms: [
    ['Correlazione', 'Misura, da −1 a +1, di quanto i rendimenti di due asset tendono a muoversi nella stessa direzione.'],
    ['Correlazione positiva', 'Situazione in cui due asset tendono a salire e scendere insieme.'],
    ['Correlazione negativa', 'Situazione in cui, quando un asset sale, l’altro tende a scendere.'],
    ['Correlazione nulla', 'Assenza di un legame lineare tra i movimenti di due asset.'],
    ['Volatilità', 'Ampiezza delle oscillazioni dei rendimenti, misurata di solito con la deviazione standard.'],
    ['Matrice di correlazione', 'Tabella che mostra il legame tra i rendimenti di ogni coppia di asset di un portafoglio.'],
    ['Asset decorrelato', 'Investimento poco legato al resto del portafoglio, utile a ridurne le oscillazioni complessive.'],
    ['Covarianza', 'Misura di come variano insieme due rendimenti; divisa per le due volatilità dà la correlazione.'],
  ],
  tf: [
    ['Una correlazione di +1 indica che due asset si muovono sempre nella stessa direzione.', true, 'È la correlazione perfetta positiva: in questo caso combinarli non riduce la volatilità rispetto alla media ponderata.'],
    ['Con correlazione inferiore a +1, la volatilità di un portafoglio è minore della media ponderata delle volatilità.', true, 'È il cuore matematico della diversificazione: più bassa è la correlazione, più ampio è il beneficio.'],
    ['Una correlazione vicina a 0 significa che i due asset hanno lo stesso rendimento.', false, 'Correlazione 0 significa che non c’è un legame lineare tra i loro movimenti, non che rendano allo stesso modo.'],
    ['Le correlazioni tra asset restano stabili e si possono calcolare una volta per sempre.', false, 'Cambiano con il contesto: nelle crisi molti asset rischiosi tendono a muoversi insieme, riducendo i benefici attesi.'],
    ['Nel 2022 azioni e titoli di Stato sono scesi insieme, smentendo l’idea che si compensino sempre.', true, 'Con inflazione e rialzo dei tassi entrambe le asset class hanno perso: la correlazione bassa o negativa del passato non è garantita.'],
    ['Due ETF azionari su Europa e Stati Uniti hanno di solito una correlazione alta.', true, 'I grandi mercati sviluppati reagiscono a fattori globali simili: combinarli diversifica per area, ma poco per tipo di rischio.'],
    ['Una correlazione di +0,9 dimostra che un asset causa i movimenti dell’altro.', false, 'Correlazione non è causalità: due asset possono muoversi insieme perché dipendono entrambi da un terzo fattore.'],
    ['Se due asset hanno correlazione +1, si muovono sempre della stessa percentuale.', false, 'La correlazione dice la direzione comune, non l’ampiezza: uno può salire del 2% e l’altro del 6% anche con correlazione +1.'],
    ['Aggiungere un asset volatile ma poco correlato può ridurre la volatilità del portafoglio.', true, 'Se si muove in modo diverso dal resto, anche un asset volatile, in piccola dose, può compensare parte delle oscillazioni complessive.'],
    ['Per diversificare basta scegliere asset con rendimenti attesi diversi.', false, 'Mito: conta come si muovono insieme, non quanto rendono in media. Due asset con rendimenti diversi possono essere molto correlati.'],
  ],
  mcq: [
    { q: 'A parità di volatilità e di pesi, quale correlazione offre il beneficio di diversificazione maggiore?', a: '−0,6', w: ['+0,9', '+0,3', '0'], e: 'Più la correlazione è bassa, verso −1, più i movimenti dei due asset si compensano e più si riduce la volatilità del portafoglio.' },
    { q: 'Due asset con volatilità del 20% sono in parti uguali e hanno correlazione +1. Qual è la volatilità del portafoglio?', a: '20%', w: ['10%', '14%', '0%'], e: 'Con correlazione +1 non c’è beneficio: la volatilità è la media ponderata, cioè 20%. Con correlazione 0 sarebbe circa il 14%.' },
    { q: 'Cosa tende a succedere alle correlazioni tra asset rischiosi durante una crisi?', a: 'Tendono ad aumentare', w: ['Tendono verso −1', 'Diventano tutte 0', 'Restano invariate'], e: 'Nei momenti di panico gli investitori vendono molti asset insieme: le correlazioni salgono e la diversificazione rende meno del previsto.' },
    { q: 'Una correlazione di −1 tra due asset significa che…', a: 'si muovono sempre in direzioni opposte', w: ['non hanno alcun legame tra loro', 'perdono sempre entrambi insieme', 'hanno sempre la stessa volatilità'], e: 'È la correlazione perfetta negativa: quando uno sale l’altro scende. Tra asset finanziari reali è rarissima.' },
    { q: 'Quale convinzione sulla correlazione è sbagliata?', a: 'Azioni e obbligazioni si compensano sempre', w: ['Le correlazioni cambiano nel tempo', 'Correlazione non significa causalità', 'Una correlazione bassa aiuta a diversificare'], e: 'Spesso è successo, ma non sempre: nel 2022, con inflazione e tassi in rialzo, sono scese insieme.' },
    { q: 'Come si ottiene la correlazione dalla covarianza?', a: 'Dividendo per il prodotto delle due volatilità', w: ['Moltiplicandola per la somma delle volatilità', 'Sottraendo i due rendimenti medi', 'Dividendo per il numero di osservazioni'], e: 'ρ = covarianza ÷ (σ₁ × σ₂): così il valore è normalizzato tra −1 e +1 e si può confrontare tra coppie diverse.' },
    { q: 'Hai un portafoglio di azioni globali. Quale aggiunta, a parità di peso e di volatilità, riduce di più il rischio?', a: 'Un asset con correlazione 0 con le azioni', w: ['Un ETF sulle grandi aziende azionarie USA', 'Un ETF sulle azioni delle società europee', 'Un fondo azionario globale a gestione attiva'], e: 'A parità di volatilità vince l’asset meno correlato: gli altri si muovono quasi come le azioni globali che hai già.' },
    { q: 'Quale strumento riassume le correlazioni tra tutte le coppie di asset di un portafoglio?', a: 'La matrice di correlazione', w: ['Il prospetto informativo', 'La curva dei rendimenti', 'Il grafico a candele'], e: 'È una tabella: ogni cella mostra la correlazione tra due asset, e la diagonale vale sempre 1.' },
  ],
  fill: [
    { s: 'Il coefficiente di correlazione può variare da −1 a ___.', a: '+1', w: ['+100', '0', '+10'] },
    { s: 'Con correlazione ___ due asset si muovono sempre in direzioni opposte.', a: '−1', w: ['+1', '0', '+0,5'] },
    { s: 'Più la correlazione tra due asset è ___, maggiore è il beneficio della diversificazione.', a: 'bassa', w: ['alta', 'stabile', 'positiva'] },
    { s: 'Nelle crisi le correlazioni tra asset rischiosi tendono ad ___.', a: 'aumentare', w: ['azzerarsi', 'invertirsi', 'annullarsi'] },
    { s: 'La correlazione si ottiene dividendo la ___ per il prodotto delle due volatilità.', a: 'covarianza', w: ['varianza', 'media', 'mediana'] },
  ],
  order: [
    { q: 'Ordina dal maggiore al minore beneficio di diversificazione (stessa volatilità e stessi pesi)', i: ['Correlazione −0,8', 'Correlazione −0,2', 'Correlazione +0,3', 'Correlazione +0,9'], e: 'A parità di volatilità e pesi, il rischio del portafoglio cresce con la correlazione: più è bassa, più le oscillazioni si compensano.' },
    { q: 'Ordina i passi per capire se un nuovo asset diversifica il tuo portafoglio', i: ['Raccogli i rendimenti storici di entrambi', 'Calcola la covarianza tra i rendimenti', 'Dividi per il prodotto delle volatilità', 'Verifica se la correlazione è stabile anche nelle crisi'], e: 'Dalla covarianza si ricava la correlazione; poi conviene controllare come è cambiata in periodi diversi, soprattutto nei momenti di stress.' },
  ],
  cat: [
    { q: 'Correlazione tipicamente positiva o negativa?', g: [['Positiva', ['Due ETF su indici azionari simili', 'Azioni di due banche dello stesso paese', 'Petrolio e azioni delle compagnie petrolifere']], ['Negativa', ['Un ETF e il suo ETF inverso', 'Prezzo di un’obbligazione e suo rendimento', 'Un titolo e una sua vendita allo scoperto']]] },
    { q: 'Beneficio reale di diversificazione o falso amico?', g: [['Beneficio reale', ['Asset con correlazione bassa e stabile', 'Asset class con fattori di rischio diversi', 'Aree con cicli economici diversi']], ['Falso amico', ['Correlazione bassa misurata solo in anni tranquilli', 'Due fondi con gli stessi titoli', 'Nomi diversi ma stesso indice sottostante']]] },
  ],
  scen: [
    { s: 'Marco, 44 anni, ha un portafoglio di sole azioni europee. Vuole ridurne il rischio e pensa di spostare metà del capitale su azioni americane, convinto di dimezzare così le oscillazioni.', q: 'Cosa fa?', o: [
      { t: 'Valuta asset class diverse, come obbligazioni di qualità', ok: true, f: 'Le azioni dei paesi sviluppati sono molto correlate: per ridurre davvero il rischio servono asset che si muovono diversamente, pur sapendo che non si compensano sempre.' },
      { t: 'Sposta metà su azioni USA: così il rischio si dimezza', ok: false, f: 'Diversifica per area, ma con una correlazione alta il rischio cala poco, altro che dimezzarsi.' },
      { t: 'Non cambia nulla: la correlazione non conta', ok: false, f: 'La correlazione è proprio ciò che decide quanto rischio si elimina combinando gli asset.' },
    ] },
    { s: 'Rita, 52 anni, vede la pubblicità di un fondo “decorrelato dai mercati”: negli ultimi due anni, tranquilli e in rialzo, la sua correlazione con le azioni è stata vicina a 0.', q: 'Cosa fa prima di decidere?', o: [
      { t: 'Verifica come si è comportato nelle fasi di crisi e su periodi lunghi', ok: true, f: 'Una correlazione misurata solo in anni tranquilli può cambiare quando servirebbe: conta il comportamento sotto stress.' },
      { t: 'Investe subito: correlazione 0 significa protezione garantita', ok: false, f: 'Correlazione 0 non è protezione: indica solo assenza di legame lineare nel periodo osservato, che può cambiare.' },
      { t: 'Lo scarta perché rende meno delle azioni', ok: false, f: 'Il valore di un asset decorrelato sta nel ridurre il rischio complessivo, non nel battere le azioni: va giudicato nel portafoglio.' },
    ] },
    { s: 'Enrico, 39 anni, ha un portafoglio 60% azioni e 40% obbligazioni. In un anno di inflazione alta perde su entrambe le componenti e pensa che la diversificazione “sia morta”.', q: 'Qual è la lettura corretta?', o: [
      { t: 'Le correlazioni cambiano nel tempo: resta diversificato', ok: true, f: 'Le correlazioni non sono fisse: in certi contesti azioni e obbligazioni scendono insieme. Sul lungo periodo combinare asset diversi resta utile.' },
      { t: 'Passa tutto in azioni: le obbligazioni non servono più', ok: false, f: 'Un anno anomalo non cancella il ruolo stabilizzatore delle obbligazioni in molti altri contesti: concentrarsi aumenta il rischio.' },
      { t: 'Vende tutto e aspetta che le correlazioni tornino “normali”', ok: false, f: 'Nessuno sa quando succederà: uscire dal mercato trasforma una perdita temporanea in definitiva.' },
    ] },
    { s: 'Paola, 35 anni, ha un portafoglio azionario e vuole ridurne la volatilità. Valuta due asset con volatilità simile: A ha un rendimento atteso del 7% e correlazione 0,95 con le sue azioni; B un rendimento atteso del 5% e correlazione 0,1.', q: 'Quale aggiunge per il suo obiettivo?', o: [
      { t: 'B: la bassa correlazione riduce di più la volatilità', ok: true, f: 'Per ridurre il rischio conta come l’asset si muove rispetto al portafoglio: B compensa le oscillazioni, A le replica quasi identiche.' },
      { t: 'A: rende di più, quindi è migliore', ok: false, f: 'Rende di più ma si muove quasi come le sue azioni: non abbassa la volatilità, che era l’obiettivo di Paola.' },
      { t: 'Nessuno: con volatilità simili l’effetto è uguale', ok: false, f: 'A parità di volatilità è proprio la correlazione a fare la differenza sul rischio del portafoglio.' },
    ] },
  ],
  tip: 'Prima di aggiungere un investimento chiediti non solo quanto può rendere, ma come si comporta quando il resto del portafoglio scende.',
});
