FQC(47, {
  intro: 'Come dividi i soldi tra azioni, obbligazioni e liquidità conta più del singolo titolo che scegli: impara l’asset allocation strategica e tattica.',
  cards: [
    { t: 'Cos’è l’asset allocation', x: 'È la ripartizione del patrimonio tra classi di attività: azioni, obbligazioni, liquidità e talvolta immobili o materie prime. Molti studi la indicano come il fattore che spiega di più le oscillazioni di un portafoglio diversificato.', v: { k: 'pie', d: [['Azioni', 60], ['Obbligazioni', 30], ['Liquidità', 10]] } },
    { t: 'Strategica e tattica', x: 'L’allocazione strategica fissa i pesi di lungo periodo in base a obiettivi, orizzonte e profilo di rischio. Quella tattica si discosta per un periodo limitato di pochi punti percentuali, entro margini decisi in anticipo.', v: { k: 'vs', a: ['Strategica', 'Pesi di lungo periodo'], b: ['Tattica', 'Scostamenti temporanei e limitati'] } },
    { t: 'Il rendimento atteso del mix', x: 'Il rendimento atteso del portafoglio è la media ponderata di quelli delle singole classi. Il rischio invece non è una semplice media: dipende anche da quanto le classi si muovono insieme.', v: { k: 'formula', f: 'Rendimento atteso = Σ (peso × rendimento atteso di ogni classe)', n: 'Es.: 60% × 6% + 40% × 2% = 4,4%' } },
    { t: 'Più azioni, più oscillazioni', x: 'Aumentando la quota azionaria crescono il rendimento atteso di lungo periodo e l’ampiezza dei cali possibili. Non esiste il mix migliore in assoluto: esiste quello adatto ai tuoi obiettivi.', v: { k: 'scale', a: 'Rischio più basso', b: 'Rischio più alto', d: [['20% azioni', 25], ['40% azioni', 45], ['60% azioni', 65], ['80% azioni', 85]] } },
    { t: 'Dagli obiettivi agli strumenti', x: 'L’ordine conta: prima chiarisci per cosa investi e quando ti servono i soldi, poi quanto rischio puoi reggere. Solo alla fine scegli i prodotti con cui riempire ogni casella.', v: { k: 'steps', s: ['Obiettivo', 'Orizzonte', 'Profilo di rischio', 'Pesi strategici', 'Strumenti'] } },
    { t: 'Una regola empirica', x: 'Una regola semplice suggerisce una quota azionaria pari a 100 meno l’età: a 40 anni il 60%. È solo un punto di partenza: obiettivi, patrimonio e tolleranza alle perdite contano più dell’età.', v: { k: 'stat', n: '100 − età', l: 'quota azionaria indicativa secondo una regola empirica' } },
  ],
  terms: [
    ['Asset allocation', 'Ripartizione del patrimonio tra diverse classi di attività, come azioni, obbligazioni e liquidità.'],
    ['Allocazione strategica', 'Composizione di lungo periodo del portafoglio, definita in base a obiettivi, orizzonte e rischio.'],
    ['Allocazione tattica', 'Scostamento temporaneo e limitato dai pesi di lungo periodo per sfruttare una situazione di mercato.'],
    ['Portafoglio 60/40', 'Mix classico con circa sei decimi in azioni e quattro decimi in obbligazioni.'],
    ['Liquidità', 'Parte del patrimonio disponibile subito e a rischio minimo, come conti e strumenti a brevissimo termine.'],
    ['Life cycle', 'Strategia che riduce gradualmente la quota azionaria man mano che si avvicina l’obiettivo.'],
    ['Rendimento atteso', 'Rendimento medio che si stima di ottenere da un investimento, senza alcuna garanzia.'],
    ['Sovrappeso', 'Peso di una classe di attività superiore a quello previsto dall’allocazione strategica.'],
  ],
  tf: [
    ['L’allocazione strategica si definisce in base a obiettivi, orizzonte e profilo di rischio.', true, 'È la mappa di lungo periodo: cambia quando cambiano la tua vita o i tuoi obiettivi, non ogni volta che si muovono i mercati.'],
    ['L’allocazione tattica consiste nel cambiare completamente i pesi ogni mese in base alle notizie.', false, 'La tattica prevede scostamenti temporanei e contenuti dai pesi strategici, entro limiti prefissati: stravolgere tutto è speculazione.'],
    ['Il rendimento atteso di un portafoglio 50% al 6% e 50% al 2% è il 4%.', true, '0,5 × 6% + 0,5 × 2% = 4%. Il rendimento atteso è una media ponderata; il rischio invece dipende anche dalle correlazioni.'],
    ['Esiste un’asset allocation ottimale valida per tutti gli investitori.', false, 'Mito: il mix giusto dipende da obiettivi, orizzonte, capacità e tolleranza al rischio. Ciò che va bene a 25 anni può essere inadatto a 70.'],
    ['La ripartizione tra azioni, obbligazioni e liquidità pesa sul rischio del portafoglio più della scelta tra due fondi azionari simili.', true, 'Molti studi indicano che la ripartizione tra classi di attività spiega gran parte delle oscillazioni di un portafoglio diversificato.'],
    ['Secondo la regola “100 meno l’età”, una persona di 30 anni terrebbe circa il 70% in azioni.', true, '100 − 30 = 70. È una regola empirica semplice, da adattare a obiettivi, patrimonio e tolleranza al rischio.'],
    ['La liquidità non ha alcun ruolo in un’asset allocation di lungo periodo.', false, 'Serve per le spese impreviste e per gli obiettivi vicini: evita di dover vendere titoli nel momento sbagliato.'],
    ['Una strategia life cycle aumenta la quota azionaria man mano che si avvicina l’obiettivo.', false, 'Fa il contrario: riduce gradualmente le azioni avvicinandosi alla data in cui servono i soldi, per limitare il rischio di un calo finale.'],
    ['Due persone con lo stesso patrimonio possono avere asset allocation molto diverse, entrambe corrette.', true, 'Orizzonte, obiettivi e capacità di sopportare perdite cambiano da persona a persona: il patrimonio da solo non basta a decidere.'],
    ['Aumentare la quota azionaria aumenta il rendimento garantito del portafoglio.', false, 'Aumenta il rendimento atteso nel lungo periodo, non quello garantito: in cambio crescono oscillazioni e possibili perdite.'],
  ],
  mcq: [
    { q: 'Un portafoglio è al 70% in azioni (rendimento atteso 6%) e al 30% in obbligazioni (2%). Qual è il rendimento atteso?', a: '4,8%', w: ['4,0%', '8,0%', '3,2%'], e: '0,7 × 6% + 0,3 × 2% = 4,2% + 0,6% = 4,8%. Non è la media semplice (4%) né la somma dei rendimenti.' },
    { q: 'Qual è la differenza tra allocazione strategica e tattica?', a: 'La strategica è di lungo periodo, la tattica temporanea', w: ['La strategica riguarda le azioni, la tattica le obbligazioni', 'La strategica usa ETF, la tattica usa fondi', 'La strategica è attiva, la tattica è passiva'], e: 'La strategica fissa i pesi di fondo; la tattica li modifica di poco e per un periodo limitato, poi si torna ai pesi strategici.' },
    { q: 'Da dove si parte per costruire un’asset allocation?', a: 'Da obiettivi e orizzonte temporale', w: ['Dal fondo che ha reso di più', 'Dalle previsioni sui tassi', 'Dal titolo più consigliato online'], e: 'Prima si chiarisce a cosa servono i soldi e quando; poi si stabilisce il rischio sostenibile e infine si scelgono gli strumenti.' },
    { q: 'Il tuo piano prevede il 60% in azioni. Per qualche mese decidi di portarle al 65%. Cosa stai facendo?', a: 'Un sovrappeso tattico di 5 punti', w: ['Una nuova allocazione strategica', 'Un ribilanciamento al target', 'Una riduzione del rischio'], e: 'Ti scosti temporaneamente dal peso strategico: è un sovrappeso tattico, da chiudere tornando al 60%.' },
    { q: 'Quale affermazione sull’asset allocation è un errore comune?', a: '“Conta solo scegliere i titoli migliori”', w: ['“Più azioni, più oscillazioni”', '“La liquidità serve per gli imprevisti”', '“Il mix dipende dall’orizzonte”'], e: 'La ripartizione tra classi di attività pesa molto sul rischio complessivo: pensare solo ai singoli titoli fa perdere di vista l’insieme.' },
    { q: 'Cosa fa una strategia life cycle avvicinandosi all’obiettivo?', a: 'Riduce gradualmente la quota azionaria', w: ['Aumenta gradualmente la quota azionaria', 'Mantiene sempre gli stessi pesi', 'Passa tutto in azioni nell’ultimo anno'], e: 'Riduce l’esposizione al rischio quando resta poco tempo per recuperare un eventuale calo.' },
    { q: 'Perché il rischio di un portafoglio non è la media ponderata dei rischi delle sue componenti?', a: 'Perché dipende anche dalle correlazioni', w: ['Perché dipende dai costi di gestione', 'Perché le tasse modificano la volatilità', 'Perché le obbligazioni non hanno rischio'], e: 'Se le classi di attività non si muovono insieme, le oscillazioni si compensano in parte: il rischio complessivo è di solito inferiore alla media.' },
    { q: 'Secondo la regola empirica “100 meno l’età”, quale quota azionaria avrebbe una persona di 55 anni?', a: '45%', w: ['55%', '35%', '100%'], e: '100 − 55 = 45%. È solo un punto di partenza: obiettivi e capacità di rischio possono giustificare scelte diverse.' },
  ],
  fill: [
    { s: 'L’asset allocation ___ fissa i pesi di lungo periodo del portafoglio.', a: 'strategica', w: ['tattica', 'tecnica', 'speculativa'] },
    { s: 'L’allocazione ___ si discosta per un periodo limitato dai pesi di lungo periodo.', a: 'tattica', w: ['strategica', 'neutrale', 'passiva'] },
    { s: 'Il rendimento atteso di un portafoglio è la media ___ dei rendimenti attesi delle sue componenti.', a: 'ponderata', w: ['semplice', 'geometrica', 'mobile'] },
    { s: 'Un portafoglio con circa il 60% in azioni e il 40% in obbligazioni è detto ___.', a: '60/40', w: ['40/60', 'core-satellite', 'life cycle'] },
    { s: 'Una strategia ___ riduce le azioni man mano che si avvicina la data dell’obiettivo.', a: 'life cycle', w: ['buy and hold', 'momentum', 'growth'] },
  ],
  order: [
    { q: 'Ordina i passi per definire un’asset allocation', i: ['Chiarisci l’obiettivo', 'Stabilisci l’orizzonte temporale', 'Valuta il profilo di rischio', 'Fissa i pesi strategici', 'Scegli gli strumenti'], e: 'Si va dal perché al come: gli strumenti si scelgono per ultimi, per riempire una struttura già decisa.' },
    { q: 'Ordina dal portafoglio meno rischioso al più rischioso', i: ['100% liquidità', '20% azioni e 80% obbligazioni', '60% azioni e 40% obbligazioni', '100% azioni'], e: 'Aumentando la quota azionaria crescono il rendimento atteso e l’ampiezza dei cali possibili.' },
  ],
  cat: [
    { q: 'Decisione strategica o tattica?', g: [['Strategica', ['Fissare il 60% in azioni per i prossimi 20 anni', 'Ridurre le azioni avvicinandosi alla pensione', 'Includere le obbligazioni nel piano di lungo periodo']], ['Tattica', ['Portare le azioni al 65% per qualche mese', 'Sottopesare le obbligazioni lunghe per un trimestre', 'Aumentare per poco tempo la liquidità, entro i limiti']]] },
    { q: 'Motore di crescita o stabilizzatore del portafoglio?', g: [['Motore di crescita', ['Azioni globali', 'Azioni dei paesi emergenti', 'Azioni di piccole aziende']], ['Stabilizzatore', ['Titoli di Stato a breve scadenza', 'Liquidità', 'Obbligazioni di alta qualità']]] },
  ],
  scen: [
    { s: 'Lorenzo, 28 anni, ha un lavoro stabile, un fondo di emergenza e vuole investire per la pensione, tra oltre 30 anni. Per paura di perdere tiene tutto sul conto corrente.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Definire un mix diversificato con una quota azionaria', ok: true, f: 'Con un orizzonte così lungo e una base solida può assumere un rischio misurato: la quota azionaria si sceglie in base a quanto riesce a reggere i cali.' },
      { t: 'Lasciare tutto sul conto: è l’unica scelta senza rischi', ok: false, f: 'Su 30 anni l’inflazione erode il potere d’acquisto: anche “non rischiare” ha un costo, solo meno visibile.' },
      { t: 'Investire tutto in azioni di un solo settore promettente', ok: false, f: 'Passa dall’estremo prudente a quello concentrato: un’asset allocation diversificata è la via di mezzo sensata.' },
    ] },
    { s: 'Simona, 60 anni, andrà in pensione tra 2 anni e userà i risparmi per integrare il reddito. Oggi ha il 90% in azioni, scelto quando ne aveva 40.', q: 'Cosa fa?', o: [
      { t: 'Riduce gradualmente la quota azionaria', ok: true, f: 'Un calo del 30-40% poco prima della pensione lascerebbe poco tempo per recuperare: l’allocazione va adattata alla nuova fase.' },
      { t: 'Lascia il 90%: le azioni sul lungo periodo salgono', ok: false, f: 'Il suo “lungo periodo” si è accorciato: i soldi le serviranno a breve e un calo potrebbe costringerla a vendere in perdita.' },
      { t: 'Vende tutto domani e passa al 100% liquidità', ok: false, f: 'La pensione può durare decenni: azzerare le azioni d’un colpo espone all’inflazione. Meglio una riduzione graduale e misurata.' },
    ] },
    { s: 'Giulio, 45 anni, ha un’allocazione strategica 60/40. Legge che le azioni sono “troppo care” e pensa di vendere tutte le azioni finché non torneranno convenienti.', q: 'Cosa fa?', o: [
      { t: 'Mantiene il 60/40, al massimo con un piccolo scostamento', ok: true, f: 'Una convinzione di mercato può giustificare pochi punti di scostamento temporaneo, non lo smontaggio del piano di lungo periodo.' },
      { t: 'Vende tutte le azioni finché non saranno “economiche”', ok: false, f: 'Nessuno sa quando succederà: azzerare le azioni è market timing estremo e il mercato può salire ancora a lungo.' },
      { t: 'Passa al 100% azioni per compensare in anticipo', ok: false, f: 'Va nella direzione opposta alla sua stessa preoccupazione e stravolge il rischio deciso nel piano.' },
    ] },
    { s: 'Martina, 35 anni, ha due obiettivi: 40.000 € per l’anticipo della casa tra 3 anni e un capitale per la pensione tra 30 anni.', q: 'Come imposta gli investimenti?', o: [
      { t: 'Casa a basso rischio, pensione con più azioni', ok: true, f: 'Ogni obiettivo ha il suo orizzonte: i soldi per la casa non possono permettersi un calo, quelli per la pensione hanno tempo per recuperare.' },
      { t: 'Un unico portafoglio all’80% azionario per entrambi', ok: false, f: 'Se le azioni calano proprio tra 3 anni, l’anticipo per la casa sarebbe a rischio.' },
      { t: 'Tutto in liquidità per entrambi gli obiettivi', ok: false, f: 'Va bene per la casa, ma per un obiettivo a 30 anni rinuncia alla crescita e subisce l’inflazione.' },
    ] },
  ],
  tip: 'Scrivi la tua asset allocation strategica, con i pesi e il motivo di ogni scelta: ti servirà da bussola quando i mercati ti spingeranno a cambiare idea.',
});
