FQC(48, {
  intro: 'I mercati spostano i pesi del portafoglio senza chiederti il permesso: impara quando e come riportarli al target, con quali costi e benefici.',
  cards: [
    { t: 'La deriva del portafoglio', x: 'Parti con 10.000 €: 60% azioni e 40% obbligazioni. Se le azioni salgono del 30% e le obbligazioni restano ferme, il mix diventa circa 66/34: senza accorgertene, il portafoglio è diventato più rischioso.', v: { k: 'pie', d: [['Azioni', 66], ['Obbligazioni', 34]] } },
    { t: 'Il calcolo', x: 'Moltiplichi il nuovo totale per il peso obiettivo e lo confronti con il valore attuale. Nell’esempio il totale è 11.800 €: vendi 720 € di azioni e compri 720 € di obbligazioni per tornare a 60/40.', v: { k: 'formula', f: 'Da spostare = valore attuale − peso target × totale', n: 'Es.: 7.800 − 60% × 11.800 = 720 €' } },
    { t: 'Quando ribilanciare', x: 'Puoi ribilanciare a date fisse oppure quando un peso si allontana troppo dal target. Molti combinano i due metodi: controllo annuale e intervento solo se la deviazione supera la soglia.', v: { k: 'vs', a: ['A calendario', 'Data fissa, es. ogni anno'], b: ['A soglia', 'Fuori dalla banda, es. ±5 punti'] } },
    { t: 'Ribilanciare senza vendere', x: 'Se fai versamenti periodici, puoi destinare i nuovi soldi all’asset sottopesato finché i pesi tornano vicini al target. Così eviti commissioni di vendita e tasse sulle plusvalenze.', v: { k: 'steps', s: ['Controlla i pesi', 'Trova l’asset sottopesato', 'Indirizza lì i nuovi versamenti', 'Pesi di nuovo vicini al target'] } },
    { t: 'Il vero obiettivo', x: 'Il ribilanciamento serve soprattutto a mantenere il livello di rischio che hai scelto, non a massimizzare il rendimento. Lasciato a sé stesso, un portafoglio misto tende ad appesantirsi di azioni.', v: { k: 'scale', a: 'Rischio più basso', b: 'Rischio più alto', d: [['60/40 ribilanciato', 55], ['60/40 lasciato derivare per anni', 75]] } },
    { t: 'I costi da considerare', x: 'Ribilanciare troppo spesso fa pagare commissioni e, se vendi in guadagno, imposte sulle plusvalenze (in generale il 26%). Farlo troppo di rado lascia il rischio fuori controllo: serve una regola equilibrata.', v: { k: 'icons', d: [['🧾', 'Imposte sulle plusvalenze'], ['💶', 'Commissioni'], ['↔️', 'Spread'], ['⏳', 'Disciplina']] } },
  ],
  terms: [
    ['Ribilanciamento', 'Operazione che riporta i pesi delle classi di attività ai valori obiettivo fissati nel piano.'],
    ['Peso target', 'Percentuale obiettivo di una classe di attività prevista dall’allocazione strategica.'],
    ['Deriva', 'Allontanamento spontaneo dei pesi dal target, dovuto ai rendimenti diversi delle classi di attività.'],
    ['Ribilanciamento a calendario', 'Metodo che riporta i pesi all’obiettivo a scadenze fisse, per esempio una volta l’anno.'],
    ['Ribilanciamento a soglia', 'Metodo che interviene solo quando un peso supera una deviazione massima prefissata.'],
    ['Banda di tolleranza', 'Intervallo intorno al peso obiettivo entro cui non si interviene, per esempio ±5 punti.'],
    ['Sottopeso', 'Peso attuale di una classe di attività inferiore a quello previsto dall’allocazione obiettivo.'],
    ['Ribilanciamento con i flussi', 'Uso di nuovi versamenti o prelievi per riavvicinare i pesi all’obiettivo senza vendere.'],
  ],
  tf: [
    ['Senza ribilanciamento, un portafoglio misto tende col tempo a diventare più azionario.', true, 'Le azioni in media crescono più delle obbligazioni: il loro peso aumenta e con esso il rischio complessivo.'],
    ['Ribilanciare significa vendere in parte ciò che è salito di più e comprare ciò che è rimasto indietro.', true, 'Riportando i pesi al target riduci l’asset salito e aumenti quello sceso: una disciplina che va contro l’emotività.'],
    ['Lo scopo principale del ribilanciamento è massimizzare il rendimento.', false, 'Lo scopo principale è mantenere il livello di rischio scelto; l’effetto sul rendimento può essere positivo o negativo.'],
    ['Più spesso ribilanci, meglio è: l’ideale è farlo ogni giorno.', false, 'Mito: ribilanciare troppo spesso moltiplica commissioni e tasse senza benefici apprezzabili. Bastano controlli periodici e soglie ragionevoli.'],
    ['Puoi ribilanciare anche senza vendere, indirizzando i nuovi versamenti sull’asset sottopesato.', true, 'È il modo più efficiente per chi versa con regolarità: eviti costi di vendita e tasse sulle plusvalenze.'],
    ['Con target 60% azioni e banda di ±5 punti, si interviene quando le azioni arrivano al 63%.', false, 'La banda va dal 55% al 65%: al 63% sei ancora dentro. Si interviene solo sotto il 55% o sopra il 65%.'],
    ['Vendere in guadagno quote di un ETF per ribilanciare può far pagare imposte sulle plusvalenze.', true, 'Realizzando un guadagno paghi le imposte (in generale il 26%): è un costo da considerare nella scelta di come e quando ribilanciare.'],
    ['Dopo un forte calo delle azioni, ribilanciare significa vendere altre azioni.', false, 'Il contrario: se le azioni sono scese sono sottopesate. Ribilanciare vuol dire comprarne, vendendo parte dell’asset più stabile.'],
    ['Un portafoglio 60/40 diventato 70/30 ha un rischio più alto di quello pianificato.', true, 'Dieci punti in più di azioni significano oscillazioni e cali potenziali più ampi rispetto al piano iniziale.'],
    ['Ribilanciare richiede di cambiare l’allocazione strategica ogni volta.', false, 'Il ribilanciamento serve proprio a tornare all’allocazione strategica, che resta invariata finché non cambiano obiettivi o situazione.'],
  ],
  mcq: [
    { q: 'Target 50/50 su 20.000 €. Dopo un anno: azioni 13.000 €, obbligazioni 9.000 €. Quanto sposti dalle azioni alle obbligazioni?', a: '2.000 €', w: ['3.000 €', '1.000 €', '4.000 €'], e: 'Il totale è 22.000 €, il 50% è 11.000 €. Le azioni valgono 13.000 €: ne vendi 2.000 € e li investi in obbligazioni.' },
    { q: 'Target 60% azioni con banda di ±5 punti. In quale caso intervieni?', a: 'Azioni al 67%', w: ['Azioni al 62%', 'Azioni al 58%', 'Azioni al 64%'], e: 'La banda va dal 55% al 65%: solo al 67% il peso è fuori e serve ribilanciare.' },
    { q: 'Qual è il modo più efficiente di ribilanciare per chi versa ogni mese?', a: 'Indirizzare i versamenti sull’asset sottopesato', w: ['Vendere tutto e ricomprare ai pesi target', 'Aspettare che i pesi tornino da soli', 'Fare piccole vendite ogni giorno'], e: 'Usare i flussi in entrata non richiede vendite: niente commissioni di vendita né tasse sulle plusvalenze.' },
    { q: 'Dopo un crollo le azioni pesano il 48% invece del 60%. Cosa prevede il ribilanciamento?', a: 'Comprare azioni vendendo parte delle obbligazioni', w: ['Vendere altre azioni per limitare le perdite', 'Lasciare tutto com’è finché non risalgono', 'Abbassare per sempre il target al 48%'], e: 'Riportare le azioni al 60% vuol dire comprarle quando sono scese: è controintuitivo, ma è ciò che mantiene il piano.' },
    { q: 'Quale idea sul ribilanciamento è sbagliata?', a: 'Aumenta sempre il rendimento', w: ['Mantiene il rischio vicino al piano', 'Può generare tasse e commissioni', 'Si può fare con i nuovi versamenti'], e: 'Non garantisce più rendimento: in un lungo mercato al rialzo, ridurre le azioni può far guadagnare meno. Il suo scopo è controllare il rischio.' },
    { q: 'Cosa succede a un portafoglio 60/40 mai ribilanciato durante un lungo periodo di rialzi azionari?', a: 'Aumentano il peso delle azioni e il rischio', w: ['Il peso delle azioni scende a poco a poco', 'Il portafoglio resta sempre al 60/40 iniziale', 'Il rischio complessivo scende da solo'], e: 'Le azioni crescono più delle obbligazioni e il loro peso sale: il portafoglio diventa più aggressivo di quanto avevi scelto.' },
    { q: 'Qual è uno svantaggio di ribilanciare troppo spesso?', a: 'Più commissioni e possibili tasse', w: ['Il rischio esce dal controllo', 'Il portafoglio diventa meno diversificato', 'È vietato dalla normativa'], e: 'Ogni operazione costa e vendere in guadagno fa pagare imposte: piccole deviazioni dal target non giustificano questi costi.' },
    { q: 'Cosa prevede un metodo misto “calendario più soglia”?', a: 'Controllo periodico, intervento oltre la banda', w: ['Ribilanciamento ogni giorno, senza alcuna banda', 'Vendita di tutto il portafoglio a fine anno', 'Cambio dei pesi target a ogni controllo'], e: 'Controlli i pesi a date fisse, per esempio ogni anno, ma intervieni solo se uno di essi è uscito dalla banda di tolleranza.' },
  ],
  fill: [
    { s: 'Riportare i pesi delle classi di attività ai valori obiettivo si chiama ___.', a: 'ribilanciamento', w: ['market timing', 'stock picking', 'leva'] },
    { s: 'Il ribilanciamento a ___ interviene solo quando un peso esce dalla banda di tolleranza.', a: 'soglia', w: ['calendario', 'scadenza', 'rendimento'] },
    { s: 'L’allontanamento spontaneo dei pesi dal target si chiama ___ del portafoglio.', a: 'deriva', w: ['leva', 'liquidità', 'duration'] },
    { s: 'Chi versa ogni mese può ribilanciare indirizzando i nuovi soldi sull’asset ___.', a: 'sottopesato', w: ['sovrappesato', 'più rischioso', 'più costoso'] },
    { s: 'Vendere in guadagno per ribilanciare può far pagare le imposte sulle ___.', a: 'plusvalenze', w: ['minusvalenze', 'cedole', 'perdite'] },
  ],
  order: [
    { q: 'Ordina i passi di un ribilanciamento', i: ['Calcoli il valore totale del portafoglio', 'Moltiplichi il totale per i pesi target', 'Confronti con i valori attuali', 'Vendi l’asset in eccesso e compri quello in difetto'], e: 'Prima misuri, poi calcoli quanto dovrebbe valere ogni classe di attività, infine sposti solo la differenza.' },
    { q: 'Ordina gli eventi tipici di un 60/40 non ribilanciato durante un lungo rialzo', i: ['I pesi partono da 60/40', 'Le azioni salgono più delle obbligazioni', 'Il peso azionario arriva al 70%', 'Un crollo colpisce un portafoglio più rischioso del previsto'], e: 'La deriva aumenta il rischio proprio mentre le cose vanno bene; il conto arriva al primo forte ribasso.' },
  ],
  cat: [
    { q: 'Ribilanciamento a calendario o a soglia?', g: [['Calendario', ['Ogni 31 dicembre', 'Ogni sei mesi, a date fisse', 'Una volta l’anno, al compleanno']], ['Soglia', ['Quando le azioni superano il 65%', 'Quando un peso devia di oltre 5 punti', 'Quando le obbligazioni scendono sotto il 35%']]] },
    { q: 'Ribilanciamento corretto o errore?', g: [['Corretto', ['Comprare azioni dopo un calo che le ha sottopesate', 'Usare i versamenti per l’asset sottopesato', 'Valutare le tasse prima di vendere']], ['Errore', ['Vendere azioni dopo un crollo per paura', 'Ribilanciare ogni giorno per piccole deviazioni', 'Cambiare i pesi target a ogni notizia']]] },
  ],
  scen: [
    { s: 'Giacomo, 50 anni, ha un target 60/40, ma dopo anni di rialzi le azioni pesano il 72%, con plusvalenze elevate. Versa 500 € al mese nel portafoglio.', q: 'Come ribilancia?', o: [
      { t: 'Versa sulle obbligazioni e vende solo il necessario', ok: true, f: 'Riporta il rischio verso il piano riducendo al minimo vendite e tasse; un ribilanciamento ragionato è meglio di nessuno.' },
      { t: 'Lascia tutto com’è: le azioni stanno andando bene', ok: false, f: 'Il portafoglio ora è più rischioso del piano: in un crollo perderebbe più di quanto Giacomo aveva accettato.' },
      { t: 'Vende tutte le azioni e ricomincia da zero', ok: false, f: 'Stravolge il piano e paga tasse su tutte le plusvalenze: non è ribilanciare, è cambiare strategia.' },
    ] },
    { s: 'Elisa, 33 anni, ha un target 70% azioni e 30% obbligazioni. Dopo un forte calo dei mercati le azioni pesano il 58%. Ribilanciare vorrebbe dire comprarne, ma ha paura che scendano ancora.', q: 'Cosa fa?', o: [
      { t: 'Segue la regola e compra azioni fino al 70%', ok: true, f: 'È il momento in cui la disciplina conta: comprare dopo un calo è proprio ciò che il ribilanciamento automatizza.' },
      { t: 'Vende altre azioni per non perdere di più', ok: false, f: 'Vendere dopo un crollo trasforma un calo temporaneo in una perdita definitiva e porta il portafoglio lontano dal piano.' },
      { t: 'Abbassa per sempre il suo target al 58%', ok: false, f: 'Cambiare strategia per paura dopo un calo significa vendere basso. Il target si rivede quando cambiano obiettivi o situazione, non per i prezzi.' },
    ] },
    { s: 'Andrea, 41 anni, controlla il portafoglio ogni giorno e ribilancia appena un peso si sposta dell’1%. Ogni operazione gli costa commissioni e a volte tasse.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Adottare un controllo annuale con una banda di ±5 punti', ok: true, f: 'Una regola chiara e meno frequente mantiene il rischio sotto controllo tagliando costi, tasse e stress.' },
      { t: 'Continuare: più precisione significa più rendimento', ok: false, f: 'Inseguire piccole deviazioni non migliora il risultato: aggiunge solo costi certi.' },
      { t: 'Smettere del tutto di ribilanciare', ok: false, f: 'Passerebbe all’estremo opposto: senza ribilanciamento il rischio deriva lontano dal piano.' },
    ] },
    { s: 'Cristina, 64 anni, ha un target 40% azioni e 60% obbligazioni con banda di ±5 punti. Al controllo annuale trova 43% azioni e 57% obbligazioni.', q: 'Cosa fa?', o: [
      { t: 'Non interviene: la deviazione è dentro la banda', ok: true, f: 'Tre punti sono nella tolleranza prevista: intervenire genererebbe costi senza un reale beneficio sul rischio.' },
      { t: 'Ribilancia subito: ogni scostamento va corretto', ok: false, f: 'La banda esiste proprio per evitare operazioni inutili su piccole deviazioni.' },
      { t: 'Porta le azioni al 50%, visto che vanno bene', ok: false, f: 'Non è ribilanciare: è aumentare il rischio inseguendo i rialzi, contro il piano che si era data.' },
    ] },
  ],
  tip: 'Scegli in anticipo una regola semplice, per esempio controllo annuale e intervento oltre ±5 punti, e usa prima i nuovi versamenti: ribilanciare diventa automatico.',
});
