FQC(49, {
  intro: 'Investire una cifra fissa ogni mese: scopri come funziona il piano di accumulo, l’effetto media dei prezzi, i costi da controllare e i suoi limiti.',
  cards: [
    { t: 'Cos’è un PAC', x: 'Nel piano di accumulo investi una cifra fissa a intervalli regolari, per esempio 150 € al mese, in un fondo o in un ETF. È l’opposto del PIC, in cui versi tutto il capitale in un’unica soluzione.', v: { k: 'steps', s: ['Scegli importo e frequenza', 'Versamento automatico', 'Acquisto di quote', 'Ripeti per anni'] } },
    { t: 'L’effetto media dei prezzi', x: 'Con un importo fisso compri più quote quando il prezzo è basso e meno quando è alto. Con 100 € al mese e prezzi di 10, 5 e 10 € compri 10, 20 e 10 quote.', v: { k: 'bars', d: [['Mese 1: 10 €', 10], ['Mese 2: 5 €', 20], ['Mese 3: 10 €', 10]], u: ' quote' } },
    { t: 'Il prezzo medio di carico', x: 'Con il PAC paghi in media meno della media aritmetica dei prezzi del periodo. Non è magia: è l’effetto di comprare più quote quando costano meno.', v: { k: 'formula', f: 'Prezzo medio di carico = totale versato ÷ quote acquistate', n: 'Es.: 300 € ÷ 40 quote = 7,50 € (media dei prezzi: 8,33 €)' } },
    { t: 'PAC o PIC?', x: 'Se hai già il capitale, storicamente investirlo subito ha reso di più nella maggior parte dei casi, perché i mercati tendono a salire nel lungo periodo. Il PAC però riduce il rischio di entrare nel momento peggiore.', v: { k: 'vs', a: ['PAC', 'Entri gradualmente'], b: ['PIC', 'Tutto subito, più tempo sul mercato'] } },
    { t: 'Attenzione ai costi fissi', x: 'Una commissione fissa di 5 € pesa il 5% su una rata da 100 €, lo 0,5% su una da 1.000 €. Controlla anche se il piano concentra le commissioni d’ingresso sulle prime rate: se interrompi presto, costano molto.', v: { k: 'stat', n: '5%', l: 'peso di una commissione di 5 € su una rata da 100 €' } },
    { t: 'La disciplina conta', x: 'Il PAC funziona se lo porti avanti anche quando i mercati scendono: proprio allora compri a prezzi più bassi. Fermarsi nei ribassi annulla il suo vantaggio principale.', v: { k: 'icons', d: [['📉', 'Nei cali compri più quote'], ['🧘', 'Non fermarti per paura'], ['🔁', 'Automatizza il versamento']] } },
  ],
  terms: [
    ['PAC', 'Piano di accumulo: investimento di una somma fissa a intervalli regolari in fondi o ETF.'],
    ['PIC', 'Piano di investimento del capitale: investimento dell’intera somma in un’unica soluzione.'],
    ['Rata', 'Importo versato a ogni scadenza del piano, per esempio ogni mese.'],
    ['Prezzo medio di carico', 'Costo medio pagato per ogni quota: totale investito diviso per il numero di quote possedute.'],
    ['Cost averaging', 'Effetto per cui un importo fisso compra più quote a prezzi bassi e meno a prezzi alti.'],
    ['Durata del piano', 'Numero di anni o di versamenti previsto per completare il piano di accumulo.'],
    ['Commissioni anticipate', 'Costi d’ingresso concentrati sulle prime rate del piano invece che distribuiti nel tempo.'],
    ['Rischio di sequenza', 'Rischio che un forte calo arrivi verso la fine del piano, quando il capitale accumulato è maggiore.'],
  ],
  tf: [
    ['Con un PAC compri più quote quando il prezzo è basso e meno quando è alto.', true, 'Con un importo fisso, a un prezzo più basso corrisponde un numero di quote maggiore: è l’effetto media dei prezzi.'],
    ['Un PAC garantisce di non perdere soldi, se lo porti avanti abbastanza a lungo.', false, 'Mito: riduce il rischio di tempismo, ma se il mercato è in calo alla fine del piano puoi comunque essere in perdita.'],
    ['Con il PAC il prezzo medio di carico è di solito inferiore alla media aritmetica dei prezzi del periodo.', true, 'Comprando più quote a prezzi bassi, il costo medio per quota non supera mai la media dei prezzi; è uguale solo se il prezzo non cambia.'],
    ['Se hai già tutto il capitale, il PAC rende sempre più che investire subito.', false, 'Storicamente investire subito ha reso di più nella maggior parte dei casi; il PAC riduce soprattutto il rischio di entrare al momento peggiore.'],
    ['Una commissione fissa di 3 € su una rata da 60 € pesa il 5% del versamento.', true, '3 ÷ 60 = 5%: con rate piccole i costi fissi diventano molto pesanti. Meglio rate più alte o piani a commissioni ridotte.'],
    ['Durante un forte ribasso conviene sospendere il PAC e riprenderlo quando i mercati sono risaliti.', false, 'È proprio la fase in cui il PAC compra a prezzi più bassi: sospenderlo annulla il suo vantaggio principale.'],
    ['Verso la fine di un PAC lungo, un calo del mercato pesa di più perché il capitale accumulato è maggiore.', true, 'Le ultime rate sono piccole rispetto al montante: un ribasso finale colpisce quasi tutto il capitale. Per questo si riduce il rischio vicino all’obiettivo.'],
    ['In un PAC con commissioni anticipate, interrompere il piano dopo pochi mesi può costare molto.', true, 'Gran parte dei costi d’ingresso è caricata sulle prime rate: chi si ferma presto paga molto avendo investito poco.'],
    ['Il PAC è adatto solo a chi ha grandi capitali da investire.', false, 'È pensato proprio per chi risparmia un po’ ogni mese: bastano rate contenute, purché i costi fissi non le erodano.'],
    ['In un PAC la scelta dello strumento conta poco, perché il metodo dei versamenti riduce tutti i rischi.', false, 'Il PAC agisce sul momento di ingresso, non sulla qualità o sui costi dello strumento: un prodotto caro o inadatto resta tale.'],
  ],
  mcq: [
    { q: 'Investi 200 € al mese. I prezzi della quota nei tre mesi sono 20 €, 10 € e 20 €. Quante quote possiedi alla fine?', a: '40', w: ['30', '36', '60'], e: '200 ÷ 20 = 10, 200 ÷ 10 = 20, 200 ÷ 20 = 10: in tutto 40 quote, pagate in media 15 € l’una.' },
    { q: 'Versi 100 € al mese per tre mesi; la quota costa 10 €, 5 € e 10 €. Qual è il tuo prezzo medio di carico?', a: '7,50 €', w: ['8,33 €', '10,00 €', '5,00 €'], e: 'Compri 10 + 20 + 10 = 40 quote con 300 €: 300 ÷ 40 = 7,50 €, meno della media dei prezzi (8,33 €).' },
    { q: 'Che differenza c’è tra PAC e PIC?', a: 'Il PAC investe a rate, il PIC tutto in una volta', w: ['Il PAC è per le azioni, il PIC per le obbligazioni', 'Il PAC ha il capitale garantito, il PIC no', 'Il PAC si usa solo nei fondi pensione'], e: 'La differenza sta nel modo di entrare: gradualmente con il PAC, in un’unica soluzione con il PIC. Gli strumenti possono essere gli stessi.' },
    { q: 'Quale costo pesa di più su un PAC con rate da 50 €?', a: 'Una commissione fissa di 2,50 € a rata', w: ['Un TER dello 0,2% annuo', 'L’imposta di bollo dello 0,2% annuo', 'Uno spread dello 0,1% a ogni acquisto'], e: '2,50 € su 50 € sono il 5% di ogni versamento: molto più dei costi percentuali indicati nelle altre risposte.' },
    { q: 'Quale convinzione sul PAC è un errore comune?', a: 'Elimina il rischio di perdere', w: ['Media i prezzi di acquisto', 'Abitua a risparmiare con regolarità', 'Riduce il rischio di tempismo'], e: 'Il PAC distribuisce gli acquisti nel tempo, ma resta investito in strumenti rischiosi: a fine piano il valore può essere inferiore al versato.' },
    { q: 'Al quinto anno del tuo PAC ventennale i mercati perdono il 25%. Qual è la scelta più coerente con il piano?', a: 'Continuare i versamenti come previsto', w: ['Sospendere i versamenti fino alla ripresa', 'Riscattare tutto e ripartire da capo', 'Dimezzare la rata mensile per prudenza'], e: 'Nei ribassi la stessa rata compra più quote: è la fase in cui il PAC lavora meglio, se l’orizzonte resta lungo.' },
    { q: 'Perché un crollo nell’ultimo anno di un PAC fa più danni di uno nel primo anno?', a: 'Colpisce un capitale accumulato più grande', w: ['Le ultime rate hanno costi più alti', 'Le quote diventano non vendibili', 'Il TER aumenta con gli anni'], e: 'All’inizio hai investito poco e le rate successive comprano a sconto; alla fine il calo colpisce quasi tutto il montante. È il rischio di sequenza.' },
    { q: 'Hai ereditato 60.000 € e temi di investirli subito prima di un calo. Quale soluzione riduce il rischio di tempismo?', a: 'Investirli a rate mensili in 12-24 mesi', w: ['Investirli tutti insieme oggi stesso', 'Aspettare il prossimo crollo di borsa', 'Investirli solo dopo un forte rialzo'], e: 'Entrare a rate riduce il rimpianto di un ingresso sfortunato; in media rende un po’ meno, ma rende il percorso più sopportabile.' },
  ],
  fill: [
    { s: 'Nel PAC versi una somma ___ a intervalli regolari.', a: 'fissa', w: ['casuale', 'unica', 'garantita'] },
    { s: 'Investire tutto il capitale in un’unica soluzione si chiama ___.', a: 'PIC', w: ['PAC', 'TER', 'NAV'] },
    { s: 'Con un importo fisso, quando il prezzo scende compri ___ quote.', a: 'più', w: ['meno', 'le stesse', 'zero'] },
    { s: 'Il totale versato diviso per le quote acquistate dà il prezzo medio di ___.', a: 'carico', w: ['mercato', 'chiusura', 'emissione'] },
    { s: 'Nei PAC con commissioni ___ gran parte dei costi d’ingresso si paga con le prime rate.', a: 'anticipate', w: ['di performance', 'di uscita', 'di gestione'] },
  ],
  order: [
    { q: 'Ordina i passi per avviare e gestire un PAC', i: ['Definisci obiettivo e orizzonte', 'Scegli lo strumento confrontando i costi', 'Attiva il versamento automatico', 'Controlla il piano una volta l’anno'], e: 'Prima il perché e il quando, poi lo strumento e i suoi costi; l’automatismo e un controllo periodico aiutano a mantenere la disciplina.' },
    { q: 'Ordina dal peso percentuale più alto al più basso di una commissione fissa di 2 €', i: ['Rata da 25 €', 'Rata da 50 €', 'Rata da 100 €', 'Rata da 400 €'], e: '2 € pesano l’8% su 25 €, il 4% su 50 €, il 2% su 100 € e lo 0,5% su 400 €.' },
  ],
  cat: [
    { q: 'Vantaggio o limite del PAC?', g: [['Vantaggio', ['Media i prezzi di acquisto', 'Si adatta a chi risparmia ogni mese', 'Riduce il rischio di entrare al momento sbagliato']], ['Limite', ['Non elimina il rischio di perdita', 'I costi fissi pesano sulle rate piccole', 'Un calo a fine piano colpisce tutto il capitale']]] },
    { q: 'Comportamento corretto o sbagliato in un PAC?', g: [['Corretto', ['Continuare a versare nei ribassi', 'Automatizzare i versamenti', 'Ridurre il rischio vicino all’obiettivo']], ['Sbagliato', ['Sospendere i versamenti a ogni calo', 'Accettare costi fissi del 5% a rata', 'Interrompere presto un piano con costi anticipati']]] },
  ],
  scen: [
    { s: 'Giulia, 26 anni, vuole investire 100 € al mese in un ETF azionario globale. Il suo intermediario applica 4 € di commissione per ogni acquisto.', q: 'Cosa fa?', o: [
      { t: 'Versa ogni tre mesi o cerca costi più bassi', ok: true, f: '4 € su 100 € sono il 4% a rata. Con versamenti trimestrali da 300 € il costo scende a circa l’1,3%, o meno con piani a commissioni ridotte.' },
      { t: 'Va avanti così: 4 € a rata sono pochi soldi', ok: false, f: 'In euro sembrano pochi, ma sono il 4% di ogni versamento: molto più di quanto costa in un anno un ETF a basso costo.' },
      { t: 'Rinuncia finché non avrà 10.000 € da investire', ok: false, f: 'Rimandare ha un costo: perde tempo sul mercato e l’abitudine al risparmio. Basta ridurre il peso dei costi.' },
    ] },
    { s: 'Michele, 47 anni, ha avviato 3 anni fa un PAC azionario per la pensione. I mercati sono scesi del 30% e gli amici gli consigliano di fermarsi “finché non passa la tempesta”. Ha un fondo di emergenza e un lavoro stabile.', q: 'Cosa fa?', o: [
      { t: 'Continua i versamenti come previsto', ok: true, f: 'Orizzonte e situazione non sono cambiati: ora la stessa rata compra molte più quote, ed è così che il PAC abbassa il prezzo medio.' },
      { t: 'Sospende e riprende quando i mercati salgono', ok: false, f: 'Smette di comprare proprio quando i prezzi sono bassi e ricomincia quando sono già risaliti: il contrario di ciò che serve.' },
      { t: 'Riscatta tutto per limitare i danni', ok: false, f: 'Vendere dopo un calo del 30% rende definitiva una perdita temporanea, su un obiettivo ancora lontano.' },
    ] },
    { s: 'Ornella, 58 anni, porta avanti da 20 anni un PAC azionario per la pensione, che arriverà tra 2 anni. Ormai il capitale accumulato è molto più grande delle rate che versa.', q: 'Cosa fa?', o: [
      { t: 'Riduce gradualmente il rischio del capitale accumulato', ok: true, f: 'A due anni dall’obiettivo un crollo colpirebbe quasi tutto il montante, con poco tempo per recuperare: ridurre il rischio è coerente.' },
      { t: 'Resta al 100% azionario: il PAC la protegge', ok: false, f: 'Il PAC non protegge il capitale già accumulato: le nuove rate sono piccole rispetto al montante.' },
      { t: 'Aumenta le rate azionarie per sfruttare gli ultimi anni', ok: false, f: 'Aumenta l’esposizione proprio quando il tempo per recuperare un calo si sta esaurendo.' },
    ] },
    { s: 'Riccardo, 39 anni, ha ricevuto un’eredità di 50.000 € che vuole investire a lungo termine. È molto nervoso all’idea di investire tutto e vedere subito un calo.', q: 'Cosa fa?', o: [
      { t: 'Entra a rate per 12-18 mesi, tenendo il resto su un conto deposito', ok: true, f: 'Sacrifica un po’ di rendimento atteso in cambio di un ingresso più sereno: è un compromesso sensato se lo aiuta a restare investito.' },
      { t: 'Investe tutto in un titolo che “deve salire”', ok: false, f: 'Concentrare un’eredità su un solo titolo aggiunge rischio specifico: il nervosismo non si cura con una scommessa.' },
      { t: 'Lascia tutto sul conto finché i mercati non sono “tranquilli”', ok: false, f: 'I mercati non sono mai del tutto tranquilli: aspettare il momento perfetto spesso significa non entrare mai.' },
    ] },
  ],
  tip: 'Imposta il versamento automatico subito dopo lo stipendio e controlla il piano una volta l’anno: la regolarità vale più del tentativo di scegliere il momento giusto.',
});
