FQC(50, {
  intro: 'Quanto rischio puoi e vuoi prenderti? Scopri il questionario MiFID e la differenza tra tolleranza, capacità di rischio e orizzonte temporale.',
  cards: [
    { t: 'Il questionario MiFID', x: 'Prima di consigliarti un investimento, banca o consulente devono valutare conoscenze ed esperienza, situazione finanziaria (inclusa la capacità di sopportare perdite) e obiettivi. Lo prevede la normativa europea MiFID II.', v: { k: 'icons', d: [['🎓', 'Conoscenza ed esperienza'], ['💼', 'Situazione finanziaria'], ['🎯', 'Obiettivi e orizzonte']] } },
    { t: 'Tolleranza e capacità', x: 'La tolleranza è psicologica: come reagisci a un calo del 20%. La capacità è oggettiva: reddito, patrimonio, debiti, persone a carico. Se divergono, conta la più bassa delle due.', v: { k: 'vs', a: ['Tolleranza', 'Quanto rischio sei disposto a reggere'], b: ['Capacità', 'Quanto rischio puoi permetterti'] } },
    { t: 'L’orizzonte temporale', x: 'Più è lontano il momento in cui ti servono i soldi, più tempo hai per recuperare eventuali cali. Per un obiettivo vicino serve un investimento poco volatile, anche se il tuo profilo generale è dinamico.', v: { k: 'scale', a: 'Orizzonte breve', b: 'Orizzonte lungo', d: [['Spesa tra 1 anno', 8], ['Auto tra 4 anni', 30], ['Casa tra 8 anni', 55], ['Pensione tra 30 anni', 95]] } },
    { t: 'Quanto potresti perdere?', x: 'Ordini di grandezza indicativi dei cali in una grave crisi: più azioni significano cadute più profonde. Chiediti se reggeresti quel calo senza vendere, non solo quanto vorresti guadagnare.', v: { k: 'bars', d: [['20% azioni', -10], ['50% azioni', -25], ['80% azioni', -40], ['100% azioni', -50]], u: '%' } },
    { t: 'L’indicatore di rischio del prodotto', x: 'Nel KID ogni prodotto ha un indicatore sintetico di rischio da 1 (più basso) a 7 (più alto). L’intermediario confronta il rischio del prodotto con il tuo profilo per valutare se è adeguato.', v: { k: 'stat', n: '1-7', l: 'scala dell’indicatore sintetico di rischio nel KID' } },
    { t: 'Rispondi con sincerità', x: 'Gonfiare esperienza o tolleranza per accedere a prodotti più rischiosi si ritorce contro di te. Il profilo va aggiornato quando cambiano lavoro, famiglia, patrimonio o obiettivi.', v: { k: 'steps', s: ['Rispondi con onestà', 'Ricevi il profilo', 'Valuta proposte adeguate', 'Aggiorna se cambia la vita'] } },
  ],
  terms: [
    ['Profilo di rischio', 'Sintesi di quanto rischio un investitore vuole e può sostenere, in base a obiettivi e situazione.'],
    ['Questionario MiFID', 'Insieme di domande con cui l’intermediario raccoglie le informazioni sul cliente per tutelarlo.'],
    ['Tolleranza al rischio', 'Disponibilità psicologica a sopportare oscillazioni e perdite temporanee del capitale.'],
    ['Capacità di rischio', 'Possibilità economica di sopportare perdite senza compromettere tenore di vita e obiettivi.'],
    ['Orizzonte temporale', 'Periodo che separa il momento dell’investimento da quello in cui serviranno i soldi.'],
    ['Adeguatezza', 'Coerenza di un investimento consigliato con conoscenze, situazione finanziaria e obiettivi del cliente.'],
    ['Appropriatezza', 'Verifica, senza consulenza, che il cliente abbia conoscenze ed esperienza per capire un prodotto.'],
    ['Indicatore sintetico di rischio', 'Numero da 1 a 7, riportato nel KID, che riassume il livello di rischio di un prodotto.'],
  ],
  tf: [
    ['Tolleranza e capacità di rischio sono la stessa cosa.', false, 'La tolleranza è la disponibilità psicologica a sopportare perdite; la capacità è la possibilità economica di farlo. Possono essere molto diverse.'],
    ['Se tolleranza e capacità di rischio non coincidono, è prudente basarsi sulla più bassa.', true, 'Un investitore coraggioso con finanze fragili, o uno solido ma ansioso, sbaglierebbe guardando solo l’aspetto più alto.'],
    ['Nel questionario MiFID conviene dichiararsi più esperti per accedere a più prodotti.', false, 'Mito pericoloso: risposte non veritiere portano a proposte inadeguate, e le perdite restano tue. Il questionario serve a proteggerti.'],
    ['A parità di altre condizioni, un orizzonte temporale più lungo consente di assumere più rischio.', true, 'Con più tempo è più probabile recuperare i cali temporanei; con soldi che servono presto, un calo può diventare una perdita definitiva.'],
    ['Una persona giovane ha sempre un profilo di rischio alto.', false, 'L’età aiuta, ma contano anche reddito, debiti, fondo di emergenza, obiettivi e reazione emotiva alle perdite.'],
    ['Il profilo di rischio va aggiornato quando cambiano lavoro, famiglia o patrimonio.', true, 'Un figlio, un mutuo o la perdita del lavoro possono ridurre la capacità di rischio: il profilo deve seguire la vita reale.'],
    ['La capacità di rischio dipende anche dalla presenza di un fondo di emergenza.', true, 'Senza riserve liquide un imprevisto può costringerti a vendere in perdita: un cuscinetto di sicurezza aumenta la capacità di reggere i cali.'],
    ['Un indicatore di rischio 2 su 7 nel KID indica un prodotto ad alto rischio.', false, 'La scala va da 1 (rischio più basso) a 7 (più alto): 2 indica un rischio basso.'],
    ['Dopo un lungo periodo di rialzi molte persone tendono a sovrastimare la propria tolleranza al rischio.', true, 'Quando i mercati salgono è facile sentirsi coraggiosi; la vera tolleranza si vede durante un calo. Aiuta pensare a perdite concrete in euro.'],
    ['Chi ha un profilo prudente non dovrebbe mai detenere alcuna azione.', false, 'Prudente non significa zero azioni: una piccola quota azionaria ben diversificata può essere coerente, se il rischio complessivo resta basso.'],
  ],
  mcq: [
    { q: 'Cosa misura la capacità di rischio?', a: 'Quanto puoi perdere senza danni ai tuoi obiettivi', w: ['Quanto ti senti a tuo agio con le oscillazioni', 'Quanto conosci gli strumenti finanziari', 'Quante operazioni fai in un anno'], e: 'È un dato oggettivo legato a reddito, patrimonio, debiti e impegni; il disagio emotivo riguarda invece la tolleranza.' },
    { q: 'Carlo, 35 anni, ama il rischio ma ha un mutuo, due figli piccoli e nessun risparmio di emergenza. Come va valutato il suo profilo?', a: 'Più prudente, per la bassa capacità di rischio', w: ['Aggressivo, per l’alta tolleranza al rischio', 'Aggressivo, perché è ancora giovane', 'Indifferente: conta solo l’orizzonte'], e: 'La sua tolleranza è alta ma la capacità è bassa: prevale la più bassa. Prima servono un fondo di emergenza e una base solida.' },
    { q: 'Quali aree copre la valutazione di adeguatezza prevista dalla MiFID?', a: 'Conoscenze, situazione finanziaria e obiettivi', w: ['Solo età, professione e titolo di studio', 'Solo il patrimonio e il reddito annuo', 'Le previsioni del cliente sui mercati'], e: 'Considera conoscenze ed esperienza, situazione finanziaria (inclusa la capacità di sostenere perdite) e obiettivi, compresa la tolleranza al rischio.' },
    { q: 'Ti servono 20.000 € tra 18 mesi per il matrimonio. Quale orizzonte va considerato per quei soldi?', a: 'Breve, anche se investi a lungo il resto', w: ['Lungo, perché hai solo 30 anni', 'Lungo, se il profilo generale è dinamico', 'Nessuno: conta solo la tolleranza'], e: 'L’orizzonte si valuta per obiettivo: soldi che servono tra 18 mesi non possono permettersi un calo del 20% poco prima della scadenza.' },
    { q: 'Quale affermazione sul profilo di rischio è un errore comune?', a: '“Da giovane posso rischiare tutto, sempre”', w: ['“Il profilo va aggiornato nel tempo”', '“Conta anche quanto posso perdere”', '“Un obiettivo vicino chiede meno rischio”'], e: 'L’età è solo un fattore: debiti, reddito instabile o obiettivi vicini possono rendere inadatto molto rischio anche a 25 anni.' },
    { q: 'Cosa indica un indicatore sintetico di rischio 6 su 7 nel KID?', a: 'Un prodotto ad alto rischio', w: ['Un prodotto a capitale garantito', 'Un rendimento atteso del 6%', 'Una durata consigliata di 6 anni'], e: 'La scala va da 1 a 7: 6 indica un rischio elevato, tipico per esempio di prodotti azionari. Non è un rendimento né una durata.' },
    { q: 'Quale esercizio aiuta di più a capire la tua reale tolleranza al rischio?', a: 'Immaginare una perdita concreta in euro', w: ['Ripensare al miglior anno della borsa', 'Chiedere quanto rende il collega', 'Copiare le risposte di un esperto'], e: 'Chiederti “se 50.000 € diventassero 35.000 €, resterei investito?” è più realistico che ragionare solo in percentuali o sui guadagni.' },
    { q: 'Oltre a rischio e obiettivi, nella consulenza l’intermediario deve raccogliere anche…', a: 'le tue preferenze di sostenibilità', w: ['i codici fiscali dei tuoi familiari', 'le tue previsioni sull’inflazione', 'i saldi dei conti in altre banche'], e: 'La normativa europea prevede che nella valutazione di adeguatezza si chiedano anche le preferenze del cliente in materia di sostenibilità.' },
  ],
  fill: [
    { s: 'La ___ al rischio è la disponibilità psicologica a sopportare le perdite.', a: 'tolleranza', w: ['capacità', 'copertura', 'misurazione'] },
    { s: 'La ___ di rischio dipende da reddito, patrimonio, debiti e persone a carico.', a: 'capacità', w: ['tolleranza', 'percezione', 'preferenza'] },
    { s: 'Più è lungo l’___ temporale, più tempo hai per recuperare eventuali cali.', a: 'orizzonte', w: ['obiettivo', 'indicatore', 'andamento'] },
    { s: 'L’indicatore sintetico di rischio del KID va da 1 a ___.', a: '7', w: ['5', '10', '100'] },
    { s: 'La valutazione di ___ verifica che un investimento consigliato sia coerente con il profilo del cliente.', a: 'adeguatezza', w: ['appropriatezza', 'solvibilità', 'liquidità'] },
  ],
  order: [
    { q: 'Ordina i passi di una consulenza secondo la MiFID', i: ['Compili il questionario', 'L’intermediario definisce il tuo profilo', 'Ti propone prodotti adeguati', 'Il profilo viene aggiornato nel tempo'], e: 'Prima si raccolgono le informazioni, poi si definisce il profilo e su quella base si valutano i prodotti; il profilo va rivisto periodicamente.' },
    { q: 'Ordina gli obiettivi dall’orizzonte più breve al più lungo', i: ['Vacanza tra 6 mesi', 'Auto nuova tra 3 anni', 'Anticipo della casa tra 7 anni', 'Pensione tra 25 anni'], e: 'Più l’obiettivo è lontano, più rischio puoi in genere assumere per la parte di patrimonio dedicata a quell’obiettivo.' },
  ],
  cat: [
    { q: 'Riguarda la tolleranza o la capacità di rischio?', g: [['Tolleranza', ['Ansia quando il portafoglio scende', 'Reazione passata a un forte calo', 'Disponibilità ad accettare oscillazioni']], ['Capacità', ['Stabilità del reddito', 'Presenza di un fondo di emergenza', 'Debiti e persone a carico']]] },
    { q: 'Aumenta o riduce la capacità di rischio?', g: [['Aumenta', ['Reddito alto e stabile', 'Fondo di emergenza solido', 'Obiettivo lontano nel tempo']], ['Riduce', ['Mutuo appena acceso con rata elevata', 'Lavoro precario', 'Spesa importante tra un anno']]] },
  ],
  scen: [
    { s: 'Federica, 29 anni, compila il questionario MiFID. Le interessa un prodotto complesso e un conoscente le suggerisce di dichiarare più esperienza di quella che ha, “così te lo fanno comprare”.', q: 'Cosa fa?', o: [
      { t: 'Risponde con sincerità e chiede spiegazioni', ok: true, f: 'Il questionario serve a proteggerla: se il prodotto è adatto lo scoprirà capendolo, non falsando il proprio profilo.' },
      { t: 'Dichiara più esperienza: tanto è una formalità', ok: false, f: 'Non è una formalità: risposte false portano a prodotti inadatti, e il rischio di perdite resta suo.' },
      { t: 'Lascia in bianco le domande sull’esperienza', ok: false, f: 'Senza queste informazioni l’intermediario non può valutare l’adeguatezza e quindi non può consigliarle prodotti.' },
    ] },
    { s: 'Gianni, 62 anni, ha compilato il questionario 10 anni fa con un profilo “dinamico”. Ora è in pensione, ha smesso di risparmiare e userà gli investimenti per integrare il reddito.', q: 'Cosa fa?', o: [
      { t: 'Chiede di aggiornare il profilo alla nuova situazione', ok: true, f: 'Reddito, orizzonte e obiettivi sono cambiati: un profilo di 10 anni fa non descrive più la sua capacità di rischio.' },
      { t: 'Lascia tutto com’è: il profilo è già stato fatto', ok: false, f: 'Il profilo non è eterno: con un orizzonte più breve e senza nuovi risparmi, un calo forte peserebbe molto di più.' },
      { t: 'Dichiara un profilo più aggressivo per recuperare tempo', ok: false, f: 'Aumentare il rischio proprio quando la capacità si è ridotta è la scelta più pericolosa.' },
    ] },
    { s: 'Alessia, 40 anni, nel questionario si era detta “molto tollerante al rischio”. Al primo calo del 15% del portafoglio è stata tentata di vendere tutto e non ha dormito per giorni.', q: 'Cosa fa?', o: [
      { t: 'Non vende nel panico e poi rivede con calma il profilo', ok: true, f: 'La reazione al calo è un’informazione preziosa: meglio un portafoglio un po’ meno rischioso che sa tenere, deciso con calma.' },
      { t: 'Vende tutto subito: il mercato potrebbe scendere ancora', ok: false, f: 'Vendere nel panico rende definitiva la perdita: le decisioni sul rischio si prendono a mente fredda, non durante il calo.' },
      { t: 'Aumenta il rischio per recuperare più in fretta', ok: false, f: 'Va contro ciò che ha appena scoperto di sé: con più rischio il prossimo calo sarebbe ancora più difficile da sopportare.' },
    ] },
    { s: 'Pietro, 45 anni, ha un reddito alto e stabile, nessun debito e un patrimonio solido. Però si agita moltissimo quando i suoi investimenti perdono anche solo il 5%.', q: 'Quale portafoglio è più adatto a lui?', o: [
      { t: 'Un portafoglio moderato, che regge anche nei cali', ok: true, f: 'Ha capacità alta ma tolleranza bassa: conta la più bassa. Un portafoglio che lo porta a vendere nel panico renderebbe meno di uno più prudente.' },
      { t: 'Il massimo rischio: le sue finanze lo permettono', ok: false, f: 'La capacità c’è, ma se l’ansia lo porta a vendere nei cali le perdite diventano definitive.' },
      { t: 'Tutto sul conto corrente, per non pensarci', ok: false, f: 'Zero rischio di mercato ma perdita certa di potere d’acquisto: un portafoglio prudente è una via di mezzo migliore.' },
    ] },
  ],
  tip: 'Prima di firmare il questionario traduci le percentuali in euro: se perdere il 20% del tuo capitale ti toglierebbe il sonno, il tuo profilo non è aggressivo.',
});
