FQC(51, {
  intro: 'Il bilancio è la carta d’identità economica di un’azienda: scopri i tre prospetti, chi li controlla e ogni quanto vengono pubblicati.',
  cards: [
    { t: 'Tre prospetti, una storia', x: 'Il bilancio racconta l’azienda da tre angoli: il conto economico dice se guadagna, lo stato patrimoniale cosa possiede e cosa deve, il rendiconto finanziario come entra ed esce la cassa.', v: { k: 'icons', d: [['🧮', 'Conto economico'], ['🏗️', 'Stato patrimoniale'], ['🌊', 'Rendiconto finanziario']] } },
    { t: 'Film contro fotografia', x: 'Conto economico e rendiconto finanziario coprono un periodo, di solito un anno: sono un film. Lo stato patrimoniale descrive la situazione a una data precisa, spesso il 31 dicembre: è una fotografia.', v: { k: 'vs', a: ['Conto economico', 'Flussi di un periodo'], b: ['Stato patrimoniale', 'Situazione a una data'] } },
    { t: 'I prospetti sono collegati', x: 'L’utile netto non distribuito come dividendo va ad aumentare il patrimonio netto. Così il conto economico si aggancia allo stato patrimoniale, e il rendiconto spiega la variazione della cassa.', v: { k: 'formula', f: 'PN finale = PN iniziale + utile netto − dividendi', n: 'Es. Alfa Spa: 500 + 60 − 20 = 540 (senza altre operazioni)' } },
    { t: 'Dal CdA all’assemblea', x: 'Chiuso l’esercizio, gli amministratori preparano il progetto di bilancio, il revisore lo verifica ed esprime un giudizio, l’assemblea degli azionisti lo approva e decide sull’eventuale dividendo.', v: { k: 'steps', s: ['Chiusura esercizio', 'Progetto del CdA', 'Revisione', 'Approvazione assemblea'] } },
    { t: 'Il giudizio del revisore', x: 'Una società di revisione indipendente controlla che il bilancio rispetti i principi contabili. Dà una ragionevole sicurezza, non una garanzia assoluta: un giudizio con rilievi o negativo è un campanello d’allarme.', v: { k: 'scale', a: 'Rassicurante', b: 'Allarme', d: [['Senza rilievi', 10], ['Con rilievi', 50], ['Negativo', 95]] } },
    { t: 'Il calendario dei conti', x: 'Le quotate italiane pubblicano la relazione annuale entro quattro mesi dalla chiusura e una relazione semestrale. Nell’UE le trimestrali non sono più obbligatorie per tutte, ma molte società le diffondono comunque.', v: { k: 'stat', n: '4 mesi', l: 'tempo massimo per la relazione annuale delle quotate italiane' } },
  ],
  terms: [
    ['Note al bilancio', 'Sezione che spiega i criteri contabili usati e dettaglia le singole voci dei prospetti.'],
    ['Relazione sulla gestione', 'Documento degli amministratori che commenta andamento, rischi ed evoluzione prevedibile.'],
    ['Bilancio consolidato', 'Conti di un gruppo presentati come se capogruppo e controllate fossero un’unica entità.'],
    ['IFRS', 'Principi contabili internazionali obbligatori per i bilanci consolidati delle quotate nell’UE.'],
    ['Società di revisione', 'Soggetto indipendente che verifica il bilancio ed esprime un giudizio professionale.'],
    ['Principio di competenza', 'Regola per cui ricavi e costi si registrano quando maturano, non quando si incassa o si paga.'],
    ['Giudizio con rilievi', 'Parere del revisore: conti corretti nel complesso, salvo alcune eccezioni specifiche.'],
    ['Relazione semestrale', 'Rendiconto dei primi sei mesi dell’esercizio che le società quotate devono pubblicare.'],
  ],
  tf: [
    ['Lo stato patrimoniale descrive la situazione dell’azienda a una data precisa.', true, 'È una fotografia di attività, passività e patrimonio netto alla data di chiusura, per esempio il 31 dicembre.'],
    ['Il conto economico mostra quanta cassa è entrata e uscita durante l’anno.', false, 'Il conto economico segue la competenza: ricavi e costi maturati. I movimenti di cassa stanno nel rendiconto finanziario.'],
    ['Un giudizio di revisione senza rilievi garantisce che in azienda non ci siano frodi.', false, 'Il revisore offre una ragionevole sicurezza sulla correttezza dei conti, non una certezza assoluta: frodi ben nascoste possono sfuggire.'],
    ['Nell’Unione europea le relazioni trimestrali non sono obbligatorie per tutte le società quotate.', true, 'Le regole europee hanno eliminato l’obbligo generale; molte società però continuano a pubblicarle su base volontaria.'],
    ['Il bilancio consolidato rappresenta capogruppo e controllate come un’unica entità economica.', true, 'Somma i conti delle società del gruppo ed elimina i rapporti interni, come vendite e crediti tra società dello stesso gruppo.'],
    ['L’utile dell’anno non distribuito come dividendo fa aumentare il patrimonio netto.', true, 'Gli utili trattenuti confluiscono nelle riserve: è il ponte tra conto economico e stato patrimoniale.'],
    ['In una Spa italiana il bilancio viene approvato in via definitiva dal revisore.', false, 'Il revisore esprime solo un giudizio. Nel modello tradizionale il progetto lo redigono gli amministratori e lo approva l’assemblea.'],
    ['Un’azienda in utile può comunque trovarsi a corto di liquidità.', true, 'Se i clienti pagano in ritardo o gli investimenti assorbono denaro, l’utile contabile non si traduce in cassa disponibile.'],
    ['Per giudicare un’azienda basta guardare l’utile netto dell’ultimo anno.', false, 'Un solo numero di un solo anno può ingannare: servono i tre prospetti, più esercizi a confronto e le note sulle voci straordinarie.'],
    ['Le note al bilancio sono una parte accessoria che si può saltare senza perdere nulla.', false, 'Le note spiegano criteri contabili, scadenze dei debiti, contenziosi e impegni: spesso contengono le informazioni più rivelatrici.'],
  ],
  mcq: [
    { q: 'Quale prospetto mostra cosa l’azienda possiede e cosa deve a una certa data?', a: 'Lo stato patrimoniale', w: ['Il conto economico', 'Il rendiconto finanziario', 'La relazione sulla gestione'], e: 'Lo stato patrimoniale elenca attività, passività e patrimonio netto alla data di chiusura dell’esercizio.' },
    { q: 'Quale prospetto spiega perché la cassa è cambiata nel corso dell’anno?', a: 'Il rendiconto finanziario', w: ['Lo stato patrimoniale', 'Il conto economico', 'La relazione del revisore'], e: 'Il rendiconto finanziario divide i flussi di cassa in tre aree: gestione operativa, investimenti e finanziamenti.' },
    { q: 'Nel modello di governance tradizionale, chi approva il bilancio di una Spa italiana?', a: 'L’assemblea degli azionisti', w: ['La società di revisione', 'La CONSOB', 'Il collegio sindacale'], e: 'Gli amministratori redigono il progetto, revisore e sindaci lo controllano, ma l’approvazione spetta all’assemblea dei soci.' },
    { q: 'Che cosa indica un giudizio «con rilievi» del revisore?', a: 'Conti corretti salvo alcune eccezioni', w: ['Conti corretti senza alcuna eccezione', 'Conti che non è stato possibile esaminare', 'Conti scorretti nel loro complesso'], e: 'Con rilievi: ci sono aspetti non conformi ma circoscritti. Un giudizio negativo o l’impossibilità di esprimerlo sono segnali più gravi.' },
    { q: 'Quale principio fa registrare a dicembre una vendita che il cliente pagherà a febbraio?', a: 'Il principio di competenza', w: ['Il principio di cassa', 'Il principio di prudenza', 'Il principio di continuità'], e: 'Per competenza il ricavo si registra quando la vendita avviene; l’incasso di febbraio comparirà nei flussi di cassa dell’anno successivo.' },
    { q: 'Quali principi contabili usano le società quotate nell’UE per il bilancio consolidato?', a: 'Gli IFRS', w: ['Gli US GAAP', 'I principi OIC', 'Le norme del TUIR'], e: 'Dal 2005 il consolidato delle quotate UE segue gli IFRS; i principi OIC sono usati da molte società italiane non quotate.' },
    { q: 'Quale di queste convinzioni sul bilancio è un errore comune?', a: 'Se c’è utile, c’è anche cassa', w: ['L’esercizio dura di solito un anno', 'Il revisore è esterno all’azienda', 'Le note dettagliano le voci'], e: 'Utile e cassa sono diversi: crediti non incassati, magazzino e investimenti possono assorbire liquidità anche in un anno in utile.' },
    { q: 'Dove trovi i commenti degli amministratori su rischi e prospettive?', a: 'Nella relazione sulla gestione', w: ['Nello stato patrimoniale', 'Nel rendiconto finanziario', 'Nella relazione del revisore'], e: 'La relazione sulla gestione accompagna i prospetti e descrive andamento, rischi principali ed evoluzione prevedibile dell’attività.' },
  ],
  fill: [
    { s: 'Il conto economico è un film, mentre lo stato ___ è una fotografia.', a: 'patrimoniale', w: ['finanziario', 'economico', 'consolidato'] },
    { s: 'Il giudizio sul bilancio è espresso da una società di ___ indipendente.', a: 'revisione', w: ['rating', 'gestione', 'consulenza'] },
    { s: 'Il bilancio ___ rappresenta un gruppo come un’unica entità.', a: 'consolidato', w: ['separato', 'civilistico', 'abbreviato'] },
    { s: 'Per il principio di ___ i costi si registrano quando maturano, non quando si pagano.', a: 'competenza', w: ['cassa', 'liquidità', 'prudenza'] },
    { s: 'Oltre al bilancio annuale, le quotate pubblicano una relazione ___ sui primi sei mesi.', a: 'semestrale', w: ['trimestrale', 'consolidata', 'previsionale'] },
  ],
  order: [
    { q: 'Ordina le fasi del bilancio annuale di una Spa', i: ['Chiusura dell’esercizio', 'Progetto di bilancio del CdA', 'Relazione del revisore', 'Approvazione in assemblea', 'Pagamento dell’eventuale dividendo'], e: 'Il CdA redige il progetto, il revisore lo verifica, l’assemblea approva e delibera l’eventuale dividendo, che viene poi pagato.' },
    { q: 'Ordina il percorso di una vendita attraverso i prospetti', i: ['Vendita al cliente', 'Ricavo nel conto economico', 'Utile netto dell’esercizio', 'Utile trattenuto nel patrimonio netto'], e: 'La vendita genera un ricavo; dopo costi e imposte resta l’utile netto, che se non distribuito accresce il patrimonio netto.' },
  ],
  cat: [
    { q: 'Riguarda un periodo o una data precisa?', g: [['Un periodo', ['Conto economico', 'Rendiconto finanziario', 'Ricavi dell’anno', 'Flusso di cassa operativo']], ['Una data precisa', ['Stato patrimoniale', 'Cassa al 31 dicembre', 'Debiti verso banche', 'Magazzino di fine anno']]] },
    { q: 'Chi se ne occupa: amministratori o revisore?', g: [['Amministratori', ['Redigono il progetto di bilancio', 'Scrivono la relazione sulla gestione', 'Propongono il dividendo']], ['Revisore', ['Verifica i conti con controlli a campione', 'Esprime un giudizio professionale', 'Deve essere indipendente dall’azienda']]] },
  ],
  scen: [
    { s: 'Giulia, 34 anni, legge che Alfa Spa ha annunciato utili record. Nella relazione annuale però la società di revisione dichiara di non poter esprimere un giudizio, perché non ha ottenuto documenti sufficienti.', q: 'Cosa fa Giulia?', o: [
      { t: 'Approfondisce e resta alla larga finché la questione non è chiarita', ok: true, f: 'Se il revisore non riesce a esprimersi, quei numeri non sono verificati: gli utili record potrebbero non essere affidabili.' },
      { t: 'Compra subito, perché gli utili record contano più della revisione', ok: false, f: 'Un utile non verificato vale poco: senza un giudizio di revisione non sai se il numero è attendibile.' },
      { t: 'Ignora la relazione del revisore, è solo un tecnicismo formale', ok: false, f: 'La relazione del revisore è il primo controllo esterno sui conti: un’impossibilità di giudizio è un segnale grave.' },
    ] },
    { s: 'Marco, 45 anni, confronta due società quotate: Beta Spa pubblica i conti ogni trimestre, Gamma Spa solo ogni sei mesi. Marco pensa che Gamma nasconda qualcosa.', q: 'Come dovrebbe ragionare?', o: [
      { t: 'Gamma ha sicuramente problemi, quindi va scartata', ok: false, f: 'Nell’UE le trimestrali non sono obbligatorie per tutte: pubblicare ogni sei mesi è una scelta legittima, non una prova di problemi.' },
      { t: 'Valuta entrambe sulla qualità e chiarezza dei conti pubblicati', ok: true, f: 'Conta la qualità dell’informativa, non solo la frequenza: giudizio del revisore, note chiare e coerenza tra un periodo e l’altro.' },
      { t: 'Sceglie Beta, perché più report significano conti migliori', ok: false, f: 'Più report danno più aggiornamenti, ma non rendono l’azienda più sana né i suoi conti più corretti.' },
    ] },
    { s: 'Sara, 28 anni, vuole investire in Delta Spa. Ha letto solo il conto economico: ricavi e utile crescono da tre anni. Non ha guardato né lo stato patrimoniale né il rendiconto finanziario.', q: 'Qual è la mossa più sensata?', o: [
      { t: 'Decide subito: tre anni di crescita dell’utile bastano', ok: false, f: 'L’utile può crescere anche mentre i debiti esplodono o la cassa si esaurisce: un solo prospetto non basta.' },
      { t: 'Si affida solo all’andamento del prezzo in borsa', ok: false, f: 'Il prezzo riflette aspettative e umori del mercato, non sostituisce la lettura dei conti dell’azienda.' },
      { t: 'Controlla anche debiti, patrimonio e flussi di cassa', ok: true, f: 'Solo i tre prospetti insieme mostrano se la crescita è sana: un utile in aumento con cassa in calo merita domande.' },
    ] },
    { s: 'Luca, 52 anni, studia il gruppo Epsilon Spa. Il bilancio separato della capogruppo mostra un buon utile, grazie ai dividendi ricevuti dalle controllate; il bilancio consolidato del gruppo chiude invece in perdita.', q: 'Quale bilancio deve guardare per valutare il gruppo?', o: [
      { t: 'Il consolidato, che rappresenta l’intero gruppo', ok: true, f: 'Il consolidato elimina i dividendi interni e mostra il risultato economico complessivo: è quello che riflette l’attività del gruppo.' },
      { t: 'Il separato, perché mostra un utile più alto', ok: false, f: 'L’utile della capogruppo nasce in parte da dividendi interni: per il gruppo nel suo insieme quei soldi sono solo spostati.' },
      { t: 'La media dei due, per avere una via di mezzo', ok: false, f: 'Fare la media tra due prospetti diversi non ha senso contabile: ognuno risponde a una domanda diversa.' },
    ] },
  ],
  tip: 'Prima di valutare un’azienda leggi la relazione del revisore e confronta almeno tre esercizi: i trend raccontano più di un singolo anno.',
});
