FQC(52, {
  intro: 'Dai ricavi all’utile netto, un gradino alla volta: impara a leggere il conto economico e a capire dove un’azienda guadagna o perde.',
  cards: [
    { t: 'Una scala che scende', x: 'Il conto economico parte dai ricavi e sottrae i costi a gradini: prima quelli operativi, poi ammortamenti, oneri finanziari e imposte. Ogni gradino risponde a una domanda diversa sulla salute dell’azienda.', v: { k: 'steps', s: ['Ricavi', 'EBITDA', 'EBIT', 'Utile ante imposte', 'Utile netto'] } },
    { t: 'Un esempio: Alfa Spa', x: 'Alfa Spa ha ricavi per 1.000 milioni; tolti 800 di costi operativi resta un EBITDA di 200. Meno 60 di ammortamenti, EBIT 140. Meno 20 di oneri finanziari e 30 di imposte: utile netto 90.', v: { k: 'bars', d: [['Ricavi', 1000], ['EBITDA', 200], ['EBIT', 140], ['Utile netto', 90]], u: 'mln €' } },
    { t: 'L’EBITDA', x: 'L’EBITDA, o margine operativo lordo, misura quanto rende la gestione tipica prima di ammortamenti, interessi e imposte. Non è definito dagli IFRS: ogni azienda può calcolarlo in modo un po’ diverso, quindi leggi la sua definizione.', v: { k: 'formula', f: 'EBITDA = ricavi − costi operativi (esclusi ammortamenti)', n: 'Es. Alfa Spa: 1.000 − 800 = 200' } },
    { t: 'EBITDA o EBIT?', x: 'L’EBIT, o risultato operativo, sottrae anche ammortamenti e svalutazioni, cioè l’usura di impianti e macchinari ripartita negli anni. Per un’azienda con molti impianti l’EBIT è più realistico dell’EBITDA.', v: { k: 'vs', a: ['EBITDA', 'Prima degli ammortamenti'], b: ['EBIT', 'Dopo gli ammortamenti'] } },
    { t: 'Dove finiscono 100 euro di ricavi', x: 'Su 100 euro di ricavi di Alfa Spa, 80 coprono materie prime, personale e servizi, 6 gli ammortamenti, 2 gli interessi e 3 le imposte. All’azienda restano 9 euro di utile netto.', v: { k: 'pie', d: [['Costi operativi', 80], ['Ammortamenti', 6], ['Oneri finanziari', 2], ['Imposte', 3], ['Utile netto', 9]] } },
    { t: 'Ricorrente o una tantum?', x: 'Plusvalenze da cessioni, svalutazioni e costi di ristrutturazione sono spesso non ricorrenti. Separali per capire la redditività di fondo, ma diffida se gli eventi «eccezionali» si ripetono ogni anno.', v: { k: 'icons', d: [['🔁', 'Vendite abituali'], ['🏷️', 'Plusvalenza da cessione'], ['🧹', 'Costi di ristrutturazione']] } },
  ],
  terms: [
    ['Ricavi', 'Valore di beni e servizi venduti nel periodo; nel linguaggio comune, fatturato.'],
    ['Margine lordo', 'Ricavi meno costo del venduto: quanto resta per coprire le altre spese.'],
    ['EBITDA', 'Risultato prima di interessi, imposte, ammortamenti e svalutazioni; in italiano MOL.'],
    ['EBIT', 'Risultato operativo: EBITDA meno ammortamenti e svalutazioni.'],
    ['Ammortamento', 'Quota annua del costo di un bene durevole, ripartito lungo la sua vita utile.'],
    ['Oneri finanziari', 'Interessi e altri costi sostenuti sui debiti verso banche e obbligazionisti.'],
    ['Utile netto', 'Ciò che resta dei ricavi dopo tutti i costi, gli interessi e le imposte.'],
    ['Voci non ricorrenti', 'Proventi o costi eccezionali, come plusvalenze o ristrutturazioni, che di norma non si ripetono.'],
  ],
  tf: [
    ['L’EBIT si ottiene sottraendo dall’EBITDA ammortamenti e svalutazioni.', true, 'È la differenza tra le due misure: l’EBIT tiene conto dell’usura dei beni durevoli, l’EBITDA no.'],
    ['L’EBITDA è una misura definita in modo uniforme dai principi IFRS.', false, 'È un indicatore alternativo di performance: ogni società lo calcola a modo suo, per questo va letta la definizione adottata.'],
    ['Un EBITDA positivo significa che l’azienda sta generando cassa.', false, 'L’EBITDA ignora investimenti, circolante, interessi e imposte: un’azienda può avere EBITDA positivo e bruciare cassa.'],
    ['Un ricavo registrato nel conto economico può non essere ancora stato incassato.', true, 'Per competenza la vendita si registra quando avviene; se il cliente paga a 90 giorni, nel frattempo resta un credito.'],
    ['L’ammortamento è un costo che, di per sé, non comporta un’uscita di cassa.', true, 'La cassa è uscita quando il bene è stato acquistato; l’ammortamento ne distribuisce il costo negli anni di utilizzo.'],
    ['Se i ricavi crescono, anche l’utile netto cresce necessariamente.', false, 'Se i costi crescono più dei ricavi, o aumentano interessi e imposte, l’utile può scendere anche con un fatturato in crescita.'],
    ['Gli oneri finanziari si sottraggono dopo l’EBIT, non prima.', true, 'L’EBIT misura la gestione operativa; gli interessi dipendono da come l’azienda è finanziata e vengono dopo.'],
    ['Una plusvalenza dalla vendita di un immobile indica che il business principale sta migliorando.', false, 'È un provento una tantum, estraneo all’attività tipica: gonfia l’utile di un anno senza dire nulla sulla gestione ricorrente.'],
    ['Due aziende con lo stesso EBITDA possono avere utili netti molto diversi.', true, 'Ammortamenti, debiti e tassazione diversi cambiano il risultato finale anche partendo dallo stesso EBITDA.'],
    ['Le imposte nel conto economico coincidono sempre con quanto versato al fisco nell’anno.', false, 'Le imposte seguono la competenza: acconti, saldi e imposte differite fanno sì che il pagamento effettivo possa differire.'],
  ],
  mcq: [
    { q: 'Alfa Spa ha ricavi 500, costi operativi 380 e ammortamenti 40. Quanto vale l’EBIT?', a: '80', w: ['120', '460', '40'], e: 'EBITDA = 500 − 380 = 120; EBIT = 120 − 40 = 80. Il valore 120 è l’EBITDA, non l’EBIT.' },
    { q: 'Che cosa misura principalmente l’EBITDA?', a: 'Il risultato operativo prima degli ammortamenti', w: ['La cassa rimasta in azienda a fine anno', 'L’utile che resta agli azionisti', 'Il valore di mercato dell’intera azienda'], e: 'L’EBITDA guarda alla gestione tipica prima di ammortamenti, interessi e imposte: non è cassa né utile netto.' },
    { q: 'Quale voce si trova tra l’EBIT e l’utile ante imposte?', a: 'Gli oneri finanziari', w: ['Gli ammortamenti', 'Il costo del venduto', 'Le imposte sul reddito'], e: 'Dall’EBIT si sottraggono gli oneri finanziari netti per arrivare all’utile ante imposte; le imposte vengono dopo.' },
    { q: 'Beta Spa riporta un utile netto in forte aumento grazie alla vendita della sede storica. Come leggi il dato?', a: 'Separo la plusvalenza dall’utile ricorrente', w: ['Concludo che il business tipico è migliorato', 'Considero l’utile ripetibile anche in futuro', 'Guardo solo la crescita dell’utile netto'], e: 'La plusvalenza è non ricorrente: per giudicare la gestione tipica va esclusa, sapendo che l’anno dopo non si ripeterà.' },
    { q: 'Perché in un’azienda con molti impianti si guarda l’EBIT oltre all’EBITDA?', a: 'Perché tiene conto dell’usura degli impianti', w: ['Perché esclude il costo di tutto il personale', 'Perché include già le imposte dell’esercizio', 'Perché esclude i ricavi non ancora incassati'], e: 'L’EBIT sottrae gli ammortamenti: dove gli impianti pesano molto, l’EBITDA rischia di dare un’immagine troppo ottimista.' },
    { q: 'Quale affermazione sull’EBITDA è un errore comune?', a: 'Coincide con la cassa generata', w: ['Esclude gli ammortamenti', 'Non è definito dagli IFRS', 'Precede l’EBIT nel prospetto'], e: 'L’EBITDA non considera investimenti, circolante, interessi e imposte: per la cassa serve il rendiconto finanziario.' },
    { q: 'Delta Srl ha ricavi 300 e costo del venduto 180. Quanto vale il margine lordo?', a: '120', w: ['480', '180', '60'], e: 'Margine lordo = ricavi − costo del venduto = 300 − 180 = 120: ciò che resta per coprire spese commerciali, generali e il resto.' },
    { q: 'Una società ha EBITDA in crescita ma utile netto in calo. Quale causa è plausibile?', a: 'Interessi sul debito in forte aumento', w: ['Ricavi in crescita a costi stabili', 'Costi operativi in calo sui ricavi', 'Prezzi di vendita più alti a pari costi'], e: 'Sotto l’EBITDA ci sono ammortamenti, oneri finanziari e imposte: se crescono, l’utile netto può scendere anche con EBITDA in aumento.' },
  ],
  fill: [
    { s: 'L’EBITDA in italiano è chiamato margine operativo ___.', a: 'lordo', w: ['netto', 'finale', 'corrente'] },
    { s: 'L’___ ripartisce il costo di un macchinario lungo gli anni della sua vita utile.', a: 'ammortamento', w: ['accantonamento', 'investimento', 'interesse'] },
    { s: 'Sottraendo all’EBIT gli oneri finanziari si ottiene l’utile ante ___.', a: 'imposte', w: ['ammortamenti', 'interessi', 'ricavi'] },
    { s: 'Le voci ___, come una plusvalenza una tantum, vanno separate per capire la redditività di fondo.', a: 'non ricorrenti', w: ['operative', 'ricorrenti', 'caratteristiche'] },
    { s: 'I ___ sono la prima riga del conto economico: il valore delle vendite del periodo.', a: 'ricavi', w: ['dividendi', 'ammortamenti', 'debiti'] },
  ],
  order: [
    { q: 'Ordina i risultati come compaiono scendendo nel conto economico', i: ['Ricavi', 'EBITDA', 'EBIT', 'Utile ante imposte', 'Utile netto'], e: 'Dai ricavi si tolgono i costi operativi (EBITDA), poi gli ammortamenti (EBIT), gli oneri finanziari e infine le imposte.' },
    { q: 'Ordina i costi nell’ordine in cui vengono sottratti dai ricavi', i: ['Costi operativi', 'Ammortamenti', 'Oneri finanziari', 'Imposte'], e: 'Prima i costi della gestione tipica, poi l’usura dei beni, poi il costo del debito; le imposte si calcolano sull’utile ante imposte.' },
  ],
  cat: [
    { q: 'Questo costo incide sull’EBITDA?', g: [['Sì, sta sopra l’EBITDA', ['Stipendi del personale', 'Materie prime', 'Bollette dell’energia', 'Costi di marketing']], ['No, sta sotto l’EBITDA', ['Ammortamento dei macchinari', 'Interessi sui finanziamenti', 'Imposte sul reddito', 'Svalutazione dell’avviamento']]] },
    { q: 'Voce ricorrente o non ricorrente?', g: [['Ricorrente', ['Vendite ai clienti abituali', 'Stipendi mensili', 'Abbonamenti dei clienti']], ['Non ricorrente', ['Plusvalenza dalla vendita della sede', 'Costi di una ristrutturazione aziendale', 'Risarcimento per una causa legale']]] },
  ],
  scen: [
    { s: 'Chiara, 31 anni, confronta Alfa Spa e Beta Spa: entrambe hanno un EBITDA di 100 milioni. Un forum sostiene che sono equivalenti. Scendendo nel conto economico vede che Alfa ha un utile netto di 50, Beta di 10.', q: 'Cosa fa Chiara?', o: [
      { t: 'Le considera equivalenti, visto che l’EBITDA è identico', ok: false, f: 'L’EBITDA si ferma prima di ammortamenti, interessi e imposte: proprio lì le due aziende si separano.' },
      { t: 'Cerca le voci sotto l’EBITDA che spiegano la differenza', ok: true, f: 'Esatto: ammortamenti più alti o un forte debito con molti interessi possono spiegare il divario. Capirne la causa è il punto.' },
      { t: 'Preferisce Beta, perché un utile basso paga meno imposte', ok: false, f: 'Pagare meno imposte perché si guadagna meno non è un vantaggio: conta quanto resta agli azionisti.' },
    ] },
    { s: 'Paolo, 47 anni, legge che Gamma Spa presenta un «EBITDA rettificato» in crescita del 20%, mentre l’EBITDA riportato cala. Le rettifiche escludono costi definiti eccezionali, ma compaiono ogni anno da cinque anni.', q: 'Come valuta il dato?', o: [
      { t: 'Si fida del dato rettificato, che è quello scelto dall’azienda', ok: false, f: 'Le rettifiche le decide il management: se i costi «eccezionali» si ripetono ogni anno, sono di fatto costi normali.' },
      { t: 'Guarda entrambi e tratta come ricorrenti i costi che si ripetono', ok: true, f: 'Un costo presente ogni anno fa parte del business: il dato riportato, con le note, racconta una storia più fedele.' },
      { t: 'Ignora ogni EBITDA e guarda solo il prezzo del titolo', ok: false, f: 'Il prezzo non dice se i conti sono solidi: meglio leggere i numeri con spirito critico che smettere di leggerli.' },
    ] },
    { s: 'Elena, 39 anni, confronta Delta Spa, acciaieria con EBITDA 200 e ammortamenti 150, con Zeta Spa, società di servizi con EBITDA 180 e ammortamenti 20. Un amico dice che Delta è più redditizia.', q: 'Come ragiona Elena?', o: [
      { t: 'Dà ragione all’amico: 200 è più di 180', ok: false, f: 'Fermarsi all’EBITDA ignora l’usura degli impianti, che per un’acciaieria è un costo reale e pesante.' },
      { t: 'Considera l’EBITDA irrilevante in ogni caso', ok: false, f: 'L’EBITDA è utile per alcuni confronti; il problema è usarlo da solo in aziende con investimenti molto diversi.' },
      { t: 'Confronta l’EBIT: 50 per Delta contro 160 per Zeta', ok: true, f: 'Dopo gli ammortamenti il quadro si ribalta: Zeta genera molto più risultato operativo per i suoi azionisti.' },
    ] },
    { s: 'Andrea, 25 anni, nota che i ricavi di Theta Spa sono cresciuti del 30%, ma l’utile netto è sceso. Nelle note scopre forti sconti ai clienti e costi di consegna in aumento più veloce delle vendite.', q: 'Qual è la conclusione più ragionevole?', o: [
      { t: 'La crescita dei ricavi basta: l’utile arriverà da solo', ok: false, f: 'Crescere vendendo in perdita non crea valore: se i costi corrono più dei ricavi, più vendite possono voler dire più perdite.' },
      { t: 'La crescita sta costando troppo e va monitorata', ok: true, f: 'Ricavi su e utile giù segnalano che i costi crescono più in fretta: va capito se è temporaneo o un problema strutturale.' },
      { t: 'L’utile in calo è solo un errore contabile', ok: false, f: 'Sconti e costi di consegna sono costi reali descritti nelle note: non c’è motivo di pensare a un errore.' },
    ] },
  ],
  tip: 'Leggi il conto economico dall’alto verso il basso e chiediti a ogni gradino cosa si perde: spesso la storia vera sta tra l’EBITDA e l’utile netto.',
});
