FQC(53, {
  intro: 'Cosa possiede un’azienda, cosa deve e cosa resta ai soci: impara a leggere lo stato patrimoniale e la sua equazione fondamentale.',
  cards: [
    { t: 'L’equazione di base', x: 'Tutto ciò che l’azienda possiede è stato finanziato da terzi, con le passività, oppure dai soci, con il patrimonio netto. Per questo i due lati dello stato patrimoniale sono sempre in equilibrio.', v: { k: 'formula', f: 'Attivo = Passività + Patrimonio netto', n: 'Es. Alfa Spa: 1.000 = 600 + 400 milioni' } },
    { t: 'Di cosa è fatto l’attivo', x: 'L’attivo di Alfa Spa: impianti e immobili, marchi e avviamento, poi magazzino, crediti verso clienti e liquidità. Le prime voci restano in azienda per anni, le altre ruotano entro dodici mesi.', v: { k: 'pie', d: [['Immobilizzazioni materiali', 40], ['Immateriali e avviamento', 20], ['Magazzino', 15], ['Crediti commerciali', 15], ['Liquidità', 10]] } },
    { t: 'Corrente o non corrente', x: 'L’attivo non corrente comprende beni usati per più esercizi, come impianti e brevetti. L’attivo corrente comprende magazzino, crediti e liquidità, che ruotano entro circa un anno. La stessa distinzione vale per le passività.', v: { k: 'vs', a: ['Non corrente', 'Resta in azienda per anni'], b: ['Corrente', 'Ruota entro 12 mesi'] } },
    { t: 'Chi ha finanziato l’attivo', x: 'Il passivo di Alfa Spa mostra le fonti: banche e obbligazionisti con i debiti finanziari, fornitori che aspettano di essere pagati, fondi per obblighi futuri come il TFR e, infine, i soci con il patrimonio netto.', v: { k: 'bars', d: [['Debiti finanziari', 350], ['Debiti v. fornitori', 150], ['Fondi e altre', 100], ['Patrimonio netto', 400]], u: 'mln €' } },
    { t: 'Il patrimonio netto', x: 'È ciò che resterebbe ai soci se l’attivo valesse esattamente quanto scritto in bilancio e tutti i debiti fossero pagati. Comprende il capitale versato, le riserve e gli utili trattenuti negli anni.', v: { k: 'icons', d: [['🏛️', 'Capitale sociale'], ['🧱', 'Riserve e utili a nuovo'], ['📈', 'Utile dell’esercizio']] } },
    { t: 'Valori contabili, non prezzi', x: 'Molte voci sono iscritte con regole contabili, spesso al costo storico, e non coincidono con quanto varrebbero sul mercato. La liquidità è certa; l’avviamento è la voce più soggettiva e può essere svalutato.', v: { k: 'scale', a: 'Valore certo', b: 'Valore stimato', d: [['Liquidità', 5], ['Crediti', 25], ['Magazzino', 50], ['Impianti', 65], ['Avviamento', 90]] } },
  ],
  terms: [
    ['Attivo', 'Insieme di beni e diritti dell’azienda: impianti, marchi, magazzino, crediti e liquidità.'],
    ['Passività', 'Obblighi verso terzi: debiti finanziari, debiti verso fornitori, fondi e altri impegni.'],
    ['Patrimonio netto', 'Differenza tra attivo e passività: la parte dell’azienda che spetta ai soci.'],
    ['Avviamento', 'Eccedenza del prezzo pagato per un’acquisizione sul valore equo delle attività nette acquisite.'],
    ['Immobilizzazioni', 'Beni destinati a restare in azienda per più esercizi, come impianti, immobili e brevetti.'],
    ['Capitale circolante netto', 'Attività correnti meno passività correnti: le risorse che ruotano nel ciclo operativo.'],
    ['Impairment test', 'Verifica che il valore di bilancio di un’attività, come l’avviamento, sia ancora recuperabile.'],
    ['Utili a nuovo', 'Utili degli esercizi passati non distribuiti e lasciati nel patrimonio netto.'],
  ],
  tf: [
    ['Il totale dell’attivo è sempre uguale alla somma di passività e patrimonio netto.', true, 'È l’equazione contabile: ogni bene è finanziato da terzi o dai soci, quindi i due lati del prospetto si bilanciano.'],
    ['Il patrimonio netto è la cassa che l’azienda tiene in banca.', false, 'Il patrimonio netto è una fonte di finanziamento, non un bene: la cassa sta nell’attivo, tra le attività correnti.'],
    ['Il patrimonio netto di un’azienda può diventare negativo.', true, 'Se le perdite accumulate superano capitale e riserve, le passività superano l’attivo: è un serio segnale di squilibrio.'],
    ['Il valore contabile di un’azienda coincide con il suo valore in borsa.', false, 'Il bilancio usa regole contabili, spesso al costo storico; la borsa prezza le prospettive future. Di solito i due valori divergono.'],
    ['I crediti verso clienti sono un’attività dell’azienda.', true, 'Sono somme che i clienti devono ancora pagare: un diritto a incassare denaro, quindi una voce dell’attivo corrente.'],
    ['Un prestito bancario da rimborsare in un’unica soluzione tra cinque anni è una passività corrente.', false, 'Le passività correnti scadono entro circa dodici mesi: un prestito con rimborso tra cinque anni è una passività non corrente.'],
    ['L’avviamento nasce di solito quando si acquista un’azienda pagando più del valore delle sue attività nette.', true, 'L’eccedenza pagata per marchio, clienti e sinergie è iscritta come avviamento e sottoposta ogni anno a impairment test.'],
    ['Un magazzino in forte crescita è sempre un buon segno.', false, 'Può preparare vendite future, ma anche indicare merce invenduta che rischia di perdere valore: va confrontato con i ricavi.'],
    ['Una svalutazione dell’avviamento riduce il patrimonio netto.', true, 'La svalutazione è un costo che abbassa l’utile e quindi le riserve: attivo e patrimonio netto scendono insieme.'],
    ['Le immobilizzazioni immateriali, come i marchi, non compaiono mai nello stato patrimoniale.', false, 'Marchi, brevetti e software acquistati sono iscritti tra le immobilizzazioni immateriali; i marchi creati internamente spesso no.'],
  ],
  mcq: [
    { q: 'Alfa Spa ha un attivo di 800 e passività per 500. Quanto vale il patrimonio netto?', a: '300', w: ['1.300', '500', '800'], e: 'Patrimonio netto = attivo − passività = 800 − 500 = 300.' },
    { q: 'Quale di queste voci è un’attività corrente?', a: 'Crediti verso clienti', w: ['Impianti produttivi', 'Avviamento', 'Mutuo a dieci anni'], e: 'I crediti commerciali si incassano di norma entro un anno. Impianti e avviamento sono non correnti; il mutuo è una passività.' },
    { q: 'Dove si trovano gli utili degli anni passati non distribuiti?', a: 'Nel patrimonio netto', w: ['Nell’attivo corrente', 'Tra i debiti finanziari', 'Tra le immobilizzazioni'], e: 'Gli utili trattenuti alimentano le riserve del patrimonio netto: sono una fonte di finanziamento, non un bene.' },
    { q: 'Perché l’avviamento è considerato una voce delicata?', a: 'Il suo valore è stimato e può essere svalutato', w: ['È sempre pari alla cassa disponibile', 'Si trasforma in cassa entro dodici mesi', 'Non è soggetto ad alcun controllo annuale'], e: 'L’avviamento si basa su aspettative future: se un’acquisizione delude, l’impairment test può imporre una svalutazione.' },
    { q: 'Che cosa rappresenta il patrimonio netto?', a: 'Il valore contabile che spetta ai soci', w: ['Il valore di borsa dell’azienda', 'La liquidità presente in banca', 'Il totale dei debiti verso terzi'], e: 'È attivo meno passività: il valore contabile dei soci. Non è cassa e non coincide con la capitalizzazione di borsa.' },
    { q: 'Quale di queste convinzioni sullo stato patrimoniale è sbagliata?', a: 'Un attivo grande indica un’azienda sana', w: ['L’attivo è pari a passività più PN', 'I crediti commerciali sono attività', 'Il PN può anche diventare negativo'], e: 'Un attivo grande può essere finanziato quasi tutto a debito: conta come è composto e chi lo ha finanziato.' },
    { q: 'Beta Spa ha attività correnti per 300 e passività correnti per 200. Quanto vale il capitale circolante netto?', a: '100', w: ['500', '1,5', '−100'], e: 'CCN = attività correnti − passività correnti = 300 − 200 = 100. Il rapporto 300/200 = 1,5 è invece l’indice di liquidità corrente.' },
    { q: 'Una passività corrente è un obbligo che scade…', a: 'entro circa dodici mesi', w: ['tra due e cinque anni', 'oltre i cinque anni', 'solo in caso di liquidazione'], e: 'Le passività correnti, come i debiti verso fornitori o le rate a breve dei prestiti, vanno pagate entro un anno circa.' },
  ],
  fill: [
    { s: 'Attivo = passività + ___ netto.', a: 'patrimonio', w: ['utile', 'margine', 'flusso'] },
    { s: 'L’___ nasce quando si paga un’azienda più del valore delle sue attività nette.', a: 'avviamento', w: ['ammortamento', 'immobile', 'accantonamento'] },
    { s: 'Magazzino, crediti e liquidità fanno parte dell’attivo ___.', a: 'corrente', w: ['immobilizzato', 'immateriale', 'non corrente'] },
    { s: 'I debiti verso ___ nascono quando l’azienda acquista merci e le paga più avanti.', a: 'fornitori', w: ['clienti', 'soci', 'dipendenti'] },
    { s: 'Ogni anno l’avviamento è sottoposto a un ___ test per verificarne il valore.', a: 'impairment', w: ['stress', 'audit', 'rating'] },
  ],
  order: [
    { q: 'Ordina le attività dalla più liquida alla meno liquida', i: ['Cassa e depositi', 'Crediti verso clienti', 'Magazzino', 'Impianti', 'Avviamento'], e: 'La cassa è già denaro, i crediti si incassano a breve, il magazzino va prima venduto; impianti e avviamento restano per anni.' },
    { q: 'Ordina le passività dalla scadenza più vicina alla più lontana', i: ['Debito verso fornitori a 60 giorni', 'Rata del mutuo tra 9 mesi', 'Prestito bancario a 3 anni', 'Obbligazione a 10 anni'], e: 'Le prime due sono passività correnti perché scadono entro un anno; prestito e obbligazione sono passività non correnti.' },
  ],
  cat: [
    { q: 'Attivo o passivo?', g: [['Attivo', ['Crediti verso clienti', 'Magazzino', 'Brevetti acquistati', 'Liquidità in banca']], ['Passività e patrimonio netto', ['Debiti verso fornitori', 'Obbligazioni emesse', 'Fondo TFR', 'Capitale sociale']]] },
    { q: 'Corrente o non corrente?', g: [['Corrente (entro 12 mesi)', ['Crediti commerciali a 90 giorni', 'Scorte di materie prime', 'Fatture fornitori da pagare', 'Saldo del conto corrente']], ['Non corrente (oltre 12 mesi)', ['Capannone industriale', 'Software acquistato', 'Mutuo a 15 anni', 'Partecipazione in una controllata']]] },
  ],
  scen: [
    { s: 'Francesca, 36 anni, analizza Alfa Spa, cresciuta con molte acquisizioni. Scopre che l’avviamento vale il 60% dell’attivo ed è più alto dell’intero patrimonio netto.', q: 'Che conclusione trae?', o: [
      { t: 'Nessun problema: l’avviamento è un’attività come le altre', ok: false, f: 'L’avviamento è una stima basata su aspettative: non si vende da solo e non paga i debiti in caso di difficoltà.' },
      { t: 'Verifica come stanno andando le società acquisite', ok: true, f: 'Se le acquisizioni deludono, una svalutazione dell’avviamento può azzerare gran parte del patrimonio netto: va monitorato.' },
      { t: 'Considera l’avviamento come liquidità disponibile', ok: false, f: 'L’avviamento non è denaro: è la parte del prezzo pagato che eccede il valore delle attività nette acquisite.' },
    ] },
    { s: 'Roberto, 58 anni, nota che le azioni di Beta Spa salgono per le voci di un nuovo contratto. Il patrimonio netto è negativo dopo anni di perdite e un grosso debito scade entro l’anno.', q: 'Come si comporta?', o: [
      { t: 'Compra subito per non perdere il rialzo', ok: false, f: 'Inseguire una voce di mercato ignorando un patrimonio negativo e un debito in scadenza espone a perdite pesanti.' },
      { t: 'Ignora il patrimonio negativo: conta solo il contratto', ok: false, f: 'Con debiti superiori all’attivo e una scadenza vicina, il rischio di ricapitalizzazione o ristrutturazione è concreto.' },
      { t: 'Valuta con prudenza il rischio di un aumento di capitale', ok: true, f: 'Per rimettere in sesto i conti potrebbe servire un aumento di capitale che diluisce i soci attuali: va considerato prima di investire.' },
    ] },
    { s: 'Valentina, 29 anni, segue Gamma Spa, azienda di abbigliamento. In un anno il magazzino è raddoppiato, mentre i ricavi sono rimasti stabili.', q: 'Cosa ne pensa?', o: [
      { t: 'Lo approfondisce: la merce potrebbe restare invenduta', ok: true, f: 'Nella moda le scorte invecchiano in fretta: se non si vendono, servono sconti o svalutazioni che pesano sui conti futuri.' },
      { t: 'È positivo: più magazzino significa più attivo', ok: false, f: 'Un attivo più grande non è automaticamente un valore: merce che non si vende assorbe cassa e può perdere valore.' },
      { t: 'È irrilevante: il magazzino non influisce mai sugli utili', ok: false, f: 'Le scorte invendute possono essere svalutate, e la svalutazione è un costo che riduce l’utile.' },
    ] },
    { s: 'Stefano, 41 anni, legge che Delta Spa ha un patrimonio netto di 500 milioni e conclude che l’azienda ha 500 milioni in cassa pronti da distribuire agli azionisti.', q: 'Qual è la lettura corretta?', o: [
      { t: 'Ha ragione: il patrimonio netto è la cassa dei soci', ok: false, f: 'Il patrimonio netto sta tra le fonti, non tra gli impieghi: può essere investito in impianti, magazzino e altri beni.' },
      { t: 'Deve guardare la liquidità nell’attivo, voce distinta', ok: true, f: 'La cassa è una voce dell’attivo: il patrimonio netto dice chi ha finanziato i beni, non quanti soldi ci sono in banca.' },
      { t: 'Deve sottrarre i debiti dal patrimonio netto', ok: false, f: 'Il patrimonio netto è già al netto delle passività: sottrarre di nuovo i debiti significherebbe contarli due volte.' },
    ] },
  ],
  tip: 'Davanti a uno stato patrimoniale chiediti due cose: di cosa è fatto l’attivo e chi lo ha finanziato. Le risposte dicono molto sul rischio dell’azienda.',
});
