FQC(54, {
  intro: 'L’utile è un’opinione, la cassa è un fatto: scopri come leggere i flussi di cassa e perché il free cash flow conta così tanto.',
  cards: [
    { t: 'Tre aree di flussi', x: 'Il rendiconto finanziario divide la cassa in tre aree: quella generata dall’attività tipica, quella spesa o incassata con gli investimenti e quella legata a debiti, dividendi e capitale dei soci.', v: { k: 'icons', d: [['⚙️', 'Gestione operativa'], ['🏭', 'Investimenti'], ['🏦', 'Finanziamenti']] } },
    { t: 'Dall’utile alla cassa', x: 'Con il metodo indiretto si parte dall’utile netto, si riaggiungono i costi che non fanno uscire cassa, come gli ammortamenti, e si corregge per la variazione di crediti, magazzino e debiti verso fornitori.', v: { k: 'steps', s: ['Utile netto', '+ Ammortamenti', '− Aumento del circolante', '= Flusso operativo'] } },
    { t: 'Il free cash flow', x: 'Il free cash flow è la cassa che resta dopo aver pagato gli investimenti necessari all’attività. È il denaro con cui l’azienda può pagare dividendi, ridurre i debiti o riacquistare azioni proprie.', v: { k: 'formula', f: 'FCF = flusso di cassa operativo − capex', n: 'Es. Alfa Spa: 120 − 70 = 50 milioni' } },
    { t: 'Il caso Alfa Spa', x: 'Alfa Spa ha un utile netto di 90 milioni. Aggiungendo 60 di ammortamenti e togliendo 30 assorbiti dal circolante, il flusso operativo è 120. Dopo 70 di investimenti restano 50 di free cash flow.', v: { k: 'bars', d: [['Utile netto', 90], ['Flusso operativo', 120], ['Capex', -70], ['Free cash flow', 50]], u: 'mln €' } },
    { t: 'Utile e cassa possono divergere', x: 'Un’azienda che vende molto ma incassa tardi può avere utili alti e poca cassa. Se per anni l’utile resta molto sopra il flusso operativo, vale la pena capire dove si ferma il denaro.', v: { k: 'vs', a: ['Utile netto', 'Ricavi e costi maturati'], b: ['Flusso di cassa', 'Denaro entrato e uscito'] } },
    { t: 'Mantenere o crescere', x: 'Per Alfa Spa il 60% del capex sostituisce macchinari usurati, il 40% finanzia la crescita. Tagliare gli investimenti alza subito il free cash flow, ma ridurre anche quelli di mantenimento impoverisce l’azienda.', v: { k: 'pie', d: [['Capex di mantenimento', 60], ['Capex di sviluppo', 40]] } },
  ],
  terms: [
    ['Rendiconto finanziario', 'Prospetto che mostra entrate e uscite di cassa del periodo, divise in tre aree.'],
    ['Flusso di cassa operativo', 'Cassa generata dall’attività tipica, tenuto conto della variazione del circolante.'],
    ['Capex', 'Spese per acquistare o migliorare beni durevoli come impianti, macchinari e software.'],
    ['Free cash flow', 'Cassa che resta dopo gli investimenti: disponibile per dividendi, debiti e buyback.'],
    ['Metodo indiretto', 'Modo di calcolare il flusso operativo partendo dall’utile netto e rettificandolo.'],
    ['Flusso da finanziamenti', 'Movimenti di cassa legati a prestiti, rimborsi, dividendi, aumenti di capitale e buyback.'],
    ['Cash conversion', 'Quanta parte dell’utile si trasforma in cassa, ad esempio free cash flow diviso utile netto.'],
    ['Cash burn', 'Ritmo con cui un’azienda con flussi negativi consuma la liquidità disponibile.'],
  ],
  tf: [
    ['Il free cash flow si ottiene sottraendo gli investimenti dal flusso di cassa operativo.', true, 'È la definizione più usata: cassa generata dall’attività meno quella spesa per mantenere e sviluppare gli impianti.'],
    ['Con il metodo indiretto gli ammortamenti si sommano all’utile per calcolare il flusso operativo.', true, 'Sono costi che riducono l’utile senza far uscire cassa nel periodo, quindi vanno riaggiunti.'],
    ['Un aumento dei crediti verso clienti fa aumentare la cassa.', false, 'Se i crediti salgono, l’azienda ha venduto senza ancora incassare: quel denaro è ancora nelle tasche dei clienti.'],
    ['Il pagamento di un dividendo compare nel flusso da investimenti.', false, 'I dividendi pagati remunerano i soci: si classificano di norma tra i flussi da finanziamenti, non tra gli investimenti.'],
    ['Un free cash flow negativo è sempre un segnale di crisi.', false, 'Può dipendere da forti investimenti per crescere. Diventa preoccupante se persiste senza che gli investimenti producano risultati.'],
    ['Un’azienda può avere utile netto positivo e flusso di cassa operativo negativo.', true, 'Succede se crediti e magazzino crescono molto: le vendite sono registrate, ma il denaro non è ancora entrato.'],
    ['Ottenere un nuovo finanziamento bancario aumenta il free cash flow.', false, 'Il prestito entra nel flusso da finanziamenti: aumenta la cassa, non il free cash flow, che dipende da gestione e investimenti.'],
    ['Ritardare i pagamenti ai fornitori può migliorare temporaneamente il flusso operativo.', true, 'Più debiti verso fornitori significa trattenere cassa più a lungo, ma è un effetto che non si può ripetere all’infinito.'],
    ['La vendita di un impianto genera un’entrata nel flusso da investimenti.', true, 'Acquisti e cessioni di beni durevoli stanno nel flusso da investimenti: una vendita genera un’entrata in quest’area.'],
    ['Se l’EBITDA cresce, anche il free cash flow cresce di sicuro.', false, 'Tra EBITDA e free cash flow ci sono imposte, circolante e capex: se questi aumentano, il FCF può anche calare.'],
  ],
  mcq: [
    { q: 'Beta Spa ha un flusso operativo di 200 e capex per 80. Quanto vale il free cash flow?', a: '120', w: ['280', '80', '200'], e: 'FCF = flusso operativo − capex = 200 − 80 = 120.' },
    { q: 'In quale area del rendiconto compare l’acquisto di un nuovo macchinario?', a: 'Flusso da investimenti', w: ['Flusso operativo', 'Flusso da finanziamenti', 'Variazione del circolante'], e: 'L’acquisto di beni durevoli è capex: compare nel flusso da investimenti, con segno negativo.' },
    { q: 'Con il metodo indiretto, che effetto ha sul flusso operativo un aumento del magazzino?', a: 'Lo riduce, perché assorbe cassa', w: ['Lo aumenta, perché cresce l’attivo', 'Nessuno, è solo una voce contabile', 'Lo aumenta, perché è un ricavo'], e: 'Comprare merce che resta in magazzino immobilizza denaro: nel rendiconto l’aumento delle scorte si sottrae.' },
    { q: 'Un’azienda chiude l’anno con 50 di utile netto e −20 di flusso operativo. Qual è la causa più probabile?', a: 'Forte crescita di crediti e magazzino', w: ['Ammortamenti molto elevati nell’anno', 'Un dividendo straordinario ai soci', 'Un nuovo prestito bancario a lungo'], e: 'Crediti e scorte in aumento assorbono cassa. Gli ammortamenti si riaggiungono; dividendi e prestiti stanno nei finanziamenti.' },
    { q: 'Quale di queste idee sul free cash flow è un errore comune?', a: 'Un FCF negativo è sempre una crisi', w: ['Il FCF tiene conto del capex', 'Il FCF può finanziare i dividendi', 'Il FCF parte dal flusso operativo'], e: 'Un FCF negativo può riflettere investimenti per crescere: va valutato insieme ai risultati che quegli investimenti producono.' },
    { q: 'Perché molti analisti guardano il free cash flow oltre all’utile?', a: 'Dipende meno dalle stime contabili', w: ['È sempre più alto dell’utile netto', 'Non dipende dagli investimenti', 'Lo stabilisce l’assemblea dei soci'], e: 'L’utile dipende da stime e criteri di competenza; il free cash flow misura denaro realmente entrato e uscito.' },
    { q: 'Quale di queste operazioni compare nel flusso da finanziamenti?', a: 'Il riacquisto di azioni proprie', w: ['L’acquisto di un capannone', 'L’incasso da un cliente', 'Il pagamento dei fornitori'], e: 'Buyback, dividendi, nuovi prestiti e rimborsi riguardano soci e finanziatori: sono flussi da finanziamenti.' },
    { q: 'Gamma Spa ha un FCF positivo solo perché ha tagliato quasi tutti gli investimenti, anche di manutenzione. Come lo interpreti?', a: 'Un miglioramento poco sostenibile', w: ['Un segnale di forte crescita', 'Un aumento stabile della redditività', 'Un effetto del nuovo debito'], e: 'Senza manutenzione gli impianti invecchiano: il FCF sale oggi, ma quegli investimenti andranno recuperati più avanti.' },
  ],
  fill: [
    { s: 'Il free cash flow è il flusso operativo meno il ___.', a: 'capex', w: ['dividendo', 'debito', 'fatturato'] },
    { s: 'Nel metodo indiretto gli ___ si riaggiungono all’utile perché non fanno uscire cassa.', a: 'ammortamenti', w: ['incassi', 'investimenti', 'interessi'] },
    { s: 'I dividendi pagati compaiono di norma nel flusso da ___.', a: 'finanziamenti', w: ['investimenti', 'ricavi', 'ammortamenti'] },
    { s: 'Un aumento dei crediti verso clienti ___ la cassa generata nel periodo.', a: 'riduce', w: ['aumenta', 'raddoppia', 'non tocca'] },
    { s: 'L’acquisto di un nuovo impianto compare nel flusso da ___.', a: 'investimenti', w: ['finanziamenti', 'dividendi', 'ricavi'] },
  ],
  order: [
    { q: 'Ordina i passaggi per arrivare al free cash flow', i: ['Partire dall’utile netto', 'Riaggiungere gli ammortamenti', 'Sottrarre l’aumento del circolante', 'Ottenere il flusso operativo', 'Sottrarre il capex'], e: 'Dall’utile si passa al flusso operativo con le rettifiche non monetarie e del circolante; togliendo il capex si arriva al FCF.' },
    { q: 'Ordina le sezioni come appaiono nel rendiconto finanziario', i: ['Flusso operativo', 'Flusso da investimenti', 'Flusso da finanziamenti', 'Variazione netta della cassa'], e: 'Le tre aree si sommano e danno la variazione della cassa, che riconcilia la liquidità di inizio e di fine periodo.' },
  ],
  cat: [
    { q: 'In quale area del rendiconto finanziario?', g: [['Investimenti', ['Acquisto di macchinari', 'Vendita di un capannone', 'Acquisizione di una società']], ['Finanziamenti', ['Nuovo prestito bancario', 'Pagamento di dividendi', 'Riacquisto di azioni proprie', 'Rimborso di un’obbligazione']]] },
    { q: 'Metodo indiretto: si somma o si sottrae all’utile?', g: [['Si somma', ['Ammortamenti dell’anno', 'Calo del magazzino', 'Aumento dei debiti verso fornitori']], ['Si sottrae', ['Aumento dei crediti verso clienti', 'Aumento delle scorte', 'Calo dei debiti verso fornitori']]] },
  ],
  scen: [
    { s: 'Martina, 33 anni, segue Alfa Spa: l’utile netto cresce da tre anni, ma il flusso di cassa operativo è negativo ogni anno. I crediti verso clienti crescono molto più dei ricavi.', q: 'Cosa fa Martina?', o: [
      { t: 'Si fida dell’utile in crescita e non approfondisce', ok: false, f: 'Un utile che non diventa mai cassa è un segnale classico di bassa qualità degli utili: va spiegato.' },
      { t: 'Indaga sui crediti: i clienti pagano davvero?', ok: true, f: 'Crediti che corrono più dei ricavi possono indicare clienti in difficoltà o vendite troppo generose: un rischio di perdite future.' },
      { t: 'Conclude che il rendiconto contiene un errore', ok: false, f: 'Utile e cassa divergono per motivi precisi, come qui i crediti: non c’è motivo di pensare a un errore.' },
    ] },
    { s: 'Giorgio, 60 anni, cerca azioni che paghino dividendi. Beta Spa offre un dividendo generoso, ma da quattro anni il dividendo supera il free cash flow e il debito cresce ogni anno.', q: 'Come valuta Giorgio quel dividendo?', o: [
      { t: 'Lo considera sicuro, visto che è pagato da anni', ok: false, f: 'Pagare dividendi a debito può durare un po’, non per sempre: lo storico non garantisce il futuro.' },
      { t: 'Lo considera fragile e a rischio di taglio', ok: true, f: 'Un dividendo non coperto dal free cash flow e finanziato con debito è fragile: un taglio futuro è una possibilità concreta.' },
      { t: 'Pensa che il debito non conti, conta solo il dividendo', ok: false, f: 'Il debito crescente erode la solidità dell’azienda e, prima o poi, la sua capacità di pagare i soci.' },
    ] },
    { s: 'Ilaria, 27 anni, analizza Gamma Spa: il flusso operativo è positivo e in crescita, ma il free cash flow è negativo perché l’azienda sta costruendo due nuovi stabilimenti.', q: 'Qual è la lettura più equilibrata?', o: [
      { t: 'Vende subito: un FCF negativo è un segnale di crisi', ok: false, f: 'Qui il FCF è negativo per scelta di investimento, non per una gestione che perde cassa.' },
      { t: 'Ignora il FCF: conta solo il flusso operativo', ok: false, f: 'Gli investimenti sono denaro reale che esce: vanno considerati, chiedendosi se renderanno abbastanza.' },
      { t: 'Valuta se i nuovi impianti potranno rendere abbastanza', ok: true, f: 'Un FCF negativo da investimenti è accettabile se i progetti creano valore: conta il ritorno atteso e come sono finanziati.' },
    ] },
    { s: 'Davide, 44 anni, nota che il free cash flow di Delta Spa è salito del 40% in un anno. Leggendo il rendiconto scopre che i debiti verso fornitori sono aumentati molto, mentre ricavi e margini sono stabili.', q: 'Come interpreta il balzo?', o: [
      { t: 'Una crescita stabile della capacità di generare cassa', ok: false, f: 'Ricavi e margini sono fermi: il miglioramento non viene dal business, ma dai tempi di pagamento.' },
      { t: 'Un effetto in parte temporaneo, da non proiettare nel futuro', ok: true, f: 'Pagare i fornitori più tardi libera cassa una volta sola; se poi i tempi si normalizzano, il flusso torna indietro.' },
      { t: 'Un segnale che i fornitori finanzieranno l’azienda per sempre', ok: false, f: 'I fornitori possono chiedere di tornare ai tempi normali o cambiare condizioni: non è una fonte stabile di cassa.' },
    ] },
  ],
  tip: 'Confronta sempre per più anni l’utile netto con il flusso di cassa operativo: se l’utile cresce e la cassa no, prima di investire cerca il perché.',
});
