FQC(55, {
  intro: 'Quanto utile spetta a ogni azione e quanto lo paghi in borsa? Impara a calcolare l’EPS e a leggere il P/E senza cadere nelle sue trappole.',
  cards: [
    { t: 'L’utile per azione', x: 'L’EPS (earnings per share) dice quanta parte dell’utile spetta a ciascuna azione. Si usa il numero medio di azioni in circolazione nel periodo, escluse le azioni proprie detenute dalla società.', v: { k: 'formula', f: 'EPS = utile netto ÷ numero medio di azioni', n: 'Es. Alfa Spa: 50 mln € ÷ 100 mln di azioni = 0,50 €' } },
    { t: 'Il rapporto P/E', x: 'Il P/E (prezzo/utili) indica quante volte il mercato paga l’utile annuo per azione. Equivale a capitalizzazione divisa per utile netto: con un P/E di 20 paghi 20 euro per ogni euro di utile annuo.', v: { k: 'stat', n: '20x', l: 'P/E di Alfa Spa: prezzo 10 € ÷ EPS 0,50 €' } },
    { t: 'Trailing o forward', x: 'Il P/E trailing usa gli utili degli ultimi dodici mesi: dati certi, ma passati. Il P/E forward usa le stime degli analisti per i prossimi dodici mesi: guarda avanti, ma le stime possono rivelarsi sbagliate.', v: { k: 'vs', a: ['P/E trailing', 'Utili già realizzati'], b: ['P/E forward', 'Utili stimati'] } },
    { t: 'Cosa racconta un P/E', x: 'Un P/E alto indica che il mercato si aspetta una forte crescita degli utili, oppure che il titolo è caro. Un P/E basso può segnalare un’occasione, ma anche problemi che il mercato ha già visto.', v: { k: 'scale', a: 'Aspettative basse', b: 'Aspettative alte', d: [['P/E 6', 12], ['P/E 15', 40], ['P/E 30', 72], ['P/E 60', 95]] } },
    { t: 'Confronta con chi è simile', x: 'Il P/E ha senso soprattutto nel confronto con aziende dello stesso settore e con la storia del titolo. Paragonare il P/E di una banca con quello di una società di software dice molto poco.', v: { k: 'bars', d: [['Alfa Spa', 20], ['Beta Spa', 12], ['Gamma Spa', 15], ['Media settore', 16]], u: 'x' } },
    { t: 'Attenti alla diluizione', x: 'Stock option, warrant e obbligazioni convertibili possono creare nuove azioni. L’EPS diluito tiene conto di questo effetto: se è molto più basso dell’EPS base, gli azionisti attuali rischiano di essere diluiti.', v: { k: 'icons', d: [['📜', 'Stock option'], ['🎟️', 'Warrant'], ['🔄', 'Obbligazioni convertibili']] } },
  ],
  terms: [
    ['EPS', 'Utile netto attribuibile agli azionisti diviso il numero medio di azioni in circolazione.'],
    ['EPS diluito', 'Utile per azione che include le azioni potenziali derivanti da opzioni e convertibili.'],
    ['P/E', 'Rapporto tra prezzo dell’azione e utile per azione: quante volte si paga l’utile annuo.'],
    ['Earnings yield', 'Inverso del P/E: utile per azione diviso prezzo, espresso in percentuale.'],
    ['P/E forward', 'Rapporto calcolato sugli utili attesi dagli analisti per i prossimi dodici mesi.'],
    ['PEG', 'P/E diviso il tasso di crescita annua atteso degli utili, espresso in punti percentuali.'],
    ['Value trap', 'Titolo che sembra a sconto per il P/E basso, ma i cui utili sono destinati a scendere.'],
    ['Utili ciclici', 'Utili che salgono e scendono con il ciclo economico, come in auto, acciaio e chimica.'],
  ],
  tf: [
    ['Il P/E si può calcolare anche dividendo la capitalizzazione di borsa per l’utile netto.', true, 'Moltiplicando prezzo ed EPS per il numero di azioni si ottengono capitalizzazione e utile netto: il rapporto non cambia.'],
    ['Un P/E basso significa sempre che il titolo è un affare.', false, 'Il mercato può già prezzare un calo atteso degli utili: un P/E basso può nascondere una value trap.'],
    ['Un riacquisto di azioni proprie può far salire l’EPS anche se l’utile netto resta invariato.', true, 'Con meno azioni in circolazione, lo stesso utile si divide su meno quote: l’EPS cresce senza che il business migliori.'],
    ['Se un’azienda è in perdita, il P/E è un indicatore molto affidabile.', false, 'Con utili negativi il P/E non è significativo: si usano altri indicatori, ad esempio basati su ricavi o flussi di cassa.'],
    ['Un P/E di 25 corrisponde a un earnings yield del 4%.', true, 'L’earnings yield è l’inverso del P/E: 1 ÷ 25 = 0,04, cioè il 4%.'],
    ['Nei titoli ciclici, un P/E molto basso al picco del ciclo può essere un segnale ingannevole.', true, 'Al picco gli utili sono gonfiati: il P/E sembra basso proprio quando gli utili stanno per scendere.'],
    ['L’EPS diluito è di norma maggiore o uguale all’EPS base.', false, 'L’EPS diluito aggiunge azioni potenziali al denominatore, quindi è minore o uguale all’EPS base.'],
    ['Confrontare il P/E di aziende di settori molto diversi è sempre corretto.', false, 'Crescita, rischio e ciclicità cambiano molto tra settori: il P/E va confrontato soprattutto con aziende simili.'],
    ['Il P/E forward si basa su utili stimati, che possono rivelarsi sbagliati.', true, 'Le stime degli analisti sono previsioni: se gli utili deludono, un P/E forward che sembrava basso si rivela più alto.'],
    ['Un utile gonfiato da una plusvalenza una tantum fa sembrare il P/E più alto del dovuto.', false, 'Un utile gonfiato abbassa il P/E: il titolo sembra più conveniente di quanto sia. Meglio usare l’utile ricorrente.'],
  ],
  mcq: [
    { q: 'Beta Spa ha un utile netto di 30 milioni e 60 milioni di azioni. Qual è l’EPS?', a: '0,50 €', w: ['2,00 €', '0,20 €', '30,00 €'], e: 'EPS = 30 milioni ÷ 60 milioni di azioni = 0,50 € per azione.' },
    { q: 'Un’azione costa 18 € e l’EPS è 1,20 €. Qual è il P/E?', a: '15', w: ['21,6', '12', '18'], e: 'P/E = 18 ÷ 1,20 = 15: il mercato paga 15 volte l’utile annuo per azione.' },
    { q: 'Che cosa misura il PEG?', a: 'Il P/E rispetto alla crescita attesa degli utili', w: ['Il P/E rispetto al dividendo distribuito', 'Il prezzo rispetto al patrimonio netto', 'L’utile netto rispetto ai ricavi'], e: 'PEG = P/E ÷ crescita % attesa degli utili: un P/E alto è più giustificabile se la crescita attesa è forte.' },
    { q: 'Gamma Spa ha un P/E di 6, molto sotto la media del settore. Qual è la mossa più prudente?', a: 'Capire perché il mercato teme un calo degli utili', w: ['Considerarlo subito un titolo sottovalutato', 'Concludere che gli utili cresceranno molto', 'Pensare che tutto il settore sia sopravvalutato'], e: 'Un P/E molto basso può riflettere rischi già noti al mercato: prima di vederci un’occasione, serve capirne la causa.' },
    { q: 'Con il 10% di azioni in meno dopo un buyback e lo stesso utile netto, come cambia l’EPS?', a: 'Aumenta di circa l’11%', w: ['Resta invariato', 'Diminuisce del 10%', 'Aumenta esattamente del 10%'], e: 'Con il 90% delle azioni, l’EPS diventa 1 ÷ 0,9 ≈ 1,11 volte quello iniziale: circa +11%, a parità di utile.' },
    { q: 'Quale di queste convinzioni sul P/E è un errore comune?', a: 'Più è basso, più il titolo è conveniente', w: ['Va confrontato con aziende simili', 'Con utili negativi non è significativo', 'È il prezzo diviso l’utile per azione'], e: 'Il P/E va letto insieme a crescita, rischio e qualità degli utili: un numero basso, da solo, non indica convenienza.' },
    { q: 'Un’azienda ciclica è al picco del ciclo, con utili record e P/E di 7. Che cosa devi considerare?', a: 'Gli utili potrebbero calare con il ciclo', w: ['Il titolo è di certo sottovalutato', 'Gli utili record sono ormai stabili', 'Il P/E basso annulla ogni rischio'], e: 'Nei ciclici il P/E è spesso basso al picco e alto nella fase peggiore: conta l’utile medio lungo tutto il ciclo.' },
    { q: 'Perché l’EPS diluito è utile all’investitore?', a: 'Include le azioni da opzioni e convertibili', w: ['Esclude le perdite non ricorrenti', 'Usa gli utili stimati del prossimo anno', 'Aggiunge i dividendi già distribuiti'], e: 'L’EPS diluito conta le azioni che potrebbero nascere da stock option, warrant e convertibili: mostra il rischio di diluizione.' },
  ],
  fill: [
    { s: 'Il P/E si calcola dividendo il ___ dell’azione per l’utile per azione.', a: 'prezzo', w: ['dividendo', 'nominale', 'valore contabile'] },
    { s: 'L’inverso del P/E si chiama earnings ___.', a: 'yield', w: ['growth', 'margin', 'ratio'] },
    { s: 'Un titolo con P/E basso ma utili destinati a calare è una value ___.', a: 'trap', w: ['chain', 'gap', 'line'] },
    { s: 'Il P/E ___ usa le stime degli utili per i prossimi dodici mesi.', a: 'forward', w: ['trailing', 'storico', 'diluito'] },
    { s: 'Il riacquisto di azioni proprie riduce il numero di azioni e può far salire l’___.', a: 'EPS', w: ['EBITDA', 'EBIT', 'avviamento'] },
  ],
  order: [
    { q: 'Ordina i passaggi per calcolare il P/E', i: ['Prendere l’utile netto', 'Dividerlo per il numero medio di azioni', 'Ottenere l’EPS', 'Dividere il prezzo per l’EPS'], e: 'Prima si ricava l’utile per azione, poi si confronta con il prezzo di borsa: P/E = prezzo ÷ EPS.' },
    { q: 'Ordina dal P/E più basso al più alto', i: ['Alfa: prezzo 12 €, EPS 2 €', 'Beta: prezzo 9 €, EPS 1 €', 'Gamma: prezzo 30 €, EPS 2,5 €', 'Delta: prezzo 18 €, EPS 1 €'], e: 'P/E: Alfa 6, Beta 9, Gamma 12, Delta 18. Il prezzo più alto non significa P/E più alto: conta il rapporto con l’utile.' },
  ],
  cat: [
    { q: 'A parità del resto, fa salire o scendere l’EPS?', g: [['Fa salire l’EPS', ['Riacquisto di azioni proprie', 'Aumento dell’utile netto', 'Calo degli oneri finanziari']], ['Fa scendere l’EPS', ['Aumento di capitale con nuove azioni', 'Esercizio di stock option dei manager', 'Svalutazione dell’avviamento']]] },
    { q: 'Quale effetto tende ad avere sul P/E?', g: [['Tende ad alzarlo', ['Forte crescita attesa degli utili', 'Utili temporaneamente depressi', 'Business molto stabile e prevedibile']], ['Tende ad abbassarlo', ['Utili attesi in calo', 'Elevato rischio percepito', 'Utile gonfiato da una plusvalenza']]] },
  ],
  scen: [
    { s: 'Laura, 30 anni, sente dire che Alfa Spa è «la più economica della borsa» con un P/E di 5. Nelle note scopre che metà dell’utile viene dalla vendita di una controllata.', q: 'Cosa fa Laura?', o: [
      { t: 'Ricalcola il P/E sull’utile ricorrente', ok: true, f: 'Senza la plusvalenza l’utile si dimezza e il P/E sale a circa 10: il titolo è meno economico di quanto sembri.' },
      { t: 'Compra: un P/E di 5 è comunque bassissimo', ok: false, f: 'Il P/E di 5 si basa su un utile gonfiato da un evento che non si ripeterà: il confronto è falsato.' },
      { t: 'Scarta il P/E e guarda solo il prezzo per azione', ok: false, f: 'Il prezzo da solo non dice se un titolo è caro o economico: serve rapportarlo agli utili ricorrenti.' },
    ] },
    { s: 'Michele, 50 anni, confronta una banca con P/E 8 e una società di software con P/E 35. Conclude che la banca è più conveniente perché costa meno volte i suoi utili.', q: 'Come dovrebbe ragionare?', o: [
      { t: 'Ha ragione: il P/E più basso vince sempre', ok: false, f: 'Settori diversi hanno crescita, rischio e modelli di business diversi: il P/E da solo non basta per confrontarli.' },
      { t: 'Confronta ciascuna con aziende del proprio settore', ok: true, f: 'Il P/E è utile soprattutto tra aziende simili: la banca va confrontata con altre banche, il software con altro software.' },
      { t: 'Sceglie il software, perché un P/E alto indica qualità', ok: false, f: 'Un P/E alto riflette aspettative elevate, non qualità garantita: se la crescita delude, il prezzo può scendere molto.' },
    ] },
    { s: 'Federica, 37 anni, nota che l’EPS di Beta Spa è cresciuto del 15%, ma l’utile netto è fermo. La società ha riacquistato molte azioni proprie finanziandosi con nuovo debito.', q: 'Come interpreta la crescita dell’EPS?', o: [
      { t: 'Come prova che il business sta crescendo', ok: false, f: 'L’utile netto è fermo: l’EPS cresce solo perché si divide per meno azioni, non perché si guadagna di più.' },
      { t: 'Come effetto del buyback, da pesare con il debito', ok: true, f: 'Il buyback ha alzato l’EPS, ma l’ha finanziato a debito: va valutato se il riacquisto ha creato valore o solo rischio.' },
      { t: 'Come un errore nel calcolo dell’EPS', ok: false, f: 'Non c’è errore: meno azioni in circolazione con lo stesso utile producono un EPS più alto.' },
    ] },
    { s: 'Antonio, 63 anni, guarda Delta Spa: il P/E trailing è 24, quello forward è 12, perché gli analisti si aspettano un raddoppio degli utili il prossimo anno.', q: 'Qual è l’approccio più sensato?', o: [
      { t: 'Usa solo il P/E forward: è quello che guarda avanti', ok: false, f: 'Il P/E forward è valido quanto le stime su cui si basa: se il raddoppio non arriva, il titolo resta caro.' },
      { t: 'Usa solo il trailing: le stime sono sempre sbagliate', ok: false, f: 'Le stime non sono sempre sbagliate: vanno verificate, non scartate a priori.' },
      { t: 'Verifica quanto è realistico il raddoppio degli utili', ok: true, f: 'Tutto dipende da quella previsione: capire da dove dovrebbe arrivare la crescita dice se il P/E di 12 è credibile.' },
    ] },
  ],
  tip: 'Non usare mai il P/E da solo: confrontalo con aziende simili e con la storia del titolo, e verifica che l’utile al denominatore sia ricorrente.',
});
