FQC(56, {
  intro: 'Il P/E non basta: scopri P/B, enterprise value, EV/EBITDA e gli altri multipli, quando usarli e dove possono ingannarti.',
  cards: [
    { t: 'Il rapporto P/B', x: 'Il P/B (price to book) confronta il valore di borsa con il patrimonio netto contabile. È molto usato per banche e assicurazioni, il cui attivo è fatto soprattutto di attività finanziarie.', v: { k: 'formula', f: 'P/B = capitalizzazione ÷ patrimonio netto', n: 'Es. Alfa Spa: 800 ÷ 400 = 2x' } },
    { t: 'L’enterprise value', x: 'L’enterprise value (EV) è il valore dell’intera azienda per azionisti e creditori: capitalizzazione più debiti finanziari meno cassa. Chi comprasse tutta Alfa Spa si accollerebbe anche il suo debito netto.', v: { k: 'bars', d: [['Capitalizzazione', 800], ['Debiti finanziari', 300], ['Cassa', -100], ['Enterprise value', 1000]], u: 'mln €' } },
    { t: 'Il multiplo EV/EBITDA', x: 'L’EV/EBITDA confronta il valore dell’intera azienda con il margine operativo lordo. EV ed EBITDA stanno entrambi «prima» del debito: per questo permette di confrontare aziende finanziate in modo diverso.', v: { k: 'stat', n: '8x', l: 'EV/EBITDA di Alfa Spa: 1.000 ÷ 125' } },
    { t: 'Coppie coerenti', x: 'Ogni multiplo deve mettere in rapporto grandezze dello stesso livello: il prezzo, che spetta agli azionisti, con utile netto e patrimonio; l’EV, che spetta a tutti i finanziatori, con EBITDA, EBIT e ricavi.', v: { k: 'vs', a: ['Prezzo', 'Con utile netto e PN'], b: ['Enterprise value', 'Con EBITDA, EBIT, ricavi'] } },
    { t: 'Un multiplo per ogni azienda', x: 'Non esiste un multiplo universale. Il P/B è tipico di banche e assicurazioni, l’EV/EBITDA dell’industria, l’EV/Sales delle aziende ancora in perdita, il FCF yield di chi genera cassa stabile.', v: { k: 'icons', d: [['🏦', 'Banche: P/B'], ['🏭', 'Industria: EV/EBITDA'], ['🚀', 'In perdita: EV/Sales'], ['💶', 'Cassa stabile: FCF yield']] } },
    { t: 'Il limite dell’EV/EBITDA', x: 'L’EV/EBITDA ignora gli investimenti. Per chi spende molto in impianti e reti, come le telecomunicazioni, conviene affiancare l’EV/EBIT o il free cash flow, che tengono conto di quei costi.', v: { k: 'scale', a: 'Pochi investimenti', b: 'Molti investimenti', d: [['Consulenza', 10], ['Grande distribuzione', 45], ['Telecomunicazioni', 85]] } },
  ],
  terms: [
    ['P/B', 'Rapporto tra capitalizzazione di borsa e patrimonio netto contabile.'],
    ['Enterprise value', 'Valore dell’azienda per azionisti e creditori: capitalizzazione più debito netto.'],
    ['EV/EBITDA', 'Multiplo che confronta il valore dell’intera azienda con il margine operativo lordo.'],
    ['EV/Sales', 'Rapporto tra enterprise value e ricavi, usato spesso per aziende ancora in perdita.'],
    ['FCF yield', 'Free cash flow diviso capitalizzazione: quanta cassa libera genera ogni euro di valore.'],
    ['Valore contabile per azione', 'Patrimonio netto diviso il numero di azioni in circolazione.'],
    ['Multipli comparabili', 'Metodo che valuta un’azienda confrontando i suoi multipli con quelli di società simili.'],
    ['Patrimonio netto tangibile', 'Patrimonio netto meno avviamento e altre attività immateriali.'],
  ],
  tf: [
    ['L’enterprise value tiene conto anche del debito netto dell’azienda.', true, 'EV = capitalizzazione + debiti finanziari − cassa: è il valore per tutti i finanziatori, non solo per gli azionisti.'],
    ['Un P/B inferiore a 1 indica sempre un titolo sottovalutato.', false, 'Può riflettere attivi sopravvalutati in bilancio o una redditività scarsa: il mercato può avere buoni motivi per lo sconto.'],
    ['L’EV/EBITDA è utile per confrontare aziende con livelli di debito diversi.', true, 'EV ed EBITDA sono entrambi calcolati prima della struttura finanziaria: il confronto non è distorto da quanto debito c’è.'],
    ['Dividere la capitalizzazione per l’EBITDA è un modo corretto di costruire un multiplo.', false, 'È incoerente: la capitalizzazione spetta ai soli azionisti, l’EBITDA serve tutti i finanziatori. Con l’EBITDA va usato l’EV.'],
    ['Il P/B è particolarmente usato per valutare banche e assicurazioni.', true, 'Il loro attivo è fatto soprattutto di attività finanziarie e il patrimonio è centrale per la vigilanza: il valore contabile è un riferimento utile.'],
    ['L’EV/EBITDA tiene già conto degli investimenti necessari all’attività.', false, 'L’EBITDA è prima degli ammortamenti e ignora il capex: per aziende ad alta intensità di capitale va affiancato da EV/EBIT o FCF.'],
    ['Se un’azienda ha più cassa che debiti, il suo enterprise value è inferiore alla capitalizzazione.', true, 'Con cassa netta, l’EV si ottiene togliendola dalla capitalizzazione: il valore dell’attività operativa è più basso del valore di borsa.'],
    ['Un multiplo basso rispetto ai concorrenti dimostra che l’azienda è sottovalutata.', false, 'Lo sconto può riflettere crescita più lenta, margini più bassi o rischi maggiori: va spiegato prima di parlare di sottovalutazione.'],
    ['L’EV/Sales si può calcolare anche quando un’azienda ha utili ed EBITDA negativi.', true, 'I ricavi restano positivi anche in perdita: il multiplo è calcolabile, ma va letto pensando ai margini futuri.'],
    ['Il patrimonio netto tangibile è di solito più alto del patrimonio netto contabile.', false, 'Si ottiene sottraendo avviamento e immateriali, quindi è minore o uguale al patrimonio netto contabile.'],
  ],
  mcq: [
    { q: 'Beta Spa capitalizza 500 milioni e ha un patrimonio netto di 250 milioni. Qual è il P/B?', a: '2x', w: ['0,5x', '1,5x', '2,5x'], e: 'P/B = 500 ÷ 250 = 2: il mercato valuta l’azienda il doppio del suo valore contabile.' },
    { q: 'Gamma Spa capitalizza 600, ha debiti finanziari per 250 e cassa per 50. Quanto vale l’EV?', a: '800', w: ['900', '600', '400'], e: 'EV = 600 + 250 − 50 = 800. Con 900 si dimentica di togliere la cassa; con 400 si sottrae il debito invece di sommarlo.' },
    { q: 'Un’azienda ha un EV di 900 e un EBITDA di 100. Qual è l’EV/EBITDA?', a: '9x', w: ['0,11x', '90x', '10x'], e: 'EV/EBITDA = 900 ÷ 100 = 9: l’intera azienda vale nove volte il suo margine operativo lordo annuo.' },
    { q: 'Per confrontare un’azienda molto indebitata con una senza debiti, perché si preferisce l’EV/EBITDA al P/E?', a: 'Non è distorto dalla struttura finanziaria', w: ['Esclude del tutto i ricavi delle aziende', 'Considera solo la cassa disponibile', 'Usa il patrimonio netto contabile'], e: 'Il P/E risente di interessi e leva; EV ed EBITDA sono prima del debito, quindi il confronto è più omogeneo.' },
    { q: 'Per quale tipo di azienda il P/B è più usato?', a: 'Una banca', w: ['Una società di software', 'Una start-up in perdita', 'Una società di consulenza'], e: 'Per una banca il patrimonio è centrale e l’attivo è soprattutto finanziario; per software e consulenza il valore sta in risorse poco visibili a bilancio.' },
    { q: 'Quale di queste convinzioni sui multipli è un errore comune?', a: 'Un P/B sotto 1 è sempre un affare', w: ['L’EV include il debito netto', 'Ogni settore ha multipli tipici', 'L’EV/Sales esiste anche in perdita'], e: 'Un P/B sotto 1 può riflettere attivi sopravvalutati o rendimenti bassi sul capitale: non è uno sconto garantito.' },
    { q: 'Quale multiplo è più adatto a una giovane azienda con ricavi in crescita ma ancora in perdita?', a: 'EV/Sales', w: ['P/E', 'EV/EBIT', 'PEG'], e: 'Con utile ed EBIT negativi, P/E, EV/EBIT e PEG non sono significativi; i ricavi invece sono positivi.' },
    { q: 'Alfa Spa ha un EV/EBITDA basso, ma reinveste ogni anno quasi tutto l’EBITDA in nuovi impianti. Cosa concludi?', a: 'Sembra più economica di quanto sia', w: ['È di sicuro sottovalutata dal mercato', 'Il capex non incide sul suo valore', 'Basta guardare il suo P/B contabile'], e: 'Se il capex assorbe quasi tutto l’EBITDA, resta poco free cash flow: EV/EBIT o FCF yield danno un quadro più realistico.' },
  ],
  fill: [
    { s: 'L’enterprise value è la capitalizzazione più il debito ___.', a: 'netto', w: ['lordo', 'commerciale', 'fiscale'] },
    { s: 'Il P/B confronta la capitalizzazione con il ___ netto.', a: 'patrimonio', w: ['utile', 'debito', 'flusso'] },
    { s: 'Per una società ancora in perdita si usa spesso il rapporto EV/___.', a: 'Sales', w: ['EBIT', 'Utile', 'EPS'] },
    { s: 'Per banche e assicurazioni un multiplo molto usato è il ___.', a: 'P/B', w: ['EV/EBITDA', 'EV/Sales', 'PEG'] },
    { s: 'Il FCF ___ rapporta il free cash flow alla capitalizzazione di borsa.', a: 'yield', w: ['margin', 'ratio', 'cover'] },
  ],
  order: [
    { q: 'Ordina i passaggi per calcolare l’EV/EBITDA', i: ['Calcolare la capitalizzazione', 'Aggiungere i debiti finanziari', 'Sottrarre la cassa', 'Dividere l’EV per l’EBITDA'], e: 'Prima si costruisce l’EV (capitalizzazione + debiti − cassa), poi lo si divide per il margine operativo lordo.' },
    { q: 'Ordina dal P/B più basso al più alto', i: ['Alfa: cap. 300, PN 600', 'Beta: cap. 450, PN 500', 'Gamma: cap. 600, PN 400', 'Delta: cap. 900, PN 300'], e: 'P/B: Alfa 0,5; Beta 0,9; Gamma 1,5; Delta 3. Sotto 1 il mercato valuta l’azienda meno del suo patrimonio contabile.' },
  ],
  cat: [
    { q: 'Multiplo basato sul prezzo o sull’enterprise value?', g: [['Sul prezzo (azionisti)', ['P/E', 'P/B', 'Dividend yield', 'FCF yield']], ['Sull’EV (tutti i finanziatori)', ['EV/EBITDA', 'EV/EBIT', 'EV/Sales']]] },
    { q: 'Dalla capitalizzazione all’EV: si somma o si sottrae?', g: [['Si somma', ['Debiti verso banche', 'Obbligazioni emesse', 'Debiti per leasing']], ['Si sottrae', ['Cassa in banca', 'Depositi a breve termine', 'Titoli di Stato liquidi in portafoglio']]] },
  ],
  scen: [
    { s: 'Sofia, 35 anni, nota che Banca Alfa ha un P/B di 0,6, contro una media di 1 per le banche simili. Leggendo il bilancio vede una redditività molto più bassa e molti crediti deteriorati.', q: 'Come interpreta lo sconto?', o: [
      { t: 'È un affare: il mercato la paga meno del suo patrimonio', ok: false, f: 'Il P/B basso può essere giustificato: se i crediti valgono meno di quanto scritto, anche il patrimonio è più basso.' },
      { t: 'Lo sconto può essere meritato: valuta la qualità dell’attivo', ok: true, f: 'Bassa redditività e crediti a rischio spiegano spesso un P/B sotto 1: conta quanto è affidabile quel patrimonio.' },
      { t: 'Il P/B non conta nulla per le banche', ok: false, f: 'Al contrario, per le banche il P/B è uno dei multipli più usati: va però letto insieme a redditività e qualità dei crediti.' },
    ] },
    { s: 'Nicola, 42 anni, confronta Beta Spa, senza debiti, con P/E 15 ed EV/EBITDA 7, e Gamma Spa, molto indebitata, con P/E 10 ed EV/EBITDA 9. A prima vista Gamma gli sembra più economica.', q: 'Quale ragionamento è corretto?', o: [
      { t: 'Gamma è più economica: conta il P/E', ok: false, f: 'Il P/E di Gamma ignora il peso del debito: considerando anche i creditori, Gamma risulta più cara.' },
      { t: 'Sono uguali: i multipli si compensano', ok: false, f: 'I due multipli misurano cose diverse e qui indicano conclusioni opposte: non si compensano.' },
      { t: 'Con debiti così diversi pesa di più l’EV/EBITDA', ok: true, f: 'L’EV include il debito di Gamma: sull’intera azienda Beta costa 7 volte l’EBITDA, Gamma 9. Il P/E basso era un’illusione.' },
    ] },
    { s: 'Elisa, 26 anni, studia Delta Spa, giovane azienda con ricavi in crescita del 60% l’anno ma ancora in perdita. Un amico le dice che non si può valutare, perché il P/E è negativo.', q: 'Cosa può fare Elisa?', o: [
      { t: 'Usa l’EV/Sales con aziende simili e guarda ai margini', ok: true, f: 'Con utili negativi i ricavi sono il riferimento: conta però capire se e quando l’azienda potrà diventare redditizia.' },
      { t: 'Calcola comunque il P/E e lo confronta con il settore', ok: false, f: 'Un P/E con utili negativi non ha significato economico: il confronto sarebbe privo di senso.' },
      { t: 'Rinuncia: senza utili nessuna valutazione è possibile', ok: false, f: 'Esistono multipli e metodi adatti anche alle aziende in perdita: serve solo usarli con cautela.' },
    ] },
    { s: 'Riccardo, 55 anni, legge un commento secondo cui Epsilon Spa è «regalata»: capitalizza 400 milioni con un EBITDA di 100, cioè «4 volte l’EBITDA». L’azienda però ha 800 milioni di debito netto.', q: 'Cosa fa Riccardo?', o: [
      { t: 'Si fida del commento: 4 volte l’EBITDA è pochissimo', ok: false, f: 'Il commento mescola capitalizzazione ed EBITDA, due grandezze incoerenti: ignora completamente il debito.' },
      { t: 'Ricalcola con l’EV: (400 + 800) ÷ 100 = 12 volte', ok: true, f: 'Considerando il debito netto, l’azienda vale 12 volte l’EBITDA: tutt’altro che regalata, e con un debito molto pesante.' },
      { t: 'Divide il debito per la capitalizzazione e si ferma lì', ok: false, f: 'Il rapporto debito/capitalizzazione dice qualcosa sulla leva, ma non sostituisce un multiplo di valutazione coerente.' },
    ] },
  ],
  tip: 'Usa più multipli insieme e sempre in coppie coerenti: il prezzo con utili e patrimonio, l’EV con EBITDA, EBIT e ricavi. E confrontali con aziende davvero simili.',
});
