FQC(57, {
  intro: 'Quanto rende il capitale affidato a un’azienda? Impara a leggere ROE, ROA, ROIC e margini, e a capire cosa si nasconde dietro un numero alto.',
  cards: [
    { t: 'Il ROE', x: 'Il ROE (return on equity) misura quanto utile genera ogni euro di capitale dei soci. Si usa spesso il patrimonio netto medio dell’anno, per tenere conto delle variazioni tra inizio e fine esercizio.', v: { k: 'formula', f: 'ROE = utile netto ÷ patrimonio netto', n: 'Es. Alfa Spa: 90 ÷ 450 = 20%' } },
    { t: 'ROE e ROA', x: 'Il ROA divide l’utile per il totale dell’attivo, cioè per tutte le risorse impiegate, comunque finanziate. Per Alfa Spa: 90 ÷ 1.200 = 7,5%. La distanza tra ROE e ROA dipende soprattutto dal debito.', v: { k: 'vs', a: ['ROE', 'Utile sul capitale dei soci'], b: ['ROA', 'Utile su tutto l’attivo'] } },
    { t: 'La cascata dei margini', x: 'I margini rapportano ogni livello del conto economico ai ricavi. Alfa Spa ha margine EBITDA del 20%, EBIT del 14% e netto del 9%. Confrontarli negli anni mostra se l’azienda diventa più o meno efficiente.', v: { k: 'bars', d: [['Margine EBITDA', 20], ['Margine EBIT', 14], ['Margine netto', 9]], u: '%' } },
    { t: 'La scomposizione DuPont', x: 'Il ROE si scompone in tre leve: quanto si guadagna su ogni euro venduto, quante vendite genera l’attivo e quanto l’attivo è finanziato con capitale di terzi. Lo stesso ROE può nascere da ricette molto diverse.', v: { k: 'steps', s: ['Margine netto 9%', '× Rotazione attivo 0,83', '× Leva 2,67', '= ROE 20%'] } },
    { t: 'Ogni settore ha i suoi margini', x: 'Un supermercato vive con margini netti di pochi punti, ma vende moltissimo rispetto all’attivo; software e lusso hanno margini alti. I margini vanno confrontati soprattutto tra aziende dello stesso settore.', v: { k: 'scale', a: 'Margini bassi', b: 'Margini alti', d: [['Supermercati', 10], ['Auto', 30], ['Lusso', 75], ['Software', 85]] } },
    { t: 'ROIC contro costo del capitale', x: 'Il ROIC misura il rendimento operativo, dopo le imposte, del capitale investito da soci e creditori. Un’azienda crea valore solo se il ROIC supera stabilmente il costo del capitale che usa.', v: { k: 'stat', n: '12% > 8%', l: 'ROIC di Alfa Spa contro il suo costo del capitale' } },
  ],
  terms: [
    ['ROE', 'Utile netto diviso patrimonio netto: rendimento contabile del capitale dei soci.'],
    ['ROA', 'Utile netto diviso totale dell’attivo: rendimento di tutte le risorse impiegate.'],
    ['ROIC', 'Risultato operativo dopo le imposte diviso capitale investito da soci e creditori.'],
    ['Margine EBITDA', 'EBITDA diviso ricavi: quanto resta di ogni euro venduto prima di ammortamenti e interessi.'],
    ['Margine netto', 'Utile netto diviso ricavi: quanto resta all’azienda per ogni euro venduto.'],
    ['Rotazione dell’attivo', 'Ricavi divisi totale dell’attivo: quante vendite genera ogni euro investito.'],
    ['Moltiplicatore del capitale', 'Attivo diviso patrimonio netto: la leva della scomposizione DuPont.'],
    ['NOPAT', 'Risultato operativo al netto delle imposte, prima degli oneri finanziari.'],
  ],
  tf: [
    ['Un ROE alto può dipendere da un forte uso del debito.', true, 'Con più debito e meno capitale proprio il ROE sale anche a parità di utile: va letto insieme al livello di indebitamento.'],
    ['Il margine netto di un supermercato è di solito più basso di quello di una società di software.', true, 'La grande distribuzione lavora con margini di pochi punti e alti volumi; il software ha costi marginali bassi e margini elevati.'],
    ['Un ROE in crescita indica sempre che l’azienda sta migliorando.', false, 'Può salire per più debito, per un buyback o perché perdite passate hanno ridotto il patrimonio: va capito da dove nasce.'],
    ['Il ROE si calcola dividendo l’utile netto per il totale dell’attivo.', false, 'Quella è la definizione del ROA. Il ROE divide l’utile netto per il patrimonio netto, cioè il capitale dei soci.'],
    ['Due aziende con lo stesso ROE possono avere margini molto diversi.', true, 'Con la scomposizione DuPont lo stesso ROE può nascere da margini alti e poca rotazione, o da margini bassi e molta rotazione.'],
    ['Un’azienda crea valore se il ROIC supera stabilmente il costo del capitale.', true, 'Se il capitale investito rende più di quanto costa finanziarlo, ogni euro reinvestito aumenta il valore per i soci.'],
    ['Un margine EBITDA del 30% significa che l’azienda guadagna 30 euro netti ogni 100 di ricavi.', false, 'L’EBITDA viene prima di ammortamenti, interessi e imposte: l’utile netto su 100 euro di ricavi è più basso.'],
    ['Il ROE può risultare molto alto perché il patrimonio netto è stato ridotto da perdite passate.', true, 'Con un denominatore piccolo, anche un utile modesto produce un ROE alto: non è un segno di eccellenza.'],
    ['Margini stabili negli anni non dicono nulla sulla qualità di un’azienda.', false, 'Margini stabili o in crescita, anche nelle fasi difficili, suggeriscono potere di prezzo e buon controllo dei costi.'],
    ['Per giudicare un margine basta confrontarlo con quello di aziende di qualsiasi settore.', false, 'Ogni settore ha strutture di costo tipiche: il confronto utile è con aziende simili e con la storia della stessa azienda.'],
  ],
  mcq: [
    { q: 'Beta Spa ha un utile netto di 30 e un patrimonio netto medio di 200. Qual è il ROE?', a: '15%', w: ['6,7%', '30%', '20%'], e: 'ROE = 30 ÷ 200 = 15%: ogni 100 euro di capitale dei soci hanno prodotto 15 euro di utile.' },
    { q: 'Gamma Spa ha ricavi per 800 e un utile netto di 40. Qual è il margine netto?', a: '5%', w: ['20%', '4%', '8%'], e: 'Margine netto = 40 ÷ 800 = 5%: restano 5 euro di utile ogni 100 euro venduti.' },
    { q: 'Nella scomposizione DuPont, quali tre fattori moltiplicati danno il ROE?', a: 'Margine netto, rotazione dell’attivo e leva', w: ['Margine lordo, P/E e rotazione del magazzino', 'EBITDA, capex e free cash flow', 'Ricavi, dividendi e numero di azioni'], e: 'ROE = (utile ÷ ricavi) × (ricavi ÷ attivo) × (attivo ÷ patrimonio netto): redditività, efficienza e indebitamento.' },
    { q: 'Delta Spa ha un ROE del 25%, molto sopra i concorrenti, ma un ROA del 2%. Cosa suggerisce?', a: 'Un forte uso della leva finanziaria', w: ['Margini eccezionalmente alti', 'L’assenza totale di debiti', 'Un attivo piccolo rispetto ai ricavi'], e: 'Un ROE molto superiore al ROA indica un attivo finanziato soprattutto da terzi: più rendimento per i soci, ma più rischio.' },
    { q: 'Quale di queste convinzioni sul ROE è un errore comune?', a: 'Un ROE alto è sempre un pregio', w: ['Il ROE usa il patrimonio netto', 'Il debito può gonfiare il ROE', 'Il ROE va confrontato nel tempo'], e: 'Un ROE alto può nascere da troppo debito o da un patrimonio eroso dalle perdite: va scomposto prima di giudicare.' },
    { q: 'Perché il ROIC è utile per giudicare la gestione operativa meglio del ROE?', a: 'Non dipende da come l’azienda è finanziata', w: ['Include anche il prezzo dell’azione', 'Considera solo il capitale dei soci', 'Si calcola sui ricavi lordi del periodo'], e: 'Il ROIC rapporta il risultato operativo al capitale investito da soci e creditori: confronta aziende con leve diverse.' },
    { q: 'Un supermercato ha un margine netto del 2% e una rotazione dell’attivo pari a 3. Qual è il suo ROA?', a: '6%', w: ['2%', '1,5%', '0,67%'], e: 'ROA = margine netto × rotazione dell’attivo = 2% × 3 = 6%: margini bassi possono essere compensati da alti volumi.' },
    { q: 'Quale andamento dei margini segnala più probabilmente un vantaggio sui concorrenti?', a: 'Margini alti e stabili anche in recessione', w: ['Margini in calo mentre i ricavi crescono', 'Margini alti solo nell’anno di una cessione', 'Margini molto variabili di anno in anno'], e: 'Difendere margini alti nei periodi difficili indica potere di prezzo o costi più bassi dei concorrenti.' },
  ],
  fill: [
    { s: 'Il ___ misura l’utile netto rispetto al patrimonio netto.', a: 'ROE', w: ['ROA', 'ROIC', 'P/E'] },
    { s: 'Il ROA divide l’utile netto per il totale dell’___.', a: 'attivo', w: ['utile', 'EBITDA', 'avviamento'] },
    { s: 'Il margine ___ è l’utile netto diviso i ricavi.', a: 'netto', w: ['lordo', 'operativo', 'EBITDA'] },
    { s: 'Nella scomposizione DuPont, a parità di margini e rotazione, più ___ fa salire il ROE.', a: 'debito', w: ['cassa', 'capitale proprio', 'avviamento'] },
    { s: 'Un’azienda crea valore quando il ROIC supera il costo del ___.', a: 'capitale', w: ['venduto', 'personale', 'lavoro'] },
  ],
  order: [
    { q: 'Ordina i margini dal più alto al più basso (azienda con interessi e imposte positivi)', i: ['Margine EBITDA', 'Margine EBIT', 'Utile ante imposte su ricavi', 'Margine netto'], e: 'Scendendo nel conto economico si sottraggono ammortamenti, oneri finanziari e imposte: ogni margine è più basso del precedente.' },
    { q: 'Ordina dal ROE più basso al più alto', i: ['Alfa: utile 20, PN 400', 'Beta: utile 30, PN 300', 'Gamma: utile 60, PN 400', 'Delta: utile 50, PN 200'], e: 'ROE: Alfa 5%, Beta 10%, Gamma 15%, Delta 25%. Non conta l’utile più alto, ma l’utile rispetto al capitale dei soci.' },
  ],
  cat: [
    { q: 'Indicatore rapportato ai ricavi o al capitale?', g: [['Ai ricavi', ['Margine EBITDA', 'Margine EBIT', 'Margine netto']], ['Al capitale', ['ROE', 'ROA', 'ROIC']]] },
    { q: 'Questo fa salire il ROE in modo sano o in modo rischioso?', g: [['In modo sano', ['Più efficienza sui costi', 'Più vendite con lo stesso attivo', 'Prezzi più alti accettati dai clienti']], ['In modo rischioso o ingannevole', ['Molto debito in più', 'Patrimonio eroso da perdite passate', 'Utile gonfiato da una plusvalenza']]] },
  ],
  scen: [
    { s: 'Alessia, 32 anni, scopre che Alfa Spa ha un ROE del 35%, contro il 12% medio del settore. Approfondendo vede che i debiti sono sei volte il patrimonio netto e in gran parte a tasso variabile.', q: 'Come valuta quel ROE?', o: [
      { t: 'Lo scompone e pesa il rischio legato al debito', ok: true, f: 'Il ROE è alto soprattutto per la leva: se i tassi salgono o gli utili calano, lo stesso debito può mettere l’azienda in difficoltà.' },
      { t: 'È la migliore del settore: il ROE parla chiaro', ok: false, f: 'Un ROE gonfiato dalla leva non indica un business migliore: aumenta anche la fragilità dell’azienda.' },
      { t: 'Ignora il debito: conta solo il rendimento per i soci', ok: false, f: 'Il rendimento per i soci dipende proprio dal debito: se le cose vanno male, la leva amplifica le perdite.' },
    ] },
    { s: 'Fabio, 48 anni, vuole scartare Beta Spa, catena di supermercati, perché ha un margine netto del 2%, mentre Gamma Spa, marchio di lusso, ha il 20%.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Ha ragione: il margine più alto è sempre preferibile', ok: false, f: 'Il margine da solo ignora la rotazione dell’attivo: due modelli di business diversi non si confrontano su un solo numero.' },
      { t: 'Confrontare Beta con altre catene e guardare anche ROA e ROE', ok: true, f: 'Un supermercato ha margini bassi per natura ma ruota l’attivo molte volte: conta la redditività del capitale e il confronto con i simili.' },
      { t: 'Scegliere Beta, perché margini bassi significano prezzi bassi', ok: false, f: 'Margini bassi non sono un pregio in sé: il punto è capire se il modello rende abbastanza sul capitale investito.' },
    ] },
    { s: 'Serena, 29 anni, segue Delta Spa, che ha raddoppiato i ricavi con molte acquisizioni. Nello stesso periodo il ROIC è sceso dal 15% al 5%, mentre il costo del capitale è stimato intorno all’8%.', q: 'Che conclusione trae?', o: [
      { t: 'La crescita dei ricavi dimostra che la strategia funziona', ok: false, f: 'Crescere non basta: se il capitale investito rende meno di quanto costa, ogni acquisizione riduce il valore per i soci.' },
      { t: 'Il ROIC non conta finché i ricavi crescono', ok: false, f: 'Il ROIC dice se la crescita è redditizia: ignorarlo significa non vedere la distruzione di valore.' },
      { t: 'Le acquisizioni stanno distruggendo valore', ok: true, f: 'Con un ROIC al 5% e un costo del capitale all’8%, le acquisizioni rendono meno di quanto costano: un segnale da non ignorare.' },
    ] },
    { s: 'Giacomo, 61 anni, legge che Epsilon Spa celebra ricavi record. Guardando gli ultimi quattro anni, però, il margine EBIT è passato dal 18% al 16%, poi al 13% e infine al 10%.', q: 'Cosa fa Giacomo?', o: [
      { t: 'Si concentra sui ricavi record e ignora i margini', ok: false, f: 'Ricavi in crescita con margini in calo possono voler dire sconti, costi fuori controllo o concorrenza più forte.' },
      { t: 'Indaga perché i margini si stanno erodendo anno dopo anno', ok: true, f: 'Un calo costante dei margini è uno dei segnali più importanti: può indicare perdita di potere di prezzo o costi in aumento.' },
      { t: 'Conclude che un margine del 10% è comunque alto', ok: false, f: 'Più del livello conta la tendenza: un margine che scende ogni anno racconta un problema, qualunque sia il punto di partenza.' },
    ] },
  ],
  tip: 'Quando vedi un ROE alto, scomponilo: margini, rotazione o debito? Lo stesso numero può descrivere un’azienda eccellente o una molto fragile.',
});
