FQC(58, {
  intro: 'Il debito può far crescere un’azienda o affondarla: impara a misurare debito netto, leva, copertura degli interessi e rischio di scadenza.',
  cards: [
    { t: 'Il debito netto', x: 'Il debito netto, in Italia spesso chiamato posizione finanziaria netta, sottrae la liquidità dai debiti verso banche e obbligazionisti. Attenzione al segno: alcune aziende lo presentano negativo, altre positivo.', v: { k: 'formula', f: 'Debito netto = debiti finanziari − liquidità', n: 'Es. Alfa Spa: 500 − 100 = 400 milioni' } },
    { t: 'Debito netto su EBITDA', x: 'Indica quanti anni di margine operativo lordo servirebbero per ripagare il debito netto. Come regola empirica, oltre 3-4 volte il debito è considerato elevato, ma la soglia cambia molto da settore a settore.', v: { k: 'scale', a: 'Debito leggero', b: 'Debito pesante', d: [['0,5x', 10], ['2x', 35], ['4x', 70], ['6x', 92]] } },
    { t: 'La copertura degli interessi', x: 'Dice quante volte il risultato operativo copre gli oneri finanziari. Più è alta, più l’azienda può sopportare un calo degli utili o un rialzo dei tassi senza faticare a pagare gli interessi.', v: { k: 'stat', n: '7x', l: 'Alfa Spa: EBIT 140 ÷ oneri finanziari 20' } },
    { t: 'Il muro delle scadenze', x: 'Non conta solo quanto debito c’è, ma quando scade. Se una grossa quota scade tutta insieme, l’azienda deve rifinanziarla alle condizioni di quel momento: un rischio serio se i mercati del credito sono in tensione.', v: { k: 'bars', d: [['Entro 1 anno', 50], ['1-2 anni', 300], ['3-5 anni', 100], ['Oltre 5 anni', 50]], u: 'mln €' } },
    { t: 'Tasso fisso o variabile', x: 'Con il debito a tasso variabile, un rialzo dei tassi di mercato fa salire presto gli oneri finanziari. Il tasso fisso protegge da questo rischio fino alla scadenza, quando il debito andrà rinnovato.', v: { k: 'vs', a: ['Tasso fisso', 'Costo prevedibile'], b: ['Tasso variabile', 'Segue i tassi di mercato'] } },
    { t: 'Gli altri segnali nelle note', x: 'Nelle note cerca i covenant, cioè i limiti concordati con le banche, il rating, le linee di credito non utilizzate e i debiti per leasing, che con l’IFRS 16 sono iscritti tra le passività.', v: { k: 'icons', d: [['📜', 'Covenant'], ['🅰️', 'Rating'], ['💧', 'Linee di credito'], ['🏢', 'Leasing']] } },
  ],
  terms: [
    ['Debito netto', 'Debiti finanziari meno cassa e altre disponibilità liquide.'],
    ['Posizione finanziaria netta', 'Termine usato in Italia per il saldo tra liquidità e debiti finanziari.'],
    ['Leva finanziaria', 'Uso del debito per finanziare l’attività: amplifica sia i guadagni sia le perdite dei soci.'],
    ['Copertura degli interessi', 'Risultato operativo diviso oneri finanziari: quante volte si possono pagare gli interessi.'],
    ['Covenant', 'Clausola di un finanziamento che impone limiti, ad esempio un tetto al rapporto debito/EBITDA.'],
    ['Rifinanziamento', 'Sostituzione di un debito in scadenza con un nuovo prestito o nuove obbligazioni.'],
    ['Gearing', 'Rapporto tra debito netto e patrimonio netto: quanto si usa il debito rispetto al capitale proprio.'],
    ['Linea di credito', 'Somma messa a disposizione da una banca, che l’azienda può usare quando ne ha bisogno.'],
  ],
  tf: [
    ['Il debito netto si ottiene sottraendo la liquidità dai debiti finanziari.', true, 'La cassa disponibile potrebbe ripagare parte dei debiti: per questo si guarda il saldo netto.'],
    ['Un’azienda senza debiti è sempre un investimento migliore di una indebitata.', false, 'Un debito moderato e ben gestito può aumentare il rendimento per i soci: conta la sostenibilità, non l’assenza di debito.'],
    ['La copertura degli interessi si calcola dividendo l’EBIT per gli oneri finanziari.', true, 'Indica quante volte il risultato operativo copre gli interessi; alcune analisi usano l’EBITDA al posto dell’EBIT.'],
    ['La leva finanziaria amplifica solo i guadagni, non le perdite.', false, 'La leva agisce nei due sensi: se gli utili calano, gli interessi restano e la perdita per i soci è amplificata.'],
    ['Con il debito a tasso variabile, un rialzo dei tassi aumenta gli oneri finanziari.', true, 'Gli interessi si aggiornano in base ai tassi di mercato: un aumento si scarica rapidamente sul conto economico.'],
    ['Un rapporto debito netto/EBITDA di 3 ha lo stesso significato in tutti i settori.', false, 'Settori con flussi stabili, come le utility, reggono più debito di quelli ciclici: la stessa soglia può essere comoda o pericolosa.'],
    ['Violare un covenant può permettere alle banche di chiedere il rimborso anticipato del prestito.', true, 'I covenant sono condizioni contrattuali: se non sono rispettati, i finanziatori possono rinegoziare o esigere il rimborso.'],
    ['Se la liquidità supera i debiti finanziari, il debito netto è negativo: l’azienda ha cassa netta.', true, 'Debiti finanziari meno una liquidità più grande danno un numero negativo: è la situazione di un’azienda con cassa netta.'],
    ['Una grossa quota di debito in scadenza nello stesso anno non è un rischio se l’azienda è in utile.', false, 'Anche un’azienda in utile deve trovare i soldi per rimborsare o rifinanziare: se il credito si chiude, rischia una crisi di liquidità.'],
    ['I debiti per leasing non contano mai nella valutazione della solidità finanziaria.', false, 'Con l’IFRS 16 i leasing sono iscritti tra le passività: sono impegni di pagamento simili a un debito e vanno considerati.'],
  ],
  mcq: [
    { q: 'Beta Spa ha debiti finanziari per 300 e liquidità per 120. Qual è il debito netto?', a: '180', w: ['420', '300', '120'], e: 'Debito netto = 300 − 120 = 180.' },
    { q: 'Gamma Spa ha un debito netto di 600 e un EBITDA di 150. Quanto vale il rapporto debito netto/EBITDA?', a: '4x', w: ['0,25x', '2,5x', '6x'], e: '600 ÷ 150 = 4: servirebbero circa quattro anni di EBITDA per ripagare il debito, un livello già elevato per molti settori.' },
    { q: 'Delta Spa ha un EBIT di 90 e oneri finanziari per 30. Qual è la copertura degli interessi?', a: '3x', w: ['0,33x', '1,5x', '4x'], e: 'Copertura = 90 ÷ 30 = 3: il risultato operativo copre gli interessi tre volte, un margine di sicurezza contenuto.' },
    { q: 'Perché il debito a tasso variabile è più rischioso quando i tassi possono salire?', a: 'Gli interessi da pagare aumentano presto', w: ['Il debito da rimborsare si riduce', 'L’azienda smette di pagare interessi', 'Il rating migliora automaticamente'], e: 'Con il tasso variabile gli oneri seguono i tassi di mercato: un rialzo riduce l’utile e la copertura degli interessi.' },
    { q: 'Quale di queste convinzioni sul debito aziendale è un errore comune?', a: 'Zero debiti è sempre la scelta migliore', w: ['La leva amplifica utili e perdite', 'Le scadenze contano quanto l’importo', 'Il tasso variabile espone ai rialzi'], e: 'Un debito moderato può finanziare la crescita a costo contenuto: il problema è il debito eccessivo o mal strutturato.' },
    { q: 'Che cos’è un covenant finanziario?', a: 'Un limite concordato con i finanziatori', w: ['Un tipo di azione privilegiata', 'Un indice obbligazionario di borsa', 'Una tassa sugli interessi passivi'], e: 'Ad esempio un tetto al debito netto/EBITDA: se viene superato, le banche possono rinegoziare o chiedere il rimborso.' },
    { q: 'Due aziende hanno lo stesso debito netto/EBITDA pari a 3. Quale delle due regge meglio quel debito?', a: 'Quella con ricavi stabili e regolati', w: ['Quella con utili molto ciclici', 'Quella con il debito tutto in scadenza', 'Quella con interessi tutti variabili'], e: 'Flussi prevedibili, come quelli di una utility regolata, permettono di sostenere più debito di un business ciclico.' },
    { q: 'Epsilon Spa ha un debito moderato, ma l’80% scade entro un anno, la cassa ne copre poco e il mercato del credito è in tensione. Qual è il rischio principale?', a: 'Rischio di rifinanziamento', w: ['Rischio di cambio', 'Rischio di concentrazione', 'Rischio di inflazione'], e: 'Se non riesce a rinnovare il debito in scadenza, anche un’azienda poco indebitata può trovarsi senza liquidità.' },
  ],
  fill: [
    { s: 'In Italia il saldo tra debiti finanziari e liquidità è spesso chiamato posizione finanziaria ___.', a: 'netta', w: ['lorda', 'corrente', 'operativa'] },
    { s: 'Il rapporto di ___ degli interessi confronta l’EBIT con gli oneri finanziari.', a: 'copertura', w: ['rotazione', 'conversione', 'distribuzione'] },
    { s: 'Un ___ è una clausola che impone all’azienda dei limiti, come un tetto al debito.', a: 'covenant', w: ['warrant', 'rating', 'buyback'] },
    { s: 'Sostituire un debito in scadenza con un nuovo prestito si chiama ___.', a: 'rifinanziamento', w: ['ammortamento', 'rimborso anticipato', 'accantonamento'] },
    { s: 'La leva finanziaria amplifica sia i guadagni sia le ___ per i soci.', a: 'perdite', w: ['imposte', 'vendite', 'cedole'] },
  ],
  order: [
    { q: 'Ordina dal rapporto debito netto/EBITDA più basso al più alto', i: ['Alfa: debito 50, EBITDA 100', 'Beta: debito 300, EBITDA 200', 'Gamma: debito 400, EBITDA 150', 'Delta: debito 600, EBITDA 120'], e: 'Rapporti: Alfa 0,5x; Beta 1,5x; Gamma circa 2,7x; Delta 5x. Delta è la più esposta: servirebbero cinque anni di EBITDA.' },
    { q: 'Ordina dal segnale meno preoccupante al più preoccupante', i: ['Copertura interessi 12x', 'Copertura interessi 6x', 'Copertura interessi 2x', 'Copertura interessi 0,8x'], e: 'Sotto 1 il risultato operativo non basta nemmeno a pagare gli interessi: è il segnale più grave.' },
  ],
  cat: [
    { q: 'Rende l’azienda più solida o più fragile?', g: [['Più solida', ['Scadenze del debito ben distribuite', 'Linee di credito non utilizzate', 'Debito in gran parte a tasso fisso', 'Alta copertura degli interessi']], ['Più fragile', ['Molto debito in scadenza nello stesso anno', 'Covenant vicini alla violazione', 'Debito variabile con tassi in rialzo', 'EBIT appena sopra gli oneri finanziari']]] },
    { q: 'Debito finanziario o debito operativo?', g: [['Finanziario (nel debito netto)', ['Prestito bancario', 'Obbligazioni emesse', 'Debito per leasing']], ['Operativo (fuori dal debito netto)', ['Debiti verso fornitori', 'Stipendi da pagare', 'IVA da versare']]] },
  ],
  scen: [
    { s: 'Pietro, 46 anni, ha in portafoglio Alfa Spa: debito netto pari a 5 volte l’EBITDA, quasi tutto a tasso variabile. Con il rialzo dei tassi la copertura degli interessi è scesa da 6x a 2x in un anno.', q: 'Cosa fa Pietro?', o: [
      { t: 'Rivaluta il rischio e il peso del titolo nel portafoglio', ok: true, f: 'Leva alta, tassi variabili e copertura in calo sono una combinazione fragile: ha senso chiedersi se il rischio è ancora accettabile.' },
      { t: 'Ignora il problema: prima o poi i tassi scenderanno', ok: false, f: 'Nessuno sa quando i tassi scenderanno: nel frattempo gli interessi pesano e i covenant potrebbero essere violati.' },
      { t: 'Compra altre azioni, perché il prezzo è sceso', ok: false, f: 'Un prezzo più basso non rende il debito più leggero: aumentare l’esposizione senza analisi concentra il rischio.' },
    ] },
    { s: 'Monica, 39 anni, confronta Beta Spa, senza debiti e con ROE dell’8%, e Gamma Spa, con debito netto pari a 1,5 volte l’EBITDA, copertura interessi 10x e ROE del 15%. Pensa che solo un’azienda senza debiti sia sicura.', q: 'Come dovrebbe ragionare?', o: [
      { t: 'Scartare Gamma: qualunque debito è pericoloso', ok: false, f: 'Il debito di Gamma è contenuto e ben coperto: escluderla solo per questo significa ignorare un profilo solido.' },
      { t: 'Considerare che il debito di Gamma è moderato e sostenibile', ok: true, f: 'Con 1,5x l’EBITDA e interessi coperti 10 volte, il debito di Gamma è gestibile e contribuisce a un ROE più alto.' },
      { t: 'Preferire Gamma perché un ROE alto annulla i rischi', ok: false, f: 'Il ROE non annulla nulla: qui il debito è sostenibile, ma va comunque monitorato nel tempo.' },
    ] },
    { s: 'Tommaso, 52 anni, nota che Delta Spa ha utili in crescita, ma 600 milioni di obbligazioni scadono tra otto mesi, la cassa è di 100 milioni e non ha linee di credito disponibili. I mercati del credito sono in tensione.', q: 'Qual è il punto chiave da valutare?', o: [
      { t: 'Gli utili in crescita: il resto si sistemerà', ok: false, f: 'Gli utili di un anno non bastano a rimborsare 600 milioni: serve un rifinanziamento, e in questo momento non è scontato.' },
      { t: 'Il P/E del titolo rispetto al settore', ok: false, f: 'Il multiplo conta poco se l’azienda rischia una crisi di liquidità: prima viene la capacità di rimborsare.' },
      { t: 'Come e a che costo rifinanzierà quel debito', ok: true, f: 'Il rischio di rifinanziamento è il tema centrale: un rinnovo a tassi molto più alti, o un aumento di capitale, peserebbe sui soci.' },
    ] },
    { s: 'Irene, 31 anni, legge nel comunicato di Epsilon Spa «posizione finanziaria netta: −250 milioni» e conclude che l’azienda ha 250 milioni di cassa in più dei debiti.', q: 'Cosa dovrebbe fare prima di trarre conclusioni?', o: [
      { t: 'Controllare nelle note come l’azienda definisce il segno', ok: true, f: 'Molte società italiane presentano l’indebitamento con il segno meno: quel −250 potrebbe indicare 250 milioni di debito netto.' },
      { t: 'Considerarla senz’altro un’azienda con cassa netta', ok: false, f: 'Il segno della posizione finanziaria netta non è uniforme: interpretarlo a intuito può ribaltare la conclusione.' },
      { t: 'Ignorare il dato, perché ogni azienda lo calcola diversamente', ok: false, f: 'Il dato è importante: basta leggere la definizione usata per interpretarlo correttamente.' },
    ] },
  ],
  tip: 'Guarda il debito da tre lati: quanto pesa (debito netto/EBITDA), quanto costa (copertura degli interessi) e quando scade. Un solo indicatore non basta.',
});
