FQC(59, {
  intro: 'Un’azienda vale i flussi di cassa che produrrà, riportati a oggi: scopri come funziona il DCF e perché ogni ipotesi pesa sul risultato.',
  cards: [
    { t: 'L’idea di fondo', x: 'Il DCF (discounted cash flow) stima il valore di un’azienda come somma dei flussi di cassa che genererà in futuro, riportati a oggi. Un euro tra cinque anni vale meno di un euro oggi.', v: { k: 'steps', s: ['Prevedere i FCF', 'Scegliere il WACC', 'Valore terminale', 'Attualizzare e sommare'] } },
    { t: 'Attualizzare', x: 'Attualizzare significa chiedersi quanto vale oggi una somma futura, dato un rendimento richiesto r. Più il flusso è lontano nel tempo e più r è alto, più il suo valore attuale si riduce.', v: { k: 'formula', f: 'Valore attuale = flusso futuro ÷ (1 + r)^t', n: 'Es.: 110 € tra un anno al 10% valgono 110 ÷ 1,10 = 100 € oggi' } },
    { t: 'Il WACC', x: 'Il WACC è il costo medio ponderato del capitale: la media tra costo del capitale proprio e costo del debito dopo le imposte, pesati per la loro quota. Es.: 70% × 10% + 30% × 4% = 8,2%.', v: { k: 'pie', d: [['Capitale proprio', 70], ['Debito', 30]] } },
    { t: 'Il valore terminale', x: 'Oltre gli anni di previsione si stima un valore terminale, spesso con la formula di Gordon: FCF dell’anno successivo ÷ (WACC − g). Es.: 6 ÷ (8% − 2%) = 100. Pesa spesso più di metà del valore totale.', v: { k: 'stat', n: 'Oltre metà', l: 'quota del valore che spesso dipende dal valore terminale' } },
    { t: 'La sensibilità', x: 'Con un FCF di 6 e crescita al 2%, il valore terminale è 120 con WACC al 7%, 100 all’8% e circa 86 al 9%. Un punto di tasso sposta il risultato di oltre il 10%: per questo si fanno tabelle di sensibilità.', v: { k: 'bars', d: [['WACC 7%', 120], ['WACC 8%', 100], ['WACC 9%', 86]], u: 'mln €' } },
    { t: 'Dall’EV al valore per azione', x: 'Attualizzando i flussi al WACC si ottiene l’enterprise value. Sottraendo il debito netto si arriva al valore del capitale proprio; dividendo per il numero di azioni si ottiene il valore stimato per azione.', v: { k: 'icons', d: [['🏢', 'Enterprise value'], ['➖', 'Debito netto'], ['🧾', 'Valore dell’equity'], ['➗', 'Valore per azione']] } },
  ],
  terms: [
    ['DCF', 'Metodo che stima il valore come somma dei flussi di cassa futuri attualizzati.'],
    ['Attualizzazione', 'Calcolo del valore oggi di una somma futura, scontata a un rendimento richiesto.'],
    ['WACC', 'Costo medio ponderato del capitale: media dei costi di capitale proprio e debito.'],
    ['Costo del capitale proprio', 'Rendimento minimo richiesto dagli azionisti, spesso stimato con il CAPM.'],
    ['Valore terminale', 'Valore di tutti i flussi oltre l’orizzonte di previsione, condensato in un unico numero.'],
    ['Crescita perpetua', 'Tasso annuo, indicato con g, a cui si ipotizza crescano i flussi per sempre.'],
    ['Margine di sicurezza', 'Sconto tra valore stimato e prezzo pagato, che protegge dagli errori di stima.'],
    ['Analisi di sensibilità', 'Ricalcolo del valore al variare delle ipotesi chiave, come WACC e crescita.'],
  ],
  tf: [
    ['Un euro ricevuto tra cinque anni vale oggi meno di un euro.', true, 'Il denaro disponibile subito può essere investito e rendere: per questo i flussi futuri vanno attualizzati.'],
    ['Aumentando il WACC, il valore stimato con il DCF aumenta.', false, 'Un tasso di sconto più alto riduce il valore attuale dei flussi futuri: a parità di flussi, il valore scende.'],
    ['Nella formula di Gordon il tasso di crescita perpetua deve essere inferiore al WACC.', true, 'Se g fosse pari o superiore al WACC, la formula darebbe un valore infinito o negativo, senza senso economico.'],
    ['Il DCF dà un valore preciso e oggettivo, indipendente dalle ipotesi.', false, 'Il risultato dipende da previsioni di flussi, WACC e crescita: piccoli cambiamenti nelle ipotesi spostano molto il valore.'],
    ['Il valore terminale rappresenta spesso più di metà del valore totale stimato.', true, 'I flussi oltre l’orizzonte di previsione pesano molto: le ipotesi su g e WACC di lungo periodo sono decisive.'],
    ['Una crescita perpetua del 10% annuo è un’ipotesi prudente per un’azienda matura.', false, 'Nessuna azienda può crescere per sempre molto più dell’economia: per le aziende mature si usano tassi bassi.'],
    ['Attualizzando i flussi al WACC si ottiene l’enterprise value, non direttamente il valore delle azioni.', true, 'Il WACC remunera soci e creditori: per arrivare al valore delle azioni va sottratto il debito netto.'],
    ['Il costo del capitale proprio è di solito più basso del costo del debito.', false, 'Gli azionisti sono pagati dopo i creditori e corrono più rischi: chiedono un rendimento atteso più alto.'],
    ['Un margine di sicurezza aiuta a proteggersi dagli errori di stima del DCF.', true, 'Comprare solo a un prezzo ben sotto il valore stimato lascia spazio a previsioni rivelatesi troppo ottimistiche.'],
    ['Se il DCF indica un valore superiore al prezzo di borsa, il titolo salirà di sicuro.', false, 'Il DCF è una stima basata su ipotesi: il mercato può avere ragione, o restare lontano dalla tua stima a lungo.'],
  ],
  mcq: [
    { q: 'Quanto vale oggi un flusso di 121 € che riceverai tra due anni, con un tasso di sconto del 10%?', a: '100 €', w: ['121 €', '110 €', '96,80 €'], e: '121 ÷ 1,10² = 121 ÷ 1,21 = 100 €. Con 110 € si attualizza per un solo anno invece che per due.' },
    { q: 'Con FCF dell’anno successivo pari a 5, WACC al 9% e crescita perpetua al 4%, quanto vale il valore terminale?', a: '100', w: ['55,6', '38,5', '125'], e: 'Valore terminale = 5 ÷ (9% − 4%) = 5 ÷ 0,05 = 100.' },
    { q: 'Che cosa rappresenta il WACC?', a: 'Il costo medio di capitale proprio e debito', w: ['Il rendimento medio del mercato azionario', 'Il tasso di crescita perpetua dei flussi', 'Il tasso di riferimento fissato dalla BCE'], e: 'È la media dei costi di capitale proprio e debito (dopo le imposte), pesati per la loro quota nel finanziamento.' },
    { q: 'Con WACC all’8%, un analista alza la crescita perpetua dal 2% al 3%, a parità di FCF. Cosa succede al valore terminale?', a: 'Aumenta di circa il 20%', w: ['Aumenta di circa l’1%', 'Resta praticamente uguale', 'Diminuisce di circa il 20%'], e: 'Il denominatore passa dal 6% al 5%: il valore terminale si moltiplica per 6/5 = 1,2, cioè +20%. Ecco perché g va scelto con cura.' },
    { q: 'Quale di queste convinzioni sul DCF è un errore comune?', a: 'Dà un valore preciso e indiscutibile', w: ['Dipende dalle ipotesi sui flussi', 'Il WACC influenza molto il risultato', 'Il valore terminale pesa parecchio'], e: 'Il DCF è uno strumento di ragionamento: il risultato vale quanto le ipotesi che lo alimentano.' },
    { q: 'Un DCF dà un enterprise value di 1.000 milioni. Il debito netto è 300 milioni e le azioni sono 70 milioni. Qual è il valore per azione?', a: '10 €', w: ['14,3 €', '18,6 €', '4,3 €'], e: 'Valore dell’equity = 1.000 − 300 = 700 milioni; 700 ÷ 70 = 10 € per azione. Con 14,3 € si dimentica di sottrarre il debito.' },
    { q: 'Perché il costo del capitale proprio è di solito più alto del costo del debito?', a: 'Gli azionisti corrono più rischi dei creditori', w: ['Le azioni pagano sempre cedole fisse', 'Il debito non va mai rimborsato', 'Gli azionisti sono rimborsati per primi'], e: 'In caso di difficoltà i creditori vengono pagati prima: gli azionisti, più esposti, chiedono un rendimento atteso maggiore.' },
    { q: 'Il tuo DCF stima 20 € per azione e il titolo quota 19 €. Qual è l’approccio più prudente?', a: 'Riconoscere che lo sconto è troppo piccolo', w: ['Comprare subito: il titolo vale di più', 'Alzare la crescita per allargare lo sconto', 'Considerare il DCF una stima esatta'], e: 'Uno sconto del 5% è ben dentro il margine di errore di qualsiasi DCF: senza margine di sicurezza il vantaggio è illusorio.' },
  ],
  fill: [
    { s: 'Riportare a oggi il valore di un flusso futuro si chiama ___.', a: 'attualizzazione', w: ['capitalizzazione', 'ammortamento', 'rivalutazione'] },
    { s: 'Il tasso usato per scontare i flussi dell’intera azienda è di solito il ___.', a: 'WACC', w: ['ROE', 'PEG', 'P/E'] },
    { s: 'Nella formula di Gordon la crescita perpetua g deve essere ___ al WACC.', a: 'inferiore', w: ['superiore', 'uguale', 'doppia'] },
    { s: 'Il valore dei flussi oltre l’orizzonte di previsione si chiama valore ___.', a: 'terminale', w: ['nominale', 'contabile', 'facciale'] },
    { s: 'Comprare solo con un forte sconto sul valore stimato significa avere un margine di ___.', a: 'sicurezza', w: ['profitto', 'interesse', 'garanzia'] },
  ],
  order: [
    { q: 'Ordina i passaggi di una valutazione DCF', i: ['Prevedere i free cash flow', 'Calcolare il valore terminale', 'Attualizzare flussi e valore terminale', 'Sottrarre il debito netto dall’EV', 'Dividere per il numero di azioni'], e: 'Si prevedono i flussi, si stima il valore terminale, si attualizza tutto per avere l’EV, poi si passa all’equity e al valore per azione.' },
    { q: 'Ordina dal valore attuale più alto al più basso (tasso di sconto 10%)', i: ['100 € oggi', '100 € tra 1 anno', '100 € tra 5 anni', '100 € tra 10 anni'], e: 'A parità di importo, più il flusso è lontano, meno vale oggi: 100 € tra 10 anni al 10% valgono oggi circa 39 €.' },
  ],
  cat: [
    { q: 'A parità del resto, questa modifica alza o abbassa il valore stimato?', g: [['Lo alza', ['WACC più basso', 'Crescita perpetua più alta', 'Margini futuri più alti']], ['Lo abbassa', ['WACC più alto', 'Capex futuri più elevati', 'Crescita perpetua più bassa']]] },
    { q: 'Ingrediente del WACC o dei flussi di cassa?', g: [['WACC', ['Costo del capitale proprio', 'Costo del debito dopo le imposte', 'Pesi di debito ed equity']], ['Flussi di cassa', ['Crescita dei ricavi', 'Margini operativi', 'Investimenti in impianti', 'Variazione del circolante']]] },
  ],
  scen: [
    { s: 'Lorenzo, 34 anni, costruisce un DCF su Alfa Spa: ipotizza ricavi in crescita del 15% l’anno per dieci anni e una crescita perpetua del 5%. Ottiene 50 € per azione, contro un prezzo di 30 €.', q: 'Cosa dovrebbe fare Lorenzo?', o: [
      { t: 'Comprare: il DCF indica un forte sconto', ok: false, f: 'Lo sconto nasce da ipotesi molto ottimistiche: con premesse aggressive, qualsiasi titolo sembra a buon mercato.' },
      { t: 'Rivedere le ipotesi e provare scenari più prudenti', ok: true, f: 'Una crescita del 15% per dieci anni e un g del 5% sono ipotesi ambiziose: con scenari prudenti lo sconto potrebbe sparire.' },
      { t: 'Alzare il WACC fino a far coincidere valore e prezzo', ok: false, f: 'Aggiustare il tasso per ottenere il risultato voluto svuota il metodo: le ipotesi vanno motivate, non piegate.' },
    ] },
    { s: 'Beatrice, 45 anni, legge un report che fissa per Beta Spa un valore di 40 € per azione con un DCF. Nelle note scopre che l’85% del valore dipende dal valore terminale.', q: 'Come legge quel numero?', o: [
      { t: 'Lo accetta: l’ha calcolato un professionista', ok: false, f: 'Anche i professionisti usano ipotesi: se l’85% dipende dal lungo periodo, quelle ipotesi vanno capite.' },
      { t: 'Lo scarta: un DCF non serve a nulla', ok: false, f: 'Il DCF resta utile per ragionare sui fattori che creano valore: va solo letto con spirito critico.' },
      { t: 'Verifica le ipotesi su crescita perpetua e WACC', ok: true, f: 'Con l’85% del valore nel terminale, piccoli cambi di g o WACC spostano molto il prezzo obiettivo: sono il punto da controllare.' },
    ] },
    { s: 'Matteo, 28 anni, chiede a due analisti il WACC giusto per Gamma Spa. Uno usa il 7%, l’altro il 9%, e i valori risultanti differiscono di oltre il 30%. Matteo vorrebbe sapere quale sia «quello vero».', q: 'Qual è l’approccio migliore?', o: [
      { t: 'Usare un intervallo di WACC e valori, non un solo numero', ok: true, f: 'Una tabella di sensibilità mostra l’intervallo plausibile: se il prezzo è conveniente anche nello scenario prudente, è più robusto.' },
      { t: 'Scegliere il WACC più basso, che dà il valore più alto', ok: false, f: 'Scegliere l’ipotesi più favorevole porta a sopravvalutare: è il contrario della prudenza.' },
      { t: 'Fare la media e considerarla il valore esatto', ok: false, f: 'La media non rende il risultato esatto: l’incertezza resta e va esplicitata con più scenari.' },
    ] },
    { s: 'Gabriella, 57 anni, ottiene con un DCF un enterprise value di 2 miliardi per Delta Spa, che ha 1,2 miliardi di debito netto e 100 milioni di azioni. Divide 2 miliardi per 100 milioni e conclude che il titolo vale 20 €.', q: 'Dove sbaglia?', o: [
      { t: 'Non sbaglia: l’EV diviso le azioni dà il valore per azione', ok: false, f: 'L’EV appartiene a soci e creditori insieme: agli azionisti spetta solo ciò che resta dopo il debito.' },
      { t: 'Doveva sommare il debito netto all’EV', ok: false, f: 'Sommare il debito gonfierebbe ancora di più il valore: il debito va tolto, perché spetta ai creditori.' },
      { t: 'Doveva prima sottrarre il debito netto: il valore è 8 €', ok: true, f: '2 miliardi − 1,2 miliardi = 800 milioni di equity, cioè 8 € per azione: dimenticare il debito porta a un errore enorme.' },
    ] },
  ],
  tip: 'Tratta il DCF come un ragionamento, non come un oracolo: prova più scenari, osserva come cambia il valore e pretendi un margine di sicurezza.',
});
