FQC(60, {
  intro: 'Perché alcune aziende difendono i profitti per decenni e altre no? Scopri le fonti del vantaggio competitivo e come riconoscerle nei numeri.',
  cards: [
    { t: 'Il fossato attorno al castello', x: 'Il moat, termine reso popolare da Warren Buffett, è un vantaggio competitivo duraturo che protegge i profitti dai concorrenti, come un fossato protegge un castello. Senza moat, i profitti alti attirano rivali che li erodono.', v: { k: 'icons', d: [['🏷️', 'Brand'], ['🔒', 'Costi di switching'], ['🕸️', 'Effetti rete'], ['🏭', 'Scala e costi']] } },
    { t: 'Brand e beni immateriali', x: 'Un marchio forte permette di vendere a prezzi più alti o di essere scelti per fiducia. Anche brevetti e licenze creano barriere, ma i brevetti hanno una scadenza e le licenze possono essere revocate o non rinnovate.', v: { k: 'vs', a: ['Marchio forte', 'Clienti disposti a pagare di più'], b: ['Prodotto anonimo', 'Si compete solo sul prezzo'] } },
    { t: 'I costi di switching', x: 'Se cambiare fornitore costa tempo, denaro o rischi, il cliente tende a restare. Un’azienda che ha formato i dipendenti su un software gestionale e vi ha caricato anni di dati difficilmente lo sostituisce.', v: { k: 'scale', a: 'Facile cambiare', b: 'Difficile cambiare', d: [['Marca di acqua', 5], ['Conto corrente', 50], ['Software gestionale', 88]] } },
    { t: 'Gli effetti rete', x: 'Un servizio ha effetti rete quando diventa più utile all’aumentare degli utenti: marketplace, circuiti di pagamento, borse valori. Chi parte in vantaggio tende ad attirare ancora più utenti, e il divario cresce.', v: { k: 'formula', f: 'Collegamenti possibili = n × (n − 1) ÷ 2', n: 'Es.: 10 utenti → 45 collegamenti; 100 utenti → 4.950' } },
    { t: 'Scala e costi bassi', x: 'Con costi fissi elevati, chi produce di più li spalma su più unità. Con 40.000 € di costi fissi e 10 € variabili a pezzo, il costo unitario è 50 € su 1.000 pezzi, ma 10,40 € su 100.000.', v: { k: 'bars', d: [['1.000 pezzi', 50], ['10.000 pezzi', 14], ['100.000 pezzi', 10.4]], u: '€' } },
    { t: 'Come si vede nei conti', x: 'Un moat lascia tracce nei numeri: ROIC stabilmente sopra il costo del capitale, margini che reggono nelle crisi, quote di mercato stabili e la capacità di alzare i prezzi senza perdere clienti.', v: { k: 'stat', n: 'ROIC > WACC', l: 'per molti anni, anche nelle fasi difficili' } },
  ],
  terms: [
    ['Moat', 'Vantaggio competitivo duraturo che protegge i profitti di un’azienda dai concorrenti.'],
    ['Potere di prezzo', 'Capacità di alzare i prezzi senza perdere una quota significativa di clienti.'],
    ['Costi di switching', 'Costi economici o pratici che un cliente sostiene per passare a un concorrente.'],
    ['Effetto rete', 'Situazione in cui un prodotto diventa più utile man mano che aumentano gli utenti.'],
    ['Economie di scala', 'Riduzione del costo unitario grazie all’aumento dei volumi prodotti.'],
    ['Barriere all’ingresso', 'Ostacoli che rendono difficile a nuovi concorrenti entrare in un mercato.'],
    ['Beni immateriali', 'Risorse non fisiche, come marchi, brevetti e licenze, che possono proteggere i profitti.'],
    ['Disruption', 'Innovazione che cambia le regole di un settore e può rendere inutile un vantaggio esistente.'],
  ],
  tf: [
    ['Un’azienda con un moat solido tende ad avere un ROIC stabilmente superiore al costo del capitale.', true, 'Il vantaggio impedisce ai concorrenti di erodere i rendimenti: per questo restano alti per molti anni.'],
    ['Un’azienda che cresce velocemente ha per forza un moat.', false, 'La crescita può venire da un mercato in espansione o da prezzi aggressivi: senza barriere, i concorrenti arriveranno.'],
    ['Gli effetti rete rendono un servizio più utile all’aumentare dei suoi utenti.', true, 'Più utenti attirano altri utenti: per un nuovo concorrente diventa difficile convincerli a spostarsi.'],
    ['Un brevetto garantisce un vantaggio competitivo per sempre.', false, 'I brevetti hanno una durata limitata: alla scadenza i concorrenti possono copiare il prodotto, come accade con i farmaci generici.'],
    ['Anche un’azienda con un ottimo moat può essere un cattivo investimento se la paghi troppo.', true, 'Il moat riguarda la qualità dell’azienda, non il prezzo: un multiplo eccessivo può annullare i rendimenti futuri.'],
    ['I costi di switching sono solo costi monetari, come una penale di uscita.', false, 'Contano anche tempo, formazione, rischio di errori e dati da migrare: spesso pesano più di una penale.'],
    ['Un moat può erodersi a causa di innovazioni tecnologiche o nuove regole.', true, 'Una nuova tecnologia o un cambio normativo possono rendere irrilevante un vantaggio che sembrava solido.'],
    ['Avere la quota di mercato più alta significa sempre avere un moat.', false, 'Una quota alta può essere temporanea o comprata con prezzi in perdita: conta se è difendibile con rendimenti alti.'],
    ['In un settore con costi fissi elevati, le economie di scala possono favorire le aziende più grandi.', true, 'Distribuendo i costi fissi su più unità, il grande produttore ha costi unitari più bassi e può battere i rivali sul prezzo.'],
    ['Un marchio famoso crea automaticamente potere di prezzo.', false, 'Essere conosciuti non basta: il moat c’è se i clienti accettano di pagare di più o scelgono il marchio anche a prezzo pieno.'],
  ],
  mcq: [
    { q: 'Quale di questi è un esempio di moat basato sui costi di switching?', a: 'Un software gestionale integrato in azienda', w: ['Un supermercato con prezzi molto bassi', 'Un nuovo marchio di bevande gassate', 'Una campagna pubblicitaria intensa'], e: 'Cambiare gestionale richiede migrare dati, formare persone e rischiare errori: i clienti tendono a restare.' },
    { q: 'Quale attività beneficia di più degli effetti rete?', a: 'Un marketplace tra venditori e acquirenti', w: ['Un piccolo panificio di quartiere', 'Un’impresa di pulizie della città', 'Un produttore di bulloni industriali'], e: 'Più venditori attirano più acquirenti e viceversa: la piattaforma diventa più utile a ogni nuovo utente.' },
    { q: 'Quale dato di bilancio suggerisce più di tutti la presenza di un moat?', a: 'ROIC alto e stabile per molti anni', w: ['Ricavi raddoppiati in un solo anno', 'Utile record grazie a una cessione', 'Debito molto basso per un anno'], e: 'Rendimenti sul capitale alti e duraturi indicano che i concorrenti non riescono a eroderli: è la traccia tipica di un moat.' },
    { q: 'Alfa Spa alza i prezzi del 10% e perde solo l’1% dei clienti. Che cosa dimostra?', a: 'Un forte potere di prezzo', w: ['Un’elevata leva finanziaria', 'Un forte effetto di diluizione', 'Una bassa rotazione dell’attivo'], e: 'Se i clienti accettano aumenti senza andarsene, l’azienda ha un vantaggio che i concorrenti non riescono a sfidare.' },
    { q: 'Quale di queste convinzioni sul moat è un errore comune?', a: 'Un buon moat giustifica ogni prezzo', w: ['Un moat può erodersi nel tempo', 'I brevetti hanno una scadenza', 'Gli effetti rete creano barriere'], e: 'La qualità dell’azienda non giustifica qualsiasi prezzo: se paghi troppo, anche un’ottima azienda può rendere poco.' },
    { q: 'Perché le economie di scala possono creare un vantaggio competitivo?', a: 'Abbassano il costo per unità prodotta', w: ['Aumentano i costi fissi dei concorrenti', 'Eliminano la necessità di investire', 'Garantiscono la crescita dei ricavi'], e: 'Spalmando i costi fissi su volumi maggiori il costo unitario scende: il leader può vendere a prezzi che i piccoli non reggono.' },
    { q: 'Qual è la minaccia principale per un moat basato su un brevetto farmaceutico?', a: 'La scadenza del brevetto', w: ['L’aumento dei pazienti', 'La crescita del mercato', 'Il calo dei costi di produzione'], e: 'Alla scadenza arrivano i generici a prezzi più bassi: i ricavi del farmaco possono calare molto in poco tempo.' },
    { q: 'Beta Spa ha margini altissimi in un settore senza barriere all’ingresso. Che cosa è più probabile nel tempo?', a: 'Nuovi concorrenti erodono i margini', w: ['I margini salgono ancora per anni', 'I concorrenti ignorano il settore', 'I clienti accettano prezzi più alti'], e: 'Profitti alti senza protezioni attirano rivali: la concorrenza tende a riportare i rendimenti verso la media.' },
  ],
  fill: [
    { s: 'Il termine ___ indica il vantaggio competitivo che protegge i profitti di un’azienda.', a: 'moat', w: ['spread', 'rally', 'leverage'] },
    { s: 'Un servizio che diventa più utile all’aumentare degli utenti beneficia dell’effetto ___.', a: 'rete', w: ['leva', 'scala', 'prezzo'] },
    { s: 'La capacità di alzare i prezzi senza perdere clienti si chiama potere di ___.', a: 'prezzo', w: ['acquisto', 'scala', 'voto'] },
    { s: 'Con costi fissi elevati, le economie di ___ favoriscono i produttori più grandi.', a: 'scala', w: ['rete', 'tempo', 'mercato'] },
    { s: 'I costi di ___ trattengono i clienti, perché passare a un concorrente è costoso o rischioso.', a: 'switching', w: ['marketing', 'listing', 'trading'] },
  ],
  order: [
    { q: 'Ordina il ciclo dei profitti in un settore senza moat', i: ['Un’azienda ottiene margini alti', 'I profitti attirano nuovi concorrenti', 'L’offerta aumenta e i prezzi calano', 'I margini tornano verso la media'], e: 'Senza barriere, la concorrenza erode i rendimenti elevati: è proprio il meccanismo che un moat serve a bloccare.' },
    { q: 'Ordina i passi per valutare un moat', i: ['Individuare la fonte del vantaggio', 'Verificarla nei numeri: ROIC e margini', 'Stimarne la durata e le minacce', 'Confrontare il prezzo con il valore'], e: 'Prima capisci da dove nasce il vantaggio, poi lo verifichi nei conti, ne stimi la durata e solo alla fine ti chiedi se il prezzo è giusto.' },
  ],
  cat: [
    { q: 'Effetto rete o costi di switching?', g: [['Effetto rete', ['Social network', 'Marketplace online', 'Circuito di pagamento con carte']], ['Costi di switching', ['Software gestionale aziendale', 'Sistema di cartelle cliniche di un ospedale', 'Macchinari con ricambi proprietari']]] },
    { q: 'Segnale di moat o falso segnale?', g: [['Segnale di moat', ['ROIC alto per molti anni', 'Margini stabili anche in recessione', 'Prezzi aumentati senza perdere clienti']], ['Falso segnale', ['Ricavi in crescita per un solo anno', 'Utile gonfiato da una cessione', 'Quota di mercato comprata con sconti in perdita']]] },
  ],
  scen: [
    { s: 'Edoardo, 40 anni, nota che Alfa Spa ha avuto margini eccezionali negli ultimi due anni grazie a un boom della domanda. Il settore non ha barriere all’ingresso e diversi concorrenti stanno aprendo nuovi impianti.', q: 'Come valuta quei margini?', o: [
      { t: 'Li proietta uguali per i prossimi dieci anni', ok: false, f: 'Senza barriere, i nuovi impianti dei concorrenti aumenteranno l’offerta e tenderanno a comprimere prezzi e margini.' },
      { t: 'Li considera probabilmente temporanei', ok: true, f: 'Margini alti nati da un boom, in un settore aperto, attirano concorrenza: è prudente stimare un ritorno verso la media.' },
      { t: 'Li considera la prova di un moat solido', ok: false, f: 'Un moat si vede nella durata dei rendimenti, non in due anni favorevoli: qui manca una barriera che li protegga.' },
    ] },
    { s: 'Camilla, 33 anni, è convinta che Beta Spa, piattaforma con forti effetti rete, sia un’azienda eccezionale. Il titolo però quota 80 volte gli utili e la crescita attesa è in rallentamento. Camilla pensa che la qualità si paghi sempre.', q: 'Qual è il ragionamento più equilibrato?', o: [
      { t: 'Comprare a qualunque prezzo: la qualità vince sempre', ok: false, f: 'Anche le aziende migliori possono deludere come investimento se il prezzo sconta già ogni scenario positivo.' },
      { t: 'Separare la qualità dell’azienda dal prezzo da pagare', ok: true, f: 'Il moat è reale, ma con P/E 80 e crescita in calo il prezzo lascia poco margine: va valutato quanto valore c’è già nel prezzo.' },
      { t: 'Scartare Beta: un P/E alto è sempre una bolla', ok: false, f: 'Un P/E alto non è automaticamente una bolla: va confrontato con la crescita e la durata del vantaggio.' },
    ] },
    { s: 'Simone, 50 anni, valuta Gamma Spa, società farmaceutica molto redditizia. Scopre che il 70% degli utili arriva da un solo farmaco, il cui brevetto scade tra due anni.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che gli utili attuali dureranno per sempre', ok: false, f: 'Il vantaggio è legato al brevetto: alla scadenza arrivano i generici e i ricavi del farmaco possono crollare.' },
      { t: 'Che la redditività alta prova un moat permanente', ok: false, f: 'Il moat qui ha una data di scadenza scritta: la redditività di oggi non dice molto su quella fra tre anni.' },
      { t: 'Il calo degli utili dopo la scadenza e cosa c’è in sviluppo', ok: true, f: 'Conta quanto si perderà con i generici e se i nuovi farmaci in sviluppo potranno sostituire quei profitti.' },
    ] },
    { s: 'Giorgia, 26 anni, legge che Delta Spa, catena di negozi, vanta un «marchio fortissimo». Dopo un aumento dei prezzi del 5%, però, ha perso molti clienti a favore di concorrenti più economici.', q: 'Che conclusione trae Giorgia?', o: [
      { t: 'Il marchio è noto, ma non dà un vero potere di prezzo', ok: true, f: 'Se un piccolo aumento fa scappare i clienti, il marchio non crea un vantaggio difendibile: il moat dichiarato è debole.' },
      { t: 'Il moat è confermato dalla notorietà del marchio', ok: false, f: 'Essere conosciuti non basta: il test è se i clienti restano anche quando paghi di più.' },
      { t: 'I clienti persi sono irrilevanti per il moat', ok: false, f: 'La perdita di clienti dopo un rincaro è proprio la prova che manca potere di prezzo.' },
    ] },
  ],
  tip: 'Davanti a un’azienda chiediti: perché un concorrente con molti soldi non riesce a copiarla? Se non trovi una risposta chiara, forse il moat non c’è.',
});
