FQC(61, {
  intro: 'Linee, barre e candele: impari a leggere apertura, massimo, minimo e chiusura e a riconoscere doji, martello ed engulfing.',
  cards: [
    { t: 'Tre modi di disegnare il prezzo', x: 'Il grafico a linea unisce di solito le sole chiusure; quello a barre (OHLC) e quello a candele mostrano anche apertura, massimo e minimo di ogni periodo. Le candele rendono più immediato capire chi ha prevalso.', v: { k: 'icons', d: [['📈', 'Linea: solo chiusure'], ['📊', 'Barre OHLC'], ['🕯️', 'Candele giapponesi']] } },
    { t: 'OHLC: quattro prezzi per periodo', x: 'Ogni candela riassume un intervallo (1 minuto, 1 giorno, 1 settimana) con quattro prezzi: Open, High, Low, Close. Cambiando timeframe, la stessa storia appare con un livello di dettaglio diverso.', v: { k: 'steps', s: ['Open: apertura', 'High: massimo', 'Low: minimo', 'Close: chiusura'] } },
    { t: 'Corpo e ombre', x: 'Il corpo va dall’apertura alla chiusura: verde (o bianco) se la chiusura è più alta, rosso (o nero) se è più bassa. Le ombre, o stoppini, arrivano fino al massimo e al minimo del periodo.', v: { k: 'vs', a: ['Candela rialzista', 'Chiusura sopra l’apertura'], b: ['Candela ribassista', 'Chiusura sotto l’apertura'] } },
    { t: 'Doji: l’indecisione', x: 'Una doji ha apertura e chiusura quasi uguali: corpo sottilissimo, ombre variabili. Segnala equilibrio tra compratori e venditori; da sola non indica una direzione, conta il contesto in cui compare.', v: { k: 'formula', f: 'Doji: chiusura ≈ apertura', n: 'Es.: apre a 10,00 €, chiude a 10,01 €' } },
    { t: 'Il martello', x: 'Corpo piccolo in alto e ombra inferiore lunga almeno il doppio del corpo, dopo un ribasso: i venditori hanno spinto giù, ma i compratori hanno recuperato. È un possibile segnale di inversione, da confermare.', v: { k: 'stat', n: '≥ 2×', l: 'lunghezza dell’ombra inferiore rispetto al corpo nel martello' } },
    { t: 'Engulfing: la candela che ingloba', x: 'Nell’engulfing rialzista, dopo un ribasso, il corpo di una candela verde ingloba del tutto il corpo rosso precedente; il ribassista è l’opposto. Pesa di più con volumi alti e in zone chiave, ma non è mai una certezza.', v: { k: 'scale', a: 'Segnale debole', b: 'Segnale più solido', d: [['Figura isolata', 20], ['Su un supporto', 55], ['Supporto + volumi + conferma', 85]] } },
  ],
  terms: [
    ['OHLC', 'Sigla dei quattro prezzi di un periodo: apertura, massimo, minimo e chiusura.'],
    ['Corpo', 'Parte piena della candela, compresa tra il prezzo di apertura e quello di chiusura.'],
    ['Ombra', 'Tratto sottile sopra o sotto il corpo che raggiunge il massimo o il minimo del periodo.'],
    ['Doji', 'Candela con apertura e chiusura quasi coincidenti: segnala indecisione del mercato.'],
    ['Martello', 'Candela con corpo piccolo in alto e lunga ombra inferiore, che compare dopo un ribasso.'],
    ['Engulfing', 'Figura a due candele in cui il corpo della seconda copre interamente quello della prima.'],
    ['Timeframe', 'Durata del periodo rappresentato da ogni candela o barra: minuti, ore, giorni, settimane.'],
    ['Shooting star', 'Candela con corpo piccolo in basso e lunga ombra superiore dopo un rialzo: possibile esaurimento.'],
  ],
  tf: [
    ['Una candela con chiusura sopra l’apertura ha di solito il corpo verde o bianco.', true, 'Il corpo chiaro o verde indica che nel periodo il prezzo ha chiuso più in alto di dove aveva aperto.'],
    ['Il classico grafico a linea mostra massimo e minimo di ogni giornata.', false, 'Il grafico a linea collega di norma solo le chiusure; massimi e minimi si vedono su barre e candele.'],
    ['Le ombre di una candela indicano il massimo e il minimo toccati nel periodo.', true, 'Partono dal corpo e arrivano fino agli estremi raggiunti dal prezzo in quell’intervallo.'],
    ['Una doji annuncia sempre un’inversione imminente del trend.', false, 'La doji segnala indecisione: può precedere un’inversione, una pausa o la ripresa del trend. Servono contesto e conferma.'],
    ['Il martello è letto come possibile segnale di inversione soprattutto quando compare dopo un ribasso.', true, 'Dopo un calo mostra il rifiuto dei prezzi bassi; la stessa forma dopo un rialzo si chiama impiccato e ha un’altra lettura.'],
    ['Nella convenzione standard, una candela rossa indica una chiusura sotto quella del giorno prima.', false, 'Il colore confronta chiusura e apertura dello stesso periodo: una candela rossa può anche chiudere sopra la chiusura precedente.'],
    ['Lo stesso titolo può essere in rialzo sul grafico giornaliero e in ribasso su quello a 15 minuti.', true, 'Ogni timeframe racconta una parte della storia: conviene partire da quello coerente con il tuo orizzonte.'],
    ['Un engulfing rialzista garantisce un rialzo nelle sedute successive.', false, 'Nessuna figura a candele garantisce nulla: al massimo rende un movimento più probabile. Servono conferme e uno stop.'],
    ['In un engulfing rialzista il corpo verde copre interamente il corpo rosso precedente.', true, 'È la definizione: apre sotto la chiusura precedente e chiude sopra la sua apertura, così il nuovo corpo ingloba il vecchio.'],
    ['Una candela con ombre lunghe e corpo minuscolo indica un periodo in cui il prezzo si è mosso poco.', false, 'Le ombre lunghe dicono che il prezzo ha oscillato molto; il corpo piccolo dice solo che ha chiuso vicino all’apertura.'],
  ],
  mcq: [
    { q: 'Che cosa rappresenta il corpo di una candela?', a: 'L’intervallo tra apertura e chiusura', w: ['L’intervallo tra massimo e minimo', 'La media dei prezzi del periodo', 'Il volume scambiato nel periodo'], e: 'Il corpo è delimitato da apertura e chiusura; massimo e minimo sono indicati dalle ombre.' },
    { q: 'Una candela apre a 20 €, tocca 22 €, scende a 19 € e chiude a 21,50 €. Com’è?', a: 'Rialzista, con corpo da 20 a 21,50 €', w: ['Ribassista, con corpo da 22 a 19 €', 'Rialzista, con corpo da 19 a 22 €', 'Una doji, perché il prezzo è risalito'], e: 'Chiude sopra l’apertura, quindi è rialzista: il corpo va da 20 a 21,50 €, le ombre arrivano a 22 € e a 19 €.' },
    { q: 'Che cosa segnala tipicamente una doji?', a: 'Equilibrio tra compratori e venditori', w: ['Netta prevalenza dei compratori', 'Un volume di scambi eccezionale', 'Una seduta con orario ridotto'], e: 'Apertura e chiusura quasi uguali: a fine periodo nessuno dei due schieramenti ha prevalso.' },
    { q: 'Qual è la differenza tra martello e impiccato?', a: 'Hanno la stessa forma ma compaiono in contesti opposti', w: ['Il martello ha l’ombra lunga in alto, l’impiccato in basso', 'Il martello è una figura a due candele, l’impiccato a una', 'Il martello vale solo sul settimanale, l’impiccato sul giornaliero'], e: 'Corpo piccolo in alto e lunga ombra inferiore: dopo un ribasso è un martello, dopo un rialzo un impiccato.' },
    { q: 'In quale grafico ogni periodo è una linea verticale con un trattino a sinistra e uno a destra?', a: 'Nel grafico a barre OHLC', w: ['Nel grafico a linea', 'Nel grafico ad area', 'Nel grafico a torta'], e: 'Il trattino a sinistra indica l’apertura, quello a destra la chiusura; la linea verticale va dal minimo al massimo.' },
    { q: 'Quando un engulfing ribassista è considerato più significativo?', a: 'Dopo un rialzo, vicino a una resistenza e con volumi alti', w: ['In qualunque punto del grafico, a prescindere dal contesto', 'In un mercato laterale e con volumi molto bassi', 'Dopo un forte ribasso, vicino a un supporto'], e: 'Una figura di inversione conta di più se c’è un movimento da invertire e se cade in una zona chiave con partecipazione elevata.' },
    { q: 'Quale di questi comportamenti è un errore tipico con le candele?', a: 'Leggere una candela isolata ignorando trend e contesto', w: ['Usare un timeframe coerente con il proprio orizzonte', 'Aspettare la chiusura prima di valutare la candela', 'Combinare la candela con supporti e volumi'], e: 'Una candela riassume un solo periodo: isolata dal contesto produce molti falsi segnali.' },
    { q: 'Perché conviene aspettare la chiusura di una candela prima di interpretarla?', a: 'Perché fino alla chiusura forma e colore possono cambiare', w: ['Perché prima della chiusura il grafico non è visibile', 'Perché le candele si formano solo a mercato chiuso', 'Perché la chiusura coincide sempre con il massimo'], e: 'Un martello a metà seduta può trasformarsi in una candela rossa piena: la figura è definita solo a periodo concluso.' },
  ],
  fill: [
    { s: 'La sigla ___ indica apertura, massimo, minimo e chiusura di un periodo.', a: 'OHLC', w: ['RSI', 'MACD', 'SMA'] },
    { s: 'Una ___ ha apertura e chiusura quasi identiche e segnala indecisione.', a: 'doji', w: ['marubozu', 'engulfing', 'candela piena'] },
    { s: 'Il massimo e il minimo del periodo sono indicati dalle ___ della candela.', a: 'ombre', w: ['bande', 'medie', 'barre di volume'] },
    { s: 'Il ___ ha corpo piccolo in alto, lunga ombra inferiore e compare dopo un ribasso.', a: 'martello', w: ['marubozu', 'gap', 'pivot'] },
    { s: 'Nell’engulfing rialzista il corpo verde ___ completamente il corpo rosso precedente.', a: 'ingloba', w: ['dimezza', 'ripete', 'precede'] },
  ],
  order: [
    { q: 'Ordina i prezzi di una candela rialzista dal più alto al più basso', i: ['Massimo', 'Chiusura', 'Apertura', 'Minimo'], e: 'In una candela rialzista la chiusura sta sopra l’apertura; le ombre arrivano fino al massimo in alto e al minimo in basso.' },
    { q: 'Ordina le fasi di una seduta che forma un martello', i: ['Apertura della seduta', 'Forte discesa dei prezzi', 'Recupero dei compratori', 'Chiusura vicino all’apertura, in alto'], e: 'Il martello nasce da un calo durante la seduta poi riassorbito: la lunga ombra inferiore registra la discesa respinta.' },
  ],
  cat: [
    { q: 'Candela rialzista o ribassista?', g: [['Rialzista', ['Apre a 10 €, chiude a 11 €', 'Apre a 50 €, chiude a 52 €', 'Apre a 7 €, chiude a 7,40 €']], ['Ribassista', ['Apre a 10 €, chiude a 9 €', 'Apre a 30 €, chiude a 28 €', 'Apre a 7 €, chiude a 6,60 €']]] },
    { q: 'Informazione mostrata dal corpo o dalle ombre?', g: [['Corpo', ['Prezzo di apertura', 'Prezzo di chiusura', 'Colore rialzista o ribassista']], ['Ombre', ['Massimo del periodo', 'Minimo del periodo', 'Prezzi toccati ma poi respinti']]] },
  ],
  scen: [
    { s: 'Marco, 34 anni, segue un titolo del FTSE MIB in forte rialzo da settimane. Sul grafico giornaliero compare una doji e un amico gli scrive che è il segnale del crollo.', q: 'Cosa fa Marco?', o: [
      { t: 'Osserva le candele successive e il contesto prima di decidere', ok: true, f: 'La doji segnala indecisione, non una direzione: una conferma, come una chiusura sotto il minimo della doji, rende la lettura più solida.' },
      { t: 'Vende subito tutto: la doji annuncia il crollo', ok: false, f: 'Una doji può essere solo una pausa del trend. Agire su una singola candela espone a molti falsi segnali.' },
      { t: 'Smette di guardare le candele: si sono rivelate inutili', ok: false, f: 'Le candele sono uno strumento di lettura, non un oracolo: il problema è pretendere certezze, non lo strumento in sé.' },
    ] },
    { s: 'Giulia, 27 anni, investe con un piano di accumulo su un ETF azionario con orizzonte di 20 anni. Una sera apre il grafico a 5 minuti e vede una serie di candele rosse lunghe.', q: 'Come dovrebbe leggere quel grafico?', o: [
      { t: 'Lo ridimensiona: per il suo orizzonte contano i timeframe lunghi', ok: true, f: 'Il timeframe va scelto in base all’orizzonte: per obiettivi ventennali le candele a 5 minuti sono quasi solo rumore.' },
      { t: 'Sospende il piano finché il 5 minuti non torna verde', ok: false, f: 'Il grafico a 5 minuti non dice nulla di utile su un obiettivo di 20 anni e cambia colore di continuo.' },
      { t: 'Vende l’ETF e lo ricompra quando compare un martello', ok: false, f: 'Inseguire le figure di breve con un investimento di lungo aggiunge costi, tasse ed errori di tempismo.' },
    ] },
    { s: 'Paolo, 45 anni, vede un engulfing rialzista su un supporto importante, con volumi doppi rispetto alla media. Vuole entrare sul titolo.', q: 'Qual è l’approccio più razionale?', o: [
      { t: 'Entra con una posizione dimensionata e uno stop sotto il minimo della figura', ok: true, f: 'Il contesto è favorevole, ma la figura resta probabilistica: lo stop sotto il minimo definisce dove l’idea è smentita.' },
      { t: 'Entra con tutto il capitale disponibile: la figura è perfetta', ok: false, f: 'Anche le figure migliori falliscono: puntare tutto su un singolo segnale espone a una perdita che può pesare molto.' },
      { t: 'Entra senza stop, perché i volumi confermano già la figura', ok: false, f: 'I volumi rafforzano il segnale ma non lo rendono certo: senza stop una perdita piccola può diventare grande.' },
    ] },
    { s: 'Sara, 52 anni, alle 15:00 nota che sul grafico giornaliero di un titolo si sta formando un martello dopo un lungo ribasso. La Borsa chiude alle 17:30.', q: 'Cosa le conviene fare?', o: [
      { t: 'Aspettare la chiusura per vedere se la figura si completa', ok: true, f: 'Fino alla chiusura il martello può trasformarsi in un’altra candela: la figura esiste solo a periodo concluso.' },
      { t: 'Comprare subito, prima che il martello si completi', ok: false, f: 'Anticipare la figura significa agire su qualcosa che ancora non esiste: il prezzo può tornare sui minimi entro sera.' },
      { t: 'Comprare ora e raddoppiare se domani il prezzo scende', ok: false, f: 'Mediare al ribasso senza un piano aumenta l’esposizione proprio quando l’idea si rivela sbagliata.' },
    ] },
  ],
  tip: 'Una candela è una frase, non un libro: leggila con trend, livelli chiave e volumi, aspetta la chiusura e decidi prima dove uscire se hai torto.',
});
