FQC(62, {
  intro: 'Massimi e minimi crescenti o decrescenti, linee di tendenza e canali: impari a riconoscere la direzione del mercato e quando si indebolisce.',
  cards: [
    { t: 'Che cos’è un trend', x: 'Un trend rialzista è una sequenza di massimi e minimi crescenti; uno ribassista, di massimi e minimi decrescenti. Se la sequenza non è chiara, il mercato è laterale e oscilla in un intervallo.', v: { k: 'icons', d: [['↗️', 'Rialzista: massimi e minimi crescenti'], ['↘️', 'Ribassista: massimi e minimi decrescenti'], ['↔️', 'Laterale: oscillazione in un range']] } },
    { t: 'Tracciare una linea di tendenza', x: 'In un trend rialzista la linea unisce almeno due minimi crescenti, in uno ribassista almeno due massimi decrescenti. Un terzo contatto la rende più significativa, ma la scelta dei punti resta in parte soggettiva.', v: { k: 'steps', s: ['Individua due minimi crescenti', 'Uniscili con una retta', 'Prolungala verso destra', 'Osserva il terzo contatto'] } },
    { t: 'Pendenza e sostenibilità', x: 'Una linea molto ripida descrive un movimento rapido ma spesso poco sostenibile: tende a essere violata presto, anche solo da una pausa laterale. Linee più moderate di solito reggono più a lungo.', v: { k: 'scale', a: 'Pendenza dolce', b: 'Pendenza estrema', d: [['Trend regolare', 25], ['Trend accelerato', 60], ['Movimento parabolico', 92]] } },
    { t: 'Dalla linea al canale', x: 'Tracciando una parallela alla linea di tendenza sul lato opposto del prezzo ottieni un canale. Aiuta a vedere quando il prezzo è nella parte alta, più tirata, o in quella bassa del movimento.', v: { k: 'vs', a: ['Linea di tendenza', 'Unisce i minimi (o i massimi) principali'], b: ['Canale', 'Aggiunge la parallela sul lato opposto'] } },
    { t: 'Trend dentro altri trend', x: 'Il trend primario (mesi o anni) contiene trend secondari (settimane) e minori (giorni). Un ribasso di pochi giorni può essere solo una correzione dentro un trend primario rialzista.', v: { k: 'stat', n: '3', l: 'livelli di trend: primario, secondario e minore' } },
    { t: 'Rottura non vuol dire inversione', x: 'La violazione di una linea di tendenza è un campanello d’allarme, non un’inversione certa. Il cambio di trend si conferma quando salta la sequenza: per esempio un massimo più basso seguito da un minimo più basso.', v: { k: 'formula', f: 'Inversione al ribasso = massimo più basso + minimo più basso', n: 'La sola rottura della linea non basta' } },
  ],
  terms: [
    ['Trend rialzista', 'Sequenza di massimi e minimi via via più alti nel tempo.'],
    ['Mercato laterale', 'Fase in cui il prezzo oscilla in un intervallo senza una direzione definita.'],
    ['Linea di tendenza', 'Retta che unisce almeno due minimi crescenti o due massimi decrescenti.'],
    ['Canale', 'Coppia di rette parallele che contiene le oscillazioni del prezzo durante un trend.'],
    ['Correzione', 'Movimento temporaneo contro la direzione del trend principale.'],
    ['Trend primario', 'Direzione di fondo del mercato su un orizzonte di mesi o anni.'],
    ['Scala logaritmica', 'Asse in cui distanze uguali rappresentano variazioni percentuali uguali.'],
    ['Inversione', 'Cambio di direzione confermato dalla rottura della sequenza di massimi e minimi.'],
  ],
  tf: [
    ['In un trend rialzista i minimi sono crescenti.', true, 'Ogni ritracciamento si ferma più in alto del precedente: è uno dei due elementi che definiscono il trend rialzista.'],
    ['Bastano due sedute positive per parlare di trend rialzista.', false, 'Un trend richiede una sequenza di massimi e minimi crescenti; due giornate positive possono essere semplice rumore.'],
    ['In un trend ribassista la linea di tendenza si traccia unendo i massimi decrescenti.', true, 'La linea ribassista sta sopra il prezzo e collega i picchi via via più bassi.'],
    ['La rottura di una linea di tendenza segnala con certezza l’inversione del trend.', false, 'Può indicare un rallentamento, una fase laterale o una falsa rottura: l’inversione si conferma con la sequenza di massimi e minimi.'],
    ['Una linea di tendenza molto ripida tende a essere violata prima di una più moderata.', true, 'Un movimento quasi verticale è difficile da mantenere: anche una semplice pausa laterale basta a romperla.'],
    ['Due analisti possono tracciare linee di tendenza diverse sullo stesso grafico.', true, 'La scelta dei punti, l’uso di corpi o ombre e la scala del grafico introducono soggettività: è un limite da ricordare.'],
    ['I mercati sono sempre in trend: le fasi laterali in pratica non esistono.', false, 'I mercati alternano trend e fasi laterali anche lunghe; in quelle fasi gli strumenti di trend producono molti falsi segnali.'],
    ['Su grafici di molti anni la scala logaritmica rappresenta con lo stesso spazio variazioni percentuali uguali.', true, 'In scala logaritmica un +10% occupa lo stesso spazio verticale a qualunque livello di prezzo.'],
    ['Un ribasso di qualche giorno è incompatibile con un trend primario rialzista.', false, 'Il trend primario include correzioni secondarie e minori: un calo breve può essere solo una pausa.'],
    ['Una linea di tendenza con un solo punto di contatto è già affidabile.', false, 'Per un solo punto passano infinite rette: servono almeno due contatti, e un terzo la rende più significativa.'],
  ],
  mcq: [
    { q: 'Quale sequenza definisce un trend ribassista?', a: 'Massimi e minimi decrescenti', w: ['Massimi crescenti e minimi decrescenti', 'Massimi decrescenti e minimi crescenti', 'Massimi e minimi crescenti'], e: 'Nel trend ribassista ogni rimbalzo si ferma più in basso del precedente e ogni calo scende sotto il minimo prima.' },
    { q: 'Quanti punti servono, come minimo, per tracciare una linea di tendenza?', a: 'Due', w: ['Uno', 'Cinque', 'Dieci'], e: 'Due punti definiscono una retta; un terzo contatto successivo ne aumenta la rilevanza.' },
    { q: 'Il prezzo scende sotto una linea rialzista senza fare un minimo più basso, poi segna un nuovo massimo. Cosa concludi?', a: 'Il trend rialzista resta valido; la linea va ridisegnata', w: ['Il trend è diventato ribassista appena la linea è stata rotta', 'Il mercato è entrato in una fase laterale definitiva', 'È il segnale certo di un crollo imminente'], e: 'Finché la sequenza di massimi e minimi crescenti regge, il trend non è invertito: va aggiornata la linea, non il giudizio.' },
    { q: 'Perché su un grafico di 20 anni si preferisce spesso la scala logaritmica?', a: 'Perché mostra in modo omogeneo le variazioni percentuali', w: ['Perché elimina dal grafico tutte le correzioni', 'Perché fa sembrare più alti i rendimenti ottenuti', 'Perché trasforma qualsiasi trend in una retta'], e: 'In scala lineare un +10% da 100 € sembra minuscolo rispetto a un +10% da 1.000 €; in scala logaritmica occupano lo stesso spazio.' },
    { q: 'In un canale rialzista, dove si traccia la linea superiore?', a: 'Sui massimi, parallela alla linea che unisce i minimi', w: ['Sui minimi, perpendicolare alla linea dei massimi', 'Sulla media di tutte le chiusure del periodo', 'Sul massimo storico, in orizzontale'], e: 'Il canale rialzista ha la linea di tendenza sotto, sui minimi, e la sua parallela sopra, a toccare i massimi.' },
    { q: 'Che cos’è una correzione in un trend rialzista?', a: 'Un calo temporaneo dentro la tendenza di fondo', w: ['Un errore nel tracciare la linea di tendenza', 'Un aggiustamento contabile del prezzo', 'L’inizio certo di un trend ribassista'], e: 'Le correzioni sono fisiologiche: un trend rialzista procede a gradini, alternando spinte e ritracciamenti.' },
    { q: 'Quale comportamento è un errore tipico nel tracciare le linee di tendenza?', a: 'Ridisegnarle di continuo per adattarle alla propria idea', w: ['Usare almeno due punti di contatto chiari', 'Verificare la linea su un timeframe superiore', 'Decidere in anticipo cosa considerare una rottura'], e: 'Adattare le linee a ciò che si spera trasforma lo strumento in una conferma delle proprie convinzioni: fissa prima le regole.' },
    { q: 'Un investitore con orizzonte pluriennale vuole capire il trend di fondo. Quale grafico è più adatto?', a: 'Il settimanale o il mensile', w: ['Il grafico a 1 minuto', 'Il grafico a 5 minuti', 'Il grafico orario'], e: 'Il timeframe va scelto in base all’orizzonte: i grafici molto brevi mostrano soprattutto rumore rispetto a obiettivi di anni.' },
  ],
  fill: [
    { s: 'In un trend rialzista si formano massimi e minimi ___.', a: 'crescenti', w: ['decrescenti', 'costanti', 'alternati'] },
    { s: 'Una linea di tendenza rialzista si traccia unendo almeno due ___ crescenti.', a: 'minimi', w: ['massimi', 'volumi', 'gap'] },
    { s: 'Un ___ si ottiene tracciando una parallela alla linea di tendenza sul lato opposto del prezzo.', a: 'canale', w: ['triangolo', 'gap', 'martello'] },
    { s: 'Quando il prezzo oscilla in un intervallo senza direzione, il mercato è ___.', a: 'laterale', w: ['rialzista', 'ribassista', 'parabolico'] },
    { s: 'Su orizzonti lunghi si usa la scala ___ per confrontare variazioni percentuali.', a: 'logaritmica', w: ['lineare', 'decimale', 'assoluta'] },
  ],
  order: [
    { q: 'Ordina i segnali di un’inversione da rialzo a ribasso, dal primo all’ultimo', i: ['Rottura della linea di tendenza rialzista', 'Rimbalzo che non supera il massimo precedente', 'Discesa sotto l’ultimo minimo', 'Sequenza di massimi e minimi decrescenti'], e: 'È lo schema classico: la linea si rompe, il rimbalzo fallisce sotto il vecchio massimo, poi cede l’ultimo minimo e nasce il nuovo trend.' },
    { q: 'Ordina i grafici dal più rumoroso al più adatto a leggere il trend di fondo', i: ['1 minuto', 'Orario', 'Giornaliero', 'Settimanale', 'Mensile'], e: 'Più il timeframe è lungo, più ogni candela riassume informazioni e meno pesano le oscillazioni casuali.' },
  ],
  cat: [
    { q: 'Segnale di trend rialzista o ribassista?', g: [['Rialzista', ['Minimi crescenti', 'Nuovo massimo sopra il precedente', 'Prezzo sopra una linea che sale']], ['Ribassista', ['Massimi decrescenti', 'Nuovo minimo sotto il precedente', 'Prezzo sotto una linea che scende']]] },
    { q: 'Buona o cattiva pratica nel tracciare le linee?', g: [['Buona pratica', ['Usare almeno due contatti chiari', 'Controllare il timeframe superiore', 'Usare la scala logaritmica su anni di dati']], ['Cattiva pratica', ['Forzare la linea per confermare un’idea', 'Considerare certa ogni rottura', 'Tracciare una linea con un solo punto']]] },
  ],
  scen: [
    { s: 'Luca, 29 anni, ha un titolo in trend rialzista da mesi. Durante la seduta il prezzo scende dello 0,5% sotto la linea di tendenza e un amico gli scrive: «Il trend è finito, vendi tutto».', q: 'Cosa fa Luca?', o: [
      { t: 'Verifica la chiusura e la sequenza di massimi e minimi prima di agire', ok: true, f: 'Una violazione intraday è spesso rumore: il trend cambia quando salta la sequenza di massimi e minimi, non al primo sforamento.' },
      { t: 'Vende subito tutto: la linea è rotta e il trend è finito', ok: false, f: 'La rottura di una linea è un avviso, non una sentenza. Vendere a ogni sforamento moltiplica errori e costi.' },
      { t: 'Ridisegna la linea più in basso così risulta intatta', ok: false, f: 'Spostare la linea per non vedere il segnale è autoinganno: le regole di tracciamento vanno decise prima.' },
    ] },
    { s: 'Elena, 41 anni, investe ogni mese in un ETF azionario globale con orizzonte di 15 anni. Guardando il grafico orario vede una serie di massimi decrescenti da tre giorni e si preoccupa.', q: 'Come dovrebbe interpretare la situazione?', o: [
      { t: 'Guarda il trend su timeframe coerenti con l’orizzonte e segue il piano', ok: true, f: 'Un trend minore di pochi giorni può essere solo una correzione: per un orizzonte di 15 anni contano trend primario, piano e diversificazione.' },
      { t: 'Interrompe il piano finché l’orario non torna rialzista', ok: false, f: 'Il grafico orario cambia direzione di continuo: legarci un piano pluriennale porta a decisioni casuali.' },
      { t: 'Vende l’ETF e aspetta una nuova linea di tendenza rialzista', ok: false, f: 'Uscire e rientrare su trend minori aggiunge costi, tasse e il rischio di perdere i rialzi più forti.' },
    ] },
    { s: 'Davide, 36 anni, vede una small cap salire quasi in verticale: la sua linea di tendenza ha una pendenza estrema. Vuole aumentare molto la posizione perché il trend sembra fortissimo.', q: 'Qual è la scelta più razionale?', o: [
      { t: 'Contiene l’esposizione e fissa uno stop: i trend verticali si rompono facilmente', ok: true, f: 'Le linee molto ripide vengono violate spesso e le correzioni possono essere violente: dimensione ridotta e stop sono essenziali.' },
      { t: 'Raddoppia la posizione: più la linea è ripida, più il trend è sicuro', ok: false, f: 'È il contrario: una pendenza estrema è di solito meno sostenibile e più esposta a correzioni brusche.' },
      { t: 'Compra a leva per sfruttare al massimo la pendenza', ok: false, f: 'La leva amplifica anche le perdite: su un movimento parabolico una correzione rapida può essere molto costosa.' },
    ] },
    { s: 'Chiara, 58 anni, analizza 25 anni di FTSE MIB su scala lineare. La linea di tendenza tracciata sui minimi degli anni 2000 le sembra rotta da tempo, ma un collega le suggerisce di cambiare scala.', q: 'Cosa le conviene fare?', o: [
      { t: 'Ripete l’analisi in scala logaritmica e confronta le due letture', ok: true, f: 'Su decenni di dati la scala logaritmica rappresenta in modo omogeneo le variazioni percentuali e cambia l’aspetto delle linee.' },
      { t: 'Ignora il consiglio: la scala non cambia mai le linee', ok: false, f: 'La scala cambia la geometria del grafico: una linea retta in scala lineare non lo è in quella logaritmica, e viceversa.' },
      { t: 'Prova varie scale finché la linea risulta intatta e tiene quella', ok: false, f: 'Scegliere la scala in base al risultato desiderato è un modo per confermare ciò che si vuole vedere: decidi prima il criterio.' },
    ] },
  ],
  tip: 'Prima di tracciare una linea chiediti su quale orizzonte investi, poi scrivi in anticipo cosa consideri una rottura: la linea deve aiutarti a decidere, non a confermare ciò che speri.',
});
