FQC(63, {
  intro: 'Supporti e resistenze sono zone in cui domanda e offerta si sono già scontrate: impari a tracciarle, a leggere le rotture e a difenderti dai falsi breakout.',
  cards: [
    { t: 'Supporto e resistenza', x: 'Un supporto è un’area in cui in passato gli acquisti hanno fermato la discesa; una resistenza, un’area in cui le vendite hanno fermato la salita. Funzionano in parte perché molti operatori ricordano quei livelli e vi piazzano ordini.', v: { k: 'vs', a: ['Supporto', 'Sotto il prezzo: la domanda ha fermato i cali'], b: ['Resistenza', 'Sopra il prezzo: l’offerta ha fermato i rialzi'] } },
    { t: 'Zone, non linee al centesimo', x: 'Il prezzo raramente si ferma al centesimo: meglio ragionare per fasce. Più reazioni evidenti ha avuto un livello, più è osservato; ma test ripetuti possono anche esaurire gli ordini che lo difendono.', v: { k: 'scale', a: 'Livello poco osservato', b: 'Livello molto osservato', d: [['Toccato una volta', 20], ['Toccato più volte', 60], ['Massimo storico e numero tondo', 88]] } },
    { t: 'Inversione di polarità', x: 'Una resistenza rotta con decisione tende a trasformarsi in supporto, e un supporto rotto in resistenza. Chi ha mancato la rottura o ha venduto troppo presto spesso torna a comprare su quel livello.', v: { k: 'steps', s: ['Resistenza a 50 €', 'Chiusura sopra 50 €', 'Ritorno su 50 € (pullback)', '50 € regge come supporto'] } },
    { t: 'Dove nascono i livelli', x: 'I livelli più osservati vengono da massimi e minimi precedenti, da aree di congestione dove il prezzo ha scambiato a lungo, da numeri tondi e, in modo dinamico, da linee di tendenza e medie mobili.', v: { k: 'icons', d: [['🏔️', 'Massimi e minimi precedenti'], ['📦', 'Aree di congestione'], ['🔢', 'Numeri tondi'], ['〽️', 'Livelli dinamici']] } },
    { t: 'Rischio e rendimento tra i livelli', x: 'Supporti e resistenze aiutano a pianificare: lo stop va dove l’idea è smentita, l’obiettivo verso il livello successivo. Se il potenziale guadagno non vale il rischio, l’operazione si può semplicemente evitare.', v: { k: 'formula', f: 'R/R = (obiettivo − ingresso) ÷ (ingresso − stop)', n: 'Es.: (56 − 50) ÷ (50 − 48) = 3' } },
    { t: 'Il falso breakout', x: 'Il prezzo supera una resistenza e poi rientra subito nel range, intrappolando chi ha comprato la rottura. Chiusura oltre il livello, volumi alti e tenuta sul pullback riducono il rischio, ma nessun filtro lo elimina.', v: { k: 'bars', d: [['Resistenza', 50], ['Massimo intraday', 51.2], ['Chiusura', 49.6]], u: '€' } },
  ],
  terms: [
    ['Supporto', 'Area di prezzo in cui in passato la domanda ha fermato i ribassi.'],
    ['Resistenza', 'Area di prezzo in cui in passato l’offerta ha fermato i rialzi.'],
    ['Inversione di polarità', 'Principio per cui un supporto rotto tende a fare da resistenza e viceversa.'],
    ['Breakout', 'Uscita del prezzo oltre una resistenza o sotto un supporto, spesso con volumi in aumento.'],
    ['Falso breakout', 'Rottura apparente di un livello seguita da un rapido rientro nel range precedente.'],
    ['Pullback', 'Ritorno del prezzo sul livello appena rotto, prima di proseguire o di fallire.'],
    ['Range', 'Intervallo orizzontale in cui il prezzo oscilla tra un supporto e una resistenza.'],
    ['Numero tondo', 'Livello come 10 € o 30.000 punti che attira ordini per motivi psicologici.'],
  ],
  tf: [
    ['Un supporto si trova sempre sopra il prezzo attuale.', false, 'Il supporto sta sotto il prezzo corrente, le resistenze sopra. Se il prezzo scende sotto un supporto, quel livello può diventare resistenza.'],
    ['Supporti e resistenze sono prezzi esatti al centesimo.', false, 'Sono zone: gli ordini si distribuiscono attorno al livello e il prezzo spesso lo supera di poco prima di tornare indietro.'],
    ['Una resistenza rotta con decisione tende a trasformarsi in supporto.', true, 'È l’inversione di polarità: chi ha mancato la rottura o ha venduto lì spesso ricompra quando il prezzo torna sul livello.'],
    ['Un supporto toccato molte volte non può essere rotto.', false, 'Ogni livello può cedere; anzi, test ripetuti possono esaurire gli ordini di acquisto che lo difendono.'],
    ['Un falso breakout può intrappolare chi compra non appena il prezzo supera la resistenza.', true, 'Se il prezzo rientra nel range, chi ha comprato la rottura si ritrova in perdita e le sue vendite possono accelerare la discesa.'],
    ['Chiusura oltre il livello e volumi alti riducono, ma non eliminano, il rischio di falso breakout.', true, 'Sono filtri probabilistici: migliorano la qualità del segnale, ma nessuna conferma rende certa una rottura.'],
    ['I numeri tondi non hanno alcun effetto sugli ordini dei partecipanti al mercato.', false, 'Molti ordini limite e stop si concentrano su cifre tonde: per questo possono agire da supporto o resistenza.'],
    ['Mettere lo stop esattamente sul supporto è sempre la scelta più sicura.', false, 'Sui livelli ovvi si accumulano molti stop e il prezzo può toccarli prima di ripartire: serve un margine coerente con la volatilità.'],
    ['Il pullback è il ritorno del prezzo sul livello appena rotto.', true, 'Dopo un breakout il prezzo torna spesso a testare il livello, che può confermarsi nel nuovo ruolo oppure cedere.'],
    ['In un range laterale il prezzo oscilla tra un supporto in basso e una resistenza in alto.', true, 'Il range è delimitato dalle due zone: finché nessuna delle due viene rotta, il mercato resta senza direzione.'],
  ],
  mcq: [
    { q: 'Un titolo rompe la resistenza a 30 €, poi torna a 30 € e riparte verso l’alto. Che cosa è successo?', a: 'La resistenza è diventata supporto', w: ['Il breakout è stato annullato', 'Si è formato un doppio massimo', 'Il supporto è diventato resistenza'], e: 'Il livello rotto viene ritestato dall’alto e regge: è l’inversione di polarità al rialzo.' },
    { q: 'Che cosa caratterizza un falso breakout rialzista?', a: 'Il prezzo supera la resistenza e rientra presto sotto', w: ['Il prezzo supera la resistenza e prosegue con volumi alti', 'Il prezzo resta sempre sotto la resistenza', 'Il prezzo rompe il supporto e prosegue al ribasso'], e: 'La rottura non regge: il prezzo torna nel range e chi aveva comprato sul superamento si ritrova in perdita.' },
    { q: 'Quale filtro si usa più spesso per ridurre i falsi breakout?', a: 'Attendere una chiusura oltre il livello', w: ['Entrare al primo scambio oltre il livello', 'Aumentare la leva sulla rottura', 'Togliere lo stop per non farlo scattare'], e: 'La chiusura oltre il livello filtra parte delle rotture solo intraday, al prezzo di un ingresso un po’ meno favorevole.' },
    { q: 'Compri a 50 € sopra un supporto a 48 €, con stop a 47,50 € e obiettivo a 57,50 €. Qual è il rapporto rischio/rendimento?', a: '1 a 3', w: ['1 a 2', '3 a 1', '1 a 5'], e: 'Rischio: 50 − 47,50 = 2,50 €. Potenziale: 57,50 − 50 = 7,50 €. 7,50 ÷ 2,50 = 3, cioè 1 a 3.' },
    { q: 'Perché i numeri tondi agiscono spesso da supporto o resistenza?', a: 'Perché vi si concentrano molti ordini limite e stop', w: ['Perché la Borsa vieta gli scambi oltre quei livelli', 'Perché la CONSOB li fissa come soglie ufficiali', 'Perché i prezzi di Borsa non hanno decimali'], e: 'Gli operatori scelgono spesso cifre tonde per ordini e obiettivi: la concentrazione di ordini crea attrito sul prezzo.' },
    { q: 'Un supporto viene testato cinque volte in poche settimane, con rimbalzi sempre più deboli. Che cosa suggerisce?', a: 'Che il supporto potrebbe essere vicino a cedere', w: ['Che il supporto è ormai indistruttibile', 'Che il prezzo salirà di sicuro a breve', 'Che i rimbalzi non hanno alcun significato'], e: 'Reazioni sempre più deboli indicano che la domanda sul livello si sta esaurendo: la zona resta rilevante, ma più fragile.' },
    { q: 'Dove si posiziona di solito lo stop di un acquisto vicino a un supporto?', a: 'Poco sotto la zona di supporto, con un margine', w: ['Esattamente sul supporto, al centesimo', 'Sopra la resistenza più vicina', 'Molto lontano, così non scatta mai'], e: 'Se il supporto cede l’idea è smentita: lo stop va sotto la zona, con margine per il rumore, e la posizione si dimensiona di conseguenza.' },
    { q: 'Quale di questi livelli è di solito più osservato come resistenza?', a: 'Un massimo precedente che ha respinto il prezzo più volte', w: ['La chiusura di ieri, qualunque essa sia', 'Un livello toccato per pochi minuti anni fa', 'Il prezzo medio di carico di un singolo investitore'], e: 'La rilevanza cresce con il numero e l’evidenza delle reazioni e con la visibilità del livello per molti operatori.' },
  ],
  fill: [
    { s: 'Una resistenza rotta che diventa supporto è un esempio di inversione di ___.', a: 'polarità', w: ['rendimento', 'volatilità', 'liquidità'] },
    { s: 'Il ___ è il ritorno del prezzo sul livello appena rotto.', a: 'pullback', w: ['breakout', 'gap', 'range'] },
    { s: 'Si parla di ___ breakout quando il prezzo supera un livello e poi rientra subito nel range.', a: 'falso', w: ['doppio', 'lungo', 'primo'] },
    { s: 'Un supporto si trova ___ il prezzo attuale.', a: 'sotto', w: ['sopra', 'dentro', 'oltre'] },
    { s: 'Il prezzo che oscilla tra un supporto e una resistenza disegna un ___.', a: 'range', w: ['canale rialzista', 'martello', 'gap'] },
  ],
  order: [
    { q: 'Ordina le fasi di un’inversione di polarità al rialzo', i: ['Il prezzo viene respinto dalla resistenza', 'Il prezzo chiude sopra la resistenza', 'Il prezzo torna sul livello rotto', 'Il livello tiene e fa da supporto'], e: 'Prima il livello frena i rialzi, poi viene superato; il ritorno sul livello e la sua tenuta confermano il cambio di ruolo.' },
    { q: 'Ordina le fasi di un falso breakout rialzista', i: ['Il prezzo si avvicina alla resistenza', 'Supera il livello di poco', 'Chi compra la rottura entra', 'Il prezzo rientra sotto la resistenza', 'Scattano gli stop dei compratori'], e: 'Il rientro nel range mette in perdita chi ha comprato la rottura: le uscite forzate possono accelerare la discesa.' },
  ],
  cat: [
    { q: 'Supporto o resistenza?', g: [['Supporto', ['Minimo da cui il prezzo è rimbalzato più volte', 'Resistenza rotta e poi ritestata dall’alto', 'Zona sotto il prezzo con forti acquisti']], ['Resistenza', ['Massimo che ha respinto il prezzo più volte', 'Supporto rotto e poi ritestato dal basso', 'Zona sopra il prezzo con forti vendite']]] },
    { q: 'Rende la rottura più o meno affidabile?', g: [['Più affidabile', ['Chiusura oltre il livello', 'Volumi superiori alla media', 'Pullback che regge']], ['Meno affidabile', ['Rottura solo intraday', 'Volumi in calo', 'Rientro immediato nel range']]] },
  ],
  scen: [
    { s: 'Federica, 31 anni, compra a 25,10 € quando il titolo supera la resistenza a 25 €. A fine seduta il prezzo è tornato a 24,60 € e i volumi della giornata sono stati bassi.', q: 'Cosa le conviene fare?', o: [
      { t: 'Applica il piano: esce o riduce, perché la rottura non ha tenuto', ok: true, f: 'Chiusura sotto il livello e volumi scarsi sono i segni tipici del falso breakout: rispettare il piano limita il danno.' },
      { t: 'Compra ancora per abbassare il prezzo medio di carico', ok: false, f: 'Aumentare la posizione quando il segnale fallisce significa raddoppiare l’esposizione a un’idea smentita.' },
      { t: 'Toglie lo stop e aspetta con pazienza che torni sopra 25 €', ok: false, f: 'Rimuovere lo stop trasforma una perdita controllata in un rischio aperto: il prezzo può tornare a 23 € prima che a 25 €.' },
    ] },
    { s: 'Antonio, 47 anni, vuole comprare un titolo che ha rimbalzato tre volte nella zona di 12 €. Deve decidere dove mettere lo stop.', q: 'Quale scelta è più sensata?', o: [
      { t: 'Poco sotto la zona di 12 €, con un margine, e una quantità adatta al rischio', ok: true, f: 'Lo stop va dove l’idea è smentita, con margine per il rumore; la quantità si calcola in modo che la perdita possibile resti accettabile.' },
      { t: 'Esattamente a 12,00 €, dove tutti vedono il supporto', ok: false, f: 'Sui livelli ovvi si accumulano stop: un affondo di pochi centesimi può farli scattare prima della ripartenza.' },
      { t: 'Nessuno stop: il supporto ha sempre tenuto e terrà anche stavolta', ok: false, f: 'Il passato non garantisce il futuro: test ripetuti possono anzi indebolire il livello.' },
    ] },
    { s: 'Martina, 26 anni, vede un titolo rompere la resistenza a 40 € con volumi doppi rispetto alla media. Qualche giorno dopo il prezzo è tornato proprio a 40 €.', q: 'Come dovrebbe leggere la situazione?', o: [
      { t: 'È un possibile pullback: valuta l’ingresso solo se 40 € regge, con stop sotto la zona', ok: true, f: 'Se l’ex resistenza tiene come supporto, la rottura è confermata; se cede, lo stop limita la perdita.' },
      { t: 'Compra subito tutto: rottura con volumi significa rialzo garantito', ok: false, f: 'I volumi rafforzano il segnale ma non lo garantiscono: il ritorno sul livello va ancora superato.' },
      { t: 'Considera 40 € ancora una resistenza e vende allo scoperto', ok: false, f: 'Dopo una rottura convincente, il ruolo del livello può essersi invertito: ignorarlo va contro l’evidenza del grafico.' },
    ] },
    { s: 'Roberto, 63 anni, segue un titolo che da mesi oscilla tra 18 € e 22 €. Oggi è a 21,80 € dopo tre sedute positive e lui vorrebbe comprare perché «sta salendo».', q: 'Qual è la scelta più razionale?', o: [
      { t: 'Aspetta una rottura confermata di 22 € o un ritorno verso il supporto', ok: true, f: 'Comprare sotto la resistenza offre poco potenziale e un rischio ampio fino al supporto: il rapporto rischio/rendimento è sfavorevole.' },
      { t: 'Compra subito: tre sedute positive indicano che il range è finito', ok: false, f: 'Tre giorni di rialzo dentro un range non bastano: la resistenza a 22 € ha già respinto il prezzo più volte.' },
      { t: 'Compra e mette lo stop a 17 €, così non scatta', ok: false, f: 'Uno stop così lontano, con l’obiettivo vicino, significa rischiare molto per guadagnare poco.' },
    ] },
  ],
  tip: 'Disegna zone, non linee al centesimo; aspetta una chiusura oltre il livello e metti lo stop dove l’idea è smentita, non dove ti fa meno male.',
});
