FQC(64, {
  intro: 'Le medie mobili smussano il rumore dei prezzi: impari la differenza tra semplice ed esponenziale, come leggere gli incroci e perché sono sempre in ritardo.',
  cards: [
    { t: 'Media mobile semplice (SMA)', x: 'La SMA a 20 periodi è la media aritmetica delle ultime 20 chiusure: a ogni nuovo periodo entra il dato più recente ed esce il più vecchio. Smussa le oscillazioni e rende più leggibile la direzione di fondo.', v: { k: 'formula', f: 'SMA(n) = somma delle ultime n chiusure ÷ n', n: 'Es.: (10 + 11 + 12 + 13 + 14) ÷ 5 = 12' } },
    { t: 'Media esponenziale (EMA)', x: 'La EMA assegna più peso ai prezzi recenti, quindi reagisce prima ai cambi di direzione. Il prezzo da pagare: più reattività significa anche reagire di più al rumore, con più falsi segnali.', v: { k: 'vs', a: ['SMA', 'Pesi uguali: più lenta e stabile'], b: ['EMA', 'Più peso ai dati recenti: più reattiva'] } },
    { t: 'I periodi più usati', x: 'Medie brevi (10-20) seguono i movimenti di breve, la 50 il medio periodo, la 200 il trend di lungo. Più la media è lunga, più è lenta e meno sensibile alle oscillazioni casuali.', v: { k: 'scale', a: 'Più reattiva', b: 'Più lenta', d: [['Media a 10', 10], ['Media a 20', 25], ['Media a 50', 55], ['Media a 200', 92]] } },
    { t: 'Golden cross e death cross', x: 'Il golden cross è l’incrocio della media a 50 sopra quella a 200; il death cross è l’incrocio opposto. Sono segnali molto citati, ma arrivano tardi, spesso quando buona parte del movimento è già avvenuta.', v: { k: 'icons', d: [['🌟', 'Golden cross: la 50 sale sopra la 200'], ['💀', 'Death cross: la 50 scende sotto la 200']] } },
    { t: 'Il ritardo è inevitabile', x: 'Ogni media si basa su prezzi passati: segue il trend, non lo anticipa. In un mercato laterale prezzo e medie si incrociano di continuo, generando falsi segnali e costi di transazione.', v: { k: 'stat', n: '(n − 1) ÷ 2', l: 'ritardo, in periodi, di una SMA a n periodi rispetto ai prezzi' } },
    { t: 'Medie come supporti dinamici', x: 'In un trend ben definito il prezzo torna spesso verso una media, per esempio la 50, e riparte: la media funziona da supporto o resistenza in movimento. Vale finché il trend regge, non per sempre.', v: { k: 'steps', s: ['Trend sopra la media', 'Ritorno verso la media', 'Reazione del prezzo', 'Nuova spinta o rottura'] } },
  ],
  terms: [
    ['SMA', 'Media aritmetica delle ultime n chiusure, ricalcolata a ogni nuovo periodo.'],
    ['EMA', 'Media che pesa di più i prezzi recenti e reagisce quindi più in fretta.'],
    ['Golden cross', 'Incrocio della media a 50 periodi al di sopra di quella a 200: lettura rialzista di lungo.'],
    ['Death cross', 'Incrocio della media a 50 periodi al di sotto di quella a 200: lettura ribassista di lungo.'],
    ['Lag', 'Ritardo con cui un indicatore basato su prezzi passati segue i movimenti reali.'],
    ['Whipsaw', 'Serie di falsi segnali in un mercato laterale, con ingressi e uscite in perdita.'],
    ['Periodo', 'Numero di dati usati nel calcolo di una media, per esempio 20, 50 o 200 sedute.'],
    ['Supporto dinamico', 'Linea in movimento, come una media, su cui il prezzo tende a rimbalzare durante un trend.'],
  ],
  tf: [
    ['La SMA a 5 periodi di 10, 11, 12, 13 e 14 € vale 12 €.', true, 'La somma è 60 €; divisa per 5 periodi dà 12 €.'],
    ['La EMA dà lo stesso peso a tutti i prezzi del periodo.', false, 'Quella è la SMA. La EMA pesa di più i dati recenti ed è quindi più reattiva.'],
    ['Una media mobile a 200 sedute reagisce più lentamente di una a 20 sedute.', true, 'Ogni nuovo prezzo pesa 1/200 invece di 1/20: la media lunga cambia direzione molto più lentamente.'],
    ['Le medie mobili anticipano i movimenti futuri del prezzo.', false, 'Sono calcolate su prezzi passati: confermano un trend in ritardo, non lo prevedono.'],
    ['Il golden cross è l’incrocio della media a 50 sopra quella a 200.', true, 'È la definizione classica: la media di medio periodo supera quella di lungo, segno che il trend recente è più forte.'],
    ['Dopo un death cross il mercato scende sempre nei mesi successivi.', false, 'Molti death cross sono stati seguiti da recuperi: arrivano tardi e, da soli, hanno un valore predittivo limitato.'],
    ['In un mercato laterale gli incroci tra prezzo e media generano molti falsi segnali.', true, 'Senza trend il prezzo attraversa la media in entrambe le direzioni: ogni segnale viene presto smentito.'],
    ['Una media più reattiva produce meno falsi segnali di una più lenta.', false, 'È il contrario: reagire prima significa anche reagire al rumore, con più segnali errati.'],
    ['Nella SMA a 20 periodi, a ogni nuovo periodo il prezzo più vecchio esce dal calcolo.', true, 'Per questo si chiama mobile: la finestra di 20 dati scorre in avanti di un periodo alla volta.'],
    ['Una media mobile funziona allo stesso modo su qualsiasi titolo e in qualsiasi fase di mercato.', false, 'L’efficacia cambia con strumento, volatilità e fase: in trend aiuta, in laterale peggiora. Va verificata, non data per scontata.'],
  ],
  mcq: [
    { q: 'Ultime 4 chiusure: 20, 22, 21 e 25 €. Quanto vale la SMA a 4 periodi?', a: '22 €', w: ['21 €', '22,50 €', '25 €'], e: '(20 + 22 + 21 + 25) ÷ 4 = 88 ÷ 4 = 22 €.' },
    { q: 'Qual è il principale vantaggio della EMA rispetto alla SMA?', a: 'Reagisce prima ai cambi di direzione', w: ['Non genera mai falsi segnali', 'Usa molti più dati storici', 'Non risente della volatilità'], e: 'Pesando di più i prezzi recenti, la EMA gira prima; in cambio è più esposta al rumore.' },
    { q: 'Che cos’è il death cross?', a: 'La media a 50 che scende sotto quella a 200', w: ['La media a 200 che sale sopra il prezzo', 'Il prezzo che tocca la media a 20', 'La media a 50 che sale sopra quella a 200'], e: 'È l’opposto del golden cross: la media di medio periodo scende sotto quella di lungo.' },
    { q: 'In quale contesto le strategie basate sugli incroci di medie funzionano peggio?', a: 'In un mercato laterale senza direzione', w: ['In un trend rialzista prolungato', 'In un trend ribassista prolungato', 'In un mercato con trend ben definito'], e: 'Senza trend, prezzo e medie si intrecciano: ogni incrocio è un segnale che si smentisce presto (whipsaw).' },
    { q: 'Perché la media a 200 sedute è usata come riferimento di lungo periodo?', a: 'Perché smussa molto il rumore e riflette il trend di fondo', w: ['Perché è imposta dalle regole degli intermediari', 'Perché prevede il prezzo delle 200 sedute successive', 'Perché non reagisce a nessun movimento di prezzo'], e: '200 sedute sono circa 40 settimane di Borsa: la media cambia lentamente e descrive la direzione di lungo.' },
    { q: 'Un trader passa dalla SMA a 50 alla EMA a 10 per avere segnali più rapidi. Che cosa deve aspettarsi?', a: 'Ingressi anticipati, ma più falsi segnali e più costi', w: ['Gli stessi segnali di prima, solo più precisi', 'Meno operazioni e quindi meno commissioni', 'Nessun falso segnale, grazie alla maggiore reattività'], e: 'Una media più corta e reattiva genera più incroci: alcuni anticipano bene, molti sono rumore che si paga in commissioni.' },
    { q: 'Quale di questi comportamenti è un errore con le medie mobili?', a: 'Cambiare periodo dopo ogni segnale sbagliato', w: ['Scegliere periodi coerenti con il proprio orizzonte', 'Tenere conto del ritardo nel valutare i segnali', 'Considerare la fase di mercato, trend o laterale'], e: 'Cambiare parametri inseguendo l’ultimo errore adatta la media al passato recente, senza migliorare i segnali futuri.' },
    { q: 'Il prezzo è sopra la media a 200, che sale da mesi. Come si legge di solito?', a: 'Contesto di trend rialzista di lungo periodo', w: ['Segnale certo di nuovi massimi a breve', 'Mercato in una fase laterale', 'Contesto di trend ribassista di lungo periodo'], e: 'Prezzo sopra una media crescente descrive un trend positivo: non garantisce il futuro, ma inquadra il contesto.' },
  ],
  fill: [
    { s: 'La ___ dà più peso ai prezzi recenti rispetto alla media semplice.', a: 'EMA', w: ['RSI', 'OHLC', 'VWAP'] },
    { s: 'Il ___ cross è l’incrocio della media a 50 sopra quella a 200.', a: 'golden', w: ['death', 'silver', 'double'] },
    { s: 'Le medie mobili seguono il prezzo con un certo ___.', a: 'ritardo', w: ['anticipo', 'sconto', 'margine'] },
    { s: 'In un mercato ___ gli incroci tra prezzo e media generano molti falsi segnali.', a: 'laterale', w: ['rialzista', 'ribassista', 'in forte trend'] },
    { s: 'Più il periodo della media è lungo, più la media è ___.', a: 'lenta', w: ['reattiva', 'volatile', 'nervosa'] },
  ],
  order: [
    { q: 'Ordina le medie dalla più reattiva alla più lenta', i: ['EMA a 10', 'SMA a 20', 'SMA a 50', 'SMA a 200'], e: 'Meno periodi e più peso ai dati recenti rendono la media più rapida; la 200 è la più lenta e stabile.' },
    { q: 'Ordina i passi per calcolare e aggiornare una SMA a 5 periodi', i: ['Prendi le ultime 5 chiusure', 'Sommale', 'Dividi il totale per 5', 'Al periodo dopo togli la più vecchia e aggiungi la nuova'], e: 'La media mobile è una finestra che scorre: il calcolo si ripete a ogni periodo con gli ultimi n dati.' },
  ],
  cat: [
    { q: 'Caratteristica della SMA o della EMA?', g: [['SMA', ['Pesi uguali per tutti i prezzi', 'Più lenta a girare', 'Semplice media aritmetica']], ['EMA', ['Più peso ai prezzi recenti', 'Reagisce prima ai cambi di direzione', 'Usa un fattore di ponderazione']]] },
    { q: 'Lettura rialzista o ribassista, secondo l’uso classico?', g: [['Rialzista', ['Golden cross', 'Prezzo che supera la media a 200', 'Media a 50 inclinata verso l’alto']], ['Ribassista', ['Death cross', 'Prezzo che scende sotto la media a 200', 'Media a 50 inclinata verso il basso']]] },
  ],
  scen: [
    { s: 'Simone, 33 anni, legge che su un titolo si è appena verificato un golden cross, «segnale storico di acquisto». Il prezzo però è già salito del 35% dal minimo di qualche mese fa.', q: 'Cosa fa Simone?', o: [
      { t: 'Considera che il segnale arriva in ritardo e valuta rischio e stop prima di agire', ok: true, f: 'Il golden cross conferma un rialzo già avvenuto: conta quanto rischi ora, non quanto il titolo è salito prima.' },
      { t: 'Compra con tutti i risparmi: è un segnale storico', ok: false, f: 'Nessun incrocio è una garanzia e arriva sempre in ritardo: puntare tutto su un segnale ignora la gestione del rischio.' },
      { t: 'Vende allo scoperto: dopo un golden cross il titolo scende sempre', ok: false, f: 'Non esiste una regola simile: è solo l’errore opposto, una certezza inventata nella direzione contraria.' },
    ] },
    { s: 'Anna, 44 anni, compra quando il prezzo supera la SMA a 20 e vende quando scende sotto. Il titolo è in laterale da quattro mesi: 9 operazioni, 7 in perdita, più le commissioni.', q: 'Qual è la decisione più sensata?', o: [
      { t: 'Riconosce la fase laterale e sospende o filtra la strategia di trend', ok: true, f: 'Gli incroci con le medie funzionano nei trend e soffrono nei laterali: riconoscere la fase evita una serie di whipsaw.' },
      { t: 'Passa a una EMA a 5 per avere segnali ancora più rapidi', ok: false, f: 'Una media più veloce in un laterale genera ancora più incroci, più falsi segnali e più costi.' },
      { t: 'Raddoppia le quantità per recuperare con la prossima operazione', ok: false, f: 'Aumentare l’esposizione dopo le perdite non migliora il segnale: amplifica solo il danno se la fase non cambia.' },
    ] },
    { s: 'Giorgio, 55 anni, investe a lungo termine con un portafoglio diversificato. Legge che l’indice principale ha appena fatto un death cross ed è sceso sotto la media a 200.', q: 'Come dovrebbe reagire?', o: [
      { t: 'Lo legge come contesto e verifica che il portafoglio rispetti il suo piano', ok: true, f: 'Il death cross descrive un indebolimento già avvenuto: per un investitore di lungo conta un piano che regga anche le fasi negative.' },
      { t: 'Vende subito tutto il portafoglio per evitare il crollo', ok: false, f: 'Il segnale arriva tardi e spesso è stato seguito da recuperi: vendere tutto rischia di cristallizzare le perdite.' },
      { t: 'Compra a leva perché il death cross segna sempre il minimo', ok: false, f: 'Non segna né il minimo né il massimo: la leva su una certezza inesistente espone a perdite amplificate.' },
    ] },
    { s: 'Valentina, 24 anni, nota che un titolo in trend rialzista è rimbalzato tre volte sulla media a 50 sedute. Il prezzo si sta avvicinando di nuovo alla media.', q: 'Qual è l’approccio più prudente?', o: [
      { t: 'Aspetta una reazione sulla media ed entra con stop sotto di essa', ok: true, f: 'La media fa da supporto dinamico finché il trend regge: aspettare la reazione e fissare uno stop rende l’idea verificabile.' },
      { t: 'Compra in anticipo: rimbalzerà di sicuro come le altre volte', ok: false, f: 'Tre rimbalzi non garantiscono il quarto: prima o poi ogni supporto dinamico viene rotto.' },
      { t: 'Compra ora e, se il prezzo rompe la media, compra ancora', ok: false, f: 'Aumentare la posizione proprio quando il supporto cede significa aggiungere rischio a un’idea smentita.' },
    ] },
  ],
  tip: 'Le medie mobili descrivono il trend, non lo prevedono: scegli periodi coerenti con il tuo orizzonte, metti in conto il ritardo e diffida dei loro segnali nei mercati laterali.',
});
