FQC(65, {
  intro: 'Il volume misura la partecipazione: impari a usarlo per confermare trend e rotture, a leggere le divergenze e a non sovrainterpretarlo.',
  cards: [
    { t: 'Che cosa misura il volume', x: 'Il volume è la quantità di titoli o contratti scambiati in un periodo. Ogni scambio ha un compratore e un venditore: il volume non dice chi ha vinto, ma quanta partecipazione c’è dietro un movimento.', v: { k: 'icons', d: [['📊', 'Quantità scambiate nel periodo'], ['🤝', 'Ogni scambio: un compratore e un venditore'], ['🔊', 'Intensità della partecipazione']] } },
    { t: 'Volume e trend', x: 'In un trend sano il volume tende a crescere nelle spinte nella direzione del trend e a calare nelle correzioni. Nell’esempio, volumi in % della media: forti sulle salite, deboli sulle pause.', v: { k: 'bars', d: [['Spinta 1', 140], ['Correzione 1', 70], ['Spinta 2', 150], ['Correzione 2', 65]], u: '%' } },
    { t: 'Rotture con volume', x: 'Una rottura di resistenza accompagnata da volumi ben superiori alla media indica partecipazione ampia e tende a essere più affidabile. Una rottura con volumi scarsi merita più cautela.', v: { k: 'vs', a: ['Rottura con volume alto', 'Partecipazione ampia: segnale più solido'], b: ['Rottura con volume basso', 'Pochi scambi: rischio di falso breakout'] } },
    { t: 'Il volume relativo', x: 'Il volume va confrontato con la media dello stesso strumento: un milione di pezzi è tanto per una small cap e poco per una grande banca quotata. Un valore doppio rispetto alla media segnala attività insolita.', v: { k: 'formula', f: 'Volume relativo = volume di oggi ÷ volume medio', n: 'Es.: 3 milioni ÷ 1,5 milioni = 2 volte la media' } },
    { t: 'Divergenze di volume', x: 'Se il prezzo fa nuovi massimi ma il volume cala, la partecipazione si riduce: è un avvertimento, non un ordine di vendita. Picchi di volume dopo lunghi ribassi possono invece indicare capitolazione.', v: { k: 'scale', a: 'Conferma forte', b: 'Avvertimento', d: [['Prezzo su, volume su', 15], ['Prezzo su, volume stabile', 50], ['Prezzo su, volume in calo', 85]] } },
    { t: 'L’OBV', x: 'L’On Balance Volume somma il volume nelle sedute che chiudono in rialzo e lo sottrae in quelle in ribasso. Serve a vedere se i flussi accompagnano il prezzo; come ogni indicatore, va letto nel contesto.', v: { k: 'steps', s: ['Chiusura in rialzo: + volume', 'Chiusura in ribasso: − volume', 'Somma cumulata = OBV', 'Confronto tra OBV e prezzo'] } },
  ],
  terms: [
    ['Volume', 'Quantità di titoli o contratti scambiati in un determinato periodo.'],
    ['Volume medio', 'Media degli scambi su un certo numero di sedute, usata come termine di confronto.'],
    ['Volume relativo', 'Rapporto tra gli scambi di oggi e quelli medi dello stesso strumento.'],
    ['OBV', 'Indicatore cumulato che somma i volumi delle sedute positive e sottrae quelli delle negative.'],
    ['Divergenza di volume', 'Situazione in cui il prezzo prosegue ma gli scambi che lo accompagnano diminuiscono.'],
    ['Capitolazione', 'Ondata di vendite di panico con scambi eccezionali, talvolta vicino a un minimo.'],
    ['Climax di acquisto', 'Rialzo finale con scambi altissimi che a volte segna l’esaurimento del trend.'],
    ['Conferma', 'Segnale indipendente che rafforza la lettura di un altro, come la partecipazione su una rottura.'],
  ],
  tf: [
    ['Ogni scambio di Borsa ha sia un compratore sia un venditore.', true, 'Per questo il volume misura la partecipazione e l’intensità, non da solo la prevalenza degli acquisti sulle vendite.'],
    ['Un volume alto in una seduta di rialzo significa che c’erano più titoli comprati che venduti.', false, 'Titoli comprati e venduti sono sempre in pari quantità: a spingere il prezzo è l’urgenza dei compratori, non il loro numero.'],
    ['In un trend rialzista sano i volumi tendono a crescere nelle fasi di salita.', true, 'Spinte con partecipazione crescente indicano che nuovi acquirenti sostengono il movimento.'],
    ['Una rottura con volumi molto superiori alla media tende a essere più affidabile di una con volumi scarsi.', true, 'Una partecipazione ampia rende la rottura meno dipendente da pochi ordini; resta comunque un segnale probabilistico.'],
    ['Un volume di 500.000 pezzi è alto per qualunque titolo.', false, 'Dipende dallo strumento: va confrontato con il suo volume medio. Per una blue chip può essere poco, per una small cap moltissimo.'],
    ['Nuovi massimi con volumi in calo garantiscono un’inversione imminente.', false, 'Sono un avvertimento sulla forza del trend, che però può proseguire a lungo. Nessuna divergenza è una garanzia.'],
    ['L’OBV aggiunge il volume nelle sedute che chiudono in rialzo e lo sottrae in quelle che chiudono in ribasso.', true, 'È la regola di base dell’indicatore: il segno dipende solo dalla direzione della chiusura rispetto alla seduta precedente.'],
    ['Un picco di volume durante un forte ribasso indica sempre l’inizio di un crollo ancora più grande.', false, 'Può essere anche capitolazione, cioè l’esaurimento delle vendite vicino a un minimo. Serve il contesto per distinguere i casi.'],
    ['Volumi anomali possono dipendere da eventi tecnici come scadenze dei derivati o ribilanciamenti degli indici.', true, 'Non ogni picco racconta una nuova storia di domanda e offerta: controlla calendario, notizie e contesto.'],
    ['In un trend rialzista, una correzione con volumi bassi preoccupa di solito meno di una con volumi alti.', true, 'Pochi scambi in correzione suggeriscono prese di profitto più che vendite convinte; volumi alti indicano più pressione.'],
  ],
  mcq: [
    { q: 'Che cosa misura il volume?', a: 'La quantità di titoli scambiati nel periodo', w: ['Il numero di compratori meno quello dei venditori', 'La distanza tra massimo e minimo del periodo', 'Il controvalore dei soli ordini di acquisto'], e: 'Il volume conta i titoli passati di mano: ogni pezzo scambiato ha un compratore e un venditore.' },
    { q: 'Oggi un titolo scambia 4,5 milioni di pezzi contro una media di 1,5 milioni. Quanto vale il volume relativo?', a: '3 volte la media', w: ['1,5 volte la media', '6 volte la media', 'Metà della media'], e: '4,5 ÷ 1,5 = 3: attività tre volte superiore al normale, da interpretare con il contesto.' },
    { q: 'Il prezzo rompe una resistenza con un volume pari al 60% della media. Come valuti la rottura?', a: 'Con cautela, perché la partecipazione è scarsa', w: ['Come una rottura certamente valida', 'Come un segnale di vendita immediato', 'Come irrilevante, perché il volume non conta'], e: 'Una rottura con pochi scambi è più esposta al rientro nel range: meglio attendere conferme.' },
    { q: 'Un indice segna nuovi massimi, ma ogni spinta ha volumi minori della precedente. Che cosa può indicare?', a: 'Un possibile indebolimento della partecipazione', w: ['Un crollo certo nei giorni immediatamente successivi', 'Un trend più forte e sano del normale', 'Un errore nei dati diffusi dalla Borsa'], e: 'È una divergenza di volume: un avvertimento da monitorare, non una previsione certa.' },
    { q: 'Che cos’è una capitolazione?', a: 'Vendite di panico con volumi eccezionali dopo un lungo calo', w: ['Acquisti regolari con volumi bassi in un trend rialzista', 'La sospensione di un titolo per eccesso di ribasso', 'Una fase laterale con scambi quasi assenti'], e: 'Chi resisteva vende in massa: a volte segna l’esaurimento delle vendite, ma va confermata dai giorni successivi.' },
    { q: 'Tre sedute: rialzo con volume 100, ribasso con 80, rialzo con 120. Partendo da zero, quanto vale l’OBV?', a: '140', w: ['300', '60', '−100'], e: 'OBV = +100 − 80 + 120 = 140. Il segno dipende dalla direzione della chiusura.' },
    { q: 'Quale combinazione conferma meglio un trend rialzista?', a: 'Rialzi con volumi crescenti e correzioni con volumi in calo', w: ['Rialzi con volumi in calo e correzioni con volumi alti', 'Volumi identici in ogni seduta, a prescindere dal prezzo', 'Rialzi con volumi bassi e correzioni con volumi stabili'], e: 'La partecipazione deve concentrarsi nella direzione del trend: le pause con pochi scambi sono fisiologiche.' },
    { q: 'Perché un picco di volume va interpretato con prudenza?', a: 'Perché può dipendere da eventi tecnici e non da nuova domanda', w: ['Perché i dati sui volumi sono quasi sempre falsati', 'Perché il volume non ha relazione con il prezzo', 'Perché i volumi vengono pubblicati solo a fine anno'], e: 'Scadenze di derivati, ribilanciamenti degli indici o grandi blocchi possono gonfiare gli scambi senza cambiare la storia del titolo.' },
  ],
  fill: [
    { s: 'Il ___ indica quanti titoli sono stati scambiati in un periodo.', a: 'volume', w: ['corpo', 'rendimento', 'spread'] },
    { s: 'Il volume ___ confronta gli scambi di oggi con quelli medi.', a: 'relativo', w: ['assoluto', 'nominale', 'netto'] },
    { s: 'Una rottura accompagnata da volumi ___ alla media è considerata più affidabile.', a: 'superiori', w: ['inferiori', 'identici', 'vicini'] },
    { s: 'L’___ somma i volumi delle sedute positive e sottrae quelli delle negative.', a: 'OBV', w: ['RSI', 'EMA', 'ATR'] },
    { s: 'Le vendite di panico con volumi eccezionali dopo un lungo calo prendono il nome di ___.', a: 'capitolazione', w: ['accumulazione', 'distribuzione', 'consolidamento'] },
  ],
  order: [
    { q: 'Ordina dal segnale di rottura più debole al più solido', i: ['Rottura solo intraday con volume basso', 'Chiusura oltre il livello con volume basso', 'Chiusura oltre il livello con volume alto', 'Chiusura con volume alto e pullback che regge'], e: 'Ogni conferma aggiunge informazione: chiusura, partecipazione e tenuta del livello riducono, senza azzerarlo, il rischio di falso segnale.' },
    { q: 'Ordina i passi per aggiornare l’OBV a fine seduta', i: ['Confronta la chiusura di oggi con quella di ieri', 'Stabilisci il segno: più se sale, meno se scende', 'Applica il segno al volume della seduta', 'Aggiungi il risultato al totale precedente'], e: 'L’OBV è un totale cumulato: conta la sua direzione rispetto al prezzo, non il valore assoluto.' },
  ],
  cat: [
    { q: 'Conferma o avvertimento per un trend rialzista?', g: [['Conferma', ['Rialzi con volumi crescenti', 'Correzioni con volumi bassi', 'Rottura di resistenza con volume doppio', 'OBV che segna nuovi massimi']], ['Avvertimento', ['Nuovi massimi con volumi in calo', 'Ribassi con volumi in aumento', 'Rottura con volume sotto la media', 'OBV che scende mentre il prezzo sale']]] },
    { q: 'Picco di volume per causa tecnica o per una notizia sull’azienda?', g: [['Causa tecnica', ['Scadenza delle opzioni', 'Scadenza dei futures', 'Ribilanciamento di un indice']], ['Notizia sull’azienda', ['Pubblicazione della trimestrale', 'Annuncio di un’acquisizione', 'Taglio delle stime da parte del management']]] },
  ],
  scen: [
    { s: 'Lorenzo, 38 anni, vede un titolo superare la resistenza a 8 € a metà agosto, con un volume pari al 40% della media. Il titolo chiude appena sopra il livello.', q: 'Come dovrebbe valutare la rottura?', o: [
      { t: 'Attende conferme: tenuta del livello e volumi in ripresa', ok: true, f: 'Con mercati sottili una rottura può dipendere da pochi ordini: chiusure successive sopra 8 € e volumi più alti la renderebbero più credibile.' },
      { t: 'Compra subito tutto: la resistenza è rotta', ok: false, f: 'La rottura c’è, ma con poca partecipazione il rischio di rientro nel range è più alto: serve un piano con stop.' },
      { t: 'Ignora qualsiasi rottura che avvenga d’estate', ok: false, f: 'Il periodo conta, ma una regola rigida non aiuta: vanno valutati volumi relativi e conferme, non il calendario da solo.' },
    ] },
    { s: 'Francesca, 50 anni, ha un portafoglio di ETF diversificato per la pensione. L’indice principale segna nuovi massimi da settimane, ma con volumi sempre più bassi.', q: 'Qual è la scelta più razionale?', o: [
      { t: 'Ne prende nota e controlla che il portafoglio rispetti il piano', ok: true, f: 'La divergenza è un’informazione, non una sentenza: per un investitore di lungo conta che l’allocazione sia coerente con obiettivi e rischio.' },
      { t: 'Vende tutto subito: con volumi in calo il crollo è ormai certo', ok: false, f: 'Le divergenze possono durare mesi mentre il mercato sale: uscire del tutto è una scommessa sul tempismo.' },
      { t: 'Aumenta l’esposizione: nuovi massimi significano altri rialzi', ok: false, f: 'Nuovi massimi non garantiscono altri rialzi e la partecipazione in calo invita alla cautela, non all’euforia.' },
    ] },
    { s: 'Matteo, 42 anni, nota che un titolo ha scambiato 5 volte il suo volume medio, ma il prezzo è quasi invariato. Un forum sostiene che «qualcuno di grosso sta comprando».', q: 'Cosa fa Matteo?', o: [
      { t: 'Cerca la causa del picco: notizie, scadenze o ribilanciamenti', ok: true, f: 'Un volume anomalo a prezzo fermo può nascere da scadenze di derivati o da movimenti degli indici: prima di trarre conclusioni serve una spiegazione.' },
      { t: 'Compra subito per seguire il grande investitore', ok: false, f: 'Ogni scambio ha un compratore e un venditore: il volume da solo non dice chi abbia iniziativa.' },
      { t: 'Vende allo scoperto perché tanto volume indica distribuzione', ok: false, f: 'È la stessa lettura arbitraria nella direzione opposta: senza contesto il picco non indica una direzione.' },
    ] },
    { s: 'Ilaria, 30 anni, segue un titolo in calo da mesi. Oggi il volume è sei volte la media, il prezzo crolla in apertura ma chiude lontano dai minimi con una lunga ombra inferiore.', q: 'Qual è l’approccio più prudente?', o: [
      { t: 'Lo considera un possibile minimo da confermare, con un rischio definito', ok: true, f: 'Può essere capitolazione, ma servono conferme nelle sedute successive; se decide di entrare, lo fa con stop e quantità limitate.' },
      { t: 'Compra con tutto il capitale: la capitolazione segna sempre il fondo', ok: false, f: 'Non sempre: dopo un picco di vendite possono arrivarne altri. Puntare tutto su un segnale ignora il rischio.' },
      { t: 'Vende allo scoperto con leva: volume alto significa crollo', ok: false, f: 'Il recupero dai minimi suggerisce che la pressione si è attenuata: la leva contro questo segnale amplifica il rischio.' },
    ] },
  ],
  tip: 'Confronta sempre il volume con la media dello stesso titolo e usalo come conferma, non come segnale isolato: prezzo e partecipazione devono raccontare la stessa storia.',
});
