FQC(66, {
  intro: 'RSI e stocastico misurano la forza dei movimenti: impari ipercomprato, ipervenduto e divergenze, e perché nei trend forti gli estremi possono durare a lungo.',
  cards: [
    { t: 'Che cos’è l’RSI', x: 'Il Relative Strength Index, ideato da J. Welles Wilder, confronta la media dei rialzi e quella dei ribassi recenti, di solito su 14 periodi, e oscilla tra 0 e 100. Valori alti indicano rialzi dominanti, bassi ribassi dominanti.', v: { k: 'formula', f: 'RSI = 100 − 100 ÷ (1 + RS), con RS = media rialzi ÷ media ribassi', n: 'Es.: RS = 2 → RSI = 100 − 100 ÷ 3 ≈ 66,7' } },
    { t: 'Ipercomprato e ipervenduto', x: 'Per convenzione l’RSI sopra 70 indica ipercomprato e sotto 30 ipervenduto. Non sono ordini di vendita o di acquisto: dicono che il movimento recente è stato intenso, non che finirà subito.', v: { k: 'scale', a: 'RSI 0', b: 'RSI 100', d: [['Ipervenduto', 30], ['Zona neutra', 50], ['Ipercomprato', 70]] } },
    { t: 'Laterale o trend forte?', x: 'In un range gli estremi dell’RSI spesso precedono un rientro verso il centro. In un trend robusto invece l’RSI può restare sopra 70 per settimane mentre il prezzo continua a salire: vendere solo per l’ipercomprato significa andare contro il trend.', v: { k: 'vs', a: ['Mercato laterale', 'Gli estremi spesso precedono un rientro'], b: ['Trend forte', 'Gli estremi possono durare a lungo'] } },
    { t: 'Le divergenze', x: 'Divergenza ribassista: il prezzo fa un massimo più alto, l’RSI un massimo più basso. Rialzista: prezzo con un minimo più basso, RSI con un minimo più alto. Segnalano perdita di slancio, ma possono durare a lungo prima di contare.', v: { k: 'icons', d: [['📈', 'Prezzo: massimo più alto'], ['📉', 'RSI: massimo più basso'], ['⚠️', 'Slancio in calo, da confermare']] } },
    { t: 'Lo stocastico', x: 'Lo stocastico, sviluppato da George Lane, misura dove si trova la chiusura nell’intervallo tra minimo e massimo degli ultimi n periodi (%K); la %D è una sua media. Sopra 80 si parla di ipercomprato, sotto 20 di ipervenduto.', v: { k: 'formula', f: '%K = (chiusura − minimo n) ÷ (massimo n − minimo n) × 100', n: 'Es.: (18 − 10) ÷ (20 − 10) × 100 = 80' } },
    { t: 'Usarli con giudizio', x: 'Gli oscillatori rendono di più come conferma: un ipervenduto vicino a un supporto, dentro un trend di fondo rialzista, dice più di un numero isolato. E prima di entrare va sempre definito il rischio.', v: { k: 'steps', s: ['Identifica il trend di fondo', 'Individua i livelli chiave', 'Leggi l’oscillatore', 'Definisci stop e dimensione'] } },
  ],
  terms: [
    ['RSI', 'Oscillatore da 0 a 100 che confronta l’ampiezza media dei rialzi e dei ribassi recenti.'],
    ['Ipercomprato', 'Condizione di un oscillatore su valori alti dopo rialzi intensi: per l’RSI, oltre 70.'],
    ['Ipervenduto', 'Condizione di un oscillatore su valori bassi dopo cali intensi: per l’RSI, sotto 30.'],
    ['Divergenza ribassista', 'Prezzo con un massimo più alto mentre l’oscillatore segna un massimo più basso.'],
    ['Divergenza rialzista', 'Prezzo con un minimo più basso mentre l’oscillatore segna un minimo più alto.'],
    ['Stocastico', 'Oscillatore che misura la posizione della chiusura nel range massimo-minimo recente.'],
    ['Oscillatore', 'Indicatore che si muove entro limiti fissi o attorno a un valore centrale.'],
    ['%D', 'Media mobile della linea %K dello stocastico, usata come linea di segnale.'],
  ],
  tf: [
    ['L’RSI oscilla tra 0 e 100.', true, 'È costruito come rapporto normalizzato: non può scendere sotto 0 né superare 100.'],
    ['Un RSI sopra 70 è un segnale certo di vendita.', false, 'Indica solo rialzi recenti intensi: in un trend forte l’RSI può restare in ipercomprato a lungo mentre il prezzo sale.'],
    ['Il periodo proposto da Wilder per l’RSI è di 14 periodi.', true, 'È l’impostazione classica, ancora la più usata; periodi più brevi o più lunghi cambiano la sensibilità dell’indicatore.'],
    ['Si ha una divergenza ribassista quando prezzo e RSI fanno entrambi massimi più alti.', false, 'In quel caso c’è concordanza. La divergenza ribassista è prezzo con massimo più alto e RSI con massimo più basso.'],
    ['Uno stocastico a 90 indica che la chiusura è vicina al massimo del range recente.', true, 'La %K misura la posizione della chiusura tra minimo e massimo: 90 significa al 90% dell’intervallo, nella parte alta.'],
    ['Comprare ogni volta che l’RSI scende sotto 30 funziona bene anche nei forti trend ribassisti.', false, 'In un trend ribassista l’ipervenduto può durare e il prezzo continuare a scendere: è il classico tentativo di afferrare un coltello che cade.'],
    ['Una divergenza può persistere a lungo prima che il prezzo cambi direzione.', true, 'Lo slancio può calare per settimane mentre il trend prosegue: la divergenza va confermata dal prezzo, per esempio con una rottura.'],
    ['Accorciare il periodo dell’RSI lo rende più sensibile e gli fa toccare più spesso le soglie.', true, 'Con meno periodi l’indicatore reagisce di più: produce più segnali estremi, e quindi anche più falsi segnali.'],
    ['RSI e stocastico usano dati diversi dal prezzo, quindi danno conferme indipendenti dal grafico.', false, 'Sono calcolati sugli stessi prezzi: rielaborano il grafico senza aggiungere dati nuovi. Sommarli non moltiplica le conferme.'],
    ['Le soglie 70 e 30 dell’RSI sono convenzioni, non leggi del mercato.', true, 'Sono riferimenti pratici: c’è chi usa 80 e 20 nei trend forti. Nessun valore fa scattare automaticamente un’inversione.'],
  ],
  mcq: [
    { q: 'Se la media dei rialzi è il triplo di quella dei ribassi (RS = 3), quanto vale l’RSI?', a: '75', w: ['25', '66,7', '90'], e: 'RSI = 100 − 100 ÷ (1 + 3) = 100 − 25 = 75.' },
    { q: 'Che cosa indica un RSI a 25?', a: 'Ribassi recenti intensi: zona di ipervenduto', w: ['Rialzi recenti intensi: zona di ipercomprato', 'Che il titolo ha perso il 25% del suo valore', 'Che il prezzo risalirà di sicuro a breve'], e: 'Sotto 30 l’RSI segnala che i ribassi hanno dominato: è una descrizione dello slancio, non una previsione.' },
    { q: 'Il prezzo fa un nuovo minimo a 40 €, sotto il precedente a 42 €; l’RSI fa un minimo a 28, sopra il precedente a 22. Che cosa osservi?', a: 'Una divergenza rialzista', w: ['Una divergenza ribassista', 'Una conferma del ribasso', 'Un golden cross'], e: 'Il prezzo scende ancora ma con meno slancio: è una divergenza rialzista, da confermare con il prezzo.' },
    { q: 'Stocastico su 14 periodi: minimo 50 €, massimo 60 €, chiusura 52 €. Quanto vale la %K?', a: '20', w: ['52', '80', '2'], e: '(52 − 50) ÷ (60 − 50) × 100 = 20: la chiusura è nella parte bassa del range recente.' },
    { q: 'In quale contesto i segnali di ipercomprato e ipervenduto tendono a funzionare meglio?', a: 'In un mercato laterale con un range definito', w: ['In un trend rialzista molto forte', 'In un trend ribassista molto forte', 'Nei giorni di notizie societarie rilevanti'], e: 'Nei range il prezzo tende a tornare verso il centro; nei trend forti gli estremi possono durare a lungo.' },
    { q: 'RSI, stocastico e un terzo oscillatore sono tutti in ipercomprato. Che cosa deve considerare un trader?', a: 'Che sono tre letture degli stessi prezzi', w: ['Che il ribasso è ormai sicuro', 'Che tre segnali equivalgono a una certezza', 'Che deve aprire tre posizioni distinte'], e: 'Gli oscillatori derivano tutti da prezzi passati e concordano spesso: è ridondanza, non una conferma indipendente.' },
    { q: 'Che cosa rappresenta la linea %D dello stocastico?', a: 'Una media mobile della %K', w: ['Il volume medio del periodo', 'Il massimo degli ultimi 14 periodi', 'La differenza tra due medie esponenziali'], e: 'La %D smussa la %K e funge da linea di segnale: gli incroci tra le due sono il segnale classico dello stocastico.' },
    { q: 'Qual è un uso prudente dell’RSI dentro un trend rialzista di fondo?', a: 'Cercare ipervenduti sulle correzioni, vicino ai supporti', w: ['Vendere allo scoperto ogni volta che supera 70', 'Comprare soltanto quando supera quota 90', 'Ignorare il trend e seguire solo le soglie'], e: 'Allinearsi al trend e usare l’oscillatore per il tempismo evita molti segnali contro tendenza, che sono più rischiosi.' },
  ],
  fill: [
    { s: 'Per convenzione un RSI sopra 70 indica una condizione di ___.', a: 'ipercomprato', w: ['ipervenduto', 'equilibrio', 'neutralità'] },
    { s: 'Il periodo classico dell’RSI proposto da Wilder è di ___ periodi.', a: '14', w: ['200', '50', '3'] },
    { s: 'Se il prezzo fa un massimo più alto e l’RSI un massimo più basso, si parla di divergenza ___.', a: 'ribassista', w: ['rialzista', 'neutrale', 'nascosta'] },
    { s: 'Lo ___ misura dove si colloca la chiusura nel range tra massimo e minimo recenti.', a: 'stocastico', w: ['spread', 'sconto', 'storno'] },
    { s: 'RSI e stocastico appartengono alla famiglia degli ___.', a: 'oscillatori', w: ['indici di Borsa', 'ordini limite', 'strumenti derivati'] },
  ],
  order: [
    { q: 'Ordina i passi per calcolare l’RSI', i: ['Calcola il rialzo o il ribasso di ogni seduta', 'Fai la media dei rialzi e dei ribassi su 14 periodi', 'Dividi la media dei rialzi per quella dei ribassi (RS)', 'Applica RSI = 100 − 100 ÷ (1 + RS)'], e: 'L’RSI trasforma il rapporto tra forza dei rialzi e dei ribassi in una scala da 0 a 100.' },
    { q: 'Ordina le fasi di una divergenza ribassista', i: ['Primo massimo del prezzo con RSI alto', 'Correzione del prezzo e dell’RSI', 'Nuovo massimo del prezzo con RSI più basso', 'Rottura di un supporto come conferma'], e: 'La divergenza nasce dal confronto fra due massimi; la conferma arriva solo quando anche il prezzo cede.' },
  ],
  cat: [
    { q: 'Ipercomprato o ipervenduto, con le soglie classiche?', g: [['Ipercomprato', ['RSI a 78', 'Stocastico a 88', 'RSI a 72']], ['Ipervenduto', ['RSI a 22', 'Stocastico a 12', 'RSI a 28']]] },
    { q: 'Divergenza rialzista o ribassista?', g: [['Rialzista', ['Prezzo con minimo più basso, RSI con minimo più alto', 'Stocastico che sale mentre il prezzo fa nuovi minimi', 'Discesa che perde slancio sull’oscillatore']], ['Ribassista', ['Prezzo con massimo più alto, RSI con massimo più basso', 'Stocastico che scende mentre il prezzo fa nuovi massimi', 'Salita che perde slancio sull’oscillatore']]] },
  ],
  scen: [
    { s: 'Giacomo, 35 anni, segue un titolo in forte rialzo dopo risultati trimestrali molto sopra le attese. L’RSI è sopra 80 da due settimane e lui vorrebbe vendere allo scoperto.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Evita di andare contro il trend solo per l’RSI e aspetta segnali dal prezzo', ok: true, f: 'Nei trend forti l’ipercomprato può durare a lungo: senza un indebolimento visibile sul prezzo, la vendita allo scoperto è una scommessa.' },
      { t: 'Vende allo scoperto con leva: sopra 80 il titolo deve scendere', ok: false, f: 'Nessuna soglia obbliga il prezzo a scendere: con la leva, un rialzo che continua può causare perdite pesanti.' },
      { t: 'Compra il doppio: un RSI alto significa che salirà per sempre', ok: false, f: 'È l’errore opposto: l’RSI descrive lo slancio passato e non garantisce che prosegua.' },
    ] },
    { s: 'Laura, 46 anni, vede un titolo in trend ribassista da un anno con l’RSI a 18. Pensa di usare buona parte dei risparmi per comprarlo, «visto che è ipervenduto».', q: 'Qual è la scelta più prudente?', o: [
      { t: 'Aspetta segni di stabilizzazione e, se entra, rischia solo una piccola parte con stop', ok: true, f: 'In un trend ribassista l’ipervenduto può durare: servono segnali dal prezzo e un rischio limitato e definito.' },
      { t: 'Compra subito con buona parte dei risparmi: sotto 20 il rimbalzo è sicuro', ok: false, f: 'Nessun valore dell’RSI garantisce un rimbalzo; concentrare i risparmi su un segnale aumenta molto il rischio.' },
      { t: 'Compra a rate ogni volta che l’RSI scende di altri 5 punti', ok: false, f: 'Aggiungere a una posizione che continua a scendere, senza un piano di uscita, amplifica le perdite.' },
    ] },
    { s: 'Pietro, 28 anni, ha un titolo in guadagno. Sul grafico giornaliero nota una divergenza ribassista: nuovo massimo del prezzo, RSI con un massimo più basso.', q: 'Qual è la reazione più sensata?', o: [
      { t: 'La tratta come un avvertimento: alza lo stop o riduce in parte', ok: true, f: 'La divergenza segnala perdita di slancio, non un’inversione certa: proteggere il guadagno è più sensato che indovinare il massimo.' },
      { t: 'Vende tutto e apre uno short: la divergenza è infallibile', ok: false, f: 'Le divergenze possono durare a lungo senza effetto: trasformarle in certezze porta a molti errori.' },
      { t: 'La ignora: gli oscillatori non servono mai a niente', ok: false, f: 'Non sono infallibili, ma possono aiutare a gestire il rischio: il punto è usarli come informazione, non come oracolo.' },
    ] },
    { s: 'Noemi, 39 anni, ha cinque oscillatori sul grafico, tutti in ipervenduto. È convinta di avere cinque conferme indipendenti per comprare.', q: 'Che cosa dovrebbe considerare?', o: [
      { t: 'Che sono letture ridondanti e servono conferme diverse, come supporti o volumi', ok: true, f: 'Oscillatori calcolati sugli stessi prezzi tendono a concordare: una conferma utile viene da informazioni diverse.' },
      { t: 'Che cinque segnali concordi rendono il rimbalzo praticamente certo', ok: false, f: 'Cinque misure dello stesso fenomeno non sono cinque prove: la probabilità non si moltiplica.' },
      { t: 'Che deve aggiungere altri oscillatori per avere più sicurezza', ok: false, f: 'Più indicatori simili aggiungono confusione, non informazione: è una forma di eccesso di fiducia.' },
    ] },
  ],
  tip: 'Ipercomprato non vuol dire «vendi» e ipervenduto non vuol dire «compra»: guarda prima il trend, usa l’oscillatore per affinare il momento e fissa sempre lo stop.',
});
