FQC(67, {
  intro: 'Il MACD misura la distanza tra due medie esponenziali: impari linea MACD, linea di segnale, istogramma, momentum e i loro inevitabili ritardi.',
  cards: [
    { t: 'Come nasce il MACD', x: 'Il MACD (Moving Average Convergence Divergence), ideato da Gerald Appel, è la differenza tra una EMA a 12 periodi e una a 26. Se la media veloce è sopra la lenta il MACD è positivo: lo slancio recente è rialzista.', v: { k: 'formula', f: 'MACD = EMA(12) − EMA(26)', n: 'Es.: 105,00 − 103,50 = +1,50' } },
    { t: 'Le tre componenti', x: 'La linea MACD, la linea di segnale (una EMA a 9 periodi del MACD) e l’istogramma, cioè la differenza tra le due. L’istogramma mostra se lo slancio sta accelerando o rallentando.', v: { k: 'icons', d: [['〰️', 'Linea MACD'], ['➖', 'Linea di segnale: EMA a 9 del MACD'], ['📊', 'Istogramma: MACD − segnale']] } },
    { t: 'Incroci con la linea di segnale', x: 'Quando il MACD sale sopra la linea di segnale si parla di incrocio rialzista, quando scende sotto di incrocio ribassista. Nei mercati laterali gli incroci sono frequenti e spesso falsi.', v: { k: 'vs', a: ['Incrocio rialzista', 'Il MACD sale sopra la linea di segnale'], b: ['Incrocio ribassista', 'Il MACD scende sotto la linea di segnale'] } },
    { t: 'La linea dello zero', x: 'Il MACD sopra zero significa EMA a 12 sopra EMA a 26. L’attraversamento dello zero arriva di solito più tardi degli incroci con il segnale: meno segnali, ma più ritardo.', v: { k: 'scale', a: 'Più tempestivo', b: 'Più tardivo', d: [['Istogramma che si accorcia', 15], ['Incrocio con il segnale', 45], ['Passaggio dello zero', 80]] } },
    { t: 'Momentum e ROC', x: 'Il momentum misura di quanto è cambiato il prezzo rispetto a n periodi prima; il Rate of Change (ROC) esprime la stessa variazione in percentuale. Un momentum che rallenta mentre il prezzo sale può anticipare una pausa.', v: { k: 'stat', n: '+10%', l: 'ROC se il prezzo passa da 50 € a 55 € in n periodi' } },
    { t: 'L’istogramma che si accorcia', x: 'Barre sempre più corte indicano che il MACD si avvicina alla linea di segnale: lo slancio rallenta. Il MACD non ha soglie fisse come l’RSI e, derivando da medie, resta sempre in ritardo sui prezzi.', v: { k: 'bars', d: [['Seduta 1', 1.2], ['Seduta 2', 0.8], ['Seduta 3', 0.3], ['Seduta 4', -0.2]] } },
  ],
  terms: [
    ['MACD', 'Differenza tra una media esponenziale veloce (12) e una lenta (26) dei prezzi.'],
    ['Linea di segnale', 'EMA a 9 periodi del MACD, usata per individuare gli incroci.'],
    ['Istogramma', 'Barre che misurano la distanza tra il MACD e la sua linea di segnale.'],
    ['Momentum', 'Velocità del movimento, misurata come variazione del prezzo rispetto a n periodi prima.'],
    ['ROC', 'Variazione percentuale del prezzo rispetto a quello di n periodi prima.'],
    ['Linea dello zero', 'Livello in cui le due EMA del MACD si equivalgono; sopra prevale la media veloce.'],
    ['Incrocio rialzista', 'Momento in cui il MACD sale sopra la sua linea di segnale.'],
    ['Parametri 12-26-9', 'Impostazione classica: EMA veloce a 12, EMA lenta a 26, segnale a 9 periodi.'],
  ],
  tf: [
    ['Il MACD è la differenza tra una EMA a 12 periodi e una EMA a 26 periodi.', true, 'È la costruzione classica di Appel: quando la media veloce si allontana dalla lenta, il MACD cresce in valore assoluto.'],
    ['La linea di segnale è una EMA a 9 periodi del MACD stesso.', true, 'È una media dell’indicatore, non del prezzo: per questo è ancora più lenta della linea MACD.'],
    ['Il MACD oscilla sempre tra 0 e 100, come l’RSI.', false, 'Il MACD non ha limiti: è una differenza di prezzi, quindi dipende dal livello e dalla volatilità dello strumento.'],
    ['Un MACD positivo indica che la EMA veloce è sopra quella lenta.', true, 'MACD = EMA 12 − EMA 26: se il risultato è positivo, la media a 12 periodi sta sopra quella a 26.'],
    ['Comprando a ogni incrocio rialzista del MACD si chiude sempre in guadagno.', false, 'Molti incroci, soprattutto nei laterali, falliscono: il segnale va filtrato con trend e livelli e gestito con uno stop.'],
    ['L’istogramma del MACD vale zero quando MACD e linea di segnale coincidono.', true, 'L’istogramma è la loro differenza: cambia segno proprio nel momento dell’incrocio.'],
    ['Essendo calcolato su medie, il MACD anticipa le inversioni prima che compaiano sul prezzo.', false, 'Deriva da medie di prezzi passati, quindi è in ritardo. Le divergenze possono avvisare, ma senza certezze.'],
    ['Il MACD di un titolo da 500 € non è direttamente confrontabile con quello di un titolo da 5 €.', true, 'Il MACD è espresso in unità di prezzo: a parità di movimento percentuale, un titolo più caro produce valori più grandi.'],
    ['Il ROC a 10 periodi di un titolo passato da 40 € a 44 € è del 4%.', false, '(44 − 40) ÷ 40 = 0,10, cioè +10%. I 4 € sono la variazione assoluta, cioè il momentum in euro.'],
    ['Un istogramma che si accorcia mentre il prezzo sale indica che lo slancio si sta riducendo.', true, 'Il MACD si avvicina alla linea di segnale: il rialzo prosegue ma con meno forza, il che non implica un’inversione.'],
  ],
  mcq: [
    { q: 'EMA a 12 periodi = 48,40 €, EMA a 26 periodi = 47,10 €. Quanto vale il MACD?', a: '+1,30', w: ['−1,30', '+0,13', '+95,50'], e: 'MACD = EMA 12 − EMA 26 = 48,40 − 47,10 = +1,30: la media veloce è sopra la lenta.' },
    { q: 'MACD = 0,80 e linea di segnale = 1,10. Quanto vale l’istogramma?', a: '−0,30', w: ['+0,30', '+1,90', '−1,90'], e: 'Istogramma = MACD − segnale = 0,80 − 1,10 = −0,30: il MACD si trova sotto la linea di segnale.' },
    { q: 'Che cosa significa che il MACD attraversa la linea dello zero verso l’alto?', a: 'Che la EMA a 12 ha superato la EMA a 26', w: ['Che il prezzo ha superato i massimi storici', 'Che l’RSI è entrato in ipercomprato', 'Che il volume ha superato la sua media'], e: 'Il MACD vale zero quando le due medie coincidono: sopra zero la media veloce è più alta della lenta.' },
    { q: 'Perché il MACD non ha soglie universali di ipercomprato?', a: 'Perché non ha limiti fissi e dipende dal prezzo', w: ['Perché è vietato dalle autorità di vigilanza', 'Perché il suo valore resta sempre tra −1 e +1', 'Perché si può usare solo sugli indici di Borsa'], e: 'Essendo una differenza di prezzi, il MACD non è normalizzato: un valore alto per un titolo è normale per un altro.' },
    { q: 'Un titolo passa da 80 € a 76 € in 10 sedute. Quanto vale il ROC a 10 periodi?', a: '−5%', w: ['−4%', '+5%', '−0,5%'], e: '(76 − 80) ÷ 80 = −0,05, cioè −5%.' },
    { q: 'In quale situazione gli incroci tra MACD e linea di segnale generano più falsi segnali?', a: 'In un laterale con oscillazioni strette', w: ['In un trend rialzista ampio e ordinato', 'In un trend ribassista ampio e ordinato', 'In un trend di lungo periodo ben definito'], e: 'Nei laterali le due medie si avvicinano e si intrecciano: ogni piccola oscillazione produce un incrocio.' },
    { q: 'Il prezzo segna un massimo più alto, mentre il MACD fa un picco più basso del precedente. Come si chiama?', a: 'Divergenza ribassista', w: ['Divergenza rialzista', 'Incrocio rialzista', 'Golden cross'], e: 'Il prezzo sale ma lo slancio cala: è un avvertimento, da confermare con il comportamento del prezzo.' },
    { q: 'Come si usa in modo prudente un incrocio rialzista del MACD?', a: 'Verificando trend, livelli chiave e rischio prima di agire', w: ['Comprando sempre al primo incrocio, con tutto il capitale', 'Vendendo allo scoperto per anticipare il segnale opposto', 'Guardando solo l’istogramma e ignorando il prezzo'], e: 'L’incrocio è un indizio sullo slancio: il contesto e uno stop definito decidono se e quanto rischiare.' },
  ],
  fill: [
    { s: 'Il MACD è la differenza tra una EMA a 12 periodi e una EMA a ___ periodi.', a: '26', w: ['9', '50', '200'] },
    { s: 'La linea di ___ è una media esponenziale a 9 periodi del MACD.', a: 'segnale', w: ['tendenza', 'supporto', 'resistenza'] },
    { s: 'L’___ rappresenta la differenza tra il MACD e la linea di segnale.', a: 'istogramma', w: ['oscillatore', 'indice', 'OBV'] },
    { s: 'Il ___ esprime in percentuale la variazione del prezzo rispetto a n periodi prima.', a: 'ROC', w: ['MACD', 'P/E', 'TER'] },
    { s: 'Derivando da medie mobili, il MACD è un indicatore in ___ rispetto al prezzo.', a: 'ritardo', w: ['anticipo', 'pareggio', 'vantaggio'] },
  ],
  order: [
    { q: 'Ordina i passi per costruire il MACD completo', i: ['Calcola le EMA a 12 e a 26 periodi', 'Sottrai la EMA a 26 dalla EMA a 12', 'Calcola la EMA a 9 del MACD', 'Sottrai la linea di segnale dal MACD'], e: 'Prima la differenza tra le medie (MACD), poi la sua media (segnale), infine la distanza tra le due (istogramma).' },
    { q: 'Ordina i segnali di una ripresa al rialzo, dal più tempestivo al più tardivo', i: ['L’istogramma negativo inizia ad accorciarsi', 'Il MACD incrocia sopra la linea di segnale', 'Il MACD supera la linea dello zero', 'La media a 50 incrocia sopra la 200'], e: 'Più componenti lente entrano nel segnale, più arriva tardi: guadagni in conferma, perdi in tempestività.' },
  ],
  cat: [
    { q: 'Lettura rialzista o ribassista?', g: [['Rialzista', ['MACD sopra la linea di segnale', 'MACD che passa sopra lo zero', 'Istogramma negativo che si accorcia']], ['Ribassista', ['MACD sotto la linea di segnale', 'MACD che scende sotto lo zero', 'Istogramma positivo che si accorcia']]] },
    { q: 'Caratteristica del MACD o dell’RSI?', g: [['MACD', ['Differenza tra due EMA', 'Valori senza limiti fissi', 'Linea di segnale a 9 periodi']], ['RSI', ['Oscilla tra 0 e 100', 'Soglie classiche 70 e 30', 'Periodo standard di 14']]] },
  ],
  scen: [
    { s: 'Emanuele, 31 anni, segue un titolo bloccato da tre mesi in un range stretto. Il MACD ha appena dato un incrocio rialzista, il quinto del periodo: i quattro precedenti sono falliti.', q: 'Cosa fa Emanuele?', o: [
      { t: 'Aspetta la rottura del range prima di dare peso all’incrocio', ok: true, f: 'Nei laterali gli incroci del MACD sono soprattutto rumore: la rottura del range fornisce il contesto che manca.' },
      { t: 'Compra subito: prima o poi un incrocio deve funzionare', ok: false, f: 'Ogni incrocio in un laterale ha poche probabilità in più del precedente: insistere moltiplica perdite e costi.' },
      { t: 'Compra il doppio per recuperare i quattro tentativi persi', ok: false, f: 'Aumentare la posizione per rifarsi delle perdite è un errore di gestione del rischio, non una strategia.' },
    ] },
    { s: 'Beatrice, 49 anni, confronta due titoli: A costa 300 € e ha MACD 12, B costa 6 € e ha MACD 0,40. Conclude che A ha uno slancio molto più forte.', q: 'Cosa dovrebbe fare per un confronto corretto?', o: [
      { t: 'Usa una misura percentuale come il ROC, perché il MACD dipende dal prezzo', ok: true, f: 'Il MACD è in unità di prezzo: 12 su 300 € è il 4%, 0,40 su 6 € quasi il 7%. Normalizzando, il confronto può ribaltarsi.' },
      { t: 'Si fida del confronto: un MACD più alto indica sempre più slancio', ok: false, f: 'Vale solo sullo stesso strumento: tra titoli con prezzi diversi i valori assoluti non sono confrontabili.' },
      { t: 'Sceglie il titolo con il MACD più basso perché è più economico', ok: false, f: 'Il prezzo unitario di un titolo non dice nulla sulla sua convenienza né sul suo slancio.' },
    ] },
    { s: 'Tommaso, 37 anni, ha in portafoglio un titolo in forte rialzo, in guadagno. Da cinque sedute l’istogramma del MACD si accorcia, anche se il prezzo continua a salire.', q: 'Qual è la reazione più sensata?', o: [
      { t: 'Lo legge come un rallentamento e alza lo stop di protezione', ok: true, f: 'L’istogramma che si accorcia segnala meno slancio, non un ribasso certo: proteggere il guadagno è prudente.' },
      { t: 'Vende tutto e apre uno short: l’inversione è iniziata', ok: false, f: 'Un rallentamento dello slancio può essere solo una pausa: trasformarlo in certezza porta a errori costosi.' },
      { t: 'Compra ancora: il prezzo sale, quindi il MACD sbaglia', ok: false, f: 'Ignorare il segnale non è meglio che assolutizzarlo: è un’informazione da usare nella gestione del rischio.' },
    ] },
    { s: 'Silvia, 60 anni, legge che impostando il MACD a 3-10-16 sul grafico giornaliero si ottengono segnali più rapidi. Vuole sostituire i parametri classici sul suo conto.', q: 'Che cosa deve aspettarsi?', o: [
      { t: 'Più segnali e più falsi allarmi: va verificato prima di usarlo', ok: true, f: 'Medie più corte reagiscono prima ma anche al rumore: più operazioni significano più costi e più errori, da testare con prudenza.' },
      { t: 'Gli stessi segnali di prima, solo più puntuali', ok: false, f: 'Cambiando i parametri cambiano anche numero e qualità dei segnali, non solo il loro tempismo.' },
      { t: 'Nessun falso segnale, perché le medie corte non sbagliano', ok: false, f: 'Le medie corte sbagliano più spesso, non meno: rapidità e affidabilità sono un compromesso.' },
    ] },
  ],
  tip: 'Il MACD racconta lo slancio con ritardo: usalo per capire se una spinta accelera o si spegne, filtralo con trend e livelli chiave e non confondere un incrocio con una certezza.',
});
