FQC(68, {
  intro: 'Testa e spalle, doppi massimi e minimi, triangoli e bandiere: impari a riconoscerli, a capire quando si completano e a stimare obiettivi senza illuderti.',
  cards: [
    { t: 'Inversione o continuazione', x: 'I pattern si dividono in figure di inversione (testa e spalle, doppi massimi e minimi) e di continuazione (bandiere, pennant, molti triangoli). La classificazione è indicativa: conta come la figura si risolve davvero.', v: { k: 'vs', a: ['Inversione', 'Testa e spalle, doppio massimo, doppio minimo'], b: ['Continuazione', 'Bandiere, pennant, triangoli'] } },
    { t: 'Testa e spalle', x: 'Tre picchi: spalla sinistra, testa più alta, spalla destra più bassa della testa. I minimi tra i picchi definiscono la neckline: la figura si completa solo con la rottura della neckline, non prima.', v: { k: 'steps', s: ['Spalla sinistra', 'Testa', 'Spalla destra', 'Rottura della neckline'] } },
    { t: 'Doppio massimo e doppio minimo', x: 'Il doppio massimo ha due picchi simili separati da un minimo e si conferma con la rottura di quel minimo; il doppio minimo è il suo speculare. Senza rottura restano solo due tentativi falliti di superare un livello.', v: { k: 'icons', d: [['🔻', 'Doppio massimo: forma a M, conferma sotto il minimo intermedio'], ['🔺', 'Doppio minimo: forma a W, conferma sopra il massimo intermedio']] } },
    { t: 'Triangoli', x: 'Ascendente: resistenza orizzontale e minimi crescenti. Discendente: supporto orizzontale e massimi decrescenti. Simmetrico: linee convergenti. Il prezzo si comprime e la rottura indica la direzione, con possibili falsi segnali.', v: { k: 'scale', a: 'Lettura rialzista', b: 'Lettura ribassista', d: [['Ascendente', 20], ['Simmetrico', 50], ['Discendente', 80]] } },
    { t: 'Bandiere', x: 'Dopo un movimento quasi verticale (l’asta) il prezzo consolida in un piccolo canale inclinato contro il trend. La rottura nella direzione dell’asta suggerisce una continuazione; l’obiettivo si stima con la lunghezza dell’asta.', v: { k: 'formula', f: 'Obiettivo ≈ punto di rottura + lunghezza dell’asta', n: 'Es.: asta di 10 €, rottura a 52 € → circa 62 €' } },
    { t: 'L’obiettivo di misura', x: 'Nel testa e spalle si misura la distanza tra testa e neckline e la si proietta dal punto di rottura: testa a 60 €, neckline a 50 €, obiettivo stimato 40 €. È una stima, non una promessa: il prezzo può fermarsi prima o andare oltre.', v: { k: 'bars', d: [['Testa', 60], ['Neckline', 50], ['Obiettivo stimato', 40]], u: '€' } },
  ],
  terms: [
    ['Neckline', 'Linea che unisce i minimi tra spalle e testa; la sua rottura completa la figura.'],
    ['Testa e spalle', 'Figura di inversione con tre picchi, di cui quello centrale è il più alto.'],
    ['Testa e spalle rovesciato', 'Figura speculare con tre minimi, il centrale più basso: possibile inversione al rialzo.'],
    ['Doppio massimo', 'Due picchi simili separati da un minimo, confermati dalla rottura di quel minimo.'],
    ['Triangolo ascendente', 'Figura con resistenza orizzontale e minimi crescenti che comprimono il prezzo.'],
    ['Bandiera', 'Breve consolidamento inclinato contro il trend dopo un movimento rapido.'],
    ['Asta', 'Movimento quasi verticale che precede una bandiera e ne misura l’obiettivo.'],
    ['Obiettivo di misura', 'Stima del movimento dopo una rottura, ottenuta proiettando l’altezza della figura.'],
  ],
  tf: [
    ['Un testa e spalle si considera completato solo dopo la rottura della neckline.', true, 'Prima della rottura è solo una possibile figura: molte spalle destre in formazione non portano mai a un’inversione.'],
    ['Nel testa e spalle la spalla destra è più alta della testa.', false, 'La testa è il picco più alto e le spalle sono più basse. Se la spalla destra superasse la testa, la figura sarebbe annullata.'],
    ['Un doppio massimo si conferma con la rottura del minimo intermedio tra i due picchi.', true, 'Finché quel minimo regge, i due picchi sono solo un livello che ha respinto il prezzo due volte.'],
    ['Riconosciuto un pattern, il raggiungimento dell’obiettivo di misura è garantito.', false, 'L’obiettivo è una stima indicativa: molti pattern falliscono o si fermano prima. Serve sempre uno stop.'],
    ['Il triangolo ascendente ha una resistenza orizzontale e minimi crescenti.', true, 'I compratori comprano a prezzi sempre più alti contro un tetto fisso: per questo la lettura classica è rialzista.'],
    ['Una bandiera rialzista di solito si inclina verso l’alto, nella stessa direzione dell’asta.', false, 'Di solito si inclina contro l’asta: in un rialzo la bandiera scende leggermente, poi la rottura verso l’alto riprende il trend.'],
    ['Il riconoscimento dei pattern contiene una componente soggettiva.', true, 'Proporzioni, simmetria e linee vengono interpretate: due analisti possono vedere figure diverse sugli stessi dati.'],
    ['Un pattern su un grafico a 1 minuto ha di solito la stessa rilevanza di uno su un grafico settimanale.', false, 'Le figure su timeframe lunghi riassumono più scambi e più tempo; quelle su timeframe brevi sono molto più esposte al rumore.'],
    ['Quando la rottura di un pattern fallisce, il prezzo può muoversi con forza nella direzione opposta.', true, 'Chi era entrato sulla rottura chiude in perdita e alimenta il movimento contrario: per questo lo stop fa parte del piano.'],
    ['Il doppio minimo ha la forma di una M.', false, 'Il doppio minimo ricorda una W; la M è il doppio massimo.'],
  ],
  mcq: [
    { q: 'Testa e spalle con testa a 80 € e neckline a 70 €. Qual è l’obiettivo di misura dopo la rottura?', a: '60 €', w: ['50 €', '65 €', '90 €'], e: 'Altezza: 80 − 70 = 10 €, proiettata dalla neckline verso il basso: 70 − 10 = 60 €. È una stima, non un prezzo garantito.' },
    { q: 'Quando si considera confermato un doppio minimo?', a: 'Quando il prezzo rompe il massimo intermedio tra i due minimi', w: ['Quando il prezzo tocca per la seconda volta il minimo', 'Quando i due minimi sono identici al centesimo', 'Quando il volume del secondo minimo uguaglia il primo'], e: 'La rottura del massimo intermedio dimostra che i compratori hanno preso il sopravvento: prima è solo un doppio test del supporto.' },
    { q: 'Quale figura ha una resistenza orizzontale e minimi crescenti?', a: 'Triangolo ascendente', w: ['Triangolo discendente', 'Triangolo simmetrico', 'Testa e spalle'], e: 'Il tetto fisso e i minimi crescenti comprimono il prezzo verso l’alto: la lettura classica è rialzista, ma va confermata dalla rottura.' },
    { q: 'Dopo un rialzo verticale da 40 a 50 €, si forma una bandiera che viene rotta al rialzo a 48 €. Quale obiettivo indicativo dà la regola dell’asta?', a: '58 €', w: ['50 €', '60 €', '88 €'], e: 'L’asta è 50 − 40 = 10 €; proiettata dal punto di rottura dà 48 + 10 = 58 €. Una stima da gestire con uno stop.' },
    { q: 'Che cosa fa un trader prudente se vede una possibile spalla destra in formazione?', a: 'Aspetta la rottura della neckline prima di agire', w: ['Vende subito, anticipando la figura completa', 'Considera la figura già completa e certa', 'Raddoppia la posizione per sfruttare il pattern'], e: 'Molte figure in formazione non si completano: agire prima della conferma aumenta i falsi segnali.' },
    { q: 'In che direzione si rompe un triangolo simmetrico?', a: 'Non è definito in anticipo: conta la rottura', w: ['Sempre al rialzo, per come è costruito', 'Sempre al ribasso, per come è costruito', 'Sempre in direzione opposta al trend precedente'], e: 'Le linee convergenti comprimono il prezzo senza indicare un vincitore: spesso prevale il trend precedente, ma la rottura va attesa.' },
    { q: 'Quale elemento rende più credibile la rottura di un pattern?', a: 'Un aumento del volume sulla rottura', w: ['Un volume in calo sulla rottura', 'Una rottura solo durante la seduta', 'Un ritorno immediato dentro la figura'], e: 'Una partecipazione ampia sulla rottura riduce, senza eliminarlo, il rischio di falso segnale.' },
    { q: 'Quale affermazione sui pattern grafici è corretta?', a: 'Sono soggettivi e non sempre si risolvono come previsto', w: ['Si completano sempre nella direzione indicata', 'Hanno la stessa affidabilità su ogni timeframe', 'Rendono superfluo l’uso dello stop loss'], e: 'I pattern descrivono probabilità, non certezze: vanno confermati e gestiti con un rischio definito.' },
  ],
  fill: [
    { s: 'Nel testa e spalle, la ___ unisce i minimi tra le spalle e la testa.', a: 'neckline', w: ['asta', 'bandiera', 'media mobile'] },
    { s: 'Il doppio ___ ricorda la lettera W.', a: 'minimo', w: ['massimo', 'triangolo', 'canale'] },
    { s: 'Nella bandiera, il movimento rapido che precede il consolidamento si chiama ___.', a: 'asta', w: ['spalla', 'neckline', 'cuneo'] },
    { s: 'Un triangolo ___ ha una resistenza orizzontale e minimi crescenti.', a: 'ascendente', w: ['discendente', 'simmetrico', 'rovesciato'] },
    { s: 'L’obiettivo di ___ si ottiene proiettando l’altezza della figura dal punto di rottura.', a: 'misura', w: ['rendimento', 'bilancio', 'liquidità'] },
  ],
  order: [
    { q: 'Ordina le fasi di un testa e spalle', i: ['Spalla sinistra', 'Testa', 'Spalla destra', 'Rottura della neckline', 'Eventuale pullback sulla neckline'], e: 'La figura si costruisce da sinistra a destra e si completa solo con la rottura; il pullback, quando c’è, arriva dopo.' },
    { q: 'Ordina le fasi di una bandiera rialzista', i: ['Trend rialzista precedente', 'Asta: salita rapida e quasi verticale', 'Bandiera: consolidamento inclinato verso il basso', 'Rottura al rialzo della bandiera'], e: 'La bandiera è una pausa dentro un movimento forte: la rottura nella direzione dell’asta suggerisce la ripresa del trend.' },
  ],
  cat: [
    { q: 'Pattern di inversione o di continuazione, nella lettura classica?', g: [['Inversione', ['Testa e spalle', 'Testa e spalle rovesciato', 'Doppio massimo', 'Doppio minimo']], ['Continuazione', ['Bandiera rialzista', 'Bandiera ribassista', 'Pennant', 'Rettangolo dentro un trend']]] },
    { q: 'Segnale rialzista o ribassista al completamento?', g: [['Rialzista', ['Testa e spalle rovesciato', 'Doppio minimo', 'Triangolo ascendente rotto in alto']], ['Ribassista', ['Testa e spalle', 'Doppio massimo', 'Triangolo discendente rotto in basso']]] },
  ],
  scen: [
    { s: 'Riccardo, 43 anni, possiede un titolo che sembra disegnare una spalla destra: la neckline è a 32 € e il prezzo è a 34 €. Un amico gli dice di vendere subito «prima che sia tardi».', q: 'Qual è l’approccio più razionale?', o: [
      { t: 'Decide ora cosa farà se il prezzo chiude sotto 32 €, senza anticipare', ok: true, f: 'Il testa e spalle esiste solo dopo la rottura della neckline: preparare il piano evita sia il panico sia l’immobilità.' },
      { t: 'Vende tutto e apre uno short: il testa e spalle è ormai certo', ok: false, f: 'Molte spalle destre in formazione non si completano: anticipare la figura significa agire su un’ipotesi.' },
      { t: 'Compra ancora e, se rompe la neckline, aspetta che risalga', ok: false, f: 'Aumentare l’esposizione senza un piano di uscita ignora proprio lo scenario negativo che la figura segnala.' },
    ] },
    { s: 'Camilla, 34 anni, vede un triangolo ascendente rotto al rialzo a 25 €, con volumi 2,5 volte la media. L’obiettivo di misura indica circa 29 €.', q: 'Come imposta l’operazione?', o: [
      { t: 'Entra con stop sotto la zona di rottura e usa 29 € solo come riferimento', ok: true, f: 'La rottura è di qualità, ma resta probabilistica: lo stop limita il danno se fallisce e l’obiettivo è una stima, non un traguardo garantito.' },
      { t: 'Entra senza stop: con quei volumi l’obiettivo è sicuro', ok: false, f: 'I volumi alti migliorano le probabilità, non danno certezze: senza stop un falso breakout può costare caro.' },
      { t: 'Investe tutto il capitale per massimizzare il guadagno atteso', ok: false, f: 'Concentrare tutto su una sola figura espone a una perdita sproporzionata se la rottura fallisce.' },
    ] },
    { s: 'Fabio, 52 anni, nota due massimi a 48 € e 48,20 € separati da un minimo a 44 €. Ora il prezzo è a 45 € e un forum parla di «doppio massimo confermato».', q: 'Come dovrebbe leggere la situazione?', o: [
      { t: 'Considera la figura non confermata finché il prezzo non chiude sotto 44 €', ok: true, f: 'Il doppio massimo si conferma solo con la rottura del minimo intermedio: fino ad allora 44 € resta un supporto valido.' },
      { t: 'Vende allo scoperto subito: il doppio massimo è già certo', ok: false, f: 'Senza rottura del minimo intermedio la figura non è completa e il prezzo può ripartire dal supporto.' },
      { t: 'Compra: il secondo massimo è più alto, quindi il rialzo riparte', ok: false, f: '20 centesimi di differenza non bastano a cambiare la lettura: due massimi così vicini sono un livello che ha respinto il prezzo.' },
    ] },
    { s: 'Greta, 27 anni, è andata short alla rottura della neckline di un testa e spalle a 20 €, con stop a 21,20 €. Due giorni dopo il prezzo torna a 20,80 €, sopra la neckline, con volumi in aumento.', q: 'Cosa le conviene fare?', o: [
      { t: 'Rispetta lo stop e accetta che la figura possa essere fallita', ok: true, f: 'Una rottura che rientra con volumi in aumento è un campanello d’allarme: i movimenti contrari ai pattern falliti possono essere rapidi.' },
      { t: 'Sposta lo stop più in alto per lasciare spazio alla figura', ok: false, f: 'Allargare lo stop quando il trade va male aumenta la perdita possibile senza migliorare l’idea.' },
      { t: 'Raddoppia lo short: il testa e spalle deve arrivare all’obiettivo', ok: false, f: 'Nessun pattern deve arrivare da nessuna parte: aumentare la posizione su un segnale che fallisce amplifica il rischio.' },
    ] },
  ],
  tip: 'Un pattern esiste solo dopo la conferma: aspetta la rottura, guarda i volumi, usa l’obiettivo di misura come stima e decidi prima il punto in cui la figura è smentita.',
});
