FQC(69, {
  intro: 'I ritracciamenti di Fibonacci stimano dove una correzione potrebbe fermarsi: impari i livelli 38,2%, 50% e 61,8%, come tracciarli e perché non sono magici.',
  cards: [
    { t: 'Da dove vengono i numeri', x: 'Nella successione di Fibonacci (1, 1, 2, 3, 5, 8, 13, 21, 34…) il rapporto tra un numero e il successivo tende a 0,618, quello con il numero due posizioni dopo a 0,382. Da qui nascono i livelli usati sui grafici.', v: { k: 'formula', f: '21 ÷ 34 ≈ 0,618 · 21 ÷ 55 ≈ 0,382', n: 'Il 50% non deriva dalla successione: si usa per convenzione' } },
    { t: 'I livelli principali', x: 'I ritracciamenti più usati sono 23,6%, 38,2%, 50%, 61,8% e 78,6%. Indicano quanta parte del movimento precedente viene recuperata dalla correzione: più alta la percentuale, più profonda la correzione.', v: { k: 'bars', d: [['23,6%', 23.6], ['38,2%', 38.2], ['50%', 50], ['61,8%', 61.8], ['78,6%', 78.6]], u: '%' } },
    { t: 'Come si tracciano', x: 'In un rialzo si parte dal minimo significativo e si arriva al massimo: i livelli si misurano scendendo dal massimo. In un ribasso si fa il contrario. La scelta dei due punti è soggettiva e cambia i risultati.', v: { k: 'steps', s: ['Scegli un movimento evidente', 'Segna minimo e massimo', 'Calcola i livelli in percentuale', 'Osserva la reazione del prezzo'] } },
    { t: 'Il calcolo', x: 'In un rialzo: livello = massimo − (massimo − minimo) × percentuale. Con un rialzo da 100 a 150 €, il 38,2% è a 130,90 € e il 61,8% a 119,10 €.', v: { k: 'stat', n: '119,10 €', l: 'ritracciamento del 61,8% di un rialzo da 100 € a 150 €' } },
    { t: 'Confluenza', x: 'Un livello acquista interesse quando coincide con altro: un vecchio supporto, una media mobile, un numero tondo. Da solo, con tanti livelli vicini, è facile trovare a posteriori quello che sembra aver funzionato.', v: { k: 'icons', d: [['🐚', 'Livello di Fibonacci'], ['🧱', 'Vecchio supporto'], ['〽️', 'Media mobile'], ['🎯', 'Zona di confluenza']] } },
    { t: 'Profezia che si autoavvera?', x: 'Non ci sono prove solide che il rapporto aureo governi i mercati. Se i livelli a volte funzionano, può dipendere dal fatto che molti li osservano e vi piazzano ordini. Trattali come zone di attenzione, non come previsioni.', v: { k: 'vs', a: ['Uso corretto', 'Zone di attenzione da confermare'], b: ['Uso scorretto', 'Livelli magici che il prezzo deve rispettare'] } },
  ],
  terms: [
    ['Ritracciamento', 'Correzione che recupera una parte del movimento precedente prima di una possibile ripresa.'],
    ['Successione di Fibonacci', 'Serie in cui ogni numero è la somma dei due precedenti: 1, 1, 2, 3, 5, 8…'],
    ['Rapporto aureo', 'Valore pari a circa 1,618, il cui inverso 0,618 è alla base del livello del 61,8%.'],
    ['Livello 61,8%', 'Ritracciamento profondo legato al rapporto aureo, tra i più osservati dai trader.'],
    ['Livello 50%', 'Ritracciamento di metà movimento, non derivato dalla successione ma usato per convenzione.'],
    ['Estensione', 'Proiezione oltre il 100% del movimento, come il 161,8%, usata per stimare obiettivi.'],
    ['Confluenza', 'Coincidenza di più strumenti tecnici nella stessa zona di prezzo.'],
    ['Swing', 'Movimento tra un minimo e un massimo significativi, da cui si tracciano i livelli.'],
  ],
  tf: [
    ['Nella successione di Fibonacci ogni numero è la somma dei due precedenti.', true, 'È la regola che genera la serie: 1, 1, 2, 3, 5, 8, 13, 21 e così via.'],
    ['Il livello del 50% deriva direttamente dalla successione di Fibonacci.', false, 'Il 50% non è un rapporto di Fibonacci: si usa per convenzione e per l’idea diffusa che metà movimento sia un punto di equilibrio.'],
    ['In un rialzo da 20 a 30 €, il ritracciamento del 50% è a 25 €.', true, '30 − (30 − 20) × 0,5 = 30 − 5 = 25 €.'],
    ['Il prezzo rimbalza sempre esattamente su un livello di Fibonacci.', false, 'Spesso li supera o si ferma altrove. Sono zone di attenzione e, con molti livelli vicini, è facile trovare coincidenze a posteriori.'],
    ['Scegliendo un minimo o un massimo di partenza diversi, i livelli di Fibonacci cambiano.', true, 'I livelli sono percentuali del movimento scelto: cambiando i punti estremi cambiano anche tutti i prezzi calcolati.'],
    ['Un ritracciamento del 23,6% indica una correzione più profonda di uno del 61,8%.', false, 'È il contrario: il 23,6% recupera meno di un quarto del movimento, il 61,8% quasi due terzi.'],
    ['La confluenza tra un livello di Fibonacci e un vecchio supporto rende la zona più osservata.', true, 'Più strumenti indicano la stessa area, più operatori la guardano: resta però una zona, non una garanzia.'],
    ['Esistono prove scientifiche solide che i mercati seguano il rapporto aureo.', false, 'Non ci sono evidenze robuste: l’efficacia, quando c’è, può dipendere dal fatto che molti operatori guardano quei livelli.'],
    ['In un ribasso, i ritracciamenti del rimbalzo si misurano salendo dal minimo.', true, 'Il rimbalzo recupera una parte della discesa: i livelli si calcolano dal minimo verso il massimo di partenza.'],
    ['Le estensioni di Fibonacci, come il 161,8%, servono a stimare possibili obiettivi oltre il movimento iniziale.', true, 'Proiettano il movimento oltre il punto di partenza: sono stime da usare con prudenza, come ogni obiettivo.'],
  ],
  mcq: [
    { q: 'Rialzo da 40 a 60 €. Dove si trova il ritracciamento del 38,2%?', a: '52,36 €', w: ['47,64 €', '55,28 €', '50,00 €'], e: '60 − (60 − 40) × 0,382 = 60 − 7,64 = 52,36 €.' },
    { q: 'Ribasso da 80 a 60 €. Dove si trova il ritracciamento del 61,8% del rimbalzo?', a: '72,36 €', w: ['67,64 €', '70,00 €', '92,36 €'], e: 'Nel ribasso si sale dal minimo: 60 + (80 − 60) × 0,618 = 60 + 12,36 = 72,36 €.' },
    { q: 'Nella successione di Fibonacci, quale rapporto tende a 0,618?', a: 'Un numero diviso per il successivo', w: ['Un numero diviso per il precedente', 'Un numero diviso per sé stesso', 'La somma di due numeri divisa per 100'], e: 'Per esempio 21 ÷ 34 ≈ 0,618; il rapporto inverso, 34 ÷ 21, tende invece a 1,618.' },
    { q: 'Perché la scelta dei punti di partenza e di arrivo è così importante?', a: 'Perché punti diversi producono livelli diversi', w: ['Perché i livelli sono fissati dalla Borsa', 'Perché i livelli non dipendono dai prezzi', 'Perché si usano solo i prezzi di apertura'], e: 'I livelli sono percentuali del movimento scelto: estremi diversi spostano tutte le zone, ed è qui che entra la soggettività.' },
    { q: 'Quale situazione rende più interessante un livello di Fibonacci?', a: 'La coincidenza con un supporto e una media mobile', w: ['Il fatto di essere molto lontano dal prezzo', 'Un minimo di partenza scelto a caso', 'L’assenza di qualunque altro riferimento'], e: 'La confluenza con altri riferimenti rende la zona più osservata dagli operatori: resta una probabilità, non una certezza.' },
    { q: 'Il prezzo scende oltre il 61,8% e chiude sotto il 78,6% di un rialzo. Che cosa è ragionevole pensare?', a: 'Che il trend precedente è ormai in discussione', w: ['Che il rimbalzo sul 100% è ormai garantito', 'Che i livelli vanno ricalcolati finché tengono', 'Che il trend rialzista è più forte di prima'], e: 'Più la correzione si avvicina all’origine del movimento, più il trend precedente perde credibilità.' },
    { q: 'Qual è il rischio principale di usare molti livelli di Fibonacci insieme?', a: 'Trovare a posteriori un livello che sembra funzionare', w: ['Rendere il grafico illeggibile per la piattaforma', 'Ridurre troppo il numero di segnali possibili', 'Annullare l’effetto delle medie mobili sul grafico'], e: 'Con cinque o sei livelli ravvicinati il prezzo si fermerà quasi sempre vicino a uno di essi: è una coincidenza, non una prova.' },
    { q: 'Dove si colloca in modo coerente lo stop di un acquisto sul ritracciamento del 61,8%?', a: 'Sotto la zona, dove l’idea di rimbalzo è smentita', w: ['Esattamente sul livello del 61,8%, al centesimo', 'Sopra il massimo del movimento precedente', 'Da nessuna parte, perché il 61,8% tiene sempre'], e: 'Lo stop va dove l’idea è smentita, con un margine: per esempio oltre la zona successiva o sotto il minimo di partenza.' },
  ],
  fill: [
    { s: 'Nella successione di Fibonacci ogni numero è la ___ dei due precedenti.', a: 'somma', w: ['media', 'differenza', 'metà'] },
    { s: 'Il livello del ___ non deriva dalla successione ma è usato per convenzione.', a: '50%', w: ['61,8%', '38,2%', '23,6%'] },
    { s: 'Quando più strumenti tecnici indicano la stessa zona si parla di ___.', a: 'confluenza', w: ['divergenza', 'capitolazione', 'neckline'] },
    { s: 'Il rapporto aureo vale circa ___.', a: '1,618', w: ['3,14', '2,718', '1,414'] },
    { s: 'Le ___ di Fibonacci, come il 161,8%, stimano obiettivi oltre il movimento iniziale.', a: 'estensioni', w: ['candele', 'divergenze', 'medie'] },
  ],
  order: [
    { q: 'Ordina i ritracciamenti dal meno profondo al più profondo', i: ['23,6%', '38,2%', '50%', '61,8%', '78,6%'], e: 'La percentuale indica quanta parte del movimento precedente viene restituita: più è alta, più la correzione è profonda.' },
    { q: 'Ordina i passi per calcolare un ritracciamento in un rialzo', i: ['Individua minimo e massimo del movimento', 'Calcola l’ampiezza: massimo − minimo', 'Moltiplica l’ampiezza per la percentuale', 'Sottrai il risultato dal massimo'], e: 'Esempio: da 100 a 150 €, ampiezza 50 €; 50 × 0,382 = 19,10; 150 − 19,10 = 130,90 €.' },
  ],
  cat: [
    { q: 'Uso corretto o scorretto di Fibonacci?', g: [['Corretto', ['Cercare confluenze con supporti', 'Usare i livelli come zone', 'Definire uno stop oltre la zona']], ['Scorretto', ['Spostare i punti finché un livello funziona', 'Considerare il 61,8% una certezza', 'Entrare senza alcuno stop']]] },
    { q: 'Correzione lieve o profonda?', g: [['Lieve', ['Ritracciamento del 23,6%', 'Ritracciamento del 38,2%', 'Breve pausa laterale']], ['Profonda', ['Ritracciamento del 61,8%', 'Ritracciamento del 78,6%', 'Ritorno vicino al minimo di partenza']]] },
  ],
  scen: [
    { s: 'Daniele, 40 anni, segue un titolo salito da 30 a 50 €. La correzione si ferma a 42,36 €, sul 38,2%, dove c’era anche una vecchia resistenza, e compare un martello.', q: 'Qual è l’approccio più razionale?', o: [
      { t: 'Valuta l’ingresso con stop sotto la zona e quantità calibrata sul rischio', ok: true, f: 'La confluenza di livello, vecchia resistenza e candela rende la zona interessante, ma lo stop resta indispensabile.' },
      { t: 'Compra a leva: il 38,2% con un martello tiene sempre', ok: false, f: 'Nessuna combinazione di segnali è infallibile: la leva amplifica la perdita se la zona cede.' },
      { t: 'Ignora il segnale: conta solo il 61,8%, l’unico livello affidabile', ok: false, f: 'Non esiste un livello «unico» che funziona: conta la confluenza con il contesto, non la percentuale in sé.' },
    ] },
    { s: 'Alessia, 29 anni, traccia Fibonacci partendo da minimi diversi finché uno dei livelli coincide con il punto in cui il prezzo è rimbalzato ieri. Poi lo mostra come prova che il metodo funziona.', q: 'Che cosa dovrebbe fare per un’analisi onesta?', o: [
      { t: 'Fissare in anticipo le regole per scegliere i punti e accettarne i risultati', ok: true, f: 'Scegliere i punti dopo aver visto il rimbalzo garantisce sempre una coincidenza: le regole vanno decise prima.' },
      { t: 'Aggiungere altri livelli per trovare coincidenze ancora più precise', ok: false, f: 'Più livelli aumentano le coincidenze casuali, non l’affidabilità del metodo.' },
      { t: 'Usare solo i casi riusciti come esempi per gli altri', ok: false, f: 'Mostrare solo i successi è un classico bias di selezione: i casi falliti contano quanto quelli riusciti.' },
    ] },
    { s: 'Stefano, 56 anni, ha comprato sul 61,8% di un rialzo senza mettere uno stop. Il prezzo ha rotto anche il 78,6% e ora è vicino al minimo di partenza.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Riconosce che l’ipotesi di rimbalzo è smentita e applica una regola di uscita', ok: true, f: 'Rotti il 61,8% e il 78,6%, l’idea iniziale non regge più: limitare la perdita viene prima della speranza di recupero.' },
      { t: 'Aspetta che torni sul 61,8%, perché quel livello tiene sempre', ok: false, f: 'Il livello ha già fallito: aspettare senza un piano trasforma un errore gestibile in una perdita aperta.' },
      { t: 'Compra ancora per abbassare il prezzo medio di carico', ok: false, f: 'Mediare al ribasso su un’ipotesi smentita aumenta l’esposizione proprio quando il segnale è contrario.' },
    ] },
    { s: 'Sofia, 22 anni, trova un corso online che promette: «Con Fibonacci prevedi il 90% delle inversioni». Il corso usa sei livelli diversi su ogni grafico.', q: 'Come dovrebbe valutare la promessa?', o: [
      { t: 'Chiede come si misurano i successi con sei livelli in gioco', ok: true, f: 'Con tante zone ravvicinate il prezzo si fermerà quasi sempre vicino a una: senza una verifica rigorosa la percentuale non significa nulla.' },
      { t: 'Si iscrive subito: il 90% è una percentuale molto alta', ok: false, f: 'Una percentuale senza metodo di misura è solo marketing: nessuno strumento tecnico prevede le inversioni con quella affidabilità.' },
      { t: 'Si fida perché il rapporto aureo si trova anche in natura', ok: false, f: 'La presenza del rapporto aureo in natura non dimostra nulla sui mercati: servono dati, non analogie.' },
    ] },
  ],
  tip: 'Traccia Fibonacci su movimenti evidenti, scegli i punti prima di guardare la reazione e cerca confluenze: un livello è una zona di attenzione, non una promessa.',
});
