FQC(70, {
  intro: 'Efficienza dei mercati, bias di conferma, overfitting e costi: impari perché l’analisi tecnica non garantisce nulla e come usarla senza illuderti.',
  cards: [
    { t: 'Mercati (abbastanza) efficienti', x: 'Nella forma debole, l’ipotesi dei mercati efficienti sostiene che i prezzi passati siano già incorporati in quelli attuali: se valesse del tutto, i grafici non darebbero un vantaggio sistematico. Le evidenze empiriche sono miste.', v: { k: 'scale', a: 'Efficienza debole', b: 'Efficienza forte', d: [['Debole: prezzi passati', 20], ['Semi-forte: informazioni pubbliche', 55], ['Forte: anche informazioni riservate', 90]] } },
    { t: 'Il bias di conferma', x: 'Tendiamo a notare i segnali che confermano la nostra idea e a dimenticare quelli falliti. Sui grafici succede facilmente: le figure riuscite restano impresse, quelle identiche finite male scivolano via.', v: { k: 'vs', a: ['Ciò che ricordi', 'I pattern che hanno funzionato'], b: ['Ciò che dimentichi', 'I segnali identici finiti male'] } },
    { t: 'L’overfitting', x: 'Se ottimizzi i parametri sul passato finché i risultati sono perfetti, la strategia si adatta al rumore di quei dati, non a una regolarità reale. Su dati nuovi i risultati tendono a peggiorare, anche di molto.', v: { k: 'steps', s: ['Provi 1.000 combinazioni', 'Scegli la migliore sul passato', 'La applichi a dati nuovi', 'Scopri che era in gran parte rumore'] } },
    { t: 'I costi erodono il vantaggio', x: 'Commissioni, spread, slippage e tasse si pagano a ogni operazione. Una strategia con molti scambi deve guadagnare abbastanza da coprirli: un piccolo vantaggio lordo può diventare una perdita netta.', v: { k: 'formula', f: 'Risultato netto = lordo − commissioni − spread − slippage − tasse', n: 'Es.: 100 operazioni con lo 0,3% di costi ciascuna ≈ 30% del capitale, se investi tutto ogni volta' } },
    { t: 'Il caso sembra un trend', x: 'Anche serie di prezzi generate a caso mostrano trend, supporti e figure riconoscibili. Vedere uno schema non dimostra che abbia valore previsivo: va verificato su molti casi, con regole fissate prima.', v: { k: 'icons', d: [['🎲', 'Serie casuali'], ['👀', 'Schemi apparenti'], ['🧪', 'Verifica fuori campione']] } },
    { t: 'Probabilità, non garanzie', x: 'Anche una buona strategia perde spesso. Conta il valore atteso: probabilità di guadagno per guadagno medio, meno probabilità di perdita per perdita media, al netto dei costi. E serve un rischio per operazione sostenibile.', v: { k: 'formula', f: 'Valore atteso = p × guadagno medio − (1 − p) × perdita media', n: 'Es.: 0,4 × 300 € − 0,6 × 150 € = +30 € prima dei costi' } },
  ],
  terms: [
    ['Ipotesi dei mercati efficienti', 'Teoria secondo cui i prezzi riflettono rapidamente l’informazione disponibile.'],
    ['Random walk', 'Modello in cui le variazioni future dei prezzi non sono prevedibili da quelle passate.'],
    ['Bias di conferma', 'Tendenza a cercare e ricordare le informazioni che confermano le proprie convinzioni.'],
    ['Overfitting', 'Adattamento eccessivo di una strategia ai dati passati, rumore compreso.'],
    ['Backtest', 'Simulazione di una strategia su dati storici per stimarne il comportamento.'],
    ['Test fuori campione', 'Verifica di una strategia su dati non usati per costruirla o ottimizzarla.'],
    ['Slippage', 'Differenza tra il prezzo atteso di un ordine e quello a cui viene davvero eseguito.'],
    ['Valore atteso', 'Risultato medio per operazione, pesando guadagni e perdite per le loro probabilità.'],
  ],
  tf: [
    ['Nessun indicatore tecnico garantisce un guadagno.', true, 'Gli strumenti tecnici descrivono probabilità e contesto: anche i segnali migliori falliscono una parte delle volte.'],
    ['Se un pattern ha funzionato tre volte di fila, funzionerà anche la prossima.', false, 'Tre casi sono troppo pochi per una statistica e i successi passati non garantiscono quelli futuri.'],
    ['Nella forma debole dell’efficienza, dai soli prezzi passati non si ottiene un vantaggio sistematico.', true, 'È proprio ciò che la forma debole afferma: i prezzi passati sono già incorporati in quelli attuali.'],
    ['Un backtest con risultati eccellenti dimostra che la strategia funzionerà in futuro.', false, 'Può essere frutto di overfitting, di costi ignorati o di un periodo favorevole: servono test su dati nuovi e prudenza.'],
    ['Anche serie di prezzi casuali possono mostrare trend e figure apparenti.', true, 'Il nostro cervello cerca schemi anche nel rumore: per questo un pattern va verificato statisticamente, non solo riconosciuto.'],
    ['Più operazioni fai, meno incidono i costi sul risultato finale.', false, 'È il contrario: ogni operazione paga commissioni, spread e slippage, che si sommano. Più scambi richiedono un vantaggio maggiore.'],
    ['Una strategia può vincere meno della metà delle volte e avere comunque un valore atteso positivo.', true, 'Se i guadagni medi sono abbastanza più grandi delle perdite medie, il valore atteso, anche al netto dei costi, può essere positivo.'],
    ['Il bias di conferma porta a ricordare soprattutto i segnali che hanno funzionato.', true, 'I successi confermano ciò in cui crediamo e restano impressi; i fallimenti vengono dimenticati o giustificati.'],
    ['Ottimizzare molti parametri sugli stessi dati passati riduce il rischio di overfitting.', false, 'Più parametri regoli sugli stessi dati, più è facile adattarti al rumore: il rischio di overfitting aumenta.'],
    ['Se l’analisi tecnica ha dei limiti, allora è sempre inutile.', false, 'Può aiutare a strutturare decisioni, definire il rischio e gli scenari. Il punto è usarla con regole, verifiche e aspettative realistiche.'],
  ],
  mcq: [
    { q: 'Che cosa afferma la forma debole dell’ipotesi dei mercati efficienti?', a: 'Che i prezzi passati non offrono un vantaggio sistematico', w: ['Che anche le informazioni riservate sono già nei prezzi', 'Che i prezzi salgono sempre nel lungo periodo', 'Che nei mercati non si formano mai bolle o crisi'], e: 'La forma debole riguarda solo i prezzi passati; quella forte estende l’idea anche alle informazioni riservate.' },
    { q: 'Una strategia vince il 35% delle volte, con guadagno medio di 400 € e perdita media di 200 €. Qual è il valore atteso per operazione, prima dei costi?', a: '+10 €', w: ['+140 €', '−10 €', '+70 €'], e: '0,35 × 400 − 0,65 × 200 = 140 − 130 = +10 €. Un margine sottile: bastano costi modesti per renderlo negativo.' },
    { q: 'Qual è il segnale tipico di overfitting in un backtest?', a: 'Risultati ottimi sul passato che crollano su dati nuovi', w: ['Risultati simili su periodi e mercati diversi', 'Poche regole semplici fissate prima del test', 'Costi realistici inclusi nella simulazione'], e: 'Se la strategia brilla solo sui dati usati per costruirla, ha probabilmente imparato il rumore invece di una regolarità.' },
    { q: 'Una strategia guadagna in media lo 0,15% lordo per operazione e paga lo 0,20% tra commissioni e spread. Che cosa succede?', a: 'Perde in media lo 0,05% per operazione', w: ['Guadagna in media lo 0,35% per operazione', 'Guadagna in media lo 0,15% per operazione', 'Va in pari perché costi e guadagni si compensano'], e: '0,15% − 0,20% = −0,05%: un vantaggio lordo positivo diventa una perdita netta, che si ripete a ogni operazione.' },
    { q: 'Come si riduce il bias di conferma nell’analisi dei grafici?', a: 'Annotando tutti i segnali, anche quelli falliti', w: ['Guardando solo i grafici dei titoli in rialzo', 'Cercando forum che la pensano come te', 'Ricordando i casi di successo più evidenti'], e: 'Un diario completo mostra la vera frequenza di successo di un segnale, non quella che la memoria seleziona.' },
    { q: 'Che cos’è un test fuori campione?', a: 'Una verifica su dati non usati per costruire la strategia', w: ['Un test ripetuto sugli stessi dati già usati', 'Una simulazione fatta senza considerare i costi', 'Il confronto tra due indicatori nello stesso periodo'], e: 'Dati mai visti durante l’ottimizzazione sono il modo più semplice per capire se la strategia ha colto qualcosa di reale.' },
    { q: 'Perché alcuni livelli tecnici possono funzionare, almeno a volte?', a: 'Perché molti operatori vi piazzano i loro ordini', w: ['Perché leggi naturali governano i prezzi di Borsa', 'Perché la Borsa li fissa ogni mattina per legge', 'Perché i prezzi non possono mai attraversarli'], e: 'È l’effetto della profezia che si autoavvera: funziona finché abbastanza operatori agiscono sugli stessi livelli, e non sempre.' },
    { q: 'Qual è l’atteggiamento più corretto verso l’analisi tecnica?', a: 'Usarla come strumento probabilistico, con gestione del rischio', w: ['Considerarla un metodo per prevedere i prezzi con certezza', 'Scartarla del tutto perché qualche segnale fallisce', 'Applicarla senza stop perché i segnali si compensano'], e: 'Né oracolo né inutile: è un modo per strutturare decisioni, che va verificato e sempre accompagnato da un rischio limitato.' },
  ],
  fill: [
    { s: 'Adattare troppo una strategia ai dati passati, rumore compreso, si chiama ___.', a: 'overfitting', w: ['hedging', 'slippage', 'arbitraggio'] },
    { s: 'Il ___ di conferma ci porta a ricordare soprattutto i segnali riusciti.', a: 'bias', w: ['trend', 'test', 'margine'] },
    { s: 'La differenza tra prezzo atteso e prezzo effettivo di esecuzione si chiama ___.', a: 'slippage', w: ['spread', 'drawdown', 'leva'] },
    { s: 'Un test su dati non usati per costruire la strategia si dice fuori ___.', a: 'campione', w: ['mercato', 'bilancio', 'tempo'] },
    { s: 'Il valore ___ pesa guadagni e perdite per le rispettive probabilità.', a: 'atteso', w: ['nominale', 'contabile', 'di mercato'] },
  ],
  order: [
    { q: 'Ordina i passi di una verifica onesta di una strategia tecnica', i: ['Scrivi regole precise prima del test', 'Esegui il backtest includendo i costi', 'Verifica su dati fuori campione', 'Prova con capitale ridotto e rischio limitato'], e: 'Ogni passo filtra un’illusione diversa: regole vaghe, costi ignorati, overfitting e differenza tra simulazione e realtà.' },
    { q: 'Ordina le strategie dalla meno alla più esposta all’impatto dei costi', i: ['2 operazioni all’anno', '1 operazione al mese', '1 operazione al giorno', '20 operazioni al giorno'], e: 'A parità di costo per operazione, l’impatto cresce con la frequenza: più scambi richiedono un vantaggio lordo più alto.' },
  ],
  cat: [
    { q: 'Buona pratica o trappola?', g: [['Buona pratica', ['Fissare le regole prima del test', 'Includere costi e tasse', 'Tenere un diario di tutti i segnali', 'Limitare il rischio di ogni operazione']], ['Trappola', ['Ottimizzare finché il backtest è perfetto', 'Ricordare solo le operazioni vincenti', 'Ignorare commissioni e spread', 'Considerare certo un segnale']]] },
    { q: 'Costo esplicito o implicito del trading?', g: [['Esplicito', ['Commissione del broker', 'Imposta sulle plusvalenze', 'Canone della piattaforma']], ['Implicito', ['Spread bid-ask', 'Slippage', 'Impatto sul prezzo degli ordini grandi']]] },
  ],
  scen: [
    { s: 'Nicola, 32 anni, ha testato 2.000 combinazioni di parametri del MACD su cinque anni di FTSE MIB. La migliore avrebbe reso il 40% annuo, senza contare i costi.', q: 'Qual è la scelta più razionale?', o: [
      { t: 'La verifica fuori campione e con costi realistici', ok: true, f: 'Con 2.000 tentativi qualche combinazione brillerà per caso: solo dati nuovi e costi inclusi possono dire se c’è qualcosa di reale.' },
      { t: 'Investe subito tutti i risparmi: i numeri parlano chiaro', ok: false, f: 'Un backtest ottimizzato su migliaia di combinazioni è quasi certamente gonfiato dall’overfitting e dall’assenza di costi.' },
      { t: 'Aggiunge altri parametri per arrivare al 60% annuo', ok: false, f: 'Più parametri significano più adattamento al rumore: il risultato migliora sul passato e peggiora sul futuro.' },
    ] },
    { s: 'Elisa, 45 anni, ricorda cinque volte in cui il testa e spalle ha funzionato alla perfezione sui suoi titoli. Un collega le chiede quante volte la figura sia fallita.', q: 'Come dovrebbe rispondere in modo onesto?', o: [
      { t: 'Ricostruisce tutti i casi, inclusi i fallimenti, prima di giudicare', ok: true, f: 'La memoria seleziona i successi: solo un conteggio completo mostra la vera frequenza di riuscita del segnale.' },
      { t: 'Risponde che fallisce raramente, visto che ricorda solo successi', ok: false, f: 'Ricordare solo i successi è proprio l’effetto del bias di conferma, non una prova di affidabilità.' },
      { t: 'Cambia argomento: cinque successi bastano come prova', ok: false, f: 'Cinque casi, scelti dalla memoria, non sono un campione: senza i fallimenti la statistica è distorta.' },
    ] },
    { s: 'Gabriele, 26 anni, fa trading intraday con circa 15 operazioni al giorno. In media guadagna lo 0,05% lordo per operazione, ma tra commissioni e spread ne paga lo 0,08%.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Riduce la frequenza o sospende: al netto la strategia perde', ok: true, f: '0,05% − 0,08% = −0,03% a operazione, ripetuto 15 volte al giorno: il problema è strutturale, non di sfortuna.' },
      { t: 'Aumenta il numero di operazioni per compensare le perdite', ok: false, f: 'Con un valore atteso netto negativo, più operazioni significano più perdite, non meno.' },
      { t: 'Usa la leva per amplificare i guadagni lordi di ogni operazione', ok: false, f: 'La leva amplifica anche costi e perdite: su una strategia in perdita netta accelera solo il danno.' },
    ] },
    { s: 'Rosa, 61 anni, ha un portafoglio diversificato pensato per la pensione. Il nipote le mostra un grafico con un death cross e le dice: «L’analisi tecnica dice che crollerà, vendi tutto».', q: 'Come dovrebbe reagire Rosa?', o: [
      { t: 'Ricorda che un segnale è solo una probabilità e segue il piano', ok: true, f: 'Un singolo segnale tecnico non giustifica di stravolgere un piano costruito su obiettivi, orizzonte e tolleranza al rischio.' },
      { t: 'Vende tutto subito: se lo dice il grafico, è sicuro', ok: false, f: 'Nessun segnale è sicuro: vendere tutto per un indicatore espone a errori di tempismo, costi e tasse.' },
      { t: 'Compra a leva per scommettere contro il segnale', ok: false, f: 'Rispondere a una certezza sbagliata con un’altra, per giunta a leva, aumenta il rischio invece di gestirlo.' },
    ] },
  ],
  tip: 'Tratta ogni strategia tecnica come un’ipotesi da verificare: regole scritte prima, costi inclusi, test su dati nuovi, rischio limitato per operazione e un diario che registri anche le perdite.',
});
