FQC(71, {
  intro: 'Il PIL misura quanto produce un’economia, il ciclo ne descrive alti e bassi: capirli ti aiuta a leggere i mercati senza farti travolgere.',
  cards: [
    { t: 'Che cosa misura il PIL', x: 'Il Prodotto interno lordo è il valore dei beni e servizi finali prodotti in un paese in un periodo. Con il metodo della spesa si sommano consumi, investimenti, spesa pubblica ed esportazioni nette.', v: { k: 'formula', f: 'PIL = C + I + G + (X − M)', n: 'Consumi + Investimenti + Spesa pubblica + (Export − Import)' } },
    { t: 'Di cosa è fatto', x: 'Nelle economie avanzate i consumi delle famiglie sono di gran lunga la voce più grande. Valori indicativi, arrotondati, per un’economia europea come l’Italia.', v: { k: 'pie', d: [['Consumi', 60], ['Investimenti', 20], ['Spesa pubblica', 19], ['Export netto', 1]] } },
    { t: 'Nominale o reale?', x: 'Il PIL nominale cresce anche solo perché aumentano i prezzi. Per capire se si produce davvero di più si guarda il PIL reale, depurato con il deflatore.', v: { k: 'vs', a: ['PIL nominale', 'A prezzi correnti: include l’effetto dell’inflazione'], b: ['PIL reale', 'A prezzi costanti: misura la crescita effettiva'] } },
    { t: 'Le fasi del ciclo', x: 'L’economia alterna periodi di crescita e di calo. Le fasi non hanno durata fissa: un’espansione può durare pochi anni o più di un decennio.', v: { k: 'steps', s: ['Espansione', 'Picco', 'Contrazione', 'Minimo', 'Ripresa'] } },
    { t: 'La recessione tecnica', x: 'Due trimestri consecutivi di calo del PIL reale sono la regola empirica più usata. Non è l’unica definizione: negli USA il NBER data le recessioni guardando anche a occupazione, redditi e produzione.', v: { k: 'stat', n: '2 trimestri', l: 'consecutivi di calo del PIL reale' } },
    { t: 'Chi anticipa e chi segue', x: 'Alcuni indicatori si muovono prima del ciclo (borsa, nuovi ordini), altri insieme (produzione), altri dopo (disoccupazione). La borsa guarda avanti e spesso gira prima dell’economia.', v: { k: 'scale', a: 'Anticipa il ciclo', b: 'Segue il ciclo', d: [['Borsa', 8], ['Nuovi ordini', 25], ['Produzione industriale', 50], ['Disoccupazione', 88]] } },
  ],
  terms: [
    ['PIL', 'Valore di mercato dei beni e servizi finali prodotti in un paese in un dato periodo.'],
    ['PIL reale', 'Prodotto interno a prezzi costanti, depurato dall’effetto delle variazioni dei prezzi.'],
    ['Deflatore', 'Indice dei prezzi che trasforma il prodotto nominale in prodotto reale.'],
    ['Recessione tecnica', 'Due trimestri consecutivi di calo del prodotto interno reale.'],
    ['Output gap', 'Differenza tra produzione effettiva e potenziale; se positiva segnala surriscaldamento.'],
    ['Variazione congiunturale', 'Confronto con il periodo immediatamente precedente, ad esempio trimestre su trimestre.'],
    ['Variazione tendenziale', 'Confronto con lo stesso periodo dell’anno precedente.'],
    ['Indicatore anticipatore', 'Dato che tende a cambiare direzione prima dell’economia nel suo complesso.'],
  ],
  tf: [
    ['Il PIL conta solo i beni e servizi finali, non quelli intermedi.', true, 'Contare anche i beni intermedi (es. la farina usata dal panettiere) significherebbe conteggiare due volte lo stesso valore.'],
    ['Se il PIL nominale cresce del 4% e i prezzi del 3%, il PIL reale cresce di circa il 7%.', false, 'Il reale toglie l’effetto dei prezzi: circa 4% − 3% = 1%.'],
    ['Nel metodo della spesa le importazioni vengono sottratte.', true, 'Consumi e investimenti includono beni prodotti all’estero: togliendo le importazioni resta solo la produzione interna.'],
    ['Una borsa in forte rialzo significa sempre che l’economia sta crescendo in quel momento.', false, 'I mercati guardano avanti: spesso salgono quando l’economia è ancora debole ma si attende una ripresa, e scendono prima delle recessioni.'],
    ['La disoccupazione tende a essere un indicatore ritardatario del ciclo.', true, 'Le imprese assumono e licenziano con ritardo: la disoccupazione può continuare a salire anche dopo il minimo del ciclo.'],
    ['Un PIL in crescita garantisce che il reddito di ogni cittadino aumenti.', false, 'Il PIL è un aggregato: non dice nulla sulla distribuzione né sulla crescita della popolazione. Anche il PIL pro capite è solo una media.'],
    ['Negli Stati Uniti la crescita trimestrale del PIL viene comunicata di solito in forma annualizzata.', true, 'Un +0,5% nel trimestre diventa circa +2% annualizzato; in Europa si comunica di norma la variazione trimestrale non annualizzata.'],
    ['Le prime stime del PIL, una volta pubblicate, non vengono più modificate.', false, 'Le stime preliminari vengono riviste, a volte in modo significativo, man mano che arrivano dati più completi.'],
    ['Un output gap positivo indica un’economia sopra il suo potenziale, con possibili pressioni sui prezzi.', true, 'Quando si produce oltre il livello sostenibile, lavoro e impianti scarseggiano e salari e prezzi tendono a salire.'],
    ['La regola dei due trimestri negativi è la definizione ufficiale di recessione in tutti i paesi.', false, 'È una regola empirica. Negli USA, per esempio, il NBER data le recessioni valutando più indicatori, non solo il PIL.'],
  ],
  mcq: [
    { q: 'Quale formula descrive il PIL con il metodo della spesa?', a: 'C + I + G + (X − M)', w: ['C + I + G + (X + M)', 'C + I − G + (X − M)', 'C − I + G + (M − X)'], e: 'Consumi, investimenti e spesa pubblica più le esportazioni nette, cioè esportazioni meno importazioni.' },
    { q: 'Il PIL reale cala dello 0,1% in un trimestre e dello 0,3% nel successivo. Cosa si può dire?', a: 'È una recessione tecnica', w: ['È una ripresa moderata', 'È una fase di stagflazione', 'Serve il dato nominale per dirlo'], e: 'Due trimestri consecutivi di calo del PIL reale soddisfano la regola della recessione tecnica, anche se i cali sono piccoli.' },
    { q: 'Quale tra questi è tipicamente un indicatore anticipatore?', a: 'Nuovi ordini all’industria', w: ['Tasso di disoccupazione', 'Costo del lavoro per unità', 'Inflazione dei servizi'], e: 'Gli ordini precedono la produzione; disoccupazione, costo del lavoro e inflazione dei servizi tendono invece a seguire il ciclo.' },
    { q: 'Perché per valutare la crescita si guarda il PIL reale?', a: 'Perché elimina l’effetto dei prezzi', w: ['Perché include l’economia sommersa', 'Perché esclude la spesa pubblica', 'Perché è espresso in dollari'], e: 'Il PIL nominale può salire solo per l’inflazione; quello reale mostra se si producono davvero più beni e servizi.' },
    { q: 'In quale fase del ciclo l’utilizzo degli impianti e le pressioni sui prezzi sono di solito più alti?', a: 'Vicino al picco', w: ['Al minimo del ciclo', 'All’inizio della ripresa', 'A metà della contrazione'], e: 'Vicino al picco la capacità produttiva è molto sfruttata e il mercato del lavoro è teso: è lì che le pressioni inflazionistiche tendono a crescere.' },
    { q: 'Un dato USA indica crescita del PIL del +2% annualizzato. A quanto corrisponde circa la variazione nel trimestre?', a: 'Circa +0,5%', w: ['Circa +2%', 'Circa +8%', 'Circa +0,2%'], e: 'L’annualizzazione proietta il ritmo del trimestre su un anno: (1,005)^4 ≈ 1,02, quindi circa +0,5% trimestrale.' },
    { q: 'Quale affermazione sul legame tra borsa ed economia è più corretta?', a: 'La borsa tende ad anticipare il ciclo', w: ['La borsa segue il PIL di un anno', 'La borsa sale solo se il PIL cresce', 'La borsa non dipende mai dal ciclo'], e: 'I prezzi riflettono attese su utili futuri: per questo la borsa spesso gira prima dell’economia reale, sia al ribasso sia al rialzo.' },
    { q: 'Cosa indica un output gap negativo?', a: 'Economia sotto il potenziale', w: ['Economia surriscaldata', 'Bilancia commerciale in deficit', 'Debito pubblico oltre il PIL'], e: 'Produzione sotto il potenziale significa risorse inutilizzate, come disoccupazione e impianti fermi, e di solito poche pressioni sui prezzi.' },
  ],
  fill: [
    { s: 'Due trimestri consecutivi di calo del PIL reale sono detti recessione ___.', a: 'tecnica', w: ['strutturale', 'nominale', 'potenziale'] },
    { s: 'Il confronto tra un trimestre e lo stesso trimestre dell’anno prima è una variazione ___.', a: 'tendenziale', w: ['congiunturale', 'annualizzata', 'marginale'] },
    { s: 'Il PIL ___ è depurato dall’effetto delle variazioni dei prezzi.', a: 'reale', w: ['nominale', 'potenziale', 'lordo'] },
    { s: 'Il punto più alto del ciclo, prima della contrazione, si chiama ___.', a: 'picco', w: ['minimo', 'ripresa', 'plateau'] },
    { s: 'Nel metodo della spesa le ___ vengono sottratte perché prodotte all’estero.', a: 'importazioni', w: ['esportazioni', 'imposte', 'scorte'] },
  ],
  order: [
    { q: 'Ordina le fasi del ciclo economico partendo dall’espansione', i: ['Espansione', 'Picco', 'Contrazione', 'Minimo', 'Ripresa'], e: 'Dopo l’espansione si raggiunge il picco, poi la contrazione fino al minimo, da cui parte la ripresa che apre un nuovo ciclo.' },
    { q: 'Ordina dall’indicatore che di solito anticipa di più il ciclo a quello che lo segue di più', i: ['Indici di borsa', 'Nuovi ordini industriali', 'Produzione industriale', 'Tasso di disoccupazione'], e: 'La borsa sconta il futuro, gli ordini precedono la produzione, la produzione è coincidente e la disoccupazione reagisce per ultima.' },
  ],
  cat: [
    { q: 'Nel PIL (metodo della spesa) è un consumo o un investimento?', g: [['Consumi', ['Spesa alimentare di una famiglia', 'Taglio di capelli', 'Abbonamento in palestra']], ['Investimenti', ['Nuovo macchinario per una fabbrica', 'Costruzione di un capannone', 'Software acquistato da un’impresa']]] },
    { q: 'Indicatore anticipatore o ritardatario?', g: [['Anticipatore', ['Indici di borsa', 'Nuovi ordini industriali', 'Permessi di costruzione']], ['Ritardatario', ['Tasso di disoccupazione', 'Costo del lavoro per unità di prodotto', 'Inflazione dei servizi']]] },
  ],
  scen: [
    { s: 'Marco, 45 anni, investe da anni con un PAC su un ETF azionario globale pensato per i prossimi 20 anni. Legge il titolo “Italia in recessione tecnica” dopo due trimestri a −0,1% e vuole vendere tutto.', q: 'Cosa gli consigli di fare?', o: [
      { t: 'Verificare se obiettivi e orizzonte sono cambiati', ok: true, f: 'Il dato era in gran parte atteso e la borsa anticipa il ciclo. Se il piano resta valido, una recessione lieve non è un motivo per smontarlo.' },
      { t: 'Vendere tutto e rientrare quando il PIL tornerà positivo', ok: false, f: 'Quando il PIL torna positivo la borsa ha spesso già recuperato molto: si rischia di vendere in basso e ricomprare in alto.' },
      { t: 'Comprare a leva perché “la borsa anticipa sempre la ripresa”', ok: false, f: 'Anticipare non significa prevedere con certezza i tempi. La leva può trasformare un calo temporaneo in una perdita permanente.' },
    ] },
    { s: 'Giulia, 30 anni, confronta due paesi per un ETF regionale. Nel paese A il PIL nominale è cresciuto del 6% con inflazione al 5%; nel paese B del 3% con inflazione all’1%.', q: 'Quale economia è cresciuta di più in termini reali?', o: [
      { t: 'Il paese B, con circa +2% reale', ok: true, f: 'Togliendo l’inflazione, A cresce di circa l’1% e B di circa il 2%: il numero nominale più alto nascondeva soprattutto prezzi in salita.' },
      { t: 'Il paese A, perché +6% è più del doppio di +3%', ok: false, f: 'Confronta grandezze nominali: gran parte della crescita di A è solo inflazione.' },
      { t: 'Sono uguali, perché l’inflazione non conta', ok: false, f: 'L’inflazione conta eccome: è proprio ciò che separa la crescita nominale da quella reale.' },
    ] },
    { s: 'Luca, 52 anni, legge che il PIL USA è cresciuto del 3% annualizzato e quello dell’area euro dello 0,4% nel trimestre. Conclude che gli USA crescono quasi 8 volte più dell’Europa.', q: 'Come dovrebbe leggere i due dati?', o: [
      { t: 'Riportarli sulla stessa base prima di confrontarli', ok: true, f: '3% annualizzato è circa 0,74% nel trimestre; 0,4% trimestrale è circa 1,6% annualizzato. Gli USA crescono di più, ma meno del doppio, non 8 volte.' },
      { t: 'Prenderli così come sono: sono entrambi dati ufficiali', ok: false, f: 'Ufficiali sì, ma calcolati in modo diverso: confrontare un dato annualizzato con uno trimestrale porta a conclusioni sbagliate.' },
      { t: 'Sommare i due dati per avere la crescita mondiale', ok: false, f: 'Non ha senso sommare tassi di crescita di economie diverse, tanto meno se espressi su basi diverse.' },
    ] },
    { s: 'Elena, 60 anni, andrà in pensione tra 5 anni. Legge che l’economia è vicina al picco del ciclo: output gap positivo, disoccupazione ai minimi, inflazione in risalita.', q: 'Qual è la scelta più ragionevole?', o: [
      { t: 'Ribilanciare secondo il piano, coerente con i 5 anni', ok: true, f: 'Nessuno sa quando il ciclo girerà. Allineare il rischio all’orizzonte protegge senza dover indovinare il momento esatto.' },
      { t: 'Spostare tutto su azioni cicliche perché l’economia va forte', ok: false, f: 'Vicino al picco i settori ciclici sono i più esposti a un’inversione, e un orizzonte di 5 anni non regge rischi concentrati.' },
      { t: 'Vendere tutto subito perché la recessione è certa', ok: false, f: 'I segnali di fine ciclo possono durare a lungo: uscire del tutto può far perdere anni di rendimenti senza alcuna certezza.' },
    ] },
  ],
  tip: 'Davanti a un dato di PIL chiediti: è reale o nominale? Congiunturale, tendenziale o annualizzato? Com’era rispetto alle attese? Solo così il numero ha senso.',
});
