FQC(72, {
  intro: 'NIC, FOI, IPCA, core: scopri come si misura l’inflazione e perché mercati e BCE guardano a indici diversi.',
  cards: [
    { t: 'Come nasce un indice', x: 'L’ISTAT sceglie un paniere di beni e servizi, gli dà pesi in base a quanto le famiglie spendono, rileva i prezzi ogni mese e calcola l’indice. Paniere e pesi vengono aggiornati ogni anno.', v: { k: 'steps', s: ['Paniere', 'Pesi di spesa', 'Rilevazione prezzi', 'Indice e variazioni'] } },
    { t: 'Dall’indice al tasso', x: 'L’inflazione annua è la variazione percentuale dell’indice rispetto allo stesso mese dell’anno prima. Il livello dell’indice da solo non dice nulla: conta il confronto.', v: { k: 'formula', f: 'Inflazione a/a = (Indice oggi ÷ Indice di 12 mesi prima − 1) × 100', n: 'Es.: 106,1 ÷ 103,0 − 1 ≈ 3,0%' } },
    { t: 'Tre indici ISTAT', x: 'Il NIC riguarda tutta la popolazione; il FOI le famiglie di operai e impiegati ed è usato per rivalutare affitti e assegni; l’IPCA segue regole comuni UE ed è quello confrontabile tra paesi.', v: { k: 'icons', d: [['🇮🇹', 'NIC: intera collettività'], ['👷', 'FOI: operai e impiegati'], ['🇪🇺', 'IPCA: armonizzato UE']] } },
    { t: 'Headline e core', x: 'L’inflazione complessiva (headline) include energia e alimentari, molto volatili. La core li esclude per mostrare la tendenza di fondo, quella che più interessa alle banche centrali.', v: { k: 'vs', a: ['Headline', 'Tutto il paniere: è ciò che paghi davvero'], b: ['Core', 'Senza le voci più volatili: mostra la tendenza'] } },
    { t: 'L’obiettivo della BCE', x: 'La BCE mira a un’inflazione del 2% nel medio termine, misurata sull’indice armonizzato dell’intera area euro. L’obiettivo è simmetrico: deviazioni sopra o sotto sono ugualmente indesiderate.', v: { k: 'stat', n: '2%', l: 'obiettivo simmetrico BCE nel medio termine (HICP area euro)' } },
    { t: 'L’effetto base', x: 'Se un anno fa i prezzi erano saliti molto, il tasso annuo di oggi può crollare anche senza alcun calo dei prezzi. Esempio: indice +8% in un anno, poi +1% l’anno dopo.', v: { k: 'bars', d: [['Anno 1', 100], ['Anno 2', 108], ['Anno 3', 109]] } },
  ],
  terms: [
    ['IPCA', 'Indice dei prezzi al consumo armonizzato a livello UE, confrontabile tra i paesi membri.'],
    ['NIC', 'Indice ISTAT dei prezzi al consumo riferito all’intera collettività nazionale.'],
    ['FOI', 'Indice ISTAT per le famiglie di operai e impiegati, usato per rivalutare affitti e assegni.'],
    ['Inflazione core', 'Inflazione calcolata escludendo le componenti più volatili, come energia e alimentari.'],
    ['Paniere', 'Insieme di beni e servizi rappresentativi dei consumi, di cui si rilevano i prezzi.'],
    ['Disinflazione', 'Rallentamento dell’aumento dei prezzi: crescono ancora, ma più lentamente.'],
    ['Deflazione', 'Calo generalizzato e persistente del livello dei prezzi.'],
    ['Effetto base', 'Impatto sul tasso annuo di ciò che accadde ai prezzi nello stesso mese dell’anno prima.'],
  ],
  tf: [
    ['La BCE fissa il suo obiettivo sull’indice armonizzato dei prezzi dell’intera area euro.', true, 'L’obiettivo del 2% nel medio termine riguarda l’HICP dell’area euro nel suo insieme, non l’inflazione di un singolo paese.'],
    ['Disinflazione significa che i prezzi stanno scendendo.', false, 'Con la disinflazione i prezzi salgono ancora, ma più lentamente. Se scendono si parla di deflazione.'],
    ['L’inflazione core esclude le componenti più volatili, come energia e alimentari.', true, 'Togliendo le voci più ballerine si vede meglio la tendenza di fondo, meno influenzata da shock temporanei.'],
    ['Se l’inflazione passa dal 5% al 3%, i prezzi medi sono più bassi di un anno fa.', false, 'Sono comunque più alti del 3% rispetto a un anno prima: è calato il ritmo di aumento, non il livello dei prezzi.'],
    ['L’IPCA può differire dal NIC anche perché tiene conto dei prezzi scontati di saldi e promozioni.', true, 'L’IPCA considera i prezzi effettivamente pagati, inclusi saldi e promozioni; anche i pesi delle voci sono diversi.'],
    ['Per la BCE un’inflazione all’1% è sempre preferibile a una al 2%.', false, 'L’obiettivo è il 2% simmetrico: un’inflazione troppo bassa è indesiderata quanto una troppo alta, perché avvicina il rischio di deflazione.'],
    ['L’inflazione percepita dalle famiglie coincide sempre con quella misurata dall’ISTAT.', false, 'La percezione è influenzata dagli acquisti frequenti, come spesa e carburante, e dal paniere personale, che può essere molto diverso dalla media.'],
    ['Paniere e pesi dell’indice dei prezzi vengono aggiornati periodicamente.', true, 'L’ISTAT li aggiorna ogni anno: entrano nuovi prodotti, ne escono altri e cambiano le quote di spesa.'],
    ['Un forte rincaro dell’energia un anno fa può far scendere l’inflazione annua di oggi anche se i prezzi non calano.', true, 'È l’effetto base: il confronto avviene con un mese già molto caro, quindi la variazione annua si riduce.'],
    ['L’inflazione headline è sempre più alta di quella core.', false, 'Dipende: quando energia e cibo scendono di prezzo l’headline può finire sotto la core, come accade spesso dopo uno shock energetico.'],
  ],
  mcq: [
    { q: 'Quale indice ISTAT si usa di norma per rivalutare canoni di affitto e assegni di mantenimento?', a: 'FOI', w: ['IPCA', 'NIC', 'Indice core'], e: 'Il FOI (nella versione senza tabacchi) è l’indice di riferimento per molti adeguamenti previsti da leggi e contratti.' },
    { q: 'Perché le banche centrali guardano con attenzione all’inflazione core?', a: 'Segnala meglio la tendenza di fondo', w: ['Include solo i beni importati', 'È sempre più bassa dell’headline', 'Esclude servizi e affitti'], e: 'Senza energia e alimentari, la core è meno disturbata dagli shock temporanei e dice di più sulla persistenza dell’inflazione.' },
    { q: 'L’indice dei prezzi passa da 120 a 123 in un anno. Qual è l’inflazione annua?', a: '2,5%', w: ['3%', '3,5%', '1,5%'], e: '123 ÷ 120 − 1 = 0,025, cioè 2,5%. Non basta la differenza di punti: va divisa per il livello di partenza.' },
    { q: 'Quale scenario descrive la stagflazione?', a: 'Prezzi in forte crescita, economia ferma', w: ['Prezzi in calo, economia in boom', 'Prezzi stabili, economia in crescita', 'Prezzi in calo, economia in recessione'], e: 'Stagflazione = stagnazione + inflazione: un mix difficile perché alzare i tassi frena ancora di più la crescita.' },
    { q: 'Qual è l’obiettivo di inflazione della BCE?', a: '2% simmetrico nel medio termine', w: ['Sotto il 2% in ogni singolo mese', 'Tra lo 0% e l’1% ogni anno', '3% con banda di tolleranza'], e: 'Dal 2021 la BCE punta al 2% nel medio termine, con deviazioni sopra e sotto considerate ugualmente indesiderate.' },
    { q: 'Perché una deflazione persistente preoccupa le banche centrali?', a: 'Spinge a rinviare le spese e appesantisce i debiti', w: ['Fa crescere in automatico salari e profitti', 'Riduce sempre il valore reale dei debiti', 'Rende inutile il risparmio delle famiglie'], e: 'Se i prezzi calano conviene aspettare a comprare, mentre i debiti fissi pesano di più in termini reali: si rischia una spirale di domanda debole.' },
    { q: 'Quale indice dei prezzi al consumo usa una metodologia comune a tutti i paesi UE?', a: 'IPCA', w: ['NIC', 'FOI', 'Deflatore del PIL'], e: 'L’IPCA è la versione italiana dell’HICP: regole comuni permettono di confrontare l’inflazione tra i paesi dell’Unione.' },
    { q: 'Quale situazione descrive meglio un’inflazione “da costi”?', a: 'Rincari dell’energia trasferiti sui prezzi finali', w: ['Famiglie che spendono più dell’offerta disponibile', 'Banca centrale che alza i tassi per frenare il credito', 'Calo generalizzato della domanda di beni durevoli'], e: 'Nell’inflazione da costi i prezzi salgono perché produrre costa di più; in quella da domanda perché si vuole comprare più di quanto si produce.' },
  ],
  fill: [
    { s: 'L’inflazione ___ esclude energia e alimentari per cogliere la tendenza di fondo.', a: 'core', w: ['headline', 'importata', 'percepita'] },
    { s: 'Quando i prezzi crescono ma a un ritmo sempre più lento si parla di ___.', a: 'disinflazione', w: ['deflazione', 'stagflazione', 'svalutazione'] },
    { s: 'L’indice ___ è calcolato con regole comuni in tutta l’Unione europea.', a: 'IPCA', w: ['NIC', 'FOI', 'PMI'] },
    { s: 'Il ___ è l’insieme di beni e servizi di cui l’ISTAT rileva i prezzi.', a: 'paniere', w: ['listino', 'catalogo', 'portafoglio'] },
    { s: 'Un calo dell’inflazione annua dovuto ai forti rincari dell’anno prima si chiama effetto ___.', a: 'base', w: ['leva', 'ricchezza', 'soglia'] },
  ],
  order: [
    { q: 'Ordina dalla variazione dei prezzi più bassa alla più alta', i: ['Deflazione', 'Stabilità dei prezzi', 'Inflazione elevata', 'Iperinflazione'], e: 'In deflazione i prezzi calano; la stabilità corrisponde a circa il 2%; poi l’inflazione elevata e, all’estremo, l’iperinflazione con prezzi fuori controllo.' },
    { q: 'Ordina i passaggi per costruire e leggere un indice dei prezzi al consumo', i: ['Scegliere il paniere', 'Assegnare i pesi in base alla spesa', 'Rilevare i prezzi', 'Calcolare l’indice', 'Calcolare la variazione annua'], e: 'Prima si definisce cosa misurare e quanto pesa, poi si rilevano i prezzi, si calcola l’indice e infine lo si confronta con 12 mesi prima.' },
  ],
  cat: [
    { q: 'Esclusa o inclusa nella misura core più usata nell’area euro (senza energia, alimentari, alcol e tabacchi)?', g: [['Esclusa', ['Bolletta della luce', 'Carburante', 'Frutta e verdura']], ['Inclusa', ['Taglio di capelli', 'Abbigliamento', 'Biglietto aereo']]] },
    { q: 'Spinta inflazionistica da domanda o da costi?', g: [['Da domanda', ['Forte aumento del credito alle famiglie', 'Boom dei consumi dopo un periodo di risparmio forzato', 'Ampio stimolo fiscale in piena occupazione']], ['Da costi', ['Rincaro del petrolio', 'Euro debole che rincara le importazioni', 'Strozzature nelle catene di fornitura']]] },
  ],
  scen: [
    { s: 'Chiara, 34 anni, legge: “Inflazione headline scesa all’1,5%, core ferma al 3%”. Pensa che la BCE taglierà i tassi alla prossima riunione e vuole comprare titoli lunghi per guadagnare dal taglio.', q: 'Come dovrebbe ragionare?', o: [
      { t: 'Considerare che la BCE guarda anche alla core e al medio termine', ok: true, f: 'Il calo dell’headline può dipendere dall’energia; con una core al 3% la BCE potrebbe non avere fretta. Scommettere su un taglio certo è rischioso.' },
      { t: 'Comprare subito: con l’1,5% il taglio è sicuro', ok: false, f: 'Le decisioni dipendono da più dati e dalle proiezioni: l’headline di un mese non basta, e un taglio atteso può essere già nei prezzi.' },
      { t: 'Vendere tutti i titoli: l’inflazione core al 3% è iperinflazione', ok: false, f: 'Un 3% è sopra l’obiettivo, ma lontanissimo dall’iperinflazione: reazioni estreme a dati moderati portano a scelte sbagliate.' },
    ] },
    { s: 'Roberto, 47 anni, vuole capire se i prezzi crescono più in Italia o in Germania. Confronta il NIC italiano con l’indice nazionale tedesco e trova una differenza di mezzo punto.', q: 'Qual è il metodo corretto?', o: [
      { t: 'Confrontare gli indici armonizzati dei due paesi', ok: true, f: 'Gli indici nazionali usano metodi e panieri diversi; quelli armonizzati seguono regole comuni e sono fatti apposta per i confronti.' },
      { t: 'Va bene così: sono due indici ufficiali', ok: false, f: 'Ufficiali ma non omogenei: parte della differenza potrebbe dipendere dal metodo e non dai prezzi.' },
      { t: 'Usare il FOI italiano al posto del NIC', ok: false, f: 'Anche il FOI è un indice nazionale: il problema di metodi non omogenei resterebbe.' },
    ] },
    { s: 'Annalisa, 29 anni, vede che a settembre i prezzi sono saliti dello 0,8% rispetto ad agosto e scrive in chat che “l’inflazione annua è allo 0,8%”.', q: 'Cosa le faresti notare?', o: [
      { t: 'Che quella è una variazione mensile, non annua', ok: true, f: 'La variazione congiunturale confronta due mesi vicini; quella tendenziale 12 mesi. Inoltre a settembre pesano effetti stagionali, come la fine dei saldi.' },
      { t: 'Che l’annua si ottiene moltiplicando per dieci', ok: false, f: 'Non esiste una regola così: un singolo mese può essere distorto da stagionalità e non va proiettato meccanicamente su un anno.' },
      { t: 'Che ha ragione: mensile e annua coincidono', ok: false, f: 'Confondere variazione mensile e annua è uno degli errori più comuni nella lettura dei dati sui prezzi.' },
    ] },
    { s: 'Davide, 58 anni, tiene 40.000 € fermi sul conto corrente: “Tanto l’inflazione ora è solo al 2%, non mi tocca”. Non ha bisogno di quei soldi per almeno 10 anni.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che al 2% in 10 anni perde circa il 18% di potere d’acquisto', ok: true, f: '1 ÷ 1,02^10 ≈ 0,82: un’inflazione “normale” erode comunque molto nel tempo. Conviene valutare strumenti adatti a un orizzonte di 10 anni.' },
      { t: 'Che con un’inflazione al 2% il problema non esiste', ok: false, f: 'Il 2% composto per 10 anni pesa: la stabilità dei prezzi non significa che il denaro fermo conservi il suo valore.' },
      { t: 'Che deve mettere tutto in oro per difendersi', ok: false, f: 'Concentrare tutto in un solo bene volatile non è una protezione: l’oro può perdere molto anche per anni.' },
    ] },
  ],
  tip: 'Quando esce un dato d’inflazione guarda insieme headline, core e variazione mensile: il titolo del giornale, da solo, racconta mezza storia.',
});
