FQC(73, {
  intro: 'BCE e Fed decidono il costo del denaro per centinaia di milioni di persone: scopri mandati, tassi ufficiali e perché la loro indipendenza conta.',
  cards: [
    { t: 'Due mandati diversi', x: 'Il Trattato UE assegna alla BCE un obiettivo primario: la stabilità dei prezzi. La Fed ha invece un doppio mandato fissato dal Congresso: prezzi stabili e massima occupazione.', v: { k: 'vs', a: ['BCE', 'Mandato primario: stabilità dei prezzi (2% simmetrico)'], b: ['Fed', 'Doppio mandato: prezzi stabili e massima occupazione'] } },
    { t: 'Il corridoio della BCE', x: 'La BCE fissa tre tassi ufficiali: depositi, rifinanziamento principale e rifinanziamento marginale. Con l’ampia liquidità degli ultimi anni, il tasso sui depositi è diventato il riferimento principale.', v: { k: 'scale', a: 'Tasso più basso', b: 'Tasso più alto', d: [['Depositi', 15], ['Rifinanziamento principale', 50], ['Rifinanziamento marginale', 85]] } },
    { t: 'Come arriva a te', x: 'Una mossa sui tassi ufficiali si trasmette ai tassi tra banche, poi a mutui e prestiti, e infine a domanda e prezzi. Il percorso richiede tempo: spesso uno-due anni per l’effetto pieno.', v: { k: 'steps', s: ['Tasso ufficiale', 'Tassi interbancari (€STR, Euribor)', 'Mutui e prestiti', 'Domanda e inflazione'] } },
    { t: 'Chi decide', x: 'Nell’area euro decide il Consiglio direttivo della BCE, formato dal Comitato esecutivo e dai governatori delle banche centrali nazionali. Negli USA decide il FOMC, che si riunisce otto volte l’anno.', v: { k: 'icons', d: [['🇪🇺', 'Consiglio direttivo BCE'], ['🇺🇸', 'FOMC della Fed'], ['🏛️', 'Banca d’Italia nell’Eurosistema']] } },
    { t: 'Il passo classico', x: 'I tassi si muovono di solito a passi di 25 punti base, cioè 0,25 punti percentuali. Mosse da 50 o 75 pb segnalano urgenza, tipica di fasi di inflazione alta o di crisi.', v: { k: 'stat', n: '25 pb', l: 'il passo tipico di un rialzo o di un taglio (0,25 punti)' } },
    { t: 'Restrittiva o accomodante?', x: 'Per giudicare la politica monetaria conta il tasso reale. Un tasso nominale “alto” può essere ancora accomodante se l’inflazione attesa è più alta.', v: { k: 'formula', f: 'Tasso reale ≈ tasso nominale − inflazione attesa', n: 'Es.: 3% − 2% ≈ 1% reale' } },
  ],
  terms: [
    ['Doppio mandato', 'Obiettivo della Fed che unisce stabilità dei prezzi e massima occupazione.'],
    ['Tasso sui depositi', 'Remunerazione BCE sulla liquidità che le banche lasciano overnight presso l’Eurosistema.'],
    ['Fed funds', 'Tasso overnight tra banche USA, per cui la Fed fissa una fascia obiettivo.'],
    ['FOMC', 'Comitato della Fed che decide la politica monetaria USA.'],
    ['Eurosistema', 'Insieme della BCE e delle banche centrali nazionali dei paesi che usano l’euro.'],
    ['Falco', 'Banchiere centrale più incline a tassi alti per contrastare l’inflazione.'],
    ['Forward guidance', 'Comunicazione sulle probabili mosse future dei tassi per orientare le aspettative.'],
    ['Finanziamento monetario', 'Acquisto di debito pubblico all’emissione da parte della banca centrale: vietato nell’UE.'],
  ],
  tf: [
    ['L’obiettivo primario della BCE è la stabilità dei prezzi.', true, 'Lo stabilisce il Trattato UE; il sostegno alle politiche economiche generali viene dopo, senza pregiudicare la stabilità dei prezzi.'],
    ['La Fed ha come unico obiettivo un’inflazione al 2%, proprio come la BCE.', false, 'La Fed ha un doppio mandato: stabilità dei prezzi e massima occupazione.'],
    ['La BCE può comprare titoli di Stato direttamente all’emissione per finanziare un governo.', false, 'Il Trattato vieta il finanziamento monetario: gli eventuali acquisti avvengono solo sul mercato secondario.'],
    ['La Fed esprime il suo obiettivo del 2% sull’inflazione PCE, non sul CPI.', true, 'Dal 2012 il target ufficiale è il 2% sull’indice dei prezzi delle spese per consumi personali (PCE).'],
    ['Un banchiere centrale “colomba” tende a preferire tassi più alti per combattere l’inflazione.', false, 'Quella è la posizione del “falco”; la colomba dà più peso a crescita e occupazione e preferisce tassi più bassi.'],
    ['Un rialzo dei tassi ufficiali produce i suoi effetti pieni sull’inflazione entro poche settimane.', false, 'La trasmissione agisce con ritardi lunghi e variabili, spesso stimati in uno-due anni.'],
    ['L’indipendenza della banca centrale serve a rendere credibile l’impegno contro l’inflazione.', true, 'Se i governi potessero decidere i tassi, sarebbero tentati di tenerli bassi prima delle elezioni: le aspettative d’inflazione salirebbero.'],
    ['Se il tasso ufficiale è al 3% e l’inflazione attesa al 4%, il tasso reale è negativo.', true, '3% − 4% ≈ −1%: anche con tassi nominali che sembrano alti la politica può restare accomodante.'],
    ['La Banca d’Italia decide in autonomia i tassi di interesse validi per l’Italia.', false, 'Fa parte dell’Eurosistema: i tassi li decide il Consiglio direttivo della BCE, in cui siede anche il governatore della Banca d’Italia.'],
    ['Il tasso sui depositi è il più basso dei tre tassi ufficiali della BCE.', true, 'Depositi < rifinanziamento principale < rifinanziamento marginale: il corridoio delimita i tassi del mercato overnight.'],
  ],
  mcq: [
    { q: 'Quale organo decide i tassi di interesse ufficiali nell’area euro?', a: 'Il Consiglio direttivo della BCE', w: ['Il Parlamento europeo', 'La Commissione europea', 'L’Eurogruppo dei ministri'], e: 'Le decisioni di politica monetaria spettano al Consiglio direttivo della BCE, indipendente da governi e istituzioni UE.' },
    { q: 'Quali sono i due obiettivi del mandato della Fed?', a: 'Prezzi stabili e massima occupazione', w: ['Prezzi stabili e dollaro forte', 'Massima occupazione e debito basso', 'Crescita del PIL e borsa stabile'], e: 'Il Congresso USA ha assegnato alla Fed il doppio mandato: stabilità dei prezzi e massima occupazione.' },
    { q: 'Il tasso ufficiale sale dal 2,50% al 2,75%. Di quanto è il rialzo?', a: '25 punti base', w: ['2,5 punti base', '0,25 punti base', '250 punti base'], e: 'Un punto percentuale vale 100 punti base: 0,25 punti percentuali sono 25 pb.' },
    { q: 'Perché le banche centrali usano la forward guidance?', a: 'Per orientare aspettative e tassi di mercato', w: ['Per fissare per legge i tassi dei mutui', 'Per obbligare le banche a prestare di più', 'Per stabilire il cambio euro-dollaro'], e: 'Dicendo cosa probabilmente faranno, influenzano subito i tassi a più lunga scadenza, che dipendono dalle attese sui tassi futuri.' },
    { q: 'L’inflazione è molto sopra l’obiettivo e in accelerazione. Quale reazione è tipica di una banca centrale?', a: 'Alzare i tassi ufficiali', w: ['Tagliare i tassi ufficiali', 'Aumentare gli acquisti di titoli', 'Abbassare il tasso sui depositi'], e: 'Tassi più alti rendono il credito più caro, frenano la domanda e aiutano a riportare l’inflazione verso l’obiettivo.' },
    { q: 'Cosa significa che l’obiettivo della BCE è “simmetrico”?', a: 'Sopra o sotto il 2% è ugualmente indesiderato', w: ['L’inflazione deve restare tra 0% e 2%', 'Il 2% va rispettato in ogni singolo mese', 'Ogni paese ha un proprio obiettivo del 2%'], e: 'Dal 2021 la BCE considera ugualmente indesiderato stare troppo sotto o troppo sopra il 2% nel medio termine.' },
    { q: 'Quale rischio è associato a una banca centrale non indipendente dal governo?', a: 'Pressioni a finanziare deficit e più inflazione', w: ['Tassi sempre troppo alti e deflazione', 'Impossibilità di stampare banconote', 'Cambio fisso obbligatorio con il dollaro'], e: 'Un governo può essere tentato di finanziare la spesa con la banca centrale: le aspettative d’inflazione salgono e la credibilità crolla.' },
    { q: 'Quale strumento è tipico della Fed e non della BCE?', a: 'Il dot plot con le previsioni sui tassi', w: ['Il tasso di rifinanziamento principale', 'Il tasso sui depositi overnight', 'Il Consiglio con i governatori nazionali'], e: 'Il dot plot raccoglie le previsioni dei singoli membri FOMC sul livello futuro dei tassi; gli altri tre sono elementi della BCE.' },
  ],
  fill: [
    { s: 'Negli Stati Uniti la politica monetaria è decisa dal ___.', a: 'FOMC', w: ['FMI', 'Tesoro', 'Congresso'] },
    { s: 'Il ___ di una banca centrale è l’obiettivo che la legge le assegna.', a: 'mandato', w: ['bilancio', 'corridoio', 'capitale'] },
    { s: 'Un banchiere centrale che dà più peso alla crescita e preferisce tassi bassi è detto ___.', a: 'colomba', w: ['falco', 'orso', 'toro'] },
    { s: 'Nell’UE il divieto di finanziamento ___ impedisce alla BCE di comprare titoli di Stato all’emissione.', a: 'monetario', w: ['bancario', 'fiscale', 'privato'] },
    { s: 'Un rialzo di mezzo punto percentuale equivale a ___ punti base.', a: '50', w: ['5', '0,5', '500'] },
  ],
  order: [
    { q: 'Ordina la catena di trasmissione di un rialzo dei tassi BCE', i: ['La BCE alza i tassi ufficiali', 'Salgono €STR ed Euribor', 'Le banche alzano i tassi su mutui e prestiti', 'Credito e domanda rallentano', 'L’inflazione si raffredda'], e: 'Il segnale parte dai tassi ufficiali, passa al mercato monetario e al credito, frena la domanda e solo alla fine, con ritardo, raffredda i prezzi.' },
    { q: 'Ordina dalla politica più accomodante alla più restrittiva, in base al tasso reale', i: ['Tasso 1%, inflazione 4%', 'Tasso 2%, inflazione 3%', 'Tasso 3%, inflazione 2%', 'Tasso 4%, inflazione 1%'], e: 'Tasso reale ≈ nominale − inflazione: −3%, −1%, +1%, +3%. Più il tasso reale è alto, più la politica frena l’economia.' },
  ],
  cat: [
    { q: 'Riguarda la BCE o la Fed?', g: [['BCE', ['Stabilità dei prezzi come obiettivo primario', 'Tasso sui depositi e corridoio', 'Consiglio con i governatori nazionali']], ['Fed', ['Doppio mandato', 'Fascia obiettivo dei Fed funds', 'Dot plot']]] },
    { q: 'Mossa restrittiva o espansiva?', g: [['Restrittiva', ['Rialzo dei tassi ufficiali', 'Riduzione del bilancio della banca centrale', 'Guidance su tassi alti più a lungo']], ['Espansiva', ['Taglio dei tassi ufficiali', 'Acquisti di titoli sul mercato', 'Guidance su tassi bassi per un lungo periodo']]] },
  ],
  scen: [
    { s: 'Federico, 35 anni, nota che la BCE ha alzato i tassi da tre mesi ma l’inflazione è ancora alta. Conclude che “i rialzi non funzionano” e vuole riorganizzare tutto il portafoglio su questa idea.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che gli effetti dei tassi arrivano con ritardi lunghi e variabili', ok: true, f: 'La trasmissione richiede spesso uno-due anni: giudicare l’efficacia dopo tre mesi porta a conclusioni affrettate.' },
      { t: 'Che la BCE ha sbagliato e taglierà i tassi a breve', ok: false, f: 'Con l’inflazione ancora alta un taglio sarebbe contrario al mandato: la conclusione non segue dai fatti.' },
      { t: 'Che i tassi non influenzano mai l’inflazione', ok: false, f: 'Il canale dei tassi funziona attraverso credito e domanda: è lento, non inesistente.' },
    ] },
    { s: 'Marta, 55 anni, ha un portafoglio con azioni europee e USA. Legge che la Fed taglia i tassi mentre la BCE li lascia fermi e pensa che qualcuno abbia sbagliato, perché “le banche centrali devono muoversi insieme”.', q: 'Come interpreti la situazione?', o: [
      { t: 'Economie e mandati diversi, scelte diverse', ok: true, f: 'Inflazione, occupazione e crescita possono divergere tra le due aree. La differenza tra i tassi può anche muovere il cambio euro-dollaro.' },
      { t: 'Una delle due ha di sicuro sbagliato', ok: false, f: 'Non esiste un obbligo di coordinamento: ciascuna risponde alle condizioni della propria economia.' },
      { t: 'La BCE deve seguire la Fed entro un mese', ok: false, f: 'La BCE è indipendente e decide in base all’area euro, non alle mosse della Fed.' },
    ] },
    { s: 'Giorgio, 47 anni, investe in BTP. Un politico propone che sia il governo a decidere i tassi per “aiutare la crescita”, con una riforma che toglierebbe autonomia alla banca centrale.', q: 'Quale rischio dovrebbe valutare?', o: [
      { t: 'Perdita di credibilità e aspettative d’inflazione più alte', ok: true, f: 'Se i mercati temono tassi decisi per ragioni politiche chiedono più rendimento per compensare l’inflazione attesa: i tassi a lungo possono salire.' },
      { t: 'Nessuno: tassi più bassi aiutano sempre tutti', ok: false, f: 'Tassi tenuti artificialmente bassi possono alimentare inflazione e far salire i rendimenti a lunga scadenza.' },
      { t: 'Solo un rischio per chi ha azioni, non per i BTP', ok: false, f: 'Proprio i titoli a lungo termine sono i più esposti a un aumento delle aspettative d’inflazione.' },
    ] },
    { s: 'Elisa, 28 anni, ha 15.000 € da parcheggiare. La BCE, con la forward guidance, lascia intendere futuri tagli. Una banca offre un conto deposito vincolato a 2 anni a tasso fisso, un’altra un conto svincolabile a tasso variabile.', q: 'Come dovrebbe decidere?', o: [
      { t: 'In base a quando le serviranno i soldi', ok: true, f: 'I tagli attesi sono già in parte nei tassi offerti. Il criterio decisivo resta l’orizzonte: vincolare solo ciò che non servirà prima della scadenza.' },
      { t: 'Vincolare tutto per 5 anni: i tagli sono certi', ok: false, f: 'La guidance non è una promessa: le banche centrali cambiano rotta se cambiano i dati, e i soldi vincolati non sono disponibili.' },
      { t: 'Lasciare tutto sul conto corrente', ok: false, f: 'Aspettare a vuoto ha un costo: la liquidità non resa perde potere d’acquisto e c’è l’imposta di bollo sopra i 5.000 € di giacenza media.' },
    ] },
  ],
  tip: 'Leggi il comunicato e ascolta la conferenza stampa: per i mercati spesso conta più ciò che la banca centrale lascia intendere sul futuro della decisione di oggi.',
});
