FQC(74, {
  intro: 'Quando i tassi si muovono, si muove tutto: obbligazioni, azioni growth, valute e mutui. Scopri perché e con quale intensità.',
  cards: [
    { t: 'Il cuore di tutto: lo sconto', x: 'Ogni attività vale quanto i flussi futuri che promette, riportati a oggi con un tasso. Se il tasso sale, il valore attuale scende, e di più per i flussi lontani.', v: { k: 'formula', f: 'Valore attuale = Flusso futuro ÷ (1 + r)^anni', n: '100 € tra 10 anni: ≈ 82 € al 2%, ≈ 61 € al 5%' } },
    { t: 'Obbligazioni: relazione inversa', x: 'Se i rendimenti di mercato salgono, i titoli già emessi con cedole più basse valgono meno. Con duration 8, un +1% di rendimento costa circa l’8% di prezzo.', v: { k: 'stat', n: '≈ −8%', l: 'prezzo di un titolo con duration 8 se i rendimenti salgono di 1 punto' } },
    { t: 'Chi soffre di più', x: 'Più è lunga la scadenza, più il prezzo reagisce ai tassi. Un conto deposito svincolabile non ha oscillazioni di prezzo; un BTP a 30 anni può muoversi moltissimo.', v: { k: 'scale', a: 'Poco sensibile ai tassi', b: 'Molto sensibile ai tassi', d: [['Conto deposito', 4], ['BOT a 6 mesi', 12], ['BTP a 10 anni', 62], ['BTP a 30 anni', 92]] } },
    { t: 'Growth contro value', x: 'Le azioni growth valgono soprattutto per utili attesi tra molti anni: tassi più alti li scontano di più. Le value, con flussi più vicini e stabili, in genere soffrono meno.', v: { k: 'vs', a: ['Azioni growth', 'Utili lontani: molto sensibili ai tassi'], b: ['Azioni value', 'Flussi vicini e stabili: meno sensibili'] } },
    { t: 'Tassi e valuta', x: 'A parità di altri fattori, tassi più alti rispetto a un’altra area attirano capitali in cerca di rendimento e sostengono la valuta. Conta soprattutto il differenziale, e la sorpresa rispetto alle attese.', v: { k: 'icons', d: [['📈', 'Tassi relativi più alti'], ['💰', 'Afflusso di capitali'], ['💶', 'Valuta che tende a rafforzarsi']] } },
    { t: 'Il mutuo e la tua rata', x: 'Mutuo di 150.000 € a 25 anni: dal 2% al 4% la rata mensile sale di circa 155 €. Chi ha il variabile lo sente alle revisioni successive; chi ha il fisso no.', v: { k: 'bars', d: [['Rata al 2%', 636], ['Rata al 4%', 792]], u: '€' } },
  ],
  terms: [
    ['Valore attuale', 'Valore oggi di una somma futura, scontata a un tasso di interesse.'],
    ['Euribor', 'Tasso interbancario dell’area euro a cui sono spesso legati i mutui variabili.'],
    ['Eurirs (IRS)', 'Tasso swap usato come riferimento per i mutui a tasso fisso.'],
    ['Spread del mutuo', 'Margine che la banca aggiunge al parametro di riferimento per fissare il tasso.'],
    ['Bond proxy', 'Azioni con dividendi stabili, come utility e immobiliari, che reagiscono ai tassi quasi come obbligazioni.'],
    ['Compressione dei multipli', 'Calo del P/E pagato dal mercato, ad esempio per tassi più alti, anche a utili invariati.'],
    ['Differenziale di tasso', 'Differenza tra i tassi di due aree valutarie, che orienta i flussi di capitale.'],
    ['Premio per il rischio azionario', 'Rendimento extra richiesto per detenere azioni invece di titoli privi di rischio.'],
  ],
  tf: [
    ['Quando i rendimenti di mercato salgono, il prezzo delle obbligazioni a tasso fisso già in circolazione scende.', true, 'Le nuove emissioni pagano di più: per essere competitivi, i titoli con cedole più basse devono scendere di prezzo.'],
    ['Un rialzo dei tassi fa salire subito la rata di un mutuo a tasso fisso già stipulato.', false, 'La rata del fisso resta invariata per tutta la durata; i rialzi pesano sui nuovi mutui e su quelli variabili.'],
    ['Le azioni growth tendono a soffrire più delle value quando i tassi salgono.', true, 'Gran parte del loro valore dipende da utili lontani, che con un tasso di sconto più alto valgono molto meno oggi.'],
    ['A parità di altri fattori, tassi più alti in un’area tendono ad attirare capitali e a sostenerne la valuta.', true, 'Un differenziale di tasso favorevole rende più interessante detenere attività in quella valuta.'],
    ['Tassi più alti sono sempre negativi per tutte le azioni.', false, 'Alcuni settori, come le banche, possono beneficiare di margini di interesse più ampi; conta anche perché i tassi salgono, ad esempio un’economia forte.'],
    ['Un BTP a 30 anni è meno sensibile ai tassi di un BOT a 6 mesi.', false, 'Più è lunga la duration, più il prezzo reagisce ai rendimenti: il BTP a 30 anni è molto più sensibile.'],
    ['In Italia i mutui a tasso variabile sono di solito legati all’Euribor più uno spread.', true, 'Il tasso si aggiorna periodicamente seguendo l’Euribor; lo spread resta quello fissato nel contratto.'],
    ['Se i tassi scendono, il valore attuale di un flusso di cassa futuro aumenta.', true, 'Con un tasso di sconto più basso lo stesso importo futuro vale di più oggi: per questo il calo dei tassi sostiene obbligazioni e azioni.'],
    ['Il rendimento del BTP decennale dipende solo dal tasso ufficiale della BCE.', false, 'I tassi lunghi riflettono attese sui tassi futuri, inflazione attesa, premio a termine e rischio di credito dell’emittente.'],
    ['A parità di utili, tassi più alti tendono a ridurre il P/E che il mercato è disposto a pagare.', true, 'Se i titoli senza rischio rendono di più, gli investitori chiedono più rendimento alle azioni, cioè prezzi più bassi rispetto agli utili.'],
  ],
  mcq: [
    { q: 'Quale di questi titoli perde di più se i rendimenti salgono di un punto?', a: 'BTP a 30 anni con cedola bassa', w: ['BOT a 6 mesi', 'BTP a 3 anni con cedola alta', 'CCT a tasso variabile'], e: 'Scadenza lunga e cedola bassa danno la duration più alta. Il CCT si adegua ai tassi con la cedola, quindi oscilla poco.' },
    { q: 'Perché le azioni growth sono particolarmente sensibili ai tassi?', a: 'Il loro valore dipende da utili lontani', w: ['Pagano dividendi molto elevati', 'Sono emesse quasi sempre da banche', 'Hanno solo debiti a tasso fisso'], e: 'Più un flusso è lontano, più lo sconto composto pesa: un aumento del tasso riduce molto il valore attuale degli utili futuri.' },
    { q: 'Chi è più esposto a un rialzo dell’Euribor?', a: 'Chi ha un mutuo a tasso variabile', w: ['Chi ha un mutuo a tasso fisso', 'Chi ha un prestito auto a tasso fisso', 'Chi ha un conto deposito svincolabile'], e: 'La rata del variabile segue l’Euribor; i prestiti a tasso fisso non cambiano, mentre il conto deposito può anzi rendere di più.' },
    { q: 'La BCE alza i tassi più del previsto, mentre la Fed resta ferma. Effetto più probabile sul cambio?', a: 'L’euro tende a rafforzarsi', w: ['L’euro tende a indebolirsi', 'Il cambio reagisce solo dopo un anno', 'Si muove solo il prezzo dell’oro'], e: 'Un differenziale di tasso più favorevole all’euro e inatteso attira capitali verso l’area euro, sostenendo la moneta unica.' },
    { q: 'I rendimenti dei titoli di Stato salgono dal 2% al 5% con utili aziendali invariati. Cosa accade di solito ai P/E?', a: 'Tendono a scendere', w: ['Tendono a salire', 'Restano fissi per definizione', 'Diventano negativi'], e: 'Con alternative senza rischio più remunerative, il mercato paga meno ogni euro di utile: è la compressione dei multipli.' },
    { q: 'Quale parametro guida di solito il tasso dei nuovi mutui a tasso fisso in Italia?', a: 'L’Eurirs della durata corrispondente', w: ['Il tasso sui depositi BCE del giorno', 'L’Euribor a un mese', 'Il rendimento dei BOT a 3 mesi'], e: 'I fissi si basano sull’Eurirs (tasso swap) di durata simile al mutuo, più lo spread della banca.' },
    { q: 'Quale settore può trarre vantaggio da tassi più alti, almeno entro certi limiti?', a: 'Le banche, per il margine di interesse', w: ['Gli immobiliari, per i mutui più cari', 'Le utility, per il debito più costoso', 'Le tech growth, per lo sconto più alto'], e: 'Le banche possono allargare la differenza tra tassi sui prestiti e costo dei depositi, finché il credito non si deteriora.' },
    { q: 'Un amico dice: “I tassi salgono, quindi le obbligazioni sono da evitare per sempre”. Cosa c’è di sbagliato?', a: 'Chi compra dopo il rialzo ottiene rendimenti più alti', w: ['Le obbligazioni salgono sempre con i tassi', 'I tassi non influenzano le obbligazioni', 'Solo le azioni risentono dei tassi'], e: 'Il rialzo fa perdere a chi ha già titoli lunghi, ma chi compra dopo incassa rendimenti più alti fino alla scadenza.' },
  ],
  fill: [
    { s: 'Quando i rendimenti di mercato salgono, il prezzo delle obbligazioni a tasso fisso ___.', a: 'scende', w: ['sale', 'raddoppia', 'si azzera'] },
    { s: 'I mutui variabili sono di solito indicizzati all’___ più uno spread.', a: 'Euribor', w: ['Eurirs', 'IPCA', 'Eurostoxx'] },
    { s: 'Più i flussi di cassa sono lontani nel tempo, più il loro valore ___ è sensibile ai tassi.', a: 'attuale', w: ['nominale', 'contabile', 'facciale'] },
    { s: 'Le utility con dividendi stabili sono spesso considerate ___ proxy.', a: 'bond', w: ['equity', 'growth', 'cash'] },
    { s: 'Un aumento del ___ di tasso a favore dell’area euro tende a sostenere l’euro.', a: 'differenziale', w: ['deflatore', 'moltiplicatore', 'disavanzo'] },
  ],
  order: [
    { q: 'Ordina dal meno al più sensibile, come prezzo, a un rialzo dei rendimenti', i: ['Conto deposito svincolabile', 'BOT a 12 mesi', 'BTP a 5 anni', 'BTP a 10 anni', 'BTP a 30 anni'], e: 'Il conto deposito non ha un prezzo di mercato; tra i titoli, più cresce la scadenza (e la duration), più forte è la reazione ai tassi.' },
    { q: 'Ordina da quello che perde più valore attuale a quello che ne perde meno se il tasso di sconto sale', i: ['100 € tra 30 anni', '100 € tra 10 anni', '100 € tra 3 anni', '100 € tra 1 anno'], e: 'Più il flusso è lontano, più lo sconto composto pesa: è il motivo per cui growth e titoli lunghi soffrono di più i rialzi.' },
  ],
  cat: [
    { q: 'Tende a beneficiare o a soffrire di un rialzo dei tassi?', g: [['Beneficia', ['Chi ha liquidità su un conto deposito', 'Chi compra BOT di nuova emissione', 'Banche con molti depositi a basso costo']], ['Soffre', ['Chi ha un mutuo variabile', 'Chi detiene BTP a lunga scadenza', 'Aziende growth molto indebitate']]] },
    { q: 'Caratteristica del mutuo a tasso fisso o variabile?', g: [['Fisso', ['Rata costante per tutta la durata', 'Legato all’Eurirs alla stipula', 'Protegge dai rialzi dei tassi']], ['Variabile', ['Rata che cambia nel tempo', 'Legato all’Euribor', 'Beneficia subito dei tagli dei tassi']]] },
  ],
  scen: [
    { s: 'Valentina, 33 anni, sta per comprare casa con un mutuo a 25 anni. Il variabile oggi ha una rata più bassa del fisso, ma con quella rata arriverebbe già al limite del suo budget mensile.', q: 'Qual è la scelta più prudente?', o: [
      { t: 'Scegliere una rata sostenibile anche con tassi più alti', ok: true, f: 'Prova a simulare la rata con 2 punti in più: se non la reggi, il fisso o un importo più basso ti proteggono da brutte sorprese.' },
      { t: 'Il variabile, perché oggi costa meno', ok: false, f: 'Una rata al limite non lascia margine: un rialzo dell’Euribor potrebbe renderla insostenibile.' },
      { t: 'Rinviare l’acquisto finché i tassi non tornano a zero', ok: false, f: 'Nessuno sa se e quando succederà: aspettare un livello preciso dei tassi non è un piano.' },
    ] },
    { s: 'Stefano, 58 anni, ha comprato un BTP a 30 anni credendolo “sicuro”. I rendimenti salgono e il prezzo cala del 20%. Gli serviranno quei soldi tra due anni.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Allineare le scadenze a quando gli serviranno i soldi', ok: true, f: 'Il problema è il disallineamento: un titolo trentennale può oscillare molto. Con un orizzonte di 2 anni servono scadenze brevi.' },
      { t: 'Comprarne altri a leva per mediare il prezzo', ok: false, f: 'Aumenterebbe proprio il rischio di tasso che gli ha causato la perdita, con l’aggravante della leva.' },
      { t: 'Aspettare: tra due anni tornerà di sicuro a 100', ok: false, f: 'Il prezzo converge a 100 solo a scadenza, cioè tra quasi 30 anni: tra due anni può essere ancora più basso.' },
    ] },
    { s: 'Irene, 41 anni, ha il portafoglio concentrato su azioni tecnologiche growth. Legge che l’inflazione accelera e che i mercati si aspettano nuovi rialzi dei tassi.', q: 'Come dovrebbe muoversi?', o: [
      { t: 'Rivedere la diversificazione del piano', ok: true, f: 'Un portafoglio concentrato su titoli “a lunga duration” è molto esposto ai tassi: diversificare riduce la dipendenza da un solo fattore.' },
      { t: 'Vendere tutto e comprare solo banche', ok: false, f: 'Sostituirebbe una scommessa concentrata con un’altra, basata su una previsione dei tassi che può rivelarsi sbagliata.' },
      { t: 'Ignorare: la tecnologia cresce sempre', ok: false, f: 'Anche aziende solide possono perdere molto in borsa quando i tassi salgono: valutazioni e crescita sono cose diverse.' },
    ] },
    { s: 'Matteo, 36 anni, ha un ETF su azioni USA senza copertura del cambio. Legge che la Fed potrebbe alzare i tassi più della BCE e si chiede cosa cambi per lui.', q: 'Quale considerazione è corretta?', o: [
      { t: 'Il cambio è una fonte di rendimento e di rischio', ok: true, f: 'Se il dollaro si rafforza, il suo ETF guadagna in euro; ma i cambi sono difficili da prevedere, e la copertura va decisa nel piano, non sulle notizie.' },
      { t: 'Il cambio non incide su un ETF azionario', ok: false, f: 'Un ETF non coperto su azioni USA è esposto al dollaro: le variazioni del cambio entrano nel rendimento in euro.' },
      { t: 'Tassi USA più alti fanno salire sempre le azioni USA', ok: false, f: 'Tassi più alti di solito pesano sulle valutazioni azionarie, anche se il dollaro può compensare in parte.' },
    ] },
  ],
  tip: 'Prima di investire o firmare un mutuo chiediti cosa succederebbe con tassi più alti o più bassi di 2 punti: se il piano regge in entrambi i casi, sei sulla strada giusta.',
});
