FQC(75, {
  intro: 'Quando i tassi sono già vicini a zero, le banche centrali usano il bilancio: scopri come QE e QT muovono rendimenti, spread e prezzi degli asset.',
  cards: [
    { t: 'Come funziona il QE', x: 'Con il quantitative easing la banca centrale compra titoli sul mercato pagandoli con nuove riserve bancarie. I prezzi dei titoli salgono, i rendimenti a lungo scendono e gli investitori si spostano verso attività più rischiose.', v: { k: 'steps', s: ['Nuove riserve', 'Acquisto di titoli', 'Rendimenti lunghi in calo', 'Ricerca di rendimento', 'Credito più facile'] } },
    { t: 'QE e QT a confronto', x: 'Il QT è il percorso inverso: la banca centrale riduce il portafoglio, di solito non reinvestendo i titoli che scadono, a volte vendendoli. Più titoli restano da collocare presso gli investitori privati.', v: { k: 'vs', a: ['QE', 'Acquisti di titoli: bilancio in crescita, tassi lunghi più bassi'], b: ['QT', 'Scadenze non reinvestite o vendite: bilancio in calo'] } },
    { t: 'Un bilancio gonfiato', x: 'Valori arrotondati: il bilancio della Fed era di circa 900 miliardi di dollari prima della crisi del 2008, circa 4.500 nel 2014 e quasi 9.000 nel 2022. Anche quello dell’Eurosistema ha superato gli 8.000 miliardi di euro.', v: { k: 'bars', d: [['2007', 900], ['2014', 4500], ['2022', 9000]], u: 'mld $' } },
    { t: 'Il “taper tantrum”', x: 'Nel 2013 bastò che la Fed accennasse a rallentare gli acquisti perché il rendimento del decennale USA salisse di circa un punto in pochi mesi. Anche solo l’annuncio di un’uscita dal QE muove i mercati.', v: { k: 'stat', n: '≈ +1 punto', l: 'rialzo del decennale USA in pochi mesi nel 2013' } },
    { t: 'I canali del QE', x: 'Il QE agisce su più fronti: abbassa i tassi lunghi, sostiene i prezzi delle attività, tende a indebolire la valuta e segnala che i tassi ufficiali resteranno bassi a lungo.', v: { k: 'icons', d: [['📉', 'Tassi lunghi più bassi'], ['📈', 'Asset più cari'], ['💱', 'Valuta più debole'], ['📣', 'Segnale: tassi bassi a lungo']] } },
    { t: 'I due lati del bilancio', x: 'Quando compra un titolo la banca centrale lo iscrive all’attivo e accredita riserve alla banca venditrice, al passivo. Non consegna denaro direttamente alle famiglie.', v: { k: 'formula', f: 'Titoli acquistati (attivo) = nuove riserve bancarie (passivo)', n: 'Il QE allarga entrambi i lati del bilancio, il QT li riduce' } },
  ],
  terms: [
    ['Quantitative easing (QE)', 'Acquisti su larga scala di titoli da parte della banca centrale per abbassare i tassi a lungo termine.'],
    ['Quantitative tightening (QT)', 'Riduzione del bilancio della banca centrale tramite mancati reinvestimenti o vendite di titoli.'],
    ['Tapering', 'Rallentamento graduale del ritmo degli acquisti netti, prima di fermarli.'],
    ['Riserve bancarie', 'Depositi delle banche presso la banca centrale, creati anche dagli acquisti di titoli.'],
    ['Reinvestimento', 'Riacquisto di nuovi titoli con i rimborsi di quelli in scadenza, per mantenere stabile il portafoglio.'],
    ['PEPP', 'Programma di acquisti lanciato dalla BCE nel 2020 per la pandemia, con regole più flessibili.'],
    ['Zero lower bound', 'Livello vicino allo zero sotto cui tagliare ancora i tassi ufficiali diventa poco efficace.'],
    ['Premio a termine', 'Compenso extra richiesto per detenere titoli lunghi invece di rinnovare quelli brevi.'],
  ],
  tf: [
    ['Il QE consiste nello stampare banconote da distribuire direttamente alle famiglie.', false, 'La banca centrale compra titoli dal mercato pagandoli con riserve bancarie: non è denaro consegnato ai cittadini.'],
    ['Uno degli obiettivi del QE è abbassare i rendimenti dei titoli a lunga scadenza.', true, 'Comprando titoli lunghi la banca centrale ne alza il prezzo e ne riduce il rendimento, agendo dove i tassi ufficiali non arrivano.'],
    ['Il QT può avvenire anche senza vendere titoli, semplicemente non reinvestendo quelli che scadono.', true, 'È il QT “passivo”: il portafoglio si riduce man mano che i titoli arrivano a scadenza e vengono rimborsati.'],
    ['Il tapering significa che la banca centrale inizia a vendere i titoli in portafoglio.', false, 'Il tapering riduce il ritmo dei nuovi acquisti: il bilancio continua a crescere, solo più lentamente.'],
    ['Nel 2013 il solo annuncio di un possibile rallentamento degli acquisti della Fed fece salire con forza i rendimenti.', true, 'È il “taper tantrum”: il decennale USA salì di circa un punto percentuale in pochi mesi.'],
    ['Le banche centrali ricorrono al QE soprattutto quando i tassi ufficiali sono già vicini allo zero.', true, 'Quando i tassi non possono scendere ancora in modo efficace, gli acquisti di titoli servono ad allentare ulteriormente le condizioni finanziarie.'],
    ['Il QE porta sempre e subito a un’inflazione molto alta.', false, 'Dopo il 2008 anni di QE hanno convissuto con inflazione bassa: l’effetto dipende da domanda, credito e condizioni dell’economia.'],
    ['Gli acquisti di titoli di Stato della BCE tendono a comprimere lo spread BTP-Bund.', true, 'Un grande acquirente stabile riduce il premio richiesto dal mercato, soprattutto per i paesi più indebitati.'],
    ['Durante il QT gli investitori privati devono assorbire una quota maggiore dei titoli emessi dagli Stati.', true, 'Se la banca centrale non reinveste, i nuovi titoli devono trovare altri compratori, che possono chiedere rendimenti più alti.'],
    ['Con il PEPP la BCE ha comprato titoli di Stato direttamente dai governi all’emissione.', false, 'Anche il PEPP opera sul mercato secondario: gli acquisti all’emissione violerebbero il divieto di finanziamento monetario.'],
  ],
  mcq: [
    { q: 'Cosa compra principalmente una banca centrale durante il QE?', a: 'Titoli di Stato e altri titoli', w: ['Azioni delle banche commerciali', 'Immobili e terreni pubblici', 'Oro dalle riserve degli Stati'], e: 'Il QE si basa soprattutto su titoli di Stato; la BCE ha comprato anche obbligazioni societarie e covered bond.' },
    { q: 'Perché il QE tende a far salire anche i prezzi delle azioni?', a: 'Spinge verso attività più rischiose', w: ['Obbliga le banche a comprare azioni', 'Riduce il numero di azioni quotate', 'Aumenta le tasse sui titoli di Stato'], e: 'Con rendimenti obbligazionari compressi, gli investitori cercano rendimento altrove: è l’effetto di ribilanciamento di portafoglio.' },
    { q: 'Qual è la differenza tra QT “passivo” e “attivo”?', a: 'Il passivo lascia scadere, l’attivo vende', w: ['Il passivo vende, l’attivo lascia scadere', 'Il passivo è della Fed, l’attivo della BCE', 'Il passivo alza i tassi, l’attivo li taglia'], e: 'Nel QT passivo i titoli in scadenza non vengono reinvestiti; in quello attivo la banca centrale vende titoli prima della scadenza.' },
    { q: 'Quale rischio viene spesso associato a un QE prolungato?', a: 'Prezzi degli attivi gonfiati', w: ['Rendimenti dei titoli troppo alti', 'Scarsità di liquidità nelle banche', 'Valuta nazionale troppo forte'], e: 'Tassi molto bassi a lungo possono spingere valutazioni eccessive e assunzione di rischi, con il pericolo di bolle.' },
    { q: 'Durante il QT, cosa succede di solito alle riserve delle banche presso la banca centrale?', a: 'Diminuiscono', w: ['Aumentano', 'Restano identiche', 'Si trasformano in azioni'], e: 'Quando un titolo scade senza reinvestimento, il rimborso riduce sia l’attivo sia le riserve al passivo del bilancio.' },
    { q: 'Con quale programma di acquisti la BCE ha risposto alla pandemia del 2020?', a: 'PEPP', w: ['OMT', 'TPI', 'SMP'], e: 'Il PEPP è stato lanciato nel marzo 2020. OMT (2012) e TPI (2022) servono contro tensioni anomale sugli spread; l’SMP risale al 2010.' },
    { q: 'Perché una banca centrale può registrare perdite quando alza i tassi dopo un lungo QE?', a: 'Paga sulle riserve più di quanto incassa', w: ['Deve restituire i titoli ai governi', 'Le banconote perdono valore legale', 'È obbligata a vendere tutto subito'], e: 'I titoli comprati con rendimenti bassi rendono poco, mentre gli interessi pagati sulle riserve seguono i tassi ufficiali in salita.' },
    { q: 'Viene annunciato un QE più ampio del previsto. Quale reazione è più probabile sulla valuta?', a: 'Tende a indebolirsi', w: ['Tende a rafforzarsi', 'Resta bloccata per legge', 'Si aggancia all’oro'], e: 'Rendimenti più bassi e più liquidità rendono meno attraente detenere quella valuta, a parità di altre condizioni.' },
  ],
  fill: [
    { s: 'Il ___ riduce gradualmente il ritmo degli acquisti di titoli.', a: 'tapering', w: ['rating', 'buyback', 'leasing'] },
    { s: 'Nel QE la banca centrale paga i titoli acquistati creando nuove ___ bancarie.', a: 'riserve', w: ['azioni', 'cedole', 'filiali'] },
    { s: 'Il QT riduce il ___ della banca centrale.', a: 'bilancio', w: ['mandato', 'capitale sociale', 'corridoio'] },
    { s: 'Quando non reinveste i titoli in scadenza, la banca centrale attua un QT ___.', a: 'passivo', w: ['attivo', 'espansivo', 'fiscale'] },
    { s: 'La BCE può comprare titoli di Stato solo sul mercato ___.', a: 'secondario', w: ['primario', 'parallelo', 'interbancario'] },
  ],
  order: [
    { q: 'Ordina le fasi tipiche della politica di bilancio di una banca centrale', i: ['Avvio del QE', 'Tapering degli acquisti', 'Fine degli acquisti netti con reinvestimenti', 'Stop ai reinvestimenti (QT)'], e: 'Prima si compra, poi si rallenta, poi si mantiene stabile il portafoglio reinvestendo, infine lo si lascia ridurre: è il percorso seguito sia dalla Fed sia dalla BCE.' },
    { q: 'Ordina questi eventi in ordine cronologico', i: ['Primo QE della Fed dopo la crisi del 2008', 'Taper tantrum', 'Avvio del QE della BCE', 'Lancio del PEPP per la pandemia'], e: 'La Fed avviò il QE tra fine 2008 e inizio 2009, il taper tantrum è del 2013, la BCE avviò il suo QE sui titoli pubblici nel 2015 e il PEPP è del 2020.' },
  ],
  cat: [
    { q: 'QE o QT?', g: [['QE', ['Acquisti netti di titoli', 'Bilancio della banca centrale in espansione', 'Riserve bancarie in aumento']], ['QT', ['Titoli in scadenza non reinvestiti', 'Bilancio in contrazione', 'Più titoli da collocare presso i privati']]] },
    { q: 'Con il QE questa grandezza tende ad aumentare o a diminuire?', g: [['Aumenta', ['Prezzi delle obbligazioni', 'Valutazioni azionarie', 'Liquidità del sistema bancario']], ['Diminuisce', ['Rendimenti a lungo termine', 'Spread dei paesi più indebitati', 'Valore esterno della valuta']]] },
  ],
  scen: [
    { s: 'Laura, 44 anni, ha una parte del portafoglio in BTP decennali. Legge che la BCE ha smesso di reinvestire i titoli in scadenza e che gli Stati dovranno trovare più compratori privati.', q: 'Come dovrebbe ragionare?', o: [
      { t: 'Verificare la durata dei BTP rispetto all’orizzonte', ok: true, f: 'Il QT può spingere su rendimenti e spread, ma l’effetto è graduale. Se la scadenza è in linea con il piano, le oscillazioni di prezzo pesano meno.' },
      { t: 'Vendere tutto: lo spread esploderà di sicuro', ok: false, f: 'Il QT è annunciato e in buona parte atteso: dare per certo un crollo porta a vendere sull’onda della paura.' },
      { t: 'Ignorare: la BCE non influisce sui BTP', ok: false, f: 'Gli acquisti BCE hanno compresso gli spread per anni: la loro fine è un fattore che conta per i titoli di Stato.' },
    ] },
    { s: 'Nicola, 27 anni, guarda un video secondo cui “la BCE stampa soldi a pioggia, l’euro varrà zero” e il consiglio finale è di mettere tutti i risparmi in oro e cripto.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Capire come funziona davvero il QE e restare diversificato', ok: true, f: 'Il QE crea riserve bancarie per comprare titoli, non denaro a pioggia. I suoi effetti sono reali ma non giustificano scommesse estreme.' },
      { t: 'Seguire il consiglio: meglio prevenire', ok: false, f: 'Concentrare tutto su attività molto volatili per paura di uno scenario estremo espone a perdite pesanti.' },
      { t: 'Ritirare i soldi dal conto e tenerli in contanti', ok: false, f: 'Se temesse davvero la svalutazione, i contanti in euro non lo proteggerebbero affatto: la scelta è incoerente.' },
    ] },
    { s: 'Gianni, 66 anni, pensionato, è convinto che con il QE i tassi resteranno bassissimi per sempre e vuole mettere metà dei risparmi in un titolo di Stato a 50 anni.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che i titoli lunghissimi possono oscillare moltissimo', ok: true, f: 'Quando i tassi sono risaliti, i titoli lunghissimi comprati con rendimenti minimi hanno perso, in alcuni casi, più di metà del valore. Il QE non dura per sempre.' },
      { t: 'Che un titolo di Stato non può perdere valore', ok: false, f: 'Il rimborso a scadenza non impedisce forti cali di prezzo nel frattempo, soprattutto con durate molto lunghe.' },
      { t: 'Che deve investire tutto, non solo metà', ok: false, f: 'Raddoppierebbe un rischio di tasso enorme, del tutto incoerente con l’orizzonte di un pensionato.' },
    ] },
    { s: 'Beatrice, 39 anni, investe con un PAC in un ETF azionario. La Fed annuncia un tapering più veloce del previsto e il suo ETF perde il 5% in una settimana.', q: 'Qual è la reazione più sensata?', o: [
      { t: 'Continuare il piano, consapevole del perché del calo', ok: true, f: 'Il mercato ha scontato condizioni monetarie meno accomodanti. Per chi investe a lungo con un PAC, i cali permettono anche di comprare a prezzi più bassi.' },
      { t: 'Sospendere il PAC finché la Fed non cambia idea', ok: false, f: 'Interrompere il piano per tentare di prevedere la Fed toglie al PAC il suo vantaggio principale: la disciplina.' },
      { t: 'Vendere tutto e passare a un ETF a leva per recuperare', ok: false, f: 'La leva amplifica le perdite quanto i guadagni: usarla per “rifarsi” è una delle reazioni più pericolose.' },
    ] },
  ],
  tip: 'Segui non solo i tassi ufficiali ma anche il bilancio della banca centrale: QE e QT agiscono sui rendimenti lunghi, quindi su BTP, mutui fissi e valutazioni.',
});
