FQC(76, {
  intro: 'Occupati, PMI, fiducia e vendite: impara a leggere i dati che muovono i mercati e a usare il calendario macro senza farti travolgere.',
  cards: [
    { t: 'Il tasso di disoccupazione', x: 'Si calcola sulle forze di lavoro, cioè occupati più disoccupati che cercano attivamente un impiego. Chi non lavora e non cerca resta fuori dal conto.', v: { k: 'formula', f: 'Disoccupazione = disoccupati ÷ forze di lavoro × 100', n: 'Es.: 1,5 milioni ÷ 25 milioni = 6%' } },
    { t: 'Occupati, disoccupati, inattivi', x: 'Esempio: su 100 persone in età lavorativa, 62 lavorano, 5 cercano e 33 sono inattive. Il tasso di disoccupazione è 5 ÷ 67 ≈ 7,5%, non 5%.', v: { k: 'pie', d: [['Occupati', 62], ['Disoccupati', 5], ['Inattivi', 33]] } },
    { t: 'Il PMI e la soglia 50', x: 'Il PMI nasce da sondaggi tra i responsabili acquisti delle imprese. Sopra 50 l’attività si espande rispetto al mese prima, sotto 50 si contrae. Esce a inizio mese, con una stima flash già a fine mese.', v: { k: 'scale', a: 'Contrazione', b: 'Espansione', d: [['PMI 45', 45], ['PMI 50', 50], ['PMI 55', 55]] } },
    { t: 'Dati hard e dati soft', x: 'I dati hard misurano fatti, come produzione e vendite; i soft misurano opinioni e aspettative. I soft arrivano prima ma a volte divergono dai fatti.', v: { k: 'vs', a: ['Dati hard', 'Fatti: produzione, vendite, occupati'], b: ['Dati soft', 'Opinioni: fiducia, PMI, aspettative'] } },
    { t: 'I protagonisti del calendario', x: 'Il report sull’occupazione USA esce di solito il primo venerdì del mese; le richieste di sussidi ogni giovedì. In Europa contano PMI, fiducia (come l’Ifo tedesco) e dati ISTAT ed Eurostat.', v: { k: 'icons', d: [['👷', 'Occupazione USA (payrolls)'], ['🏭', 'PMI manifattura e servizi'], ['🛍️', 'Vendite al dettaglio'], ['😊', 'Fiducia di famiglie e imprese']] } },
    { t: 'Come leggere un dato', x: 'Ogni voce del calendario macro riporta orario, dato precedente, consenso e dato effettivo. Guarda anche le revisioni dei mesi passati: possono cambiare il quadro.', v: { k: 'steps', s: ['Data e ora', 'Precedente e consenso', 'Dato effettivo', 'Revisioni'] } },
  ],
  terms: [
    ['Forze di lavoro', 'Persone occupate più quelle disoccupate che cercano attivamente un impiego.'],
    ['Inattivi', 'Persone che non lavorano e non cercano lavoro, escluse dal calcolo della disoccupazione.'],
    ['Tasso di occupazione', 'Quota di occupati sulla popolazione in età lavorativa.'],
    ['Nonfarm payrolls', 'Posti di lavoro creati negli USA fuori dall’agricoltura, pubblicati ogni mese.'],
    ['PMI', 'Indice da sondaggi tra i responsabili acquisti delle imprese: sopra 50 indica espansione.'],
    ['Indice di fiducia', 'Misura, da sondaggio, dell’ottimismo di famiglie o imprese sull’economia.'],
    ['Vendite al dettaglio', 'Dato mensile sul valore delle vendite dei negozi, termometro dei consumi.'],
    ['Calendario macroeconomico', 'Elenco di date e orari dei dati economici, con valori attesi e precedenti.'],
  ],
  tf: [
    ['Chi non lavora e non cerca lavoro non viene conteggiato tra i disoccupati.', true, 'È considerato inattivo: per essere disoccupati bisogna cercare attivamente un impiego.'],
    ['Un calo del tasso di disoccupazione indica sempre che sono stati creati nuovi posti di lavoro.', false, 'Può calare anche perché alcune persone smettono di cercare e diventano inattive: guarda anche occupazione e partecipazione.'],
    ['Un PMI a 48 indica che il settore è in contrazione rispetto al mese precedente.', true, 'Sotto 50 prevalgono le imprese che segnalano un calo dell’attività.'],
    ['Un PMI che passa da 44 a 47 segnala che l’attività ha ripreso a crescere.', false, 'Sotto 50 l’attività continua a contrarsi, solo a un ritmo più lento: il miglioramento non è ancora crescita.'],
    ['Negli Stati Uniti i consumi delle famiglie valgono circa due terzi del PIL.', true, 'Per questo i dati su vendite, redditi e fiducia dei consumatori USA sono seguiti con grande attenzione.'],
    ['Fiducia e PMI sono dati soft: possono anticipare la tendenza ma a volte divergono dai dati reali.', true, 'Le opinioni reagiscono in fretta a notizie e umori; i fatti, come le vendite, possono raccontare una storia diversa.'],
    ['Il report sull’occupazione USA viene pubblicato ogni giorno.', false, 'È mensile, di solito il primo venerdì del mese; le richieste di sussidi di disoccupazione sono invece settimanali.'],
    ['Un mercato del lavoro molto teso può alimentare l’inflazione tramite salari più alti.', true, 'Se le imprese faticano ad assumere alzano i salari e spesso trasferiscono i costi sui prezzi, soprattutto nei servizi.'],
    ['I dati sui payrolls USA possono essere rivisti anche in modo rilevante nei mesi successivi.', true, 'Le prime stime si basano su dati parziali: le revisioni possono cambiare la lettura del mercato del lavoro.'],
    ['Il tasso di disoccupazione si calcola dividendo i disoccupati per l’intera popolazione.', false, 'Si divide per le forze di lavoro (occupati + disoccupati), non per tutta la popolazione.'],
  ],
  mcq: [
    { q: 'Ci sono 600.000 disoccupati e 9,4 milioni di occupati. Qual è il tasso di disoccupazione?', a: '6%', w: ['6,4%', '5,6%', '9,4%'], e: 'Forze di lavoro = 9,4 + 0,6 = 10 milioni. 0,6 ÷ 10 = 6%.' },
    { q: 'Cosa misura un indice PMI?', a: 'Sondaggi tra i responsabili acquisti', w: ['Prezzi medi delle materie prime', 'Profitti delle imprese quotate', 'Vendite effettive dei negozi'], e: 'Il PMI chiede alle imprese se ordini, produzione, occupazione e altre voci sono aumentati o diminuiti rispetto al mese prima.' },
    { q: 'Quale dato USA esce ogni settimana ed è seguito come segnale rapido sul lavoro?', a: 'Le nuove richieste di sussidi', w: ['Il report sui payrolls', 'La stima del PIL', 'L’indice dei prezzi PCE'], e: 'Le richieste iniziali di sussidi escono ogni giovedì: sono rumorose, ma segnalano presto un aumento dei licenziamenti.' },
    { q: 'Quale di questi è un dato “soft”?', a: 'La fiducia dei consumatori', w: ['Le vendite al dettaglio', 'La produzione industriale', 'Il numero di occupati'], e: 'La fiducia nasce da un sondaggio di opinioni; gli altri misurano grandezze effettive.' },
    { q: 'Perché una banca centrale segue con attenzione la crescita dei salari?', a: 'Può spingere l’inflazione dei servizi', w: ['Fissa per legge i tassi ufficiali', 'Serve a calcolare l’indice PMI', 'Riguarda solo il debito pubblico'], e: 'Nei servizi il costo del lavoro pesa molto: salari che crescono più della produttività tendono a tradursi in prezzi più alti.' },
    { q: 'Sul calendario leggi un PMI con precedente 52,1, consenso 51,5 ed effettivo 49,8. Cosa è successo?', a: 'Sotto le attese e in contrazione', w: ['Sopra le attese e in espansione', 'In linea con le attese', 'Sotto le attese ma in espansione'], e: '49,8 è sotto il consenso di 51,5 e sotto la soglia di 50: l’attività si contrae, contro un’attesa di lieve espansione.' },
    { q: 'Quale componente pesa di più nel PIL delle grandi economie avanzate?', a: 'I consumi delle famiglie', w: ['La spesa pubblica', 'Le esportazioni nette', 'Gli investimenti delle imprese'], e: 'I consumi privati valgono più della metà del PIL in Europa e circa due terzi negli USA: per questo i dati sui consumi contano tanto.' },
    { q: 'Un collega dice: “La fiducia dei consumatori è crollata, quindi i consumi crolleranno di sicuro il mese prossimo”. Cosa rispondi?', a: 'È un segnale, da confermare con dati reali', w: ['Ha ragione: fiducia e consumi coincidono', 'La fiducia non ha legami con i consumi', 'Conta solo se lo dice la banca centrale'], e: 'Fiducia e consumi sono collegati, ma non in modo meccanico: redditi, risparmi e occupazione possono sostenere la spesa anche con umore basso.' },
  ],
  fill: [
    { s: 'Le persone senza lavoro che non lo cercano sono classificate come ___.', a: 'inattive', w: ['disoccupate', 'occupate', 'precarie'] },
    { s: 'Un PMI sopra quota ___ indica espansione.', a: '50', w: ['0', '100', '30'] },
    { s: 'Il ___ macroeconomico indica date, orari, valori attesi e dati precedenti.', a: 'calendario', w: ['bilancio', 'listino', 'prospetto'] },
    { s: 'Fiducia e PMI sono dati ___, basati su sondaggi di opinione.', a: 'soft', w: ['hard', 'core', 'reali'] },
    { s: 'Le forze di lavoro sono date dagli occupati più i ___.', a: 'disoccupati', w: ['inattivi', 'pensionati', 'studenti'] },
  ],
  order: [
    { q: 'Ordina la catena con cui un mercato del lavoro teso può alimentare l’inflazione', i: ['Le imprese faticano ad assumere', 'I salari crescono più in fretta', 'Salgono i costi delle imprese di servizi', 'Aumentano i prezzi dei servizi', 'La banca centrale valuta una stretta'], e: 'La scarsità di lavoratori spinge i salari, che pesano soprattutto nei servizi: se i prezzi salgono, la banca centrale può reagire alzando i tassi.' },
    { q: 'Ordina questi dati USA dal più frequente al meno frequente', i: ['Richieste di sussidi di disoccupazione', 'Payrolls e tasso di disoccupazione', 'PIL', 'Revisione annuale dei payrolls'], e: 'Sussidi: settimanali; payrolls: mensili; PIL: trimestrale; la revisione di riferimento dei payrolls avviene una volta l’anno.' },
  ],
  cat: [
    { q: 'Dato hard o soft?', g: [['Hard', ['Produzione industriale', 'Vendite al dettaglio', 'Occupati non agricoli']], ['Soft', ['PMI manifatturiero', 'Fiducia dei consumatori', 'Indice Ifo tedesco']]] },
    { q: 'Fa parte delle forze di lavoro o è inattivo?', g: [['Forze di lavoro', ['Impiegata a tempo pieno', 'Neolaureato che invia candidature', 'Operaio part-time']], ['Inattivi', ['Pensionata che non cerca lavoro', 'Studente che non cerca lavoro', 'Persona scoraggiata che ha smesso di cercare']]] },
  ],
  scen: [
    { s: 'Carlo, 50 anni, fa trading part-time sull’indice USA. Ha una posizione grande aperta e tra dieci minuti escono i payrolls. Pensa di lasciarla com’è, con uno stop molto vicino.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Ridurre la posizione prima del dato', ok: true, f: 'Nei minuti dopo il dato spread e volatilità esplodono: lo stop può essere eseguito molto peggio del previsto. Meglio ridurre il rischio prima.' },
      { t: 'Aumentare la leva per sfruttare il movimento', ok: false, f: 'Più leva su un evento imprevedibile significa scommettere, non gestire il rischio.' },
      { t: 'Fidarsi dello stop: proteggerà di sicuro', ok: false, f: 'Su movimenti bruschi gli stop possono subire slittamenti importanti: non garantiscono il prezzo indicato.' },
    ] },
    { s: 'Alessia, 37 anni, legge “disoccupazione ai minimi da anni” e conclude che la borsa può solo salire. Vuole aumentare molto le azioni nel suo portafoglio.', q: 'Cosa le faresti notare?', o: [
      { t: 'Che un lavoro teso può far salire i tassi', ok: true, f: 'Salari in forte crescita possono alimentare l’inflazione e spingere la banca centrale a stringere: un buon dato non è sempre una buona notizia per la borsa.' },
      { t: 'Che ha ragione: lavoro forte, borsa in salita', ok: false, f: 'Il legame non è automatico: la borsa guarda avanti e a tassi e utili, non solo al lavoro di oggi.' },
      { t: 'Che la disoccupazione non conta per i mercati', ok: false, f: 'Conta eccome, perché influenza consumi, inflazione e decisioni della banca centrale.' },
    ] },
    { s: 'Piero, 55 anni, legge il titolo “Industria in recessione: PMI manifatturiero a 47”. Lo stesso giorno il PMI dei servizi è a 54. Pensa di vendere tutto il comparto azionario europeo.', q: 'Come dovrebbe leggere i dati?', o: [
      { t: 'Considerare entrambi: i servizi pesano molto', ok: true, f: 'In molte economie avanzate i servizi valgono più dell’industria: un PMI composito può restare sopra 50 anche con la manifattura in calo.' },
      { t: 'Basarsi solo sulla manifattura, più importante', ok: false, f: 'La manifattura è ciclica e seguita, ma da sola non rappresenta tutta l’economia.' },
      { t: 'Sommare i due PMI: 101, quindi tutto bene', ok: false, f: 'I PMI non si sommano: sono indici di diffusione con soglia 50, ciascuno per il suo settore.' },
    ] },
    { s: 'Sofia, 31 anni, investe a lungo termine con ETF diversificati. Vuole seguire la macro per capire meglio i mercati, ma ogni giorno escono decine di dati.', q: 'Qual è l’approccio più sensato?', o: [
      { t: 'Seguire pochi dati chiave e la tendenza', ok: true, f: 'Lavoro, inflazione e PMI bastano per un quadro solido. Le tendenze contano più del singolo dato, spesso rumoroso e rivisto.' },
      { t: 'Reagire a ogni dato con un’operazione', ok: false, f: 'Operare su ogni uscita moltiplica costi ed errori, senza un vero vantaggio per chi investe a lungo.' },
      { t: 'Informarsi solo dai titoli sui social', ok: false, f: 'I titoli semplificano e a volte distorcono: senza consenso e contesto il dato si legge male.' },
    ] },
  ],
  tip: 'Non giudicare l’economia da un solo dato: guarda la tendenza su 3-6 mesi e confronta dati hard e soft. Un mese anomalo capita spesso.',
});
