FQC(77, {
  intro: 'Il cambio è il prezzo di una valuta in un’altra: scopri cosa lo muove e come può cambiare il rendimento dei tuoi investimenti esteri.',
  cards: [
    { t: 'Leggere una quotazione', x: 'Nella coppia EUR/USD la prima valuta è la base: il numero dice quanti dollari servono per 1 euro. Se il numero sale, l’euro si apprezza; se scende, si deprezza.', v: { k: 'formula', f: 'EUR/USD = 1,10 → 1 € = 1,10 $', n: 'Da 1,10 a 1,20: euro più forte. Da 1,10 a 1,00: euro più debole' } },
    { t: 'Cosa muove il cambio', x: 'Nel breve contano soprattutto differenziali di tasso, flussi di capitali e propensione al rischio; nel lungo periodo pesano anche inflazione relativa e conti con l’estero.', v: { k: 'icons', d: [['🏦', 'Differenziale dei tassi'], ['🛒', 'Inflazione relativa'], ['🚢', 'Conti con l’estero'], ['🛡️', 'Ricerca di beni rifugio']] } },
    { t: 'Euro forte o debole?', x: 'Nessuno dei due è “buono” in assoluto: un euro forte aiuta chi importa e frena l’inflazione, un euro debole aiuta chi esporta ma rincara energia e beni importati.', v: { k: 'vs', a: ['Euro forte', 'Import ed energia meno cari, export meno competitivo'], b: ['Euro debole', 'Export favorito, ma più inflazione importata'] } },
    { t: 'Il cambio nel tuo rendimento', x: 'Se investi in dollari, il tuo risultato in euro dipende sia dal titolo sia dal cambio. Le due componenti si moltiplicano.', v: { k: 'formula', f: 'Rendimento in € = (1 + rendimento in valuta) × (1 + variazione della valuta) − 1', n: 'Azioni USA +10%, dollaro −10% sull’euro → circa −1%' } },
    { t: 'Anche le grandi valute oscillano', x: 'Valori arrotondati: l’EUR/USD è passato da circa 0,82 nel 2000 a circa 1,60 nel 2008, ed è sceso sotto la parità nel 2022. Movimenti del 20-30% in pochi anni non sono rari.', v: { k: 'bars', d: [['Minimo 2000', 0.82], ['Massimo 2008', 1.6], ['Minimo 2022', 0.95]] } },
    { t: 'Il cambio della lira', x: 'Dal 1999 il valore della lira è fissato in modo irrevocabile all’euro. Le banconote in euro sono arrivate nel 2002.', v: { k: 'stat', n: '1.936,27', l: 'lire per 1 euro: il tasso di conversione fisso' } },
  ],
  terms: [
    ['Tasso di cambio', 'Prezzo di una valuta espresso in unità di un’altra.'],
    ['Valuta base', 'Prima valuta di una coppia, di cui si indica il prezzo: l’euro in EUR/USD.'],
    ['Apprezzamento', 'Aumento di valore di una valuta rispetto a un’altra in un regime di cambi flessibili.'],
    ['Svalutazione', 'Riduzione del valore di una valuta decisa dalle autorità in un regime di cambio fisso.'],
    ['Parità del potere d’acquisto', 'Teoria per cui nel lungo periodo i cambi tendono a rendere uguali i prezzi dei beni tra paesi.'],
    ['Copertura valutaria', 'Tecnica che neutralizza in gran parte l’effetto delle oscillazioni del cambio su un investimento.'],
    ['Carry trade', 'Indebitarsi in una valuta a tasso basso per investire in una a tasso più alto.'],
    ['Valuta rifugio', 'Valuta ricercata nelle fasi di paura, come il franco svizzero o lo yen.'],
  ],
  tf: [
    ['Se l’EUR/USD passa da 1,10 a 1,20, l’euro si è apprezzato sul dollaro.', true, 'Con 1 euro ora si comprano più dollari: l’euro vale di più.'],
    ['Un investitore italiano con azioni USA non coperte guadagna dal rafforzamento dell’euro.', false, 'Se l’euro si rafforza, i suoi dollari valgono meno euro: il rendimento in euro si riduce.'],
    ['Un euro più debole tende a rendere più care le importazioni di energia, spesso pagate in dollari.', true, 'Petrolio e molte materie prime sono quotati in dollari: con un euro debole costano di più in euro.'],
    ['La parità del potere d’acquisto spiega bene i movimenti del cambio giorno per giorno.', false, 'È un’àncora di lungo periodo: nel breve contano molto di più flussi di capitali, tassi e sentiment.'],
    ['Il tasso di conversione tra lira ed euro è fisso a 1.936,27 lire per euro.', true, 'È stato fissato in modo irrevocabile all’avvio dell’euro, nel 1999.'],
    ['Un ETF con copertura valutaria elimina tutti i rischi di un investimento estero.', false, 'Riduce il rischio di cambio, non quello dei titoli; inoltre la copertura ha un costo legato al differenziale dei tassi.'],
    ['Nelle fasi di forte paura sui mercati il franco svizzero tende a rafforzarsi.', true, 'È una classica valuta rifugio: in momenti di stress molti investitori la cercano.'],
    ['Un cambio fisso o un tetto deciso da una banca centrale protegge sempre da movimenti bruschi.', false, 'Un aggancio può saltare all’improvviso: nel 2015 la Banca nazionale svizzera abbandonò la soglia minima sull’euro e il franco balzò in pochi minuti.'],
    ['Nel carry trade il rischio principale è un brusco apprezzamento della valuta in cui ci si è indebitati.', true, 'Se la valuta del debito sale di colpo, il debito si gonfia e può cancellare in pochi giorni anni di differenziale incassato.'],
    ['L’EUR/USD è rimasto quasi stabile intorno a 1 dalla nascita dell’euro.', false, 'Si è mosso molto: da circa 0,82 nel 2000 a circa 1,60 nel 2008, per poi tornare sotto la parità nel 2022.'],
  ],
  mcq: [
    { q: 'L’EUR/USD è a 1,25. Quanti euro servono per comprare 1.000 dollari?', a: '800 €', w: ['1.250 €', '750 €', '1.000 €'], e: '1.000 $ ÷ 1,25 $ per euro = 800 €.' },
    { q: 'Chi beneficia di più, in genere, di un euro debole?', a: 'Un’azienda italiana che esporta negli USA', w: ['Un’azienda italiana che importa petrolio', 'Un turista italiano in vacanza negli USA', 'Un’impresa che compra macchinari in dollari'], e: 'Con un euro debole i prodotti italiani costano meno in dollari e i ricavi in dollari valgono più euro.' },
    { q: 'Cosa indica la valuta base nella coppia EUR/USD?', a: 'L’euro, il cui prezzo è espresso in dollari', w: ['Il dollaro, il cui prezzo è espresso in euro', 'La valuta con il tasso più alto', 'La valuta del paese più grande'], e: 'La prima valuta è la base: EUR/USD = 1,10 significa che 1 euro vale 1,10 dollari.' },
    { q: 'Quale fattore tende a indebolire una valuta nel lungo periodo?', a: 'Inflazione stabilmente più alta degli altri', w: ['Tassi reali più alti degli altri', 'Avanzo commerciale persistente', 'Afflussi stabili di capitali esteri'], e: 'Se i prezzi salgono più che altrove, la moneta perde potere d’acquisto e nel tempo tende a deprezzarsi, come suggerisce la PPP.' },
    { q: 'Cosa succede di solito quando si smonta in fretta un carry trade finanziato in yen?', a: 'Lo yen si apprezza, le valute ad alto tasso calano', w: ['Lo yen si deprezza, le valute ad alto tasso salgono', 'Tutte le valute restano ferme', 'I tassi in Giappone scendono subito'], e: 'Chi chiude il carry deve ricomprare yen per rimborsare il debito: la domanda di yen lo spinge in alto e le valute comprate vengono vendute.' },
    { q: 'Un investitore italiano compra un ETF su azioni USA con copertura in euro (EUR hedged). Cosa ottiene?', a: 'Il rischio di cambio quasi azzerato', w: ['Un rendimento garantito in euro', 'Un’esposizione doppia al dollaro', 'Nessun rischio sulle azioni USA'], e: 'La copertura neutralizza in gran parte l’effetto del cambio, ma resta tutto il rischio delle azioni e c’è un costo di copertura.' },
    { q: 'Cosa accadde alla lira nel settembre 1992?', a: 'Uscì dallo SME e si svalutò', w: ['Fu sostituita dall’euro', 'Si agganciò al dollaro', 'Fu rivalutata dalla Banca d’Italia'], e: 'Sotto la pressione dei mercati la lira lasciò gli accordi di cambio europei e perse molto valore nei mesi successivi.' },
    { q: 'Un amico dice: “Il cambio non conta, compro solo aziende estere solide”. Cosa gli faresti notare?', a: 'Il cambio può aggiungere o togliere molti punti', w: ['Il cambio conta solo per le obbligazioni', 'Il cambio conta solo se investi in Asia', 'Il cambio incide solo sui dividendi'], e: 'Un’ottima azienda in dollari può dare un risultato deludente in euro se il dollaro si indebolisce, e viceversa.' },
  ],
  fill: [
    { s: 'Nella coppia EUR/USD l’euro è la valuta ___.', a: 'base', w: ['secondaria', 'rifugio', 'ancorata'] },
    { s: 'Se l’EUR/USD scende da 1,15 a 1,05, l’euro si è ___.', a: 'deprezzato', w: ['apprezzato', 'rivalutato', 'stabilizzato'] },
    { s: 'Un ETF con ___ valutaria riduce l’effetto delle oscillazioni del cambio.', a: 'copertura', w: ['leva', 'replica', 'distribuzione'] },
    { s: 'Il franco svizzero è spesso considerato una valuta ___.', a: 'rifugio', w: ['emergente', 'ancorata', 'debole'] },
    { s: 'Un euro più debole rende più cari i beni importati e alimenta l’inflazione ___.', a: 'importata', w: ['da domanda', 'salariale', 'percepita'] },
  ],
  order: [
    { q: 'Ordina dall’euro più debole al più forte rispetto al dollaro', i: ['EUR/USD 0,95', 'EUR/USD 1,05', 'EUR/USD 1,15', 'EUR/USD 1,30'], e: 'Più alto è il numero, più dollari compra un euro: a 1,30 l’euro è più forte che a 0,95.' },
    { q: 'Ordina questi eventi valutari in ordine cronologico', i: ['Uscita della lira dallo SME', 'Nascita dell’euro sui mercati', 'Arrivo delle banconote in euro', 'Fine della soglia minima del franco svizzero', 'Euro sotto la parità con il dollaro'], e: '1992, 1999, 2002, 2015 e 2022: trent’anni che mostrano quanto i cambi possano muoversi, anche tra grandi valute.' },
  ],
  cat: [
    { q: 'A parità di altri fattori, tende a rafforzare o a indebolire una valuta?', g: [['Rafforzare', ['Tassi reali più alti', 'Avanzo delle partite correnti', 'Inflazione più bassa dei partner']], ['Indebolire', ['Taglio dei tassi a sorpresa', 'Crisi politica interna', 'Deficit esterno elevato e persistente']]] },
    { q: 'Beneficia di un euro debole o di un euro forte?', g: [['Euro debole', ['Esportatore italiano verso gli USA', 'Hotel italiano con turisti americani', 'Italiano con ETF USA non coperto']], ['Euro forte', ['Azienda che importa petrolio', 'Italiano in vacanza a New York', 'Impresa che compra macchinari in dollari']]] },
  ],
  scen: [
    { s: 'Tommaso, 42 anni, ha il 40% del portafoglio in azioni USA senza copertura del cambio. Legge diverse previsioni di un dollaro in calo e vorrebbe fare qualcosa.', q: 'Qual è la scelta più ragionevole?', o: [
      { t: 'Decidere una quota coperta coerente con il piano', ok: true, f: 'I cambi sono difficili da prevedere: scegliere a priori quanto coprire, magari in parte, evita di inseguire le previsioni del momento.' },
      { t: 'Vendere tutte le azioni USA', ok: false, f: 'Rinuncerebbe a un’esposizione azionaria per una previsione sul cambio, che potrebbe rivelarsi sbagliata.' },
      { t: 'Scommettere con la leva contro il dollaro', ok: false, f: 'Trasformerebbe una preoccupazione in una scommessa ad alto rischio su un mercato molto difficile da prevedere.' },
    ] },
    { s: 'Francesca, 50 anni, ha una piccola azienda che esporta macchinari negli USA. Incasserà 200.000 dollari tra sei mesi e i suoi costi sono tutti in euro.', q: 'Cosa può fare per proteggersi dal cambio?', o: [
      { t: 'Valutare con la banca una copertura a termine', ok: true, f: 'Un contratto a termine fissa oggi il cambio a cui convertirà i dollari: rinuncia a un eventuale guadagno, ma elimina il rischio di una forte perdita.' },
      { t: 'Aspettare e convertire al momento, sperando bene', ok: false, f: 'Se il dollaro scendesse del 10%, incasserebbe circa il 10% in meno in euro: per un’impresa può essere tutto il margine.' },
      { t: 'Comprare altri dollari per raddoppiare l’esposizione', ok: false, f: 'Aumenterebbe il rischio invece di ridurlo, proprio dove l’azienda è già esposta.' },
    ] },
    { s: 'Lorenzo, 29 anni, vede che un conto in una valuta emergente rende il 30% annuo, contro tassi molto più bassi in euro. Pensa di spostarci i risparmi.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che un tasso così alto spesso compensa una forte svalutazione', ok: true, f: 'Le valute con tassi molto alti hanno spesso inflazione alta: se la valuta perde il 30% sull’euro, il guadagno sparisce o diventa perdita.' },
      { t: 'Che il 30% è un guadagno sicuro', ok: false, f: 'Il tasso è in valuta locale: il rendimento in euro dipende dal cambio, che può crollare.' },
      { t: 'Che conviene indebitarsi in euro per investire di più', ok: false, f: 'È un carry trade a leva: se la valuta emergente si svaluta, le perdite si moltiplicano.' },
    ] },
    { s: 'Daniela, 48 anni, confronta due ETF sullo stesso indice USA: uno coperto dal cambio e uno no. L’anno scorso quello coperto ha reso meno e vuole passare all’altro.', q: 'Come dovrebbe ragionare?', o: [
      { t: 'Scegliere in base al piano, non all’ultimo anno', ok: true, f: 'La differenza dipende da cambio e costo della copertura in quel periodo: l’anno prossimo potrebbe invertirsi. Conta quanto rischio di cambio vuole tenere.' },
      { t: 'Passare al non coperto: rende sempre di più', ok: false, f: 'Rende di più solo quando il dollaro si rafforza: con un dollaro debole accade il contrario.' },
      { t: 'Alternare i due ETF ogni anno', ok: false, f: 'Inseguire il vincitore dell’anno passato genera costi e spesso arriva in ritardo.' },
    ] },
  ],
  tip: 'Quando investi fuori dall’euro fai due scommesse: sul titolo e sulla valuta. Decidi consapevolmente se e quanto coprire il cambio, prima e non dopo.',
});
