FQC(78, {
  intro: 'Petrolio, rame, grano e oro: scopri cosa muove le materie prime, perché l’oro è un caso a parte e quali trappole nascondono gli strumenti per investirci.',
  cards: [
    { t: 'Le grandi famiglie', x: 'Le materie prime si dividono in energetiche, metalli industriali, metalli preziosi e agricole. Sono quotate per lo più in dollari e i prezzi dipendono da domanda, offerta, scorte, meteo e geopolitica.', v: { k: 'icons', d: [['🛢️', 'Energia'], ['🔩', 'Metalli industriali'], ['🥇', 'Metalli preziosi'], ['🌾', 'Agricole']] } },
    { t: 'Molto più volatili', x: 'Le materie prime possono muoversi con forza in poco tempo: uno shock di offerta o un inverno freddo bastano. Valori indicativi di volatilità relativa.', v: { k: 'scale', a: 'Meno volatile', b: 'Più volatile', d: [['Titoli di Stato', 15], ['Oro', 45], ['Petrolio', 78], ['Gas naturale', 92]] } },
    { t: 'L’unità dell’oro', x: 'L’oro si quota in dollari per oncia troy. L’Italia, tramite la Banca d’Italia, detiene circa 2.450 tonnellate: la terza riserva ufficiale al mondo dopo USA e Germania.', v: { k: 'stat', n: '31,1 g', l: 'il peso di un’oncia troy' } },
    { t: 'Il costo di tenere oro', x: 'L’oro non paga cedole né dividendi. Quando i titoli rendono molto in termini reali, tenere oro “costa” di più in rendimento rinunciato; quando i rendimenti reali scendono, quel costo cala.', v: { k: 'formula', f: 'Costo opportunità dell’oro ≈ rendimento reale rinunciato', n: 'Titolo che rende il 2% oltre l’inflazione: è ciò a cui rinunci tenendo oro' } },
    { t: 'Rifugio, non senza rischio', x: 'Valori arrotondati in dollari per oncia: dopo il picco del 1980 l’oro perse circa il 70% e impiegò quasi 30 anni per tornare a quei livelli nominali.', v: { k: 'bars', d: [['Picco 1980', 850], ['Fine anni ’90', 250], ['Ritorno nel 2008', 850]], u: '$' } },
    { t: 'La trappola del rinnovo', x: 'Molti ETC replicano le materie prime con i futures e devono rinnovarli alla scadenza. In contango il rinnovo costa e l’ETC può rendere molto meno del prezzo a pronti.', v: { k: 'vs', a: ['Contango', 'Futures più cari dello spot: il rinnovo erode il rendimento'], b: ['Backwardation', 'Futures più economici dello spot: il rinnovo può aggiungere rendimento'] } },
  ],
  terms: [
    ['Commodity', 'Bene di base standardizzato e scambiato in grandi volumi, come petrolio, grano o rame.'],
    ['Brent', 'Petrolio di riferimento internazionale, originario del Mare del Nord.'],
    ['ETC', 'Strumento quotato che replica il prezzo di una materia prima, fisicamente o tramite futures.'],
    ['Contango', 'Situazione in cui i futures con scadenza lontana costano più del prezzo a pronti.'],
    ['Backwardation', 'Situazione in cui i futures con scadenza lontana costano meno del prezzo a pronti.'],
    ['Rendimento di roll', 'Guadagno o perdita dovuto al rinnovo di un future in scadenza con il successivo.'],
    ['Bene rifugio', 'Attività ricercata nelle fasi di paura perché ritenuta capace di conservare valore.'],
    ['OPEC+', 'Alleanza di paesi produttori di petrolio che coordina le quote di estrazione.'],
  ],
  tf: [
    ['L’oro non paga cedole né dividendi: il suo rendimento dipende solo dalla variazione di prezzo.', true, 'Per questo il suo costo opportunità cresce quando le alternative, come i titoli di Stato, rendono di più.'],
    ['L’oro è un investimento senza rischio perché è un bene rifugio.', false, 'Il prezzo oscilla molto: dopo il picco del 1980 perse circa il 70% e impiegò quasi 30 anni per tornare a quei livelli.'],
    ['Storicamente l’oro tende a soffrire quando i rendimenti reali salgono molto.', true, 'Rendimenti reali più alti aumentano il costo opportunità di tenere un’attività che non paga interessi.'],
    ['Un ETC su futures sul petrolio replica sempre esattamente il prezzo a pronti del petrolio.', false, 'Deve rinnovare i futures: in contango il costo del rinnovo può far rendere l’ETC molto meno del prezzo spot.'],
    ['Le principali materie prime sono quotate a livello internazionale in dollari USA.', true, 'Per questo anche il cambio euro-dollaro incide su quanto paghiamo energia e materie prime in euro.'],
    ['Il rame è spesso visto come un termometro della salute dell’economia industriale.', true, 'È usato in edilizia, reti elettriche e manifattura: la sua domanda segue da vicino il ciclo industriale.'],
    ['Nell’aprile 2020 il future sul petrolio WTI in scadenza scese per breve tempo sotto zero.', true, 'Con domanda crollata e depositi quasi pieni, chi doveva ricevere il petrolio pagò pur di liberarsi dei contratti.'],
    ['I prezzi delle materie prime agricole dipendono solo dalla domanda dei consumatori.', false, 'Contano molto anche offerta, meteo, raccolti, scorte, costi energetici e politiche commerciali.'],
    ['Comprare lingotti o monete d’oro fisico non comporta alcun costo.', false, 'Ci sono la differenza tra prezzo di acquisto e di vendita, i costi di custodia e di assicurazione.'],
    ['Le materie prime possono offrire una certa protezione quando l’inflazione è trainata da energia e cibo.', true, 'Se a far salire i prezzi sono proprio le materie prime, chi ne è esposto ne beneficia, come accadde negli anni ’70.'],
  ],
  mcq: [
    { q: 'Perché un dollaro debole tende a sostenere i prezzi in dollari delle materie prime?', a: 'Costano meno a chi compra in altre valute', w: ['Si pagano solo in euro', 'L’OPEC+ deve alzare i prezzi', 'Le scorte si riducono per legge'], e: 'Con un dollaro debole la stessa quantità costa meno in euro, yuan o yen: la domanda internazionale sale e sostiene il prezzo in dollari.' },
    { q: 'Cosa significa che il mercato dei futures su una materia prima è in contango?', a: 'Le scadenze lontane costano più dello spot', w: ['Le scadenze lontane costano meno dello spot', 'Il prezzo a pronti è uguale a zero', 'I futures non possono essere rinnovati'], e: 'Il contango riflette spesso costi di stoccaggio e finanziamento; per chi rinnova i contratti è un costo ricorrente.' },
    { q: 'Quale fattore tende ad aumentare il costo opportunità di detenere oro?', a: 'Rendimenti reali dei titoli in aumento', w: ['Inflazione in forte aumento', 'Crisi geopolitica improvvisa', 'Acquisti di oro delle banche centrali'], e: 'Se i titoli rendono di più al netto dell’inflazione, rinunciarvi per tenere oro, che non rende nulla, costa di più.' },
    { q: 'Secondo i dati ufficiali, quale paese detiene la terza riserva aurea al mondo per tonnellate?', a: 'Italia', w: ['Svizzera', 'Giappone', 'Regno Unito'], e: 'Dopo USA e Germania c’è l’Italia, con circa 2.450 tonnellate custodite dalla Banca d’Italia.' },
    { q: 'L’OPEC+ annuncia a sorpresa un forte taglio della produzione. Effetto immediato più probabile?', a: 'Rialzo del prezzo del petrolio', w: ['Calo del prezzo del petrolio', 'Calo del prezzo dell’oro', 'Nessun effetto sull’energia'], e: 'Meno offerta a parità di domanda spinge in alto i prezzi, soprattutto se la mossa non era attesa.' },
    { q: 'Che cosa è successo all’oro nel 1971?', a: 'Finì la convertibilità del dollaro in oro', w: ['Nacque il gold standard negli USA', 'Fu quotato il primo ETC sull’oro', 'Fu vietato possedere oro in Europa'], e: 'Con la fine degli accordi di Bretton Woods il dollaro smise di essere convertibile in oro a 35 $ l’oncia e il prezzo divenne libero.' },
    { q: 'Qual è un vantaggio di un ETC fisico sull’oro rispetto a uno basato su futures?', a: 'Non subisce i costi di rinnovo dei contratti', w: ['Garantisce un rendimento minimo annuo', 'Non risente del prezzo dell’oro', 'Paga una cedola fissa ogni anno'], e: 'L’ETC fisico è garantito da lingotti custoditi: segue il prezzo spot senza l’effetto del roll, ma ha comunque costi di gestione.' },
    { q: 'Rame e petrolio crollano insieme per settimane. Cosa segnalano più spesso?', a: 'Timori di rallentamento globale', w: ['Un’accelerazione dell’inflazione', 'Una forte ripresa industriale', 'Un dollaro molto debole'], e: 'Sono materie prime legate alla crescita: un calo congiunto riflette spesso attese di domanda più debole.' },
  ],
  fill: [
    { s: 'L’oro si quota in dollari per ___ troy.', a: 'oncia', w: ['libbra', 'grammo', 'tonnellata'] },
    { s: 'Quando i futures lontani costano più del prezzo a pronti, il mercato è in ___.', a: 'contango', w: ['backwardation', 'parità', 'equilibrio'] },
    { s: 'Un ___ fisico sull’oro è garantito da lingotti custoditi in un caveau.', a: 'ETC', w: ['CFD', 'BOT', 'PMI'] },
    { s: 'Il ___ è il petrolio di riferimento usato per molti prezzi in Europa.', a: 'Brent', w: ['WTI', 'TTF', 'Urals'] },
    { s: 'L’oro è considerato un bene ___ nei momenti di forte incertezza.', a: 'rifugio', w: ['ciclico', 'di consumo', 'deperibile'] },
  ],
  order: [
    { q: 'Ordina questi eventi in ordine cronologico', i: ['Fine della convertibilità del dollaro in oro', 'Picco dell’oro dopo l’inflazione degli anni ’70', 'Petrolio vicino a 150 $ al barile', 'Future WTI sotto zero'], e: '1971, 1980, 2008 e 2020: cinquant’anni di shock che mostrano quanto possano oscillare i prezzi delle materie prime.' },
    { q: 'Ordina i passaggi del rinnovo di un ETC su futures in contango', i: ['L’ETC detiene il future in scadenza', 'La scadenza del contratto si avvicina', 'Vende il future in scadenza', 'Compra il future successivo, più caro', 'Con gli stessi soldi ottiene meno contratti'], e: 'Vendere basso e comprare più alto a ogni rinnovo riduce la quantità posseduta: in contango è un costo che si ripete.' },
  ],
  cat: [
    { q: 'Metallo prezioso o industriale?', g: [['Prezioso', ['Oro', 'Argento', 'Platino']], ['Industriale', ['Rame', 'Alluminio', 'Nichel']]] },
    { q: 'A parità di altri fattori, tende a far salire o scendere il prezzo dell’oro?', g: [['Salire', ['Forte paura sui mercati', 'Calo dei rendimenti reali', 'Acquisti delle banche centrali']], ['Scendere', ['Forte rialzo dei rendimenti reali', 'Dollaro molto più forte', 'Vendite massicce di riserve ufficiali']]] },
  ],
  scen: [
    { s: 'Antonio, 63 anni, pensionato, dopo una notizia di guerra vuole spostare il 60% dei risparmi in oro, “l’unica cosa che non perde mai valore”.', q: 'Cosa gli consigli?', o: [
      { t: 'Solo una quota contenuta, in un piano diversificato', ok: true, f: 'L’oro può aiutare nelle crisi, ma oscilla molto e non rende interessi: una quota limitata diversifica senza esporre tutto a un solo bene.' },
      { t: 'Il 60% va bene: l’oro non scende mai', ok: false, f: 'L’oro ha avuto cali di circa il 70% e decenni di attesa per recuperare: non è adatto a concentrare i risparmi di un pensionato.' },
      { t: 'Tutto in oro, finché la guerra non finisce', ok: false, f: 'Comprare sull’onda della paura spesso significa comprare dopo un forte rialzo, con alto rischio di un ritracciamento.' },
    ] },
    { s: 'Martina, 32 anni, ha comprato un ETC sul gas naturale basato su futures per “guadagnare dalle bollette alte”. Dopo un anno il prezzo spot è salito, ma il suo ETC ha perso.', q: 'Come si spiega?', o: [
      { t: 'Il costo del rinnovo dei futures in contango', ok: true, f: 'A ogni rinnovo ha venduto il contratto in scadenza e comprato quello successivo più caro: questo costo può superare il rialzo del prezzo spot.' },
      { t: 'Un errore di calcolo dell’emittente', ok: false, f: 'Non è un errore: è il funzionamento normale di un ETC su futures, spiegato nel prospetto.' },
      { t: 'Le commissioni di acquisto in borsa', ok: false, f: 'Le commissioni pesano poco: la differenza con lo spot nasce dal meccanismo dei futures.' },
    ] },
    { s: 'Bruno, 57 anni, riceve da un venditore porta a porta un’offerta di lingotti “a prezzo di mercato”, con riacquisto garantito. Non gli dicono a che prezzo potrà rivenderli.', q: 'Cosa dovrebbe fare prima di decidere?', o: [
      { t: 'Verificare venditore, spread e prezzo di rivendita', ok: true, f: 'Nell’oro fisico la differenza tra acquisto e rivendita può essere ampia: senza un prezzo di riacquisto chiaro non sai quanto paghi davvero.' },
      { t: 'Comprare subito: l’oro è sempre un affare', ok: false, f: 'Il valore dell’oro non dice nulla sui costi e sull’affidabilità di chi lo vende.' },
      { t: 'Firmare, tanto il riacquisto è garantito', ok: false, f: 'Una garanzia di riacquisto senza prezzo definito non protegge: potrebbe riacquistare molto sotto il valore di mercato.' },
    ] },
    { s: 'Ilaria, 45 anni, vuole esporsi all’oro e sceglie un ETF su società minerarie aurifere, convinta che segua il prezzo dell’oro come un ETC fisico.', q: 'Cosa dovrebbe sapere?', o: [
      { t: 'Che le minerarie sono azioni, con rischi in più', ok: true, f: 'I loro utili amplificano i movimenti dell’oro e dipendono da costi, debito e gestione: possono salire o scendere molto più del metallo.' },
      { t: 'Che è identico a comprare oro fisico', ok: false, f: 'Un’azione rappresenta un’impresa, non il metallo: i risultati possono divergere molto.' },
      { t: 'Che le minerarie non dipendono dal prezzo dell’oro', ok: false, f: 'Ne dipendono eccome, anzi in modo amplificato: ma non solo da quello.' },
    ] },
  ],
  tip: 'Prima di comprare un ETC controlla se è fisico o su futures e come gestisce il rinnovo: sullo stesso sottostante i risultati possono essere molto diversi.',
});
