FQC(79, {
  intro: 'Dal 1929 al 2020: ripercorri le grandi crisi con dati arrotondati e scopri cosa le ha causate, come sono finite e cosa insegnano a chi investe.',
  cards: [
    { t: 'Quanto si è perso', x: 'Cali dal massimo al minimo, valori arrotondati: Dow Jones 1929-32, Nasdaq 2000-02, S&P 500 2007-09 e S&P 500 nel 2020. Anche gli indici più ampi possono dimezzarsi.', v: { k: 'bars', d: [['1929-32', -89], ['2000-02', -78], ['2007-09', -57], ['2020', -34]], u: '%' } },
    { t: 'Anatomia di una crisi', x: 'Molte crisi seguono uno schema simile: credito facile ed euforia gonfiano i prezzi, uno shock rompe la fiducia, la leva costringe a vendere e servono interventi per fermare la spirale.', v: { k: 'steps', s: ['Credito facile ed euforia', 'Bolla dei prezzi', 'Shock e fiducia che crolla', 'Vendite forzate', 'Interventi e lenta ripresa'] } },
    { t: 'La crisi del debito sovrano', x: 'Nel 2011 i timori sulla sostenibilità dei debiti pubblici colpirono Grecia, Irlanda, Portogallo, Spagna e Italia. La svolta arrivò nel luglio 2012 con il “whatever it takes” di Draghi.', v: { k: 'stat', n: '≈ 575 pb', l: 'spread BTP-Bund al picco di novembre 2011' } },
    { t: 'Due risposte opposte', x: 'Nel 1929-33 politica monetaria restrittiva, fallimenti bancari a catena e protezionismo aggravarono la Depressione. Nel 2008 e nel 2020 banche centrali e governi intervennero in modo massiccio.', v: { k: 'vs', a: ['1929-33', 'Banche lasciate fallire, stretta monetaria, dazi'], b: ['2008 e 2020', 'Tassi tagliati, QE, sostegno a banche ed economia'] } },
    { t: 'Quanto ci è voluto per recuperare', x: 'Tempo per tornare al massimo precedente, prezzi nominali senza dividendi. Con i dividendi reinvestiti i recuperi sono stati più brevi, ma comunque molto variabili.', v: { k: 'scale', a: 'Recupero rapido', b: 'Recupero lentissimo', d: [['2020: circa 6 mesi', 3], ['2007: oltre 5 anni', 22], ['2000: circa 15 anni (Nasdaq)', 60], ['1929: circa 25 anni (Dow)', 100]] } },
    { t: 'Cosa insegnano', x: 'Nessuno ha previsto con precisione tempi e forma delle crisi. Chi le ha attraversate meglio aveva difese preparate prima: diversificazione, liquidità, niente leva e un orizzonte lungo.', v: { k: 'icons', d: [['🧺', 'Diversificare'], ['💧', 'Tenere liquidità'], ['⚠️', 'Evitare la leva'], ['⏳', 'Orizzonte lungo']] } },
  ],
  terms: [
    ['Grande Depressione', 'Lunga crisi economica mondiale seguita al crollo di Wall Street del 1929.'],
    ['Bolla speculativa', 'Prezzi saliti molto oltre il valore fondamentale, spinti da euforia e attese irrealistiche.'],
    ['Mutui subprime', 'Prestiti per la casa a debitori con scarsa capacità di rimborso, al centro della crisi del 2008.'],
    ['Contagio', 'Diffusione di una crisi da un paese o da un mercato ad altri collegati.'],
    ['Corsa agli sportelli', 'Ritiro massiccio dei depositi per paura che la banca fallisca.'],
    ['Rischio sistemico', 'Rischio che il fallimento di un’istituzione travolga l’intero sistema finanziario.'],
    ['Bear market', 'Ribasso di almeno il 20% dai massimi, secondo la convenzione più diffusa.'],
    ['Whatever it takes', 'Frase di Draghi del 2012 che segnò la svolta nella crisi del debito sovrano europeo.'],
  ],
  tf: [
    ['Dopo il crollo del 1929 il Dow Jones perse circa l’89% dal massimo al minimo del 1932.', true, 'È il ribasso più profondo della storia della borsa USA: servirono circa 25 anni per rivedere quei massimi in termini nominali.'],
    ['Dopo lo scoppio della bolla dot-com il Nasdaq tornò ai massimi del 2000 in circa un anno.', false, 'Il Nasdaq perse circa il 78% e impiegò circa 15 anni per tornare ai massimi del 2000, in termini nominali.'],
    ['Il fallimento di Lehman Brothers nel settembre 2008 fu uno dei momenti più acuti della crisi finanziaria.', true, 'Il crollo di una grande banca d’investimento bloccò la fiducia tra le banche e innescò il panico su scala mondiale.'],
    ['Nella crisi del 2011 lo spread BTP-Bund superò i 500 punti base.', true, 'A novembre 2011 arrivò vicino ai 575 punti base: i rendimenti dei BTP decennali superarono il 7%.'],
    ['Nel 2020 il calo dell’S&P 500 di circa un terzo durò diversi anni.', false, 'Il calo avvenne in circa 5 settimane e i massimi furono recuperati in circa 6 mesi, anche grazie a enormi interventi monetari e fiscali.'],
    ['Le crisi finanziarie gravi sono spesso precedute da un forte aumento del debito e della leva.', true, 'Il debito amplifica i guadagni in salita e costringe a vendere in discesa: è il filo che lega 1929, 2008 e molte altre crisi.'],
    ['Nel 1929-33 le autorità reagirono con tagli dei tassi e grandi acquisti di titoli, come nel 2008.', false, 'Politica monetaria restrittiva, fallimenti bancari e protezionismo aggravarono la Depressione; nel 2008 si fece quasi l’opposto.'],
    ['Chi vendette tutto vicino al minimo del marzo 2009 e restò fuori perse la successiva ripresa.', true, 'Dal minimo di marzo 2009 la borsa USA iniziò uno dei rialzi più lunghi della storia: vendere nel panico cristallizzò le perdite.'],
    ['Una recessione e un crollo di borsa si verificano sempre insieme e con la stessa durata.', false, 'Non sempre: la borsa spesso anticipa calo e ripresa, e ci sono stati crolli senza recessione, come nel 1987.'],
    ['Le crisi storiche dimostrano che la diversificazione rende impossibile perdere denaro.', false, 'Nelle crisi le correlazioni salgono e molti attivi scendono insieme: la diversificazione riduce le perdite, non le elimina.'],
  ],
  mcq: [
    { q: 'Quale fu il detonatore principale della crisi finanziaria del 2008?', a: 'Le perdite sui mutui subprime', w: ['Lo scoppio della bolla dot-com', 'Il default del debito italiano', 'Una pandemia globale'], e: 'I mutui subprime, impacchettati in titoli complessi e diffusi nel sistema, generarono perdite enormi e una crisi di fiducia tra banche.' },
    { q: 'Cosa caratterizzò la bolla dot-com?', a: 'Valutazioni altissime di società internet con pochi utili', w: ['Prezzi delle case gonfiati dal credito facile', 'Un rialzo esplosivo del prezzo del petrolio', 'Il default di diversi Stati europei'], e: 'Bastava legarsi a internet per ottenere valutazioni enormi, spesso senza utili: quando le attese si sgonfiarono il Nasdaq crollò.' },
    { q: 'Quale intervento è associato alla svolta nella crisi del debito sovrano europeo?', a: 'Il “whatever it takes” di Draghi', w: ['Il fallimento di Lehman Brothers', 'La fine di Bretton Woods', 'Il lancio del PEPP'], e: 'Nel luglio 2012 Draghi disse che la BCE avrebbe fatto tutto il necessario per preservare l’euro: gli spread iniziarono a scendere.' },
    { q: 'Un indice ha perso il 50%. Di quanto deve risalire per tornare al livello iniziale?', a: '+100%', w: ['+50%', '+75%', '+150%'], e: 'Da 100 a 50 si perde il 50%; da 50 a 100 bisogna guadagnare il 100%. Le perdite profonde richiedono rialzi molto più grandi.' },
    { q: 'Perché la crisi del 2011 colpì duramente l’Italia?', a: 'Debito alto e crescita debole minarono la fiducia', w: ['L’Italia aveva un cambio fisso con il dollaro', 'Le banche italiane erano piene di subprime', 'La BCE aveva portato i tassi al 10%'], e: 'Con un debito pubblico elevato e una crescita bassa, i mercati chiesero rendimenti sempre più alti per finanziare lo Stato.' },
    { q: 'Quale caratteristica distinse il ribasso del 2020?', a: 'Velocità estrema del calo e del recupero', w: ['Durata di oltre dieci anni', 'Nessun intervento delle banche centrali', 'Calo limitato al solo settore tecnologico'], e: 'Circa un terzo di calo in 5 settimane e nuovi massimi dopo circa 6 mesi: una crisi brevissima, sostenuta da interventi senza precedenti.' },
    { q: 'Quale insegnamento accomuna 1929, 2000 e 2008?', a: 'Leva ed euforia amplificano le perdite', w: ['Le crisi colpiscono solo i piccoli', 'Le banche centrali le causano sempre', 'Gli immobili non scendono mai'], e: 'In tutti e tre i casi prezzi spinti da entusiasmo e debito si sono rivelati fragili quando la fiducia è venuta meno.' },
    { q: 'Un amico dice: “Dopo un calo del 30% un indice non può scendere ancora molto”. Cosa rispondi?', a: 'Può scendere ancora molto, come nel 1929-32', w: ['Ha ragione, il 30% è un limite storico', 'Ha ragione, ma solo per gli indici USA', 'Ha ragione se interviene la BCE'], e: 'Non esiste un pavimento: nel 1929-32 il Dow Jones, dopo i primi forti cali, arrivò a perdere circa l’89% dal massimo.' },
  ],
  fill: [
    { s: 'Il crollo di Wall Street del 1929 diede avvio alla Grande ___.', a: 'Depressione', w: ['Recessione', 'Inflazione', 'Moderazione'] },
    { s: 'Nel 2008 i mutui ___ furono al centro della crisi finanziaria.', a: 'subprime', w: ['prime', 'agevolati', 'studenteschi'] },
    { s: 'Nel novembre 2011 lo ___ BTP-Bund arrivò vicino ai 575 punti base.', a: 'spread', w: ['rating', 'swap', 'stacco'] },
    { s: 'Un ribasso di almeno il 20% dai massimi è detto ___ market.', a: 'bear', w: ['bull', 'flat', 'side'] },
    { s: 'Nelle crisi la ___ amplifica le perdite e costringe a vendite forzate.', a: 'leva', w: ['liquidità', 'diversificazione', 'cedola'] },
  ],
  order: [
    { q: 'Ordina le crisi in ordine cronologico', i: ['Crollo di Wall Street', 'Scoppio della bolla dot-com', 'Fallimento di Lehman Brothers', 'Crisi del debito sovrano europeo', 'Crollo da pandemia'], e: '1929, 2000, 2008, 2011 e 2020: cause diverse, ma la stessa lezione sulla fragilità di euforia e leva.' },
    { q: 'Ordina dal calo massimo più ampio al più contenuto', i: ['Dow Jones 1929-32', 'Nasdaq 2000-02', 'S&P 500 2007-09', 'S&P 500 2020'], e: 'Valori arrotondati: circa −89%, −78%, −57% e −34%.' },
  ],
  cat: [
    { q: 'Crisi finanziaria del 2008 o crisi del debito sovrano europeo?', g: [['Crisi del 2008', ['Fallimento di Lehman Brothers', 'Mutui subprime', 'Crisi partita dagli Stati Uniti']], ['Debito sovrano', ['Spread BTP-Bund oltre 500 punti', 'Ristrutturazione del debito greco', 'Timori sulla tenuta dell’euro']]] },
    { q: 'Bolla dot-com (2000) o crollo da pandemia (2020)?', g: [['Dot-com', ['Società internet senza utili', 'Nasdaq giù di circa il 78%', 'Recupero in circa 15 anni']], ['Pandemia', ['Lockdown e attività bloccate', 'Calo di un terzo in 5 settimane', 'Massimi recuperati in circa 6 mesi']]] },
  ],
  scen: [
    { s: 'Marzo 2020. Giuseppe, 52 anni, vede il suo portafoglio diversificato perdere il 30% in quattro settimane. Ha un fondo di emergenza e un orizzonte di 15 anni, ma la paura è fortissima.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Seguire il piano e ribilanciare se previsto', ok: true, f: 'Con liquidità di riserva e orizzonte lungo non era costretto a vendere. Chi ha seguito il piano ha visto i massimi tornare in circa sei mesi.' },
      { t: 'Vendere tutto e aspettare tempi migliori', ok: false, f: 'Vendere vicino al minimo trasforma un calo temporaneo in una perdita definitiva, e il momento di rientrare è difficilissimo da scegliere.' },
      { t: 'Chiedere un prestito per comprare tutto', ok: false, f: 'Indebitarsi nel pieno del panico espone a perdite ancora più grandi se il calo continua, come nel 1929-32.' },
    ] },
    { s: 'Novembre 2011. Rita, 61 anni, ha BTP con scadenza tra 5 anni che perdono valore mentre lo spread supera i 500 punti. Non le servono quei soldi prima della scadenza.', q: 'Qual è la scelta più prudente?', o: [
      { t: 'Evitare vendite nel panico e diversificare in futuro', ok: true, f: 'Se lo Stato rimborsa, a scadenza riceve il nominale. Vendere nel picco della crisi avrebbe reso definitiva la perdita; per il futuro, meglio non concentrarsi su un solo emittente.' },
      { t: 'Vendere tutto subito per limitare i danni', ok: false, f: 'Vendere al picco dello spread avrebbe fissato la perdita proprio prima della svolta del 2012.' },
      { t: 'Comprare altri BTP con tutti i risparmi', ok: false, f: 'Concentrare tutto su un solo emittente nel mezzo di una crisi è una scommessa, non una gestione prudente.' },
    ] },
    { s: 'Edoardo, 30 anni, vede un settore di moda salire del 200% in un anno. Gli amici dicono che “stavolta è diverso” e che le vecchie valutazioni non contano più.', q: 'Come dovrebbe comportarsi?', o: [
      { t: 'Limitare l’esposizione e guardare le valutazioni', ok: true, f: '“Stavolta è diverso” si è sentito anche nel 2000: un’esposizione contenuta gli permette di partecipare senza rischiare il patrimonio.' },
      { t: 'Investire tutto prima che salga ancora', ok: false, f: 'Entrare con tutto dopo un +200% significa esporsi al massimo proprio quando il rischio di una correzione è più alto.' },
      { t: 'Vendere allo scoperto il settore con la leva', ok: false, f: 'Le bolle possono gonfiarsi ancora a lungo: scommettere a leva sul loro scoppio può portare a perdite enormi.' },
    ] },
    { s: 'Caterina, 45 anni, vuole tenere tutto in liquidità finché non arriverà “il prossimo crollo”, per comprare ai minimi. Aspetta già da tre anni.', q: 'Cosa le faresti notare?', o: [
      { t: 'Che un piano con difese prefissate batte l’attesa', ok: true, f: 'Nessuno sa quando arriverà la prossima crisi. Diversificazione, fondo di emergenza e investimenti graduali la preparano senza dover indovinare i tempi.' },
      { t: 'Che ha ragione: il crollo arriverà presto', ok: false, f: 'Anche se arrivasse, i mercati potrebbero prima salire così tanto che il minimo resterebbe sopra i prezzi di oggi.' },
      { t: 'Che deve investire tutto oggi a leva', ok: false, f: 'Passare da un estremo all’altro non risolve: la leva rende fragile proprio chi teme le crisi.' },
    ] },
  ],
  tip: 'Le crisi tornano, sempre diverse. Prepara prima le difese: fondo di emergenza, niente leva, diversificazione e un piano scritto da seguire quando arriva il panico.',
});
