FQC(80, {
  intro: 'I prezzi si muovono più sulle sorprese che sulle notizie: scopri il ruolo di consenso, aspettative e “buy the rumor, sell the news”.',
  cards: [
    { t: 'Conta la sorpresa', x: 'Prima di ogni dato gli analisti formano un consenso. I prezzi incorporano già quell’attesa: a muoverli è soprattutto la distanza tra dato effettivo e consenso.', v: { k: 'formula', f: 'Sorpresa = dato effettivo − consenso', n: 'Es.: consenso +0,3%, effettivo +0,6% → sorpresa di +0,3 punti' } },
    { t: 'Buy the rumor, sell the news', x: 'Quando si diffonde un’attesa positiva, molti comprano in anticipo. Quando la notizia diventa ufficiale non resta nessuno da convincere e scattano le prese di profitto.', v: { k: 'steps', s: ['Voce o attesa', 'Acquisti in anticipo', 'Notizia ufficiale', 'Prese di profitto'] } },
    { t: 'Attesa o inattesa?', x: 'Una notizia attesa è in gran parte già nei prezzi; una inattesa li costringe ad aggiornarsi in fretta. Per questo la stessa notizia può muovere molto o quasi nulla.', v: { k: 'vs', a: ['Notizia attesa', 'Già nei prezzi: reazione spesso modesta'], b: ['Notizia inattesa', 'Prezzi da aggiornare: reazione forte e rapida'] } },
    { t: 'Dove si leggono le attese', x: 'Le aspettative si ricavano dai sondaggi tra economisti, dalle stime degli analisti sugli utili, dai prezzi dei futures sui tassi e dalle indicazioni di aziende e banche centrali.', v: { k: 'icons', d: [['📊', 'Consenso degli economisti'], ['🧾', 'Stime sugli utili'], ['📈', 'Futures sui tassi'], ['🗣️', 'Guidance']] } },
    { t: 'Stesso utile, reazioni opposte', x: 'Esempio illustrativo: un’azienda annuncia un utile per azione di 1,10 €. Se il mercato si aspettava 1,00 € il titolo può salire; se si aspettava 1,20 € può scendere.', v: { k: 'bars', d: [['Attese 1,00 €', 4], ['Attese 1,20 €', -5]], u: '%' } },
    { t: 'Più veloci di te', x: 'Gli algoritmi leggono e incorporano i dati macro in frazioni di secondo. Chi reagisce dopo aver letto il titolo di giornale arriva quasi sempre a prezzi già aggiornati.', v: { k: 'stat', n: '< 1 secondo', l: 'il tempo in cui gli algoritmi reagiscono a un dato macro' } },
  ],
  terms: [
    ['Consenso', 'Media o mediana delle previsioni degli analisti su un dato economico o un utile.'],
    ['Sorpresa', 'Differenza tra il dato pubblicato e quanto il mercato si aspettava.'],
    ['Priced in', 'Detto di un’informazione già incorporata nei prezzi di mercato.'],
    ['Whisper number', 'Stima informale di cosa il mercato si aspetta davvero, spesso diversa dal consenso ufficiale.'],
    ['Guidance', 'Indicazioni dell’azienda sui risultati attesi nei periodi futuri.'],
    ['Gap', 'Salto di prezzo tra una chiusura e l’apertura successiva, spesso dopo una notizia.'],
    ['Efficienza informativa', 'Capacità del mercato di incorporare rapidamente le informazioni pubbliche nei prezzi.'],
    ['Sell the news', 'Vendite che arrivano proprio quando una notizia attesa diventa ufficiale.'],
  ],
  tf: [
    ['Un dato economico migliore del previsto fa sempre salire la borsa.', false, 'Dipende dal contesto: dati forti possono far temere tassi più alti e far scendere le azioni (“good news is bad news”).'],
    ['Il mercato reagisce soprattutto alla differenza tra dato effettivo e attese, non al dato in sé.', true, 'Ciò che era atteso è già nei prezzi: a spostarli è la parte inattesa dell’informazione.'],
    ['Un’azienda può salire in borsa anche dopo aver annunciato una perdita.', true, 'Se la perdita è più piccola del previsto o la guidance migliora, il mercato può premiare il titolo.'],
    ['“Buy the rumor, sell the news” descrive vendite che arrivano quando una notizia attesa diventa ufficiale.', true, 'Chi ha comprato sull’attesa incassa il guadagno all’annuncio: il prezzo può scendere anche con una notizia positiva.'],
    ['Comprare dopo aver letto il titolo su un dato macro dà di solito un vantaggio sugli altri investitori.', false, 'Gli algoritmi incorporano i dati in frazioni di secondo: chi reagisce dopo arriva a prezzi già aggiornati.'],
    ['Se un taglio dei tassi è dato per certo dai futures, la sola conferma tende a muovere poco i mercati.', true, 'Era già nei prezzi: contano piuttosto i segnali sulle mosse successive.'],
    ['Utili sopra il consenso garantiscono un rialzo del titolo.', false, 'Contano anche guidance, qualità dei ricavi, margini e attese informali: un risultato sopra il consenso può essere accolto con vendite.'],
    ['Nei minuti intorno a un dato importante spread e volatilità tendono ad aumentare.', true, 'Gli operatori riducono le offerte in attesa del dato e poi i prezzi saltano: ordini a mercato possono essere eseguiti male.'],
    ['Una notizia molto negativa ma già ampiamente attesa può essere seguita da un rialzo.', true, 'Se il peggio è già nei prezzi, la conferma toglie incertezza e può innescare ricoperture e acquisti.'],
    ['Operare sfruttando informazioni privilegiate non ancora pubbliche è legale, se si è abbastanza veloci.', false, 'È abuso di informazioni privilegiate, vietato dal regolamento europeo MAR: in Italia comporta sanzioni della CONSOB e anche penali.'],
  ],
  mcq: [
    { q: 'Consenso sul PIL +0,2%, dato effettivo +0,5%. Quanto vale la sorpresa?', a: '+0,3 punti percentuali', w: ['+0,5 punti percentuali', '+0,7 punti percentuali', '−0,3 punti percentuali'], e: 'Sorpresa = effettivo − consenso = 0,5 − 0,2 = +0,3 punti.' },
    { q: 'Un’azienda batte le stime sugli utili del trimestre, ma taglia le previsioni per l’anno. Reazione più probabile?', a: 'Il titolo può scendere: conta il futuro', w: ['Il titolo deve salire per forza', 'Il titolo resta fermo per regola', 'Il titolo viene sospeso dalla borsa'], e: 'Il prezzo riflette gli utili futuri: una guidance peggiore può pesare più di un trimestre migliore del previsto.' },
    { q: 'Che cosa significa che una notizia è “già nei prezzi”?', a: 'Le attese erano già incorporate', w: ['La notizia è stata pagata dagli investitori', 'Il prezzo è fissato dalla CONSOB', 'La notizia riguarda solo i prezzi'], e: 'Se il mercato aveva già previsto la notizia, la sua uscita non cambia le stime e la reazione tende a essere modesta.' },
    { q: 'Come si può stimare cosa il mercato si aspetta da una riunione della banca centrale?', a: 'Dai prezzi dei futures sui tassi a breve', w: ['Dal numero di articoli di giornale', 'Dall’andamento del prezzo dell’oro', 'Dal volume di scambi del giorno prima'], e: 'I futures sui tassi incorporano le attese degli operatori e permettono di ricavare la probabilità implicita di un rialzo o di un taglio.' },
    { q: 'Una voce di acquisizione fa salire un titolo del 25% in un mese. L’offerta viene poi annunciata proprio al prezzo atteso. Cosa può accadere?', a: 'Il titolo può fermarsi: era già nei prezzi', w: ['Il titolo deve salire di un altro 25%', 'Il titolo torna sempre al prezzo iniziale', 'Il titolo raddoppia il giorno dell’annuncio'], e: 'Il rialzo è avvenuto sull’attesa: l’annuncio in linea con le voci non aggiunge informazioni nuove.' },
    { q: 'Quale comportamento è più sensato prima di un dato macro molto atteso?', a: 'Ridurre la leva e le posizioni troppo grandi', w: ['Aumentare la leva per sfruttare il movimento', 'Usare ordini a mercato con spread ampi', 'Indovinare il dato e puntare tutto'], e: 'Intorno ai dati spread e volatilità salgono: ridurre l’esposizione limita i danni di un movimento imprevedibile.' },
    { q: 'Quale affermazione descrive meglio l’efficienza informativa dei mercati?', a: 'Le notizie pubbliche entrano nei prezzi in fretta', w: ['I prezzi ignorano le notizie per giorni', 'Solo i piccoli investitori muovono i prezzi', 'I prezzi riflettono solo i dati passati'], e: 'Nei mercati liquidi le informazioni pubbliche vengono incorporate quasi subito: è difficile guadagnare reagendo a notizie già note.' },
    { q: 'Dopo una notizia inattesa diffusa a borsa chiusa, un titolo apre molto sotto la chiusura precedente. Come si chiama questo salto?', a: 'Gap', w: ['Spread', 'Pullback', 'Breakout'], e: 'Il gap è un vuoto di prezzo tra chiusura e apertura: gli ordini di stop possono essere eseguiti molto peggio del livello impostato.' },
  ],
  fill: [
    { s: 'La differenza tra dato effettivo e attese si chiama ___.', a: 'sorpresa', w: ['consenso', 'guidance', 'revisione'] },
    { s: 'Il ___ è la media delle previsioni degli analisti.', a: 'consenso', w: ['gap', 'rumor', 'dividendo'] },
    { s: '“Buy the rumor, sell the ___” descrive le prese di profitto all’annuncio.', a: 'news', w: ['fact', 'trend', 'dip'] },
    { s: 'Le indicazioni di un’azienda sui risultati futuri si chiamano ___.', a: 'guidance', w: ['rating', 'payout', 'spread'] },
    { s: 'Un’informazione già incorporata nei prezzi si dice ___.', a: 'scontata', w: ['riservata', 'ritardata', 'garantita'] },
  ],
  order: [
    { q: 'Ordina le fasi tipiche di “buy the rumor, sell the news”', i: ['Circola una voce', 'Acquisti in anticipo e prezzo in salita', 'La notizia diventa ufficiale', 'Prese di profitto e prezzo in calo'], e: 'Il prezzo sale sull’attesa e scende quando l’attesa si realizza: chi compra all’annuncio arriva spesso tardi.' },
    { q: 'Ordina cosa succede intorno a un dato macro', i: ['Gli analisti pubblicano le stime', 'Si forma il consenso', 'Esce il dato effettivo', 'Gli algoritmi reagiscono in pochi istanti', 'Il mercato digerisce dettagli e revisioni'], e: 'Prima si formano le attese, poi esce il dato e arriva la reazione immediata; nelle ore successive contano dettagli e revisioni.' },
  ],
  cat: [
    { q: 'Tende a muovere molto o poco i prezzi?', g: [['Molto', ['Taglio dei tassi non atteso', 'Utili molto sotto il consenso', 'Guidance tagliata a sorpresa']], ['Poco', ['Rialzo dei tassi atteso al 100%', 'Dato in linea con il consenso', 'Notizia già ampiamente anticipata']]] },
    { q: 'Sorpresa positiva o negativa per l’economia rispetto al consenso?', g: [['Positiva', ['PIL atteso +0,1%, effettivo +0,4%', 'Disoccupazione attesa 6,5%, effettiva 6,2%', 'Vendite attese +0,2%, effettive +0,6%']], ['Negativa', ['PMI atteso 52, effettivo 49', 'Vendite attese +0,5%, effettive −0,2%', 'Occupati attesi +150.000, effettivi +40.000']]] },
  ],
  scen: [
    { s: 'Valerio, 34 anni, legge sui social di un’imminente offerta di acquisto su una società quotata. Il titolo è già salito del 30% in due settimane e lui vorrebbe entrare subito.', q: 'Cosa dovrebbe considerare?', o: [
      { t: 'Che la voce non è verificata ed è già nei prezzi', ok: true, f: 'Se l’offerta non arriva il titolo può crollare; se arriva al prezzo atteso il guadagno residuo è minimo. Le voci sui social possono anche essere manipolazioni.' },
      { t: 'Che deve comprare prima che sia ufficiale', ok: false, f: 'Inseguire una voce dopo un +30% significa prendersi quasi tutto il rischio con poco potenziale rimasto.' },
      { t: 'Che conviene comprare con la leva', ok: false, f: 'La leva su una voce non verificata può trasformare una delusione in una perdita molto pesante.' },
    ] },
    { s: 'Monica, 46 anni, ha azioni di un’azienda che annuncia utili record. Il titolo però scende del 7% perché la guidance per il prossimo anno è più debole del previsto.', q: 'Qual è la reazione più sensata?', o: [
      { t: 'Rileggere la tesi d’investimento alla luce della guidance', ok: true, f: 'Il mercato guarda al futuro: conta capire se le nuove previsioni cambiano le ragioni per cui possiede il titolo, non il -7% in sé.' },
      { t: 'Vendere subito tutto per evitare altre perdite', ok: false, f: 'Decidere sotto l’emozione del momento, senza leggere i motivi del calo, porta spesso a vendere nel punto peggiore.' },
      { t: 'Raddoppiare: utili record, il mercato sbaglia', ok: false, f: 'Gli utili passati sono già noti: ignorare il segnale sul futuro non è una strategia.' },
    ] },
    { s: 'Fabio, 40 anni, vuole aprire una posizione con un ordine a mercato un secondo prima dell’annuncio della BCE, per “prendere il movimento”.', q: 'Cosa gli suggeriresti?', o: [
      { t: 'Evitare ordini a mercato nei secondi della notizia', ok: true, f: 'Intorno all’annuncio lo spread si allarga e il prezzo salta: l’ordine potrebbe essere eseguito molto lontano dal prezzo visto a schermo.' },
      { t: 'Usare la massima leva per sfruttarlo', ok: false, f: 'Più leva in un momento di massima incertezza significa rischiare molto su un evento imprevedibile.' },
      { t: 'Comprare: le decisioni BCE fanno sempre salire', ok: false, f: 'La reazione dipende dalla sorpresa rispetto alle attese e dai segnali sul futuro, non dalla riunione in sé.' },
    ] },
    { s: 'Elena, 55 anni, pensa: “Tutti dicono che arriverà una recessione. Venderò le azioni quando il PIL uscirà negativo”.', q: 'Cosa c’è di debole nel suo piano?', o: [
      { t: 'Quando il dato esce, il mercato l’ha già anticipato', ok: true, f: 'La borsa sconta le attese: spesso scende prima del dato e a volte risale proprio quando esce. Meglio un’allocazione adatta al rischio già da ora.' },
      { t: 'Niente: il PIL è il segnale migliore per vendere', ok: false, f: 'Il PIL esce in ritardo rispetto ai prezzi: usarlo come segnale porta a vendere spesso dopo la maggior parte del calo.' },
      { t: 'Dovrebbe vendere solo se il PIL scende del 10%', ok: false, f: 'Cambiare soglia non risolve il problema: il dato arriva comunque dopo che il mercato si è mosso.' },
    ] },
  ],
  tip: 'Prima di reagire a una notizia chiediti: era attesa? Quanto si discosta dal consenso? Cosa dice sul futuro? Se non sai rispondere, probabilmente non hai un vantaggio.',
});
