FQC(81, {
  intro: 'La leva ti fa muovere più capitale di quello che hai e moltiplica guadagni e perdite. Scopri margine, margin call e liquidazione.',
  cards: [
    { t: 'Cos’è la leva', x: 'Con la leva controlli una posizione più grande del capitale che versi, usando denaro preso a prestito o un deposito di garanzia. Il rapporto tra esposizione e capitale proprio misura quanta leva stai usando.', v: { k: 'formula', f: 'Leva = Esposizione ÷ Capitale proprio', n: 'Es.: posizione da 10.000 € con 2.000 € propri = leva 5' } },
    { t: 'Un −4% con leve diverse', x: 'Con leva 5 un movimento del 4% del sottostante diventa circa il 20% sul tuo capitale, in guadagno o in perdita. Interessi e costi, inoltre, si calcolano sull’intera esposizione.', v: { k: 'bars', d: [['Senza leva', -4], ['Leva 2', -8], ['Leva 5', -20], ['Leva 10', -40]], u: '%' } },
    { t: 'Margine iniziale e di mantenimento', x: 'Il margine iniziale è la garanzia da versare per aprire la posizione; il margine di mantenimento è il capitale minimo che deve restare sul conto per tenerla aperta. Sotto quella soglia scatta la richiesta di reintegro.', v: { k: 'vs', a: ['Margine iniziale', 'Serve per aprire la posizione'], b: ['Margine di mantenimento', 'Soglia minima per tenerla aperta'] } },
    { t: 'La margin call', x: 'Quando le perdite erodono il capitale sotto la soglia, il broker ti chiede di versare fondi o ridurre la posizione. Se non lo fai in tempo, o se il mercato corre troppo, chiude lui le posizioni al posto tuo.', v: { k: 'steps', s: ['Il prezzo va contro di te', 'Il capitale scende sotto il mantenimento', 'Margin call: versi o riduci', 'Se non agisci: liquidazione'] } },
    { t: 'Liquidazione forzata', x: 'Il broker chiude al primo prezzo disponibile, spesso nel momento peggiore. In mercati veloci o con un gap di apertura la chiusura può avvenire molto sotto la soglia prevista e la perdita supera quella che avevi stimato.', v: { k: 'stat', n: '−100%', l: 'capitale proprio perso con leva 10 se il sottostante cala del 10%' } },
    { t: 'Il costo nascosto della leva', x: 'Il denaro preso a prestito costa: interessi sul margine o finanziamento overnight maturano ogni giorno sull’importo finanziato. Tenere a lungo una posizione a leva erode il risultato anche se il prezzo resta fermo.', v: { k: 'icons', d: [['💸', 'Interessi sul prestito'], ['📉', 'Perdite amplificate'], ['⏰', 'Costi che maturano ogni giorno']] } },
  ],
  terms: [
    ['Leva finanziaria', 'Rapporto tra l’esposizione complessiva di una posizione e il capitale proprio impiegato.'],
    ['Esposizione', 'Valore complessivo della posizione sul mercato, a prescindere da quanto capitale hai versato.'],
    ['Margine iniziale', 'Garanzia minima richiesta dall’intermediario per aprire una posizione a leva.'],
    ['Margine di mantenimento', 'Livello minimo di capitale sul conto sotto il quale scatta la richiesta di reintegro.'],
    ['Margin call', 'Richiesta del broker di versare fondi o ridurre le posizioni per ripristinare le garanzie.'],
    ['Liquidazione forzata', 'Chiusura delle posizioni decisa dal broker quando le garanzie non sono più sufficienti.'],
    ['Conto a margine', 'Conto che consente di comprare strumenti finanziari con credito concesso dall’intermediario.'],
    ['Equity del conto', 'Valore del conto inclusi guadagni e perdite non realizzati: la parte che è davvero tua.'],
  ],
  tf: [
    ['Con leva 5, un calo del 20% del sottostante azzera il capitale proprio investito nella posizione.', true, 'Perdita = 20% × 5 = 100% del capitale proprio, ancora prima di contare interessi e commissioni.'],
    ['La leva aumenta il rendimento atteso senza aumentare il rischio.', false, 'La leva moltiplica nella stessa misura guadagni e perdite: il rischio cresce almeno quanto il rendimento potenziale.'],
    ['Il margine è una commissione che il broker trattiene definitivamente.', false, 'Il margine è una garanzia: resta tuo, ma serve a coprire le perdite. Commissioni e interessi sono costi separati.'],
    ['Una margin call può arrivare anche se la tua previsione si rivelerà giusta nel lungo periodo.', true, 'Conta il prezzo di oggi: se le perdite intaccano il margine devi reintegrare, anche se poi il mercato ti darà ragione.'],
    ['Con un forte gap di apertura, la liquidazione può avvenire a un prezzo molto peggiore della soglia di margine.', true, 'La chiusura avviene al primo prezzo disponibile: se il mercato salta un livello, la perdita supera quella prevista.'],
    ['Se non rispondi alla margin call, il broker deve chiedere il tuo consenso prima di chiudere le posizioni.', false, 'Il contratto di norma autorizza l’intermediario a liquidare senza ulteriore consenso per proteggere le garanzie.'],
    ['Il costo di finanziamento si calcola sulla parte presa in prestito, che può essere molto più grande del tuo capitale.', true, 'Con leva 5 prendi in prestito 4 volte il tuo capitale: anche un tasso modesto pesa molto sul risultato.'],
    ['A parità di movimento del prezzo, una leva più bassa rende meno probabile una margin call.', true, 'Con meno debito il capitale proprio assorbe movimenti più ampi prima di scendere sotto la soglia di mantenimento.'],
    ['Con leva 2, un rialzo del 10% del sottostante vale circa +20% sul capitale proprio, al lordo dei costi.', true, 'L’esposizione è il doppio del capitale: il 10% dell’esposizione equivale al 20% del capitale, prima di interessi e commissioni.'],
    ['La leva è lo strumento giusto per recuperare in fretta le perdite subite.', false, 'È un errore classico: aumentare la leva dopo una perdita accresce il rischio proprio quando il capitale è già ridotto.'],
  ],
  mcq: [
    { q: 'Hai 5.000 € e apri una posizione da 25.000 €. Qual è la leva?', a: '5', w: ['2,5', '20', '0,2'], e: 'Leva = esposizione ÷ capitale proprio = 25.000 ÷ 5.000 = 5. Ogni 1% del sottostante vale circa il 5% del tuo capitale.' },
    { q: 'Cosa succede di solito quando l’equity del conto scende sotto il margine di mantenimento?', a: 'Ricevi una margin call', w: ['Il broker sospende gli interessi', 'La leva torna da sola a 1', 'Le perdite vengono congelate'], e: 'Il broker chiede di reintegrare le garanzie; se non lo fai può chiudere le posizioni.' },
    { q: 'Con leva 10, di quanto deve scendere il sottostante per azzerare il capitale proprio, ignorando i costi?', a: 'Del 10%', w: ['Dell’1%', 'Del 50%', 'Del 100%'], e: 'Soglia di azzeramento ≈ 100% ÷ leva = 100% ÷ 10 = 10%. Con i costi basta anche meno.' },
    { q: 'Perché la leva è pericolosa anche se nel lungo periodo il mercato sale?', a: 'Un calo temporaneo può farti liquidare prima del recupero', w: ['I guadagni ottenuti con la leva sono esclusi da ogni tassazione', 'La leva riduce i rendimenti quando i mercati sono al rialzo', 'Il margine viene restituito solo dopo dieci anni di detenzione'], e: 'La margin call guarda al prezzo di oggi: un ribasso intermedio può liquidarti e trasformare una perdita temporanea in definitiva.' },
    { q: 'Quale scelta riduce di più il rischio di liquidazione forzata?', a: 'Usare una leva bassa e tenere liquidità libera sul conto', w: ['Aumentare la posizione dopo ogni perdita', 'Tenere il conto esattamente al margine minimo', 'Aprire più posizioni a leva su titoli molto simili tra loro'], e: 'Meno leva e più capitale libero significano più spazio prima di toccare la soglia di mantenimento.' },
    { q: 'Il margine depositato presso il broker è…', a: 'una garanzia a copertura delle perdite', w: ['una commissione per aprire l’ordine', 'un premio che non viene restituito', 'un interesse pagato in anticipo sul prestito ricevuto'], e: 'Il margine resta tuo finché non viene consumato dalle perdite; i costi della leva sono interessi e commissioni.' },
    { q: 'Un errore comune di chi usa la leva è…', a: 'dimensionare la posizione sul margine disponibile', w: ['tenere liquidità libera sul conto', 'calcolare la perdita massima accettabile prima di entrare', 'controllare il costo del finanziamento'], e: 'Il margine dice quanto puoi aprire, non quanto dovresti: la dimensione va decisa su quanto sei disposto a perdere.' },
    { q: 'Tieni per mesi una posizione con leva 3 e il prezzo finisce invariato. Qual è l’esito più probabile?', a: 'Una perdita dovuta ai costi di finanziamento', w: ['Un pareggio esatto, perché il prezzo è uguale', 'Un guadagno dovuto all’effetto leva', 'Un rimborso degli interessi da parte del broker'], e: 'Gli interessi maturano ogni giorno sull’importo finanziato: con il prezzo fermo il conto scende comunque.' },
  ],
  fill: [
    { s: 'La ___ è la richiesta del broker di reintegrare le garanzie dopo le perdite.', a: 'margin call', w: ['cedola', 'stop loss', 'rollover'] },
    { s: 'Il margine di ___ è la soglia minima di capitale che deve restare sul conto.', a: 'mantenimento', w: ['apertura', 'rendimento', 'profitto'] },
    { s: 'Con leva 4, un ribasso del 5% del sottostante produce una perdita di circa il ___ del capitale proprio.', a: '20%', w: ['5%', '9%', '1,25%'] },
    { s: 'Se non reintegri il margine, il broker può procedere alla ___ forzata delle posizioni.', a: 'liquidazione', w: ['capitalizzazione', 'diversificazione', 'conversione'] },
    { s: 'La leva amplifica nella stessa misura guadagni e ___.', a: 'perdite', w: ['dividendi', 'cedole', 'rimborsi'] },
  ],
  order: [
    { q: 'Ordina gli eventi di una posizione a leva che va male', i: ['Apertura con il margine iniziale', 'Il prezzo si muove contro', 'L’equity scende sotto il mantenimento', 'Arriva la margin call', 'Liquidazione forzata'], e: 'La margin call è l’ultimo avviso: se non reintegri o riduci, il broker chiude le posizioni.' },
    { q: 'Con lo stesso capitale di 2.000 €, ordina dalla leva più bassa alla più alta', i: ['Posizione da 2.000 €', 'Posizione da 4.000 €', 'Posizione da 10.000 €', 'Posizione da 40.000 €'], e: 'Leva 1, 2, 5 e 20: a parità di capitale, più grande è l’esposizione, più alta è la leva e più vicina la liquidazione.' },
  ],
  cat: [
    { q: 'Riduce o aumenta il rischio di margin call?', g: [['Riduce', ['Leva più bassa', 'Liquidità libera sul conto', 'Posizione più piccola']], ['Aumenta', ['Mediare al ribasso a leva', 'Usare tutto il margine disponibile', 'Sottostante molto volatile']]] },
    { q: 'Garanzia o costo?', g: [['Garanzia (resta tua se non perdi)', ['Margine iniziale', 'Margine di mantenimento', 'Versamento dopo una margin call']], ['Costo (lo paghi comunque)', ['Interessi sul prestito', 'Commissioni di negoziazione', 'Finanziamento overnight']]] },
  ],
  scen: [
    { s: 'Giulia, 34 anni, ha aperto con 5.000 € una posizione a leva 4 su un’azione. Il titolo scende del 15%: ha già perso circa 3.000 € e il broker le invia una margin call.', q: 'Cosa fa?', o: [
      { t: 'Riduce la posizione per rientrare nei margini e rivede il rischio', ok: true, f: 'Accetta una perdita controllata e torna a una leva sostenibile, senza mettere in gioco altri risparmi.' },
      { t: 'Versa il fondo di emergenza per non chiudere in perdita', ok: false, f: 'Trasforma un errore di trading in un problema finanziario: il fondo di emergenza non serve a difendere una posizione a leva.' },
      { t: 'Ignora la richiesta, convinta che il titolo risalirà', ok: false, f: 'Il broker può liquidare in automatico al prezzo peggiore: la convinzione sul futuro non ferma la margin call.' },
    ] },
    { s: 'Marco, 45 anni, investe ogni mese in un ETF azionario globale per la pensione. Legge che con un conto a margine potrebbe usare leva 2 per vent’anni e raddoppiare i risultati.', q: 'Cosa decide?', o: [
      { t: 'Usa leva 2: in vent’anni il mercato sale comunque', ok: false, f: 'Il mercato può salire nel lungo periodo, ma la liquidazione arriva durante il ribasso e non aspetta il recupero.' },
      { t: 'Resta senza leva: un ribasso del 50% lo azzererebbe', ok: true, f: 'Le borse hanno già avuto cali del 50% e oltre: con leva 2 ne basterebbe uno per perdere tutto e uscire dal mercato.' },
      { t: 'Usa leva 5 solo nei mesi in cui il mercato è forte', ok: false, f: 'Nessuno sa in anticipo quali mesi saranno forti: più leva e market timing aumentano il rischio, non lo riducono.' },
    ] },
    { s: 'Sara, 29 anni, ha 3.000 € e un’idea su un titolo. Il broker le permette di aprire posizioni fino a 5 volte il capitale disponibile.', q: 'Come imposta l’operazione?', o: [
      { t: 'Apre la posizione massima: se ha ragione guadagna cinque volte tanto', ok: false, f: 'Se ha torto perde cinque volte tanto: un calo del 20% le azzererebbe il conto.' },
      { t: 'Apre al massimo e promette a sé stessa di controllare il grafico ogni ora', ok: false, f: 'Guardare spesso il grafico non riduce il rischio: in un gap o di notte non potrà reagire in tempo.' },
      { t: 'Decide prima quanto è disposta a perdere e dimensiona la posizione su quello', ok: true, f: 'La dimensione si sceglie partendo dalla perdita accettabile, non dal massimo consentito dal broker.' },
    ] },
    { s: 'Paolo, 61 anni, tiene da otto mesi una posizione a leva 3 su un indice. Il prezzo è quasi uguale a quello di ingresso, ma il conto è in rosso.', q: 'Come interpreta la situazione?', o: [
      { t: 'È un errore del broker: chiede il rimborso della differenza', ok: false, f: 'Non è un errore: gli interessi sul finanziamento sono previsti dal contratto e indicati tra i costi.' },
      { t: 'Sono i costi di finanziamento accumulati: valuta se la sua idea giustifica ancora quel costo', ok: true, f: 'Il tempo ha un prezzo nelle posizioni a leva: ogni giorno paga interessi sull’importo finanziato.' },
      { t: 'Aumenta la leva per recuperare più in fretta i costi', ok: false, f: 'Più leva significa più interessi e più rischio: rincorrere le perdite peggiora la situazione.' },
    ] },
  ],
  tip: 'Prima di usare la leva calcola di quanto deve muoversi il prezzo per azzerarti (100% ÷ leva): se è un movimento plausibile, la posizione è troppo grande.',
});
