FQC(82, {
  intro: 'Con la vendita allo scoperto guadagni se un titolo scende. Scopri prestito titoli, costi, perdita potenzialmente illimitata e short squeeze.',
  cards: [
    { t: 'Come funziona lo short', x: 'Vendi oggi titoli che non possiedi, presi in prestito tramite il broker, e li ricompri più avanti per restituirli. Se nel frattempo il prezzo è sceso guadagni la differenza; se è salito, perdi.', v: { k: 'steps', s: ['Prendi in prestito le azioni', 'Le vendi sul mercato', 'Le ricompri più tardi', 'Le restituisci al prestatore'] } },
    { t: 'Guadagno limitato, perdita illimitata', x: 'Un titolo può al massimo azzerarsi: chi è short guadagna al massimo il prezzo incassato alla vendita. Il prezzo però non ha un tetto, quindi la perdita dello short può superare di molto il capitale impegnato.', v: { k: 'vs', a: ['Long', 'Perdita massima 100%, guadagno senza tetto'], b: ['Short', 'Guadagno massimo 100%, perdita senza tetto'] } },
    { t: 'Il calcolo del risultato', x: 'Il risultato è la differenza tra prezzo di vendita e prezzo di riacquisto, moltiplicata per il numero di azioni, al netto di commissioni, costo del prestito ed eventuali dividendi da rimborsare.', v: { k: 'formula', f: 'Risultato short = (Prezzo di vendita − Prezzo di riacquisto) × Quantità − costi', n: 'Es.: vendi 100 azioni a 50 € e ricompri a 40 € → +1.000 € lordi' } },
    { t: 'I costi dello short', x: 'Chi è short paga una commissione per il prestito, che sale molto per i titoli difficili da reperire, versa al prestatore l’equivalente dei dividendi staccati e deve tenere un margine a garanzia.', v: { k: 'icons', d: [['🏷️', 'Commissione di prestito titoli'], ['💶', 'Dividendi da compensare'], ['🔒', 'Margine a garanzia']] } },
    { t: 'Lo short squeeze (esempio)', x: 'Se un titolo molto venduto allo scoperto inizia a salire, gli short ricomprano per limitare le perdite o per le margin call. Questi acquisti forzati spingono il prezzo ancora più su, in una spirale.', v: { k: 'bars', d: [['Giorno 1', 20], ['Giorno 2', 26], ['Giorno 3', 38], ['Giorno 4', 60]], u: '€' } },
    { t: 'Regole e trasparenza in UE', x: 'Il regolamento europeo sulle vendite allo scoperto vieta lo short su azioni senza aver reperito i titoli (naked short) e impone di notificare le posizioni corte nette rilevanti. In situazioni di crisi CONSOB ed ESMA possono imporre divieti temporanei.', v: { k: 'stat', n: '0,5%', l: 'del capitale: soglia oltre cui una posizione corta netta su azioni UE diventa pubblica' } },
  ],
  terms: [
    ['Vendita allo scoperto', 'Vendita di titoli presi in prestito con l’obiettivo di ricomprarli in seguito a un prezzo più basso.'],
    ['Posizione corta', 'Esposizione che guadagna quando il prezzo dello strumento scende; detta anche short.'],
    ['Prestito titoli', 'Cessione temporanea di azioni a chi le richiede, in cambio di una commissione e di garanzie.'],
    ['Commissione di prestito', 'Costo periodico pagato da chi prende titoli in prestito; sale quando i titoli sono scarsi.'],
    ['Short squeeze', 'Rialzo violento alimentato dagli acquisti forzati di chi deve chiudere posizioni corte.'],
    ['Naked short selling', 'Vendita allo scoperto senza aver prima preso in prestito o reperito i titoli.'],
    ['Short interest', 'Quota di azioni vendute allo scoperto rispetto a quelle in circolazione o al flottante.'],
    ['Recall', 'Richiesta del prestatore di riavere i titoli, che può costringere a chiudere la posizione corta.'],
  ],
  tf: [
    ['Uno short guadagna se il titolo scende più di quanto costano prestito e dividendi da compensare.', true, 'Il calo del prezzo deve coprire commissioni, costo del prestito e dividendi versati al prestatore.'],
    ['La perdita massima di una vendita allo scoperto è pari al margine versato.', false, 'Il prezzo può salire senza limite: la perdita può superare il margine e richiedere nuovi versamenti.'],
    ['Se il titolo stacca un dividendo mentre sei short, devi versarne l’equivalente al prestatore.', true, 'Il prestatore non deve perdere il dividendo: chi è corto lo compensa, ed è un costo dello short.'],
    ['Un titolo con short interest molto alto è più esposto al rischio di short squeeze.', true, 'Molti venditori allo scoperto significano molti potenziali acquisti forzati se il prezzo comincia a salire.'],
    ['Vendere allo scoperto è sempre illegale perché fa crollare i prezzi.', false, 'È una pratica legale e regolata che contribuisce alla formazione dei prezzi; le autorità possono vietarla solo temporaneamente.'],
    ['Nell’UE la vendita allo scoperto di azioni senza aver reperito i titoli è vietata.', true, 'Il regolamento europeo richiede di aver preso in prestito i titoli o di avere un accordo che ne garantisca la disponibilità.'],
    ['Se un titolo venduto allo scoperto a 50 € sale a 75 €, la perdita è del 25%.', false, 'Perdi 25 € su 50 € incassati: il 50% del valore iniziale della posizione, prima dei costi.'],
    ['La commissione di prestito è uguale per tutti i titoli.', false, 'Dipende da domanda e offerta di titoli da prestare: per azioni scarse o molto vendute allo scoperto può diventare molto alta.'],
    ['Il prestatore può richiamare i titoli e costringerti a chiudere lo short in un momento sfavorevole.', true, 'Con il recall i titoli vanno restituiti: se il broker non li trova altrove, la posizione viene chiusa.'],
    ['Tenere uno short per anni conviene perché nel lungo periodo le borse tendono a scendere.', false, 'Storicamente gli indici azionari sono cresciuti nel lungo periodo: lo short lavora contro questa tendenza e paga costi continui.'],
  ],
  mcq: [
    { q: 'Vendi allo scoperto 200 azioni a 30 € e le ricompri a 24 €. Qual è il risultato lordo?', a: '+1.200 €', w: ['−1.200 €', '+600 €', '+4.800 €'], e: '(30 − 24) × 200 = 1.200 € di guadagno, prima di commissioni, costo del prestito ed eventuali dividendi.' },
    { q: 'Perché la perdita di uno short è teoricamente illimitata?', a: 'Il prezzo di un titolo non ha un limite massimo', w: ['Il broker applica sempre una leva infinita', 'Le azioni possono avere un prezzo negativo', 'I dividendi da rimborsare al prestatore crescono ogni anno'], e: 'Un titolo può salire di qualunque percentuale: chi deve ricomprarlo non ha un tetto alla perdita.' },
    { q: 'Cosa alimenta uno short squeeze?', a: 'Gli acquisti forzati di chi deve chiudere posizioni corte', w: ['Le vendite dei grandi azionisti di lungo periodo', 'Il taglio dei dividendi annunciato a sorpresa dalla società', 'La riduzione dello short interest nei mesi precedenti'], e: 'Ogni short che ricompra aggiunge domanda: il prezzo sale, altri short sono costretti a ricomprare e la spirale si autoalimenta.' },
    { q: 'Quale costo è tipico di chi è short e non di chi compra azioni senza leva?', a: 'La commissione per il prestito dei titoli', w: ['La commissione di negoziazione', 'L’imposta sulle plusvalenze realizzate alla chiusura', 'Lo spread denaro-lettera'], e: 'Commissioni, spread e tasse riguardano entrambi; il costo del prestito (e la compensazione dei dividendi) è specifico dello short.' },
    { q: 'Un titolo ha uno short interest pari al 40% del flottante e inizia a salire forte. Qual è il rischio principale per chi è short?', a: 'Uno short squeeze con rialzi improvvisi', w: ['Un calo improvviso del costo del prestito titoli', 'Un aumento dei dividendi da incassare', 'Una riduzione della volatilità'], e: 'Con tanti short sullo stesso titolo, l’uscita è stretta: i riacquisti forzati possono far esplodere il prezzo.' },
    { q: 'Cosa prevede il regolamento UE per le posizioni corte nette rilevanti su azioni?', a: 'Notifica all’autorità e, oltre una soglia, pubblicazione', w: ['Il permesso di aprirle riservato alle sole banche centrali', 'Una durata massima di un giorno di borsa', 'L’esenzione da qualsiasi obbligo di garanzia'], e: 'Le posizioni sopra lo 0,1% del capitale vanno notificate all’autorità; dallo 0,5% diventano pubbliche.' },
    { q: 'Un errore comune di chi apre uno short è…', a: 'non fissare in anticipo un limite di perdita', w: ['considerare il costo del prestito titoli nel calcolo', 'controllare le date di stacco dei dividendi', 'verificare la liquidità del titolo shortato'], e: 'Senza un limite, una perdita potenzialmente illimitata può crescere oltre ogni previsione: la speranza non è una strategia di uscita.' },
    { q: 'Vai short su un titolo a 40 € e il prezzo sale a 100 €. Quanto perdi rispetto al prezzo di vendita?', a: '150%', w: ['60%', '100%', '40%'], e: 'Perdi 60 € per azione su 40 € incassati, cioè il 150%: uno short può perdere più del 100%, un acquisto senza leva no.' },
  ],
  fill: [
    { s: 'Per vendere allo scoperto devi prima prendere in ___ i titoli tramite il broker.', a: 'prestito', w: ['custodia', 'gestione', 'deposito'] },
    { s: 'Un rialzo violento causato dagli acquisti forzati dei venditori allo scoperto si chiama short ___.', a: 'squeeze', w: ['interest', 'selling', 'position'] },
    { s: 'Chi è short deve compensare il prestatore per i ___ staccati durante il prestito.', a: 'dividendi', w: ['interessi passivi', 'margini iniziali', 'diritti di voto'] },
    { s: 'Nello short il guadagno massimo è limitato, mentre la ___ è teoricamente illimitata.', a: 'perdita', w: ['commissione', 'cedola', 'liquidità'] },
    { s: 'Il ___ short selling, cioè vendere senza aver reperito i titoli, è vietato sulle azioni nell’UE.', a: 'naked', w: ['covered', 'squeeze', 'long'] },
  ],
  order: [
    { q: 'Ordina i passaggi di una vendita allo scoperto', i: ['Prendi in prestito i titoli', 'Vendi i titoli sul mercato', 'Il prezzo si muove', 'Ricompri i titoli', 'Restituisci i titoli al prestatore'], e: 'Prima si vende, poi si ricompra: è l’ordine inverso rispetto a un acquisto, e i titoli vanno sempre restituiti.' },
    { q: 'Ordina le fasi di uno short squeeze', i: ['Molti investitori sono short sul titolo', 'Una notizia positiva fa salire il prezzo', 'Gli short subiscono perdite e margin call', 'Gli short ricomprano in massa', 'Il prezzo sale ancora più in fretta'], e: 'I riacquisti forzati sono essi stessi domanda: per questo lo squeeze si autoalimenta finché gli short non sono usciti.' },
  ],
  cat: [
    { q: 'Favorevole o sfavorevole per chi è short?', g: [['Favorevole', ['Il titolo cala dopo la trimestrale', 'Il costo del prestito resta basso', 'Il mercato scende in modo ordinato']], ['Sfavorevole', ['Forte aumento della commissione di prestito', 'Offerta pubblica di acquisto sul titolo', 'Recall dei titoli prestati']]] },
    { q: 'Posizione long o short?', g: [['Long', ['Guadagna se il prezzo sale', 'Perdita massima pari all’investito (senza leva)', 'Incassa i dividendi']], ['Short', ['Guadagna se il prezzo scende', 'Perdita teoricamente illimitata', 'Compensa i dividendi al prestatore']]] },
  ],
  scen: [
    { s: 'Luca, 38 anni, è short su un titolo per 10.000 €. In due giorni il titolo sale del 30%, lo short interest è altissimo e sui social si parla di squeeze.', q: 'Cosa fa?', o: [
      { t: 'Raddoppia lo short perché ora il titolo è ancora più sopravvalutato', ok: false, f: 'Il mercato può restare irrazionale più a lungo di quanto tu resti solvibile: raddoppiare durante uno squeeze moltiplica il rischio.' },
      { t: 'Aspetta senza fare nulla: prima o poi i fondamentali vinceranno', ok: false, f: 'Forse sì, ma intanto margin call e liquidazione possono chiudere la posizione ai massimi.' },
      { t: 'Chiude o riduce lo short accettando la perdita, come previsto dal suo limite', ok: true, f: 'Rispetta il piano: uno squeeze può spingere il prezzo molto oltre ogni valutazione ragionevole, e la perdita non ha tetto.' },
    ] },
    { s: 'Elena, 45 anni, pensa che un’azienda abbia conti deboli e vuole andare short. Il broker le segnala che il titolo è difficile da reperire e la commissione di prestito è molto alta.', q: 'Come valuta l’operazione?', o: [
      { t: 'Inserisce il costo del prestito nel risultato atteso e riduce la dimensione o rinuncia', ok: true, f: 'Un costo di prestito alto può mangiarsi il guadagno atteso, e segnala che molti sono già short sullo stesso titolo.' },
      { t: 'Ignora la commissione: conta solo il calo del prezzo', ok: false, f: 'La commissione matura ogni giorno: se il calo tarda ad arrivare, può trasformare un’idea giusta in una perdita.' },
      { t: 'Interpreta la commissione alta come prova che il titolo crollerà', ok: false, f: 'Indica soprattutto che lo short è affollato: è anche un segnale di rischio squeeze, non una garanzia di ribasso.' },
    ] },
    { s: 'Andrea, 26 anni, vede che un titolo è salito del 300% in un mese. Vuole andare short con tutto il suo capitale perché, dice, non può durare.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Va short con tutto il capitale per massimizzare il guadagno', ok: false, f: 'Se il titolo raddoppia ancora, perde l’intero capitale e oltre: «non può durare» non è un piano di gestione del rischio.' },
      { t: 'Non apre la posizione, o la apre piccola con un limite di perdita definito', ok: true, f: 'Un titolo salito molto può salire ancora: la dimensione piccola e lo stop pianificato proteggono dal rischio illimitato.' },
      { t: 'Va short con leva per guadagnare di più dal crollo atteso', ok: false, f: 'La leva avvicina la liquidazione: anche se il crollo arrivasse, potrebbe essere già stato chiuso in perdita.' },
    ] },
    { s: 'Francesca, 50 anni, è short da tre mesi su un titolo. All’improvviso la società riceve un’offerta pubblica di acquisto con un premio del 40% sul prezzo di borsa.', q: 'Cosa le conviene fare?', o: [
      { t: 'Restare short perché molte offerte pubbliche falliscono', ok: false, f: 'Alcune falliscono, ma scommetterci significa rischiare altre perdite, magari con un’offerta concorrente più alta.' },
      { t: 'Aumentare lo short sperando che l’offerta venga ritirata', ok: false, f: 'Raddoppiare su un evento binario e incerto è speculazione pura, con perdita potenziale ancora più grande.' },
      { t: 'Chiudere lo short: il prezzo tenderà ad allinearsi a quello dell’offerta', ok: true, f: 'L’OPA cambia lo scenario: la tesi ribassista non regge più e restare short espone a ulteriori rialzi o a rilanci dell’offerta.' },
    ] },
  ],
  tip: 'Prima di andare short fissa la perdita massima che accetti e controlla costo del prestito, dividendi in arrivo e short interest: lo short punisce chi spera.',
});
