FQC(83, {
  intro: 'Un future è l’impegno a comprare o vendere un sottostante a una data futura, a un prezzo fissato oggi. Scopri margini, mark-to-market, hedging e rollover.',
  cards: [
    { t: 'Un contratto standardizzato', x: 'Il future si negozia in borsa con caratteristiche fissate: sottostante, dimensione, scadenza e modalità di liquidazione. Una controparte centrale si interpone tra compratore e venditore e garantisce i pagamenti.', v: { k: 'icons', d: [['📦', 'Sottostante'], ['📅', 'Scadenza'], ['📏', 'Dimensione del contratto'], ['🏛️', 'Controparte centrale']] } },
    { t: 'Un obbligo per entrambe le parti', x: 'Chi è lungo si impegna a comprare, chi è corto a vendere: nessuno dei due può tirarsi indietro, a differenza di un’opzione. Il guadagno di una parte è esattamente la perdita dell’altra.', v: { k: 'vs', a: ['Long future', 'Guadagna se il prezzo sale'], b: ['Short future', 'Guadagna se il prezzo scende'] } },
    { t: 'Nozionale e leva', x: 'Per aprire versi solo il margine iniziale, una piccola frazione del valore nozionale: per questo il future è uno strumento a leva. Il rischio si misura sul nozionale, e le perdite possono superare il margine versato.', v: { k: 'formula', f: 'Nozionale = Prezzo del future × Valore del punto', n: 'Es.: 30.000 punti × 5 € a punto = 150.000 € di esposizione' } },
    { t: 'Mark-to-market giornaliero', x: 'Ogni giorno la controparte centrale rivaluta le posizioni al prezzo di regolamento: i guadagni vengono accreditati e le perdite addebitate in contanti come margine di variazione. Non si aspetta la scadenza.', v: { k: 'steps', s: ['Chiusura della seduta', 'Prezzo di regolamento', 'Calcolo di guadagni e perdite', 'Margine di variazione regolato'] } },
    { t: 'Hedging: coprirsi dal rischio', x: 'Chi possiede azioni può vendere future sull’indice per compensare un ribasso: la perdita sul portafoglio è bilanciata in gran parte dal guadagno sul future. La copertura è raramente perfetta (rischio base).', v: { k: 'bars', d: [['Portafoglio azionario', -10000], ['Short future sull’indice', 9500], ['Risultato netto', -500]], u: '€' } },
    { t: 'Scadenza e rollover', x: 'Per restare esposto oltre la scadenza chiudi il contratto in scadenza e apri il successivo: è il rollover. Costi di negoziazione e differenza di prezzo tra le scadenze (contango o backwardation) incidono sul risultato.', v: { k: 'stat', n: '4', l: 'scadenze trimestrali all’anno per molti future su indici: marzo, giugno, settembre, dicembre' } },
  ],
  terms: [
    ['Future', 'Contratto standardizzato che obbliga a comprare o vendere un sottostante a prezzo e data fissati.'],
    ['Sottostante', 'Attività a cui si riferisce il contratto: indice, materia prima, valuta, tasso o titolo.'],
    ['Margine iniziale', 'Deposito richiesto per aprire una posizione, fissato dalla controparte centrale e dal broker.'],
    ['Margine di variazione', 'Somma regolata ogni giorno in contanti per coprire guadagni e perdite della posizione.'],
    ['Mark-to-market', 'Rivalutazione giornaliera delle posizioni al prezzo di regolamento di fine seduta.'],
    ['Controparte centrale', 'Soggetto che si interpone tra le parti di ogni contratto e ne garantisce l’esecuzione.'],
    ['Rollover', 'Chiusura del contratto in scadenza e apertura di quello successivo per mantenere l’esposizione.'],
    ['Contango', 'Situazione in cui i contratti a scadenza più lontana quotano sopra il prezzo a pronti.'],
  ],
  tf: [
    ['Chi compra un future ha il diritto, ma non l’obbligo, di acquistare il sottostante a scadenza.', false, 'Questo vale per le opzioni: il future vincola entrambe le parti, che devono regolare il contratto a scadenza.'],
    ['Con il mark-to-market, guadagni e perdite sui future vengono regolati ogni giorno e non solo a scadenza.', true, 'La controparte centrale accredita o addebita ogni giorno il margine di variazione in base al prezzo di regolamento.'],
    ['Su un future la perdita massima è pari al margine iniziale versato.', false, 'Il margine è solo un deposito: se il prezzo va contro di te devi versare altro margine di variazione, senza un tetto prefissato.'],
    ['Molti future su indici azionari si liquidano in contanti, senza consegna fisica.', true, 'Un indice non si può consegnare: a scadenza si regola la differenza tra prezzo del contratto e valore finale dell’indice.'],
    ['Un produttore che venderà grano tra sei mesi può usare i future per fissare oggi il prezzo di vendita.', true, 'Vendendo future si protegge da un calo del prezzo, rinunciando però al guadagno di un eventuale rialzo.'],
    ['In contango il future con scadenza più lontana quota sotto il prezzo a pronti.', false, 'È il contrario: in contango le scadenze lontane quotano sopra il prezzo a pronti; se quotano sotto si parla di backwardation.'],
    ['Avvicinandosi alla scadenza, il prezzo del future converge verso il prezzo a pronti.', true, 'A scadenza il future deve valere quanto il sottostante, altrimenti ci sarebbe un arbitraggio senza rischio.'],
    ['La controparte centrale elimina ogni rischio di perdita per chi negozia future.', false, 'Riduce il rischio che l’altra parte non paghi, ma non il rischio di mercato: le perdite dovute al prezzo restano tue.'],
    ['In una copertura con future puoi perdere sul future mentre il portafoglio coperto guadagna.', true, 'È la logica dell’hedging: rinunci a parte del rialzo per proteggerti dal ribasso. Non è un errore, è il costo della protezione.'],
    ['Se non fai rollover, la posizione in future resta aperta a tempo indeterminato.', false, 'Ogni future ha una scadenza: a quella data il contratto viene liquidato, quindi per restare esposto devi passare alla scadenza successiva.'],
  ],
  mcq: [
    { q: 'Un future sull’indice vale 5 € per punto e quota 30.000 punti. Qual è il valore nozionale di un contratto?', a: '150.000 €', w: ['30.000 €', '6.000 €', '35.000 €'], e: 'Nozionale = 30.000 × 5 € = 150.000 €. È su questo valore, non sul margine, che si misura il rischio.' },
    { q: 'Sei long di 1 future da 5 € a punto. Oggi il prezzo di regolamento scende di 200 punti. Cosa succede?', a: 'Ti vengono addebitati 1.000 €', w: ['Non succede nulla fino a scadenza', 'Ti vengono accreditati 1.000 €', 'Ti vengono addebitati 200 €'], e: '200 punti × 5 € = 1.000 € di perdita, regolata subito come margine di variazione con il mark-to-market.' },
    { q: 'Gestisci un portafoglio di azioni italiane e temi un calo nei prossimi mesi. Come puoi coprirti con i future?', a: 'Vendendo future sul FTSE MIB', w: ['Comprando future sul FTSE MIB', 'Facendo rollover dei future in scadenza', 'Aumentando il margine iniziale del conto'], e: 'Con lo short sul future, se l’indice scende il guadagno sul contratto compensa in parte la perdita delle azioni.' },
    { q: 'Cosa indica una situazione di backwardation?', a: 'Scadenze lontane quotate sotto il prezzo a pronti', w: ['Scadenze lontane quotate sopra il prezzo a pronti', 'Un contratto senza altre scadenze disponibili', 'Un contratto liquidato con consegna fisica'], e: 'In backwardation la curva dei future è inclinata verso il basso; in contango verso l’alto.' },
    { q: 'Perché il future è considerato uno strumento a leva?', a: 'Con un margine ridotto controlli un nozionale molto più grande', w: ['Il broker ti presta sempre il doppio del capitale che hai versato', 'Il suo prezzo si muove sempre più del sottostante', 'Il guadagno è garantito dalla controparte centrale'], e: 'Il margine è una frazione del nozionale: piccoli movimenti del sottostante producono grandi variazioni rispetto al capitale versato.' },
    { q: 'Cos’è il rischio base in una copertura con future?', a: 'Che future e portafoglio coperto non si muovano in parallelo', w: ['Che la borsa sospenda il contratto prima della sua scadenza naturale', 'Che il margine iniziale venga restituito in anticipo', 'Che il sottostante smetta del tutto di avere un prezzo'], e: 'Se il portafoglio non replica l’indice o il future prezza in modo diverso dal pronti, la copertura lascia un residuo.' },
    { q: 'Un errore comune di chi usa i future per la prima volta è…', a: 'guardare il margine e non il nozionale', w: ['controllare con cura la data di scadenza', 'calcolare il valore di un punto prima', 'verificare la liquidità del contratto scelto'], e: 'Il margine sembra piccolo, ma il rischio dipende dal nozionale: con pochi migliaia di euro puoi muovere un’esposizione da centinaia di migliaia.' },
    { q: 'Hai un future long con scadenza a marzo e vuoi restare esposto fino all’estate. Cosa fai?', a: 'Prima di marzo chiudi il contratto e apri quello di giugno', w: ['Aspetti: alla scadenza il contratto si rinnova in automatico', 'Apri un secondo future con la stessa scadenza di marzo', 'Versi più margine iniziale sul contratto di marzo'], e: 'È il rollover: i future non si rinnovano automaticamente. Considera costi e differenza di prezzo tra le due scadenze.' },
  ],
  fill: [
    { s: 'La rivalutazione giornaliera delle posizioni al prezzo di regolamento si chiama ___.', a: 'mark-to-market', w: ['rollover', 'hedging', 'contango'] },
    { s: 'Passare dal future in scadenza a quello successivo per mantenere l’esposizione si chiama ___.', a: 'rollover', w: ['arbitraggio', 'hedging', 'squeeze'] },
    { s: 'Usare i future per ridurre il rischio di una posizione già esistente si chiama ___.', a: 'hedging', w: ['scalping', 'leverage', 'contango'] },
    { s: 'Quando le scadenze lontane quotano sotto il prezzo a pronti, il mercato è in ___.', a: 'backwardation', w: ['contango', 'parità', 'arbitraggio'] },
    { s: 'La ___ centrale si interpone tra compratore e venditore e garantisce il buon fine dei contratti.', a: 'controparte', w: ['banca', 'società', 'agenzia'] },
  ],
  order: [
    { q: 'Ordina il ciclo di vita di una posizione in future', i: ['Versi il margine iniziale', 'Apri la posizione long o short', 'Regoli ogni giorno il margine di variazione', 'Prima della scadenza chiudi o fai rollover'], e: 'Il margine iniziale apre la posizione, il mark-to-market la accompagna ogni giorno, la scadenza impone una decisione.' },
    { q: 'Ordina i passaggi per coprire un portafoglio azionario con i future', i: ['Stimi il valore da proteggere', 'Calcoli il numero di contratti', 'Vendi i future sull’indice', 'Monitori margini e rischio base', 'Chiudi la copertura quando non serve più'], e: 'Il numero di contratti dipende dal valore da coprire diviso il nozionale di un contratto, corretto per quanto il portafoglio segue l’indice.' },
  ],
  cat: [
    { q: 'Hedging o speculazione?', g: [['Hedging', ['Un produttore di grano vende future sul grano', 'Un fondo vende future sull’indice per proteggere le azioni', 'Una compagnia aerea compra future sul carburante']], ['Speculazione', ['Compri future sul petrolio per puntare su un rialzo', 'Vendi future sull’indice senza avere azioni', 'Apri e chiudi future in giornata per trarne profitto']]] },
    { q: 'Accade ogni giorno o alla scadenza?', g: [['Ogni giorno', ['Mark-to-market', 'Regolamento del margine di variazione', 'Calcolo del prezzo di regolamento']], ['Alla scadenza', ['Liquidazione finale del contratto', 'Consegna fisica, se prevista', 'Prezzo del future pari al sottostante']]] },
  ],
  scen: [
    { s: 'Roberto, 55 anni, ha 300.000 € in azioni italiane e teme un forte calo nei prossimi due mesi. Non vuole vendere i titoli, su cui ha plusvalenze elevate.', q: 'Cosa valuta?', o: [
      { t: 'Comprare future sull’indice per aumentare l’esposizione', ok: false, f: 'Così raddoppia il rischio che vuole ridurre: se il mercato scende perde sia sulle azioni sia sui future.' },
      { t: 'Vendere future sull’indice per coprire il portafoglio, tenendo liquidità per i margini', ok: true, f: 'Protegge il valore senza vendere le azioni; deve però tenere liquidità per il margine di variazione se il mercato sale.' },
      { t: 'Vendere future per un nozionale doppio rispetto al portafoglio', ok: false, f: 'Non è più una copertura: metà della posizione è una scommessa al ribasso, con perdite se il mercato sale.' },
    ] },
    { s: 'Chiara, 31 anni, ha un conto da 10.000 €. Scopre che con circa 4.000 € di margine può aprire un future con un nozionale di 120.000 €.', q: 'Cosa fa?', o: [
      { t: 'Apre due contratti, perché il margine sul conto basta', ok: false, f: 'Il margine non misura il rischio: con 240.000 € di nozionale un calo del 4% le azzererebbe quasi il conto.' },
      { t: 'Apre un contratto e non guarda il conto fino alla scadenza', ok: false, f: 'Le perdite si regolano ogni giorno: potrebbe ricevere richieste di margine e liquidazioni molto prima della scadenza.' },
      { t: 'Rinuncia o usa un contratto mini, dopo aver calcolato quanto perde per ogni punto', ok: true, f: 'Un’esposizione 12 volte il conto è enorme: un movimento del 4% costerebbe circa la metà del suo capitale.' },
    ] },
    { s: 'Stefano, 47 anni, è long su un future sul petrolio in scadenza la prossima settimana e vuole restare esposto. Il contratto successivo quota più alto (contango).', q: 'Cosa deve sapere?', o: [
      { t: 'Che il rollover ha un costo e in contango il risultato può restare indietro rispetto al pronti', ok: true, f: 'Ricomprare ogni volta una scadenza più cara pesa sul rendimento nel tempo: è una delle ragioni per cui i future non replicano il prezzo a pronti.' },
      { t: 'Che il contratto si rinnova da solo senza costi', ok: false, f: 'Nessun rinnovo automatico: alcuni future prevedono la consegna fisica e il broker può chiudere d’ufficio prima della scadenza.' },
      { t: 'Che in contango il rollover genera sempre un guadagno', ok: false, f: 'In contango, per una posizione long, il rollover tende a pesare sul risultato, non ad aggiungere guadagni.' },
    ] },
    { s: 'Laura, 40 anni, è long su 1 future da 10 € a punto. In una settimana l’indice scende di 600 punti e il broker le chiede di reintegrare il margine.', q: 'Cosa fa?', o: [
      { t: 'Non versa nulla: le perdite si pagano solo a scadenza', ok: false, f: 'Falso: con il mark-to-market le perdite sono già state addebitate. Senza reintegro la posizione viene chiusa.' },
      { t: 'Valuta se ridurre la posizione: ha già perso 6.000 € e le perdite si regolano ogni giorno', ok: true, f: '600 × 10 € = 6.000 €: rivedere la dimensione evita che altre perdite giornaliere erodano il conto.' },
      { t: 'Apre un secondo contratto per mediare il prezzo', ok: false, f: 'Raddoppia l’esposizione proprio mentre il mercato le va contro: ogni punto ora vale 20 €.' },
    ] },
  ],
  tip: 'Prima di aprire un future calcola quanto vale un punto e quanto perderesti con un movimento avverso realistico: il rischio si misura sul nozionale, non sul margine.',
});
