FQC(84, {
  intro: 'Una call dà il diritto, non l’obbligo, di comprare un sottostante a un prezzo fissato. Scopri premio, strike, scadenza, break-even e rischi.',
  cards: [
    { t: 'Il diritto di comprare', x: 'Chi compra una call paga un premio e ottiene il diritto di acquistare il sottostante allo strike, entro o alla scadenza. Chi la vende incassa il premio ma si impegna a consegnare il sottostante se la call viene esercitata.', v: { k: 'vs', a: ['Compratore della call', 'Paga il premio, ha il diritto di comprare'], b: ['Venditore della call', 'Incassa il premio, ha l’obbligo di vendere'] } },
    { t: 'Gli elementi di una call', x: 'Lo strike è il prezzo a cui puoi comprare, la scadenza è la data limite, il premio è il prezzo dell’opzione. Sulle opzioni su azioni ogni contratto copre un lotto di titoli fissato dalla borsa.', v: { k: 'icons', d: [['🎯', 'Strike'], ['📅', 'Scadenza'], ['💰', 'Premio'], ['📦', 'Sottostante e lotto']] } },
    { t: 'Il risultato a scadenza', x: 'A scadenza la call vale la differenza tra prezzo del sottostante e strike, se positiva, altrimenti zero. Per sapere se hai guadagnato devi sottrarre il premio pagato.', v: { k: 'formula', f: 'Risultato call = max(0; S − K) − premio', n: 'Es.: K 50 €, premio 3 €, S 60 € → 10 − 3 = +7 € per azione' } },
    { t: 'Break-even = strike + premio', x: 'La call comprata guadagna a scadenza solo se il sottostante supera strike più premio. Sotto lo strike perdi l’intero premio, che è anche la perdita massima di chi compra. Esempio con strike 50 € e premio 3 €.', v: { k: 'bars', d: [['S = 45 €', -3], ['S = 50 €', -3], ['S = 53 €', 0], ['S = 60 €', 7]], u: '€' } },
    { t: 'In, at o out of the money', x: 'Con il sottostante a 50 €, una call strike 40 è in the money (ha valore intrinseco), strike 50 è at the money, strike 60 è out of the money: costa poco, ma serve un rialzo forte per guadagnare.', v: { k: 'scale', a: 'Out of the money', b: 'In the money', d: [['Strike 60 €', 15], ['Strike 50 €', 50], ['Strike 40 €', 85]] } },
    { t: 'Vendere call senza titoli', x: 'Chi vende una call scoperta incassa al massimo il premio, ma se il sottostante sale molto deve consegnare titoli che valgono ben più dello strike: la perdita non ha un tetto. Per questo il broker chiede margini elevati.', v: { k: 'stat', n: 'Illimitata', l: 'perdita teorica di chi vende una call senza possedere il sottostante' } },
  ],
  terms: [
    ['Opzione call', 'Contratto che dà il diritto, non l’obbligo, di comprare il sottostante a un prezzo fissato.'],
    ['Strike', 'Prezzo di esercizio al quale il possessore dell’opzione può acquistare il sottostante.'],
    ['Premio', 'Prezzo pagato dal compratore al venditore per ottenere il diritto previsto dall’opzione.'],
    ['Valore intrinseco', 'Per una call, la differenza tra prezzo del sottostante e strike se positiva; altrimenti zero.'],
    ['Valore temporale', 'Parte del premio che eccede il valore intrinseco, legata a tempo residuo e volatilità.'],
    ['Break-even', 'Prezzo del sottostante a scadenza oltre il quale la call comprata inizia a guadagnare.'],
    ['Opzione europea', 'Opzione esercitabile soltanto alla data di scadenza.'],
    ['In the money', 'Condizione di un’opzione che, esercitata subito, avrebbe un valore positivo.'],
  ],
  tf: [
    ['Chi compra una call può perdere al massimo il premio pagato.', true, 'Se a scadenza il sottostante è sotto lo strike, l’opzione scade senza valore: si perde il premio e nulla di più.'],
    ['Chi compra una call è obbligato a comprare il sottostante a scadenza.', false, 'Ha un diritto, non un obbligo: lo esercita solo se conviene. L’obbligo ricade su chi ha venduto la call.'],
    ['Una call out of the money ha solo valore temporale.', true, 'Non ha valore intrinseco perché lo strike è sopra il prezzo corrente: il premio è tutto tempo e volatilità.'],
    ['Se il sottostante sale, la call comprata è sempre in guadagno.', false, 'Il rialzo deve superare strike + premio entro la scadenza: un rialzo piccolo o troppo lento può comunque dare una perdita.'],
    ['In genere una call con scadenza più lontana costa di più di una identica con scadenza vicina.', true, 'Più tempo significa più possibilità che il sottostante salga oltre lo strike: il valore temporale è maggiore.'],
    ['Comprare call molto out of the money è un modo prudente di investire perché costano poco.', false, 'Costano poco perché hanno basse probabilità di finire in the money: spesso scadono a zero e si perde tutto il premio.'],
    ['Chi vende una call senza possedere il sottostante ha una perdita potenziale illimitata.', true, 'Se il prezzo sale molto deve consegnare titoli da comprare a prezzi sempre più alti: non c’è un tetto alla perdita.'],
    ['Un’opzione europea può essere esercitata in qualsiasi giorno prima della scadenza.', false, 'L’europea si esercita solo a scadenza, l’americana in qualunque momento. Se il mercato è liquido entrambe si possono rivendere prima.'],
    ['Con sottostante a 80 € e strike 70 €, il valore intrinseco della call è 10 €.', true, 'Valore intrinseco = max(0; 80 − 70) = 10 €. Il premio di mercato sarà in genere più alto per via del valore temporale.'],
    ['Il premio di una call non dipende dalla volatilità del sottostante.', false, 'Più il sottostante è volatile, più è probabile un forte rialzo: la call vale di più. La volatilità è un ingrediente chiave del prezzo.'],
  ],
  mcq: [
    { q: 'Compri una call strike 100 € pagando un premio di 4 €. Qual è il break-even a scadenza?', a: '104 €', w: ['96 €', '100 €', '108 €'], e: 'Break-even = strike + premio = 100 + 4 = 104 €. Solo sopra questo prezzo la posizione è in guadagno.' },
    { q: 'Hai comprato una call strike 100 € a 4 €. A scadenza il sottostante vale 95 €. Qual è il risultato per azione?', a: '−4 €', w: ['−5 €', '−9 €', '0 €'], e: 'Sotto lo strike la call scade senza valore: perdi solo il premio (4 €), non la discesa del sottostante.' },
    { q: 'Con il sottostante a 50 € e la stessa scadenza, quale call ha il premio più alto?', a: 'Strike 40 €', w: ['Strike 50 €', 'Strike 55 €', 'Strike 60 €'], e: 'Più basso è lo strike, maggiore è il valore intrinseco: la call 40 è in the money di 10 € e costa più delle altre.' },
    { q: 'Quale vantaggio offre una call comprata rispetto all’acquisto del sottostante?', a: 'Esposizione al rialzo con perdita massima pari al premio', w: ['Incasso dei dividendi distribuiti dal sottostante', 'Nessun limite di tempo per vedere realizzata la previsione', 'Guadagno anche se il prezzo del sottostante resta fermo'], e: 'La call limita la perdita al premio, ma non dà dividendi, ha una scadenza e perde valore se il prezzo non si muove.' },
    { q: 'Qual è il rischio principale di chi vende una call senza possedere il sottostante?', a: 'Un forte rialzo del sottostante', w: ['Un forte calo del sottostante', 'La scadenza senza esercizio', 'Un calo della volatilità implicita'], e: 'Un rialzo forte obbliga a consegnare titoli che valgono molto più dello strike: la perdita può essere enorme.' },
    { q: 'Da cosa è composto il premio di una call?', a: 'Valore intrinseco più valore temporale', w: ['Strike più valore intrinseco', 'Strike più dividendi attesi', 'Margine iniziale più commissioni'], e: 'Il valore intrinseco è ciò che varrebbe esercitandola subito; il resto è valore temporale, legato a tempo e volatilità.' },
    { q: 'Un errore comune di chi compra call è…', a: 'sottovalutare l’erosione del tempo sul premio', w: ['scegliere una scadenza coerente con la previsione', 'calcolare il break-even prima di comprare', 'limitare i premi a una piccola quota del capitale'], e: 'Se il rialzo arriva dopo la scadenza, la previsione giusta non serve: il valore temporale si consuma ogni giorno.' },
    { q: 'Compri 1 contratto call con lotto da 100 azioni e premio di 2 €. Quanto paghi, senza commissioni?', a: '200 €', w: ['2 €', '100 €', '20 €'], e: 'Premio × lotto = 2 × 100 = 200 €: è anche la perdita massima della posizione.' },
  ],
  fill: [
    { s: 'Il prezzo al quale il possessore della call può comprare il sottostante si chiama ___.', a: 'strike', w: ['premio', 'spread', 'pip'] },
    { s: 'Il prezzo pagato per acquistare un’opzione si chiama ___.', a: 'premio', w: ['cedola', 'dividendo', 'nozionale'] },
    { s: 'Una call con strike sotto il prezzo del sottostante è ___ the money.', a: 'in', w: ['out of', 'at', 'over'] },
    { s: 'A scadenza una call out of the money vale ___.', a: 'zero', w: ['lo strike', 'il premio', 'il sottostante'] },
    { s: 'L’opzione ___ si può esercitare solo alla scadenza.', a: 'europea', w: ['americana', 'scoperta', 'coperta'] },
  ],
  order: [
    { q: 'Con il sottostante a 50 € e la stessa scadenza, ordina queste call dal premio più basso al più alto', i: ['Strike 65 €', 'Strike 58 €', 'Strike 50 €', 'Strike 42 €'], e: 'Più lo strike è basso, più la call è vicina o dentro il denaro: cresce il valore intrinseco e quindi il premio.' },
    { q: 'Hai comprato una call strike 50 € a 3 €. Ordina i prezzi a scadenza dal risultato peggiore al migliore', i: ['50 € o meno', '52 €', '53 €', '57 €'], e: 'Fino a 50 € perdi il premio (−3 €); a 52 € −1 €; a 53 € sei in pareggio; a 57 € guadagni 4 €.' },
  ],
  cat: [
    { q: 'Con il sottostante a 100 €, la call è in the money o out of the money?', g: [['In the money', ['Strike 80 €', 'Strike 90 €', 'Strike 95 €']], ['Out of the money', ['Strike 105 €', 'Strike 110 €', 'Strike 130 €']]] },
    { q: 'Compratore o venditore della call?', g: [['Compratore', ['Paga il premio', 'Ha il diritto di comprare', 'Perdita massima pari al premio']], ['Venditore', ['Incassa il premio', 'Ha l’obbligo di vendere se assegnato', 'Deve versare margini']]] },
  ],
  scen: [
    { s: 'Davide, 33 anni, è convinto che un titolo oggi a 40 € salirà nei prossimi mesi. Valuta una call strike 42 € con scadenza a tre mesi che costa 1,50 €.', q: 'Cosa deve avere chiaro prima di comprare?', o: [
      { t: 'Niente: se il titolo sale anche di poco, guadagna', ok: false, f: 'Con un rialzo modesto, sotto 43,50 €, la call a scadenza è in perdita anche se il titolo è salito.' },
      { t: 'Che il titolo deve superare 43,50 € entro tre mesi e che può perdere tutto il premio', ok: true, f: 'Break-even = 42 + 1,50 = 43,50 €: serve un rialzo di quasi il 9% entro la scadenza, altrimenti il premio è perso.' },
      { t: 'Che la sua perdita massima è lo strike, cioè 42 €', ok: false, f: 'Chi compra una call rischia solo il premio, 1,50 € per azione, non lo strike.' },
    ] },
    { s: 'Serena, 41 anni, vuole investire 2.000 € solo in call molto out of the money a scadenza breve, perché costano poco e possono fare +500%.', q: 'Qual è la scelta più sensata?', o: [
      { t: 'Destina alle call solo una piccola quota che accetta di perdere, sapendo che spesso scadono a zero', ok: true, f: 'Le call molto lontane dal denaro sono biglietti della lotteria: la maggior parte scade senza valore.' },
      { t: 'Investe tutti i 2.000 €: il rischio è limitato al premio', ok: false, f: 'Il rischio è limitato al premio, ma il premio sono tutti i suoi 2.000 €: la perdita totale è uno scenario probabile.' },
      { t: 'Rinnova le call a ogni scadenza finché non arriva il colpo grosso', ok: false, f: 'Ogni rinnovo costa un nuovo premio: sommati nel tempo, i premi persi possono superare l’eventuale vincita.' },
    ] },
    { s: 'Matteo, 58 anni, vuole vendere ogni mese call su un titolo che non possiede, per incassare premi con regolarità.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Vendere molte call, tanto la maggior parte scade a zero', ok: false, f: 'Vincere spesso poco e perdere raramente moltissimo non è una strategia sicura: è rischio concentrato nelle code.' },
      { t: 'Vendere call con strike vicino al prezzo per incassare di più', ok: false, f: 'Premi più alti significano più probabilità di esercizio: il rischio cresce insieme all’incasso.' },
      { t: 'Evitare la vendita scoperta: il premio è limitato, la perdita in un forte rialzo no', ok: true, f: 'Un solo rialzo improvviso, per esempio un’OPA, può cancellare anni di premi incassati.' },
    ] },
    { s: 'Alessia, 36 anni, ha comprato una call che, dopo un rialzo del sottostante, vale il doppio del premio pagato. Mancano due mesi alla scadenza.', q: 'Cosa sa di poter fare?', o: [
      { t: 'Deve aspettare la scadenza per incassare il guadagno', ok: false, f: 'Non è necessario: può chiudere la posizione quando vuole, se il mercato dell’opzione è liquido.' },
      { t: 'Rivendere la call sul mercato prima della scadenza, senza esercitarla', ok: true, f: 'Le opzioni quotate si possono vendere in ogni momento: rivendendo incassa anche il valore temporale residuo.' },
      { t: 'Deve esercitarla subito, altrimenti perde il guadagno', ok: false, f: 'Esercitare in anticipo una call spesso butta via il valore temporale: rivenderla di solito rende di più.' },
    ] },
  ],
  tip: 'Prima di comprare una call scrivi break-even, perdita massima e scadenza: avere ragione sulla direzione non basta, serve anche avere ragione sui tempi.',
});
