FQC(85, {
  intro: 'Una put dà il diritto di vendere un sottostante a un prezzo fissato: è lo strumento base per proteggersi dai ribassi. Scopri payoff, costi e rischi.',
  cards: [
    { t: 'Il diritto di vendere', x: 'Chi compra una put paga un premio per poter vendere il sottostante allo strike. Chi la vende incassa il premio e si impegna a comprare allo strike se la put viene esercitata, anche con il mercato molto più in basso.', v: { k: 'vs', a: ['Compratore della put', 'Paga il premio, ha il diritto di vendere'], b: ['Venditore della put', 'Incassa il premio, ha l’obbligo di comprare'] } },
    { t: 'Il risultato a scadenza', x: 'A scadenza la put vale la differenza tra strike e prezzo del sottostante, se positiva, altrimenti zero. Il risultato netto si ottiene sottraendo il premio pagato.', v: { k: 'formula', f: 'Risultato put = max(0; K − S) − premio', n: 'Es.: K 50 €, premio 2 €, S 40 € → 10 − 2 = +8 € per azione' } },
    { t: 'Break-even = strike − premio', x: 'La put comprata guadagna a scadenza solo se il sottostante scende sotto strike meno premio. Sopra lo strike scade senza valore e perdi il premio. Esempio con strike 50 € e premio 2 €.', v: { k: 'bars', d: [['S = 40 €', 8], ['S = 45 €', 3], ['S = 48 €', 0], ['S = 55 €', -2]], u: '€' } },
    { t: 'Un’assicurazione contro i ribassi', x: 'Chi possiede azioni può comprare put per fissare un prezzo minimo di vendita fino alla scadenza. Come un’assicurazione, la protezione costa un premio che si perde se il ribasso non arriva.', v: { k: 'icons', d: [['🛡️', 'Protegge un titolo che possiedi'], ['💶', 'Il premio è il costo della polizza'], ['⏳', 'La protezione dura fino alla scadenza']] } },
    { t: 'Un guadagno con un tetto', x: 'Un prezzo non può scendere sotto zero: il massimo che una put può valere è lo strike. Per chi la vende, quindi, la perdita massima è strike meno premio, che può essere comunque molto grande.', v: { k: 'stat', n: 'K − premio', l: 'guadagno massimo della put comprata, se il sottostante va a zero' } },
    { t: 'Vendere put: rischi nascosti', x: 'Chi vende put incassa spesso premi e perde di rado, ma in un crollo le perdite arrivano tutte insieme. Senza la liquidità per comprare allo strike si rischiano margin call e chiusure forzate.', v: { k: 'scale', a: 'Rischio più basso', b: 'Rischio più alto', d: [['Put comprata', 20], ['Put venduta con liquidità a copertura', 60], ['Put vendute a leva senza liquidità', 95]] } },
  ],
  terms: [
    ['Opzione put', 'Contratto che dà il diritto, non l’obbligo, di vendere il sottostante a un prezzo fissato.'],
    ['Valore intrinseco della put', 'Differenza tra strike e prezzo del sottostante se positiva; zero se il sottostante è sopra lo strike.'],
    ['Break-even della put', 'Prezzo del sottostante pari allo strike meno il premio pagato.'],
    ['Put in the money', 'Put con strike superiore al prezzo corrente del sottostante.'],
    ['Put out of the money', 'Put con strike inferiore al prezzo corrente del sottostante.'],
    ['Put scoperta', 'Put venduta senza avere la liquidità necessaria per comprare il sottostante allo strike.'],
    ['Cash-secured put', 'Put venduta tenendo da parte la liquidità per comprare il sottostante in caso di esercizio.'],
    ['Assegnazione', 'Notifica al venditore che l’opzione è stata esercitata e che deve adempiere all’obbligo.'],
  ],
  tf: [
    ['Chi compra una put guadagna a scadenza se il sottostante è sotto strike meno premio.', true, 'Sotto il break-even il valore intrinseco supera il premio pagato: la differenza è il guadagno.'],
    ['Comprare una put obbliga a vendere il sottostante.', false, 'È un diritto: si esercita solo se conviene. L’obbligo ricade su chi ha venduto la put, che deve comprare allo strike.'],
    ['Il guadagno massimo di una put comprata è illimitato.', false, 'Il sottostante non può scendere sotto zero: il guadagno massimo è lo strike meno il premio.'],
    ['Chi vende una put può dover comprare il sottostante a un prezzo molto superiore a quello di mercato.', true, 'Se il titolo crolla, il venditore paga lo strike per un titolo che vale molto meno: la perdita è la differenza, meno il premio.'],
    ['Una put con strike sotto il prezzo corrente del sottostante è out of the money.', true, 'Esercitarla significherebbe vendere sotto il prezzo di mercato: non ha valore intrinseco, solo valore temporale.'],
    ['Proteggere un portafoglio con le put non costa nulla se il mercato non scende.', false, 'Il premio si paga comunque: se il ribasso non arriva la put scade senza valore, ed è il costo della protezione.'],
    ['Vendere put è privo di rischi perché la maggior parte scade senza valore.', false, 'Guadagni piccoli e frequenti possono essere cancellati da un solo crollo: il rischio è raro ma molto grande.'],
    ['Nei momenti di panico sui mercati le put tendono a costare di più.', true, 'Sale la volatilità attesa e cresce la domanda di protezione: il premio aumenta proprio quando servirebbe di più.'],
    ['Con sottostante a 30 € e strike 36 €, il valore intrinseco della put è 6 €.', true, 'Valore intrinseco = max(0; 36 − 30) = 6 €. Il prezzo di mercato include anche il valore temporale.'],
    ['Una put ha valore a scadenza solo se il sottostante va a zero.', false, 'Basta che a scadenza il sottostante sia sotto lo strike; per guadagnare deve scendere sotto strike meno premio.'],
  ],
  mcq: [
    { q: 'Compri una put strike 60 € pagando un premio di 3 €. Qual è il break-even a scadenza?', a: '57 €', w: ['63 €', '60 €', '54 €'], e: 'Break-even = strike − premio = 60 − 3 = 57 €. Sotto questo prezzo la put comprata è in guadagno.' },
    { q: 'Hai comprato una put strike 60 € a 3 €. A scadenza il sottostante vale 50 €. Qual è il risultato per azione?', a: '+7 €', w: ['+10 €', '−3 €', '+13 €'], e: 'Valore a scadenza = 60 − 50 = 10 €; tolto il premio di 3 €, il guadagno netto è di 7 € per azione.' },
    { q: 'Qual è la perdita massima di chi vende una put strike 40 € incassando un premio di 2 €?', a: '38 € per azione', w: ['2 € per azione', '40 € per azione', 'Illimitata'], e: 'Se il titolo va a zero deve pagare 40 € per un titolo senza valore; il premio incassato riduce la perdita a 38 €.' },
    { q: 'Hai azioni a 100 € e temi un calo nei prossimi tre mesi. Quale operazione ti dà il diritto di vendere a un prezzo minimo?', a: 'Comprare una put', w: ['Comprare una call', 'Vendere una put', 'Vendere una call'], e: 'La put comprata fissa un prezzo minimo di vendita: sotto lo strike compensa il calo del titolo.' },
    { q: 'Perché una put out of the money costa meno di una in the money con la stessa scadenza?', a: 'Non ha valore intrinseco, solo valore temporale', w: ['Scade sempre qualche giorno prima', 'Si può esercitare solo alla scadenza', 'Il venditore non deve versare margini'], e: 'Lo strike è sotto il prezzo corrente: esercitarla oggi non darebbe nulla, quindi il premio riflette solo tempo e volatilità.' },
    { q: 'Cosa succede di solito al premio delle put durante un crollo improvviso dei mercati?', a: 'Aumenta, per il calo dei prezzi e la volatilità più alta', w: ['Diminuisce, perché tutti vendono le proprie azioni', 'Resta invariato fino alla data di scadenza', 'Si azzera, perché le borse sospendono le opzioni'], e: 'Il sottostante scende e la volatilità implicita sale: due fattori che fanno crescere il valore delle put.' },
    { q: 'Un errore comune di chi vende put è…', a: 'vendere più contratti di quanti potrebbe pagare', w: ['tenere da parte la liquidità per l’assegnazione', 'scegliere titoli che accetterebbe di possedere', 'valutare lo scenario di un forte ribasso'], e: 'In un crollo tutte le put vengono esercitate insieme: senza liquidità arrivano margin call e perdite forzate.' },
    { q: 'Cosa significa l’assegnazione per chi ha venduto una put?', a: 'Deve comprare il sottostante allo strike', w: ['Deve vendere il sottostante allo strike', 'Riceve un secondo premio dal compratore', 'Può restituire il premio e annullare tutto'], e: 'Il compratore ha esercitato il diritto di vendere: il venditore della put è obbligato a comprare allo strike.' },
  ],
  fill: [
    { s: 'La put dà il diritto di ___ il sottostante a un prezzo fissato.', a: 'vendere', w: ['comprare', 'prestare', 'convertire'] },
    { s: 'Il break-even di una put comprata è pari allo strike ___ il premio.', a: 'meno', w: ['più', 'per', 'diviso'] },
    { s: 'Una put con strike sopra il prezzo del sottostante è ___ the money.', a: 'in', w: ['out of', 'at', 'over'] },
    { s: 'Chi vende una put e viene ___ deve comprare il sottostante allo strike.', a: 'assegnato', w: ['liquidato', 'rimborsato', 'coperto'] },
    { s: 'Il costo della protezione offerta da una put è il ___ pagato.', a: 'premio', w: ['margine', 'dividendo', 'pip'] },
  ],
  order: [
    { q: 'Con il sottostante a 50 € e la stessa scadenza, ordina queste put dal premio più basso al più alto', i: ['Strike 35 €', 'Strike 42 €', 'Strike 50 €', 'Strike 58 €'], e: 'Per le put vale il contrario delle call: più lo strike è alto, più valore intrinseco e quindi più premio.' },
    { q: 'Hai comprato una put strike 50 € a 2 €. Ordina i prezzi a scadenza dal risultato migliore al peggiore', i: ['40 €', '45 €', '48 €', '50 € o più'], e: 'A 40 € guadagni 8 €; a 45 € 3 €; a 48 € sei in pareggio; da 50 € in su perdi il premio (−2 €).' },
  ],
  cat: [
    { q: 'Con il sottostante a 80 €, la put è in the money o out of the money?', g: [['In the money', ['Strike 85 €', 'Strike 90 €', 'Strike 100 €']], ['Out of the money', ['Strike 60 €', 'Strike 70 €', 'Strike 75 €']]] },
    { q: 'Rischio tipico di chi compra o di chi vende la put?', g: [['Chi compra', ['Perde il premio se il titolo non scende', 'Il tempo erode il valore dell’opzione', 'Paga di più quando la paura è alta']], ['Chi vende', ['Deve comprare allo strike durante un crollo', 'Può ricevere margin call', 'Guadagno limitato al premio incassato']]] },
  ],
  scen: [
    { s: 'Giorgio, 62 anni, ha 50.000 € in un ETF azionario e tra sei mesi gli serviranno per comprare casa. Teme un ribasso del mercato.', q: 'Cosa valuta?', o: [
      { t: 'Vendere put sull’ETF per incassare premi e aumentare il capitale', ok: false, f: 'Vendere put aggiunge rischio al ribasso proprio quando vuole ridurlo: in un crollo perderebbe due volte.' },
      { t: 'Non fare nulla, perché nel lungo periodo il mercato sale', ok: false, f: 'Sei mesi non sono il lungo periodo: un ribasso del 20-30% in quel lasso di tempo è possibile.' },
      { t: 'Ridurre l’esposizione o comprare put a sei mesi, mettendo in conto il premio', ok: true, f: 'Con un obiettivo vicino non può permettersi un crollo: vendere o assicurarsi con put costa, ma protegge la spesa.' },
    ] },
    { s: 'Ilaria, 37 anni, vende ogni mese put su un titolo volatile. Ha 10.000 € sul conto, ma se tutte le put fossero esercitate dovrebbe pagare 40.000 €.', q: 'Cosa fa?', o: [
      { t: 'Continua così: finora le put sono sempre scadute a zero', ok: false, f: 'Il passato tranquillo non dice nulla sul prossimo crollo: con leva 4 un ribasso forte le azzererebbe il conto.' },
      { t: 'Riduce i contratti finché la liquidità copre un’eventuale assegnazione', ok: true, f: 'Vendere put coperte da liquidità limita la leva: in un crollo può comprare i titoli senza essere liquidata.' },
      { t: 'Aumenta i contratti per incassare più premi', ok: false, f: 'Aumenta l’esposizione già eccessiva: più premi oggi, perdite molto più grandi nello scenario peggiore.' },
    ] },
    { s: 'Fabio, 44 anni, ha comprato put strike 20 € su un titolo che era a 22 €. Ora il titolo è salito a 26 € e mancano sette giorni alla scadenza.', q: 'Cosa sa della sua posizione?', o: [
      { t: 'La put è out of the money e perde valore ogni giorno: può rivenderla per recuperare il residuo', ok: true, f: 'Il valore rimasto è solo temporale e si sta esaurendo: rivenderla limita la perdita, sempre che ci sia un compratore.' },
      { t: 'Deve esercitarla per limitare le perdite', ok: false, f: 'Esercitarla significherebbe vendere a 20 € un titolo che vale 26 €: aggiungerebbe una perdita.' },
      { t: 'Se non la esercita, il premio gli verrà restituito', ok: false, f: 'Il premio non torna mai indietro: è il prezzo pagato per il diritto, che lo usi o no.' },
    ] },
    { s: 'Martina, 29 anni, vuole puntare sul crollo di un titolo e confronta due strade: vendere allo scoperto l’azione o comprare una put.', q: 'Qual è la differenza chiave?', o: [
      { t: 'Con la put non c’è nessuna scadenza da rispettare', ok: false, f: 'Ogni put ha una scadenza: se il crollo arriva dopo, l’opzione è già scaduta senza valore.' },
      { t: 'Lo short costa sempre meno della put', ok: false, f: 'Lo short ha costi di prestito e dividendi da compensare, la put il premio: quale costi meno dipende dal caso.' },
      { t: 'Con la put la perdita massima è il premio; con lo short è teoricamente illimitata', ok: true, f: 'La put definisce il rischio in anticipo, ma ha una scadenza e il tempo ne erode il valore.' },
    ] },
  ],
  tip: 'Una put comprata è un’assicurazione: decidi cosa vuoi proteggere, per quanto tempo e quanto sei disposto a pagare. Chi vende put, invece, fa l’assicuratore.',
});
