FQC(86, {
  intro: 'Combinando opzioni e sottostante costruisci profili di rischio diversi: covered call, protective put, spread e straddle. Ognuno ha un costo e un rischio.',
  cards: [
    { t: 'Covered call', x: 'Possiedi le azioni e vendi call sullo stesso sottostante: il premio incassato migliora il rendimento se il prezzo resta stabile, ma rinunci ai guadagni sopra lo strike. Il rischio di ribasso resta quasi tutto tuo.', v: { k: 'vs', a: ['Cosa ottieni', 'Il premio, un piccolo cuscinetto'], b: ['A cosa rinunci', 'Ai guadagni sopra lo strike'] } },
    { t: 'Protective put', x: 'Possiedi le azioni e compri una put: fissi un prezzo minimo di vendita fino alla scadenza. È un’assicurazione che costa il premio, il quale riduce il rendimento se il ribasso non arriva.', v: { k: 'formula', f: 'Perdita massima = (Prezzo d’acquisto − Strike) + Premio', n: 'Es.: azione a 100 €, put strike 90 € a 3 € → massimo −13 € per azione' } },
    { t: 'Spread verticale', x: 'Nel bull call spread compri una call e ne vendi un’altra con strike più alto: il premio incassato riduce il costo, ma il guadagno massimo è la distanza tra gli strike meno il costo netto. Esempio: call 50 € a 4 € e call 60 € a 1,50 €.', v: { k: 'bars', d: [['S = 45 €', -2.5], ['S = 55 €', 2.5], ['S = 60 €', 7.5], ['S = 70 €', 7.5]], u: '€' } },
    { t: 'Straddle', x: 'Lo straddle comprato guadagna se il sottostante si muove molto, in qualsiasi direzione. Se il prezzo resta fermo perdi buona parte dei due premi; venduto, è l’opposto, con perdite potenzialmente molto grandi.', v: { k: 'steps', s: ['Compri call e put con lo stesso strike', 'Paghi due premi', 'Serve un movimento ampio', 'Guadagni oltre strike ± premi totali'] } },
    { t: 'Perdita massima a confronto', x: 'Le strategie comprate a debito hanno in genere una perdita massima nota; quelle vendute a credito incassano subito ma possono perdere molto. Prima di aprire, scrivi sempre perdita massima e scenario peggiore.', v: { k: 'scale', a: 'Perdita massima contenuta', b: 'Perdita potenzialmente illimitata', d: [['Bull call spread', 15], ['Protective put', 20], ['Covered call', 60], ['Straddle venduto', 95]] } },
    { t: 'I costi delle strategie complesse', x: 'Ogni gamba paga commissioni e spread denaro-lettera, e le opzioni vendute di tipo americano possono essere esercitate in anticipo. Più gambe significa più costi e più cose da controllare.', v: { k: 'icons', d: [['💸', 'Commissioni su ogni gamba'], ['↔️', 'Spread denaro-lettera'], ['📅', 'Esercizio anticipato'], ['🧩', 'Gestione più complessa']] } },
  ],
  terms: [
    ['Covered call', 'Vendita di call su azioni già possedute per incassare il premio, limitando il guadagno massimo.'],
    ['Protective put', 'Acquisto di put su un titolo posseduto per fissare un prezzo minimo di vendita.'],
    ['Bull call spread', 'Acquisto di una call e vendita di una call con strike più alto: costo ridotto, guadagno limitato.'],
    ['Bear put spread', 'Acquisto di una put e vendita di una put con strike più basso per puntare su un ribasso moderato.'],
    ['Straddle', 'Call e put con stesso strike e scadenza, comprate o vendute insieme: punta sull’ampiezza del movimento.'],
    ['Strangle', 'Call e put con strike diversi, entrambe out of the money: più economica, serve un movimento più ampio.'],
    ['Collar', 'Titolo posseduto con put comprata e call venduta: protezione a costo ridotto, rialzo limitato.'],
    ['Gamba', 'Ciascuna delle singole opzioni o posizioni che compongono una strategia combinata.'],
  ],
  tf: [
    ['La covered call protegge completamente dal ribasso del titolo.', false, 'Il premio incassato compensa solo una piccola parte del calo: se il titolo crolla, la perdita resta quasi intera.'],
    ['La protective put fissa una perdita massima sul titolo fino alla scadenza dell’opzione.', true, 'Sotto lo strike la put compensa il calo: la perdita massima è la distanza dallo strike più il premio pagato.'],
    ['Uno straddle comprato guadagna se il sottostante resta fermo vicino allo strike.', false, 'È lo scenario peggiore: call e put scadono con poco o nessun valore e perdi buona parte dei due premi.'],
    ['In un bull call spread il guadagno massimo è limitato.', true, 'La call venduta a strike più alto annulla i guadagni oltre quel livello: è il prezzo pagato per ridurre il costo.'],
    ['Nello straddle venduto la perdita massima è limitata ai premi incassati.', false, 'È il contrario: i premi sono il guadagno massimo, mentre un forte movimento può causare perdite molto grandi, illimitate al rialzo.'],
    ['Con la covered call rischi di dover consegnare le azioni se il prezzo supera lo strike.', true, 'Se la call viene esercitata vendi le azioni allo strike e rinunci al rialzo oltre quel livello.'],
    ['Più gambe ha una strategia, più bassi sono i costi di transazione complessivi.', false, 'Ogni gamba ha commissioni e spread denaro-lettera: le strategie complesse costano di più da aprire e da chiudere.'],
    ['Uno straddle comprato prima di un evento atteso può perdere anche se il prezzo si muove.', true, 'Se il movimento è inferiore a quello già prezzato, il calo della volatilità implicita dopo l’evento riduce il valore di entrambe le opzioni.'],
    ['Una strategia che incassa premi ogni mese garantisce un reddito sicuro.', false, 'Incassare premi significa vendere protezione: rendimenti regolari possono essere cancellati da un singolo movimento estremo.'],
    ['Il collar combina put comprata e call venduta per ridurre il costo della protezione.', true, 'Il premio della call venduta finanzia in tutto o in parte la put, ma limita anche il guadagno al rialzo.'],
  ],
  mcq: [
    { q: 'Possiedi azioni e ti aspetti un mercato laterale. Quale strategia può aggiungere rendimento in cambio di parte del rialzo?', a: 'Covered call', w: ['Protective put', 'Straddle comprato', 'Bear put spread'], e: 'Vendendo call sulle azioni possedute incassi premi; se il titolo sale oltre lo strike, però, il guadagno si ferma lì.' },
    { q: 'Quale strategia trae profitto da un forte movimento del sottostante, senza scommettere sulla direzione?', a: 'Straddle comprato', w: ['Covered call', 'Bull call spread', 'Collar'], e: 'Lo straddle comprato guadagna se il prezzo sale o scende abbastanza da superare il costo dei due premi.' },
    { q: 'Compri una call strike 50 € a 4 € e vendi una call strike 60 € a 1,50 €. Qual è il guadagno massimo per azione a scadenza?', a: '7,50 €', w: ['10 €', '2,50 €', '5,50 €'], e: 'Distanza tra gli strike (10 €) meno il costo netto (2,50 €) = 7,50 €, raggiunto con il sottostante a 60 € o più.' },
    { q: 'Un bull call spread costa 2,50 € netti per azione. Qual è la perdita massima a scadenza?', a: '2,50 € per azione', w: ['Illimitata', '10 € per azione', '4 € per azione'], e: 'Se il sottostante finisce sotto lo strike più basso, entrambe le call scadono a zero: perdi il costo netto pagato.' },
    { q: 'Hai azioni comprate a 100 € e compri una put strike 90 € a 3 €. Qual è la perdita massima per azione fino alla scadenza?', a: '13 €', w: ['3 €', '10 €', '90 €'], e: 'Perdi al massimo 10 € sul titolo (da 100 a 90) più i 3 € di premio: 13 € per azione, qualunque sia il crollo.' },
    { q: 'Quale strategia è la più pericolosa se il sottostante esplode al rialzo?', a: 'Straddle venduto', w: ['Protective put', 'Bull call spread', 'Straddle comprato'], e: 'Nello straddle venduto la call venduta è scoperta: un rialzo forte produce perdite senza un tetto.' },
    { q: 'Un errore comune con la covered call è…', a: 'considerarla una protezione dal crollo', w: ['valutare lo strike rispetto ai propri obiettivi', 'sapere che le azioni possono essere assegnate', 'tenere conto dei dividendi in arrivo'], e: 'Il premio è un piccolo cuscinetto: se il titolo crolla, la covered call perde quasi quanto il titolo da solo.' },
    { q: 'Perché si sceglie uno spread invece di comprare una sola call?', a: 'Per ridurre il costo accettando un guadagno massimo limitato', w: ['Per eliminare qualsiasi possibile perdita sul capitale', 'Per ottenere un guadagno potenziale illimitato', 'Per evitare che l’opzione arrivi a scadenza'], e: 'La call venduta finanzia parte di quella comprata: costa meno, ma oltre lo strike più alto il guadagno si ferma.' },
  ],
  fill: [
    { s: 'Vendere call su azioni che possiedi si chiama ___ call.', a: 'covered', w: ['naked', 'long', 'straddle'] },
    { s: 'Comprare una put su azioni che possiedi per limitarne il calo si chiama ___ put.', a: 'protective', w: ['covered', 'naked', 'short'] },
    { s: 'Lo ___ si costruisce con una call e una put con lo stesso strike e la stessa scadenza.', a: 'straddle', w: ['strangle', 'spread', 'collar'] },
    { s: 'In uno spread verticale compri un’opzione e ne ___ un’altra dello stesso tipo con strike diverso.', a: 'vendi', w: ['eserciti', 'raddoppi', 'converti'] },
    { s: 'Ciascuna opzione che compone una strategia combinata si chiama ___.', a: 'gamba', w: ['lotto', 'tranche', 'cedola'] },
  ],
  order: [
    { q: 'Ordina i passaggi per costruire e gestire una covered call', i: ['Possiedi le azioni', 'Scegli strike e scadenza della call', 'Vendi la call e incassi il premio', 'A scadenza consegni le azioni o la call scade', 'Decidi se vendere una nuova call'], e: 'La covered call parte sempre dalle azioni possedute: senza di esse la call venduta sarebbe scoperta.' },
    { q: 'Con il sottostante a 50 €, ordina le posizioni dalla perdita massima più bassa alla più alta', i: ['Bull call spread con costo netto 2 €', 'Call comprata a 4 €', 'Azione comprata a 50 €', 'Call venduta scoperta'], e: 'Perdite massime: 2 €, 4 €, 50 € (il titolo a zero) e nessun tetto per la call venduta senza titoli.' },
  ],
  cat: [
    { q: 'Strategia a debito o a credito?', g: [['A debito (paghi un premio netto)', ['Protective put', 'Straddle comprato', 'Bull call spread']], ['A credito (incassi un premio netto)', ['Covered call', 'Straddle venduto', 'Put venduta']]] },
    { q: 'Perdita massima limitata o potenzialmente illimitata?', g: [['Limitata', ['Protective put', 'Bear put spread', 'Straddle comprato']], ['Illimitata', ['Straddle venduto', 'Call venduta scoperta', 'Strangle venduto']]] },
  ],
  scen: [
    { s: 'Antonio, 66 anni, possiede azioni di una utility e vorrebbe un reddito extra. Pensa di vendere covered call ogni mese.', q: 'Come procede?', o: [
      { t: 'Le considera una protezione e smette di valutare il rischio del titolo', ok: false, f: 'Il premio copre solo una piccola parte di un eventuale calo: il rischio del titolo resta quasi intero.' },
      { t: 'Le vende solo su azioni che accetta di cedere allo strike, sapendo che il ribasso resta suo', ok: true, f: 'Così la strategia è coerente: incassa premi, accetta di vendere a un prezzo che gli va bene e non si illude di essere protetto.' },
      { t: 'Vende call per un numero di azioni doppio rispetto a quelle che possiede', ok: false, f: 'Metà delle call diventa scoperta: in un forte rialzo la perdita su quella parte non ha un tetto.' },
    ] },
    { s: 'Valentina, 39 anni, vuole comprare uno straddle prima della trimestrale di un titolo, convinta che si muoverà comunque molto.', q: 'Cosa fa prima di operare?', o: [
      { t: 'Compra subito senza fare calcoli, visto che guadagna in entrambe le direzioni', ok: false, f: 'Guadagna solo se il movimento supera i due premi: un movimento atteso ma modesto porta a una perdita.' },
      { t: 'Vende lo straddle per incassare i premi, che sono molto alti', ok: false, f: 'Premi alti significano anche rischio alto: un movimento forte dopo i conti può causare perdite molto superiori.' },
      { t: 'Confronta il movimento che si aspetta con il costo dei due premi, che già incorpora la volatilità prevista', ok: true, f: 'Se il mercato prevede già un movimento ampio, i premi sono cari: serve un movimento ancora maggiore per guadagnare.' },
    ] },
    { s: 'Riccardo, 50 anni, ha un forte guadagno su un titolo e teme una correzione nei prossimi tre mesi, ma non vuole spendere molto in protezione.', q: 'Quale soluzione valuta?', o: [
      { t: 'Un collar: put comprata finanziata da una call venduta, accettando di limitare il rialzo', ok: true, f: 'La call venduta paga in tutto o in parte la put: protegge il guadagno a costo ridotto, rinunciando ai rialzi oltre lo strike.' },
      { t: 'Vendere call scoperte su un altro titolo per finanziare la protezione', ok: false, f: 'Aggiunge un rischio potenzialmente illimitato per coprirne un altro: il rimedio è peggiore del problema.' },
      { t: 'Comprare put a una settimana e rinnovarle di continuo per tre mesi', ok: false, f: 'Le scadenze brevissime perdono valore molto in fretta: rinnovate per tre mesi, il costo totale è alto e la copertura può avere buchi.' },
    ] },
    { s: 'Noemi, 35 anni, trova in un corso online una strategia a quattro gambe che promette un rendimento mensile del 3% a rischio limitato.', q: 'Cosa fa?', o: [
      { t: 'Replica la strategia con tutto il capitale per sfruttare il rendimento', ok: false, f: 'Senza aver capito perdita massima e costi, impegnare tutto il capitale significa esporsi a sorprese gravi.' },
      { t: 'Verifica perdita massima, costi di tutte le gambe e scenario peggiore prima di operare', ok: true, f: 'Un rendimento regolare promesso spesso nasconde rischi nelle code: i numeri vanno controllati, non presi sulla fiducia.' },
      { t: 'Si fida: con quattro gambe la strategia è per forza diversificata', ok: false, f: 'Più gambe sullo stesso sottostante non diversificano: aumentano costi e complessità, non riducono di per sé il rischio.' },
    ] },
  ],
  tip: 'Per ogni strategia disegna il risultato a scadenza: guadagno massimo, perdita massima e break-even. Se non sai cosa succede in un crollo o in un’esplosione al rialzo, non aprirla.',
});
