FQC(87, {
  intro: 'Il prezzo di un’opzione dipende da sottostante, tempo e volatilità. Le greche misurano queste sensibilità: delta, gamma, theta e vega.',
  cards: [
    { t: 'Volatilità storica e implicita', x: 'La volatilità storica misura quanto il prezzo si è mosso in passato; quella implicita è il valore che, inserito in un modello di prezzo, restituisce il premio di mercato. È un’aspettativa, non una previsione garantita.', v: { k: 'vs', a: ['Volatilità storica', 'Calcolata sui rendimenti passati'], b: ['Volatilità implicita', 'Ricavata dai prezzi delle opzioni'] } },
    { t: 'Delta: la sensibilità al prezzo', x: 'Il delta stima di quanto varia l’opzione per 1 € di movimento del sottostante. Va da 0 a 1 per le call comprate e da −1 a 0 per le put comprate; at the money è vicino a ±0,5.', v: { k: 'formula', f: 'Variazione opzione ≈ Delta × Variazione sottostante', n: 'Es.: delta 0,5 e sottostante +2 € → opzione circa +1 €' } },
    { t: 'Gamma: la velocità del delta', x: 'Il gamma misura quanto cambia il delta quando si muove il sottostante. È massimo per le opzioni at the money vicine alla scadenza: lì l’esposizione della posizione può cambiare molto in fretta.', v: { k: 'scale', a: 'Gamma basso', b: 'Gamma alto', d: [['Molto out of the money', 10], ['Molto in the money', 15], ['At the money, scadenza lontana', 50], ['At the money, scadenza vicina', 95]] } },
    { t: 'Theta: il tempo che consuma', x: 'Il theta misura quanto valore perde l’opzione ogni giorno, a parità del resto. Nel grafico, il valore temporale di un’opzione at the money (esempio): il decadimento accelera avvicinandosi alla scadenza.', v: { k: 'bars', d: [['90 giorni', 6], ['60 giorni', 4.9], ['30 giorni', 3.5], ['10 giorni', 2], ['1 giorno', 0.6]], u: '€' } },
    { t: 'Vega: la sensibilità alla volatilità', x: 'Il vega misura quanto cambia il premio se la volatilità implicita varia di un punto. Chi compra opzioni ha vega positivo, chi le vende negativo: un calo della volatilità può far perdere anche con il prezzo nella direzione giusta.', v: { k: 'stat', n: '0,20 €', l: 'guadagno di un’opzione con vega 0,20 se la volatilità implicita sale di 1 punto' } },
    { t: 'Le greche in sintesi', x: 'Le greche sono stime locali: valgono per piccoli movimenti e cambiano di continuo con prezzo, tempo e volatilità. Non dicono se un’opzione è conveniente, solo come reagisce.', v: { k: 'icons', d: [['🎯', 'Delta: prezzo'], ['🌀', 'Gamma: velocità del delta'], ['⏳', 'Theta: tempo'], ['🌪️', 'Vega: volatilità']] } },
  ],
  terms: [
    ['Volatilità storica', 'Variabilità dei rendimenti passati, di solito espressa come deviazione standard annualizzata.'],
    ['Volatilità implicita', 'Volatilità che, inserita in un modello di prezzo, restituisce il premio osservato sul mercato.'],
    ['Delta', 'Variazione stimata del prezzo dell’opzione per 1 € di movimento del sottostante.'],
    ['Gamma', 'Variazione del delta per 1 € di movimento del sottostante.'],
    ['Theta', 'Perdita di valore dell’opzione per il passare di un giorno, a parità degli altri fattori.'],
    ['Vega', 'Variazione del premio per 1 punto percentuale di variazione della volatilità implicita.'],
    ['Delta hedging', 'Neutralizzare il delta di una posizione in opzioni con una posizione opposta nel sottostante.'],
    ['VIX', 'Indice della volatilità implicita a circa 30 giorni ricavata dalle opzioni sull’S&P 500.'],
  ],
  tf: [
    ['La volatilità implicita si ricava dai prezzi delle opzioni, non dai prezzi passati del sottostante.', true, 'Si ottiene invertendo un modello di prezzo: esprime la variabilità che il mercato sta prezzando oggi.'],
    ['Un’alta volatilità implicita garantisce che il sottostante si muoverà molto.', false, 'È un’aspettativa incorporata nei prezzi, non una certezza: il movimento realizzato può essere molto più piccolo.'],
    ['Una call comprata ha un delta compreso tra 0 e 1.', true, 'Guadagna valore se il sottostante sale, ma per ogni euro di rialzo del sottostante non più di un euro per azione.'],
    ['Una put comprata ha delta positivo.', false, 'Il delta di una put comprata è compreso tra −1 e 0: guadagna quando il sottostante scende.'],
    ['Per chi compra opzioni, il theta è in genere negativo.', true, 'A parità di prezzo e volatilità, ogni giorno che passa il valore temporale si riduce: il tempo lavora contro chi compra.'],
    ['Il gamma è più alto per le opzioni molto out of the money.', false, 'Il gamma è massimo vicino allo strike, soprattutto a ridosso della scadenza; lontano dallo strike è basso.'],
    ['Puoi perdere su una call comprata anche se il sottostante sale, se la volatilità implicita crolla.', true, 'Con vega positivo, un forte calo della volatilità implicita può compensare il guadagno dovuto al delta.'],
    ['Un delta di 0,30 significa che l’opzione ha esattamente il 30% di probabilità di scadere in the money.', false, 'Il delta è spesso usato come stima approssimativa di quella probabilità, ma non coincide con essa e non è una garanzia.'],
    ['Il VIX si basa sulla volatilità implicita delle opzioni sull’indice S&P 500.', true, 'Misura la volatilità attesa a circa 30 giorni sull’S&P 500 ed è spesso chiamato indice della paura.'],
    ['Le greche restano costanti per tutta la vita dell’opzione.', false, 'Cambiano di continuo con prezzo, tempo residuo e volatilità: vanno ricalcolate e monitorate.'],
  ],
  mcq: [
    { q: 'Una call ha delta 0,60. Se il sottostante sale di 5 €, di quanto varia circa l’opzione?', a: '+3 €', w: ['+5 €', '+0,60 €', '+8,33 €'], e: 'Variazione ≈ delta × movimento = 0,60 × 5 € = 3 €. È una stima: il gamma modifica il delta durante il movimento.' },
    { q: 'Quale greca misura la sensibilità del premio alla volatilità implicita?', a: 'Vega', w: ['Theta', 'Gamma', 'Delta'], e: 'Il vega indica quanto cambia il premio per ogni punto di variazione della volatilità implicita.' },
    { q: 'Un’opzione ha theta pari a −0,05. Cosa significa?', a: 'Perde circa 0,05 € al giorno, a parità del resto', w: ['Guadagna 0,05 € per ogni euro di rialzo', 'Perde il 5% del valore ogni mese in qualsiasi caso', 'Ha il 5% di probabilità di scadere in the money'], e: 'Il theta misura l’erosione giornaliera del valore temporale, a prezzo e volatilità invariati.' },
    { q: 'Dove è tipicamente più alto il gamma?', a: 'Opzioni at the money vicine alla scadenza', w: ['Opzioni molto in the money a lunga scadenza', 'Opzioni out of the money a lunga scadenza', 'Opzioni molto out of the money a breve scadenza'], e: 'Vicino allo strike e a ridosso della scadenza il delta può passare in fretta da circa 0 a circa 1: è lì che il gamma è massimo.' },
    { q: 'Dopo l’annuncio dei conti il titolo sale del 2%, ma la tua call comprata perde valore. Qual è la causa più probabile?', a: 'Il calo della volatilità implicita dopo l’evento', w: ['Un aumento improvviso del delta della call comprata', 'Il gamma della call diventato negativo', 'L’aumento dello strike deciso dalla borsa'], e: 'Prima dei conti la volatilità implicita è alta; dopo l’annuncio crolla e il vega positivo fa perdere più di quanto guadagni con il delta.' },
    { q: 'Qual è la differenza tra volatilità storica e implicita?', a: 'La prima guarda al passato, la seconda alle attese prezzate', w: ['La prima riguarda le azioni, la seconda solo le obbligazioni', 'La prima è giornaliera, la seconda è sempre mensile', 'Sono due nomi diversi per la stessa identica misura'], e: 'La storica si calcola sui rendimenti già realizzati; l’implicita si ricava dai premi delle opzioni.' },
    { q: 'Un errore comune di chi compra opzioni è…', a: 'pagare una volatilità implicita molto alta', w: ['confrontare implicita e storica prima di comprare', 'controllare il theta della posizione ogni giorno', 'valutare l’effetto di un calo della volatilità'], e: 'Se la volatilità è già molto prezzata, serve un movimento eccezionale per guadagnare: si può avere ragione e perdere comunque.' },
    { q: 'Hai venduto opzioni e il delta complessivo è vicino a zero. Quale rischio resta?', a: 'Un movimento ampio, perché il gamma negativo sposta il delta', w: ['Nessuno, perché la posizione è del tutto neutrale al mercato', 'Soltanto il rischio di cambio sulla valuta', 'Soltanto il rischio di un aumento dei tassi'], e: 'Il delta neutrale vale per piccoli movimenti: con gamma negativo, un movimento ampio rende la posizione sempre più esposta nella direzione sbagliata.' },
  ],
  fill: [
    { s: 'La greca che misura l’effetto del passare del tempo si chiama ___.', a: 'theta', w: ['vega', 'gamma', 'rho'] },
    { s: 'La volatilità ___ è quella ricavata dai prezzi delle opzioni.', a: 'implicita', w: ['storica', 'realizzata', 'annuale'] },
    { s: 'Il ___ misura di quanto cambia il delta quando si muove il sottostante.', a: 'gamma', w: ['theta', 'vega', 'beta'] },
    { s: 'Una call comprata at the money ha di solito un delta vicino a ___.', a: '0,5', w: ['0', '1', '−1'] },
    { s: 'Una posizione con ___ positivo guadagna se la volatilità implicita sale.', a: 'vega', w: ['theta', 'rho', 'beta'] },
  ],
  order: [
    { q: 'Con il sottostante a 100 €, ordina queste call dal delta più basso al più alto', i: ['Strike 130 €', 'Strike 115 €', 'Strike 100 €', 'Strike 85 €', 'Strike 70 €'], e: 'Più la call è in the money, più il delta si avvicina a 1; molto out of the money si avvicina a 0.' },
    { q: 'Ordina queste opzioni at the money dal theta giornaliero più piccolo al più grande, in valore assoluto', i: ['Scadenza 1 anno', 'Scadenza 6 mesi', 'Scadenza 1 mese', 'Scadenza 1 settimana'], e: 'Per un’opzione at the money il decadimento temporale accelera man mano che la scadenza si avvicina.' },
  ],
  cat: [
    { q: 'Favorevole o sfavorevole per chi ha comprato una call?', g: [['Favorevole', ['Il sottostante sale', 'La volatilità implicita aumenta', 'Un rialzo rapido oltre lo strike']], ['Sfavorevole', ['Passano i giorni senza movimenti', 'La volatilità implicita crolla', 'Il sottostante scende']]] },
    { q: 'Volatilità storica o implicita?', g: [['Storica', ['Calcolata sui rendimenti passati', 'Deviazione standard degli ultimi 30 giorni', 'Misura ciò che è già successo']], ['Implicita', ['Ricavata dal premio delle opzioni', 'Alla base del calcolo del VIX', 'Riflette le attese del mercato']]] },
  ],
  scen: [
    { s: 'Simone, 40 anni, vuole comprare call su un titolo il giorno prima dei conti trimestrali. Nota che la volatilità implicita è il doppio della storica.', q: 'Cosa fa?', o: [
      { t: 'Compra: una volatilità alta significa che il titolo salirà', ok: false, f: 'La volatilità non indica la direzione: misura l’ampiezza attesa dei movimenti, al rialzo come al ribasso.' },
      { t: 'Compra il doppio dei contratti per sfruttare la volatilità', ok: false, f: 'Raddoppia l’esposizione proprio quando le opzioni sono più care e più esposte al crollo della volatilità.' },
      { t: 'Mette in conto che dopo i conti la volatilità può crollare e valuta se il movimento atteso giustifica il prezzo', ok: true, f: 'Con la volatilità così alta paga caro il movimento atteso: se il titolo si muove meno del previsto, perde anche avendo ragione sulla direzione.' },
    ] },
    { s: 'Beatrice, 48 anni, ha venduto put e call at the money sullo stesso titolo. Il delta complessivo è vicino a zero e si sente al sicuro dalle oscillazioni.', q: 'Cosa dovrebbe sapere?', o: [
      { t: 'Che ha gamma e vega negativi: un movimento ampio o un aumento di volatilità possono causarle forti perdite', ok: true, f: 'Il delta neutrale protegge solo dai piccoli movimenti: la posizione venduta soffre i grandi movimenti e i picchi di volatilità.' },
      { t: 'Che con delta zero il rischio è zero', ok: false, f: 'Il delta è solo una delle sensibilità: gamma e vega negativi espongono a perdite rilevanti.' },
      { t: 'Che conviene aumentare la posizione perché è neutrale', ok: false, f: 'Aumentare la posizione moltiplica anche gamma e vega negativi: lo scenario peggiore diventa ancora più grave.' },
    ] },
    { s: 'Nicola, 31 anni, ha comprato una call a tre mesi. Dopo due mesi il sottostante è allo stesso prezzo di partenza, ma la call vale molto meno.', q: 'Come si spiega la perdita?', o: [
      { t: 'È un errore di prezzo del broker', ok: false, f: 'Non c’è errore: la perdita di valore temporale è una caratteristica di tutte le opzioni comprate.' },
      { t: 'È l’effetto del theta: il valore temporale si consuma, sempre più in fretta verso la scadenza', ok: true, f: 'Senza movimento del sottostante, il tempo erode il premio: nell’ultimo mese l’erosione accelera ancora.' },
      { t: 'Il delta della call è diventato negativo', ok: false, f: 'Il delta di una call comprata resta tra 0 e 1: la perdita viene dal tempo, non dal delta.' },
    ] },
    { s: 'Teresa, 55 anni, ha un ETF sull’S&P 500. Durante una correzione vede il VIX salire bruscamente e vuole comprare put per proteggersi.', q: 'Cosa considera?', o: [
      { t: 'Che con il VIX alto le put sono più economiche', ok: false, f: 'È il contrario: un VIX alto riflette volatilità implicita alta, quindi premi più cari.' },
      { t: 'Che conviene comprare put a scadenza brevissima senza calcoli, perché costano meno', ok: false, f: 'Costano meno in assoluto ma perdono valore molto in fretta: la protezione può svanire prima che serva.' },
      { t: 'Che ora le put costano di più e valuta se il costo è accettabile o se ridurre l’esposizione in altro modo', ok: true, f: 'La protezione costa di più proprio quando la paura è alta: confrontare il costo con alternative come ridurre l’ETF è la scelta razionale.' },
    ] },
  ],
  tip: 'Prima di comprare un’opzione guarda la volatilità implicita, non solo il prezzo: puoi avere ragione sulla direzione e perdere comunque per effetto del tempo e della volatilità.',
});
