FQC(88, {
  intro: 'CFD e certificati a leva permettono di speculare con poco capitale. Scopri come funzionano, le tutele ESMA per il retail e perché la maggior parte perde.',
  cards: [
    { t: 'Cos’è un CFD', x: 'Il contratto per differenza replica il movimento di un sottostante senza che tu lo possieda: alla chiusura incassi o paghi la differenza tra prezzo di apertura e di chiusura. È un contratto fuori borsa e la controparte è il broker.', v: { k: 'steps', s: ['Apri il contratto con il broker', 'Versi un margine', 'Il sottostante si muove', 'Alla chiusura incassi o paghi la differenza'] } },
    { t: 'Leva massima per il retail', x: 'Dal 2018 l’ESMA, e poi la CONSOB con misure nazionali permanenti, limita la leva sui CFD per i clienti al dettaglio in base al sottostante: da 30:1 sulle principali coppie di valute a 2:1 sulle criptovalute.', v: { k: 'bars', d: [['Valute principali', 30], ['Indici principali e oro', 20], ['Altre materie prime', 10], ['Singole azioni', 5], ['Criptovalute', 2]], u: ':1' } },
    { t: 'Le tutele obbligatorie', x: 'Il broker deve chiudere le posizioni quando i fondi scendono al 50% del margine minimo richiesto; non puoi perdere più del saldo del conto; sono vietati gli incentivi a fare trading ed è obbligatoria un’avvertenza standard sul rischio.', v: { k: 'icons', d: [['🛑', 'Chiusura al 50% del margine'], ['🧯', 'Protezione dal saldo negativo'], ['🚫', 'Niente bonus per fare trading'], ['⚠️', 'Avvertenza sul rischio']] } },
    { t: 'Quanti conti perdono', x: 'Ogni broker deve indicare la percentuale dei propri conti retail che perdono denaro con i CFD. Le analisi dell’ESMA del 2018 mostravano che la grande maggioranza perdeva: è un dato da leggere con attenzione, non una formalità.', v: { k: 'stat', n: '74-89%', l: 'quota di conti retail in perdita sui CFD rilevata dall’ESMA nel 2018' } },
    { t: 'Il costo di restare aperti', x: 'Oltre allo spread, le posizioni tenute oltre la giornata pagano un finanziamento calcolato sull’intera esposizione, non sul margine. Per chi tiene a lungo, questi costi pesano molto.', v: { k: 'formula', f: 'Costo overnight ≈ Esposizione × Tasso annuo ÷ 365', n: 'Es.: 20.000 € × 5% ÷ 365 ≈ 2,74 € al giorno' } },
    { t: 'CFD e certificati a leva', x: 'Anche i certificati a leva quotati (turbo, mini future, leva fissa) amplificano i movimenti. Non hanno margin call, ma possono azzerarsi al knock-out o perdere valore nel tempo per il ribilanciamento giornaliero.', v: { k: 'vs', a: ['CFD', 'Contratto fuori borsa con il broker, a margine'], b: ['Certificato a leva', 'Titolo quotato, perdita massima pari all’investito'] } },
  ],
  terms: [
    ['CFD', 'Contratto per differenza: scambia la variazione di prezzo di un sottostante senza possederlo.'],
    ['Cliente al dettaglio', 'Categoria di investitore a cui spetta il livello più alto di tutele previsto da MiFID II.'],
    ['Cliente professionale su richiesta', 'Retail che chiede di rinunciare a parte delle tutele, se soddisfa requisiti di esperienza e patrimonio.'],
    ['Protezione dal saldo negativo', 'Tutela per cui le perdite di un retail non possono superare i fondi presenti sul conto CFD.'],
    ['Chiusura al 50% del margine', 'Obbligo di chiudere le posizioni quando i fondi scendono a metà del margine minimo richiesto.'],
    ['Costo overnight', 'Finanziamento addebitato per ogni notte in cui una posizione a leva resta aperta.'],
    ['Market maker', 'Intermediario che quota i prezzi e si pone come controparte dei clienti, con possibile conflitto di interessi.'],
    ['Knock-out', 'Livello di prezzo che, se toccato, estingue un certificato turbo con perdita quasi totale.'],
  ],
  tf: [
    ['Con un CFD diventi proprietario del sottostante.', false, 'Il CFD replica solo la variazione di prezzo: non hai le azioni né il diritto di voto, e i dividendi diventano rettifiche in denaro.'],
    ['Per i clienti retail nell’UE la leva massima sui CFD su singole azioni è 5:1.', true, 'È uno dei limiti introdotti dall’ESMA nel 2018 e resi poi permanenti dalle autorità nazionali, inclusa la CONSOB.'],
    ['Grazie alla protezione dal saldo negativo, il retail non può perdere i soldi depositati sul conto.', false, 'Puoi perdere tutto il saldo del conto: la protezione impedisce solo di finire in debito con il broker.'],
    ['L’avvertenza standard indica la percentuale di conti retail che perdono denaro con quel broker.', true, 'È obbligatoria e specifica per ogni fornitore: un dato concreto su come vanno davvero i suoi clienti.'],
    ['Il costo di finanziamento overnight si calcola solo sul margine versato.', false, 'Si calcola sull’intera esposizione: con leva 20 paghi interessi su un importo 20 volte il margine.'],
    ['Chi chiede di diventare cliente professionale per avere più leva rinuncia ad alcune tutele.', true, 'Limiti di leva, chiusura al 50% e protezione dal saldo negativo previsti per il retail possono non applicarsi più.'],
    ['I broker possono offrire bonus ai clienti retail per incentivarli a fare trading in CFD.', false, 'Le misure ESMA e CONSOB vietano benefici, monetari e non, che incentivino il trading in CFD dei clienti al dettaglio.'],
    ['Nell’UE le opzioni binarie non possono essere vendute ai clienti al dettaglio.', true, 'L’ESMA ne ha vietato la vendita al retail nel 2018 e le autorità nazionali hanno reso il divieto permanente.'],
    ['Con un certificato turbo puoi perdere più del capitale investito.', false, 'Il certificato è un titolo: la perdita massima è quanto hai pagato, anche se il knock-out può azzerarlo in pochi istanti.'],
    ['Se la maggior parte dei conti perde, basta essere più disciplinati della media per guadagnare di sicuro.', false, 'Spread, finanziamento e leva giocano contro tutti: la disciplina aiuta, ma non garantisce alcun risultato.'],
  ],
  mcq: [
    { q: 'Qual è la leva massima per un cliente retail UE su un CFD sulle principali coppie di valute?', a: '30:1', w: ['50:1', '100:1', '5:1'], e: 'È il limite più alto previsto dalle misure ESMA, poi rese permanenti in Italia dalla CONSOB.' },
    { q: 'Qual è la leva massima per un cliente retail UE su un CFD su criptovalute?', a: '2:1', w: ['10:1', '20:1', '30:1'], e: 'Le cripto hanno il limite più basso perché sono il sottostante più volatile tra quelli ammessi.' },
    { q: 'Hai 1.000 € di margine e apri un CFD su un indice principale con leva 20:1. Qual è l’esposizione?', a: '20.000 €', w: ['1.000 €', '2.000 €', '50 €'], e: 'Esposizione = margine × leva = 1.000 € × 20 = 20.000 €: un movimento del 5% vale l’intero margine.' },
    { q: 'Cosa prevede la regola di chiusura al 50% del margine?', a: 'Posizioni chiuse a metà del margine richiesto', w: ['Metà delle perdite rimborsata ogni volta dal broker', 'Leva dimezzata dopo ogni perdita subita', 'Posizioni aperte solo per metà del saldo'], e: 'Quando i fondi scendono al 50% del margine minimo richiesto, il broker deve chiudere una o più posizioni.' },
    { q: 'Perché nei CFD con un market maker c’è un possibile conflitto di interessi?', a: 'Il broker è la controparte delle tue operazioni', w: ['Il CFD è sempre quotato su un mercato regolamentato', 'La CONSOB stabilisce i prezzi a cui operi', 'Il broker non guadagna nulla dallo spread'], e: 'Se il broker non copre le posizioni sul mercato, le perdite dei clienti possono diventare suoi guadagni.' },
    { q: 'Da cosa ti protegge la protezione dal saldo negativo?', a: 'Dal finire in debito oltre il saldo del conto', w: ['Dal perdere il capitale versato sul conto di trading', 'Dai costi di finanziamento overnight', 'Dalla chiusura automatica delle posizioni'], e: 'Il saldo può arrivare a zero, ma non sotto: il broker non può chiederti altro denaro per le perdite sui CFD.' },
    { q: 'Un errore comune di chi inizia con i CFD è…', a: 'usare la leva massima come se fosse consigliata', w: ['leggere l’avvertenza sui conti in perdita', 'calcolare i costi overnight prima di aprire', 'dimensionare la posizione sul rischio accettabile'], e: 'Il limite ESMA è un tetto di sicurezza, non un suggerimento: la leva va scelta in base alla perdita che puoi sostenere.' },
    { q: 'L’avvertenza di un broker dice che il 78% dei conti retail perde denaro con i CFD. Cosa ne deduci?', a: 'Che la probabilità di perdere è alta', w: ['Che il 22% guadagna in modo garantito', 'Che riguarda solo i conti professionali', 'Che il broker ha perso il 78% del capitale'], e: 'Il dato misura l’esperienza reale dei clienti di quel broker: va pesato prima di iniziare, non ignorato.' },
  ],
  fill: [
    { s: 'CFD significa contratto per ___.', a: 'differenza', w: ['deposito', 'dividendo', 'derivazione'] },
    { s: 'Per i retail, il broker deve chiudere le posizioni quando i fondi scendono al ___ del margine minimo richiesto.', a: '50%', w: ['10%', '90%', '100%'] },
    { s: 'La protezione dal saldo ___ impedisce al retail di perdere più dei fondi presenti sul conto.', a: 'negativo', w: ['positivo', 'minimo', 'medio'] },
    { s: 'Il costo per tenere aperta una posizione a leva oltre la giornata si chiama costo ___.', a: 'overnight', w: ['intraday', 'spot', 'fisso'] },
    { s: 'Un certificato turbo si estingue quando il sottostante tocca la barriera di ___.', a: 'knock-out', w: ['break-even', 'esercizio', 'rollover'] },
  ],
  order: [
    { q: 'Ordina questi CFD dalla leva massima retail più bassa alla più alta', i: ['Bitcoin', 'Azioni di una singola società', 'Petrolio', 'Indice EURO STOXX 50', 'Cambio EUR/USD'], e: 'Limiti ESMA: 2:1 cripto, 5:1 azioni, 10:1 materie prime diverse dall’oro, 20:1 indici principali, 30:1 valute principali.' },
    { q: 'Ordina cosa succede a un conto CFD retail che va in perdita', i: ['Il prezzo va contro la posizione', 'I fondi scendono sotto il margine richiesto', 'I fondi toccano il 50% del margine minimo', 'Il broker chiude le posizioni'], e: 'La chiusura al 50% limita i danni, ma in un gap il prezzo di chiusura può essere peggiore: il saldo comunque non va sotto zero.' },
  ],
  cat: [
    { q: 'È una tutela prevista per i clienti retail sui CFD?', g: [['Sì, è prevista', ['Limiti di leva per sottostante', 'Protezione dal saldo negativo', 'Avvertenza sui conti in perdita', 'Divieto di bonus per fare trading']], ['No, non esiste', ['Rimborso delle perdite subite', 'Guadagno minimo garantito', 'Costi overnight a carico del broker']]] },
    { q: 'CFD o certificato a leva quotato?', g: [['CFD', ['Contratto fuori borsa con il broker', 'Margine e chiusure forzate', 'Leva scelta entro i limiti ESMA']], ['Certificato a leva', ['Titolo quotato in borsa', 'Perdita massima pari al prezzo pagato', 'Si estingue al knock-out']]] },
  ],
  scen: [
    { s: 'Lorenzo, 23 anni, vede una pubblicità di CFD sull’oro e vuole aprire una posizione con 1.000 € a leva 20:1.', q: 'Cosa fa?', o: [
      { t: 'Apre con la leva massima, tanto c’è la protezione dal saldo negativo', ok: false, f: 'La protezione evita il debito, non la perdita: i 1.000 € possono sparire in poche ore.' },
      { t: 'Legge la percentuale di conti in perdita, calcola che un calo del 5% azzererebbe il margine e riduce l’esposizione', ok: true, f: 'Con 20.000 € di esposizione bastano piccoli movimenti per perdere tutto: ridurre la leva gli lascia margine di errore.' },
      { t: 'Chiede di diventare cliente professionale per avere più leva', ok: false, f: 'Più leva significa perdere più in fretta, e da professionale rinuncerebbe a tutele pensate proprio per lui.' },
    ] },
    { s: 'Paola, 46 anni, riceve dal broker la proposta di passare a cliente professionale per avere leva 100:1. Fa trading da pochi mesi e non lavora nel settore finanziario.', q: 'Cosa decide?', o: [
      { t: 'Rifiuta: perderebbe tutele importanti e non ha l’esperienza richiesta', ok: true, f: 'La classificazione professionale ha requisiti precisi di esperienza e patrimonio: serve a chi li ha davvero, non a chi vuole più leva.' },
      { t: 'Accetta: con più leva può guadagnare di più', ok: false, f: 'Con leva 100 basta un movimento dell’1% per perdere tutto il margine, e senza protezione dal saldo negativo potrebbe andare in debito.' },
      { t: 'Accetta e dichiara un’esperienza che non ha per qualificarsi', ok: false, f: 'Dichiarare il falso la priva di tutele senza averne i requisiti: è la combinazione peggiore possibile.' },
    ] },
    { s: 'Gianluca, 52 anni, tiene da quattro mesi un CFD long su un indice. L’indice è salito del 3%, ma il conto mostra un guadagno quasi nullo.', q: 'Cosa controlla?', o: [
      { t: 'Nulla: pensa a un errore e raddoppia la posizione', ok: false, f: 'Non è un errore ma un costo previsto: raddoppiare raddoppia anche il finanziamento giornaliero.' },
      { t: 'Passa a un CFD con leva più alta per recuperare', ok: false, f: 'Più leva aumenta costi e rischio: non risolve il problema, lo amplifica.' },
      { t: 'I costi overnight accumulati sull’intera esposizione, oltre allo spread', ok: true, f: 'Mesi di finanziamento sull’esposizione totale possono assorbire gran parte del guadagno: i CFD sono costosi da tenere a lungo.' },
    ] },
    { s: 'Silvia, 34 anni, vuole puntare su un rialzo dell’indice DAX rischiando al massimo 500 €. Confronta un CFD con un certificato turbo long.', q: 'Cosa considera?', o: [
      { t: 'Che sono identici e cambia solo il nome', ok: false, f: 'Hanno struttura diversa: uno è un contratto con il broker, l’altro un titolo quotato con barriera.' },
      { t: 'Che il turbo limita la perdita al prezzo pagato ma può azzerarsi al knock-out, mentre il CFD richiede di gestire i margini', ok: true, f: 'Comprando turbo per 500 € la perdita massima è nota; con il CFD dipende dalla dimensione e dai movimenti.' },
      { t: 'Che il CFD è più sicuro grazie alla chiusura al 50%', ok: false, f: 'La chiusura al 50% riduce i danni ma non fissa la perdita a 500 €: tutto dipende dalla dimensione della posizione.' },
    ] },
  ],
  tip: 'Prima di aprire un CFD leggi la percentuale di conti in perdita del broker, calcola l’esposizione reale e i costi overnight: la leva massima consentita è un limite, non un obiettivo.',
});
