FQC(89, {
  intro: 'Il Forex è il mercato globale delle valute, aperto 24 ore nei giorni feriali. Scopri coppie, pip, lotti, carry trade e i rischi della leva sui cambi.',
  cards: [
    { t: 'Valuta base e valuta quotata', x: 'Ogni coppia indica quante unità della seconda valuta servono per comprare una unità della prima. Comprare EUR/USD significa comprare euro e vendere dollari; venderla, il contrario.', v: { k: 'formula', f: 'EUR/USD = 1,0850 → 1 € vale 1,0850 $', n: 'La prima è la valuta base, la seconda la valuta di quotazione' } },
    { t: 'Il pip', x: 'Il pip è la variazione minima convenzionale di un cambio: la quarta cifra decimale per la maggior parte delle coppie, la seconda per quelle con lo yen. Molti broker quotano anche frazioni di pip.', v: { k: 'stat', n: '0,0001', l: 'un pip sulla maggior parte delle coppie (0,01 per quelle con lo yen)' } },
    { t: 'Quanto vale un pip su EUR/USD', x: 'Su EUR/USD un pip vale circa 10 $ per un lotto standard da 100.000 €, 1 $ per un mini lotto e 0,10 $ per un micro lotto. Conoscere il valore del pip serve a sapere quanto rischi davvero.', v: { k: 'bars', d: [['Lotto standard', 10], ['Mini lotto', 1], ['Micro lotto', 0.1]], u: '$' } },
    { t: 'Major, cross ed esotiche', x: 'Le coppie principali contro il dollaro hanno grandi volumi e spread stretti; i cross non includono il dollaro; le esotiche, con valute emergenti, hanno spread più larghi e movimenti più bruschi.', v: { k: 'scale', a: 'Più liquide', b: 'Meno liquide', d: [['EUR/USD', 5], ['USD/JPY', 12], ['EUR/GBP', 35], ['USD/TRY', 90]] } },
    { t: 'Il carry trade', x: 'Il carry trade incassa il differenziale tra i tassi di due valute, accreditato o addebitato ogni notte come swap. Funziona finché il cambio è stabile: un’inversione brusca può cancellare in pochi giorni anni di interessi.', v: { k: 'steps', s: ['Ti indebiti in una valuta a tasso basso', 'Investi in una valuta a tasso alto', 'Incassi il differenziale', 'Rischio: il cambio si muove contro'] } },
    { t: 'I rischi del Forex', x: 'Nel gennaio 2015 la Banca nazionale svizzera abbandonò il cambio minimo con l’euro: il franco si apprezzò di colpo, per qualche minuto anche di oltre il 20%, molti stop furono eseguiti molto peggio del previsto e diversi conti a leva andarono in negativo.', v: { k: 'icons', d: [['⚡', 'Shock delle banche centrali'], ['🔍', 'Spread larghi sulle notizie'], ['🏗️', 'Leva elevata'], ['🌙', 'Swap overnight']] } },
  ],
  terms: [
    ['Coppia di valute', 'Rapporto di scambio tra due valute: la prima è la base, la seconda quella di quotazione.'],
    ['Valuta base', 'Prima valuta della coppia, il cui prezzo è espresso in unità dell’altra valuta.'],
    ['Pip', 'Variazione minima convenzionale di un cambio, di solito la quarta cifra decimale.'],
    ['Lotto standard', 'Unità di contrattazione pari a 100.000 unità della valuta base.'],
    ['Carry trade', 'Strategia che si indebita in una valuta a tasso basso per investire in una a tasso più alto.'],
    ['Swap overnight', 'Accredito o addebito giornaliero legato al differenziale dei tassi tra le due valute.'],
    ['Coppia esotica', 'Coppia con la valuta di un paese emergente o minore: spread più larghi e liquidità ridotta.'],
    ['Cross', 'Coppia di valute che non include il dollaro statunitense.'],
  ],
  tf: [
    ['Se EUR/USD passa da 1,1000 a 1,1050, l’euro si è apprezzato sul dollaro.', true, 'Servono più dollari per comprare un euro: la valuta base si è rafforzata di 50 pip.'],
    ['Sulla coppia USD/JPY un pip corrisponde di solito a 0,0001.', false, 'Per le coppie con lo yen il pip è convenzionalmente 0,01, cioè la seconda cifra decimale.'],
    ['Il Forex è un mercato fuori borsa, senza una sede unica, aperto 24 ore su 24 nei giorni feriali.', true, 'Le contrattazioni passano dai centri asiatici a quelli europei e americani, seguendo i fusi orari.'],
    ['Il carry trade è privo di rischio perché incassi ogni giorno il differenziale di interesse.', false, 'Il differenziale è piccolo rispetto ai movimenti dei cambi: un’inversione brusca può annullare in pochi giorni anni di interessi.'],
    ['Su un lotto standard di EUR/USD, un movimento di 50 pip vale circa 500 $.', true, 'Un pip vale circa 10 $ per 100.000 €: 50 × 10 $ = 500 $, positivi o negativi a seconda della posizione.'],
    ['Visto che il Forex è il mercato più liquido del mondo, gli spread restano stretti anche durante le notizie importanti.', false, 'Durante dati macro o decisioni delle banche centrali gli spread possono allargarsi molto e i prezzi saltare.'],
    ['Comprare EUR/USD equivale a vendere dollari per comprare euro.', true, 'Ogni operazione sui cambi è doppia: compri la valuta base e vendi quella di quotazione.'],
    ['Le coppie esotiche hanno in genere spread più stretti delle major.', false, 'Le esotiche sono meno liquide: spread più larghi, costi più alti e movimenti più bruschi.'],
    ['Una decisione a sorpresa di una banca centrale può far eseguire gli stop loss a livelli molto peggiori del previsto.', true, 'Nei gap il prezzo salta i livelli intermedi e l’ordine viene eseguito al primo prezzo disponibile, come accadde con il franco svizzero nel 2015.'],
    ['Con leva 30:1, un movimento avverso di circa il 3,3% può azzerare il margine della posizione.', true, '100% ÷ 30 ≈ 3,3%: per un cambio è un movimento possibile in poche settimane, a volte in pochi minuti.'],
  ],
  mcq: [
    { q: 'La coppia GBP/JPY quota 190,00. Cosa indica questo prezzo?', a: 'Quanti yen servono per comprare una sterlina', w: ['Quante sterline servono per comprare uno yen', 'Il tasso di interesse annuo della sterlina', 'Il valore di un pip espresso in yen'], e: 'La sterlina è la valuta base: il prezzo dice quante unità della valuta di quotazione, lo yen, valgono una sterlina.' },
    { q: 'EUR/USD passa da 1,0820 a 1,0870. Di quanti pip si è mosso?', a: '50', w: ['5', '500', '0,5'], e: '1,0870 − 1,0820 = 0,0050, cioè 50 volte 0,0001: 50 pip.' },
    { q: 'Quante unità della valuta base compongono un mini lotto?', a: '10.000', w: ['1.000', '100.000', '1.000.000'], e: 'Lotto standard 100.000, mini lotto 10.000, micro lotto 1.000 unità della valuta base.' },
    { q: 'In un carry trade classico, quale scenario fa perdere di più?', a: 'La valuta ad alto tasso si deprezza bruscamente', w: ['La valuta ad alto tasso si apprezza lentamente', 'Il differenziale di interesse resta stabile', 'La volatilità del cambio resta molto bassa per mesi'], e: 'Il carry incassa poco ogni giorno ma è esposto al cambio: un crollo della valuta ad alto tasso cancella mesi o anni di interessi.' },
    { q: 'Quale di queste coppie è un cross?', a: 'EUR/GBP', w: ['EUR/USD', 'USD/JPY', 'GBP/USD'], e: 'Si chiamano cross le coppie che non includono il dollaro statunitense.' },
    { q: 'Hai 2.000 € sul conto e apri 0,5 lotti di EUR/USD, cioè 50.000 €. Qual è la leva effettiva?', a: '25:1', w: ['2,5:1', '50:1', '5:1'], e: 'Leva = esposizione ÷ capitale = 50.000 ÷ 2.000 = 25: un movimento del 4% contro di te azzera il conto.' },
    { q: 'Un errore comune nel Forex è…', a: 'aprire posizioni senza conoscere il valore del pip', w: ['controllare il calendario delle notizie macro', 'calcolare lo swap prima di tenere aperto la notte', 'scegliere coppie con spread più contenuti e liquidi'], e: 'Senza sapere quanto vale un pip non sai quanto rischi: è così che una posizione «piccola» diventa enorme.' },
    { q: 'Perché nel gennaio 2015 molti conti a leva sul franco svizzero andarono in negativo?', a: 'Il cambio saltò di colpo e gli stop furono eseguiti molto peggio', w: ['I broker tennero il mercato chiuso per un’intera settimana di fila', 'Lo swap overnight divenne all’improvviso molto negativo', 'La banca centrale svizzera raddoppiò la leva dei clienti'], e: 'Dopo l’abbandono del cambio minimo il prezzo saltò i livelli degli stop: le perdite superarono i margini depositati.' },
  ],
  fill: [
    { s: 'In EUR/USD l’euro è la valuta ___.', a: 'base', w: ['di quotazione', 'di riserva', 'locale'] },
    { s: 'Un ___ standard corrisponde a 100.000 unità della valuta base.', a: 'lotto', w: ['pip', 'punto', 'swap'] },
    { s: 'Il ___ trade sfrutta il differenziale tra i tassi di interesse di due valute.', a: 'carry', w: ['swing', 'day', 'spot'] },
    { s: 'Per le coppie con lo yen il pip corrisponde di solito a ___.', a: '0,01', w: ['0,0001', '1', '0,1'] },
    { s: 'L’accredito o addebito notturno legato al differenziale dei tassi si chiama ___.', a: 'swap', w: ['spread', 'pip', 'lotto'] },
  ],
  order: [
    { q: 'Ordina queste posizioni su EUR/USD dalla più piccola alla più grande', i: ['1 micro lotto', '5 micro lotti', '1 mini lotto', '0,5 lotti standard', '2 lotti standard'], e: 'In unità di euro: 1.000, 5.000, 10.000, 50.000 e 200.000. Il valore del pip cresce nella stessa proporzione.' },
    { q: 'Ordina le fasi di un carry trade che va male', i: ['Ti indebiti nella valuta a tasso basso', 'Investi nella valuta a tasso alto', 'Incassi lo swap per mesi', 'Uno shock fa crollare la valuta ad alto tasso', 'Le perdite sul cambio superano gli interessi incassati'], e: 'Il carry raccoglie piccoli guadagni regolari ed è esposto a perdite rare ma grandi, spesso quando molti escono insieme.' },
  ],
  cat: [
    { q: 'Coppia con il dollaro o cross?', g: [['Con il dollaro', ['EUR/USD', 'USD/JPY', 'GBP/USD']], ['Cross (senza dollaro)', ['EUR/GBP', 'EUR/JPY', 'GBP/CHF']]] },
    { q: 'Aumenta o riduce il rischio di un conto Forex?', g: [['Aumenta', ['Leva vicina al massimo consentito', 'Posizioni aperte durante le decisioni delle banche centrali', 'Coppie esotiche poco liquide']], ['Riduce', ['Dimensione calcolata sul valore del pip', 'Leva effettiva bassa', 'Liquidità libera sul conto']]] },
  ],
  scen: [
    { s: 'Tommaso, 27 anni, ha 4.000 € e vuole aprire un lotto standard di EUR/USD perché, dice, il cambio si muove poco.', q: 'Cosa fa?', o: [
      { t: 'Apre il lotto standard: con movimenti piccoli il rischio è basso', ok: false, f: 'Su un lotto standard 100 pip valgono circa 1.000 $: un movimento normale può costargli un quarto del conto.' },
      { t: 'Apre il lotto e toglie lo stop per non essere chiuso dal rumore', ok: false, f: 'Senza stop, con una leva così alta, un movimento contrario può portarlo alla chiusura forzata con perdite pesanti.' },
      { t: 'Calcola il valore del pip e sceglie micro lotti coerenti con la perdita che accetta', ok: true, f: 'Partendo dal valore del pip può dimensionare la posizione sul rischio: con micro lotti 100 pip valgono circa 10 $.' },
    ] },
    { s: 'Ludovica, 44 anni, nota che una valuta emergente offre tassi molto più alti dell’euro e pensa a un carry trade a leva per incassare lo swap.', q: 'Come ragiona?', o: [
      { t: 'Usa la leva massima per moltiplicare lo swap incassato', ok: false, f: 'La leva moltiplica anche le perdite sul cambio: un deprezzamento del 5-10% azzererebbe la posizione.' },
      { t: 'Considera che il cambio può perdere più del differenziale incassato e, se procede, usa leva bassa e dimensione piccola', ok: true, f: 'Il differenziale è il premio per un rischio reale: le valute ad alto tasso possono deprezzarsi bruscamente.' },
      { t: 'Pensa che un tasso alto renda la valuta più forte nel tempo', ok: false, f: 'Spesso i tassi alti compensano inflazione e rischi più elevati: la valuta può deprezzarsi proprio per questo.' },
    ] },
    { s: 'Emanuele, 35 anni, ha una posizione aperta su EUR/USD. Alle 14:30 escono i dati sul lavoro negli Stati Uniti e il broker avvisa che gli spread possono allargarsi.', q: 'Cosa fa?', o: [
      { t: 'Riduce o chiude la posizione prima del dato, se non vuole correre quel rischio', ok: true, f: 'Un dato macro importante può far saltare il prezzo: ridurre l’esposizione prima è una scelta di gestione del rischio, non di previsione.' },
      { t: 'Apre una posizione più grande per sfruttare il movimento', ok: false, f: 'Puntare sulla direzione di un dato è una scommessa: con spread larghi e salti di prezzo il rischio è massimo.' },
      { t: 'Sposta lo stop molto vicino al prezzo per sentirsi protetto', ok: false, f: 'Con spread allargati uno stop troppo vicino può scattare anche solo per l’allargamento, o essere eseguito peggio.' },
    ] },
    { s: 'Carla, 58 anni, ha una piccola impresa e tra sei mesi deve pagare una fornitura in dollari. Teme che nel frattempo l’euro si indebolisca.', q: 'Cosa valuta?', o: [
      { t: 'Aprire CFD a leva su EUR/USD per guadagnare sul cambio', ok: false, f: 'Così aggiunge un rischio speculativo a quello dell’impresa, con la possibilità di perdere molto più di quanto voleva proteggere.' },
      { t: 'Non fare nulla e sperare che il cambio migliori', ok: false, f: 'È una scelta possibile, ma lascia l’impresa esposta: se l’euro scende, la fornitura costerà di più.' },
      { t: 'Una copertura con la banca, per esempio un acquisto a termine dei dollari necessari', ok: true, f: 'Fissare oggi il cambio elimina l’incertezza sul costo della fornitura: è una copertura, non una speculazione.' },
    ] },
  ],
  tip: 'Prima di ogni operazione sul Forex calcola quanto vale un pip per la tua dimensione e quanti pip puoi permetterti di perdere: la leva sui cambi lavora in fretta, nei due sensi.',
});
