FQC(90, {
  intro: 'Criptovalute, blockchain e stablecoin: come funzionano, perché sono così volatili, come si custodiscono e cosa cambia con il regolamento europeo MiCA.',
  cards: [
    { t: 'La blockchain', x: 'La blockchain è un registro distribuito: molti nodi conservano una copia delle transazioni, raggruppate in blocchi collegati tra loro con funzioni crittografiche. Modificare il passato richiederebbe di controllare gran parte della rete.', v: { k: 'steps', s: ['La transazione viene trasmessa alla rete', 'I nodi la verificano', 'Viene inserita in un blocco', 'Il blocco si aggiunge alla catena'] } },
    { t: 'Bitcoin: i grandi ribassi', x: 'Bitcoin ha perso più volte circa il 75-85% dal massimo precedente (valori arrotondati per ciclo). Molte criptovalute minori hanno avuto crolli ancora più profondi, fino alla scomparsa del progetto.', v: { k: 'bars', d: [['Ciclo 2013-15', -85], ['Ciclo 2017-18', -84], ['Ciclo 2021-22', -77]], u: '%' } },
    { t: 'Chi custodisce le chiavi', x: 'Chi possiede la chiave privata controlla i fondi. Lasciare le cripto su un exchange espone al rischio di fallimento o attacco della piattaforma; l’autocustodia sposta il rischio sulla tua capacità di proteggere le chiavi.', v: { k: 'vs', a: ['Custodia su exchange', 'Comoda, ma dipendi dalla piattaforma'], b: ['Autocustodia', 'Controlli tu le chiavi, ma se le perdi nessuno le recupera'] } },
    { t: 'Wallet caldi e freddi', x: 'Il wallet non contiene le monete, che restano registrate sulla blockchain, ma le chiavi per spostarle. La frase di recupero (seed) ricostruisce il wallet: chi la ottiene può svuotarlo, e nessun servizio clienti serio te la chiederà mai.', v: { k: 'icons', d: [['🔥', 'Hot wallet: online, pratico, più esposto'], ['🧊', 'Cold wallet: offline, più sicuro'], ['🔑', 'Seed phrase: mai condividerla']] } },
    { t: 'MiCA: le regole europee', x: 'Il regolamento MiCA disciplina emittenti di cripto-attività e prestatori di servizi (CASP), che devono essere autorizzati. Aumenta trasparenza e tutele, ma non garantisce il valore delle cripto né prevede fondi di garanzia sui depositi.', v: { k: 'stat', n: '2024', l: 'anno in cui il regolamento europeo MiCA è entrato in applicazione' } },
    { t: 'Stablecoin: stabili, non senza rischi', x: 'Le stablecoin puntano a un valore stabile rispetto a una valuta. MiCA distingue i token di moneta elettronica (EMT) e i token collegati ad attività (ART). Il crollo della stablecoin algoritmica TerraUSD nel 2022 ha mostrato che l’aggancio può saltare.', v: { k: 'scale', a: 'Volatilità bassa', b: 'Volatilità altissima', d: [['Stablecoin in euro', 8], ['Bitcoin', 70], ['Token piccolo appena lanciato', 95]] } },
  ],
  terms: [
    ['Blockchain', 'Registro distribuito di transazioni, organizzato in blocchi collegati crittograficamente.'],
    ['Chiave privata', 'Codice segreto che autorizza a spostare le cripto-attività associate a un indirizzo.'],
    ['Seed phrase', 'Sequenza di parole che permette di ricostruire un wallet e tutte le sue chiavi.'],
    ['Cold wallet', 'Portafoglio che conserva le chiavi offline, meno esposto ad attacchi via internet.'],
    ['Exchange', 'Piattaforma che permette di comprare e vendere cripto-attività e spesso le custodisce.'],
    ['Stablecoin', 'Cripto-attività progettata per mantenere un valore stabile rispetto a una valuta o ad altre attività.'],
    ['MiCA', 'Regolamento UE che disciplina l’emissione di cripto-attività e i prestatori di servizi su di esse.'],
    ['CASP', 'Prestatore di servizi per le cripto-attività, che nell’UE deve essere autorizzato secondo MiCA.'],
  ],
  tf: [
    ['Il wallet contiene materialmente le criptovalute.', false, 'Le cripto sono registrate sulla blockchain: il wallet custodisce le chiavi che permettono di spostarle.'],
    ['Chi conosce la tua seed phrase può trasferire tutte le cripto del tuo wallet.', true, 'La seed phrase ricostruisce le chiavi: va custodita offline e non comunicata a nessuno, nemmeno a un sedicente supporto tecnico.'],
    ['Il regolamento MiCA garantisce un rimborso se una criptovaluta perde valore.', false, 'MiCA regola emittenti e prestatori di servizi, ma non protegge dal rischio di mercato: il prezzo può crollare comunque.'],
    ['Se l’exchange dove tieni le cripto fallisce, potresti non riaverle o riaverle solo in parte.', true, 'Casi come Mt. Gox e FTX lo hanno dimostrato. MiCA impone di separare i beni dei clienti, ma il rischio operativo non sparisce.'],
    ['Una stablecoin non può mai perdere il suo aggancio.', false, 'L’aggancio dipende da riserve, fiducia e meccanismi di rimborso: alcune stablecoin lo hanno perso, a volte in modo definitivo.'],
    ['Le transazioni registrate su una blockchain pubblica di solito non si possono annullare.', true, 'Non c’è una banca che possa stornarle: un trasferimento all’indirizzo sbagliato è in genere perso.'],
    ['In Italia le cripto-attività hanno una disciplina fiscale specifica, con un’aliquota che può cambiare con le leggi di bilancio.', true, 'Le regole sono cambiate più volte: prima di vendere verifica la normativa in vigore o chiedi a un professionista.'],
    ['Una criptovaluta a bassa capitalizzazione è più sicura perché ha più margini di crescita.', false, 'Le cripto piccole sono in genere più volatili, meno liquide e più esposte a manipolazioni e all’abbandono del progetto.'],
    ['Nell’UE chi presta servizi su cripto-attività ai clienti deve essere autorizzato come CASP.', true, 'L’autorizzazione si verifica nei registri pubblici; in Italia le autorità competenti sono CONSOB e Banca d’Italia.'],
    ['Bitcoin è un bene rifugio che sale sempre quando le borse crollano.', false, 'In fasi di stress come marzo 2020 e il 2022 Bitcoin è sceso insieme alle azioni: non si è comportato da rifugio affidabile.'],
  ],
  mcq: [
    { q: 'Cosa controlla davvero chi possiede la chiave privata di un indirizzo?', a: 'La possibilità di spostare le cripto associate', w: ['Il prezzo di mercato della criptovaluta', 'Le regole del protocollo della rete', 'L’identità reale di tutti gli altri utenti della rete'], e: 'La chiave privata firma le transazioni: chi la possiede dispone dei fondi, chiunque sia il titolare «ufficiale».' },
    { q: 'Qual è il rischio principale di lasciare tutte le cripto su un exchange?', a: 'Fallimento, frode o attacco alla piattaforma', w: ['Perdere la seed phrase del proprio cold wallet', 'Pagare commissioni di rete molto più basse', 'Non poter seguire il prezzo in tempo reale'], e: 'Sull’exchange le chiavi le ha la piattaforma: se fallisce o viene violata, il cliente diventa un creditore.' },
    { q: 'Cosa disciplina il regolamento europeo MiCA?', a: 'Emittenti di cripto-attività e prestatori di servizi', w: ['Il prezzo massimo delle criptovalute in euro', 'Le aliquote fiscali applicate dai singoli Stati membri', 'Il funzionamento tecnico della rete Bitcoin'], e: 'MiCA fissa regole di autorizzazione, trasparenza e condotta per emittenti e CASP, non i prezzi né le tasse.' },
    { q: 'Cos’è, secondo MiCA, un token di moneta elettronica (EMT)?', a: 'Un token che punta al valore di una valuta ufficiale', w: ['Un token legato a un paniere di azioni quotate in borsa', 'Una moneta a corso legale emessa dalla BCE', 'Una cripto senza alcun emittente identificabile'], e: 'L’EMT mira a mantenere un valore stabile facendo riferimento a una sola valuta ufficiale, come l’euro.' },
    { q: 'Il «supporto tecnico» del tuo wallet ti scrive e chiede la seed phrase per risolvere un problema. Di cosa si tratta?', a: 'Di un tentativo di furto', w: ['Di una normale verifica', 'Di un obbligo previsto da MiCA', 'Di un controllo antiriciclaggio'], e: 'Nessun servizio legittimo chiede la seed phrase: chi la ottiene può svuotare il wallet in pochi secondi.' },
    { q: 'Perché un trasferimento di cripto sbagliato è difficile da recuperare?', a: 'Nessuno può stornare una transazione confermata', w: ['Le banche lo bloccano per trenta giorni', 'Il regolamento MiCA vieta qualsiasi forma di rimborso', 'Il wallet si cancella dopo ogni invio'], e: 'Una volta confermata, la transazione è definitiva: non esiste un intermediario centrale che possa annullarla.' },
    { q: 'Un errore comune di chi compra cripto è…', a: 'investire più di quanto potrebbe perdere', w: ['conservare la seed phrase offline', 'verificare l’autorizzazione della piattaforma', 'attivare l’autenticazione a due fattori'], e: 'Con cali storici dell’80% e oltre, la quota in cripto deve essere una somma la cui perdita non comprometta i tuoi obiettivi.' },
    { q: 'Quale affermazione descrive meglio la storia della volatilità di Bitcoin?', a: 'Ha avuto più cali superiori al 70% dal massimo', w: ['Non ha mai perso più del 20% in un anno', 'Si è sempre mosso in linea con i titoli di Stato', 'È diventato stabile dopo l’arrivo di MiCA'], e: 'Nei cicli 2013-15, 2017-18 e 2021-22 Bitcoin ha perso circa il 75-85% dal massimo precedente.' },
  ],
  fill: [
    { s: 'Il registro distribuito su cui sono annotate le transazioni in cripto si chiama ___.', a: 'blockchain', w: ['wallet', 'exchange', 'stablecoin'] },
    { s: 'Un wallet che conserva le chiavi offline si definisce ___ wallet.', a: 'cold', w: ['hot', 'smart', 'web'] },
    { s: 'La ___ phrase permette di ricostruire un wallet e va custodita offline.', a: 'seed', w: ['hash', 'block', 'token'] },
    { s: 'Il regolamento europeo sui mercati delle cripto-attività si chiama ___.', a: 'MiCA', w: ['MiFID', 'EMIR', 'PSD2'] },
    { s: 'Una ___ è progettata per mantenere un valore stabile rispetto a una valuta.', a: 'stablecoin', w: ['altcoin', 'memecoin', 'blockchain'] },
  ],
  order: [
    { q: 'Ordina dal meno volatile al più volatile, in condizioni normali', i: ['Conto deposito in euro', 'Stablecoin in euro', 'ETF azionario globale', 'Bitcoin', 'Token appena lanciato a bassa capitalizzazione'], e: 'La volatilità cresce passando dai depositi alle azioni diversificate, a Bitcoin, fino ai token piccoli e poco liquidi.' },
    { q: 'Ordina i passaggi per spostare cripto da un exchange a un cold wallet', i: ['Configuri il cold wallet', 'Scrivi la seed phrase su carta e la custodisci offline', 'Invii una piccola somma di prova', 'Verifichi l’arrivo e trasferisci il resto'], e: 'La seed va messa al sicuro prima di ricevere fondi, e l’invio di prova evita di perdere tutto per un indirizzo sbagliato.' },
  ],
  cat: [
    { q: 'Buona pratica o errore?', g: [['Buona pratica', ['Seed phrase su carta in un luogo sicuro', 'Verificare l’autorizzazione MiCA della piattaforma', 'Invio di prova prima di un grande trasferimento']], ['Errore', ['Foto della seed phrase sul telefono', 'Seguire i consigli di sconosciuti sui social', 'Investire il fondo di emergenza in cripto']]] },
    { q: 'Hot wallet o cold wallet?', g: [['Hot wallet', ['App sullo smartphone', 'Estensione del browser', 'Programma su un computer sempre connesso']], ['Cold wallet', ['Dispositivo hardware scollegato', 'Chiavi generate su un computer mai connesso', 'Wallet di carta chiuso in cassaforte']]] },
  ],
  scen: [
    { s: 'Federico, 24 anni, ha messo 3.000 € in una criptovaluta poco conosciuta consigliata da un influencer. In una settimana il prezzo è salito del 200%.', q: 'Cosa fa?', o: [
      { t: 'Chiede un prestito per comprarne ancora', ok: false, f: 'Indebitarsi per comprare un asset così volatile può lasciargli un debito da ripagare anche se il token si azzera.' },
      { t: 'Valuta di ridurre la posizione, ricordando che le cripto piccole possono crollare altrettanto in fretta', ok: true, f: 'Un rialzo così rapido su un token poco liquido è spesso seguito da crolli altrettanto rapidi: mettere al sicuro una parte riduce il rischio.' },
      { t: 'Convince i genitori a investire i loro risparmi', ok: false, f: 'Un rialzo recente non è una prova di qualità: espone anche i genitori a una possibile perdita totale.' },
    ] },
    { s: 'Rosa, 57 anni, tiene tutte le sue cripto su un exchange estero che offre il 12% annuo sui depositi. Non sa se la piattaforma è autorizzata nell’UE.', q: 'Cosa fa?', o: [
      { t: 'Verifica l’autorizzazione come CASP e valuta di ridurre l’esposizione o passare all’autocustodia', ok: true, f: 'Rendimenti alti su piattaforme non verificate sono un segnale di rischio, come hanno mostrato i fallimenti del 2022.' },
      { t: 'Aumenta il deposito per sfruttare il rendimento', ok: false, f: 'Più deposito significa più esposizione alla piattaforma: se fallisce, potrebbe perdere tutto.' },
      { t: 'Non cambia nulla: le cripto sono sulla blockchain e quindi al sicuro', ok: false, f: 'Sull’exchange le chiavi le ha la piattaforma: in caso di fallimento Rosa sarebbe solo una creditrice.' },
    ] },
    { s: 'Michele, 42 anni, ha comprato un cold wallet. Durante la configurazione il dispositivo gli mostra 24 parole di recupero.', q: 'Come le conserva?', o: [
      { t: 'Le salva in una nota sul telefono sincronizzata nel cloud', ok: false, f: 'Così la seed torna online: se il telefono o il cloud vengono violati, il cold wallet diventa inutile.' },
      { t: 'Le invia per email a sé stesso per non perderle', ok: false, f: 'Le email possono essere violate o lette da terzi: è uno dei modi più comuni in cui le seed vengono rubate.' },
      { t: 'Le scrive su carta e le custodisce offline in un luogo sicuro, senza fotografarle', ok: true, f: 'Tenere la seed lontano da qualsiasi dispositivo connesso è il senso stesso di un cold wallet.' },
    ] },
    { s: 'Anna, 30 anni, vuole investire in cripto una parte dei risparmi destinati all’anticipo della casa, che comprerà tra un anno.', q: 'Cosa decide?', o: [
      { t: 'Investe tutto in Bitcoin perché nel lungo periodo è salito', ok: false, f: 'Un anno non è il lungo periodo: Bitcoin ha avuto più cali dell’80% nel giro di uno-due anni.' },
      { t: 'Non usa quei soldi: con un orizzonte di un anno un calo del 50% è plausibile', ok: true, f: 'I soldi con una scadenza vicina non devono stare su asset che possono dimezzarsi in pochi mesi.' },
      { t: 'Li mette in una stablecoin con rendimento alto offerto da una piattaforma sconosciuta', ok: false, f: 'Il rischio si sposta sulla piattaforma e sull’aggancio della stablecoin: per soldi che servono tra un anno non è una scelta prudente.' },
    ] },
  ],
  tip: 'Investi in cripto solo una quota che puoi perdere del tutto, usa piattaforme autorizzate, custodisci la seed phrase offline e ricorda che nessun regolamento protegge dal crollo dei prezzi.',
});
