FQC(91, {
  intro: 'Quanto puntare su ogni operazione? Impara a dimensionare le posizioni perché nessun singolo errore possa affondare il tuo capitale.',
  cards: [
    { t: 'Il rischio per operazione', x: 'Molti trader professionisti limitano la perdita massima di ogni operazione all’1-2% del capitale. Così anche una lunga serie di errori lascia il conto in piedi e la strategia può continuare.', v: { k: 'stat', n: '1-2%', l: 'del capitale a rischio per singola operazione' } },
    { t: 'La formula del position sizing', x: 'La quantità si ricava dal rischio, non dall’istinto: quanto accetti di perdere in euro diviso la distanza tra prezzo d’ingresso e stop. Prima si decide lo stop, poi la dimensione.', v: { k: 'formula', f: 'Quantità = (Capitale × % rischio) ÷ (Ingresso − Stop)', n: 'Es.: (20.000 € × 1%) ÷ (50 € − 46 €) = 50 azioni' } },
    { t: 'Importo fisso o rischio fisso?', x: 'Investire sempre la stessa cifra non significa rischiare sempre lo stesso: con uno stop più largo perdi di più. La regola del rischio fisso rende uguale la perdita potenziale di ogni operazione.', v: { k: 'vs', a: ['Importo fisso', 'Sempre 5.000 € investiti: la perdita varia con lo stop'], b: ['Rischio fisso', 'Sempre l’1% a rischio: varia la quantità'] } },
    { t: 'Dieci perdite di fila', x: 'Serie di dieci perdite capitano anche a strategie valide. Con l’1% a rischio resta circa il 90% del capitale; con il 10% ne resta circa un terzo, e risalire diventa durissimo.', v: { k: 'bars', d: [['Rischio 1%', 90], ['Rischio 2%', 82], ['Rischio 5%', 60], ['Rischio 10%', 35]], u: '%' } },
    { t: 'Il rischio di portafoglio', x: 'Cinque titoli bancari con l’1% di rischio ciascuno si muovono insieme: in una crisi del settore è come avere una sola posizione da 5%. Conta il rischio complessivo, non solo quello della singola operazione.', v: { k: 'scale', a: 'Rischio complessivo basso', b: 'Rischio complessivo alto', d: [['Posizioni poco correlate', 25], ['Stesso settore', 70], ['Tutto su un titolo', 95]] } },
    { t: 'Volatilità e dimensione', x: 'Un titolo più volatile richiede uno stop più ampio, quindi una posizione più piccola a parità di rischio. Molti usano l’ATR, l’escursione media dei prezzi, per tarare la distanza dello stop.', v: { k: 'steps', s: ['Scegli la % di rischio', 'Fissa lo stop (es. 2 × ATR)', 'Misura la distanza', 'Ricava la quantità'] } },
  ],
  terms: [
    ['Position sizing', 'Calcolo di quanto capitale destinare a una singola operazione in base alla perdita accettata.'],
    ['Rischio per operazione', 'Perdita massima accettata su un singolo trade, espressa in percentuale del capitale.'],
    ['Regola del rischio fisso', 'Metodo che mantiene costante la quota di capitale esposta a perdita, adattando la quantità.'],
    ['Rischio di rovina', 'Probabilità di perdere tanto capitale da non poter più proseguire la propria strategia.'],
    ['Distanza dallo stop', 'Differenza tra prezzo d’ingresso e livello di uscita in perdita: fissa la perdita per unità.'],
    ['ATR', 'Indicatore dell’escursione media dei prezzi in un periodo, usato per tarare stop e posizioni.'],
    ['Esposizione complessiva', 'Totale del capitale coinvolto in tutte le posizioni aperte, considerate insieme.'],
    ['Martingala', 'Tecnica che raddoppia la posizione dopo ogni perdita per recuperare: rischio in crescita esponenziale.'],
  ],
  tf: [
    ['Con la regola dell’1%, su un capitale di 30.000 € la perdita prevista se scatta lo stop è di 300 €.', true, 'L’1% di 30.000 € è 300 €: è la perdita accettata allo stop, non l’importo investito nell’operazione.'],
    ['Rischiare l’1% del capitale significa investire solo l’1% del capitale in ogni operazione.', false, 'L’1% è la perdita accettata se scatta lo stop. L’importo investito può essere molto più grande: dipende dalla distanza dello stop.'],
    ['A parità di rischio in euro, uno stop più lontano dall’ingresso comporta una posizione più piccola.', true, 'Quantità = rischio ÷ distanza: se la distanza raddoppia, la quantità si dimezza per mantenere invariata la perdita potenziale.'],
    ['Se una strategia vince il 60% delle volte, rischiare il 20% del capitale per operazione è prudente.', false, 'Con il 40% di perdite, serie di quattro errori di fila sono frequenti: al 20% per operazione il capitale scenderebbe sotto la metà.'],
    ['Cinque posizioni con l’1% di rischio su titoli molto correlati possono comportarsi come un’unica posizione da circa il 5%.', true, 'Se si muovono insieme, gli stop possono scattare tutti nello stesso momento: il rischio effettivo è la somma dei singoli rischi.'],
    ['Dopo una serie di guadagni conviene alzare la percentuale di rischio perché si è “in forma”.', false, 'Le operazioni passate non cambiano le probabilità delle prossime: è eccesso di fiducia. La % resta fissa; cresce in euro solo se cresce il capitale.'],
    ['Con il rischio fisso in percentuale, dopo una perdita il rischio in euro dell’operazione successiva si riduce.', true, 'La percentuale si applica al capitale aggiornato: se il capitale scende, scende anche l’importo a rischio e le perdite rallentano.'],
    ['Il position sizing serve solo ai trader: chi investe a lungo termine non deve badare al peso delle posizioni.', false, 'Anche nel lungo periodo conta quanto pesa ogni titolo: una singola azione al 40% del portafoglio è un forte rischio di concentrazione.'],
    ['L’ATR può essere usato per adattare la distanza dello stop alla volatilità del titolo.', true, 'L’ATR misura l’escursione media dei prezzi: uno stop a un multiplo dell’ATR evita di uscire per le normali oscillazioni.'],
    ['Raddoppiare la posizione dopo ogni perdita è un modo prudente per recuperare in fretta.', false, 'È la martingala: aumenta l’esposizione proprio quando le cose vanno male e una serie negativa abbastanza lunga può azzerare il conto.'],
  ],
  mcq: [
    { q: 'Capitale 25.000 €, rischio 1%, ingresso a 40 €, stop a 38 €. Quante azioni compri?', a: '125', w: ['250', '625', '62'], e: 'Rischio in euro: 25.000 × 1% = 250 €. Rischio per azione: 40 − 38 = 2 €. Quantità: 250 ÷ 2 = 125 azioni.' },
    { q: 'Nella regola del rischio fisso, che cosa determina la quantità da acquistare?', a: 'Il rischio in euro diviso la distanza dallo stop', w: ['Il prezzo dell’azione diviso il capitale', 'Il numero di operazioni aperte nel mese', 'Il guadagno atteso diviso la commissione'], e: 'Prima fissi quanto perdere (es. 1% del capitale) e dove uscire; la quantità è la conseguenza: rischio ÷ distanza ingresso-stop.' },
    { q: 'Perché molti limitano il rischio per operazione all’1-2% del capitale?', a: 'Per reggere le inevitabili serie di perdite', w: ['Per garantirsi un rendimento minimo annuo', 'Perché lo impone un regolamento CONSOB', 'Per ridurre le imposte sulle plusvalenze'], e: 'Nessuna strategia vince sempre. Un rischio piccolo per operazione permette di superare le serie negative senza danni irreparabili.' },
    { q: 'Hai 4 posizioni su titoli petroliferi, ciascuna con rischio 1,5%. Qual è la valutazione più corretta?', a: 'Il rischio effettivo si avvicina al 6%', w: ['Il rischio resta 1,5%: conta la singola posizione', 'Il rischio è nullo: le posizioni si compensano', 'Il rischio scende allo 0,4%: si divide per quattro'], e: 'Titoli dello stesso settore tendono a muoversi insieme: uno shock sul petrolio può far scattare tutti gli stop, sommando le perdite.' },
    { q: 'Qual è il limite di chi investe sempre lo stesso importo in ogni operazione?', a: 'Rischia cifre diverse a seconda dello stop', w: ['Paga commissioni più alte degli altri', 'Non può usare ordini con limite di prezzo', 'Finisce per diversificare troppo'], e: 'Con 5.000 € investiti, uno stop al 3% rischia 150 €, uno al 10% rischia 500 €. Il rischio fisso rende uniforme la perdita potenziale.' },
    { q: 'Quale affermazione sul position sizing è un mito?', a: 'Con un segnale forte si può puntare tutto', w: ['La quantità dipende dalla distanza dello stop', 'Il rischio si calcola sul capitale totale', 'Posizioni correlate sommano il loro rischio'], e: 'Nessun segnale è certo. Puntare tutto su una singola idea espone a perdite che le vincite successive difficilmente possono compensare.' },
    { q: 'Un trader rischia il 2% per operazione e subisce 10 perdite di fila. Quanto capitale gli resta, circa?', a: 'Circa l’82%', w: ['Circa il 98%', 'Circa il 60%', 'Circa il 50%'], e: 'Ogni perdita è il 2% del capitale residuo: 0,98^10 ≈ 0,82. Con il rischio fisso in percentuale le perdite in euro si riducono man mano.' },
    { q: 'Il titolo A ha un ATR di 1 €, il titolo B di 4 €. Con stop a 2 × ATR e stesso rischio in euro, cosa succede?', a: 'Su B la quantità sarà quattro volte più piccola', w: ['Su B la quantità sarà quattro volte più grande', 'Le due quantità saranno identiche', 'Su B non è possibile usare uno stop'], e: 'Lo stop di B dista 8 €, quello di A 2 €. Per rischiare gli stessi euro, su B servono quattro volte meno azioni.' },
  ],
  fill: [
    { s: 'La regola dell’1% fissa la ___ massima accettata per operazione, non l’importo investito.', a: 'perdita', w: ['commissione', 'leva', 'cedola'] },
    { s: 'Quantità = rischio in euro ÷ distanza tra prezzo d’ingresso e ___.', a: 'stop', w: ['dividendo', 'massimo storico', 'benchmark'] },
    { s: 'Posizioni su titoli molto ___ sommano il loro rischio come se fossero una sola.', a: 'correlati', w: ['liquidi', 'economici', 'capitalizzati'] },
    { s: 'Il rischio di ___ è la probabilità di perdere tanto da non poter più continuare.', a: 'rovina', w: ['cambio', 'tasso', 'controparte'] },
    { s: 'Raddoppiare la posizione dopo ogni perdita è la tecnica detta ___, molto pericolosa.', a: 'martingala', w: ['scalping', 'hedging', 'ribilanciamento'] },
  ],
  order: [
    { q: 'Ordina i passi per calcolare la dimensione di una posizione', i: ['Scegli la percentuale di rischio', 'Moltiplicala per il capitale', 'Dividi per la distanza dallo stop', 'Arrotonda la quantità per difetto', 'Inserisci l’ordine con lo stop'], e: 'Prima il rischio in euro, poi la divisione per la distanza ingresso-stop. Si arrotonda per difetto per non superare il rischio previsto.' },
    { q: 'Ordina dal capitale residuo più alto al più basso dopo 10 perdite di fila', i: ['Rischio 0,5% per operazione', 'Rischio 1% per operazione', 'Rischio 3% per operazione', 'Rischio 10% per operazione'], e: 'Il capitale residuo è (1 − rischio)^10: circa 95%, 90%, 74% e 35%. Un rischio alto trasforma una serie negativa in un disastro.' },
  ],
  cat: [
    { q: 'Prassi prudente o errore di gestione del rischio?', g: [['Prassi prudente', ['Rischio fisso all’1%', 'Stop deciso prima di entrare', 'Controllo delle correlazioni']], ['Errore', ['Martingala dopo una perdita', 'Tutto su un solo titolo', 'Rischio alzato dopo tre vincite']]] },
    { q: 'A parità del resto, cosa aumenta e cosa riduce la quantità acquistabile?', g: [['Aumenta la quantità', ['Capitale più grande', 'Percentuale di rischio più alta', 'Stop più vicino all’ingresso']], ['Riduce la quantità', ['Capitale più piccolo', 'Percentuale di rischio più bassa', 'Stop più lontano dall’ingresso']]] },
  ],
  scen: [
    { s: 'Marco, 34 anni, ha 15.000 € sul conto di trading e applica la regola dell’1%. Vuole comprare un titolo a 22 € con stop a 20 €, appena sotto un supporto importante.', q: 'Quante azioni compra?', o: [
      { t: '75 azioni', ok: true, f: 'Rischia 150 € (1% di 15.000 €) e 2 € per azione: 150 ÷ 2 = 75. Investe 1.650 €, ma ne mette a rischio solo 150.' },
      { t: '680 azioni, quasi tutto il capitale', ok: false, f: 'Così rischierebbe circa 1.360 €, oltre il 9% del capitale, su una sola idea: ben oltre la sua regola.' },
      { t: '7 azioni, cioè l’1% del capitale investito', ok: false, f: 'Confonde capitale investito e capitale a rischio: con 7 azioni rischierebbe 14 €, una posizione inutilmente piccola.' },
    ] },
    { s: 'Giulia, 41 anni, ha chiuso cinque operazioni vincenti di fila rischiando il 2% ciascuna. Si sente in forma e pensa di rischiare il 6% sulla prossima, “visto che il metodo funziona”.', q: 'Cosa le conviene fare?', o: [
      { t: 'Mantenere il 2% previsto dal piano', ok: true, f: 'Le vincite passate non aumentano la probabilità della prossima. Restare sulla regola protegge dall’eccesso di fiducia.' },
      { t: 'Rischiare il 6% solo su questa operazione', ok: false, f: 'Una sola perdita al 6% cancellerebbe gran parte dei guadagni delle ultime cinque operazioni.' },
      { t: 'Rischiare il 6% e togliere lo stop', ok: false, f: 'Somma due errori: rischio triplicato e perdita potenzialmente senza limite. Una serie positiva non rende il mercato prevedibile.' },
    ] },
    { s: 'Paolo, 52 anni, ha sei posizioni aperte su produttori di semiconduttori, ciascuna con rischio 1%. Arriva un nuovo segnale d’acquisto su un’altra azienda di chip.', q: 'Come si comporta?', o: [
      { t: 'Valuta il rischio di settore e rinuncia o riduce', ok: true, f: 'Le sei posizioni sono fortemente correlate: di fatto ha già circa il 6% esposto a un solo settore. Aggiungere concentrerebbe ancora il rischio.' },
      { t: 'Apre la posizione: è solo un altro 1%', ok: false, f: 'Il singolo 1% inganna: se il settore crolla, tutte le posizioni perdono insieme e il rischio reale sale al 7%.' },
      { t: 'Apre la posizione e allarga tutti gli stop', ok: false, f: 'Allargare gli stop senza ridurre le quantità aumenta il rischio di ogni posizione, oltre a concentrarlo su un settore.' },
    ] },
    { s: 'Sara, 29 anni, ha perso tre operazioni di fila con rischio 1%. Per recuperare in fretta vuole raddoppiare la quantità sulla prossima, e raddoppiarla ancora se andasse male.', q: 'Qual è la scelta più razionale?', o: [
      { t: 'Restare all’1% e rivedere le ultime operazioni', ok: true, f: 'Tre perdite di fila sono normali anche per una strategia valida. Verificare di aver seguito le regole è utile; aumentare l’esposizione no.' },
      { t: 'Raddoppiare a ogni perdita fino a recuperare', ok: false, f: 'È la martingala: il rischio cresce in modo esponenziale e una serie negativa appena più lunga può svuotare il conto.' },
      { t: 'Passare a un prodotto a leva per fare prima', ok: false, f: 'La leva amplifica anche le perdite: inseguire il recupero con più rischio è una reazione emotiva, non una strategia.' },
    ] },
  ],
  tip: 'Prima di cliccare “compra” scrivi tre numeri: quanto rischi in euro, dove esci in perdita e quante azioni ne derivano. Se non li conosci, non entrare.',
});
