FQC(92, {
  intro: 'Decidi prima dove uscire, in perdita e in guadagno: stop loss, take profit, rapporto rischio/rendimento, trailing stop e rischio di gap.',
  cards: [
    { t: 'Le due uscite', x: 'Lo stop loss chiude la posizione se il prezzo raggiunge il livello di perdita prestabilito; il take profit la chiude al raggiungimento dell’obiettivo. Entrambi vanno decisi prima di entrare, a mente fredda.', v: { k: 'icons', d: [['🛑', 'Stop loss: limita la perdita'], ['🎯', 'Take profit: incassa il guadagno'], ['📝', 'Entrambi decisi prima']] } },
    { t: 'Il rapporto rischio/rendimento', x: 'Confronta quanto puoi perdere con quanto puoi guadagnare. Un rapporto 1:3 significa che rischi 1 euro per obiettivo di guadagnarne 3. Si calcola prima di entrare, non durante il trade.', v: { k: 'formula', f: 'R/R = (Target − Ingresso) ÷ (Ingresso − Stop)', n: 'Es.: ingresso 50 €, stop 48 €, target 56 € → 6 ÷ 2 = 1:3' } },
    { t: 'R/R e percentuale di successo', x: 'Più alto è il R/R, meno spesso serve vincere per andare in pari (costi esclusi). Ma un target lontano si raggiunge più di rado: R/R e probabilità vanno sempre valutati insieme.', v: { k: 'bars', d: [['R/R 1:0,5', 67], ['R/R 1:1', 50], ['R/R 1:2', 33], ['R/R 1:3', 25]], u: '%' } },
    { t: 'Il trailing stop', x: 'Il trailing stop segue il prezzo a distanza fissa, in percentuale o in euro, quando si muove a tuo favore, ma non torna mai indietro. Protegge i guadagni lasciando correre il trend.', v: { k: 'steps', s: ['Entri a 100 € con stop a 95 €', 'Il prezzo sale a 110 €', 'Lo stop sale a 105 €', 'Se il prezzo torna a 105 €, esci in utile'] } },
    { t: 'Il rischio di gap', x: 'Se il titolo apre molto sotto lo stop, per esempio dopo una notizia notturna, lo stop a mercato viene eseguito al primo prezzo disponibile: la perdita supera quella pianificata. Uno stop limit, invece, può restare ineseguito.', v: { k: 'vs', a: ['Stop a mercato', 'Esecuzione quasi certa, prezzo incerto'], b: ['Stop limit', 'Prezzo controllato, esecuzione incerta'] } },
    { t: 'Dove mettere lo stop', x: 'Lo stop va dove l’idea di trading risulta sbagliata, per esempio oltre un supporto o a un multiplo dell’ATR, non su una cifra tonda scelta a caso. Poi è la quantità ad adattarsi allo stop.', v: { k: 'scale', a: 'Stop troppo stretto', b: 'Stop troppo largo', d: [['Dentro il rumore del prezzo', 10], ['Oltre un supporto o 2 × ATR', 50], ['Così lontano da non proteggere', 90]] } },
  ],
  terms: [
    ['Stop loss', 'Ordine che chiude la posizione in perdita al raggiungimento di un prezzo prestabilito.'],
    ['Take profit', 'Ordine che chiude la posizione in guadagno quando il prezzo tocca l’obiettivo fissato.'],
    ['Rapporto rischio/rendimento', 'Confronto tra guadagno potenziale e perdita potenziale di un’operazione.'],
    ['Trailing stop', 'Livello di uscita che si sposta a favore del prezzo mantenendo una distanza fissa, senza mai arretrare.'],
    ['Gap', 'Salto di prezzo tra una chiusura e l’apertura successiva, senza scambi ai livelli intermedi.'],
    ['Slippage', 'Differenza tra il prezzo previsto e quello a cui l’ordine viene effettivamente eseguito.'],
    ['Stop limit', 'Ordine che, raggiunto il prezzo di attivazione, diventa un ordine con limite di prezzo.'],
    ['Stop a break-even', 'Spostamento dell’uscita al prezzo d’ingresso, perché un trade in utile non finisca in perdita.'],
  ],
  tf: [
    ['Uno stop loss a mercato garantisce l’uscita esattamente al prezzo indicato.', false, 'Garantisce di fatto l’esecuzione, non il prezzo: in caso di gap o mercato veloce si esce al primo prezzo disponibile.'],
    ['Con un rapporto rischio/rendimento di 1:3, una vincita piena compensa tre perdite piene.', true, 'Ogni vincita vale +3 unità di rischio e ogni perdita −1: una vincita annulla tre perdite, costi esclusi.'],
    ['Un rapporto rischio/rendimento elevato garantisce di guadagnare nel lungo periodo.', false, 'Conta anche quanto spesso si raggiunge il target: un R/R di 1:5 centrato una volta su dieci produce in media perdite.'],
    ['In una posizione long, il trailing stop può salire ma non scende mai.', true, 'Segue il prezzo verso l’alto mantenendo la distanza fissata; quando il prezzo scende, lo stop resta fermo.'],
    ['Allontanare lo stop quando il prezzo si avvicina è una buona pratica per “dare respiro” al trade.', false, 'È uno degli errori più comuni: trasforma una piccola perdita pianificata in una grande perdita non pianificata.'],
    ['Lo stop loss va posizionato dove l’ipotesi di trading si rivela sbagliata.', true, 'Se il prezzo rompe il livello che giustificava l’ingresso, l’idea non regge più: è lì che ha senso uscire.'],
    ['Uno stop troppo stretto, dentro le normali oscillazioni del prezzo, fa uscire spesso senza un vero motivo.', true, 'Le oscillazioni casuali lo colpiscono di continuo: tante piccole perdite e costi, anche quando l’idea era corretta.'],
    ['Uno stop limit protegge sempre meglio di uno stop a mercato.', false, 'Fissa un prezzo minimo, ma se il prezzo salta oltre il limite l’ordine resta ineseguito e la perdita può continuare a crescere.'],
    ['Uno stop “mentale”, non inserito a mercato, è affidabile quanto un ordine reale.', false, 'Richiede disciplina proprio nel momento peggiore e non funziona se non sei davanti allo schermo quando serve.'],
    ['Un trailing stop può sostituire il take profit per lasciare correre un trend favorevole.', true, 'Invece di un obiettivo fisso, esci solo quando il prezzo inverte di una certa misura, catturando una parte maggiore del trend.'],
  ],
  mcq: [
    { q: 'Ingresso a 80 €, stop a 76 €, target a 92 €. Qual è il rapporto rischio/rendimento?', a: '1:3', w: ['1:2', '1:4', '1:1,5'], e: 'Rischio: 80 − 76 = 4 €. Rendimento potenziale: 92 − 80 = 12 €. Rapporto: 12 ÷ 4 = 3, cioè 1:3.' },
    { q: 'Con R/R 1:2 e costi trascurabili, quale percentuale di successo serve per andare in pari?', a: 'Circa il 33%', w: ['Il 50%', 'Circa il 67%', 'Il 20%'], e: 'Win rate di pareggio = 1 ÷ (1 + 2) ≈ 33%: una vincita da +2 compensa due perdite da −1.' },
    { q: 'Un titolo chiude a 50 € con il tuo stop a mercato a 47 €. Il giorno dopo apre a 41 € per una notizia. Cosa succede?', a: 'Lo stop viene eseguito intorno a 41 €', w: ['Lo stop viene eseguito a 47 €', 'Lo stop viene annullato in automatico', 'Lo stop viene eseguito a 50 €'], e: 'All’apertura il prezzo è già sotto lo stop: l’ordine diventa a mercato ed è eseguito al primo prezzo utile, con una perdita maggiore del previsto.' },
    { q: 'Hai un trailing stop del 10% su un titolo comprato a 100 €. Sale fino a 130 € e poi scende. Dove scatta lo stop?', a: 'Intorno a 117 €', w: ['Intorno a 90 €', 'Intorno a 110 €', 'Intorno a 127 €'], e: 'Lo stop segue il massimo: 130 € × 0,9 = 117 €. Esci con circa il 17% di guadagno invece di restituire tutto il rialzo.' },
    { q: 'Quale comportamento è l’errore più comune con lo stop loss?', a: 'Allontanarlo quando il prezzo si avvicina', w: ['Deciderlo prima di entrare', 'Calcolarlo in base all’ATR', 'Legarlo alla dimensione della posizione'], e: 'Spostare lo stop per “non uscire” nasce dall’avversione alle perdite e rende la perdita finale imprevedibile.' },
    { q: 'Qual è il principale svantaggio di uno stop limit rispetto a uno stop a mercato?', a: 'Può non essere eseguito se il prezzo salta', w: ['Costa sempre il doppio di commissioni', 'Non si può più modificare una volta inserito', 'Viene eseguito con un giorno di ritardo'], e: 'Una volta attivato diventa un ordine limite: se il prezzo scende oltre il limite senza tornarci, resti in posizione.' },
    { q: 'Spostare lo stop a break-even dopo un buon movimento a favore serve soprattutto a…', a: 'Evitare che un trade in utile chiuda in perdita', w: ['Aumentare il rendimento atteso del trade', 'Ridurre le commissioni del broker', 'Eliminare del tutto il rischio di gap'], e: 'Lo stop al prezzo d’ingresso protegge il capitale se il prezzo torna indietro, ma un gap può comunque causare una piccola perdita.' },
    { q: 'Un trader vince il 30% delle operazioni con R/R 1:3. Al lordo dei costi, qual è il risultato atteso per operazione?', a: '+0,2 volte il rischio', w: ['−0,2 volte il rischio', '+0,9 volte il rischio', 'Esattamente zero'], e: 'Valore atteso: 0,3 × 3 − 0,7 × 1 = 0,9 − 0,7 = +0,2 unità di rischio per operazione, prima di costi e slippage.' },
  ],
  fill: [
    { s: 'Il rapporto rischio/rendimento confronta il guadagno potenziale con la ___ potenziale.', a: 'perdita', w: ['commissione', 'volatilità', 'liquidità'] },
    { s: 'Il ___ stop si sposta a favore del prezzo ma non torna mai indietro.', a: 'trailing', w: ['hard', 'mental', 'time'] },
    { s: 'Quando un titolo apre molto sotto lo stop si parla di ___, e la perdita può superare quella pianificata.', a: 'gap', w: ['spread', 'pivot', 'rally'] },
    { s: 'La differenza tra prezzo atteso e prezzo eseguito si chiama ___.', a: 'slippage', w: ['leva', 'cedola', 'premio'] },
    { s: 'Lo stop va deciso ___ di entrare nell’operazione.', a: 'prima', w: ['dopo', 'invece', 'al posto'] },
  ],
  order: [
    { q: 'Ordina gli eventi di un’operazione gestita con trailing stop', i: ['Entri a 100 € con stop a 95 €', 'Il prezzo sale a 108 €', 'Lo stop viene alzato a 103 €', 'Il prezzo ripiega a 103 €', 'La posizione si chiude in utile'], e: 'Il trailing stop sale con il prezzo e resta fermo quando scende: un’operazione partita con rischio di 5 € si chiude con +3 €.' },
    { q: 'Ordina dal rapporto rischio/rendimento più favorevole al meno favorevole', i: ['Rischi 1 € per guadagnarne 4', 'Rischi 1 € per guadagnarne 2', 'Rischi 2 € per guadagnarne 2', 'Rischi 3 € per guadagnarne 1'], e: 'I rapporti sono 1:4, 1:2, 1:1 e circa 1:0,33. Più il guadagno potenziale supera il rischio, più il rapporto è favorevole.' },
  ],
  cat: [
    { q: 'Caratteristica dello stop a mercato o dello stop limit?', g: [['Stop a mercato', ['Diventa ordine a mercato all’attivazione', 'Esecuzione quasi certa', 'Prezzo finale incerto']], ['Stop limit', ['Diventa ordine limite all’attivazione', 'Non vende sotto il limite fissato', 'Esecuzione incerta']]] },
    { q: 'Buona o cattiva pratica nella gestione delle uscite?', g: [['Buona pratica', ['Stop oltre un supporto rilevante', 'Stop a break-even dopo un forte rialzo', 'Trailing stop durante un trend']], ['Cattiva pratica', ['Allontanare lo stop in perdita', 'Stop su una cifra tonda a caso', 'Nessuno stop su un prodotto a leva']]] },
  ],
  scen: [
    { s: 'Luca, 38 anni, ha comprato un titolo a 30 € con stop a 27 €. Il prezzo scende a 27,40 € e lui è tentato di spostare lo stop a 25 €, “tanto poi risale”.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Lasciare lo stop a 27 € come pianificato', ok: true, f: 'Lo stop era il punto in cui l’idea risultava sbagliata. Rispettarlo mantiene la perdita entro il rischio deciso a mente fredda.' },
      { t: 'Spostare lo stop a 25 € per dare respiro', ok: false, f: 'Così la perdita massima sale da 3 € a 5 € per azione, quasi il doppio, senza alcuna nuova informazione a sostegno.' },
      { t: 'Togliere lo stop e comprare altre azioni', ok: false, f: 'Elimina il limite alla perdita e aumenta l’esposizione su un’idea che il mercato sta smentendo.' },
    ] },
    { s: 'Elena, 45 anni, ha una posizione con stop a mercato il 5% sotto il prezzo attuale. Domani, prima dell’apertura, l’azienda pubblica i conti trimestrali.', q: 'Come valuta il rischio?', o: [
      { t: 'Riduce la posizione: un gap può saltare lo stop', ok: true, f: 'Una notizia a mercato chiuso può far aprire il titolo ben oltre lo stop. Ridurre la quantità limita il danno anche nel caso peggiore.' },
      { t: 'Sta tranquilla: lo stop garantisce al massimo il −5%', ok: false, f: 'Lo stop a mercato garantisce l’esecuzione, non il prezzo: con un’apertura a −15% la perdita sarebbe circa del 15%.' },
      { t: 'Trasforma lo stop in stop limit per avere il prezzo certo', ok: false, f: 'Con un gap oltre il limite l’ordine non verrebbe eseguito: resterebbe in posizione senza alcuna protezione.' },
    ] },
    { s: 'Davide, 27 anni, valuta un trade con stop a 2 € dall’ingresso e target a 1 €. È convinto che il target “si prenda facilmente”.', q: 'Qual è la scelta più razionale?', o: [
      { t: 'Rivedere il trade: il rapporto è sfavorevole', ok: true, f: 'Rischiando 2 per guadagnare 1, il pareggio richiede circa due vincite su tre, prima dei costi. Serve un vantaggio molto solido.' },
      { t: 'Entrare: un target vicino si raggiunge quasi sempre', ok: false, f: 'Anche lo stop, in proporzione, è vicino: la sensazione di facilità non sostituisce il calcolo del valore atteso.' },
      { t: 'Entrare con quantità doppia per compensare', ok: false, f: 'Aumentare la quantità non migliora il rapporto rischio/rendimento: raddoppia solo la perdita in caso di errore.' },
    ] },
    { s: 'Chiara, 50 anni, ha un titolo in guadagno del 25% dentro un trend rialzista forte. Teme di restituire il guadagno, ma non vuole chiudere troppo presto.', q: 'Cosa può fare?', o: [
      { t: 'Alzare lo stop o usare un trailing stop', ok: true, f: 'Protegge una parte del guadagno e lascia spazio al trend: se il prezzo inverte, esce comunque in utile.' },
      { t: 'Lasciare lo stop iniziale, tanto il trend è forte', ok: false, f: 'Con lo stop iniziale potrebbe restituire tutto il guadagno e chiudere persino in perdita.' },
      { t: 'Togliere lo stop: ormai è in guadagno', ok: false, f: 'Essere in utile non elimina il rischio: un’inversione brusca può cancellare il guadagno senza alcun limite.' },
    ] },
  ],
  tip: 'Inserisci stop e target nel momento in cui apri la posizione, non dopo. E non spostare mai lo stop nella direzione che aumenta la perdita.',
});
