FQC(93, {
  intro: 'Perché un −50% richiede un +100% per tornare in pari? Drawdown, tempi di recupero e come evitare che un calo diventi una perdita definitiva.',
  cards: [
    { t: 'L’asimmetria delle perdite', x: 'Dopo una perdita il capitale è più piccolo, quindi per tornare al punto di partenza serve un rendimento percentuale più alto di quello perso. È matematica, non sfortuna.', v: { k: 'formula', f: 'Guadagno per recuperare = 1 ÷ (1 − perdita) − 1', n: 'Es.: −50% → 1 ÷ 0,5 − 1 = +100%' } },
    { t: 'Più si scende, più è ripida', x: 'Un −10% si recupera con circa +11%, un −33% richiede +50%, un −75% addirittura +300%. Le perdite profonde sono difficilissime da recuperare: meglio evitarle che curarle.', v: { k: 'bars', d: [['−10%', 11], ['−20%', 25], ['−33%', 50], ['−50%', 100], ['−75%', 300]], u: '%' } },
    { t: 'Che cos’è il drawdown', x: 'Il drawdown misura il calo dal massimo precedente al minimo successivo. Il massimo drawdown è il peggiore registrato in un periodo: dice quanto male è andata, nel momento peggiore, a chi era investito.', v: { k: 'steps', s: ['Picco a 100', 'Minimo a 70: drawdown −30%', 'Recupero', 'Nuovo massimo oltre 100'] } },
    { t: 'Anche il tempo conta', x: 'Un drawdown ha una profondità e una durata. Dopo la bolla del 2000 l’indice Nasdaq ha impiegato circa 15 anni per tornare ai massimi nominali. Il tempo “sott’acqua” mette alla prova la pazienza.', v: { k: 'stat', n: '≈15 anni', l: 'per il Nasdaq per tornare ai massimi del 2000' } },
    { t: 'Calo temporaneo o perdita definitiva?', x: 'Un drawdown diventa perdita definitiva se l’emittente fallisce o se vendi nel panico vicino al minimo. Gli indici ampi e diversificati in passato hanno recuperato, ma senza garanzie sui tempi.', v: { k: 'vs', a: ['Drawdown', 'Calo che può ancora essere recuperato'], b: ['Perdita permanente', 'Fallimento o vendita al minimo: non si recupera'] } },
    { t: 'Come limitare i drawdown', x: 'Non puoi eliminare i drawdown, ma puoi renderli sopportabili: diversificazione, poca o nessuna leva, posizioni ben dimensionate e un’allocazione coerente con il calo che sapresti tollerare.', v: { k: 'icons', d: [['🧺', 'Diversificazione'], ['⚖️', 'Poca o nessuna leva'], ['📐', 'Position sizing'], ['🔄', 'Ribilanciamento']] } },
  ],
  terms: [
    ['Drawdown', 'Calo percentuale dal massimo precedente al minimo successivo del valore di un investimento.'],
    ['Max drawdown', 'Peggior calo dal picco al minimo registrato in un determinato periodo di osservazione.'],
    ['Tempo di recupero', 'Periodo necessario per tornare al massimo precedente dopo un calo.'],
    ['Periodo sott’acqua', 'Fase in cui il valore resta sotto il massimo precedente, finché questo non viene superato.'],
    ['Asimmetria delle perdite', 'Fenomeno per cui un calo percentuale richiede un rialzo percentuale maggiore per essere recuperato.'],
    ['Perdita permanente', 'Perdita non più recuperabile, per fallimento dell’emittente o vendita definitiva in perdita.'],
    ['Volatility drag', 'Freno al rendimento composto causato dalle oscillazioni: alti e bassi erodono la crescita.'],
    ['Tolleranza al drawdown', 'Calo massimo che un investitore riesce a sopportare senza abbandonare il proprio piano.'],
  ],
  tf: [
    ['Dopo una perdita del 50% serve un guadagno del 100% per tornare al capitale iniziale.', true, 'Da 100 si scende a 50; per tornare a 100 bisogna raddoppiare, cioè guadagnare il 100% sulla nuova base.'],
    ['Un −20% seguito da un +20% riporta esattamente al punto di partenza.', false, '100 × 0,8 × 1,2 = 96: resti sotto del 4%. Le percentuali si applicano a basi diverse.'],
    ['Il max drawdown misura il peggior calo dal picco al minimo in un dato periodo.', true, 'È la misura del “momento peggiore”: utile per capire quanto dolore avrebbe dovuto sopportare chi era investito.'],
    ['Il drawdown si misura rispetto al prezzo di acquisto, non rispetto al massimo precedente.', false, 'Si misura dal picco precedente: anche chi è ancora in guadagno sul prezzo di acquisto può trovarsi in drawdown.'],
    ['Gli indici azionari ampi in passato hanno recuperato i drawdown, ma talvolta in tempi molto lunghi.', true, 'Storicamente i grandi indici hanno superato i massimi precedenti, ma a volte dopo molti anni; e il passato non garantisce il futuro.'],
    ['Un titolo già sceso del 60% non può scendere ancora molto: il grosso del calo è alle spalle.', false, 'Un titolo sceso del 60% può perdere un altro 60%, arrivando a −84%, o fallire. Il prezzo passato non fa da pavimento.'],
    ['A parità di media aritmetica dei rendimenti, una volatilità più alta tende a ridurre il rendimento composto.', true, 'Le oscillazioni pesano più in discesa che in salita: è il volatility drag. Per questo un portafoglio più stabile può crescere di più.'],
    ['Diversificare tra asset poco correlati non ha alcun effetto sulla profondità dei drawdown.', false, 'Se gli asset non scendono tutti insieme, il calo del portafoglio è in genere meno profondo di quello del singolo asset peggiore.'],
    ['Comprare sempre di più su un singolo titolo in calo riduce il rischio di perdita permanente.', false, 'Aumenta l’esposizione a un titolo in difficoltà: se l’azienda fallisce, perdi di più. Mediare ha senso solo dentro un piano diversificato.'],
    ['Chi vende nel panico durante un drawdown trasforma un calo temporaneo in una perdita realizzata.', true, 'Finché non vendi, un indice diversificato può recuperare; vendendo al minimo, la perdita diventa definitiva e perdi l’eventuale rimbalzo.'],
  ],
  mcq: [
    { q: 'Un portafoglio scende del 25%. Quale guadagno serve per tornare in pari?', a: 'Circa +33%', w: ['+25%', 'Circa +20%', '+50%'], e: 'Da 100 a 75; per tornare a 100 serve 100 ÷ 75 − 1 ≈ +33%. Il recupero richiede sempre più della perdita.' },
    { q: 'Un fondo passa da 100 a 140, poi scende a 98, poi risale a 120. Qual è il max drawdown del periodo?', a: '−30%', w: ['−2%', '−14%', '−42%'], e: 'Il picco è 140 e il minimo successivo 98: 98 ÷ 140 − 1 = −30%. Il drawdown si misura dal massimo, non dal valore iniziale.' },
    { q: 'Perché un −50% richiede un +100% per tornare in pari?', a: 'Il recupero parte da una base dimezzata', w: ['Le commissioni raddoppiano dopo una perdita', 'Le imposte dimezzano ogni recupero', 'I mercati salgono più lentamente di come scendono'], e: 'Il +100% si calcola su 50, non su 100. Che i mercati spesso scendano più in fretta è vero, ma non spiega questa matematica.' },
    { q: 'Quale convinzione sui drawdown è un errore comune?', a: 'Un titolo crollato non può scendere ancora molto', w: ['Il drawdown si misura dal massimo precedente', 'La leva amplifica i drawdown', 'La diversificazione può ridurre i cali'], e: 'Non esiste un pavimento: dopo un −60% un altro −60% porta a −84%. Molti titoli crollati sono poi falliti.' },
    { q: 'Cosa distingue un drawdown da una perdita permanente?', a: 'Il drawdown può ancora essere recuperato', w: ['Il drawdown riguarda solo le obbligazioni', 'La perdita permanente è sempre più piccola', 'Il drawdown non si può misurare'], e: 'Il drawdown è un calo dal picco ancora aperto; diventa permanente con il fallimento dell’emittente o con una vendita definitiva.' },
    { q: 'Quale misura riduce in modo più diretto la profondità dei drawdown di un portafoglio?', a: 'Ridurre leva e concentrazione', w: ['Controllare il prezzo più spesso', 'Aumentare il numero di operazioni', 'Preferire titoli dal prezzo unitario basso'], e: 'La leva moltiplica i cali e la concentrazione li rende dipendenti da un solo titolo. Guardare più spesso il prezzo non cambia il rischio.' },
    { q: 'Il portafoglio A fa +10% e poi −10%; il portafoglio B fa +30% e poi −30%. Come sono dopo due anni?', a: 'A perde circa l’1%, B circa il 9%', w: ['Sono entrambi in pari', 'B guadagna più di A', 'Perdono entrambi circa il 9%'], e: 'A: 1,1 × 0,9 = 0,99. B: 1,3 × 0,7 = 0,91. Stessa media aritmetica (0%), ma più volatilità significa meno rendimento composto.' },
    { q: 'Un investitore dichiara di tollerare cali del 40%, ma ha venduto tutto al primo −15%. Cosa indica?', a: 'La sua tolleranza reale è più bassa', w: ['Il mercato era sicuramente sopravvalutato', 'Il −15% era già una perdita permanente', 'Doveva usare più leva per recuperare'], e: 'Il questionario misura le intenzioni, il drawdown misura i comportamenti. Il piano va tarato sulla tolleranza dimostrata.' },
  ],
  fill: [
    { s: 'Il ___ è il calo dal massimo precedente al minimo successivo.', a: 'drawdown', w: ['dividendo', 'rendimento', 'spread'] },
    { s: 'Per recuperare una perdita del 50% serve un guadagno del ___.', a: '100%', w: ['50%', '75%', '150%'] },
    { s: 'Vendere nel panico al minimo trasforma un calo temporaneo in una perdita ___.', a: 'realizzata', w: ['virtuale', 'apparente', 'latente'] },
    { s: 'Le oscillazioni frenano il rendimento composto: è il cosiddetto volatility ___.', a: 'drag', w: ['spread', 'gap', 'hedge'] },
    { s: 'Il tempo trascorso sotto il massimo precedente si chiama periodo ___.', a: 'sott’acqua', w: ['di grazia', 'di carenza', 'cedolare'] },
  ],
  order: [
    { q: 'Ordina i drawdown dal più facile al più difficile da recuperare', i: ['−10%', '−25%', '−40%', '−60%', '−80%'], e: 'Per tornare in pari servono circa +11%, +33%, +67%, +150% e +400%: il recupero cresce molto più in fretta della perdita.' },
    { q: 'Ordina le fasi di un drawdown', i: ['Massimo precedente', 'Inizio del calo', 'Minimo (fondo)', 'Fase di recupero', 'Nuovo massimo'], e: 'Il drawdown va dal picco al fondo; il periodo sott’acqua dura finché il valore non supera il massimo precedente.' },
  ],
  cat: [
    { q: 'Riduce o amplifica i drawdown di un portafoglio?', g: [['Riduce', ['Diversificazione tra asset class', 'Position sizing prudente', 'Quota di obbligazioni di qualità']], ['Amplifica', ['Leva finanziaria', 'Concentrazione su un titolo', 'Mediare al ribasso senza limiti']]] },
    { q: 'Per tornare in pari serve meno o più del +50%?', g: [['Meno del +50%', ['Perdita del 10%', 'Perdita del 20%', 'Perdita del 30%']], ['Più del +50%', ['Perdita del 40%', 'Perdita del 50%', 'Perdita del 70%']]] },
  ],
  scen: [
    { s: 'Roberto, 46 anni, ha perso il 50% del conto di trading in un anno. Vuole recuperare entro dicembre e pensa di usare una leva elevata su pochi titoli molto volatili.', q: 'Qual è la scelta più razionale?', o: [
      { t: 'Accettare tempi lunghi e ridurre il rischio', ok: true, f: 'Serve un +100%: inseguirlo in pochi mesi con la leva espone a un nuovo crollo, e da −75% servirebbe +300%.' },
      { t: 'Usare la leva per fare +100% in pochi mesi', ok: false, f: 'La leva amplifica anche le perdite: un altro −50% lascerebbe solo il 25% del capitale iniziale.' },
      { t: 'Concentrare tutto sul titolo più volatile', ok: false, f: 'Più volatilità e meno diversificazione rendono più probabile un drawdown ancora più profondo.' },
    ] },
    { s: 'Federica, 33 anni, ha un’azione in calo del 65%. Vuole comprarne ancora fino a farla diventare il 40% del portafoglio, per abbassare il prezzo medio.', q: 'Cosa le conviene fare?', o: [
      { t: 'Rivalutare i fondamentali e tenere un peso limitato', ok: true, f: 'Il prezzo medio non conta per il futuro dell’azienda. Se la tesi regge ancora, un peso contenuto evita che un fallimento la travolga.' },
      { t: 'Comprare fino al 40%: più scende, più è un affare', ok: false, f: 'Un forte calo può segnalare problemi seri. Concentrare il 40% su un titolo in crisi espone a una perdita permanente.' },
      { t: 'Aspettare il prezzo di carico per vendere, qualunque cosa accada', ok: false, f: 'Il titolo non sa a quanto lo ha comprato: legarsi al prezzo di carico può significare restare in un’azienda che peggiora.' },
    ] },
    { s: 'Antonio, 45 anni, sceglie tra due strategie: A con rendimento storico più alto e max drawdown del −55%; B un po’ meno redditizia, con max drawdown del −25%. In passato ha venduto in preda al panico dopo un −20%.', q: 'Quale sceglie?', o: [
      { t: 'B: un piano che riesce a mantenere vale di più', ok: true, f: 'Il rendimento di A si ottiene solo restando investiti durante il −55%. Con la sua storia, rischierebbe di vendere vicino al minimo.' },
      { t: 'A: il rendimento storico è più alto', ok: false, f: 'Il rendimento storico conta solo se riesci a sopportare il percorso: vendere durante il drawdown cancellerebbe il vantaggio.' },
      { t: 'A con un po’ di leva, per rendere ancora di più', ok: false, f: 'La leva renderebbe il drawdown ancora più profondo, ben oltre la sua tolleranza dimostrata.' },
    ] },
    { s: 'Martina, 26 anni, fa un PAC mensile su un ETF azionario globale con orizzonte di 30 anni. Durante un mercato ribassista il suo investimento è in calo del 30%.', q: 'Cosa fa?', o: [
      { t: 'Continua il PAC come previsto dal piano', ok: true, f: 'Con un orizzonte lungo e un indice diversificato, continuare significa comprare quote a prezzi più bassi, senza garanzie ma con coerenza.' },
      { t: 'Sospende il PAC e lo riprende dopo il recupero', ok: false, f: 'Smette di comprare proprio quando i prezzi sono più bassi e rischia di rientrare dopo il rimbalzo: è market timing.' },
      { t: 'Vende tutto e passa al conto deposito', ok: false, f: 'Trasforma il calo in perdita realizzata e rinuncia alla crescita di lungo periodo per cui aveva scelto l’azionario.' },
    ] },
  ],
  tip: 'Prima di scegliere un’allocazione guarda il suo peggior drawdown storico e chiediti: lo reggerei senza vendere? Se la risposta è no, riduci il rischio.',
});
