FQC(94, {
  intro: 'Quanto ha reso davvero, e con quanto rischio? Rendimento annualizzato, volatilità, Sharpe, Sortino e confronto con il benchmark.',
  cards: [
    { t: 'Il rendimento annualizzato', x: 'Un +61% in 5 anni non è un +12,2% all’anno: il rendimento annualizzato composto (CAGR) tiene conto della capitalizzazione e rende confrontabili periodi di durata diversa.', v: { k: 'stat', n: '≈10%', l: 'annuo composto: è il CAGR di un +61% in 5 anni' } },
    { t: 'La volatilità', x: 'È la deviazione standard dei rendimenti, di solito annualizzata: misura quanto i risultati oscillano attorno alla media. Non distingue tra oscillazioni verso l’alto e verso il basso.', v: { k: 'scale', a: 'Volatilità bassa', b: 'Volatilità alta', d: [['Fondo monetario', 5], ['Obbligazionario globale', 25], ['Azionario globale', 60], ['Singola azione tecnologica', 88]] } },
    { t: 'Lo Sharpe ratio', x: 'Misura quanto rendimento in eccesso rispetto al tasso privo di rischio ottieni per ogni unità di volatilità. Serve a confrontare strategie diverse sullo stesso periodo.', v: { k: 'formula', f: 'Sharpe = (Rendimento − Tasso privo di rischio) ÷ Volatilità', n: 'Es.: (8% − 2%) ÷ 12% = 0,5' } },
    { t: 'Sharpe o Sortino?', x: 'Il Sortino ratio mette al denominatore solo le oscillazioni negative (downside deviation): non penalizza i rialzi improvvisi. È più informativo quando i rendimenti sono asimmetrici.', v: { k: 'vs', a: ['Sharpe', 'Penalizza tutta la volatilità'], b: ['Sortino', 'Penalizza solo la volatilità al ribasso'] } },
    { t: 'Il confronto con il benchmark', x: 'Un +7% sembra buono, ma se l’indice coerente con quel fondo ha fatto +9% hai sottoperformato di 2 punti. Il benchmark deve avere universo e rischio simili, e il confronto va fatto al netto dei costi.', v: { k: 'bars', d: [['Il tuo fondo', 7], ['Benchmark coerente', 9]], u: '%' } },
    { t: 'Le trappole del confronto', x: 'Confronta rendimenti sullo stesso periodo, al netto di costi e con rischio simile. Diffida delle classifiche che mostrano solo i fondi sopravvissuti o il periodo più favorevole.', v: { k: 'icons', d: [['📅', 'Stesso periodo'], ['💶', 'Al netto dei costi'], ['⚖️', 'Rischio comparabile'], ['🔍', 'Attenzione ai sopravvissuti']] } },
  ],
  terms: [
    ['CAGR', 'Tasso medio composto annuo che porta dal valore iniziale a quello finale di un investimento.'],
    ['Volatilità', 'Deviazione standard dei rendimenti: misura l’ampiezza delle oscillazioni attorno alla media.'],
    ['Sharpe ratio', 'Rendimento in eccesso sul tasso privo di rischio diviso per la volatilità totale.'],
    ['Sortino ratio', 'Rendimento in eccesso diviso per la sola deviazione dei rendimenti negativi.'],
    ['Benchmark', 'Indice di riferimento con universo e rischio simili, usato per giudicare un investimento.'],
    ['Tracking error', 'Volatilità della differenza di rendimento tra un portafoglio e il suo indice di riferimento.'],
    ['Alfa', 'Rendimento in eccesso rispetto a quanto spiegato dal rischio di mercato assunto.'],
    ['Survivorship bias', 'Distorsione che gonfia i rendimenti medi escludendo i fondi chiusi per cattivi risultati.'],
  ],
  tf: [
    ['Un rendimento cumulato del 50% in 5 anni equivale a un 10% annuo composto.', false, 'Il 10% annuo per 5 anni dà circa +61%. Un +50% in 5 anni corrisponde a circa l’8,4% annuo composto.'],
    ['Lo Sharpe ratio misura il rendimento in eccesso ottenuto per ogni unità di volatilità.', true, 'Divide il rendimento oltre il tasso privo di rischio per la volatilità: più è alto, più rendimento per unità di rischio.'],
    ['Una volatilità alta indica che l’investimento perderà valore.', false, 'La volatilità misura l’ampiezza delle oscillazioni, in su e in giù, non la direzione. Un asset volatile può anche salire molto.'],
    ['Il Sortino ratio considera nel denominatore solo le oscillazioni al ribasso.', true, 'Usa la downside deviation: i rialzi improvvisi non vengono penalizzati come nello Sharpe.'],
    ['Per giudicare un fondo azionario globale, il FTSE MIB è un benchmark adatto.', false, 'Il benchmark deve avere universo e rischio simili: per un azionario globale serve un indice globale, non uno italiano.'],
    ['Un fondo che ha battuto il benchmark negli ultimi 3 anni lo batterà quasi certamente anche nei 3 successivi.', false, 'La persistenza delle sovraperformance è storicamente debole: molti fondi che battono l’indice in un periodo non ci riescono nel successivo.'],
    ['Per confrontare due fondi bisogna usare lo stesso periodo e rendimenti al netto dei costi.', true, 'Periodi diversi o rendimenti lordi rendono il confronto ingannevole: conta ciò che resta in tasca all’investitore.'],
    ['Uno Sharpe ratio negativo indica che l’investimento ha reso meno del tasso privo di rischio.', true, 'Il numeratore è negativo: in quel periodo un’attività priva di rischio avrebbe fatto meglio, con meno oscillazioni.'],
    ['Le classifiche dei fondi possono sovrastimare il rendimento medio perché escludono i fondi chiusi.', true, 'È il survivorship bias: i fondi peggiori spesso vengono chiusi o fusi e spariscono dalle statistiche.'],
    ['La media aritmetica dei rendimenti annui coincide sempre con il rendimento annualizzato composto.', false, '+50% e poi −50% danno media aritmetica 0%, ma il capitale scende del 25%: il rendimento composto è circa −13% annuo.'],
  ],
  mcq: [
    { q: 'Fondo A: rendimento 9%, volatilità 15%. Fondo B: 7%, volatilità 8%. Tasso privo di rischio 2%. Quale ha lo Sharpe più alto?', a: 'B, con circa 0,63', w: ['A, con circa 0,47', 'A, con circa 0,60', 'Sono uguali'], e: 'A: (9 − 2) ÷ 15 ≈ 0,47. B: (7 − 2) ÷ 8 ≈ 0,63. B rende meno, ma offre più rendimento per unità di rischio.' },
    { q: 'Quando il Sortino ratio è più informativo dello Sharpe?', a: 'Quando i rendimenti sono asimmetrici', w: ['Quando il tasso privo di rischio è zero', 'Quando il portafoglio è solo liquidità', 'Quando il periodo è inferiore al mese'], e: 'Se una strategia ha rialzi improvvisi ma ribassi contenuti, lo Sharpe la penalizza troppo; il Sortino guarda solo al rischio di ribasso.' },
    { q: 'Un portafoglio passa da 20.000 a 29.282 € in 4 anni, senza versamenti. Qual è il rendimento annualizzato?', a: 'Circa 10%', w: ['Circa 11,6%', 'Circa 46%', 'Circa 9%'], e: '29.282 ÷ 20.000 = 1,4641 = 1,1^4: il CAGR è 10%. L’11,6% è la media semplice (46,4% ÷ 4), che ignora la capitalizzazione.' },
    { q: 'Qual è il benchmark più adatto per un ETF di titoli di Stato dell’area euro?', a: 'Un indice di titoli di Stato dell’area euro', w: ['Un indice delle azioni dell’area euro', 'Il tasso d’inflazione dell’area euro', 'Un indice azionario mondiale ampio'], e: 'Il benchmark deve contenere strumenti simili per tipo, area e rischio: per un ETF governativo euro serve un indice governativo euro.' },
    { q: 'Quale modo di leggere i rendimenti è un errore comune?', a: 'Guardare il rendimento ignorando il rischio', w: ['Confrontarlo con un benchmark coerente', 'Usare rendimenti al netto dei costi', 'Annualizzare i rendimenti pluriennali'], e: 'Due fondi con lo stesso rendimento possono avere rischi molto diversi: senza volatilità e drawdown il numero è incompleto.' },
    { q: 'Hai versato molto denaro poco prima di un forte calo. Quale misura riflette meglio il tuo risultato personale?', a: 'Il rendimento ponderato per il denaro', w: ['Il rendimento ponderato per il tempo', 'Lo Sharpe ratio del benchmark', 'Il rendimento cedolare medio'], e: 'Il rendimento ponderato per il denaro (simile al TIR) pesa i flussi e riflette i tuoi tempi di versamento; quello ponderato per il tempo valuta il gestore.' },
    { q: 'Cosa misura il tracking error di un ETF?', a: 'La variabilità dello scarto dall’indice', w: ['Il costo annuo totale di gestione', 'La perdita massima dal picco al minimo', 'La liquidità sul mercato secondario'], e: 'È la volatilità della differenza tra rendimento dell’ETF e dell’indice: più è basso, più fedele è la replica.' },
    { q: 'Un fondo ha battuto il benchmark del 2% in un anno, ma con volatilità doppia. Cosa puoi concludere?', a: 'Va pesato il rischio extra assunto', w: ['Il gestore è sicuramente più bravo', 'Il fondo è meno rischioso dell’indice', 'Il risultato si ripeterà l’anno prossimo'], e: 'Un rendimento più alto ottenuto con molto più rischio non dimostra abilità: indicatori come lo Sharpe aiutano a confrontare in modo corretto.' },
  ],
  fill: [
    { s: 'Il rapporto di ___ divide il rendimento in eccesso per la volatilità totale.', a: 'Sharpe', w: ['Sortino', 'Calmar', 'Treynor'] },
    { s: 'La ___ è la deviazione standard dei rendimenti di un investimento.', a: 'volatilità', w: ['duration', 'liquidità', 'convessità'] },
    { s: 'Il rendimento annualizzato composto si indica spesso con la sigla ___.', a: 'CAGR', w: ['TER', 'NAV', 'EPS'] },
    { s: 'L’indice di riferimento con cui confrontare un fondo si chiama ___.', a: 'benchmark', w: ['rating', 'prospetto', 'collaterale'] },
    { s: 'Le classifiche che ignorano i fondi chiusi soffrono di ___ bias.', a: 'survivorship', w: ['confirmation', 'home', 'recency'] },
  ],
  order: [
    { q: 'Ordina per Sharpe ratio, dal più alto al più basso (tasso privo di rischio 2%)', i: ['Rendimento 8%, volatilità 6%', 'Rendimento 10%, volatilità 10%', 'Rendimento 12%, volatilità 16%', 'Rendimento 5%, volatilità 12%'], e: 'Sharpe: 6 ÷ 6 = 1; 8 ÷ 10 = 0,8; 10 ÷ 16 ≈ 0,63; 3 ÷ 12 = 0,25. Il rendimento più alto non ha lo Sharpe migliore.' },
    { q: 'Ordina dal rendimento annualizzato più alto al più basso', i: ['+100% in 5 anni', '+60% in 5 anni', '+50% in 6 anni', '+30% in 5 anni'], e: 'Annualizzando si ottiene circa 14,9%, 9,9%, 7,0% e 5,4% all’anno: la durata del periodo cambia molto la lettura.' },
  ],
  cat: [
    { q: 'Misura di rendimento o misura di rischio?', g: [['Rendimento', ['CAGR', 'Rendimento cumulato', 'Alfa']], ['Rischio', ['Volatilità', 'Max drawdown', 'Tracking error']]] },
    { q: 'Confronto corretto o scorretto tra due investimenti?', g: [['Corretto', ['Stesso periodo per entrambi', 'Rendimenti al netto dei costi', 'Benchmark con rischio simile']], ['Scorretto', ['Fondo azionario contro conto deposito', 'Periodi scelti ad arte', 'Solo i fondi sopravvissuti']]] },
  ],
  scen: [
    { s: 'Stefano, 47 anni, riceve la proposta di un fondo azionario globale che in 5 anni ha fatto +80%. Nello stesso periodo il suo benchmark dichiarato ha fatto +95%.', q: 'Come valuta la proposta?', o: [
      { t: 'Nota la sottoperformance e chiede costi e motivi', ok: true, f: 'Il +80% sembra ottimo, ma l’indice di riferimento ha fatto meglio: spesso la differenza è spiegata in gran parte dai costi.' },
      { t: 'Investe: +80% in 5 anni è un risultato eccellente', ok: false, f: 'Un rendimento va sempre letto rispetto all’alternativa coerente: qui un semplice indice avrebbe reso di più.' },
      { t: 'Investe perché i fondi recuperano sempre lo svantaggio', ok: false, f: 'Non esiste una regola simile: la sottoperformance dovuta ai costi tende anzi a ripetersi ogni anno.' },
    ] },
    { s: 'Anna, 39 anni, legge la pubblicità di un fondo con “rendimento medio del 10% annuo”. I rendimenti degli ultimi tre anni sono stati +50%, −30% e +10%.', q: 'Cosa ne conclude?', o: [
      { t: 'Calcola il composto: circa +4,9% annuo', ok: true, f: '1,5 × 0,7 × 1,1 = 1,155: in tre anni +15,5%, cioè circa 4,9% annuo. La media aritmetica del 10% sopravvaluta il risultato.' },
      { t: 'Si fida: il 10% annuo per tre anni fa +33%', ok: false, f: 'La media aritmetica non è il rendimento ottenuto: chi ha investito all’inizio ha guadagnato il 15,5%, non il 33%.' },
      { t: 'Guarda solo l’anno migliore, che conta di più', ok: false, f: 'Scegliere il periodo più favorevole è proprio una delle trappole del confronto: conta il risultato composto sull’intero periodo.' },
    ] },
    { s: 'Giorgio, 61 anni, ha investito a più riprese, versando la cifra maggiore poco prima di un calo. Il report mostra +7% ponderato per il tempo, ma il suo rendimento ponderato per il denaro è +3%.', q: 'Quale dato descrive la sua esperienza?', o: [
      { t: 'Il rendimento ponderato per il denaro', ok: true, f: 'Tiene conto di quando e quanto ha versato: riflette il suo risultato reale. Il dato ponderato per il tempo serve a giudicare la gestione.' },
      { t: 'Il rendimento ponderato per il tempo', ok: false, f: 'Neutralizza l’effetto dei versamenti: misura le scelte del gestore, non quanto ha guadagnato Giorgio con i suoi tempi.' },
      { t: 'Nessuno: conta solo il saldo di oggi', ok: false, f: 'Il saldo da solo non dice nulla senza considerare quanto è stato versato e quando: servono misure di rendimento.' },
    ] },
    { s: 'Valentina, 31 anni, confronta due strategie con rendimento simile, circa 7% annuo. La prima ha Sharpe 0,3 e max drawdown −45%; la seconda Sharpe 0,6 e max drawdown −20%.', q: 'Quale sceglie?', o: [
      { t: 'La seconda: stesso rendimento con meno rischio', ok: true, f: 'A parità di rendimento, uno Sharpe più alto e un drawdown più contenuto significano un percorso più sostenibile.' },
      { t: 'La prima: più volatilità significa più opportunità', ok: false, f: 'La volatilità in più non è stata ricompensata da rendimento extra: è solo rischio in più.' },
      { t: 'È indifferente: conta solo il rendimento', ok: false, f: 'Il rendimento è metà della storia: un −45% mette a dura prova la capacità di restare investiti.' },
    ] },
  ],
  tip: 'Davanti a un rendimento chiedi sempre: è annualizzato? È al netto dei costi? Rispetto a quale benchmark? Con quanto rischio? Un numero senza contesto non dice nulla.',
});
