FQC(95, {
  intro: 'Il nemico più insidioso dei tuoi investimenti può essere la tua mente: impara a riconoscere i bias che distorcono le decisioni.',
  cards: [
    { t: 'L’avversione alle perdite', x: 'Secondo gli studi di Kahneman e Tversky, una perdita pesa psicologicamente circa il doppio di un guadagno equivalente. Per non “sentire” la perdita si prendono decisioni irrazionali.', v: { k: 'stat', n: '≈2×', l: 'il peso emotivo di una perdita rispetto a un guadagno uguale' } },
    { t: 'L’effetto disposizione', x: 'È la tendenza a vendere presto i titoli in guadagno e tenere a lungo quelli in perdita. Risultato: si tagliano i guadagni e si lasciano correre le perdite, l’opposto di ciò che vorresti.', v: { k: 'vs', a: ['Titoli in guadagno', 'Venduti troppo presto per “incassare”'], b: ['Titoli in perdita', 'Tenuti troppo a lungo sperando nel pareggio'] } },
    { t: 'FOMO ed effetto gregge', x: 'La paura di perdere l’occasione (FOMO) e l’imitazione degli altri spingono a comprare dopo forti rialzi, spesso vicino ai massimi, e a vendere insieme a tutti durante il panico.', v: { k: 'steps', s: ['Il titolo sale e tutti ne parlano', 'Paura di restare fuori', 'Acquisto vicino ai massimi', 'Correzione e vendita in perdita'] } },
    { t: 'L’ancoraggio', x: 'L’ancoraggio lega le decisioni a un numero di riferimento spesso irrilevante. Il mercato non sa a quanto hai comprato: la domanda giusta è se compreresti quel titolo oggi, a questo prezzo.', v: { k: 'icons', d: [['⚓', 'Prezzo di carico'], ['🏔️', 'Massimo di un anno fa'], ['🎯', 'Target di un analista']] } },
    { t: 'L’eccesso di fiducia', x: 'Molti si ritengono investitori sopra la media. L’eccesso di fiducia porta a operare troppo e a diversificare poco: studi su investitori privati mostrano che chi scambia di più tende a rendere di meno.', v: { k: 'scale', a: 'Sottostima', b: 'Sovrastima', d: [['Abilità reale', 45], ['Abilità percepita', 85]] } },
    { t: 'Il recency bias', x: 'Dà troppo peso agli eventi recenti: dopo anni di rialzi sembra impossibile perdere, dopo un crollo sembra impossibile recuperare. Un piano scritto e regole automatiche aiutano a non farsi trascinare.', v: { k: 'vs', a: ['Dopo anni di rialzi', '“Le azioni salgono sempre”'], b: ['Dopo un crollo', '“Non si riprenderanno mai”'] } },
  ],
  terms: [
    ['Avversione alle perdite', 'Tendenza a percepire una perdita più intensamente di un guadagno di pari importo.'],
    ['Effetto disposizione', 'Tendenza a vendere presto i titoli in guadagno e a tenere a lungo quelli in perdita.'],
    ['FOMO', 'Paura di restare esclusi da un rialzo, che spinge a comprare d’impulso dopo forti salite.'],
    ['Ancoraggio', 'Uso di un numero di riferimento, spesso irrilevante, come base per decidere.'],
    ['Eccesso di fiducia', 'Sovrastima delle proprie capacità e della precisione delle proprie previsioni.'],
    ['Effetto gregge', 'Tendenza a imitare le scelte della maggioranza invece di valutare in autonomia.'],
    ['Recency bias', 'Tendenza a dare troppo peso agli eventi più recenti nel prevedere il futuro.'],
    ['Bias di conferma', 'Ricerca selettiva di informazioni che sostengono un’opinione già formata.'],
  ],
  tf: [
    ['Secondo la finanza comportamentale, una perdita pesa psicologicamente più di un guadagno della stessa entità.', true, 'È l’avversione alle perdite: le ricerche di Kahneman e Tversky stimano che una perdita pesi circa il doppio di un guadagno uguale.'],
    ['L’effetto disposizione porta a vendere troppo presto i titoli in perdita.', false, 'È il contrario: si vendono presto i titoli in guadagno e si tengono troppo a lungo quelli in perdita, sperando di tornare in pari.'],
    ['Un titolo tende a tornare al prezzo a cui l’hai comprato, quindi conviene aspettare il pareggio prima di vendere.', false, 'È ancoraggio: il mercato ignora il tuo prezzo di carico. Chiediti se lo ricompreresti oggi; il prezzo di carico conta al più per il fisco.'],
    ['Studi su investitori privati mostrano che chi fa più compravendite tende, in media, a ottenere rendimenti netti inferiori.', true, 'Più operazioni significano più costi e più decisioni prese d’impulso: l’eccesso di fiducia si paga in rendimento.'],
    ['Conoscere un bias è sufficiente per non esserne influenzati.', false, 'I bias agiscono anche quando li conosci. Servono regole e automatismi: piano scritto, PAC, ribilanciamento programmato, checklist.'],
    ['Comprare un titolo solo perché ne parlano tutti sui social è un esempio di effetto gregge.', true, 'La decisione nasce dall’imitazione degli altri, non da un’analisi propria: spesso si entra quando il rialzo è già maturo.'],
    ['Il recency bias porta a credere, dopo anni di rialzi, che il mercato continuerà a salire.', true, 'Il passato recente viene proiettato nel futuro: si sottovaluta il rischio proprio quando le valutazioni sono più alte.'],
    ['L’eccesso di fiducia riguarda solo i principianti: gli esperti ne sono immuni.', false, 'L’esperienza e i successi passati possono anzi rafforzarlo: anche i professionisti sovrastimano spesso la precisione delle loro previsioni.'],
    ['Leggere solo analisi che confermano la propria tesi d’investimento è un segnale di bias di conferma.', true, 'Si filtrano le informazioni scomode. Un antidoto è cercare attivamente le opinioni contrarie prima di decidere.'],
    ['Il senno di poi ci rende più prudenti nel giudicare la nostra capacità di previsione.', false, 'Al contrario: fa sembrare prevedibili gli eventi passati (“lo sapevo”) e gonfia la fiducia nelle previsioni future.'],
  ],
  mcq: [
    { q: 'Luisa vende un titolo appena sale del 5%, ma tiene da anni un titolo in perdita del 40%. Quale bias mostra?', a: 'Effetto disposizione', w: ['Effetto gregge', 'Bias di conferma', 'Recency bias'], e: 'Incassare subito i guadagni e rimandare le perdite è il tipico effetto disposizione, alimentato dall’avversione alle perdite.' },
    { q: 'Quale domanda aiuta a neutralizzare l’ancoraggio al prezzo di carico?', a: '“Lo comprerei oggi a questo prezzo?”', w: ['“Quanto ho perso finora?”', '“A che prezzo l’avevo comprato?”', '“Quando tornerà in pari?”'], e: 'Sposta l’attenzione dal passato, che non conta, al valore atteso futuro rispetto al prezzo attuale.' },
    { q: 'Un investitore aumenta la quota azionaria dopo tre anni di forti rialzi, “perché ormai sale sempre”. Quale bias prevale?', a: 'Recency bias', w: ['Avversione alle perdite', 'Effetto disposizione', 'Ancoraggio'], e: 'Proietta nel futuro i risultati recenti. L’allocazione andrebbe decisa in base al piano, non all’andamento degli ultimi anni.' },
    { q: 'Quale credenza sui bias è un errore comune?', a: 'Conoscerli basta per non caderci', w: ['Influenzano anche gli esperti', 'Le regole scritte aiutano a contenerli', 'Le emozioni pesano sulle decisioni'], e: 'Sapere che esistono non basta: servono processi che decidono al posto dell’emozione, come piani scritti e regole automatiche.' },
    { q: 'Cosa misura il cosiddetto “behavior gap”?', a: 'Lo scarto tra resa dei fondi e degli investitori', w: ['Lo scarto tra prezzo denaro e prezzo lettera', 'Lo scarto tra inflazione attesa e reale', 'Il ritardo tra invio dell’ordine ed esecuzione'], e: 'Entrando dopo i rialzi e uscendo dopo i ribassi, molti investitori ottengono meno dei fondi che possiedono: è il costo del comportamento.' },
    { q: 'Perché l’eccesso di fiducia danneggia il rendimento?', a: 'Porta a operare troppo e diversificare poco', w: ['Riduce troppo le commissioni pagate', 'Spinge a investire solo in obbligazioni', 'Porta a tenere troppa liquidità'], e: 'Più operazioni significano più costi; poca diversificazione significa più rischio specifico. Entrambi riducono il rendimento atteso.' },
    { q: 'Quale strumento contrasta meglio la FOMO?', a: 'Un piano scritto con regole di ingresso', w: ['Controllare i social più spesso', 'Seguire i titoli più discussi del giorno', 'Comprare appena un titolo sale del 10%'], e: 'Regole decise a mente fredda filtrano gli acquisti d’impulso: se l’occasione non rientra nel piano, non si compra.' },
    { q: 'Un trader non chiude una posizione in perdita “per non rendere reale la perdita”. Quale bias è più evidente?', a: 'Avversione alle perdite', w: ['Effetto gregge', 'Bias di conferma', 'Recency bias'], e: 'Il dolore di realizzare la perdita lo spinge a restare in una posizione che non riaprirebbe mai oggi.' },
  ],
  fill: [
    { s: 'Secondo Kahneman e Tversky, una perdita pesa circa il ___ di un guadagno equivalente.', a: 'doppio', w: ['decimo', 'quintuplo', 'centuplo'] },
    { s: 'La paura di restare esclusi da un rialzo si indica con l’acronimo ___.', a: 'FOMO', w: ['YOLO', 'FIRE', 'HODL'] },
    { s: 'Usare il prezzo di carico come riferimento per decidere è un esempio di ___.', a: 'ancoraggio', w: ['diversificazione', 'ribilanciamento', 'arbitraggio'] },
    { s: 'Il bias di ___ porta a cercare solo informazioni che sostengono le proprie idee.', a: 'conferma', w: ['disponibilità', 'sopravvivenza', 'status quo'] },
    { s: 'Vendere presto i vincenti e tenere i perdenti è l’effetto ___.', a: 'disposizione', w: ['dotazione', 'gregge', 'leva'] },
  ],
  order: [
    { q: 'Ordina le fasi tipiche di una bolla alimentata da FOMO ed effetto gregge', i: ['Rialzo iniziale con pochi acquirenti', 'Attenzione crescente dei media', 'Euforia e acquisti di massa', 'Primi cali e negazione', 'Panico e vendite generalizzate'], e: 'Chi entra per imitazione arriva di solito nella fase di euforia ed esce nel panico: compra caro e vende a sconto.' },
    { q: 'Ordina gli eventi di una storia di effetto disposizione', i: ['Compri due titoli, A e B', 'A sale del 15%, B scende del 15%', 'Vendi A per “incassare”', 'Tieni B sperando nel pareggio', 'B continua a scendere'], e: 'Tagli il vincente e lasci correre il perdente. Una regola di uscita decisa prima di entrare evita la trappola.' },
  ],
  cat: [
    { q: 'Segnale di bias o comportamento disciplinato?', g: [['Segnale di bias', ['Comprare perché “lo fanno tutti”', 'Aspettare il pareggio per vendere', 'Leggere solo chi la pensa come te']], ['Disciplina', ['Ribilanciare a date fisse', 'Annotare i motivi di ogni acquisto', 'Fissare l’uscita prima di entrare']]] },
    { q: 'Quale bias descrive la frase?', g: [['Ancoraggio', ['“Lo vendo quando torna a 50 €”', '“Era a 100 €, a 60 € è un affare”', '“Il target è 80 €, quindi vale 80 €”']], ['Effetto gregge', ['“Lo stanno comprando tutti nel forum”', '“Se tutti vendono, vendo anch’io”', '“Tutti i colleghi ci hanno investito”']]] },
  ],
  scen: [
    { s: 'Francesca, 36 anni, vede una small cap tecnologica salita del 120% in un mese. Sui social ne parlano tutti e lei vorrebbe investirci il 30% dei risparmi prima che “sia troppo tardi”.', q: 'Cosa le conviene fare?', o: [
      { t: 'Fermarsi e valutare a mente fredda', ok: true, f: 'La fretta è il segnale della FOMO. Se il titolo supera un’analisi seria, una quota piccola e prevista dal piano limita il danno.' },
      { t: 'Investire subito il 30%, prima che salga ancora', ok: false, f: 'Entrare dopo un +120% sull’onda dell’entusiasmo significa spesso comprare vicino ai massimi, con un peso enorme in portafoglio.' },
      { t: 'Investire tutto con un prodotto a leva', ok: false, f: 'Somma FOMO, concentrazione e leva: anche una correzione normale potrebbe azzerare il capitale investito.' },
    ] },
    { s: 'Giovanni, 55 anni, ha comprato un titolo a 40 €, oggi a 25 €. I conti dell’azienda sono peggiorati, ma lui ripete: “Lo vendo quando torna a 40 €”.', q: 'Qual è l’approccio corretto?', o: [
      { t: 'Valutare il titolo come se dovesse comprarlo oggi', ok: true, f: 'Il prezzo di carico è un’àncora irrilevante. Se oggi non lo comprerebbe, tenerlo equivale a ricomprarlo ogni giorno.' },
      { t: 'Aspettare il pareggio, qualunque cosa accada', ok: false, f: 'Il mercato non sa a quanto ha comprato: con fondamentali in peggioramento il pareggio potrebbe non arrivare mai.' },
      { t: 'Comprare altre azioni per abbassare il prezzo medio', ok: false, f: 'Abbassa il prezzo medio solo sulla carta e aumenta l’esposizione a un’azienda che sta peggiorando.' },
    ] },
    { s: 'Ilaria, 42 anni, ha chiuso tre anni ottimi facendo trading. Ora vuole abbandonare la diversificazione e concentrare tutto su tre titoli che “conosce benissimo”.', q: 'Cosa le conviene fare?', o: [
      { t: 'Mantenere la diversificazione: tre anni non provano un’abilità', ok: true, f: 'Tre anni sono un campione piccolo, spesso favorito dal mercato. L’eccesso di fiducia è più pericoloso proprio dopo i successi.' },
      { t: 'Concentrare tutto: i risultati dimostrano che è brava', ok: false, f: 'Buoni risultati possono dipendere da fortuna o da un mercato favorevole. La concentrazione rende un errore molto costoso.' },
      { t: 'Concentrare e aggiungere leva per sfruttare il talento', ok: false, f: 'Unisce eccesso di fiducia, concentrazione e leva: la combinazione più pericolosa per il capitale.' },
    ] },
    { s: 'Pietro, 30 anni, vede il mercato scendere del 25%. Tutti i notiziari parlano di crisi senza fine. Il suo piano scritto prevede di proseguire il PAC e di ribilanciare.', q: 'Cosa fa?', o: [
      { t: 'Segue il piano scritto e ribilancia', ok: true, f: 'Il piano è stato scritto a mente fredda proprio per questi momenti: protegge da recency bias ed effetto gregge.' },
      { t: 'Vende tutto: le notizie dicono che scenderà ancora', ok: false, f: 'Le notizie riflettono il passato recente e il sentimento comune: vendere con la folla significa spesso vendere vicino ai minimi.' },
      { t: 'Sospende il PAC finché i giornali non tornano ottimisti', ok: false, f: 'Quando l’ottimismo torna i prezzi sono di solito già risaliti: così compra caro e salta i prezzi bassi.' },
    ] },
  ],
  tip: 'Prima di un’operazione non pianificata aspetta 48 ore e scrivi perché la fai. Se il motivo è “lo fanno tutti” o “voglio tornare in pari”, lascia perdere.',
});
