FQC(96, {
  intro: 'Quanto pesa il fisco su cedole, dividendi e plusvalenze? Aliquote, redditi di capitale e diversi, minusvalenze, regimi fiscali e bollo.',
  cards: [
    { t: 'Le due aliquote', x: 'In Italia i redditi finanziari sono tassati in genere al 26%; interessi e plusvalenze dei titoli di Stato italiani e dei Paesi della white list al 12,5%. La normativa può cambiare: verifica sempre le regole in vigore.', v: { k: 'bars', d: [['Azioni, ETF, obbligazioni societarie', 26], ['Titoli di Stato e white list', 12.5]], u: '%' } },
    { t: 'Redditi di capitale e redditi diversi', x: 'La distinzione conta perché solo i redditi diversi si compensano con le minusvalenze. Cedole, dividendi e proventi di fondi ed ETF sono redditi di capitale: non assorbono le perdite.', v: { k: 'vs', a: ['Redditi di capitale', 'Cedole, interessi, dividendi, proventi di fondi ed ETF'], b: ['Redditi diversi', 'Plusvalenze e minusvalenze da cessione, derivati, certificati'] } },
    { t: 'Lo zainetto fiscale', x: 'Le minusvalenze si compensano con plusvalenze della stessa natura realizzate nello stesso anno e fino al quarto anno successivo. Poi scadono e si perdono.', v: { k: 'steps', s: ['Anno 1: minusvalenza di 3.000 €', 'Entra nello zainetto fiscale', 'Entro l’anno 5: plusvalenza su azioni', 'Paghi il 26% solo sulla differenza'] } },
    { t: 'L’asimmetria degli ETF', x: 'Per fondi ed ETF armonizzati il guadagno da vendita è reddito di capitale, mentre la perdita è reddito diverso. Una minus da ETF compensa plus su azioni; una plus da ETF non assorbe le minus pregresse.', v: { k: 'formula', f: 'Imposta = 26% × plusvalenza da ETF, senza compensazione', n: 'Es.: plus da ETF azionario 2.000 € e 2.000 € di minus nello zainetto → paghi comunque 520 €' } },
    { t: 'Amministrato o dichiarativo', x: 'In regime amministrato banca o broker italiano fanno da sostituto d’imposta: calcolano, compensano e versano. In regime dichiarativo, tipico dei broker esteri, dichiari tu redditi e attività estere.', v: { k: 'icons', d: [['🏦', 'Amministrato: fa l’intermediario'], ['📝', 'Dichiarativo: dichiari tu'], ['🌍', 'Broker estero: di solito dichiarativo']] } },
    { t: 'L’imposta di bollo', x: 'Si paga ogni anno sul valore di mercato degli strumenti in deposito, anche se non vendi nulla: su 50.000 € sono 100 €. Il conto corrente paga invece 34,20 € se la giacenza media supera 5.000 €.', v: { k: 'stat', n: '0,2%', l: 'imposta di bollo annua sul valore del dossier titoli' } },
  ],
  terms: [
    ['Redditi di capitale', 'Interessi, cedole, dividendi e proventi di fondi: tassati senza compensazione con le minusvalenze.'],
    ['Redditi diversi', 'Plusvalenze e minusvalenze da cessione di titoli, derivati e certificati, compensabili tra loro.'],
    ['Minusvalenza', 'Perdita realizzata vendendo un titolo a un prezzo inferiore al costo medio di carico.'],
    ['Zainetto fiscale', 'Insieme delle minusvalenze non ancora usate, compensabili fino al quarto anno successivo.'],
    ['Regime amministrato', 'L’intermediario calcola e versa le imposte su ogni operazione; non serve la dichiarazione.'],
    ['Regime dichiarativo', 'Il contribuente indica i redditi finanziari nella dichiarazione dei redditi e versa le imposte.'],
    ['Sostituto d’imposta', 'Soggetto, come una banca italiana, che trattiene e versa le imposte per conto del cliente.'],
    ['White list', 'Elenco di Paesi collaborativi sul piano fiscale: i loro titoli di Stato sono tassati al 12,5%.'],
  ],
  tf: [
    ['Le plusvalenze realizzate vendendo azioni sono tassate in genere al 26%.', true, 'È l’aliquota ordinaria sui redditi finanziari; l’aliquota agevolata del 12,5% riguarda titoli di Stato italiani e white list.'],
    ['Le cedole dei BTP sono tassate al 26%, come quelle delle obbligazioni societarie.', false, 'I titoli di Stato italiani e dei Paesi white list godono del 12,5%; le obbligazioni societarie scontano il 26%.'],
    ['Una minusvalenza può essere compensata fino al quarto anno successivo a quello in cui è stata realizzata.', true, 'Oltre quel termine scade e non è più utilizzabile: conviene tenere d’occhio le scadenze dello zainetto fiscale.'],
    ['Le minusvalenze si possono compensare con dividendi e cedole incassati.', false, 'Dividendi e cedole sono redditi di capitale: le minusvalenze, redditi diversi, si compensano solo con plusvalenze della stessa natura.'],
    ['Secondo la normativa vigente, il guadagno dalla vendita di un ETF armonizzato non può assorbire minusvalenze pregresse.', true, 'È reddito di capitale, quindi è tassato per intero anche se hai minusvalenze nello zainetto. La normativa può cambiare.'],
    ['In regime amministrato è l’intermediario a calcolare e versare le imposte sulle operazioni.', true, 'Banca o broker italiano agiscono da sostituto d’imposta e gestiscono anche la compensazione delle minusvalenze sullo stesso rapporto.'],
    ['L’imposta di bollo sul dossier titoli si paga solo negli anni in cui vendi qualcosa.', false, 'È un’imposta sul patrimonio: 0,2% annuo sul valore degli strumenti detenuti, a prescindere dalle compravendite.'],
    ['Con un broker estero che non fa da sostituto d’imposta, di norma redditi e attività vanno indicati in dichiarazione.', true, 'Il residente in Italia è tassato su tutti i redditi, ovunque prodotti: senza sostituto d’imposta tocca a lui dichiarare e versare.'],
    ['Un ETF ad accumulazione è tassato ogni anno sui guadagni maturati anche se non lo vendi.', false, 'Per un privato l’imposta sui guadagni scatta alla vendita o al rimborso: fino ad allora il capitale cresce al lordo dell’imposta, bollo a parte.'],
    ['Le minusvalenze non utilizzate entro il termine previsto vanno perse.', true, 'Dopo il quarto anno successivo a quello di realizzo non sono più compensabili: è un credito fiscale con scadenza.'],
  ],
  mcq: [
    { q: 'Vendi azioni con una plusvalenza di 4.000 € e hai 1.500 € di minusvalenze dell’anno precedente. Quanto paghi di imposta?', a: '650 €', w: ['1.040 €', '390 €', '1.430 €'], e: 'Le minus compensano la plus da azioni: (4.000 − 1.500) × 26% = 650 €. Senza lo zainetto pagheresti 1.040 €.' },
    { q: 'Quale di questi guadagni non può essere compensato con minusvalenze pregresse?', a: 'Plusvalenza dalla vendita di un ETF', w: ['Plusvalenza dalla vendita di azioni', 'Plusvalenza su un certificato', 'Plusvalenza su un ETC'], e: 'Per la normativa vigente il guadagno su fondi ed ETF armonizzati è reddito di capitale; azioni, certificati ed ETC generano redditi diversi.' },
    { q: 'Secondo la normativa vigente, una minusvalenza dalla vendita di un ETF armonizzato è…', a: 'Un reddito diverso, compensabile', w: ['Un reddito di capitale, non compensabile', 'Deducibile dal reddito da lavoro', 'Rimborsata dallo Stato al 26%'], e: 'È l’asimmetria degli ETF: la perdita è reddito diverso e può compensare, per esempio, plusvalenze su azioni od obbligazioni.' },
    { q: 'Hai un dossier titoli dal valore di circa 40.000 € per tutto l’anno. Quanto paghi di imposta di bollo?', a: 'Circa 80 €', w: ['34,20 €', 'Circa 800 €', 'Circa 8 €'], e: '0,2% di 40.000 € = 80 €. I 34,20 € fissi riguardano il conto corrente con giacenza media oltre 5.000 €.' },
    { q: 'Qual è la differenza principale tra regime amministrato e dichiarativo?', a: 'Chi calcola e versa le imposte', w: ['L’aliquota sulle plusvalenze', 'Il numero di titoli acquistabili', 'La possibilità di comprare ETF'], e: 'Le aliquote sono le stesse: nell’amministrato provvede l’intermediario, nel dichiarativo il contribuente con la dichiarazione dei redditi.' },
    { q: 'Una cedola di 1.000 € lordi pagata da un BTP: quanto incassi al netto dell’imposta?', a: '875 €', w: ['740 €', '1.000 €', '974 €'], e: 'Sui titoli di Stato italiani l’aliquota è il 12,5%: 1.000 − 125 = 875 €. Con il 26% di un’obbligazione societaria incasseresti 740 €.' },
    { q: 'Quale convinzione fiscale è un errore comune?', a: 'Le perdite su azioni compensano i dividendi', w: ['Il bollo si paga anche senza vendere', 'I BTP hanno un’aliquota ridotta', 'Le minusvalenze hanno una scadenza'], e: 'I dividendi sono redditi di capitale e non si compensano con le minusvalenze, che sono redditi diversi.' },
    { q: 'Perché nel lungo periodo un ETF ad accumulazione può risultare fiscalmente efficiente rispetto a uno a distribuzione?', a: 'Rinvia l’imposta alla vendita', w: ['Ha un’aliquota inferiore al 26%', 'È esente dall’imposta di bollo', 'Compensa sempre le minusvalenze'], e: 'Non distribuendo proventi, rinvia la tassazione alla vendita: nel frattempo anche la parte che andrebbe al fisco continua a capitalizzare.' },
  ],
  fill: [
    { s: 'Gli interessi dei titoli di Stato italiani sono tassati con aliquota del ___.', a: '12,5%', w: ['26%', '20%', '43%'] },
    { s: 'Le plusvalenze da azioni sono redditi ___ e si compensano con le minusvalenze.', a: 'diversi', w: ['di capitale', 'da lavoro', 'fondiari'] },
    { s: 'Una minusvalenza si può usare fino al ___ anno successivo a quello di realizzo.', a: 'quarto', w: ['primo', 'secondo', 'decimo'] },
    { s: 'Nel regime ___ l’intermediario italiano fa da sostituto d’imposta.', a: 'amministrato', w: ['dichiarativo', 'forfettario', 'agevolato'] },
    { s: 'L’imposta di ___ sul dossier titoli è pari allo 0,2% annuo.', a: 'bollo', w: ['registro', 'successione', 'consumo'] },
  ],
  order: [
    { q: 'Ordina il calcolo dell’imposta su una vendita di azioni in regime amministrato', i: ['Prezzo di vendita meno costo medio di carico', 'Si ottiene la plusvalenza', 'Si sottraggono le minus dello zainetto', 'Si applica l’aliquota del 26%', 'L’intermediario versa l’imposta'], e: 'Prima si calcola la plusvalenza sul costo medio ponderato, poi si compensano le minus disponibili e si tassa solo la differenza.' },
    { q: 'Ordina nel tempo la vita di una minusvalenza', i: ['Vendi in perdita nell’anno X', 'La minus entra nello zainetto', 'Realizzi una plusvalenza su azioni', 'La compensi entro l’anno X + 4', 'Le minus residue scadono'], e: 'La minus resta utilizzabile fino al quarto anno successivo al realizzo; la parte non usata entro quel termine si perde.' },
  ],
  cat: [
    { q: 'Reddito di capitale o reddito diverso (normativa vigente)?', g: [['Reddito di capitale', ['Cedola di un BTP', 'Dividendo azionario', 'Guadagno dalla vendita di un ETF']], ['Reddito diverso', ['Plusvalenza su azioni', 'Minusvalenza su un ETF', 'Guadagno su un certificato']]] },
    { q: 'Aliquota del 26% o del 12,5%?', g: [['26%', ['Plusvalenza su un’azione estera', 'Cedola di un’obbligazione societaria', 'Dividendo di una società italiana']], ['12,5%', ['Cedola di un BTP', 'Rendimento di un BOT', 'Interessi di un titolo di Stato tedesco']]] },
  ],
  scen: [
    { s: 'Alessandro, 44 anni, ha 5.000 € di minusvalenze su azioni che scadono a fine anno. In portafoglio ha un ETF con 5.000 € di guadagno e un’azione con 3.000 € di guadagno.', q: 'Come può usare le minusvalenze?', o: [
      { t: 'Valutare la vendita dell’azione in guadagno', ok: true, f: 'La plus su azioni è reddito diverso e assorbe 3.000 € di minus, senza imposta. Ma il fisco non deve guidare da solo le scelte.' },
      { t: 'Vendere l’ETF: la plus annullerà le minus', ok: false, f: 'Per la normativa vigente la plus da ETF è reddito di capitale: pagherebbe il 26% su 5.000 € e le minus scadrebbero comunque.' },
      { t: 'Non fare nulla: le minus si rinnovano da sole', ok: false, f: 'Le minusvalenze scadono dopo il quarto anno successivo al realizzo: se non usate, si perdono.' },
    ] },
    { s: 'Beatrice, 35 anni, apre un conto presso un broker estero che non fa da sostituto d’imposta, attratta dalle commissioni basse.', q: 'Cosa deve mettere in conto?', o: [
      { t: 'Gli obblighi dichiarativi, eventualmente con un professionista', ok: true, f: 'Dovrà indicare redditi e attività estere in dichiarazione e versare le imposte dovute: un costo di tempo o di consulenza da considerare.' },
      { t: 'Nulla: all’estero non si pagano imposte italiane', ok: false, f: 'Un residente in Italia è tassato su tutti i redditi, ovunque prodotti. Omettere la dichiarazione espone a sanzioni.' },
      { t: 'Aspettare che sia l’Agenzia delle Entrate a contattarla', ok: false, f: 'Gli obblighi dichiarativi sono a carico del contribuente: attendere un controllo significa rischiare sanzioni.' },
    ] },
    { s: 'Claudio, 50 anni, vuole trasferirsi a una nuova banca ma ha 8.000 € di minusvalenze non ancora utilizzate e teme di perderle.', q: 'Cosa fa?', o: [
      { t: 'Chiede la certificazione delle minusvalenze', ok: true, f: 'Alla chiusura del rapporto l’intermediario rilascia la certificazione: le minus restano utilizzabili nei limiti di legge, entro la scadenza.' },
      { t: 'Resta per sempre nella vecchia banca', ok: false, f: 'Non è necessario: la certificazione permette di non perdere le minus. Restare per forza potrebbe costargli di più in commissioni.' },
      { t: 'Cambia banca: le minus passano da sole', ok: false, f: 'Non è automatico: senza la certificazione rilasciata dal vecchio intermediario rischia di non poterle più usare.' },
    ] },
    { s: 'Noemi, 28 anni, vuole vendere un ETF azionario con 3.000 € di guadagno. Nello zainetto ha 3.000 € di minusvalenze su azioni e pensa che la vendita sarà esente.', q: 'Cosa deve aspettarsi?', o: [
      { t: 'Un’imposta di circa 780 €, senza compensazione', ok: true, f: 'Per la normativa vigente la plus da ETF è reddito di capitale: 3.000 × 26% = 780 €, e le minus restano nello zainetto.' },
      { t: 'Nessuna imposta: plus e minus si annullano', ok: false, f: 'È l’errore tipico: il guadagno su ETF armonizzati non può assorbire le minusvalenze, che sono redditi diversi.' },
      { t: 'Un’imposta del 12,5%, perché è un ETF', ok: false, f: 'Il 12,5% vale solo per la quota riferibile a titoli di Stato e white list. Su un ETF azionario si applica il 26%.' },
    ] },
  ],
  tip: 'Controlla ogni anno le scadenze del tuo zainetto fiscale e ricorda che le regole cambiano: verifica sempre la normativa in vigore o chiedi a un professionista.',
});
