FQC(97, {
  intro: 'Obiettivi, orizzonte, rischio e regole scritte: costruisci un piano d’investimento che regga anche quando i mercati si agitano.',
  cards: [
    { t: 'Dagli obiettivi agli strumenti', x: 'Un piano parte da cosa vuoi ottenere e quando, non dal prodotto. Gli strumenti si scelgono per ultimi, per realizzare un’allocazione coerente con obiettivi, orizzonte e rischio sopportabile.', v: { k: 'steps', s: ['Obiettivi', 'Orizzonte e rischio', 'Asset allocation', 'Strumenti', 'Monitoraggio'] } },
    { t: 'Obiettivi concreti', x: '“Diventare ricco” non è un obiettivo. “Accumulare 60.000 € per l’anticipo di una casa in 10 anni” sì: ha un importo, una scadenza e permette di calcolare quanto versare.', v: { k: 'icons', d: [['🎯', 'Specifico'], ['📏', 'Misurabile'], ['📅', 'Con una scadenza'], ['✅', 'Realistico']] } },
    { t: 'L’Investment Policy Statement', x: 'L’IPS è un documento in cui scrivi obiettivi, vincoli, allocazione target, regole di ribilanciamento e cosa farai nei crolli. È un contratto con te stesso, firmato a mente fredda.', v: { k: 'vs', a: ['Senza IPS', 'Decisioni prese sull’onda delle notizie'], b: ['Con IPS', 'Regole scritte decise a mente fredda'] } },
    { t: 'Un’allocazione per obiettivo', x: 'Esempio illustrativo per un orizzonte lungo, non una raccomandazione. La quota di azioni dipende da orizzonte, capacità e tolleranza al rischio: non esiste una percentuale giusta per tutti.', v: { k: 'pie', d: [['Azionario globale', 60], ['Obbligazionario', 30], ['Liquidità', 10]] } },
    { t: 'Il tempo lavora per il piano', x: 'Esempio con 200 € al mese e un ipotetico 6% annuo, non garantito: dopo 30 anni hai versato 72.000 € e il capitale stimato è di circa 200.000 €. Iniziare presto conta più dell’importo.', v: { k: 'bars', d: [['10 anni', 32800], ['20 anni', 92400], ['30 anni', 200900]], u: '€' } },
    { t: 'Regole semplici e misurabili', x: 'Le regole migliori sono decise in anticipo: quanto versare, quando ribilanciare, cosa fare se il mercato perde il 30%. Il piano si rivede per cambi di vita, non per le notizie.', v: { k: 'formula', f: 'Ribilancia se una classe si scosta di oltre ±5 punti dal target', n: 'Es.: azioni al 60% → ribilanci sotto il 55% o sopra il 65%' } },
  ],
  terms: [
    ['IPS', 'Documento scritto con obiettivi, vincoli, allocazione target e regole di gestione del portafoglio.'],
    ['Orizzonte temporale', 'Periodo entro cui ti servirà il denaro investito per un determinato obiettivo.'],
    ['Tolleranza al rischio', 'Disponibilità psicologica a sopportare oscillazioni e perdite temporanee.'],
    ['Capacità di rischio', 'Perdite che puoi permetterti senza compromettere obiettivi e tenore di vita.'],
    ['Asset allocation strategica', 'Ripartizione di lungo periodo tra classi di attività, definita in base agli obiettivi.'],
    ['Banda di ribilanciamento', 'Scostamento massimo dal peso target oltre il quale si riporta il portafoglio in equilibrio.'],
    ['Approccio a secchielli', 'Divisione del patrimonio in parti dedicate a obiettivi con orizzonti e rischi diversi.'],
    ['Fondo di emergenza', 'Riserva liquida per imprevisti, tenuta separata dagli investimenti rischiosi.'],
  ],
  tf: [
    ['In un buon piano d’investimento la scelta dei prodotti viene prima della definizione degli obiettivi.', false, 'È il contrario: prima obiettivi, orizzonte e rischio, poi l’allocazione e solo alla fine gli strumenti per realizzarla.'],
    ['Tolleranza al rischio e capacità di rischio possono non coincidere.', true, 'Puoi sentirti pronto a rischiare ma avere un reddito instabile, o viceversa: il piano dovrebbe tenere conto del valore più basso.'],
    ['Un IPS ben scritto indica anche cosa fare durante un forte calo dei mercati.', true, 'Decidere prima come reagire a un crollo evita scelte impulsive proprio quando le emozioni sono più forti.'],
    ['Il piano va modificato ogni volta che i mercati scendono di qualche punto.', false, 'Si rivede per cambi di obiettivi, orizzonte o situazione personale; cambiarlo a ogni oscillazione lo svuota di senso.'],
    ['Il denaro che servirà tra un anno è adatto a un’allocazione prevalentemente azionaria.', false, 'Su orizzonti brevi un calo azionario potrebbe non essere recuperato in tempo: servono strumenti a bassa volatilità.'],
    ['Un fondo di emergenza separato riduce il rischio di dover vendere investimenti nel momento peggiore.', true, 'Gli imprevisti si coprono con la liquidità, senza vendere azioni magari in pieno drawdown.'],
    ['Obiettivi diversi, come la casa tra 5 anni e la pensione tra 30, possono richiedere allocazioni diverse.', true, 'Ogni obiettivo ha il suo orizzonte e quindi il suo livello di rischio sostenibile: per questo si usano spesso i “secchielli”.'],
    ['Un piano d’investimento ben fatto garantisce un rendimento minimo.', false, 'Nessun piano garantisce rendimenti: serve a prendere decisioni coerenti e a gestire il rischio in modo consapevole.'],
    ['Il ribilanciamento può seguire il calendario oppure soglie di scostamento dal target.', true, 'Si può ribilanciare a date fisse, per esempio una volta l’anno, o quando un peso esce dalla banda prevista.'],
    ['Per costruire un piano basta scegliere il fondo che ha reso di più negli ultimi 5 anni.', false, 'Il rendimento passato non è un piano: contano obiettivi, orizzonte, rischio e costi. I migliori di ieri spesso non lo sono domani.'],
  ],
  mcq: [
    { q: 'Qual è il primo passo nella costruzione di un piano d’investimento?', a: 'Definire obiettivi e orizzonte temporale', w: ['Scegliere l’ETF con il costo più basso', 'Aprire un conto presso un broker', 'Analizzare il grafico del FTSE MIB'], e: 'Senza obiettivi e orizzonte non sai quanto rischio puoi prendere né quali strumenti servono: il resto viene dopo.' },
    { q: 'Quale di questi è un obiettivo ben definito?', a: '30.000 € per l’università tra 12 anni', w: ['Far crescere i miei risparmi nel tempo', 'Battere l’indice di riferimento ogni anno', 'Guadagnare il più possibile in borsa'], e: 'Ha un importo e una scadenza: permette di stimare i versamenti necessari e il rischio sostenibile.' },
    { q: 'Quale elemento appartiene a un IPS?', a: 'La regola per ribilanciare il portafoglio', w: ['La previsione sul prezzo del petrolio', 'I titoli più citati sui social', 'Il target di prezzo di un analista'], e: 'L’IPS contiene regole e vincoli stabili, non previsioni o opinioni di breve periodo che cambiano ogni settimana.' },
    { q: 'Silvia ha un’alta tolleranza al rischio, ma reddito precario e nessun fondo di emergenza. Cosa deve prevalere nel piano?', a: 'La sua bassa capacità di rischio', w: ['La sua alta tolleranza al rischio', 'Il rendimento storico più alto', 'La ricerca dei titoli più dinamici'], e: 'Se una perdita la costringesse a vendere per pagare le spese, la tolleranza non servirebbe: prevale il vincolo più stringente.' },
    { q: 'Cosa prevede una banda di ribilanciamento di ±5 punti su un target azionario del 60%?', a: 'Ribilanci se le azioni escono dal 55-65%', w: ['Ribilanci ogni volta che il mercato sale del 5%', 'Vendi tutto se le azioni scendono del 5%', 'Aumenti le azioni del 5% ogni anno'], e: 'Finché il peso resta tra 55% e 65% non fai nulla; fuori dalla banda riporti il portafoglio al 60%.' },
    { q: 'Quale idea sui piani d’investimento è un errore comune?', a: 'Un buon piano evita tutte le perdite', w: ['Un piano va scritto prima di investire', 'Obiettivi diversi hanno orizzonti diversi', 'Il piano si rivede per cambi di vita'], e: 'Un piano non elimina le perdite temporanee: le mette in conto e dice in anticipo come gestirle.' },
    { q: 'Perché dividere il patrimonio in “secchielli” per obiettivo?', a: 'Per dare a ogni obiettivo il giusto rischio', w: ['Per pagare meno imposta di bollo ogni anno', 'Per possedere un numero maggiore di titoli', 'Per poter usare la leva su ogni secchiello'], e: 'La liquidità per la casa tra 3 anni e il risparmio per la pensione tra 30 richiedono rischi diversi: separarli rende tutto più chiaro.' },
    { q: 'Quando ha senso rivedere l’asset allocation strategica?', a: 'Dopo un cambiamento importante di vita', w: ['Dopo ogni notizia sui tassi della BCE', 'Quando un titolo in portafoglio sale del 20%', 'Quando un amico cambia la sua strategia'], e: 'Nascita di un figlio, cambio di lavoro, pensione vicina: cambiano obiettivi e orizzonte. Le notizie di mercato invece no.' },
  ],
  fill: [
    { s: 'Il documento con obiettivi e regole del tuo portafoglio si chiama ___.', a: 'IPS', w: ['KID', 'ISIN', 'IBAN'] },
    { s: 'L’orizzonte ___ è il periodo entro cui ti servirà il denaro investito.', a: 'temporale', w: ['fiscale', 'contabile', 'tecnico'] },
    { s: 'La ___ di rischio indica quante perdite puoi permetterti senza compromettere i tuoi obiettivi.', a: 'capacità', w: ['percezione', 'memoria', 'leva'] },
    { s: 'Riportare i pesi del portafoglio ai valori target si chiama ___.', a: 'ribilanciamento', w: ['arbitraggio', 'hedging', 'market timing'] },
    { s: 'Prima di investire conviene avere un fondo di ___ per gli imprevisti.', a: 'emergenza', w: ['investimento', 'pensione', 'garanzia'] },
  ],
  order: [
    { q: 'Ordina le fasi di costruzione di un piano d’investimento', i: ['Definisci obiettivi e scadenze', 'Valuta tolleranza e capacità di rischio', 'Scegli l’asset allocation', 'Seleziona gli strumenti', 'Monitora e ribilancia'], e: 'Si parte dal perché e dal quando; il rischio sostenibile determina l’allocazione; gli strumenti vengono dopo e il monitoraggio non finisce mai.' },
    { q: 'Ordina gli obiettivi dall’orizzonte più breve al più lungo', i: ['Fondo per un imprevisto', 'Viaggio tra 2 anni', 'Anticipo casa tra 7 anni', 'Università dei figli tra 15 anni', 'Pensione tra 30 anni'], e: 'Più l’orizzonte è lungo, più rischio si può in genere sostenere: il fondo imprevisti resta liquido, la pensione può contenere più azioni.' },
  ],
  cat: [
    { q: 'Da inserire in un IPS o da evitare?', g: [['Da inserire', ['Allocazione target', 'Regole di ribilanciamento', 'Piano per i forti cali']], ['Da evitare', ['Previsioni di mercato a breve', 'Titoli suggeriti sui forum', 'Obiettivo generico “fare soldi”']]] },
    { q: 'Impostazione più adatta a un orizzonte breve o lungo?', g: [['Orizzonte breve (1-3 anni)', ['Conto deposito vincolato', 'BOT e titoli a breve scadenza', 'Fondo monetario']], ['Orizzonte lungo (20+ anni)', ['ETF azionario globale', 'PAC su un indice ampio', 'Portafoglio bilanciato diversificato']]] },
  ],
  scen: [
    { s: 'Lorenzo, 32 anni, vuole iniziare a investire 300 € al mese. Un collega gli consiglia un titolo “sicuro” del momento. Lorenzo non ha ancora un fondo di emergenza.', q: 'Da dove parte?', o: [
      { t: 'Fondo di emergenza, poi obiettivi e allocazione', ok: true, f: 'Prima la protezione dagli imprevisti, poi un piano scritto: così non sarà costretto a vendere nel momento sbagliato.' },
      { t: 'Compra il titolo, al piano penserà dopo', ok: false, f: 'Partire dal prodotto rovescia il processo: un singolo titolo consigliato da un collega non è un piano.' },
      { t: 'Investe in un prodotto a leva per recuperare tempo', ok: false, f: 'La leva amplifica le perdite: senza fondo di emergenza e senza piano è una scommessa, non un investimento.' },
    ] },
    { s: 'Simona, 47 anni, ha un IPS con target 60% azioni e banda di ±5 punti. Dopo un forte rialzo le azioni sono arrivate al 68% del portafoglio.', q: 'Cosa fa?', o: [
      { t: 'Ribilancia verso il 60%, come previsto', ok: true, f: 'È esattamente il caso per cui la regola esiste: vende parte di ciò che è salito e riporta il rischio al livello scelto.' },
      { t: 'Lascia correre: le azioni vanno bene', ok: false, f: 'Così il portafoglio diventa più rischioso di quanto deciso, proprio dopo un rialzo: è recency bias.' },
      { t: 'Porta le azioni al 90% per seguire il trend', ok: false, f: 'Stravolge il piano sull’onda dell’entusiasmo: un calo successivo colpirebbe un portafoglio molto più esposto.' },
    ] },
    { s: 'Matteo e Laura, 38 e 36 anni, risparmiano per l’anticipo della casa tra 4 anni e per la pensione. Tengono tutto in un unico ETF azionario globale.', q: 'Come possono migliorare il piano?', o: [
      { t: 'Separare i due obiettivi con rischi diversi', ok: true, f: 'Per la casa servono strumenti a bassa volatilità; per la pensione, lontana, è sostenibile più azionario.' },
      { t: 'Tenere tutto in azioni: rendono di più', ok: false, f: 'Un calo del 30% a un anno dall’acquisto della casa potrebbe far saltare l’obiettivo più vicino.' },
      { t: 'Spostare tutto in liquidità, pensione compresa', ok: false, f: 'Per un obiettivo a 30 anni la liquidità rischia di perdere potere d’acquisto per l’inflazione.' },
    ] },
    { s: 'Giuseppe, 63 anni, andrà in pensione tra due anni. Il suo portafoglio è ancora al 90% in azioni, come aveva deciso a 40 anni, e non l’ha mai rivisto.', q: 'Cosa dovrebbe fare?', o: [
      { t: 'Rivedere il piano: orizzonte e bisogni sono cambiati', ok: true, f: 'La pensione vicina è un cambio di vita: un forte calo ora potrebbe incidere sul reddito futuro. Rivedere il piano è doveroso.' },
      { t: 'Non cambiare nulla: il piano non si tocca mai', ok: false, f: 'Il piano non si cambia per le notizie, ma va aggiornato quando cambiano obiettivi e orizzonte.' },
      { t: 'Aumentare le azioni per avere più capitale', ok: false, f: 'Aumentare il rischio a ridosso del momento in cui servirà il denaro espone a un drawdown che non avrebbe tempo di recuperare.' },
    ] },
  ],
  tip: 'Scrivi il tuo piano su una pagina: obiettivi, orizzonte, allocazione, versamenti, regole di ribilanciamento e cosa farai in un crollo. Rileggilo prima di ogni decisione.',
});
