FQC(98, {
  intro: 'Trading attivo o investimento paziente? Costi, tempo, statistica e cosa dicono i dati sui risultati degli investitori privati.',
  cards: [
    { t: 'Due approcci diversi', x: 'Il trading cerca di sfruttare i movimenti di prezzo di breve periodo; l’investimento a lungo termine punta a partecipare alla crescita di aziende ed economie nel corso degli anni.', v: { k: 'vs', a: ['Trading', 'Orizzonte breve, tante operazioni, risultato legato al timing'], b: ['Lungo termine', 'Orizzonte lungo, poche operazioni, risultato legato alla crescita'] } },
    { t: 'L’asticella dei costi', x: 'Nel breve periodo il trading è, al lordo dei costi, quasi un gioco a somma zero tra partecipanti; commissioni, spread e imposte lo rendono negativo in media. Più operi, più l’asticella sale.', v: { k: 'formula', f: 'Rendimento netto = lordo − commissioni − spread − imposte', n: 'Es.: 200 operazioni × 5 € = 1.000 € l’anno di sole commissioni' } },
    { t: 'Il dato sui CFD', x: 'L’ESMA ha rilevato che la grande maggioranza dei conti retail perde denaro con i CFD: per questo i broker devono mostrare un’avvertenza con la percentuale dei propri clienti in perdita.', v: { k: 'stat', n: '74-89%', l: 'dei conti retail in perdita sui CFD (rilevazione ESMA)' } },
    { t: 'Il tempo riduce il rumore', x: 'Su un giorno il movimento di un indice azionario è quasi solo rumore; su decenni, storicamente, ha prevalso la crescita di utili ed economia. Non è una garanzia, ma il tempo ha ridotto la dispersione dei risultati.', v: { k: 'scale', a: 'Domina il caso', b: 'Domina la crescita di fondo', d: [['Un giorno', 8], ['Un anno', 35], ['Dieci anni', 70], ['Vent’anni', 85]] } },
    { t: 'I costi nascosti del trading', x: 'Il trading richiede ore di analisi, disciplina e capitale da rischiare. In più, ogni plusvalenza realizzata viene tassata subito, mentre chi mantiene a lungo rinvia l’imposta e lascia lavorare l’interesse composto.', v: { k: 'icons', d: [['⏰', 'Tempo e attenzione'], ['😰', 'Stress decisionale'], ['🧾', 'Imposte anticipate'], ['💸', 'Costi di transazione']] } },
    { t: 'Serve un vantaggio statistico', x: 'Per guadagnare nel trading serve un vantaggio (edge) che resti positivo dopo i costi, su centinaia di operazioni. Un piccolo vantaggio lordo può diventare negativo al netto. Valori dell’esempio puramente illustrativi.', v: { k: 'bars', d: [['Edge lordo', 0.3], ['Costi', -0.4], ['Edge netto', -0.1]], u: '%' } },
  ],
  terms: [
    ['Trading', 'Compravendita frequente per sfruttare movimenti di prezzo di breve periodo.'],
    ['Buy and hold', 'Strategia che compra e mantiene gli strumenti per anni, ignorando le oscillazioni di breve.'],
    ['Day trading', 'Operatività in cui le posizioni si aprono e si chiudono nella stessa giornata.'],
    ['Edge', 'Vantaggio statistico che rende positivo il valore atteso di una strategia dopo i costi.'],
    ['Market timing', 'Tentativo di entrare e uscire dal mercato anticipandone i movimenti.'],
    ['Turnover', 'Quota del portafoglio compravenduta in un anno: più è alta, più crescono i costi.'],
    ['Gioco a somma zero', 'Situazione in cui il guadagno di un partecipante corrisponde alla perdita di un altro.'],
    ['Swing trading', 'Operatività che mantiene le posizioni da alcuni giorni a qualche settimana.'],
  ],
  tf: [
    ['Al lordo dei costi, il trading di breve periodo è in larga parte un gioco a somma zero tra i partecipanti.', true, 'Rispetto al mercato, ciò che un trader guadagna in più un altro lo guadagna in meno: sottraendo i costi, la somma diventa negativa.'],
    ['Secondo le rilevazioni dell’ESMA, la maggioranza dei conti retail che negoziano CFD perde denaro.', true, 'Le percentuali rilevate andavano dal 74% all’89%: per questo i broker devono esporre un’avvertenza sui conti in perdita.'],
    ['Più operazioni fai, più è probabile che i costi erodano il tuo rendimento.', true, 'Ogni operazione paga commissioni e spread: con molte operazioni anche costi piccoli diventano una zavorra pesante.'],
    ['Il market timing è facile: basta uscire prima dei ribassi e rientrare prima dei rialzi.', false, 'Richiede due previsioni giuste, uscita e rientro. Perdere pochi giorni di forte rialzo ha storicamente ridotto molto il rendimento.'],
    ['Investire a lungo termine in un indice azionario elimina il rischio di perdite.', false, 'Riduce il peso delle oscillazioni di breve, ma non elimina il rischio: anche su periodi lunghi ci sono stati rendimenti deludenti.'],
    ['Una strategia con un piccolo guadagno atteso prima dei costi può risultare in perdita dopo i costi.', true, 'Se commissioni e spread superano il vantaggio lordo, il valore atteso netto diventa negativo.'],
    ['Fare trading con orizzonte giornaliero è il modo migliore per sfruttare la crescita economica di lungo periodo.', false, 'La crescita economica si manifesta in anni: chi opera su un giorno è esposto soprattutto al rumore dei prezzi.'],
    ['Lo swing trading mantiene di solito le posizioni per diversi anni.', false, 'Lo swing trading lavora su orizzonti da alcuni giorni a qualche settimana; le posizioni pluriennali sono tipiche del buy and hold.'],
    ['Qualche mese di guadagni con il trading basta a dimostrare di avere un vantaggio statistico.', false, 'Pochi mesi sono un campione troppo piccolo: servono molte operazioni e periodi diversi per distinguere abilità e fortuna.'],
    ['Storicamente molti dei giorni migliori di borsa si sono verificati vicino ai giorni peggiori.', true, 'Nei periodi di alta volatilità grandi cali e grandi rimbalzi si alternano: chi esce per paura rischia di perdere i rimbalzi.'],
  ],
  mcq: [
    { q: 'Un trader invia 300 ordini l’anno con 4 € di commissione ciascuno, su un capitale di 20.000 €. Quanto pesano le sole commissioni?', a: '6% del capitale', w: ['0,6% del capitale', '1,2% del capitale', '12% del capitale'], e: '300 × 4 € = 1.200 €, cioè il 6% di 20.000 €. Prima di guadagnare, deve rendere il 6% solo per coprire le commissioni.' },
    { q: 'Perché i costi pesano di più sul trading che sull’investimento di lungo periodo?', a: 'Perché si ripetono a ogni operazione', w: ['Perché il trading ha aliquote più alte', 'Perché i broker vietano gli ordini limite', 'Perché di giorno le azioni costano di più'], e: 'Commissioni e spread si pagano a ogni ingresso e uscita: con decine di operazioni al mese la somma diventa rilevante.' },
    { q: 'Cosa serve a un trader per avere, nel tempo, un risultato atteso positivo?', a: 'Un vantaggio netto dopo i costi', w: ['Un conto con una leva più alta', 'Più operazioni ogni giorno', 'Un grafico con più indicatori'], e: 'Senza un edge netto positivo, più operazioni e più leva accelerano solo le perdite.' },
    { q: 'Quale affermazione sul trading è un mito?', a: 'Si vive di trading dopo pochi mesi', w: ['I costi riducono il rendimento netto', 'Serve un ampio campione di operazioni', 'La leva amplifica le perdite'], e: 'I dati sui conti retail mostrano che la maggioranza perde: vivere di trading è raro e richiede capitale, tempo e un vantaggio verificato.' },
    { q: 'Cosa rischia chi esce dal mercato dopo un crollo per “rientrare più in basso”?', a: 'Perdere i rimbalzi che spesso seguono', w: ['Dover pagare una penale alla CONSOB', 'Perdere il diritto ai dividendi futuri', 'Dover chiudere il proprio conto titoli'], e: 'I rimbalzi più forti arrivano spesso quando il pessimismo è massimo: rientrare al momento giusto è molto difficile.' },
    { q: 'Quale fattore rende l’investimento di lungo periodo più favorevole del trading per la maggior parte dei risparmiatori?', a: 'Costi bassi e tempo per la crescita composta', w: ['La garanzia del capitale da parte della borsa', 'L’assenza totale di oscillazioni', 'L’accesso a informazioni riservate'], e: 'Pochi costi e molti anni lasciano lavorare la crescita composta; nessuno però garantisce il capitale o elimina le oscillazioni.' },
    { q: 'Un trader vince il 55% delle volte, con guadagno medio pari alla perdita media. I costi valgono il 15% della perdita media per operazione. Risultato atteso?', a: 'Leggermente negativo', w: ['Positivo del 10%', 'Esattamente nullo', 'Positivo del 55%'], e: 'Lordo: 0,55 − 0,45 = +0,10 unità di rischio. Togliendo 0,15 di costi si scende a −0,05: un vantaggio piccolo non regge costi alti.' },
    { q: 'Quale differenza fiscale c’è, a parità di aliquota, tra trading frequente e buy and hold su azioni?', a: 'Il buy and hold rinvia l’imposta', w: ['Il trading paga solo il 12,5%', 'Il buy and hold è esente dal bollo', 'Il trading è esente sotto 1.000 €'], e: 'Chi vende spesso realizza e paga subito le plusvalenze; chi mantiene paga alla vendita e intanto l’intero capitale continua a crescere.' },
  ],
  fill: [
    { s: 'Il ___ trading apre e chiude le posizioni nella stessa giornata.', a: 'day', w: ['swing', 'position', 'carry'] },
    { s: 'Un vantaggio statistico che resta positivo dopo i costi si chiama ___.', a: 'edge', w: ['spread', 'gap', 'pivot'] },
    { s: 'Il tentativo di anticipare entrate e uscite dal mercato si chiama market ___.', a: 'timing', w: ['making', 'maker', 'cap'] },
    { s: 'Il ___ misura quanta parte del portafoglio viene compravenduta in un anno.', a: 'turnover', w: ['TER', 'drawdown', 'beta'] },
    { s: 'Al lordo dei costi, il trading di breve è quasi un gioco a somma ___.', a: 'zero', w: ['positiva', 'fissa', 'doppia'] },
  ],
  order: [
    { q: 'Ordina gli stili dall’orizzonte più breve al più lungo', i: ['Scalping', 'Day trading', 'Swing trading', 'Position trading', 'Buy and hold'], e: 'Lo scalping dura secondi o minuti, il day trading una giornata, lo swing giorni o settimane, il position trading mesi, il buy and hold anni.' },
    { q: 'Ordina dal turnover più basso al più alto', i: ['Buy and hold su un ETF globale', 'Portafoglio ribilanciato una volta l’anno', 'Swing trading', 'Day trading'], e: 'Più compravendite significano più turnover, quindi più commissioni, spread e imposte realizzate in anticipo.' },
  ],
  cat: [
    { q: 'Tipico del trading o dell’investimento a lungo termine?', g: [['Trading', ['Analisi dei grafici intraday', 'Stop loss stretti', 'Decine di operazioni al mese']], ['Lungo termine', ['Orizzonte di decenni', 'Ribilanciamento periodico', 'PAC su indici ampi']]] },
    { q: 'Aumenta o riduce le probabilità di successo di un trader?', g: [['Aumenta', ['Costi di transazione bassi', 'Rischio per operazione limitato', 'Diario delle operazioni']], ['Riduce', ['Leva elevata', 'Operare per noia', 'Cambiare strategia dopo ogni perdita']]] },
  ],
  scen: [
    { s: 'Riccardo, 24 anni, ha guadagnato il 20% in tre mesi facendo trading con 5.000 €. Pensa di lasciare il lavoro e fare trading a tempo pieno con tutti i suoi 15.000 € di risparmi.', q: 'Cosa gli conviene fare?', o: [
      { t: 'Tenere il lavoro e continuare a misurare i risultati', ok: true, f: 'Tre mesi sono un campione minimo: servono molte operazioni, in mercati diversi, per capire se c’è un vantaggio reale al netto dei costi.' },
      { t: 'Licenziarsi: il 20% in tre mesi dimostra il talento', ok: false, f: 'Un buon trimestre può essere fortuna. Senza stipendio, ogni perdita colpirebbe anche le spese di vita: pressione enorme.' },
      { t: 'Chiedere un prestito per avere più capitale', ok: false, f: 'Indebitarsi per fare trading somma leva e rischio di dover restituire soldi anche in caso di perdite.' },
    ] },
    { s: 'Elisa, 40 anni, investe a lungo termine in un ETF azionario globale. Il mercato perde il 20% e un collega le dice: “Esci adesso e rientri quando ha toccato il fondo”.', q: 'Cosa fa?', o: [
      { t: 'Resta investita secondo il piano', ok: true, f: 'Il market timing richiede due previsioni corrette. I rimbalzi spesso arrivano all’improvviso, quando il pessimismo è massimo.' },
      { t: 'Esce del tutto e aspetta un segnale per rientrare', ok: false, f: 'Il fondo si riconosce solo dopo: rischia di rientrare a prezzi più alti di quelli a cui è uscita.' },
      { t: 'Esce a metà e rientra quando i giornali sono ottimisti', ok: false, f: 'Quando i giornali tornano ottimisti, di solito i prezzi sono già risaliti: compra caro dopo aver venduto a sconto.' },
    ] },
    { s: 'Fabio, 35 anni, ha un portafoglio di lungo periodo e vuole provare il trading per passione.', q: 'Come si organizza?', o: [
      { t: 'Un piccolo conto separato, con risultati netti misurati', ok: true, f: 'Separare i conti protegge il piano di lungo periodo e rende chiaro se il trading crea valore dopo i costi.' },
      { t: 'Usa tutto il portafoglio: più capitale, più guadagni', ok: false, f: 'Mette a rischio gli obiettivi di lungo periodo per un’attività di cui non ha ancora verificato il vantaggio.' },
      { t: 'Opera sulla parte destinata alla pensione', ok: false, f: 'Proprio il denaro più importante finirebbe esposto a un’attività ad alto rischio e costo.' },
    ] },
    { s: 'Marta, 52 anni, chiude l’anno di trading con +8% lordo. Le commissioni le sono costate il 3% e deve pagare le imposte sulle plusvalenze. Nello stesso anno un ETF sull’indice di riferimento ha fatto +10%.', q: 'Come valuta il suo anno?', o: [
      { t: 'Calcola il netto e lo confronta con l’ETF', ok: true, f: 'Al netto di costi e imposte ha fatto molto meno dell’alternativa passiva: è il confronto che dice se il tempo speso ha creato valore.' },
      { t: 'Considera solo il lordo: misura la sua abilità', ok: false, f: 'Il lordo ignora ciò che ha pagato davvero: conta quello che resta in tasca rispetto all’alternativa più semplice.' },
      { t: 'Aumenta le operazioni per compensare i costi', ok: false, f: 'Più operazioni significano più costi: senza un vantaggio netto il risultato tende a peggiorare.' },
    ] },
  ],
  tip: 'Se vuoi fare trading, usa una piccola quota separata e registra ogni operazione al netto dei costi. Confronta il risultato con un semplice ETF: decidono i numeri.',
});
