FQC(100, {
  intro: 'L’ultimo livello: colleghi tutto il percorso, dal denaro ai derivati, in una visione da investitore consapevole.',
  cards: [
    { t: 'Le fondamenta', x: 'Tutto parte da qui: l’inflazione erode il denaro fermo, l’interesse composto premia il tempo e un fondo di emergenza ti evita di vendere nel momento sbagliato.', v: { k: 'formula', f: 'Rendimento reale ≈ nominale − inflazione', n: 'Es.: 5% − 2% = 3% di potere d’acquisto in più' } },
    { t: 'Lo spettro rischio-rendimento', x: 'Ogni strumento si colloca su uno spettro: più rendimento atteso significa più rischio. Nessuno strumento offre insieme rendimento alto, liquidità immediata e sicurezza totale.', v: { k: 'scale', a: 'Rischio più basso', b: 'Rischio più alto', d: [['Conto deposito', 8], ['BTP a breve', 20], ['Obbligazioni societarie', 40], ['ETF azionario globale', 65], ['Derivati a leva', 95]] } },
    { t: 'Gli ingranaggi del mercato', x: 'Azioni per partecipare agli utili, obbligazioni per flussi più prevedibili, ETF per diversificare a costi bassi, derivati per coprire o speculare con leva. Ognuno ha un ruolo e rischi propri.', v: { k: 'icons', d: [['📈', 'Azioni: quote di aziende'], ['📜', 'Obbligazioni: prestiti'], ['🧺', 'ETF: panieri a basso costo'], ['⚙️', 'Derivati: leva e coperture']] } },
    { t: 'La catena dei tassi', x: 'Le banche centrali influenzano i tassi; i tassi muovono obbligazioni, valutazioni azionarie e valute. Capire questa catena aiuta a leggere le notizie macro senza reagire d’impulso.', v: { k: 'vs', a: ['Tassi in salita', 'Prezzi delle obbligazioni in calo, di più con duration alta'], b: ['Tassi in discesa', 'Prezzi delle obbligazioni in rialzo'] } },
    { t: 'Il portafoglio consapevole', x: 'Esempio illustrativo, non una raccomandazione: l’allocazione giusta dipende da obiettivi, orizzonte e tolleranza al rischio. Diversificazione, costi bassi e ribilanciamento pesano spesso più della ricerca del titolo perfetto.', v: { k: 'pie', d: [['Azioni globali', 50], ['Obbligazioni', 35], ['Liquidità', 10], ['Altro', 5]] } },
    { t: 'Le regole che proteggono', x: 'Bias, leva eccessiva, costi, fisco trascurato e truffe sono tra le cause più comuni di risultati deludenti. Un piano scritto e poche regole semplici proteggono il capitale più di qualsiasi previsione.', v: { k: 'steps', s: ['Piano scritto', 'Position sizing', 'Regole automatiche', 'Verifica di costi, fisco e intermediari'] } },
  ],
  terms: [
    ['Interesse composto', 'Meccanismo per cui gli interessi maturati producono a loro volta interessi nel tempo.'],
    ['Duration', 'Misura della sensibilità del prezzo di un’obbligazione alle variazioni dei tassi.'],
    ['P/E', 'Rapporto tra prezzo di un’azione e utile per azione, usato per confrontare valutazioni.'],
    ['Correlazione', 'Grado in cui due asset si muovono insieme: se è bassa, la diversificazione funziona meglio.'],
    ['TER', 'Costo annuo complessivo di gestione di un fondo o ETF, espresso in percentuale.'],
    ['Leva finanziaria', 'Uso di prestiti o derivati per aumentare l’esposizione, amplificando guadagni e perdite.'],
    ['Spread denaro-lettera', 'Differenza tra prezzo lettera e prezzo denaro di un titolo: un costo implicito di ogni scambio.'],
    ['Asset allocation', 'Ripartizione del patrimonio tra classi di attività come azioni, obbligazioni e liquidità.'],
  ],
  tf: [
    ['Con un’inflazione al 3% e un conto che rende l’1%, il potere d’acquisto dei risparmi diminuisce.', true, 'Il rendimento reale è circa 1% − 3% = −2%: il saldo nominale cresce, ma compra meno beni di prima.'],
    ['Quando i tassi di mercato salgono, i prezzi delle obbligazioni già in circolazione tendono a salire.', false, 'Salgono i rendimenti richiesti, quindi i vecchi titoli con cedole più basse valgono meno: i prezzi scendono, di più con duration alta.'],
    ['Un ETF che replica un indice ampio offre diversificazione immediata a costi in genere contenuti.', true, 'Con un solo strumento si possiedono centinaia o migliaia di titoli, spesso con un TER molto basso.'],
    ['Un P/E basso indica sempre che un’azione è un affare.', false, 'Può riflettere utili in calo o rischi elevati (value trap): il multiplo va letto insieme a crescita, debito e qualità del business.'],
    ['L’analisi tecnica permette di prevedere con certezza i movimenti futuri dei prezzi.', false, 'Lavora su probabilità, non certezze: i segnali falliscono spesso e vanno sempre gestiti con stop e position sizing.'],
    ['La leva finanziaria amplifica sia i guadagni sia le perdite.', true, 'Con leva 5, un calo del 20% del sottostante azzera il capitale investito: la leva moltiplica gli effetti in entrambe le direzioni.'],
    ['Dopo una perdita del 50% basta un guadagno del 50% per tornare in pari.', false, 'Da 100 si scende a 50 e un +50% porta solo a 75: per tornare a 100 serve un +100%.'],
    ['Combinare asset poco correlati può ridurre la volatilità del portafoglio più di quanto riduca il rendimento atteso.', true, 'È il principio della diversificazione: le oscillazioni si compensano in parte, mentre i rendimenti attesi si sommano in media ponderata.'],
    ['In Italia la plusvalenza sulla vendita di azioni è in genere tassata al 26%.', true, 'È l’aliquota ordinaria sui redditi finanziari; i titoli di Stato italiani e white list godono del 12,5%. Le regole possono cambiare.'],
    ['Un intermediario assente dagli elenchi CONSOB ma con ottime recensioni online è affidabile.', false, 'Le recensioni si possono falsificare: senza autorizzazione verificabile negli elenchi ufficiali, non si investe.'],
  ],
  mcq: [
    { q: 'Quale combinazione descrive meglio un investitore consapevole?', a: 'Piano scritto, costi bassi, rischio dimensionato', w: ['Titoli di moda, leva alta, tanti scambi', 'Liquidità ferma, nessun piano né obiettivo', 'Un solo titolo, nessuno stop, medie al ribasso'], e: 'Piano, costi contenuti, diversificazione e controllo del rischio sono il filo conduttore di tutto il percorso.' },
    { q: 'La BCE alza i tassi in modo inatteso. Quale effetto è più probabile nel breve periodo?', a: 'Calo dei prezzi dei BTP a lunga scadenza', w: ['Rialzo dei prezzi dei BTP a lunga scadenza', 'Aumento automatico dei dividendi', 'Garanzia di un euro più debole'], e: 'Tassi più alti riducono il valore dei titoli già emessi con cedole più basse; l’effetto è maggiore sulle scadenze lunghe, a duration più alta.' },
    { q: 'Due ETF replicano lo stesso indice: uno ha TER 0,07%, l’altro 0,50%. Su un orizzonte lungo, a parità del resto…', a: 'Il TER più basso tende a lasciarti di più', w: ['Il TER più alto garantisce una gestione migliore', 'La differenza è irrilevante su ogni orizzonte', 'Il TER incide solo nel primo anno'], e: 'Su un indice identico il costo è la principale differenza prevedibile: la distanza tra i due si accumula ogni anno con l’interesse composto.' },
    { q: 'Capitale 50.000 €, rischio 1% per operazione, stop a 5 € dall’ingresso. Quante azioni compri?', a: '100', w: ['1.000', '50', '10.000'], e: 'Rischio in euro: 50.000 × 1% = 500 €. Quantità: 500 ÷ 5 = 100 azioni.' },
    { q: 'Quale abbinamento tra strumento e funzione è corretto?', a: 'Opzione put: protezione dai ribassi', w: ['Future: garanzia del capitale', 'CFD: investimento a basso rischio', 'Azione: rendimento fisso garantito'], e: 'Una put acquistata guadagna se il sottostante scende sotto lo strike: per questo si usa come copertura, pagando un premio.' },
    { q: 'Quale convinzione errata è stata smontata più volte nel percorso?', a: '“I rendimenti passati garantiscono i futuri”', w: ['“I costi riducono il rendimento netto”', '“La leva amplifica anche le perdite”', '“Diversificare riduce il rischio specifico”'], e: 'Il passato aiuta a capire rischi e comportamenti, ma non garantisce nulla: dai fondi “stellati” alle strategie di trading.' },
    { q: 'Ti servono 20.000 € tra 18 mesi per acquistare un’auto. Quale scelta è più coerente?', a: 'Strumenti a breve scadenza e bassa volatilità', w: ['Un ETF azionario dei mercati emergenti', 'Opzioni call su un indice azionario', 'Azioni di una singola small cap'], e: 'Con un orizzonte così breve un calo non avrebbe tempo di essere recuperato: conta preservare il capitale più che massimizzarlo.' },
    { q: 'Un titolo ha P/E 40, il suo settore in media 15. Cosa ti dice, da solo, questo dato?', a: 'Il mercato prezza attese di crescita più alte', w: ['Il titolo è certamente sopravvalutato', 'Il titolo è certamente sottovalutato', 'Il titolo pagherà dividendi più alti'], e: 'Un multiplo alto riflette aspettative elevate: possono essere giustificate o eccessive. Servono crescita, margini e flussi di cassa per giudicare.' },
  ],
  fill: [
    { s: 'Il prezzo di un’obbligazione e il suo rendimento si muovono in direzione ___.', a: 'opposta', w: ['identica', 'parallela', 'casuale'] },
    { s: 'La ___ riduce il rischio specifico distribuendo il capitale su molti titoli.', a: 'diversificazione', w: ['leva', 'speculazione', 'concentrazione'] },
    { s: 'Il fondo di ___ evita di dover vendere gli investimenti nel momento peggiore.', a: 'emergenza', w: ['garanzia', 'investimento', 'rotazione'] },
    { s: 'Una ___ call dà il diritto, non l’obbligo, di comprare a un prezzo prefissato.', a: 'opzione', w: ['obbligazione', 'azione', 'cedola'] },
    { s: 'Investire una cifra fissa a intervalli regolari si chiama piano di ___.', a: 'accumulo', w: ['ammortamento', 'rimborso', 'riparto'] },
  ],
  order: [
    { q: 'Ordina i passi di un percorso finanziario consapevole', i: ['Metti in ordine budget e debiti costosi', 'Costruisci il fondo di emergenza', 'Scrivi obiettivi e piano', 'Investi con un’allocazione diversificata', 'Ribilancia e rivedi per cambi di vita'], e: 'Prima la stabilità, poi la protezione dagli imprevisti, quindi il piano e l’investimento: senza basi solide ogni crollo diventa un’emergenza.' },
    { q: 'Ordina dal meno rischioso al più rischioso', i: ['Conto deposito', 'BTP a 10 anni', 'ETF azionario globale', 'CFD con leva elevata'], e: 'Dal capitale stabile al rischio tasso, poi al rischio azionario diversificato, fino alla leva che può azzerare il capitale in poco tempo.' },
  ],
  cat: [
    { q: 'Rischio sistematico o rischio specifico?', g: [['Sistematico (di mercato)', ['Recessione globale', 'Rialzo dei tassi della BCE', 'Crisi finanziaria internazionale']], ['Specifico (riducibile diversificando)', ['Scandalo contabile di un’azienda', 'Fallimento di un singolo emittente', 'Richiamo di un prodotto difettoso']]] },
    { q: 'Strumento di analisi fondamentale o tecnica?', g: [['Analisi fondamentale', ['P/E e multipli', 'Free cash flow', 'Valutazione DCF']], ['Analisi tecnica', ['Medie mobili', 'RSI', 'Supporti e resistenze']]] },
  ],
  scen: [
    { s: 'Serena, 30 anni, eredita 50.000 €. Ha già un fondo di emergenza e un lavoro stabile. Un amico le consiglia il titolo “che quest’anno è salito di più”.', q: 'Cosa fa?', o: [
      { t: 'Scrive obiettivi e piano, poi investe in modo diversificato', ok: true, f: 'Obiettivi, orizzonte e rischio guidano l’allocazione; entrare anche in modo graduale può aiutarla a gestire l’emotività.' },
      { t: 'Mette tutto sul titolo che è salito di più', ok: false, f: 'Concentrazione e recency bias insieme: il rialzo passato non dice nulla sul futuro e un singolo titolo può crollare.' },
      { t: 'Lascia tutto sul conto corrente per non rischiare', ok: false, f: 'Il rischio non sparisce: l’inflazione erode il potere d’acquisto e il denaro fermo non lavora per i suoi obiettivi.' },
    ] },
    { s: 'Michele, 48 anni, ha un BTP a 10 anni che terrà fino a scadenza. I tassi salgono e il prezzo del titolo scende del 12%.', q: 'Come valuta la situazione?', o: [
      { t: 'Ricorda che a scadenza riceverà il nominale', ok: true, f: 'Se l’emittente rimborsa, a scadenza incassa il valore nominale: il calo di prezzo conta solo se vende prima.' },
      { t: 'Vende subito per evitare altre perdite', ok: false, f: 'Trasformerebbe una perdita temporanea in perdita realizzata, pur avendo deciso di tenere il titolo fino a scadenza.' },
      { t: 'Compra opzioni con leva per recuperare', ok: false, f: 'Rispondere a un calo con la leva aggiunge rischio senza risolvere nulla: è una reazione emotiva.' },
    ] },
    { s: 'Rita, 55 anni, vede una pubblicità: “Bot di trading con intelligenza artificiale, 5% a settimana garantito”. Per iniziare bisogna versare in criptovaluta.', q: 'Cosa fa?', o: [
      { t: 'Lascia perdere: ha tutti i segnali di una truffa', ok: true, f: 'Rendimento garantito altissimo e pagamento in cripto non tracciabile sono segnali classici. Nessuna tecnologia garantisce il 5% a settimana.' },
      { t: 'Prova con 1.000 € per vedere se funziona', ok: false, f: 'I primi “guadagni” servono a convincere a versare di più: anche 1.000 € sarebbero molto probabilmente persi.' },
      { t: 'Chiede screenshot dei guadagni di altri clienti', ok: false, f: 'Gli screenshot si falsificano in pochi secondi: l’unica verifica valida è l’autorizzazione negli elenchi CONSOB.' },
    ] },
    { s: 'Daniele, 37 anni, ha un piano scritto, ma dopo un calo del 25% del portafoglio vuole passare al trading con leva per “recuperare in fretta”.', q: 'Qual è la scelta più consapevole?', o: [
      { t: 'Torna al piano: allocazione, ribilanciamento, rischio', ok: true, f: 'Il piano è stato scritto per questi momenti. Inseguire il recupero con la leva rischia di trasformare un calo in una perdita permanente.' },
      { t: 'Usa leva 10 per recuperare in un mese', ok: false, f: 'Con leva 10 basta un movimento contrario del 10% per azzerare il capitale investito: un drawdown può diventare definitivo.' },
      { t: 'Vende tutto e aspetta che il mercato si calmi', ok: false, f: 'Vendere dopo il calo realizza la perdita; rientrare “quando è calmo” spesso significa farlo a prezzi più alti.' },
    ] },
  ],
  tip: 'Il vero vantaggio dell’investitore privato è la pazienza: costi bassi, diversificazione, un piano scritto e calma nei momenti difficili. E continua a imparare.',
});
