/* Scenario 4 · ASL Valle Serena · gara pubblica, consultazione di mercato, partner, correttezza */
(function (g) {
  'use strict';
  const CL = g.CL, ch = CL.ch;

  CL.registerScenario({
    id: 'asl',
    title: `La Gara`,
    client: `ASL Valle Serena`,
    sector: `Sanità pubblica · gara`,
    hook: `Quando il bando è pubblicato, le regole del gioco cambiano: vince chi le rispetta meglio.`,
    brief: `Sistema di logistica sanitaria e gestione scorte per sei presidi ospedalieri: €750k di ACV a listino, in gara pubblica con criterio dell’offerta economicamente più vantaggiosa. L’ASL ha aperto una consultazione preliminare di mercato. Il concorrente, Vertex Systems, è già fornitore di altre ASL della regione.`,
    scout: `L’unico momento in cui puoi incidere legittimamente è la consultazione: dopo la pubblicazione ogni contatto riservato col RUP è un rischio. Il partner locale più forte, Sinergia IT, ha anche un accordo di rivendita con Vertex.`,
    teaches: [`Gara pubblica`, `Par condicio`, `Partner e conflitti`, `Offerta tecnica vs prezzo`, `Condotta corretta`],
    list: 750, cost: 3, window: [3, 10], stars: 4, lep: 20, slip: 0.4, dqRefund: 1,
    crm: { cat: `Best Case`, prob: 50 },
    cast: {
      bellandi: { name: `Laura Bellandi`, role: `RUP · ASL Valle Serena`, hue: 20 },
      moro: { name: `Stefano Moro`, role: `AD di Sinergia IT · partner`, hue: 105 },
      davide: { name: `Davide Ferri`, role: `Tuo Solution Engineer`, hue: 175 },
      fenu: { name: `Marco Fenu`, role: `Direttore Sistemi Informativi ASL`, hue: 215 },
    },
    start: { t: 42, v: 40, u: 48, c: 26, r: 46, have: ['I'] },
    caps: [
      { id: 'lobby', max: 0.12, if: (d) => d.flags.lobbied, why: `Hai avuto un contatto riservato col RUP a bando pubblicato. Il ricorso di Vertex può escluderti dalla gara.` },
      { id: 'tailored', max: 0.35, if: (d) => d.flags.tailored, why: `Il tuo contributo “su misura” in consultazione è agli atti: il capitolato è facilmente impugnabile.` },
      { id: 'clarif', max: 0.45, if: (d) => !d.flags.clarified, why: `Il requisito che favorisce Vertex è rimasto. Senza un chiarimento formale, parti già escluso.` },
      { id: 'tech', max: 0.60, if: (d) => !d.flags.techStrong, why: `Hai un’offerta tecnica debole: nel criterio 70/30, la gara si vince sul punteggio tecnico.` },
    ],
    nodes: {
      n1: {
        where: `Avviso di consultazione preliminare di mercato`,
        scene: [
          { n: `L’ASL ha pubblicato un avviso di consultazione preliminare di mercato. È l’unico momento legittimo per influenzare i requisiti della gara.` },
          { w: 'bellandi', a: `formale`, t: `Il dialogo con il mercato serve a scrivere un capitolato che permetta la più ampia partecipazione. Ogni operatore avrà lo stesso tempo e le stesse informazioni.` },
        ],
        prompt: `Come usi la consultazione?`,
        hint: `È l’unica finestra in cui puoi legittimamente incidere. Ma c’è una linea che non si attraversa.`,
        tip: `Nella consultazione si portano contributi neutrali (esiti misurabili, standard aperti, KPI, suddivisione in lotti), non requisiti cuciti sul proprio prodotto. Un capitolato “su misura” è il modo più rapido per vedere la gara impugnata (par condicio).`,
        choices: [
          ch('a', 0, `Propongo requisiti tecnici che solo il nostro prodotto soddisfa, ben argomentati, così la gara si indirizza.`,
            `Bellandi ringrazia con cortesia. Ma il verbale della consultazione è pubblico: i concorrenti leggeranno il tuo contributo, e un requisito troppo specifico è il primo motivo di ricorso. Hai messo una mina nel tuo stesso terreno.`,
            { t: -6, c: -2, r: 16 }, { integ: -10, set: { tailored: true }, next: 'n2' }),
          ch('b', 3, `Porto un contributo neutrale: obiettivi di servizio misurabili (scorte, rotture, tempi di consegna), standard aperti per l’interoperabilità, suddivisione in lotti per favorire la concorrenza, tempi realistici di implementazione.`,
            `Bellandi prende nota: “Contributo molto utile”. Alcuni dei tuoi KPI finiscono nel capitolato. Hai plasmato la gara senza forzarla e ti sei fatto riconoscere come interlocutore serio.`,
            { t: 10, v: 8, u: 4, c: 10, r: -6 }, { mp: ['Dc', 'Dp'], next: 'n2' }),
          ch('c', 3, `Porto Davide: un’architettura di riferimento aperta e una demo con dati sintetici, a disposizione di tutti i partecipanti alla consultazione.`,
            `La sessione tecnica, aperta a tutti gli operatori, mostra che la tua architettura è matura e interoperabile. Davide viene citato nel verbale come interlocutore tecnico di riferimento.`,
            { t: 8, v: 10, c: 8, r: -8 }, { jolly: 'se', mp: ['Dc', 'Dp'], next: 'n2' }),
          ch('d', 1, `Non partecipo: la gara è pubblica, parteciperò al bando quando uscirà.`,
            `Il bando esce senza i tuoi contributi. Il capitolato contiene tre requisiti poco adatti alla tua soluzione, e non hai potuto spiegare perché. Hai rinunciato all’unica leva legittima.`,
            { v: -4, c: -6, r: 8 }, { next: 'n2' }),
        ],
      },

      n2: {
        where: `Incontro · sede Sinergia IT`,
        scene: [
          { n: `Per una gara di questa dimensione serve un partner locale per installazione e assistenza. Sinergia IT ha vinto tre forniture in ASL vicine.` },
          { w: 'moro', a: `sicuro di sé`, t: `Con noi avete il territorio. Chiediamo l’esclusiva di zona e il diciotto per cento di margine sul servizio.` },
          { w: 'davide', a: `ti prende da parte`, t: `Ho visto la loro pagina partner: sono anche certificati Vertex.` },
        ],
        prompt: `Come imposti il teaming?`,
        hint: `Un partner con due cappelli è un rischio di riservatezza e di lealtà.`,
        tip: `Il partner locale è decisivo per il punteggio tecnico (presenza sul territorio, referenze). Ma uno con legami col concorrente è un rischio: tutelati con esclusiva di partecipazione, riservatezza scritta e obiettivi condivisi.`,
        choices: [
          ch('a', 0, `Firmo subito: Sinergia è il partner giusto, il resto lo vediamo dopo.`,
            `Una settimana dopo, Vertex presenta un’impostazione con molte somiglianze con la tua. Hai condiviso la tua strategia con chi ha un piede nell’altra squadra.`,
            { v: -2, c: -4, r: 14 }, { next: 'n3' }),
          ch('b', 3, `Firmo con Sinergia solo con patto di esclusiva per questa gara, clausole di riservatezza e divieto di partecipare in raggruppamento col concorrente. In cambio: margine del 15% sul servizio e co-marketing sul territorio.`,
            `Moro accetta, un po’ a malincuore: l’esclusiva gli costa l’opzione Vertex, ma la gara è un buon affare. Hai protetto il vantaggio e conservato l’accesso al territorio.`,
            { t: 4, v: 4, c: 10, r: -8 }, { mp: ['Co'], next: 'n3' }),
          ch('c', 1, `Cerco un altro partner, magari globale: meno rapporti locali, meno rischio.`,
            `Il partner globale ha ottima qualità ma nessuna presenza sul territorio né referenze presso l’ASL: il punteggio tecnico ne risente, e il prezzo lievita.`,
            { v: -2, c: 2, r: -2 }, { next: 'n3' }),
          ch('d', 1, `Vado da solo con un servizio diretto: nessun terzo, nessun problema di fedeltà.`,
            `Costruire una presenza locale in tre mesi costa tempo e personale. Il punteggio sulla presenza sul territorio ne soffre, ma sei libero e riservato.`,
            { v: -4, c: 4, r: 4 }, { next: 'n3' }),
        ],
      },

      n3: {
        where: `Bando pubblicato · giorno 4 di 13 per i chiarimenti`,
        scene: [
          { n: `Il bando è online. Tra i requisiti obbligatori c’è un modulo certificato che oggi solo Vertex Systems possiede. Hai tredici giorni per i chiarimenti, trenta per presentare l’offerta.` },
          { w: 'davide', a: `concentrato`, t: `Questo requisito non è funzionalmente necessario: lo stesso risultato si ottiene con standard aperti. Ma così com’è scritto, ci esclude.` },
        ],
        prompt: `Come reagisci al requisito che ti esclude?`,
        hint: `Dopo la pubblicazione il canale è uno solo: le richieste di chiarimento formali e pubbliche. Ogni altra strada è un rischio.`,
        tip: `A bando pubblicato non si parla in privato col RUP: si usano i chiarimenti, pubblici e uguali per tutti, motivati su equivalenza funzionale e concorrenza. Un contatto riservato espone il tuo nome (e la gara) a contestazioni.`,
        choices: [
          ch('a', 0, `Chiamo la dottoressa Bellandi in privato: le spiego che il requisito è sbagliato e che la gara rischia di essere annullata.`,
            `Bellandi, gelida: “Dopo la pubblicazione non posso avere interlocuzioni riservate. La invito a usare il canale dei chiarimenti”. Il contatto è annotato e ti espone a una futura accusa di tentata influenza.`,
            { t: -8, c: -6, r: 16 }, { integ: -12, set: { lobbied: true }, next: 'n4' }),
          ch('b', 3, `Presento una richiesta di chiarimento formale: chiedo di ammettere soluzioni funzionalmente equivalenti basate su standard aperti, motivando con i principi di concorrenza e proporzionalità.`,
            `La risposta è pubblicata per tutti: l’ASL chiarisce che sono ammesse soluzioni equivalenti, purché dimostrino i risultati. Il chiarimento aiuta tutti ma ti ha reso un giocatore corretto, e ti ha aperto la porta.`,
            { t: 6, v: 4, c: 10, r: -12 }, { mp: ['Dc'], set: { clarified: true }, next: 'n4' }),
          ch('c', 3, `Faccio redigere dal legale una richiesta di chiarimento puntuale, con riferimenti normativi e giurisprudenza, valutando con lui anche un’eventuale diffida a tutela.`,
            `Il legale prepara un testo inattaccabile. L’ASL risponde pubblicando un chiarimento che ammette l’equivalenza. Un po’ più forte, ma costoso: poteva bastare un chiarimento ben scritto.`,
            { t: 4, v: 4, c: 10, r: -14 }, { jolly: 'legal', mp: ['Dc'], set: { clarified: true }, next: 'n4' }),
          ch('d', 1, `Impugno subito il bando davanti al TAR: il requisito è illegittimo.`,
            `Il ricorso è un’arma nucleare. Il giudice non sospende, il rapporto con l’ASL si guasta e Vertex capisce che sei disperato. Il ricorso si tiene per quando i chiarimenti non bastano.`,
            { t: -6, u: -6, c: -6, r: 8 }, { next: 'n4' }),
        ],
      },

      n4: {
        where: `Sala gara · Nexora`,
        scene: [
          { n: `Criterio: offerta economicamente più vantaggiosa. 70 punti all’offerta tecnica, 30 al prezzo. Il tecnico premia le migliorie misurabili: formazione, presenza sul territorio, tempi di attivazione, referenze.` },
          { w: 'davide', a: `davanti alla lavagna`, t: `Possiamo investire su quattro elementi migliorativi. Non tutti possono entrare: dobbiamo scegliere dove farci notare.` },
        ],
        prompt: `Dove concentri l’offerta tecnica?`,
        hint: `Il 70% dei punti non si vince con il prezzo.`,
        tip: `Nel criterio dell’offerta economicamente più vantaggiosa ciò che distingue è la qualità dell’offerta tecnica: migliorie misurabili, referenze verificabili, un piano di attivazione credibile. Il prezzo pesa meno di quanto ti viene istintivo pensare.`,
        choices: [
          ch('a', 0, `Tecnico minimo e battaglia sul prezzo: più basso di tutti, così i 30 punti economici sono nostri.`,
            `Il punteggio tecnico è mediocre. Peggio, un prezzo troppo basso ti espone al sospetto di offerta anomala e ti toglie ogni margine.`,
            { v: -6, c: -2, r: 10 }, { next: 'n5' }),
          ch('b', 3, `Concentro l’offerta sulle migliorie che pesano: piano di attivazione in 90 giorni su due presidi pilota, formazione certificata del personale, presenza locale h24 garantita da Sinergia, tre referenze sanitarie verificabili.`,
            `Davide e Moro lavorano per due settimane. Il documento tecnico è denso, verificabile, senza promesse vaghe: sai che prenderai punteggio pieno su almeno tre criteri.`,
            { t: 6, v: 14, u: 4, c: 8, r: -6 }, { mp: ['M'], set: { techStrong: true }, next: 'n5' }),
          ch('c', 2, `Metto tutto: ogni miglioria possibile, anche quelle costose.`,
            `L’offerta è vasta ma dispersiva: la commissione non premia ciò che non sa misurare. Spendi troppo per punti marginali.`,
            { v: 4, c: 2, r: 2 }, { set: { techStrong: true }, next: 'n5' }),
          ch('d', 3, `Faccio verificare dalla stessa ASL tre nostre referenze con visite ai presidi, così la commissione potrà riscontrare direttamente i risultati.`,
            `Le referenze verificate pesano nel punteggio e rafforzano la credibilità. Una mossa solida e istituzionale.`,
            { t: 8, v: 10, c: 4, r: -6 }, { jolly: 'ref', mp: ['M'], set: { techStrong: true }, next: 'n5' }),
        ],
      },

      n5: {
        where: `Offerta economica · scadenza fra 48 ore`,
        scene: [
          { n: `L’offerta economica si presenta una volta sola: in gara non c’è un secondo round. Il punteggio premia i ribassi, ma oltre una certa soglia scatta la verifica dell’anomalia.` },
          { w: 'davide', a: `con il foglio di calcolo`, t: `Con questo perimetro il margine regge fino a circa il 20% sul listino. Oltre, ogni imprevisto in attivazione diventa una perdita.` },
        ],
        prompt: `Quale ribasso offri?`,
        hint: `Il 30% di punteggio economico non vale un margine azzerato. Ma un ribasso timido regala punti.`,
        tip: `In gara il prezzo si congela alla consegna. Scegli il ribasso che dà un punteggio competitivo senza avvicinarti alla soglia di anomalia né al limite del tuo margine.`,
        choices: [
          ch('a', 1, `Ribasso del 5%: prudente e redditizio.`,
            `Prudente e redditizio, ma il punteggio economico è basso. Se Vertex scende di dieci punti ti ritrovi dietro.`,
            { c: -2 }, { next: 'n6' }),
          ch('b', 3, `Ribasso del 12%: competitivo e sostenibile.`,
            `Competitivo e sostenibile. Hai tenuto una riserva di margine e ottenuto un buon punteggio economico.`,
            { c: 4, r: -2, d: 12 }, { next: 'n6' }),
          ch('c', 2, `Ribasso del 20%: massimizzo il punteggio economico.`,
            `Punteggio economico quasi massimo, ma sei al limite del margine: ogni imprevisto in attivazione si trasforma in perdita.`,
            { r: 4, d: 20 }, { next: 'n6' }),
          ch('d', 0, `Ribasso del 32%: vinco sul prezzo, il resto lo gestiamo.`,
            `La commissione apre la verifica di anomalia: dovrai giustificare costi e margini. Anche se vinci, il progetto parte in perdita.`,
            { v: -6, c: -4, r: 14, d: 32 }, { next: 'n6' }),
        ],
      },

      n6: {
        where: `Comunicazione di aggiudicazione · periodo di stand-still`,
        scene: [
          { n: `La commissione ha concluso. Il tuo punteggio complessivo è fra i primi due.` },
          { if: (d) => d.flags.lobbied, n: `Il concorrente presenta ricorso e allega la traccia del tuo contatto riservato con il RUP.` },
          { if: (d) => d.flags.tailored, n: `Il concorrente cita il tuo contributo in consultazione come prova di un requisito “tagliato su misura”.` },
          { if: (d) => !d.flags.lobbied && !d.flags.tailored, n: `Vertex annuncia un ricorso generico, in attesa di leggere gli atti.` },
        ],
        prompt: `Nel periodo di stand-still, cosa fai?`,
        hint: `Dopo l’aggiudicazione c’è un periodo in cui si può ancora impugnare: tieni la condotta pulita.`,
        tip: `Nel periodo sensibile contano la trasparenza e la documentazione. Un dossier di conformità, ordinato e completo, è la tua migliore difesa; una telefonata “per sapere come va” può diventare un problema.`,
        choices: [
          ch('a', 3, `Preparo il dossier di conformità: verbale dei miei contributi, chiarimenti, comunicazioni ufficiali. E preparo la fase di avvio con l’ASL, senza mai toccare la valutazione.`,
            `Quando Vertex deposita il ricorso, il tuo dossier mostra una condotta trasparente dall’inizio alla fine. L’aggiudicazione regge e l’avvio può partire.`,
            { c: 8, u: 4, r: -12 }, { mp: ['P'], next: 'END' }),
          ch('b', 1, `Chiamo l’ASL per verificare “come stanno andando le cose”.`,
            `Bellandi ti ricorda con cortesia che durante il periodo non può dare informazioni oltre quelle pubbliche. Hai fatto una telefonata inutile.`,
            { t: -2, r: 4 }, { next: 'END' }),
          ch('c', 0, `Faccio pressione su Moro per portare l’ASL a un incontro informale prima dell’avvio.`,
            `L’incontro, in un periodo sensibile, diventa agli atti. Un ricorso lo userà come prova di ingerenza.`,
            { t: -4, r: 14 }, { integ: -6, set: { lobbied: true }, next: 'END' }),
          ch('d', 2, `Aspetto in silenzio e mi limito a controllare le comunicazioni ufficiali.`,
            `Corretto, ma passivo: se il ricorso arriva, il dossier non è ancora pronto.`,
            { c: 0 }, { mp: ['P'], next: 'END' }),
        ],
      },
    },
    endings: {
      won: `L’aggiudicazione è definitiva. Il primo presidio pilota parte a gennaio. Bellandi ti scrive solo: “Grazie per la correttezza”. In una gara pubblica è l’unico complimento che conta.`,
      lost: `La commissione assegna la gara a Vertex per quattro punti. Nel verbale, la tua offerta tecnica è citata come “completa ma meno circostanziata”. Lo leggerai due volte.`,
      slip: `La gara viene sospesa per un ricorso. Se ne riparla fra sei mesi, con le stesse regole e tutta la pazienza che serve.`,
    },
    lessons: [
      { if: (d) => d.flags.clarified && !d.flags.lobbied, good: true, t: `Hai usato il canale giusto: un chiarimento formale ha aiutato te e ha dimostrato correttezza.` },
      { if: (d) => d.flags.lobbied, good: false, t: `Un contatto riservato a bando aperto ti ha esposto al rischio di esclusione. In gara pubblica la correttezza non è un valore: è una condizione di accesso.` },
      { if: (d) => d.flags.tailored, good: false, t: `Il requisito “su misura” è finito agli atti e ha reso il capitolato attaccabile. Si influenza una gara con contributi neutrali, non con vantaggi mascherati.` },
      { if: (d) => d.flags.techStrong, good: true, t: `Hai investito nel 70% dei punti che contano davvero: l’offerta tecnica. Il prezzo ha fatto il resto.` },
      { if: (d) => d.disc >= 25, good: false, t: `Un ribasso così aggressivo espone a verifica di anomalia e annulla il margine. Vincere in perdita non è vincere.` },
    ],
  });
})(typeof window !== 'undefined' ? window : globalThis);
