/* CLOSER · shock generici del giorno di chiusura (valgono per tutti gli scenari).
   hit(d) = true: la trattativa è vulnerabile (negativi) oppure beneficia della fortuna (positivi).
   d è lo stato "ricostruito" al momento della firma: d.mp (Set), d.m, d.disc, d.flags. */
(function (g) {
  'use strict';
  const CL = g.CL;

  CL.shocksGeneric = [
    /* ───────────── NEGATIVI ───────────── */
    {
      id: 'g_freeze',
      title: `Congelamento degli acquisti`,
      kind: 'neg',
      w: 1,
      hit: (d) => !d.mp.has('P') || d.m.urgency < 50 || d.m.value < 50,
      dp: -0.30,
      dpProt: -0.04,
      hitText: `Alle 9:05 una circolare della Direzione Finanza di {client} blocca ogni ordine non ancora emesso fino alla conferma dei budget. La tua pratica è in cima alla pila, ma nessuno ha una ragione abbastanza forte da chiedere un’eccezione: il costo di aspettare non è scritto da nessuna parte. “Ne riparliamo a gennaio”, ti risponde una voce cortese.`,
      protText: `Alle 9:05 una circolare della Direzione Finanza di {client} blocca ogni ordine non ancora emesso. Ma il tuo contratto è già nel circuito di firma, e nel business case il costo di un rinvio ha una cifra precisa e una data. Basta una mail con quel numero per ottenere l’eccezione: sapevi che prima o poi sarebbe successo.`,
    },
    {
      id: 'g_buyer_change',
      title: `Cambia chi firma`,
      kind: 'neg',
      w: 1,
      hit: (d) => !(d.mp.has('E') && d.mp.has('C')),
      dp: -0.32,
      dpProt: -0.03,
      hitText: `Un comunicato interno annuncia che il direttore finanziario di {client} lascia l’incarico a fine mese. Il successore arriva lunedì con una priorità dichiarata: rivedere ogni impegno pluriennale. Non hai mai incontrato chi arriva, e nessuno ha motivo di difendere il tuo progetto davanti a un volto nuovo.`,
      protText: `Un comunicato interno annuncia che il direttore finanziario di {client} lascia l’incarico. Ti chiama {contact} prima ancora che tu lo legga: lo scenario lo avevate già immaginato insieme. In due giorni chi arriva ha il business case sul tavolo, e a presentarlo c’è chi lo conosce meglio di chiunque.`,
    },
    {
      id: 'g_champion_moves',
      title: `Il tuo contatto cambia incarico`,
      kind: 'neg',
      w: 1,
      hit: (d) => !d.mp.has('E'),
      dp: -0.27,
      dpProt: -0.02,
      hitText: `Una mail interna annuncia che {contact} passa a un’altra divisione dal primo del mese. Nessun altro in azienda conosceva la storia del progetto, né sapeva con chi parlarne: chi subentra non ha mai sentito il tuo nome e chiede di ripartire dai requisiti.`,
      protText: `Una mail interna annuncia la promozione di {contact}, che lascia il progetto per un nuovo incarico. Ti chiama in persona: sapeva di dover passare la mano, e il progetto lo conosce anche {buyer}, che ti ha già visto più volte. Perdi un alleato, non l’accesso a chi decide.`,
    },
    {
      id: 'g_price_cut',
      title: `Vertex taglia il prezzo del 35%`,
      kind: 'neg',
      w: 1,
      hit: (d) => !(d.mp.has('Co') && d.mp.has('M')),
      dp: -0.28,
      dpProt: -0.04,
      hitText: `Alle 17:40 ti arriva inoltrata, senza commento, un’offerta di Vertex Systems: stesso perimetro, prezzo ridotto del 35%, validità fino a sera. Non hai un confronto pronto, né numeri che mostrino perché la differenza di prezzo non è la differenza di costo. Ti ritrovi a rispondere con le parole contro una cifra.`,
      protText: `Alle 17:40 ti arriva inoltrata un’offerta di Vertex Systems: stesso perimetro, prezzo ridotto del 35%, validità fino a sera. Non è una sorpresa: sapevi che sarebbero scesi, e hai già in cartella il confronto sul costo totale, costruito sui numeri del cliente. Basta mezz’ora per mostrare che la differenza è nel perimetro, non nel valore.`,
    },
    {
      id: 'g_board_postpones',
      title: `Il board rinvia`,
      kind: 'neg',
      w: 1,
      hit: (d) => !(d.mp.has('Dp') && d.mp.has('P')),
      dp: -0.30,
      dpProt: -0.03,
      hitText: `Il consiglio di {client} sposta la seduta di tre settimane per un’urgenza di bilancio. Avevi una data in testa, non un calendario: scopri adesso che senza quel voto il contratto non può nemmeno essere aperto. Il trimestre chiude e la pratica resta in un cassetto.`,
      protText: `Il consiglio di {client} sposta la seduta di tre settimane per un’urgenza di bilancio. Conoscevi il percorso passo per passo e il contratto è già negoziato in ogni clausola: ti basta chiedere che il punto sia trattato in via d’urgenza, con la firma subordinata al solo voto. Una telefonata e una serata un po’ lunga, niente di più.`,
    },
    {
      id: 'g_signer_away',
      title: `Il firmatario è irraggiungibile`,
      kind: 'neg',
      w: 1,
      hit: (d) => !d.mp.has('P'),
      dp: -0.24,
      dpProt: -0.02,
      hitText: `L’ultimo giorno utile scopri che chi ha la firma è in ferie fino a lunedì, in un posto senza copertura. Nessuno ha mai chiesto chi potesse firmare al suo posto, e il portale di firma digitale richiede il suo certificato personale. Il telefono squilla a vuoto, la scadenza no.`,
      protText: `L’ultimo giorno utile chi ha la firma è in trasferta e non rientra prima di lunedì. Lo avevi messo in conto: nel piano di firma c’è un procuratore con delega scritta, e il documento è già sulla piattaforma. Il passaggio slitta di un’ora, non di una settimana.`,
    },
    {
      id: 'g_last_haggle',
      title: `Rinegoziazione all’ultima ora`,
      kind: 'neg',
      w: 1,
      hit: (d) => (d.disc >= 12 && !d.flags.giveGet) || d.m.control < 50,
      dp: -0.25,
      dpProt: -0.03,
      hitText: `Il giorno della firma Acquisti di {client} ti chiama con un tono cordiale e una richiesta fredda: “Ancora un piccolo gesto sul prezzo, il 5%, e chiudiamo oggi”. Il tavolo non è più tuo, e qualunque cosa risponderai diventerà la base della richiesta successiva. Prendi tempo, ma l’orologio non gioca dalla tua parte.`,
      protText: `Il giorno della firma Acquisti di {client} ti chiama con un tono cordiale: “Ancora il 5%, e chiudiamo oggi”. Era nel copione, e hai già la risposta: ti muovi solo se si muove anche la durata. Dall’altra parte una pausa, poi una risata: ci provano sempre.`,
    },
    {
      id: 'g_compliance_audit',
      title: `Audit di compliance sul fornitore`,
      kind: 'neg',
      w: 1,
      hit: (d) => !d.mp.has('Dc'),
      dp: -0.26,
      dpProt: -0.03,
      hitText: `Il giorno prima della firma l’ufficio compliance di {client} apre una verifica sui nuovi fornitori: questionario di sicurezza, certificazioni e coperture assicurative da consegnare in cinque giorni lavorativi. Nessuno ti aveva parlato di questo passaggio, e non c’è modo di saltarlo. Il contratto resta fermo, in attesa di un timbro che non sapevi di dover chiedere.`,
      protText: `L’ufficio compliance di {client} apre una verifica sui nuovi fornitori proprio alla vigilia della firma. Conoscevi i criteri di ammissione perché li avevi chiesti da tempo, e il fascicolo con certificazioni e polizze è già pronto. Due ore dopo la pratica torna in firma; al telefono qualcuno aggiunge: “Siete i primi che rispondono senza chiederci una proroga”.`,
    },

    /* ───────────── POSITIVI (hit = ne approfitti; altrimenti l’occasione passa) ───────────── */
    {
      id: 'g_board_accelerates',
      title: `Il board accelera il budget`,
      kind: 'pos',
      w: 1,
      hit: (d) => d.mp.has('E') && d.m.urgency >= 50,
      dp: 0.12,
      dpProt: 0,
      hitText: `Alle 8:30 ti arriva un messaggio di tre righe da parte di {buyer}: il board ha anticipato la delibera sul budget e vuole chiudere con i fornitori entro la settimana. Hai l’accesso diretto a chi decide, un motivo per cui il progetto non può aspettare e un contratto che si legge in una sera. Per una volta, la corsa è dalla tua parte.`,
      protText: `Il board di {client} anticipa la delibera sul budget e chiede ai fornitori di stringere i tempi. Ma tu non hai una strada diretta verso chi decide, né un motivo abbastanza forte per correre: la finestra si apre e la vedi passare. L’accelerazione va a chi è già pronto a firmare.`,
    },
    {
      id: 'g_second_department',
      title: `Un secondo reparto si accoda`,
      kind: 'pos',
      w: 1,
      hit: (d) => d.mp.has('C') && d.m.trust >= 50,
      dp: 0.10,
      dpProt: 0,
      hitText: `In una riunione interna {contact} parla del progetto con tale convinzione che un altro responsabile chiede di aggiungere il proprio reparto: stesso contratto, un secondo budget. Non è merito di una mossa dell’ultima ora, ma di quello che succede quando qualcuno vende per te anche quando non ci sei.`,
      protText: `Un altro reparto di {client} sente parlare del progetto e chiede informazioni. Ma nessuno, all’interno, sa spiegare con precisione cosa fate e perché: i messaggi si perdono in due scambi di mail e la curiosità si spegne da sola. Una porta si è aperta, e nessuno l’ha tenuta ferma per te.`,
    },
    {
      id: 'g_rival_withdraws',
      title: `Il concorrente si ritira`,
      kind: 'pos',
      w: 1,
      hit: (d) => d.mp.has('Co'),
      dp: 0.10,
      dpProt: 0,
      hitText: `Vertex Systems comunica a {client} che non parteciperà alla fase finale: un riassetto interno ha bloccato l’offerta. Conoscevi i loro punti deboli e quella partita l’avevi già preparata, così la notizia ti trova con la proposta pronta a riempire il vuoto. Il cliente ha un confronto in meno da giustificare, e tu uno spazio in più.`,
      protText: `Vertex Systems si ritira dalla fase finale, ma la notizia ti arriva da terzi, due giorni dopo. Non avevi mai mappato chi altro sedesse al tavolo, e il vantaggio non lo hai potuto usare quando contava. Quando provi a farlo, il cliente è già andato avanti.`,
    },
  ];
})(typeof window !== 'undefined' ? window : globalThis);
